### ISSUE TITLE
ERROR: cuMemsetD8() 1

### ISSUE THREAD

**Issue by Xanadrel** [hashcat/hashcat#1]
Multiple users reported getting this error (both on windows/linux), with driver versions higher than the required one.

OS: Windows 7 64b
GPU : GTX Titan X
CPU : i5 2500k
Driver : 353.62
oclHashcat : 2.00

Command :
`./cudaHashcat64.exe -m 100 ../hashcat-0.50/examples/A0.M100.hash example.dict`

Output :

```
cudaHashcat v2.00 starting...

Device #1: GeForce GTX TITAN X, 12288MB, 1076Mhz, 24MCU

Hashes: 100 hashes; 100 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Scalar-Mode
* Raw-Hash
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 80c
Device #1: Kernel z:\Hashcat\cudaHashcat-2.00/kernels/4318/m00100_a0.sm_52.64.cubin

Generated dictionary stats for example.dict: 1210228 bytes, 129988 words, 129988 keyspace
[...]
[s]tatus [p]ause [r]esume [b]ypass [q]uit =>

ERROR: cuMemsetD8() 1
```

**Comment by Xanadrel** [comment]
The error seems to happen only with wordlist based attacks, so all but -a 3.

**Comment by Wohn** [comment]
I got the same error :(

**Comment by philsmd** [comment]
The pull request above fixes the problem.
The problem doesn't seem to be specific to any particular nvidia driver. However, it seems to be a very recently introduced code and this problem somehow did remain undetected.

**Comment by Wohn** [comment]
ok, with -a 3 i got GPU speed 0 H/s but its running 10 digits

**Comment by Xanadrel** [comment]
Ok for merging.

**Comment by epixoip** [comment]
This has my signoff as well. @jsteube, please merge to master if you approve.

**Comment by jsteube** [comment]
Problem solved with PR https://github.com/hashcat/oclHashcat/pull/2

**Comment by Wohn** [comment]
oclhashcat 2.0.1 released!!! :)
