### ISSUE TITLE
RAR 3 unencrypted filenames

### ISSUE THREAD

**Issue by quaesit** [hashcat/hashcat#1001]
Aka 99% of the archives out there. Please consider adding mode/kernel if possible. Thank you for sharing your work for free.

**Comment by philsmd** [comment]
This is a duplicate of https://github.com/hashcat/hashcat/issues/68 . We should consider closing this issue as duplicate and keep #68 open, do you agree?

**Comment by corporateshark** [comment]
#68 was closed. Please, reopen this one.
