### ISSUE TITLE
Reuse PBKDF2 intermediate keys if duplicate essid is detected not working on hybrid attack

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1002]
hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list test.hccap -a 6 wordlist ?d?d?d

Session..........: hashcat
Status...........: Running
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccap
Time.Started.....: Sun Jan 29 18:06:57 2017 (1 min, 14 secs)
Time.Estimated...: Mon Nov 27 21:51:28 2017 (302 days, 3 hours)
Input.Base.......: File (test.dict), Left Side
Input.Mod........: Mask (?d?d?d) [3], Right Side
Input.Queue.Base.: 1/1 (100.00%)
Input.Queue.Mod..: 1/1 (100.00%)
Speed.Dev.#1.....:   165.7 kH/s (79.36ms)
Recovered........: 0/418 (0.00%) Digests, 0/396 (0.00%) Salts
Progress.........: 11927552/43270828920 (0.00%)
Rejected.........: 0/11927552 (0.00%)
Restore.Point....: 0/10926977 (0.00%)
Candidates.#1....: abaftaa510 -> agreeablecotton510
HWMon.Dev.#1.....: Temp: 74c Fan: 54% Util:100% Core:1265Mhz Mem:3004Mhz Lanes:16

(302 days, 3 hours) !!

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list test.hccap -a 3 ?d?d?d?d?d?d?d?d

Session..........: hashcat                                
Status...........: Running
Hash.Type........: WPA/WPA2
Hash.Target......: /test.hccap
Time.Started.....: Sun Jan 29 18:09:49 2017 (31 secs)
Time.Estimated...: Sun Jan 29 18:14:11 2017 (3 mins, 51 secs)
Input.Mask.......: ?d?d?d?d?d?d?d?d [8]
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   167.3 MH/s (78.99ms)
Recovered........: 0/418 (0.00%) Digests, 0/396 (0.00%) Salts
Progress.........: 941850624/39600000000 (2.38%)
Rejected.........: 0/941850624 (0.00%)
Restore.Point....: 0/10000000 (0.00%)
Candidates.#1....: 12345678 -> 19496099
HWMon.Dev.#1.....: Temp: 75c Fan: 42% Util: 95% Core:1277Mhz Mem:3004Mhz Lanes:16

(3 mins, 51 secs) !!

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list test.hccap wordlist

Session..........: hashcat
Status...........: Running
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccap
Time.Started.....: Sun Jan 29 19:15:21 2017 (1 min, 49 secs)
Time.Estimated...: Sun Jan 29 19:19:58 2017 (2 mins, 48 secs)
Input.Base.......: File (wordlist)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   171.9 MH/s (79.19ms)
Recovered........: 0/418 (0.00%) Digests, 0/396 (0.00%) Salts
Progress.........: 5213618176/34146740232 (15.27%)
Rejected.........: 0/5213618176 (0.00%)
Restore.Point....: 12779520/86229142 (14.82%)
Candidates.#1....: 5300503mdrz -> 555662867639641
HWMon.Dev.#1.....: Temp: 76c Fan: 56% Util: 98% Core:1265Mhz Mem:3004Mhz Lanes:16

(2 mins, 48 secs) !!

Best regards
ZerBea

**Comment by jsteube** [comment]
Not a bug this time. It's important to feed hashcat with enough words in the wordlist. In your case it's only ~100k words -> 43270828920  / (1000 * 418 ) = 103518

If your intention was to get enough traction by using -a 6 that's possible, but you need to do it differently.

So, instead of:

```
hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list test.hccap -a 6 wordlist ?d?d?d
```

Do this:

```
hashcat --stdout -a 6 wordlist ?d?d?d | hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list test.hccap
```

This should give you full speed.

**Comment by ZerBea** [comment]
Thank you for this information.
Indeed I was very surprised, because if I use a very, vey small wordlist (only wordlistattack with tis testfile), speed is everytime obove 160 MH/s.
Now I understand......
Best Regards
