### ISSUE TITLE
support for substr(sha1($pass),0,32)

### ISSUE THREAD

**Issue by d2-d2** [hashcat/hashcat#1012]
Hey guys, amazing work on new algos. Do you think you can implement that one too?
```
substr(sha1($pass),0,32)
```

Couple of examples:
```
8954b6f938902227609185b466b15753:zzzzxx12
9eab102e8f9431bb23016851d11e658e:88888
0ddb5877c896f43e8734e10b001e7f1e:8888
eaa67f3a93d0acb08d8a5e8ff9866f51:888
7278934df282ee1027073d9eedbfee47:tttt
99ebdbd711b0e1854a6c2e93f759efc2:ttt
```

**Comment by philsmd** [comment]
Please follow this guide (https://hashcat.net/faq#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this) if you want to request some new algorithm.
Especially the information about where this hash type is used would be very crucial for the devs to decide if this makes sense (for other users too) to add this new algorithm.
Thanks

**Comment by d2-d2** [comment]
Hi philsmd, actually I don't have any names of webapps that are using this scheme. To be honest, there are other variations of substr() function but the one listed here is most commonly used. I base that statement on what I've seen on forums so far (insidepro and hashkiller to say the least) and lists are very large (hundreds thousands of hashes). There is also very well known list of hashes mentioned by KoreLogic (https://www.korelogic.com/InfoSecSouthwest2012_Ripe_Hashes.html). There are many substr() in there too.

**Comment by DoZ10** [comment]
Below is a quick hack showing what mostly needs to be done for a simple substr() operation on sha1. This kind of change may not be trivial for all algorithms and will require a lot of work for compatibility reasons... 

Implementing a more stable, but invasive code would be a lot more work. I am honestly not that much interested in investing the required time into this. Perhaps someone else is looking for a good challenge ? 

```
git clone -b substr https://github.com/DoZ10/hashcat/
```

**Comment by magnumripper** [comment]
@DoZ10 don't you also need to comment out the early rejection of `e`? Eg. line 493 of m00100_a1.cl.

**Comment by DoZ10** [comment]
Yes. My bad I only tested multi-mode with provided examples. 

Just pushed the modification. This is a nice example of all the little details that needs to be addressed only for changing R0 .. R3 values. to fit with substring(... , 0, 32).

**Comment by d2-d2** [comment]
Thanks @DoZ10 it works :-) There are some trailing '0' visible in output but that's fine, I can delete them easily.
```
46aef2f12cde0f185843a837a307669700000000:cvugvuhvbuh
```

**Comment by DoZ10** [comment]
I fixed the output.

I'll leave it as is for now. You probably want to fork it in case I delete it some day.

For the substring() feature itself, still not sure how and why it should be merged to master unless there are some indications of frameworks/applications that are using this.

Cheers,

**Comment by jsteube** [comment]
Closing this issue because there's a solution from @DoZ10 and at the same time there's no known frameworks/application that are using this. Feel free to reopen in case some frameworks/application will pop up.
