### ISSUE TITLE
Check for weak hashes

### ISSUE THREAD

**Issue by firefart** [hashcat/hashcat#1015]
Currently hashcat checks for weak hashes on start but this can be improved. Currently I run JohnTheRipper first because it does a pretty good job on trying weak passes.

Things I would like to see:
-) If the --username parameter is specified, try the username as password
-) If the username is an email like first.last@domain.com try first, last, domain.com and so on as passwords too

Do you think it's possible to implement these checks?

**Comment by jsteube** [comment]
Is that exactly what JtR does? I mean, is that all of it?

**Comment by firefart** [comment]
@jsteube I don't think it's all JtR does, but it is a good start to also check variants of the username if supplied. Other checks could be added in the future if someone analyzes JtR's source code.

**Comment by roycewilliams** [comment]
From http://www.openwall.com/john/doc/MODES.shtml:

> This is the mode you should start cracking with. It will use the login names, "GECOS" / "Full Name" fields, and users' home directory names as candidate passwords, also with a large set of mangling rules applied. Since the information is only used against passwords for the accounts it was taken from (and against password hashes which happened to be assigned the same salt), "single crack" mode is much faster than wordlist mode. This permits for the use of a much larger set of word mangling rules with "single crack", and their use is always enabled with this mode. Successfully guessed passwords are also tried against all loaded password hashes just in case more users have the same password.

**Comment by magnumripper** [comment]
The really cool thing with Solar's single mode, is it will run near single-salt-speed with many salts. That's obviously because it only tries the things described above on the very user that had them (unless there are salt collisions, in which case all other hashes with same salt will be tested too). The bad news is this is all CPU, and would be very tricky to implement on GPU I guess. JtR "can" use single mode with GPU formats, but they perform like shit (if at all).

**Comment by firefart** [comment]
awesome guys thanks for the details. So anyone of the core members think this is possible to implement with the current code structure?

**Comment by matrix** [comment]
Hi @FireFart, personally I think it's more simple do it yourself by specifying the "username" as a single password than rewrite something in C.

**Comment by jsteube** [comment]
I agree with @magnumripper. The single mode, to be efficient, needs a different architecture which is kind of incompatible with devices (such as gpu) that require high parallelization (especially with mixed gpu types). There's a reason why hashcat limits the weak-hash-check (empty password) to a maximum of 100 salts. It would slow down the startup too much, especially with slow algorithms like LUKS or itunes. Adding more password candidates would not make a big difference in startup time for fast hashes, but for slow ones. There's also the problem of how to feed hashcat with a wordlist that is build out of data using --username. Such a logic could be implemented, but that's additional effort. 

Maybe in the future, when hashcat makes another refactorization that enables iterating through salts in the inner loop, this could be a thing to add, but I only see limited potential for this atm...
