### ISSUE TITLE
Android chroot support

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1017]
Is there any possibilities of having hashcat work in a chroot environment, on Qualcomm based Android devices?

I currently haven't been able to get OpenCL working in a chroot but OpenCL is available in Android, according to this utility: https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android&hl=en_GB

My chroot is from kali nethunter (debian-based).

**Comment by jsteube** [comment]
I have no experience with Android development. Maybe someone else can answer the questions

**Comment by DoZ10** [comment]
I **could** look into this, but I mean... why on earth would you want to crack hashes on Android ? Not sure it worths the time investment...

**Comment by jsteube** [comment]
Not a hashcat issue

**Comment by Saikatsaha1996** [comment]
> Not a hashcat issue

I am install successful
Chroot Linux (Linux deploy)
Ubuntu 20.04
Adreno 650 gpu
My Clinfo showing 
OpenCL device type cpu...
Why showing device type cpu?..
In my android device already available OpenCL 2.0
Any solution for this?

**Comment by albaluz35** [comment]
@Saikatsaha1996 have you found a solution? I did the following procedure and the OpenCL Rusticl freedreno inside my nspawn container shows in hashcat the GPU but when I run any cracking or benchmark I get the error XX as stated in these issues:
* https://github.com/hashcat/hashcat/issues/4550  
* https://gitlab.freedesktop.org/mesa/mesa/-/issues?show=eyJpaWQiOiIxNDE0MyIsImZ1bGxfcGF0aCI6Im1lc2EvbWVzYSIsImlkIjoxNDIyMTB9

# PROCEDURE:

sudo apt install -y debootstrap systemd-container
mkdir -p ~/rusticl-opencl-runtime
cd ~/rusticl-opencl-runtime

# choose an output path
ROOTFS=~/rusticl-opencl-runtime/rusticl-rootfs

# create the rootfs (arm64)
sudo debootstrap --arch=arm64 trixie "$ROOTFS" http://deb.debian.org/debian

/////////////////////////////////////////////////////
#  PREPARE RUSTICL (Mesa OpenCL runtime)
/////////////////////////////////////////////////////
# Freedreno uses DRM device nodes under /dev/dri.

cat > ~/rusticl-opencl-runtime/run_rusticl_container.sh <<'EOF'
#!/bin/bash
set -e
ROOTFS="$HOME/rusticl-opencl-runtime/rusticl-rootfs"
# Prefer /dev/dri for Mesa/Freedreno, fallback to /dev/kgsl-3d0 if needed
DEVICE="/dev/dri"
[ -e /dev/kgsl-3d0 ] && DEVICE="/dev/kgsl-3d0"
echo "Starting minimal container with $DEVICE bound..."
sudo systemd-nspawn -D "$ROOTFS" \
  --bind=$DEVICE \
  --private-users=no \
  --bind-ro=/sys/class/drm \
  --bind-ro=/sys/devices \
  --bind-ro=/lib/modules/$(uname -r) \
  --bind-ro=/lib/firmware/qcom \
  --property=DeviceAllow='/dev/dri/renderD128 rwm' \
  --property=DeviceAllow='/dev/dri/card0 rwm' \
  --capability=all \
  /bin/bash --login
EOF
chmod u+x ~/rusticl-opencl-runtime/run_rusticl_container.sh

-----------------------------------------
# Enter the container
# You will be dropped into a root shell inside the debootstrap Debian environment. 
# Everything you do now is isolated (except for the bound device nodes).

~/rusticl-opencl-runtime/run_rusticl_container.sh

root@rusticl-rootfs:/#
ls -l /dev/dri
total 0
drwxr-xr-x  2 root root         80 Oct 16 16:27 by-path
crw-rw----+ 1 root video  226,   0 Oct 16 16:33 card0
crw-rw----+ 1 root render 226, 128 Oct 16 16:33 renderD128
root@rusticl-rootfs:/# getent group render
render:x:992:
ls -l /lib/firmware/qcom/a63*
ls -l /lib/firmware/qcom/sdm845
test -r /dev/dri/renderD128 && echo "Can read renderD128" || echo "Cannot read"
test -w /dev/dri/renderD128 && echo "Can write renderD128" || echo "Cannot write"

apt update
apt install -t trixie-backports \
  hashcat clinfo binutils \
  mesa-libgallium \
  mesa-opencl-icd \
  libgl1-mesa-dri \
  libgbm1 \
  libegl-mesa0 \
  mesa-vulkan-drivers \
  libdrm-common \
  libdrm-freedreno1 \
  libdrm2 \
  mesa-utils

ldconfig
export RUSTICL_ENABLE=freedreno
