### ISSUE TITLE
Hashcat 3.3 - Format 3910

### ISSUE THREAD

**Issue by MarcoPaulo75** [hashcat/hashcat#1018]
Hello everyone.

I am very pleased to be able to use all the power of my machine thanks to the new version of hashcat 3.3, but I'm surprised that the format 3910 "md5(md5 ($p).md5($s))" processing of PHPFOX passwords no longer exists in the software.

Is this an oversight?

Thank you in advance.

**Comment by philsmd** [comment]
This is one of those formats that were only present in hashcat-legacy (CPU version only).
There was never GPU support for -m 3910 = md5 (md5 ($pass) . md5 ($salt))

Some example hash of this algo:
```
250920b3a5e31318806a032a4674df7e:1234:hashcat
462ae870f71e3926c2661f3fb9dee273:200027583:hashcat
```

(note: just to clarify, the output of both inner MD5 () is in - lowercase - hexadecimal, not binary)

**Comment by Chick3nman** [comment]
This would be pretty easy cut/paste addition using hash mode -m 2811 md5(md5($salt).md5(pass)), would it not? Just some swapping around and then adding it to the mode selection.
