### ISSUE TITLE
Add HTTP Digest access authentication algorithm

### ISSUE THREAD

**Issue by olsh** [hashcat/hashcat#1021]
It would be nice to add ability to brute this algorithm.

More information about the algo:
https://en.wikipedia.org/wiki/Digest_access_authentication
https://tools.ietf.org/html/rfc2617#section-3
http://pentestmonkey.net/cheat-sheet/john-the-ripper-hash-formats (look for `hdaa`)
https://github.com/piyushcse29/john-the-ripper/blob/master/doc/HDAA_README

Thanks!

**Comment by philsmd** [comment]
This should be already supported by this hash type:
-m 11400 = SIP digest authentication (MD5) 
Did you test with that hash type?

**Comment by olsh** [comment]
@philsmd 
Thanks for the reply.
Could you please provide a valid pattern? 

https://hashcat.net/wiki/doku.php?id=example_hashes
It seems to me that pattern described here has different parameters.
`$sip$*192.168.100.100*192.168.100.121*username*asterisk*REGISTER*sip*192.168.100.121**2b01df0b****MD5*ad0520061ca07c120d7e8ce696a6df2d`

**Comment by philsmd** [comment]
What do you mean by "different parameters" ? Different from what?
Here is the explanation of the fields:
```
$sip$*[URI_SERVER]*[URI_CLIENT]*[USERNAME]*[REALM]*[METHOD]*[URI_PREFIX]*[URI_RESOURCE]*[URI_SUFFIX]*[NONCE_SERVER]*[NONCE_CLIENT]*[NONCE_COUNT]*[QOP]*[DIRECTIVE]*[MD5]
```

**Comment by olsh** [comment]
Sorry, I meant they are different from what I see in digest parameters and in the john documentation. I was confused by $sip$, URI_SUFFIX, URI_PREFIX etc.

This method works, thank you. 👍
