### ISSUE TITLE
clEnqueueNDRangeKernel(): CL_UNKNOWN_ERROR when use -a 0 -m 2500

### ISSUE THREAD

**Issue by pascalqq** [hashcat/hashcat#1022]
I'm trying to test the compatibility of intel openCL, and i get a intel xeon l5520 with intel opencl runtime 16.1.1. 
**I found that -a 3 can work properly but -a 0 can't.** 
Here is the output:

============================================

C:\Users\Administrator\Desktop\hashcat-3.30>hashcat64.exe -m 2500 **-a 3** -p : -D 1 -d 1 C:\Users\Administrator\Desktop\Test\test.hccap 1988?d?d?d?d
hashcat (v3.30) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Xeon(R) CPU           L5520  @ 2.27GHz, 2047/20469 MB allocatable, 16MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

XXXX:xxx:xxx:1xxxxxxx

Session..........: hashcat
Status...........: Cracked
Hash.Type........: WPA/WPA2
Hash.Target......: XXXX (xxx <-> xxx)
Time.Started.....: Sat Feb 04 20:30:21 2017 (2 secs)
Time.Estimated...: Sat Feb 04 20:30:23 2017 (0 secs)
Input.Mask.......: 1988?d?d?d?d [8]
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:     5546 H/s (11.30ms)
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 8192/10000 (81.92%)
Rejected.........: 0/8192 (0.00%)
Restore.Point....: 6144/10000 (61.44%)
Candidates.#1....: 19887235 -> 19880974
HWMon.Dev.#1.....: N/A

Started: Sat Feb 04 20:30:20 2017
Stopped: Sat Feb 04 20:30:24 2017

============================================

C:\Users\Administrator\Desktop\hashcat-3.30>hashcat64.exe -m 2500 **-a 0** -p : -D 1 -d 1 C:\Users\Administrator\Desktop\Test\test.hccap  C:\Users\Administrator\Desktop\Test\test
hashcat (v3.30) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Xeon(R) CPU           L5520  @ 2.27GHz, 2047/20469 MB allocatable, 16MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

**clEnqueueNDRangeKernel(): CL_UNKNOWN_ERROR**

Started: Sat Feb 04 20:33:37 2017
Stopped: Sat Feb 04 20:33:37 2017

============================================

C:\Users\Administrator\Desktop\hashcat-3.30>hashcat64.exe -I
hashcat (v3.30) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) OpenCL
  Version : OpenCL 1.2

  Device ID #1
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Xeon(R) CPU           L5520  @ 2.27GHz
    Version        : OpenCL 1.2 (Build 25)
    Processor(s)   : 16
    Clock          : 2270
    Memory         : 2047/20469 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 6.4.0.25

**Comment by jsteube** [comment]
Nice, I can reproduce this on my Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, 2047/15999 MB allocatable, 8MCU. The -a 3 works, but the -a 0 fails

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/9005b6662663ebbfab7025d03aa661374d34bf31

If it's not working for you, please reopen the issue. Thanks for reporting!
