### ISSUE TITLE
Hashcat watchdog cannot be activated for Titan X with --gpu-temp-abort=100

### ISSUE THREAD

**Issue by derhornspieler** [hashcat/hashcat#1027]
Using this option from the wiki pages, but I am still seeing Watchdog Temperature abort trigger disabled warnings when starting hashcat.  Am I doing something wrong or need another package installed I am not aware of?  Cheers!

**Comment by jsteube** [comment]
Was the NVML initialization successfull? Does nvidia-smi work?

**Comment by jsteube** [comment]
I've tested with Xanadrel. We had to update to latest driver, but after that the Titan X worked fine.
