### ISSUE TITLE
hashcat (v3.30-103-g65d5921e) -m 2500 --remove destroys hccapx

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1029]
Using the --remove option destrys the hccapx file:
Example:

running hashcat against test.hccapx with the complete wordlist:

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found test.hccapx wordlistpart1and2

Session..........: hashcat
Status...........: Cracked
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccapx
Time.Started.....: Tue Feb  7 15:14:50 2017 (24 secs)
Time.Estimated...: Tue Feb  7 15:15:14 2017 (0 secs)
Input.Base.......: File (wordlistpart1and2)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   339.7 kH/s (4.89ms)
Recovered........: 383/383 (100.00%) Digests, 383/383 (100.00%) Salts
Progress.........: 9949574/9949574 (100.00%)
Rejected.........: 383/9949574 (0.00%)
Restore.Point....: 0/25978 (0.00%)
Candidates.#1....: ~!@#$%^&* -> 7643675634963062
HWMon.Dev.#1.....: Temp: 60c Fan: 33% Util: 99% Core:1290Mhz Mem:3004Mhz Lanes:16
Started: Tue Feb  7 15:14:47 2017
Stopped: Tue Feb  7 15:15:15 2017

all passwords found.

Now I split the wordlist into two parts and do the first run with the first part of the wordlist

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found test.hccapx wordlistpart1

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccapx
Time.Started.....: Tue Feb  7 15:12:13 2017 (17 secs)
Time.Estimated...: Tue Feb  7 15:12:30 2017 (0 secs)
Input.Base.......: File (wordlistpart1)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   261.7 kH/s (3.55ms)
Recovered........: 89/383 (23.24%) Digests, 89/383 (23.24%) Salts
Progress.........: 5628568/5628568 (100.00%)
Rejected.........: 0/5628568 (0.00%)
Restore.Point....: 14696/14696 (100.00%)
Candidates.#1....: 0000000000000000 -> 9999999999999999
HWMon.Dev.#1.....: Temp: 54c Fan: 33% Util: 99% Core:1303Mhz Mem:3004Mhz Lanes:16
Started: Tue Feb  7 15:12:09 2017
Stopped: Tue Feb  7 15:12:31 2017

89 password found
After this I did a run with the second part of the wordlist against the remaining handshakes and expect the ramaining passwords are found.....

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found test.hccapx wordlistpart1

Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccapx
Time.Started.....: Tue Feb  7 15:12:39 2017 (1 sec)
Time.Estimated...: Tue Feb  7 15:12:40 2017 (0 secs)
Input.Base.......: File (wordlistpart2)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....: 87533.4 kH/s (4.80ms)
Recovered........: 0/294 (0.00%) Digests, 0/294 (0.00%) Salts
Progress.........: 7611366/7611366 (100.00%)
Rejected.........: 294/7611366 (0.00%)
Restore.Point....: 25889/25889 (100.00%)
Candidates.#1....: ~!@#$%^&* -> 7643675634963062
HWMon.Dev.#1.....: Temp: 54c Fan: 37% Util: 99% Core:1290Mhz Mem:3004Mhz Lanes:16

No passwords found - test.hccapx is destroyed.....

Best regards
ZerBea

**Comment by jsteube** [comment]
Should be fixed. Please test. If not working, please reopen issue
