### ISSUE TITLE
New rule: replace Nth character

### ISSUE THREAD

**Issue by julioauto** [hashcat/hashcat#1035]
I would like to propose a new feature, which would be this rule to replace the Nth instance of a character with a different character. The classic 's' rule replaces _all_ instances of the given character; this new rule could perhaps be 'S'. The idea is to be able to generate candidates such as 'pa$swords', based solely on premises e.g. that some users like to use leetspeak for the first 'a' in the word but not the rest - or things of that nature.

New rule could be of the form SNXY: replace Nth instance of character X with Y

So, to illustrate:

Rule | Input | Output
--- | --- | ---
ss$ | passwords | pa$$word$
S1s$ | passwords | pa$swords
S2s$ | passwords | pas$words
S1s$S1s$ | passwords | pa$$words

**EDIT:**
After about a month since opening this issue, I just wanted to reiterate how useful I think it will be when it is implemented.

The idea came to me when I couldn't crack the password 'Odes$a77'. I spent some decent time with fairly good hardware, my favorite wordlists and rule files, some good masks and combinations... nothing worked, even though I knew (due to the nature of the challenge) that it had to be a somewhat simple password ('Odessa' is in every wordlist, obviously). Luckily I had the opportunity to ask the challenge owner for the correct answer and that's when I realized that none of the existing rules would have matched it, except maybe some very random rule by chance - delete s @ N then insert $ @ N, etc.

When this gets implemented, a think a new, more selective/fine-grained leetspeak rule file will be due, and I can't wait to see what it will catch when run against large bases :)

**Comment by magnumripper** [comment]
I have wanted something similar. For what it's worth, 'S' is already taken in JtR. Ideally we should find some mnemonic compatible with both HC, JtR and possibly others.

Heads-up @solardiz.

**Comment by jsteube** [comment]
@magnumripper Please do a suggestion on the character to use

**Comment by magnumripper** [comment]
I'll try to create a wiki page listing all free or taken HC and JtR-jumbo mnemonics ASAP. That will come handy in the future too.

**Comment by d2-d2** [comment]
@jsteube 

> Please do a suggestion on the character to use

Since 's' is taken, how about 'a' (for alter)?

**Comment by magnumripper** [comment]
In JtR, 'a' is free but not 'A'.

https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/RULES

I really should create that wiki page.

**Comment by julioauto** [comment]
For what is worth, I just updated my original post with some (motivating?) background.

**Comment by solardiz** [comment]
I think we already have this functionality in JtR, here's an example of it in use:
http://www.openwall.com/lists/john-users/2010/07/31/1

The position code "p" is documented as "position of the character last found with the "/" or "%" commands" in doc/RULES.

**Comment by julioauto** [comment]
You're right, @solardiz. That does seem to do the trick.
I think all of the commands you mentioned are implemented in hashcat, in john-compatible syntax, except for the 'p' position. I haven't tried it, but src/rp_cpu.c:12 tells me it expects a digit for position (conv_ctoi()).

**Comment by jsteube** [comment]
@julioauto While I find your syntax more intuitive I also like the idea of using / and %. We should use the same approach to stay compatible with JtR ruleset.

**Comment by mhasbini** [comment]
@jsteube `p` rule is already taken in hashcat as: pN -> Append duplicated word N times.

**Comment by solardiz** [comment]
> @jsteube `p` rule is already taken in hashcat as: pN -> Append duplicated word N times. 

JtR's `p` discussed here is not a rule command, it is a character position code, so hashcat should have no problem introducing that position code as well.

hashcat's different meaning of the `p` rule command is unfortunate (in JtR the `p` command means "pluralize", and we inherited it from Crack, so it's 20+ years old), but is irrelevant here.

**Comment by mhasbini** [comment]
@solardiz Got it, thanks.

Though, seems like `/` & `%` rules are only supported when using `-j` or `-k` with hashcat.
So while the combination of `/`, `%`, `o` & `p` will apply this functionality, it’ll be limited to the usage with `-j` or `-k` (will not work as regular rules in a file loaded with `-r`).

**Comment by jsteube** [comment]
Note that hashcat also inherited this function but from PasswordsPro,
which I thought inherited from crack. Anyway I'd prefer to stay Crack
compatible. Is there any rule in Crack that does what hashcat is doing
with "p" rule function?

**Comment by solardiz** [comment]
On Sun, May 14, 2017 at 04:48:48AM -0700, Jens Steube wrote:
> Is there any rule in Crack that does what hashcat is doing with "p" rule function?

No, Crack only has "d" (duplicate), which allows for 2x, 4x, etc., but not 3x.  In JtR, we have the powerful "X" command, which can be used e.g. in "d X0zz" (triplicate the word - one of the examples given in doc/RULES) assuming that we're at the start of a rule or after an "M".

Other examples with the "X" command (under same assumption) include "X011" (duplicate the first character) and "Xm1z" (duplicate the last character), which IIRC hashcat has dedicated commands for.

**Comment by roycewilliams** [comment]
Examples are now documented here: https://hashcat.net/wiki/doku.php?id=rule_based_attack#using_p_nth_instance_of_a_character_with_positional_rules

**Comment by solardiz** [comment]
On Wed, May 17, 2017 at 08:08:36AM -0700, Royce Williams wrote:
> Examples are now documented here: https://hashcat.net/wiki/doku.php?id=rule_based_attack#using_p_nth_instance_of_a_character_with_positional_rules

Royce, you're wrongly calling "p" a "rule".  It is not.  It is a character position code.  This distinction is important.

**Comment by mhasbini** [comment]
@roycewilliams 

> 'p' becomes available automatically when using '%' (reject plains unless they have at least X characters) and '=' (reject plains that do not have a character in a specific position).

I think you meant `%` and `/` rules?

**Comment by roycewilliams** [comment]
@solardiz, @0xbsec - good points, both. The distinction is indeed important. I lacked the vocabulary to make it - thanks. Fixed.
