### ISSUE TITLE
Find out where atomics can be eliminated

### ISSUE THREAD

**Issue by KOLANICH** [hashcat/hashcat#1039]
I have an ancient pre GCN card not having a good open-source driver. And you know, flgrx has dropped pre-gcn cards support. Mesa Gallium driver is incomplete, [it lacks atomics, they are in "WIP" stage for ever](https://dri.freedesktop.org/wiki/GalliumCompute/) (the card is old and obsolete, most likely most of that cards are already recycled, so noone will care about it). The header with atomics is included to every kernel file which breaks kernel compilation. Do we really need atomics in every kernel?

**Comment by neheb** [comment]
FWIW atom tested Mesa before. It's really slow. Plus to get better performance, assembly has to be written (no idea if even possible) since several AMD specific functions are missing in Clover (cl_amd_media_ops and 2).

**Comment by jsteube** [comment]
It's multiple threads writing to the same memory section. There's really no way to get rid of atomics.
