### ISSUE TITLE
why custom-charset not work in Brute-force????

### ISSUE THREAD

**Issue by kerry911** [hashcat/hashcat#1040]
command : hashcat64.exe -a 3 -m 9600 --custom-charset1=0123456789 doc.hash -o pass.txt

But it display input.charset:-1 ?l?d?u , -2 ?l?d -3 ?l?d*!$@_ , ......

why ?????

**Comment by philsmd** [comment]
--custom-charset1 (or short -1) per definition only defines a custom charset.
You need to tell hashcat what your mask is, e.g something like this:
```
hashcat64.exe -a 3 -m 9600 --increment --increment-min 1 --increment-max 7 --custom-charset1 0123456789 -o pass.txt doc.hash ?1?1?1?1?1?1?1
```

As you can see here, the mask "?1?1?1?1?1?1?1" (should always be at the end of the command line for -a 3), is needed and tells hashcat: at position one use the custom charset number 1 defined as all numbers from zero to nine, at position 2 also use the custom charset number 1, ...., at position 7 use the charset number 1

**Comment by magnumripper** [comment]
I can see a little room for enhancement with that... How about allowing use of default custom charsets 1..4 with a specified non-default mask, and vice versa (as in OP)? Should be a trivial change in code. I have several times wanted that and been bitten by this unintuitive behavior.

**Comment by jsteube** [comment]
OK, we can do that. Question is just how. I think it's better (for the user) if we abort hashcat with an error message and not try to fix his errors silently. I'd suggest abort hashcat with an appropriate error message if the user specifies a custom charset but does not specify a mask.

**Comment by magnumripper** [comment]
> I'd suggest abort hashcat with an appropriate error message if the user specifies a custom charset but does not specify a mask.

That's definitely better than current behavior.
