### ISSUE TITLE
Add Coverity support to hashcat

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#1045]
Well the, since appvayor was added recently, adding coverity support would be great as well since it's free for open source projects. Requires the hashcat github account I believe.

**Comment by jsteube** [comment]
OK, what to do?

**Comment by neheb** [comment]
Log in to https://scan.coverity.com , log in with GitHub account, add project.  Last I remember it took 2 days for them to accept it. After that  hashcat needs to be built and sent to them for analysis.

**Comment by jsteube** [comment]
I've had to add it "manually" because the correct hashcat/hashcat project name is already claimed. That's kind of strange and causes us to not be able to link it. That's bad because we can not integrate it into Travis CI this way. But let's first try to fix the reported problems and then see how to continue

**Comment by roycewilliams** [comment]
I found @neheb's hashcat-utils integration also:

https://scan.coverity.com/projects/hashcat-utils

**Comment by neheb** [comment]
Ah yes. I remember that from long ago. Need to find out how to delete a
project...

**Comment by jsteube** [comment]
This is the current hashcat-utils path: https://scan.coverity.com/projects/hashcat-hashcat-utils

**Comment by neheb** [comment]
Since coverity support was added, closing.

**Comment by jsteube** [comment]
The hashcat/hashcat project is now linked inside Covertiy to this GitHub repository. We should be able to run it from within Travis. @neheb can you try to find out how?

**Comment by neheb** [comment]
info is here: https://scan.coverity.com/travis_ci
