### ISSUE TITLE
Segmentation fault (core dumped) when running hashcat

### ISSUE THREAD

**Issue by julesduvivier** [hashcat/hashcat#1052]
Hi,

I'm using hashcat (v3.30-155-g8743d758) and it seems to crash every time i run it.

GDB ouput : 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
hashcat (v3.30-155-g8743d758) starting...

Program received signal SIGSEGV, Segmentation fault.
0x0000000000002230 in ?? ()

Can you help ?

Thanks :)

**Comment by philsmd** [comment]
That output doesn't show anything interesting.

You need to use at least:
```
make clean
git pull
make DEBUG=1
gdb --args hashcat ....
```
(after gdb started, you need to type "r" to start the process, after it crashes you need to type "bt" for the backtrack, you can quit gdb with "q" and "yes")

You also forgot to mention what your command line looks like etc.

BTW: it's probably something related to your GPU(s), drivers, OpenCL environment etc... does clinfo work without crash ? Are you sure that all drivers are correctly installed?

**Comment by julesduvivier** [comment]
Hey thanks for the quick answer.

clinfo was SIGSEGV as well, i reinstall the drivers and it now works perfectly.

Sorry !

**Comment by markmaniac** [comment]
I am having the same issue on hashcat latest version 
this is my output

`
mades@SKILZCORE-PC ~/hashcat
$ ./hashcat.exe -b -m 500 -D 1
hashcat (v6.2.5-606-g5e71422af) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 ) - Platform #1 [Intel(R) Corporation]
=============================================================
* Device #1: Intel(R) HD Graphics 4400, skipped
* Device #2: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 5810/11685 MB (1460 MB allocatable), 4MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1
* --optimized-kernel-enable

------------------------------------------------------------------------------
* Hash-Mode 500 (md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)) [Iterations: 1000]
------------------------------------------------------------------------------

   Segmentation fault (core dumped)

`

**Comment by NoFacePeace** [comment]
感谢您的来信，我尽快回复您！
