### ISSUE TITLE
Hashcat 3.30 " BUG feof() " When cracking NTLM

### ISSUE THREAD

**Issue by jackpit110** [hashcat/hashcat#1056]
When attempting to crack NTLM (1000) hashes with dictionary files, hashcat 3.30 returns repeatedly BUG feof()  .

BUG feof()!!
BUG feof()!!
BUG feof()!!
BUG feof()!!
BUG feof()!!
BUG feof()!!

**Comment by philsmd** [comment]
Please retry with the beta versions (https://hashcat.net/beta), or compile the master branch from source.

This bug seems to be already fixed with the latest version.

**Comment by jackpit110** [comment]
yes it is fixed in hashcat-3.30+155.7z  
thx
