### ISSUE TITLE
support for UTF-8 with rules

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#106]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | a.ryabkov |
| Title: | rule engine for UTF-8 |
| Ticket number: | 667 |
| Date reported: | 2015-10-15T23:18:00+02:00 |
| **Description**: | Can you [please] add [to the] rule engine support for UTF-8...<br><br>I understand that support of all mutations will be difficult... But may be you add some base rules:<br>-l<br>-c<br>-u<br>-$X<br>-X |

**Comment by roycewilliams** [comment]
Somewhat related to #1580. The rules syntax today assume that replacement rules are only one byte for their arguments (so0, etc.). Ideally, a rule syntax that allows delimiting of the two arguments (like /o/0, /oo/00, etc.) would be very valuable for use with multibyte rules and with hex rules. Otherwise, it is difficult to tell when one string argument ends and the next one begins.

**Comment by philsmd** [comment]
I agree with royce that this is an issue that is actually almost fixed with the addition of the \x00-\xff syntax that can be used in rules... btw you could also combine several rule functions to add multi-byte emoticons  etc by just using the rules multiple times `$\x00 $\x01 $\x02` etc

I think since this is a very old issue reported on the old `trac` issue tracking software that we used before github, it could also be time to close this for now and see if we need a new (similar ? but more up-to-date) issue in the future.

The problem with the rule engines is of course that we also always try to be compatible with JTR and other password crackers... so it wouldn't be bad to come up with a solution both teams agree with etc. ... but for now I guess the \x00-\xff support already solves almost 99% of the cases with some workarounds. I hope you agree and let's just get rid of those very old `trac` issues for now (and if we really need we could always come up with a new issue that is more up-to-date and focuses on the **new** changes required).
Thx
