### ISSUE TITLE
support for OpenCart (cms/shop) hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#107]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | wonderfulme |
| Title: | OpenCart support: sha1($salt.sha1($salt.sha1($pass))) |
| Ticket number: | 668 |
| Date reported: | 2015-10-17T13:37:44+02:00 |
| **Description**: | Currently both Hashcat and JtR Jumbo lack any kind of [OpenCart](https://www.opencart.com) support.<br><br>Hashing format is as follows: sha1($salt.sha1($salt.sha1($pass))) |

**Comment by philsmd** [comment]
we need much more information here. like max/min salt length (if exists), max/min password length (if exists) etc

**Comment by hops** [comment]
The following has been tested with OpenCart 2.1.0.2 released on January 12, 2016.

Length of the salt is always 9. The possible characters are:
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

Passwords have to be in the range of 4 to 20 characters.
This is hardcoded and can't be changed in the settings.
The check uses mb_strlen() with UTF-8 as encoding so a multi-byte character will be counted as 1.

The password hashing scheme is still the same. sha1($salt.sha1($salt.sha1($pass)))

All of the above is true for both the customers and the admin users.

Here are two example hash:salt pairs both having the password set to "hashcat".
010a5d86210ea0b6a940d0d5ac0ef18a95eee3be:Xm4acCHwq
acb2c573b2293673f1bc6f7a46bd929f7ce3be73:JN0tj1J2U

If you need more information let me know.

**Comment by jsteube** [comment]
Support was added with #453
