### ISSUE TITLE
Output format for WPA should include the AP's MAC address and exclude the essid (ctrl chars in pwd and / or essid)

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1113]
Please change the format of founds:
replace essid by mac_ap:
Hash.....................................................:mac_ap...........:Password
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:112233445566:Password

Explanation:
If there are more than one ap using the same essid it's much faster to find
the corresponding password for an ap by the mac than calculating the hash values.

If there are non ascii-char's in the essid, the found is fragmented or unreadable using ascii-readers.
I found many ap's using non ascii-chars and non utf8 in essid! 

By the way:
your cap2hccapx doesn't find 4way handshakes if only:
1 and 4 (nonce in 4 not  32 -> 0x00)
3 and 4 (nonce in 4 not  32 -> 0x00)
of the exchange are captured.

For further analyses, it would be nice to change the value of
(u8  authenticated;) in hccapx struct to the following:

0 = 1 and 2 of the 4way used
1 = 2 and 3 of the 4way used
2 = 3 and 4 of the 4way used
3 = 1 and 4 of the 4way used

Best regards
ZerBea

**Comment by philsmd** [comment]
First, thank you for your contribution.

Please consider these (maybe seemingly unimportant) points for the future:
1. give better names to the issue "-m 2500 feature request" and/or even "hashcat" within the title doesn't make much sense... the title should be something easily findable. Just name your problem/suggestion/feature request directly within the title: e.g. "Output format for WPA should include the AP's MAC address". Do you notice the difference? "output format" (or "potfile format?) together with "MAC" address is something that we can find when searching for it in the future
2. bug reports for hashcat-utils (or any separate project/repo) should not be mentioned between the lines here. There you go: https://github.com/hashcat/hashcat-utils/issues
3. the same is true for feature requests (e.g. the change for possible values you are suggestion for the "authenticated" field)
4. to fix the cap2hccapx problem you should also not forget to provide some examples and explain it in more details (but again, not here!)

Thanks

**Comment by ZerBea** [comment]
Hi.
1) title edited
   I noticed the difference between pot and outputfile. I only use the outputfile for automated analyses.
  (because the pot is "owned" by hashcat only....)
2) please do not missunderstand me. That was only a remark, and not a bug report
    (I don't use cap2hccapx - wrote my own tool instead.....)
3) shall I open a new issue for this? It's only an idea of me.....
4) example is on it's way to your pm

If you need more examples - please let me know....

**Comment by ZerBea** [comment]
Well, it's no longer a feature, it's a bug.
I've send you a pm which contains a hccapx and the concomitant cap which is able to destroy the format of the pot and the -o output file.

Best regards
ZerBea
