### ISSUE TITLE
#bug -m2500 remove option in connection with potfile not working properly

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1115]
It' seems, that not all the hashes are removed correctly.
Running hashcat 3 times on the same testfile shows every time that files from the potfile are not removed

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-path=$HOME/test/Potfiles/hashcat.pot --outfile-autohex-disable --outfile-format=2 -o $HOME/test/founds $HOME/test/test.hccapx $HOME/test/wordlist

First run:
INFO: Removed 75971 hashes found in potfile
Second run:
INFO: Removed 264 hashes found in potfile             -> not all removed during first run
Third run
INFO: Removed 1 hash found in potfile                     -> again not all removed during second run

The wordlist is every time the same.
Issue only happens on big files containing more or less duplicate hashes

Best regards
ZerBea

**Comment by philsmd** [comment]
Hey @ZerBea,
thank you for the report.

Could I kindly ask you to share the .hccapx file with us (if you prefer privately), such that we can reproduce this.
It would be great if you also include all the commands that need to be run (step by step).

BTW: I think @jsteube still expects an answer to the cap2hccapx problem (about the M1+M4 and M3+M4 problem mentioned here: https://github.com/hashcat/hashcat/issues/1113#issue-208649274 ), so please check your mail inbox ;)

**Comment by ZerBea** [comment]
Well, that's no problem, but the file is realy big. The dumps are downloaded from various sites of the www. So please give me a pm  (at) hashcat.net to send to....
Checked my mails (jens got my pm address), nothing in there.....

The command was every time the same:
hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-path=$HOME/test/Potfiles/hashcat.pot --outfile-autohex-disable --outfile-format=2 -o $HOME/test/founds $HOME/test/test.hccapx $HOME/test/wordlist

Same test.hccapx, same hashcat.pot, same wordlist
First run:
INFO: Removed 76018 hashes found in potfile
Second run (every time 264 hashes removed):
INFO: Removed 264 hashes found in potfile
Third run (every time 1 hash removed):
INFO: Removed 1 hash found in potfile
Well, it seems that hasccat doesn't remove all the founds in pot during the first run.

hccapxinfo -i test.hccapx -I
shows
1286885 records readed from test.hccapx
hccapx information:
total.hashes.............: 1286885
unique.nets..............: 94165
unique.essids............: 71670
unique.key.mics..........: 285292
false.essids.............: 0
false.nonces.............: 0
false.eap.len............: 0
keytype.wpa1.............: 28457
false.keytypes.wpa1......: 0
keytype.wpa2.............: 1258428
false.keytypes.wpa2......: 0
eap.4way.type1...........: 0
eap.4way.type2...........: 1282932
eap.4way.type3...........: 0
eap.4way.type4...........: 3953

Well, the file contains many, many duplicates (doing a cat *.hccapx > test.hccapx isn't such a good idea - but that's the recommended way -> hashcat wiki). On the other hand such a file is very usefull, to explore the boundaries of hashcat....

Well, I didn't realyze that jsteube expects a bug report (cap2hccapx). But that's no problem, I can do it, if you want. And I can send you my own tools (c-source).
The M1+M4 / M3+M4 problem (cap2hccapx) isn't such a big problem, as you the see in the output of hccapxinfo above. Only 3953 hashes of that type dumped....

There is also no real need to expand the contence of the authenticated field, because the infos can be gathered from the eapol frame. On the other hand, if there is such a field, why don't we use it in the best manner....

That's why I didn't make a bug report.


Best regards
ZerBea

**Comment by jsteube** [comment]
I've send you 3 emails to your gmx address. Maybe check the spam folder?

**Comment by ZerBea** [comment]
Very strange......
No emails, nothing in spam...
put you now in white list....
Maybe gmx didn't accept mails from hashcat.net generally????
Please try again.

**Comment by ZerBea** [comment]
Send you a pm containing the testfiles....
Three parts of 7z archive

**Comment by ZerBea** [comment]
None incoming mails. Could it be, that gmx blocked hashcat?

**Comment by jsteube** [comment]
Maybe. I've send you like 5 emails now. hashcat email is using gmail services and also has all kinds of SPF info in DNS. So probably blocking gmail incorrectly?

**Comment by jsteube** [comment]
Come to IRC freenode #hashcat

**Comment by ZerBea** [comment]
Never used freenode bevor, Must do some investigations how to use it....... on pidgin

**Comment by ZerBea** [comment]
Ok, works using pidgin......

**Comment by jsteube** [comment]
OK I've pushed a a fix https://github.com/hashcat/hashcat/commit/2dd027af65b2fec951e9a9afb0b3959c55510b57 which is likely the root cause for your issue. Unfortionally this is the result of some uninitialized variable on start which means that your current potfile might contain invalid data. You need to rebuild the potfile from scratch to verify it's working. A new beta is up on https://hashcat.net/beta/

**Comment by ZerBea** [comment]
Again great job.
Works like a charm...
best regards
ZerBea
