### ISSUE TITLE
add support for Bitlocker

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1117]
Placeholder for adding Bitlocker support.

Spec that might provide enough info: https://github.com/libyal/libbde/blob/master/documentation/BitLocker%20Drive%20Encryption%20(BDE)%20format.asciidoc

As requested in this older forums thread: https://hashcat.net/forum/thread-5474.html

**Comment by Manouchehri** [comment]
There's also dislocker to use as a reference. 

https://github.com/Aorimn/dislocker

**Comment by jsteube** [comment]
I think it needs an extraction utility first. After that, adding a mode is simple, since we already have GPU code for TrueCrypt and LUKS which ships all of the ciphers, hashes and modes we'd need.

**Comment by magnumripper** [comment]
I believe @e-ago will commit a utility and establish a hash format in https://github.com/magnumripper/JohnTheRipper/pull/2427 RSN. If you do so before her, I'll see to it that JtR uses the same hash format.

**Comment by e-ago** [comment]
Yes, I will release the final version of the code no later than 1 or 2 days

**Comment by IncognitoEntity** [comment]
Just writing to add support a bitlocker feature within hashcat.  I believe it uses AES-XTS.  Will it be alike truecrypt striping out the first 512 bytes?

**Comment by jsteube** [comment]
If it's AES-XTS that would be nice, since we have this kind of kernel
already optimized and well tested.

**Comment by IncognitoEntity** [comment]
I've just looked at a bitlocker encrypted drive that i'm working on, and using a command prompt from a Windows 10 live cd within a VM of the bitlocker encrypted machine, the manage-bde -status command shows Encryption Method: AES-XTS 128.  I'm not sure though if bitlocker lets you set up different options like Truecrypt etc.  Something I can test if need be.

**Comment by Manouchehri** [comment]
You can override the default (AES-XTS 128) via group policy. I don't think
it's common though.

**Comment by roycewilliams** [comment]
The [PR](https://github.com/magnumripper/JohnTheRipper/pull/2427) is still pending at this writing, but this may be enough fodder for an extraction utility:

https://github.com/e-ago/JohnTheRipper/blob/6fb90c306f420f179db3d143962dbc36daeebba2/src/bitlocker2john.c

Not sure if this is just a staged copy, or something that's actually functional yet.

**Comment by kholia** [comment]
That version of `bitlocker2john.c` is unreliable at the moment and does not extract "non-hashes" properly.

https://github.com/kholia/bitlocker2john is super reliable but it is a big project. Ideas from this project can be used to improve the former standalone `bitlocker2john.c` utility. This task is already on e-ago's list I believe.

**Comment by magnumripper** [comment]
I think @e-ago mentioned somewhere AES-XTS is not needed for cracking, just normal AES.

**Comment by QuelonaSec** [comment]
[#2516](https://github.com/magnumripper/JohnTheRipper/pull/2516) states: "New hash format supported". Since it seems to be implemented in JTR Jumbo, does this mean something for hashcat?

Is there any progress? Is there something to help for someone with limited coding skills?

**Comment by roycewilliams** [comment]
See also https://github.com/magnumripper/JohnTheRipper/pull/2728
