### ISSUE TITLE
support for longer hash lengths for the blockchain hash type

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#112]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | x34cha |
| Title: | Blockchain Line length. |
| Ticket number: | 679 |
| Date reported: | 2015-11-20T14:52:35+01:00 |
| **Description**: | The [blockchain2john.py](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/blockchain2john.py) hash can be up to 50,000 bytes depending on how many addresses are inside each wallet which I think is max 1000 which is around the 50,000bytes, so some will throw line length exceptions. |

**Comment by jsteube** [comment]
Should be implemented with commit https://github.com/hashcat/hashcat/commit/9fc193ce47d5be59460fb00ee26c80bae84fab96
