### ISSUE TITLE
-m 2500 wpa feature request: Expand uint8_t authenticated field

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1121]
Please expand values
uint8_t  authenticated
from only 0 and 1
to

0 M1 + M2 used
1 M2 + M3 used (anonce from M2, eapol from M3)
2 M3 + M4 used (anonce from M3, eapol from M4)
4 M4 + M1 used (anonce from M1, eapol from M4)
and
5  M3 + M2 used (anonce from M3, eapol from M2)
6  M4 + M3 used (anonce from M4, eapol from M3)

Having this information it became very easy
for third party tools to do a qsort() to get only
wanted records (you now why...)
Best regards
ZerBea

**Comment by jsteube** [comment]
I'll push this implementation to hashcat-utils soon. The only change I made is with the mapping. Here's the new enum:

```
typedef enum
{
  MESSAGE_PAIR_M12E2 = 0,
  MESSAGE_PAIR_M14E4 = 1,
  MESSAGE_PAIR_M32E2 = 2,
  MESSAGE_PAIR_M32E3 = 3,
  MESSAGE_PAIR_M34E3 = 4,
  MESSAGE_PAIR_M34E4 = 5,

} message_pair_t;
```

I'll also update hccapx version to 4 and rename the "authenticated" attribute name to "message_pair".

**Comment by jsteube** [comment]
OK, everything's updated. Please test

**Comment by ZerBea** [comment]
Great. I hope that upcomming cap2hccapx converters use this agreement to.
So we will get no longer uncontrolled hccapx files in www :)
Thanks again......
