### ISSUE TITLE
No device detected - CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by latot** [hashcat/hashcat#1122]
Hi all, well i update this from a very very low version to here, but sadly i can't run it:

```
hashcat -I
hashcat (v3.30-327-g96370d0c+) starting...

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
```

i get the same if i try benchmark, i compile hashcat today.

I'm using gentoo 64, with nvidia enabled (as modules and enabled in the compilation of hashcat) and original drivers, my pc have and i7 and a geforce 740m but no one is detected.....

i try this normally and with optirun (it works fine, so isn't a nvidia module problem) and from admin with the same result.

Gentoo have all dev libs and deps, so i don't think i missed something like that.

Thx. Cya.

**Comment by epixoip** [comment]
This is question is more appropriate for hashcat forums than github issues.
