### ISSUE TITLE
LUKS mode 14600 not working properly

### ISSUE THREAD

**Issue by blafois** [hashcat/hashcat#1123]
Hi,

I extracted a drive LUKS header for which I know the password ("password") to test LUKS mode.

The LUKS header is valid:

`root@dual-k80:~/hashcat/hashcat# cryptsetup luksDump /tmp/header.luks
LUKS header information for /tmp/header.luks

Version:       	1
Cipher name:   	aes
Cipher mode:   	xts-plain64
Hash spec:     	sha1
Payload offset:	4096
MK bits:       	512
MK digest:     	6a 11 8c f9 b8 f1 98 13 27 33 18 c5 b8 24 4e f1 3f a5 0d 87
MK salt:       	c5 1d 08 a3 c4 9e 9c 07 57 2c d5 e6 5d 32 a8 67
               	22 82 d7 fa e3 85 7d 7d d3 33 94 62 f1 22 be 8d
MK iterations: 	75750
UUID:          	b9b782a4-ae58-40af-b928-230331dbf915

Key Slot 0: ENABLED
	Iterations:         	315270
	Salt:               	57 55 dc e3 e0 48 54 0e 10 cd d2 55 c3 67 56 69
	                      	c2 d4 a0 3e 8a da 1d d4 66 9b e6 f5 a1 ae 02 32
	Key material offset:	8
	AF stripes:            	4000
Key Slot 1: DISABLED
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED`

I compiled Hashcat from GIT:

`root@kali-fa:~/tools/hashcat-git/hashcat# ./hashcat -b -m 14600
hashcat (v3.30-329-g14883bcd) starting in benchmark mode...

* Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code CL_OUT_OF_RESOURCES
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro M2000M, 1009/4038 MB allocatable, 5MCU

Hashtype: LUKS

Speed.Dev.#1.....:     1445 H/s (10.45ms)

Started: Wed Feb 22 11:23:58 2017
Stopped: Wed Feb 22 11:24:11 2017`

Creating a simple dictionary containing only password and performing attack using the following command works:

`root@kali-fa:~/tools/hashcat-git/hashcat# echo "password" > simplepasswordlist.txt
root@kali-fa:~/tools/hashcat-git/hashcat# ./hashcat -a 0 -m 14600 ~/header.luks simplepasswordlist.txt
hashcat (v3.30-329-g14883bcd) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code CL_OUT_OF_RESOURCES
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro M2000M, 1009/4038 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Generated dictionary stats for simplepasswordlist.txt: 9 bytes, 1 words, 1 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s

Session..........: hashcat
Status...........: Running
Hash.Type........: LUKS
Hash.Target......: /root/header.luks
Time.Started.....: Wed Feb 22 11:27:02 2017 (4 secs)
Time.Estimated...: Wed Feb 22 11:27:06 2017 (0 secs)
Input.Base.......: File (simplepasswordlist.txt)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (4.08ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/1 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: password -> password
HWMon.Dev.#1.....: N/A

/root/header.luks:password

Session..........: hashcat
Status...........: Cracked
Hash.Type........: LUKS
Hash.Target......: /root/header.luks
Time.Started.....: Wed Feb 22 11:27:02 2017 (5 secs)
Time.Estimated...: Wed Feb 22 11:27:07 2017 (0 secs)
Input.Base.......: File (simplepasswordlist.txt)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (4.07ms)
**Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts**
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: password -> password
HWMon.Dev.#1.....: N/A

Started: Wed Feb 22 11:26:52 2017
Stopped: Wed Feb 22 11:27:09 2017`

Using a big dictionnary, for example example.dict provided with Hashcat, it doesn't work:

`root@kali-fa:~/tools/hashcat-git/hashcat# grep "^password\$" example.dict
password
password

root@kali-fa:~/tools/hashcat-git/hashcat# ./hashcat -a 0 -m 14600 ~/header.luks example.dict
hashcat (v3.30-329-g14883bcd) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code CL_OUT_OF_RESOURCES
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro M2000M, 1009/4038 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Generated dictionary stats for example.dict: 1080240 bytes, 129988 words, 129988 keyspace

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: LUKS
Hash.Target......: /root/header.luks
Time.Started.....: Wed Feb 22 11:28:08 2017 (5 mins, 52 secs)
Time.Estimated...: Wed Feb 22 11:34:00 2017 (0 secs)
Input.Base.......: File (example.dict)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:      369 H/s (5.27ms)
**Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts**
Progress.........: 129988/129988 (100.00%)
Rejected.........: 0/129988 (0.00%)
Restore.Point....: 129988/129988 (100.00%)
Candidates.#1....: ykqkd -> zzzzzzzzzzz
HWMon.Dev.#1.....: N/A

Started: Wed Feb 22 11:27:58 2017
Stopped: Wed Feb 22 11:34:02 2017
`

So it seems there is a bug with "large" dictionaries ?

**Comment by jsteube** [comment]
Can you please retry with --opencl-vector-width 1 also send me the header for debugging

**Comment by blafois** [comment]
Hi Jens !

Here is the header:
[header.luks.zip](https://github.com/hashcat/hashcat/files/794152/header.luks.zip)

Same result with --opencl-vector-width:

./hashcat -a 0 -m 14600 --opencl-vector-width 1 ~/header.luks example.dict
hashcat (v3.30-329-g14883bcd) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code CL_OUT_OF_RESOURCES
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro M2000M, 1009/4038 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Cache-hit dictionary stats example.dict: 1080240 bytes, 129988 words, 129988 keyspace

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: LUKS
Hash.Target......: /root/header.luks
Time.Started.....: Wed Feb 22 17:41:00 2017 (5 mins, 52 secs)
Time.Estimated...: Wed Feb 22 17:46:52 2017 (0 secs)
Input.Base.......: File (example.dict)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:      369 H/s (5.27ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 129988/129988 (100.00%)
Rejected.........: 0/129988 (0.00%)
Restore.Point....: 129988/129988 (100.00%)
Candidates.#1....: ykqkd -> zzzzzzzzzzz
HWMon.Dev.#1.....: N/A

Started: Wed Feb 22 17:40:42 2017
Stopped: Wed Feb 22 17:46:53 2017

**Comment by jsteube** [comment]
Congratulations, I think you pulled the probably most unlikely bug I've ever seen in almost 20 years coding :)

It's related to the example.dict example wordlist, which has another bug. It has twice the password "password" in it and also directly following each other and this is also the password of your LUKS header. On top of that, it's exactly in the same workitem frame which is already as thin as possible because of the enforced -n 2 value. On top of that the buffer allocated for cracked passwords is bound to the number of hashes, which is just 1 for LUKS. But we're cracking it twice now, because the password is twice in the wordlist, leading the Kernel to write into uninitialized memory region, which then creates clEnqueueReadBuffer(), but I'm using a different GPU for testing, so that's fine.

I'll fix this soon. In the meanwhile you can remove the 2nd password "password" in the example.dict.

**Comment by blafois** [comment]
Thank you Jens ! It works !
