### ISSUE TITLE
segfault on AMDGPU-Pro 16.60.379184

### ISSUE THREAD

**Issue by Qwertylex** [hashcat/hashcat#1131]
4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
AMD Radeon HD7970
AMDGPU-Pro 16.60
I have added myself to the "video" group, I have tried executing hashcat as both normal user and as root.

`./hashcat64.bin -t 32 -a 7 example0.hash ?a?a?a?a example.dict`
`hashcat (v3.30) starting...`

`Segmentation fault (core dumped)`

`[   27.617719] hashcat64.bin[342]: segfault at 0 ip           (null) sp 00007ffebbb2dfd8 error 14 in hashcat64.bin[400000+8f000]`

`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
`

Output of: `strace -o strace.txt -f -s128 ./hashcat64.bin -t 32 -a 7 example0.hash ?a?a?a?a example.dict` [strace.txt](https://github.com/hashcat/hashcat/files/798093/strace.txt)

**Comment by jsteube** [comment]
It's hard to tell what the error is coming from. It looks like the AMDGPU OpenCL runtime but we need to be sure about that. Since I can not reproduce this locally with AMDGPU-Pro on Ubuntu 16.04, please create the following view for me on your system:

```
make clean
git pull
make DEBUG=1
gdb --args ./hashcat -t 32 -a 7 example0.hash ?a?a?a?a example.dict
```

after that type "r" to start the gdb run... after the crash occurs type "bt" (for backtrack). You can exit gdb by typing "q" and "yes".

**Comment by Qwertylex** [comment]
ah! When I installed amdgpu-pro-installer on arch, I failed to install: ``amdgpu-pro-libdrm, amdgpu-pro-libgl`` 
which means nvidia's libgl and mesa were installed instead and some other libdrm.

Everything in 3.30 works fine now that I have properly installed amdgpu-pro!
(however latest git [ffc6788] says I have old or broken amd drivers)

Thanks for your time anyway :+1:

**Comment by jsteube** [comment]
Note that this is intentional. AMDGPU-Pro is partially broken, the best AMDGPU-Pro is still 16.40. Details here: https://hashcat.net/forum/thread-6242-post-33291.html#pid33291
