### ISSUE TITLE
try to understand hmac-sha256

### ISSUE THREAD

**Issue by Hans-Maulwurf** [hashcat/hashcat#1132]
hey guys,

i try to learn something in encryption and have a hmac-sha256 hash built in nodejs with

> var hash = crypto.createHmac('sha512', key).update(text).digest('hex');

Now I'm in the situation that I have the _hash_ and the _text_ and want hashcat to get the _key_

Reading the docs and examples, I couldn't figure out how to give all these information to hashcat and start bruteforcing. As I know the _key_ for my examples, I first wanted to test it with just giving it to hashcat except the last character so I tried

> hashcat -m 1460 -a 3 hash.txt b7527413534c861d91f66c889120d66a6ff2bb5d9dcc363d9b78187d44187af?1 -o cracked.txt

In the hash.txt there is jsut one line with the hash. But I get _Line-length exception_

Any hints how I get this working?

**Comment by philsmd** [comment]
Please be more specific, do you mean that your password is longer than the maximum supported password length (64 in your case?) ?

see https://hashcat.net/faq#what_is_the_maximum_supported_password_length for the maximum supported length of the password

Also, it seems that you are sometimes speaking about hmac-sha512 and sometimes about hmac-sha256... it's a little bit confusing.... and maybe your "hash" has the same problem.

See https://hashcat.net/wiki/example_hashes for example hashes for all hmac variants

BTW: you always need to use hash:salt to the hash.txt file (depending on the hash type either the salt or the password is used as the hmac key)

**Comment by Hans-Maulwurf** [comment]
Sorry, of course I mean SHA512. It's not really a password, it's a "server seed" and it's 64 characters long. But this seems to be longer than the supported length?

**Comment by jsteube** [comment]
Right, see here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_the_maximum_supported_password_length

Also note that passwords with static components are better added as salts so that only the variable part of it is actualyl the password. In such a case, the password can be much longer than 64, theoretically unlimited, but it requries to write a special hash-mode for it.
