### ISSUE TITLE
restored a session but showing clFinish(): CL_INVALID_COMMAND_QUEUE 

### ISSUE THREAD

**Issue by kenkoonwong** [hashcat/hashcat#1133]
Win10 64bit
RAM: 32G
Mobo: ASUS Z170-P LGA
CPU: Intel core i7-6700
GPU: 4x GTX 1080
Driver: 378.49
Hashcat 3.30
Recent timeout patch (https://hashcat.net/wiki/doku.php?id=timeout_patch) for CL_OUT_OF_RESOURCES (https://github.com/hashcat/hashcat/issues/1116) which worked.

Below happened when I try to restore a session. 

`Time.Started.....: Thu Feb 23 21:57:15 2017 (4 mins, 39 secs)
Time.Estimated...: Fri Feb 24 00:27:27 2017 (2 hours, 25 mins)
Input.Mask.......: ?u?l?l?1?l?l?l?l?l?d?d?s [12]
Input.Charset....: -1 aeiou, -2 Undefined, -3 Undefined, -4 Undefined
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#3.....: 19595.7 MH/s (6.81ms)
Speed.Dev.#4.....: 21119.0 MH/s (6.54ms)
Speed.Dev.#5.....: 15380.6 MH/s (7.41ms)
Speed.Dev.#6.....: 17067.8 MH/s (7.79ms)
Speed.Dev.#*.....: 73232.4 MH/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 2806147838771200/3445646565504000 (81.44%)
Rejected.........: 0/2806147838771200 (0.00%)
Restore.Point....: 159653888000/196042704000 (81.44%)
Candidates.#3....: Sgnanstyy63( -> Zikugcuyy63(
Candidates.#4....: Hfgagxwfm46< -> Jiduqstyy63(
Candidates.#5....: Hwjaxdhhb63( -> Jepubxwfm46<
Candidates.#6....: Hvhahyosl46< -> Jaxuobbdm46<
HWMon.Dev.#3.....: Temp: 75c Fan: 58% Util: 77% Core:1797Mhz Mem:4513Mhz Lanes:4
HWMon.Dev.#4.....: Temp: 76c Fan: 57% Util: 81% Core:1898Mhz Mem:4513Mhz Lanes:1
HWMon.Dev.#5.....: Temp: 76c Fan: 42% Util: 64% Core:1885Mhz Mem:4513Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 75c Fan: 44% Util: 81% Core:1607Mhz Mem:4513Mhz Lanes:16

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => clFinish(): CL_INVALID_COMMAND_QUEUE

clGetEventProfilingInfo(): CL_OUT_OF_RESOURCESclGetEventProfilingInfo(): CL_OUT_OF_RESOURCESclGetEventProfilingInfo(): CL_OUT_OF_RESOURCES

Session..........: ***
Status...........: Exhausted
Hash.Type........: MD5
Hash.Target......: ***
Time.Started.....: Thu Feb 23 21:57:15 2017 (11 mins, 0 secs)
Time.Estimated...: Fri Feb 24 02:30:29 2017 (4 hours, 22 mins)
Input.Mask.......: ?u?l?l?1?l?l?l?l?l?d?d?s [12]
Input.Charset....: -1 aeiou, -2 Undefined, -3 Undefined, -4 Undefined
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#3.....:  9917.0 MH/s (6.79ms)
Speed.Dev.#4.....:  9917.0 MH/s (6.44ms)
Speed.Dev.#5.....:  9817.1 MH/s (7.31ms)
Speed.Dev.#6.....:  9845.5 MH/s (6.93ms)
Speed.Dev.#*.....: 39496.5 MH/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 2824186298368000/3445646565504000 (81.96%)
Rejected.........: 0/2824186298368000 (0.00%)
Restore.Point....: 160678707200/196042704000 (81.96%)
Candidates.#3....: Laqangfhg88  -> Mmqugtxxw77"
Candidates.#4....: Dkqalzybp77" -> Pequffkpj56\
Candidates.#5....: Ciwaadcjf34( -> Xfzulgzef34(
Candidates.#6....: Dkqapcxxw77" -> Pequrzybp77"
HWMon.Dev.#3.....: Temp: 75c Fan: 45% Util: 42% Core:1822Mhz Mem:4513Mhz Lanes:4
HWMon.Dev.#4.....: Temp: 68c Fan: 33% Util: 38% Core:1936Mhz Mem:4513Mhz Lanes:1
HWMon.Dev.#5.....: Temp: 67c Fan: 33% Util: 40% Core:1898Mhz Mem:4513Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 76c Fan: 48% Util: 42% Core:1784Mhz Mem:4513Mhz Lanes:16

Started: Thu Feb 23 21:57:10 2017
Stopped: Thu Feb 23 22:08:17 2017

C:\hashcat-3.30>`

Any idea what happened? Thanks

**Comment by jsteube** [comment]
I can not reproduce this on my 4x1080 box. Maybe it's because I'm running them on Ubuntu 16.04. Can you please try to reproduce this issue with Ubuntu 16.04? If it occur on there, too, maybe it's a local hardware problem. Your PCI-E lane configuration looks kind of weird and made me think that.

**Comment by kenkoonwong** [comment]
Thanks Atom. I will try that.

**Comment by jsteube** [comment]
No response from OP after long time, therefore closing the issue. Feel free to reopen if needed.
