### ISSUE TITLE
aes128(md5($pass)) 

### ISSUE THREAD

**Issue by wuppp** [hashcat/hashcat#1138]
Can someone add this specific hash type?  
aes128(md5($pass)) 
 Thanks a lot!

**Comment by magnumripper** [comment]
That doesn't make any sense. You would need a known plain or something.

**Comment by wuppp** [comment]
@magnumripper I known the ciphertext and length of key.

**Comment by magnumripper** [comment]
OK that makes sense 😃

**Comment by jsteube** [comment]
Please provide all information stated here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

**Comment by jsteube** [comment]
No response from OP for some time plus the request itself doesn't make much sense. Feel free to reopen in case you provide the missing informations.
