### ISSUE TITLE
hashcat (v3.30) OpenCL error (windows 7) HELP

### ISSUE THREAD

**Issue by X-HAT** [hashcat/hashcat#1140]
Hello,

I'm facing this error when i run hashcat 3.30 on windows 7

hashcat (v3.30) starting...

Device #2: Intel's OpenCL runtime (GPU only) is currently broken
We need to wait for an update of their OpenCL drivers
You can use --force to override this but do not post error reports if you do so
No devices found/left
Started: Mon Feb 27 23:43:36 2017
Stopped: Mon Feb 27 23:43:36 2017

i'll be appreciated by any help.
Thanks.

**Comment by pascalqq** [comment]
Frist, use this http://www.intel.com/content/www/us/en/support/detect.html to update or reinstall your intel gpu driver.
Second, add --force to your para.
Then, this should not be posted in issue, your should post your question here: https://hashcat.net/forum/forum-45.html

**Comment by jsteube** [comment]
Please use the hashcat forum

**Comment by X-HAT** [comment]
Thanks jsteube, and i'm sorry it's the first time that i post something.
