### ISSUE TITLE
Hitting Q to quit hashcat at the wrong time can cause an infinite loop

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1146]
Using "Q" to quit hashcat after some, but not all hashes have been found **before** the attack has advanced from the current dictionary will cause hashcat to loop infinitely.

Test command:
hashcat64.exe -a 0 -m 0 example.hashes LargeDictionary -r .\rules\best64.rule --loopback

Test hashes:
5f4dcc3b5aa765d61d8327deb882cf99:password
5f4dcc3b5aa765d61d0000000000000 Invalidated purposefully to cause hashcat to continue running.

Test methodology:
Place "password" at the start of a large wordlist(larger = more time to cause the issue) and run with the command and hashes given. After the first hash has been found, hit "Q" and hashcat should loop indefinitely.

**Comment by jsteube** [comment]
OK, should be fixed with https://github.com/hashcat/hashcat/commit/6b77606bdd71a39dec48f78db7bce1457eeb5cab

New beta is up. Please test and close the issue if fixed. Thanks for reporting!

**Comment by Chick3nman** [comment]
Fixed, Thanks!
