### ISSUE TITLE
full status codes?

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1155]
I have been searching for full status codes for output '--machine-readable'
all i have found is status codes on exit: https://github.com/hashcat/hashcat/blob/master/docs/status_codes.txt

can you make a doc file that state all the status codes, including the changed ones (v3.10 to v3.40)

**Comment by philsmd** [comment]
The current complete list of the codes is here: https://github.com/hashcat/hashcat/blob/89f8739ddeccd90ef60f0637cfa4a965f35e131a/include/types.h#L161-L171

The main problem is that not all of these values are valid status/exit codes (so there is that slight difference between status codes and "device status" value displayed in the machine readable output).

Maybe @jsteube has an idea what we should do here: maybe a wiki section or a separate wiki page on hashcat.net should be sufficient to explain the values!?

**Comment by s77rt** [comment]
that what i was searching for ^^
thank you
a wiki page would be much easier to access
