### ISSUE TITLE
Changes on INFO: approaching final keyspace, workload adjusted

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1156]
Something seems wrong,,
even keyspace is a bit large, it adjuste the speed, therefore drop in performance..
can i get the changes from v3.10 to v3.40 regarding that adjustement?

**Comment by Chick3nman** [comment]
These questions seem better suited for the hashcat forums( https://hashcat.net/forum/index.php ) than for the issue tracker. You will likely have better luck asking there.

**Comment by jsteube** [comment]
Yes, please post on forum, doesn't sound like a bug from the description
