### ISSUE TITLE
BUG: Speed.Dev

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1158]
Hi
testing a .hccapx file with 6 digests (4 uniq)
bruteforce: 10 digits
after running the attack command got an normal output: (gtx 1080)
Speed.Dev.#1.....:   370.7 kH/s (92.33ms)
after few seconds..
Speed.Dev.#1.....:  1238.6 kH/s (11.47ms)
and keep increasing for no sense reaosn..
Speed.Dev.#1.....:  1509.5 kH/s (91.87ms)

**Comment by s77rt** [comment]
Looks the speed is being doubled per how many uniq hashes ..

1 uniq hashes:
 Speed.Dev.#1.....: 370.7 kH/s (92.33ms)

2 uniq hashes:
 Speed.Dev.#1.....: 741.2 kH/s (92.33ms)

3 uniq hashes:
 Speed.Dev.#1.....: 1114.4 kH/s (92.33ms)

4 uniq hashes:
 Speed.Dev.#1.....: 1480.9 kH/s (92.33ms)

**Comment by jsteube** [comment]
hopefully will be fixed soon
