### ISSUE TITLE
What happened to --pw-min and --pw-max

### ISSUE THREAD

**Issue by phillycheeze** [hashcat/hashcat#1172]
It seems like these command line options disappeared in 3.0. 

Is there anyway to tell hashcat to ignore hashing plain passwords that is under a certain a length?

I have tried -k '>8' but this has no effect.

**Comment by epixoip** [comment]
--pw-min and --pw-max have been renamed --increment-min and --increment-max. They never had any affect on any attack mode other than ''-a 3 -i'', so the new nomenclature is more correct.

-k only works with -a 1 and -a 7. Maybe you want -r instead?

**Comment by phillycheeze** [comment]
I have a -r with a rule based list. The problem is with a dictionary and ruleset, I want hashcat to skip passwords less than 8 characters. This is because some combos of the rules with the plaintext passwords generate passwords less than 8 characters.

Since I know the hash is at least 8 characters, there is no point in testing it. Maybe there is a way to run the rules against a dictionary and output every possible plaintext password?

**Comment by roycewilliams** [comment]
This is more of a usage thing that's more appropriate for the forums if it needs to be addressed further, but you have a few options to truncate depending on context.

1. You can stack rulesets. So you can add a second ruleset with -r that just contains '8

2. Using  -j '8 or -k '8

3. Appending '8 to all lines in your ruleset

But even then, you're likely to get duplicates, because all these do is truncate.

Also note that unless it's a pretty slow hash, or most of your rules result in strings longer than 8, there's no need to be worried about a few % of strings that are too long.

**Comment by phillycheeze** [comment]
Okay thanks for the feedback and help. My problem is actually the opposite. I want to not hash anything under 8 characters.

**Comment by roycewilliams** [comment]
~~ Ah, sorry. OK, then creating a rule file with '>8' in it, and then adding it as a second -r (so -r myrules.rule -r min8.rule) may do the trick.~~ Using > -in an -r ruleset doesn't work:

`Cannot convert rule for use on OpenCL device in file /var/local/rules/min8.rule on line 1: >8`

-j / -k should skip post-rules plains without trying to hash them. You'll see plains less than 7 in --stdout output, but they'll show up in the "Rejected" status line.

**Comment by phillycheeze** [comment]
If i do that, it says it is an invalid rule. I tried >8 and '>8' on hashcat v3.4.

When i use it with -j -k, it doesn't have any effect on the program. Maybe the documentation is out of date?

**Comment by epixoip** [comment]
It would actually be '<8' not '>8'. But yeah now that you mention it, I don't think the reject rules have been ported to OpenCL because it's too slow. It's actually faster to hash unnecessary candidates than it is to try to reject them.

**Comment by phillycheeze** [comment]
Is it always the case they are too slow? Currently I am running against bcrypt hashes with a cost factor of 10. That is why this rejection rule can really speed up my hashing time :)

**Comment by h4cker-dev** [comment]
hmmm

**Comment by heapbytes** [comment]
anyone help me :
I am decoding the bcrypt hash 
and I know the password length is 4 ........ how can I set the length...
hashcat -m 3200 
 hashes1.txt /usr/share/wordlists/rockyou.txt  I used this command 
 the hash is _redacted_

**Comment by JBalanza** [comment]
I think this options still makes lot of sense nowadays. In other attacks like dictionary+rules its neccesary to filter out candidates that do not meet minimun password length (i.e.: a domain password that should meet domain requirements as for minimun length) there is no way to filter candidates that does not meet the requirement and thus, speed up the cracking.
