### ISSUE TITLE
rules not working?

### ISSUE THREAD

**Issue by mistermisschief** [hashcat/hashcat#1174]
i have another one

if i run a rule based attack when i know what the password is.  it is missing the password on both beta and 3.4. unless its my fault. i am trying to use a rule base attack to make use of the word in the text file and make it lower case and append two digits but no luck

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: MOMMAM (AP:e0:ca:94:b8:71:d6 STA:48:02:2a:09:91:98)
Time.Started.....: Fri Mar 10 17:39:24 2017 (0 secs)
Time.Estimated...: Fri Mar 10 17:39:24 2017 (0 secs)
Input.Base.......: File (C:\Users\x\Desktop\hashcat-3.40\mommam.txt)
Input.Mod........: Rules (C:\Users\x\Desktop\hashcat-3.40\one rule.txt)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....: 0 H/s (0.00ms)
Speed.Dev.#2.....: 0 H/s (0.00ms)
Speed.Dev.#*.....: 0 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 1/1 (100.00%)
Rejected.........: 1/1 (100.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Copying]
Candidates.#2....: [Copying]
HWMon.Dev.#1.....: Temp: 44c Fan: 33% Util: 0% Core: 65MHz Mem:4513MHz Lanes:16
HWMon.Dev.#2.....: Temp: 58c Fan: 55% Util:100% Core: 65MHz Mem:3802MHz Lanes:1

Started: Fri Mar 10 17:39:17 2017
Stopped: Fri Mar 10 17:39:25 2017

and if i run a stdout

C:\Users\x>C:\Users\x\Desktop\hashcat-3.40\hashcat64.exe -m 2500 -w 3 --stdout C:\Users\x\Desktop\hashcat-3.40\mommam.txt -r "C:\Users\x\Desktop\hashcat-3.40\one rule.txt"
mommam88

and if i run bruteforce 27a730499071fdd4e5db542a8f79080e:e0ca94b871d6:48022a099198:MOMMAM:mommam88

Session..........: hashcat
Status...........: Cracked
Hash.Type........: WPA/WPA2
Hash.Target......: MOMMAM (AP:e0:ca:94:b8:71:d6 STA:48:02:2a:09:91:98)
Time.Started.....: Fri Mar 10 17:43:35 2017 (0 secs)
Time.Estimated...: Fri Mar 10 17:43:35 2017 (0 secs)
Input.Mask.......: mommam?d?d [8]
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....: 0 H/s (0.61ms)
Speed.Dev.#2.....: 0 H/s (0.00ms)
Speed.Dev.#*.....: 0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 100/100 (100.00%)
Rejected.........: 0/100 (0.00%)
Restore.Point....: 0/100 (0.00%)
Candidates.#1....: mommam12 -> mommam59
Candidates.#2....: [Generating]
HWMon.Dev.#1.....: Temp: 50c Fan: 33% Util:100% Core: 65MHz Mem:4513MHz Lanes:16
HWMon.Dev.#2.....: Temp: 53c Fan: 33% Util:100% Core: 65MHz Mem:3802MHz Lanes:1

Started: Fri Mar 10 17:43:29 2017
Stopped: Fri Mar 10 17:43:36 2017

Any thoughts?

see https://forum.hashkiller.co.uk/topic-view.aspx?t=18081&m=124940#124940 for files

**Comment by jsteube** [comment]
It's working as expected, see here:

```
Rejected.........: 1/1 (100.00%)
```

Your input word was < length 8, so it's rejected because of WPA minimum length 8. If you want the behaviour the different way, like after rule to check apply to check for length 8 you need to use a pipe and run the first hashcat instance in --stdout mode.

**Comment by mistermisschief** [comment]
but with the rule in place it creates a word that is 8 length in total as it adds 88 to the end of the word i.e momman88. so this means hashcat will only use 8 plus passwords to add rules too and not a smaller word that when ran with the rules is 8 or over in length?

**Comment by GommeAntiLegit** [comment]
Is a fix of this issue planned?
