### ISSUE TITLE
Error when using mask along with --stdout and custom charset

### ISSUE THREAD

**Issue by Xanadrel** [hashcat/hashcat#1175]
Command to reproduce and output:
```
$ hashcat --stdout -a 3 -1 hH ?1ashcat
You need to specify a mask if you specify a custom-charset
```

This may be related to #1153 

Edit: For now a workaround consist in adding an extra "param" at the end of the command such as: 
```
$ hashcat64 --stdout -a 3 -1 hH ?1ashcat blah
hashcat
Hashcat
```

**Comment by philsmd** [comment]
Nice find, I admit I missed that specific case when fixing #1153 . Yeah, it was kinda related.

Hopefully now we have covered all cases of custom charsets + command line switches.

Thanks
