### ISSUE TITLE
restore point / checkpoint quit slower than expected for fast hash

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1176]
With a 23M-word wordlist, & two stacked rule sets (250695 x 43) = 10779885 rules, the total predicted time on my rig is ~8 hours. I asked for a checkpoint quit 40 minutes earlier in this run, and it's showing no signs of slowing down (and note that the restore point is still 0%):

Session..........: hashtest
Status...........: Running
Hash.Type........: SHA1
Hash.Target......: left.txt
Time.Started.....: Fri Mar 10 14:11:50 2017 (1 hour, 34 mins)
Time.Estimated...: Fri Mar 10 22:23:41 2017 (6 hours, 37 mins)
Input.Base.......: File ([redacted])
Input.Mod........: Rules (test.rule, ./hybrid/append_ds.rule)
Input.Queue......: 4/74 (5.41%)
Speed.Dev.#1.....:  1718.3 MH/s (390.47ms)
Speed.Dev.#2.....:  1279.0 MH/s (340.93ms)
Speed.Dev.#3.....:  1492.9 MH/s (292.10ms)
Speed.Dev.#4.....:  1398.2 MH/s (311.89ms)
Speed.Dev.#5.....:  1384.7 MH/s (314.87ms)
Speed.Dev.#6.....:  1296.7 MH/s (336.31ms)
Speed.Dev.#*.....:  8574.1 MH/s
Recovered........: 2612024/4579032 (57.04%) Digests, 0/1 (0.00%) Salts
Recovered/Time...: CUR:6,167,N/A AVG:7,445,10690 (Min,Hour,Day)
Progress.........: 48017499488256/252073359486120 (19.05%)
Rejected.........: 0/48017499488256 (0.00%)
Restore.Point....: 0/23393476 (0.00%)
Candidates.#1....: Diluiate1`>@ -> OOmbmdsuen7a@
Candidates.#2....: Mascidiane@ -> ZRetsaciccuL@
Candidates.#3....: 3budsmen9] -> TSeunder92]
Candidates.#4....: vSteuoders1] -> gxascidian4]
Candidates.#5....: AAAABBBB22^ -> Diluiite0^
Candidates.#6....: e7s@{i{{ul] -> m0kerden6]
HWMon.Dev.#1.....: Temp: 73c Fan: 80% Util:100% Core:1835MHz Mem:4513MHz Lanes:8
HWMon.Dev.#2.....: Temp: 57c Fan: 50% Util:100% Core:1354MHz Mem:3004MHz Lanes:4
HWMon.Dev.#3.....: Temp: 53c Fan: 50% Util:100% Core:1354MHz Mem:3004MHz Lanes:16
HWMon.Dev.#4.....: Temp: 48c Fan: 50% Util:100% Core:1341MHz Mem:3004MHz Lanes:4
HWMon.Dev.#5.....: Temp: 64c Fan: 50% Util:100% Core:1379MHz Mem:3004MHz Lanes:1
HWMon.Dev.#6.....: Temp: 66c Fan: 50% Util:100% Core:1366MHz Mem:3004MHz Lanes:1

**Comment by roycewilliams** [comment]
It did checkpoint-quit at this point. Maybe I just don't understand well enough how to do back-of-the-napkin checkpoint calculations?

Session..........: hashtest
Status...........: Aborted (Checkpoint)
Hash.Type........: SHA1
Hash.Target......: left.txt
Time.Started.....: Fri Mar 10 14:11:50 2017 (2 hours, 6 mins)
Time.Estimated...: Fri Mar 10 23:40:45 2017 (7 hours, 22 mins)
Input.Base.......: File ([redacted])
Input.Mod........: Rules (test.rule, ./hybrid/append_ds.rule)
Input.Queue......: 4/74 (5.41%)
Speed.Dev.#1.....:  1755.1 MH/s (381.22ms)
Speed.Dev.#2.....:  1051.0 MH/s (413.80ms)
Speed.Dev.#3.....:  1100.5 MH/s (395.12ms)
Speed.Dev.#4.....:  1107.9 MH/s (392.49ms)
Speed.Dev.#5.....:  1117.1 MH/s (389.22ms)
Speed.Dev.#6.....:  1107.3 MH/s (392.67ms)
Speed.Dev.#*.....:  7238.9 MH/s
Recovered........: 2612036/4579032 (57.04%) Digests, 0/1 (0.00%) Salts
Recovered/Time...: CUR:0,61,N/A AVG:5,337,8111 (Min,Hour,Day)
Progress.........: 60024845107200/252073359486120 (23.81%)
Rejected.........: 0/60024845107200 (0.00%)
Restore.Point....: 851968/23393476 (3.64%)
Candidates.#1....: 1Diluiate~ -> DSMEN7OMBU~
Candidates.#2....: 5ascidian~ -> CICCULETSA~
Candidates.#3....: 9Ombudsmen~ -> EUNDER9ST~
Candidates.#4....: 1Steunders~ -> CIDIAN4AS~
Candidates.#5....: BAAA-BBB~ -> LUIATE0DI~
Candidates.#6....: letsaciccu~ -> KERDEN6MO~
HWMon.Dev.#1.....: Temp: 60c Fan: 80% Util:100% Core:1873MHz Mem:4513MHz Lanes:8
HWMon.Dev.#2.....: Temp: 24c Fan: 50% Util:  0% Core: 734MHz Mem:3004MHz Lanes:4
HWMon.Dev.#3.....: Temp: 16c Fan: 50% Util:  0% Core:1164MHz Mem:3004MHz Lanes:16
HWMon.Dev.#4.....: Temp: 19c Fan: 50% Util:  0% Core: 607MHz Mem:3004MHz Lanes:4
HWMon.Dev.#5.....: Temp: 20c Fan: 50% Util:  0% Core: 822MHz Mem:3004MHz Lanes:1
HWMon.Dev.#6.....: Temp: 23c Fan: 50% Util:  0% Core:1164MHz Mem:3004MHz Lanes:1

Started: Fri Mar 10 07:29:54 2017
Stopped: Fri Mar 10 16:18:38 2017

**Comment by roycewilliams** [comment]
1/4 of the way into a job, I wouldn't expect the restore point to only be at 3.64%.

**Comment by philsmd** [comment]
I think this is to be expected and normal behaviour. The GPUs didn't finish the huge set of password candidates earlier than @ 3.64%. If the checkpoint was not yet reached, the Checkpoint Quit feature can't terminate hashcat. The only way to stop earlier (and therefore have finer grained checkpoint goals) would be to have different/smaller -w (or -n/-u) settings, but this of course would also affect performance a lot.

**Comment by jsteube** [comment]
The more modifier you use, the longer it takes to reach a checkpoint. That's true for both fast and slow hashes.

**Comment by roycewilliams** [comment]
For future searchers - my intuition is that for any given run, there would be roughly x restore points that are each 1/x percent of the total. If there's a quick way to capture why not, then it might head off future questions. I will add the answer to the FAQ.
