### ISSUE TITLE
Speed drop while using -a0 mode

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1178]
Hi
many times, while using dictionary attack -a0 the speed drop,, much lower
than the -a3 mode

and i get msg "INFO: approaching final keyspace, workload adjusted", however the keyspace is already large..

this issue occur just on the new hashcat v3.40

**Comment by jsteube** [comment]
Looks legit to me, if the keyspace is too small then the speed drops. I'm sorry but since you did not add any additional information to clarify the situation there's nothing we can do.
