### ISSUE TITLE
Re-write hashcat help for Truecrypt/Veracrypt

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#1186]
Hi, 

Could I request that hashcat help info for Truecrypt and Veracrypt be expanded instead of using X and Y? I am using regex to generate list of supported hashes by reading the help option and it would make it easier for users to select the right option instead of trying to decode X-Y combination.

Thanks

**Comment by jsteube** [comment]
No sorry, that would look kind of bloated
