### ISSUE TITLE
allow customizable bypass thresholds (--bypass) based on recover rates, etc.

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1187]
Feature request: 

A simple framework for automatically bypassing the current attack based on user-selected thresholds. 

This could be useful for running a series of attacks in sequence. It would behave similarly to --runtime, but would be based on recovery rates or other thresholds. And a generic framework might stimulate creative contributions.

--bypass
    Enable bypass thresholds.

--bypass-limit=[Num]
   The desired threshold.

--bypass-type=[Str]
    Specify bypass type. Some of them could be based on recovery rate, as in:

   amin - average per minute
   ahour - average per hour
   aday - average per day
   cmin - current per minute

Other ideas, may or may not be useful, just brainstorming:

   rejectp - rejection percent (could automatically abort if too many rejects)
   progressp - progress percentage (probably not useful)
   recoveredp - recovered percentage (100% would be popular ;)
   saltp - percentage of recovered salts
   restorep - automatically quit after a specific restorepoint percentage has been exceeded

etc.

**Comment by magnumripper** [comment]
This could end up in lots of bloat but I can see some useful cases.

Just FWIW, JtR has a KISS variant of it: Given a negative *N* for `--max-runtime=N` it will stop after that many seconds of not cracking anything.

**Comment by magnumripper** [comment]
> progressp - progress percentage (probably not useful)

I can see a use case. Let's say you attacked 500 salts for a week and got 12.34% progress. Then you get a few more hashes. You could pause the first job, run the new hashes up to 12.34% and then resume the original job with the new hashes added to it.

**Comment by roycewilliams** [comment]
Note also that the tags/names for these attributes were just enough to disambiguate but are otherwise pretty artless, so they could be changed to whatever is best, of course. :)

**Comment by jsteube** [comment]
We already had such options in the past (not exactly those, but similar) to shutdown hashcat in case XY occurs and made some experience with them. They were mostly based on cracks-per-time but also time in general. It turned out that such options make sense only for a very few cases, like cracking LI or other mass data. In the real life when we only have to crack a single TrueCrypt volume it created more problems because users misused the flags. It raised lots of support questions that we wouldn't have to deal with if there are no such options, therefore we dropped them.

**Comment by roycewilliams** [comment]
That's interesting - bummer that it's a net loss from a support load perspective. FWIW, if an automatic bypass existed for average per hour and average per day, I would probably use them a lot.

**Comment by Shooter3k** [comment]
how about a --max-runtime=N like JtR?
