### ISSUE TITLE
These errors always appear. clCreateContext(): CL_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by d3301** [hashcat/hashcat#1188]
I can not use this tool ...
Each update appears a different error.
Now I get this error at the end :(  --> clCreateContext(): CL_UNKNOWN_ERROR

~# hashcat -m 0 hash.txt /root//WORDLIST/tbswordlist1.txt -d 1
hashcat (v3.30) starting...

Old potfile detected: /root/.hashcat/hashcat.pot
New potfile is: /root/.hashcat/hashcat.potfile 

**clGetDeviceIDs(): CL_DEVICE_NOT_FOUND**

**clGetDeviceIDs(): CL_DEVICE_NOT_FOUND**

OpenCL Platform #1: Mesa, skipped or no OpenCL compatible devices found

OpenCL Platform #2: Intel(R) Corporation

 Device #1: Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz, 435/1742 MB allocatable, 2MCU

Hashes: 9 digests; 9 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory..**.clCreateContext(): CL_UNKNOWN_ERROR**

Started: Fri Mar 17 19:01:44 2017
Stopped: Fri Mar 17 19:01:48 2017

**Comment by philsmd** [comment]
Please do not post bug reports if you use old versions of hashcat.

hashcat 3.40 is the *current* release version. Please always use the latest versions (especially if you try to troubleshoot and/or report bugs).

**Comment by jsteube** [comment]
No response from OP after long time, therefore closing the issue. Feel free to reopen if needed.
