### ISSUE TITLE
some invalid attack modes not rejected early

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1189]
I stumbled upon this while looking into #1185 . 

From briefly looking at https://github.com/hashcat/hashcat/blob/f651f446061c3b0fb8d48f30621c5d04194a3c2d/src/user_options.c#L384-L391, I would have expected hashcat to abort before initializing OpenCL, etc.

$ echo -en 'hashcathashcat' | sha1sum | awk '{print $1}' | tee sha1.hash
2b3d941e2811b310844213aef353e37955d65c07

$ ./hashcat -m 100 **-a bogus** sha1.hash
hashcat (v3.40-49-g20057d85) starting...

[snip]

Starting attack in stdin mode...

^C

$ ./hashcat -m 100 **-a 9** sha1.hash
hashcat (v3.40-49-g20057d85) starting...

[snip]

Starting attack in stdin mode...

^C

**Comment by jsteube** [comment]
I can see the problem with -a bogus (which atoi() translates to 0), but I can not reproduce the case with -a 9:

```
root@ht:~/hashcat# ./hashcat -m 100 -a 9 hash.txt
Invalid attack-mode specified
```

**Comment by roycewilliams** [comment]
Confirmed as non-reproducible on my side. I am not sure now how I got that case. 

I have a shell script with each test case in it to capture exactly what parameters I used, and this one now behaves as expected. 

If I can determine that it really was happening, I will open a separate issue.
