### ISSUE TITLE
outfile_write method does not output crack_pos.

### ISSUE THREAD

**Issue by syntaxmonkey** [hashcat/hashcat#1194]
When using --outfile-format=11, hashcat is suppose to include the guess number as the last item.  However, this was the output:

a2593e6a5ae8ba54b95ff7b182d738a8:jblaze:

Looking at outfile_write, I tracked down the problem.  Variable 'tmp_len' needs to be increased in size to accommodate the crackpos text.  Here is my rudimentary fix on line 439:

435:  if (outfile_ctx->outfile_format & OUTFILE_FMT_CRACKPOS)
436:  {
437:    sprintf (tmp_buf + tmp_len, "%" PRIu64, crackpos);
438:  }
439:  tmp_len += 20; // Need to move end of the buffer to include crackpos.
440:  tmp_buf[tmp_len] = 0;

After adding line 439, the output is now:
a2593e6a5ae8ba54b95ff7b182d738a8:jblaze:9612916440

I'm using version 3.40 of hashcat.

**Comment by magnumripper** [comment]
Hard-coding 20 can't be right. It should be more like this
```c
    if (outfile_ctx->outfile_format & OUTFILE_FMT_CRACKPOS)
    {
        tmp_len += sprintf (tmp_buf + tmp_len, "%" PRIu64, crackpos);
    }
```
(Edit: I see @philsmd already commented on #1195. snprintf should be used as well.)
