### ISSUE TITLE
--show exits application if password needs to be cracked

### ISSUE THREAD

**Issue by tankbusta** [hashcat/hashcat#1197]
Hi,

I've been working on a tool to manage hashcat tasks via a UI using the ability to link against libhashcat. I want to use a potfile but I have an issue around `--show` where hashcat will exit with no output if the hash does not exist in the potfile.

Would it be possible to have `--show` do nothing and have hashcat go about it's business if the hash does not exist in the potfile? 

Example: 
        
    hashcat --potfile-path=/Users/cschmitt/.hashcat/mypotfile.pot --show \
    5d41402abc4b2a76b9719d911017c592 /Users/cschmitt/.hashcat/shared/default.hcmask
    $ rc: 0 

What I'd like to see instead:

    $ hashcat --potfile-path=/Users/cschmitt/.hashcat/mypotfile.pot --show \
    5d41402abc4b2a76b9719d911017c592 /Users/cschmitt/.hashcat/shared/default.hcmask

    hashcat (v3.40+) starting...

    OpenCL Platform #1: Apple
    =========================
    * Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
    * Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
    * Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 10MCU

    Hashes: 1 digests; 1 unique digests, 1 unique salts
    Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
    Rules: 1

    INFO: Hash(s) does not exist in potfile, continuing with cracking.

If the user specified a file with one or more hashes and lets say, 2 of them exist in the potfile and 10 do not.. hashcat would do this:

    $ hashcat --potfile-path=/Users/cschmitt/.hashcat/mypotfile.pot --show \
    /tmp/myhashes /Users/cschmitt/.hashcat/shared/default.hcmask

    hashcat (v3.40+) starting...

    OpenCL Platform #1: Apple
    =========================
    * Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
    * Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
    * Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 10MCU

    5d41402abc4b2a76b9719d911017c592:hello
    4f41243847da693a4f356c0486114bc6:deadbeef

    INFO: 8/10 hashes do not exist in potfile, continuing..

    Hashes: 8 digests; 1 unique digests, 1 unique salts
    Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
    Rules: 1
    
    ...

**Comment by philsmd** [comment]
I don't understand this problem completely.

--show should always be run independently form the actual cracking.
--show/--left were designed to be used after your cracking job and not mix them up with the cracking itself.

There are basically always 2 steps involved (2-fold), like described here: https://hashcat.net/faq#how_can_i_show_previously_cracked_passwords_and_output_them_in_a_specific_format_eg_emailpassword

--show/--left are just meant to be used after cracking to output the cracks (and if you want with a different --outfile-format)

I don't know if this is just a missunderstanding from your side how --left/--show were designed or maybe I just didn't understand this "issue"!?

**Comment by tankbusta** [comment]
The issue is that I may not know the contents of the potfile and/or the contents of a file that contains a list of 10 MD5's to crack. Some of them might exist in the potfile, all of them might, or none of them do. 

As it works now I may have to run hashcat several times just to get my results. 

Example: `hashcat_session_init`, `hashcat_session_execute`, see that some hashes exist in potfile when my event callback gets `EVENT_POTFILE_ALL_CRACKED`, `hashcat_session_destroy`, `hashcat_session_init`, `hashcat_session_execute (with show)`, ...

**Comment by philsmd** [comment]
hashcat will output this line
`INFO: Removed x hashes found in potfile`
whenever it has found some hashes within the potfile, but of course it won't print all the hashes again and again, each time.

If this is not enough information (just the number of hashes), then you need to start hashcat twice or have some other means to store the information externally that you need.
I don't think that hashcat should change anything here, it works exactly as it was designed:
1. crack only the hashes that are not yet cracked (whenever --show was not used)
2. show all hashes that were cracked whenever --show was used (and show all hashes that were not cracked when --left was used). These commands should always be run independently, not in combination with the cracking job itself.

**Comment by tankbusta** [comment]
You would still only be cracking the hashes that are not yet cracked and you would still be showing the hashes that were cracked whenever `--show` was used. The only change is that if show is specified AND there is still work to be done, that it continues with the cracking instead of just exiting.

I guess I fail to see why `--show` has to be run independently. It seems a bit silly to have to start it twice.

**Comment by philsmd** [comment]
--show was always designed to only display what was already cracked (and the user can use different --outfile-format options to modify the output).

Maybe it seems silly to you, but other users need exactly this option: e.g. display everything that was already cracked (and exit).

BTW: it is very often the case that not 100% of the hashes are cracked, so --show would always need to start cracking and that is not what it should do (therefore the name "show", it only shows what was already cracked and exits).

**Comment by tankbusta** [comment]
I guess let me ask this then, is there a way I can pull the hash(s) out of hashcat/potfile if I get `EVENT_POTFILE_ALL_CRACKED`? (Maybe `ctx->hashes`?)

**Comment by tankbusta** [comment]
Nevermind, I figured out a way to do it by looking at `potfile_handle_show`.
