### ISSUE TITLE
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by pavlinux** [hashcat/hashcat#1207]
1. Debian Linux  8.7 amd64, 
2.  AMD Opteron(tm) Processor 4386
3.  GeForce GT 740, Driver Version: 375.39

$ strace -ff -e open ./hashcat  passwd.txt 
....
open("/dev/nvidia-uvm", O_RDWR|O_CLOEXEC) = -1 EIO (Input/output error)
open("/dev/nvidia-uvm", O_RDWR)         = -1 EIO (Input/output error)
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

**Comment by philsmd** [comment]
Please provide more information:
1. did you download hashcat from https://hashcat.net/ ?
2. which version of hashcat do you use?
3. how did you install the Nvidia GPU driver ?
4. did you install the OpenCL ICD ?
etc

**Comment by jsteube** [comment]
OpenCL installation error. Please ask on forum or see here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

**Comment by cipri-tom** [comment]
just to mention, for me this issue is gone if I run as root: `sudo hashcat ...`  

[from here](https://devtalk.nvidia.com/default/topic/465288/cuda-programming-and-performance/problem-running-opencl-programs/post/3306829/#3306829)

**Comment by roycewilliams** [comment]
@pavlinux - by any chance are you running without X11 on this system?

This may be related to devices getting created on non-X11 systems. I don't know a lot about it yet, but this thread may be informative:

https://bugs.archlinux.org/task/39203

**Comment by Aspect9** [comment]
im tryna install hashcat here - not even cuda* - anyone point me in the right direction?

**Comment by anandumdas** [comment]
I didn't have graphics card and had to use OpenCL for CPU alone. I solved the error as shown here https://youtu.be/AieYqNQ6ADM

**Comment by polonskiy** [comment]
1. Download `OpenCL™ Runtime 16.1.2 for Intel® Core™ and Intel® Xeon® Processors for Red Hat* and Ubuntu* Linux* (64-bit)` from https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime
2. Extract
3. `sudo ./install.sh`
4. Next, ignore missing dependencies, finish

**Comment by Puvipavan** [comment]
@polonskiy  Yup, It's working.

**Comment by maxsxu** [comment]
@polonskiy Thanks.

And the same time I installed the below packages to avoid *Cannot find an OpenCL ICD loader library.*:
```
sudo apt install ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev
```

**Comment by bzorigt** [comment]
>     1. Download `OpenCL™ Runtime 16.1.2 for Intel® Core™ and Intel® Xeon® Processors for Red Hat* and Ubuntu* Linux* (64-bit)` from https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime
> 
>     2. Extract
> 
>     3. `sudo ./install.sh`
> 
>     4. Next, ignore missing dependencies, finish

Its working !

**Comment by entrpn** [comment]
If you don't want to register, the link. I don't know how long this link stays valid. http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz

**Comment by xkiller0** [comment]
you can fix this problem in centos by using : yum install ocl-icd + yum upgrade .
And than run sudo hashcat

**Comment by mijowe** [comment]
running on google cloud vm instance
keep getting 
Start chunk...
HC error: clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
HC error: ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

when i run  python3 agent.zip on hashtopolis they set as cpu only  please can someone help 

 less /proc/cpuinfo

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) CPU
stepping        : 7
microcode       : 0x1
cpu MHz         : 3100.192
cache size      : 25344 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa
bogomips        : 6200.38
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) CPU
stepping        : 7
microcode       : 0x1
cpu MHz         : 3100.192
cache size      : 25344 KB
physical id     : 0

lspci

00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 03)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:03.0 Non-VGA unclassified device: Red Hat, Inc. Virtio SCSI
00:04.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:05.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG

**Comment by ghost** [comment]
> I didn't have graphics card and had to use OpenCL for CPU alone. I solved the error as shown here https://youtu.be/AieYqNQ6ADM

the video is gone...

**Comment by niroop893** [comment]
I am getting the below issue for latest hashcat

Linux default 4.14.322-246.539.amzn2.x86_64 #1 SMP Wed Sep 6 22:22:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

hashcat (v6.2.5) starting

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible, HIP-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL, CUDA or HIP runtime installation.

* AMD GPUs on Linux require this driver:
  "AMD ROCm" (4.5 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)

Started: Thu Oct 12 10:53:41 2023
Stopped: Thu Oct 12 10:53:41 2023
