### ISSUE TITLE
Possible descrypt performance issue

### ISSUE THREAD

**Issue by me-scotty** [hashcat/hashcat#121]
descrypt performance appears to drop dramatically with multiple hashes (same salt)

First run: one descrypt hash (masked)
Second run: 13 descrypt hashes with the same salt

Session.Name...: all
Status.........: Running
Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
Hash.Target....: xxxxxxxxxxxxx  
Hash.Type......: descrypt, DES(Unix), Traditional DES
Time.Started...: Tue Jan 12 15:37:35 2016 (6 secs)
Time.Estimated.: Fri Jan 29 11:19:59 2016 (16 days, 19 hours)
Speed.GPU.#1...: 76175.5 kH/s
Speed.GPU.#2...: 76185.9 kH/s
Speed.GPU.#*...:   152.4 MH/s
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 1019215872/218340105584896 (0.00%)
Rejected.......: 0/1019215872 (0.00%)
Restore.Point..: 0/916132832 (0.00%)
HWMon.GPU.#1...: 98% Util, 51c Temp, 90% Fan
HWMon.GPU.#2...: 98% Util, 50c Temp, 30% Fan

Session.Name...: all
Status.........: Running
Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
Hash.Target....: File (C:\descrypt(x13).txt)
Hash.Type......: descrypt, DES(Unix), Traditional DES
Time.Started...: Tue Jan 12 15:35:29 2016 (8 secs)
Time.Estimated.: Wed Apr 06 15:14:53 2016 (84 days, 22 hours)
Speed.GPU.#1...: 15133.2 kH/s
Speed.GPU.#2...: 15144.5 kH/s
Speed.GPU.#*...: 30277.7 kH/s
Recovered......: 0/13 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 251658240/218340105584896 (0.00%)
Rejected.......: 0/251658240 (0.00%)
Restore.Point..: 0/916132832 (0.00%)
HWMon.GPU.#1...: 99% Util, 57c Temp, 82% Fan
HWMon.GPU.#2...: 99% Util, 56c Temp, 30% Fan

**Comment by jsteube** [comment]
I've tried to reproduce on my 750Ti but can not:

1 hash: 162.7 MH/s
15 hashes: 147.0 MH/s

Is this with beta38 ?

**Comment by me-scotty** [comment]
HD6990 on v2.01

Perhaps this is an AMD thing?
Or fixed in beta?

Really good news that NVidia okay.
Past time that I updated anyways...

Many thanks.

**Comment by jsteube** [comment]
Yes, please retry with the latest beta from https://hashcat.net/beta/

**Comment by me-scotty** [comment]
It's nice to be able to try current beta (alpha really) - to see what you guys are up to.
Anybody who does should understand that this is a work-in-progress.
So...

Exact same launch parameters as above.
With this hardware at least, system becomes barely responsive.
And temp control problems - didn't settle down until MSI Afterburner launched.

But now single salt performance nearly the same.
The bad news is that both are a fraction of the previous performance.

Note below that utilization shows 0%, but system response acts like 100%

---

oclHashcat-2.10b44.7z

oclHashcat v2.10 starting...

Device #1: skipped
Device #2: Cayman, 512/2048 MB allocatable, 880Mhz, 24MCU
Device #3: Cayman, 512/2048 MB allocatable, 880Mhz, 24MCU
Device #4: skipped

Hashes: 13 hashes; 13 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Precompute-Final-Permutation
- Not-Iterated
- Single-Salt
- Brute-Force
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 80c

Device #1: Kernel C:\utils\unix-utils\usr\local\console\oclHashcat-2.10beta/OpenCL/m01500_a3.cl (128532 bytes)
Device #1: Kernel C:\utils\unix-utils\usr\local\console\oclHashcat-2.10beta/kernels/markov_le.13581e63.kernel (44956 bytes)
Device #2: Kernel C:\utils\unix-utils\usr\local\console\oclHashcat-2.10beta/OpenCL/m01500_a3.cl (128532 bytes)
Device #2: Kernel C:\utils\unix-utils\usr\local\console\oclHashcat-2.10beta/kernels/markov_le.13581e63.kernel (44956 bytes)

Session.Name...: all
Status.........: Running
Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
Hash.Target....: xxxxxxxxxxxxx
Hash.Type......: descrypt, DES(Unix), Traditional DES
Time.Started...: Wed Jan 13 15:24:39 2016 (1 min, 49 secs)
Time.Estimated.: Fri Oct 20 00:11:34 2017 (1 year, 280 days)
Speed.Dev.#1...:  2186.9 kH/s
Speed.Dev.#2...:  2187.1 kH/s
Speed.Dev.#*...:  4374.1 kH/s
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 427819008/218340105584896 (0.00%)
Rejected.......: 0/427819008 (0.00%)
Restore.Point..: 0/916132832 (0.00%)
HWMon.GPU.#1...:  0% Util, 58c Temp, 69% Fan
HWMon.GPU.#2...:  0% Util, 61c Temp, 30% Fan

Session.Name...: all
Status.........: Running
Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
Hash.Target....: File (C:\xxx
Hash.Type......: descrypt, DES(Unix), Traditional DES
Time.Started...: Wed Jan 13 15:29:20 2016 (20 secs)
Time.Estimated.: Fri Apr 06 19:50:01 2018 (2 years, 84 days)
Speed.Dev.#1...:  1763.8 kH/s
Speed.Dev.#2...:  1763.6 kH/s
Speed.Dev.#*...:  3527.5 kH/s
Recovered......: 0/13 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 62914560/218340105584896 (0.00%)
Rejected.......: 0/62914560 (0.00%)
Restore.Point..: 0/916132832 (0.00%)
HWMon.GPU.#1...:  0% Util, 54c Temp, 69% Fan
HWMon.GPU.#2...:  0% Util, 53c Temp, 30% Fan

**Comment by jsteube** [comment]
OK, the performance problem seems to be fixed. If there's some new error please open a new issue. 1 error = 1 issue, It's much easier this way.
