### ISSUE TITLE
custom charsets with special characters don't work.

### ISSUE THREAD

**Issue by nmxhc** [hashcat/hashcat#1210]
Hi, 
I've experienced a kind of bug that I didn't find in any other issue:

When you supply a special character to your custom charset, it acts in unexpected ways:
This gives me the status exhausted:
`./hashcat64.bin --potfile-disable -a 3 -m 0 -1 ä (INSERT HERE HASH OF GERMAN LOWERCASE ä) ?1`

Whereas the same custom set used as mask twice gives the status cracked, althoug I took the hash of one letter:
`./hashcat64.bin --potfile-disable -a 3 -m 0 -1 ä (INSERT HERE HASH OF GERMAN LOWERCASE ä) ?1?1`

The same with the letter a works fine as well as the usage of ?l for the hash of a.
Using charsets/standard/German/ANYTHING didn't work.

I can supply the script I used for checking if it helps you, but there are the hashs of ä and a in it and I read that you don't like publishing any hashes.

I'm working on a current Ubuntu Gnome 16.10 with Intel OpenCL-Drivers that are a few (?) weeks old.
EDIT: I'm working with the current stable hashcat 3.40.

Can I supply any other helpful information for you?

Thanks for your effort.
Nmxhc

**Comment by philsmd** [comment]
hashcat works on a byte-by-byte password length. Each position/char within your mask also determines the bytes that should be tried on that specific position.

Unfortunately, this is exactly how encoding works (and yeah, sometimes encoding is a little bit counter-intuitive:
```
echo -n ä | xxd -p
c3a4
```
2 bytes -> a mask of length 2

I don't think hashcat can and should do something here, because this is exactly how encoding works.
It's just a little bit confusing if users think their "char is of length 1" while it is not at all.

**Comment by nmxhc** [comment]
Thanks for your confimation. This is, what I already expected. 
>  Using charsets/standard/German/ANYTHING didn't work.

However, how can I work with something like
`./hashcat64.bin --potfile-disable -a 3 -m 0 -1 charsets/standard/German/de_ISO-8859-1.hcchr (HASH OF GERMAN ä) ?1`

None of the German charset-files with either ?1 or ?1?1 has cracked my string.

**Comment by philsmd** [comment]
ISO-8859-1 is not the same as UTF8

Different encoding also (could) imply different bytes (even for the same "character").
That's why the hex char 0xe4 in ISO-8859-1 and 0xc3a4 in UTF8 both represent the "ä" character, but the hash of those bytes of course is different.

**Comment by nmxhc** [comment]
So how do I attack such a hash? Try to find out the encoding and then work with this encoding? Is there any way in hashcat to use UTF8 inbuilt / self-built charsets (files) as encoding, as that is probably what I'm looking for.

**Comment by philsmd** [comment]
UTF8 encoding is the most common, straightforward to use and therefore there are no special charset files. You can always just convert the charset files with something like iconv (or similar software):

```
iconv -f ISO-8859-1 -t UTF-8 charsets/combined/German.hcchr > German-UTF8.hcchr
```

... but keep in mind that different encoding could also imply different lengths for the same symbol/character, so you need to increase the mask length accordingly (or use --increment and a mask that is long enough).

**Comment by jsteube** [comment]
I think @philsmd explained what to do. Since it turned out to be a usage issue and not a bug, please continue the discussion on hashcat forum. Github issues is only for bugs and feature requests.
