### ISSUE TITLE
Implement a signal handler to perform standard UI actions

### ISSUE THREAD

**Issue by tautology0** [hashcat/hashcat#1211]
At the moment it's painful to try and run hashcat as a separate process, as you need to tie into both stdin/stdout upon process initiation.

What would make it easier would be for hashcat to implement a signal handler to allow the basic actions to be performed without the mankiness of using stdin.

E.g. mapping SIGUSR1 to status[1], SIGTERM to pause, SIGCONT to resume, SIGUSR2 to checkpoint, SIGINT to quit

[1] SIGINFO would be better, but it's a BSDism

**Comment by jsteube** [comment]
Why run hashcat as binary, call the library instead.

**Comment by tautology0** [comment]
Good idea; except that the only mention of a library is in the release notes for 3.20 and there's no documentation (that I can find from searching the wiki, the forum and github).

So should I raise a new issue asking for documentation of libhashcat?

**Comment by jsteube** [comment]
There's no documentation in text form, but there's two examples in code. The first one that the hashcat binary itself is using the library, therefore everything the binary can do can be done from your application, too. See the main.c file for details and set the SHARED variable in Makefile. The other example is pyhashcat here: https://github.com/Rich5/pyHashcat

**Comment by tautology0** [comment]
Thanks; I've been working my way through pyhashcat this morning.
