### ISSUE TITLE
Segmentation fault when running oclHashcat

### ISSUE THREAD

**Issue by mrpeppels** [hashcat/hashcat#1212]
Hi,
Just installed via apt-get on Debian 4.9.6-3kali2 (2017-01-30), on every run of oclHashcat I get a segfault, even when running with no parameters. Any ideas? If more info is needed i'm happy to help.

(gdb) run
Starting program: /usr/bin/oclhashcat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
32      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.

**Comment by philsmd** [comment]
1. oclHashcat was superseded with just "hashcat" a long time ago (years!!!), please do not use oclHashcat (or at least do not use it if you want to report bugs)
2. Kali linux unfortunately does everything wrong when it comes to packaging "hashcat", it uses completely incorrect dependencies etc
3. you should first make sure that you have the correct OpenCL driver (and ICD) installed for your OpenCL devices, see the recommendations on https://hashcat.net, and after that download hashcat from https://hashcat.net/hashcat/ (version 3.40 or above)
4. yeah, problems with drivers/setup/installations could result in "crashes", even if hashcat has nothing to do with them... the drivers might just not work correctly
5. make sure that neither Mesa, nor pocl is installed (they often cause "crashes")
6. if you want to debug something with hashcat, you need to compile it like this: make clean; git pull; make DEBUG=1; gdb --args hashcat -b

My guess is, that this has nothing to do with hashcat itself, it is just your installation that was not correctly configured/installed (including the hashcat version - always use the newest version - and the correct driver).

BTW: it would also help a lot if you mention which OpenCL device(s) you have (the hardware) to reduce the amount of possible point of failures (at least a little bit)

**Comment by mrpeppels** [comment]
Apologies, I wasnt too thorough:)
