### ISSUE TITLE
make clean is dangerous

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#1218]
I'm writing this as an issue instead of a patch because we might disagree.

In my humble opinion, `make clean` should **absolutely not** destroy any pot files or session files. Instead, they should be listed in .gitignore so they don't turn up in eg. `git status` or accidentally get added in a commit.

If you really want to, you could have an alternative target `make distclean` that actually does destroy such files, but in the world of git it's not really needed. For example, you'd better create archives (eg. zip files) using `git archive` instead of a "manual" zip command. The former will never include anything not actually in the git tree.

**Comment by jsteube** [comment]
OK, we should do that
