### ISSUE TITLE
Hybrid Attack Issue

### ISSUE THREAD

**Issue by redbluebg** [hashcat/hashcat#1220]
Hello,

When I do a Hybrid attack with the following parameters on a GPU card:

hashcat64 -D 2 -a 6 -m 11300 wallet.hash.dos dictionary.dict.txt -1 ?a?a?a?a?a

I get speed close to 1 H per 10 seconds.

When I do the same attack with a pipe combined with maskprocessor:

mp64.exe dictionaryword?a?a?a?a?a | ./hashcat64 -D 2 -a 0 -m 11300 wallet.hash.dos

I get full speed of the GPU arround 4000 H/s

Can you please advice?

Greetings,
redbluebg

**Comment by philsmd** [comment]
What do you mean with this:
`
-1 ?a?a?a?a?a
`
?

--custom-charset1 (or short -1) is used to define custom charsets.

I think this is pebcak because you are mixing up custom charsets with masks

**Comment by redbluebg** [comment]
I'm sorry

The actual command that I execute is that:

hashcat64 -D 2 -a 6 -m 11300 wallet.hash.dos dictionary.dict.txt ?a?a?a

![image](https://cloud.githubusercontent.com/assets/26966436/24757603/5d47ed90-1ae8-11e7-9e8c-86370a088372.png)

**Comment by jsteube** [comment]
Just make the wordlist larger and you will get full speed. If you want to stick to a small wordlist you need to pipe, like:

hashcat64 -a 6 dictionary.dict.txt ?a?a?a --stdout | hashcat64 -D 2 -m 11300 wallet.hash.dos  --status --status-timer 1
