### ISSUE TITLE
wpa feature request --nonce-error-corrections also on big endian

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1221]
currently  "--nonce-error-corrections"  only works on litle endian nonces.
There are many devices that uses big endian.
Please add big endian nonce error corrections.

Best regards
Mike

**Comment by philsmd** [comment]
Can you please describe it a little bit better what needs to be done (in your opinion)?

Do we need to make changes to the .hccapx structure (again)?

Do we have this type of information somewhere ? I think the .cap file could know if the devices are using little/big endian, or? ... or do we always need to perform both, little and big endian brute-force?
Thx
