### ISSUE TITLE
WPA2 reduce the password length

### ISSUE THREAD

**Issue by XxoraxX** [hashcat/hashcat#1222]
Is there a way to modify the source code so hachcat accept wpa2 password less the 8 length or which code responsible for this option  

Thanks

**Comment by neheb** [comment]
Why

**Comment by XxoraxX** [comment]
If im using wordlist + rule attack on wpa2  i need to make the wordlist contain password with 8 length 
if the password is less then 8 will not be used in cracking hashcat will search in wordlist for password min-len 8 and use it to crack the handshake 
if i have password like (google) hachcat will not use it for cracking but i know that wpa/wpa2 use 8 length password so i want to use the rule to add for me the renaming length (exp : google?d?d?d?d google2017)
but its not working because when hashcat detect that the password less then 8 will ignore the pass and use password with 8 length .
 I tried to search for option in hashcat and online but i did not find .

**Comment by neheb** [comment]
You could work around that issue by using a pipe. eg.

combinator wordlist.dict 4digits.dict | hashcat -a 0 ...

**Comment by roycewilliams** [comment]
Something doesn't sound right. @XxoraxX, could you post your command line (with hashes redacted), including any errors that hashcat produces?

**Comment by philsmd** [comment]
This is not really a bug but just a known limitation (or let's call it optimization?).... and it has to do with how/when the final length of the password candidate is known and when it can be rejected... in most of the cases (with fast hashes) the final length is only known very late (when we speak about the GPU-based rule engine etc)... therefore the host can't really know the final length. Therefore every password from the dictionary that doesn't meet the min/max length will be rejected as soon as possible. This is true also for slow hashes.

You have 2 options:

- use -j/-k (with single rules, not rule files!)
- use a pipe and an external tool like e.g. from hashcat-utils (or hashcat itself, e.g. hashcat --stdout -a 6 dict.txt ?d?d?d?d | hashcat -m 2500 -a 0 -w 4 --status --status-timer 10 a.hccapx)

BTW: this is a question that was answered dozens of times on the hashcat forum... please use the search function of the hashcat forum next time
