### ISSUE TITLE
Ethereum KDF - PBKDF2-SHA256

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1227]
New algorithm: Ethereum PBKDF2-SHA256

Use: Currently in use by Ethereum wallets to secure the wallet encryption password.

The algorithm design is explained very well here: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

To quote from that page:

All such files have an associated password. To derive a given `.json` file's secret key, first derive the file's encryption key; this is done through taking the file's password and passing it through a key derivation function as described by the `kdf` key. KDF-dependent static and dynamic parameters to the KDF function are described in `kdfparams` key.

PBKDF2 must be supported by all minimally-compliant implementations, denoted though:

- `kdf`: `pbkdf2`

For PBKDF2, the `kdfparams` include:

- `prf`: Must be `hmac-sha256` (may be extended in the future);
- `c`: number of iterations;
- `salt`: salt passed to PBKDF;
- `dklen`: length for the derived key. Must be >= 32.

Once the file's key has been derived, it should be verified through the derivation of the MAC. The MAC should be calculated as the SHA3 (keccak-256) hash of the byte array formed as the concatenations of the second-leftmost 16 bytes of the derived key with the `ciphertext` key's contents, i.e.:

```
KECCAK(DK[16..31] ++ <ciphertext>)
```

(where `++` is the concatenation operator)

This value should be compared to the contents of the `mac` key; if they are different, an alternative password should be requested (or the operation cancelled).

To summarize, the password is hashed with PBKDF2-SHA256, then the "second leftmost 16 bytes" of the derived hash are concatenated with the ciphertext, which is then hashed with SHA3-256. The SHA3-256 hash is then directly compared to the "mac" value to verify whether or not the password is correct. If the SHA3 hashes match, the password is correct and the decryption of the ciphertext/wallet proceeds.

The page linked above includes this example of a valid wallet:password pair:

## Test Vectors

Details:

- Address: `008aeeda4d805471df9b2a5b0f38a0c3bcba786b`
- ICAP: `XE542A5PZHH8PYIZUBEJEO0MFWRAPPIL67`
- UUID: `3198bc9c-6672-5ab3-d9954942343ae5b6`
- Password: `testpassword`
- Secret: `7a28b5ba57c53603b0b07b56bba752f7784bf506fa95edc395f5cf6c7514fe9d`

### PBKDF2-SHA-256

Test vector using AES-128-CTR and PBKDF2-SHA-256:

File contents of `~/.web3/keystore/3198bc9c-6672-5ab3-d9954942343ae5b6.json`:
```json
{
    "crypto" : {
        "cipher" : "aes-128-ctr",
        "cipherparams" : {
            "iv" : "6087dab2f9fdbbfaddc31a909735c1e6"
        },
        "ciphertext" : "5318b4d5bcd28de64ee5559e671353e16f075ecae9f99c7a79a38af5f869aa46",
        "kdf" : "pbkdf2",
        "kdfparams" : {
            "c" : 262144,
            "dklen" : 32,
            "prf" : "hmac-sha256",
            "salt" : "ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd"
        },
        "mac" : "517ead924a9d0dc3124507e3393d175ce3ff7c1e96529c6c555ce9e51205e9b2"
    },
    "id" : "3198bc9c-6672-5ab3-d995-4942343ae5b6",
    "version" : 3
}
```

Intermediates:

- Derived key: `f06d69cdc7da0faffb1008270bca38f5e31891a3a773950e6d0fea48a7188551`
- MAC Body: `e31891a3a773950e6d0fea48a71885515318b4d5bcd28de64ee5559e671353e16f075ecae9f99c7a79a38af5f869aa46`
- MAC `517ead924a9d0dc3124507e3393d175ce3ff7c1e96529c6c555ce9e51205e9b2`
- Cipher key: `f06d69cdc7da0faffb1008270bca38f5`

I have written [ether2hashcat](https://github.com/magnumripper/JohnTheRipper/pull/2525) to extract the relevant information from the json blobs and present it in a proposed hash format for hashcat. The proposed format would be as follows:

` $ethereum$p*iter*salt*mac*ciphertext`

Using the example data from the test wallet above, we would get the following hash:

`$ethereum$p*262144*ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd*517ead924a9d0dc3124507e3393d175ce3ff7c1e96529c6c555ce9e51205e9b2*5318b4d5bcd28de64ee5559e671353e16f075ecae9f99c7a79a38af5f869aa46`

This would be cracked as `testpassword`

Because there are multiple KDF variations, one using PBKDF2 and one using Scrypt, the format includes a P or S to denote the different versions. The Scrypt variant is addressed in a separate issue, as it is technically a different algorithm.

Both algorithms were previously discussed on [this forum thread](https://hashcat.net/forum/thread-6405.html) and example code for cracking both algorithms was written by @philsmd 

This was previously requested in issue #262, however that issue/request did not seem to be completed with the required information.

**Comment by jsteube** [comment]
I was playing a bit with the data you provided. Some notes:

* The example hash "$ethereum$p*262144*ae3cd4e7013836..." provided does not crack with password "testpassword", at least not with JtR's mode (latest github master).
* The AES part is not needed at all, neither in PBKDF2 nor in SCRYPT mode
* We will need to rewrite the keccak GPU implementation to get this to work
* By assuming the keccak part will be so fast that it doesn't change the cracking speed, the only relevant slowdown is the PBKDF2. I've tested this to run to approx. 4430 H/s on a single GTX1080

**Comment by kholia** [comment]
@jsteube 

The following hash is not correct,

`$ethereum$p*262144*ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd*517ead924a9d0dc3124507e3393d175ce3ff7c1e96529c6c555ce9e51205e9b2*5318b4d5bcd28de64ee5559e671353e16f075ecae9f99c7a79a38af5f869aa46`

It should be,

`$ethereum$p*262144*ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd*5318b4d5bcd28de64ee5559e671353e16f075ecae9f99c7a79a38af5f869aa46*517ead924a9d0dc3124507e3393d175ce3ff7c1e96529c6c555ce9e51205e9b2`

The last two fields are reversed in the first copy of the hash. This is why you couldn't crack it.

https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/ethereum2john.py generates the correct hash which cracks just fine with JtR.

**Comment by Chick3nman** [comment]
Sorry, I had noticed CT and Mac were swapped in your script and forgot to update the examples. They we're generated with my original script, which is no longer the correct format.
