### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE in m02500.cl with Intel CPU

### ISSUE THREAD

**Issue by alphabt** [hashcat/hashcat#1229]
Might be a regression from https://github.com/hashcat/hashcat/commit/26949a4fce572d4699ae32b48c93ec2bf0288e42 since that commit added `t = swap32 (t);` to m02500.cl:894,898

    $ hashcat -b -m 2500 -D1
    hashcat (v3.5.0-15-g26a34533+) starting in benchmark mode...
    
    OpenCL Platform #1: Apple
    =========================
    * Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, 4096/16384 MB allocatable, 8MCU
    * Device #2: Iris Pro, skipped.
    * Device #3: GeForce GT 750M, skipped.
    
    Hashtype: WPA/WPA2
    
    clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
    
    <program source>:894:7: error: assigning to 'u32' (aka 'unsigned int') from incompatible type 'u32x' (aka '__uint4')
        t = swap32 (t);
          ^ ~~~~~~~~~~
    <program source>:898:7: error: assigning to 'u32' (aka 'unsigned int') from incompatible type 'u32x' (aka '__uint4')
        t = swap32 (t);
          ^ ~~~~~~~~~~
    
    * Device #1: Kernel /Users/<user>/hashcat/OpenCL/m02500.cl build failed - proceeding without this device.

**Comment by jsteube** [comment]
Should be fixed with commit https://github.com/hashcat/hashcat/commit/a93a143d1e2820e2fae5da11e4a9b3292d09e690

Please close if fixed. Thanks for reporting!

**Comment by alphabt** [comment]
Confirmed fixed. Thanks for the quick turnaround!
