### ISSUE TITLE
Hashcat fails to work at all on the Inspiron 1545.

### ISSUE THREAD

**Issue by AraHaan** [hashcat/hashcat#1230]
I am using an Inspiron 1545 and it has windows 7 ultimate SP1 Build 7601 installed, However it has the GM45 graphics and so as such the following probably does not apply:

```
Cannot find an OpenCL ICD loader library.

You are probably missing the native OpenCL runtime or driver for your platform.

* AMD GPUs on Windows require this runtime and/or driver:
  "AMD Radeon Software Crimson Edition" (15.12 or later)
* Intel CPUs require this runtime and/or driver:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* Intel GPUs on Windows require this runtime and/or driver:
  "OpenCL Driver for Intel Iris and Intel HD Graphics"
* NVIDIA GPUs require this runtime and/or driver:
  "NVIDIA Driver" (367.x or later)
```

Also the CPU I this I personally switched out the T3400 (2.17 GHz per core, 2) with an P8800 (2.66 GHz per core, 2).

I am currently not sure on what to do rn.

Also I do suggest bute force + mask as well in case something would need both algorithms at the same time.

**Comment by roycewilliams** [comment]
This is really more a question for the hashcat forums.

Your question isn't really whether this GPU is supported by hashcat, so much as whether there is OpenCL available for the GM45. From a brief search, it looks to me like there is no OpenCL for this chip. OpenCL is required for modern (GPU-based) hashcat. You can still use [hashcat-legacy](https://github.com/hashcat/hashcat-legacy/releases) on CPU.

**Comment by jsteube** [comment]
As @roycewilliams explained, this is a question for hashcat forums.
