### ISSUE TITLE
Mode 9820 misbehaving

### ISSUE THREAD

**Issue by recon-ng** [hashcat/hashcat#1232]
Hi, I'm running hashcat 3.5.0 on a fully-updated OpenSUSE 42.2 instance.

Command: ./hashcat -m 9820 -a 3 hashes.rc4 ?a?a?a?a?a?a?a -o /home/user/myfile.txt

The hash is of type oldoffice3

(I have already completed the 9810 step)

In this case hashcat never detects that it has found a collision, even though the output file will be updated with collisions. Repeated runs with a different mask exhibit the same behavior. Only upon a subsequent launch of the regular 9800 mode on the original (without RC4) hash does hashcat claim that "all hashes were found in potfile". 

UPDATE: I have tested several of the reported valid collisions but none unlock the file in question.

**Comment by jsteube** [comment]
Yes that's a feature, it's actually the only feature why there's 9820 at all. The goal is to find as many colliding passwords as possible to use them for reuse cases. That's why it's never stopping once it has found a collision. I think what you're looking for is simply -m 9800

**Comment by recon-ng** [comment]
Thanks. I'll just assume the collisions aren't opening the file because it's corrupted... although a bruteforce did yield a password that successfully unlocked it.
