### ISSUE TITLE
Consider dropping early-reject padding checks in 7z format.

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#1239]
See https://github.com/philsmd/7z2hashcat/issues/12

It's not clear why that particular sample doesn't have "correct" zero padding but until we know better I just dropped the padding checks in JtR. Performance wasn't hurt much, but it will be if many 7z hashes are loaded at once (because we can re-use the KDF for all of them but this means the time for doing AES/LZMA for each will become significant).

Sample was sent to us in private, @philsmd has a copy.

**Comment by jsteube** [comment]
@magnumripper do you know how to reproduce such an archive locally? How much was the speed drop?

**Comment by magnumripper** [comment]
The only archive I've seen is the non-public one we got from a user. Phil can send it to you (or I can). The performance drop is insignificant except for the case of attacking a lot of hashes at once (because we can re-use the KDF, but not the AES and verify, for each "salt" - are you doing that in hashcat too?).

**Comment by philsmd** [comment]
it would be very great and helpful in the decision making if we discover some way on how .7z files like this can be generated (i.e. with a tool/archiver or sdk etc) and how wide-spread/rare they are. Maybe even more details like if the padding is really random or not... I'm just curious about why one tool/generator is using non-default padding (maybe it was even designed like this to circumvent cracking by jtr and hashcat, that would be funny or it has something to do with antivirus signature bypassing: "let's use random bytes within the AES padding, such that the sha checksums are arbitrary for each malicious file" etc)

I agree, that especially with the standard cost of 2^19 of .7z, the final fast "verify part" (including aes+lzma+crc32) doesn't make much of a (speed) difference.

**Comment by jsteube** [comment]
If there's no other disadvantage caused by this, we can drop the
early-reject based on the padding

**Comment by solardiz** [comment]
> If there's no other disadvantage caused by this, we can drop the early-reject based on the padding

Apparently, there was - false positives, as reported in 2023 in https://github.com/openwall/john/issues/5228

In JtR, we have the `TrustPadding` setting in `john.conf`, which is currently enabled by default (so should suppress those false positives by default, but will not crack that one private archive from 2017 mentioned in here).

We did not investigate those false positives fully, and do not have a copy of the archive where they're seen, but @fred913 may still have it.
