### ISSUE TITLE
When setting custom character sets, ?[l|d|u|s|b] is treated as a path

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1240]
When running a mask attack in hashcat with a custom character set defined, a file with a 2 letter name in the same folder will be called if the second letter is any of the predfined character sets(?l?u?d?s?b), instead of the correct character set.

Running the example command below
```
hashcat64.exe -m 3 -m 0 example0.hash -1 ?l ?1?1?1?1?1
```
While there is a file with any 2 letter name ending in "l" in the same directory, such as "pl", will yeild the following error:

`pl: Custom charset file is too large.`

It seems that hashcat is calling the file "pl" as a custom characterset file instead of using the predefined characterset "?l" in this case. Removing or renaming the file will clear the error and the attack will launch as expected, with ?1 set to ?l. This is present with all of the default character sets in hashcat 3.5.0. OS is Windows 7 x64.

**Comment by DoZ10** [comment]
Hi,

are you sure this isn't shell specific ? By that, I mean that '?' is interpreted by the command line as a wildcard. Try escape the question mark with a "\\".

**Comment by DoZ10** [comment]
Just reproduced your problem on Ubuntu with a file called "dl". Look at the output of _strace_ utility:

```
UBUNTU:~/dev/hashcat$ strace ./hashcat -a 3 -m 0 example0.hash -1 ?l ?1?1?1?1?1
execve("./hashcat", ["./hashcat", "-a", "3", "-m", "0", "example0.hash", "-1", "dl", "?1?1?1?1?1"], [/* 65 vars */]) = 0
brk(NULL)                               = 0x250b000
```

One of the arguments is "dl" and not "?l" so it was interpreted by bash and not hashcat.

Sorry, there is no fix for this^^

**Comment by Chick3nman** [comment]
Interesting, that does seem like an issue with the shell and not hashcat. I'll play with surrounding things in quotes and escaping things to see if i can come up with something that works.

**Comment by magnumripper** [comment]
It sure is shell wildcard expansion. I never saw that, it's a bit amusing. One workaround is to just wrap the mask in quotes. There's no way to fix this in hashcat as it happens even before hashcat starts. Try changing "hashcat" to "echo" and you'll see what happens.

```
$ touch al bl cl

$ echo -m 3 -m 0 example0.hash -1 ?l ?1?1?1?1?1
-m 3 -m 0 example0.hash -1 al bl cl ?1?1?1?1?1

$ echo -m 3 -m 0 example0.hash -1 "?l" ?1?1?1?1?1
-m 3 -m 0 example0.hash -1 ?l ?1?1?1?1?1
```

**Comment by magnumripper** [comment]
BTW another workaround is to use long option `--custom-charset1=?l`
```
$ touch al bl cl

$ echo -m 3 -m 0 example0.hash --custom-charset1=?l ?1?1?1?1?1
-m 3 -m 0 example0.hash --custom-charset1=?l ?1?1?1?1?1
```

**Comment by Chick3nman** [comment]
Huh, that's weird. I guess it's just something we'll need to work around during usage. I'll go ahead and close this as it's not a hashcat issue however I do think it could use some visibility so that others arent confused when they run across it. It caught me completely by surprise when testing a list earlier.
