### ISSUE TITLE
hashcat3.5 graphics4600 Display driver crashes

### ISSUE THREAD

**Issue by liyuefeng** [hashcat/hashcat#1241]
hello everthing master, my envirment is windows7 64bit  user hashcat3.5 when i use :hashcat64 --force -m 0 -a 3 --custom-charset1 ?l?d d:\test.txt ?1?1?1  my display is stop  this https://github.com/hashcat/hashcat/issues/191 can not anwser my question  this https://hashcat.net/wiki/doku.php?id=timeout_patch can not too

**Comment by liyuefeng** [comment]
com here everyone

**Comment by jsteube** [comment]
Make sure to have hashcat and your display driver in the latest version, then it should work.
