### ISSUE TITLE
When using hybrid mode (6), masks and dictionaries in the folder do not combine properly

### ISSUE THREAD

**Issue by satmonkey** [hashcat/hashcat#1244]
Ubuntu 16,04 x64
NVidia 375.39
hashcat-3.5.0+76
./hashcat64.bin -m 400 wp_400_002.hash -a6 ../wordlist/base masks/monkey-16.hcmask
The error: masks and files are not fully combined. Only the last file in the folder ( ../wordlist/base) is fully combined with all masks. Possibly, all modes using dictionary are affected.
[test.zip](https://github.com/hashcat/hashcat/files/996864/test.zip)

**Comment by mhasbini** [comment]
@satmonkey Can you please reproduce the bug with a small dataset and attach them ?

**Comment by satmonkey** [comment]
No problem, see attached.
[test_log.zip](https://github.com/hashcat/hashcat/files/999608/test_log.zip)
[test.zip](https://github.com/hashcat/hashcat/files/999609/test.zip)
This is the dirty fix, which works for me:

*** hashcat.c	2017-05-13 09:23:17.311735018 +0200
--- hashcat.c.bak	2017-05-13 09:20:56.119833768 +0200
***************
*** 357,363 ****
  
    if (straight_ctx->dicts_cnt)
    {
!     for (u32 dicts_pos = straight_ctx->dicts_pos = 0; dicts_pos < straight_ctx->dicts_cnt; dicts_pos++)
      {
        straight_ctx->dicts_pos = dicts_pos;
  
--- 357,363 ----
  
    if (straight_ctx->dicts_cnt)
    {
!     for (u32 dicts_pos = straight_ctx->dicts_pos; dicts_pos < straight_ctx->dicts_cnt; dicts_pos++)
      {
        straight_ctx->dicts_pos = dicts_pos;

**Comment by mhasbini** [comment]
@satmonkey Can you please add the command you are using with the mask, the expected and actual behaviour?

**Comment by satmonkey** [comment]
The particular command for the test you asked for:
./hashcat64.bin.ori -m 400 wp_400_002.hash -a6 ../wordlist/test masks/monkey-16.hcmask
I expect all wordlists in the folder (../wordlists/test) will be combined with all masks in the file monkey-16.hcmask. In other words, the hcmask file will be applied to every file in that folder.
And the actual behaviour I described initially. In addition, see the log what is happening.
