### ISSUE TITLE
Different behaviour for some rules with input of length 32 between host & GPU mode 

### ISSUE THREAD

**Issue by mhasbini** [hashcat/hashcat#1246]
Examples:

- rule `@`:

```
$ echo '123456790abcdefghijklmnopqrstuvw' | ./hashcat --stdout -j '@a'
123456790bcdefghijklmnopqrstuvw
$ echo '123456790abcdefghijklmnopqrstuvw' | ./hashcat --stdout -r <(echo '@a')
$
```

- rule '4

```
$ echo '123456790abcdefghijklmnopqrstuvw' | ./hashcat --stdout -j "'4"
1234
$ echo '123456790abcdefghijklmnopqrstuvw' | ./hashcat --stdout -r <(echo "'4")
$
```

Same behaviour for `D`, `O`, `Y`, `[`, `]`, `x` and `y` rules:

host mode: rule executed correctly.
GPU mode: blank response.

Other shared rules have consistent behaviour between both modes: blank response.

Is this an expected behaviour ?

**Comment by DoZ10** [comment]
I noticed a similar problem for some algorithms in GPU mode with input legnth 32 bytes. Problem was mentionned in my current PR, but not addressed yet... it might be related... here's a copy.

```
Okay I found what is the problematic code, but I'm not sure if this is some "desired" behavior.

The pw_max is overriden to 31 in straight.c at function straight_ctx_init see below:

[...]

const bool has_noop = kernel_rules_has_noop (straight_ctx->kernel_rules_buf, straight_ctx->kernel_rules_cnt);

  if (has_noop == false)
  {
    switch (user_options_extra->attack_kern)
    {
      case ATTACK_KERN_STRAIGHT:  if (pw_max > PW_DICTMAX) pw_max = PW_DICTMAX;
                                  break;
      case ATTACK_KERN_COMBI:     if (pw_max > PW_DICTMAX) pw_max = PW_DICTMAX;
                                  break;
    }
  }
  else
  {
    if (hashconfig->attack_exec == ATTACK_EXEC_INSIDE_KERNEL)
    {
      switch (user_options_extra->attack_kern)
      {
        case ATTACK_KERN_STRAIGHT:  if (pw_max > PW_DICTMAX) pw_max = PW_DICTMAX;
                                    break;
        case ATTACK_KERN_COMBI:     if (pw_max > PW_DICTMAX) pw_max = PW_DICTMAX;
                                    break;
      }
    }
    else
    {
      // in this case we can process > 32
    }
  }

ATTACK_EXEC_INSIDE_KERNEL is set for my hash mode 670 and has_noop is true.

What was the original intent from this code ? Since it now seem to conflict with modes that permits pw > 31, I am not sure if we should use a workaround by selecting different configuration options or figure out a patch.
```

**Comment by DoZ10** [comment]
So the question to @jsteube is if there is some design requirements for inputs over 31 bytes to be ignored in GPU ?

**Comment by jsteube** [comment]
Yes, there is, since hashcat can optimize the addition of the 0x80 stopbit by simply adding it to each word in the wordlist. This save the branch in the innerloop of the kernel

**Comment by jsteube** [comment]
I've noticed there's fundamental different that should be added to test_rules.pl. That is simply the fact that rules never get rejected on GPU. For example this:

input: test
rule: '6
expected CPU: 
expected GPU: test

Also I'd suggest to remove all checks that use rules that are not supported on GPU (reason here is the above reason) like /, <, >, etc

**Comment by mhasbini** [comment]
@jsteube 

Your proposed format look cleaner :+1:
What do you think about the format bellow?

Shared rules:

```
'6:
    input: ...
    expected_host: ...
    expected_gpu: ...
```

CPU rules:

```
/e:
    input: ...
    expected_host: ...
```

>Also I'd suggest to remove all checks that use rules that are not supported on GPU (reason here is the above reason) like /, <, >, etc

I'm was adding `mode: 1` for the cases that should run only on host. Maybe this won't be necessary with  the proposed format.
I was basing on the assumption that a rule would produce the same output for any input on both host & GPU.

**Comment by jsteube** [comment]
The format with expected_host and expected_gpu is good, but I'd use the wording expected_cpu and expected_opencl here, because this matches it better. Also not listing expected_opencl  in case it's not supported is really nice. So I'd say go for it!

Note that I'd use the tool without specifying a mode to it. This is kind of confusion and should be used only optional. If no mode is selected by the user, do "the right thing" ;)
