### ISSUE TITLE
Watchdog - not being detected in x86_64 lib directory

### ISSUE THREAD

**Issue by smarek** [hashcat/hashcat#1247]
Hey,

```
# ./hashcat64.bin --version
v3.5.0
```

is not being able to detect NVIDIA temperature (nvidia-smi works correctly), if the library `libnvidia-ml.so` is placed in `/usr/lib/x86_64-linux-gnu/nvidia/current/`

To temporary fix the issue, we use this solution

```
ln -s /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so /usr/lib/libnvidia-ml.so
```

For the Debian distribution, where we debugged this, there are multiple locations, where the library can be found (all symlinks), see:

```
# locate libnvidia-ml.so
/etc/alternatives/nvidia--libnvidia-ml.so.1-x86_64-linux-gnu -> /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so.1
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 -> /etc/alternatives/nvidia--libnvidia-ml.so.1-x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so -> libnvidia-ml.so.1
/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so.1 -> libnvidia-ml.so.375.39
/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so.375.39
```

**Comment by jsteube** [comment]
Thanks for your report!

I'm not sure if this issue should be assigned to hashcat. The root of this problem goes back to how the OS handles the dlopen() function because it's this logic in this function (or even deeper) which handles the search paths for the libraries. So this is basically a question related to OS or maybe how drivers copy the libraries and to where, depending on how you see it.

**Comment by smarek** [comment]
Thank you, well according to this Debian bug-report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819990

The solution would be to fallback dlopen `libnvidia-ml.so.1`, see for reference BOINC project https://github.com/BOINC/boinc/pull/1522/files

But that still feels a bit like a workaround for existing problem, you decide please @jsteube

**Comment by smarek** [comment]
This would also match the naming of library here: `/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1`, which path should be the in LD_LIBRARY_PATH
So maybe we should, after all, try to load the `.so.1` variant first or as a fallback?

**Comment by jsteube** [comment]
The proposed workaround sounds simple enought to me, I'll add it

**Comment by jsteube** [comment]
I've pushed a fix with commit https://github.com/hashcat/hashcat/commit/bb2118a2906280b2c356c2b887c6a18cab98f5ba

There's also a new beta binary on https://hashcat.net/beta/

Please test the fix and close the issue if successfull

**Comment by jsteube** [comment]
No response from OP but I think workaround is working
