### ISSUE TITLE
when I build hashcat for windows on MSYS2，I had a problem as follow

### ISSUE THREAD

**Issue by ouguanxiaosilang** [hashcat/hashcat#1260]
make: *** 没有规则可制作目标“/opt/win-iconv-32/lib/libiconv.a”，由“hashcat32.exe” 需求。 停止。
In

**Comment by jsteube** [comment]
I think you're doing something wrong here. If you compile for Windows (on Windows by using MSYS2), you use the native makefile target. The windows target is only for cross compilation from linux which is used when I'm create the binary package for the site, which is not what you want. So simply use "make" without a target and it will not drop that error and you get the windows binary you're looking for.

**Comment by ouguanxiaosilang** [comment]
Anyway thanks. I have solved this problem by installing the win-iconv and  patching the Makefile. @jsteube
