### ISSUE TITLE
Hashcat ruleset not cracking an 8 char WPA password

### ISSUE THREAD

**Issue by FalseProfit** [hashcat/hashcat#1262]
First of all, let me start by saying that Hashcat is an excellent tool, and I don't know where I would be without it. It is held in great regard by myself and my coworkers as it has been so beneficial during our pentests.

I'm having an issue that another user opened an issue about back on March 10th that I believe was closed prematurely on the same day.

Hashcat appears to be unable to crack 8 character WPA passwords when using a dictionary and ruleset. Dictionary attacks without a ruleset as well as bruteforce attacks are successful.

In my case, the dictionary word that should crack the password is "Guest" and the ruleset is "$8 $6 $3" therefore creating the correct password of "Guest863". I have not researched into whether this is an issue with cracking exactly 8 character passwords or if hashcat is only looking at the length of the dictionary word and not considering the length of the final word after the ruleset is applied and could perhaps be missing passwords of a greater length.

**Comment by jsteube** [comment]
I think we discussed that often enought, it's working correctly. Words < length 8 get rejected because they do not match the WPA policy of being at least length 8. If you want your rules pre-processed, please use hashcats stdout and stdin features in combination by using a pipe.

**Comment by FalseProfit** [comment]
I understand what you're saying, but just because the dictionary word is less than 8 characters does not mean the final product after applying the rule is.

After talking with some coworkers, it looks like the issue may actually be with the way aircrack creates its hccap file. I'll have to find some free time to continue debugging this but will update when I get a moment.

This is the forum post in particular that a coworker directed my attention to: https://hashcat.net/forum/thread-6273.html 

Thanks.
