### ISSUE TITLE
double-free / corruption error in v3.5.0-144-gef33544b+

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1263]
From a little testing, it appears to happen during display of status output, which @jsteube suspects might be related to #1255. Running 3.5.0-release for the same attack (against a few concatenated .hccapx) has not triggered the error so far in my testing. 

```
*** Error in `hashcat': double free or corruption (!prev): 0x000000000853b6b0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f7183cf27e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7f7183cfae0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f7183cfe98c]
hashcat[0x46ebe9]
hashcat[0x470d9a]
hashcat[0x4713b4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f718425a6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f7183d8182d]
```

Full error output here:

https://gist.github.com/roycewilliams/7ea14f4b0f3cee226475aeb9022f7ad5

**Comment by neheb** [comment]
Might want to compile with -Og next time :)

**Comment by roycewilliams** [comment]
Appears to be fixed now - thanks!
