### ISSUE TITLE
compiling v3.5.0-147-g2dcad3f0 causes gcc 7.1.1 warnings

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1264]
After updating gcc to 7.1.1, I got the following warnings when compiling 
v3.5.0-147-g2dcad3f0:

src/convert.c: In Funktion »printable_utf8«:
src/convert.c:41:36: Warnung: diese Anweisung könnte durchfallen
[-Wimplicit-fallthrough=]
       if ((a = (*--srcptr)) < 0x80 || a > 0xbf) return false;
           ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
src/convert.c:42:5: Anmerkung: hier
     case 3:
     ^~~~
src/convert.c:43:36: Warnung: diese Anweisung könnte durchfallen
[-Wimplicit-fallthrough=]
       if ((a = (*--srcptr)) < 0x80 || a > 0xbf) return false;
           ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
src/convert.c:44:5: Anmerkung: hier
     case 2:
     ^~~~
src/convert.c:51:21: Warnung: diese Anweisung könnte durchfallen
[-Wimplicit-fallthrough=]
       case 0xF4: if (a > 0x8f) return false;
                     ^
src/convert.c:54:5: Anmerkung: hier
     case 1:
     ^~~~

Best regards
Mike

**Comment by jsteube** [comment]
Thanks fort reporting. This is an code snippet from @magnumripper - can you take a look please?

**Comment by magnumripper** [comment]
The code is OK. We are deliberately using the fall-through feature of switch/case and apparently the `-Wall` option now comments on that. Just add `-Wno-implicit-fallthrough` to get rid of the warning.

**Comment by ZerBea** [comment]
Thank you for the info. I know that the code is working well. It was just an information that there are some gcc warnings using the default options of gcc 7.1.1.
Best regards
Mike

**Comment by magnumripper** [comment]
Will still might want to add `-Wno-implicit-fallthrough` before most dists has a gcc that new.

**Comment by neheb** [comment]
Adding __attribute__((fallthrough)) seems to be the recommended way to silence the warning.

**Comment by ZerBea** [comment]
Well, it's a good idea to silence the warning, before gcc 7.1.1 reaches UBUNTU.

**Comment by magnumripper** [comment]
I think `-Wimplicit-fallthrough` is a good option but it shouldn't be included in `-Wall`. Is gcc 7.1.1 a mature release?

Personally, I really wouldn't want to bloat the code with non-portable attributes to work around silly compiler warnings for perfectly fine code. In JtR I will add `-Wno-implicit-fallthrough` when supported by compiler.

BTW how would an older version of gcc react to `__attribute__((fallthrough))` (which it won't recognize)? With a warning? Then we're back to square one.

**Comment by magnumripper** [comment]
> Personally, I really wouldn't want to bloat the code with non-portable attributes

I take that back. #1266 solves this in a way that doesn't fail on other compilers, and that actually makes the code a bit more clear about what's happening.

BTW it's not `-Wall` that turns this on, it's `-Wextra`.

**Comment by ZerBea** [comment]
It's the default compiler on arch
https://www.archlinux.org/packages/core/x86_64/gcc/
and it's a major release, containing new features (as well as many other improvements) relative to GCC 6.x.
https://gcc.gnu.org/gcc-7/
