### ISSUE TITLE
DCC2 can't crack a length 16 password

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#1277]
```
$ echo > test.in '$DCC2$10240#january#26b5495b21f9ad58255d99b5e117abe2'
```
The password is "verylongpassword". Hashcat produce a false negative for this. Is it too long? Then why is it not rejected? And BTW where can I see the max. password length for any given format without dry running the source?

**Comment by jsteube** [comment]
Should be fixed now, thanks! There's no commandline option to show the max password length supported, but a relative good wiki article where the max lengths are listed.

**Comment by magnumripper** [comment]
> There's no commandline option to show the max password length supported, but a relative good wiki article where the max lengths are listed.

Where? Google let me down.

**Comment by magnumripper** [comment]
OK, `git grep 'hashconfig->pw.max'` is good enough for me 😆

**Comment by jsteube** [comment]
Latest version on github can crack passwords up to length 256 and salts (in this case the domain name) up to length 256, also in combination: https://pastebin.com/8HkttUpy
