### ISSUE TITLE
DCC2 can't parse a salt containing "#"

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#1278]
Test vector:
```
$DCC2$10240##january#cceed966f6689269b758893bb6bbb985
```
The salt/username is `#january`. Password is "issue#2575" (named from https://github.com/magnumripper/JohnTheRipper/issues/2575)

Current output:
```
Hashfile 'test.in' on line 1 ($DCC2$10240##january#cceed966f6689269b758893bb6bbb985): Hash-encoding exception
```
The trick is to find the last field separator by searching from end of string (eg. `strrchr()`).

**Comment by jsteube** [comment]
Is # a valid character as username? I don't feel like changing this is required otherwise.

**Comment by Fist0urs** [comment]
Windows username can contain anything but these characters:
" / \ [ ] : ; | = , + * ? < >
Even if # is very unlikely to be found, the implementation allows it (though I never saw this)
