### ISSUE TITLE
Temperature limit keeps getting reached on dinosaur GPUs

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1280]
I'm using 2 old Fermi graphics cards (GTX 480 and GTX 460) and these cards are known to run pretty toasty. For a GTX 480, 92C at full load is considered quite "normal" but every time this card hits that, hashcat aborts to save graphics cards from cooking themselves.

The GTX 480 is more than capable of running at these temperatures and it runs at such temps even while gaming. I have the fan speed at 100% but it doesn't really help much. It's a GTX 480, after all. I think that says enough.

Is there any way to bypass these limits or at the very least, increase them? These GPUs are the best I currently have.

**Comment by Chick3nman** [comment]
```
     --gpu-temp-disable        |      | Disable temperature and fanspeed reads and triggers  |
     --gpu-temp-abort          | Num  | Abort if GPU temperature reaches X degrees Celsius   | --gpu-temp-abort=100
     --gpu-temp-retain         | Num  | Try to retain GPU temperature at X degrees Celsius   | --gpu-temp-retain=95
```

**Comment by jsteube** [comment]
Question for forum, not github issue

**Comment by ghost** [comment]
Do those arguments work even when resuming a .restore file?

**Comment by ghost** [comment]
--gpu-temp-disable doesn't work. I originally specified it when I ran hashcat and it never saved the argument in my .restore file. When specifying `--gpu-temp-disable` after `--restore`, hashcat still persists on controlling fan speed and it still seems to have temperature limits.

**Comment by Chick3nman** [comment]
You can't add flags to a restored session without modifying the restore file. Modifying the restore file is risky as well but there are some tutorials online how to do it if you look around. If you ask on the forums, there are more people that can help with the issue.

**Comment by ghost** [comment]
Considering that I originally specified `--gpu-temp-disable ` and it wasn't put in the .restore, I think hashcat needs to be updated so that it does add the argument to the .restore. Perhaps also add an implementation where specifying arguments after `--restore` will become valid/recognized (to an extent).

If a user wants to change a setting, then it's tedious to have to edit the restore file, with the risk of it breaking.

**Comment by Chick3nman** [comment]
You can simply restart the attack to change the settings, taking note of where you left off and using --skip and --limit to start roughly where you left off and not go over the same work twice.
