### ISSUE TITLE
How to tackle " No Nvidia Compatible platform found " error

### ISSUE THREAD

**Issue by chipsang** [hashcat/hashcat#1281]
Guys Good Morning.
I have made little progress and have hashed my xlsx file. I have used latest python version (v.3.6) & Cudahashcat v2.01 . I have  Nvidia Geforce 8400 GS graphics card , I have installed latest 8 series drives as well. 
I have also used latest nvcuda.dll  (v 6.14.13.142 )
When I run hashcat , I am getting error -- Generating bitmap tables  with 16 bits --- 
" No Nvidia compatible platform found "
What is wrong & what should I do to correct it ? Here are snaps of the error -
https://drive.google.com/file/d/0B2HFQZABf3JPTVpzY1FrbnpVQjQ/view?usp=sharing
Thank you
Regards
![no compatible](https://user-images.githubusercontent.com/29501566/27271190-e9f27d6e-54e0-11e7-82b9-2e264d0bfa2b.PNG)
![nvcuda](https://user-images.githubusercontent.com/29501566/27271199-f37321e0-54e0-11e7-8321-d8600cd41ace.png)
![no compatible2](https://user-images.githubusercontent.com/29501566/27271203-f9768654-54e0-11e7-8181-845be651df4d.PNG)

**Comment by jsteube** [comment]
cudaHashcat is outdated, use hashcat.
