### ISSUE TITLE
request algorithm

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1282]
Heya !

Seen on hashkiller, no info on the software though, but would greatly be appreciated !

md5(sha1(hash).md5(hash).sha1(hash))

cheers ;)

**Comment by ghost** [comment]
(it appears to be SunShop CMS)

**Comment by ghost** [comment]
anything ? I read yo can edit the sources, but I dunno anytging bout compiling I do only PHP and Python and such ...

**Comment by jsteube** [comment]
It's not too hard too implement, but it takes a few hours. I'd like to see
more requests for it in here, first

**Comment by roycewilliams** [comment]
@sergiolover Do you have any info on how popular SunShop CMS might be, or what other platforms might use this algorithm? If I search for "SunShop CMS", I get almost no hits.

**Comment by ghost** [comment]
not huge but still a real thing :+1: 

google.com/search?q=powered.by.sunshop

**Comment by ghost** [comment]
and do you think of any alternative software to do so ?

I could dev something in python but it would be a very basic loop wich won't be very efficient I guess

**Comment by jsteube** [comment]
Double Issue: https://github.com/hashcat/hashcat/issues/293
