### ISSUE TITLE
Ethereum2john hash format mismatch

### ISSUE THREAD

**Issue by stealthsploit** [hashcat/hashcat#1296]
Reposting as new issue:
-------------------------------
I saw the ether2hashcat note said it was considered deprecated and replaced by ethereum2john.
The ether2hashcat format shown above was $ethereum$s&#42;n&#42;r&#42;p&#42;salt&#42;mac&#42;ciphertext , however ethereum2john converts it to $ethereum$s&#42;n&#42;r&#42;p&#42;salt&#42;ciphertext&#42;mac.

Hashcat only cracks $ethereum$s&#42;n&#42;r&#42;p&#42;salt&#42;ciphertext&#42;mac for me and fails to crack $ethereum$s&#42;n&#42;r&#42;p&#42;salt&#42;mac&#42;ciphertext (?)

E.g. (password of P@ssw0rd1!)

{“ciphertext”:”7f5c865554d67604394ae54d7a4f9735bdb85c90e606a672d18add1d167d793b“,
“cipherparams”:{“iv”:”ae4e8c9c2ac201d6c2baa58ff670fd39″},
“cipher”:”aes-128-ctr”,
“kdf”:”scrypt”,
“kdfparams”:{“dklen”:32,”salt”:”437964c9bd1b5f63bde56560808c894792f8f670694590b776e22381e32dd
33b“,”n”:1024,”r”:8,”p”:1},
“mac”:”96f2a849321cc04cb6c0fcee1bd4b195ca681ca28064dc45000f02e47230c5b6“}}

through ethereum2john gives (and successfully cracks):

$ethereum$s&#42;1024&#42;8&#42;1&#42;437964c9bd1b5f63bde56560808c894792f8f670694590b776e22381e32dd33b&#42;7f5c865554d67604394ae54d7a4f9735bdb85c90e606a672d18add1d167d793b&#42;96f2a849321cc04cb6c0fcee1bd4b195ca681ca28064dc45000f02e47230c5b6

Is there an ethereum2john post i've missed somewhere?

**Comment by jsteube** [comment]
This is confusing. I just tried to crack it with both hashcat and jtr and both crack it. I was under the assumption that hashcat can not crack it because of the switched input data?

**Comment by Chick3nman** [comment]
I was under the same assumption @jsteube , i thought hashcat was failing to crack the proper format, which is `$ethereum$s*n*r*p*salt*ciphertext*mac`. It seems both hashcat and JTR are aligned and following the correct format. The old format, `$ethereum$s*n*r*p*salt*mac*ciphertext`, was deprecated when @kholia built his script for john, and should NOT be used. Hashcat failing to crack the deprecated format is proper behaviour, there is no issue here.

**Comment by jsteube** [comment]
Closing the issue then. Feel free to reopen if needed.
