### ISSUE TITLE
Using -L option crashes hashcat.

### ISSUE THREAD

**Issue by kost123** [hashcat/hashcat#1297]
When using -L on either sha256 or sha512, I'm getting program crashes on windows, I havn't tried it on others but I'm guessing theres a bug here.. I am using latest release from /beta

Command:

hashcat64.exe -a 0 -m 1410 --session=all -p : -L -o "D:\Users\x\New folder (19)\tmp8674_found1410.txt" --outfile-format=3 -w 2 --gpu-temp-disable "C:\Users\x\AppData\Local\Temp\tmp8674.tmp" "C:\Users\x\Documents\New folder\found.2015.txt"

It crashes soon as it gets to "checking weak hashes".. working fine without the -L option.

GPU= 1080, driver = 382.53

when using hashcat32 instead of hashcat64 it gives an error when intializing device kernals and memory which says "insufficient memory available" but I have over 10gb of ram free.. not sure if it's even related.

Update: works fine in bruteforce mode and hybrid, just not in wordlist mode.

**Comment by jsteube** [comment]
Can't reproduce it locally on windows 7, same GPU, same driver. Please send all data I need to reproduce

**Comment by kost123** [comment]
I'm on windows 10, 16gb ram, can anybody else on windows 10 check? thanks.

**Comment by jsteube** [comment]
I still can not understand how this would occur in -a 1, -a 6 and -a 7 mode. For -a 0 it's clear, that's just some missing feature which I haven't added, but it's giving me some real headache with -a 1, -a 6 and -a 7. Also I can not reproduce locally.

**Comment by jsteube** [comment]
Please retry with latest version, I've also pushed a new binary beta to hashcat.net/beta

**Comment by kost123** [comment]
Well, whatever you did it works fine across all modes now, good job.
