### ISSUE TITLE
Create OpenCL/inc_hash_blake2b.cl

### ISSUE THREAD

**Issue by jsteube** [hashcat/hashcat#1298]
@DoZ10 Do you think you can do this? See OpenCL/inc_hash_sha512.cl etc for examples. The structure is always the same, I think you can copy/paste most of it. The only thing where I'm unsure about is how the Merkle-Demgard construction is done with Blake2b. After that, you can generate -m 600 pure kernels, again mostly copy/paste.

**Comment by DoZ10** [comment]
Sure !

I'll check this out.

**Comment by DoZ10** [comment]
Some heads up on this.

I did not forget, will do this work in upcoming week. 

Cheers.

**Comment by jsteube** [comment]
Any updates here?

**Comment by DoZ10** [comment]
Wow I completely forgot this issue. 

Yeah I'll get back to it. Shouldn't be a problem. Happy new year @jsteube
