### ISSUE TITLE
hashcat does not work under Wayland

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#1299]
No idea if this is a driver or hashcat limitation, but it errors out when trying to run it:

[mangix@clevo hashcat]$ ./hashcat -b
hashcat (v3.6.0-218-gf87ac210+) starting in benchmark mode...

X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

* Device #1: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

No devices found/left.

Started: Mon Jul 17 18:41:57 2017
Stopped: Mon Jul 17 18:41:57 2017

**Comment by philsmd** [comment]
It should be actually very easy to find out if other OpenCL tools work with your setup... e.g. just run "clinfo" and see if it works.
If neither hashcat nor clinfo works, it's very likely that your setup is not configured correctly (or in this specific case that wayland doesn't work correctly together with the drivers of your graphics card). My guess is that it's not really hashcat-related, but please test it.
Thx

**Comment by neheb** [comment]
driver bug. closing.
