### ISSUE TITLE
slight formatting problem in source code (sometimes there are tabs instead of 2 space)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#13]
According to the contribution/formatting rule in the README.md the rule is:
5. Uses 2-character tabs and 2-character indentations

I found some inconsistencies and would like to suggest that we fix them as soon as possible.
(the fixes should be cosmetic only and affect only the souce code, no changes for the binaries and final users)

**Comment by jsteube** [comment]
Merged
