### ISSUE TITLE
Build Hardening

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#130]
Not as issue, just wondering. Since some distributions are moving towards having hardened builds(Fedora and OpenWRT come to mind), does it make sense to move some of that upstream?

Reference: https://fedoraproject.org/wiki/Changes/Harden_All_Packages

**Comment by jsteube** [comment]
Wait, oclHashcat is neither +s nor it does run as a server process. I'm not getting it...

**Comment by neheb** [comment]
i mean just adding -fstack-protector-strong, -pie and other such stuff in the CFLAGS.

**Comment by epixoip** [comment]
Why do you feel this must be done upstream?

**Comment by neheb** [comment]
I don't really have an opinion on the matter. Just wondering what the consensus here is.

**Comment by epixoip** [comment]
it is my opinion that downstream can compile with whatever flags they like, and an issue should only be opened with upstream if the build fails when enabling some compiler flag. Then upstream can evaluate if there is a bug that needs to be fixed in the code, or if downstream should simply not use that flag.

**Comment by jsteube** [comment]
Two questions:

Which disadvantages does it have to add those flags? 
Will it work with all compilers we depend on like clang and mingw?

**Comment by neheb** [comment]
Some have a performance reduction. Some don't. I've tested with gcc and clang and it all seems to work. Not sure if it really matters since the OpenCL kernels(not impacted by the flags) are the ones doing the heavy lifting. I think i'll just close this. There's no point to this with a password cracker. Don't really want to lower performance in any way.
