### ISSUE TITLE
Initializing device kernels and memory...clCreateContext(): CL_UNKNOWN_ERROR.  A problem of using 3.4 and 3.6.

### ISSUE THREAD

**Issue by specYyt** [hashcat/hashcat#1307]
I used this two version of hashcat. But there comes the same error.  Give me some advice please.
hashcat (v3.6.0) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Tesla C2050, 671/2687 MB allocatable, 14MCU
* Device #2: Tesla C2050, 671/2686 MB allocatable, 14MCU
* Device #3: Tesla C2050, 671/2687 MB allocatable, 14MCU

Hashes: 6494 digests; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

INFO: Removed 2217 hashes found in potfile.

Initializing device kernels and memory...clCreateContext(): CL_UNKNOWN_ERROR

**Comment by jsteube** [comment]
Please post output of clinfo

**Comment by jsteube** [comment]
Should be fixed with latest beta.
