### ISSUE TITLE
Support for NetIQ Self Service Password Reset - Salted SHA1

### ISSUE THREAD

**Issue by crypticgeek** [hashcat/hashcat#131]
# Intro

[NetIQ Self Service Password Reset](https://www.netiq.com/products/self-service-password-reset/) (SSPR) is a user self service password application. Users configure challenge/response questions and answers then later use them to reset their forgotten password. SSPR can be configured to store the user's SSPR responses as part of the Active Directory schema. The AD schema is extended and a pwmResponseSet attribute is created and added to user accounts. Of course as a normal user we can read many AD attributes and in the environment I am testing in these attributes were readable as well. SSPR stores answers as plain text or hashed using PBKDF2WithHmacSHA1, SHA1, Salted SHA1, or bcrypt. 

At the moment I only have access to an environment with Salted SHA1 hashes. My C is pretty rusty but I'm willing to help out with this implementation in any way I can.
# Dumping hashes

I wrote some PowerShell to dump this information out of AD for potential cracking. The hash is stored base64 encoded so I just left it like that in my output because I'm lazy.
https://gist.github.com/crypticgeek/28ee0d0cdbb8b38092ab
## Example output

```
C:\PS>Get-pwmResponseSet -User jdoe
MinLen           CaseInsensitive AnswerText      Format          Challenge       Salt            Iterations      MaxLen          User           
------           --------------- ----------      ------          ---------       ----            ----------      ------          ----           
4                true            B:FxHUyOPwsr... SHA1_SALT       What was you... MBS9ZgZ5r7IG... 100000          200             jdoe     
4                true            B:ozKD1xwuyv... SHA1_SALT       What is your... CxCpGqosk9Pk... 100000          200             jdoe     
4                true            B:pC4sEaFy9l... SHA1_SALT       Who is your ... pGsXpx5ZyS5K... 100000          200             jdoe     
4                true            B:cgMui+ZJ+L... SHA1_SALT       What is the ... Q5HCvD8ms3Lg... 100000          200             jdoe

C:\PS>Get-pwmResponseSet -user jdoe | Convert-pwm2Hashcat
$SHA$100000$MBS9ZgZ5r7IGU8O1hfVyajXZkaoSZPbu$FxHUyOPwsrulLoacXlrkHN2qJ3M=
$SHA$100000$CxCpGqosk9PkCBcoRFp6DLjjRhVEJKK8$ozKD1xwuyvTzAXsKif7KL8h5Ihw=
$SHA$100000$pGsXpx5ZyS5K72dGE7vBoGny8LcpeygI$pC4sEaFy9l/11CEmAIGeYXPMeM8=
$SHA$100000$Q5HCvD8ms3LgsrMsswzYPTO5CgRAzzfj$cgMui+ZJ+L6+RHhfzO6XM/v7f30=
```
# Example hashes

```
$Format$Iterations$Salt$Base64
password -> $SHA$100000$MBS9ZgZ5r7IGU8O1hfVyajXZkaoSZPbu$FxHUyOPwsrulLoacXlrkHN2qJ3M= 
hashcat  -> $SHA$100000$CxCpGqosk9PkCBcoRFp6DLjjRhVEJKK8$ozKD1xwuyvTzAXsKif7KL8h5Ihw=
atom     -> $SHA$100000$pGsXpx5ZyS5K72dGE7vBoGny8LcpeygI$pC4sEaFy9l/11CEmAIGeYXPMeM8=
hiro     -> $SHA$100000$Q5HCvD8ms3LgsrMsswzYPTO5CgRAzzfj$cgMui+ZJ+L6+RHhfzO6XM/v7f30=
```
# Hashing algorithm

Here's some ruby code showing how NetIQ calculates salted sha1 hashes. But basically it does X iterations of sha($salt+$answer) but only salts on the first iteration (do most salt every iteration?).
https://gist.github.com/crypticgeek/031302d973909e0d4867

**Comment by matrix** [comment]
done in PR #3730
