### ISSUE TITLE
-m 500 on AMD can't crack password length > 15

### ISSUE THREAD

**Issue by julioauto** [hashcat/hashcat#1310]
I am seeing 3 problems with the current(ish) code, although this issue entry only has evidence of one of them. If there's any data you want me to collect to help with any of the other issues, please let me know. The problems are:
1) md5crypt (-m 500) does not crack passwords with length greater than 15 on my AMD cards (6x R9 380X). **This is not the case with my NVIDIA system** (1x GTX 960), as I have tested.
2) Hashcat only detects 5 out of my 6 GPUs - as you can see in the beginning of the output below.
3) On this AMD setup, the current code (master) is taking A LONG TIME in the dictionary cache phase (or it could be before - in the weak hash check - or right after, it's hard to tell just from the UI output), like 1 minute or so. Because of that I'm using the 3.6.0 release (from the .tar.gz in GitHub), which does not suffer from this issue.

root@a:\~/hashcat-3.6.0# openssl passwd -1 -salt 12345678 abcdefghijklmno > test_hashes
root@a:\~/hashcat-3.6.0# openssl passwd -1 -salt 12345678 abcdefghijklmnop >> test_hashes
root@a:\~/hashcat-3.6.0# cat test_hashes 
$1$12345678$4rRGiP0updDe4bIVYSafj/
$1$12345678$Sy0u0qLp5W1f/aNE5VcBp/
root@a:\~/hashcat-3.6.0# cat test_passwords 
abcdefghijklmno
abcdefghijklmnop
root@cracker:~/hashcat-3.6.0# ./hashcat -m 500 test_hashes test_passwords 
hashcat (pull/1273/head) starting...

* Device #6: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Tonga, 3839/4064 MB allocatable, 14MCU
* Device #2: Tonga, 3839/4068 MB allocatable, 14MCU
* Device #3: Tonga, 3839/4068 MB allocatable, 14MCU
* Device #4: Tonga, 3839/4068 MB allocatable, 14MCU
* Device #5: Tonga, 3839/4068 MB allocatable, 14MCU
* Device #6: Intel(R) Celeron(R) CPU G1820 @ 2.70GHz, skipped.

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Dictionary cache built:
* Filename..: test_passwords
* Passwords.: 2
* Bytes.....: 33
* Keyspace..: 2
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$1$12345678$4rRGiP0updDe4bIVYSafj/:abcdefghijklmno        
                                                          
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: test_hashes
Time.Started.....: Fri Jul 28 15:49:05 2017 (0 secs)
Time.Estimated...: Fri Jul 28 15:49:05 2017 (0 secs)
Guess.Base.......: File (test_passwords)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.51ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#4.....:        0 H/s (0.00ms)
Speed.Dev.#5.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/2 (50.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Candidates.#1....: abcdefghijklmno -> abcdefghijklmnop
Candidates.#2....: [Copying]
Candidates.#3....: [Copying]
Candidates.#4....: [Copying]
Candidates.#5....: [Copying]
HWMon.Dev.#1.....: Temp: 50c Fan: 30% Core: 473MHz Mem: 700MHz Bus:16
HWMon.Dev.#2.....: Temp: 54c Fan: 30% Core:1040MHz Mem:1500MHz Bus:8
HWMon.Dev.#3.....: Temp: 54c Fan: 30% Core: 938MHz Mem:1500MHz Bus:8
HWMon.Dev.#4.....: Temp: 54c Fan: 30% Core: 745MHz Mem:1500MHz Bus:8
HWMon.Dev.#5.....: Temp: 55c Fan: 30% Core: 745MHz Mem:1500MHz Bus:8

Started: Fri Jul 28 15:49:02 2017
Stopped: Fri Jul 28 15:49:05 2017

**Comment by jsteube** [comment]
Can not reproduce on my NV system:

```
root@ro:~/hashcat# ./hashcat -m 500 test_hashes test_passwords --potfile-disable 
hashcat (v3.6.0-354-g1759315) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: AMD Ryzen 7 1700 Eight-Core Processor, skipped.

OpenCL Platform #2: NVIDIA Corporation
======================================
* Device #2: GeForce GTX 750 Ti, 497/1991 MB allocatable, 5MCU

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled.

Dictionary cache hit:
* Filename..: test_passwords
* Passwords.: 2
* Bytes.....: 33
* Keyspace..: 2

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$1$12345678$4rRGiP0updDe4bIVYSafj/:abcdefghijklmno        
$1$12345678$Sy0u0qLp5W1f/aNE5VcBp/:abcdefghijklmnop       
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: test_hashes
Time.Started.....: Mon Aug 14 12:22:49 2017 (0 secs)
Time.Estimated...: Mon Aug 14 12:22:49 2017 (0 secs)
Guess.Base.......: File (test_passwords)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.29ms)
Recovered........: 2/2 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Candidates.#2....: abcdefghijklmno -> abcdefghijklmnop
HWMon.Dev.#2.....: Temp: 37c Fan: 33% Util:100% Core:1189MHz Mem:2700MHz Bus:16

Started: Mon Aug 14 12:22:40 2017
Stopped: Mon Aug 14 12:22:49 2017
```

Can not reproduce on my Intel system:

```
root@ro:~/hashcat# ./hashcat -m 500 test_hashes test_passwords --potfile-disable  -D1
hashcat (v3.6.0-354-g1759315) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: AMD Ryzen 7 1700 Eight-Core Processor, 4014/16057 MB allocatable, 16MCU

OpenCL Platform #2: NVIDIA Corporation
======================================
* Device #2: GeForce GTX 750 Ti, skipped.

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled.

Dictionary cache hit:
* Filename..: test_passwords
* Passwords.: 2
* Bytes.....: 33
* Keyspace..: 2

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$1$12345678$4rRGiP0updDe4bIVYSafj/:abcdefghijklmno        
$1$12345678$Sy0u0qLp5W1f/aNE5VcBp/:abcdefghijklmnop       
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: test_hashes
Time.Started.....: Mon Aug 14 12:22:58 2017 (0 secs)
Time.Estimated...: Mon Aug 14 12:22:58 2017 (0 secs)
Guess.Base.......: File (test_passwords)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.06ms)
Recovered........: 2/2 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Candidates.#1....: abcdefghijklmno -> abcdefghijklmnop
HWMon.Dev.#1.....: N/A

Started: Mon Aug 14 12:22:57 2017
Stopped: Mon Aug 14 12:23:00 2017
```

Probably an AMD JiT compiler error, because all use the same kernel code source file

**Comment by enilfodne** [comment]
Off-topic, but I'm wondering why is `Ryzen` detected as `Intel Platform` in your logs?

`
OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: AMD Ryzen 7 1700 Eight-Core Processor, 4014/16057 MB allocatable, 16MCU
`

**Comment by jsteube** [comment]
There's currently no AMD OpenCL runtime (or OpenCL "Platform") that supports the AMD Ryzen CPU. 

We have to fall back to generic CPU support to utilize the Ryzen. This generic CPU support is only the Intel OpenCL runtime. That's what you see there.

**Comment by jsteube** [comment]
I can also not reproduce on latest ROCm on Vega 64:

```
root@ro:~/hashcat# cat > test_passwords
abcdefghijklmno
abcdefghijklmnop
root@ro:~/hashcat# ./hashcat -m 500 test_hashes test_passwords
hashcat (v3.6.0-433-g2bc2137+) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: AMD Ryzen 7 1700 Eight-Core Processor, skipped.

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: gfx900, 6132/8176 MB allocatable, 64MCU

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt

Password length minimum: 0
Password length maximum: 256

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Dictionary cache built:
* Filename..: test_passwords
* Passwords.: 2
* Bytes.....: 33
* Keyspace..: 2
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$1$12345678$4rRGiP0updDe4bIVYSafj/:abcdefghijklmno        
$1$12345678$Sy0u0qLp5W1f/aNE5VcBp/:abcdefghijklmnop       
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: test_hashes
Time.Started.....: Sat Aug 26 14:44:45 2017 (0 secs)
Time.Estimated...: Sat Aug 26 14:44:45 2017 (0 secs)
Guess.Base.......: File (test_passwords)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.85ms)
Recovered........: 2/2 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Candidates.#2....: abcdefghijklmno -> abcdefghijklmnop
HWMon.Dev.#2.....: Temp: 61c Fan: 13% Core:1630MHz Mem: 945MHz Bus:16

Started: Sat Aug 26 14:44:31 2017
Stopped: Sat Aug 26 14:44:46 2017
```

In optimized mode it cracks the one of length 15 only

```
root@ro:~/hashcat# ./hashcat -m 500 test_hashes test_passwords -O
hashcat (v3.6.0-433-g2bc2137+) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: AMD Ryzen 7 1700 Eight-Core Processor, skipped.

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: gfx900, 6132/8176 MB allocatable, 64MCU

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Optimized-Kernel
* Zero-Byte
* Single-Salt

Password length minimum: 0
Password length maximum: 15

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Dictionary cache hit:
* Filename..: test_passwords
* Passwords.: 2
* Bytes.....: 33
* Keyspace..: 2

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$1$12345678$4rRGiP0updDe4bIVYSafj/:abcdefghijklmno        
                                                          
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: test_hashes
Time.Started.....: Sat Aug 26 14:47:04 2017 (0 secs)
Time.Estimated...: Sat Aug 26 14:47:04 2017 (0 secs)
Guess.Base.......: File (test_passwords)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.40ms)
Recovered........: 1/2 (50.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 2/2 (100.00%)
Rejected.........: 1/2 (50.00%)
Restore.Point....: 2/2 (100.00%)
Candidates.#2....: abcdefghijklmno -> abcdefghijklmno
HWMon.Dev.#2.....: Temp: 61c Fan: 13% Core:1536MHz Mem: 945MHz Bus:16

Started: Sat Aug 26 14:47:02 2017
Stopped: Sat Aug 26 14:47:05 2017
```

But that's how it's supposed to work, see here:

```
Password length minimum: 0
Password length maximum: 15
```

and

```
Rejected.........: 1/2 (50.00%)
```

Please retry with latest version and close this issue

**Comment by julioauto** [comment]
The latest version (from Git) does not contain this bug, therefore I'm closing the issue.
The latest release version (zip from June) still has it, so I recommend releasing a new one ASAP.

I'm curious: Any idea of what might have solved the issue?
