### ISSUE TITLE
--left corrupts valid descrypt hashes in output, when input contains invalid hashes

### ISSUE THREAD

**Issue by extended11** [hashcat/hashcat#1313]
Hi,

I stumbled upon a very weird corruption issue viewing left descrypt hashes. It seems related to my input file containing an invalid character in the salt. Hashcat does not notice this (doesn't throw a warning or error), but in addition to that, hashcat --left will corrupt certain *other* salts from the same input, that are actually valid. The corruption seems to happen only with a very small number of specific salts. I haven't been able to put the finger on the exact criteria that need to be in place for corruption to happen.

The problem can be illustrated with the following testcase, where 2 hashes contain an illegal '$' character, but --left outputs 4 hashes with the '$'. Two other hashes in the input have been corrupted, however not all hashes in the input are corrupted.

```
$ hashcat -V
pull/1273/head

$ cat empty.pot
$ cat testhashes
1$ccccccccccc
1$QQQQQQQQQQQ
1qYYYYYYYYYYY
1qwwwwwwwwwww
1rwwwwwwwwwww
1rsssssssssss

$ hashcat -m1500 --left --potfile-path=empty.pot testhashes
1$ccccccccccc
1$YYYYYYYYYYY
1$QQQQQQQQQQQ
1$wwwwwwwwwww
1rsssssssssss
1rwwwwwwwwwww
```

**Comment by extended11** [comment]
A note on the validity of '$' in the salt. While the crypt(3) man page states: "salt is a two-character string chosen from the set [a-zA-Z0-9./].", apparently some real-world systems do seem to use the '$' character in the salt. I just confirmed that hashcat is able to crack hashes with a '1$' salt.

So I guess allowing '$' in the salt is debatable. But regardless, the corruption should not happen.

**Comment by roycewilliams** [comment]
Side question: what real-world systems allow '$' in the salt? That would have to be a pretty deliberate and specific modification to the algorithm without a lot of payoff.

**Comment by extended11** [comment]
@roycewilliams Good question, I actually don't know. I concluded that from the fact that in thedescrypt hash collection I'm working on there's a couple of hashes starting with '1$' and they can be cracked with -m 1500. So that means, *some software* has generated them at some point in the past. However this hash collection is over 20 years old (obviously, as I hope no one uses descrypt any more) and it does not contain any contextual information about the origin of the hashes or the software that was used to generate them.

**Comment by roycewilliams** [comment]
@extended11 It's off-topic, but I'm very interested in descrypt in its historical context, so I'd love to confer with you offline in more detail. I'm quite Google-stalkable. :)

**Comment by roycewilliams** [comment]
For what it's worth, I can reproduce this on the latest.

```
$ hashcat -V
v3.6.0-328-ge6cb69e

$ cat empty.pot

$ cat testhashes
1$ccccccccccc
1$QQQQQQQQQQQ
1qYYYYYYYYYYY
1qwwwwwwwwwww
1rwwwwwwwwwww
1rsssssssssss

$ hashcat -m 1500 --left --potfile-path=empty.pot testhashes
1$ccccccccccc
1$YYYYYYYYYYY
1$QQQQQQQQQQQ
1$wwwwwwwwwww
1rsssssssssss
1rwwwwwwwwwww
```

**Comment by extended11** [comment]
This can explain the '$' in the salts:
http://www.openwall.com/lists/oss-security/2011/11/15/5

Seems like multiple BSD (Free, Open, DragonFly, Net) variants used to have crypt.c implementations that (silently) converted invalid chars in the salt to a '.' char when crypt()ing.

Also, here is an online implementation (in js, based on crypt.c from OpenBSD from 2003) that will accept invalid chars: https://unix4lyfe.org/crypt/
