### ISSUE TITLE
support for custom sha256

### ISSUE THREAD

**Issue by rockygsm** [hashcat/hashcat#1318]
Hello
its possible to add custom sha256 support ? i have algo in c 
min and max limit is 8 and only numbers 
sha2 is custom because each time hash is updated 1048 time min and 1056 time max.
even paid possible ready to paid for private exclusive use.

**Comment by jsteube** [comment]
Please be more specific about what algorithm is this, read "New feature/algorithm" here:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

**Comment by rockygsm** [comment]
Hello
algo is private i can share via email to you. if u can send me your email ? 
its 8 digit number sha256 its update with uniq id of 0xc byte and loop update for min 1048 also it have custom sha2update which use if data is not 0x20 then its xor with F0 first byte.
i have try to add u on google hangout if possible we can talk private ?

**Comment by jsteube** [comment]
Sounds like this is related to GSM. I am not interessted, especially not
after the SL3 disaster.

Am 14.08.2017 6:05 nachm. schrieb "rockymaster" <notifications@github.com>:

**Comment by rockygsm** [comment]
its ok thanks for look.
