### ISSUE TITLE
using literal '$HEX[]' strings as wordlist input?

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1321]
It appears that trying to treat literal $HEX strings as input (for example, if someone accidentally used HEX strings as input to a hashing process) results in failure.

$ echo -n doña | hexify
$HEX[646fc3b161]
$ echo \\$HEX[646fc3b161] | hashcat --stdout
doña

In this example, a file containing only HEX strings is fed to hashcat, and the results are converted prior to being used. On @Chick3nman's suggestion, I tried to use this rule to work around the issue:

```
$ cat hexfix.rule
[ ^$
```
... but no dice:

```
$ hashcat --session=troyhunt-rehex --potfile-path=./unfound.potfile --remove     -m 100 -a 0 -w 4 troyhunt-unfound-tycho_2017-08-1800U /storage-hdd/founds/found.2015.txt.hex -r hexfix.rule
hashcat (v3.6.0-351-gec874c1d+) starting...

Approaching final keyspace - workload adjusted.

Session..........: troyhunt-rehex
Status...........: Exhausted
Hash.Type........: SHA1
Hash.Target......: troyhunt-unfound-tycho_2017-08-1800U
Time.Started.....: Sun Aug 13 21:52:54 2017 (0 secs)
Time.Estimated...: Sun Aug 13 21:52:54 2017 (0 secs)
Guess.Base.......: File (/storage-hdd/founds/found.2015.txt.hex)
Guess.Mod........: Rules (hexfix.rule)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   125.8 MH/s (5.07ms)
Speed.Dev.#2.....:   118.1 MH/s (5.00ms)
Speed.Dev.#3.....:   116.4 MH/s (5.49ms)
Speed.Dev.#4.....:   135.3 MH/s (4.74ms)
Speed.Dev.#5.....:   123.9 MH/s (5.17ms)
Speed.Dev.#6.....:   123.6 MH/s (5.19ms)
Speed.Dev.#*.....:   743.0 MH/s
Recovered........: 0/1121550 (0.00%) Digests, 0/1 (0.00%) Salts
Recovered/Time...: CUR:N/A,N/A,N/A AVG:0,0,0 (Min,Hour,Day)
Progress.........: 3910008/3910008 (100.00%)
Rejected.........: 0/3910008 (0.00%)
Restore.Point....: 0/3910008 (0.00%)
Candidates.#1....: $ä?&! -> $DäG
Candidates.#2....: $HEX[245d89c2ad] -> $HEX[24c3a43f263a]
Candidates.#3....: $ö%A -> $öX=
Candidates.#4....: $DäG -> $ö#A
Candidates.#5....: $HEX[24c3b6583e] -> $HEX[24bc346237]
Candidates.#6....: $HEX[24bc344237] -> $HEX[24a0707265736964656e74]
HWMon.Dev.#1.....: Temp: 42c Fan: 80% Util:  0% Core:1607MHz Mem:4513MHz Bus:8
HWMon.Dev.#2.....: Temp: 40c Fan: 80% Util:  0% Core:1771MHz Mem:4513MHz Bus:4
HWMon.Dev.#3.....: Temp: 42c Fan: 80% Util:  0% Core:1607MHz Mem:4513MHz Bus:16
HWMon.Dev.#4.....: Temp: 39c Fan: 80% Util:  0% Core:1797MHz Mem:4513MHz Bus:4
HWMon.Dev.#5.....: Temp: 40c Fan: 80% Util: 62% Core:1911MHz Mem:4513MHz Bus:1
HWMon.Dev.#6.....: Temp: 38c Fan: 80% Util:100% Core:1898MHz Mem:4513MHz Bus:1
```

**Comment by jsteube** [comment]
The reading of $HEX[] strings from a wordlist is still supported in hashcat, but the output has changed. It's used only in case the string includes the separator char or if the output string is not a valid UTF8 string.

I do not see the need for a fix

**Comment by philsmd** [comment]
I think the problem is that in very, very, very rare situations the password could start with $HEX[ and end with ] (and have only hex characters in between, the length must be a multiple of 2).
If this is the case, hashcat converts the $HEX[] string into the raw string. Sometimes this could not be wanted, therefore @roycewilliams suggested that we add a new flag to turn off this automatically conversion of $HEX[] strings within the word list.

my suggestion is to introduce a new flag called something like --wordlist-autohex-disable to disable the automatical conversion of $HEX[] strings whenever the words from the word lists are read in

**Comment by roycewilliams** [comment]
it's a pretty rare corner case, with a known workaround (HEX-ify, then convert that to hex and use --hex-wordlist (i've been calling this "hexception"):

https://gist.github.com/roycewilliams/8f3bf8e3109f771b1b773265317c6c1c

... so it won't hurt my feelings if this is a wontfix ... though there may be a better fix for the more general case.
