### ISSUE TITLE
$[HEX] output corruption when using rules - extraneous NULLs, etc.

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1322]
(from a discussion with waffle)

These hashes were emitted as founds for -m 100 in hashcat, but they are not valid founds. In some cases, they appear to contain extraneous nulls.

Bad: 188d8ebe3b3893b7789c644207686ae5fc94d022:$HEX[25d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d08500bfd197d085d0bf]
Good: 188d8ebe3b3893b7789c644207686ae5fc94d022:$HEX[2525d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bf]

 Bad: 5b22ee787b1eddf56df98fd0b3e17604e6559510:$HEX[d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085353031d0bfd197d085d0]
Good: 5b22ee787b1eddf56df98fd0b3e17604e6559510:$HEX[d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085353030d0bfd197d085d0]

 Bad: 51e0de298b263c020fc8f398df589baa2dc423a5:$HEX[d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085323231d0bfd197d085d0]
Good: 51e0de298b263c020fc8f398df589baa2dc423a5:$HEX[d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085d0bfd197d085323232d0bfd197d085d0]

 Bad: 3059d53a182689430f2dcfa946d5acfec8b91573:$HEX[2623393637393a2623393637393a2623393637393a2623393637393a2623393637393a2623393637393a2623393637393a]
Good: 3059d53a182689430f2dcfa946d5acfec8b91573:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:&#9679:

All were rule-processed finds. These are the rules that were in use:

$1
$1 $0 $0
$1 $4 $8 $8
$1 $9 $9 $3
$1 $9 $9 $5
$2 $0 $0 $9
$2 $8
$7
$7 $7 $7
$9 $2
$:
$@
$n $e
$q
:
Y4
]
] ]
] ] ]
] ] ] ]
] ] ] ] ]
] ] ] ] ] ]
^1 ]
^2 ]
^2 ^2 ^2
^2 ^3 ^4
^5 ^4 ^3 ^2 ^1
^6 ]
^a ^n ^i ^n
l [ ^s
l o7e
ss1 $Q
t

More examples here:

https://gist.github.com/roycewilliams/5841b746cda244aa2a483ebf10b119bc

**Comment by jsteube** [comment]
This strongly depends on version, please retry with latest beta.

**Comment by roycewilliams** [comment]
The issue was apparently seen when using v3.6.0-345-g98b4aab

**Comment by roycewilliams** [comment]
... and is apparently no longer happening in the latest beta. Closing - thanks!
