### ISSUE TITLE
Link to maskprocessor in the wiki

### ISSUE THREAD

**Issue by dandv** [hashcat/hashcat#1326]
https://hashcat.net/wiki/doku.php?id=hybrid_atttack_with_rules mentions mp64, which isn't among the binaries on the download page. (Happy to edit the Wiki, but I couldn't figure out how to register.)

**Comment by roycewilliams** [comment]
Good catch. I've added a link to the maskprocessor page, which in turn links to downloads thereof. If that's good enough, please close the issue; otherwise, we'll discuss. :)

**Comment by dandv** [comment]
Thanks! The rest is just typos:

> That is useful if you want to do Hybrid attack in hashcat. All you need it to add the “-r bf.rule”.

->

> The generated rule file can be used to perform Hybrid attacks with `hashcat`. All you need is to pass the rule file to `hashcat` via `-r bf.rule`.

**Comment by roycewilliams** [comment]
Done (ish).
