### ISSUE TITLE
please make hashcat more leet

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1337]
So that forevermore, everyone can refer to #1337 as "the issue that made hashcat the most leet EVAR"

**Comment by roycewilliams** [comment]
This should be closed as "wontfix - maximum leetness already achieved" (at least until we reach #31337)

**Comment by m33x** [comment]
Maybe some cool ASCII art can help fix the problem?
BTW: +1

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/1644ac30b50f4cc5fc38762bf93a6913ab1d0030

**Comment by roycewilliams** [comment]
Confirmed - this addresses the issue. Thanks! (and credit/blame to @m33x, who noticed that the number was coming up)
