### ISSUE TITLE
Unexpected "Skipping mask '?1?1?1?1?1?1?1?1'" error on DES-ECB -m 14000

### ISSUE THREAD

**Issue by mattames** [hashcat/hashcat#1339]
Hi Guys,

I suspect that DES-ECB is now broken in the latest repo - here is a test that I have run using the previous release (3.6) and the current HEAD in Github:-

(3.6.0):-

`$ ./hashcat64.bin --force -w 3 -m 14000 0123456789ABCDEF:0123456789ABCDEF -a 3 --hex-charset  ?1?1?1?1?1?1?1?1 -1 charsets/DES_full.charset
hashcat (v3.6.0) starting...

OpenCL Platform #1: Intel
=========================
* Device #1: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 1024/2048 MB allocatable, 24MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Precompute-Final-Permutation
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s

Session..........: hashcat
Status...........: Running
Hash.Type........: DES (PT = $salt, key = $pass)
Hash.Target......: 0123456789abcdef:0123456789abcdef
Time.Started.....: Mon Aug 21 12:45:39 2017 (2 secs)
Time.Estimated...: Wed Oct 21 23:32:21 2020 (14 years, 326 days)
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 charsets/DES_full.charset, -2 Undefined, -3 Undefined, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   153.3 MH/s (78.27ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 314572800/72057594037927936 (0.00%)
Rejected.........: 0/314572800 (0.00%)
Restore.Point....: 0/34359738368 (0.00%)
Candidates.#1....: $HEX[7391036173657331] -> $HEX[ff9f03ffbf010101]
HWMon.Dev.#1.....: N/A

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => q

Session..........: hashcat                                
Status...........: Quit
Hash.Type........: DES (PT = $salt, key = $pass)
Hash.Target......: 0123456789abcdef:0123456789abcdef
Time.Started.....: Mon Aug 21 12:45:39 2017 (3 secs)
Time.Estimated...: Wed Oct 21 23:32:22 2020 (14 years, 298 days)
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 charsets/DES_full.charset, -2 Undefined, -3 Undefined, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   154.1 MH/s (78.30ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 503316480/72057594037927936 (0.00%)
Rejected.........: 0/503316480 (0.00%)
Restore.Point....: 0/34359738368 (0.00%)
Candidates.#1....: $HEX[7315056173657331] -> $HEX[ff7f05ffbf010101]
HWMon.Dev.#1.....: N/A

Started: Mon Aug 21 12:45:38 2017
Stopped: Mon Aug 21 12:45:43 2017
`

Here is the output from the current Github repo (v3.6.0-402-gf32e113)

` $ ./hashcat --force -w 3 -m 14000 0123456789ABCDEF:0123456789ABCDEF -a 3 --hex-charset  ?1?1?1?1?1?1?1?1 -1 charsets/DES_full.charset
hashcat (v3.6.0-402-gf32e113) starting...

OpenCL Platform #1: Intel
=========================
* Device #1: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 1024/2048 MB allocatable, 24MCU

/home/mames/Documents/git/hashcat/OpenCL/m14000_a3.cl: Pure kernel not found, falling back to optimized kernel
Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Optimized-Kernel
* Zero-Byte
* Precompute-Final-Permutation
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

Skipping mask '?1?1?1?1?1?1?1?1' because it is larger than the maximum password length.
The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: DES (PT = $salt, key = $pass)
Hash.Target......: 0123456789abcdef:0123456789abcdef
Time.Started.....: Mon Aug 21 12:46:45 2017 (0 secs)
Time.Estimated...: Mon Aug 21 12:46:45 2017 (0 secs)
Guess.Mask.......: ?1?1?1?1?1?1?1?1 [8]
Guess.Charset....: -1 charsets/DES_full.charset, -2 Undefined, -3 Undefined, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0
Rejected.........: 0
Restore.Point....: 0
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: N/A

Started: Mon Aug 21 12:46:43 2017
Stopped: Mon Aug 21 12:46:45 2017
`

**Comment by jsteube** [comment]
I can't reproduce with the latest github version. You sure you're in the right current working directory when executing?

**Comment by philsmd** [comment]
maybe you had pulled/cloned the repo some time ago and didn't use "make clean".

You could also try to use the beta (https://hashcat.net/beta/) to see if the problem also happens with pre-compiled code (the beta binaries).

**Comment by mattames** [comment]
Well this is slightly embarrassing - "git pull" and "make clean" fixed it. Looks like I compiled a broken build by leaving that out.

On another note - I tested the "Time Estimated" bug and its now working as expected! Thanks for the fix guys!
