### ISSUE TITLE
crack sha256-hash, password length 64?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [hashcat/hashcat#1345]
Hey guys,
is it possible to crack a password of length 64 if i know the sha256 hash? password consists only of numbers and lowercase letters.

**Comment by jsteube** [comment]
It depends on what you mean exactly. In current release version 3.6.0 this is not possible at all. In current github master version (or beta from https://hashcat.net/beta/) it is possible if you guess it right. That means for example if you know 60 positions for sure and just want to iterate through the unknown 4, then it works.

**Comment by Hans-Maulwurf** [comment]
no, it would be 64 unknown characters (letters and numbers only)

**Comment by jsteube** [comment]
There's currently no way known to do that, therefore no software can do it.
