### ISSUE TITLE
Intel open cl.

### ISSUE THREAD

**Issue by moo0174** [hashcat/hashcat#1349]
I got an error when I try cracking hashes.

'' Intels opencl runtime (gpu only) is currently broken.
We are waiting for updated opencl drivers from intel.
You can use --force to override but do not report related errors.

How do i fix this?

**Comment by roycewilliams** [comment]
There is currently no way to fix this within hashcat. Only Intel can provide a fix.

You can also add --force to your hashcat parameters, but it may not work well, and if it has errors, they are not hashcat's fault.
