### ISSUE TITLE
OSX sometimes fails to crack -m 5600 (NetNTLMv2)

### ISSUE THREAD

**Issue by hubert3** [hashcat/hashcat#1350]
Hi,

using the NetNTLMv2 sample hash from the Hashcat wiki:

```
$ cat example.hash
admin::N46iSNekpT:08ca45b7d7ea58ee:88dcbe4446168966a153a0064958dac6:5c7830315c7830310000000000000b45c67103d07d7b95acd12ffa11230e0000000052920b85f78d013c31cdb3b92f5d765c783030
```

With a test wordlist of 4 passwords, including the correct one (hashcat):

```
$ cat example.wordlist
hashcat
wrongpass
anotherpass
hellopass
```

Hashcat is failing to find the correct password in approximately 1/3 runs:

```
$ ./hashcat -m 5600 example.hash ./example.wordlist
hashcat (v3.6.0-465-g0a0522cf) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped.
* Device #2: Intel(R) HD Graphics 530, 384/1536 MB allocatable, 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, 512/2048 MB allocatable, 12MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Password length minimum: 0
Password length maximum: 256

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

Dictionary cache hit:
* Filename..: ./example.wordlist
* Passwords.: 5
* Bytes.....: 41
* Keyspace..: 5

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: NetNTLMv2
Hash.Target......: ADMIN::N46iSNekpT:08ca45b7d7ea58ee:88dcbe4446168966...783030
Time.Started.....: Tue Sep  5 19:02:08 2017 (1 sec)
Time.Estimated...: Tue Sep  5 19:02:09 2017 (0 secs)
Guess.Base.......: File (./example.wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 5/5 (100.00%)
Rejected.........: 0/5 (0.00%)
Restore.Point....: 0/5 (0.00%)
Candidates.#2....: [Copying]
Candidates.#3....:  ->

Started: Tue Sep  5 19:02:07 2017
Stopped: Tue Sep  5 19:02:09 2017
```

Running hashcat again immediately afterwards, the hash is found this time:

```
$ ./hashcat -m 5600 example.hash ./example.wordlist
hashcat (v3.6.0-465-g0a0522cf) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped.
* Device #2: Intel(R) HD Graphics 530, 384/1536 MB allocatable, 24MCU
* Device #3: AMD Radeon Pro 455 Compute Engine, 512/2048 MB allocatable, 12MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Password length minimum: 0
Password length maximum: 256

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

Dictionary cache hit:
* Filename..: ./example.wordlist
* Passwords.: 5
* Bytes.....: 41
* Keyspace..: 5

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

ADMIN::N46iSNekpT:08ca45b7d7ea58ee:88dcbe4446168966a153a0064958dac6:5c7830315c7830310000000000000b45c67103d07d7b95acd12ffa11230e0000000052920b85f78d013c31cdb3b92f5d765c783030:hashcat

Session..........: hashcat
Status...........: Cracked
Hash.Type........: NetNTLMv2
Hash.Target......: ADMIN::N46iSNekpT:08ca45b7d7ea58ee:88dcbe4446168966...783030
Time.Started.....: Tue Sep  5 19:03:12 2017 (0 secs)
Time.Estimated...: Tue Sep  5 19:03:12 2017 (0 secs)
Guess.Base.......: File (./example.wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.67ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 5/5 (100.00%)
Rejected.........: 0/5 (0.00%)
Restore.Point....: 0/5 (0.00%)
Candidates.#2....: hashcat ->
Candidates.#3....: [Copying]

Started: Tue Sep  5 19:03:11 2017
Stopped: Tue Sep  5 19:03:14 2017
```

The failure rate is roughly 1/3 or 1/4 runs where the match is not found.

I noticed this after a real-world run (380mb wordlist including the correct password) also failed to find a match for a NetNTLMv2 hash which John The Ripper finds reliably

The machine is a new MacBook Pro (15-inch, 2016) running macOS Sierra 10.12.6 with 2.7 GHz Intel Core i7 and GPUs as shown in console output above.

hashcat binary compiled from source today (git pull = up-to-date as of right now)

Please let me know if I can help debug this somehow?

**Comment by jsteube** [comment]
Since hashcat has to dispatch the password candidates to different devices in order to make use of parallelisation it's possible that you have one device in which hashcat works as expected and another where it doesn't, for whatever reason. This processes is quasi-random because it's unknown which device gets the candidates first. If you select the device using -d 2 and -d 3 directly and you rerun the test, it's possible one device will always crack and the other never. Also note that John the ripper uses your CPU, you can do that on hashcat by using -D 1 (notice the upper case). On there, it should crack the same way. Please report back when you tried all 3 variants

**Comment by hubert3** [comment]
-D 1 always seems to work

-d 2 always seems to work

-d 3 never works.

So the culprit seems to be my "AMD Radeon Pro 455 Compute Engine, 512/2048 MB allocatable, 12MCU"

**Comment by jsteube** [comment]
That's consistent with the behavior of many AMD devices in OSX. Their OpenCL runtime is kind of broken. We can only hope ROCm will be ported to OSX soon ;)

**Comment by hubert3** [comment]
Ok good to know that the AMD device should not be used for now.

However, I am also seeing crashes on launch (Abort Trap 6) when I'm using all devices or device 2 only (Intel(R) HD Graphics 530) in combination with larger wordlists and rulesets.

I was running -d 3 to avoid these crashes but it appears cracking is broken with this device (no wonder I didn't crack anything the last few days).

See https://github.com/hashcat/hashcat/issues/309

**Comment by jsteube** [comment]
That's not exactly correct because there's also some AMD devices that work fine. 

The Trap 6 is when the OSX kernel watchdog sees a GPU kernel to long running. But that's what we do here, computation. So desktop response is not so important, but the driver doesn't know that. It therefore kills the running kernel. The best way to avoid this is to hold the kernel runtime as low as possible. The user can do that by reducing the workload. That means if you set -w 1, the chances are good you're not running into Trap 6. However, this is again not a hashcat problem. On Linux and on Windows there's the same type of watchdog, but there's ways to turn it off. On OSX, there's no such option. If -w 1 doesn't work, you can also try -u 1 -n 1 --force.

**Comment by hubert3** [comment]
Thanks

-d 2 -w 1 with large wordlist/ruleset still gets Abort Trap 6 on launch

-d 2 -w 1 -u 1 -n 1 --force runs, but the speed is 720 kH/s which is approximately John CPU only speed.

**Comment by jsteube** [comment]
You can increase those numbers and see if they have an influence in performance. Also note that you can always use -O and fall back to optimized kernels. This gives you a great advantage in performance and perhaps allows you to not use to be forced to use -n and -u. It may also allows you to use -d 3. Anyway, this not a hashcat problem, we should close the issue.

**Comment by hubert3** [comment]
If "AMD Radeon Pro 455 Compute Engine, 512/2048 MB allocatable, 12MCU" is known not to work on OSX currently perhaps it should be auto-disabled or there should be a warning?

**Comment by jsteube** [comment]
Perhaps. Also note that this wasn't known until now since most users that run hashcat use Linux and Windows. OTOH what if they fix the drivers in the future. Then we'd tell the user not to use device even if it works.

**Comment by jsteube** [comment]
As discussed and verified by @hubert3 it turns out the error is not within hashcat but in AMD OpenCL runtime for OSX, therefore closing.

**Comment by hubert3** [comment]
Same result with -O (optimized kernels) - Using the AMD Radeon Pro 455 device on OSX (-d 3) Hashcat doesn't display any warnings or errors but silently fails to find any passwords.

Does Hashcat v3.6.0-465-g0a0522cf contain the self-test mentioned in https://github.com/hashcat/hashcat/issues/1348? Should that catch it?

In my humble opinion, I think it would be a good idea to disable this particular AMD device on OSX as it seems broken, or at least explicitly document this issue.

Whether it's a bug in the OpenCL runtime or Hashcat itself is an irrelevant distinction from the user's perspective.

Hashcat running on OSX on current Mac hardware with default options gives the user feedback that everything is working normally, but it will randomly fail to find some passwords (or never find any passwords, if selecting to run only on the buggy device, which I was doing to try to avoid the crashing issue documented in https://github.com/hashcat/hashcat/issues/309, which is also not resolved).

So Hashcat is giving the user false assurance about the strength of the hashes tested.

**Comment by roycewilliams** [comment]
A warning to the user - similar to the one shown when using Intel's OpenCL runtime - may be warranted.

**Comment by jsteube** [comment]
I'm not certain here, because I'm not convinced that this is not also PEBKAC in some way. We'd add some warning that is maybe not required. Also, since I do not own any apple devices, I also can't write a patch because I can't test. You'd need to send in a PR.

**Comment by roycewilliams** [comment]
Fair. I have macOS, but I have no AMD with it. To determine whether or not it is PEBCAK, we'd need to find someone with this combination.

**Comment by hubert3** [comment]
I'm as sure as I can be (as the reporter) that it's not PEBKAC.

I gave the contents of the hash and wordlist files, and the exact commands used above.

Using both the Intel and AMD devices in my MacBook Pro (default behaviour), it fails to find the password randomly, which I also experienced during a real-world run with a large dictionary and bigger list of hashes.

Specifying only the AMD device, it never finds any passwords. This is 100% repeatable and consistent.

I have asked the reporter of https://github.com/hashcat/hashcat/issues/1348 if he could try my commands, as he may be hitting the same issue also with an AMD device on OSX.

**Comment by mhasbini** [comment]
@jsteube What do you think about running the self-test on all target devices?
So that faulty devices can be found early.

**Comment by hubert3** [comment]
@0xbsec I think that would be a great idea. Would have saved me several days of running Hashcat on a non-working GPU device and not finding any passwords

**Comment by roycewilliams** [comment]
Latest GitHub has an interesting workaround for multiple OS' watchdog timeout at the 2-second or higher mark (macOS appears to be 5 seconds; MSDN says 2 seconds for Windows). This workaround promises to eliminate most "abort trap 6" errors. Please test.

https://github.com/hashcat/hashcat/commit/73bba00286d815878b544d2d0aa6a79e6cf698ce

Since "abort trap 6" kills hashcat and halts the benchmarking, this script may be useful for testing (it tests one algorithm at a time):

https://gist.github.com/roycewilliams/a343489ed73a3b4e96d2df7e5201dbb4

Some modes (10700, 15700) will still fail for a different set of reasons. In the future, they may be skipped entirely on platforms that prove to not be able to handle them.

[Edit: you'll also be able to test when 4.0.0 is released :) ]
