### ISSUE TITLE
LDAP-NTLMV1

### ISSUE THREAD

**Issue by omriman067** [hashcat/hashcat#1351]
HI,
I tested my org and got the following hash :

test::testdomain:000000000000000000000000000000000000000000000000:A44B9396CE62039A99632E13E5C8B8F80101000000000000646BE9505325D3014F560F72D60C217B0000000002000A0073006D006200310032000100140053004500520056004500520032003000300038000400160073006D006200310032002E006C006F00630061006C0003002C0053004500520056004500520032003000300038002E0073006D006200310032002E006C006F00630061006C000500160073006D006200310032002E006C006F00630061006C0008003000300000000000000000000000002000008D2149B9EA8B826B9EDA0C33F483A937BD9D9CB89DB0F8FE898AAB0E25C004FD0A00100000000000000000000000000000000000090014006C006400610070002F006C00650075006D0069000000000000000000:1122334455667788

it's seems to be output from "ldap.py" and the Responder repersent it as : "[LDAP] NTLMv1 Hash"
but HashID could not recognize it, and hashcat couldn't crack it too,
Maybe the hash format is wrong ?

does anyone know what the problem here is?
thanks

**Comment by jsteube** [comment]
This format is horrible broken. Note that the github issue is only for feature requests and bug reports. Please ask on forum
