### ISSUE TITLE
--keyspace calculation is incorrect

### ISSUE THREAD

**Issue by quarklove** [hashcat/hashcat#1352]
As the title says, the calculation for `--keyspace` is incorrect.

Here's the output of 3 commands:
```
> .\hashcat64.exe -a 3 -m 500 --keyspace '?l'
1
> .\hashcat64.exe -a 3 -m 500 --keyspace '?l?l'
26
> .\hashcat64.exe -a 3 -m 500 --keyspace '?l?l?l'
676
```

Lowercase letters `?l` should give a keyspace of 26 for one character, and 676 for 2 characters. The numbers seem to be off by 1 character.

This bug was tested to be present since 3.6.0.

**Comment by jsteube** [comment]
Not a bug, everything is working as expected (even when not intuitional). Note that masks are split into two parts internally to give hashcat something to work as amplifier to overcome PCI-E bottleneck.
