### ISSUE TITLE
-a7 and --stdout prints garbage

### ISSUE THREAD

**Issue by Hydraze** [hashcat/hashcat#1354]
If I put "cat" in a wordlist "wordlist.txt" and I do
`./hashcat -a7 "?l?l?l?l" wordlist.txt --stdout`

I get 

> sarisari
> sarimari
> sarichan
> saribari
> sariange

instead of expected "mask" + "cat".

It still doesn't work with -O and it does not take -k into account, however it works correctly with -a6.

**Comment by jsteube** [comment]
Can reproduce, thanks for reporting
