### ISSUE TITLE
[Feature Request] md5(md5(md5($pass)))

### ISSUE THREAD

**Issue by jjruiz** [hashcat/hashcat#1355]
I haven't seen the md5(md5(md5($pass))) function combination in the hash modes list. Would you mind implementing it, please?

**Comment by jjruiz** [comment]
Nobody? It had implemented in hashcat-legacy (hash mode 3500): https://hashcat.net/wiki/doku.php?id=example_hashes#legacy_hash_types and then it was removed (I don't know the reasons).

Is it possible to reuse that code? Although it works only with CPU, it's better that than none...

**Comment by elyerinhaughie** [comment]
Suggestion if I may, to make this a little more dynamic.
How about an iteration-loop flag? a flag that specifies how many times to hash the previous calculation?

eg: 5
`md5(md5(md5(md5(md5($text)))))`

**Comment by jsteube** [comment]
There's so much details here that can make this more complicated than one might think of in the first place.  For example, is the out used as binary or as requested by the OP as ascii hex encoded string. If that's the case, should the hex encoding always be lower case or upper case, etc.. Therefore I don't like that Idea to have dynamic modes.

**Comment by trounce1** [comment]
@jjruiz is this still of interest to you? I can implement this very quickly?

**Comment by trounce1** [comment]
implemented here https://github.com/hashcat/hashcat/pull/2593

**Comment by trounce1** [comment]
here is some sample code for this algo

```python3
from binascii import hexlify
from hashlib import md5

password = b'hashcat'

r1 = hexlify(md5(password).digest())
r2 = hexlify(md5(r1).digest())
r3 = md5(r2).digest()

print(hexlify(r3))
```

it can be tested here https://repl.it/repls/AridMerryProgrammingmacro

**Comment by jjruiz** [comment]
@trounce1 thank you!

I have updated the hashcat to the last version, downloaded the 5 new files and installed the program. However I get this error when I try use the -m3500 parameter:

./hashcat/OpenCL/m03500_a3-pure.cl: No such file or directory

**Comment by trounce1** [comment]
@jjruiz For testing before it’s fully implemented. Use this fork https://github.com/trounce1/hashcat/tree/new-3500-mode

**Comment by jjruiz** [comment]
@trounce1 ok. 

(In the other tree) I tested that the error appears whether I try to use increments (-i parameter). i.e.:

./hashcat HASH -m3500 -a3 -w3 -O -i --increment-min=5 --increment-max=8 ?a?a?a?a?a?a?a?a

EDIT: 

Using the fork, it works fine. 

I'm going to check it better. Thank you so much!

**Comment by jsteube** [comment]
Support merged into master, thanks @trounce1 for the contribution.
