### ISSUE TITLE
BUG pw_add()!!  with version v3.6.0-479-gb169653

### ISSUE THREAD

**Issue by rvn2p** [hashcat/hashcat#1356]
Hi,
when cracking 2 NetNTLMv2 hashes (-m 5600) against several wordlists with rules i get a lot of these error msg after completing one wordlist before building the index of the next one.
`
......
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
Cracking performance lower than expected?

* Update your OpenCL runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: NetNTLMv2
Hash.Target......: /*REDACTED*/hashes.txt
Time.Started.....: Fri Sep 15 09:45:05 2017 (41 mins, 5 secs)
Time.Estimated...: Fri Sep 15 10:26:19 2017 (9 secs)
Guess.Base.......: File (*REDACTED*)
Guess.Mod........: Rules (*REDACTED)
Guess.Queue......: 2/6 (33.33%)
Speed.Dev.#1.....:   117.2 MH/s (89.22ms)
Speed.Dev.#2.....:   111.9 MH/s (64.57ms)
Speed.Dev.#3.....:   115.6 MH/s (62.56ms)
Speed.Dev.#4.....:   112.3 MH/s (46.52ms)
Speed.Dev.#*.....:   457.0 MH/s
Recovered........: 0/2 (0.00%) Digests, 0/2 (0.00%) Salts
Progress.........: 992200181776/996566112816 (99.56%)
Rejected.........: 0/992200181776 (0.00%)
Restore.Point....: 12124160/14341557 (84.54%)
Candidates.#1....: tandamlaz -> ttttttomeetyouz
Candidates.#2....: $HEX[79616972656e657a] -> $HEX[e8e8e8e8e8e881bde697a5e4bdbfe59494e4bdbfe795aae78999e4bda07a]
Candidates.#3....: universi4z -> wwwwwwaterpower009705z
Candidates.#4....: r779. -> xxxxxx877192z
HWMon.Dev.#1.....: Temp: 42c Fan:100% Util:  0% Core:1607MHz Mem:4513MHz Bus:8
HWMon.Dev.#2.....: Temp: 50c Fan:100% Util:100% Core:1923MHz Mem:4513MHz Bus:8
HWMon.Dev.#3.....: Temp: 42c Fan:100% Util:  0% Core:1607MHz Mem:4513MHz Bus:8
HWMon.Dev.#4.....: Temp: 38c Fan:100% Util:  0% Core:1607MHz Mem:4513MHz Bus:16

Dictionary cache built:
* Filename..: *REDACTED*
* Passwords.: 171896740
* Bytes.....: 2018842580
* Keyspace..: 5972380334560
* Runtime...: 44 secs
`
clinfo is attached, if there is anything i can supply in addition to that let ne know
[clinfo.txt](https://github.com/hashcat/hashcat/files/1305816/clinfo.txt)

**Comment by rvn2p** [comment]
Driver is NVIDIA-Linux-x86_64-375.39.run

**Comment by rvn2p** [comment]
Bug dows not show up when using https://hashcat.net/files/hashcat-3.6.0.7z

**Comment by rvn2p** [comment]
I could corner it a bit more. The error happens if one of the pws gets cracked by the last wordlist and then it switches to the next one.
The last remaining hash is weirdly formatted. I can force the error by using this hash+ the default hash from the example page. I think the parser dies when parsing "$" as username for the NETNTLM hash.

$::CUSTOMERDOMAIN:HASH
admin::N46iSNekpT:08ca45b7d7ea58ee:88dcbe4446168966a153a0064958dac6:5c7830315c7830310000000000000b45c67103d07d7b95acd12ffa11230e0000000052920b85f78d013c31cdb3b92f5d765c783030

**Comment by jsteube** [comment]
I tried to reproduce this using 2 netntlmv2 hashes in my hashlist. One of them will crack during the run with the first wordlist, the other one will never crack. Anyway, the bug popped not up in on my system so I think this must be related to something else. Try to reduce the variables to an absolute minimum, then pack all files together and send them to me so that I can reproduce locally.

About that thing with $ in the username - that has no effect. The first line in your hash would just not be loaded from hashcat, it will tell you something about line length exception.

**Comment by jsteube** [comment]
OP, please send me the files I need to reproduce

**Comment by rvn2p** [comment]
I tried to reduce it to a smaller pack (hashes, wordlists,rules) but couldn't reproduce it with it. I can't upload the original hashes do to customer NDAs.  The system is busy now with another set of hashes but I'll try to reproduce it using the original hashes on the weekend

**Comment by Bobbymac99** [comment]
I have the same issue under Ubuntu.  I will try and gather basic info too.

**Comment by jsteube** [comment]
Is this really related to the hashlist? That would explain why I can not reproduce it, but otoh this is very unexpected. Please try with some different hashes

**Comment by jsteube** [comment]
Please retry with latest version (make sure to run make clean when building from source)

**Comment by rvn2p** [comment]
I'll try to recreate the original run (same hashes, same lists, same rules with v3.6.0-479-gb169653 and latest. This will take a few hours. i currently have an unreleated problem that dictionary chaches are not being saved and therefore are created over and over

**Comment by jsteube** [comment]
Do you use a network filesystem for your hashcat installation or your wordlist? Don't do that, it will break hashcat functionality. 

Also do not edit or copy or save dictstat cache database files, this will cause errors of that type "BUG pw_add". Maybe you do that?

**Comment by rvn2p** [comment]
the wordlists and hashcat are on a local storage on a zfs volume. I see that hashcat.dictstat is being modified after each run. 
Are dictstats always saved in hashcat's working dir, or are they saved in the wordlist directory as well? would nuking the hashcat direcotry and pulling an building it again fix this issues?

**Comment by rvn2p** [comment]
could reproduce the original bug after 11 hours =(.
doing a 4.0.0-rc1 run now

**Comment by rvn2p** [comment]
I could also reproduce it with 4.0.0-rc1. But it takes me almost a day to reproduce the exact circumstances and I am unable to isolate it further =(

> BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: NetNTLMv2
Hash.Target......: /tmp/hashes.txt
Time.Started.....: Fri Sep 22 11:05:51 2017 (1 day, 20 hours)
Time.Estimated...: Sun Sep 24 07:44:26 2017 (1 sec)


Sorry for wasting your time, should i close the bug?

**Comment by rvn2p** [comment]
Btw the not caching issue is in fact a zfs problem, when i put the wordlists on a local ext4 drive the caching works

**Comment by Bobbymac99** [comment]
Mine happened using a wordlist using Ubuntu 16.04.  Hashcat V3.6.0-462-g151dbc5, hash Truecrypt 6213, or one in that range.  It is actually on a large script so I would need to reassemble both the original script, and the multiple word lists I had concatenated together.  This was installed on one SSD drive, alone with the wordlist in the same directory, as I recall I had something like 26 million rejects when I looked at the status on it before terminating the script - since I was running it overnight

If you wish me to actually reproduce this - I can I think, but it will take a bit of work to do. Looking at the code I was wondering what that actual conditional statement says:  What are pws_cnt and kernel_power as related to each other?

WORDLIST.C
  if (device_param->pws_cnt < device_param->kernel_power)
.....
  else
  {
    fprintf (stderr, "BUG pw_add()!!\n");
    return;

**Comment by jsteube** [comment]
I've upload RC2 to hashcat.net/beta this should eventuelly fix both problems. Please try.

**Comment by voideater** [comment]
Just experienced this myself running 

`./hashcat-4.0.0/hashcat64.bin -m 100 file_with_hashes.txt -a 6 wordlists.txt ?d?d?d?d -O --gpu-temp-retain=65 -o hashes_found.txt`

Running hashcat-4.0.0-rc2.7z from 02-Oct-2017 13:53 on Ubuntu 16.04 w/ 3x GTX 970 Ti (w/ NVIDIA v384.90)

Wordlist I used was the ``crackstation.txt`` (700MB file that can be downloaded from various sources). Haven't been able to pin down for which words it happens, but it occurs near the end of the job every time.

Wordlist is located on the same drive for which I run hashcat from if that should have anything to say.

Update; same scenario using other wordlists as well (same list of hashes but slightly different mask used in the attack).

**Comment by jsteube** [comment]
I think I found the issue finally. Fix was pushed with this: https://github.com/hashcat/hashcat/commit/bfd3c57308c91de6e39e06fe1be4d05dfffa867d

Please retry with latest version from github or hashcat.net/beta (rc4) and close this issue if fixed

**Comment by rvn2p** [comment]
could not reproduce bug with 4.0.0-rc4

**Comment by jeffmcjunkin** [comment]
So uh, I have this error again, and I'm really confused as to how I could have it, given the timeframe involved here.

Using the NTLM example hash (https://hashcat.net/wiki/doku.php?id=example_hashes), here's the minimum reproducible bug for me:
```
jeff@blue:/pentest/password-recovery/hashcat$ ./hashcat -V
v6.1.1-120-g15bf8b730
jeff@blue:/pentest/password-recovery/hashcat$ echo b4b9b02e6f09a9bd760f388b67351e2b > /tmp/hash
jeff@blue:/pentest/password-recovery/hashcat$ echo badguess > /tmp/wordlist
jeff@blue:/pentest/password-recovery/hashcat$ ./hashcat /tmp/hash /tmp/wordlist -m 1000
hashcat (v6.1.1-120-g15bf8b730) starting...

Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
nvmlDeviceGetFanSpeed(): Not Supported

OpenCL API (OpenCL 1.2 CUDA 11.1.110) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: GeForce RTX 2070 with Max-Q Design, 6976/7982 MB (1995 MB allocatable), 36MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 632 MB

Dictionary cache built:
* Filename..: /tmp/wordlist
* Passwords.: 1
* Bytes.....: 9
* Keyspace..: 1
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.  

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => BUG pw_add()!!
Session..........: hashcat                       
Status...........: Exhausted
Hash.Name........: NTLM
Hash.Target......: b4b9b02e6f09a9bd760f388b67351e2b
Time.Started.....: Mon Dec 28 15:14:01 2020 (0 secs)
Time.Estimated...: Mon Dec 28 15:14:01 2020 (0 secs)
Guess.Base.......: File (/tmp/wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 0/1 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Copying]
Hardware.Mon.#1..: Temp: 45c Util:  0% Core: 885MHz Mem:6000MHz Bus:16

Started: Mon Dec 28 15:13:59 2020
Stopped: Mon Dec 28 15:14:02 2020

jeff@blue:/pentest/password-recovery/hashcat$ dpkg -l nvidia-driver-* | egrep '^ii'
ii  nvidia-driver-440    455.38-1pop0~1605144088~20.04~3cf77da amd64        Transitional package for nvidia-driver-455
ii  nvidia-driver-455    455.38-1pop0~1605144088~20.04~3cf77da amd64        NVIDIA driver metapackage
jeff@blue:/pentest/password-recovery/hashcat$ hashcat -I
hashcat (v6.1.1-120-g15bf8b730) starting...

Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 11.1.110

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce RTX 2070 with Max-Q Design
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 36
    Clock..........: 1185
    Memory.Total...: 7982 MB (limited to 1995 MB allocatable in one block)
    Memory.Free....: 6976 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 455.38

jeff@blue:/pentest/password-recovery/hashcat$ git show
commit 15bf8b7302fd2febd93845eb26d60efed6255bae (HEAD -> master, origin/master, origin/HEAD)
Merge: 1a6d8c6f9 2a3f487d9
Author: Jens Steube <jens.steube@gmail.com>
Date:   Tue Oct 13 11:22:31 2020 +0200

    Merge pull request #2579 from philsmd/tests_remove_asn1_package
    
    tests: remove requirement Convert::ASN1

jeff@blue:/pentest/password-recovery/hashcat$ git pull
Already up to date.
```

I fully admit it's possible something's gone awry with my nvidia drivers (because... nvidia), but this is an odd one.

There's one `BUG pw_add()!!` entry per wordlist entry, as demonstrated more clearly here:
```
jeff@blue:/pentest/password-recovery/hashcat$ head -n 10 /opt/Passwords/rockyou.txt  > /tmp/wordlist 
jeff@blue:/pentest/password-recovery/hashcat$ ./hashcat /tmp/hash /tmp/wordlist -m 1000
hashcat (v6.1.1-120-g15bf8b730) starting...

Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
nvmlDeviceGetFanSpeed(): Not Supported

OpenCL API (OpenCL 1.2 CUDA 11.1.110) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: GeForce RTX 2070 with Max-Q Design, 6976/7982 MB (1995 MB allocatable), 36MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 632 MB

Dictionary cache built:
* Filename..: /tmp/wordlist
* Passwords.: 10
* Bytes.....: 82
* Keyspace..: 10
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.  

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
BUG pw_add()!!
Session..........: hashcat                       
Status...........: Exhausted
Hash.Name........: NTLM
Hash.Target......: b4b9b02e6f09a9bd760f388b67351e2b
Time.Started.....: Mon Dec 28 15:16:32 2020 (0 secs)
Time.Estimated...: Mon Dec 28 15:16:32 2020 (0 secs)
Guess.Base.......: File (/tmp/wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 0/10 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 10/10 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Copying]
Hardware.Mon.#1..: Temp: 44c Util: 12% Core:1860MHz Mem:6000MHz Bus:16

Started: Mon Dec 28 15:16:32 2020
Stopped: Mon Dec 28 15:16:33 2020
```

Should I open the above as a new issue instead of resurrecting this old issue?

**Comment by matrix** [comment]
Hi,
I cannot reproduce the bug on my system.

```
$ ./hashcat /tmp/hash /tmp/wordlist -m 1000
hashcat (v6.1.1-120-g15bf8b730+) starting...

Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

OpenCL API (OpenCL 1.2 CUDA 10.0.206) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: GeForce GTX 1080 Ti, 10880/11178 MB (2794 MB allocatable), 28MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 491 MB

Dictionary cache hit:
* Filename..: /tmp/wordlist
* Passwords.: 10
* Bytes.....: 82
* Keyspace..: 10

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.  

Session..........: hashcat                       
Status...........: Exhausted
Hash.Name........: NTLM
Hash.Target......: b4b9b02e6f09a9bd760f388b67351e2b
Time.Started.....: Tue Dec 29 07:29:40 2020 (0 secs)
Time.Estimated...: Tue Dec 29 07:29:40 2020 (0 secs)
Guess.Base.......: File (/tmp/wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:    56476 H/s (0.01ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 10/10 (100.00%)
Rejected.........: 0/10 (0.00%)
Restore.Point....: 10/10 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: 123456 -> abc123
Hardware.Mon.#1..: Temp: 30c Fan: 29% Util: 35% Core:1835MHz Mem:5005MHz Bus:8
```

I suggest you to fix this, and then try again:

```
* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
```

Also there is this huge difference between your output and mine.

```
Progress.........: 0/10 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 10/10 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Copying]
```

There is most likely a problem with your setup.
