### ISSUE TITLE
Not known error in Hashcat Ubuntu

### ISSUE THREAD

**Issue by 9128213** [hashcat/hashcat#1362]
I have these error with every hash i try to deshash it. I have a powerfull ubuntu server so i can deshash faster But apparently i cant make it work

I get these error everytime  i try to decrypt

Hashfile 'h.txt' on line 238663 (haha866:1b711e4b87c9a950d02594c4e7ff7ca5:|y<): Line-length exception

 I get these error on other 238662 lines but i just stopped here cause i get the same thing in every line. And its a 5m line textfile.

command i type is these inside the hashcat 3.6.0 folder with the hashcat64.bin archive

`./hashcat64.bin -m 2711 --username  /hash/h.txt  /wordlist/1.txt`

hashes are from 2611 or 2711 i really dont know i put in a hash finder and it tells me these but i try changing the 

text file off hash is in user: hash:  salt format  (witouth spaces)

**md5(md5($pass)$salt) : VBuliten < v3.8.5 , VBuliten > v3.8.5 **

PS:I need output user:cracked clean password so deleting usernames is not a way

Additional info:

Is a ubuntu 16.04 Server
I installed OpenCL drivers for use GPU too. 
64GB ram 
i7 Quad core 6700k
Intel GPU

I try everything nothing worked, i also try to unix2dos the file from windows for chec if something wrong but isnt. I also in the hashcat forums i see theset

[https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_can_i_show_previously_cracked_passwords_and_output_them_in_a_specific_format_eg_emailpassword](url)

But i try it too and some commands
./hashcat64.bin -m 0 --username --potfile-path md5.pot original_MD5_hashes.txt rockyou.txt

in profile path i dont know what to put in pothfile-path my hash type is Vbulletin

**Comment by philsmd** [comment]
your hash works perfectly fine if I put "haha866:1b711e4b87c9a950d02594c4e7ff7ca5:|y<" (without quotes) within a file hash.txt and use the command:
```
./hashcat64.bin -m 2611 -a 0 --username hash.txt rockyou.txt
```

to output the results in username:plain format, you can use this command:
```
./hashcat64.bin -m 2611 --show --outfile-format 2 --username hash.txt
```

Therefore, the single hash works... maybe you have a hash file that consist of several different hash types etc... so you need to clean it and find out which hashes are using -m 2611 and which hashes do not etc
hashcat won't/can't do that job for you... the input must be correct. If it is not correct, you will see a warning.

BTW: it's not a good idea to make 2 forum posts and one github issue about the exact same problem:  https://hashcat.net/forum/thread-6877.html , https://hashcat.net/forum/thread-6873-post-36693.html#pid36693 and https://github.com/hashcat/hashcat/issues/1362 . This type of eager behaviour actually should be punished (forum ban?) and you should be glad that nevertheless someone took there precious free time to answer you at all... don't be a d*ck.

**Comment by 9128213** [comment]
@philsmd
Thanks for your response, and yes i ask in a lot off forums reddit too and maybe im asking a lot. I just see 2 problems.

1- In the second command for username output
`./hashcat64.bin -m 2611 --show --outfile-format 2 --username hash.txt`

Where is wordlist.txt ?

or it is like these
`./hashcat64.bin -m 2611 --show --outfile-format 2 --username hash.txt wordlist.txt`


2. I think you are in the good direction cause inside my hash.txt there are 2 different VBulletin hashes, ill have to manually remove them or there is any good tool for remove specific hash type(ill search now)

3. I dont have hashcat installed i just download binaries or whatever and go to the folder i have hashcat-3.6.0 inside there is hashcat64.bin and from here i just do
`./hashcat64.bin -m 2611  --username  /dir/dir/dir/hash.txt /dir/dir/dir/dir/wordlist.txt`

these command is just and example maybe is something bad inside just for you check thath i dont have installed.

4. Refering to 3. Should be better if i install it?.



Pretty new to linux/hashcat linux, i use windows hashcat time before and everything was quite more easy, but also more slow i think in these server i can have some good p/s.

Also thanks for getting free time for answer me :( sorry for being a d*ck sometimes i am.

**Comment by philsmd** [comment]
As the wiki section that you linked already explains, to display all cracks with the corresponding username you need to run 2 commands (one after the other):
1. crack with --username
2. --show --username

The first one saves the results (cracks) to hashcat.potfile and the second one uses the hashcat.potfile and looks for all hashes that are present in both your original hash file and the pot file and combines it with the usernames.

You could try to use the beta (https://hashcat.net/beta/) which has different limits for -m 2611/2711.

At this point... I don't think that this problem is a code issue at all. You just need to read the wiki/forum and other resources to learn how to use hashcat correctly.
The github issues here are for code issues, not user questions.

I would therefore say that you/we should close the issue here.
Thx
