### ISSUE TITLE
How to create hash function with known source code to use in hashcat?

### ISSUE THREAD

**Issue by manjunath7472** [hashcat/hashcat#1363]
Attached source code used for password hash algorithm used in DD-WRT routers. Could i get algorithm to use it in hashcat? or How to create a custom hash function to use it in hashcat?

[algo_ddwrt_router password_encode.txt](https://github.com/hashcat/hashcat/files/1317169/algo_ddwrt_router.password_encode.txt)

**Comment by jsteube** [comment]
There's no official documentation about how to add a new algorithm to hashcat. I'd say find a similar algorithm in hashcat, then search for it in the source and write the new one accordingly.

**Comment by manjunath7472** [comment]
ok thanks! Let me give it a try.
I have gone thru the default hashes in OpenCL folder.

So, What you mean is to learn openCL and edit that openCL file in notepad and rewrite custom hash function?

**Comment by jsteube** [comment]
It's a bit more complicated than that. However a github issue is the wrong place to ask for. This is only for bug reports and feature requests. Please use hashcat forum.
