### ISSUE TITLE
cant use cpu in hashcat and it is very slow (Please help me)

### ISSUE THREAD

**Issue by mehrad100** [hashcat/hashcat#1366]
please help me i have this problem like a week that install hashcat in my new laptop
when i use try to crack wp2 with 8 number 0 to 9 its take like 5 min with cpu with aircrack-ng
and when i try hashcat in windows too i try to do the same in hashcat with gpu and cpu and i see that its take 5 min!
(I mean the times are the same for any crack )
and i see many other problems too but mine are not in those
my system:
12 gb ram
Nvidia Geforce 940mx
cpu i7 7500u

when i try
C:\hashcat>hashcat.exe -m 2500 -a3 tplinkm.hccapx ?d?d?d?d?d?d?d?d -D 1,2

i give this:

hashcat (v3.6.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
* Device #3: Outdated or broken Intel OpenCL runtime detected!

You are STRONGLY encouraged to use the officially supported NVIDIA driver.
See hashcat.net for officially supported NVIDIA drivers.
See also: https://hashcat.net/faq/wrongdriver
You can use --force to override this, but do not report related errors.

Started: Sat Sep 23 06:36:45 2017
Stopped: Sat Sep 23 06:36:46 2017
and here is another

c:\hashcat>hashcat64.exe -b -w 4 -D 1,2
hashcat (v3.6.0) starting in benchmark mode...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
* Device #3: Outdated or broken Intel OpenCL runtime detected!

You are STRONGLY encouraged to use the officially supported NVIDIA driver.
See hashcat.net for officially supported NVIDIA drivers.
See also: https://hashcat.net/faq/wrongdriver
You can use --force to override this, but do not report related errors.

Started: Sat Sep 23 08:07:33 2017
Stopped: Sat Sep 23 08:07:33 2017

c:\hashcat>hashcat64.exe -b -w 4 -D 1,2 --force
hashcat (v3.6.0) starting in benchmark mode...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce 940MX, 512/2048 MB allocatable, 3MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) HD Graphics 620, 2047/4859 MB allocatable, 24MCU
* Device #3: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 3042/12168 MB allocatable, 4MCU

Hashtype: MD4

Speed.Dev.#1.....:  2794.6 MH/s (287.88ms)
Speed.Dev.#2.....:   849.8 MH/s (469.33ms)
Speed.Dev.#3.....:   285.6 MH/s (14.25ms)
Speed.Dev.#*.....:  3930.0 MH/s

Hashtype: MD5

Speed.Dev.#1.....:  1726.3 MH/s (465.98ms)
Speed.Dev.#2.....:   505.3 MH/s (393.49ms)
Speed.Dev.#3.....:   168.4 MH/s (24.76ms)
Speed.Dev.#*.....:  2400.0 MH/s

Hashtype: Half MD5

Speed.Dev.#1.....:  1144.6 MH/s (351.30ms)
Speed.Dev.#2.....:   338.8 MH/s (294.88ms)
Speed.Dev.#3.....: 97375.8 kH/s (42.87ms)
Speed.Dev.#*.....:  1580.7 MH/s

Hashtype: SHA1

Speed.Dev.#1.....:   734.7 MH/s (273.67ms)
Speed.Dev.#2.....: 26695.9 kH/s (463.11ms)
Speed.Dev.#3.....: 68081.6 kH/s (61.25ms)
Speed.Dev.#*.....:   829.5 MH/s

Please help me
I get headache i really dont know what else to do !!!!

**Comment by mehrad100** [comment]
and i fotgot to say when i dont use -D it is show
c:\hashcat>hashcat64.exe -b
hashcat (v3.6.0) starting in benchmark mode...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce 940MX, 512/2048 MB allocatable, 3MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) HD Graphics 620, skipped.
* Device #3: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, skipped.

Hashtype: MD4

Speed.Dev.#1.....:  2781.2 MH/s (72.24ms)

Hashtype: MD5
it is just skipped!!!

**Comment by mehrad100** [comment]
i'm really sorry for so much comment but i forgot this
c:\hashcat>hashcat64.exe -a3 -m 2500 gh.hccapx ?d?d?d?d?d?d?d?d
hashcat (v3.6.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce 940MX, 512/2048 MB allocatable, 3MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) HD Graphics 620, skipped.
* Device #3: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, skipped.

Hashes: 3 digests; 3 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>

Session..........: hashcat
Status...........: Running
Hash.Type........: WPA/WPA2
Hash.Target......: gh.hccapx
Time.Started.....: Sat Sep 23 10:46:22 2017 (5 secs)
Time.Estimated...: Sat Sep 23 11:34:59 2017 (48 mins, 32 secs)
Guess.Mask.......: ?d?d?d?d?d?d?d?d [8]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:    34276 H/s (10.00ms)
Recovered........: 0/3 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 168960/100000000 (0.17%)
Rejected.........: 0/168960 (0.00%)
Restore.Point....: 0/10000000 (0.00%)
Candidates.#1....: 72345678 -> 71899001
HWMon.Dev.#1.....: N/A

**Comment by jsteube** [comment]
GitHub issues are for posting bugs and feature requests only. Please use hashcat forum for usage questsions please.

**Comment by hussainashara** [comment]
Did you found the solution? then please tell me having same problem

**Comment by azamet90** [comment]
same problem here my nvidia gpu is skipped :(
