### ISSUE TITLE
Kernel m12000 Odd behaviour if atempted to produce more than 20 bytes output.

### ISSUE THREAD

**Issue by wdworks** [hashcat/hashcat#1369]
Hello!
I'm trying to add custom algorithm to hashcat based on PBKDF2-SHA1 in [m12000](https://github.com/hashcat/hashcat/blob/master/OpenCL/m12000.cl) kernel.

Normally it runs single iteration and produces 20 bytes output into  `pbkdf2_sha1_tmp` structure. It works great, but i need more than 20 bytes out of it, so i've attempted to slightly modify _loop kernel and change outer loop iterations count so it iterates twice and produce twice more data.

`

        -for (u32 i = 0; i < 4; i += 5){ 
        +for (u32 i = 0; i < 8; i += 5){ 
          u32x dgst[5];
          u32x out[5];

          dgst[0] = packv (tmps, dgst, gid, i + 0);
          dgst[1] = packv (tmps, dgst, gid, i + 1);
          dgst[2] = packv (tmps, dgst, gid, i + 2);
          dgst[3] = packv (tmps, dgst, gid, i + 3);
          dgst[4] = packv (tmps, dgst, gid, i + 4);

          out[0] = packv (tmps, out, gid, i + 0);
          out[1] = packv (tmps, out, gid, i + 1);
          out[2] = packv (tmps, out, gid, i + 2);
          out[3] = packv (tmps, out, gid, i + 3);
          out[4] = packv (tmps, out, gid, i + 4);

          for (u32 j = 0; j < loop_cnt; j++)
          {
            u32x w0[4];
            u32x w1[4];
            u32x w2[4];
            u32x w3[4];

            w0[0] = dgst[0];
            w0[1] = dgst[1];
            w0[2] = dgst[2];
            w0[3] = dgst[3];
            w1[0] = dgst[4];
            w1[1] = 0x80000000;
            w1[2] = 0;
            w1[3] = 0;
            w2[0] = 0;
            w2[1] = 0;
            w2[2] = 0;
            w2[3] = 0;
            w3[0] = 0;
            w3[1] = 0;
            w3[2] = 0;
            w3[3] = (64 + 20) * 8;

            hmac_sha1_run_V (w0, w1, w2, w3, ipad, opad, dgst);

            out[0] ^= dgst[0];
            out[1] ^= dgst[1];
            out[2] ^= dgst[2];
            out[3] ^= dgst[3];
            out[4] ^= dgst[4];
          }

          unpackv (tmps, dgst, gid, i + 0, dgst[0]);
          unpackv (tmps, dgst, gid, i + 1, dgst[1]);
          unpackv (tmps, dgst, gid, i + 2, dgst[2]);
          unpackv (tmps, dgst, gid, i + 3, dgst[3]);
          unpackv (tmps, dgst, gid, i + 4, dgst[4]);

          unpackv (tmps, out, gid, i + 0, out[0]);
          unpackv (tmps, out, gid, i + 1, out[1]);
          unpackv (tmps, out, gid, i + 2, out[2]);
          unpackv (tmps, out, gid, i + 3, out[3]);
          unpackv (tmps, out, gid, i + 4, out[4]);
        }

`

I've indeed got 40 bytes of output, however still only first 20 are correct (mathes the output of openssl [PKCS5_PBKDF2_HMAC](https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=crypto/evp/p5_crpt2.c).
Then i've got a thought that the dgst & out are initiated with padding in the m12000_init kernel which was only executed once so only first 5 dwords were initiated with padding.
I've tried to change the init loop counter the same way and output has changed, but it is still not correct.
I'm suspicious about:
`sha1_hmac_ctx_t sha1_hmac_ctx2 = sha1_hmac_ctx;` vs `HMAC_CTX_copy(hctx, hctx_tpl)`
Since it is not base type structure not sure if it is copied correctly by assignment.
But also maybe my logic is flawed and i'm doing it wrong.

Thanks in advance and keep up the awesome work you doing!

**Comment by philsmd** [comment]
let's step back a little bit and discuss this:
can you please explain why you really need more output?
20 bytes should be long enough to make sure that the password is indeed the correct one. From that perspective there is no need to have a longer output length.
The only valid reason for a longer output would be if you need to re-use the longer-than-20-byte output for further computation at later steps.
So what exactly is you reason you need to have longer output ? Do you need to do further computation with the output?

I think this discussion is not really suitable here. This is not a hashcat issue. It might fit in the Developer section of the hashcat.net forum. I don't think this is a problem of hashcat. This is just a general question. It is not a hashcat issue.

**Comment by wdworks** [comment]
Well, you probably right. Like i sad i'm trying to integrate the algo i'm researching into the hashcat to use all the great attack modes already implemented. So i need longer non standard kdf to use it than as a key etc. And because it is stated as "Generic KDF" i thought that it is appropriate starting point for my modification. I'm going to close the issue.
