### ISSUE TITLE
how can i use the checkpoint option in wpa cracking ?

### ISSUE THREAD

**Issue by minanagehsalalma** [hashcat/hashcat#1370]
latest hashcat  windows version  64 bit

**Comment by philsmd** [comment]
When you see this prompt:
`[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>`

you should press the key "c" (without quotes) and your status (to see it press "s", without quotes) should change to 
`Status...........: Running (Checkpoint Quit requested)`
after that you need to wait until the next checkpoint was reached (could take some time depending on your attack type and number of hashes etc).

BTW: this is not the correct place to ask questions. Github issues are only intended for problems/feature requests/development stuff. Please close the issue and (if you really can't figure it out at all with all the documentation wiki/faq/hashcat forums) you can open a new thread on the hashcat forum. Thx

**Comment by und3fined404** [comment]
How to continue from where I left?

**Comment by minanagehsalalma** [comment]
> How to continue from where I left?

Mate check the frekin wiki ... and he has already mentioned the answer up there  !!
https://hashcat.net/wiki/doku.php?id=restore

**Comment by und3fined404** [comment]
He didn't mention how to continue from where you left,
when one presses "c" it just says saved and that's about it.

**Comment by und3fined404** [comment]
Anyways here's the answer for the people accessing this Q&A from google
`hashcat --session session_name --restore`

**Comment by minanagehsalalma** [comment]
> He didn't mention how to continue from where you left,
> when one presses "c" it just says saved and that's about it.

Because he didn't need to ! 
I just used the wiki as he suggested.

**Comment by minanagehsalalma** [comment]
> Anyways here's the answer for the people accessing this Q&A from google
> `hashcat --session session_name --restore`

What did  you type in google to find this as a result and not the wiki ?!

**Comment by und3fined404** [comment]
> > Anyways here's the answer for the people accessing this Q&A from google
> > `hashcat --session session_name --restore`
> 
> What did you type in google to find this as a result and not the wiki ?!

how to use hashcat restore point

**Comment by minanagehsalalma** [comment]
> > > Anyways here's the answer for the people accessing this Q&A from google
> > > `hashcat --session session_name --restore`
> > 
> > 
> > What did you type in google to find this as a result and not the wiki ?!
> 
> how to use hashcat restore point

And you clicked on this not the wiki ?!
My question is a bit more different and specific 
"how can i use the checkpoint option in wpa cracking ?"

**Comment by und3fined404** [comment]
I actually specified the WPA cracking as well (typo)

**Comment by minanagehsalalma** [comment]
![Screenshot_2020-01-13-23-43-06-1](https://user-images.githubusercontent.com/20546638/72294588-88502180-365e-11ea-96ac-6acb6a3f5e51.png)
 the wiki is the first result in google

**Comment by minanagehsalalma** [comment]
> I actually specified the WPA cracking as well (typo)

Hm.. yup  mutual ideas/goals .... btw you would really need a very powerful gpu for wpa cracking to  be efficient.
