### ISSUE TITLE
it just doesn't work

### ISSUE THREAD

**Issue by globbergouhl** [hashcat/hashcat#1371]
I have tried installing hashcat on 5 different machines using several different online tutorials and it just does not work.  The closest I have some to get this working is following this tutorial:

https://mark911.wordpress.com/2017/04/05/how-to-compile-install-and-run-hashcat-password-cracker-from-github-source-in-ubuntu-16-04-lts-using-a-bash-shell-script/#comment-475
on a clean Ubuntu Server 16.04 LTS (as Amazon t2.micro EC2 instance)

However, trying to run a basic dictionary attack, I get: 

> Cannot find an OpenCL ICD loader library

I have no idea what this means, but after some research I did 

`sudo apt-get install olc-icd-libopencl1`

but when I run hashcat again , I get:

> clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

There seems to be no solution to this error anywhere. What am I missing here?

**Comment by roycewilliams** [comment]
Your OpenCL is either broken, or your cards are not supported by the NVIDIA drivers themselves.

https://hashcat.net/faq/wrongdriver/

This question should probably on the Hashcat forums instead, as this isn't a problem with hashcat itself. Github issues are only intended for problems/feature requests/development stuff. Please close the issue and (if you really can't figure it out at all with all the documentation wiki/faq/hashcat forums) you can open a new thread on the hashcat forum.

**Comment by globbergouhl** [comment]
I don't know what that means.  What NVIDIA drivers and what "cards" are you referring to? I am using an EC2 instance with no GPU. Also, how could OpenGL possibly be broken if I got it via 
`sudo apt-get install olc-icd-libopencl1`

**Comment by roycewilliams** [comment]
Hashcat requires a working installation of OpenCL for both CPU and GPU.

Please close this issue and open a forums thread instead.

**Comment by globbergouhl** [comment]
Sorry for the back and forth, but you are assuming I know more than I do. Would hashcat work at all on a machine that does not even have a GPU?

**Comment by roycewilliams** [comment]
Yes. But that is a question for the forums, too. :)

Please close this issue and open a forums thread instead.
