### ISSUE TITLE
feature: expanded version information

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#138]
In the new world of open source and publicly available betas, it might be handy to have the git commit hash in both the output of -h/--help/-V/--version, and the general "oclHashcat vX.YY starting" messages.

This allows precise version identification in pasted/posted output, when bugs are reported/fixed, etc. 

It might be useful to leave it out for official binary releases, so that they can be clearly differentiated from any and all self-compiled/test/unofficial/beta versions. Or a "-release" suffix might be used instead, to explicitly disambiguate.

One possible method:

```
$ ./oclHashcat -V
2.10 (30293a0)

$ ./oclHashcat -h | head -2
oclHashcat, advanced password recovery
v2.10 (30293a0)

$ ./oclHashcat -b -m 1500
oclHashcat v2.10 (30293a0) starting in benchmark-mode...
[snip]
```

... or:

```
$ ./oclHashcat -V
2.10-30293a0

$ ./oclHashcat -h | head -2
oclHashcat, advanced password recovery
v2.10-30293a0

$ ./oclHashcat -b -m 1500
oclHashcat v2.10-30293a0 starting in benchmark-mode...
[snip]
```

... with official binary releases either using the current basic version number only, or a simple tag:

```
$ ./oclHashcat -V
2.10

$ ./oclHashcat -V
2.10-release

$ ./oclHashcat -V
2.10 (release)
```

**Comment by philsmd** [comment]
would it be okay if we just append the compile time to the version number information ?
There is a variable COMPTIME used within the Makefile for such purposes.

Why not git commit hash? Because somtimes (well, not that often, but rarely) it happens that betas will be compiled just for testing (even before every piece of new/changed code was committed) and therefore we do not know any git commit SHA1 hash at that time.
On the other hand, adding COMPTIME to the version number should be fine (in my opinion).
What do you think ? @roycewilliams would that be okay?

**Comment by roycewilliams** [comment]
Thanks for the opportunity to weigh in. This may seem like a bit of trouble -- but once the effort is invested, it will benefit many future developers, testers, troubleshooters and researchers forever. :)

I hadn't thought about the "compile from uncommitted changes and publish that" corner case -- good point.

I agree that compile time alone is useful if commit hash is unavailable or there are uncommitted changes.  But the real value is in being able to compare apples to apples over time for a variety of code states -- and commit hash is almost always the best approximation of that.  IMO, it should be used if it's available. And even when there are betas compiled just for testing, knowing what commit they are _derived from_ is useful.

So I'd like to propose always including the commit hash, and if there are uncommitted changes, appending a clean datestamp (and I see that COMPTIME is now based on `date +%s`, so that's perfect).  

So if it's possible (and I don't know if it is), maybe something like (pseudocode):

```
VERSION_STAMP := $(shell git rev-parse HEAD | cut -b1-7)
if (there_are_uncommitted_changes), then
    VERSION_STAMP := $(VERSION_STAMP)_$(COMPTIME);
```

This would cover the somewhat rare test-compile case cleanly, and still enable future researchers and testers to compare known outputs. And at a glance, everyone can tell if it was based on a specific commit or a local compile (and if a local compile, the commit it was based on).

The Makefile would have to know to skip this step if git is not available, of course.  And I've never scripted a check for uncommitted changes, but this looks like a reasonable shell-based approach:
http://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes

EDIT: changed separator to underscore, fixed some formatting.

**Comment by roycewilliams** [comment]
Once this functionality is available, it would also be awesome if betas pushed to /beta/ had the version stamp appended to the base of the filename, as in:

```
oclHashcat-2.10b61-cd430d5.7z
```

or 

```
oclHashcat-2.10b61-cd430d5_1453306037.7z
```

This way, potential testers can tell at a glance if the code was at a point where testing is relevant for them, and exactly which changes are in play (to the extent feasible).

Royce

**Comment by magnumripper** [comment]
Here's a wonderful way to produce a version string (here applied in oclHashcat master branch):

```
$ git describe --tags --dirty=+
v2.01-289-gcd430d5
```

What it says is
- Name of latest tag/release (v2.01)
- Number of commits past that tag (289)
- And finally a commit hash prepended with g (cd430d5).

Note that a dirty tree (uncommitted changes) would show as "v2.01-289-gcd430d5+" so you would know that it was based upon cd430d5.

**Comment by epixoip** [comment]
^ that's the proper way to do it

**Comment by roycewilliams** [comment]
+1. Covers all of the bases reasonably, I think.

**Comment by jsteube** [comment]
In general I liked the idea, thanks! I'll push a patch to use "git describe --tags --dirty=+". 

But, I don't want it to be shown on startup screen nor the --help menu. It will be shown when using the -V argument.

It's hard to explain my reasons for this, basically it goes back a mix of gut feelings, design and practical use reasons.

I haven't decided if we'll change the filename convention as you suggested. It's possible that I'll add another push related to this issue, therefore I'll let it open for a while. Feel free to convince me if you really want it in startup screen and --help menu.

**Comment by roycewilliams** [comment]
Awesome!  OK, here's my elevator pitch:

Posted information about hashing speeds matter - for dev, for troubleshooting, for shopping for GPUs, for academic research, etc.  Now that hashcat is open source and people can be running arbitrary versions, knowing what version was used to create a given piece of output is important. The best way to ensure that all current (and future) uses of output -- most especially, benchmarks and cracking runs -- can be closely tied to what algorithms/code was in use is to include the commit information.

If leaving it out of --help is better, I've got no problem with that at all.  But I believe strongly that there is significant value in including it in the startup (so that it shows up in benchmarks and cracking runs).  Knowing which code they came from matters more than it used to.

**Comment by jsteube** [comment]
OK, we'll do that. My only concern is that beta tester need to understand that new output. For example at this time it will show v2.01 + X instead v2.10. This is very technical and even if this is more correct from a developing view it can be confusing for normal users, even beta testers.

**Comment by epixoip** [comment]
I don't think it will be an issue. If anything it should be less confusing rather than more confusing.

**Comment by magnumripper** [comment]
You could tag each beta (as in 2.10b61) and it would be reflected in the version string. Actually you _should_ do that - how else are you going to find a particular beta in the Git history if needed?

Unfortunately Github will list ANY tag as a "release". But it should not matter much.

**Comment by jsteube** [comment]
The checksum in the version string from git describe --tags --dirty=+ is the first 7 chars from the commit hash that you can find git log. Note that I'm not commiting each beta I create therefore I can't add any tags

**Comment by jsteube** [comment]
@roycewilliams do you think we can close this issue?

**Comment by roycewilliams** [comment]
Yes - done.
