### ISSUE TITLE
[Feature request] Lucky Mask Attack Mode

### ISSUE THREAD

**Issue by Szeak** [hashcat/hashcat#1380]
Hi,

We need a Lucky Mask Attack mode for the software.

The problem: We know that the brute force attack takes as long time, how many isn't in our life.

Solution: The Lucky Mask (Brute force) Attack Mode gives us a chance to found the password within a set of time. So this mode must generating random passwords by the given mask, and hash it to check reaching the target hash (or any algorithm). Do it for a given time maximum long, ie.: 5min or 1h etc., or stop searching, when password found of course.

Our exactly need to find a 64 character long password (which can contains only cahracters 0-9 and a-f /maybe a hex representation of something/) from SHA-256 hash code.
But it may be useful for everyone else.

Thank you, best regards.

Szeak

**Comment by roycewilliams** [comment]
This will not work the way that you think it will work.

https://hashcat.net/forum/thread-6293.html

**Comment by Chick3nman** [comment]
So...chained SHA256 to try and derive the "Hash of the day" likely from a gambling site? Probably shouldn't be doing that.

**Comment by Szeak** [comment]
Ok, yes i want luckily to crack server seed on a site where can win free bitcoins. By posted forum thread, i can generate random passwords now. thank you.
I thinking of generating speed. It looks like a bit slow for GPU cracking, wich can calculate extremly more hashes per second than passwords CPU can generates/s. ??? any idea?

**Comment by roycewilliams** [comment]
@Szeak, the point of that thread wasn't to show you how to generate random passwords. It was to demonstrate how useless it is.
