### ISSUE TITLE
CPU not used when running on GPU

### ISSUE THREAD

**Issue by globbergouhl** [hashcat/hashcat#1381]
When I run on GPU, GPU load is 100% but CPU is not used at all. How to force GPU and CPU load to 100%.

**Comment by neheb** [comment]
Add -D 1,2 to command line. Usually not a good idea

**Comment by globbergouhl** [comment]
Why not good idea?

**Comment by neheb** [comment]
Nvidia has a runtime bug that causes 100% CPU usage. Additionally, overall speeds probably won't increase. I think the CPU slows the GPU down. You'll have to test.

**Comment by globbergouhl** [comment]
for me works! speed is almost perfectly additive. Btw, I am on Amazon g2.2xlarge instance with 8CPU and 1 GPU.

**Comment by philsmd** [comment]
I think this problem was solved by using the --opencl-device-types (short -D) command line parameter.
@globbergouhl can you please close the issue if you think this problem is solved?
