### ISSUE TITLE
Long start time

### ISSUE THREAD

**Issue by amitaymolko** [hashcat/hashcat#1388]
When running on a server with multiple GPUs (8) it takes some time (~1 min) to warmup.
But if I run a second hashcat right after the first one finishes it needs to warmup again.
Is there anyway to reduce the second warmup time?

**Comment by jsteube** [comment]
Unless you use some kernel code that can not be cached (scrypt based, cisco $9$, descrypt, lm) there's no way to improve startup time, at least not in hashcat. It's not hashcat hanging, it's the OpenCL runtime.

**Comment by amitaymolko** [comment]
ok thanks
