### ISSUE TITLE
all passwords rejected

### ISSUE THREAD

**Issue by globbergouhl** [hashcat/hashcat#1390]
why when using dictionary + rules, almost all candidate pw rejected (Rejected = 98%) for WPA2? wordlist has many words with below minimum number of characters (min is 8), but with rules should add characters so that more become longer than min length. it seem potential pw get rejected before rule applied? this beg two question:
1) how to perform setting such that only ever reject after rule applied?
2) speed in kH/s is include or exclude rejected password? For example, if say 100kH/s but 99% rejected, reality is only 1kH/s?

**Comment by jsteube** [comment]
rules which apply on device can be of arbitrary size, therefore they cannot be checked at this point. the correct use would be to use a pipe, like this:

```
hashcat wordlist.txt -r rule.txst --stdout | hashcat -m 2500 your.hccapx
```

i'm closing this because this is not a hashcat bug and github issues are only for bugs and feature requests. please use hashcat forum for usage questions.

**Comment by globbergouhl** [comment]
what about second question? is "speed" number cleaned of rejected? if not, this would be a bug.
Also, running command as you suggested gives other bug: I run 
`hashcat wordlist.txt -r rule.txst --stdout | hashcat -m 2500 your.hccapx -w 4 -D 1,2`
now give output every 10 seconds or so and no more time till competion which makes sense. But Candidates.#1 (GPU) line in output only changes every 10 updates or so (sigh), while Candidates.#2 (CPU) changes every update, meaning GPU try same password many times?
Btw, exist no documentation about what is correct interpretation of this line anyway: 
`Candidates.#1 Lamabrta -> ehaillaster`
