### ISSUE TITLE
hashcat trys same passwords over and over

### ISSUE THREAD

**Issue by globbergouhl** [hashcat/hashcat#1391]
I run

> hashcat wordlist.txt -r rule.txst --stdout | hashcat -m 2500 your.hccapx -w 4 -D 1,2

But Candidates.#1 (GPU) line in output only changes every 10 updates or so (sigh), while Candidates.#2 (CPU) changes every update, meaning GPU try same password many times?
Btw, exist no documentation about what is correct interpretation of this line anyway:

> Candidates.#1 Lamabrta -> ehaillaster

**Comment by jsteube** [comment]
It's fine, GPU needs much more work to assign at once than a CPU.

**Comment by globbergouhl** [comment]
answer makes no sense, it's GPU which does not update. please do not close issue before resolved. If does more than 1 hash/10 seconds, should always show different candidate already. Mine does 100kH/s and shows same after 10 seconds.

**Comment by Chick3nman** [comment]
Please take this question and others like it to the forums. The candidates displayed are the selection of current work, from point A - point Z. If the GPU can do 1 candidate at a time, it will load up a chunk of work, such as A,B,C,D,E,F,G,H,I and display A-I while it process through them 1 at a time. It will not update the chunk of work until it finishes. If it loads a chunk such as A-I and has only made it to candidate G when the status is printed, it will still display A-I.
