### ISSUE TITLE
hashtag fails to run when symlinked to root filesystem

### ISSUE THREAD

**Issue by juanitotc** [hashcat/hashcat#1393]
tinycorelinux packages apps using the squashfs and then loop mounts and symlinks them to the root filesystem

/usr/local/bin/hashcat -> /tmp/tcloop/hashcat/usr/local/bin/hashcat

..but hashcat will not run like this:

~$ hashcat -b -m 1000 --opencl-device-types 1 --opencl-platforms 1 --force
hashcat (pull/1273/head) starting in benchmark mode...

/tmp/tcloop/hashcat/usr/local/bin/OpenCL/: No such file or directory

*** Error in `hashcat': corrupted double-linked list: 0x0000000000d92160 ***
======= Backtrace: =========
/lib/libc.so.6(+0x5f2cc)[0x7f8b049302cc]
/lib/libc.so.6(+0x63a45)[0x7f8b04934a45]
/lib/libc.so.6(+0x6490d)[0x7f8b0493590d]
hashcat[0x458405]
hashcat[0x41e48a]
hashcat[0x4033d7]
/lib/libc.so.6(__libc_start_main+0x15a)[0x7f8b048f1e9e]
hashcat[0x40463a]
======= Memory map: ========
00400000-00482000 r-xp 00000000 07:7e 4                                  /tmp/tcloop/hashcat/usr/local/bin/hashcat
00681000-00682000 r--p 00081000 07:7e 4                                  /tmp/tcloop/hashcat/usr/local/bin/hashcat
00682000-00683000 rw-p 00082000 07:7e 4                                  /tmp/tcloop/hashcat/usr/local/bin/hashcat
00d7e000-00d9f000 rw-p 00000000 00:00 0                                  [heap]
7f8b00000000-7f8b00021000 rw-p 00000000 00:00 0 
7f8b00021000-7f8b04000000 ---p 00000000 00:00 0 
7f8b046bf000-7f8b046d0000 r-xp 00000000 00:02 1309                       /usr/lib/libgcc_s.so.1
7f8b046d0000-7f8b048cf000 ---p 00011000 00:02 1309                       /usr/lib/libgcc_s.so.1
7f8b048cf000-7f8b048d0000 r--p 00010000 00:02 1309                       /usr/lib/libgcc_s.so.1
7f8b048d0000-7f8b048d1000 rw-p 00011000 00:02 1309                       /usr/lib/libgcc_s.so.1
7f8b048d1000-7f8b04a2c000 r-xp 00000000 00:02 1469                       /lib/libc-2.24.so
7f8b04a2c000-7f8b04c2c000 ---p 0015b000 00:02 1469                       /lib/libc-2.24.so
7f8b04c2c000-7f8b04c30000 r--p 0015b000 00:02 1469                       /lib/libc-2.24.so
7f8b04c30000-7f8b04c32000 rw-p 0015f000 00:02 1469                       /lib/libc-2.24.so
7f8b04c32000-7f8b04c37000 rw-p 00000000 00:00 0 
7f8b04c37000-7f8b04c39000 r-xp 00000000 00:02 1472                       /lib/libdl-2.24.so
7f8b04c39000-7f8b04e38000 ---p 00002000 00:02 1472                       /lib/libdl-2.24.so
7f8b04e38000-7f8b04e39000 r--p 00001000 00:02 1472                       /lib/libdl-2.24.so
7f8b04e39000-7f8b04e3a000 rw-p 00002000 00:02 1472                       /lib/libdl-2.24.so
7f8b04e3a000-7f8b04e50000 r-xp 00000000 00:02 1480                       /lib/libpthread-2.24.so
7f8b04e50000-7f8b0504f000 ---p 00016000 00:02 1480                       /lib/libpthread-2.24.so
7f8b0504f000-7f8b05050000 r--p 00015000 00:02 1480                       /lib/libpthread-2.24.so
7f8b05050000-7f8b05051000 rw-p 00016000 00:02 1480                       /lib/libpthread-2.24.so
7f8b05051000-7f8b05055000 rw-p 00000000 00:00 0 
7f8b05055000-7f8b05073000 r-xp 00000000 00:02 1466                       /lib/ld-2.24.so
7f8b05265000-7f8b05267000 rw-p 00000000 00:00 0 
7f8b0526f000-7f8b05272000 rw-p 00000000 00:00 0 
7f8b05272000-7f8b05273000 r--p 0001d000 00:02 1466                       /lib/ld-2.24.so
7f8b05273000-7f8b05274000 rw-p 0001e000 00:02 1466                       /lib/ld-2.24.so
7f8b05274000-7f8b05275000 rw-p 00000000 00:00 0 
7fff3ed81000-7fff3eda2000 rw-p 00000000 00:00 0                          [stack]
7fff3edf1000-7fff3edf3000 r--p 00000000 00:00 0                          [vvar]
7fff3edf3000-7fff3edf5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

$ sudo cp /tmp/tcloop/hashcat/usr/local/bin/hashcat /usr/local/bin
~$ hashcat -b -m 1000 --opencl-device-types 1 --opencl-platforms 1 --force
hashcat (pull/1273/head) starting in benchmark mode...

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 18075/18075 MB allocatable, 4MCU

Hashtype: NTLM

Speed.Dev.#1.....: 75338.2 kH/s (55.58ms)

Started: Tue Oct 17 15:37:27 2017
Stopped: Tue Oct 17 15:37:46 2017

**Comment by jsteube** [comment]
ultra outdated version, please use latest and reopen if not fixed

**Comment by juanitotc** [comment]
v3.6.0 Jun 9, 2017 is "ultra outdated"?

**Comment by jsteube** [comment]
Oh yeah, you may want to check the commit logs of the last 4 month ;)

**Comment by magnumripper** [comment]
On another note, it's called hashcat, not hashtag 😂 😂

**Comment by roycewilliams** [comment]
From a downstream maintainer's perspective, "outdated" usually means "there's a later release available". :) 3.6.0 is indeed the most recent formal release. (Many changes have been made in preparation for the next release, but it is not yet released (but very close)).
