### ISSUE TITLE
hashtag from latest git fails to run when symlinked to root filesystem

### ISSUE THREAD

**Issue by juanitotc** [hashcat/hashcat#1394]
Ref: https://github.com/hashcat/hashcat/issues/1393

$ hashcat -b -m 1000 --opencl-device-types 1 --opencl-platforms 1 --force
hashcat (4.0.0-rc6) starting in benchmark mode...
...
/tmp/tcloop/hashcat/usr/local/bin/OpenCL/: No such file or directory

$ sudo cp /tmp/tcloop/hashcat/usr/local/bin/hashcat /usr/local/bin
tc@boxdell:~$ hashcat -b -m 1000 --opencl-device-types 1 --opencl-platforms 1 --force
hashcat (4.0.0-rc6) starting in benchmark mode...
...
OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 18075/18075 MB allocatable, 4MCU

Benchmark relevant options:
===========================
* --force
* --opencl-device-types=1
* --opencl-platforms=1
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.Dev.#1.....: 75168.1 kH/s (55.73ms)

Started: Tue Oct 17 17:03:52 2017
Stopped: Tue Oct 17 17:04:08 2017

**Comment by jsteube** [comment]
That looks much better (no more segfault). Still, the package maintainer seem to have it installed incorrectly, therefore the error message is correct. Not a hashcat error, therefore closing.

**Comment by juanitotc** [comment]
I am the package maintainer and it has not been installed incorrectly - the contents of the package can be seen here:

http://tinycorelinux.net/8.x/x86_64/tcz/hashcat.tcz.list

**Comment by jsteube** [comment]
You need to make sure that the realpath of argv[0] matches the INSTALL_FOLDER, otherwise hashcat looks for it's local content in the realpath folder. IOW, you need so fix the path in the Makefile (which is job of the package maintainer from my perspective).

**Comment by juanitotc** [comment]
..but literally hundreds of apps packaged exactly like this work without problems.

In the few cases where apps packaged like this have not worked (eg the folks contacts app), the maintainers have kindly agreed to modify the code so that it follows symlinks as would be expected.

It would seem logical that the symlinked hashcat looks for data in /usr/local/share/hashcat/OpenCL or /tmp/tcloop/hashcat/usr/local/share/hashcat/OpenCL, either of which would work, but it doesn't.
