### ISSUE TITLE
support for sha1(md5($pass.$username).$salt) hashes

### ISSUE THREAD

**Issue by demo555** [hashcat/hashcat#1395]
I am requesting that the sha1(md5($pass.$username).$salt) hashes type 
here is a example: 
username:86542565@qq.com 
pass:11111111Q
salt:kz;FMYfHEycaJuGIJZhK@s04),Jr16&($tG4DCz~
hash:955e59e4a26aeacc2dec77c1cf1dc1724b221520 #

**Comment by jsteube** [comment]
where is it used in?
