### ISSUE TITLE
version blank on Mac after building from source release

### ISSUE THREAD

**Issue by sloopjon** [hashcat/hashcat#1403]
When I built hashcat v3.6.0 from the June 9 source release on macOS 10.12.6 using the command line tools for Xcode 8.3.2, I saw the following error message:

    $ make
    sed: illegal option -- r

After the build completed, the output of the -V option was blank:

    $ ./hashcat -V
    
    $ 

After changing the -r option to -E on the `VERSION_TAG` line of the Makefile and rebuilding, the -V option worked as expected:

    $ ./hashcat -V
    v3.6.0
    $ 

This should be simple enough to fix in the general case with something like the `SED_IN_PLACE` variable. However, it's not clear to me whether this sed command is still used to populate the version.  It's commented out in the repo, with the `VERSION_TAG` hard coded.

**Comment by jsteube** [comment]
I can't say much on the SED_IN_PLACE behavior of macOS since I do not own a macOS compatible system.

The reason for VERSION_TAG being hardcoded is just temporarily due the RC phase and it will be switched back to the commented version when we do the release / normal work afterwards.

**Comment by philsmd** [comment]
It should be easy to replace the:
-r, --regexp-extended     use extended regular expressions in the script.
we currently use with a different regular expression for sed that does not need the "-r" option
