### ISSUE TITLE
Clang-format support

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#1405]
README says Allman style. I played a little with clang-format to see if I can get something similar to the current code. Not quite but meh. Real question is, anyone interested in seeing a .clang-format file in the repository? git integration is available as well.

Current .clang-format file: 

AlignConsecutiveAssignments: true
AllowShortIfStatementsOnASingleLine: true
BasedOnStyle: LLVM
BreakBeforeBraces: Allman
ColumnLimit: 0
IndentCaseLabels: true
SpaceAfterCStyleCast: true
SpaceBeforeParens: Always
SpacesBeforeTrailingComments: 1

comments welcome.

**Comment by jsteube** [comment]
I think it depends on how much it breaks readability. If the changes done are minor I think we can live with a compromise. If you want, try to get as close as possible to original formating. We can then do a comparison and decide.
