### ISSUE TITLE
clCreateContext(): CL_DEVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by mostafa88** [hashcat/hashcat#1409]
Hi,
I download hashcat version 3.6.0 and want to run it's first example just on my CPU. So I added the "--opencl-platforms=2" commands to exampl0. But it return the following error. "clCreateContext(): CL_DEVICE_NOT_AVAILABLE".

Here is the information about my OpenCL platform that return by: hashcat64 -I 
```
OpenCL Info:
Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.1 CUDA 6.0.1

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce 9300M GS
    Version        : OpenCL 1.0 CUDA
    Processor(s)   : 1
    Clock          : 1450
    Memory         : 128/256 MB allocatable
    OpenCL Version : OpenCL C 1.0
    Driver Version : 337.88

Platform ID #2
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) OpenCL
  Version : OpenCL 1.2

  Device ID #2
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Core(TM)2 Duo CPU     T9550  @ 2.66GHz
    Version        : OpenCL 1.2 (Build 25)
    Processor(s)   : 2
    Clock          : 2660
    Memory         : 511/511 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 6.4.0.25

Platform ID #3
  Vendor  : Intel(R) Corporation
  Name    : Experimental OpenCL 2.1 CPU Only Platform
  Version : OpenCL 2.1

  Device ID #3
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Core(TM)2 Duo CPU     T9550  @ 2.66GHz
    Version        : OpenCL 2.1 (Build 10)
    Processor(s)   : 2
    Clock          : 2660
    Memory         : 511/511 MB allocatable
    OpenCL Version : OpenCL C 2.0
    Driver Version : 7.0.0.2519
```
I installed  "opencl_runtime_16.1.1_x64_setup".
I have this problem on windows7 SP1 and ubuntu 16.04 (LTS) virtual machine and physical machine.

Thank you in advance for any help you can provide.

**Comment by philsmd** [comment]
are you sure that this old CPU (Core Duo) even supports OpenCL ?
It seems that the drivers do support only i3 or newer (or xeon CPUs).

https://stackoverflow.com/questions/16647567/opencl-sdk-for-intel-core-2-due/16650270#16650270

**Comment by mostafa88** [comment]
@philsmd : 
You are right, hashcat 3.6.0 need this driver
`Intel CPUs require "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)` that need support SSE 4.2 where Inter Core 2 Due supoort  SSE 4.1. So I cannot run hashcat 3.6.0 on and proper opencl driver on my laptop.
