### ISSUE TITLE
Display Set Cost/Rounds During Benchmarking

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1410]
Display the number of rounds or the cost of the algorithm during benchmarking.

Example:
```
Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix)

Speed.Dev.#1.....:    54655 H/s (183.03ms)
Speed.Dev.#2.....:    54639 H/s (182.95ms)
Speed.Dev.#3.....:    54330 H/s (183.78ms)
Speed.Dev.#4.....:    54652 H/s (183.01ms)
Speed.Dev.#*.....:   218.3 kH/s
```
Cost not shown, even though it is known to some to be 05. This can be confusing for new users or users unaware of what the default benchmarking cost is.

**Comment by jsteube** [comment]
Feel free to modify the output of the code. Shouldn't be too hard.

**Comment by jsteube** [comment]
Added with https://github.com/hashcat/hashcat/commit/9aa9725b9104702355465fb4a778c4ef8420a250
