### ISSUE TITLE
4.0.0 build failure

### ISSUE THREAD

**Issue by ilovezfs** [hashcat/hashcat#1412]
REF: https://github.com/Homebrew/homebrew-core/pull/19948

For a full log see https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/11773/version=sierra/consoleText
(duplicate in case that gets deleted https://gist.github.com/ilovezfs/82ff5572a74b6e14871c3f5af3ab352e)

The error is
```
clang    -pipe -std=gnu99 -Iinclude/ -Iinclude/lzma_sdk/ -IOpenCL/ -O2 src/main.c obj/affinity.NATIVE.STATIC.o obj/autotune.NATIVE.STATIC.o obj/benchmark.NATIVE.STATIC.o obj/bitmap.NATIVE.STATIC.o obj/bitops.NATIVE.STATIC.o obj/combinator.NATIVE.STATIC.o obj/common.NATIVE.STATIC.o obj/convert.NATIVE.STATIC.o obj/cpt.NATIVE.STATIC.o obj/cpu_aes.NATIVE.STATIC.o obj/cpu_crc32.NATIVE.STATIC.o obj/cpu_des.NATIVE.STATIC.o obj/cpu_md4.NATIVE.STATIC.o obj/cpu_md5.NATIVE.STATIC.o obj/cpu_sha1.NATIVE.STATIC.o obj/cpu_sha256.NATIVE.STATIC.o obj/debugfile.NATIVE.STATIC.o obj/dictstat.NATIVE.STATIC.o obj/dispatch.NATIVE.STATIC.o obj/dynloader.NATIVE.STATIC.o obj/event.NATIVE.STATIC.o obj/ext_ADL.NATIVE.STATIC.o obj/ext_nvapi.NATIVE.STATIC.o obj/ext_nvml.NATIVE.STATIC.o obj/ext_OpenCL.NATIVE.STATIC.o obj/ext_sysfs.NATIVE.STATIC.o obj/ext_xnvctrl.NATIVE.STATIC.o obj/ext_lzma.NATIVE.STATIC.o obj/lzma_sdk/Alloc.NATIVE.STATIC.o obj/lzma_sdk/Lzma2Dec.NATIVE.STATIC.o obj/lzma_sdk/LzmaDec.NATIVE.STATIC.o obj/filehandling.NATIVE.STATIC.o obj/folder.NATIVE.STATIC.o obj/hashcat.NATIVE.STATIC.o obj/hashes.NATIVE.STATIC.o obj/hlfmt.NATIVE.STATIC.o obj/hwmon.NATIVE.STATIC.o obj/induct.NATIVE.STATIC.o obj/interface.NATIVE.STATIC.o obj/locking.NATIVE.STATIC.o obj/logfile.NATIVE.STATIC.o obj/loopback.NATIVE.STATIC.o obj/memory.NATIVE.STATIC.o obj/monitor.NATIVE.STATIC.o obj/mpsp.NATIVE.STATIC.o obj/opencl.NATIVE.STATIC.o obj/outfile_check.NATIVE.STATIC.o obj/outfile.NATIVE.STATIC.o obj/pidfile.NATIVE.STATIC.o obj/potfile.NATIVE.STATIC.o obj/restore.NATIVE.STATIC.o obj/rp.NATIVE.STATIC.o obj/rp_cpu.NATIVE.STATIC.o obj/rp_kernel_on_cpu.NATIVE.STATIC.o obj/rp_kernel_on_cpu_optimized.NATIVE.STATIC.o obj/selftest.NATIVE.STATIC.o obj/shared.NATIVE.STATIC.o obj/status.NATIVE.STATIC.o obj/stdout.NATIVE.STATIC.o obj/straight.NATIVE.STATIC.o obj/terminal.NATIVE.STATIC.o obj/thread.NATIVE.STATIC.o obj/timer.NATIVE.STATIC.o obj/tuningdb.NATIVE.STATIC.o obj/usage.NATIVE.STATIC.o obj/user_options.NATIVE.STATIC.o obj/wordlist.NATIVE.STATIC.o                -s -framework OpenCL -lpthread -liconv -DCOMPTIME=1509128756 -DVERSION_TAG=\"HEAD -> master, tag: v4.0.0\" -DINSTALL_FOLDER=\"/usr/local/Cellar/hashcat/4.0.0/bin\" -DSHARED_FOLDER=\"/usr/local/Cellar/hashcat/4.0.0/share/hashcat\" -DDOCUMENT_FOLDER=\"/usr/local/Cellar/hashcat/4.0.0/share/doc/hashcat\" -o hashcat
clang: error: -E or -x required when input is from standard input
clang: error: no such file or directory: 'tag:'
clang: error: no such file or directory: 'v4.0.0"'
make: *** [hashcat] Error 1
```

It seems that
```
    inreplace "src/Makefile", '| $(SED) \'s/.*: v\([\.0-9]*\),.*/v\1/\')',
                              '| $(SED) \'s/.*: v\([\.0-9]*\),\?.*/v\1/\')'
```
is an effective workaround in the Homebrew formula (courtesy of @JCount)

**Comment by ilovezfs** [comment]
Also part of the workaround, it seems these need to be manually set
```
SED=gsed SED_IN_PLACE=-i
```

**Comment by jsteube** [comment]
If you have a solution for the needed Makefile changes please send in a PR

**Comment by ilovezfs** [comment]
I'd suggest reverting https://github.com/hashcat/hashcat/commit/c6d7fc845dfcde15af332b40ac19def13a9334b8.

**Comment by philsmd** [comment]
This problem might be related to the recent patch for this issue: https://github.com/hashcat/hashcat/issues/1403
The patch was successfully tested on a mac mini.

It's also interesting to note that the format of the "VERSION_EXPORT" variable did change which would make this sed command behave incorrectly.
The replace from the "git archive" for version 3.6 was:
VERSION_EXPORT          := tag: v3.6.0, refs/pull/1273/head

while the format for the new source tar.gz is:
VERSION_EXPORT          := HEAD -> master, tag: v4.0.0

Therefore the sed which is looking for "v" + some numbers (and dots) + "," is not correct anymore.

**Comment by philsmd** [comment]
reverting c6d7fc8 is not an option, because we do not want to have the hard coded "4.0.0-rc6" within the Makefile

**Comment by philsmd** [comment]
My conclusion is, that since we have no more a tag like this:
": v4.0.0,"
but only this substring:
": v4.0.0"
(without the comma ",", and the tag information could be at the end)

... my suggestion is that we replace this:
`sed 's/.*: v\([\.0-9]*\),.*/v\1/'`
by
`sed 's/.*: v\([\.0-9]*\).*/v\1/'`
(no comma needed)

**Comment by ilovezfs** [comment]
yes
```
diff --git a/src/Makefile b/src/Makefile
index 2173355..a3c9b2b 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -127,7 +127,7 @@ COMPTIME                := $(shell date +%s)
 # the value will be something like this: "tag: vX.Y.Z, refs/pull/Y/head"
 
 VERSION_EXPORT          := HEAD -> master, tag: v4.0.0
-VERSION_TAG             := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)" | $(SED) 's/.*: v\([\.0-9]*\),.*/v\1/')
+VERSION_TAG             := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)" | $(SED) 's/.*: v\([\.0-9]*\).*/v\1/')
 
 ##
 ## General compiler and linker options
```
seems to work

**Comment by jsteube** [comment]
Thanks!

**Comment by ilovezfs** [comment]
@jsteube shall I backport the fix or do you want to cut a new release?

**Comment by jsteube** [comment]
A good question. I'd say go with the backport for now. Maybe I'll change my mind but currently I'd like to stay with 4.0.0.

**Comment by ilovezfs** [comment]
@jsteube no worries

**Comment by ilovezfs** [comment]
4.0.0 shipped in Homebrew! Thanks again @philsmd and @jsteube!

**Comment by rjzak** [comment]
For whatever it's worth, I'm trying to install hashcat 4.0.0 from the tarball on the website, and I had to manually change the VERSION_TAG line in the Makefile to get it to compile on Ubuntu 16.04. So it seems the fix didn't make it to the website.

`VERSION_TAG            := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)" | $(SED) 's/.*: v\([\.0-9]*\).*/v\1/')`

**Comment by jsteube** [comment]
but 4.0.1 fixed that already

**Comment by rjzak** [comment]
Yup.. I missed the latest download link on the website. Sorry.
