### ISSUE TITLE
keepass inlined hash

### ISSUE THREAD

**Issue by jackpit110** [hashcat/hashcat#1415]
keepass2john supports inlined kdb files
if i have a 300kb file result would be 300kb hash
please add support for cracking long generated hashes
hashcat cant load this hashes
`https://github.com/magnumripper/JohnTheRipper/issues/1026`

**Comment by jackpit110** [comment]
@Fist0urs
we need more than 50k. could you give me a clue. i am in a hurry.
https://github.com/hashcat/hashcat/pull/282

**Comment by jackpit110** [comment]
OpenCL/types_ocl.c in old version is 50kb
`  u32 contents[12500];`
and in new increased to 300000 bytes
`  u32 contents[75000];`
Also other parts like maxlen increased but below line in src/interface.c is still 50000. i think this part should be increased
`    if (contents_len > 50000) return (PARSER_SALT_LENGTH);`

I increased these parts but hashcat still can not load large hash.

**Comment by jackpit110** [comment]
ok
i have increased HCBUFSIZ_LARGE, now i can load my hash. problem is that i have not enough resources.
EDIT: clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

so below line should be changed and warn based on HCBUFSIZ_LARGE or "u32 contents"
`if (contents_len > 50000) return (PARSER_SALT_LENGTH);`

50000 is 50 kb file that Fist0urs added.

should i buy new hardware?

**Comment by Fist0urs** [comment]
Hi!
I don't think that is related to hardware, 300k would be the maxium for you, right? I'll try to fix that ASAP

**Comment by jackpit110** [comment]
Hi
thanks i need maximum   600kb hash file, and 300kb is my kdb file.
i have fixed input hash but i am getting that error about resources.
may be i did wrong.
300k is in new version of hashcat, but this line should be fixed:
`if (contents_len > 50000) return (PARSER_SALT_LENGTH);`
