### ISSUE TITLE
hash type request: QAS ("Quest Authentication Services")

### ISSUE THREAD

**Issue by googlesecurityteam** [hashcat/hashcat#1417]
Hi all, I have come across a hash type that is not supported by hashcat. It is the "QAS" (Quest Authentication Services, an active directory / ldap like environment for Unix machines). It stores hashes in the following format in one of their databases:

sha256sum(#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX-p@ssw0rd)

Or more specifically: '#' sign, eight characters, dash sign, 4 characters, dash sign, 4 characters, dash sign, 4 characters, dash sign, 12 characters, dash sign, PASSWORD

This long salt is actually a uuid for users in the system. If I recall correctly, the salt characters seem to be only numbers, but I will double-check and post back soon.

I have tried using the sha256($salt.$pass) format, but it seems to be too large.

**Comment by philsmd** [comment]
With which version of hashcat did you try it?
Hashcat 4.0 supports a length of up to 256 characters.

The hash file needs to contain hash:salt i.e
hexhash:#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX-

It's working perfectly fine here with a little test:
```
$ cat hash.txt
5f4cdf48b7579100ac9e0fe6ffe73ebf85b99200181033d371151cefab72190a:#12345678-1234-1234-1234-123456789abc-
$ ./hashcat -m 1420 -a 3 hash.txt ?lashcat
5f4cdf48b7579100ac9e0fe6ffe73ebf85b99200181033d371151cefab72190a:#12345678-1234-1234-1234-123456789abc-:hashcat
```

**Comment by googlesecurityteam** [comment]
My apologies, I was still on 3.10. 4.0.0 works great! Closing the issue
