### ISSUE TITLE
pbkdf2-hmac-sha256 + aes-256-cbc

### ISSUE THREAD

**Issue by harwoodr** [hashcat/hashcat#1424]
I'm looking for something that:

Step1: takes a 32 byte ciphertext, an 8 byte hash,  and a 4 byte salt -> pbkdf2-hmac-sha256 (with 4096 iterations and 64 bytes out).  Output is split as: first 32 bytes as cipherkey, next 16 bytes as iv and last 16 bytes as an hmac key.

Step2:  cipherkey,  iv and ciphertext -> aes-256-cbc decrypt. 

Step3: uses output from step2 as a message and hmac key ->hmac-sha256.  If first 8 bytes of output matches the 8 byte hash from step1, password is correct.

I've looked through the list of example hashes but if I've missed one that does this, I'm sorry. :)  ...or, am I asking for a new algo?

Thanks

**Comment by jsteube** [comment]
There's many tools using exactly this architecture to protect some sort of data or to do some verification. For example TrueCrypt, LUKS, Office docs, RAR, etc. Hashcat maps a special hashmode to each of them. Same would be required for your software.

See here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

**Comment by harwoodr** [comment]
Alright, I guess I'll hack at the code and see what I can do. My opencl experience is limited, but perhaps this will be a good excuse to sharpen said skills.

Thanks.

**Comment by harwoodr** [comment]
Just to see if I'm on the right track, I'm working on just understanding how hashcat does the pbkdf2-hmac-sha256 component.
I've created the following hash:

sha256:4096:kh3A5g==:H9GA2pYsBCJ2p0o7r54T6/7BURU5F4QVrG0WpsVu0i//0FE2eVz4D8f0YGtkexArX6RBGaKpV4ujgGyiJXH41w==

...which uses the password "password1".

All well and good.  Now, I need to figure out the next step - an AES-256-CBC decrypt.  From what I can tell, there is no existing mode that uses both - except maybe LUKS... but I'm still wrapping my brain around that.
