### ISSUE TITLE
Problem with Invoke-DCSync.ps1 created hashlists

### ISSUE THREAD

**Issue by anlx-sl** [hashcat/hashcat#143]
Regarding https://hashcat.net/forum/thread-5063.html:

I extracted NTLM hashes with Invoke-DCSync.ps1 (https://gist.github.com/monoxgas/9d238accd969550136db) and used
Powershell's Out-File cmdlet to pipe the output in a textfile.

Using this textfile, hashcat threw a Line-length exception for every single line in the file.

After I opended the textfile in Ubuntu's gedit and copy-pasted the content in a newly created text file, the new text file did work with hashcat.

**Comment by philsmd** [comment]
We need an example of output to test what the problem really is.
@anlx-sl can you please provide some lines of the file that showed you the error message ? (It's okay if you anonymize/mask it, as long as it is still of the same format and results in the same error).
Without any concret example it is difficult to guess what could be possibly going on here.
Thx

**Comment by anlx-sl** [comment]
I will provide an example ASAP. One more detail: I prepared the lists using Neotepad++ v6.8.8 on Win 10 (removing empty lines etc.). Then i saved the files to the Desktop and copied them to the linux host using scp (mobaxterm). Maybe one of this steps may cause the problem?

**Comment by jsteube** [comment]
Yes. Most texteditors have an option to select the CRLF. Also I know from some FTP tools to convert between CRLF depending on the selected Host OS so it's possible some scp tools inherited this behavior.

Anyway I don't think this is an empty line problem. It's propably CRLF related.

**Comment by philsmd** [comment]
@anlx-sl we still need at least one sample to reproduce this problem. Unless we have a reproducible issue, we can't troubleshoot/fix this problem.
Could you (@anlx-sl) please provide such an example "hash" file?
Thx

**Comment by anlx-sl** [comment]
@philsmd [https://www.dropbox.com/s/55vki7bnah85skn/smpl3.zip?dl=0](sample)

**Comment by philsmd** [comment]
the output is utf-16 encoded. That means that for this particular file we have NULL-bytes every second byte and therefore several "string functions" don't work correctly (strlen etc) when we open/read it like we currently do (with utf-8 support).
To fix this problem, we need to add utf-16 file reading (and encoding detection) support... I'm not sure if this is really that important and common such that it is worth to add it.
The files also can easily be converted beforehand:

```
iconv -f utf-16 -t utf-8 FILE
```

utf-16 encoded files start with the Byte Order Mark (BOM, 0xfffe) and the 4th byte is a NULL byte (if > 1 byte is needed), after that every second byte is a NULL-byte (if > 1 byte is needed to encode the character).

**Comment by jsteube** [comment]
@anlx-sl did the hint from @philsmd help? can we close the issue?

**Comment by anlx-sl** [comment]
@jsteube yes, thanks a lot guys!
