### ISSUE TITLE
Alpine linux no `qsort_r`

### ISSUE THREAD

**Issue by wenerme** [hashcat/hashcat#1440]
Something like these

* https://github.com/libgit2/libgit2/pull/3446
* https://github.com/libgit2/libgit2/issues/3438

```
obj/shared.NATIVE.STATIC.o: In function `hc_qsort_r':
shared.c:(.text+0x4d1): undefined reference to `qsort_r'
collect2: error: ld returned 1 exit status
make: *** [src/Makefile:410: hashcat] Error 1
```

**Comment by neheb** [comment]
There's a pull request already

**Comment by jsteube** [comment]
I've merged it. Please retry with latest github master version

**Comment by Kochise** [comment]
Fyi, `qsort_r` has been added to Alpine on 2021/09/22 (musl-1.2.2-r7) :

https://gitlab.alpinelinux.org/alpine/aports/-/commit/bf5bbfdbf780092f387b7abe401fbfceda90c84d

Profit.
