### ISSUE TITLE
Support for sha1(md5($pass.$salt)) new algorithm

### ISSUE THREAD

**Issue by anmakar111** [hashcat/hashcat#1446]
Add support new algo sha1(md5($pass.$salt))

**Comment by philsmd** [comment]
you could just use -m 4700 = sha1(md5($pass)) and append the salt with rules etc. This of course only works sufficiently if the hash list is small (ideally only one hash is used).

If you really want that this new hashing algorithm gets implemented you need to provide much more information.
Important information that is required would be: where is this hash type used in? are there any limitations of salt length/password length etc

**Comment by jsteube** [comment]
The requested algorithm was added to hashcat. You can either wait for release version or use the binary beta from https://hashcat.net/beta or compile from GitHub master source yourself. Thanks for the request!
