### ISSUE TITLE
Rule application prior workflow estimation

### ISSUE THREAD

**Issue by KKGBiz** [hashcat/hashcat#1449]
Hi there,

I have a pass list of short words (w/o dash):
- root
- admin
- toor

i have file of 5 rules as follows (w/o dash):
- :
- u
- l $2$0$1$7
- l $2$0$1$6
- l $2$0$1$5

On WPA cracking (2500), all password candidates will be rejected, since HC reads passlist for pass starting from 8 symbols w/o application of rulles before. 
Meanwhile, potentially, in the abobe mentioned case at least 9 candidates must be available with length over 8 symbols , i.e each short word (3) + last 3 rules (appending 4 symboles to the end).

Can u add this feature to count password candidates after rule applcation?

**Comment by philsmd** [comment]
This is a known "feature". If you want to use shorter words mangled with rules, you should use this:
```
hashcat --stdout -r rule.txt dict.txt | hashcat -m 2500 -a 0 hashes.hccapx
```

**Comment by jsteube** [comment]
That's the way

**Comment by KKGBiz** [comment]
Thank you all.

How to restore this pipe session?

**Comment by jsteube** [comment]
It's supposed to have only a few candidates in this case, therefore it's not supposed to restore a piped session. You can however use the -s parameter directly on the first command.
