### ISSUE TITLE
cmdline change: always require -m for actions that act on hashes

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1456]
Because the command line currently has an implied default mode (-m 0, MD5), a number of actions could become less ambiguous for naive users if -m was instead required.

For example, when using `--show`, the user must specify a hash type (to avoid ambiguous salts/separators, etc.)

Before the suggested change, the user gets this error, and the naive user has no idea what to do next, because hashcat defaults to MD5 and knows that this hash is the wrong length:

```
$ hashcat --show hashfile.sha1 
Hashfile 'hashfile.sha1' on line 1 (b89eaac7e61417341b710b727768294d0e6a277b): Line-length exception
No hashes loaded.
```

With the suggested change, the user might instead see something like:

```
$ hashcat --show hashfile.sha1 
Please specify a hashtype with -m.
```

If it's not desirable to require -m in most cases, then at least explicitly requiring it for features like `--show/--left` would improve usability.

More generally, iif any command that expects to act on hashes make the hash type explicit, then many naive users will not be confused by line-length exception errors, and could instead figure things out for themselves without having to ask, check the FAQ, etc.

(Side note: am I crazy, or is the default (-m 0, MD5) not documented in the help? Maybe in the example column, we could list -m 0 instead of -m 1000 and say "-m 0 (default)"? Or say it somewhere else, maybe in the hash modes list?)

[EDIT: If this idea is appealing, I can submit a PR, depending on what approach you recommend]

**Comment by jsteube** [comment]
Some things to notice is that:

* Removing the default just for --show and --left would be hard to explain. If we do, it should be global.
* Some example scripts would be need to be patched, too (example0.cmd etc)
* Removing the -m 0 default would also solve the missing default marker
* Lot's of tutorials in the wild explain -m 0 to be the default (in case of critic on the change we can point to "it's a new version")
* The "Please specify a hashtype with -m." misses a hint on -h to get a list of all available modes

**Comment by jsteube** [comment]
@roycewilliams feel free to send in a PR

**Comment by jsteube** [comment]
With the autodetection feature added, this Issue is kind of obsolete. Do you think we can close?

**Comment by roycewilliams** [comment]
Concur that -m makes this largely obsolete - closing!
