### ISSUE TITLE
Rule is rejected

### ISSUE THREAD

**Issue by dizcza** [hashcat/hashcat#1457]
I have a hccapx file with several WPA2 handshakes of one WiFi access point with the password "mypass22". I'm trying to guess it using

- wordlist: http://downloads.skullsecurity.org/passwords/conficker.txt.bz2
- rules: best64.rule (shipped with hashcat)

I know that `conficker.txt` wordlist contains "mypass" and using `best64.rule` would yield "mypass22" - I've checked it with `hashcat -m2500 --stdout -r rules/best64.rule wordlists/conficker.txt | grep mypass22`. But hashcat didn't crack it: 

`hashcat -m2500 -r rules/best64.rule captures/handshake-17.hccapx wordlists/conficker.txt`

```
Dictionary cache hit:
* Filename..: wordlists/conficker.txt
* Passwords.: 182
* Bytes.....: 1411
* Keyspace..: 14378

Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: captures/handshake-17.hccapx
Time.Started.....: Wed Nov 22 10:56:23 2017 (6 secs)
Time.Estimated...: Wed Nov 22 10:56:29 2017 (0 secs)
Guess.Base.......: File (wordlists/conficker.txt)
Guess.Mod........: Rules (rules/best64.rule)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:      637 H/s (0.56ms)
Recovered........: 0/2 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 14378/14378 (100.00%)
Rejected.........: 10191/14378 (70.88%)
Restore.Point....: 182/182 (100.00%)
Candidates.#1....: 000000002017 -> testtest2017
HWMon.Dev.#1.....: Temp: 38c Fan: 34%
```
If I manually add "mypass22" to the `conficker.txt` wordlist, it _will_ crack with or without the rules.
Tried with hashcat-4.0.1 and hashcat-3.6.0 - the same behavior.

**Comment by freeroute** [comment]
Did you tried this?
Solution 1:
1) echo [[[[[ > pre.rule  
2) hashcat <as usual> -j ^X^X^X^X^X -r pre.rule -r yournormalrule.rule  

Solution 2:
$ ./hashcat wordlist.txt -r rule.txt --stdout| ./hashcat -m 2500 mywpa.hccap -w 3

**Comment by dizcza** [comment]
Yes, 2nd option works, thank you.
I also found already discussed topic at https://github.com/hashcat/hashcat/issues/1262. I'm closing this a duplicate.
