### ISSUE TITLE
add support for TACACS+ hashes

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1462]
TACACS+ is used to perform AAA for Cisco and other networking gear. It is a very common framework that would be of strong interest to penetration testers.

Code reference:
https://github.com/magnumripper/JohnTheRipper/pull/2926

pcap2john.py
https://github.com/magnumripper/JohnTheRipper/pull/2926/commits/2f00169adb077db130450b5a8f4edba0c349fbc2

RFC (has been in stages of draft mode for years):
https://www.cisco.com/warp/public/459/tac-rfc.1.76.txt (very early)
https://tools.ietf.org/html/draft-ietf-opsawg-tacacs-07 (most recent)

Other references:
http://www.openwall.com/articles/TACACS+-Protocol-Security

_The body of TACACS+ packets is encrypted by XOR'ing it with a series of MD5 hashes (each 16 bytes long). The first two hashes (used to encrypt first 32 bytes of the packet body) are as specified in the RFC draft:_

	MD5_1 = MD5{session_id, key, version, seq_no}
	MD5_2 = MD5{session_id, key, version, seq_no, MD5_1}

**Comment by jsteube** [comment]
done https://github.com/hashcat/hashcat/commit/e5ca2e2fcb06d6577564c0462c82cfe58f61e9ea

**Comment by roycewilliams** [comment]
Awesome - thanks!
