### ISSUE TITLE
14000 DES clSetKernelArg(): CL_INVALID_ARG_SIZE

### ISSUE THREAD

**Issue by Meatballs1** [hashcat/hashcat#1464]
` -m 14000 des -a 3 -1 /usr/local/share/doc/hashcat/charsets/DES_full.charset --hex-charset ?1?1?1?1?1?1?1?1 -w 3 --powertune-enable --gpu-temp-disable`  works fine

but ` -m 14000 des -a 3 -1 /usr/local/share/doc/hashcat/charsets/DES_full.charset --hex-charset ?1?1?1?1?1?1?1?1 -w 3 --powertune-enable --gpu-temp-disable -O` gives the following error multiple times ( then hashcat exits at 0%.

`clSetKernelArg(): CL_INVALID_ARG_SIZE`

I removed all the kernels from `~/.hashcat/kernels` and the following are there:

```
-rw------- 1 x x 385361 Nov 30 17:30 m14000_a3.239835be.kernel
-rw------- 1 x x 392383 Nov 30 17:30 m14000_a3-optimized.239835be.kernel
-rw------- 1 x x  35776 Nov 30 17:30 markov_le.654b20eb.kernel
```

**Comment by Meatballs1** [comment]
v4.0.0

**Comment by philsmd** [comment]
can't reproduce. Can you give more details about your system.
Is this an apple system?
What type of OpenCL device (CPU/GPU) and which make/model do you use?

**Comment by jsteube** [comment]
Maybe you did install the 4.0.0 files over an existing hashcat folder of an older version? That could cause the problem. Please run make uninstall first, then run make install.

**Comment by Meatballs1** [comment]
Yes that looks like the problem. `make install` needs to clear out the /usr/local/share/hashcat/OpenCL directory?

**Comment by jsteube** [comment]
Yeah, it does already
