### ISSUE TITLE
Windows 10 x64 "fatal error: 'inc_vendor.cl' file not found"

### ISSUE THREAD

**Issue by ZVitaliy** [hashcat/hashcat#1465]
Hello guys!
I have the same problem as a [1308](https://github.com/hashcat/hashcat/issues/1308) only on Windows 10.

Benchmark and **-I** work well but when I started brute-force I see this error "fatal error: 'inc_vendor.cl' file not found". But I check the folder and this file already in a folder **hashcat-4.0.1\OpenCL**. I'm trying to start the console as administrator and have the same error.

System work with 6 GPU RX470 with drivers [AMD Dag Fix](https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx) especially for blockchain. I'm tried other drivers latest version and Crimson edition but the system has no seen the GPU's.

**Comment by philsmd** [comment]
Are there any other strange characters within the path?

Try to download a fresh copy directly to C:\ and extract it there such that you have this folder:
C:\hashcat-4.0.1\OpenCL\

**Comment by ZVitaliy** [comment]
Thanks @philsmd it works.
