### ISSUE TITLE
Integer overflow detected in keyspace of mask: ?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a

### ISSUE THREAD

**Issue by carlos204** [hashcat/hashcat#1467]
OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 10035/10035 MB allocatable, 1MCU

Hashes: 92 digests; 72 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

* Device #1: build_opts '-I /usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D VECT_SIZE=4 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=2500 -D _unroll -cl-std=CL1.2'
Initialized device kernels and memory...Integer overflow detected in keyspace of mask: ?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a

- Device #1: autotuned kernel-accel to 64                 
- Device #1: autotuned kernel-loops to 64
[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: /tmp/hctmp.hccapx
Time.Started.....: Tue Dec  5 21:58:55 2017 (0 secs)
Time.Estimated...: Tue Dec  5 21:58:55 2017 (0 secs)
Guess.Mask.......: ?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a [15]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/72 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0
Rejected.........: 0
Restore.Point....: 0
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: N/A

Started: Tue Dec  5 21:58:45 2017
Stopped: Tue Dec  5 21:58:55 2017
Pulsa la tecla [Enter] para continuar...

**Comment by carlos204** [comment]
what is the problem???

**Comment by roycewilliams** [comment]
The mask is A) far too large for hashcat to handle and B) even if it could would take thousands of years to complete. You will need to know more about your target plaintext in order to attack it.

**Comment by carlos204** [comment]
how can i do to put only numbers and letters??

**Comment by jsteube** [comment]
Everything here working as it should. GitHub issues are for bug reports and feature requests only. Please use the forum for usage questions. Please read https://hashcat.net/wiki/doku.php?id=mask_attack first.
