### ISSUE TITLE
Hybrid mask and rule

### ISSUE THREAD

**Issue by Lexus89** [hashcat/hashcat#1468]
I have been using a hybrid attack (wordlist + mask) however i'd like to add a rule as well for common substitutions like a->@, a->4, o->0 and uppercasing. For example not just a mask with ?d: 

password1
password2
password3

but also trying the following possibilities:

p@ssw0rd1
p@ssword2
P@ssword3

Although it is possible to generate such rules based on masks however processing masks in memory is way faster than reading rules from disk (for me masks are 3x faster). Is it possible to have rules in combination with masks as a hybrid attack?

**Comment by jsteube** [comment]
Please use rule stack feature. If unclear how to do that, ask on hashcat forum. GitHub issues are for bug reports and feature requests only.
