### ISSUE TITLE
warning /home/hp/hashcat-4.0.1/OpenCL/m02500-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel

### ISSUE THREAD

**Issue by nlona** [hashcat/hashcat#1469]
`Linux hp-desktop 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

./maskprocessor-master/src/mp64.bin ?1?1?1?1?1?1?1 -i 8:64 -r 7 -q 3 -1 ?l?u?d?s|/home/hp/hashcat-4.0.1/hashcat64.bin -w 3 -m 2500 L.hccapx --force -O
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1050 Ti, 1007/4031 MB allocatable, 6MCU

/home/hp/hashcat-4.0.1/OpenCL/m02500-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
Hashes: 2 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimize
`
Why does this warning appear?

**Comment by roycewilliams** [comment]
This is a question for the forums, not for a GitHub issue.

This is informational only. If you ask for optimized kernels (with -O), but there is no separate optimized kernel needed (there is no speed difference), you get this warning. Either drop the -O for this format (if you don't want to see the error), or just ignore the warning, as it has no impact on performance.

**Comment by jsteube** [comment]
Not a bug
