### ISSUE TITLE
ERROR: clGetPlatformIDs() : -1001 : CL_UNKNOWN_ERROR on latest git version

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#147]
I recently compiled the latest git version of oclHahscat and got the following error message when ever I try and run either a benchmark or a crack:
`ERROR: clGetPlatformIDs() : -1001 : CL_UNKNOWN_ERROR`

I am running a Nvidia card on Ubuntu 15.10 . It looks like a OpenCL error so I tried reinstalling deps and a reboot but the error still persists.

**Comment by roycewilliams** [comment]
This is usually video driver-related.  Please see our FAQ for more information on how to return your video drivers to a known good state. The FAQ refers to AMD only in spots, but it applies to NVIDIA as well.

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_does_the_clgetplatformids_-1001_error_mean

**Comment by thesle3p** [comment]
I just did a fresh install of Ubuntu and Nvidia-352-updates drivers and this issue still persists.

**Comment by epixoip** [comment]
Are you root?

**Comment by thesle3p** [comment]
Yes, though I found the issue, on the reinstall I had a bad download of
gdk_linux_amd64_352_55_release.run , it works after a fresh download and
run of tools/deps.sh

**Comment by philsmd** [comment]
@thesle3p could you please close the issue if you think this is not an issue anymore (because you fixed it with a clean install/download of deps)?
