### ISSUE TITLE
problem whit veracrypt and hashcat

### ISSUE THREAD

**Issue by BarbaVerde** [hashcat/hashcat#1475]
hello everyone, it's the first time I write I have a problem with Veracrypt, because I have encrypted a folder that I can not remember the password, or rather I do not remember it all but a part I remember it, 
I'm trying with hashcat but I always find this problem,what I insert is: hashcat64.exe -m 13721 --outfile=PasswordHits.txt VeraCryptFile.vera Dictionary.txt It is unfortunately always me this mistake 
*Device #2 intel openCl runtime (GPU only) is currently broken 
we are waiting for update openCL drivers from intel 
you can use --   to overraide,but do not report related errors.
no device found/left

but I have intel updated on purpose,someone more experienced can help me I have windows 8, 
thanks regardless :)

**Comment by philsmd** [comment]
Which cpu do you have?

Do you also have a GPU (graphics card) which would be much faster? Intel GPUs are not recommended, use an modern Nvidia or AMD GPU

The drivers for the Intel CPU runtime can be found here: https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime
