### ISSUE TITLE
Cisco-ASA MD5 increase max Password

### ISSUE THREAD

**Issue by SilRo991** [hashcat/hashcat#1478]
Hi,

if I use -m 2410 I get the following warning:

./OpenCL/m02410_a3-optimized.cl: Pure OpenCL kernel not found, falling back to optimized OpenCL kernel
Skipping mask 'hashca?l?d?d?d?d?d?d' because it is larger than the maximum password length.

I Used the example Hash: hashcat64.exe -m 2410 -a 3 02dMBMYkTdC5Ziyp:36 hashca?l?d?d?d?d?d?d

No Information on how much the maximum password length is.
I found it by trying - 12 char. Is it possible to get Information in this case.

On the otherside - is it possible to force it to use the Pure OpenCL kernel for m2410 ?

**Comment by jsteube** [comment]
It makes no sense to have a pure Kernel for this algorithm as it does not support password longer that 12. It's not a hashcat problem.

**Comment by SilRo991** [comment]
Hi,

sorry but where did you get this information that it does not support password longer 12?
From the help of an ASA Device I have this Information: Enter a password between 3 and 127 characters.

You can also find this online:
Sets the password as a string from 3 to 32 characters in length (9.5 and earlier) or 127 characters (9.6 and later), which can be any combination of ASCII printable characters (character codes 32-126), with the exception of spaces and the question mark.
https://www.cisco.com/c/en/us/td/docs/security/asa/asa-command-reference/T-Z/cmdref4/u.html
