### ISSUE TITLE
clock_gettime is Invalid in C99?

### ISSUE THREAD

**Issue by MateoWartelle** [hashcat/hashcat#1479]
src/timer.c:36:3: error: implicit declaration of function 'clock_gettime' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
  clock_gettime (CLOCK_MONOTONIC, a);
  ^
src/timer.c:36:18: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  clock_gettime (CLOCK_MONOTONIC, a);
                 ^
2 errors generated.
make: *** [obj/timer.NATIVE.STATIC.o] Error 1

**Comment by matrix** [comment]
Hi, check here #1480

**Comment by jsteube** [comment]
Is this some error that occurs only for older macOS systems?

**Comment by zot24** [comment]
jtlyk I have experiencing the same error on OS X El Capitan 10.11.6

**Comment by neheb** [comment]
@jsteube yes

**Comment by jsteube** [comment]
@matrix Can you please fix the PR as described in the PR

**Comment by matrix** [comment]
@jsteube done. Check if you like it :)

**Comment by neheb** [comment]
So given that Apple doesn't seem to provide updates to old macOS versions, could justify doing the same here?

**Comment by jsteube** [comment]
Can I close the issue - is the fix working?

**Comment by jsteube** [comment]
No response from OP, but should be fixed. Please reopen if turns out otherwise.
