### ISSUE TITLE
hashcat issue with kali linux. "CL_OUT_OF_RESOURCES" "nvmlDeviceGetFanSpeed(): Not Supported" "nvmlDeviceGetPowerManagementLimit(): Not Supported"

### ISSUE THREAD

**Issue by smoklessfire** [hashcat/hashcat#1481]
hey guys,

i have the latest driver install let you look, the output : 
λ ~/ nvidia-smi
Wed Dec 27 17:40:00 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8     8W /  N/A |    212MiB /  6064MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       776      G   /usr/lib/xorg/Xorg                            19MiB |
|    0       817      G   /usr/bin/gnome-shell                          22MiB |
|    0      1116      G   /usr/lib/xorg/Xorg                            82MiB |
|    0      1199      G   /usr/bin/gnome-shell                          84MiB |
+-----------------------------------------------------------------------------+

and this one too : 
λ ~/ hashcat -I
hashcat (pull/1273/head) starting...

OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 9.0.229

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GTX 1060
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 10
    Clock          : 1670
    Memory         : 1516/6064 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 384.98

Platform ID #2
  Vendor  : The pocl project
  Name    : Portable Computing Language
  Version : OpenCL 2.0 pocl 0.14, LLVM 3.9.1

  Device ID #2
    Type           : CPU
    Vendor ID      : 128
    Vendor         : GenuineIntel
    Name           : pthread-Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Version        : OpenCL 2.0 pocl HSTR: pthread-x86_64-pc-linux-gnu-x86-64
    Processor(s)   : 8
    Clock          : 3500
    Memory         : 9970/9970 MB allocatable
    OpenCL Version : OpenCL C 2.0
    Driver Version : 0.14

but when i run with the "-b" to start a benchmark or when i start a real hash cracking sessions i got this output with this error : 
hashcat -b
hashcat (pull/1273/head) starting in benchmark mode...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
nvmlDeviceGetFanSpeed(): Not Supported

nvmlDeviceGetPowerManagementLimit(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1060, 1516/6064 MB allocatable, 10MCU

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, skipped.

Hashtype: MD4

Speed.Dev.#1.....: 16563.1 MH/s (80.94ms)

For CPU that's work fine, but i managed to not be able to solve this for the GPU usage ... and i tried several times, with different methodes...  so if someone have the answer to solve this errors.

i tried the solution who's offer in this link : "https://hashcat.net/q/timeoutpatch" the only thing a win is a blackscreen when i reboot my computer, hopefully that was simple to manage, but i still dont have a concret solutions for my probleme, and seems bad to have a 1060 and can't be able to really use it ... 

thanks for your help,
reguards,

Smokless-Fire

**Comment by Chick3nman** [comment]
You are receiving these errors because you are trying to run hashcat on a laptop where `nvmlDeviceGetPowerManagementLimit()` and `nvmlDeviceGetFanSpeed()` are not supported. Solution is basically don't run hashcat on a laptop.

**Comment by neheb** [comment]
AFAIK, those errors come with GPUs where the EC manages the fan, not the GPU itself.

So yeah, no problem there.

**Comment by jsteube** [comment]
Wait I wouldn't say don't run hashcat on laptops. You can do that like pentesters have to do it when they are on site. Just make sure you have an adequat setup and don't run it over several weeks in -w 3 or -w 4 mode.

Anyway, adding the correct configuration settings to your xorg.conf and your Xsetup file is not a hashcat issue. It's clearly an installation issue. Therefore please use the hashcat forum as GitHub issues are for bugs and feature requests only.

**Comment by Sankulaatchuth** [comment]
bro do u made anything to make it work ......i am  stuck here now this is my same isssue i'm trying to run hashcat on my hp omen laptop but cant go further its gtx1060 6gb

**Comment by mat43211** [comment]
same problem

**Comment by mat43211** [comment]
i am on windows 10

**Comment by AhmetPayaslioglu** [comment]
same problem
