### ISSUE TITLE
hascat issue "Driver temperature threshold met on GPU #3. Expect reduced performance."

### ISSUE THREAD

**Issue by tomasuno** [hashcat/hashcat#1484]
Driver temperature threshold met on GPU #3. Expect reduced performance.

Cracking performance lower than expected?

* Append -w 3 to the commandline.
  This can cause your screen to lag.

* Update your OpenCL runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

i have these problems, my GPU is a gtx 1050 (laptop). i crack wpa/wpa2 too slow (70000 h/s) hashcat latest version. I update the drivers to latest version with geforce experience 
i see other people that with a gtx 980 crack at 150 kh/s

what could be the problem?? thanks and await our response

**Comment by philsmd** [comment]
I don't see any problem of hashcat here, but...
1. you should not crack with a laptop
2. mobile GPUs are known to be slower, or at least that they do not reach the same speed as their non-mobile equivalent (even if their name is similar)
3. you need to use -w 4 to reach maximum speed
4. your laptop won't support that much heat/work and will risk to burn/damage
5. it also matters a lot what type of attack you use (and what your input is, e.g. large-enough dictionary file with rules, large-enough mask etc)... Performance could be slower if you don't supply enough work to your GPUs

**Comment by jsteube** [comment]
I wouldn't say don't crack with a laptop. It's required for pentesters that are required to use their own hardware on site. If you use an adequate notebook it's pretty fine to use it.

Everything else is as @philsmd mentioned, especially the part with mobile GPU being slower than concrete GPU.

Anyway this is not a hashcat issue and should not be discussed here. GitHub issues are for bugs and feature requests only.

**Comment by ilya7zz** [comment]
Hello!
Hashcat version 5.1.0
8 gtx 970, afterburner temperature limit of 60 degrees.
OS Win 10 or Win 7, the same. 1 GPU or 4 is the same.
options used: opt = -m 2500 -w 4 --force
speed per 1 GPU 180-200 kH / s
Nicehash works great 24/7 ... 4 years :)
On screen every second random gpu:
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 1.
Driver temperature threshold met on GPU # 3.
Driver temperature threshold met on GPU # 4.
Driver temperature threshold met on GPU # 4.
...
Tell me please.
