### ISSUE TITLE
[New Algorithm] AuthMe - SHA256(SHA256(password) + salt)

### ISSUE THREAD

**Issue by KiralyCraft** [hashcat/hashcat#1486]
**Name of algorithm**: AuthMe default password storage algorithm
**Where it is used**: AuthMe is an authentication plugin for Minecraft cracked servers. It is the most known and used plugin for all kinds of servers. By default, it stores it's passwords in a database in the mentioned format. By implementing the requested algorithm, password recovery/cracking would be available based on the hashes stored in plain text. 
**Source code**: The algorithm is implemented here: [https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/security/crypts/Sha256.java](url)

**Restrictions**: Salt length is always 16 characters. It is randomly generated but stored together with the password hash. Password length can vary from 1 to 32 characters. 

**Full example of password & hash**: 

> Password:	pantof
Stored entry: $SHA$c7dedf5a36c4a343$05ae3239eee683872ef1cc9096777bf4b1a72a179709efc17d8bf1603b082065

**Other details**: The passwords are stored in the following format: 
`String encryptedPassword = "$SHA$" + salt + "$" + sha256(sha256(password) + salt);`

**Comment by spideyroc1** [comment]
Will this be added?

**Comment by lev4ukpavel2** [comment]
Please guys, we need it. I hope you can do it.

**Comment by sergviun2** [comment]
35a30bd53de1feb4e835dc699722a21bc8deaf15a43c553664e643883f8f517c  Help please decipher

**Comment by its5Q** [comment]
Would someone like to work on that? Seems like that person abandoned his work. That would be really great if you could do it, because there are no tools that can bruteforce those kinds of hashes on GPU and, unfortunately, I don't have enough C/C++ skills to make hashmodes. Thanks.

**Comment by roycewilliams** [comment]
Semi-OT, but in the meantime ... theoretically, I _think_ this could be done with a John the Ripper dynamic mode. There's a canned one (dynamic_1503) that looks like 

`sha256(sha256($p).$s) (XenForo SHA-256)`

It's CPU only, but it's better than nothing!

**Comment by its5Q** [comment]
@roycewilliams Yeah, I know about that, but it's so slow on the CPU, and it's also implemented in Hash Manager, but still on CPU. GPU would speed up things a lot

**Comment by its5Q** [comment]
Also there is some code available https://gist.github.com/tbiehn/28531fdb324baaeaa2960aae1b9b36ab

**Comment by matrix** [comment]
Hi, I added the support by reusing code from PR #1939 

The patch is below:
https://github.com/hashcat/hashcat/compare/master...matrix:authme_1

branch:
https://github.com/matrix/hashcat/tree/authme_1

**Comment by jsteube** [comment]
The requested algorithm was added to hashcat. You can either wait for release version or use the binary beta from https://hashcat.net/beta or compile from GitHub master source yourself. Thanks for the request!
