### ISSUE TITLE
Crash during DES benchmark

### ISSUE THREAD

**Issue by killtacknine** [hashcat/hashcat#1489]
I've been trying to run a benchmark on a Google cloud machine with 4 Nvidia Tesla P100 GPUs attached but hashcat crashes whenever it reaches the DES benchmark. I've previously run the benchmark on a machine with 8 K80 GPUs and did not have any issues. So it seems like the only difference is the P100s.

Hashcat version: 4.0.1 (I also tried with a couple other versions but they all had the same problem)
OS: Ubuntu 17.04 (Also tried with 16.04 but same issue)

Hashcat output:

```
user@nvidia-p100-test:~/hashcat-4.0.1$ sudo ./hashcat64.bin --benchmark | tee benchmark.txt
hashcat (v4.0.1) starting in benchmark mode...
 
Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.
 
nvmlDeviceGetFanSpeed(): Not Supported
nvmlDeviceGetFanSpeed(): Not Supported
nvmlDeviceGetFanSpeed(): Not Supported
nvmlDeviceGetFanSpeed(): Not Supported
 
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Tesla P100-PCIE-16GB, 4069/16276 MB allocatable, 56MCU
* Device #2: Tesla P100-PCIE-16GB, 4069/16276 MB allocatable, 56MCU
* Device #3: Tesla P100-PCIE-16GB, 4069/16276 MB allocatable, 56MCU
* Device #4: Tesla P100-PCIE-16GB, 4069/16276 MB allocatable, 56MCU
 
Benchmark relevant options:
===========================
* --optimized-kernel-enable
 
Hashmode: 900 - MD4
 
Speed.Dev.#1.....: 38020.5 MH/s (49.50ms)
Speed.Dev.#2.....: 36984.0 MH/s (49.54ms)
Speed.Dev.#3.....: 37955.2 MH/s (49.50ms)
Speed.Dev.#4.....: 37892.4 MH/s (49.62ms)
Speed.Dev.#*.....:   150.9 GH/s
 
Hashmode: 0 - MD5
 
Speed.Dev.#1.....: 22002.1 MH/s (85.46ms)
Speed.Dev.#2.....: 20740.3 MH/s (85.41ms)
Speed.Dev.#3.....: 20354.1 MH/s (85.41ms)
Speed.Dev.#4.....: 21645.3 MH/s (85.36ms)
Speed.Dev.#*.....: 84741.8 MH/s
 
... (does some more benchmarks and eventually reaches DES)
 
Hashmode: 14000 - DES (PT = $salt, key = $pass)
 
user@nvidia-p100-test:~/hashcat-4.0.1$
```

Hashcat just crashes there :\

If there is a way to gather debug logs or print more information please let me know and I'd be happy to collect more info.

**Comment by Chick3nman** [comment]
What driver version is currently installed? Nvidia drivers are usually the culprit for specific modes not working.

**Comment by killtacknine** [comment]
Looks like its 387.26

```
user@nvidia-p100-test:~$ nvidia-smi
Fri Jan 12 19:53:33 2018      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
...
```

**Comment by jsteube** [comment]
There's a DEBUG variable that you can set to 1 in src/Makefile. Please make clean before recompiling. Then retry with hashcat -b -m 1500 maybe we're lucky and get some better output. If there's nothing that helps, please try with strace -f -v -s 1000 ./hashcat -b -m 1500

**Comment by jsteube** [comment]
Can you please retry with the latest version from GitHub master or hashcat.net/beta/ ? I think the problem is solved now but needs confirmation.

**Comment by jsteube** [comment]
@killtacknine any update?

**Comment by jsteube** [comment]
Closing thread because there's no response from OP. The problem is believed to be fixed using latest GitHub master or beta binary from https://hashcat.net/beta/

If you find the problem is not fixed feel free to reopen.
