### ISSUE TITLE
Error building on Mac OSX

### ISSUE THREAD

**Issue by jlmalone** [hashcat/hashcat#1490]
El Capitain 10.11.6 (15G1421)

I tried following the build instructions:

https://github.com/hashcat/hashcat/blob/master/BUILD.md

This was the result after checking out repo and updating the submodules:

`Users-iMac:hashcat user$ sudo make
Password:
clang -c -pipe -std=gnu99 -Iinclude/ -Iinclude/lzma_sdk/ -IOpenCL/ -W -Wall -Wextra -Wfloat-equal -Wundef -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wstrict-prototypes -Waggregate-return -Wswitch-enum -Winit-self -Werror-implicit-function-declaration -Wformat -ftrapv -Wwrite-strings -Wno-cast-align -Wno-cast-qual -Wno-conversion -Wno-padded -Wno-pedantic -Wno-sizeof-pointer-memaccess -O2 src/timer.c -o obj/timer.NATIVE.STATIC.o
src/timer.c:36:3: error: implicit declaration of function 'clock_gettime' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
  clock_gettime (CLOCK_MONOTONIC, a);
  ^
src/timer.c:36:18: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  clock_gettime (CLOCK_MONOTONIC, a);
                 ^
2 errors generated.
make: *** [obj/timer.NATIVE.STATIC.o] Error 1`

**Comment by neheb** [comment]
Will be fixed soon. Consider upgrading OS X to 10.12 or newer.

**Comment by jlmalone** [comment]
Thanks @neheb . I am on a Hackintosh that my friend built so I don't feel comfortable upgrading it.

**Comment by jsteube** [comment]
Please retry after pulling latest version from github and close the issue if fixed.

**Comment by jlmalone** [comment]
Thank you for fixing this! It is working now on El Capitain 10.11.6 (15G1421)
