### ISSUE TITLE
Cannot find an OpenCL ICD loader library.

### ISSUE THREAD

**Issue by vido89** [hashcat/hashcat#1491]
Im using ubuntu 16.04 and when I run hashcat Im getting this error 

`Cannot find an OpenCL ICD loader library.`

I have installed `ocl-icd-libopencl1`, `ocl-icd-dev`, `ocl-icd-opencl-dev`

There is nothing mentioned at build instructions ?

**Comment by philsmd** [comment]
I think this problem was already discussed here: https://hashcat.net/forum/thread-7197.html
The main reason for this problem and a solution was also provided.

Please close this issue

**Comment by ithieve** [comment]
Reinstalling your gpu driver from scratch sometimes solves the issue

**Comment by 1265578519** [comment]
我可以用cpu来运行他吗？
amd ryzen可以使用sha指令集。能跳过gpu使用？
因为我在hyper中运行
我使用-d指令没有任何作用
[root@cloud ~]# hashcat -d 1 -D 1 -m 0 hashlist rockyou.txt
hashcat (v5.1.0) starting...

Cannot find an OpenCL ICD loader library.

You are probably missing the native OpenCL runtime or driver for your platform.

* AMD GPUs on Linux require this runtime and/or driver:
  "RadeonOpenCompute (ROCm)" Software Platform (1.6.180 or later)
* Intel CPUs require this runtime and/or driver:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* Intel GPUs on Linux require this runtime and/or driver:
  "OpenCL 2.0 GPU Driver Package for Linux" (2.0 or later)
* NVIDIA GPUs require this runtime and/or driver:
  "NVIDIA Driver" (367.x or later)

Started: Wed Oct 21 07:07:00 2020
Stopped: Wed Oct 21 07:07:00 2020
[root@cloud ~]#
