### ISSUE TITLE
Spaces instead of tabs in machine readable output (again)

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1494]
When running hashcat v4.0.1-79-g7f087d0 (built from source code from the repository) the machine readable output uses both spaces and tabs mixed for the separation of values.

Example:
```
STATUS  5       SPEED   EXEC_RUNTIME    CURKU   0	PROGRESS	0	815702160	RECHASH	0	1785	RECSALT	0	1785	REJECTED	0
```

The first five separations are made with spaces and the others in tabs. So far there were always only single tabs used to separate the values, it would be nice to have this format again.

**Comment by jsteube** [comment]
Can't reproduce this locally. It's all tabs for me.

```
root@ht:~/hashcat# ./hashcat example0.hash -a 3 ?a --mac --quiet | grep " " | wc -l
0
```

**Comment by s3inlc** [comment]
Sorry for not stating my command clearly. I checked again, it only happens when `--quiet` is not set.

**Comment by jsteube** [comment]
Still can't reproduce :(

```
root@ht:~/hashcat# ./hashcat example0.hash -a 3 ?a --mac  | grep ^STATUS | grep " " | wc -l
0
```

**Comment by s3inlc** [comment]
Yes, because your STATUS grep statement seems to be wrong:

```
$ ./hashcat example0.hash -a 3 ?a --mac  | grep ^STATUS
```
gives no output. 

```
$ ./hashcat example0.hash -a 3 ?a --mac  | grep STATUS | grep " " | wc -l
       1
$
```

**Comment by jsteube** [comment]
It seems like we're both wrong. Here's what's happening:

```
[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => ^M                                                 ^MSTATUS    5       SPEED   0       1000    EXEC_RUNTIME    0.072939        CURKU   1       PROGRESS        95      95      RECHASH 12      6494    RECSALT 0       1       TEMP    35      REJECTED        0
```

So the ^M here is doing the carriage return, that's why grep ^STATUS isn't working. However, there are no spaces after the STATUS line, there's only some before. I'd suggest to add --quiet to the htp client. In that case, there will be no "problematic" spaces.

**Comment by s3inlc** [comment]
Ok, that's really a strange behaviour. So this carriage return was causing the first part of the STATUS line to be with spaces instead of tabs in the terminal?

Basically there is no problem with adding --quiet (I think it's cleaner anyway), just need to check that this is done everywhere on the clients. So I guess we will go with this solution.

**Comment by jsteube** [comment]
Well yeah, because from a technical perspective (since there's no newline) there's also the prompt part of the line and the prompt has spaces. From how hashcat should work it's correct that way. If you can add the --quiet to I think it's the cleanest solution.

**Comment by s3inlc** [comment]
Ok, thanks a lot.
