### ISSUE TITLE
Missing soname of libhashcat.so

### ISSUE THREAD

**Issue by TomasKorbar** [hashcat/hashcat#1496]
Hello,
According to the documentation i've read for hashcat, libhashcat.so isn't private or plugin but public interface, so i think it should have soname. Could you please add soname to this library?

**Comment by yarda** [comment]
We would like to package it to Fedora and according to the Fedora packaging guidelines every public library needs to be versioned. For me the library seems like public API/interface so it should probably have SONAME. We can provide patches. What's your opinion?

**Comment by jsteube** [comment]
Sure, sounds good. Please send in a PR.

**Comment by yarda** [comment]
The patch is more like hack, but seems to work for us. Feel free to improve it or comment. We are ready to update it according to comments.
