### ISSUE TITLE
Incorrect result for LUKS (cipher: aes, mode: xts-plain64, hash: sha256, MK bits: 256)

### ISSUE THREAD

**Issue by Frank-GL** [hashcat/hashcat#1501]
Hi,

Today I created my own small LUKS image. Specs by 'cryptsetup luksDump' are:

> Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha256
Payload offset: 4096
MK bits:        256
MK digest:      94 bc c3 31 b6 b2 54 4d 70 26 d4 b1 a5 a9 a9 8d 96 67 94 38
MK salt:        28 78 88 f5 13 c8 93 f0 b8 9b ac 88 94 9a f6 c5
                87 7d 6f a4 0a d1 c6 b2 62 c4 a7 8f 9b 7c ad c6
MK iterations:  49375
UUID:           e46db992-956e-455e-99fa-0fe6b92b697f
Key Slot 0: ENABLED
        Iterations:             195121
        Salt:                   b7 cd e2 76 00 47 02 6d 89 8b 0f 6a 08 74 1b c4
                                1c 83 01 9a af e7 0a d3 66 6c d9 f9 a5 e8 ff 8f
        Key material offset:    8
        AF stripes:             4000

The password I've set equals **sha256**

Unfortunately, hashcat does not find this: the next command line fails to crack the password (the complte file **lukssha256.hashcat** is available in [github.gz](https://github.com/hashcat/hashcat/files/1667961/github.gz))

> ./hashcat64.bin -O -w 3 -a 3 lukssha256.hashcat sha256  -m 14600

Note: I've also tested hashcats own test: **hashcat_sha256_aes_xts-plain64_256.luks**. This one works fine. Specs of this one with 'cryptsetup luksDump' (and password **hashcat**)

> Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha256
Payload offset: 4096
MK bits:        256
MK digest:      a7 b7 c2 11 96 b9 4a f0 3c c2 64 cb 45 d9 c5 21 0c 32 28 db
MK salt:        56 15 94 1e b4 00 22 a6 e6 97 e2 5d d0 64 c0 ca
                03 e4 d5 a7 65 0b 66 97 5b 67 11 25 8b 4f a7 6b
MK iterations:  23005
UUID:           c9a3108e-01fa-4147-bea3-f877d2b8d8d8
Key Slot 0: ENABLED
        Iterations:             93723
        Salt:                   55 f5 af 0b 1b 66 30 48 e6 7d e8 d1 31 b9 ed 25
                                3c a9 74 2d f2 28 38 22 e6 a5 a6 90 d8 ff 3c 68
        Key material offset:    8
        AF stripes:             4000

The only big difference is the number of iterations. Maybe something goes wrong there? Any ideas?

Please note that I did not write any sensible data within my LUKS image. Furthermore, the version of hashcat I use is:

> ./hashcat64.bin --version     v4.0.1.1-49-g7b0b0b3

**Comment by jsteube** [comment]
I think you just forgot to format the device. Please reopen if I'm wrong.
