### ISSUE TITLE
Add crackpos telemetry

### ISSUE THREAD

**Issue by evilmog** [hashcat/hashcat#1506]
Often clients ask where in a crack run passwords cracked or time to crack. With clustering software like hashtopussy its hard as they already have a specific output format.

If you can make an option to output plaintext:crackpos to a configurable log file with path when the option is set we could centrally collect via NFS and calculate time to crack based on overall cluster speed.

**Comment by jsteube** [comment]
I did a second thought on this. I don't think any longer this makes any sense for the most users (except you with your special case). It's the opposite, by adding two parameters outputting more or less the same data this will create confusion - especially for new users.

To solve your case I'd suggest to talk to @s3inlc and ask them to add the crackpos information to the hashtopussy database. From there you can easily access it. You also save the step to match it with the password. So this has multiple advantages and feels like the correct solution from a software design perspective.
