### ISSUE TITLE
Trying to crack 13 character ntlm hash

### ISSUE THREAD

**Issue by Victini517** [hashcat/hashcat#1514]
When i try to crack a 13 character ntlm hash:

hashcat64.exe -m 1000 hash.txt -a 3 -1 abcdefghijklmnopqrstuvwxyz0123456789 ?1?1?1?1?1?1?1?1?1?1?1?1?1

Hashcat gives me:

Integer overflow detected in keyspace of mask: ?1?1?1?1?1?1?1?1?1?1?1?1?1

i don't know any other way to crack

**Comment by Banaanhangwagen** [comment]
It is not an error. Keyspace is simply too large. Try a more clever attack (wordlist maybe); read some manuals/forums.
Good luck!

**Comment by Victini517** [comment]
thanks
