### ISSUE TITLE
feature request: WPA hashmodes 2500/2501 improvement hccapx messagepair field

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1525]
hashcat runs nonce-error-corrections (default value 8) for big endian routers and little endian routers.
hcxtools are able to detect the router type and set a bit in the messagepair field to inform hashcat about endianess of the router. Using this information, hascat can run nonce-error-corrections only for the detected endianess. The will speed up calculation. No change of hccapx struct neccessary (we can stay on version 4).
If you agree we can use this bitmask for the messagepair field:
0 MP info
1 MP info
2 MP info
3 x (unused)
4 x (unused)
5 LE router detected (1)
6 BE router detected (1)
7 not replaycount checked (1)

example (anonce:MP:ESSID):
$ wlanhcxinfo -i BE_bit_test.hccapx -A -p
dccda13dc8b577cf1959e6e5ea738ef2789b1ec9b1c66ec7050f608511fa4dc8:42:WLAN-2

$ wlanhcxinfo -i LE_bit_test.hccapx -A -p
dccda13dc8b577cf1959e6e5ea738ef2789b1ec9b1c66ec7050f608512fa4dc7:22:WLAN-2

Sent both hccapx files via pm to Atom.
nonce-error-corrections=1 required to recover PSK.

Reference:
https://github.com/ZerBea/hcxtools/commit/de3564ab09d1a7721ac0ba8f0487fd93c8121c0e

**Comment by RealEnder** [comment]
Please consider "negative" logic for bits 5&6.
Eg, if they are 0, we didn't detect BE/LE, if 6 is up, we should not check for BE, same for 5-LE. This way it looks to me more backward compatible.

**Comment by ZerBea** [comment]
additionally  to first request:
hcxtools would like to use also bit 4 of the message_pair field to indicate an ap-less attack:
bitmask for message_pair field:
0: MP info
1: MP info
2: MP info
3: x (unused)
4: ap-less attack (set to 1) - no nonce-error-corrections neccessary
5: LE router detected (set to 1) - nonce-error-corrections only for LE neccessary
6: BE router detected (set to 1) - nonce-error-corrections only for BE neccessary
7: not replaycount checked (set to 1) - replaycount not checked, nonce-error-corrections definitely neccessary

using bit 4 to 7, hcxtools are able to interact with hascat - that will increase speed for hashcat.

**Comment by RealEnder** [comment]
The flags from last comment implemented in JtR's tool hccapx2john.py: https://github.com/magnumripper/JohnTheRipper/commit/f8a1e676e29b9f7721baec20fafda705f95c060d

**Comment by jsteube** [comment]
Done with https://github.com/hashcat/hashcat/commit/547025ec475c2aaa4edf16184e91c24fbefe08ff
