### ISSUE TITLE
-m 5600 doesn't work correctly

### ISSUE THREAD

**Issue by mohemiv** [hashcat/hashcat#1527]
The NetNTLMv2 optimized kernel has a problem with bruteforcing some types of hashes:

```
$ echo "Hashcat@Example2018" | ./hashcat/tools/test.pl passthrough 5600 > test.txt
$ cat test.txt 
N356M78LY::V60W7Q205F5:bf223ddd4ac42547:9d1e67f730d03054bf236b72f7b096c6:0101000000000000844df756dc1c385b214ed5bb74f1480e000000003f5d59556e00
$ hashcat -m 5600 ./test.txt -O -a 3 'Hashcat@Example2018'
...
Password length minimum: 0
Password length maximum: 27
...
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
```

There is the same problem with -a 0 option, but I can't replicate this with test.pl.

**Comment by jsteube** [comment]
I can reproduce this but only in -a 3 mode if using -O. All other combination seem to work fine. Can you confirm?

**Comment by jsteube** [comment]
Issue should be fixed with commit https://github.com/hashcat/hashcat/commit/8079abffb015d1e000aa120670c1af7b2d7e8cbc

If not, please reopen the issue. Also note that in -O the maximum password length for is 27. This is also the case for -a 0.
