### ISSUE TITLE
ERROR: ./kernels/4318/m0000q_warp.sm_35.64.cubin: No such file or directory

### ISSUE THREAD

**Issue by MESWEB** [hashcat/hashcat#1531]
cudaHashcat-lite v0.9 by atom starting...

GPU-Loops: 256
GPU-Accel: 80
Password lengths range: 1 - 55
Platform: NVidia compatible platform found
Watchdog: Temperature limit set to 90c
Device #1: GeForce 920M, 4096MB, 954Mhz, 2MCU
ERROR: ./kernels/4318/m0000q_warp.sm_35.64.cubin: No such file or directory

**Comment by roycewilliams** [comment]
This is an extremely old version of hashcat. Please upgrade to the latest at hashcat.net.

**Comment by MESWEB** [comment]
Yes I know that but only this version support SL3. I was found my old phone and I want use it again for security reason and that's why I want deal with SL3.

**Comment by Xanadrel** [comment]
I will kindly invite you to fuck off.

**Comment by roycewilliams** [comment]
Anything related to SL3 is verboten in the hashcat community. Long story (which predates my work with the project, but here are some breadcrumbs):

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_can_i_crack_sl3
https://hashcat.net/forum/thread-1887.html

Further, any version of hashcat that supports SL3 is so old that it is no longer supported in any way.

Further, as I understand it, cudaHashcat-lite v0.9 shouldn't even work anymore unless you're running a cracked version that circumvents time controls.

**Comment by MESWEB** [comment]
@Xanadrel - Thank You. Strong words. I'd like to go down to your level but I don't know how far away is the idiot.
@roycewilliams - Time control is not a problem for me. As You can see I was start this script. Thank You for links but I was see this before I post here. I don't understand why all dev is angry for somebody who is looking for help. If You wish - You can help me with this problem or copy post from @Xanadrel.
Thank You for all

**Comment by neheb** [comment]
I will kindly invite you to fuck off.

**Comment by MESWEB** [comment]
@neheb :1st_place_medal: 

![](https://www.quotemaster.org/images/dd/dd142338adeacbd2687c872d035931b7.jpeg)

**Comment by MESWEB** [comment]
I found file but another one is missing.
./kernels/4318/css_be.sm_35.64.cubin: No such file or directory
