### ISSUE TITLE
Support for Ansible Vault

### ISSUE THREAD

**Issue by ngsimon** [hashcat/hashcat#1532]
Hello,

It would be nice to add the support for Ansible Vault. Further information are added below.

Vault algorithm:
- https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py

Decryption examples:
- https://github.com/ansible/ansible/blob/060001b08d98969217156b2b696613ade44eb8c5/test/units/parsing/vault/test_vault.py

Example of vault password files: 
- https://raw.githubusercontent.com/ansible/ansible/e238ae999b90b771f662ac15e6cceff8aa0b721f/test/integration/targets/vault/format_1_1_AES.yml
- https://raw.githubusercontent.com/stevenharradine/ansible-vault-brute-force/master/vault.yml

Thanks in advance!

**Comment by SpenGietz** [comment]
I'd like this too!
