### ISSUE TITLE
Support for Telegram Passcode (android)

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#1534]
The popular chat-app Telegram has a feature in the settings-menu to protect the app with a passcode. The source code for this protection can be found on the [Telegram-github (line 411)](https://github.com/DrKLO/Telegram/blob/4ebcbf61cd1ce04685c82f93b962d1094c5ffac2/TMessagesProj/src/main/java/org/telegram/messenger/UserConfig.java).

One finds the passcodeHash and the passcodeSalt in the user file *userconfig.xml*.

When reading the code, it seemed to me that it is very easy to find the passcode. I wrote the following script to retrieve the passcode. [See my Github-page for the details.](https://github.com/Banaanhangwagen/Telegram-Passcode-Bruteforce)

So, the used algorithm is `sha256($salt:key:$salt) = $pass
`Correct?

Can this be added to Hashcat?

**Comment by magnumripper** [comment]
How long is that salt? Can you please provide a test vector with a known password?

**Comment by Banaanhangwagen** [comment]
The salt is 16 bytes long. The key is 4 bytes. So in total it makes 16+4+16 bytes.
```
Testhash: a577888ff9a47b788e7f8f843d3a3e627b06684ffc89dddc2d7647e3dcf43703
Testsalt (base64 encoded): /gGQ5AXwllHCGxpp1aB1aA==
Passcode: 3033
```

**Comment by magnumripper** [comment]
Is it always 4 digits? A trivial CPU implementation or even a perl script exhausts that keyspace in a few seconds. Writing a GPU format for it would be a total waste of time.

If the key can be other characters, perhaps even Unicode ones, it makes a little more sense.

**Comment by Banaanhangwagen** [comment]
Exactly, it is always 4 digits.

I understand your argument.
My script does the job in a couple of seconds. Because the *Apple restrictions password* is supported (plist2hashcat), i thought it would be cool to implement this one also...

**Comment by jsteube** [comment]
I think we can simply add sha256($salt . $pass . $salt), and add a loader on top of it. What's the native parser output of the hash and salt?

**Comment by Banaanhangwagen** [comment]
I do not understand your question. Can you please reformulate?
I think you mean this:
The hash and salt are found in the _userconfing.xml_ (typo intended); 
`passcodeHash `is found in hex uppercase
`passcodeSalt `is found in base64
See real life examples in my first reply.

**Comment by jmvermeulen** [comment]
I've check this on iOS. But the passcode can be 4 or 6 digits or a password. This makes it much wider then earlier specified.

On Android it's indeed 4 digits, but also a password option.

In all cases having the phone and open the locked telegram screen will reveal the expected input variant.

**Comment by philsmd** [comment]
As mentioned in https://github.com/hashcat/hashcat/pull/2282#issuecomment-595715736 we use the $telegram$0 format for hashcat, see the Pull Request from above for an example (or use the command: hashcat -m 22301 --example-hashes)

**Comment by malbolgeunshackled** [comment]
does anybody know where can I find userconfig.xml or any other similar file which contains telegram passcode hash on iOS?
