### ISSUE TITLE
support for Multibit Classic

### ISSUE THREAD

**Issue by easyname889** [hashcat/hashcat#1538]
Would be great to have support for "Multibit Classic" key hashes

Test-hash
sleepy.key:$multibit$1*935f8d9b235bff03*e25936c998d095467b727db1028d9d6e4a6660bb8c48b4b6fb43ab8c348c45f2
Password:WinSuxx

https://github.com/magnumripper/JohnTheRipper/blob/7dd60616a4f08bbe26cf529997a827792fe7da79/run/multibit2john.py

Keyfiles
https://github.com/magnumripper/JohnTheRipper/files/1004226/MultiBitWallets.zip

This is not a standard hash but have support as well
https://github.com/gurnec/btcrecover/blob/master/extract-scripts/extract-multibit-privkey.py

**Comment by easyname889** [comment]
Just found this below, does this mean that it's possible to run a multibit classic hash with the correct defined variables?

Then how is it done?

https://github.com/hashcat/hashcat/issues/393

Thanks

**Comment by brucebarnes** [comment]
I'm looking for this as well.  Lost my password on a multibit classic wallet.  Ran 21M attempts using btcrecover and got nada.  If I try anything from scratch I run out of memory, need some GPU power.  

Some links I found with some code that could help.

https://github.com/magnumripper/JohnTheRipper/blob/7dd60616a4f08bbe26cf529997a827792fe7da79/run/multibit2john.py
Line 1000 https://github.com/gurnec/btcrecover/blob/master/btcrecover/btcrpass.py
https://gist.github.com/markjenkins/7036740

**Comment by philsmd** [comment]
did you run the python script multibit2john.py (https://raw.githubusercontent.com/magnumripper/JohnTheRipper/bleeding-jumbo/run/multibit2john.py) to see which format/algo is used for your wallet.

As explained over here there are several versions: https://github.com/hashcat/hashcat/issues/2023#issuecomment-492942311

**Comment by kost123** [comment]
Been waiting for this for a good year or so xD Wonder if it's even any faster on GPU vs CPU.

**Comment by philsmd** [comment]
The MD5-based algorithm for MultiBit Classic was implemented with https://github.com/hashcat/hashcat/pull/2306 .

I really hope you guys appreciate this huge change and if possible give some feedback after testing if it works for you (beta can be found at https://hashcat.net/beta/ )

**Comment by kost123** [comment]
That is absolutely awesome, been waiting for this for years, thanks a lot.
