### ISSUE TITLE
Hashcat 4.1.0 Windows PATH Bug

### ISSUE THREAD

**Issue by GrepItAll** [hashcat/hashcat#1539]
I have the hashcat-4.1.0 directory extracted into the root of the C: drive on a PC (C:\hashcat-4.1.0) and have the Windows PATH set to include this folder.

The machine is running 64bit Windows 10 Pro.

I tried calling the hashcat64 binary from another folder through command prompt or powershell e.g. ```C:\example>hashcat64 -a 3 -m 10.....```

However, I get this error:

```./hashcat.hctune: No such file or directory```

I have confirmed that this file is in fact present within the hashcat-4.1.0 directory. This issue does not exist with hashcat-4.0.1

Hope that helps!

**Comment by KeyC0de** [comment]
I have the exact same error. Did you figure it out?

**Comment by KeyC0de** [comment]
I'm not sure what went wrong. I simply executed the command from hashcat root directory instead and it worked. I was executing from an arbitrary location preciously and simply pointing to hashcat64.exe binary. I am on Windows 8.1.

**Comment by GrepItAll** [comment]
No, I didn't resolve this. I agree that executing from an arbitrary location doesn't seem to work, but executing from the hashcat root directory does work.

**Comment by jsteube** [comment]
There's a long discussion on this on a different issue and I'm afraid that's the only way of doing it. You need to cd to hashcat installation folder first. There's currently no way of working around that.

**Comment by zvodd** [comment]
@jsteube what is that issue number? Is there a plan to fix this?

**Comment by bledari** [comment]
Why is this closed, @jsteube you should reopen it

**Comment by NilsOlze** [comment]
Agreeing with @bledari, it should be open as known issue / discussion, since it is still present and searching only display open issues by default. 
Just dropping a link to the other issue would be enough information @jsteube .

**Comment by OscarAkaElvis** [comment]
I did a workaround for this. Maybe could be useful to somebody. I'll explain it.

 - First I added haschat dir to the PATH environment (remember to close cmd prompt and reopen it after modifying PATH env var to get new changes working). After doing this, I can run `hashcat64.exe -V` from anywhere but If I launch `hashcat -b -m 0 -D 1 --force` to test it is still failing saying `./hashcat.hctune: No such file or directory`.

 - Then I created on my hashcat directory (in my case is `C:\Program Files\hashcat-5.1.0`) a file called `hashcat.bat` . The content of the file is this:

```
@echo off
set original_dir="%CD%"
cd "C:\Program Files\hashcat-5.1.0"
hashcat64.exe %*
cd "%original_dir%"
``` 

The `orgininal_dir` var is set in order to return to the same directory where you are once launched. Otherwise it will change always our cmd prompt to hashcat directory. **Remember that on the third line of the bat, the path that must be appear is where you have your hashcat (the same dir you added to the PATH env var, in my case is `C:\Program Files\hashcat-5.1.0`).**

 - Last step, just test it! Execute from anywhere `hashcat -b -m 0 -D 1 --force` <- this command execute the minimal benchmark test using CPU.

This worked for me on hashcat 5.1.0 for Windows (W10).

**Comment by ignis-sec** [comment]
I'd like to leave my bit of help here for people having the same issue by extending @OscarAkaElvis' answer. 
While it was really helpful, provided batch file wont return to the same directory if hashcat is located in another drive.
You can further modify that script by handling directory changes between different disks as such:
```
@echo off
set original_dir=%CD%
D:
cd "D:\sec\hashcat-5.1.0"
hashcat64.exe %*
cd "%original_dir%"
for /f "tokens=1 delims=\\" %%G IN ("%original_dir%") DO %%G
```

**Comment by elig0n** [comment]
Another way is to use [shimgen](https://github.com/chocolatey/shimgen) to generate a "shim" .exe file and pass it `--shimgen-usetargetworkingdirectory`. If it will one day allow to embed this option in the executable itself without requiring to pass an argument it will be even more comfortable !

**Comment by SuperStormer** [comment]
My workaround is to use python to rewrite any relative paths and then call hashcat.
```python3
#!/usr/bin/env python3
import os
import sys
from pathlib import Path
HASHCAT_DIR = "*insert hashcat dir*"
HASHCAT_EXECUTABLE = "hashcat.exe"
cwd = Path(os.getcwd())
args = []
for arg in sys.argv:
    f = cwd.joinpath(arg)
    if f.exists():
        args.append(f)
    else:
        args.append(arg)
os.chdir(HASHCAT_DIR)
os.execve(HASHCAT_DIR.joinpath(HASHCAT_EXECUTABLE), args, os.environ)
```

**Comment by pouriap** [comment]
This is utterly broken behavior and closing the issue is just ridiculous.
Why isn't anyone fixing this? How hard could it possibly be?
So anyone in the world who is using hashcat either copies their hashes to the hashcat directory every single time they want to use hashcat, or uses the full path of the hash every time. You gotta be kidding me.

**Comment by samm4444** [comment]
I'm still getting this problem on hashcat-6.2.4. Is there something I should be doing or is this still not fixed?
If this is still not resolved then should this issue still be open @jsteube

**Comment by tijldeneut** [comment]
I agree, although it is a feature request, not a bug (works as intended).

**Comment by lashchev** [comment]
I'm afraid I have to disagree with @tijldeneut and @jsteube. This is a bug or serious design flaw. Imagine that I would need to change the directory to the related installation directory if I want to use git, curl, dos utilities, or nodejs? On top of this, hashcat creates a bunch of temp/out files in that directory::

- {sessionName}.outfiles" directory
- {sessionName}.pid - file
- {sessionName}.log - file
- hashcat.potfile - file

It makes that distro directory polluted super-fast, and it is hard to understand what files were there from the beginning and what files were created as part of my hashcat execution.

I ended up creating a command file similar to @OscarAkaElvis but a bit simpler:
```
@echo off
pushd "C:\hash\hashcat-6.2.4"
hashcat.exe %*
popd
```
But it is pretty annoying.

**Comment by Flangyver** [comment]
Almost 4 years later and a simple issue of using a relative path instead of an absolute path still hasn't been fixed with version 6.2.6. Is this going to ever be addressed?

**Comment by DanielSousa00** [comment]
@lashchev Yes it worked for me. Then you just call it when you open CMD.
![image](https://user-images.githubusercontent.com/102512723/228271841-67f0f573-7f9a-4145-95e5-7dd324e35d4a.png)

**Comment by makako-dev** [comment]
I know this post is old but just wanted to share the way I circumvent this problem. In windows, i just use set up my powershell profile to use an alias as such:

`Set-Alias -Name hashcat "path\to\hashcat\directory\hashcat.exe"`

**Comment by pmcstjean** [comment]
Like @lashchev said, serious design flaw. Saying "work as intended" doesn't make any sense.

**Comment by ScottQB4** [comment]
Where does the program think it is?
Most cmd programs aren't this pointlessly convoluted (and actually _know_ where it's working.).
For something as simple and dumb as this becoming a staple of an issue, when did programmers get this stubborn and/or retarded?

**Comment by PenguinKeeper7** [comment]
Completely agree that this issue isn't working as intended and should've been re-opened a long time ago but has been fixed in the above PR, 4180 ^ so now any current directory should be able to use Hashcat as normal

**Comment by Mushroomizer** [comment]
Yea this is still an issue on windows. Why is this not being reopened?

Edit: To add, the workaround works, but is not an ideal experience
This is what makes it work

> I'm afraid I have to disagree with [@tijldeneut](https://github.com/tijldeneut) and [@jsteube](https://github.com/jsteube). This is a bug or serious design flaw. Imagine that I would need to change the directory to the related installation directory if I want to use git, curl, dos utilities, or nodejs? On top of this, hashcat creates a bunch of temp/out files in that directory::
> 
> * {sessionName}.outfiles" directory
> * {sessionName}.pid - file
> * {sessionName}.log - file
> * hashcat.potfile - file
> 
> It makes that distro directory polluted super-fast, and it is hard to understand what files were there from the beginning and what files were created as part of my hashcat execution.
> 
> I ended up creating a command file similar to [@OscarAkaElvis](https://github.com/OscarAkaElvis) but a bit simpler:
> 
> ```
> @echo off
> pushd "C:\hash\hashcat-6.2.4"
> hashcat.exe %*
> popd
> ```
> 
> But it is pretty annoying.
