### ISSUE TITLE
My Mac restart after few hours of every brute force attempt

### ISSUE THREAD

**Issue by Virgula0** [hashcat/hashcat#1540]
I'm trying to crack with hashcat and I downloaded manually the git with make and all commands to check some other problems listed here: https://github.com/hashcat/hashcat/issues/1530

So I'm using that version (v3.6.0-48-g52c1e15f), but there is a problem..... After an indeterminate time using that hashcat, my osx crashes for no reasons restarting the entire o.s every time...
Why it happens? It seems to be a problem with kernel that can't work anymore and for security reason osx restart itself to protect the device...

**Comment by philsmd** [comment]
maybe a temperature issue?
Did you try with lower workload/performance settings, e.g. with -w 1 ?

Is this a macbook/notebook?

**Comment by magnumripper** [comment]
FWIW, most often when my macbook crashed good enough to reboot (which is very very rare), it was a "watchdog timer" issue. I have yet to find a way to turn that shite off on macOS.

**Comment by jsteube** [comment]
No response from OP for a long time, therefore closing the issue. Feel free to reopen if you have new insights.

**Comment by jsteube** [comment]
No response from OP for a long time, therefore closing the issue. Feel free to reopen if you have new insights.
