### ISSUE TITLE
information about skype

### ISSUE THREAD

**Issue by lhoo** [hashcat/hashcat#1544]
Hello,
Can anyone tell me where the skype's hash value comes from in this example? How can I get this hash value?

> 23 | Skype | 3af0389f093b181ae26452015f4ae728:user

in https://hashcat.net/wiki/doku.php?id=example_hashes

Thanks in advance!

**Comment by philsmd** [comment]
At least for older versions of skype (I didn't verify if this is still the case, probably yes) there was a hash stored within a config.xml file.
Read some details here: https://web.archive.org/web/20161217080113/http://insecurety.net/?p=427

BTW: you should use the forum for discussions like this. github is only used to request new features and report bugs/problems. Thx
