### ISSUE TITLE
Option to disable hash sorting and counting

### ISSUE THREAD

**Issue by roo7break** [hashcat/hashcat#1545]
Every time hashcat loads a hash file it tries to count and sort the hashes. However, this process seems to be taking a very long time. 

To speed up the whole process (especially when performing batch jobs) it would be really useful if additional flags are provided:
- flag to disable sorting (for pre-sorted hash list)
- flag to provide file count manually

**Comment by philsmd** [comment]
I think that the only way something like this could work is a mechanism similar to the dictstat file (for wordlists): hashcat could remember that it already parsed and sorted these set of hashes and have some file timestamps to make sure that the files didn't change in the meantime. It could even dump the sorted (prepared) hash list to a separate file on disk and pick it up if the user uses the same hash list again and again.

I don't think that hashcat could trust the user that it sorted the hash list correctly and that it wasn't changed afterwards :(  Therefore it needs to be done by hashcat and verified.

The disadvantage of this is that in the worse case hashcat would need to store at least a file as large as the original hash file (+ some metadata, like timestamps etc).

**Comment by jsteube** [comment]
I like the idea of the cached hashlist blob. However, this could create a mess in the hashcat installation folder. The question is in the details. Should we store such a blob in the same folder as the original hashlist or should we use a special blob folder to do that? I'd think the first one sounds better. We also need to have a different filename ideally with a special filename suffix (eg: .hcdump or so). 

We'll also need some sort of header. Any ideas of the required attributes? 

Oh and what about if the user changes the data in the original hashfile. We need to make sure that there's no change. We could, for example, store the original hashfile filestats (as @philsmd already said as we do in dictstat) and compare them before we allow hashcat to load the blob.

Finally the question is: Is it worth having such a complex system and what's the benefit? The only affected users would be users with very large hashlists. But for hashlists < 1M hashes this creates almost no advantage. I'd think most of the hashlists load by hashcat are small hashlists and single hashes but I don't have any real statistics about that.

**Comment by roycewilliams** [comment]
Perhaps the blob could be created only if the hashlist is above a certain size in bytes, as presented by the filesystem.

**Comment by jsteube** [comment]
I was talking about the complexity this adds to the hashcat sources. There's simply not enough good reason to do this. Feel free to reopen if there are new arguments.

**Comment by Kafkamorph** [comment]
I'm pointing to a couple of million hashes and my box is almost stopped for 30 minutes because hashcat has eaten all my ram /and/ swap.
I think some optimisation (any, really) would be better than the current state.

PS - the hashfile is already sorted, this isn't even needed.

**Comment by roycewilliams** [comment]
@Kafkamorph, the sorting is for reasons that may not be apparent.

@jsteube, I think a FAQ entry is needed for this, to explain why the sorting happens, what kind of sorting it is, etc.

**Comment by arlininger** [comment]
An FAQ entry on why sorting happens would be helpful. Even explaining that here would at least make it findable via google. I also suffer from delays when running large lists of hashes. It would be nice to save time and sort the hashes once.

Personally, I would like a flag to indicate that the hashlist is already sorted (with proper warnings on improper results etc. if that should happen to be a lie). A reasonably good alternative would be  some indication (maybe in the FAQ) on how the list should be sorted ahead of time to minimize the time taken in each run.
