### ISSUE TITLE
Dictionary Attack against Cascaded Truecrypt supported?

### ISSUE THREAD

**Issue by sssseossss** [hashcat/hashcat#1547]
Hi,
sorry, but cannot find info - does hashcat supports cascaded ciphers to brute truecrypt volumes?
Sorry for asking here - could not find this info elsewhere.
Thanks!

**Comment by roycewilliams** [comment]
This is a question that is better suited for the hashcat forums.

But yes, the Truecrypt 62xx family of hash types supports at least some of the possible cascades.

**Comment by jsteube** [comment]
All cascades are supported for TrueCrypt.
