### ISSUE TITLE
Not an issue just a question how to refresh hashcat

### ISSUE THREAD

**Issue by nightshadow36** [hashcat/hashcat#1548]
I was trying out hashcat on windows and decided to try out linux.
On windows its refreshes every 60 seconds, is there a command so it refreshes its status every 60 seconds in ubuntu?
Thank you.

**Comment by philsmd** [comment]
it's not clear what you mean by refresh.

If you are using the --status command line argument, you could just set the --status-timer to the number of seconds for your preferred interval. If you do not use --status, hashcat does not automatically refresh at all (you need to hit the s key on your keyboard or enter).

Questions like this should go to the hashcat forum (you can even use the search function and find some similar questions and answers)
