### ISSUE TITLE
PDF 1.7 signature not recognized

### ISSUE THREAD

**Issue by devwhatsapp** [hashcat/hashcat#1551]
Hi

Tried all values from  10400 - 10700

I am getting line length or signature unmatched error.

Hash taken from PDF 1.7

`$pdf$4*4*128*-3904*1*16*8aaf9105962aaa4182602a81b9485e69*32*615bb2bf8976796e272a3ca130b417d76a6d4429f3a6c5f3ab574bf17a02ff7d*32*3add260c37d64307876f6f0168414109638d74600eeccb925d4d472ee462e4f0`

Command used - 

`hashcat -m 10400 -a 3 -w 3 $pdf$4*4*128*-3904*1*16*8aaf9105962aaa4182602a81b9485e69*32*615bb2bf8976796e272a3ca130b417d76a6d4429f3a6c5f3ab574bf17a02ff7d*32*3add260c37d64307876f6f0168414109638d74600eeccb925d4d472ee462e4f0 ?b?b?b?b?b?b?b?b?b?b`

Please check and let me know why this hash is not working.

Version used :hashcat (v4.1.0-7-gf6cfcbb)

**Comment by magnumripper** [comment]
What if you put single quotes around the hash as in
```
hashcat -m 10400 -a 3 -w 3 '$pdf$4*4*128*-3904*1*16*8aaf9105962aaa4182602a81b9485e69*32*615bb2bf8976796e272a3ca130b417d76a6d4429f3a6c5f3ab574bf17a02ff7d*32*3add260c37d64307876f6f0168414109638d74600eeccb925d4d472ee462e4f0' ?b?b?b?b?b?b?b?b?b?b
```

**Comment by devwhatsapp** [comment]
That works. :)

Need to change 10400 to 10500

`hashcat -m 10500 -a 3 -w 3 '$pdf$4*4*128*-3904*1*16*8aaf9105962aaa4182602a81b9485e69*32*615bb2bf8976796e272a3ca130b417d76a6d4429f3a6c5f3ab574bf17a02ff7d*32*3add260c37d64307876f6f0168414109638d74600eeccb925d4d472ee462e4f0' ?b?b?b?b`

`Session..........: hashcat
Status...........: Running
Hash.Type........: PDF 1.4 - 1.6 (Acrobat 5 - 8)
Hash.Target......: $pdf$4*4*128*-3904*1*16*8aaf9105962aaa4182602a81b94...62e4f0
Time.Started.....: Sat Mar 24 01:25:01 2018 (24 secs)
Time.Estimated...: Sat Mar 24 03:38:21 2018 (2 hours, 12 mins)
Guess.Mask.......: ?b?b?b?b [4]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   536.9 kH/s (119.49ms) @ Accel:256 Loops:35 Thr:64 Vec:8
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 12582912/4294967296 (0.29%)
Rejected.........: 0/12582912 (0.00%)
Restore.Point....: 0/16777216 (0.00%)
Candidates.#1....: $HEX[7c617269] -> $HEX[7cffff01]
HWMon.Dev.#1.....: N/A

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit =>`

Anything more than 4 of "Guess.Mask.......: ?b?b?b?b" - goes to 23 days and above on my system. guess this hash cant be cracked.

Did I miss reading about the single quote somewhere ?

One thing I do not understand , the hash was obtained from 1.7 version 128 bit key , but we have to use -m 10500 which is for the lower version.

Thank you so much

**Comment by jsteube** [comment]
```
Did I miss reading about the single quote somewhere ?
```

No, but it's the shell interpreting the $, not hashcat.

```
One thing I do not understand , the hash was obtained from 1.7 version 128 bit key , but we have to use -m 10500 which is for the lower version.
```

(Guessing here): Probably the document was created with an older PDF version and then updated on a newer PDF version, which then sticks to the old encryption for backward compatibility.
