### ISSUE TITLE
Cannot crack sha512hashes

### ISSUE THREAD

**Issue by Sivylla** [hashcat/hashcat#1554]
Hi!

Could you help me please, I cannot crack sha512 with hashcat.

**# System**
Ubuntu Server 17.10
Linux hashkiller 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
Distributor ID:        Ubuntu
Description:            Ubuntu 17.10
Release:                  17.10
Codename:             artful

**# GPU**
  *-display
       description: VGA compatible controller
       product: Hawaii PRO [Radeon R9 290/390]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:27 memory:e0000000-efffffff memory:f0000000-f07fffff ioport:e000(size=256) memory:f7e00000-f7e3ffff memory:c0000-dffff
  *-display
       description: VGA compatible controller
       product: Hawaii PRO [Radeon R9 290/390]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:02:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:28 memory:c0000000-cfffffff memory:d0000000-d07fffff ioport:d000(size=256) memory:f7d00000-f7d3ffff memory:f7d40000-f7d5ffff

**# Hashcat**
root@hashkiller:/hashcat# hashcat -V
v4.1.0-7-gf6cfcbbc

**# Action**
**## Create hash**
`mkpasswd -m sha-512 -S n.x8pyjJ -s 12345 > test.hash`
Result:
$6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc6wH4oAbk.ooVn4W8yEQijadbVgKLG9omTmVJBzX.CtMLTa1

**## Crack hash I**
`hashcat -a 3 -m 1800 --status -o output.txt test.hash 12345`
Result:
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: sha512crypt $6$, SHA512 (Unix)
Hash.Target......: $6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc...tMLTa1
Time.Started.....: Wed Apr  4 03:28:14 2018 (1 sec)
Time.Estimated...: Wed Apr  4 03:28:15 2018 (0 secs)
Guess.Mask.......: 12345 [5]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        4 H/s (0.74ms) @ Accel:32 Loops:16 Thr:64 Vec:1
Speed.Dev.#2.....:        0 H/s (0.00ms) @ Accel:32 Loops:16 Thr:64 Vec:1
Speed.Dev.#*.....:        4 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: 12345 -> 12345
Candidates.#2....: [Generating]
HWMon.Dev.#1.....: Temp: 63c Fan: 44% Core:1040MHz Mem: 150MHz Bus:16
HWMon.Dev.#2.....: Temp: 52c Fan: 34% Core:1040MHz Mem: 150MHz Bus:16

Started: Wed Apr  4 03:28:12 2018
Stopped: Wed Apr  4 03:28:16 2018

There is no file output.txt

**## Crack hash II**
`hashcat -a 3 -m 1800 test.hash 12345`
Result:
Session..........: hashcat
Status...........: Exhausted
Hash.Type........: sha512crypt $6$, SHA512 (Unix)
Hash.Target......: $6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc...tMLTa1
Time.Started.....: Wed Apr  4 03:28:14 2018 (1 sec)
Time.Estimated...: Wed Apr  4 03:28:15 2018 (0 secs)
Guess.Mask.......: 12345 [5]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        4 H/s (0.74ms) @ Accel:32 Loops:16 Thr:64 Vec:1
Speed.Dev.#2.....:        0 H/s (0.00ms) @ Accel:32 Loops:16 Thr:64 Vec:1
Speed.Dev.#*.....:        4 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: 12345 -> 12345
Candidates.#2....: [Generating]
HWMon.Dev.#1.....: Temp: 63c Fan: 44% Core:1040MHz Mem: 150MHz Bus:16
HWMon.Dev.#2.....: Temp: 52c Fan: 34% Core:1040MHz Mem: 150MHz Bus:16

Started: Wed Apr  4 03:28:12 2018
Stopped: Wed Apr  4 03:28:16 2018

There is no result

**# Addition information**
Microsoft Office passwords were cracked perfectly!

Help me please :) Cannot understand the reason why it cannot crack this type of hashes. 
Thank you!

**Comment by jsteube** [comment]
Can not reproduce locally. Please reinstall hashcat and make sure to not reuse an existing folder for installation. Please feel free to reopen if you have more information in order how to reproduce this error:

hash:

```
root@et:~/hashcat# cat test.hash 
$6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc6wH4oAbk.ooVn4W8yEQijadbVgKLG9omTmVJBzX.CtMLTa1
```

on CPU:

```
root@et:~/hashcat# ./hashcat -a 3 -m 1800 --status test.hash 12345 -D1 --quiet --potfile-disable 
$6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc6wH4oAbk.ooVn4W8yEQijadbVgKLG9omTmVJBzX.CtMLTa1:12345
```

on GPU:

```
root@et:~/hashcat# ./hashcat -a 3 -m 1800 --status test.hash 12345 -D2 --quiet --potfile-disable  
$6$n.x8pyjJ$y/9YEn.7e3TrjfAmbvVK89rE9u5YlUBJyqWambc6wH4oAbk.ooVn4W8yEQijadbVgKLG9omTmVJBzX.CtMLTa1:12345
```
