### ISSUE TITLE
No progress being made

### ISSUE THREAD

**Issue by dlo** [hashcat/hashcat#1555]
Hi all. Thanks for this amazing utility! I'm running into an issue where hashcat doesn't seem to be making any progress towards completion. I'm attempting to recover a password from an iTunes backup.

I'm running my hash with a single character, and progress stalls at 0/1.

    hashcat -m 14800 -a 3 -1 a '$itunes_backup$*10*8ef8c0bcbda32d9a277c2b2c2552eaaefed0926206bd6eb17551050eebaa58896c2aac7d43505649*10000*ecaf02ffd31e819abab6c14772e22aed1929eac5*10000000*bb64e7dc719c3bde468de396a5c34d42a673f267' ?1

Result:

```
Session..........: hashcat
Status...........: Running
Hash.Type........: iTunes backup >= 10.0
Hash.Target......: $itunes_backup$*10*8ef8c0bcbda32d9a277c2b2c2552eaae...73f267
Time.Started.....: Wed Apr  4 12:28:52 2018 (1 sec)
Time.Estimated...: Wed Apr  4 12:28:53 2018 (0 secs)
Guess.Mask.......: ?1 [1]
Guess.Charset....: -1 a, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:        0 H/s (0.69ms) @ Accel:2 Loops:62 Thr:256 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/1 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#2....: a -> a
```

No matter how long I wait, Time.Estimated remains at "0 secs" but Progress is stuck at 0/1. Any ideas? Thanks in advance!

**Comment by jsteube** [comment]
This algorithm is so slow that it usually takes up to 2 minutes to perform a full walkthrough of the workitem slice. It's not stuck, it's just very slow. After that time, it's able to update the status screen, but not before that.
