### ISSUE TITLE
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE | scrypt

### ISSUE THREAD

**Issue by kolet** [hashcat/hashcat#1559]
hey ya,

so i am trying to use Scrypt when running it on the hash example it works with no error, but when i try to run it on another Scrypt hash the error happen.

command

hashcat64.exe -a 3 -m 8900 hash  -w 4 -O pass

the start of the hash is SCRYPT:4096:12:4:salt:hash

`./OpenCL/m08900-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
Increasing single-block device memory allocatable for --scrypt-tmto 1.
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILUREclEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: scrypt`

using cpu does not bring this error tho

**Comment by jsteube** [comment]
Looks good to me. Your GPU simply does not have enough memory to do it. Note that there's a critical difference between CPU and GPU, it's the number of compute units. For a CPU we're talking about 16, for a GPU we're talking about 4096. This multiplier is it that need to be applied to memory, too. IOW, you need 256 times the total memory size on each GPU that you have on your host system. If you do not have it you need to stick to CPU.
