### ISSUE TITLE
Adding #* (addition of speeds) for--benchmark

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#1561]
Like in the status display:

> Speed.Dev.#1.....:   400.0 kH/s
> Speed.Dev.#2.....:   293.3 kH/s
> **Speed.Dev.#*.....:  1108.5 kH/s**

Could you add the same "Speed.Dev.#*" addition of speeds for --benchmark mode ?
Current benchmark output is:
> 1:8300:1911:4513:72.15:1441236354
> 2:8300:1860:3802:60.25:1301211412
> 3:8300:1961:4513:73.49:1416894837

Thank you.

**Comment by jsteube** [comment]
I was thinking of that when I've added benchmark mode. However it's very likely benchmark number are post-processed either manually or automatically. The change would be easy, I'm just not sure if it creates more problems than not having it. The only reason why someone would like to see it is to be able to compare two or more entire systems to each other. But IMO that should be done on a different level (excel sheet or whatever).
