### ISSUE TITLE
How to install "hashcat" in terminal

### ISSUE THREAD

**Issue by 687766616e** [hashcat/hashcat#1562]
How to install "hashcat" in terminal (termux)?

$ uname -a
Linux localhost 4.4.78-perf-gc4c4293 #1 SMP PREEMPT Thu Apr 19 03:06:23 CST 2018 aarch64 Android

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by meme-lord** [comment]
You can install it with your package manager, one of these should work:
apt-get install hashcat
pacman -S hashcat
yum install hashcat

If those don't work you can download the binaries/source from here: https://hashcat.net/hashcat/
and compile it yourself.

This question is more suited to the hashcat forums as it isn't an issue with the codebase (error, problem or feature).
You can also read the FAQ here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions

**Comment by BenjaminWegener** [comment]
https://github.com/termux/termux-packages/pull/1764#issuecomment-460623854
