### ISSUE TITLE
osx version can't support Hybrid Wordlist + Mask mode of pzip crack

### ISSUE THREAD

**Issue by guange2015** [hashcat/hashcat#1566]
test hash
```
$7z$2$19$0$$8$ed67abc850e5ff6e0000000000000000$2002785155$96$94$8644972279b5efb0c0df2e1e3c43af337e8127101f1128bdaeb662bed90b8569781722e26fda32c25b049908ee2e167e3e6c3025a394002e432a0acaddd8f191285919426ed18463de1e17881bd05550df054d7d44828e1455f70989d9cdd08f$175$00
```
1.dict
```
hello
world
```

`hashcat -m 11600 -a 6 -w 3 pass.hash 1.dict 123`

windows version (4.10) can cracked password is `hello123`
but osx version can't cracked on 4.10 and master branch.

**Comment by emwinkler** [comment]
Please provide details on MacOS version and hardware you are using.  Both the 4.10 master and latest github pull work just fine with your test for me on 2013 Macbook Air, MacOS 10.13.4, RX 580.

**Comment by guange2015** [comment]
osx version 10.13.4 
Intel Iris Graphics 6100 1536 MB
MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by guange2015** [comment]
.......cry
today i re try, can cracked.
