### ISSUE TITLE
Want hash when bruteforce has the option of equal, greater and lesser !

### ISSUE THREAD

**Issue by raikikon** [hashcat/hashcat#1568]
(target hash) < or = or > (constant value + (variable)) hash parallel on ocl.

**Comment by roycewilliams** [comment]
I don't understand the question. Can you give an example (that doesn't use a real/sensitive hash)?

**Comment by raikikon** [comment]
there should be an option while cracking the target hash, such that the newly generated hash while bruteforce colud be compared as equal greater or lesser than the target hash.
`for(string value = aaaaa to zzzzz)`
`{ if  (hashof(value) == target hash)`
`  break;`
`// but there should be option`
`if(hashof(value) < or > target hash)`
`break;`
`// want the option of < > or == so can implement block-chain with it`
`}`

**Comment by roycewilliams** [comment]
This is probably not a use case for hashcat. In the passwords/crypto context, two hashes being "less than" or "greater than" each other is irrelevant - because they are randomly distributed by design.

**Comment by raikikon** [comment]
i want that for the blockchain implementation
