### ISSUE TITLE
Plugging power source stops hashcat

### ISSUE THREAD

**Issue by sagerpager** [hashcat/hashcat#1569]
Whenever i plug in the power source of my laptop, the temperature begins to rise eventually till it reaches the limit. So hashcat shows the following error and exits.

HWMon.Dev.#3.....: Temp: 88c Fan:  0% Util: 91% Core:1030MHz Mem:1000MHz Bus:4

Temperature limit on GPU #3 reached, aborting...

Session..........: hashcat

What's going wrong ?

**Comment by roycewilliams** [comment]
Hi! The hashcat Github is for development of hashcat. This is a question better suited to [the support section of the hashcat forums](https://hashcat.net/forum/forum-45.html). Please post your question there.
