### ISSUE TITLE
Adding couple of options in hybrid mode | request

### ISSUE THREAD

**Issue by kolet** [hashcat/hashcat#1570]
in a nutshell

when using hybrid mode u can not use rules or increment

1, be able to use a rule set attack on the dictionary alone,
for example using toggle attack on , -a 6/7 dic.txt  ?d?d?d ,  be able to use a rule base attack only for the dic file and continue with the mask . 

so be able to do -a 6/7 dic.txt -r rule/toggle ?d?d

hello123
Hello123
hEllo123 ....

2, not sure if i found a bug but when using -m 2500 -a 6 cap.hccapx dic.txt 1234567890 (123..= mask)
it worked great not issue on hashing speed.
but when using -m 2500 -a 7 cap.hccapx 1234567890 dic.txt the hashrate droped drasticly yo 18 per sec instead of 3~mil (8 1080) ,  same thing happen with -a 1 with 2 dics 1stdics.txt (1234567890)  second dic (normal words.)

**Comment by jsteube** [comment]
1)

There's no easy way to add support for rules in hybrid attack. You can however do it manually pretty easy:

```
$ hashcat words.txt -r rules/toggle.rule --stdout -o newwords.txt
$ hashcat -a6 newwords.txt ?d?d?d
```

2) This is a feature, not a bug. By not feeding hashcat with enough wordlist candidates it can not make use of the parallelization power of a GPU. Read this: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed
