### ISSUE TITLE
Kernel 3710 optimised not working

### ISSUE THREAD

**Issue by aibosss** [hashcat/hashcat#1571]
with a known passwords dictionnary and a list of those hashes, hashcat find correctly when not using the optimised, but dont find anything using the optimised one.

**Comment by jsteube** [comment]
I can not reproduce this locally. Feel free to reopen the issue with additional informations/steps how to reproduce this.

```
root@et:~/hashcat# cat > hash
a3aa0ae2b4a102a9974cdf40edeabee0:242812778074
root@et:~/hashcat# cat > word
hashcat
root@et:~/hashcat# ./hashcat -m 3710 --quiet hash word --potfile-disable
a3aa0ae2b4a102a9974cdf40edeabee0:242812778074:hashcat
root@et:~/hashcat# ./hashcat -m 3710 --quiet hash word --potfile-disable -O
a3aa0ae2b4a102a9974cdf40edeabee0:242812778074:hashcat
```

**Comment by aibosss** [comment]
Sorry for delay in answer, havent looked at that project before now. I just retried and effectively, problem still same with hashcat 4.2.1 64 bits windows.
Non-optimised Worked and Optimised didn't.

Try your: ./hashcat -m 3710 --quiet hash word --potfile-disable -O
WITH:
42a5fb96fa75bb55c519678441306c88:98c00872f8e1c1e61fe9b956f55c944e  ( Sakamoto )
194816eedfcd66859e3f1e057dd01d17:0a93f38bed8e3d7265954e965393ee22 ( BERKELEY )
584820a9c6c809d49760856d39e52b6c:64288bcdb9cc8efecf048471ecab2e4a ( dookie69 )
