### ISSUE TITLE
hashcat Not working properly ？Initializing device kernels and memory.../usr/bin/ld: can not find -lstdc++

### ISSUE THREAD

**Issue by dd404x** [hashcat/hashcat#1573]
![image](https://user-images.githubusercontent.com/19923974/40220152-b6dfd9e6-5aaa-11e8-964f-233033dd6ad1.png)

**Comment by roycewilliams** [comment]
If the version of hashcat in the prompt in your directory (3.30) is the version you're running, that's an extremely old version. Please download the latest (4.10) from hashcat.net and retest. 

You may also want to make sure you're running the latest version of Kali, as I've heard that a number of OpenCL-related issues have been fixed there.

**Comment by dd404x** [comment]
@roycewilliams 
![image](https://user-images.githubusercontent.com/19923974/40220372-7d85d988-5aab-11e8-964a-53ad78aca38a.png)
No,thanks.

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/40220448-bb669b34-5aab-11e8-8a38-0663988b2366.png)

**Comment by roycewilliams** [comment]
You appear to be using `--force`. What warnings is hashcat giving you that are prompting you to use `--force`?

**Comment by dd404x** [comment]
@roycewilliams 
![image](https://user-images.githubusercontent.com/19923974/40246340-f8e9dbac-5afa-11e8-8edd-0a7a7420a6b2.png)
Because there is no graphics on this computer

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/40486191-2e823ac4-5f93-11e8-89d3-3379abf48ed6.png)

Who can help me？

**Comment by jsteube** [comment]
As stated on the webpage and all documentation, please use the Intel OpenCL runtime. POCL still seem to create problems with complex kernel. Using Intel OpenCL runtime will fix all your problems.
