### ISSUE TITLE
help command for hashcat...

### ISSUE THREAD

**Issue by MehmetAliCan10** [hashcat/hashcat#1576]
Is hashcat better or faster than crunch wordlist generator?

I need command for hashcat I need 6 digits example loweralpha see under example command for crunch...
crunch 6 6 -f /usr/share/rainbowcrack/charset.txt loweralpha -o /root/alphawordlist.lst

I do no know how I hashcat to 6 digits loweralpha command.. need help..

**Comment by MehmetAliCan10** [comment]
and which is fast for hashcat generator wordlist windows or linux?

**Comment by roycewilliams** [comment]
This is a question better suited to [the hashcat forums](https://hashcat.net/forum/forum-45.html).

**Comment by MehmetAliCan10** [comment]
ok

**Comment by MehmetAliCan10** [comment]
I can not thread or post... I get not email resend activation :/

**Comment by MehmetAliCan10** [comment]
You do not have permission to access this page. This could be because of one of the following reasons:
Your account has either been suspended or you have been banned from accessing this resource.
You do not have permission to access this page. Are you trying to access administrative pages or a resource that you shouldn't be? Check in the forum rules that you are allowed to perform this action.
Your account may still be awaiting activation or moderation. (Resend Activation Code)
You have accessed this page directly rather than using appropriate forms or link.

You are currently logged in with the username: 'mehmet-ali_can'

**Comment by jsteube** [comment]
```
-a 3 -1 ?l?d ?1?1?1?1?1?1
```
