### ISSUE TITLE
Hashcat does not recognize correct password from the list

### ISSUE THREAD

**Issue by testersz** [hashcat/hashcat#1582]
When cracking IPMI and RAdmin v2.2 hashes I observed following:
1. If dictionary does not contain correct password - nothing found, that is ok;
2. If dictionary contain correct password - Hashcat display first password from the list as correct password. 
I'm using: 
Linux kali 4.15.0-kali3-686-pae #1 SMP Debian 4.15.17-1kali1 (2018-04-25) i686 GNU/Linux
hashcat (v4.1.0)
 Is there some explanation or solution?

**Comment by wifislax-ng** [comment]
Opss , i open another commit with same issues, but hash WPA/WPA2.

**Comment by mhasbini** [comment]
@testersz @wifislax-ng If possible, please attach a test case (.hccap & passphrase combo).

**Comment by testersz** [comment]
Admin:f5e6da01af01000097a42cf27356aef866ef545ac4b9a762aaef010ca29c37ae40f69ebb3a74ecdf00000000000000000000000000000000140541646d696e:aa42b3a4cccc9ed949c94794dd0cc046e10128ce

password: pentest

admin:c5a53db2d854061a5ae8c28acc2a077b85859ede6ea952be1d2a00005a0b0000a74800008247000035383339313447423830333334354a44140561646d696e:d82a44aa893b842ca9659f6877f3c5c46374d607

password: 12345678

Explanation:
1) create small dictionarry

123
1234
test
pentest
12345678
123456
qwerty
2)executing hashcat
hashcat -m 7300 -o crack.txt --username hashes/IPMI.list lists/passwords.list

3) using this dictionary, result cracked, and shows "123" is suitable for the hashes
4) if we change "pentest" to "pentest1" in dictionary, and set --potfiles-disable
answer cracked only for one hash, and also "123"
5) if we change "12345678" to "112345678"
result is Exhausted Recovered (0/2)

**Comment by jsteube** [comment]
I can totally not reproduce this locally. Maybe you should use hashcat from hashcat site and not from Kali. Here's what I did:

```
root@ht:~/hashcat# cat hashes
Admin:f5e6da01af01000097a42cf27356aef866ef545ac4b9a762aaef010ca29c37ae40f69ebb3a74ecdf00000000000000000000000000000000140541646d696e:aa42b3a4cccc9ed949c94794dd0cc046e10128ce
admin:c5a53db2d854061a5ae8c28acc2a077b85859ede6ea952be1d2a00005a0b0000a74800008247000035383339313447423830333334354a44140561646d696e:d82a44aa893b842ca9659f6877f3c5c46374d607
root@ht:~/hashcat# cat words 
123
1234
test
pentest
12345678
123456
qwerty
root@ht:~/hashcat# ./hashcat -m 7300 hashes words --username -o cracked
hashcat (v4.1.0-22-g469fece1+) starting...

...

Hashes: 2 digests; 2 unique digests, 2 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

...

Dictionary cache hit:
* Filename..: words
* Passwords.: 7
* Bytes.....: 45
* Keyspace..: 7

...
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Type........: IPMI2 RAKP HMAC-SHA1
Hash.Target......: hashes
Time.Started.....: Wed Jun 13 16:59:40 2018 (0 secs)
Time.Estimated...: Wed Jun 13 16:59:40 2018 (0 secs)
Guess.Base.......: File (words)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:    19611 H/s (0.05ms) @ Accel:128 Loops:1 Thr:512 Vec:1
Recovered........: 2/2 (100.00%) Digests, 2/2 (100.00%) Salts
Progress.........: 14/14 (100.00%)
Rejected.........: 0/14 (0.00%)
Restore.Point....: 0/7 (0.00%)
Candidates.#1....: 123 -> qwerty
HWMon.Dev.#1.....: Temp: 37c Fan: 33% Util: 13% Core:1032MHz Mem:2700MHz Bus:16

Started: Wed Jun 13 16:59:37 2018
Stopped: Wed Jun 13 16:59:41 2018
root@ht:~/hashcat# cat cracked 
c5a53db2d854061a5ae8c28acc2a077b85859ede6ea952be1d2a00005a0b0000a74800008247000035383339313447423830333334354a44140561646d696e:d82a44aa893b842ca9659f6877f3c5c46374d607:12345678
f5e6da01af01000097a42cf27356aef866ef545ac4b9a762aaef010ca29c37ae40f69ebb3a74ecdf00000000000000000000000000000000140541646d696e:aa42b3a4cccc9ed949c94794dd0cc046e10128ce:pentest
```

**Comment by jsteube** [comment]
I've tested again on different hardware (NV, AMD and CPU). I still can not reproduce this. Please feel free to reopen if you have additional information to reproduce, but make sure to use the latest version.

**Comment by testersz** [comment]
From technical perspective - which Kali components may impact the process of cracking? 
Did you tried to reproduce it using Kali Linux?

**Comment by freeroute** [comment]
I have a same problem with hashcat v.4.x.x. I tried on 2 difference old laptop, the result: hashcat found passwords, but it is not the correct password.
I didn't report it, because I use OS Kali and amd-opencl-icd driver as workaround (2 different, 8 years old laptop with NVidia GeForce 8400M GS graphic card). With hashcat v.3.6.0 has no such problem, it works well.

With my new "upto-date" PC there is no problem with hashcat v.4.x.x.

**Comment by jsteube** [comment]
Note that for WPA it's perfectly ok to crack invalid passwords IF the user has used the wrong password. The difference to regular hashes is that we're cracking a captured network handshake, not a fixed hash. But this is a wanted behaviour: https://hashcat.net/forum/thread-6273.html

**Comment by janisrubenis** [comment]
1. My hashcat version is different from version mentioned above 
>hashcat (v4.1.0-22-g469fece1+) starting...<
My hashcat (v4.1.0) starting...

additionally I tested on х86 system.

2) before test  I deleted hashcat (apt remove) and installed it again.

Error is still the same.
Should I focus on another components of the system, drivers for videocard or any libraries? 

Full scneario is here
[hashcat_bug_2 (1).txt](https://github.com/hashcat/hashcat/files/2209811/hashcat_bug_2.1.txt)


[hashcat_bug.txt](https://github.com/hashcat/hashcat/files/2210333/hashcat_bug.txt)

**Comment by EricSajuPeter** [comment]
I have the same problem.
I downloaded the sample .hccapx from hashcat and the wordlist I made also had the password in it. Yet in the end it was still saying exhausted.

sample .hccapx: https://hashcat.net/misc/example_hashes/hashcat.hccapx
password: hashcat

**Comment by philsmd** [comment]
The password is "hashcat!" (without quotes) as mentioned on the wiki: https://hashcat.net/wiki/example_hashes

WPA / WPA2 have a mimimum password length of 8. all shorter passwords will be rejected. the password "hashcat" (without quotes) isn't long enough. it's not the correct password. You always need to test with the **correct** password. For the test hashes the correct passwords are mentioned here: https://hashcat.net/wiki/example_hashes
