### ISSUE TITLE
new add request for mode 10900 PBKDF2-HMAC-SHA256

### ISSUE THREAD

**Issue by rockygsm** [hashcat/hashcat#1583]
Hello
Its possible to add support for hex-salt 0x10 length on PBKDF2-HMAC-SHA256 ?
i checked sources of PBKDF2,salt is used only once on sha2 before starting iterations.. its not going to low down speed of current cracking.. 
worth to add it.
as i tested current latest release do not support it.

**Comment by jsteube** [comment]
Not sure what you mean. A salt of length 16 is already supported in -m 10900.

**Comment by jsteube** [comment]
Feel free to reopen the issue if you think there's some change needed.

**Comment by rockygsm** [comment]
as from all search and reading i found valid method and way to use hash for my task.
`hashcat64 -m 10900 -a 3 -w 3 --hex-salt sha256:5000:DBE4ECEF10CED715D83F4F8BE938BE3DFEAB1DB7CB57DD16514E5623BBFB2F0B:239AC14998913570FC0F2E25001CB6F5 ?d?d?d?d?d?d?d?d`
i get error
`Parameter hex-salt not valid for hash-type 10900

Unknown hash-type '10900' selected.`

if i remove --hex-salt it work but never find correct hash.. answer of this hash is 00000000 for testing.
after 40 sec or more i recieve such error 
`Driver temperature threshold met on GPU #1. Expect reduced performance.
Driver temperature threshold met on GPU #1. Expect reduced performance.
Driver temperature threshold met on GPU #1. Expect reduced performance.
Driver temperature threshold met on GPU #1. Expect reduced performance.
Driver temperature threshold met on GPU #1. Expect reduced performance.
Driver temperature threshold met on GPU #1. Expect reduced performance.`

my device details 
`OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080 Ti, 2816/11264 MB allocatable, 28MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, skipped.

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates`

note i am using hashcat (v4.1.0)

**Comment by jsteube** [comment]
The -m 10900 format expect the data given in base64, not hex. So you have to recode your salt and hash to base64 first:

```
root@ht:~/hashcat# perl -e 'print pack ("H*", "DBE4ECEF10CED715D83F4F8BE938BE3DFEAB1DB7CB57DD16514E5623BBFB2F0B")' | base64
2+Ts7xDO1xXYP0+L6Ti+Pf6rHbfLV90WUU5WI7v7Lws=
root@ht:~/hashcat# perl -e 'print pack ("H*", "239AC14998913570FC0F2E25001CB6F5")' | base64
I5rBSZiRNXD8Dy4lABy29Q==
```

You've also confused salt and hash, you need to swap it. The resulting hash looks like this:

```
sha256:5000:I5rBSZiRNXD8Dy4lABy29Q==:2+Ts7xDO1xXYP0+L6Ti+Pf6rHbfLV90WUU5WI7v7Lws=
```

You can then simply crack it as usual:

```
root@ht:~/hashcat# ./hashcat -m 10900 -a 3 sha256:5000:I5rBSZiRNXD8Dy4lABy29Q==:2+Ts7xDO1xXYP0+L6Ti+Pf6rHbfLV90WUU5WI7v7Lws= ?d?d?d?d?d?d?d?d
hashcat (v4.1.0-26-g60f2d413) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 750 Ti, 500/2000 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

sha256:5000:I5rBSZiRNXD8Dy4lABy29Q==:2+Ts7xDO1xXYP0+L6Ti+Pf6rHbfLV90WUU5WI7v7Lws=:00000000
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Type........: PBKDF2-HMAC-SHA256
Hash.Target......: sha256:5000:I5rBSZiRNXD8Dy4lABy29Q==:2+Ts7xDO1xXYP0...v7Lws=
Time.Started.....: Thu Jun 14 20:51:16 2018 (6 secs)
Time.Estimated...: Thu Jun 14 20:51:22 2018 (0 secs)
Guess.Mask.......: ?d?d?d?d?d?d?d?d [8]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:    33498 H/s (9.51ms) @ Accel:32 Loops:16 Thr:640 Vec:1
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 204800/100000000 (0.20%)
Rejected.........: 0/204800 (0.00%)
Restore.Point....: 0/10000000 (0.00%)
Candidates.#1....: 02345678 -> 07689012
HWMon.Dev.#1.....: Temp: 44c Fan: 33% Util: 97% Core:1189MHz Mem:2700MHz Bus:16

Started: Thu Jun 14 20:51:10 2018
Stopped: Thu Jun 14 20:51:23 2018
```

When it comes to Driver temperature threshold, it's usually set to 79c on nvidia on windows. If you stick below it, everything is fine, otherwise the driver clocks down the GPU a bit.
