### ISSUE TITLE
WPA/WPA2 hash crack , fails.

### ISSUE THREAD

**Issue by wifislax-ng** [hashcat/hashcat#1584]
Hi , i make dictionary , for wpa/wpa , (little random combination with 8 characters) , and put correct passwork inside txt file.

Hashcat end "exhaust", and no see the key ....

I test same files in to old 3.5.0 version and hashcat "cracked" , the hash.

**Comment by RealEnder** [comment]
Can you provide samples (if they come from test network) and output log?

**Comment by wifislax-ng** [comment]
OK . i found where is the problem.

hashcat-4.1.0 + beignet-1.3.1

When process start i see a warning mesaage

OPENCL kernel-self-test failed !!!!

But hashcat continue ..ignoring this ...

Other plattform with hashcat-4.1.0  + Nvidia opencl device
message not appears ..all is ok , and cracked works.

I think , when kernel-self-test fails ... then no need continue with process.

**Comment by jsteube** [comment]
OK, thanks for reporting. That's one of the reason why I've added the self-test functionality, to find out invalid OpenCL drivers/runtimes. It's good to see it' s working. The reason you didn't see it in 3.5 is because this feature was added in 4.0.0

The suggestion to stop hashcat in such a case can be discussed. We could make it like that and only if the user specified --force hashcat will continue.

**Comment by wifislax-ng** [comment]
We have  --> --self-test-disable

I think , when test fails , --force never overwrite that , only the user, using the especific argument to ingoring this.

--force sometimes are needing , cause some driver mismatch , but working, but if self test say no , please , stop with message , and point to use the specific argument.

only --self-test-disable , can ignore te opencl test failing , at least the user know the driver is failing without time lost passing dictionary for nothing.

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/469fece141384e766739f88b4f4ddced6d927a51

**Comment by wifislax-ng** [comment]
Thanks !!!

Now is perfect.
