### ISSUE TITLE
Slow speed on one specific WPA2 network

### ISSUE THREAD

**Issue by cubagithub** [hashcat/hashcat#1586]
**Summary**
I'm seeing a huge discrepancy in speed when processing WPA2 handshakes with any attack - one specific network's capture is processed much slower. I have collected up to 10 different handshakes with aircrack-ng, and converted them to hccapx with hashcat-utils. I have tried several different captures for this specific network "CAP2", but hashcat processes it much slower than all others.

The only difference I can see is the number of collected hashes is much higher in CAP2 (slower), and also the 'AP/STA' addresses under 'Hash.Target' do not appear for CAP2, where they do for all other networks.

**Command line**
`hashcat -m 2500 -a 0 --status -w 4 --gpu-temp-disable CAP1-01.hccapx rockyou.txt`

**Results**

--- CAP1
Hashes: 2 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Hash.Type........: WPA/WPA2
Hash.Target......: CAP1 (AP:18:90:d8:<removed> STA:02:0f:b5:<removed>)
Time.Started.....: Wed Jun  6 02:08:46 2018 (37 mins, 13 secs)
Time.Estimated...: Wed Jun  6 02:46:09 2018 (10 secs)
Guess.Base.......: File (rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   186.6 kH/s (320.24ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#2.....:   187.8 kH/s (320.51ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#3.....:   187.0 kH/s (320.61ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#4.....:   186.5 kH/s (320.85ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#*.....:   747.9 kH/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts

--- CAP2
Hashes: 394 digests; 328 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Hash.Type........: WPA/WPA2
Hash.Target......: CAP2-01.hccapx
Time.Started.....: Wed Jun  6 02:51:39 2018 (20 secs)
Time.Estimated...: Wed Jun  6 02:52:57 2018 (58 secs)
Guess.Base.......: File (rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:    42114 H/s (6.31ms) @ Accel:32 Loops:8 Thr:1024 Vec:1
Speed.Dev.#2.....:    41922 H/s (6.32ms) @ Accel:32 Loops:8 Thr:1024 Vec:1
Speed.Dev.#3.....:    42231 H/s (6.31ms) @ Accel:32 Loops:8 Thr:1024 Vec:1
Speed.Dev.#4.....:    42521 H/s (6.28ms) @ Accel:32 Loops:8 Thr:1024 Vec:1
Speed.Dev.#*.....:   168.8 kH/s
Recovered........: 0/328 (0.00%) Digests, 0/1 (0.00%) Salts

**Benchmark**
Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)
Speed.Dev.#1.....:   203.1 kH/s (318.47ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#2.....:   202.1 kH/s (320.04ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#3.....:   202.5 kH/s (319.47ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#4.....:   203.7 kH/s (317.61ms) @ Accel:64 Loops:256 Thr:1024 Vec:1
Speed.Dev.#*.....:   811.5 kH/s

Hashmode: 0 - MD5
Speed.Dev.#1.....:  5700.4 MH/s (188.70ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.Dev.#2.....:  5700.6 MH/s (189.04ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.Dev.#3.....:  5693.4 MH/s (188.95ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.Dev.#4.....:  5724.2 MH/s (187.87ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.Dev.#*.....: 22818.6 MH/s

Any assistance or tips would be appreciated.

**Comment by jsteube** [comment]
Looks good to me. You have multiple handshakes, therefore you have a loss in speed. 

If there's many handshakes, hashcat does not display the mac addresses since they could be all different. So this is just a display thing.

If you want full speed, select a single handshake.

**Comment by cubagithub** [comment]
Is there any benefit to target multiple handshakes? I will research how to select one handshake - thanks for the feedback.

**Comment by jsteube** [comment]
To get the idea behind the hccapx format (which supports the multiple handshake cracking), you should read this: https://hashcat.net/forum/thread-6273.html

There's some advantages over single handshake cracking
