### ISSUE TITLE
No hashes loaded. 

### ISSUE THREAD

**Issue by gidsumaya** [hashcat/hashcat#1587]
~# hashcat -m 1500 -a 0 /root/Desktop/hostname /root/Desktop/rockyou.txt --force
hashcat (v4.1.0) starting...

OpenCL Platform #1: The pocl project

* Device #1: pthread-Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz, 1024/2872 MB allocatable, 4MCU

Hashfile '/root/Desktop/hostname' on line 1 (V0}$%\xff\x85): Line-length exception
No hashes loaded.

Started: Sat Jun  9 02:49:13 2018
Stopped: Sat Jun  9 02:49:13 2018

**Comment by jsteube** [comment]
Looks like the content of that file is not a hash, so the error is a correct one.
