### ISSUE TITLE
Cannot read /root/.hashcat/sessions/hashcat.pid

### ISSUE THREAD

**Issue by Spear0070** [hashcat/hashcat#1588]
i was in the process of cracking wpa password via hashcat when suddenly there was a powercut, so the process stopped in between. Now after the power came back i tried running the same but now it gives me an error "Cannot read /root/.hashcat/sessions/hashcat.pid"
kindly help me
thanks

**Comment by jsteube** [comment]
What's the size of the file?

**Comment by Spear0070** [comment]
Hey jsteube, I tried deleting the pid to see if it works and it worked. Thanks for replying anyways. I'll close the issue now.
