### ISSUE TITLE
Funny argument parsing problem

### ISSUE THREAD

**Issue by DerBunteBall** [hashcat/hashcat#1589]
## What I am doing

This: hashcat -a 3 -m 13763 -1 1.hcchr hashfile wordlist2

## What I am getting

I really don't understand why - eventually because I oversaw something - but this:

hashcat (v4.1.0) starting...

OpenCL Platform #1: Apple

* Device #1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.
* Device #2: AMD Radeon R9 M390 Compute Engine, 512/2048 MB allocatable, 16MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 64

Watchdog: Temperature abort trigger disabled.

Custom-charset 1 is undefined.

## My Environment

macOS 10.13 High Sierra highest update state with Hashcat installed from Homebrew. The wordlist contains a PW string with "mask definition parts" e.g. car?1?d?1

## My Question

Why the hell my custom charset 1 is claimed as not defined. I tried both - writing -1 mychars and -1 myfilewithchars.hcchr. Both doesn't work. I checked my file mutlipele times. It's just ASCII. I also tried to use "" or '' when writing the chars directly inside the command - nothing helps.

Every thoughts are welcome.

Thanks in advance!

Best Regards

**Comment by jsteube** [comment]
If you use a maskfile you need to define the custom charset in the maskfile. See here for reference:

https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files

In the past we had support for -1 to be used from a mask file, but it was kind of confusing. A user had multiple lines of masks in his maskfile (which is supported) but wanted to use different custom charsets for each of the masks.

Since this is a topic for hashcat forum I'm closing it here.

**Comment by roycewilliams** [comment]
I have seen this question from multiple users. It might be good to expand the error message from "Custom-charset X is undefined" to "Custom-charset 1 is missing from the mask file" or similar, to anticipate similar questions in the future.

**Comment by DerBunteBall** [comment]
With the reply from @jsteube I could solve my problem within 1 minute. Eventually I simply don't read enough documentation but the error message really is missleading. Eventually something like "Wrong maskfile syntax" could be a better error message and would help more.

Best Regards
