### ISSUE TITLE
forget itune backup password

### ISSUE THREAD

**Issue by mila999** [hashcat/hashcat#1590]
i just forget password what i had set and that was minimum 8 char to 14 char with latter,num,symbol,upper,lower all things are mixed but i cant remember what is that so plz give me terminal command line code to start define it.

./hashcat -d 2 Manifest.plist  -m 14800  (what should i add to crack this bunch of password)

help to define it 
thank u....

**Comment by DerBunteBall** [comment]
First of all: If you don't know something of the structure of the pass I would say that you will not be able to recover it.

My benchmark shows 21h/s for a ATI GPU.... that's really. slow. The mode must be more or less complex.

Steps to try:

1. Extract the Hash of the iTunes Backup with something like itunes_backup2john.pl from the JohnTheRipper Package (http://www.openwall.com/john/). The exporters are helpful but Hashcat is the magic maker.
2. You will need to generate custom masks. You can gen a dictionary with the PACK Package (https://github.com/iphelix/pack). IMPORTANT: I think this won't work well. You try to solve the unsolveable problem.
3. Your command looks like this: hashcat -a 3 -m 14800 -o cracked.txt --outfile-format=15 yourhash dict|mask|wordlist

For example a silly brute force for an 8 char pass about which you know nothing would look so:

hashcat -a 3 -m 14800 -o cracked.txt --outfile-format=15 yourhash ?a?a?a?a?a?a?a?a

This would start but run until the universe explodes/implodes/or what ever it thinks it shoudl do when it ends. Think 9 char with ?a would cause an integer overflow. This could only be "solved" by generating intelligent masks. But also the masks generated by PACK could explode the integer I think.

To understand Mask Attacks read this: https://hashcat.net/wiki/doku.php?id=mask_attack

Hoep this helps a bit. But I think you pass and data are gone.

Best Regards

**Comment by jsteube** [comment]
Thanks for answer @DerBunteBall 

However this is a usage topic and therefore should be moved to hashcat forum and closing here.
