### ISSUE TITLE
HEX-ify founds containing some non-visible ASCII

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1591]
As demonstrated in [this comment](https://github.com/hashcat/hashcat/issues/1580#issuecomment-397318875), founds with newlines (and perhaps other non-visible ASCII?) are not currently HEX-ified - neither in the potfile, nor when output to the screen when found.

From my testing, tabs are also not HEX-ified.

This would be better for post-processing of founds. One might even argue that any trailing whitespace should be HEX-ified. If a space or tab is not at the end of the string, that might be OK.

**Comment by magnumripper** [comment]
I believe ce4858f7a broke this. These lines were removed:
```diff
-    // This line rejects unprintables. The rest of the function
-    // reliably rejects invalid UTF-8 sequences.
-    if (*buf < 0x20 || *buf == 0x7f) return false;
```

**Comment by jsteube** [comment]
Thanks! Indeed I've worked too close to how utf-8 defines a valid sequence. It's better to leave out 0x00 - 0x1f. Should be fixed with https://github.com/hashcat/hashcat/commit/60f2d413e04f67ab39fbf80e8f356a097f29919e

**Comment by roycewilliams** [comment]
Confirmed fixed, thanks for the speed!
