### ISSUE TITLE
Hashcat 4.1.0 not using AMD RX 570 & amdconfig: command not found

### ISSUE THREAD

**Issue by d5y9nu** [hashcat/hashcat#1594]
I'm trying install hashcat on a fresh ubuntu 18.04 installation. I'm using an AMD Radeon RX 570. Both my desktop monitors are connected to the GPU (not sure if that matters or makes a difference).

Immediately after installing Ubuntu, I updated:

```
$ apt-get update && apt-get dist-upgrade && reboot
```

Then began following the install instructions as per the hashcat FAQ:

```
$ sudo find / -name libOpenCL\* -print0 | xargs -0 rm -rf && reboot
```

```
$ sudo apt-get install ocl-icd-libopencl1 opencl-headers clinfo && reboot
```

Then I downloaded what I think is the correct driver:

```
$ wget https://www2.ati.com/drivers/linux/ubuntu/18.04/amdgpu-pro-18.20-606296.tar.xz
```

Unpacked it and ran the following:

```
$ ./amdgpu-install --version="1.6.180"
```

No installation errors reported. I ran it again for this forum post, here's the output:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
amdgpu is already the newest version (18.20-606296).
amdgpu-lib32 is already the newest version (18.20-606296).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

Then rebooted again.

```
$ sudo mv ~/.hashcat/kernels /tmp/old_kernels
```

Then rebooted again. Using `clinfo` only reports 1 platform and its my CPU. After downloading hashcat and unpacking it, I ran it with:

```
$ ./hashcat64.bin -b -m2500
```

But hashcat only uses the CPU. Looking again at the FAQ, I tried the `amdconfig` command but its not found.

```
$ amdconfig --adapter=all --initial -f
amdconfig: command not found
```

Where did I go wrong? I could really use some help.

**Comment by jsteube** [comment]
This is a question better suited to [the hashcat forums](https://hashcat.net/forum/forum-45.html).
