### ISSUE TITLE
wpa_passphrase PBKDF2_SHA1 support

### ISSUE THREAD

**Issue by davidrozen76** [hashcat/hashcat#1595]
Hello,

I've been trying to figure out the encryption mechanism used by wpa_supplicant's wpa_passphrase.

wpa_passphrase is used by Linux to generate wpa_supplicant.conf network entries, e.g. -

network={
        ssid="home"
        scan_ssid=1
        key_mgmt=WPA-PSK
        psk="32 chars hexadecimal encrypted passphrase"
}

wpa_passphrase (http://docs.ros.org/diamondback/api/wpa_supplicant/html/wpa__passphrase_8c_source.html) uses PBKDF2_SHA1, with fixed 4096 iterations and 32 chars for the derived key (output key).

I encountered a similiar problem in https://github.com/hashcat/hashcat/issues/611 (adding support for another hash).

To make things short - I can't figure out the salt which is used by PBKDF2_SHA1 (maybe no salt is used?)

Assuming I have a 32 chars hexadecimal encrypted passphrase, what is the correct method to convert it to a hashcat supported format? (-m 12000 is the suitable one in this case).

EDIT: referring to issue 611 again, If I figured it out right, the psk="32 chars hexadecimal encrypted passphrase" is used as salt, with 4096 iterations.

Meaning - support for wpa_passphrase can be added to hashca, in a similiar way to issue 611.

Thanks.

**Comment by jsteube** [comment]
Hashcat support cracking WPA/WPA2 handshakes in -m 2500 mode.

**Comment by davidrozen76** [comment]
Obviously this is not the case, I'm talking about cracking the 32 chars encrypted PSK part in wpa_supplicant.conf

**Comment by RealEnder** [comment]
wpa_supplicant writes there PMK, -m 2501. The value is derived with PBKDF2-SHA1 from PSK (ie. the cleartext password) over ESSID.

**Comment by jsteube** [comment]
That makes it even more easy. Just use -m 12000.

**Comment by davidrozen76** [comment]
Yes, -m 12000 is the correct method.
