### ISSUE TITLE
Hashcat 4.1.0 fails to crack NetNTLMv2 hashes under some weired circumstances.

### ISSUE THREAD

**Issue by alexeypetrenko** [hashcat/hashcat#1598]
I stumbled upon a very unpleasant bug in the latest (`v4.1.0`) release of a hashcat.

Hashcat fails to crack a `NetNTLMv2` hash even though correct password is in a wordlist. Somehow, it depends on other words in a wordlist. If I create a wordlist with the correct password and nothing else, it works.

Here is the smallest demo I managed to do:

Hash: 
```hcuser::HCTEST:36f1f0c39436f449:8EEDF86F2522136CBB55413D1F8BBF1B:0101000000000000FE08FF78AD07D40148E5D58BBE3450480000000002000E004E004F004D00410054004300480001000A0053004D0042003100320004000A0053004D0042003100320003000A0053004D0042003100320005000A0053004D004200310032000800300030000000000000000000000000000000B3DF37D5275C8175D62AC8986B31D97B32D0F1AB91B6752AFD817534309838080A0010000000000000000000000000000000000009000E0063006900660073002F006800630000000000```

The password is `qwerty123!`. 

```
# echo qwerty123! | hashcat -m 5600 5600.hash --potfile-disable
...
Status...........: Cracked
...
```
However, if I try it with a very specific wordlist, it fails:

```
# cat wordlist.txt | hashcat -m 5600 5600.hash --potfile-disable
...
Status...........: Exhausted
...
```

Wordlist is:
```
qwerty123^&*(
qwerty123!
```

The password is in a wordlist

Other observations:
 * Removing first line from this particular wordlist makes Hashcat work properly again.
 * Changing lines order fixes issue as well.
 * Adding other lines in a wordlist do not seem to change this behavior.
 * Everything works fine in older versions.

**Comment by jsteube** [comment]
I can't reproduce this locally either on GPU nor on CPU. Maybe you can give some details about the hardware and OpenCL driver being used.

You can also try using --opencl-vector-width 1

**Comment by alexeypetrenko** [comment]
Do you have an instruction anywhere on how to gather debug info for you?

`--opencl-vector-width 1` didn't help.

Also, I'm sorry that I haven't tested it on different installation.  I think that you could simply close this issue if it's not reproducible. I'm currently running on a CentOS release, which is not exactly supported by AMD. So, there could be some problems with my configuration.

**Comment by jsteube** [comment]
I don't have such a debugging gathering info. Let's start with output of clinfo and hashcat -I

**Comment by jsteube** [comment]
I think I found the root cause of the problem, which is a problem in AMD OpenCL runtime. Luckily I was able to workaround the problem with this commit: https://github.com/hashcat/hashcat/commit/14c444fd47f9307e06dea0769c6060ac1ebec7a7

If you pull hashcat github master you should be able to crack it. Thanks for reporting!
