### ISSUE TITLE
put dependencies in the cloned directory, not in /opt/

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#16]
I want to suggest a slight modification on where to put the dependencies for hashcat.
Currently, we have all dependencies in /opt/hashcat-deps/. The problem with this is that the user needs to have the permissions (be root user) to be able to create this directory and add/modify files.

I think it would be best to put the dependencies directly into [hashcat_clone_path]/hashcat-deps/.

What do you think about this suggestion?
Thx

**Comment by jsteube** [comment]
Superb, no more root privs required
