### ISSUE TITLE
Support Veracrypt with unknown PIM

### ISSUE THREAD

**Issue by metulski2013** [hashcat/hashcat#1600]
Hi, is it possible to build in the opportunity to Bruteforce Veracrypt with all possible pims (0-9999) in one step?

Thx

**Comment by jsteube** [comment]
In theory yes, but that doesn't make much sense if you don't know the password. It could make sense if you know the password. However, in such a case a different tool would be more appropriate. 

However where did read about the maximum of 9999 for PIM?

**Comment by metulski2013** [comment]
well, i think i read it in a document from passware. here https://sourceforge.net/p/veracrypt/discussion/search/?q=PIM are some more details. but in my mind, you can only decrypt, when you have the pass and the pim. if the field is empty, different pim's are used (depends on the password length and type of target). if i have the right pass, but the false pim, hashcat fails.

**Comment by metulski2013** [comment]
maybe build-in a loop?

**Comment by metulski2013** [comment]
> In theory yes, but that doesn't make much sense if you don't know the password. It could make sense if you know the password. However, in such a case a different tool would be more appropriate.
> 
> However where did read about the maximum of 9999 for PIM?
 
well i think it makes sence because in an actual case we have some some possible candidates of passwords but no information about a used pim. yes, it is possible do build a loop but the gpu starts e new process and it costs a lot of time. maybe you can build in a loop like "--pim 0-1000".
