### ISSUE TITLE
Support for MultiBit hash (GPU crack)

### ISSUE THREAD

**Issue by deloxd** [hashcat/hashcat#1601]
Hi, Is there a chance for implementations to Multibit classic wallet? Like on btcrecover?
https://github.com/gurnec/btcrecover/blob/master/extract-scripts/extract-multibit-privkey.py

**Comment by philsmd** [comment]
Is this request the same (a duplicate) of this: https://github.com/hashcat/hashcat/issues/1538 ?

**Comment by jsteube** [comment]
Double request
