### ISSUE TITLE
Why do not add support for Android or ARM platform?

### ISSUE THREAD

**Issue by DroidKali** [hashcat/hashcat#1602]
Hello, i have installed chrooted linux on my Android phone,i want to use hashcat in it,but when i typed "hashcat -I " it displayed "clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR" ,why do not add support for Android or ARM devices? Please help me!

**Comment by magnumripper** [comment]
What does clinfo say? I'd guess the problem is the chroot and not anything missing in hashcat.

**Comment by jsteube** [comment]
Yeah, looks like OpenCL installation problem. Anyway, hashcat is not tested on android.

**Comment by DroidKali** [comment]
The clinfo retuned is "Number of platforms                               0"

**Comment by DroidKali** [comment]
What is the problem?
