### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by MintCollie** [hashcat/hashcat#1606]
when i run 
`hashcat64.exe -m 2500 -a 3 capture.hccapx`
all i get is 
`hashcat (v4.1.0) starting. . .` and then the program exits

**Comment by jsteube** [comment]
Usually that's when there's the OpenCL runtime is load. Please make sure you have a clean OpenCL installation. Please send clinfo output.

**Comment by evrial** [comment]
Same issue, everything latest. win10, nvidia driver, hashcat64. 
example0.cmd and benchmark doesn't run either. Older hashcat all the same.

**Comment by jsteube** [comment]
Which driver are you using?

**Comment by evrial** [comment]
398.36 from 26/06/2018

**Comment by cyptus** [comment]
same here, also on win10 with nvidia driver and hashcat64

**Comment by dropdeadfu** [comment]
Running win10 with nvidia 398.36 on a 1080ti and can run the example just fine.

**Comment by evrial** [comment]
1060 here, reinstalled nvidia driver, nothing changed.

**Comment by cyptus** [comment]
i am also running an gtx 1060 (6 GB) and reinstalled the nvidia drivers - still no output. same happens on hashcat64.exe -I command (i am using hashcat v3.6.0)

**Comment by jsteube** [comment]
> same happens on hashcat64.exe -I command (i am using hashcat v3.6.0)

Then it's clearly an opencl runtime installation problem. It's possible that nvidia made an error here, not you users. Pretty sure that no OpenCL application will run on your systems. Feel free to reopen if I'm wrong.

**Comment by evrial** [comment]
[hashcat-crash.zip](https://github.com/hashcat/hashcat/files/2242090/hashcat-crash.zip)

Crash dump attached. I deleted the file 

C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo64.dll
--

And hashcat works fine. Clearly should be fixed in hashcat.

**Comment by jsteube** [comment]
> Clearly should be fixed in hashcat.

This file is the OpenCL runtime from Intel Graphicscard (IG) driver (DR) for OpenCL (CL). It's automatically load by the OpenCL ICD in order to find out about existing OpenCL platforms. The ICD get's installed by your driver.

There's no relation to hashcat in any way. The same error would occur with any other OpenCL application. 

There's also no way of checking this kind of (user installation) error on start because hashcat does not control this process.

**Comment by cyptus** [comment]
this also worked for me! where did you find this and the crash dump?

**Comment by evrial** [comment]
Probably the thing is IGC disabled when no displays connected to it.

**Comment by steveo9219** [comment]
total noob here but i was able to run after just typing hastcat.exe then exiting and the trying again.
