### ISSUE TITLE
In build_plain() in Straight/Combi/Hybrid mode no need for clEnqueReadBuffer

### ISSUE THREAD

**Issue by RobotGF** [hashcat/hashcat#1607]
```
CL_rc = hc_clEnqueueReadBuffer (hashcat_ctx, device_param->command_queue, device_param->d_pws_idx, CL_TRUE, gidd * sizeof (pw_idx_t), sizeof (pw_idx_t), &pw_idx, 0, NULL, NULL);

if (CL_rc == -1) return -1;
  

if (cnt > 0)
{
   CL_rc = hc_clEnqueueReadBuffer (hashcat_ctx, device_param->command_queue, device_param->d_pws_comp_buf, CL_TRUE, off * sizeof (u32), cnt * sizeof (u32), pw->i, 0, NULL, NULL);

  if (CL_rc == -1) return -1;
}
```
In opencl.c gidd_to_pw_t() I think there is no need for data transfer. We can use the host data straightly
like this:
 ```
 pw_idx=device_param->pws_idx[gidd];

 memcpy(pw->i,device_param->pws_comp+off,cnt*sizeof(u32));
```

**Comment by jsteube** [comment]
You can try using your code by using this branch selection:

user_options_extra_t *user_options_extra  = hashcat_ctx->user_options_extra;

if (user_options_extra->attack_kern == ATTACK_KERN_COMBI)
{
... your code
}
else
{
  ... existing code
}

Add some test cases and send in a PR

**Comment by jsteube** [comment]
Any update on this?

**Comment by jsteube** [comment]
If you think this is still valid please feel free to reopen
