### ISSUE TITLE
Mode 5000 (SHA-3/Keccak) not cracking FIPS 202 SHA-3

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1608]
This mode is only able to crack the original Keccak implementation and NOT the SHA-3 FIPS 202 standard. There is a difference in the algorithm that leads to a different hash output due to some padding changes as part of FIPS 202. 

https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.202.pdf

**Comment by jsteube** [comment]
Please use https://github.com/hashcat/hashcat/issues/83
