### ISSUE TITLE
Mode 5000 (SHA-3/Keccak) loading multiple bit lengths incorrectly

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1609]
This mode loads hashes of several bit lengths but is only capable of cracking 256bit keccak hashes. If you load 512bit hashes as well as 256 bit hashes, you will get very strange behaviour and corrupted outputs.

When run with a single 256bit Keccak hashes, the output will look like this:

https://i.imgur.com/K9DX0v5.png

If you include other hashes of 512bit length, they will be counted and loaded as valid hashes, but will refuse to crack and will cause corrupted outputs such as the following:

https://i.imgur.com/xdZfcft.png

https://i.imgur.com/t95kvlb.png

**Comment by jsteube** [comment]
Please use https://github.com/hashcat/hashcat/issues/83
