### ISSUE TITLE
clang 6.0.0 error message

### ISSUE THREAD

**Issue by Gray-0men** [hashcat/hashcat#1610]
1 error generated.
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

error: <built-in>:2:10: '/usr/lib/llvm-6.0/lib/clang/6.0.0/include/opencl-c.h' file not found

After doing some digging I found that clang is now at 6.0.1 on my system.. running on kali (up2date as of 7/6/2018)
****
root@TheOmen:/usr/lib/llvm-6.0/lib/clang# ls
6.0.1
****

So the error message is correct but is there going to be a change to work with 6.0.1 or should I try to downgrade to 6.0.0?

I just update regularly so I'm assuming at this point updating my OS or something along those lines got me 6.0.1.. just wondering if hashcat is going to play catch up there too

**Comment by Gray-0men** [comment]
Also, side note, for some reason hashcat is not seeing my GPU but can find my CPU just fine.

AMD FX(tm)-8350 Eight-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480] <--- it's the 480

idk if those two symptoms correlate but just thought I should mention that as well

**Comment by Gray-0men** [comment]
Also I just found out if I rename the folder to 6.0.0 then so far hashcat seem to run fine without issues other than my GPU being missing for some reason.

*****
root@TheOmen:~# hashcat -I
hashcat (v4.1.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : The pocl project
  Name    : Portable Computing Language
  Version : OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG

  Device ID #1
    Type           : CPU
    Vendor ID      : 1
    Vendor         : AuthenticAMD
    Name           : pthread-AMD FX(tm)-8350 Eight-Core Processor
    Version        : OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-bdver1
    Processor(s)   : 8
    Clock          : 4054
    Memory         : 4096/13893 MB allocatable
    OpenCL Version : OpenCL C 1.2 pocl
    Driver Version : 1.1

**Comment by Gray-0men** [comment]
well I just checked LVMM's main site and as of 2 days ago that updated from 6.0.0 to 6.0.1 so that would explain the sudden change

**Comment by jsteube** [comment]
Do not confuse two different things.
When it comes to the include headers use the original ones from KhronosGroup (see BUILD.md).
When it comes to hashcat -I you better use rocm for AMD GPU on Linux and Intel OpenCL runtime for AMD CPU on any OS.
Anyway this topic is not suited for github issues, please use hashcat forum for usage questions.

**Comment by jsteube** [comment]
$ cd /usr/lib/llvm-6.0/lib/clang/
$ ln -s 6.0.1 6.0.0
