### ISSUE TITLE
Using -a 3 mode does not produce the correct key

### ISSUE THREAD

**Issue by komawoyo** [hashcat/hashcat#1611]
I have a WPA/2 hccapx capture that I know that the password to
using the normal wordlist approach - I'm able to find the key but fails when using mask mode
my command line is: 

>hashcat64 -m 2500 -a 3 test.hccapx -1 34wafmw ?1?1?1?1?1?1?1?1
> Correct Key: 3wafm3w4
[hccapx test.zip](https://github.com/hashcat/hashcat/files/2173062/test.zip)

**Comment by jsteube** [comment]
Works fine on my system.

```
78972e04454d4b2246a3957747806e37:94103ee1ac2c:f4a99785929c:belkin.c2c:3wafm3w4
52340951edfa73c507c11dc2c44de3ed:94103ee1ac2c:5c521e9fa24c:belkin.c2c:3wafm3w4
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccapx
```

**Comment by komawoyo** [comment]
Hello, what did you do different from me? 

![image](https://user-images.githubusercontent.com/18315233/42601678-0ddb9a54-852c-11e8-99cf-0a331ff822bd.png)
