### ISSUE TITLE
clCreateContext(): CL_DEVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by p4vook** [hashcat/hashcat#1612]
Hi!
I want to start hashcat application, but it returns an error:
`clCreateContext(): CL_DEVICE_NOT_AVAILABLE`
This is information, what hashcat -I returns:
  Platform ID #1
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) OpenCL
  Version : OpenCL 1.2

  Device ID #1
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Genuine Intel(R) CPU           U2300  @ 1.20GHz
    Version        : OpenCL 1.2 (Build 37)
    Processor(s)   : 2
    Clock          : 1200
    Memory         : 999/3998 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 6.4.0.37
How can I fix this problem?

**Comment by philsmd** [comment]
are you sure that you have installed the OpenCL driver from intel as recommended on https://hashcat.net/hashcat ?

What is the output of clinfo ?

**Comment by jsteube** [comment]
No response from OP for two weeks, probably OpenCL runtime installation error
