### ISSUE TITLE
[Feature Request] Add more status information to machine readable output 

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1613]
In the normal Hashcat status there is the `Util` value shown for each card. It would be great to have this information also in the machine-readable output of the status.
To keep everything compatible with other parsers which use the --machine-readable flag, it could be activated with a separate flag (e.g. --status-extra). 

So as an example, the status could then look like (example value of 87%, just one GPU):
```
STATUS 5 SPEED 949779 1000 EXEC_RUNTIME 7.770168 CURKU 129988 PROGRESS 129988 129988 RECHASH 224 6494 RECSALT 0 1 TEMP 51 REJECTED 0 UTIL 87
```

**Comment by roycewilliams** [comment]
IMO, since it's being appended to the end of the existing format, I would expect most implementations to be forward-compatible (or be OK with making a tweak to match it), rather than having its own flag. Just my $0.02.

**Comment by jsteube** [comment]
I've added this with commit https://github.com/hashcat/hashcat/commit/8903adb164ce6e6c554dc9cb9634a725dabcceb0

There's no new status flag, it's simply appended to the end of line. Let's see if there's anyone complaining, then we can add it with status flag.
