### ISSUE TITLE
hashcat segfaults on Xeon E5-2623

### ISSUE THREAD

**Issue by thinksilicon** [hashcat/hashcat#1614]
Hi,
I'm having trouble running hashcat on a Xeon E5-2623. I've installed https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime (OpenCL™ Runtime 16.1.1 for Intel® Core™ and Intel® Xeon® Processors - 64 Bits) and it shows up correctly running `hashcat -I`. I've also tried version 16.1.2 with the same result.

When I try to run any benchmark it stalls with a segfault:
```
./hashcat --opencl-platforms=2 -b
hashcat (v4.1.0-68-g1b30a1d6+) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: NVIDIA Corporation, skipped or no OpenCL compatible devices found.

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #1: Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz, 8009/32039 MB allocatable, 8MCU

Benchmark relevant options:
===========================
* --opencl-platforms=2
* --optimized-kernel-enable

Hashmode: 0 - MD5

Segmentation fault (core dumped)
```

I've already tryed compiling the latest version from git, also tried to compile with `DEBUG=1` and get a dump with `gdb`:

```
make clean
DEBUG=1 make
ulimit -c 999999999999
./hashcat -b
(core dumped)
gdb ./hashcat core
```
there isn't any core-file present, where would I look for that?

I'm running `4.12.14-lp150.12.4-default #1 SMP` on an openSUSE Leap 15.0 system. Hashcat has no trouble when running it on the graphics-card - the card is rather slow though, so I'd like to see if it works better on the CPU.
```
./hashcat -I
hashcat (v4.1.0-68-g1b30a1d6+) starting...

OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 9.1.84

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GT 710
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 1
    Clock          : 954
    Memory         : 243/972 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 390.67

Platform ID #2
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) OpenCL
  Version : OpenCL 2.0 LINUX

  Device ID #2
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz
    Version        : OpenCL 2.0 (Build 25)
    Processor(s)   : 8
    Clock          : 2600
    Memory         : 8009/32039 MB allocatable
    OpenCL Version : OpenCL C 2.0 
    Driver Version : 1.2.0.25
```

Any help appreciated!

**Comment by hops** [comment]
> there isn't any core-file present, where would I look for that?

Most likely systemd "hides" that from you. Try `coredumpctl debug`. This will start gdb with the last coredump.
If you don't have systemd then I don't know where core file could be. However you could try this:
`gdb --args ./hashcat --opencl-platforms=2 -b` and in the gdb prompt enter `run`

**Comment by thinksilicon** [comment]
Thanks, here's the dump:
```
Hashmode: 0 - MD5


Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffed10deb7 in ?? () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libcpu_device.so
#2  0x00007fffed10264b in ?? () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libcpu_device.so
#3  0x00007fffed103b16 in clDevCreateDeviceInstance () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libcpu_device.so
#4  0x00007fffee1af0c5 in ?? () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libintelocl.so
#5  0x00007fffee16c549 in ?? () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libintelocl.so
#6  0x00007fffee14d722 in ?? () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libintelocl.so
#7  0x00007fffee129a41 in clCreateContext () from /opt/intel/opencl-1.2-6.4.0.25/lib64/libintelocl.so
#8  0x0000000000456116 in ?? ()
#9  0x000000000045ba09 in ?? ()
#10 0x0000000000417639 in ?? ()
#11 0x0000000000417c2c in ?? ()
#12 0x0000000000402d31 in ?? ()
#13 0x00007ffff7413f4a in __libc_start_main () from /lib64/libc.so.6
#14 0x0000000000402d6a in ?? ()
(gdb) 
```
does that help in any way?

**Comment by hops** [comment]
The crash happens inside Intel's OpenCL library. There's probably not much hashcat can do about this.
It works on my Ubuntu 16.04 machine with the same driver version though my CPU is a i7-6700K.
I don't have a Xeon E5-2623. You could try with Ubuntu 16.04.

**Comment by thinksilicon** [comment]
Yeah, looks to be intel's fault. I'll try with Ubuntu, and maybe also try to reach out to Intel (don't think I'll get any response though).
Hashcat is working nicely with Intel's drivers on my i5-7200U (and openSUSE with linux 4.17.2). It's only a laptop though, so I'm afraid it'll burn after a while...

**Comment by thinksilicon** [comment]
Alright, I could verify that it's a problem with the distribution-kernel of openSUSE Leap. It's running fine with debian 9 (4.9.88).
Thanks for your help!
