### ISSUE TITLE
ROCm doesnt work using mode 11300

### ISSUE THREAD

**Issue by hashuser1** [hashcat/hashcat#1618]
Currently in a bind. I previously opened issue #1596. I understand the issue is with ROCm but until they get their stuff together, is there any work around? Does any version of ROCm work correctly since v1.6 with hashcat v4.x using mode 11300? If not, cant you stop making it a requirement to use ROCm and just use amdgpu-pro drivers with legacy or pal opencl? Ive had the issue open on ROCm for almost a month now (issue # 437). I understand if there is a bug in current software, it just doesnt make sense if it never worked correctly and you are requiring broken software to use your application.

**Comment by jsteube** [comment]
There's no workaround known. ROCm is still the best driver. amdgpu-pro drivers (both modes) are even worse (in other modes), thus we recommend ROCm.
