### ISSUE TITLE
--stdout should not require available OpenCL devices

### ISSUE THREAD

**Issue by dizcza** [hashcat/hashcat#1620]
I want to do some text preprocessing in Dockerfile. But, for some reason, `hashcat --stdout` requires OpenCL installed. Docker build cannot use OpenCL capabilities (and doesn't have to). Nvidia-docker produces the same error. I'm forced to spawn a supervisord task to do all my text processing (which could take minutes) during starting the container, when my GPU, indeed, becomes visible to hashcat.
```
hashcat --stdout -r rules/best64.rule wordlists/phpbb.txt > ...
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
```
Is it possible to use `hashcat --stdout` feature without any available OpenCL device?

**Comment by jsteube** [comment]
You can not use hashcat without an OpenCL runtime, even if it's just stdout mode. The password candidate modificatinos (rules, combinator, etc) are still done inside an OpenCL kernel. You do not need a GPU. Every CPU should be fine by using Intel OpenCL runtime (even for non-Intel CPU).

**Comment by dizcza** [comment]
> Every CPU should be fine by using Intel OpenCL runtime (even for non-Intel CPU).

To use Intel OpenCL runtime one has to install it first which adds ~130 Mb on top of docker image.

But you made it clear. OK
