### ISSUE TITLE
is hashcat broken?

### ISSUE THREAD

**Issue by dannyrock** [hashcat/hashcat#1621]
i have tried with latest binary even downloaded the source code and compiled it still it gives this error.

root@io:~/Downloads/hashcat-4.1.0# ./hashcat -b
hashcat (v4.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by jsteube** [comment]
Clearly OpenCL runtime error (uses LLVM). Which driver do you use?

**Comment by jsteube** [comment]
No response from OP, feel free to reopen

**Comment by 0jdxt** [comment]
Hello I'm getting the same error in hashcat (v5.1.0):
```
$  hashcat -b
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
