### ISSUE TITLE
 New algorithm how?

### ISSUE THREAD

**Issue by komyaka** [hashcat/hashcat#1628]
Hello
I need to add a new algorithm, but I can not understand how.
Read the forum and came across links to
https://hashcat.net/forum/thread-7339.html
https://github.com/hashcat/hashcat/commi...4dca42b511
examples of how and where to change.

Dear developers, give a similar link in the current realities. At the moment, the files specified in this commit do not exist.

Please send an example.
----------
Здравствуйте
Мне нужно добавить новый алгоритм, но не могу понять как.
Читал форум и попадались ссылки на:
https://hashcat.net/forum/thread-7339.html
https://github.com/hashcat/hashcat/commi...4dca42b511
примеры как и где нужно изменить.

Уважаемые разработчики, дайте аналогичную ссылку в текущих реалиях. На данный момент файлы указанные в этом commit не существуют.

Пришлите пожалуйста пример.

**Comment by philsmd** [comment]
here is a recent example of a new hash type addition: https://github.com/hashcat/hashcat/commit/c28fdf7f44bf5d39f9078f6d82b52bdb052125e3

**Comment by jsteube** [comment]
Example sent
