### ISSUE TITLE
when using -d larger than the available device numbers, it will be ignored (beta problem)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#163]
Consider that we have 3 OpenCL devices (2 GPUs + 1 opencl-compatible CPU), when I use this command:
./oclHashcat -d 1,4 example0.hash example.dict

oclHashcat correctly selects device 1 as a valid device but it simply ignores the "4" part within the -d list and runs oclHashcat just with 1 device.

I would suggest that in such a case we should check and report whenever the device specified is not allowed/available, show an error message and exit with an error code.
Thx

**Comment by jsteube** [comment]
There's some more of such parameters like --opencl-platforms and --opencl-device-types do we need the same fix for them?

**Comment by philsmd** [comment]
Of course! In my opinion the user specified parameter should not silently be ignored when incorrect/not allowed/available. Otherwise, this could lead to very strange problems/missunderstandings etc.
