### ISSUE TITLE
self-test fails on -m 3000 (LM) using the combinator kernel

### ISSUE THREAD

**Issue by hops** [hashcat/hashcat#1630]
Tested with GTX 1080 using driver version 390.30 and also i7-6700k using Intel OpenCL driver version 1.2-6.4.0.25.
```
cat /tmp/left
hash
```
```
hashcat -m 3000 -a6 299bd128c1101fd6 /tmp/left ?a?a?a
* Device #2: ATTENTION! OpenCL kernel self-test failed.
```
When I disable the self-test the hash gets cracked correctly. So it's not a big issue but, I'm still curious why this happens.
```
hashcat --quiet --self-test-disable -m 3000 -a6 299bd128c1101fd6 /tmp/left ?a?a?a
299bd128c1101fd6:HASHCAT
```

**Comment by philsmd** [comment]
does it work with older drivers? i.e. did you only notice the problem after updating the driver?

**Comment by hops** [comment]
I only found the bug today and can't test it with older drivers.
I added some debug printf's here: https://github.com/hashcat/hashcat/blob/master/OpenCL/m03000_a1-pure.cl#L800 (is there a better way?)
```
    printf("w0[0]: %08x\n", w0[0]);
    printf("w0[1]: %08x\n", w0[1]);
```
Now running the self-test results in this:
```
w0[0]: 68736168
w0[1]: 00746163
```
Which is "hashcat"
```
$ echo -n 68736168 | xxd -r -p | rev
hash
$ echo -n  746163 | xxd -r -p | rev
cat
```
So it looks like the self-test plaintext is not converted to uppercase and therefore calculates the wrong hash.
I hope this helps in resolving this bug.

**Comment by hops** [comment]
I had a closer look and have a possible solution.
The problem is not LM specific but with all hashmodes having set the OPTS_TYPE_PT_UPPER.
I've attached a diff and unless you find a better solution I'll create a pull requests shortly.
[selftest.diff.txt](https://github.com/hashcat/hashcat/files/2219994/selftest.diff.txt)

**Comment by jsteube** [comment]
Looks like a good fix to me. Please send in a PR.
