### ISSUE TITLE
hex notation broken in replace rule

### ISSUE THREAD

**Issue by hops** [hashcat/hashcat#1636]
When using the hex notation in the search part of the replace rule hashcat will produce a wrong rule.
For example:
```
$ cat test.rule
s\x41\x42
$ echo testA | ./hashcat -r test.rule --stdout
Skipping invalid or unsupported rule in file test.rule on line 1: s\x41\x42
```
`s\x41\x42` will be replaced by `sA[:space:][:space:][:space:]B[:space:][:space:][:space:]` in the function _old_apply_rule().
That results in a rule which would replace A with a space and leaves a dangling B and therefore skips the rule.

I believe only the replace rule is affected. And only if the search character is represented in hex notation.
For example: `sA\x42` works fine.

**Comment by jsteube** [comment]
Should be fixed with commit https://github.com/hashcat/hashcat/commit/9d431117309e51d0a29bb16daa8ac01ba15a77ee

Many thanks for reporting!
