### ISSUE TITLE
Feature request - exclude the dictionary

### ISSUE THREAD

**Issue by evrial** [hashcat/hashcat#1637]
Would be nice to have such option to save some time.

**Comment by jsteube** [comment]
Please use rli or rli2 from hashcat-utils

**Comment by evrial** [comment]
These tools work only with text files, but I wish to run naive (combinator/mask/hybrid) cracking with excluded dict file.

**Comment by jsteube** [comment]
It makes no sense from a technical perspective:

If you want to crack fast hashes (MD5 etc) then a check between existing such an exclude wordlist would slow down the attack more than it would benfit from it. IOW, it's faster to check passwords even if they have been tested already.

If you want to crack slow hashes (TrueCrypt etc) it would eventually make sense, however you can also write the candidates first to a file (use --stdout) and then apply rli/rli2 on it.

**Comment by evrial** [comment]
Yea I'm perfectly aware of everything you said, but using file is the same as dict attack and use unnecessary large disk space. Do you think it would make sense for WPA?

**Comment by jsteube** [comment]
Right, but the disk space required can not be that large for slow hashes (like WPA) because if it's really that large, the attack makes no sense anyway.

**Comment by evrial** [comment]
🤔Good point, but I don't want to waste my space anyways. 😞
