### ISSUE TITLE
Unsupported rule : "sée"

### ISSUE THREAD

**Issue by francoisihry** [hashcat/hashcat#1638]
Hi, I am trying to set a rule which replace "é" character by "e". 

Here is my rule : 

`sée`

But the rule is not supported.

`Skipping invalid or unsupported rule in file regle.rule on line 10: sée`

 Is there a problem with special characters ?

**Comment by jsteube** [comment]
There's no problem with special characters in rules, you just need to know that rules work byte-wise. IOW, you need to encode your rule as ISO and not UTF-8. You can use iconv to convert. However, that's a question for hashcat forum, therefore closing this issue.
