### ISSUE TITLE
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by w3soul** [hashcat/hashcat#1640]
Hi, 
This is my approx my 20th fresh kali2018.2 install but couldn't get hashcat to work and the only reason is hashcat is the best tool i have ever used.

Hashcat is giving me "clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE" error when use most of the algorithms e.g wpa,wpa2,zip,sha etc. It works fine with md5.

Kali is installed as standalone OS, Intel I7 with Nvidia GTX960 2GB, 250GB swap memory.

**hashcat -I produce this result:**
`OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 9.1.84

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GTX 960
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 8
    Clock          : 1177
    Memory         : 492/1968 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 390.77

Platform ID #2
  Vendor  : The pocl project
  Name    : Portable Computing Language
  Version : OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.1, SPIR, SLEEF, DISTRO, POCL_DEBUG

  Device ID #2
    Type           : CPU
    Vendor ID      : 128
    Vendor         : GenuineIntel
    Name           : pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Version        : OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
    Processor(s)   : 8
    Clock          : 4200
    Memory         : 8192/30040 MB allocatable
    OpenCL Version : OpenCL C 1.2 pocl
    Driver Version : 1.1
`

**Hashcat -b produce this result**
`Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 960, 492/1968 MB allocatable, 8MCU
OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.
Benchmark relevant options:
===========================
* --optimized-kernel-enable
Hashmode: 0 - MD5
Speed.Dev.#1.....:  6697.5 MH/s (79.54ms) @ Accel:128 Loops:512 Thr:1024 Vec:4

Hashmode: 100 - SHA1
Speed.Dev.#1.....:  2326.1 MH/s (72.08ms) @ Accel:256 Loops:128 Thr:640 Vec:1

Hashmode: 1400 - SHA-256
Speed.Dev.#1.....:   855.9 MH/s (78.32ms) @ Accel:128 Loops:64 Thr:1024 Vec:1

Hashmode: 1700 - SHA-512
Speed.Dev.#1.....:   281.5 MH/s (74.21ms) @ Accel:128 Loops:32 Thr:640 Vec:1

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE
`
It worked absolutely fine for two year, i just reinstall my OS and now it's giving me this object allocation error.

**clinfo produce this result:**
`Number of platforms                               2
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 9.1.84
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
  Platform Extensions function suffix             NV

  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.1, SPIR, SLEEF, DISTRO, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce GTX 960
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  390.77
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               8
  Max clock frequency                             1177MHz
  Compute Capability (NV)                         5.2
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              2064121856 (1.922GiB)
  Error Correction support                        No
  Max memory allocation                           516030464 (492.1MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        131072 (128KiB)
  Global Memory cache line size                   128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 256
    Max number of write image args                16
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Device Vendor                                   GenuineIntel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
  Driver Version                                  1.1
  Device OpenCL C Version                         OpenCL C 1.2 pocl
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               8
  Max clock frequency                             4200MHz
  Device Partition                                (core)
    Max number of sub-devices                     8
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              8
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                               16 / 16      
    int                                                  8 / 8       
    long                                                 4 / 4       
    half                                                 0 / 0        (n/a)
    float                                                8 / 8       
    double                                               4 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              31500021760 (29.34GiB)
  Error Correction support                        No
  Max memory allocation                           8589934592 (8GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8388608 (8MiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            536870912 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
  Local memory type                               Global
  Local memory size                               4194304 (4MiB)
  Max number of constant args                     8
  Max constant buffer size                        4194304 (4MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_spir cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContext(NULL, ...) [other]              Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
`

Any help ?

**Comment by jsteube** [comment]
On my GTX750Ti I have very similar values to yours:

GTX750Ti:
```
  Global memory size                              2098069504 (1.954GiB)
  Max memory allocation                           524517376 (500.2MiB)
```

GTX960:
```
Global memory size 2064121856 (1.922GiB)
Max memory allocation 516030464 (492.1MiB)
```

Your Driver Version : 390.77 is fine, too.

No idea why this error occurs.

**Comment by w3soul** [comment]
Thanks jsteube,
Can you think of any possible solutions ?
I installed kali almost 20 times just to get hashcat to work, because every single time i tried tons of possible solutions and then ended up at broken OS.

If you want i can provide you ssh access for a deeper look (if you have some time please)?

Thanks, W.

**Comment by jsteube** [comment]
Sure, please install Ubuntu 16.04 or 18.04 on the box, then we can start debugging (as you know Kali is not supported).

**Comment by w3soul** [comment]
Love it, But can we please debug at Kali 2018 because i am (and really wanted to use) Kali as my pentest OS. I have Ubuntu 18.04 in VM. So it will be much much appreciated if we can debug it in Kali please ?

**Comment by jsteube** [comment]
Sorry man there's no way around Ubuntu.

**Comment by w3soul** [comment]
No problem bro, But if i am understanding correctly you can help debug only if i can install Ubuntu 16.04 or 18.04? Correct ?

**Comment by jsteube** [comment]
Correct. See if the error still occurs. If yes, please come to IRC freenode channel #hashcat and msg me directly (atom) - then wait.

**Comment by w3soul** [comment]
Will do man. Appreciate your help.

Thanks, W.

**Comment by jsteube** [comment]
Any update here?

**Comment by w3soul** [comment]
Hey man, thanks for the follow up.
So the update is - hashcat 4.1.0 (from github or hashcat website) i was receiving same error no matter what. I tried every possible solution available on the internet without success.
but i garbed the binaries of 4.0.1 (also tried 4.0.0 and 3.6) from https://hashcat.net/hashcat/ and they all worked right out of the box with no issues.

So:
root@kali: hashcat -b (OBJECT_ALLOCATION_FAILURE for wpa2,zip,office etc)
root@kali:~/Downloads/hashcat4.0.1# ./hashcat -b (Works well)
**So something is definitely going in 4.1.0 and i think the problem is with m02500.cl or m13600.cl.**

Any ideas when the next/new version will be avilable in the kali repos ?
I am so sorry man, but installing ubuntu as a standalone OS and configuring 300+ pentest tools is a next level of pain in the butt.

Thanks & Hope it helps. W.

**Comment by w3soul** [comment]
Oh - By the way if you want i will be happy to provide you the ssh access to kali box if that help resolving the issue in future releases.

Thanks and appreciated. W.

**Comment by jsteube** [comment]
I was able to reproduce this on my development system, but it required me to have a second instance of hashcat running in parallel. The reason is that with OpenCL there's actually no way to check if the total available OpenCL device memory is free to use or not. That means if you have X11 running on the GPU (or any other application that requires GPU memory, miners, games, browser, etc) than this error will occur.

Please check if the error still exists with hashcat v4.2.0 and if yes, please execute nvidia-smi and post the output here.

**Comment by w3soul** [comment]
Thanks man but Yes, Still same error for wpa.

**Version check: (For verification)**
root@kali:~/Downloads/hashcat-4.2.0# ./hashcat --version
v4.2.0

**Benchmarking**
root@kali:~/Downloads/hashcat-4.2.0# ./hashcat -b
hashcat (v4.2.0) starting in benchmark mode...
Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.
* Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 960, 492/1968 MB allocatable, 8MCU

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.

OpenCL Platform #3: Intel(R) Corporation
========================================
* Device #3: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.

Benchmark relevant options:
===========================
* --optimized-kernel-enable
Hashmode: 0 - MD5
Speed.Dev.#1.....:  6633.1 MH/s (80.21ms) @ Accel:128 Loops:512 Thr:1024 Vec:4
Hashmode: 100 - SHA1
Speed.Dev.#1.....:  2301.2 MH/s (72.13ms) @ Accel:256 Loops:128 Thr:640 Vec:1
Hashmode: 1400 - SHA-256
Speed.Dev.#1.....:   819.3 MH/s (81.06ms) @ Accel:128 Loops:64 Thr:1024 Vec:1
Hashmode: 1700 - SHA-512
Speed.Dev.#1.....:   277.2 MH/s (75.15ms) @ Accel:128 Loops:32 Thr:640 Vec:1
Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE
Started: Sun Aug  5 15:21:08 2018
Stopped: Sun Aug  5 15:21:37 2018

**nvidia-smi results:**
root@kali:~/Downloads/hashcat-4.2.0# nvidia-smi 
Sun Aug  5 15:23:33 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 00000000:01:00.0  On |                  N/A |
| 38%   50C    P0    28W / 120W |    640MiB /  1968MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       880      G   /usr/lib/xorg/Xorg                            55MiB |
|    0      1155      G   /usr/bin/gnome-shell                          53MiB |
|    0      1437      G   /usr/lib/xorg/Xorg                           333MiB |
|    0      1525      G   /usr/bin/gnome-shell                         193MiB |
+-----------------------------------------------------------------------------+

Thanks,

**Comment by jsteube** [comment]
All right, that's nice. Looks like we just identified another problem related to Kali. So it takes 640mb on your X11, for whatever reason. Can you please shutdown x11 and try to run hashcat from the console directly?

**Comment by jsteube** [comment]
OK based on this information I tried to workaround the problem by checking for available memory before actually running a kernel. I've pushed a beta version of this workaround here: https://hashcat.net/beta/

Can you please retry your tests with this beta version please.

**Comment by w3soul** [comment]
Thank you for all your help man. Yes, i noticed that 640mb usage as well.

So - I haven't tested shutting down the X11 solution but i have checked the beta version  and it worked right out of the box with no shutting down of anything. It gives me the 102.3 kH/s for wpa (this is the exact speed i was expecting with my GPU, speed with my i7 CPU is 14000H/s)

I tried both wpa (2500) and zip (13600) and they both worked.

**Below are benchmark results.**
========================================================================
**root@kali:~/Downloads/hashcat-4.2.0-beta# ./hashcat -b**
hashcat (v4.2.0-4-ge67195aa) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 960, 492/1968 MB allocatable, 8MCU
OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.
OpenCL Platform #3: Intel(R) Corporation
========================================
* Device #3: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5
Speed.Dev.#1.....:  6717.2 MH/s (79.24ms) @ Accel:128 Loops:512 Thr:1024 Vec:4
Hashmode: 100 - SHA1
Speed.Dev.#1.....:  2220.7 MH/s (74.56ms) @ Accel:256 Loops:128 Thr:640 Vec:1
Hashmode: 1400 - SHA-256
Speed.Dev.#1.....:   830.9 MH/s (80.02ms) @ Accel:128 Loops:64 Thr:1024 Vec:1
Hashmode: 1700 - SHA-512
Speed.Dev.#1.....:   281.3 MH/s (74.10ms) @ Accel:128 Loops:32 Thr:640 Vec:1
Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)
Speed.Dev.#1.....:   102.6 kH/s (78.64ms) @ Accel:128 Loops:32 Thr:1024 Vec:1
Hashmode: 1000 - NTLM
Speed.Dev.#1.....: 11248.3 MH/s (94.51ms) @ Accel:128 Loops:1024 Thr:1024 Vec:2
Hashmode: 3000 - LM
Speed.Dev.#1.....:  5632.2 MH/s (94.63ms) @ Accel:256 Loops:1024 Thr:256 Vec:1
Hashmode: 5500 - NetNTLMv1 / NetNTLMv1+ESS
Speed.Dev.#1.....:  5557.5 MH/s (47.76ms) @ Accel:128 Loops:256 Thr:1024 Vec:1
Hashmode: 5600 - NetNTLMv2
Speed.Dev.#1.....:   491.5 MH/s (67.63ms) @ Accel:128 Loops:32 Thr:1024 Vec:1
Hashmode: 1500 - descrypt, DES (Unix), Traditional DES
Speed.Dev.#1.....:   259.8 MH/s (64.42ms) @ Accel:8 Loops:1024 Thr:256 Vec:1
Hashmode: 500 - md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5) (Iterations: 1000)
Speed.Dev.#1.....:  2537.2 kH/s (92.32ms) @ Accel:1024 Loops:1000 Thr:32 Vec:1
Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix) (Iterations: 32)
Speed.Dev.#1.....:     3971 H/s (31.50ms) @ Accel:16 Loops:4 Thr:8 Vec:1
Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)
Speed.Dev.#1.....:    42094 H/s (76.87ms) @ Accel:512 Loops:128 Thr:32 Vec:1
Hashmode: 7500 - Kerberos 5 AS-REQ Pre-Auth etype 23
Speed.Dev.#1.....: 70882.1 kH/s (58.96ms) @ Accel:128 Loops:64 Thr:64 Vec:1
Hashmode: 13100 - Kerberos 5 TGS-REP etype 23
^C

Would you still like me to try shutting down x11and testing hashcat from console? if yes, then i will need some time because i have google how to do this :) 

Thanks, W.

**Comment by jsteube** [comment]
OK, cool. The workaround is a bit hackish. We have to test it on all the different opencl runtimes, but I think I will let it stay as it is. Thanks for your report! No need to shutdown X11.

**Comment by w3soul** [comment]
Awesome!!! Can't wait for this to be included in the original kali repository!!

**Comment by thesle3p** [comment]
I am seeing this error on Ubuntu 16.04 but with -m 1811

**Comment by w3soul** [comment]
Are you sure it's -m 1811 ?? I am not seeing 1811 hashmode, is it 1800 ?

**Comment by thesle3p** [comment]
my mistake 2811

**Comment by jsteube** [comment]
> I am seeing this error on Ubuntu 16.04 but with -m 1811

Please retry with latest beta version from https://hashcat.net/beta/ or github master and report if it fixes the error for you.

**Comment by thesle3p** [comment]
fixed
