### ISSUE TITLE
Fix Token Length Exception on NetNTLMv1 hashes

### ISSUE THREAD

**Issue by Jack64** [hashcat/hashcat#1641]
According to [multiple](https://gist.github.com/ihciah/86860d2d7d3cfb04b0b95d3ffbb86b68) [websites](https://github.com/sa7mon/wpe-parse/blob/master/parse.sh) and [hashcat's own forums](https://hashcat.net/forum/thread-4307.html) , the third field on the hash format for NetNTLMv1 should be nullable.
In hashcat v4.2.0, such a hash throws a Token Length Exception, but any value can be inserted on the third field and the hash will still be cracked (tested on the example hash).

Working:
`u4netntlm::kNS:338d08f8e26de93300000000000000000000000000000000:9526fb8c23a90751cdd619b6cea564742e1e4bf33006ba41:cb8086049ec4736c`

Not working:
`u4netntlm:::338d08f8e26de93300000000000000000000000000000000:9526fb8c23a90751cdd619b6cea564742e1e4bf33006ba41:cb8086049ec4736c`

Error message:
```bash
MBP:hashcat user$ hashcat -m5500 -a3 u4netntlm:::338d08f8e26de93300000000000000000000000000000000:9526fb8c23a90751cdd619b6cea564742e1e4bf33006ba41:cb8086049ec4736c --potfile-disable ?l?l?l?l?l?l
hashcat (v4.2.0) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz, skipped.
* Device #2: Intel(R) Iris(TM) Graphics 650, 384/1536 MB allocatable, 48MCU

Hash 'u4netntlm:::338d08f8e26de93300000000000000000000000000000000:9526fb8c23a90751cdd619b6cea564742e1e4bf33006ba41:cb8086049ec4736c': Token length exception
No hashes loaded.
```

Please allow this field to be nullable again to maintain compatibility with older conversion scripts and hostapd-wpe hash output.

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/39af031ced759117fc7c067722950072f1827abd
