### ISSUE TITLE
[Feature Request] DiskCryptor supprt (harddrive encryption and ISO)

### ISSUE THREAD

**Issue by KotekCzek** [hashcat/hashcat#1645]
Make support DiskCryptor please :)
The program is using:
HMAC-SHA-512
Mode XTS

This program has a very good feature - you can encrypt ISO (Aes-Twofish-Serpent) and burn it into CD, and then u can mount it in program. It is very similar to Truecrypt

Thank YOU

**Comment by KotekCzek** [comment]
**Refresh :) 
DiskCryptor is really good encrypting program.**

 I am asking you to look at the program. It supports popular encryption algorithms.

![d](https://user-images.githubusercontent.com/42041983/54862956-85d4b200-4d42-11e9-9ca0-16964f7262e9.jpg)
![d2](https://user-images.githubusercontent.com/42041983/54862991-faa7ec00-4d42-11e9-9c81-104045bb4d8a.jpg)

**I wish you all good :)**

**Comment by jsteube** [comment]
added
