### ISSUE TITLE
What mode to use to decrypt PBKDF2 with  sha256?

### ISSUE THREAD

**Issue by shadowzoom** [hashcat/hashcat#1649]
del

**Comment by philsmd** [comment]
-m 10900 = PBKDF2-HMAC-SHA256

this is an issue tracker for bugs/feature request. You can answer this type of question by looking at the example hashes here: https://hashcat.net/wiki/doku.php?id=example_hashes or using the --example-hashes paramter of hashcat
```
hashcat -m 10900 --example-hashes
```

please close this issue and consider using the wiki/faq/forum next time (btw: it's not allowed to post hashes within the hashcat forum)

**Comment by shadowzoom** [comment]
-m 10900 it seems to be not a vaild type..
Hashfile 'sha256.txt' on line 1 (PBKDF2...ODW/Hfn8nO/cP3I4nMkGh26Lr1tvDlw=): Signature unmatched
Hashfile 'sha256.txt' on line 2 (PBKDF2...Y2kzRJpFZaUqoP5tQCg8h7i5SzNWaIc=): Signature unmatched
Hashfile 'sha256.txt' on line 3 (PBKDF2...J6U5iXKLjYvqTaAdN07vRpizVg85+eE=): Signature unmatched
Hashfile 'sha256.txt' on line 4 (PBKDF2...uFXqVZewfz+9C5QKBCP+tuXZ8sG/D58=): Signature unmatched
Hashfile 'sha256.txt' on line 5 (PBKDF2...D7+BeEriGGUpaYE4ZmOa07RU/2CHUL0=): Signature unmatched
No hashes loaded.
