### ISSUE TITLE
Unknown hash-type '16800' selected

### ISSUE THREAD

**Issue by cyb3rL1ght** [hashcat/hashcat#1653]
### **Unknown hash-type '16800' selected.**

What can be done in this case? just wait for updates in repositories? My system: Linux parrot 4.16.0-parrot16-amd64

**Comment by akanom11** [comment]
This is because you have the old version of hashcat, try to install the newest

**Comment by cyb3rL1ght** [comment]
Decided..... 
1. apt-get remove hashcat
2. git clone https://github.com/hashcat/hashcat.git
3. cd hashcat
4. make
5. make install (at this point, I made an error...include/ext_OpenCL.h:15:10: fatal error: CL/cl.h: No such file or directory #include <CL/cl.h>......but I decided .... apt-get install opencl-headers -> make install)

**Comment by akanom11** [comment]
and it works?

**Comment by cyb3rL1ght** [comment]
Yes !)

**Comment by akanom11** [comment]
Nice!! I have the same problem
