### ISSUE TITLE
--stdout does't print mask in attack mode 7

### ISSUE THREAD

**Issue by AlbertVeli** [hashcat/hashcat#1654]
Steps to reproduce:
```
$ echo test > test.txt
$ hashcat --stdout -a 7 ?d test.txt
test
test
test
test
test
test
test
test
test
test
$ hashcat --stdout -a 7 ?d test.txt | sort -u
test
```
It still cracks as it should in mode -a 7, it's just --stdout that doesn't print the mask. Mode -a 6 test.txt ?d does prints the mask so the bug is only in mode 7.

Tested on build from 2018-08-13, latest commit:
a5746548e8f860a41f05637a8ffd4414bd4676db

**Comment by philsmd** [comment]
I can reproduce this, thanks for the report!
We should probably fix this soon.
