### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by Pateo-yachuanhuang** [hashcat/hashcat#1655]
token.sep[2]     = '$';
  token.len_min[2] = 96;
  token.len_max[2] = 96;
  token.attr[2]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

my bitcoin addresss min is 64, 
 token.sep[2]     = '$';
  token.len_min[2] = 64;
  token.len_max[2] = 96;
  token.attr[2]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_HEX;

as this, my macbook is good ,but i could't compile windows version, can you compile a new version for windows?

**Comment by hops** [comment]
Looks like this got changed yesterday with commit ce9b56e.
The beta build available at https://hashcat.net/beta should already include this fix.
