### ISSUE TITLE
55 character limit

### ISSUE THREAD

**Issue by thepaandu** [hashcat/hashcat#166]
Need to break sha512 and need to remove 55 character limit.
Don't mind if speed decreases even by half but it is important.

**Comment by jsteube** [comment]
Do you think a total of 112 chars for both salt and password is enough?

**Comment by thepaandu** [comment]
enough for some, not enough for some.
can you help?

**Comment by epixoip** [comment]
If you need more than one block of input and don't care about the speed loss, then you're probably just better off using OpenSSL on CPU.

**Comment by jsteube** [comment]
You said in an other discussion the salt length is fixed. What is that fixed salt length?

**Comment by thepaandu** [comment]
8 characters, so alpha num chars are 62^8 that is 2-00-000-billion
With a speed of 1-billion per sec, with your speed, it would break in 2
days.
Length of total string varies from 60-160 characters

**Comment by thepaandu** [comment]
Anything that can be done sir?

**Comment by jsteube** [comment]
Everything > 112 is a problem, we can't do that easily without creating a new hash-mode for it. To do that we'd need to know where it is used in so that we can decide if it worth the effort

**Comment by thepaandu** [comment]
Can we do it on 112>
It will work for most of my problems.
It is being used at a place of high reputation.
I won't be able to disclose everything but it is going to be worth it,
trust me.
We would be more than happy to add your name in the credits list and mark
my words, its a huge thing.

**Comment by jsteube** [comment]
Do you need it for -m 1710 or -m 1720 ?

**Comment by thepaandu** [comment]
i was using raw 1700 but it is going to be 1720 since first 8 characters
are unknown.

**Comment by thepaandu** [comment]
What would be your solution , sir ?

**Comment by thepaandu** [comment]
Sir, any updates?

**Comment by magnumripper** [comment]
Breath through your nose, young jedi.

**Comment by thepaandu** [comment]
I am trying.
Need you.

**Comment by jsteube** [comment]
I'm working on it. Send me example hash and plain please.

Format: 

hash:salt

**Comment by jsteube** [comment]
Nevermind that. I just played around an temporarily added support to -m 1720 and the speed instantly dropped from 620 MH/s to 440 MH/s. The problem is that this would also affect other modes, like -m 1722 (OSX) and that's why we can't add it to generic -m 17xx. For this mode to work, we need to add a completely new one, ideally with esalt. But before I'm going to do this I want to know where it's used in.

**Comment by thepaandu** [comment]
I am working with my partner who has successfully improved the hash collision theory and can be used to break hashes with  it.
So we need your help.
Thanks.

**Comment by thepaandu** [comment]
What do you say sir? Can you help me out with the solution?
"The power is in your hands, use it wisely"

**Comment by thepaandu** [comment]
Sir, I am awaiting your response.
Thanks.

**Comment by thepaandu** [comment]
Hello sir, I am desperately waiting for your response.
-Student.

**Comment by epixoip** [comment]
Holy shit dude, do you intend to write a comment on this every day?

**Comment by thepaandu** [comment]
I do not have your email id. and it is sort of urgent. and you are my 
last hope. so i am taking my chances by irritating you.

**Comment by thepaandu** [comment]
Happy valentine's day :|

**Comment by thepaandu** [comment]
Hey sir!
At Least tell me where to look for
If you have a solution , send in that and i wont disturb you ever

**Comment by jsteube** [comment]
Support for passwords and salts up to length 256 was added
