### ISSUE TITLE
Initializing device kernels and memory...Insufficient memory available

### ISSUE THREAD

**Issue by Pateo-yachuanhuang** [hashcat/hashcat#1662]
C:\Users\Administrator\Desktop\hashcat-4.2.1>hashcat64 -m 11300 -a 3 hash.txt ?h?h?h?h?h?h?h?h?h?h?h
hashcat (v4.2.1-16-g858e73a) starting...

* Device #6: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Tonga, 1523/2048 MB allocatable, 28MCU
* Device #2: Pitcairn, 1523/2048 MB allocatable, 20MCU
* Device #3: Tonga, 1523/2048 MB allocatable, 28MCU
* Device #4: Tonga, 1523/2048 MB allocatable, 28MCU
* Device #5: Tonga, 1523/2048 MB allocatable, 28MCU
* Device #6: Intel(R) Celeron(R) CPU G1840 @ 2.80GHz, skipped.

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP
* Uses-64-Bit

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

Initializing device kernels and memory...Insufficient memory available
* Device #5: Not enough allocatable device memory for this attack.

Started: Thu Aug 16 10:31:22 2018
Stopped: Thu Aug 16 10:31:33 2018

hi,what's wrong with my problem?

**Comment by jsteube** [comment]
At least 1.5GB host memory per OpenCL device

**Comment by Pateo-yachuanhuang** [comment]
thank you!

**Comment by imperia777** [comment]
Hello,
I have mining rig with 4 devices and only 4gb ram.
With version 4.0.1 I can run bruteforce scan, but with version 4.1 onward I cannot. So memory usage went up since version 4.1?
