### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [hashcat/hashcat#1667]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by jsteube** [comment]
Is there a reason why we developers have to do that? Usually it's done by package maintainers.

**Comment by ZerBea** [comment]
Why do we need another package manager? Every distribution has it's own (working package management system):
http://kmkeen.com/maintainers-matter/

**Comment by jsteube** [comment]
No reponse from OP, therefore closing the discussion. Feel free to reopen.
