### ISSUE TITLE
Token length exception on KeePass hash

### ISSUE THREAD

**Issue by ByteRaper** [hashcat/hashcat#1669]
If you take the hash of a KeePass container which has a changed iterations value, hashcat will throw out this error. Example: $keepass$\*2\*14698688\*222\*a4b02644c6... which is a container with 14698688 iterations. If you change the value to 6000 manually it will run.

**Comment by ghost** [comment]
Similar problem on $bitcoin$64$, which oddly enough does run on v3.6.0

**Comment by jsteube** [comment]
Fixed both problems. You can either rebuild using github master or use the binary from https://hashcat.net/beta/ or wait for the next release. Thanks for reporting!
