### ISSUE TITLE
compile hashcat for windows

### ISSUE THREAD

**Issue by qiufengqq** [hashcat/hashcat#1680]
[root@localhost hashcat-4.1.0]# make win64
x86_64-w64-mingw32-gcc   -pipe -std=gnu99 -Iinclude/ -Iinclude/lzma_sdk/ -IOpenCL/ -O2 -Ideps/OpenCL-Headers/ -I/usr/local/libiconv/include/ -m64 -DWITH_HWMON      -o hashcat64.exe src/main.c obj/affinity.WIN.64.o obj/autotune.WIN.64.o obj/benchmark.WIN.64.o obj/bitmap.WIN.64.o obj/bitops.WIN.64.o obj/combinator.WIN.64.o obj/common.WIN.64.o obj/convert.WIN.64.o obj/cpt.WIN.64.o obj/cpu_aes.WIN.64.o obj/cpu_crc32.WIN.64.o obj/cpu_des.WIN.64.o obj/cpu_md4.WIN.64.o obj/cpu_md5.WIN.64.o obj/cpu_sha1.WIN.64.o obj/cpu_sha256.WIN.64.o obj/debugfile.WIN.64.o obj/dictstat.WIN.64.o obj/dispatch.WIN.64.o obj/dynloader.WIN.64.o obj/event.WIN.64.o obj/ext_ADL.WIN.64.o obj/ext_nvapi.WIN.64.o obj/ext_nvml.WIN.64.o obj/ext_OpenCL.WIN.64.o obj/ext_sysfs.WIN.64.o obj/ext_lzma.WIN.64.o obj/lzma_sdk/Alloc.WIN.64.o obj/lzma_sdk/Lzma2Dec.WIN.64.o obj/lzma_sdk/LzmaDec.WIN.64.o obj/filehandling.WIN.64.o obj/folder.WIN.64.o obj/hashcat.WIN.64.o obj/hashes.WIN.64.o obj/hlfmt.WIN.64.o obj/hwmon.WIN.64.o obj/induct.WIN.64.o obj/interface.WIN.64.o obj/locking.WIN.64.o obj/logfile.WIN.64.o obj/loopback.WIN.64.o obj/memory.WIN.64.o obj/monitor.WIN.64.o obj/mpsp.WIN.64.o obj/opencl.WIN.64.o obj/outfile_check.WIN.64.o obj/outfile.WIN.64.o obj/pidfile.WIN.64.o obj/potfile.WIN.64.o obj/restore.WIN.64.o obj/rp.WIN.64.o obj/rp_cpu.WIN.64.o obj/rp_kernel_on_cpu.WIN.64.o obj/rp_kernel_on_cpu_optimized.WIN.64.o obj/selftest.WIN.64.o obj/shared.WIN.64.o obj/status.WIN.64.o obj/stdout.WIN.64.o obj/straight.WIN.64.o obj/terminal.WIN.64.o obj/thread.WIN.64.o obj/timer.WIN.64.o obj/tuningdb.WIN.64.o obj/usage.WIN.64.o obj/user_options.WIN.64.o obj/wordlist.WIN.64.o /usr/local/libiconv/lib/libiconv.a  -s -Wl,--dynamicbase -Wl,--nxcompat -lpsapi   -DCOMPTIME=1535969416 -DVERSION_TAG=\"v4.1.0\"
obj/dispatch.WIN.64.o:dispatch.c:(.text+0x1ef): undefined reference to `iconv'
obj/dispatch.WIN.64.o:dispatch.c:(.text+0x458): undefined reference to `iconv_open'
obj/dispatch.WIN.64.o:dispatch.c:(.text+0x49c): undefined reference to `iconv_close'
obj/wordlist.WIN.64.o:wordlist.c:(.text+0x3c8): undefined reference to `iconv'
obj/wordlist.WIN.64.o:wordlist.c:(.text+0x973): undefined reference to `iconv'
obj/wordlist.WIN.64.o:wordlist.c:(.text+0xe21): undefined reference to `iconv_open'
obj/wordlist.WIN.64.o:wordlist.c:(.text+0xec5): undefined reference to `iconv_close'
collect2: error: ld returned 1 exit status

the lib is realy at the path,build by me with libiconv code

but when I compile at centos  with cross compile x86_64-w64-mingw32-gcc,   the error occurs,

**Comment by jsteube** [comment]
Not a hashcat error

**Comment by qiufengqq** [comment]
> Not a hashcat error

yes  It's because lack of code for a lib named libiconv, I download the code win-libiconv, and copy the code libiconv.c to hashcat dir, add it in Makefile, rebuild hashcat , it runs well now. thanks a lot.

**Comment by zzulb** [comment]
Hello, we have encountered the same problem. Can you send me the relevant files (Makefile, libiconv.c)? Thank you! @qiufengqq
