### ISSUE TITLE
hashcat stuck at genarated bitmap tables

### ISSUE THREAD

**Issue by root1825** [hashcat/hashcat#1682]
its just goining on for a day and still not over
i cant crack wifi passes like this
 my command
C:\Users\A life form\Desktop\hashcat-4.2.1>hashcat64 -m 2500 -a 3 "C:\Users\A life form\Desktop\hashcat-4.2.1\tamer.hccapx" "C:\Users\A life form\Desktop\05wordfromlast.txt" --force
hashcat (v4.2.1) starting...

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) HD Graphics 520, 2438/4877 MB allocatable, 24MCU
* Device #2: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, skipped.

Generated bitmap tables...
and it goes on and on please i wanna skip this..maybe its a bug?

**Comment by jsteube** [comment]
Very likely to be a problem with the HD Graphics 520. Retry with -D1 too check if the CPU works. Please continue this thread on hashcat forum, this is not a hashcat problem and shouldn't discussed here.
