### ISSUE TITLE
Issue on Kali i386 - faulty HEX in -m 400

### ISSUE THREAD

**Issue by scaery** [hashcat/hashcat#1683]
I dunno the problem in detail but from what i got is far from the expected result.

```
# Sample Hashes wp.txt
$P$BJN9LQXrnGB0VsUHPiMICK4FIFgj.u0
$P$B7DPiPfihpdYVbTCNddapMaGDklzFV0

hashcat -m 400 -a 3 wp.txt ?s?s?s?s?s?s

Results:
$P$BJN9LQXrnGB0VsUHPiMICK4FIFgj.u0:$HEX[3f5b2f3a2127]
$P$B7DPiPfihpdYVbTCNddapMaGDklzFV0:$HEX[3f5b2f3a2127]
```

The real password is 6 times "?" and not "?[/:!'"
Im using hashcat (v4.2.1) on Kali Linux 2018.3 
Even with the latest source in github the result is wrong! Please try yourself...

[EDITED: don`t want to spoil the origin hash]

**Comment by scaery** [comment]
...going back to hashcat version 4.0.1 on Kali 2018.2 i386 live iso and it works again.

**Comment by scaery** [comment]
On every other box it works as usal, the sources from github inlcuded. They (VM creators of Kali) must have some other issue at their latest release. Just stumbled up on this.... if you want to reproduce download Kali from Offensive Security or fill a bugreport.

`https://images.offensive-security.com/virtual-images/kali-linux-2018.3-vm-i386.7z
84715b351460cadad7e5d87e4034bfc50a9befc3904205bc6ca0afc6def61066  kali-linux-2018.3-vm-i386.7z`

The error truely is still in their 2018.3 i368 Release. I think it can be closed now, as it`s not anymore related to the topic in here. But be warned about it and choose a different VM wisely.

**Comment by scaery** [comment]
Reported to Kali bugtracker!

https://bugs.kali.org/view.php?id=4962

**Comment by deargle** [comment]
Probably related to #1709 and #1695

**Comment by testersz** [comment]
I wrote about this:
https://github.com/hashcat/hashcat/issues/1582
https://github.com/hashcat/hashcat/issues/1695

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/a4ac370496d030777a5d5d65a894ac6bc2f953c6

If you don't want to wait for next release you can use latest github master or beta from https://hashcat.net/beta/

Thanks for reporting!
