### ISSUE TITLE
Request for APFS cracking implementation

### ISSUE THREAD

**Issue by GrepItAll** [hashcat/hashcat#1686]
I would like to request that APFS cracking support be added into Hashcat. I was pleased to see the FileVault 2 support, but APFS support would be beneficial too.

JtR has recently added support: https://github.com/magnumripper/JohnTheRipper/pull/3390

Please see this repo for instructions on retrieving APFS hashes: https://github.com/kholia/apfs2john

I can provide sample files and hashes along with the cleartext passwords.

**Comment by Banaanhangwagen** [comment]
I tested https://github.com/kholia/apfs2john on my APFS image.

The script gave me this output (redacted):
`$fvde$1$16$0ec787cfa0bfff2c9a8ebd11d0d0XXXX$XXXXX$XXXX983140abdc4909e1ae1c2276bc672a0868bc424ab44a00000000000000000000000000000000`

As we can see, the output was padded with zeroes. I simply cut them off and Hashcat succesfully cracked APFS encryption with -m16700.

Maybe someone else can reproduce this?

**Comment by GrepItAll** [comment]
I'll try and validate, but I'm surprised that the output was crackable with FileVault 2

**Comment by GrepItAll** [comment]
Thanks @jsteube! Excellent work as always. I have some disk images with known passwords that I am looking forward to trying this against.

**Comment by Banaanhangwagen** [comment]
Thanks! Much appreciated!
Will test this in a couple of days on different images.
