### ISSUE TITLE
Nethunter meta-packages update

### ISSUE THREAD

**Issue by More2Chi** [hashcat/hashcat#1687]
I updated my nethunter metapackages and it seems to have broken wifite (wifite 2?) with the following message:
[!] Warning: Recommended app hashcat was not found. install @ https://hashcat. net/hashcat/

same warning with hcxdumptool & hcxpcaptool..

seems to me the new wifite needs new (hashcat?) dependencies that aren't yet rolled into the nethunter build, yet the new wifite is? weird but i wouldn't be posting if after days of googling the brick wall of noob still is perplexing me.

**Comment by ZerBea** [comment]
That is correct and it is neither a hashcat issue, nor a hcxtools/hcxdumptool issue. wifite2 added some "new (state of the art)" tools like hashcat, hcxtools and hcxdumptool. You must install them!
Read more about this new wifite2 features here:
https://github.com/derv82/wifite2

**Comment by jsteube** [comment]
Not a hashcat issue
