### ISSUE TITLE
Drivers issue

### ISSUE THREAD

**Issue by JeffSoh** [hashcat/hashcat#1689]
I have an install of Ubuntu 16.04 Server. Installed the AMD Pro gpu drivers; kernel module is loaded and system sees the cards, but hashcat does not. Have installed ROCm, no errors, broken dependencies or missing packages. Still does not see the cards nor does pyrit. Fairly experienced Linux user but don't use Ubuntu regularly. am I missing something obvious?
root@bwygpu01:~# lsmod | grep amdgpu
amdgpu               2719744  3
amdchash               16384  1 amdgpu
amd_sched              24576  1 amdgpu
amdttm                110592  1 amdgpu
amdkcl                 28672  4 amdttm,amdgpu,amd_sched,amdkfd
i2c_algo_bit           16384  2 igb,amdgpu
drm_kms_helper        172032  1 amdgpu
drm                   401408  9 amdttm,amdgpu,amdkcl,amd_sched,drm_kms_helper

root@bwygpu01:~# lspci -nn | grep -E 'VGA|Display'
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Malta [Radeon HD 7990/8990 OEM] [1002:679b]
06:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Malta [Radeon HD 7990/8990 OEM] [1002:679b]
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Malta [Radeon HD 7990/8990 OEM] [1002:679b]
0a:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Malta [Radeon HD 7990/8990 OEM] [1002:679b]

**Comment by philsmd** [comment]
well, it's easy to test. If for instance the tool
```
clinfo
```
reports the GPU correctly, hashcat should too.

If even clinfo does not show your GPU, we can be sure that it is not a problem within hashcat (but a problem with your installation/setup).

Also see https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

Please test clinfo and report back. Don't forget to close the issue if it is starting to work and/or you found a solution. Thx

**Comment by jsteube** [comment]
No response from OP for a long time plus probably driver error therefore closed. Feel free to reopen if you have no insights.
