### ISSUE TITLE
compiling hashcat with AMD AOCC LLVM 6.0 release

### ISSUE THREAD

**Issue by hashuser1** [hashcat/hashcat#1691]
Im trying to compile hashcat using AMDs AOCC and I keep getting the error"
In file included from src/ext_lzma.c:10:
include/ext_lzma.h:8:10: fatal error: 'Alloc.h' file not found
#include <Alloc.h>
         ^~~~~~~~~
1 error generated.
src/Makefile:459: recipe for target 'obj/ext_lzma.NATIVE.STATIC.o' failed
make: *** [obj/ext_lzma.NATIVE.STATIC.o] Error 1
In file included from src/mpsp.c:17:
include/ext_lzma.h:8:10: fatal error: 'Alloc.h' file not found
#include <Alloc.h>
         ^~~~~~~~~
In file included from src/interface.c:24:
include/ext_lzma.h:8:10: fatal error: 'Alloc.h' file not found
#include <Alloc.h>

If I change those includes to <stdlib.h> will it effect the operation of the program?

**Comment by jsteube** [comment]
For me it looks like you are using a broken github clone. Ideally re-clone the entire hashcat source from scratch.
