### ISSUE TITLE
speed variance between 2 hashes mode -11300

### ISSUE THREAD

**Issue by hashuser1** [hashcat/hashcat#1692]
Im testing 2 hashes, the first being the known hash and the second, the unknown hash. Im using the same word list on both hashes but the speed on the unknown hash is 4x faster. Does the performance of the same hash type vary so dramatically or is this another example of rocm messing up? 

./hashcat64.bin -m 11300 test wordlist3_sorted.txt 

Hash.Type........: Bitcoin/Litecoin wallet.dat
Hash.Target......: $bitcoin$
Time.Started.....: Sat Sep 15 10:29:40 2018 (22 secs)
Time.Estimated...: Sun Sep 16 04:33:32 2018 (18 hours, 3 mins)
Guess.Base.......: File (wordlist3_sorted.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:     1891 H/s (9.07ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#2.....:     1878 H/s (9.10ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#3.....:     1890 H/s (9.03ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#4.....:     1892 H/s (9.17ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#*.....:     7551 H/s

./hashcat64.bin -m 11300 bitcoin_hash wordlist3_sorted.txt 

Hash.Type........: Bitcoin/Litecoin wallet.dat
Hash.Target......: $bitcoin$
Time.Started.....: Sat Sep 15 10:35:47 2018 (2 secs)
Time.Estimated...: Sat Sep 15 14:40:04 2018 (4 hours, 4 mins)
Guess.Base.......: File (wordlist3_sorted.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:     8409 H/s (9.03ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#2.....:     8358 H/s (9.11ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#3.....:     8321 H/s (9.00ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#4.....:     8406 H/s (9.15ms) @ Accel:32 Loops:16 Thr:256 Vec:1
Speed.Dev.#*.....:    33498 H/s

OS = Xubuntu 18.04
rocm = v1.9
uname -a
Linux amd-fail 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[clinfo.txt](https://github.com/hashcat/hashcat/files/2385954/clinfo.txt)
[rocminfo.txt](https://github.com/hashcat/hashcat/files/2385955/rocminfo.txt)

**Comment by Chick3nman** [comment]
It's likely that one of the hashes you are targeting has different KDF settings, which can result in slower/faster generation times. KDF settings in applications are usually tuned towards slower generation speeds as time goes on to resist attacks from newer, more advanced hardware. It's possible that your unknown hash was generated using weaker settings and is thus easier/faster to generate candidates for.

**Comment by jsteube** [comment]
Since this algorithm is known to have a dynamic iteration count, I agree with @Chick3nman theory. Feel free to reopen this issue if you want, but please provide both hash lines so we can reproduce locally.
