### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by amheydari** [hashcat/hashcat#1694]
I use the hashcat as a library in another program.
After each use, some memory will run from the execution of the program.
What is the reason for this memory leak?
Thank.

**Comment by philsmd** [comment]
are you sure it doesn't depend on your code? did you free every buffer/struct you allocated memory for? Do you have some code we could test with?
Are you sure it is hashcat that leaks memory or could it be the driver? You could use tools like valgrind and/or gcc sanitizer features to debug where the memory leak is.
Thx

**Comment by jsteube** [comment]
Memleaks come from OpenCL runtime not hashcat. Please inform driver vendors instead.
