### ISSUE TITLE
switch buffer le optimization

### ISSUE THREAD

**Issue by RAN1** [hashcat/hashcat#1701]
Aligning LE buffers on generic platforms uses swaps and aligns, but it can also be done without swapping by reversing the direction of the bytealign (i.e. towards higher bytes instead of lower):

[switch_buffer_le.txt](https://github.com/hashcat/hashcat/files/2408089/switch_buffer_le.txt)

I see some performance gain on the Intel CPU and Apple runtimes, but I don't know how well this performs elsewhere. This could use input, especially testing on older AMD GPUs.

**Comment by jsteube** [comment]
Looks nice, please send in PR with all functions affected. Ideally you can use tools/code_generators/ and add or modify a perl script. Those are responsible for doing the changes.

**Comment by jsteube** [comment]
Based on the changes your did with your latest PR, are you going to add this change in form of a new code generator or did you do already? If yes, could please PR the changes to the inc_common.cl as well?

**Comment by jsteube** [comment]
Implemented with commit https://github.com/hashcat/hashcat/commit/e1fe3e755b54c0dd8ccb5c6a0bc3a7f48f4c9693

Not exactly the same way but performance improvement should be the same or better.
