### ISSUE TITLE
Segmentation Fault  in 4.2.1 

### ISSUE THREAD

**Issue by mathitam** [hashcat/hashcat#1703]
hashcat --force -a 0 -m 13100 ~/active/test.kirbi /usr/share/wordlists/rockyou.txt 
hashcat (v4.2.1) starting...

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 4096/13919 MB allocatable, 4MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastically reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

* Device #1: build_opts '-cl-std=CL1.2 -I OpenCL -I /usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=8 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=13100 -D _unroll'
Dictionary cache building /usr/share/wordlists/rockyou.txt: 33553434 byteDictionary cache building /usr/share/wordlists/rockyou.txt: 67106869 byteDictionary cache building /usr/share/wordlists/rockyou.txt: 134213744 bytDictionary cache built:
* Filename..: /usr/share/wordlists/rockyou.txt
* Passwords.: 14344392
* Bytes.....: 139921507
* Keyspace..: 14344385
* Runtime...: 2 secs

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => Segmentation fault
-------------------------
root@kali:~/impacket/kerberoast# uname -a
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
root@kali:~/impacket/kerberoast# uname -mrs
Linux 4.15.0-kali2-amd64 x86_64
root@kali:~/impacket/kerberoast# cat /etc/issue
Kali GNU/Linux Rolling \n \l

root@kali:~/impacket/kerberoast# cat /etc/*-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.4"
VERSION_ID="2018.4"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
root@kali:~/impacket/kerberoast# ls /boot | grep vmlinuz-
vmlinuz-4.15.0-kali2-amd64

root@kali:~/impacket/kerberoast# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          **Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz**
Stepping:            4
CPU MHz:             798.107
CPU max MHz:         3000.0000
CPU min MHz:         500.0000
BogoMIPS:            4788.52
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            4096K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt ibpb ibrs stibp dtherm ida arat pln pts

**Comment by Chick3nman** [comment]
"hashcat --force"

Well that should tell you everything you need to know right there.

**Comment by philsmd** [comment]
I agree, and furthermore both pocl and the kali distribution are not recommended by hashcat. I would suggest to use a distribution supported by the major hardware vendor (like Intel, Nvidia, AMD... i.e. ubuntu for instance) and use the native/proprietary driver that can be downloaded from the vendors web page. The recommended driver versions can be found here https://hashcat.net/hashca
(I know that pocl is in the list too, but since pocl is still kind of experimental and very often leads to driver crashes, you should stick to the proprietary drivers of the hardware vendor).

Please do not forget to close the ticket if it works with the suggestions

**Comment by mathitam** [comment]
worked after installing nvidia driver. thanks
