### ISSUE TITLE
[Bug]: Piping candidates to Hashcat not working on Windows

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1705]
When piping the password candidates to the newest Hashcat (e.g. with PRINCE), it does not process the input but stops immediately just after starting. Example:

```
prince.exe example.dict | hashcat64.exe -m 400 -a 0 hashlist.txt
```

With older Hashcat versions (e.g. 4.1.0) this was working. And it only does not work on Windows, on Linux it is still working fine.

**Comment by philsmd** [comment]
I did try to reproduce this on windows 10 with both hashcat 4.2.0 and 4.2.1 and both worked correctly.

I've tested it with
```
echo hashcat|hashcat64.exe -m 400 hashlist.txt
```
and
```
type dict.txt | hashcat64.exe -m 400 hashlist.txt
```
and
```
pp64.exe dict2.txt | hashcat64.exe -m 400 hashlist.txt
```

all of these commands succeeded and cracked the hashes as expected.

I'm not sure how to reproduce this. Did you test with a different version (non release versions)?
if not, can you please test again with a different windows 10 system (maybe it's a problem with your driver/setup)?

**Comment by jsteube** [comment]
I can reproduce this with the following command:

> type example.dict | hashcat64.exe -m 400 example400.hash

But it requires the latest github master version (or binary beta from hashcat.net/beta). Older versions 4.1.0, 4.2.0 and 4.2.1 seem not affected.
