### ISSUE TITLE
'inc_vendor.cl' file not found on macOs High Sierra 10.13.6 (17G65)

### ISSUE THREAD

**Issue by NikKovIos** [hashcat/hashcat#1706]
```
sudo -s HASH_FILE=/Users/n/SearchDumps/2.hccapx POT_FILE=home-wifi.txt HASH_TYPE=2500 ./naive-hashcat.sh
hashcat (v4.2.1-57-g58d101d4) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz, skipped.
* Device #2: HD Graphics 4000, 384/1536 MB allocatable, 16MCU

Hashes: 2 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:8:10: fatal error: 'inc_vendor.cl' file not found
#include "inc_vendor.cl"
         ^

* Device #2: Kernel /Users/n/naive-hashcat/hashcat-src/OpenCL/m02500-pure.cl build failed - proceeding without this device.

Started: Fri Sep 28 11:48:33 2018
Stopped: Fri Sep 28 11:48:33 2018
```

Any suggestions?

**Comment by philsmd** [comment]
Why do you use naive-hashcat.sh ? a third-party tool not developed/supported/maintained by hashcat ?

Please download the source code of the release version from https://hashcat.net/hashcat and extract it with "7z x". Enter the extracted folder and compile it according to the instructions (https://github.com/hashcat/hashcat/blob/master/BUILD.md), then run something like
```
./hashcat -b -m 0
```
(to benchmark the MD5 speed of your setup)

My guess is that it has something to do with naive-hashcat.sh and is not really a hashcat problem. You could also make sure that the file OpenCL/inc_vendor.cl exists within the extracted folder (from the downloaded file from https://hashcat.net/hashcat)

**Comment by jsteube** [comment]
No response from OP and probably an error in a third party overlay, therefore closing issue. Feel free to reopen.

**Comment by skozlovskiy** [comment]
Hi. I have the same problem.
MacOS Mojave 
Version: 10.14.6 (18G87)
MacBook Pro (15-inch, 2018)
Processor: 2.6 GHz Intel Core i7
Memory: 32 GB 2400 MHz DDR4
Graphics: Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

Install hashcat like this:
>>git clone https://github.com/hashcat/hashcat.git
>>make


`
MacBook-Pro:hashcat p$ ./hashcat -m 2500 -b -d 3
hashcat (v5.1.0-1379-g706d69ba) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/hashcat/OpenCL/m02500-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
OpenCL API (OpenCL 1.2 (Jun 23 2019 21:50:55)) - Platform #1 [Apple]

* Device #1: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, skipped
* Device #3: AMD Radeon Pro 560X Compute Engine, 1024/4096 MB allocatable, 16MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /Users/panter/utils/wifi_hack/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.


Started: Sun Aug 11 17:01:33 2019
Stopped: Sun Aug 11 17:01:51 2019
`

**Comment by ivanbacher** [comment]
+1

```
MacBook-Pro OpenCL % ../hashcat -m 2500 -b -d 3
hashcat (v5.1.0-1403-g87022919) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/***/***/Desktop/hashcat/OpenCL/m02500-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
OpenCL API (OpenCL 1.2 (Sep  5 2019 21:59:08)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, skipped
* Device #3: AMD Radeon Pro 560X Compute Engine, 1024/4096 MB allocatable, 16MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:11:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^

* Device #3: Kernel /***/***/***/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.


Started: Sat Oct 12 19:25:05 2019
Stopped: Sat Oct 12 19:25:06 2019
```

**Comment by Rdgeno** [comment]
Switch to windows 10 I got it working with AMD GPU force the opencl then use -- self-test-disable. It works 5 tests.

**Comment by Rdgeno** [comment]
Passed every time in 1 sec. I was working no GPU for a month with GPU 1 sec. 5 times 2 computers. It works.

**Comment by davidfbpereira** [comment]
Same here: 

➜  hashcat git:(master) ./hashcat -b -m 0
hashcat (v5.1.0-1488-g52e83c2) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 (Sep  5 2019 21:59:08)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 6100, 1472/1536 MB (384 MB allocatable), 48MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:9:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^

* Device #2: Kernel /Users/davidfbpereira/Desktop/hashcat/OpenCL/m00000_a3-optimized.cl build failed - proceeding without this device.


Started: Wed Dec  4 18:28:03 2019
Stopped: Wed Dec  4 18:28:03 2019

***************************************************************************************************
Don't know what else to do... :c
