### ISSUE TITLE
Does hashcat support substr of md5?

### ISSUE THREAD

**Issue by cwyalpha** [hashcat/hashcat#1716]
I want to crack first 10 bit of md5 like this:
$hash=substr(md5($pass), 0,10)
But there is only half md5 in hashcat. 

This post said that hashcat will support substr hash. Any progress now?

_Originally posted by @epixoip in https://github.com/hashcat/hashcat/issues/116#issuecomment-170301181_

**Comment by jsteube** [comment]
Not by default, you have to alter a kernel and white-out the unneeded bits. Also with just 10 bits you will have tons of collisions. I think 10 bit is even fast enough to produce on slowest CPU you can think of.

**Comment by jsteube** [comment]
For the above reason, I don't see a reason to have a issue in here for it.
