### ISSUE TITLE
Consider using file locking

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#172]
Some time ago I had concurrent sessions of oclHashcat completely thrash a potfile because they were both using the same one - and both assumed they had exclusive use to it. Can't remember the details but I probably used the --potfile option pointing to one same file assuming file locking was in place. Perhaps that was stupid but nothing stopped me from doing it and no docs made me any wiser.

Now that I get to see the code, I see you are using O_APPEND (actually fopen "a") but no locking. This is a decent first step but not safe enough.

This is simple to fix though. Any write to the pot file should be wrapped with a blocking write lock. I'm willing to implement this and hand you a PR unless you have some opinion against it for whatever reason?

**Comment by jsteube** [comment]
That would be great. Will it work on Windows, too?

**Comment by magnumripper** [comment]
I guess it could work fine with Cygwin but not with MinGW until someone contributes some Windows specific code. I wouldn't care about that, they still have O_APPEND which is enough for casual use.
