### ISSUE TITLE
--quiet --status --status-timer=1 Doesn't show status before exiting/finishing

### ISSUE THREAD

**Issue by rlaphoenix** [hashcat/hashcat#1720]
This results in it always ending up at progress like 90%/100% or 88% e.t.c because that last status timer doesn't get ran as it finishes.

**Comment by rlaphoenix** [comment]
Thanks @jsteube how will I know when this is in a official binary release?

**Comment by jsteube** [comment]
You can either use hashcat github master and compile yourself, use the binary beta from https://hashcat.net/beta/ or wait for the next release version. I typical announce new releases on twitter.
