### ISSUE TITLE
LM default charset

### ISSUE THREAD

**Issue by Lexus89** [hashcat/hashcat#1724]
When running a brute force on LM hashes is nicely split the hashes but it uses a very strange default charset. I tested on multiple systems and all have this issue. Result is that it can't crack all LM hashes as supposted to.

Hashcat version: 4.2.1
Command: hashcat64.exe -a 3 -m 3000 --force C:\Users\test\hash.txt

Guess.Mask.......: ?1?2?2?2?2?2?2 [7]
Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined

**Comment by jsteube** [comment]
The default mask is not supposed to crack all LM password. Please use a full mask instead.
