### ISSUE TITLE
"Not a native Intel OpenCL runtime" but I have a qualifying processor I think...

### ISSUE THREAD

**Issue by soronrheeyi** [hashcat/hashcat#1731]
Hi all,

I am new to running Kali as my primary OS. I'm following these instructions to try my hand at getting the wifi password to my own personal network: https://www.wikihow.com/Hack-WPA/WPA2-Wi-Fi-with-Kali-Linux

Everything goes smoothly until I get to the bit where I run HASH_FILE=name.hccapx POT_FILE=name.pot HASH_TYPE=2500 ./naive-hashcat.sh

At which point I get this error:
Not a native Intel OpenCL runtime. Expect massive speed loss. You can use --force to override, but do not report related errors.

At which point the program stops and I am presented with the command prompt.

I've researched my system's processor and this is what I have: https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/atom-z36xxx-z37xxx-datasheet-vol-1.pdf

From what I can conclude, my graphics card does support OpenCL. I am wondering what I am missing. Thoughts?

**Comment by jsteube** [comment]
The error message tells you that the driver used (which ships the OpenCL runtime) is not the correct one. For Intel CPU, it's Intel OpenCL runtime. Make sure there's not OpenCL SDK installed. Also make sure that the GPU OpenCL driver part is broken in the Intel OpenCL runtime itself, so it can no be used. IOW, you can only use your CPU but you need to select the right OpenCL runtime. This one was updated to 18.x version recently and I added support for this in hashcat 5. Anyway, not a bug.

**Comment by soronrheeyi** [comment]
ok, cool where can I download (sorry I reported a bug) and what is the term command, because I'm pretty sure I updated everything

**Comment by und3fined404** [comment]
> The error message tells you that the driver used (which ships the OpenCL runtime) is not the correct one. For Intel CPU, it's Intel OpenCL runtime. Make sure there's not OpenCL SDK installed. Also make sure that the GPU OpenCL driver part is broken in the Intel OpenCL runtime itself, so it can no be used. IOW, you can only use your CPU but you need to select the right OpenCL runtime. This one was updated to 18.x version recently and I added support for this in hashcat 5. Anyway, not a bug.

actual commands to run instead of the "make sure that" would be more helpful I think
