### ISSUE TITLE
brute-force hex-salt encoding-to parameter

### ISSUE THREAD

**Issue by armin884** [hashcat/hashcat#1735]
I already asked in forum and answer was encoding-from/encoding-to is only supported with wordlist. Any possibility to add that to brute-force also?
This my syntax, only works with wordlist result is correct in $HEX output.. brute-force gives no result with that syntax...
```
-m 160 --hex-salt --encoding-to=utf-16le
```

**Comment by jsteube** [comment]
We can only do it for -S so it will not work for -m 160. I guess it makes no sense then? Feel free to reopen.

**Comment by armin884** [comment]
-S is -S, --slow-candidates ? How does that work? I never used that before... Well my hash is HMAC-SHA1 (key = $salt) and the salt is given in hex.
