### ISSUE TITLE
Feature Request - New-Algo - SolarWinds

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#1736]
As described here: https://www.atredis.com/blog/2018/10/24/fun-with-the-solarwinds-orion-platform

Specific quote from the post:
> Orion password hashing is a variant of a salted SHA512 hash. The hash is computed by first generating a salt that consists of the lowercase username. If the salt is less than 8 bytes long, it is appended with bytes from the string "1244352345234" until it is 8 bytes. For example, the salt for username "ADMIN" would become "admin124", while the salt for "Bo" would become "bo124435". Once the salt has been calculated, a RFC2898 PBKFD2 is generated using the default iteration count of 1000 and the SHA1 hash algorithm. Finally, a SHA512 hash of the PBKDF2 output is taken and encoded using Base64. It doesn't appear that any existing tools support cracking passwords in this format, but Hashcat comes close with PBKDF2-HMAC-SHA1(sha1:1000) support, and is only missing the final call to SHA512(). This hashing function has been implemented in the Ruby script [hash-password.rb](https://github.com/atredispartners/solarwinds-orion-cryptography/blob/master/hash-password.rb).

- `admin` username with blank password is:
```
/+PA4Zck3arkLA7iwWIugnAEoq4ocRsYjF7lzgQWvJc+pepPz2a5z/L1Pz3c366Y/CasJIa7enKFDPJCWNiKRg==
```

**Comment by roycewilliams** [comment]
JtR reference: https://github.com/magnumripper/JohnTheRipper/pull/3449

**Comment by jsteube** [comment]
The requested algorithm was added to hashcat. You can either wait for release version or use the binary beta from https://hashcat.net/beta or compile from GitHub master source yourself. Thanks for the request!
