### ISSUE TITLE
[Bug] Hashcat brain not running on Windows

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1738]
Hashcat brain cannot be started on windows, the log only shows following messages:

```
1540806366.422404 |   0.00s |   0 | Generated authentication password: xxxxxxxx
1540806366.422404 |   0.00s |   0 | socket: No error
```

**Comment by apatedolos** [comment]
I can confirm the same issue.

**Comment by jsteube** [comment]
I can confirm that the server is not running on Windows. The client should work. Please confirm.

**Comment by s3inlc** [comment]
Yes, I can confirm that the client is working.

Though, in case of an error on the client side, the log output is quite scrambled because it's in between the other status output etc.

**Comment by apatedolos** [comment]
Clent works fine here also however the time to crack jumps quite significantly. 
On a standalone machine with hash list using rockyou with rule it would only take 20 minutes to completely run.
Once connected to the brain server this jumped up to 147 days!

**Comment by s3inlc** [comment]
@apatedolos Are you using the brain with a fast hash algorithm? Keep in mind that according to the release notes, it's only worth to use the brain for very slow algorithms otherwise the brain is a bottleneck.

**Comment by apatedolos** [comment]
ok, noted. next time i'll rtfm.... that is some bottleneck.

**Comment by philsmd** [comment]
One of the problems (I troubleshooted it a little bit), seems to be that when we start the server here:
https://github.com/hashcat/hashcat/blob/b8eb7105dd596b6cb563f7cf61addd27d5add75d/src/main.c#L1052

we didn't setup WSAStartup () yet which is in user_options_check_files ()
https://github.com/hashcat/hashcat/blob/b8eb7105dd596b6cb563f7cf61addd27d5add75d/src/user_options.c#L1873-L1890
called after https://github.com/hashcat/hashcat/blob/b8eb7105dd596b6cb563f7cf61addd27d5add75d/src/main.c#L1083

so the WSAStartup () needs to be done before the socket initialization (also for the server) on windows.

I didn't yet confirm that the bind works... but that's probably the next step to do.

---

update: it seems to work but I still get a "Too many clients" error, which is very weird o.O. The connection is correctly detected and if the firewall rule was correctly set (allow from public and/or private network) we see the connection attempt: "Connection from 192.168.0.2:44245"

---

update2: it seems to work with the correct --brain-password parameter (and the WSA fix from above). gosh damnit!!! I'm still not sure why I got the "Too many clients" beforehand with an invalid password.

**Comment by jsteube** [comment]
I've pushed a fix and updated beta version here: https://hashcat.net/beta/ please check if fixed and close the issue

**Comment by s3inlc** [comment]
Thanks, the server now starts successfully and works on Windows.

But now the brain client on Windows seem to be broken because of the change:
```
hashcat64.exe --brain-client --brain-host localhost --brain-password xxxxxx -m 0 -a 0 example0.hash example.dict
hashcat (v5.0.0-9-g61ded2bd) starting...

localhost: Either the application has not called WSAStartup, or WSAStartup failed.
Started: Wed Oct 31 10:59:42 2018
Stopped: Wed Oct 31 10:59:42 2018
```

**Comment by jsteube** [comment]
New beta up, please retry.

**Comment by s3inlc** [comment]
With the newest beta both client and server are working now on Windows, so the issue is resolved.
Thanks again.
