### ISSUE TITLE
unbundle lzma sdk

### ISSUE THREAD

**Issue by ZeroChaos-** [hashcat/hashcat#1742]
is there a reason that lzma headers installed by the distro aren't good enough?

**Comment by jsteube** [comment]
There's a flag in the Makefile to enable the use of the system headers

**Comment by ZeroChaos-** [comment]
the flag seems to expect -llzmasdk which I can't actually find in the 7-zip sdk.  Could maybe some documentation be added to explain the requirement and what is required to build this unbundled?

**Comment by jsteube** [comment]
OK I send in the path. @ZeroChaos- and @anthraxx can you please try if it works for your distributions? Maybe we need to change some of the system specific include paths?

**Comment by ZeroChaos-** [comment]
@anthraxx this sure doesn't work for me, I don't even see anything called lzmasdk inside the lzmasdk that would make -llzmasdk work, you have any insight here?

**Comment by philsmd** [comment]
I'm pretty sure on ubuntu, for instance, it's called liblzma-dev and you can link it with -llzma (instead of -llzmasdk).
Other distributions could use other names for the library of course (e.g. p7zip or 7z, 7zip related instead of lzma, lzma-sdk etc)

**Comment by jsteube** [comment]
> I'm pretty sure on ubuntu, for instance, it's called liblzma-dev and you can link it with -llzma (instead of -llzmasdk).
> Other distributions could use other names for the library of course (e.g. p7zip or 7z, 7zip related instead of lzma, lzma-sdk etc)

I couldn't find the required headers in this ubuntu package. I think what we would also need is something like liblzma-sdk-dev (which doesn't exist). Mixing SDK headers with distribution libraries could cause problems.

For Ubuntu I'd therefore recommend to stick to our bundled LZMA SDK files

**Comment by jsteube** [comment]
I don't see how we can improve this any further. If package maintainers want to use system libraries, they have to modify the path to the includes plus they may have to modify the name of the library to link. Since this can be different from distro to distro want can't do much on here.

**Comment by neheb** [comment]
Is it possible to replace LZMA-SDK with liblzma?
