### ISSUE TITLE
hashcat version number not showing git SHA

### ISSUE THREAD

**Issue by mattames** [hashcat/hashcat#1743]
Since hashcat 5.0 was released, when I build hashcat from source, "hashcat -V" only returns "v5.0.0". 

Previously when building form source it used to return a string showing the hashcat version number and the git commit that the source was built from. 

This is very useful in troubleshooting and testing new versions. Can you please fix the build so that 
"hashcat -v" returns the git commit sha.

**Comment by mattames** [comment]
An example of the old style is:-

v4.2.1-53-g77daf05d+

**Comment by mattames** [comment]
current hashcat -V 

v5.0.0

**Comment by mattames** [comment]
OK my mistake - the Makefile is still set to production = 1.

Closing issue.

**Comment by jsteube** [comment]
Should be fixed, thanks!

**Comment by mattames** [comment]
Cheers Jens!
