### ISSUE TITLE
Add option to increase or remove stdin timeout

### ISSUE THREAD

**Issue by gavriilos** [hashcat/hashcat#1744]
On version `5.0.0`, the newly introduced stdin mode timeout breaks one of my use cases.

I use an external candidate generator that takes a long time on startup. Up till `v4.2.1` everything worked out ok: hashcat would just wait until the generator starts piping candidates. However, on `v5.0.0` hashcat aborts with the following error:

> ATTENTION! Read timeout in stdin mode. The password candidates input is too slow:
> * Are you sure that you are using the correct attack mode (--attack-mode or -a)?
> * Are you sure that you want to use input from standard input (stdin)?
> * If so, are you sure that the input from stdin (the pipe) is working correctly and is fast enough?
> 
> No password candidates received in stdin mode, aborting...

Could you please add an option to increase or remove this timeout?

**Comment by magnumripper** [comment]
https://github.com/hashcat/hashcat/pull/1719#issuecomment-430603088 😉
