### ISSUE TITLE
The system hangs on the Ethereum hash

### ISSUE THREAD

**Issue by ExzoTikStyle** [hashcat/hashcat#1746]
I started the benchmark, and at the end on -m 15700 the system was completely frozen. Other algorithms work fine.
When I first started writing CL_OUT_OF_RESOURCES.I applied the patch, and now everything hangs tight
GTX1080Ti

**Comment by jsteube** [comment]
This is something that can occur pretty fast when it comes to scrypt. Almost all resources are heavily used. 

Hashcat asks for free availability of resources on startup and the OpenCL runtime is responsible for the response. If the OpenCL runtime approves for enough resources to be available even if that is not the case, it's more like an OpenCL runtime problem, not a hashcat problem.

As a workaround try to use -D 1 (after installed intel opencl runtime for your CPU).

**Comment by ExzoTikStyle** [comment]
> Это то, что может произойти довольно быстро, когда дело доходит до scrypt. В основном используются все ресурсы.
> 
> Hashcat запрашивает бесплатную доступность ресурсов при запуске, а время выполнения OpenCL отвечает за ответ. Если среда OpenCL одобряет достаточное количество ресурсов для доступности, даже если это не так, это больше похоже на проблему времени выполнения OpenCL, а не на проблему hashcat.
> 
> В качестве обходного пути попробуйте использовать -D 1 (после установки времени выполнения Microsoft opencl для вашего процессора).

I tried to display the image on the monitors via the integrated gpu, and the same thing. The computer stops responding to any action.
