### ISSUE TITLE
-z doesn't seem to work with --stdout

### ISSUE THREAD

**Issue by hobbyhorse** [hashcat/hashcat#1750]
I ma trying to use the new brain feature with --stdout to generate candidates that have been pruned by the brain. This is very useful when chaining several programs together. It doesn't seem to work and i cannot see how to fix it.

**Comment by jsteube** [comment]
Great Idea! Added support with https://github.com/hashcat/hashcat/commit/d4dad3e1e304c34468eaab6661cde940793ceafb
