### ISSUE TITLE
make & Error obj/xxhash.NATIVE.STATIC.o

### ISSUE THREAD

**Issue by Jamyz** [hashcat/hashcat#1752]
Hi !
I can use make i have the error : 
`obj/xxhash.NATIVE.STATIC.o`
I forget any package ?

**Comment by warriar** [comment]
i also get an error while make:

include/brain.h:41:10: fatal error: 'xxhash.h' file not found

**Comment by warriar** [comment]
The key was reading the manual.... BUILD.md:

git submodule update --init

I however previously also cloned https://github.com/Cyan4973/xxHash in the deps folder - duno if that is necessary.

After doing the submodule update it works fine.

**Comment by phenotypic** [comment]
I was having the same issue on macOS 10.14.1 but 
```
git submodule update --init
```
solved it for me as @warriar suggested.

**Comment by PcBlackbelt** [comment]
git submodule update --init 

comes back as : fatal: not a git repository (or any of the parent directories): .git

please help ive installed and reinstalled whole system like 6 times now learning the ins and outs

**Comment by phenotypic** [comment]
@PcBlackbelt Did you run the command inside the "hashcat" repository (I.e. `cd ~/hashcat && git submodule update --init`)? Also, which operating system are you on?

**Comment by Jamyz** [comment]
Works fine !!

**Comment by PcBlackbelt** [comment]
yes ive cd hashcat5.0.0 && git submodule update --init
still says fatal error
im running kali what os do you recommend

ive been running apt-get update and apt-get upgrade... still nothing

**Comment by jsteube** [comment]
make sure to git clone the repository. do not use the source package from the site. git requires git to be able to initialize the submodules.

**Comment by jsteube** [comment]
continued on https://github.com/hashcat/hashcat/issues/1760
