### ISSUE TITLE
v5.0.0 seems to hang when given a zero length file as dictionary

### ISSUE THREAD

**Issue by blacktraffic** [hashcat/hashcat#1756]
[I know; "don't do that then" - triggered because automated website scrape returned no data]

Reproducible on Windows and UNIX:

c:\>hashcat64.exe -a0 -m0 md5testhash.txt zerolengthfile.txt -r rules\best64.rule
hashcat (v5.0.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
nvmlDeviceGetFanSpeed(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro M2000M, 1024/4096 MB allocatable, 5MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) HD Graphics 530, skipped.
* Device #3: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, skipped.

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 77

Applicable optimizers:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastically reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.

Watchdog: Temperature abort trigger set to 90c

Initialized device kernels and memory... [hangs]

**Comment by philsmd** [comment]
Thank you very much for this report

The problem seems to have to do with the new brain feature and in particular with the computation of the checksum of the dictionaries.

The effect of this bug is that we kind of loop within this code section forever:
https://github.com/hashcat/hashcat/blob/6b2c56118c1aaa976e380912808bd23a987afb33/src/brain.c#L543-L548

we would probably need at least a check like this:
```
if (feof (fd)) break;
```
