### ISSUE TITLE
known password not found when cracking my router using pmkid attack

### ISSUE THREAD

**Issue by PcBlackbelt** [hashcat/hashcat#1758]
im using
hashcat -m 16800 -a 0  hashtocracktvfp2 fakewordlist

my password is in the fake wordlist  but  all im getting is exhausted
Session..........: hashcat                       
Status...........: Exhausted
Hash.Type........: WPA-PMKID-PBKDF2
Hash.Target......: 8ea0f2915aa3f7a7d23aeca2001dae06*2c56dc54e238*5ccf7...747479
Time.Started.....: Sat Nov  3 20:19:50 2018 (0 secs)
Time.Estimated...: Sat Nov  3 20:19:50 2018 (0 secs)
Guess.Base.......: File (fakewordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#2.....:       82 H/s (0.30ms) @ Accel:64 Loops:16 Thr:256 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 7/7 (100.00%)
Rejected.........: 0/7 (0.00%)
Restore.Point....: 7/7 (100.00%)
Candidates.#2....: yackolvlfacko -> tacostandlevelfacko
HWMon.Dev.#2.....: Temp: 36c Fan: 41%

running kali linux

**Comment by jsteube** [comment]
Please add files to reproduce

**Comment by PcBlackbelt** [comment]
Will do tommorrow when i can thank you

**Comment by PcBlackbelt** [comment]
im at a complete loss its the right hash im sure and its the right password im sure


[hashtocrack69.txt](https://github.com/hashcat/hashcat/files/2546404/hashtocrack69.txt)
[fakewordlist.txt](https://github.com/hashcat/hashcat/files/2546405/fakewordlist.txt)

**Comment by PcBlackbelt** [comment]
im using 
pmkid
run airodump-ng wlan1mon

highlight ssid copy

cd hashcat
 echo "sside">filter.txt 
 run hcxdumptool -o hash -i wlan1mon --filterlist=filter.txt --filtermode=2 --enable_status 1
wait for pmkid
 ctrl-c
run hcxpcaptool -z hashtocrack hash
 cat hashtocrack2
run : hashcat -m 16800 -a 0 hashtocrack69.tx fakewordlist.txt

**Comment by jsteube** [comment]
That's what I expected. Your are using the GPU, not the CPU. Please make sure to specify -D 1 (note the capital D, not d).

**Comment by ZerBea** [comment]
Please add a the pcapng file. If possible with a complete handshake, too.

**Comment by ZerBea** [comment]
1) The password is not in your wordlist
2) Way too much aircrack stuff inside your commands
    Do not use aircrack tools and scripts in combination with hcxtools / hcxdumptool!

Log:
Session..........: hashcat
Status...........: Cracked
Hash.Type........: WPA-PMKID-PBKDF2
Hash.Target......: 8ea0f2915aa3f7a7d23aeca2001dae06*2c56dc54e238*5ccf7...747479
Time.Started.....: Mon Nov  5 10:29:01 2018 (5 mins, 35 secs)
Time.Estimated...: Mon Nov  5 10:34:36 2018 (0 secs)
Guess.Base.......: File (hashes.org-2017.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   405.9 kH/s (60.12ms) @ Accel:256 Loops:64 Thr:256 Vec:1
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 163595622/324023281 (50.49%)
Rejected.........: 27805030/163595622 (17.00%)
Restore.Point....: 161485043/324023281 (49.84%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: gjghgf75 -> grapepocke
Hardware.Mon.#1..: Temp: 83c Fan: 71% Util:100% Core:1708MHz Mem:5005MHz Bus:16

**Comment by jsteube** [comment]
I can crack it as well, but with a password which is not inside the wordlist provided by OP

**Comment by ZerBea** [comment]
@PcBlackbelt
To understand how the filterlist works, please read this:
https://hashcat.net/forum/thread-7929-post-42699.html#pid42699
