### ISSUE TITLE
feature: limit what interfaces/IPs the brain listens on

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1759]
It would be useful to have the brain only listen on specific IPs or interfaces.

Naively, for binding to an IP, perhaps `--brain-server` could be combined with `--brain-host`?

**Comment by jsteube** [comment]
Not sure what's the problem here, that's exactly how it works.

**Comment by roycewilliams** [comment]
Confirmed - I was reading too fast and misread the netstat output.
