### ISSUE TITLE
Git submodule update —init fatal error notfoun

### ISSUE THREAD

**Issue by PcBlackbelt** [hashcat/hashcat#1760]
So i currently am instally hashcat5.0.0 my make file when ran stops and say make & Error obj/xxhash.NATIVE.STATIC.o
I read on here that : git submodule update —init will fix it but that command comes back fatal error not found in reposity or sumthing close. I dont have it in front of me. 

What do i need to get git submodule update —init to work

**Comment by jsteube** [comment]
make sure to git clone the repository. do not use the source package from the site. git requires git to be able to initialize the submodules.

**Comment by PcBlackbelt** [comment]
awesome thank you.
