### ISSUE TITLE
Brain Server fails on Windows 10 version 1803

### ISSUE THREAD

**Issue by marcus-brutus** [hashcat/hashcat#1762]
Hashcat 5.0, Windows x64 (both Enterprise and Pro tested), version 1803

Running "--brain-server" (with additional arguments or by itself), fails with a 'socket: No error' error.  Happens both using cmd.exe and powershell.exe, and tested on both limited user and administrator level shells.  Have two separate systems with similar builds (same Windows version) that the issue has been verified on.  No trouble using the  "--brain-client" command on either system.

Current workaround for single system brain use is to use a WSL (Windows Subsystem for Linux) terminal for the brain-server (because it doesn't need access to the GPUs) and then just run the client directly on the host using cmd or ps.

Both features are flawless in Linux.  Also hats off to an absolutely amazing extension to an already awesome product.  This changes everything.

**Comment by philsmd** [comment]
Please make sure that you are using the latest version of hashcat (in this specific case the beta version, since we pushed some bug fixes).
see https://github.com/hashcat/hashcat/issues/1738

don't forget to close the issue if it's fixed. thx

**Comment by marcus-brutus** [comment]
Confirmed fixed in beta.  Thanks.

**Comment by gs135269** [comment]
Please help me to see if this output indicates a successful start of the hashcat brain server.
C:\hashcat-5.1.0>hashcat64.exe --brain-server
1543818302.353285 |   0.01s |   0 | Generated authentication password: 5247d54808013065
1543818302.452291 |   0.10s |   0 | Brain server started
1543818433.460784 | 131.00s |   0 | Brain server stopping

@marcus-brutus
