### ISSUE TITLE
use brain by default

### ISSUE THREAD

**Issue by ZeroChaos-** [hashcat/hashcat#1763]
Is the brain useful when only running on one machine?  if so, start brain listening on localhost (only!) by default (when built with brain support) to get the benefit.

just a thought.  hate to have a brain and not use it.

**Comment by s3inlc** [comment]
The brain is not useful for all algorithms. It depends on the speed in total you have on it (including if you distribute it) otherwise it would introduce a large bottleneck for faster algorithms.

**Comment by ZeroChaos-** [comment]
that's fair, but probably the request is still valid, just auto-enable the brain when it's a good idea.

**Comment by jsteube** [comment]
It requires an intense amount of system resources. One does not simply activate the brain :)
