### ISSUE TITLE
hcxdumptool grabbing pmkid from wrong access point with filter what am i doing wrong

### ISSUE THREAD

**Issue by PcBlackbelt** [hashcat/hashcat#1764]
heres what my my capture looks like and the first two captures are from my router the second two are not is this normal? anyway when i turn the pmkid into hash and try to crack it.. hashcat gives me password from wrong access point.
 hcxdumptool -o hashingit -i wlan0 --filterlist=tvfp2filer.txt --filtermode=2 --enable_status 1

start capturing (stop with ctrl+c)
INTERFACE:...............: wlan0
FILTERLIST...............: 1 entries
MAC CLIENT...............: fcc233dadfba
MAC ACCESS POINT.........: b025aa99a8f8 (incremented on every new client)
EAPOL TIMEOUT............: 150000
REPLAYCOUNT..............: 63156
ANONCE...................: 1f963f900448da8c1182e40ba288928877f40543759cd5e6425deb3548407868

[16:26:17 - 001] 009fa9073914 -> 5c93a20b3897 [FOUND AUTHORIZED HANDSHAKE, EAPOL TIMEOUT 2516]
[16:40:15 - 001] 009fa9073914 -> ccfb65942f7e [FOUND AUTHORIZED HANDSHAKE, EAPOL TIMEOUT 2651]
[17:19:39 - 001] b44bd20fd6ba -> 5c8fe0bf2984 [EAPOL 4/4 - M4 RETRY ATTACK]
[17:39:53 - 011] 2c56dc54e238 -> 5ccf7f48a404 [FOUND PMKID]
INFO: cha=11, rx=145350, rx(dropped)=3145, tx=2453, powned=3, err=0^C
terminated...
the filter is working somewhat atleast cuz i tried without filter and got slammed with tons more

**Comment by PcBlackbelt** [comment]
could it be my wireless card the awus036nha?

**Comment by RealEnder** [comment]
Please post an issue on this here: https://github.com/ZerBea/hcxdumptool/issues

**Comment by jsteube** [comment]
Wrong project

**Comment by PcBlackbelt** [comment]
my bad sorry for the inconvience
