### ISSUE TITLE
Possible bug:  One GPU stop being utilized and idles (and not at the end of an attack)

### ISSUE THREAD

**Issue by mastercracker1** [hashcat/hashcat#1765]
[Brain GPU stop.txt](https://github.com/hashcat/hashcat/files/2552932/Brain.GPU.stop.txt)

First, I want to report that I had a previous issue where the brain completely hanged.  Both GPUs were idling and nothing was happening at the brain level either.  I restarted the brain and continued my attack.  I have included the brain's output to show what's happening.  If I understand correctly the brain's output (more documentation would be helpful on that), there is a number assigned to each GPU (0 and 1 in my case).  Everything goes well for a good while and around line 114, it stops interacting with GPU 0.  This is the "strongest" GPU of the 2 so it's not fun to see it idling.  Let me know if there is other content that you need to understand what's going on.  That was under Windows 7 64 bit with NVidia GPUs and the server is run locally (localhost).

**Comment by jsteube** [comment]
I'm not sure what's the problem here. You ran into the typical bottleneck caused be feature type 1. Are you sure that you read the entire documentation carefully? It's all here:

https://hashcat.net/forum/thread-7903.html

For fast attacks like yours you probably want to stick to --brain-client-features 2

**Comment by mastercracker1** [comment]
Yes it's a fast algo but I am in the desired case you described with > 150k salts.  Maybe I don't understand some concept enough.  I don't see why if I have 4 days worth of cracking, it cannot dispatch to both GPUs only to the weaker one.   For the "more documentation" I meant about the brain output: 
1541395014.654000 | 107.92s |   0 | C |     0.04 ms | Attacks: 14
1541395125.962000 | 111.31s |   1 | C |   112.98 ms | Attacks: 1
1541395233.931000 | 107.97s |   0 | C | 219260.90 ms | Hashes: 980589
1541395233.932000 |   0.00s |   0 | R |     0.64 ms | Offset: 468746240, Length: 983040, Overlap: 0
1541395236.913000 |   2.98s |   1 | C | 104533.06 ms | Hashes: 424940
1541395236.914000 |   0.00s |   1 | R |     0.36 ms | Offset: 469729280, Length: 425984, Overlap: 0
1541395305.641000 |  68.73s |  -1 | Wrote 2346884408 bytes from session 0x77687e51 in 68689.24 ms

What are the code 0, 1, -1.  What does C, R, L means?  What's the offset, the overlap?  The hashes number don't seem to correspond to the amount in the session.
