### ISSUE TITLE
Hashcat v5.0 crashing windows

### ISSUE THREAD

**Issue by wormHole3001** [hashcat/hashcat#1767]
Just updated AMD drivers and ran `hashcat64.exe -b` this causes windows 10 to crash giving the following error during the blue crash screen. `THREAD_STUCK_IN_DEVICE_DRIVER`

**Comment by jsteube** [comment]
Which driver exactly is it?

**Comment by jsteube** [comment]
I tried to reproduce this locally using the latest AMD adrenalin edition drivers (both branches, that is 18.11.1-nov8 and 18.9.3-oct5). I tried with stable 5.0.0 as well as with latest 5.1.0 beta. In all combinations, it always worked perfect. Maybe you need to reinstall the drivers with a clean install.
