### ISSUE TITLE
iSCSI CHAP Linux target framework (tgt)

### ISSUE THREAD

**Issue by coelner** [hashcat/hashcat#1773]
I tried under Linux iSCSI but I can not break the hash. I used this project: http://stgt.sourceforge.net/, therefore you can find the source in this repo : https://github.com/fujita/tgt.

1. the challenge is much longer than expected (https://github.com/fujita/tgt/blob/master/usr/iscsi/chap.c#L367)
2. which format does the hash needs?  CHAP_C : CHAP_R : CHAP_N ?

```
ID#5
InitiatorName=iqn.1993-08.org.debian:01:36337c672699
InitiatorAlias=iscsi0
TargetName=iqn.2017-09.local.snip.fqdn.iscsi1:1.1.disk
SessionType=Normal
AuthMethod=CHAP,None

ID#8
TargetPortalGroupTag=1
AuthMethod=CHAP

ID#11
CHAP_A=5

ID#13
CHAP_A=5
CHAP_I=2
CHAP_C=0xb73158a35a255d051758e95ed4abb2cdc69bb454110e827441213ddc8770e93ea141e1fc673e017e97eadc6b

ID#16
CHAP_N=user1
CHAP_R=0x7f3d71b4c0c6569d2fa26f4c14ac3cf0
```

```
C:\HashCracking\hashcat-4.2.1>hashcat64.exe -m 4800 --example-hashes
MODE: 4800
TYPE: iSCSI CHAP authentication, MD5(CHAP)
HASH: aa4aaa1d52319525023c06a4873f4c51:35343534373533343633383832343736:dc
PASS: hashcat
```

**Comment by philsmd** [comment]
what is the password for this example hash?

The format should be CHAP_R:CHAP_C:CHAP_I

7f3d71b4c0c6569d2fa26f4c14ac3cf0:b73158a35a255d051758e95ed4abb2cdc69bb454110e827441213ddc8770e93ea141e1fc673e017e97eadc6b:02

hashcat currently expects exactly 16 bytes for the challenge (note CHAP_C means chap challenge and CHAP_R means chap response, while CHAP_I is the chap_id - an incrementing counter -)

this means that the long challenge that you tried is not currently supported (length: 44 bytes, 88 hexadecimal characters)

**Comment by coelner** [comment]
The password should be `U$er1`, but I am not sure.There could be a problem with this software that leads to the password `U` in real life. That was the reason why I sniffed this at all.

 I can generate a new handshake if needed.

Maybe we should specify that hashcat only support iSCSI from the LIO in the linux kernel. the tgt framework is then not supported. Otherwise this is a request for a new algorithm

**Comment by philsmd** [comment]
yeah, the password seems to work:
```
(echo -en "\x02"; echo -n 'U$er1'; echo b73158a35a255d051758e95ed4abb2cdc69bb454110e827441213ddc8770e93ea141e1fc673e017e97eadc6b | xxd -r -p) | md5sum
7f3d71b4c0c6569d2fa26f4c14ac3cf0
```

the problem, as we already suspected, is "just" the longer challenge length (44 vs 16 bytes).
In the meantime, you coud probably work around this limit by just using -m 10 = md5 ($pass . $salt)

i.e. hashcat -m 10 -a 0 -j '^\x02' --hex-salt hash.txt dict.txt

where hash.txt contains the hash:
7f3d71b4c0c6569d2fa26f4c14ac3cf0:b73158a35a255d051758e95ed4abb2cdc69bb454110e827441213ddc8770e93ea141e1fc673e017e97eadc6b

**Comment by coelner** [comment]
I tried this `hashcat -m 10 -a 0 -j '^\x02' --hex-salt hash.txt dict.txt` but so far it does not work. I'm not sure, but I tried the option `--stdout -o file.hex` in combination with `-j '^\x02'` . This seems not be working at all. Even adding a simple char does not work. 
Did I miss something?

**Comment by philsmd** [comment]
it's important that you know how your operating system does interpret the command line arguments. on windows for instance you might need to use "^^\x02" or something like this (because of shell/dos escape rules).

anyway, you can always just put the rules into a rule file e.g. myrule.rule with the file content
```
^\x02
```
and use -r myrule.rule instead of -j ^\x02 
btw: you can't remove the ^, that's the actual rule function ! (\x02 is not a rule at all).

I think this all is quite irrelevant to this issue and very basic usage of hashcat and/or general use/understanding of your shell/operating system.

**Comment by coelner** [comment]
Sorry, I missed the ^ in the comment above. 
Under windows you need this `-j "^\x02"`or `^^^\x02`.
