### ISSUE TITLE
Hashcat v5 Doesn't Use CWD for PID file

### ISSUE THREAD

**Issue by moloch--** [hashcat/hashcat#1778]
When executing from a read-only directory or filesystem Hashcat v5 attempts to write the PID file into the same directory as the binary instead of the current working directory.

Linux v5.0.0, with the CWD set to `/tmp/` example command

### Command 

`/var/task/hashcat/hashcat64.bin --potfile-disable --keyspace -a 3 '?a?a?a?a?a?a'`

### Output
```
/var/task/hashcat/keyspace.pid: Read-only file system

/var/task/hashcat: Read-only file system
```

Copying the files into a writable directory (like `/tmp`) resolves the issue.

**Comment by jsteube** [comment]
That's the wanted behavior. Note that if you use the install target without copying/moving the binary after install, then hashcat assume to be installed system-wide and will write files to $HOME/.hashcat
