### ISSUE TITLE
Crashes on Initializing device kernels and memory

### ISSUE THREAD

**Issue by Jeffmagma** [hashcat/hashcat#1779]
The command I run is `.\hashcat64.exe -m 2500 -a 3 ../capture.hccapx ?d?d?d?d?d?d?d?d` and the output:
```
hashcat (v5.0.0) starting...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 3264/4096 MB allocatable, 36MCU

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: Ellesmere, 3264/4096 MB allocatable, 36MCU

Hashes: 7 digests; 4 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Temperature abort trigger set to 90c

Initializing device kernels and memory...
```
When it gets to `Initializing device kernels and memory...`, I get `hashcat64.exe has stopped working. Windows is collecting more information about the problem...`  
Also, I only have one GPU (RX 580), so I'm not sure why it's appearing twice  
The exact same command has worked for the computer before, except it caused the entire computer to crash, so I tried waiting for another hashcat update to retry it  
Also, I have the right driver versions: 
> AMD GPUs on Windows require "AMD Radeon Software Crimson Edition" (15.12 or later)

I have 18.11.1  
And there is no specification for AMD CPUs (I have a Ryzen 1700)

**Comment by jsteube** [comment]
I just tested 18.11.1 today and works fine. Your GPU is not too old, so I guess this is just a driver installation problem. Reinstall it and make sure the old driver was uninstalled cleanly. Check this: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

For CPU, you have to use the Intel OpenCL runtime, it's better than the AMD one (even for CPU).
