### ISSUE TITLE
No hashes loaded (example_hashes)

### ISSUE THREAD

**Issue by vecera-vojtech** [hashcat/hashcat#1782]
Hi,
I've been doing some verification of example hashes from https://hashcat.net/wiki/doku.php?id=example_hashes on hashcat version 3.6.0, 4.2.1 and 5.0.0. Most of the hashes pass except for 2. Hashcats 4 and 5 exited with **No hashes loaded" for hash-modes 12, 10700. Both hashes passed when I've tried to load when with hashcat 3.6.0 though.

Can you please double check it? It seems kinda weird to me that version 3.6.0 handles it and I wonder whether the issues is in the example_hash + hashcat 3 or in the hashcat 4+.

Thanks

**Comment by philsmd** [comment]
Thanks for report.

I can confirm -m 10700 problems but -m 12 should be fixed with 4d457ca141103a15cc8939089f5bff55a407d254
please try beta from https://hashcat.net/beta/ with -m 12 to confirm

**Comment by vecera-vojtech** [comment]
I can confirm that -m 12 works on beta.

**Comment by philsmd** [comment]
good, we should still investigate the problem with -m 10700. it probably is a minor issue with the new parser/tokenizer code (limits too strict/wrong ?)

**Comment by vecera-vojtech** [comment]
I've had also Hashcat 4.2.1 crashing on Windows when using extracted hash from a WinZip file via zip2john.sh. But I have tested it on the version 5.0.0 and on the beta version and it seems to work there too. 
Thanks for that fix.

**Comment by philsmd** [comment]
I've tracked this problem back a little bit and noticed that this commit introduced the problem:
cd552eb54dda8ab4c9729664b3aefcf4b0887b4a

this means that the conversion to the tokenizer interface has a bug for -m 10700
I guess it should be easy to fix now with this knowledge and by making the tokenizer call work like it did before we introduced our new tokenizer functions.

**Comment by vecera-vojtech** [comment]
Good job with tracking it down. And thanks for the effort, I bet it wasn't an easy bug hunting.

**Comment by jsteube** [comment]
The -m 12 seems to be fixed.
The -m 10700 hash on the wiki page has been updated.
Thanks for reporting!
