### ISSUE TITLE
brain: duplicate work is not rejected

### ISSUE THREAD

**Issue by corcuma** [hashcat/hashcat#1786]
Maybe I got something wrong, but I'm wondering about the following behavior:

I have a wordlist #1 containing a single candidate
I have a second wordlist #2, containing the candidate of wordlist #1 and another candidate (so wordlist #2 is a superset of wordlist #1)

I start hashcat with brain client mode on wordlist #1. In the results, I see that the one and only candidate has been processed.
Afterwards, I start hashcat with brain client mode on wordlist #2.
I would expect that 1 of 2 candidates would be rejected because  it has already been processed by wordlist #1 but surprisingly this does not happen, both candidates are processed with duplicate work involved.

**Comment by jsteube** [comment]
It's important to know which version exactly you are using. In case of hashcat 5.1.0 from github master or from https://hashcat.net/beta/ then you are using the new behavior which sets the --brain-client-features to 2 (from 3) and therefore does not enable deep inspection required as you are describing. In that case, simply add --brain-client-features 3 to your commandline and it should work.

If you are using hashcat 5.0.0 release version, then it should do exactly as you said. If that is not that case, please retry with latest hashcat master or beta and report back. Don't forget to set --brain-client-features 3 in that case.

If this does not help you, please provide all files we need to reproduce locally.

**Comment by corcuma** [comment]
Thank you for your fast response.
I'm using the beta, and it really looks like that enabling feature mode 3 fixed the issue.

Thanks!
