### ISSUE TITLE
GPU core clock, memory clock not detected

### ISSUE THREAD

**Issue by vecera-vojtech** [hashcat/hashcat#1787]
Hi,

I've noticed that Hashcat 5.0.0 is **not** able to read core clock and memory clock of my GPU while versions 4.2.1 and 3.6.0 can.
I'm using Windows 10 64-bit with Adrenalin 18.11.1, my GPU is ASUS Radeon ROG STRIX RX Vega 64 O8G. Have you changed anything regarding this in version 5? 

I've read you don't/didn't have the tester with Win10 + AMD card on the forum so I'm willing to help with debugging if you point what to look at or what data you need or so. I'm just asking before I go blindly hunting for the changes in code or something similar.

Regards

```
$ ./hashcat64.exe --benchmark --machine-readable
# hashcat (v3.6.0)
1:0:1385:945:98.79:21670712450
1:100:1412:945:59.05:9002801636
1:1400:1341:945:76.31:3508940167
1:1700:1342:945:77.94:859266181

$ ./hashcat64.exe --benchmark --machine-readable
# version: v4.2.1
# option: --optimized-kernel-enable
1:0:1235:945:48.82:21308427659
1:100:1179:945:60.76:8631909763
1:1400:1155:945:76.81:3459833982
1:1700:1226:945:82.31:807913668

$ ./hashcat64.exe --benchmark --machine-readable
# version: v5.0.0
# option: --optimized-kernel-enable
1:0:-1:-1:97.98:21634212476
1:100:-1:-1:60.47:8658465992
1:1400:-1:-1:76.56:3486756672
1:1700:-1:-1:83.05:794953022

```

**Comment by jsteube** [comment]
Should be fixed with latest commit. You can use the beta from https://hashcat.net/beta/ if you want to try. Thanks for reporting!

**Comment by vecera-vojtech** [comment]
Thanks, it works with the beta.
