### ISSUE TITLE
Hashcat 'limited-coverage-experimental' registered more than once!

### ISSUE THREAD

**Issue by danisoltesz** [hashcat/hashcat#1790]
I installed hashcat and tried to bruteforce my own network, but when I executed the following command in terminal, it came up with this error:
_HASH_FILE=filename.hccapx POT_FILE=filename2.pot HASH_TYPE=2500 ./naive-hashcat.sh_

**: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options**

I've installed a mesa-opencl-icd driver, but it didn't solve the problem. I hope somebody has a solution.

**Comment by roycewilliams** [comment]
You're using [naive-hashcat](https://github.com/brannondorsey/naive-hashcat), which is not managed by the hashcat project. Please either provide the hashcat commandline generated by naive-hashcat, or else start your inquiry with that project.

Please also note that the only driver/OpenCL combinations officially supported by hashcat are the ones listed at the top of hashcat.net. Analyzing such problems is better conducted on [the hashcat forum](https://hashcat.net/forum/).

**Comment by jsteube** [comment]
Also uninstall MESA, looks like a MESA JiT compiler error. Not a hashcat error.

**Comment by danisoltesz** [comment]
Thank you for your help, I will try the things you wrote above.
