### ISSUE TITLE
Add Instagram Hash

### ISSUE THREAD

**Issue by sinnlosername** [hashcat/hashcat#1792]
Please support the instagram hashing algorithm

**Comment by philsmd** [comment]
what is this issue all about? I have no clue what you mean by instagram hashing in the context of hashcat. Please give the algorithm details or link to source code and follow the instructions here:
https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this
