### ISSUE TITLE
feature: --no-keep-guessing

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#1795]
As noted in [this forum thread](https://hashcat.net/forum/thread-6071.html), for some formats (like some Office hashes) that automatically keep guessing, it might be useful to have a `--no-keep-guessing` to exit on the first hit.

**Comment by wang614340595** [comment]
it might be useful to have a --no-keep-guessing to exit on the first hit.

**Comment by jsteube** [comment]
The problem with this is, if a user sets both --keep-guessing and --no-keep-guessing both at the same time, how should hashcat react. Additionally, having both options in --help menu is confusing, too.

For that reason, I've decided to not add this option. This will affect only 4 algorithms: 9720, 9820, 14900 and 18100.

If you really need to stop this behavior, you can change the setting easily with latest modularized hashcat version. Go to src/modules/module_09720.c and remove the OPTS_TYPE_PT_NEVERCRACK option or replace it with 0. Then run make to recompile.

**Comment by roycewilliams** [comment]
Since hashcat's behavior varies depending on hash type (as it should), the user should IMO be able to control this behavior from the command line, or at least for hashcat to help with common user confusion.

One way to resolve this would be for --keep-guessing to take an optional parameter, so you could say "--keep-guessing 0" to turn it off.

This could make the help something like this:

`     --keep-guessing            |      | Keep guessing after crack (some algos only); 0 = off |`

Another way to help would be for the logic something like this:

* If user asks for --keep-guessing but hash type is already NEVERCRACK, reject the commandline.
* If user asks for --no-keep-guessing (or 0, whatever is chosen), but hash type is not NEVERCRACK, reject the commandline.
* If user asks for --no-keep-guessing (or whatever), and --keep-guessing, reject the commandline.

**Comment by jsteube** [comment]
My main concern is about how to deal with the confusion it creates having both options in the --help menu. It doesn't matter if there's a parameter available to the --keep-guessing option. The confusion is the same.

An alternative would be to remove the automatic activation of keep-guessing in the modes 9720, 9820, 14900 and 18100. For them, we could instead print a message with a suggestion to use the option --keep-guessing on the command line.

**Comment by roycewilliams** [comment]
Hey, that seems like a good idea!

**Comment by jsteube** [comment]
Done https://github.com/hashcat/hashcat/commit/111889d3fc63554382b99fe3893f63e58ba96b83
