### ISSUE TITLE
Cluster with 2+ servers for brute one hash?

### ISSUE THREAD

**Issue by hyrris** [hashcat/hashcat#1811]
Subj.
Have 1 difficult hash, some servers with GPUs, how to do it? 

Thanks.

**Comment by philsmd** [comment]
Hey.
Please search for questions like this on the hashcat forum/wiki/faq etc. These questions have been answered dozens of times and github issues are not really the right place to ask general questions  like this (which have been answered already couple of times) that have nothing to do with bugs/problems in the hashcat software.

note: you could use something like hashtopolis to distribute work across many cracking machines.

btw: do not forget to close this issue

Thx
