### ISSUE TITLE
Hashcat pauses after starting

### ISSUE THREAD

**Issue by ptrac3** [hashcat/hashcat#1818]
Hello all, I hope this is not an already posted issue.
The problem I am encountering is the following:

- When running hashcat64.exe the only output I get is the following:
 `hashcat (v5.1.0) starting in benchmark mode...
Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.`
- When running example500.cmd after hashcat is started it seems to go into pause (please refer to the screenshots below)

System Details:

- Windows 10 Home (Version 1803, OS Build 17134,471)
- GTX 1070 MAX Q with GeForce driver 417.35 (I have upgrade the driver because I also had problems with the previous)

Steps to reproduce:

- Tried with Hashcat 3.00, 4.2..1, 5.1.0 (binaries)

- I have executed hashcat/scripts by using the following command:
`cd C:\hashcat-5.1.0, 3.00, 4.2.1`  and then executed the program by invoking either hashcat64.exe, hashcat32.exe or example500.cmd

Thanks for any help.

![hashcat](https://user-images.githubusercontent.com/1253315/49895093-81495500-fe47-11e8-8bb4-e4a5cbcf4677.PNG)

**Comment by philsmd** [comment]
This is a driver installation problem, please follow these steps: https://hashcat.net/faq/wrongdriver

(also download a fresh copy of hashcat from https://hashcat.net/hashcat and install the recommended drivers mentioned there)

Please don't forget to close this issue if fixed

**Comment by ptrac3** [comment]
@philsmd Thanks for your help. Unfortunately I have already tried the latest hashcat version and I am running the recommended Nvidia drivers so I will try to reinstall them.
@jsteube I see the issue was closed. Did I miss anything from the official documentation or was it a known issue?
Thanks.
