### ISSUE TITLE
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by JacobTDC** [hashcat/hashcat#1819]
So, this seems to be a pretty common error from what I can find, but not many of the errors I find are in such an... interesting environment.

My platform is ArchLinux/TermuxArch running on Android (aarch64) in Termux.
Here is the error:
```
[root19:54hashcat-5.1.0]$ ./hashcat -b
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

Started: Wed Dec 12 19:54:34 2018
Stopped: Wed Dec 12 19:54:34 2018
```

screenfetch:
```
                   -`
                  .o+`                 root@localhost
                 `ooo/                 OS: Arch Linux
                `+oooo:                Kernel: aarch64 Linux 3.10.84-perf
               `+oooooo:               Uptime: 14h 24m
               -+oooooo+:              Packages: 436
             `/:-:++oooo+:             Shell: bash 4.4.23
            `/++++/+++++++:            CPU: 8x Qualcomm Technologies, Inc MSM8952
           `/++++++++++++++:           GPU: mdssfb_80000 mdssfb_a0000
          `/+++ooooooooooooo/`         RAM: 1533MiB / 2808MiB
         ./ooosssso++osssssso+`
        .oossssso-````/ossssss+`
       -osssssso.      :ssssssso.
      :osssssss/        osssso+++.
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

I've been looking all night to try and find something that works, and I have yet to end up successful.
How do I make this work? XD

<hr>

**NOTE:** Before you tell me how much of an idiot I am for trying to run hashcat on Android, I realize that this is not the best setup, but it's the best I've got.

**Comment by magnumripper** [comment]
This is more of an Android or ArchLinux issue that a hashcat one. It's better discussed on the [hashcat forum](https://hashcat.net/forum/) but a good start would be to forget about hashcat for now and simply run [clinfo](https://github.com/Oblomov/clinfo). Once **that** works (or does it now?), you can return to hashcat.

**Comment by JacobTDC** [comment]
Note: I included a screenfetch.

**Comment by JacobTDC** [comment]
@magnumripper what should `clinfo` return? I get:
```
Number of platforms                               0
```

I'm new to all this hashcat stuff. I just thought I'd be fun to try.

**Comment by jsteube** [comment]
OpenCL runtime is not working or not existing. Either way, not a hashcat issue.

**Comment by JacobTDC** [comment]
K. *sigh* well, so much for that...

**Comment by magnumripper** [comment]
The fact clinfo doesn't list your GPU at all shows that something is wrong with the OpenCL driver/runtime installation. There's no point in trying hashcat until this is resolved.

**Comment by sayoojsamuel** [comment]
Got a temporary fix with `pacman -S beignet`.

**Comment by binarytrails** [comment]
Hello,

Fellow Archer here, I found a way to fix the broken hashcat install as you can see:
```
    $ hashcat -b
    hashcat (...) starting in benchmark mode...

    clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

    ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.
    You are probably missing the OpenCL or CUDA runtime installation.

    $ pacman -S clinfo
    $ clinfo 
    Number of platforms                               0
```
One way to fix it is to install pocl (Portable OpenCL is an open-source implementation of OpenCL):
```
    $ pacman -S pocl
    $ clinfo
    Number of platforms                               1
      Platform Name                                   Portable Computing Language
      Platform Vendor                                 The pocl project
      ...

    $ hashcat -b
    hashcat (...) starting in benchmark mode...

    OpenCL API (...) - Platform #1 [The pocl project]
    =========================================================================================================================
    * Device #1: pthread-Intel(R) ...

    Benchmark relevant options:
    ===========================
    * --optimized-kernel-enable

    Hashmode: 0 - MD5

    Speed.#1.........:   ...
    ...
```
Happy cracking! ( ͡° ͜ʖ ͡°)
