### ISSUE TITLE
Kali linux hashcat runtime error: "/build/pocl-rUy81a/pocl-1.1/lib/CL/devices/common.c:375: pocl_mem_objs_cleanup: Assertion `r == 0' failed"

### ISSUE THREAD

**Issue by nateg123** [hashcat/hashcat#1824]
Hi, sorry if this is not the correct place to post this.  So...
Hashcat was running fine.  I pressed 'q' to quit in the middle of its run.  When I tried to rerun the command I got this error:
"hashcat: /build/pocl-rUy81a/pocl-1.1/lib/CL/devices/common.c:375: pocl_mem_objs_cleanup: Assertion `r == 0' failed."

I tried reinstalling all of hashcat's dependencies, reinstalling hashcat, and then rebooting.  I am still getting the error and cannot think of what else to do.  Here is the command and the total output:

hashcat -m 16800 galleriaHC.16800 -a 0 --kernel-accel=1 -w 4 --force 'rockyouplus.txt'
hashcat (v5.0.0) starting...

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz, 8192/29821 MB allocatable, 36MCU

Hashes: 4 digests; 4 unique digests, 4 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

* Device #1: build_opts '-cl-std=CL1.2 -I OpenCL -I /usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=16 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=16800 -D _unroll'
Dictionary cache built:
* Filename..: rockyouplus.txt
* Passwords.: 14353785
* Bytes.....: 140698182
* Keyspace..: 14353736
* Runtime...: 2 secs

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => hashcat: /build/pocl-rUy81a/pocl-1.1/lib/CL/devices/common.c:375: pocl_mem_objs_cleanup: Assertion `(event->mem_objs[i])->pocl_refcount > 0' failed.
Aborted

**Comment by jsteube** [comment]
Not a hashcat error (it's a POCL error).
