### ISSUE TITLE
Question: Slower performance on new Nvidia drivers

### ISSUE THREAD

**Issue by alexeynikitin** [hashcat/hashcat#1825]
Hello!
Am I the only one who noticed, that with new nvidia drivers 417.22, 417.35 (versions i have tried) hashcat performs less hashrate than with older driver, 399.24 for example?

Take a look:
`hashcat64.exe -b -m 2500 -w 4`

399.24 gives
> hashcat (v5.1.0) starting in benchmark mode...
> OpenCL Platform #1: NVIDIA Corporation
> Device #1: GeForce GTX 1080 Ti, 2816/11264 MB allocatable, 28MCU
> Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)
> Speed.#1.........:   624.6 kH/s ......

And 417.22, 417.35 gives

> hashcat (v5.1.0) starting in benchmark mode...
> OpenCL Platform #1: NVIDIA Corporation
> Device #1: GeForce GTX 1080 Ti, 2816/11264 MB allocatable, 28MCU
> Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)
> Speed.#1.........:   575.8 kH/s ......

The difference is significant.
Is this is a proof of nvidia conspiracy or it may have been related to hashcat somehow?
Thanks for help.

**Comment by jsteube** [comment]
You maybe want to make sure your power management settings are in sync. It's possible that the default settings are changed between the different driver versions. For example, I use this script:

```
export DISPLAY=:0

nvidia-smi -pm 1
nvidia-smi -acp 0

nvidia-smi -pl 300

nvidia-settings -a GPUPowerMizerMode=1 -a GPUFanControlState=1 -a GPUTargetFanSpeed=100 -a GPULogoBrightness=0
```

In case you're on windows, you can use MSI AfterBurner to verify the power limits are in sync

**Comment by jsteube** [comment]
I tried to verify on my local development system. This linux box only has a GTX750Ti installed and my other development box with the 1080 is currently unavailable. However I cannot see any difference for the GTX750Ti at last. If anything I'd say that there was some performance increase from 396.x -> 410.x.

Tested with hashcat v5.1.0: rm -rf kernels; ./hashcat64.bin -b -m 2500 -u 32 -n 128 -T 1024 --opencl-vector-width 1 --force 

```
384.130: 62381 H/s	
390.87:  62414 H/s
396.54:  62433 H/s      
410.93:  63651 H/s
415.25:  63532 H/s
```

Feel free to reopen if you have new insights.

**Comment by alexeynikitin** [comment]
@jsteube 
Hello again!

I applied you SMI-commands and tested one more time. Under Windows it is stiil as I said! NVidia driver 
399.24 gives more than 600 KH/s (600-620) and i also tested the latest 417.71, still got 570 KH/s at max!
Have you tested it under Windows? Please, can anyone run theese tests under Windows to confirm the issue?
