### ISSUE TITLE
Windows/Radeon 580x : failing self-tests with latest driver

### ISSUE THREAD

**Issue by bol-van** [hashcat/hashcat#1828]
It all worked fine with september 2018 driver.
Now updated to the latest : 06.12.2018  25.20.15002.58
And :

* Device #1: ATTENTION! OpenCL kernel self-test failed.
Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver
Aborting session due to kernel self-test failure.
You can use --self-test-disable to override this, but do not report related errors.

With --self-test-disable it still works and successfully finds at least WPA2 hashes
Yes, I deleted "kernels" subdir, event unpacked fresh zip, with no change

**Comment by vecera-vojtech** [comment]
I suppose it is the same as https://github.com/hashcat/hashcat/issues/1789 therefore wrong driver and not a hashcat's bug. But lets see what devs say.

**Comment by bol-van** [comment]
zcash and etherium miners work fine

**Comment by jsteube** [comment]
Which hash-mode is this?

**Comment by bol-van** [comment]
2500  WPA-EAPOL-PBKDF2

**Comment by jsteube** [comment]
I can reproduce this, but it's a driver problem, not a hashcat problem. IOW, we can't do anything about it. 

You can try other modes in hashcat and you will see hashcat will work well. This explains why zcash and etherium work well. They do not use the same algorithm which WPA is using.

**Comment by zephyrprime** [comment]
This still happens with the 3/14/2019 driver and with the February driver before this.  It seems like every newer driver is failing?
