### ISSUE TITLE
Feature Request - New Algo - codeMKII

### ISSUE THREAD

**Issue by Sid-Sun** [hashcat/hashcat#1846]
Hello,

I'd like to request support for codeMKII, a new algo; source here: https://github.com/Sid-Sun/codeMKII

**Comment by philsmd** [comment]
hmm... it's strange that it seems that this is your project/repository. That's kind of "fishy" (this is no accusation, but it's strange/uncommon that the algorithm developer wants their algorithm to be easily crackable etc).
Where is this algorithm being used? Is this really a common hashing algorithm used in the wild for which the addition to hashcat would benefit a lot of hashcat users ? I have never heard of this algorithm in the past.
Is this even considered a (secure?) password hashing algorithm (I didn't look at the code but already the project description "encode ya message!" doesn't really seem to indicate that this codeMKII algo is used to hash and store passwords).

Could you please clarify why this should be added and where this algorithm is used ?

Further details are also needed, see: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

Thank you very much

**Comment by jsteube** [comment]
No response from OP, feel free to reopen
