### ISSUE TITLE
MacOS 10.14.2 - 2501 - WPA-EAPOL-PMK - ATTENTION! OpenCL kernel self-test failed.

### ISSUE THREAD

**Issue by emwinkler** [hashcat/hashcat#1847]
I am getting a "OpenCL kernel self-test failed." error with Hashmode 2501 on MacOS 10.14.2.  The benchmark is comparable to the same hardware running on Ubuntu, 89855.8 kH/s.

./hashcat -b -m 2501 -d 3
hashcat (v5.1.0-42-g471a8ccc) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 2044/8176 MB allocatable, 64MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2501 - WPA-EAPOL-PMK (Iterations: 1)

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Speed.#3.........: 84094.6 kH/s (0.04ms) @ Accel:128 Loops:1 Thr:256 Vec:1

Started: Thu Jan  3 15:26:10 2019
Stopped: Thu Jan  3 15:26:12 2019

**Comment by philsmd** [comment]
sound like a driver issue.

does -D 1 work for you ?

do you have problems with other hash types too?

**Comment by emwinkler** [comment]
-D 1 does not work.  -D 2 works with no driver warning.

-D 1 Output:
./hashcat -b -m 2501 -d 1
hashcat (v5.1.0-42-g471a8ccc) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

No devices found/left.

Started: Mon Jan  7 10:16:12 2019
Stopped: Mon Jan  7 10:16:12 2019

-D2 Output:
/hashcat -b -m 2501 -d 2
hashcat (v5.1.0-42-g471a8ccc) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, 384/1536 MB allocatable, 40MCU
* Device #3: AMD Radeon RX Vega 64 Compute Engine, skipped.

Benchmark relevant options:
===========================
* --opencl-devices=2
* --optimized-kernel-enable

Hashmode: 2501 - WPA-EAPOL-PMK (Iterations: 1)

Speed.#2.........:  5293.0 kH/s (0.22ms) @ Accel:32 Loops:1 Thr:512 Vec:1

Started: Mon Jan  7 10:17:21 2019
Stopped: Mon Jan  7 10:17:24 2019

**Comment by philsmd** [comment]
-d is not the same as -D

you can't say that something didn't work, but at the same time you show that you tried something completely different

again:
--opencl-devices (or short -d) is not the same as --opencl-device-types (or short -D)

but it doesn't really matter actually in this very specific case, because you just found out that the problem only happens with a very specific device (not device type !) and only together with a very specific driver... therefore I would classify this problem as a driver bug (of course there could be workarounds of any bugs, but you either need to convince the driver developers or try messing around with the OpenCL kernel code and see if any code change could prevent this problem to occur with this specific faulty driver version)

**Comment by emwinkler** [comment]
Sorry for the confusion.  The -D 1 option does work fine, so it is a driver issue.  As Apple is no longer supporting OpenCL with their move to Metal, I don't suspect to get the driver bug fixed.  I can run hashcat on Ubuntu linux for now.  Thanks for your help.

**Comment by philsmd** [comment]
should/could we close this issue?

**Comment by emwinkler** [comment]
yes, this issue can be closed.  I confirm it is a driver bug.

**Comment by jsteube** [comment]
Please retry with latest version from github master. Make sure to run "make clean" before recompiling.

**Comment by emwinkler** [comment]
I did a clean "git clone" of the latest source.  Still getting the error with the RX Vega64, but faster benchmark.

./hashcat -b -m 2501 -d 3
hashcat (v5.1.0-656-g8d6a69b2) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/Users/emwinkler/Desktop/hashcat/OpenCL/m02501-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 2044/8176 MB allocatable, 64MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2501 - WPA-EAPOL-PMK (Iterations: 0)

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Speed.#3.........:   174.3 MH/s (0.00ms) @ Accel:512 Loops:1024 Thr:64 Vec:1

Started: Mon Mar  4 08:28:47 2019
Stopped: Mon Mar  4 08:28:59 2019

**Comment by jsteube** [comment]
I did some change with commit https://github.com/hashcat/hashcat/commit/ed7765d8fdca23d3eb71e8fd94ce25546ceacea3 which successfully worked around the same problem with AMDGPU driver on Linux by unrolling some AES function. It is possible that the same workaround will also work for macosx. Please clone latest github master version and retry.

**Comment by emwinkler** [comment]
Still the same issue.

./hashcat -b -m 2501 -d 3
hashcat (v5.1.0-718-g6e0ef698) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/Users/emwinkler/Desktop/hashcat/OpenCL/m02501-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped.
* Device #2: HD Graphics 5000, skipped.
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 2044/8176 MB allocatable, 64MCU

Benchmark relevant options:
===========================
* --opencl-devices=3
* --optimized-kernel-enable

Hashmode: 2501 - WPA-EAPOL-PMK (Iterations: 0)

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Speed.#3.........:  9334.9 kH/s (0.00ms) @ Accel:512 Loops:1024 Thr:64 Vec:1

Started: Mon Mar 11 09:51:40 2019
Stopped: Mon Mar 11 09:51:43 2019

**Comment by Hamid-Najafi** [comment]
what about implimenting Metal in Hashcat ?
"Metal combines functions similar to OpenGL and OpenCL under one API"
 https://en.wikipedia.org/wiki/Metal_(API)

**Comment by matrix** [comment]
Metal is only for APPLE, I don't think it's a good idea mixing engines

**Comment by jsteube** [comment]
I agree most serious HPC is done on Linux. We will stick to OpenCL.  I've recently added support for multiple backend API and then added support for CUDA. That was possible because CUDA kernel and OpenCL kernel both go back to raw C language. If that's the case with metal we could do it. However, I've never seen a raw metal kernel.

**Comment by roman-pinchuk** [comment]
@jsteube Hello! Are you going to do Metal support in Hashcat? It will be pretty cool because I have the same issue with AMD Graphics on last ver of macOS 😩

**Comment by jsteube** [comment]
We successfully fixed a similar problem on OSX + Vega GPU. Maybe it helps for this issue as well. Please retry with new GitHub master version and make sure to have the kernels/ kernel cached removed first.

**Comment by Hamid-Najafi** [comment]
> We successfully fixed a similar problem on OSX + Vega GPU. Maybe it helps for this issue as well. Please retry with new GitHub master version and make sure to have the kernels/ kernel cached removed first.

Looks like better !


`OpenCL API (OpenCL 1.2 (Nov  9 2019 04:32:50)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz, skipped
* Device #2: Intel(R) HD Graphics 630, 1472/1536 MB (384 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 560 Compute Engine, 4032/4096 MB (1024 MB allocatable), 16MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#2.........:   516.0 MH/s (47.10ms) @ Accel:128 Loops:32 Thr:256 Vec:1
Speed.#3.........:  3641.8 MH/s (67.71ms) @ Accel:128 Loops:512 Thr:256 Vec:1
Speed.#*.........:  4157.9 MH/s


Hashmode: 100 - SHA1

Speed.#2.........:   187.3 MH/s (65.70ms) @ Accel:128 Loops:16 Thr:256 Vec:1
Speed.#3.........:  1257.4 MH/s (52.16ms) @ Accel:16 Loops:1024 Thr:256 Vec:1
Speed.#*.........:  1444.7 MH/s

Hashmode: 1400 - SHA2-256

Speed.#2.........: 78268.0 kH/s (78.99ms) @ Accel:64 Loops:16 Thr:256 Vec:1
Speed.#3.........:   539.2 MH/s (61.14ms) @ Accel:64 Loops:128 Thr:256 Vec:1
Speed.#*.........:   617.5 MH/s

Hashmode: 1700 - SHA2-512

* Device #3: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Speed.#2.........: 12068.0 kH/s (63.71ms) @ Accel:32 Loops:4 Thr:256 Vec:1
Speed.#3.........: 79221.4 kH/s (51.76ms) @ Accel:32 Loops:32 Thr:256 Vec:1
Speed.#*.........: 91289.5 kH/s`
