### ISSUE TITLE
Wrong maximum length of passwords in pure kernel mode 500

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#1867]
The maximum password length of the pure kernel mode 500 is given as:
```
Maximum password length supported by kernel: 256
```
Which can not be true, as the general limit for pure kernels always is 255 (beside some other special cases where it is lower). So this should just be adjusted to 255.

Note: There might be other pure kernels where this limit is set wrongly to 256.

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/5da1e4b87266dd893d334ae27852c0c29d802b9d
