### ISSUE TITLE
MacOS 10.14.2 - 8 warnings generated in building process

### ISSUE THREAD

**Issue by askelon** [hashcat/hashcat#1868]
Good morning,
I'm using a MBP with macOS 10.14.2 i7 2.2 iGPU Intel Iris Pro + eGPU RX580 ( Sonnet Breakaway350) and during the compilation process with "make"
are generated these errors:

deps/LZMA-SDK/C/Lzma2Dec.c:317:14: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
      return LZMA_STATUS_FINISHED_WITH_MARK;
      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:320:14: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
      return LZMA_STATUS_NOT_FINISHED;
      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:325:16: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
        return LZMA_STATUS_NEEDS_MORE_INPUT;
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:347:16: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
        return LZMA_STATUS_NOT_FINISHED;
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:357:14: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
      return LZMA_STATUS_NOT_FINISHED;
      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:365:18: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
          return LZMA_STATUS_NEEDS_MORE_INPUT;
          ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:384:20: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
            return LZMA_STATUS_NEEDS_MORE_INPUT;
            ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/LZMA-SDK/C/Lzma2Dec.c:421:10: warning: implicit conversion from enumeration type 'ELzmaStatus' to different enumeration type 'ELzma2ParseStatus' [-Wenum-conversion]
  return LZMA_STATUS_NOT_SPECIFIED;
  ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
8 warnings generated.


furthermore in the benchmark, when Hashmode: 1800 - sha512crypt $ 6 $, SHA512 (Unix) is tested, the instance returns the following error.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #2: Kernel /Users/****/hashcat/OpenCL/m01800-optimized.cl build failed - proceeding without this device

Thanks in advance for any help

**Comment by magnumripper** [comment]
The warnings are benign, build works fine despite the warnings. I've been planning to fix them for quite some time but didn't get a round tuit[tm].

**Comment by askelon** [comment]
Thanks very much!
Since it is so kind I would like to ask you another question concerning the execution of the -m 400 instance (WP MD5). When I use the only_latin.Top dictionary hashcat returns a token length error for every line of the dictionary. This happens exclusively for the dictionary mentioned above, but even much "heavy" dictionaries are loaded correctly.

../only_latin.Top 'on line 1 (123456): Token length exception][only_latin.Top' on line 2 (123456789): Token length exception][...] thus continuing for every line of the dictionary

**Comment by matrix** [comment]
> The warnings are benign, build works fine despite the warnings. I've been planning to fix them for quite some time but didn't get a round tuit[tm].

Same thing here, I tryed to update the sdk locally but it's the same. We need to modify the source but after the restyling

**Comment by askelon** [comment]
Thanks for the support!
