### ISSUE TITLE
MacOS 10.14.2 - abort while running benchmark mode 15300 using GPU

### ISSUE THREAD

**Issue by mateuszwojt** [hashcat/hashcat#1869]
I updated my 2017 MacBook Pro to 10.14.2 Mojave, compiled latest version of hashcat and ran benchmark with GPU device. I noticed it fails, mostly while running mode 15300. Everything runs fine on CPU.

`hashcat -b -m 15300 -d 2`

Output:
`hashcat (v5.1.0-42-g471a8ccc) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, skipped.
* Device #2: Intel(R) Iris(TM) Plus Graphics 640, 384/1536 MB allocatable, 48MCU

Benchmark relevant options:
===========================
* --opencl-devices=2
* --optimized-kernel-enable

Hashmode: 15300 - DPAPI masterkey file v1 (Iterations: 23999)

[1]    48029 abort      hashcat -b -m 15300 -d 2`

**Comment by jsteube** [comment]
Probably the GPU driver. Please append -D 1 to try with the CPU driver. Please post results here. In your case you have to remove the -d.

**Comment by jsteube** [comment]
Please retry with latest version from github master. Make sure to run "make clean" before recompiling.

**Comment by jsteube** [comment]
The problem should be fixed with the latest GitHub master. Feel free to reopen if fixes did not work for you.
