### ISSUE TITLE
Need Help regarding macOS 

### ISSUE THREAD

**Issue by Raks-coder** [hashcat/hashcat#1871]
Hashcat doesn't work in the new macos mojave. I would request you to make necessary changes.

It says stdio.h missing in affinity.c in the src folder

**Comment by magnumripper** [comment]
I can build just fine with Mojave/10.14.2. The only problem is a few benign warnings about LZMA-SDK enums.

Did you install xcode and CLT?

**Comment by s3inlc** [comment]
I can build as well without any problems on Mojave/10.14.2

**Comment by Raks-coder** [comment]
cd hashcat/ && make
clang -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash src/affinity.c -o obj/affinity.NATIVE.STATIC.o
In file included from src/affinity.c:7:
include/types.h:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [src/Makefile:494: obj/affinity.NATIVE.STATIC.o] Error 1

This is what i get. Please help me how can i resolve this issue. I have updated command line tools

**Comment by Raks-coder** [comment]
> I can build as well without any problems on Mojave/10.14.2

Could you please elaborate the steps, i am following the steps in this gist https://gist.github.com/chadmayfield/600b211e9c309859f2bfb5dddc5de09c

**Comment by s3inlc** [comment]
Basically, the only steps I do, is to clone and then run make.
```
git clone https://github.com/hashcat/hashcat && cd hashcat
make
```

But as @magnumripper already asked, do you have xcode and the command line tools installed?

**Comment by magnumripper** [comment]
Try this
```
$ ls -l /usr/include/stdio.h
-r--r--r--  1 root  wheel  16319 Jan 21  2018 /usr/include/stdio.h
```
Do you have that file? If not, you probably need to (re-)install xtools and/or tweak some of its settings

**Comment by Raks-coder** [comment]
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
~ $ xcode-select --version
xcode-select version 2354.
I have tools installed and they are updated too. don't know why this problem is coming

**Comment by magnumripper** [comment]
You didn't answer my question though. Also, what's the output of `which clang`?

Anyway this is not a hashcat issue at all.

**Comment by Raks-coder** [comment]
This is what i get    ~$/Users/rakshitmalhotra/anaconda3/bin/clang .I get it it's not a hashcat issue now anyways could you suggest me how to correct it, i will close the issue asap then


> You didn't answer my question though. Also, what's the output of `which clang`?
> 
> Anyway this is not a hashcat issue at all.

**Comment by Raks-coder** [comment]
so anyone able to figure out the issue?

**Comment by magnumripper** [comment]
The issue is on your end. I suggest you change your path to ensure /usr/bin/clang is used and not that foreign one.

**Comment by Raks-coder** [comment]
> The issue is on your end. I suggest you change your path to ensure /usr/bin/clang is used and not that foreign one.

Thank you I will close the issue now. Thanks for the help once again
