### ISSUE TITLE
--keep-guessing returns only one plain-text in one kernel loop

### ISSUE THREAD

**Issue by Tydus** [hashcat/hashcat#1879]
Hi all,
I'm trying to solve a password with two different hashes known:
1. PBKDF2-SHA1 (specifically 15200) which is time-consuming;
2. a "prefix" of SHA2-256 which is much faster but not precise.

I tried different strategies to speed-up the guessing by utilizing the "prefix". The things I've done are:
1. Mod `m12700-pure.cl` to add a fast check of SHA-256 to skip the PBKDF2. This produces the right result, but only gives me ~1/100 of the speed of 1400, which is not promising. ([code](https://github.com/Tydus/hashcat/tree/blockchain))
2. Mod `m01400-a1-*.cl` etc. to make it only matches the prefix (I'm using `-a 6`). Then combine this with `keep-guessing` should give me all the candidates for the next step (i.e. 15200). ([code](https://github.com/Tydus/hashcat/tree/sha256prefix))

However, the `keep-guessing` does not work as I expected. It returns only one plain-text in one kernel loop. This gives me mass false-negatives which is not tolerable at all.

I digged into the code (`mark_hash` etc.) and it seems that the design actually does not allow it to return multiple plain-text simultaneously. (Pls point me out if I'm wrong.)

So how can I workaround this issue? Or I'd better go to another strategy? (e.g. invoke pbkdf2-aes things in the kernel directly when we found some candidates in the loop.)

**Comment by jsteube** [comment]
Please read https://github.com/hashcat/hashcat/blob/38e97bd89ada27dd07c74046889b102b34686781/docs/limits.txt#L25-L41

**Comment by Tydus** [comment]
Hi Steube,

Thanks for the reply. However my problem is not the case above.

I digged more deeply into the code and made some (very ugly) hacks (sry...) by hard-code a 2000x larger plain-text buffer. Now it works like charm :)

I'm using a 5-digits (20 bits) SHA256-prefix, so the expectation of the collision rate will be 1 of 2^20.
On my K80: `13 * 256 * 512 * 128 / 2^20 = ~208` results per kernel invocation (consistent with experiments). Thus, I think 2000 should be more than enough.

[commit](https://github.com/Tydus/hashcat/commit/0181d910ddf8516dd1f29eecfd63ae0028ee0d07)
