### ISSUE TITLE
No valid rules left

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#1882]
While testing a rule of my own,

```
hahscat64.exe --stdout -r failed.rule words.txt
(..)
No valid rules left.
```

failed.rule contains:
`$a$b$c$d$e$f$g$h$i$j$k$l$m$n$o$p$q$r$s$t$u$v$w$x$y$z$ $1$2$3$4$5`

while removing 2 chars works:
`$a$b$c$d$e$f$g$h$i$j$k$l$m$n$o$p$q$r$s$t$u$v$w$x$y$z$ $1$2$3$4`

Looks like I cannot add more than 32 characters in a single rule ?

Why this limitation?
How can I add more than 32 chars ? Thanks.

**Comment by philsmd** [comment]
you can use up to 31 rule functions (the amount of characters is not the problem) within one rule line, see https://hashcat.net/wiki/doku.php?id=rule_based_attack#limitations
This is of course a limitation that is well documented and is actually quite difficult to remove without breaking support for older GPUs etc which have less memory etc. (we once had support to up to 255 rule functions in a previous release, but of course it needs much more memory and therefore users complained a lot)

Please do not forget to close the issue, if this explains why there is this limit

**Comment by adrastee** [comment]
Ok ! Thanks.
For the record, I'll use combinator attack instead of rule.
