### ISSUE TITLE
OpenCl kernel self-test failed when using any version later than v4.2.1 !!

### ISSUE THREAD

**Issue by minanagehsalalma** [hashcat/hashcat#1894]
![image](https://user-images.githubusercontent.com/20546638/52016659-d6235680-24ed-11e9-9512-e817fac994e4.png)
i Get OpenCl kernel self-test failed   and when i use --self-test-disable   it just works but  whatever the password is found or not it says

Exhausted  after trying all the passwords in the queue

.................... although the intel cpu and gpu gets the correct password

the commend i use is  ( hashcat v5.1.0 )

hashcat64.exe -a 0 --session=2019-01-29 -m 2500 -w 3 --force --status --status-timer=60 --potfile-disable -p : -d 3 --self-test-disable --hwmon-temp-abort=90 -o "C:\0.txt" --outfile-format=3 "C:\Users\123\Downloads\wifiB3381C.hccapx" "E:\ccc.txt"
![image](https://user-images.githubusercontent.com/20546638/52016733-14b91100-24ee-11e9-88d7-3036f7064b2a.png)

although it does the full wordlist it still says Exhausted ...

then i tried this commend
hashcat64.exe -a 0 --session=2019-01-29 -m 2500 -w 3 -D 1 --force --status --status-timer=60 --potfile-disable -p : --self-test-disable --hwmon-temp-abort=90 -o "C:\0.txt" --outfile-format=3 "C:\Users\123\Downloads\wifiB3381C.hccapx" "E:\ccc.txt"
![image](https://user-images.githubusercontent.com/20546638/52016753-226e9680-24ee-11e9-9d66-aa57b72eb9e1.png)
and it worked just fine and got the password ..... what would the problem be ?
![image](https://user-images.githubusercontent.com/20546638/52016785-331f0c80-24ee-11e9-9c55-a59aee5ff35c.png)
i think this a common problem  [see  ](https://www.geeks3d.com/20181029/quick-test-hashcat-5-0-0-opencl-based-password-cracking-utility-released/)

![image](https://user-images.githubusercontent.com/20546638/52016870-5ba70680-24ee-11e9-9972-5fef3b2e7574.png)
even with the RX Vega 56  the problem there !!
..............................................
i think this where the problem comes from 
https://hashcat.net/forum/thread-7903.html  ![image](https://user-images.githubusercontent.com/20546638/52016902-76797b00-24ee-11e9-9014-dd92075f9d21.png)

**Comment by minanagehsalalma** [comment]
why the  "bugs that are triggered only by some hashcat versions"
and
*AMD GPUs on Windows require "AMD Radeon Software Crimson Edition" (15.12 or later)* this an outdated version of AMD Radeon Software..... Crimson Edition have a lot of errors and unoptimized performance ..... so i use Adrenalin Edition
.... will the Radeon™ Software Crimson ReLive Edition 17.11.4 work ?

**Comment by jsteube** [comment]
Double post, please continue here: https://hashcat.net/forum/thread-8112-post-43528.html#pid43528
