### ISSUE TITLE
nvmlDeviceGetFanSpeed(): Not Supported  win10 +hashcat-5.1.0+291.7z

### ISSUE THREAD

**Issue by langxj** [hashcat/hashcat#1896]
Hi guys!Can you help me?I use the latest beta version from https://hashcat.net/beta/
![image](https://user-images.githubusercontent.com/7477494/52057684-9ec1b200-25a0-11e9-9d06-23ec8e02c56f.png)

**Comment by neheb** [comment]
Don’t use hashcat on a laptop.

That’s a common error for laptops that says hashcat cannot control the fans.

**Comment by jsteube** [comment]
It's not a hashcat problem. The fan speed readings are not supported by the underlaying API (nvml) for your device. You might want to use something like afterburner to control them.

**Comment by tz4678** [comment]
this peace of shit show errors always. it is a pity that repositories cannot be disliked

**Comment by neheb** [comment]
> this peace of shit show errors always. it is a pity that repositories cannot be disliked

what part of It's not a hashcat problem do you not get?

**Comment by yogendradevil** [comment]
> Hi guys!Can you help me?I use the latest beta version from https://hashcat.net/beta/ ![image](https://user-images.githubusercontent.com/7477494/52057684-9ec1b200-25a0-11e9-9d06-23ec8e02c56f.png)

I too facing the same issue
