### ISSUE TITLE
Brain error - BUG feof()!!

### ISSUE THREAD

**Issue by yellow-starburst** [hashcat/hashcat#1897]
hashcat version - v5.1.0-42-g471a8cc
The error i get after approximately 5 minutes is - BUG feof()!!.
I am using a 1gb wordlist and the rule -j '>E'.

**Comment by philsmd** [comment]
this might have to do with your cached dict stats (hashcat.dictstat2).

Could you please try to make a backup of the dicstat2 file and delete the original file (hashcat.dictstat2) and try again ?

In the past all problems around this feof () error had either to do with your dict or dictstat2 file... this is just my educated guess... please test.

BTW: what is the hash type you are trying to crack (-m xxx) ?

**Comment by philsmd** [comment]
any updates here ?

we need an answer/confirmation. I can't reproduce it here.

Could you please test/troubeshoot what I mentioned above @fakename12345cat ?
Thx

**Comment by yellow-starburst** [comment]
works. Thanks!

**Comment by nicolas2k** [comment]
I've also :

me@mbp test % hashcat --version
v6.2.6


...
Hardware.Mon.SMC.: Fan0: 68%, Fan1: 74%
Hardware.Mon.#1..: Util: 98%

Approaching final keyspace - workload adjusted.           

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => BUG feof()!!
BUG feof()!!
BUG feof()!!
BUG feof()!!
BUG feof()!!
Session..........: hashcat                                
Status...........: Exhausted
...
