### ISSUE TITLE
Hashcat latest inno setup version

### ISSUE THREAD

**Issue by filippharg** [hashcat/hashcat#1904]
What kind of algoritm in hashcat can we choose for latest inno setup version?

https://github.com/jrsoftware/issrc/blob/32e8b217216a71d46b8dae815be919219fe88dee/Projects/Compile.pas#L3589

SHA1("PasswordCheckHash"+ PasswordSalt + UTF16(Password)) == PasswordHash

Many thanks

**Comment by jsteube** [comment]
You can use -m 140:

sha1($salt.utf16le($pass))

Make sure to prepend the static 'PasswordCheckHash' to the PasswordSalt

**Comment by filippharg** [comment]
Thanks for answer, but I'm still unable to find right settings.

I create this setup with latest inno setup utility
https://ufile.io/ykgww
 with password aaa
Innoextractor says:
; PasswordHash=842d0bef6dbb0f060b337c6a9c7d6482a24978c0
; PasswordSalt=ec2a71fc6498810b

But with hashcat command I'm unable to find aaa password.

Do you know what right options with hashcat command I have to use or how to set hashcatGUI?
Many thanks

**Comment by jsteube** [comment]
See:

```
root@ht:~/hashcat# perl -e 'print "PasswordCheckHash" . pack ("H*", "ec2a71fc6498810b") . "a\0a\0a\0"' | sha1sum  
842d0bef6dbb0f060b337c6a9c7d6482a24978c0  -
```

This mean you need to do something like this:

```
./hashcat -m 140 842d0bef6dbb0f060b337c6a9c7d6482a24978c0:50617373776f7264436865636b48617368ec2a71fc6498810b --hex-salt -a 3 aaa
```

**Comment by filippharg** [comment]
Many thanks, friend. Now all is ok.

Il mer 13 feb 2019, 16:45 Jens Steube <notifications@github.com> ha scritto:

**Comment by Lakr233** [comment]
how does 50617373776f7264436865636b48617368ec2a71fc6498810b come from?

**Comment by philsmd** [comment]
50617373776f7264436865636b48617368ec2a71fc6498810b is basically just "PasswordCheckHash" (without quotes, used as a kind of pepper aka a general "salt") and the actual salt in hex ec2a71fc6498810b (specific for this particular hash) concatenated together (both in hex)

```
echo -n PasswordCheckHash | xxd -p
50617373776f7264436865636b48617368
```

both concatenated together
```
echo -n "50617373776f7264436865636b48617368"; echo -n "ec2a71fc6498810b"
50617373776f7264436865636b48617368ec2a71fc6498810b
```
