### ISSUE TITLE
Status: Exhausted Bitcoin Wallet Passphrase Recovery

### ISSUE THREAD

**Issue by suhel1986** [hashcat/hashcat#1905]
HI,

I tried following command, It started cracking Bitcoin Wallet Passphrase and status came: Exhausted

C:\Users\wq\Desktop\hashcat-4.1.0>hashcat64.exe -a 3 -m 11300 wallethash.txt ?a?a?a

I tried on 2 different wallets and got the same result.

This what came up in orange when started in CMD;

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Cracking performance lower than expected?

* Append -w 3 to the commandline.
  This can cause your screen to lag.

* Update your OpenCL runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

Driver temperature threshold met on GPU #3. Expect reduced performance.

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: Bitcoin/Litecoin wallet.dat
Hash.Target......: $bitcoin$96$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (I removed this)
Time.Started.....: Wed Feb 13 23:42:59 2019 (12 mins, 49 secs)
Time.Estimated...: Wed Feb 13 23:55:48 2019 (0 secs)
Guess.Mask.......: ?a?a?a [3]
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#3.....:     1115 H/s (0.38ms) @ Accel:32 Loops:8 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 857375/857375 (100.00%)
Rejected.........: 0/857375 (0.00%)
Restore.Point....: 9025/9025 (100.00%)
Candidates.#3....:  ar ->   ~
HWMon.Dev.#3.....: Temp: 82c Fan: 35% Util: 83% Core:1645MHz Mem:3504MHz Bus:16

Started: Wed Feb 13 23:42:40 2019
Stopped: Wed Feb 13 23:55:49 2019

My Operating System Details; Intel® Core™ i7-7700 Processor
8M Cache, up to 4.20 GHz RAM: 16GB

I would like to know what am I doing wrong in here,

Many Thanks

**Comment by jsteube** [comment]
Looks like the wrong mask, but a wrong mask is a user problem. Please ask on forum.

**Comment by suhel1986** [comment]
Hi, Thanks for the Reply, 

Can you please post the forum link. Sorry I don’t know which one is it

**Comment by jsteube** [comment]
https://hashcat.net/forum
