### ISSUE TITLE
Display driver crashes using Intel HD Graphics 4400

### ISSUE THREAD

**Issue by Fist0urs** [hashcat/hashcat#191]
Using oclhashcat64.exe on a Windows 8.1 Professionnal and latest Intel drivers with OpenCL gpu runtime:

```
oclHashcat64.exe -b
```

display driver crashes. Looking at the eventlog, I get:

```
Display driver igfx stopped responding and has successfully recovered.
EventId: 4101
```

I know it will be difficult to debug with such few details, so if I can add some more details, do not hesitate to ask

**Comment by epixoip** [comment]
We probably need a timeout patch for Intel like we do with Nvidia.

**Comment by Zyntax3rror** [comment]
That patch changes registry TdrLevel from 3 to 0, so it should work on any card(did work on my hd4000). (If your computer hangs after the patch (after you have started oclHashcat64) then you have to use the reset button/power-button)

TdrLevel
0 - Detection disabled
1 - Bug check on detected timeout, for example, no recovery.
2 - Recover to VGA (not implemented).
3 - Recover on timeout. This is the default value.

there is plenty of guides (just search for TdrLevel). This is one way of doing it:
patch (create a file called patch.reg (not patch.reg.txt) and paste the following. Then save and double click the file(and answer yes  and then yes again) then reboot your computer)
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000000

to go back to default:
(default.reg   copy/paste + save + double click +yes+yes+reboot)
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000003

**Comment by epixoip** [comment]
Yes, this is already covered on our wiki: http://hashcat.net/wiki/doku.php?id=timeout_patch

**Comment by jsteube** [comment]
@Fist0urs can you please try again with the registry patch and tell us if it worked?

**Comment by Fist0urs** [comment]
I tried and my screen freezes. I tried supplying just a single hash of known plain to see if it actually worked but it doesn't

**Comment by magnumripper** [comment]
Does it crash on MD4 already or what format is causing the hang? My HD4000 works just fine until an `Abort trap: 6` in SHA-3(Keccak) (and that may just as well be an Apple driver bug).

**Comment by matrix** [comment]
@magnumripper probably HD4000 is not handled like Iris in oclHashcat now.
Can you post the output ?

**Comment by magnumripper** [comment]
```
$ ./oclHashcat.app -d2 -b
oclHashcat v2.01 (gd544cdb) starting in benchmark-mode...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 384/1536 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, skipped

Hashtype: MD4
Workload: 16 loops, 256 accel

Speed.Dev.#2.:   290.2 MH/s

Hashtype: MD5
Workload: 16 loops, 256 accel

Speed.Dev.#2.:   185.7 MH/s

Hashtype: Half MD5
Workload: 16 loops, 256 accel

Speed.Dev.#2.:   111.8 MH/s

Hashtype: SHA1
Workload: 16 loops, 256 accel

Speed.Dev.#2.: 68021.2 kH/s

Hashtype: SHA256
Workload: 16 loops, 256 accel

Speed.Dev.#2.: 26484.3 kH/s

Hashtype: SHA384
Workload: 16 loops, 256 accel

Speed.Dev.#2.:  8045.7 kH/s

Hashtype: SHA512
Workload: 16 loops, 256 accel

Speed.Dev.#2.:  7466.0 kH/s

Hashtype: SHA-3(Keccak)
Workload: 16 loops, 64 accel

Abort trap: 6
```

**Comment by matrix** [comment]
Try to decrease gpu accel:

`./oclHashcat.app -d2 -b --benchmark-mode 0 -m 5000 -u 16 -n 16`

**Comment by jsteube** [comment]
if you want to mod -n in -b mode you need to use --benchmark-mode 0

**Comment by magnumripper** [comment]
Yeah that works

```
$ ./oclHashcat.app -d2 -m 5000 -n 16 -b --benchmark-mode=0
oclHashcat v2.01 (g582378b) starting in benchmark-mode...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 384/1536 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, skipped

Hashtype: SHA-3(Keccak)
Workload: 2 loops, 16 accel

Speed.Dev.#2.:   207.4 kH/s

Started: Thu Feb  4 23:44:23 2016
Stopped: Thu Feb  4 23:44:33 2016 
```

```
$ ./oclHashcat.app -d2 -m 5000 -b --benchmark-mode=0 -u 8 -n 32
oclHashcat v2.01 (g582378b) starting in benchmark-mode...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 384/1536 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, skipped

Hashtype: SHA-3(Keccak)
Workload: 8 loops, 32 accel

Speed.Dev.#2.:   213.6 kH/s

Started: Thu Feb  4 23:47:26 2016
Stopped: Thu Feb  4 23:47:35 2016 
```

**Comment by matrix** [comment]
I tuned the benchmark-mode 1 for Iris card.
HD Graphics 4000 is oldest :)

You can also try increasing from 16 to 64 if you want find the limit for your card.

**Comment by Fist0urs** [comment]
> Does it crash on MD4 already or what format is causing the hang? My HD4000 works just fine until an Abort trap: 6 in SHA-3(Keccak) (and that may just as well be an Apple driver bug).

It does crash on MD4

I'll test supplying --benchmark-mode=0 and decreasing gpu accel as soon as I can

**Comment by Zyntax3rror** [comment]
11 minutes to complete the SHA-3(Keccak) benchmark  (version 2.10b79) on win 7
(used oclhashcat64 -b)

<pre><code>
Device  #1:        Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz, skipped
Device  #2: Intel(R) HD Graphics 4000, 374/1496 MB allocatable, 350Mhz, 16MCU
Hashtype: SHA-3(Keccak)
Workload: 512 loops, 256 accel
Speed.Dev.#2.:        0 H/s
Started: Fri Feb 05 00:15:44 2016
Stopped: Fri Feb 05 00:25:40 2016
</code></pre>

---

oclhashcat64 -d2 -b --benchmark-mode 0 -m 5000 -u 16 -n 16
got me this

<pre><code>
oclHashcat v2.01 (g582378b) starting in benchmark-mode...
Device #1:        Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz, skipped
Device #2: Intel(R) HD Graphics 4000, 374/1496 MB allocatable, 350Mhz, 16MCU
Hashtype: SHA-3(Keccak)
Workload: 16 loops, 16 accel
Speed.Dev.#2.:   218.1 kH/s
Started: Fri Feb 05 00:31:55 2016
Stopped: Fri Feb 05 00:32:04 2016
</code></pre>

**Comment by Fist0urs** [comment]
@Zyntax3rror , what are your custom parameters in benchmark mode? (-u and -n) Because it keeps freezing even on -u 2 -n 2. Maybe my cpu is so weak that I can't get any low parameter to make it work?

**Comment by matrix** [comment]
@Fist0urs , please post oclHashcat output

**Comment by Fist0urs** [comment]
@gm4tr1x quite difficult as my screen freezes and I have to hard-reboot (or maybe you just wanted the cpu specs?) ;-)

Anw, it displays the prompt for MD4 then freezes 5 to 10 seconds after

**Comment by matrix** [comment]
@Fist0urs , yes please. I'm curious :)

**Comment by Fist0urs** [comment]
Here they are (I had to write them on, as computer crashed):

```
Device #1: Intel(R) HD Graphics 4400, 356/1425 MB allocatable, 400MHz, 20MCU
Device #2: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz, skipped

Hashtype: MD4
Workload: 2 loops, 2 accel 
```

**Comment by matrix** [comment]
try before

`-b -m 900 --opencl-device-type 1,2 -d 2`

and then 

`-b -m 900 --benchmark-mode 0 -u 16 -n 1 --opencl-device-type 1,2 -d 1`

If is possible, post the result here.

Thank you :)

**Comment by Fist0urs** [comment]
> try before
> 
> -b -m 900 --opencl-device-type 1,2 -d 2

Wow, this one worked! Well done :+1: 

And the 2nd failed

**Comment by Zyntax3rror** [comment]
@Fist0urs 
I used default settings on benchmarks, but a shortcut would be:

<pre><code>oclhashcat64 -d2 -b --benchmark-mode 0 -m 5000 -u 512 -n 256</code></pre>

(takes 11 minutes!! and computer looks frozen (I can move the mouse, but that's it))

How long do you wait before you give up?
My computer is extremely slow when doing this so it looks like the screen freezes, but after you wait it comes back.

can you try this one and wait for at least 5 minutes and tell me if you get lucky or not?

<pre><code>oclhashcat64 -d2 -b --benchmark-mode 0 -m 5000 -u 16 -n 16</code></pre>

**Comment by matrix** [comment]
after 8 or 17 seconds end.
I don't understand why not on your system.

**Comment by Zyntax3rror** [comment]
version  b86
Tested on hd4600 on win 7 and it fails too (latest intel driver used win64_153628.4332)
tried oclhashcat -b -m0  (waited 12 minutes) and then gave up (reset button)
(Hd4000 works fine. result in 18 seconds )

**Comment by Fist0urs** [comment]
Did someone succeed in running oclhashcat on HD Graphics on Linux? Drivers provided by Intel apparently need to patch kernel and I would like to avoid that if possible...

**Comment by dropdeadfu** [comment]
at least on windows the latest beta doesn't cause a crash anymore.

**Comment by jsteube** [comment]
@Fist0urs can we close this?

**Comment by Fist0urs** [comment]
@jsteube Yes we can
