### ISSUE TITLE
Hangs in with clCreateContext(): CL_DEVICE_NOT_AVAILABLE in benchmark mode with Intel OpenCL for CPU

### ISSUE THREAD

**Issue by Mister-X-** [hashcat/hashcat#1911]
Hashcat 5.1.0 fails to run the benchmark (regardless if all benchmarks are run or a specific one) mode on Intel CPU and hangs until Ctrl-C:

```
~# ./hashcat64.bin -b
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz, 16104/64419 MB allocatable, 32MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

clCreateContext(): CL_DEVICE_NOT_AVAILABLE

Started: Thu Feb 14 00:00:00 2019
Stopped: Thu Feb 14 00:00:00 2019
```

System info:
```
# ./hashcat64.bin -I
hashcat (v5.1.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version : OpenCL 2.1 LINUX

  Device ID #1
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
    Version        : OpenCL 2.1 (Build 0)
    Processor(s)   : 32
    Clock          : 2700
    Memory         : 16104/64419 MB allocatable
    OpenCL Version : OpenCL C 2.0 
    Driver Version : 18.1.0.0920
```

OS: Ubuntu 18.10 server 64 bit
OpenCL for Intel CPU v18.1.0.013 (according to the directory name) was installed.

**Comment by philsmd** [comment]
Why are you emphasizing that this is a problem with benchmark ? I guess it's also not working during a "normal' attack, right?

I would suggest removing all drivers with this guide https://hashcat.net/faq/wrongdriver and only installing the Intel driver (as per https://hashcat.net/hashcat) from intel.com

**Comment by Mister-X-** [comment]
Most likely. I just wanted to give an accurate report how I can reproduce the bug. The benchmark was the easiest way and doesn't require to provide a hash.

The machine was a brand new install. There was nothing but the base OS on it. Then I installed the Intel driver, then I downloaded hashcat and ran it and the issue happened. As you can see with the version number, it fits the requirement mentioned on hashcat.net (I verified this before reporting).

I've done such install multiple times in the past without any issues on various machines, so I know this is the right driver and this is the first time it happened.

I forgot to mention the kernel version: 4.18.0-10-generic

**Comment by jsteube** [comment]
I tried with the same OpenCL runtime (OpenCL for Intel CPU v18.1.0.013) on my i7-6700 CPU. It works fine.

The error 'CL_DEVICE_NOT_AVAILABLE' indicated that maybe this particular XEON CPU is not supported? Did you ever tried to run hashcat on this CPU before?

**Comment by Mister-X-** [comment]
I ran hashcat in a VM on a 6700HQ just fine, on a few systems on AWS just fine and I thought running on this high-end Xeon would work.

Being a recent CPU according to ARK and my previous experience with hashcat on Intel CPU, I would assume hashcat would have given me a different output screen than the one I got when running `hashcat -I` as shown above if it wasn't supported.

**Comment by jsteube** [comment]
Yes, I agree. It should either work fine or not report back as valid OpenCL device.

Can you try running any other OpenCL application on this CPU? If that fails, too it would be a strong indication that there's some sort of error in the Intel OpenCL runtime itself.

**Comment by Mister-X-** [comment]
This server/instance is headless. What other OpenCL application should I run? Hashcat is the only one I can think of.

Anything else I should run on this? What I mean is that this is a VPS and I got to start an instance every time I need to test something.

**Comment by jsteube** [comment]
Good question actually. I just tried locally with this: https://github.com/krrishnarraj/clpeak and it worked fine. I'm pretty sure it will fail with the same error as hashcat did. Other than that I don't have any Idea what else to run.

**Comment by jsteube** [comment]
Any Update here?

**Comment by Mister-X-** [comment]
Yes but done on a cheaper system with just 2 cores

```
Platform: Intel(R) CPU Runtime for OpenCL(TM) Applications
  Device: Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
    Driver version  : 18.1.0.0920 (Linux x64)
    Compute units   : 2
    Clock frequency : 2700 MHz

    Global memory bandwidth (GBPS)
      float   : 24.16
      float2  : 17.13
      float4  : 23.68
      float8  : 26.02
      float16 : 24.42

    Single-precision compute (GFLOPS)
      float   : 52.47
      float2  : 93.59
      float4  : 182.69
      float8  : 347.23
      float16 : 88.69

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
      double   : 46.42
      double2  : 90.91
      double4  : 179.79
      double8  : 32.03
      double16 : 44.42

    Integer compute (GIOPS)
      int   : 16.50
      int2  : 32.75
      int4  : 57.19
      int8  : 21.32
      int16 : 22.75

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer         : 7.12
      enqueueReadBuffer          : 4.80
      enqueueMapBuffer(for read) : 16679.57
        memcpy from mapped ptr   : 4.80
      enqueueUnmap(after write)  : 51194.72
        memcpy to mapped ptr     : 5.04

    Kernel launch latency : 2.50 us
```

lscpu:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
Stepping:            4
CPU MHz:             2693.674
BogoMIPS:            5387.34
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke
```

In case anybody needs to compile it:
```
apt install opencl-c-headers opencl-clhpp-headers cmake build-essential
mkdir build
cd build
cmake ..
```

**Comment by Mister-X-** [comment]
Current master and stable now work fine (and tested again on the 32 CPU beast to confirm). The system is a VPS, and they were created when needed.

No idea what the difference is (apart from some package updates).

**Comment by Mister-X-** [comment]
Actually, the issue may be linked with the kernel version. I noticed I was running 18.10 when reporting the bug and just tested with 18.04. So, something to do with OpenCL and that kernel version.

clpeak reports the following and hangs until Ctrl-C with Ubuntu 18.10:
```
Platform: Intel(R) CPU Runtime for OpenCL(TM) Applications
clCreateContextFromType (-2)
```

**Comment by Mister-X-** [comment]
Ubuntu 18.04 with 4.18.0-15-generic (HWE) also works fine where Ubuntu 18.10 with 4.18.0-10-generic or 4.18.0-15-generic fails (where the latter works fine on 16.04).

**Comment by jsteube** [comment]
I've installed 18.10 Ubuntu using 4.18.0-15-generic and the Intel OpenCL runtime. No problems here! CPU is a Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz. Maybe the CPU model is also relevant, not just the Kernel?

**Comment by jsteube** [comment]
It turned out the problem is only with Ubuntu 18.10 in combination with 4.18.0 kernel and Intel OpenCL runtime and Intel(R) Xeon(R) Platinum 8168 CPU. Other OpenCL applications are affected as well. Not a hashcat error.
