### ISSUE TITLE
nvidia and -m 9600 - OpenCL kernel self-test failed

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#1913]
- OS = up-to-date Debian
- Hashcat v5.1.0-42-g471a8ccc (git clone)
- Latest nvidia driver 410.93

Only -m 9600 gives the _OpenCL kernel self-test_ error.

Is this driver related, or Hashcat related?

**Comment by jsteube** [comment]
This is fixed with latest hashcat (you need to switch to the development branch during migration).

make clean
git checkout hash-mode-plugin
make
