### ISSUE TITLE
Error occurred: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by tutorialevideo** [hashcat/hashcat#1919]
Hi,
I have a strange error any help on this? using ubuntu 14.04 pip3 installed requests too.

python3 hashtopolis.zip
Starting client 's3-python-0.4.0.1'...
Please enter the url to the API of your Hashtopolis installation:
http://IP.x.x.x./api/server.php
Error occurred: request() got an unexpected keyword argument 'json'
Connection test failed!
Please enter the url to the API of your Hashtopolis installation:

**Comment by jsteube** [comment]
Please use hashtopolis issue, not hashcat.
