### ISSUE TITLE
I'd like to decode "Blockchain second password hash, salt, and iter_count in base64". 

### ISSUE THREAD

**Issue by nori19870522** [hashcat/hashcat#1926]
I lost my second password.
Using btcrecover, I found the string "Blockchain second password hash, salt, and iter_count in base64".
YnM6*******************************************++**************//************=
I want to decode this and extract the second password. Is there a way?

**Comment by nori19870522** [comment]
Add information.
I want to revive the second password of blockchain.com.

**Comment by nori19870522** [comment]
Current situation,
· It gets garbled when decoding with base64.
· Since I am concerned about + and / contained in the string, I changed the shape.
→ %2B , / →%2F , = → %3

**Comment by jsteube** [comment]
Please ask on hashcat forum

**Comment by philsmd** [comment]
This algorithm was added recently with commit d0d4ce9 .

see https://github.com/hashcat/hashcat/issues/1650

(this is issue was basically a duplicate of #1650, asking for -m 18800 = Blockchain, My Wallet, Second Password (SHA256))
