### ISSUE TITLE
[PMKID-PMK] Skipping mask '?1?1?1?1?1?1?1?1' because it is smaller than the minimum password length.

### ISSUE THREAD

**Issue by nenser** [hashcat/hashcat#1927]
Hi, I'm running brute PMKID hashes:
**_hashcat64.exe -m 16801 -a3 pmkid.list -1 ?l?u?d ?1?1?1?1?1?1?1?1_**
and then got error:

**Skipping mask '?1?1?1?1?1?1?1?1' because it is smaller than the minimum password length.**

Why this mask is wrong? 8 symbols is allowed for WPA-password

Full output:

hashcat64.exe -m 16801 -a3 pmkid.list -1 ?l?u?d ?1?1?1?1?1?1?1?1
hashcat (v5.1.0-502-gdb189660) starting...

* Device #1: This hardware has outdated CUDA compute capability (3.0).
             For modern OpenCL performance, upgrade to hardware that supports
             CUDA compute capability version 5.0 (Maxwell) or higher.
* Device #2: This hardware has outdated CUDA compute capability (3.0).
             For modern OpenCL performance, upgrade to hardware that supports
             CUDA compute capability version 5.0 (Maxwell) or higher.
* Device #3: This hardware has outdated CUDA compute capability (3.0).
             For modern OpenCL performance, upgrade to hardware that supports
             CUDA compute capability version 5.0 (Maxwell) or higher.
* Device #4: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
nvmlDeviceGetCurrPcieLinkWidth(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetUtilizationRates(): Not Supported

nvmlDeviceGetCurrPcieLinkWidth(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetUtilizationRates(): Not Supported

nvmlDeviceGetCurrPcieLinkWidth(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetUtilizationRates(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 680, 512/2048 MB allocatable, 8MCU
* Device #2: GeForce GTX 690, 512/2048 MB allocatable, 8MCU
* Device #3: GeForce GTX 690, 512/2048 MB allocatable, 8MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #4: Intel(R) HD Graphics 530, skipped.
* Device #5: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, skipped.

Hashes: 4 digests; 4 unique digests, 4 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Brute-Force
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 64
Maximum password length supported by kernel: 64

Watchdog: Temperature abort trigger set to 90c

**Skipping mask '?1?1?1?1?1?1?1?1' because it is smaller than the minimum password length.**

**Comment by jsteube** [comment]
No, the password must have exactly length 64. I think you want to use -m 16800 not 16801.
