### ISSUE TITLE
hash-mode 2500: potfile broken since merge of branch hash-mode-plugin

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1929]
Since merge of hash-mode-plugin, potfile output is broken on hashmode 2500:
expected output:
MD5_64:MAC_AP:MAC_STA:ESSID:PSK
real output:
filename_of_hashfile.hccapx:PSK

**Comment by jsteube** [comment]
Should be fixed. Please test and close issue. Thanks for reporting.

**Comment by ZerBea** [comment]
Now everything is working like expected. Thanks.
