### ISSUE TITLE
Cannot find an OpenCL ICD loader library.

### ISSUE THREAD

**Issue by alian001** [hashcat/hashcat#1934]
13600 | WinZip                                           | Archives
hashcat  -a 3   -m 13000     -o ./out.txt  123456.zip

hashcat (v5.1.0-608-g44cd17e) starting...

Cannot find an OpenCL ICD loader library.

You are probably missing the native OpenCL runtime or driver for your platform.

* AMD GPUs on Linux require this runtime and/or driver:
  "RadeonOpenCompute (ROCm)" Software Platform (1.6.180 or later)
* Intel CPUs require this runtime and/or driver:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* Intel GPUs on Linux require this runtime and/or driver:
  "OpenCL 2.0 GPU Driver Package for Linux" (2.0 or later)
* NVIDIA GPUs require this runtime and/or driver:
  "NVIDIA Driver" (367.x or later)

Started: Tue Feb 26 10:13:45 2019
Stopped: Tue Feb 26 10:13:45 2019

my system ins centos7.x,  and the machine in vm, i have install the  hashcat and the version si latest, when i use it,

**Comment by jsteube** [comment]
Please fix OpenCL runtime. Not a hashcat problem.
