### ISSUE TITLE
Elliptic Curve Cryptography to Hashcat

### ISSUE THREAD

**Issue by komyaka** [hashcat/hashcat#1936]
Do you plan to add ECC to Hashcat? 
I want to add another algorithm trumpeting ECC.

**Comment by jsteube** [comment]
Hashcat is used to guess passwords. How is ECC related?

**Comment by komyaka** [comment]
privatekey -> publicekey -> secret

**Comment by jsteube** [comment]
Feel free to reopen if there are more concrete details available.
