### ISSUE TITLE
15200 mode (blockchain) critical error

### ISSUE THREAD

**Issue by elplum** [hashcat/hashcat#1937]
mode : 15200
real password : Dtybfvby5
hash for program : $blockchain$v2$5000$32$3ab2a1c0966199c3f829134449e59a8da52e1a59c5eb375193c4dc2d4f80e80c

hashcat don`t detect this, maybe becose decrypt string start with:
{"tx_notes":{"...
and NOT
{"guid":"*****...

(backspace`s deleted)

now many many accounts start with "tx_notes" and dont start with "guid"

**Comment by jsteube** [comment]
Thanks for info! CC @magnumripper

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/0b1169e523d9247821d07cfb783b3a43f20c7ae7

New beta on https://hashcat.net/beta/

Thanks for reporting!

**Comment by elplum** [comment]
> Fixed with commit [0b1169e](https://github.com/hashcat/hashcat/commit/0b1169e523d9247821d07cfb783b3a43f20c7ae7)

Now : $blockchain$v2$5000$32$3ab2a1c0966199c3f829134449e59a8da52e1a59c5eb375193c4dc2d4f80e80c:malutin1983malutin1983 in potfile (but password not correct)

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/f92ebc658691f629117e7c215c4d684fcd3bd8cb

Binary beta was updated, too

**Comment by elplum** [comment]
> Fixed with commit [f92ebc6](https://github.com/hashcat/hashcat/commit/f92ebc658691f629117e7c215c4d684fcd3bd8cb)

Im analyze my database (18k+), result... very big surprise!

First 16 byte of decrypted data must be start of:

```
{ "guid": "***
hex : 7B0A20202267756964223A2022****** (7B0A2020 before "guid")

{ "guid" : "
hex : 7B0A09226775696422203A2022****** (7B0A09 before "guid")

{"guid":"*******
hex : 7B2267756964223A22************** (7B before "guid")

{"sharedKey":"**
hex : 7B227368617265644B6579223A22****

{"double_encrypt
hex : 7B22646F75626C655F656E6372797074

{"address_book":
hex : 7B22616464726573735F626F6F6B223A

{"tx_notes":{},"
hex : 7B2274785F6E6F746573223A7B7D2C22

{"tx_notes":{"**
hex : 7B2274785F6E6F746573223A7B22****
```
very-very-very little (1 of 18k+):
```
{"keys":[{"creat
hex : 7B226B657973223A5B7B226372656174
```
Sorry, i didn't run the test yesterday, before create this post :(

In my delphi program, i use this code now:
```
// dblk = ansistring, decrypted first 16 byte
    if
      (pos ('"guid', dblk) <> 0)
    or
      (pos ('"tx_n', dblk) <> 0)
    or
      (pos ('"shar', dblk) <> 0)
    or
      (pos ('"addr', dblk) <> 0)
    or
      (pos ('"doub', dblk) <> 0)
    or
      (pos ('"keys', dblk) <> 0)
    then ... (decrypt_all)
```

**Comment by magnumripper** [comment]
> Thanks for info! CC @magnumripper

Thank you for the heads-up. passing it on (blindly) to @kholia : do we need to change something?

**Comment by jsteube** [comment]
Can you provide an example hash for each of the different decrypted data variants?

**Comment by jsteube** [comment]
I've add the missing pattern with commit https://github.com/hashcat/hashcat/commit/a9bafb7edb49bbf40d097fecf19a5c4ee0620076
