### ISSUE TITLE
Slow performance on Hybrid Wordlist + Mask

### ISSUE THREAD

**Issue by evrial** [hashcat/hashcat#1950]
`hashcat64.exe -m 2500 -a 6 hash.hccapx ../areacodes.txt ?d?d?d?d?d?d?d`
Makes very low performance, about 1kH/s when normally dict and mask attack runs up to 400kH/s

> hashcat (v5.1.0) starting...
> 
> * Device #1: WARNING! Kernel exec timeout is not disabled.
>              This may cause "CL_OUT_OF_RESOURCES" or related errors.
>              To disable the timeout, see: https://hashcat.net/q/timeoutpatch
> OpenCL Platform #1: NVIDIA Corporation
> ======================================
> * Device #1: GeForce GTX 1080, 2048/8192 MB allocatable, 20MCU
> 
> Hashes: 3 digests; 2 unique digests, 1 unique salts
> Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
> 
> Applicable optimizers:
> * Zero-Byte
> * Single-Salt
> * Slow-Hash-SIMD-LOOP
> 
> Minimum password length supported by kernel: 8
> Maximum password length supported by kernel: 63
> 
> Watchdog: Temperature abort trigger set to 90c
> 
> INFO: Removed 1 hash found in potfile.
> 
> Dictionary cache built:
> * Filename..: ../areacodes.txt
> * Passwords.: 35
> * Bytes.....: 174
> * Keyspace..: 350000000
> * Runtime...: 0 secs
> 
> The wordlist or mask that you are using is too small.
> This means that hashcat cannot use the full parallel power of your device(s).
> Unless you supply more work, your cracking speed will drop.
> For tips on supplying more work, see: https://hashcat.net/faq/morework
> 
> Approaching final keyspace - workload adjusted.
> 
> Cracking performance lower than expected?
> 
> * Append -w 3 to the commandline.
>   This can cause your screen to lag.
> 
> * Update your OpenCL runtime / driver the right way:
>   https://hashcat.net/faq/wrongdriver
> 
> * Create more work items to make use of your parallelization power:
>   https://hashcat.net/faq/morework
> 
> [s]tatus [p]ause [b]ypass [c]heckpoint [q]uit =>
> 
> Session..........: hashcat
> Status...........: Running
> Hash.Type........: WPA-EAPOL-PBKDF2
> Hash.Target......: hash.hccapx
> Time.Started.....: Sun Mar 10 16:08:55 2019 (17 secs)
> Time.Estimated...: Fri Mar 15 05:51:33 2019 (4 days, 13 hours)
> Guess.Base.......: File (../areacodes.txt), Left Side
> Guess.Mod........: Mask (?d?d?d?d?d?d?d) [7], Right Side
> Guess.Queue.Base.: 1/1 (100.00%)
> Guess.Queue.Mod..: 1/1 (100.00%)
> Speed.#1.........:      886 H/s (0.08ms) @ Accel:64 Loops:16 Thr:1024 Vec:1
> Recovered........: 1/2 (50.00%) Digests, 0/1 (0.00%) Salts
> Progress.........: 14630/350000000 (0.00%)
> Rejected.........: 0/14630 (0.00%)
> Restore.Point....: 0/35 (0.00%)
> Restore.Sub.#1...: Salt:0 Amplifier:418-419 Iteration:1552-1568
> Candidates.#1....: 0507788888 -> 0417788888
> Hardware.Mon.#1..: Temp: 62c Fan: 57% Util: 57% Core:1949MHz Mem:4513MHz Bus:16

**Comment by jsteube** [comment]
It's normal. You can workaround using slow candidates mode. Use -S

**Comment by evrial** [comment]
Thanks but -S doesn't work 
> Invalid attack mode (-a) value specified in slow-candidates mode.

**Comment by jsteube** [comment]
OK, use this:

``` 
hashcat64.exe -a 6 ../areacodes.txt ?d?d?d?d?d?d?d --stdout | hashcat64.exe -m 2500 hash.hccapx 
```

**Comment by evrial** [comment]
Much better now but still limited 😺 
> Guess.Base.......: Pipe
> Speed.#1.........:   236.1 kH/s (6.54ms) @ Accel:128 Loops:64 Thr:64 Vec:1

**Comment by evrial** [comment]
Reworked file into mask:

> Guess.Mask.......: 050?d?d?d?d?d?d?d [10]
> Guess.Queue......: 1/35 (2.86%)
> Speed.#1.........:   **357.7 kH/s** (12.99ms) @ Accel:64 Loops:16 Thr:1024 Vec:1

**Comment by megapro17** [comment]
Why it is closed? It is still very slow

**Comment by jsteube** [comment]
Everything works fine. If it's slow, use the -S switch

**Comment by megapro17** [comment]
> OK, use this:
> 
> ```
> hashcat64.exe -a 6 ../areacodes.txt ?d?d?d?d?d?d?d --stdout | hashcat64.exe -m 2500 hash.hccapx 
> ```

It's much slower like this: `Speed.#1.........:    87788 H/s (1.34ms) @ Accel:64 Loops:1 Thr:1024 Vec:1`
-S doesn't work
Without piping: `Speed.#1.........:   486.5 kH/s (1.28ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1`

```
hashcat.exe -a 7 -m 11500 -w 4 --status --status-timer=60 --potfile-disable -p : -O --hwmon-disable -o "good.txt" --outfile-format=1,3 "input.txt" --increment-min=6 --increment ?u?u?u?u?u?u?u?u?u?u?u "wordlist.txt"
```
vs
```
hashcat.exe -a 7  --increment-min=6 --increment ?u?u?u?u?u?u?u?u?u?u?u "wordlist.txt" --stdout | hashcat.exe -m 11500 --potfile-disable -p : -O --hwmon-disable -o "good.txt" --outfile-format=1,3 "input.txt"
```
The "wordlist.txt" consist only one line. I could use mask, I know the right part of password, but mask attack is cutting the right half in increment mode. How can I get around this?
