### ISSUE TITLE
Proposal: Changed behaviour of --keep-guessing flag

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#1951]
**Problem:**
Currently, the flag `--keep-guessing` allows you to continue an attack after all of the target hashes have been found. With `--keep-guessing` enabled, all new found collisions of the target hashes will be added to the potfile and available after the attack using `--show`. 

With `--keep-guessing` enabled, if all target hashes are already present in the potfile, you will receive the standard information line `INFO: All hashes found in potfile! Use --show to display them.` and the attack will not start. This blocks a user from starting a different attack to generate new collisions for hashes with existing collisions in the potfile. 

To work around this block, a user may enable the `--pofile-disable` flag, which will allow the attack to start, however, with the potfile disabled no new collisions will be added to the potfile and the user is forced to enable `-o outfile` to collect the new collisions.

**Proposed changes/fix:**

The `--keep-guessing` flag should still give the information alert that all or some target hashes are present in the potfile, however, it should then continue with the attack without throwing out the hashes for which collisions exist already. New collisions should still be added to the potfile as they are cracked. A user starting a new attack with `--keep-guessing` enabled shows enough understanding that they are looking for multiple collisions for their target hashes, some of which may be present in the potfile already, and should not be blocked by existing collisions in the potfile.

**Comment by Chick3nman** [comment]
After some review, I have revised my proposed fix to include a warning message in place of the potfile count, skipping the potfile remove step entirely. I've issued a pull request that implements my changes.

**Comment by jsteube** [comment]
Nothing to add here, we can do this.
