### ISSUE TITLE
#bug hashcat (v5.1.0) Possible memory leak

### ISSUE THREAD

**Issue by wrzomar** [hashcat/hashcat#1958]
I'm using Ubuntu 16.04 on laptop with hybrid graphics card and bumblebee with nvidia-384 drivers (I know, not the newest ones). While hashcat 4.1.0 run smoothly on my GTX 1050, the newest hashcat (v5.1.0-719-gd6f21b0 and v5.1.0-747-gb48056f) starts swapping a lot and also freezes desktop on running example0.sh (with additional -d 1 because I also have runtimes for Intel GPU and CPU, first device is nVidia).
If this is because my nvidia drivers are too old, then I'll stick with hashcat v4.1.0.

**Comment by jsteube** [comment]
Can you please explain what you mean with swapping and how to reproduce this?

**Comment by wrzomar** [comment]
It means that hashcat is using all availaible memory and then some more... and more. To reproduce it on my system I just need to run example0.sh script, if I'd just nvidia device.

**Comment by wrzomar** [comment]
I've just checked v5.1.0 release and it is OK, so the commit I'm looking for is somewhere after v5.1.0.

**Comment by wrzomar** [comment]
It was commit bfdeb6e 'Move test_instruction() to opencl_ctx_devices_init()' from Mar 2, 2019.

**Comment by jsteube** [comment]
This is interesting because the change is only relevant for AMD GPU:

```
if (... && (device_param->platform_vendor_id == VENDOR_ID_AMD))
```

The memory check (which is done afterward) was already part of hashcat before. The change just moved it to a different position in the code execution chain. That's why I do not understand how hashcat 5.1.0 release version worked for you.

**Comment by wrzomar** [comment]
That's because the problem was Intel, not nVidia. I've changed line 3974 in src/opencl.c in master branch from
`if (device_param->device_type & CL_DEVICE_TYPE_GPU)`
to
`if ((device_param->device_type & CL_DEVICE_TYPE_GPU) && ((device_param->platform_vendor_id == VENDOR_ID_NV) || (device_param->platform_vendor_id == VENDOR_ID_AMD)))`
as it was before and it's fixed.

**Comment by jsteube** [comment]
I've pushed this to master. Thanks for the fix.

**Comment by wrzomar** [comment]
You're welcome.
