### ISSUE TITLE
--gpu-temp-disable Invalid argument specified.

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#1960]
Hi,
`--gpu-temp-disable` and `--gpu-temp-abort` are not working
getting error: _Invalid argument specified._

**Version tried:**
5.1.0
5.1.0+749

**Comment by jsteube** [comment]
The options have been renamed with v5.0.0 -> v5.1.0

```
Hardware Monitor: Renamed --gpu-temp-abort to --hwmon-temp-abort
Hardware Monitor: Renamed --gpu-temp-disable to --hwmon-disable
```

**Comment by s77rt** [comment]
ah okay, kindly update the wiki https://hashcat.net/wiki/doku.php?id=hashcat
thank you!

**Comment by roycewilliams** [comment]
Good catch. Updated https://hashcat.net/wiki/doku.php?id=hashcat#options and defaults section.

**Comment by s77rt** [comment]
@roycewilliams the wiki should be fully updated
it makes others confused that way
> Current version is 5.0.0.

while the Options are for v5.1.0

**Comment by roycewilliams** [comment]
Fixed for the text; I'll have to defer to @jsteube to update the screenshot graphic.
