### ISSUE TITLE
Token length exception on Open Document hash

### ISSUE THREAD

**Issue by hadim** [hashcat/hashcat#1961]
I am trying to retrieve the password of an Open Document. As documentation, I used this PR https://github.com/hashcat/hashcat/pull/1822 to get started.

When I try to run this script:

```bash
#!/usr/bin/env bash

FILENAME=$1
HASH_NAME="$(basename "$FILENAME" | cut -d. -f1).hash"
HASH_PATH="$(dirname $FILENAME)/$HASH_NAME"

HASHCAT_BINARY="../hashcat-5.1.0/hashcat64.bin"

if [ ! -f "libreoffice2john.py" ]; then
   wget "https://raw.githubusercontent.com/magnumripper/JohnTheRipper/bleeding-jumbo/run/libreoffice2john.py"
fi

python2 libreoffice2john.py $FILENAME > $HASH_PATH

$HASHCAT_BINARY --username queanotio.hash
```

I run into the following error:

```
Hashfile 'MYFILE.hash' on line 1 (MYFILE...3ed9678exxxx9846:::::MYFILE.odt): Token length exception
No hashes loaded.
```

I am not sure if this a bug in hashcat or a bug in the provided Python script that generate the hash file:

```
MYFILE.odt:$odf$*0*0*1024*16*33e76ef79dddd8b4d43a70bdcb80fd892c5739a7*8*95a3b8dd5d7f3216*16*3a037e6fe6d17c494dd6deca5e34bd26*0*THIS_STRING_IS_COMPOSED_OF_2048_CHARACTERS:::::MYFILE.odt
```

**Comment by hadim** [comment]
Maybe I should ping @Naufragous for this?

**Comment by philsmd** [comment]
example hashes can be found here: https://hashcat.net/wiki/example_hashes

you do not need (and can't) provide the name of the files within the hash line. you should only provide the raw hash to hashcat, see the examples

btw: furthermore you need to specify the hash type (--hash-type or short -m), e.g. -m 18600 for  Open Document Format (ODF) 1.1 (SHA-1, Blowfish)
only the latest beta (see https://hashcat.net/beta) supports ODF cracking at the time of this writing

**Comment by hadim** [comment]
It works like a charm. Thanks for the help!
