### ISSUE TITLE
No hashes loaded.

### ISSUE THREAD

**Issue by leblanc-zx** [hashcat/hashcat#1964]
localhost:~ apple$ hashcat -m 2500 /Users/apple/Desktop/WIFI/ttt.hccap /Users/apple/Desktop/WIFI/testDic.txt 
hashcat (1.2) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, skipped.
* Device #2: Intel(R) Iris(TM) Plus Graphics 640, 384/1536 MB allocatable, 48MCU

No hashes loaded.

Started: Tue Mar 26 11:46:44 2019
Stopped: Tue Mar 26 11:46:44 2019

**Comment by jsteube** [comment]
hccap is outdated, use hccapx.
