### ISSUE TITLE
faulty report when using optimized kernel

### ISSUE THREAD

**Issue by cryptolovi** [hashcat/hashcat#1968]
Current version v5.1.0-795-g7806be32 reports some solutions when using optimized kernel (-O) as $HEX[] target with faulty bytes. This is also present in sha256 mode, didn't test others, but assuming the error is generic.

This behaviour wasn't present in 759-gaf129d32.

Replay steps;
echo -n aaaa | sha1sum | cut -b -40 > testsha1.hash
echo -n abcdefgh abcdefgh aaaab > testword.txt
grep "+5" rules/best64.rule > test.rule

hashcat --potfile-disable -0 -m 100 -a 0 testsha1.hash testword.txt -r test.rule, result;
70c881d4a26984ddce795f6f71817c9cf4480e79:$HEX[00000000]

hasscat --potfile-disable -m 100 -a 0 testsha1.hash testword.txt -r test.rule, result;
70c881d4a26984ddce795f6f71817c9cf4480e79:aaaa

**Comment by jsteube** [comment]
Great report. If only all reports would look like this. Should be fixed with commit https://github.com/hashcat/hashcat/commit/5a1d929628721bc31ef8f91fb5599439c649cfd3

Please check on your system and close the issue if fixed.

**Comment by cryptolovi** [comment]
Solved! Thank you for the fast and quick fix!
