### ISSUE TITLE
[Feature request] Specify hash-mode in hashfile

### ISSUE THREAD

**Issue by ssolidus** [hashcat/hashcat#1974]
It would be extremely helpful if the mode for the hash on a specific line of the hashfile could be specified on the line.

The syntax would look something like this:
```
mode:hash
```

Example for SHA1:
```
100:b89eaac7e61417341b710b727768294d0e6a277b
```

This could be used by simply specifying an argument, such as `--mode-from-file`.

**Comment by roycewilliams** [comment]
What is the utility or use case of this? Either all hashes in the file are the same type (in which case it would be redundant), or else there are mixed hashes in the file (which hashcat can't handle, because it only attacks one hash type at at time).

**Comment by ZerBea** [comment]
You can use --potfile-path to separate potfiles
for example
$ hashcat -m 100 --potfile-path=hashcat.100.pot ...

**Comment by ssolidus** [comment]
@roycewilliams My current use-case is that we have retrieved many different hashes, some with salts and some without, for the same engagement, and the same target network. I would like to be able to leave a device on to crack them all using hashcat and tell hashcat which ones are of which modes so that I don't have to intervene.

You will not always be cracking hashes from the same source.

**Comment by roycewilliams** [comment]
I totally get the use case. What I'm saying is that hashcat can't do that. It can only attack one hash type at a time. If that's what you're requesting, it's a much bigger ask than just requiring it in the hash file - it would probably require a significant rearchitecting of major other portions of hashcat in ways that probably aren't in scope for the project at this time (atom or someone else would have to confirm that, of course).

Don't get me wrong - I totally see what you're after, but it's a lot more complex than it might appear.

**Comment by ssolidus** [comment]
I suppose the best solution for this currently is a bash wrapper for hashcat. Thanks for the explanation though.

**Comment by jsteube** [comment]
As Royce said, we can run only attack one hash type at a time, therefore closing.
