### ISSUE TITLE
Request new algo: SHA1DASH

### ISSUE THREAD

**Issue by yhk-vuka** [hashcat/hashcat#1987]
I would like to request a new mode for the algo called SHA1DASH seen on hashes.org. For example: https://hashes.org/leaks.php?id=1881 

The algo is basically sha1(--$salt--$pass--). I am able to emulate the algo by manually adding dashes to the salts and using a rule that just appends "--" to each password candidate. However, this has the annoying side effect of outputting passwords in the potfile as "<plaintext>--". 

Example from the avvo leak:
```
00018fa5405406f024ef447a4d6d59afafbeae65:8ccb43ef51daf67244ca3ec13ff66df54aa79a64:Nathan08
00024a5845fcc9e5e069a0e8debf9a6ef0715e8b:3a0a8e8aec50cb0455b259ef6441e23e3e14675b:sammie13
0002b80997b9d9cc39f7895eebb762ce0a360bbd:224f9e85d91171f9b86c2d087f0fcc842e3f467f:Darwin97
```

The length restrictions are the same as SHA1.

**Comment by roycewilliams** [comment]
I'm just guessing, but this is a rare enough format that simply stripping the always-present last two trailing dashes would probably be preferable to adding an entire separate hash mode to hashcat.

**Comment by Chick3nman** [comment]
I've only seen 2 instances of this used in the wild, not sure that it really requires a new kernel since it can easily be run with rules and a small change to the salt. If you can identify the software where this was used, that may make it a little more motivating for us to add it.

**Comment by jsteube** [comment]
Where is this used in?

**Comment by yhk-vuka** [comment]
@jsteube It is used on Avvo.com, thefaveapp.com and 8Tracks.com as seen on hashes.org

**Comment by jsteube** [comment]
It looks like this is some site specific custom implementation, so not a valid mode to add. Feel free to reopen if there are any new informations.
