### ISSUE TITLE
Dictionary cache building stops

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1989]
I have some more problems than a title but  a title is a main one.
Main one is that the cache building was stopping on 57.16% but after reinstalling to newest driver or by putting to registry "tdrlevel" really [don t know what helped. Cause i done two things at same moment (drivers and registry)] but it worked in weird way cause now cache building stops at 70.26% then i tried to install older driver maybe it work but it didn t work and cache building stops now at 62.15% 
![image](https://user-images.githubusercontent.com/47187463/55755985-cfb2dd00-5a50-11e9-982d-bcdd253a7d66.png)
![image](https://user-images.githubusercontent.com/47187463/55756167-2ae4cf80-5a51-11e9-8f37-a159eb958feb.png)

Laptop have 32gb ram 
gtx 880m

This problem only occurs on that dictionary: dicassasin.v.1.0 206gb 
Other dictionaries seems to work or just this 206 gb dictionary is too big for hashcat idk.

Second Problem is that i have computer which have radeon 5870 everything seems ok it says cracking 68k h/s. lel just don t know how to write it. Bassicly even i put good password to a dictionary it s still says exousted 
computer have 12gb ram 
Problem occurs  even in bruteforce attack.

Two problems are in wpa2 i am not using anything different than wpa2 hash type.
If i didn t provide enought things  and/or my english suck don t shout at me pls.

**Comment by Chick3nman** [comment]
You have a LOT of problems here that I'm not sure how to address. Lets start with something easy, why do you have a 206gb dictionary for WPA on a 980m in a laptop? You will be long dead before it's even close to finished running. Also are you sure hashcat is choking on the dictionary and not something like your system disk/memory getting hung up after reading over 100gb of dictionary? 

For the second issue, you have a card which is entirely too old for me to help you with. I don't even think recent drivers accept that card so telling you to update drivers is a lost cause. 

This would all be better addressed on the forums. Please consider closing this and asking there so we can identify any real hashcat issues and not have tickets with little/no information about multiple problems.

**Comment by ghost** [comment]
i ill just close it
