### ISSUE TITLE
Brain client errors - Windows 10 Home, Version 10.0.17134 Build 17134

### ISSUE THREAD

**Issue by ScatteredThoughts** [hashcat/hashcat#1997]
I set up a brain server in one my Digital Ocean servers. When trying to use the brain client from Windows, I received the following errors:

####################################################

C:\Users\<redacted>\Downloads\hashcat-5.1.0>hashcat64.exe -z --brain-host=<redacted> --brain-password=5efd3356f62a28d2 --brain-client-features=3 -a 3 -m 1000 ntlm.txt -i -1 ?l?d ?1?1?1?1?1?1?1?1?1?1?1?1
hashcat (v5.1.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1070, 2048/8192 MB allocatable, 15MCU

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Brute-Force
* Raw-Hash

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastically reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.

Watchdog: Temperature abort trigger set to 90c

clWaitForEvents(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

clFlush(): CL_UNKNOWN_ERROR

Session..........: hashcat (Brain Session/Attack:0x75de0fcc/0x3afb8905)
Status...........: Exhausted
Hash.Type........: NTLM
Hash.Target......: ntlm.txt
Time.Started.....: Tue Apr 16 05:47:36 2019 (1 sec)
Time.Estimated...: Tue Apr 16 05:47:37 2019 (0 secs)
Guess.Mask.......: ?1 [1]
Guess.Charset....: -1 ?l?d, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/12 (8.33%)
Speed.#1.........:        0 H/s (0.00ms) @ Accel:0 Loops:0 Thr:1024 Vec:1
Recovered........: 0/2 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/36 (0.00%)
Rejected.........: 0/0 (0.00%)
Brain.Link.#1....: N/A
Restore.Point....: 0/36 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Generating]
Hardware.Mon.#1..: Temp: 62c Fan:  6% Util:  2% Core:1771MHz Mem:3802MHz Bus:16

clFlush(): CL_UNKNOWN_ERROR

####################################################

I don't get errors when not using brain client, nor when using brain client from a linux VM. Hashcat version 5.1.0 was used in all cases.

**Comment by philsmd** [comment]
can you please try again with latest beta version from https://hashcat.net/beta/ ?

**Comment by ScatteredThoughts** [comment]
Using the beta version on both sides, I am not receiving the errors, and it seems that everything is functioning normally as far as I can tell. Thanks! Appreciate it.
