### ISSUE TITLE
add Roboform please

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#1998]
del

**Comment by philsmd** [comment]
could you please give more details see https://hashcat.net/faq#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this
which version of Roboform use this algorithm? Is this type of encrypted password storage still in use ? what is the algorithm used ? what should the hash (format) look like? Any limitations (in password length etc) ? Is there any other password cracker supporting this algorithm already ?

**Comment by jsteube** [comment]
No response from OP, therefore closing.
