### ISSUE TITLE
Keyspace command not reporting correct keyspace

### ISSUE THREAD

**Issue by Limpem** [hashcat/hashcat#1999]
I discovered that the --keyspace command does not show the correct keyspace that the hashcat command will generate when using.
I encountered this problem on both the Ubuntu and macos version of hashcat 5.1.0.
As an example I use the ?d command:

> ./hashcat64.bin -a 3 ?d --keyspace
1
./hashcat64.bin -a 3 ?d?d --keyspace
10
./hashcat64.bin -a 3 ?d?d?d --keyspace
100
./hashcat64.bin -a 3 ?d?d?d?d --keyspace
1000
./hashcat64.bin -a 3 ?d?d?d?d?d --keyspace
10000
./hashcat64.bin -a 3 ?d?d?d?d?d?d --keyspace
10000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d --keyspace
10000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d --keyspace
100000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d --keyspace
1000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d --keyspace
10000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d --keyspace
100000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
1000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
10000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
100000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
1000000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
10000000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
100000000000000
./hashcat64.bin -a 3 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d --keyspace
1000000000000000

I first thought that one digit was ignored, but 5,6 and 7 digits all report a keyspace of 10000, so I think something different is wrong.
In other cracking modes there are also problem with the --keyspace command:

> wc -l rules/best64.rule 
     102 rules/best64.rule
wc -l example.dict
  128416 example.dict
./hashcat64.bin -a 0 example.dict --keyspace
128416
./hashcat64.bin -a 0 example.dict -r rules/best64.rule --keyspace
128416
./hashcat64.bin -a 6 example.dict ?d?d?d --keyspace
128416

**Comment by philsmd** [comment]
the --keyspace option for hashcat exists *exactly* for the reason to display the keyspace that hashcat internally uses.

The definition of "keyspace" that hashcat uses, which is different compared to the total number of password candidates, even made it to the MOST FREQUENTLY asked questions:
https://hashcat.net/faq#what_is_a_keyspace

Please close

**Comment by Limpem** [comment]
I totally missed that one, sorry for the report (although I do find it a little confusing that keyspace means something different than keyspace in hashcat).
