### ISSUE TITLE
Hashcat v5.1 - Syntax error in mask

### ISSUE THREAD

**Issue by SecurityAura** [hashcat/hashcat#2000]
Hi,

Since Hashcat v5, I'm getting the following error when trying to run a command with ? in the mask.

Example:
`hashcat -m 1000 -w 3 hashes.txt -a 3 -1 '?d~!@#$%&?' -2 ?u -3 ?l -4 ?d ?1?2?3?3?3?3?3?4`

This is the output:
```
hashcat (v5.1.0) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080 Ti, 2793/11175 MB allocatable, 28MCU
* Device #2: GeForce GTX 1080 Ti, 2794/11178 MB allocatable, 28MCU

Syntax error in mask: ?d~!@#$%&?

Started: Tue Apr 16 10:13:18 2019
Stopped: Tue Apr 16 10:13:19 2019
```
That error wasn't present in v2, v3 and v4, and only appeared starting in v5 (confirmed by a colleague who updated his Hashcat from v4 to v5, and then he started getting the error).

I found a thread with this issue on Hashcat forums, but it dates back from 2012, so before v5 was released. Is that a "bug" or, has it always been that way? If so, why wasn't I getting that error with v2, v3 and v4?

https://hashcat.net/forum/thread-1795.html

Using Kali Linux 4.19.0-kali4-amd64

Thank you,

Aura

Edit: I know that adding an extra ? after the 2 ?s in the command will prevent the error, but I'm wondering if:

1. That behavior is normal/expected
2. The Hashcat Guess.Charset will return this, which is a "different" mask than the one provided, and doesn't seems to recognise the extra ?s as escape characters.

`Guess.Charset....: -1 ??d~!@#$%&??, -2 ?u, -3 ?l, -4 ?d`

**Comment by jsteube** [comment]
This is not a bug, it's the opposite. It's actually a syntax error. It wasn't detected in older versions, which gives you the wrong impression that this is a new error. As you said, you need to use ?? if you want to use the question mark.

**Comment by SecurityAura** [comment]
Alright, thank you for the confirmation.

Just for my personal knowledge, since this error wasn't detected in the older versions, was the mask properly parsed, and Hashcat actually interpreted it correctly, or did it process it as an "undefined" mask, and ran, but without doing anything?
