### ISSUE TITLE
RPC interface to manage background hashcat process

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#2001]
I am working with Hashcat since few weeks and this is incredible tool.

My main use-case can be shown as next steps:
1. Run Hashcat process in background.
2. Wait few hours or days for results.
3. Get results.

I worked before with Bitcoin and the core has pretty useful functionality - I am talking about [remote procedure call](https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs).

I have plan to implement this functionality in near future (if my skills let me do it) . In my case I need next options:
* get progress/status,
* stop,
* pause.

What do you think about that? Can you propose some other functions that should be implemented?

**Comment by jsteube** [comment]
Just one thing: use the hashcat library, not the hashcat binary

**Comment by jsteube** [comment]
Since this is not really a bug I'm closing the issue. If you have any questions, you maybe want to come to IRC and ask developers directly.
