### ISSUE TITLE
Intel GPU Installation Problem

### ISSUE THREAD

**Issue by tumblerwater** [hashcat/hashcat#2004]
Hi everyone.

I want to crack using my GPU but I do not know how to enable it. 

I have Intel HD Graphics 4000 as my gpu and I have hashcat for windows.

Error:

* Device #1: Intel's OpenCL runtime (GPU only) is currently broken.
             We are waiting for updated OpenCL drivers from Intel.
             You can use --force to override, but do not report related errors.
No devices found/left.

One of the GPU Driver Requirements says:
Intel GPUs on Windows require "OpenCL Driver for Intel Iris and HD Graphics"

I checked Intel's website (here) and I downloaded the Intel® CPU Runtime for OpenCL Applications 18.1 for Windows* OS (64bit or 32bit) but I realized it is not for GPU.

I'm quite confused with things like SDK and OpenCL. Can anyone help me out? 

Thanks

**Comment by roycewilliams** [comment]
This is a question better suited to the forums (https://hashcat.net/forum/). 

GitHub is for bug reports, feature requests, etc.
