### ISSUE TITLE
Feature Request: Show brain info for all devices

### ISSUE THREAD

**Issue by f0cker** [hashcat/hashcat#2019]
It would be nice to show brain summary info across all devices instead of per device, similar to speed status status_get_hashes_msec_all. I'll work on adding this if there are no objections.

**Comment by jsteube** [comment]
OK, cool. Please do, no objections.

**Comment by jsteube** [comment]
PR https://github.com/hashcat/hashcat/commit/3bb68e7981e9a5a2d6d28338b825616b9dbaf03c was merged.
