### ISSUE TITLE
[Question] md5($salt.$pass) vs md5($pass.$salt) speeds

### ISSUE THREAD

**Issue by tamhb** [hashcat/hashcat#2025]
Hi everyone,
I'm playing with a list of MD5 hashes that have **password length of 11 (lowered alpha-numeric)** and **salt length of 14**. I have to attack with **md5($salt.$pass)**

Because the keyspace is too large 36^11, speed is critical and I noticed in the [benchmark result](https://gist.github.com/Chick3nman/5d261c5798cf4f3867fe7035ef6dd49f) that md5($pass.$salt) has almost the same speed with raw MD5 (-m 0), which nearly double as compare to md5($salt.$pass).
Can someone explain why they are both "half MD5" but so different in speed? Prepend is costly than append?
Is there any other ways to improve this attack?

Thank you!

**Comment by roycewilliams** [comment]
This is a question better suited for [the hashcat forum](https://hashcat.net/forum/). GitHub is for managing bugs and feature requests only.

**Comment by tamhb** [comment]
Thanks, I'm closing this
