### ISSUE TITLE
BUG: hashcat already running

### ISSUE THREAD

**Issue by DanielSolomon** [hashcat/hashcat#2045]
*** Running on Ubuntu 18.04 ***
The check for running hashcat process might be a false negative.

Scenario:
Hashcat running with pid 1000.
OS kills pid 1000 for some reason, the .pid file is not cleaned.
Hashcat is running again with pid 1000 (pid overlaps) and now it cannot run although no such hashcat process is running.

Solution:
If the protected pid is the process pid itself, check for running hashcat will pass.

**Comment by DanielSolomon** [comment]
BTW the overlapping is not a common case, but since I ran hashcat in docker the first hashcat process receives the same pid every time after a reboot (causing this behaviour, if last hashcat process before reboot didn't finish its job).

**Comment by philsmd** [comment]
interesting. I think you are talking about this check:
https://github.com/hashcat/hashcat/blob/ede3ac9b10c5fbbd130edc7f8d042a4ae730daf9/src/pidfile.c#L75-L79

I agree that we could add another check that makes sure it's not the same process id as the current instance, but as you already say this should be quite rarely the case

**Comment by DanielSolomon** [comment]
Indeed.
But as I mentioned before, in docker environment it is not a rare case.

**Comment by jsteube** [comment]
Note that such a check would be OS dependent.

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/68e39c2e472fc6302092093abdfd7edcfeaf53c6
