### ISSUE TITLE
ROCm only detected if Hashcat is run as root. GPU fans spin fast and don't stop, even after Hashcat stops its job.

### ISSUE THREAD

**Issue by o-alquimista** [hashcat/hashcat#2050]
Hashcat won't detect my AMD graphics unless I run it as root. And although it works when I do, the GPU fan start spinning unusually fast and never stop, even after the cracking has finished. `lm-sensors` report 2423 RPM at 25 degrees C (same as ambient temperature). It makes a lot of noise, and the speed stays fixed at that until I reboot.

If I run Hashcat again, fan speed drops to normal for the duration of the job's execution. After Hashcat quits, fans go back to 2423 RPM, continuing to make a very loud constant noise.

Without root, only POCL is detected by Hashcat.

I am using [RadeonOpenCompute (ROCm)](https://github.com/RadeonOpenCompute/ROCm) on Ubuntu 18.04.2.

According to its installation instructions, my user must be part of the `video` group, and it is.
Tested AMDGPU-PRO. Detects AMD OpenCL support without root privilege. Fan speed never exceeds 1400 RPM, even when the temperature reaches 70 degrees.

[hashcat-root.log](https://github.com/hashcat/hashcat/files/3249976/hashcat-root.log)
[hashcat-user.log](https://github.com/hashcat/hashcat/files/3249977/hashcat-user.log)

**Comment by jsteube** [comment]
Please update to latest GitHub master. It will solve all the problems.

**Comment by o-alquimista** [comment]
Running latest git version. Hashcat is still unable to see the ROCm OpenCL device unless it is run as root. This way, the potfile is stored at /root/.hashcat/, which is very inconvenient. I would like to be able to run as an unprivileged user if possible.
