### ISSUE TITLE
check restore words_cur only once for mask files

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2055]
While troubleshooting this problem on the hashcat forum (https://hashcat.net/forum/thread-8392.html), we found out that the error "Restore value is greater than keyspace." might be caused by the fact that the words_cur value of the restore structure is not guaranteed to be in sync with the current running mask.

rd->words_cur is updated in the monitor thread (cycle_restore, write_restore etc), but it is loaded on each and every new mask iteration here:

https://github.com/hashcat/hashcat/blob/1f6c82b6d1146785318c460927f48cf797fcf204/src/hashcat.c#L87-L102

I think that we either need to sync these both values or only set the "restore point" only once at startup or for the first mask (first iteration).

My testings have shown that without that block (especially status_ctx->words_off = rd->words_cur) the error doesn't occur anymore for me.

It's also good to mention here that this is a race condition and therefore **not** really, really easy to reproduce. The easiest way to reproduce is to create a huge hcmask file with a lot of masks (smaller masks after a larger mask, because this triggers the condition that the old restore value can be larger than the max of the current mask !).

Thank you very much

**Comment by matrix** [comment]
Hola :)
sync == mutex ?
What about the race condition ? Have you already solved it? :)

**Comment by philsmd** [comment]
well, as already mentioned within the first post the correct solution would be to check the "old restore value" saved within the restore file (hashcat.restore) only once (either first iteration or on startup) and therefore we do not need to sync all the time and this way we do not need any mutex or guaranteed sync all the time while iterating.

**Comment by matrix** [comment]
> well, as already mentioned within the first post the correct solution would be to check the "old restore value" saved within the restore file (hashcat.restore) only once (either first iteration or on startup) and therefore we do not need to sync all the time and this way we do not need any mutex or guaranteed sync all the time while iterating.

Ok. Have you a working patch ? Please submit a PR

**Comment by philsmd** [comment]
There are at least 2 ways to fix this and I asked @jsteube on IRC to have a look at it to discuss which fix is the best one.

btw by testing a very large hcmask file with very small masks (actually a large mask before a small mask, repeated several times), I've found that we have a even more severe problem with memory leaks if iterating over masks thousands of times. This might already be fixed in the meantime, but we should have a look at this too (unrelated to the restore value problem and therefore off topic actually)

**Comment by matrix** [comment]
> There are at least 2 ways to fix this and I asked @jsteube on IRC to have a look at it to discuss which fix is the best one.
> 
> btw by testing a very large hcmask file with very small masks (actually a large mask before a small mask, repeated several times), I've found that we have a even more severe problem with memory leaks if iterating over masks thousands of times. This might already be fixed in the meantime, but we should have a look at this too (unrelated to the restore value problem and therefore off topic actually)

@philsmd propose a patch or two patch (if you want I have the mutex version) so I can also review. Thanks

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/ca31ef43aff1726113aaef85d06aa5c3cbca6697

Thanks for analyze, I'm sure this was not so easy to debug.
