### ISSUE TITLE
Pasword lost for blockchain My Wallet V3 not working 

### ISSUE THREAD

**Issue by blockchainjack** [hashcat/hashcat#2060]
I have created blockchain.info account and download wallet.aes.json and converting it hash using blockchain2john.py --jason wallet.aes.json 
and output store to txt file and create password list 
./hashcat64.bin -m 15200 wallet.txt -a 0 passlist.dict 
i have put original passowrd in list but it not taking can you please guid me 

thanks

**Comment by philsmd** [comment]
example hashes are here: https://hashcat.net/wiki/example_hashes

blockchain2john.py does output the hashes with file names in it. Please make sure there are no file names within the hash (and the colon after the file name needs to remove too)

**Comment by blockchainjack** [comment]
thanks #philsmd for reply 

i have try blockchain2john.py for converting 

**wallet.aes.json contain**
-----------------------------------------------------------------------
{"pbkdf2_iterations":5000,"version":3,"payload":"zhFPomW8HfBmCNxNSjeAjq+esUv4EfvIr7yfgV030DgBoIpnEAZicTDGQ1SgGyVxkcz+Ee496sSSqr2lmMug6tG                                G9qTdSad52YTfOm1Z/SSDH+OkmqVugKwyYPHqGB2FutyOKicjZtkjRhUe69AwBhXlq+PaxiaNuqa3JiY83XGd9hvdElYgCrXtSw8JMp8NTK0mWZK64c89ti5gHzJ66oHHj5gKfh4                                qLyhI1OKUnk9ynYHOtBPtLsgwaAiuCpAHakVMFDIb4RYILKrs21tiO9v6npey6o/LHn5Ck23vs9XvAF1avJuagUhh2IMFGcWp3H3KIQexwTqidds1Qt3pN2DZsDBXdc1BjO3NrxO                                5olAw5HiiCyx2+rxHTZwS4yNCrCwtl+yfJJ3hEHULUQb+FnkSvcoG/ILtBjG1fIdO5FciHKenLNjv1IHSBnvI/a7EYHwd3henM7uNjVd3jK7zRf/wO4y8TKruh5CHL2zjrFXebkf                                PtKzg0vbcJ8uj7C1QWeWuWliRieUnBD11IQZnkovf86F5YafqAmhrqhg2m8TIXJjJDkqCF1LpB9HaadM/4CvGodnS3QxqoXaVNu89/ZVs7dDLavHgkx6v2rLW92GDuprmuO+tVes                                dRITPh9Uu4JL7ErMCNDjECEzOL0zY415SSHvdymU13zv2w7e6mNtHjnUQrEN/f1b3/mn9irC587eAo9+PC+3eod8uBDjabyRP8UllBxRVRRqxEdYRw87vkOGUeWy9qxv7Q5QLsfJ                                Lu1/fes64UTWxM07oUSt0tF97uoitktedNBwbga7aBTTvWyKSXEIwT7lJPH9WZ69xhjlizd1c945/A3iumODhZqQIvH1MByk4tpZobSF505G/dIinkXL3N0NoHZKo6Y309mCXjoA                                Wp1Ww9Nu4xBtz1PJE6+DhI18+btiUmyqi/gvEBIoy78NvvsfKBWBKfPdjBen0Z49CV0OMu9itg9QDDa8Pf2qqkm/2c665XYosQzbf67rW+Dl7NjHYQcWvV0s9K7+P/Y1UQPcTNlH                                03ZWESycyGeRIMhQ1sQKeRHyKhfOkIi0QoopOzHlRFp781lCIMWr5lCMafN6IuzehJ5lhyUmuD34ExZvMPAQfKf2GF1NOAsPHRzADzXnn4U+/HSU0ewPZ8xU4pfCr6vNbTX9GDxw                                W8pkYWLUrIThoIQj23pnkEub1nQQFh2WFVWIfDDzYLxFNhpdjxxoBkLO6Z1CRkqkL/rT/d4LXXtIgxeO4BGDMTDXNtzJyQyroo0Ep2EngBnDr/uhLWvAFOyUgPO4H3OvOewgm3L/                                iJjlDtC70NtYeWJ5a6oyD8tAcJ/acguhf"}
-----------------------------------------------------------------------



blockchain2john.py --jason wallet.aes.json > walletfile

output
--------------------------------------------------------------------------
$blockchain$v2$5000$1008$ce114fa265bc1df06608dc4d4a37808eaf9eb14bf811fbc8afbc9f815d37d03801a08a671006627130c64354a01b257191ccfe11ee3deac492aabda598cba0ead186f6a4dd49a779d984df3a6d59fd24831fe3a49aa56e80ac3260f1ea181d85badc8e2a272366d92346151eebd0300615e5abe3dac6268dbaa6b726263cdd719df61bdd1256200ab5ed4b0f09329f0d4cad265992bae1cf3db62e601f327aea81c78f980a7e1e2a2f2848d4e2949e4f729d81ceb413ed2ec8306808ae0a90076a454c14321be116082caaecdb5b623bdbfa9e97b2ea8fcb1e7e42936defb3d5ef005d5abc9b9a814861d8830519c5a9dc7dca2107b1c13aa275db3542dde93760d9b0305775cd418cedcdaf13b9a25030e478a20b2c76fabc474d9c12e32342ac2c2d97ec9f249de110750b5106fe167912bdca06fc82ed0631b57c874ee457221ca7a72cd8efd481d2067bc8fdaec4607c1dde17a733bb8d8d57778caef345fff03b8cbc4caaee8790872f6ce3ac55de6e47cfb4ace0d2f6dc27cba3ec2d5059e5ae5a589189e527043d75210667928bdff3a17961a7ea02686baa18369bc4c85c98c90e4a821752e907d1da69d33fe02bc6a1d9d2dd0c6aa1769536ef3dfd956cedd0cb6af1e0931eafdab2d6f76183ba9ae6b8efad55eb1d4484cf87d52ee092fb12b3023438c4084cce2f4cd8e35e52487bddca6535df3bf6c3b7ba98db478e7510ac437f7f56f7fe69fd8ab0b9f3b780a3df8f0beddea1df2e0438da6f244ff14965071455451ab111d611c3ceef90e194796cbdab1bfb43940bb1f24bbb5fdf7aceb85135b1334ee8512b74b45f7bba88ad92d79d341c1b81aeda0534ef5b22925c42304fb9493c7f5667af71863962cddd5cf78e7f0378ae98e0e166a408bc7d4c072938b696686d2179d391bf7488a79172f73743681d92a8e98df4f660978e8016a755b0f4dbb8c41b73d4f244ebe0e1235f3e6ed8949b2aa2fe0bc4048a32efc36fbec7ca05604a7cf76305e9f4678f4257438cbbd8ad83d4030daf0f7f6aaa926ff673aeb95d8a2c4336dfebbad6f8397b3631d841c5af574b3d2bbf8ffd8d5440f7133651f4dd95844b273219e448321435b1029e447c8a85f3a4222d10a28a4ecc7951169efcd65088316af994231a7cde88bb37a1279961c949ae0f7e04c59bcc3c041f29fd8617534e02c3c7473003cd79e7e14fbf1d25347b03d9f31538a5f0abeaf35b4d7f460f1c16f2991858b52b2138682108f6de99e412e6f59d040587658555621f0c3cd82f114d869763c71a0190b3ba67509192a90bfeb4ff7782d75ed220c5e3b80460cc4c35cdb73272432ae8a34129d849e00670ebfee84b5af0053b25203cee07dcebce7b0826dcbfe2263943b42ef436d61e589e5aea8c83f2d01c27f69c82e85f
--------------------------------------------------------------------------
Testing wallet : 95b0793c-927a-4e57-ac5c-5b5ba6418920

password :block$chain$07
this is original password you can login and check 

i put this password in passlist.dict file 

./hashcat64.bin -m 15200 walletfile -a 0 passlist.dict
i try but hashcat not able to detect right password 

can you please guide me what mistake am making 

thank you

**Comment by philsmd** [comment]
works for me. what is your full output of hashcat and error message (or warnings) etc

does the self-test work ? does the example hash with password hashcat work (https://hashcat.net/wiki/example_hashes) ?

**Comment by blockchainjack** [comment]
example work fine i put password hashcat in passlist.dict it detected but for my wallet it doesn't work below 

output for command
-------------------------------------------------------------------------------------------------
root@ambit-TB250-BTC:/home/ambit/ja/hashcat-5.1.0# ./hashcat64.bin -m 15200 walletfile.txt -a 0 passlit.dict --force
hashcat (v5.1.0) starting...

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_pcie: No such file or directory

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_sclk: No such file or directory

First_file_in_directory() failed.

/sys/bus/pci/devices/0000:00:00.0/pp_dpm_mclk: No such file or directory

First_file_in_directory() failed.

OpenCL Platform #1: Mesa
========================
* Device #1: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU
* Device #2: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU
* Device #3: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU
* Device #4: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU
* Device #5: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU
* Device #6: AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-51-generic, LLVM 6.0.0), 5732/8189 MB allocatable, 36MCU

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #7: Ellesmere, 4048/8090 MB allocatable, 36MCU
* Device #8: Ellesmere, 4048/8090 MB allocatable, 36MCU
* Device #9: Ellesmere, 4048/8090 MB allocatable, 36MCU
* Device #10: Ellesmere, 4048/8090 MB allocatable, 36MCU
* Device #11: Ellesmere, 4048/8090 MB allocatable, 36MCU
* Device #12: Ellesmere, 4048/8090 MB allocatable, 36MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #1: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #2: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #3: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #4: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #5: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<unknown>:0:0: in function gpu_decompress void (%struct.pw_idx addrspace(1)*, i32 addrspace(1)*, %struct.pw addrspace(1)*, i64): unsupported initializer for address space

* Device #6: Kernel /home/ambit/ja/hashcat-5.1.0/OpenCL/m12700-pure.cl build failed - proceeding without this device.

Dictionary cache built:
* Filename..: passlit.dict
* Passwords.: 29
* Bytes.....: 180
* Keyspace..: 29
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: Blockchain, My Wallet, V2
Hash.Target......: $blockchain$v2$5000$1008$ce114fa265bc1df06608dc4d4a...82e85f
Time.Started.....: Sun Jun 16 21:25:34 2019 (0 secs)
Time.Estimated...: Sun Jun 16 21:25:34 2019 (0 secs)
Guess.Base.......: File (passlit.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#7.........:        0 H/s (0.00ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#8.........:      235 H/s (0.41ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#9.........:        0 H/s (0.00ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#10.........:        0 H/s (0.00ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#11.........:        0 H/s (0.00ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#12.........:        0 H/s (0.00ms) @ Accel:64 Loops:32 Thr:64 Vec:1
Speed.#*.........:      235 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 29/29 (100.00%)
Rejected.........: 0/29 (0.00%)
Restore.Point....: 0/29 (0.00%)
Restore.Sub.#7...: Salt:0 Amplifier:0-0 Iteration:0-32
Restore.Sub.#8...: Salt:0 Amplifier:0-1 Iteration:4992-4999
Restore.Sub.#9...: Salt:0 Amplifier:0-0 Iteration:0-32
Restore.Sub.#10...: Salt:0 Amplifier:0-0 Iteration:0-32
Restore.Sub.#11...: Salt:0 Amplifier:0-0 Iteration:0-32
Restore.Sub.#12...: Salt:0 Amplifier:0-0 Iteration:0-32
Candidates.#7....: [Copying]
Candidates.#8....: jak -> fgjdhfsdjgkjdrkgj
Candidates.#9....: [Copying]
Candidates.#10....: [Copying]
Candidates.#11....: [Copying]
Candidates.#12....: [Copying]
Hardware.Mon.#7..: Temp: 43c Fan: 18% Core: 608MHz Mem: 300MHz Bus:8
Hardware.Mon.#8..: Temp: 46c Fan: 18% Core: 910MHz Mem: 300MHz Bus:8
Hardware.Mon.#9..: Temp: 46c Fan: 18% Core: 608MHz Mem: 300MHz Bus:8
Hardware.Mon.#10..: Temp: 48c Fan: 18% Core: 608MHz Mem: 300MHz Bus:8
Hardware.Mon.#11..: Temp: 49c Fan: 18% Core: 608MHz Mem: 300MHz Bus:8
Hardware.Mon.#12..: Temp: 41c Fan: 18% Core: 608MHz Mem: 300MHz Bus:8

Started: Sun Jun 16 21:24:52 2019
Stopped: Sun Jun 16 21:25:35 2019

**Comment by philsmd** [comment]
try beta (https://hashcat.net/beta/ or git version, compile from source).
also please do not use mesa (uninstall it)

you could also try with rocm on linux, but this shouldn't be the main reason for this problem at all.

did you test with 1 word in the dictionary instead of 29 and this word is the correct password ? maybe you are messing up something there too?

**Comment by jsteube** [comment]
Known MESA issue, not a hashcat issue. Please uninstall MESA.

**Comment by blockchainjack** [comment]
i have uninstall MESA and also compile beta version but still not able to detect password , it do detect hashcat example password but why doesnt work with my hash i have try 3 different account by putting password in .dict file non of them work only hashcat example work. also i have install in different pc as well i think something has change in My wallet V3 hash which need to change in hashcat try yourself. 
you said it work for you show me output of above give hash with log

**Comment by ghost** [comment]
not works! any update?

**Comment by philsmd** [comment]
@iM4hdi what exactly doesn't work ? You need to use the beta from https://hashcat.net/beta for now

**Comment by blockchainjack** [comment]
I have try beta version as well but it not working you can try by yourself

**Comment by philsmd** [comment]
it works perfectly fine here. it cracks with password block$chain$07

```
$blockchain$v2$5000$1008$ce114fa265bc1df06608dc4d4a37808eaf9eb14bf811fbc8afbc9f815d37d03801a08a671006627130c64354a01b257191ccfe11ee3deac492aabda598cba0ead186f6a4dd49a779d984df3a6d59fd24831fe3a49aa56e80ac3260f1ea181d85badc8e2a272366d92346151eebd0300615e5abe3dac6268dbaa6b726263cdd719df61bdd1256200ab5ed4b0f09329f0d4cad265992bae1cf3db62e601f327aea81c78f980a7e1e2a2f2848d4e2949e4f729d81ceb413ed2ec8306808ae0a90076a454c14321be116082caaecdb5b623bdbfa9e97b2ea8fcb1e7e42936defb3d5ef005d5abc9b9a814861d8830519c5a9dc7dca2107b1c13aa275db3542dde93760d9b0305775cd418cedcdaf13b9a25030e478a20b2c76fabc474d9c12e32342ac2c2d97ec9f249de110750b5106fe167912bdca06fc82ed0631b57c874ee457221ca7a72cd8efd481d2067bc8fdaec4607c1dde17a733bb8d8d57778caef345fff03b8cbc4caaee8790872f6ce3ac55de6e47cfb4ace0d2f6dc27cba3ec2d5059e5ae5a589189e527043d75210667928bdff3a17961a7ea02686baa18369bc4c85c98c90e4a821752e907d1da69d33fe02bc6a1d9d2dd0c6aa1769536ef3dfd956cedd0cb6af1e0931eafdab2d6f76183ba9ae6b8efad55eb1d4484cf87d52ee092fb12b3023438c4084cce2f4cd8e35e52487bddca6535df3bf6c3b7ba98db478e7510ac437f7f56f7fe69fd8ab0b9f3b780a3df8f0beddea1df2e0438da6f244ff14965071455451ab111d611c3ceef90e194796cbdab1bfb43940bb1f24bbb5fdf7aceb85135b1334ee8512b74b45f7bba88ad92d79d341c1b81aeda0534ef5b22925c42304fb9493c7f5667af71863962cddd5cf78e7f0378ae98e0e166a408bc7d4c072938b696686d2179d391bf7488a79172f73743681d92a8e98df4f660978e8016a755b0f4dbb8c41b73d4f244ebe0e1235f3e6ed8949b2aa2fe0bc4048a32efc36fbec7ca05604a7cf76305e9f4678f4257438cbbd8ad83d4030daf0f7f6aaa926ff673aeb95d8a2c4336dfebbad6f8397b3631d841c5af574b3d2bbf8ffd8d5440f7133651f4dd95844b273219e448321435b1029e447c8a85f3a4222d10a28a4ecc7951169efcd65088316af994231a7cde88bb37a1279961c949ae0f7e04c59bcc3c041f29fd8617534e02c3c7473003cd79e7e14fbf1d25347b03d9f31538a5f0abeaf35b4d7f460f1c16f2991858b52b2138682108f6de99e412e6f59d040587658555621f0c3cd82f114d869763c71a0190b3ba67509192a90bfeb4ff7782d75ed220c5e3b80460cc4c35cdb73272432ae8a34129d849e00670ebfee84b5af0053b25203cee07dcebce7b0826dcbfe2263943b42ef436d61e589e5aea8c83f2d01c27f69c82e85f:block$chain$07
```

```
Status...........: Cracked
```

please explain exactly what you are running and which driver you have installed.

what is the command you use. also post the full output of hashcat in quotes (<>) here.

**Comment by blockchainjack** [comment]
thank for replying 
Hi i have use fresh new system with AMD RX580 card and OS Win 7 x64bit 
below are output. where am i making mistake can please help me.

```
C:\Users\sai\Desktop\hashcat-5.1.0>hashcat64.exe -m 15200 hashfile.txt pass.dict
hashcat (v5.1.0) starting...
ADL_Overdrive_Caps(): -5

ADL_Overdrive_Caps(): -5

ADL_Overdrive_Caps(): -5

ADL_Overdrive_Caps(): -5

ADL_Overdrive_Caps(): -5

ADL_Overdrive_Caps(): -5

ADL_Overdrive5_CurrentActivity_Get(): -5

ADL_Overdrive5_CurrentActivity_Get(): -5

ADL_Overdrive5_CurrentActivity_Get(): -5

ADL_Overdrive5_CurrentActivity_Get(): -5


OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 4048/8192 MB allocatable, 36MCU
* Device #2: AMD FX(tm)-6100 Six-Core Processor, skipped.

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Temperature abort trigger set to 90c

Dictionary cache built:
* Filename..: pass.dict
* Passwords.: 15
* Bytes.....: 254
* Keyspace..: 15
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: Blockchain, My Wallet, V2
Hash.Target......: $blockchain$v2$5000$1008$ce114fa265bc1df06608dc4d4a...82e85f
Time.Started.....: Thu Sep 05 19:00:15 2019 (0 secs)
Time.Estimated...: Thu Sep 05 19:00:15 2019 (0 secs)
Guess.Base.......: File (pass.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:      183 H/s (0.35ms) @ Accel:128 Loops:32 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 15/15 (100.00%)
Rejected.........: 0/15 (0.00%)
Restore.Point....: 15/15 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:4992-4999
Candidates.#1....: block$chain$07 -> block$chain$07
Hardware.Mon.#1..: N/A

Started: Thu Sep 05 19:00:11 2019
Stopped: Thu Sep 05 19:00:16 2019
```

**Comment by philsmd** [comment]
this **was** a known problem (see https://github.com/hashcat/hashcat/commit/0b1169e5 and https://github.com/hashcat/hashcat/issues/1937). therefore I already said above that you need to use the beta version from https://hashcat.net/beta. 

your output
```
hashcat (v5.1.0) starting
```

clearly says that you are not using the beta version

it perfectly works here with beta version from https://hashcat.net/beta

**Comment by johnjames333** [comment]
I can recover your wallet I have powerful machine and software for recovering blockchain wallet
you can reach me in telegram @viladmir2022
my fee is 20% of the recovered fund
