### ISSUE TITLE
increase maximum password length

### ISSUE THREAD

**Issue by SquirrelAssassin** [hashcat/hashcat#2064]
I need the maximum password length increased across the board.  We required min 18 password length and many have 30+ ... we use phrases because there just better and easier to remember.  If you wont update code will you please tell me how to update the windows version to support up to say 64 char passwords out of the box from either the left or right side of passwordlist+combination.  

Were at a age where 27 limit is just not rational.

**Comment by jsteube** [comment]
Hashcat supports passwords up to length 256 if you do not use optimized mode (do not use -O to disable).
