### ISSUE TITLE
web2py pbkdf2(1000,20,sha512) format conversion details 

### ISSUE THREAD

**Issue by blacktraffic** [hashcat/hashcat#2072]
I suspect this doesn't make sense to implement as a separate module - it's the same as 12100 bar encoding. But you might have different opinions. 

pbkdf2(1000,20,sha512)$a2a2ca127df6bc19$77bb5a3d129e2ce710daaefeefef8356c4c827ff

Conversion script to hashcat type 12100 below if that's easier to read.

```
#!/bin/python

#str(LazyCrypt(crypt, 'mysecret'))
#
#input:
#pbkdf2(1000,20,sha512)$a2a2ca127df6bc19$77bb5a3d129e2ce710daaefeefef8356c4c827ff
#
#output, and crack with -m 12100
#sha512:1000:YTJhMmNhMTI3ZGY2YmMxOQ==:d7taPRKeLOcQ2q7+7++DVsTIJ/8=:mysecret

import fileinput
import base64

for line in fileinput.input():
    line=line.rstrip()
    [a,b,c]=line.split('$',3)

    print('sha512:1000:'+base64.b64encode(b)+':'+base64.b64encode(c.decode("hex")))
```

**Comment by Chick3nman** [comment]
It may be possible to add this conversion step to the parser internally and allow hashcat to do the conversion for the user without telling them. That said, i'm not sure what @jsteube wants to do about such things.

**Comment by blacktraffic** [comment]
no worries either way, i just made a note of it as i couldn't find it on the web elsewhere. it doesn't seem to be particularly common.

**Comment by jsteube** [comment]
That's what the ****x modes are for. Like -m 12001 is just a parser to kernel 12000 (PBKDF2-HMAC-SHA1), this could be the same for SHA512 based PBKDF2. So this totally makes sense to add. Feel free to add it as -m 12101. Only the parser is needed (src/modules/) and optional unit test (tools/test_modules/).

**Comment by blacktraffic** [comment]
ok, i'll have a pop this weekend - i've been meaning to write a custom mode anyway, and this looks like an easy way to start.

**Comment by jamieriden** [comment]
This works for the example I found - we came across this on an engagement, and don't have that much info about it unfortunately. 

I'll do a proper pull request soon-ish, but it's attached for now . 


[module_12101.c.txt](https://github.com/hashcat/hashcat/files/3489175/module_12101.c.txt)

**Comment by blacktraffic** [comment]
There's a PR in there now - it works for the public example I found. sadly, not a lot of info about it.

**Comment by JulyMoon87** [comment]
> I suspect this doesn't make sense to implement as a separate module - it's the same as 12100 bar encoding. But you might have different opinions. 
> 
> pbkdf2(1000,20,sha512)$a2a2ca127df6bc19$77bb5a3d129e2ce710daaefeefef8356c4c827ff
> 
> Conversion script to hashcat type 12100 below if that's easier to read.
> 
> ```
> #!/bin/python
> 
> #str(LazyCrypt(crypt, 'mysecret'))
> #
> #input:
> #pbkdf2(1000,20,sha512)$a2a2ca127df6bc19$77bb5a3d129e2ce710daaefeefef8356c4c827ff
> #
> #output, and crack with -m 12100
> #sha512:1000:YTJhMmNhMTI3ZGY2YmMxOQ==:d7taPRKeLOcQ2q7+7++DVsTIJ/8=:mysecret
> 
> import fileinput
> import base64
> 
> for line in fileinput.input():
>     line=line.rstrip()
>     [a,b,c]=line.split('$',3)
> 
>     print('sha512:1000:'+base64.b64encode(b)+':'+base64.b64encode(c.decode("he- x")))

> ```    
>                        
> 
> 
#
