### ISSUE TITLE
2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095) Kernel Build Failure MacOS 10.14.5

### ISSUE THREAD

**Issue by derhornspieler** [hashcat/hashcat#2076]
<img width="1016" alt="Screen Shot 2019-06-25 at 9 24 50 PM" src="https://user-images.githubusercontent.com/15236687/60146559-ac661700-978f-11e9-9f6f-4957cf72b601.png">

**Comment by jsteube** [comment]
This cvms_element_build_from_source error is evil, it pops up in tons of projects. It's clearly an issue inside the macOS OpenCL runtime, not inside hashcat. The only thing we can try is to find a workaround since Apple refuses to fix this bug. Please recompile hashcat with DEBUG enable and run hashcat with -m 2500 but not in benchmark. Just use a normal wordlist attack.

**Comment by matrix** [comment]
@derhornspieler your Iris Pro is working with 2500 ?

```
$ ./hashcat -m 2500 -b -D2
hashcat (v5.1.0-1187-g398c89c7) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

[...]/hashcat/OpenCL/m02500-optimized.cl: Optimized OpenCL kernel requested but not needed - falling back to pure OpenCL kernel
OpenCL API (OpenCL 1.2 (Jun 15 2018 20:52:09)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz, skipped
* Device #2: Iris, 384/1536 MB allocatable, 40MCU

Benchmark relevant options:
===========================
* --opencl-device-types=2
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

Speed.#2.........:     7346 H/s (86.21ms) @ Accel:8 Loops:16 Thr:512 Vec:1

Started: Wed Jun 26 22:08:37 2019
Stopped: Wed Jun 26 22:09:17 2019
```

**Comment by skozlovskiy** [comment]
Hi. I have the same problem.
MacOS Mojave 
Version: 10.14.6 (18G87)
MacBook Pro (15-inch, 2018)
Processor: 2.6 GHz Intel Core i7
Memory: 32 GB 2400 MHz DDR4
Graphics: Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

Install hashcat like this:
>>git clone https://github.com/hashcat/hashcat.git
>>make


`
MacBook-Pro:hashcat p$ ./hashcat -m 2500 -b -d 3
hashcat (v5.1.0-1379-g706d69ba) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/hashcat/OpenCL/m02500-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
OpenCL API (OpenCL 1.2 (Jun 23 2019 21:50:55)) - Platform #1 [Apple]

* Device #1: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, skipped
* Device #3: AMD Radeon Pro 560X Compute Engine, 1024/4096 MB allocatable, 16MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /Users/panter/utils/wifi_hack/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.


Started: Sun Aug 11 17:01:33 2019
Stopped: Sun Aug 11 17:01:51 2019
`

**Comment by skozlovskiy** [comment]
Did rebuild in DEBUG mode
>>make DEBUG=1

and run in normal mode:

MacBook-Pro:hashcat p$ ./hashcat -a 0 -m 2500 /var/tmp/home.hccapx /Users/p/utils/home-wifi.txt -r rules/best64.rule -d 3
hashcat (v5.1.0-1379-g706d69ba) starting...

OpenCL API (OpenCL 1.2 (Jun 23 2019 21:50:55)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, skipped
* Device #3: AMD Radeon Pro 560X Compute Engine, 1024/4096 MB allocatable, 16MCU

Hashes: 9 digests; 8 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 77

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

* Device #3: build_options '-D KERNEL_STATIC -I OpenCL -I /Users/p/hashcat/OpenCL -D LOCAL_MEM_TYPE=1 -D VENDOR_ID=2 -D CUDA_ARCH=0 -D HAS_VPERM=0 -D HAS_VADD3=0 -D HAS_VBFE=0 -D HAS_BFE=0 -D HAS_LOP3=0 -D HAS_MOV64=0 -D HAS_PRMT=0 -D VECT_SIZE=1 -D DEVICE_TYPE=4 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=2500 -D ATTACK_EXEC=10 -D ATTACK_KERN=0 -D _unroll '
* Device #3: build_options_module '-D KERNEL_STATIC -I OpenCL -I /Users/p/hashcat/OpenCL -D LOCAL_MEM_TYPE=1 -D VENDOR_ID=2 -D CUDA_ARCH=0 -D HAS_VPERM=0 -D HAS_VADD3=0 -D HAS_VBFE=0 -D HAS_BFE=0 -D HAS_LOP3=0 -D HAS_MOV64=0 -D HAS_PRMT=0 -D VECT_SIZE=1 -D DEVICE_TYPE=4 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=4 -D KERN_TYPE=2500 -D ATTACK_EXEC=10 -D ATTACK_KERN=0 -D _unroll  '
* Device #3: Kernel m02500-pure.d2d9de58.kernel not found in cache! Building may take a while...
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /Users/p/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.

Started: Sun Aug 11 17:16:40 2019
Stopped: Sun Aug 11 17:16:57 2019

**Comment by acnrayd** [comment]
I am having the exact same problem on Mac version 10.13.4, with two AMD D300 graphic cards installed (Mac Pro 2013), also using latest build of Hashcat.

Interestingly, only **WPA-EAPOL-PBKDF2** cracking mode gives this error. Other than that, it works fine. I was not able to isolate neither find a hint to solve this problem.

**Comment by j3llyh34d1337** [comment]
**** I appreciate this is an OpenCL issue... not a hashcat issue.

I'm running Catalina 10.15.1, and hashcat pulled today.

I'm experiencing the same symptoms when cracking WPA-EAPOL-PBKDF2....  Is the issue down to 32/64bit handling of numbers within m02500-pure.cl?  I'm beyond my comfort zone; sifting through the code...   I'm puzzled by other hash types working with external GPU's.


➜  hashcat git:(master) ✗ ./hashcat -m 2500 xxx.hccapx     
hashcat (v5.1.0-1428-g11c8a404) starting...

OpenCL API (OpenCL 1.2 (Oct  2 2019 00:43:05)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 550, 384/1536 MB allocatable, 48MCU
* Device #3: AMD Radeon Pro 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashes: 6 digests; 5 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /Users/xxx/hashcat/OpenCL/m02500-pure.cl build failed - proceeding without this device.

Host memory required for this attack: 409 MB

Starting attack in stdin mode...



Other hash types appear to be working ....

➜  hashcat git:(master) ✗ ./example0.sh
hashcat (v5.1.0-1428-g11c8a404) starting...

OpenCL API (OpenCL 1.2 (Oct  2 2019 00:43:05)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 550, 384/1536 MB allocatable, 48MCU
* Device #3: AMD Radeon Pro 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Dictionary cache built:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416
* Runtime...: 0 secs

Hashes: 6494 digests; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 1580 MB

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 134653935616

Approaching final keyspace - workload adjusted.  

a48dd0f09abaf64324be83ce86414b5f:ap2300000       
3baa3048651a65d1260eb521ab
...
049ed82a2d72da30a722141d0f81baef:and7rain        
                                                 
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: MD5
Hash.Target......: example0.hash
Time.Started.....: Sun Nov 10 01:16:55 2019 (55 secs)
Time.Estimated...: Sun Nov 10 01:17:50 2019 (0 secs)
Guess.Base.......: File (example.dict), Right Side
Guess.Mod........: Mask (?a?a?a?a) [4], Left Side
Guess.Queue.Base.: 1/1 (100.00%)
Guess.Queue.Mod..: 1/1 (100.00%)
Speed.#2.........: 57195.8 kH/s (5.34ms) @ Accel:2 Loops:16 Thr:256 Vec:1
Speed.#3.........:  2262.6 MH/s (0.96ms) @ Accel:64 Loops:64 Thr:256 Vec:1
Speed.#*.........:  2319.8 MH/s
Recovered........: 2237/6494 (34.45%) Digests
Remaining........: 4257 (65.55%) Digests
Recovered/Time...: CUR:N/A,N/A,N/A AVG:2420,145247,3485942 (Min,Hour,Day)
Progress.........: 134653935616/134653935616 (100.00%)
Rejected.........: 0/134653935616 (0.00%)
Restore.Point....: 614400/1048576 (58.59%)
Restore.Sub.#2...: Salt:0 Amplifier:128400-128416 Iteration:0-16
Restore.Sub.#3...: Salt:0 Amplifier:128384-128416 Iteration:0-64
Candidates.#2....: sarvzzy5v -> 6ojbzzzzzzzzzzz
Candidates.#3....: sao9zznzbn -> 6o9/zzzzzzzzzzz

Started: Sun Nov 10 01:16:34 2019
Stopped: Sun Nov 10 01:17:52 2019



➜  hashcat git:(master) ✗ ./example400.sh
hashcat (v5.1.0-1428-g11c8a404) starting...

OpenCL API (OpenCL 1.2 (Oct  2 2019 00:43:05)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 550, 384/1536 MB allocatable, 48MCU
* Device #3: AMD Radeon Pro 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 1106 MB

Starting attack in stdin mode...

$H$9y5boZ2wsUlgl2tI6b5PrRoADzYfXD1:hash234
Session..........: hashcat
Status...........: Cracked
Hash.Name........: phpass
Hash.Target......: $H$9y5boZ2wsUlgl2tI6b5PrRoADzYfXD1
Time.Started.....: Sun Nov 10 01:21:45 2019 (0 secs)
Time.Estimated...: Sun Nov 10 01:21:45 2019 (0 secs)
Guess.Base.......: Pipe
Speed.#2.........:        0 H/s (0.00ms) @ Accel:16 Loops:32 Thr:64 Vec:1
Speed.#3.........:   575.7 kH/s (5.56ms) @ Accel:64 Loops:256 Thr:64 Vec:1
Speed.#*.........:   575.7 kH/s
Recovered........: 1/1 (100.00%) Digests
Progress.........: 128416
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-32
Restore.Sub.#3...: Salt:0 Amplifier:0-1 Iteration:1792-2048
Candidates.#2....: [Copying]
Candidates.#3....: 0 -> zzzzzzzzzzz
Started: Sun Nov 10 01:21:26 2019
Stopped: Sun Nov 10 01:21:45 2019


➜  hashcat git:(master) ✗ ./example500.sh
hashcat (v5.1.0-1428-g11c8a404) starting...

OpenCL API (OpenCL 1.2 (Oct  2 2019 00:43:05)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 550, 384/1536 MB allocatable, 48MCU
* Device #3: AMD Radeon Pro 580 Compute Engine, 2048/8192 MB allocatable, 36MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 1106 MB

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416

$1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1:hash234       
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Name........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: $1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1
Time.Started.....: Sun Nov 10 01:22:29 2019 (0 secs)
Time.Estimated...: Sun Nov 10 01:22:29 2019 (0 secs)
Guess.Base.......: File (example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:    13806 H/s (9.11ms) @ Accel:16 Loops:3 Thr:64 Vec:1
Speed.#3.........:    82032 H/s (10.47ms) @ Accel:4 Loops:125 Thr:64 Vec:1
Speed.#*.........:    95838 H/s
Recovered........: 1/1 (100.00%) Digests
Progress.........: 27648/128416 (21.53%)
Rejected.........: 0/27648 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:99-102
Restore.Sub.#3...: Salt:0 Amplifier:0-1 Iteration:875-1000
Candidates.#2....: 0 -> bu3um
Candidates.#3....: ghost324 -> jim01

Started: Sun Nov 10 01:22:20 2019
Stopped: Sun Nov 10 01:22:30 2019

**Comment by jsteube** [comment]
We successfully fixed a similar problem on OSX + Vega GPU. Maybe it helps for this issue as well. Please retry with new GitHub master version and make sure to have the kernels/ kernel cached removed first.

**Comment by soxrok2212** [comment]
Sorry for taking a bit to get back, was enjoying the holidays :) I just did a quick, raw speed test (laptop is currently busy with something else that has it pinned circa 100°C, so there was likely throttling going on, but here are the results:
```
$ hashcat -m 2500 -b -d 3 -w 4   
hashcat (v5.1.0-1527-g80a87212) starting in benchmark mode...

OpenCL API (OpenCL 1.2 (Nov  9 2019 04:32:50)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz, skipped
* Device #2: Iris Pro, skipped
* Device #3: AMD Radeon R9 M370X Compute Engine, 1984/2048 MB (512 MB allocatable), 10MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --workload-profile=4

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

Speed.#3.........:    26913 H/s (378.24ms) @ Accel:64 Loops:256 Thr:256 Vec:1

Started: Mon Dec 30 14:22:45 2019
Stopped: Mon Dec 30 14:22:55 2019
```

It used to be around 30-33kH/s but for now, I'll attribute it to the CPU causing too much heat. I'll do a real test later on, but just wanted to get you some feedback on this ASAP. This was on macOS Catalina, 10.15.2.

**Comment by emwinkler** [comment]
The reason you see poorer performance is Apple has not provided the best OpenCL drivers (OpenCL 1.2), so that is why you see the performance drop.  For example, I get 343.5 kH/s from my Vega64 eGPU on Catalina 10.15.2, but on the exact same hardware under Ubuntu  18.04 (with OpenCL 2.1) I get 522.4 kH/s.

As Apple wants everyone to use Metal2, I don't think the state of OpenCL under macOS will change anytime soon.

**Comment by philsmd** [comment]
@derhornspieler We would really need your confirmation to confirm this problem is really fixed now.
We got some positive feedback from at least 2 people (@emwinkler and @soxrok2212 , I'm a little bit confused how @soxrok2212 is involved in this issue because as far as I see it's his/her first answer here, therefore "Sorry for taking a bit to get back" is confusing to me).
I've no clue if @derhornspieler , @emwinkler and @soxrok2212 are testing with the same hardware and operating system (driver version might probably also make a difference if there are updates between OS versions) and therefore we can't be sure whether we can close this issue.

I would suggest to wait a little bit for an answer from @derhornspieler and if some weeks pass without any updates here, we might just hope that everything is working with the update and close this... dunno if that is a good idea.... but a confirmation from the OP would always be preferred

**Comment by derhornspieler** [comment]
@philsmd I'm good.  Ended upgrading to 10.15 and a newer AMD card.  Issue can be closed as it is not throwing any errors on the benchmark tests.  Apologies for taking so long to reply.
