### ISSUE TITLE
Can't decrypt this PDF hash

### ISSUE THREAD

**Issue by its5Q** [hashcat/hashcat#2087]
Hi guys, I have a problem.I have a PDF and I know that it's password is Wn09k1l6b*89az
Where * is one to four characters from ?a charset. However, I couldn't bruteforce it. I extracted the hash from PDF using pdf2john.pl. But the hash is kind of special. I couldn't find it in Google
It's 
`$pdf$4*4*128*-4*1*16*0f03ecb09291a6458783ee605e605847*32*a4dca077eb5a64f8d1aa7e41342ff4b300000000000000000000000000000000*32*d5878297b42bb0e6e45a03c63938aceedbd61f445256b414d806b0eadd4e1a1b`
The version of the PDF is 1.6, according to the header.
What is makes it so special is that instead of the number 1024 that those hashes usually have afted the dash, it has number 4. I just can't figure out how to bruteforce this thing. Can someone help me please?

**Comment by philsmd** [comment]
but what is the problem? do you receive any error message ? ... or is the status just "exhausted" ?

How should we test this if you don't provide the password ? Devs aren't really into the game of cracking hashes for the users here. so please provide all the details

btw. the hashes load perfectly fine with -m 10500 (I'm testing with beta version from https://hashcat.net/beta but the release version and git version should work as well. no major changes that would influence this)

**Comment by its5Q** [comment]
Turns out my mask was wrong, sorry, I got this to work. Thanks!
