### ISSUE TITLE
Building Errors... <gmp.h>

### ISSUE THREAD

**Issue by mskim77** [hashcat/hashcat#21]
I report Building Errors...

make: i686-w64-mingw32-gcc: Command not found
make: *** [obj/common.WIN.32.o] Error 127
make: *** Waiting for unfinished jobs....
In file included from src/common.c:6:0:
include/common.h:30:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
                 ^
compilation terminated.
make: *** [obj/common.LINUX.32.o] Error 1

**Comment by epixoip** [comment]
You didn't install all of the build dependencies.
