### ISSUE TITLE
[Alg Request] SHA256(MD5('password'))

### ISSUE THREAD

**Issue by vido89** [hashcat/hashcat#2103]
This algorithm is used on Huawei routers to encrypt user passwords can we have it on hashcat ?

**Comment by philsmd** [comment]
How can you **encrypt** passwords with a hashing algorithm ? Can you explain the details ?

**Comment by vido89** [comment]
I gues I used bad terminology.
So I go here https://md5hashing.net/hash and paste my hash "402931e04c03e24d360477a9f90b9eb15777e154360f06228be15c37679016ef" and I got I guess un-hashed string and paste it here https://hashtoolkit.com/reverse-hash?hash=a016b28a2669f876cc24e9b3dac1bd73 and I got clear text password

**Comment by vido89** [comment]
Its the same as 4700 | sha1(md5($pass)) just insted `sha1` I need `sha256`

**Comment by matrix** [comment]
@vido89 I'm pushing the new algo. Have you time to test it?

**Comment by vido89** [comment]
sure I will be glade to test it

**Comment by matrix** [comment]
Try using the following repository, the only that not working it's a3 with -O (i'm debugging), the others works

https://github.com/matrix/hashcat/tree/sha256_md5_huawei

Let me know :)

**Comment by matrix** [comment]
fixed -a3 -O :)

**Comment by vido89** [comment]
Great it works
./hashcat -m 4710 -a 3 -i --increment-min=6 --increment-max=10 402931e04c03e24d360477a9f90b9eb15777e154360f06228be15c37679016ef ?l?l?l?l?l?l?l?l?l?l

Edit: Tnx a lot

**Comment by jsteube** [comment]
Added support with PR: https://github.com/hashcat/hashcat/pull/2110

Note: Mode was changed from 4710 to 20800

**Comment by collerok** [comment]
for those come there to findout whats the password hidden for user telecomadmin and hash is 

402931e04c03e24d360477a9f90b9eb15777e154360f06228be15c37679016ef

password is:    **admintelecom**
