### ISSUE TITLE
Can dictionary cracking be used on brain servers?

### ISSUE THREAD

**Issue by doudio** [hashcat/hashcat#2114]
> Can dictionary cracking be used on brain servers?

> In the case of keeping the dictionary on each node consistent

> what are the optimization parameters for dictionary cracking that I currently use in official documents: -O and -c 1024

> What other optimization parameters can be set for dictionary cracking

**Comment by philsmd** [comment]
these type of questions should be searched (and if nothing found posted) on the hashcat forum.

of course brain also works with -a 0, but it doesn't always make sense depending on the speed and hash type. the usage of brain is better suited for slow hash types (like bcrypt, pbkdf2 etc)

Please close and ask on forum

**Comment by doudio** [comment]
> these type of questions should be searched (and if nothing found posted) on the hashcat forum.
> 
> of course brain also works with -a 0, but it doesn't always make sense depending on the speed and hash type. the usage of brain is better suited for slow hash types (like bcrypt, pbkdf2 etc)
> 
> Please close and ask on forum

Well, thank you
