### ISSUE TITLE
attack-mode 6 and 7 broken in master

### ISSUE THREAD

**Issue by jackschmidt** [hashcat/hashcat#2117]
One gets the error message "Integer overflow detected in keyspace of mask" for all non-huge keyspaces due to a copy-paste typo in [src/mpsp.c line 1235](https://github.com/hashcat/hashcat/commit/013b914e2240220dd854bcf30e691a2f3dafd027#diff-22610ad22085d5eaa33f122303492fe0R1235) from commit 013b914e2240220dd854bcf30e691a2f3dafd027
The error message is not shown if the error condition actually occurs.

**Comment by matrix** [comment]
Fixed in #2100 but not merged yet

**Comment by jackschmidt** [comment]
Merged! :-)

**Comment by jeky--** [comment]
./hashcat -O -a 6 -m 1000 --username NTLM_all.txt ../Dizionari/Italian-Words.txt ?a?a?a?a?a
Integer overflow detected in keyspace of mask: ?a?a?a?a?a

This with hashcat 6.1.1. While using 5.1.1 or 4.2.1 it works, and the task takes less than 2 days.
May be there is a bug, in the fix?
