### ISSUE TITLE
CUDA installation not found

### ISSUE THREAD

**Issue by its5Q** [hashcat/hashcat#2126]
I've installed the latest CUDA Toolkit from Nvidia website, but hashcat is unable to use it. Here is the output:

`* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL API (OpenCL 1.2 CUDA 10.1.152) - Platform #1 [NVIDIA Corporation]`

However, it says OpenCL 1.2 CUDA 10.1.152 so I don't know why it doesn't work. 
I'm using freshly compiled version of hashcat from github branch authme_1.

**Comment by matrix** [comment]
Hi @lev4ukpavel2 , follow the link to disable timeout and/or try the hashcat forum for this kind of questions. Please remember to close this issue.
Thanks
