### ISSUE TITLE
install hashcat on Ubuntu 18.4 not sucsess

### ISSUE THREAD

**Issue by khanfar** [hashcat/hashcat#2130]
im trying to install hash cat in ubuntu 18.4 but not sucsess by this command :
sudo apt install hashcat

after that it show done ! but when try to type cd hashcat . it tell me no directory ! Help what im missing????   when try test by this command : 
 sudo hashcat --benchmark   i got error !!!! HELP

**Comment by doudio** [comment]
## install HashCat

```shell
apt install git

git clone https://github.com/hashcat/hashcat.git
cd hashcat

sudo make 
sudo make install
```

**Comment by jsteube** [comment]
Please ask on Forum

**Comment by doudio** [comment]
> Please ask on Forum

Okay, I just posted some questions about brain services on the forum.

Hope to find the answer
