### ISSUE TITLE
Salt length in 4710 not dynamic

### ISSUE THREAD

**Issue by jsteube** [hashcat/hashcat#2148]
In file: https://github.com/hashcat/hashcat/blob/master/tools/test_modules/m04710.pm

```
sub module_constraints { [[0, 256], [0, 256], [0, 55], [8, 8], [-1, -1]] }
```

Salt length 8, 8 should be 0, 15. Eventually requires additional fixing of optimized kernels, too.

**Comment by matrix** [comment]
optimized kernels should be fine ;)
