### ISSUE TITLE
request for NetWitness / RSA Security Analytics

### ISSUE THREAD

**Issue by truekonrads** [hashcat/hashcat#215]
Hello,

I would like to request a feature to crack passwords that are generated using this Python expression:
sha256(sha256("mypassword").hexdigest().upper()+gsalt).hexdigest().upper()

gsalt is a binary string

Or if there is a gentle introduction on how to add this, I can give it a crack

**Comment by jsteube** [comment]
Please read this this:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

Please answer on all the points listed

**Comment by truekonrads** [comment]
Algorithm name: NetWitness / RSA Security Analytics

In use for NetWitness and RSA Security Analytics, can be found in /etc/netwitness/nw/*.cfg. 

There are a few variants, a SHA1 variant, SHA256 variant and also a challenge-response variant which hashes the salted password hash with a challenge.

The password hash can be created using this Python code:

```
pwdhash=sha256(sha256(password).hexdigest().upper()+gsalt.decode('base64')).hexdigest().upper()
```

The challenge-response mode can be created like so:

```
sha256("netwitness"+pwdhash+srvhash).hexdigest().upper()
```

**Comment by matrix** [comment]
added hash-mode 20712
