### ISSUE TITLE
Misleading message of number of salts

### ISSUE THREAD

**Issue by mitar** [hashcat/hashcat#2152]
I think the number of salts to search is misleading:

```
Session..........: hashcat
Status...........: Running
Hash.Type........: MD5
...
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
```

I am using MD5 hash type on only one digest. Why it says that it is searching also for 1 salt? I think this is invalid. MD5 hash type does not have salt?

**Comment by jsteube** [comment]
This is because of some internal structure. There's always one salt even on unsalted hashes. It's an empty one. How would you ideally like to see it resolved?

**Comment by mitar** [comment]
Maybe:

```
Recovered........: 0/1 (0.00%) Digests, 0/0 (0.00%) Salts
```

Or:

```
Recovered........: 0/1 (0.00%) Digests, 1/1 (100.00%) Salts
```

So the main point for me is that it should look like there is no more work necessary to be done for salts. Or there are no salts to search over, or all are known (a salt of an empty string or something).

**Comment by jsteube** [comment]
The suggestions also feel kind of misleading. If the goal is to rule out any misleading status information, this is not much better than how it is now.

The only real solution would be to not print out that substring related to salt in general. What you think?

**Comment by mitar** [comment]
> The only real solution would be to not print out that substring related to salt in general. What you think?

What would be of course the best. Yes.

**Comment by jsteube** [comment]
Added with commit 0b0de6a28380e5270705b1ee17ebc6689d61a312

**Comment by f0cker** [comment]
Presumably salts_cnt will never be removed from the internal status? I'm using it.

**Comment by jsteube** [comment]
No worries, it's just a change in the visual representation.

**Comment by f0cker** [comment]
cool, just checking :)
