### ISSUE TITLE
7zip  Token length exception hashcat 5.1.0

### ISSUE THREAD

**Issue by JimmyWarHammer** [hashcat/hashcat#2154]
[hash.txt](https://github.com/hashcat/hashcat/files/3473279/hash.txt)
I have 7-zip file with encoded headers as well.
Archive length is 1340195291 bytes

7z2hashcat64-1.3.exe generated hash length of 27514 bytes (attached)
Running hashcat 5.1.0 gives (5.0.0 is the same):

>C:\bin\hashcat\hashcat-5.1.0>hashcat64 -m 11600 -a 0 hash.txt -r rules/best64.rule --force
>hashcat (v5.1.0) starting...
>
>OpenCL Platform #1: Advanced Micro Devices, Inc.
>= ===============================================
>* Device #1: Hawaii, 4048/8192 MB allocatable, 44MCU
>
>Hashfile 'hash.txt' on line 1 ($7z$1$...ed61769335a4ef$123602$5d00000200): Token length exception
>No hashes loaded.
>
>Started: Tue Aug 06 19:36:33 2019
>Stopped: Tue Aug 06 19:36:33 2019

**Comment by jsteube** [comment]
This is fixed in latest beta version. You can either clone and compile from master repository or use the binary from https://hashcat.net/beta/
