### ISSUE TITLE
FreeBSD undefined reference to libiconv

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2162]
Latest github fails to compile for me on FreeBSD. I ran `git submodule update --init`, and I also have libiconv installed. I'm using GCC, because clang build was giving many errors (I can open a new issue for that if needed)

$ uname -r
11.3-RELEASE-p2

$ pkg info | grep libiconv
libiconv-1.14_11               Character set conversion library

$ gcc --version | head -n 1
gcc (FreeBSD Ports Collection) 9.1.0

$ cc --version ( <----- not used - just including for reference)
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
Target: x86_64-unknown-freebsd11.3
Thread model: posix
InstalledDir: /usr/bin

[...]
```
gcc    -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib/ -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash src/modules/module_10800.c obj/combined.NATIVE.a -o modules/module_10800.so  -s -lpthread -lm -shared -fPIC -D MODULE_INTERFACE_VERSION_CURRENT=520
/usr/local/bin/ld: obj/combined.NATIVE.a(backend.NATIVE.o): in function `run_cracker':
backend.c:(.text+0x8526): undefined reference to `libiconv'
/usr/local/bin/ld: backend.c:(.text+0x8666): undefined reference to `libiconv_open'
/usr/local/bin/ld: backend.c:(.text+0x8972): undefined reference to `libiconv'
/usr/local/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `get_next_word.localalias':
wordlist.c:(.text+0x3b1): undefined reference to `libiconv'
/usr/local/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `count_words':
wordlist.c:(.text+0xa20): undefined reference to `libiconv'
/usr/local/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `wl_data_init':
wordlist.c:(.text+0xedb): undefined reference to `libiconv_open'
/usr/local/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `wl_data_destroy':
wordlist.c:(.text+0xf45): undefined reference to `libiconv_close'
/usr/local/bin/ld: obj/combined.NATIVE.a(dispatch.NATIVE.o): in function `calc_stdin':
dispatch.c:(.text+0x25a): undefined reference to `libiconv'
/usr/local/bin/ld: dispatch.c:(.text+0x477): undefined reference to `libiconv_open'
/usr/local/bin/ld: dispatch.c:(.text+0x4a6): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
```

**Comment by roycewilliams** [comment]
Update: @philsmd helped me track this down to a couple of tweaks to be added to the Makefile. I've pinged the current FreeBSD ports maintainer for hashcat about both this and the impending 6.0.0 release, and I'm waiting a bit to hear back from him before submitting a PR for this.

**Comment by roycewilliams** [comment]
I got in touch with the FreeBSD maintainer (@lifanov) - he is looking at striking a balance between the needs of the FreeBSD ports system and the ability to compile natively on FreeBSD outside the ports system.

**Comment by jsteube** [comment]
Any update?

**Comment by roycewilliams** [comment]
Pinging @lifanov - if no cycles for this soon, let us know so that atom can proceed with alternatives

**Comment by roycewilliams** [comment]
@jsteube, @philsmd - maintainer timeout from @lifanov - please do whatever needs to be done to work around this.
Just so I don't lose it, here's the simple workaround that philsmd and I tested a while back, which worked at the time:
```
LFLAGS_NATIVE           += -liconv
LFLAGS_NATIVE           += -L/usr/local/lib
```
This isn't optimal for working nicely with the FreeBSD port - but it will have to do until more Round Tuits are available.

**Comment by philsmd** [comment]
hmm, I'm wondering now if `LFLAGS_NATIVE += -L/usr/local/lib` is really needed, shouldn't this be a standard library path.

Could you please test with and without it and see if it works also without it for you @roycewilliams  ?  Thx

**Comment by roycewilliams** [comment]
This does address the iconv issue as far as I can tell. I'm having trouble getting pocl to work on my test system, so if there are any issues there, they will have to be solved later.
