### ISSUE TITLE
ubuntu 14.04 make error libiconv not found

### ISSUE THREAD

**Issue by changchichung** [hashcat/hashcat#2168]
OS: ubuntu 14.04 x64

I already install libiconv-1.16 , but when I try to make hashcat , there`s still an error message

```
FOLDER=\"/usr/local/bin\" -DSHARED_FOLDER=\"/usr/local/share/hashcat\" -DDOCUMENT_FOLDER=\"/usr/local/share/doc/hashcat\"
obj/dispatch.NATIVE.STATIC.o: 於函式 calc_stdin:
dispatch.c:(.text+0x53b): 未定義參考到 libiconv
dispatch.c:(.text+0x6a1): 未定義參考到 libiconv_open
dispatch.c:(.text+0x6f6): 未定義參考到 libiconv_close
obj/opencl.NATIVE.STATIC.o: 於函式 run_cracker:
opencl.c:(.text+0x496f): 未定義參考到 libiconv
opencl.c:(.text+0x4d65): 未定義參考到 libiconv
opencl.c:(.text+0x4f35): 未定義參考到 libiconv_open
obj/wordlist.NATIVE.STATIC.o: 於函式 get_next_word:
wordlist.c:(.text+0x3ba): 未定義參考到 libiconv
obj/wordlist.NATIVE.STATIC.o: 於函式 count_words:
wordlist.c:(.text+0xabf): 未定義參考到 libiconv
obj/wordlist.NATIVE.STATIC.o: 於函式 wl_data_init:
wordlist.c:(.text+0xef0): 未定義參考到 libiconv_open
obj/wordlist.NATIVE.STATIC.o: 於函式 wl_data_destroy:
wordlist.c:(.text+0xfbd): 未定義參考到 libiconv_close
collect2: error: ld returned 1 exit status
make: *** [hashcat] Error 1
```
any suggestions ?

**Comment by philsmd** [comment]
hey,

I think 14.04 is already quite old but in theory should work nonetheless.

The problem might be that (as far as I just found on the internet) there are multiple implementation of iconv (GNU vs glibc) and you might have the wrong one installed (and maybe even a too old one, dunno).

I would say that you should try to get rid of libiconv or libiconv-1.16 (apt-get purge  libiconv-1.16 libiconv) and instead try with the iconv.h provided by the libc6-dev (or similar) package.

On ubuntu you could try to find out which package ships a specific file with apt-file (for instance):
```
apt-file search /usr/include/iconv.h
```

I would say that this is definitely not really a hashcat "bug" but some kind of very specific install/package problem with you specific (old) ubuntu version. It's important that the iconv.h file contains/declares the functions "libiconv_open", "libiconv_close" etc. If the iconv.h you have installed on your system doesn't declare these functions, it's probably the wrong one (alternative implementation GNU vs glibc) or too old.
