### ISSUE TITLE
Cuda mode crack 9700hash failed, opencl succeeded.

### ISSUE THREAD

**Issue by gs135269** [hashcat/hashcat#2170]
I used cuda mode to crack 9700 hash failure, using opencl to crack successfully. My ucda version 10.1. This 

```
hash:$oldoffice$0*1042089a9ee7e9f42ed9e5a15330465c*17af93556e41b13f3195825a945c2f60*15cd3b5058af0356fdfaba39ca18258c
```

hashcat version：5.1.0+1384

**Comment by jsteube** [comment]
This instantly cracks to me on both OpenCL and CUDA. Can you please make sure to not use an old kernel cache?

On linux, please remove folder "kernels" and (more important) "$HOME/.nv". Then try again.

**Comment by gs135269** [comment]
> This instantly cracks to me on both OpenCL and CUDA. Can you please make sure to not use an old kernel cache?
> 
> On linux, please remove folder "kernels" and (more important) "$HOME/.nv". Then try again.

I did the test on windows10, 

```
$oldoffice$0*1042089a9ee7e9f42ed9e5a15330465c*17af93556e41b13f3195825a945c2f60*15cd3b5058af0356fdfaba39ca18258c  the password for this hash is 1350266924
```

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/f3fd54f8b47325863f59cc7097314b483357acd3

Can you please verify and confirm?

**Comment by philsmd** [comment]
I think we should close this. No answer from original author.

btw: it also seems that this has absolutely nothing to do with OpenCL vs CUDA, because the kernel code is the exact same and some code was just missing (again, of course, for both CUDA and OpenCL) !

please close

**Comment by gs135269** [comment]
$oldoffice$0*1042089a9ee7e9f42ed9e5a15330465c*17af93556e41b13f3195825a945c2f60*15cd3b5058af0356fdfaba39ca18258c

password:1350266924

This problem was discovered in the real test. Please test this hash, please use cuda and opencl respectively.
The result I got was that opencl could be cracked correctly.
Cuda can't crack successfully.

I want to know where the problem is, why can't I use cuda's hashcat to crack it?

If there is no answer, I will turn it off after a few days.

**Comment by philsmd** [comment]
which versions of hashcat are you trying ? Are you comparing with 2 different versions of hashcat ?
Did you try to test with the patch from above ?

Can you share the office document too ?

**Comment by gs135269** [comment]
hashcat version：5.1.0+1384，

**Comment by philsmd** [comment]
for me it cracks with password QQ123456

I do not think that the beta version already contains the patch (the patch is above and just from a few days ago. therefore not fixed in beta yet. just try the patch directly from git).
