### ISSUE TITLE
Hashcat not detecting NVIDIA GPU?

### ISSUE THREAD

**Issue by 766F6964** [hashcat/hashcat#2171]
```
OS: Linux x64, (Manjaro, Kernel: 4.19.62-1-MANJARO)
GPU : Nvidia GeForce GTX 980 Ti
CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz 
Hashcat Version: 5.1.0
```

I've installed _opencl-nvidia_, however hashcat does not detect my GPU, only the CPU. What package is required to make sure that hashcat can utilize my GPU? The latest nvidia drivers are installed too..

```
void@void-pc :: ~ $ hashcat -I
hashcat (v5.1.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Intel(R) Corporation
  Name    : Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version : OpenCL 2.1 LINUX

  Device ID #1
    Type           : CPU
    Vendor ID      : 8
    Vendor         : Intel(R) Corporation
    Name           : Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Version        : OpenCL 2.1 (Build 0)
    Processor(s)   : 4
    Clock          : 3500
    Memory         : 3992/15970 MB allocatable
    OpenCL Version : OpenCL C 2.0 
    Driver Version : 18.1.0.0920
```

**Comment by philsmd** [comment]
does nvidia-smi work for you.
what is the clinfo output ?

it could also be that just the icd is missing like "ocl-icd-libopencl1" on ubuntu, but as far as I know the nvidia driver if downloaded from https://www.nvidia.com/Download/index.aspx ships with all the parts needed including ICD etc.

**Comment by ZerBea** [comment]
This software must be installed via pacman:
nvidia 430.40
opencl-nvidia 430.40
cuda 10.1.243
opencl-headers

Additional you can install this packages, too:
nvidia-settings 430.40
nvidia-utils 430.40

If you're on the LTS kernel, choose the LTS version of tha driver package.

BTW:
95% of Manjaro packages come from Arch Linux.
I'm running Arch (GTX 970 and GTX 1080). Everything is running fine, out of the box

**Comment by 766F6964** [comment]
Thanks for replies. The issue was a mismatch between the versions of the opencl package and the NVIDIA driver.
