### ISSUE TITLE
Mask slice of distributed systems 

### ISSUE THREAD

**Issue by kedpter** [hashcat/hashcat#2172]
I wrote a [script](https://github.com/kedpter/mask_slice) to divide a mask into chunks by calculating the node speed. After i finished the script, it turns out there already is a built-in option called `--keyspace`. But keyspace in hashcat seems not to be what we usually understand. `?a?a` turns out to be 95 somehow. It's weird. Maybe someone can explain how you calculate that ?

**Comment by roycewilliams** [comment]
This is more of a question for the hashcat forums, but:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace

So yeah, it's complicated. :) If you have further questions about it, please post your question to the forums.
