### ISSUE TITLE
error: redefinition of typedef ‘Byte’ in complie

### ISSUE THREAD

**Issue by L3ss-dev** [hashcat/hashcat#2174]
'deps/LZMA-SDK/C/7zTypes.h:66' and 'deps/zlib/zconf.h:391' had the same define of Byte.

**Comment by jsteube** [comment]
This is a known issue, but so far we do not know how to work around this without modifying original sources from depending libraries. However, it has no influence on hashcat.

**Comment by L3ss-dev** [comment]
> 
> 
> This is a known issue, but so far we do not know how to work around this without modifying original sources from depending libraries. However, it has no influence on hashcat.

But when I try to 'make',I got a error,how can I fix it?
![图片](https://user-images.githubusercontent.com/12406796/63757632-05b40900-c8ed-11e9-8c4d-83c4589e4038.png)

**Comment by L3ss-dev** [comment]
That's my fault,close this inssue
