### ISSUE TITLE
electrum 2 hash definition

### ISSUE THREAD

**Issue by benjiqq** [hashcat/hashcat#2175]
How do I got from wallet file with "xprv" to the format of `$electrum$1*XXXXXX` ? hashcat expects hexstring? in the docs it gives the example. not clear to me what $1 and salt-type stands for and how to get that info from my wallet file.

`16600 | Electrum Wallet (Salt-Type 1-3) | $electrum$1*4435828310460316538361367258686*c43a6632d9f59364f74c395a03d8c2e
`

**Comment by benjiqq** [comment]
utility 
https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/electrum2john.py

**Comment by philsmd** [comment]
is this problem solved ?
If yes, please close it, otherwise it's very confusing and not clear if solved (furthermore, only original author of the issue and admin can close the issue)

**Comment by benjiqq** [comment]
@philsmd I don't understand your point. more documentation would be helpful IMO. $1 refers to version 1 I believe. I'm leaving this issue as reference to potentially doc this.

**Comment by jsteube** [comment]
confusing issue, problem description is not clear
