### ISSUE TITLE
Can only find one hash of two - Office 2010 - mode 9500

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#2179]
Hashcat (v5.1.0-1394-g0063bc72) is not able to crack multiple Office2010-hashes with same salt which are stored in one file; it only cracks one.

I had exactly the same issue with `-m 9600` a couple months ago (see here: https://github.com/hashcat/hashcat/issues/1826), which got fixed by @Naufragous 

(Example hashes can be given on request)

**Comment by Chick3nman** [comment]
This issue has been fixed in https://github.com/hashcat/hashcat/pull/2181

**Comment by jsteube** [comment]
Merged
