### ISSUE TITLE
Request build doc for RHEL/CENTOS 6.x/7.x

### ISSUE THREAD

**Issue by Vladinatrix** [hashcat/hashcat#218]
Debian and Ubuntu are great and all, but some of us have to use RHEL and CENTOS. Build docs for that platform would be awesome.

**Comment by epixoip** [comment]
Cool, go ahead and make one and submit a PR.

**Comment by jsteube** [comment]
With latest version from github, it should build out of the box by simplying running make. There's no more depencies now (unless you start cross compiling).

**Comment by jsteube** [comment]
@Vladinator Any update here?

**Comment by Vladinatrix** [comment]
No, sorry, I have had zero time to work on this. It is going to take me
some time, both because I am very unfamiliar with the project and it's
components, and because I have to do it off the clock in my personal time.

## 

W. Scott Lockwood III

**Comment by jsteube** [comment]
I've successfully build on RHEL 6.x with latest gihub version. It's simple as it can be. 1. git clone 2. make 3. fun

**Comment by Vladinatrix** [comment]
Rock on! Thanks man!
