### ISSUE TITLE
Use hashcat to crack the unusual "DF" length of winzip.hash

### ISSUE THREAD

**Issue by H-xYDdd** [hashcat/hashcat#2192]
Hi, 
I am the new guy to use the hashcat. I was comfused a problem.
I used `zip2john` to build a `winzip.hash`. But the bigger my `win.zip` is , the bigger my `winzip.hash` is.This will result in an error`( Token length exception )` when cracking large `winzip.hash` using hashcat.
> root@test:~/test/tmp# ls -sh
4K pwd_10086.hash <---- 4K pwd_10086.zip
20K file.hash <---- 12K file.zip
308M password_1_0.hash <---- 154M password_1_0.zip   

`Test hashcat cracked 20K size file.hash :`
>   root@test:~/test/tmp# hashcat -a 3 -m 13600 file.hash ?d?d?d?d?d?d
hashcat (v5.1.0-1183-g32cb1918+) starting...
OpenCL API (OpenCL 1.2 LINUX) - Platform 1 [Intel(R) Corporation]
================================================================
*Device 1: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, skipped
OpenCL API (OpenCL 2.1 AMD-APP (2901.0)) - Platform 2 [Advanced Micro Devices, Inc.]
================================================================
*Device 2: gfx803, 6963/8192 MB allocatable, 32MCU
Hashfile 'file.hash' on line 1 ($zip2$...acc*920599cfe7204be1e140*$/zip2$): **`Token length exception`**
No hashes loaded.
Started: Fri Sep 20 12:06:00 2019
Stopped: Fri Sep 20 12:06:01 2019

`Test hashcat cracked 4K size pwd_10086.hash : `
> root@test:~/test/tmp# hashcat -a 3 -m 13600 --show pwd_10086.hash ?d?d?d?d?d
$zip2$*0*3*0*b97ae4185178f04f8525e1e7254c9bb1*546d*1*bb2dd087e0414b2a3ae7fa2d5af3cdde1badca193575faa4ed87b404d06f23*2cdedefc32485078048c*$/zip2$:10086

I checked that the `token.len_max[7]` was too small ( only have 16384 ) in `module_13600.c`. But I changed this parameter，it doesnt work 😭.
How can i solve this problem ? 
Looking forward to solving this problem. Thanks a lot :) !

**Comment by philsmd** [comment]
I would say this problem is exactly the same as https://github.com/hashcat/hashcat/issues/2186#issuecomment-530489997

The data length is just way too long. 8K are supported but your 154MB or 12KB are above the limit
