### ISSUE TITLE
[Feature Request] SIP Digest with Base64(Password)

### ISSUE THREAD

**Issue by jtoddowen** [hashcat/hashcat#2194]
SIP Digest Authentication (hash-mode 11400) works well for HTTP Digest Access Authentication; however, my passwords are Base64 encoded.  Therefore, I would like a hash mode, say 11410, which simply Base64 encodes the password (including the “=“ padding) before the MD5(username:realm:password) calculation.  This way I can use the standard password mask functions **before** the Base64 encoding, and the passwords found will be unencoded.

**Comment by philsmd** [comment]
but why base64 ? where is this used in ? any popular CMS etc is using it ? does the addition of this feature really makes sense for many hashcat users ? or is that request very, very specific to your case ? in theory it could be any conversion, even hex instead of base64 etc.... so why should the algorithm use an additional base64 conversion ? it doesn't seem to be the standard way of doing SIP

**Comment by jtoddowen** [comment]
I use the "SIP" hash on HTTP Digest Access Authentication use cases.    When @yangusmerdock asked "Can you add new algo sha1(md5(md5($password))) for my own specific purpose?" in [#1652](https://github.com/hashcat/hashcat/issues/1652) @jsteube added it in [merge #1814](https://github.com/hashcat/hashcat/pull/1814).

Why Base64?  This just happens to be how a JavaScript package I've used does it.  I'm not sure how pervasive it is for HTTP DAA.

If I understood the code more, I would just hack a change, maybe just to a copy of the `m11400_a3-pure.cl` file to add the conversion.  If someone could give me insight into where I should do this, I'd be glad to try.  Meaning, should I change `module_11400.c` or the OpenCL file.  Several C modules have Base64 encoding code included, but `m09100-pure.cl` is the only OpenCL file with a Base64 reference.

I'm willing to attempt this myself if someone could point me in the right direction.

**Comment by jtoddowen** [comment]
@philsmd would the change need to be made to `m11400_a3-pure.cl` module?  Any comments on the code below?

```
/* Standard Base64 symbol index table from Wikipedia
 */
CONSTANT_VK u32a base64_table[64] =
{
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
  'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
  'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
  'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
  'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
  'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
  'w', 'x', 'y', 'z', '0', '1', '2', '3',
  '4', '5', '6', '7', '8', '9', '+', '/',
};

DECLSPEC void base64_encode (u8 *base64_hash, const u32 len, const u8 *base64_plain)
{
  u8 *out_ptr = (u8 *) base64_hash;
  u8 *in_ptr  = (u8 *) base64_plain;

  u32 i;

  for (i = 0; i < len; i += 3)
  {
    const u8 out_val0 = base64_table [                            ((in_ptr[0] >> 2) & 0x3f)];
    const u8 out_val1 = base64_table [((in_ptr[0] << 4) & 0x30) | ((in_ptr[1] >> 4) & 0x0f)];
    const u8 out_val2 = base64_table [((in_ptr[1] << 2) & 0x3c) | ((in_ptr[2] >> 6) & 0x03)];
    const u8 out_val3 = base64_table [                            ((in_ptr[2] >> 0) & 0x3f)];

    /* Add '=' (0x3d) padding to the last (1) or (2) 6-bit blocks if password length
       is not an integer multiple of 3 characters */
    if (i + 3 < len)
    {  /* Do nothing since this isn't the final 4-symbol block of 24 bits. */
    }
    else
    {
      switch(i + 3 - len)
      {
        case 0: /* no padding is required */
                break;
        case 1: out_val3 = 0x3d;
                break;
        case 2: out_val2 = 0x3d;
                out_val3 = 0x3d;
                break;
      }
    }
    
    /* The '& 0x7f' clears the high bit in case it was set for some odd reason. */
    out_ptr[0] = out_val0 & 0x7f;
    out_ptr[1] = out_val1 & 0x7f;
    out_ptr[2] = out_val2 & 0x7f;
    out_ptr[3] = out_val3 & 0x7f;

    in_ptr  += 3;
    out_ptr += 4;
  }
}
```

**Comment by jtoddowen** [comment]
I haven't programmed at this low a level in C for over 30 years, but here's my go at editing `m11400_a3-pure.cl` to add the Base64 functionality.  Comments are appreciated.  *Obviously this edit would not modify the 11400 module, but form the basis for a new one.*

My understanding of the code is that the passwords are mapped into the CL kernel as `pws[gid]` **with all of the mask processing going on elsewhere** at least outside of the `m11400_a3.cl` module.  So my theory was to intercept them, before they're written to their `w[64]` holding place.  I did have to adjust the `pw_len` variable to reflect the additional bytes from the Base64 encoding.  Again **comments are requested.**


```C
  /* Standard Base64 symbol index table from Wikipedia
   */
  CONSTANT_VK u32a base64_table[64] =
  {
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
    'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
    'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
    'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
    'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
    'w', 'x', 'y', 'z', '0', '1', '2', '3',
    '4', '5', '6', '7', '8', '9', '+', '/',
  };

  DECLSPEC void base64_encode (u8 *base64_hash, u32 *hash_len, const u32 len, const u8 *base64_plain)
  {
    u8 *out_ptr = (u8 *) base64_hash;
    u8 *in_ptr  = (u8 *) base64_plain;

    u32 i;

    for (i = 0; i < len; i += 3)
    {
      const u8 out_val0 = base64_table [                            ((in_ptr[0] >> 2) & 0x3f)];
      const u8 out_val1 = base64_table [((in_ptr[0] << 4) & 0x30) | ((in_ptr[1] >> 4) & 0x0f)];
      const u8 out_val2 = base64_table [((in_ptr[1] << 2) & 0x3c) | ((in_ptr[2] >> 6) & 0x03)];
      const u8 out_val3 = base64_table [                            ((in_ptr[2] >> 0) & 0x3f)];
      
      /* The '& 0x7f' clears the high bit in case it was set for some odd reason */
      out_ptr[0] = out_val0 & 0x7f;
      out_ptr[1] = out_val1 & 0x7f;
      
      if (i + 3 < len)  /* if this is the last block, then padding may be necessary */
      {
        out_ptr[2] = out_val2 & 0x7f;
        out_ptr[3] = out_val3 & 0x7f;
      }
      else
      {
        /* Add '=' (0x3d) padding to the last one or two 6-bit blocks if password length
         is not an integer multiple of 3 characters */
        switch(i + 3 - len)
        {
          case 0: out_ptr[2] = out_val2 & 0x7f;
                  out_ptr[3] = out_val3 & 0x7f;
                  break;
          case 1: out_ptr[2] = out_val2 & 0x7f;
                  out_ptr[3] = 0x3d & 0x7f;
                  break;
          case 2: out_ptr[2] = 0x3d & 0x7f;
                  out_ptr[3] = 0x3d & 0x7f;
                  break;
        }
        hash_len = i + 3 - len
      }

      in_ptr  += 3;
      out_ptr += 4;
    }
  }

  u32x w[64] = { 0 };
  u32 pw_len = 0;

  base64_encode (&w, &pw_len, pws[gid].pw_len, &pws[gid]);

/*
  const u32 pw_len = pws[gid].pw_len;

  u32x w[64] = { 0 };

  for (u32 i = 0, idx = 0; i < pw_len; i += 4, idx += 1)
  {
    w[idx] = pws[gid].i[idx];
  }
*/
```

**Comment by philsmd** [comment]
did you test it ? does it work for you ? (btw: do not forget to remove the cached kernels in the kernels/ folder or at least use make clean)

the u32x w to u8 conversion is a bit suspicious/wrong I would say... I don't see this problem in OpenCL/m09100-pure.cl (but the problem might only come to light with different vector-widths, --backend-vector-width).

I would probably also write it a little bit different, without the switch (), but just pad after the main (i < len) loop (i.e. loop again at most 2 times at the end replacing the last chars with "=") depending on the input length... but as long as it works correctly and is fast enough (shouldn't be a bottleneck), you should be fine

**Comment by jtoddowen** [comment]
In `m11400_a3-pure.cl`, can you verify the passwords themselves, not in ?u?l format, are in the `pws` array?  It appears the `pws` array is unpacked into `u32x w[]`, which is practically u32 when vector_size is 1.  It appears each u32 position is a single character, which could have been u8, but I assume for architecture / alignment reasons was set to u32.  Assuming this is true, the code below should do what I want, but it's very, very confusing to follow the original project code with so few comments.  If there is password mangling in here, I can't find it.  I just want to make sure I'm **only** Base64 encoding the final password after all mangling / mask processing is complete.

Can you verify the `actual salt` in the C code and `salt` in the OpenCL code is Hash1 md5(user:realm:password) and `esalt` is md5(Hash1: nonce: nonce_cnt: client_nonce: qop: md5(method:url) )?  This would help a lot.

The code below the function is the only thing I added / changed so there is a conversion in the `raw_pw[]` array prior to loading the passwords into the `w[]` array.

Also, can you please explain what the purpose / difference is between the `_mxx` and `_sxx` functions are in each OpenCL file?  They seem to be identical, in general in all the files.

```c
DECLSPEC void base64_encode (u32 *base64_hash, u32 *hash_len, const u32 len, const u32 *base64_plain)
{
  u32 *out_ptr = (u32 *) base64_hash;
  u32 *in_ptr  = (u32 *) base64_plain;

  u32 i;
  hash_len = 0;

  for (i = 0; i < len; i += 3)
  {
    const u32 out_val0 = base64_table [                                  ((in_ptr[0] >> 2) & 0x0000003f)];
    const u32 out_val1 = base64_table [((in_ptr[0] << 4) & 0x00000030) | ((in_ptr[1] >> 4) & 0x0000000f)];
    const u32 out_val2 = base64_table [((in_ptr[1] << 2) & 0x0000003c) | ((in_ptr[2] >> 6) & 0x00000003)];
    const u32 out_val3 = base64_table [                                  ((in_ptr[2] >> 0) & 0x0000003f)];
    
    /* The '& 0x7f' clears bits 8 and higher in case they're set. */
    out_ptr[0] = out_val0 & 0x0000007f;
    out_ptr[1] = out_val1 & 0x0000007f;
    out_ptr[2] = out_val2 & 0x0000007f;
    out_ptr[3] = out_val3 & 0x0000007f;

    in_ptr  += 3;
    out_ptr += 4;
    hash_len += 4;
  }
  
  /*  If this is the last block, then padding may be necessary if password length
      is not an integer multiple of 3 characters.  Add '=' (0x3d) padding to the 
      last one or two 6-bit blocks if needed. */
  out_ptr -=4;
  if (i - len == 1)
  {
    out_ptr[3] = 0x0000003d;
  }
  else if (i - len == 2)
  {
    out_ptr[2] = 0x0000003d;
    out_ptr[3] = 0x0000003d;
  }
}
//---------------------------------------------------------------------------------------
  u32x raw_pw[64] = { 0 };

  for (u32 i = 0, idx = 0; i < pws[gid].pw_len; i += 4, idx += 1)
  {
    raw_pw[idx] = pws[gid].i[idx];
  }

  /* pw_len is the Base64 encoded length; w[] is the Base64 encoded password */
  u32 pw_len = 0;
  u32x w[64] = { 0 };

  base64_encode (&w, &pw_len, pws[gid].pw_len, &raw_pw);
```

**Comment by philsmd** [comment]
Honestly, I didn't yet understand if you tested the code and if it is working for you. I guess it doesn't.

yeah, but this "const u32 out_val0" is something that you now changed, the code here has the correct type u8 : https://github.com/hashcat/hashcat/blob/7f4df9ebff5937cf852d5012bb9d5ed78529c494/OpenCL/m09100-pure.cl#L282

I'm not sure why you changed out_val0 to u32.


As what regards the second point, yeah it's exactly what I said you need to have u32x to u8x conversions to work for all vector widths. u32x to u8 conversions is not correct/accepted for every vector width >= 2 . This is exactly what I wrote above. so it might work for you with vector width 1, but doesn't work for all other ones.

mxx is for multi hashes, sxx is for a single hash : the hash lookup is very different. one (sxx) is a direct match of some bytes and can have a LOT of optimizations (early rejects for many hash types), the second one (mxx) needs a "vector"/list of hashes for the lookup

**Comment by jsteube** [comment]
Sorry for not commenting too much in these kernels, I know I should. 

First, let's address the difference u32 and u32x (same for u8 and u8x). Those vector datatypes are relevant on GPU only for super fast hashes (like NTLM) or generally if the kernel is supposed to be run on CPU. Other than that they are not as relevant as much as they were in the past when GPUs were pure SIMD architectures (today they are 100% scalar). So my suggestion is to not use vector types and safe a lot of headaches. This is supported by the fact that -m 11400 is a pure kernel anyway (not an optimized one).

The same goes for the u32 packing and unpacking to u8. This forces the JiT to copy the data to shared memory and create overhead code due to pointer arithmetics. However, compared to the rest of the code in the inner loop, this will not lower the performance significantly and I would recommend to simply do u8 * based modification in the kernel.

From best practice perspective I highly recommend adding a unit test to tools/test_modules/. This will also increase your confidence in your own kernel which gives you a much better feeling if you run this kernel over a long time period.

I hope this answers all the open questions. In this case, please close this Issue. Feel free to send in a PR with your kernel. However, the mode 11410 does not match the mode numbering logic. In case you want to send in a PR, please ping me first and I will register a new mode number for you.

**Comment by jtoddowen** [comment]
Thanks for the sxx/mxx clarification.  For this hash type I can't foresee more than one hash ever being searched for since the nonce_count increments with every packet making the hash uniquely "salted" on purpose.  I will work on this some more based on your comments and run the test case I have.  I'll update this week.

**Comment by jtoddowen** [comment]
I finally decided to compile and run (deleted the file in the kernel folder and replaced `m11400_a3-pure.cl` in the OpenCL folder, but I'm getting a `clBuildProgram(): CL_BUILD_FAILURE` on the u32 type name on line 19: `u32 salt_buf[32];` and following lines.  I then just made a version of the file with only the following added after the VECT_SIZE block, but I'm getting the same error, so I must not be doing something right.

```c
CONSTANT_VK u32a base64_table[64] =
{
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
  'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
  'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
  'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
  'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
  'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
  'w', 'x', 'y', 'z', '0', '1', '2', '3',
  '4', '5', '6', '7', '8', '9', '+', '/',
};
```

**Comment by jtoddowen** [comment]
Good news.  I'm compiling and working (somewhat).  The basic hashcat install didn't include a lot of files by default in the OpenCL folder, mostly .h files.  I just decided to dump the 5.1.0 beta files in there to start since there were a few conflicts.

I'm passing into my Base64 function and using the raw_pw[] and w[] arrays as indicated above.  I had a lot of trouble with getting the pointers straight, but everything is u32 and working fine _as long as I don't do anything in the function_ other than assign each in_ptr to an out_val, then to the out_ptr.  This defeats the purpose of the function of course, but gives me confidence I'm on the right track with the program structure at least.

This brings me to a big question about how the pws[] array is formed.  Is every u32 in the pws[] array one 8-bit character, or is it four?  I ask because `const u32 out_val0 = in_ptr[0] & 0xffffffff;` does not give me an error, but a 0x000000ff or 0xff000000 mask gives me an `ATTENTION! OpenCL kernel self-test failed` error.  The pws array is of type pw_t as defined below.

The loop below implies to me there are four bytes of the password per u32 with pw_len being the number of "u8"s that make up the password.  If this is true, is the low byte of the first word the first character, then going up?  Also, are the unused bits all zero (just curious)?

```c
typedef struct pw
{ u32 i[64];
  u32 pw_len;
} pw_t;

for (u32 i = 0, idx = 0; i < pw_len; i += 4, idx += 1)
{
  w[idx] = pws[gid].i[idx];
}
```

**Comment by jsteube** [comment]
> Is every u32 in the pws[] array one 8-bit character, or is it four? 

It's case by case. I'd say in 95% of the time it's four. This also explains the problem you have with the 0xff bitmask.

> If this is true, is the low byte of the first word the first character, then going up? Also, are the unused bits all zero (just curious)?

The ordering of the byte depends on the endianness. Some hashes are written in LE, some in BE. Sometimes even both, for example in sha1(md5()).

**Comment by jtoddowen** [comment]
IT WORKS now, although I went from about 1250 MH/s to 890 MH/s.  I never could get the u8 to u32 conversion to compile so I just encode (3) real PW characters to (4) Base64 characters per loop.

It took me a while to figure out the PW entering the kernel were in little-endian format, but once the bit shifts were adjusted the result was in the correct order.  Although the (new Base64) PW length is passed along to the next part of the code, if there are any non-zero bits encoded to something like 0x41414141 (AAAA) for example when the encoded PW is really 12, not 16 characters, the hashing routine fails.  This required more conditional statements which I'm sure slowed down the code.

I'll work on this some more to get it to run a little faster, but otherwise it's working, and I've improved my programming skills a lot.  Like I said, it's be 30 years since I've been this deep into C, so thank you for your project and your efforts.

Feel free to close this issue, and I'll PM you when I get it looking better in case you want to add it to the core project.  Also, it only works for u32, not u32x as well, so that's something I should fix too.

Thanks, again to @jsteube and @philsmd 
--Todd

**Comment by jtoddowen** [comment]
I just added this to the a0-pure kernel in about 15 minutes, and it works well there.  The speed is 250 MH/s, but I assume this is par for the course compared with the in-kernel mask attack.  Thanks again.

**Comment by philsmd** [comment]
I think we should either add the code from @jtoddowen for this variant of SIP or close the issue entirely... leaving this github issue open doesn't probably help anyone.

I see little user interest for this, therefore in my opinion it might be a very rarely used/specific algorithm (I could be wrong, of course).

@jtoddowen do you plan on adding your code to hashcat or should we close this ? only @jsteube and you (@jtoddowen) are supposed to decise if this issue should be closed, according to the current github repo settings.

Thanks

(I think we could wait for an answer from @jtoddowen for a couple of days/weeks and close it afterwards if we got no answer)

**Comment by jsteube** [comment]
No answer, but feel free to reopen
