### ISSUE TITLE
Starting up hashcat

### ISSUE THREAD

**Issue by RDcoolV** [hashcat/hashcat#2198]
What file do i need to open to startup Hashcat?
I tried hashcat 64 and hashcat32 but they just close after i opened them.
I use the latest version on windows 10 btw.

**Comment by roycewilliams** [comment]
GitHub is for bug/feature requests, not general questions. Please use the hashcat forums for general questions.

This is the first question in the official hashcat FAQ:

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#why_does_a_window_pop_up_and_close_immediately

**Comment by Rdgeno** [comment]
https://executeatwill.github.io/ctf/2019/02/11/Install-hashcat-on-windows/

**Comment by rdgeno12** [comment]
Yeah that didn't work when I tried it the link I provided work in wind 10 pro but you have to use the gui. Any answers for the opencl issue. Please dont give me the link to do I have the correct driver, Windows 10 pro, unbuntu 16.04 18.04 and kali 2019.03 it doesnt work. Please da a Google search the opencl is a real problem no one will address. It not the GPU or CPU every other OS and every other program they work with so by process of elimination it is a hashcat problem.

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 10, 2019 at 3:31 PM, Rdgeno<notifications@github.com> wrote:   
https://executeatwill.github.io/ctf/2019/02/11/Install-hashcat-on-windows/

**Comment by Rdgeno** [comment]
Thanks for the link install isnt the problem hashcat wont run my GPU self test disable wont give the password.

**Comment by Rdgeno** [comment]
So what I'm asking is, Is there a way to actually get hashcat to work with a GPU, nvidia doesnt work AMD doesnt.

**Comment by Rdgeno** [comment]
I would copy and paste their responses but theres not enough room to express a thought here.
