### ISSUE TITLE
ChaCha20 minimum password length

### ISSUE THREAD

**Issue by mem55** [hashcat/hashcat#2199]
Following the thread https://hashcat.net/forum/thread-8710.html about algorithm ChaCha20 (mode 15400),
@philsmd propose to set pw_min to 0 i.e. in module_pw_min (), or skip it entirely since the default minimum password is zero.

Otherwise password length les than 32 bytes won't be taken.

Thanks!

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/13dcae6879bfecfd981a7d9a16b6c8f83c9a4d40

Thanks for reporting!
