### ISSUE TITLE
Sip Digest MD5 syntax problem.

### ISSUE THREAD

**Issue by sakas23** [hashcat/hashcat#2207]
Hello community,

I try to create a SIP Digest Authenticaiton MD5 hash to crack it with hashcat, but there seems to be a problem.

Below is the output of a register packet from wireshark.
![SIP MD5 digest details 3](https://user-images.githubusercontent.com/57067833/67636843-8b900880-f8cc-11e9-9f57-53da64dd27fe.png)

So the hash i created with these details is : $sip$*sip:192.168.0.38**Renia*asterisk*REGISTER*sip*sip:192.168.0.38**61b3081d****MD5*e50978c1b8c8cc4d0c78988690ed461e

The nonce and response values are different. I was making some other tries.

The command  i am running in hashcat is : hashcat64.exe -a 0 - m 11400 hash.txt dictionary.txt

where dictionary is the file which contains the cracked password.

The hashcat's output is : "Approaching final keyspace - workload adjusted."

My question is if iam doing something wrong or what do i have to add to the hash?

Note: some white gaps in the pictures are because it is my public ip.

Thanks in advance.

**Comment by philsmd** [comment]
solved with an explanation from @philsmd in the hashcat forum: https://hashcat.net/forum/thread-8744-post-46470.html#pid46470

please do not (mis)use the github issue tracker for user questions like this. the issue tracker should be used for real problems/bugs and/or feature/algo requests.

also do not post on both (forum + github), just to get noticed. It's enough if you search for the answer on the forum.

Please close (only original reporter and github project owner can close issues)
