### ISSUE TITLE
Can't crack password

### ISSUE THREAD

**Issue by toptuto** [hashcat/hashcat#2210]
I used Hash-identifier to get type of these passwords : 
C3D3DACAAE919F93
B7BBB3B5B8A57A7771A0A698
C2D0D6D99E60969C
A5D5DFD2C4D78FA4959294
and it told that MD5(middle) or Mysql.
But when I tried to crack by hashcat like this : hashcat -m 300 -a 0 hash.txt rockyou.txt , it returned nothing. 
Thanks

**Comment by Rdgeno** [comment]
That's not a hashcat problem. Thats a your password wasn't in the list problem.

**Comment by toptuto** [comment]
how can I crack these ?

**Comment by roycewilliams** [comment]
That is a question for the hashcat forums, not for GitHub.
