### ISSUE TITLE
HashCat "No hashes loaded"

### ISSUE THREAD

**Issue by TheAlexBY** [hashcat/hashcat#2211]
When I try to find a password for the dictionary for the SHA256 hash (AuthMe) - 20711, I get an error "No hashes loaded." With MD5 it works fine.
SHA256 (AuthMe): $SHA$02341f57d90061fb$b8bf552f3d5d2cb777c2e7af6d955863df61b423d80e7be8b4831d08b0e6ca30
Screenshot: [https://i.imgur.com/0502WwD.png](url)

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/9ea1f88f271b0047cb989ff00bf6aa7302846ead

New beta up, too
