### ISSUE TITLE
--show option disordered

### ISSUE THREAD

**Issue by e2002e** [hashcat/hashcat#2213]
Hello, when cracking a list of hashes that is ordered, I notice the output of show is not in the order of my hash list, but rather in what seems to be the time of successful collision. This might be a detail when you deal with some hashes but when your hashes are ordered for a specific reason it makes any further work impossible even though you should recover all passwords. I Think this is an issue.

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/6adc217bae404dc3728a5514a05b8b420d3f5bf7

Also works for --left. Also updated binaries beta.
