### ISSUE TITLE
Blockchain wallets version 2,3 token length exception

### ISSUE THREAD

**Issue by eastsida** [hashcat/hashcat#2214]
Hello is this possible to remove token length check or it's somekind hardware restricted where is impossible to decrypt big length strings ? The problem is here that more people will add private or public keys into the wallet, more accounts they will create inside wallet the bigger encrypted wallet will be. The biggest wallet that i have is - $blockchain$v2$5000$487968$.
Thanks.

**Comment by philsmd** [comment]
you can just truncate the data to e.g. 288 files like the example hash. Loading a hash that long (> 500 KB) doesn't make much sense for this algo.

also read:
https://hashcat.net/forum/thread-7498-post-40352.html#pid40352
https://hashcat.net/forum/thread-7289-post-39361.html#pid39361
https://github.com/hashcat/hashcat/issues/112
etc

what you need to do is truncate the data field (last field) to e.g. 288*2 = 576 hexadecimal characters and update the second to last field of the hash line to 288 (remember: hex is twice the size of the raw bytes, therefore 288 * 2 data in hex, but data length is 288)

don't forget to close the issue (only OP and repo owner can close the issues here)
