### ISSUE TITLE
clz implemented poorly?

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#2215]
https://godbolt.org/z/nhcb3g

Note that I changed the number from 64 to 63. Otherwise, the compiler generates two more instructions.

**Comment by neheb** [comment]
This refers to this: https://github.com/hashcat/hashcat/blob/master/src/shared.c#L109

**Comment by jsteube** [comment]
In case performance is of no relevance (as in here) I prefer the code easy to read. In this case, using numbers power of two not just feel better, they also give a good hint about what is going on here and I can save to comment the code.

Feel free to change the code as long as you do not need to change the function declaration.

**Comment by neheb** [comment]
Hrm OK. I don't know if the xor trick is applicable to OpenCL. OpenCL runtimes are usually based on LLVM, which is usually able to optimize it properly.
