### ISSUE TITLE
[feature request] support for multibyte delimiters

### ISSUE THREAD

**Issue by d2-d2** [hashcat/hashcat#222]
Hello, could you please implement support for longer delimiters? Right now *hashcat allows me to use single-character delimiter but it's difficult to extract password lists from hash:salt:pass lists when salt is not constant. I'd like to ask for option where I can supply delimiter like: <this_is_my_delimiter>

Thank you!

**Comment by philsmd** [comment]
> it's difficult to extract password lists from hash:salt:pass lists when salt is not constant

@d2-d2 did you try to use this? :

```
oclHashcat -m [HASHTYPE] --show --outfile-format 2 [HASHLIST]
```

(note: the .pot file must exist of course)

**Comment by d2-d2** [comment]
@philsmd that's the thing, instead of chaining different commands in hashcat I'd like to use one consistent that will allow me to write cracked passwords and shorten the left list easily. Then, having multibyte delimiter in output file, I can prepare whatever outputs I like without loosing any characters etc.

**Comment by philsmd** [comment]
it works also directly, i.e. without using --show, e.g:

```
oclHashcat -m [HASHTYPE] -a [ATTACKTYPE] -o [OUTFILE] --outfile-format 2 [HASHLIST] [DICT/MASK/MASKFILE]
```

I think the multi-byte delimiter could still be a good idea in some very special cases (i.e. if the hash list already has some weird delimiters and the user doesn't want or isn't able to batch modify each line within the file)...

**Comment by d2-d2** [comment]
> I think the multi-byte delimiter could still be a good idea in some very special cases (i.e. if the hash list already has some weird delimiters and the user doesn't want or isn't able to batch modify each line within the file)

Exactly. Such delimiter would clearly tell you about number of fields and therefore ease further scripting.

**Comment by jsteube** [comment]
That feature is no longer required with the upcoming version hashcat v3.21 because of the following change:

```
- Files: Use $HEX[...] in case the password includes the separater character...
```

**Comment by d2-d2** [comment]
@jsteube what if separator is also in salt?

**Comment by jsteube** [comment]
In that case you can detect it by reading from right to left.

**Comment by d2-d2** [comment]
OK thanks.
