### ISSUE TITLE
Hashfile 'a.tc': Bad file descriptor No hashes loaded.

### ISSUE THREAD

**Issue by usercloud** [hashcat/hashcat#2232]
Hi 

Hashcat recognizes same  hash file in windows environment .However, it shows the following  error in Linux environment ( Colab):

Hashfile 'a.tc': Bad file descriptor
No hashes loaded.

any advice and suggestion please 

thanks

**Comment by jsteube** [comment]
Not a hashcat problem. Please ask on Forum.
