### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE - NVIDIA MX 150

### ISSUE THREAD

**Issue by MESWEB** [hashcat/hashcat#2233]
Windows 10

> OpenCL Platform #1: NVIDIA Corporation
   ======================================
>  * Device #1: GeForce MX150, 512/2048 MB allocatable, 3MCU

>   OpenCL Platform #2: Intel(R) Corporation
   ========================================
>   * Device #2: Intel(R) UHD Graphics 620, skipped.
>   * Device #3: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, skipped.

NVIDIA driver 441.20
Intel driver 26.20.100.7463
Can't run hashcat64

> clBuildProgram(): CL_INVALID_BINARY

Default driver from Windows It was work good.

**Comment by jsteube** [comment]
Not a hashcat problem. Please ask on Forum.

**Comment by MESWEB** [comment]
Solved
