### ISSUE TITLE
Inefficient code generation in inc_common.cl

### ISSUE THREAD

**Issue by usernamepi** [hashcat/hashcat#2237]
While studying the code I came across this file, inc_common.cl.
The spotted inefficiency is probably a copy paste error and has to do with conditional preprocessor statements like: #if VECT_SIZE >= 2.

hc_byte_perm (line 843): forgot to drop the first half of the instructions for  VECT_SIZE >= 4, 8 and 16 ? The instructions are already generated by the previous preprocessor conditions.
hc_add3 (line 907): same thing. But this code is currently as comment.

**Comment by jsteube** [comment]
You are right, fixed with commit https://github.com/hashcat/hashcat/commit/a6c18f48ba92e26820fc7e61f21fc2416a5c957e
Thanks for reporting!
