### ISSUE TITLE
Can't restore in USB disk

### ISSUE THREAD

**Issue by MESWEB** [hashcat/hashcat#2238]
I was working in disk c:

> c:\Users\xxx\Documents\hashcat-5.1.0

Now I have 10% complete and I decide to move restore file to another computer. So I just copy all directory to USB pendrive and I was try restore file but hashcat64.exe shout about missing folder in c:\Users\xxx\Documents\hashcat-5.1.0 
So then I change command for this:

> hashcat64.exe --session hashcat --restore --restore-file-path f:\hashcat-5.1.0\hashcat.restore

But all the time working directory is on c:\ drive
When I try edit file hashcat.restore and change path to new folder then I have this error:

> Unusually high number of arguments (argc) within restore file f:\hashcat-5.1.0\hashcat.restore

**Comment by jsteube** [comment]
Moving the hashcat installation path is not supported. Please ask on forum how to read the information from the restore file and then to make use of the relevant information in combination with -s as a workaround.

**Comment by MESWEB** [comment]
Problem solved - now it's running like should be without any adding parameters - please have a look at picture.
![2019-11-23 (2)](https://user-images.githubusercontent.com/2931024/69482039-6a103700-0e0e-11ea-8f34-6ab25628110f.png)
