### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE OS X 10.10.5

### ISSUE THREAD

**Issue by averagesecurityguy** [hashcat/hashcat#224]
When trying to run a mask attack with oclHashcat-2.10b10-osx.7z I get a CL_BUILD_PROGRAM_FAILURE error message while trying to compile the markov_le.c7d3667b.kernel.

```
./oclHashcat.app -a 3 -m 1000 domain_hashes.txt ?a?a?a?a?a?a?a --increment
oclHashcat v2.01 (g952c20e) starting...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 256/1024 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, 128/512 MB allocatable, 774Mhz, 2MCU

Device #2: Kernel /oclHashcat-2.10/./kernels/m01000_a3.c7d3667b.kernel (53133 bytes)
Device #2: Kernel /oclHashcat-2.10/./kernels/markov_le.c7d3667b.kernel not found in cache! Building may take a while...


ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE



=== Build Log (start) ===
Error: internal error.

=== Build Log (end) ===
```

Running on a MacBook Pro 15-inch, Mid 2012 with an NVIDIA GeForce GT 650M GPU.

A rule based attack works fine and the kernels compiled with no warnings or errors.

```
$ ./oclHashcat.app -m 1000 domain_hashes.txt ~/nettest/wordlists/rockyou.txt rules/d3ad0ne.rule 
oclHashcat v2.01 (g952c20e) starting...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 256/1024 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, 128/512 MB allocatable, 774Mhz, 2MCU

Device #2: Kernel /oclHashcat-2.10/./kernels/m01000_a0.c7d3667b.kernel (315260 bytes)
Device #3: Kernel /oclHashcat-2.10/./kernels/m01000_a0.1bb8e30d.kernel (191855 bytes)

INFO: removed 16 hashes found in pot file
```

**Comment by averagesecurityguy** [comment]
Getting a similar error when trying to benchmark.

```
./oclHashcat.app --benchmark
oclHashcat v2.01 (g952c20e) starting in benchmark-mode...

Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped
Device #2: HD Graphics 4000, 256/1024 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, 128/512 MB allocatable, 774Mhz, 2MCU



ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE



=== Build Log (start) ===
Error: internal error.

=== Build Log (end) ===
```

**Comment by magnumripper** [comment]
No problem seen with latest code (g8af57d5), same hardware and OSX 10.11.13.

Also no problem seen with OP version (g952c20e), same hardware and OSX 10.11.13.

**Comment by magnumripper** [comment]
@averagesecurityguy try using `-d2` and `-d3` respectively, and see if problem is limited to a certain device.

@jsteube @gm4tr1x perhaps a kernel build error could mention what device we were building for?
**Edit**: it seems to be device 2 from OP.

**Comment by jsteube** [comment]
@averagesecurityguy @magnumripper you tried in the middle of the autotune integration work, maybe that cause some errors. please retry with latest beta or git version

**Comment by matrix** [comment]
@magnumripper @averagesecurityguy the issue is related to device 2, well known HD Graphics 4000 (old gpu device).
If @jsteube hint don't work you can temporarily skip by add "--opencl-device-types 1,2 -d1,3" to your cmdline.

The device name will be included without problem in the error output.

**Comment by averagesecurityguy** [comment]
Pulled down the latest code from Github. Still having trouble compiling the markov kernels for device 2

```
Device #1: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz, skipped              
Device #2: HD Graphics 4000, 256/1024 MB allocatable, 1200Mhz, 16MCU
Device #3: GeForce GT 650M, 128/512 MB allocatable, 774Mhz, 2MCU

Device #2: Kernel /Users/shaywood/nettest/oclHashcat/./kernels/m01000_a3.c7d3667b.kernel not found in cache! Building may take a while...
Device #2: Kernel /Users/shaywood/nettest/oclHashcat/./kernels/markov_le.c7d3667b.kernel not found in cache! Building may take a while...

=== Build failed, retry with optimization disabled ===

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -I/Users/shaywood/nettest/oclHashcat/./ -DVENDOR_ID=16925696 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4 ===

=== Build Log (start) ===
Error: internal error.

=== Build Log (end) ===
Device #2: Kernel /Users/shaywood/nettest/oclHashcat/./OpenCL/markov_le.cl build failure. Proceed without this device.
```

How do I configure Hashcat to not use the optimizations when building the kernels?

**Comment by averagesecurityguy** [comment]
Attempting to compile the kernel manually to see if I can determine the issue. Using the following command.

```
clang -framework OpenCL markov_le.cl -I../ -DVENDOR_ID=16925696 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4
```

and I'm getting a lot of errors like this:

```
In file included from markov_le.cl:10:
../OpenCL/types_ocl.c:9:9: error: unknown type name 'uchar'; did you mean 'char'?
typedef uchar  u8;
        ^~~~~
        char
../OpenCL/types_ocl.c:10:9: error: unknown type name 'ushort'; did you mean 'short'?
typedef ushort u16;
        ^~~~~~
        short
```

Is there another way that I should be compiling?

**Comment by magnumripper** [comment]
You can't compile OpenCL code like that. But you could try running with `--markov-disable` and see if it works.

**Comment by averagesecurityguy** [comment]
Yep, figured out that's not the correct way to compile it. :) Would really like to figure out why it's not working. What is the proper way to attempt to compile the code? Make a wrapper that calls clBuildProgram and then compile the wrapper?

**Comment by averagesecurityguy** [comment]
Using --markov-disable did not make a difference, I'm using -d3 to skip device 2 when necessary. I can use both devices when I'm using wordlist and rules.

**Comment by magnumripper** [comment]
Building a compiler wouldn't change anything: oclHashcat would print the log if there was any. OSX' poor drivers often segfault while building, with no clue whatsoever as to why.

**Comment by averagesecurityguy** [comment]
Thanks. I'll just use -d3 as needed. This issue can be closed.
