### ISSUE TITLE
Clion in Mac OSX cannot run hashcat

### ISSUE THREAD

**Issue by Xumixue** [hashcat/hashcat#2245]
I want to debug to step through the hashcat in Clion on Mac OS.
So I install a Plugin named MakeFile Support and create a document named CMakeLists.txt.
But when I begin to build project, that can't be accomplished due to the error as follow.
[/LzmaLibExports.c:6:10: fatal error: 'windows.h' file not found](url)
I can't find related code of cross compilation in Makefile between windows and Darwin，is that the problem?
How can I achieve the step through, I wish there may be someone I can go to for advice

**Comment by jsteube** [comment]
Cross Compilation is supported from Linux only
