### ISSUE TITLE
"Failed to parse hashes using the 'pwdump' format." Error with -m 3000

### ISSUE THREAD

**Issue by emwinkler** [hashcat/hashcat#2252]
I get the following error when trying to parse pwdump formatted LM hashes.  NT hashes work fine (-m 1000).  I also tried it on Ubuntu 18.04 and I get the same error.

./hashcat -a 3 -m 3000 testhash.txt -d 3
hashcat (v5.1.0-1514-gbe38eefd) starting...

OpenCL API (OpenCL 1.2 (Nov  9 2019 04:32:50)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped
* Device #2: HD Graphics 5000, skipped
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 8112/8176 MB (2044 MB allocatable), 64MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 7

Failed to parse hashes using the 'pwdump' format.
No hashes loaded.

No error on version 5.1.0.

**Comment by 0xhexmex** [comment]
I'm having this same issue. Errors on v5.1.0-1501-ga4b39b7b but no issue on v5.1.0-42-g471a8ccc

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/6ed3003a301be43074c0eeb511b522544730033b

New beta up, too

**Comment by emwinkler** [comment]
I can confirm this has been fixed.

I have also noticed that -m 2500 and -m 2501 are now working on MacOS.  What has changed in the OpenCL code with this version?  See below

./hashcat -b -m 2500 -d 3
hashcat (v5.1.0-1523-g6ed3003a) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/Users/emwinkler/Desktop/hashcat/OpenCL/m02500-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
OpenCL API (OpenCL 1.2 (Nov  9 2019 04:32:50)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped
* Device #2: HD Graphics 5000, skipped
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 8112/8176 MB (2044 MB allocatable), 64MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4095)

Speed.#3.........:   324.2 kH/s (49.57ms) @ Accel:32 Loops:128 Thr:256 Vec:1

Started: Mon Dec 23 15:02:41 2019
Stopped: Mon Dec 23 15:02:46 2019


./hashcat -b -m 2501 -d 3
hashcat (v5.1.0-1523-g6ed3003a) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

/Users/emwinkler/Desktop/hashcat/OpenCL/m02501-optimized.cl: Optimized kernel requested but not needed - falling back to pure kernel
OpenCL API (OpenCL 1.2 (Nov  9 2019 04:32:50)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, skipped
* Device #2: HD Graphics 5000, skipped
* Device #3: AMD Radeon RX Vega 64 Compute Engine, 8112/8176 MB (2044 MB allocatable), 64MCU

Benchmark relevant options:
===========================
* --backend-devices=3
* --optimized-kernel-enable

Hashmode: 2501 - WPA-EAPOL-PMK (Iterations: 0)

Speed.#3.........:   255.3 MH/s (0.00ms) @ Accel:128 Loops:1024 Thr:256 Vec:1

Started: Mon Dec 23 15:02:26 2019
Stopped: Mon Dec 23 15:02:35 2019

**Comment by philsmd** [comment]
hey @emwinkler 
sorry to bother you, but you say
`I have also noticed that -m 2500 and -m 2501 are now working on MacOS`

we have several open issues for macOS: https://github.com/hashcat/hashcat/issues?q=is%3Aissue+is%3Aopen+macos

Can you maybe test and figure out if any of these are now "solved" ? It's very difficult for us without the macOS/apple hardware to understand what problem exactly was fixed and if some of those still open issues on github can be closed ?

Thanks a lot

**Comment by emwinkler** [comment]
Looking at the list and from my testing on the macOS 10.15.2, I would say the following can be closed as the current build code for  -m 2500 and -m 2501 addresses the issue.

#2176
#2076
#1847
#1497
#1290

I will investigate #1912 further and let you know


Thanks,
Erik

**Comment by philsmd** [comment]
sounds good, but sounds almost too good to be true.
We've now closed this/your issue: https://github.com/hashcat/hashcat/issues/1847

but it sounds weird that a small fix would fix the speed and compilation bugs too (the other issues)... hopefully the original reporters will answer soon such that we get further confirmations... It's almost unbelievable that everything on macOS should be fixed now. Maybe it's fixed on your specific setup, but not for the original/other hardware, dunno... I also do not know the main differences between those apple devices and operating system versions (and driver versions).

Thanks for the confirmations and testing... for now we "only" closed one issue, but if we get some further positive response or more confirmations, we definitely should try to merge/de-duplicate/close further issues.
Thx
