### ISSUE TITLE
No rule to make target '/opt/win-iconv-64/lib/libiconv.a'

### ISSUE THREAD

**Issue by jdoles** [hashcat/hashcat#2253]
Admittedly, this may be my own ignorance.  When building from source for Windows I get the following error:
make: *** No rule to make target '/opt/win-iconv-64/lib/libiconv.a', needed by 'hashcat.exe'.  Stop.

OS: Ubuntu 18.04

I cloned the repo per the guide.  Then I installed mingw-64 and win-iconv-mingw-w64-dev.  Next I ran  make win.  I'm not sure where to go on this error though.

**Comment by philsmd** [comment]
hey.
cross-compiling is something very specific and special and the average user won't and probably shouldn't do it.
There is some kind of "documentation" in the source/Makefile for iconv on windows:
https://github.com/hashcat/hashcat/blob/be38eefdadfb054f15ccdd67ec96752b16be4807/src/Makefile#L556-L561

i.e. clone that repo mentioned and put it under that specific path ("/opt/win-iconv-64/")... you would also need to patch it with tools/win-iconv-64.diff

I'm not sure if we should add extra documentation for this... it should be kinda rare that users want to cross-compile binaries (execept for the developers that need to ship all the different kind of binaries, linux and windows).

If this helps and you think it's good AS-IS, don't forget to close the issue :)

**Comment by jdoles** [comment]
Thanks for the quick reply.  The reason I started down this path was to get the latest code for testing.  Also I might be a glutton for punishment.  ;)  Anyhow - 

I was able to get this to build without errors.  I didn't find it too difficult personally.  Here's an overview of what I did:
-- Clone repo
sudo git clone https://github.com/win-iconv/win-iconv

-- Move directory to /opt/win-iconv-64/
sudo mv /opt/win-iconv/ /opt/win-iconv-64/

-- Patch the Makefile with the one provided by hashcat
sudo patch /opt/win-iconv-64/Makefile -i ~/hashcat/tools/win-iconv-64.diff

-- Make win-iconv
sudo make

-- Move the lib files to where hashcat expects them
sudo mkdir /opt/win-iconv-64/lib
sudo cp /opt/win-iconv-64/lib* /opt/win-iconv-64/lib/

-- Make hashcat
sudo make
sudo make win

It probably wouldn't hurt to add something like this to the BUILD.md file.  Given the simple make win reference, I thought this would be easier.  ;)

**Comment by jsteube** [comment]
If you are on windows just install MinGW or CygWin and run make.

**Comment by jdoles** [comment]
> 
> 
> If you are on windows just install MinGW or CygWin and run make.

That's an option too I suppose.  On the system I was testing on I didn't have the ability to run either.  So I was getting around that by compiling on a Linux VM I had.

Thanks for the input.

**Comment by weirdal3333** [comment]
I just wanted to let everyone know that win-iconv has significantly changed and no longer has a makefile. 

Following the BUILD_WSL.md file works for compiling on linux mint.
