### ISSUE TITLE
[Enhancement] Support --opencl-vector-width=16

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#226]
I'm working on this.

**Comment by jsteube** [comment]
Cool, is this for the PHI?

**Comment by magnumripper** [comment]
Not really, like I said in the other thread they auto-vectorize and is better given scalar code. This is for other devices, eg. CPUs with AVX-512 that doesn't auto-vectorize.

Patch is complete but I will test some more before a PR.
