### ISSUE TITLE
OpenCL/m02500-pure.cl build failed AMD RX 5700 XT

### ISSUE THREAD

**Issue by Gucciy** [hashcat/hashcat#2266]
Can't seem to find a solution for this issue, any help would be appreciated. 
Note I've looked at a lot of similar issues but not one seemed to have helped me. I might have overlooked some basic things. But to my knowledge i have latest windows 10 and AMD drivers.
C:\Users\Corsair\Desktop\hashcat-5.1.0>hashcat64 -m 2500 -b -D2 -O
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

ADL_Overdrive5_CurrentActivity_Get(): -8

ADL_Overdrive5_CurrentActivity_Get(): -8

ADL_Overdrive5_CurrentActivity_Get(): -8

ADL_Overdrive5_CurrentActivity_Get(): -8

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: gfx1010, 4048/8176 MB allocatable, 20MCU

Benchmark relevant options:
===========================
* --opencl-device-types=2
* --optimized-kernel-enable

Hashmode: 2500 - WPA-EAPOL-PBKDF2 (Iterations: 4096)

warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
__kernel void m02500_aux3 (KERN_ATTR_TMPS_ESALT (wpa_pbkdf2_tmp_t, wpa_eapol_t))
              ^
C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-05be01\input\CompileCLSource:1016:15: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
6 warnings generated.
lld: error: undefined hidden symbol: sha1_update_64
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux2)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux2)
>>> referenced 2 more times

lld: error: undefined hidden symbol: sha1_final
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_init)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux1)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux2)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux2)
>>> referenced 2 more times

lld: error: undefined hidden symbol: sha256_hmac_init_64
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)

lld: error: undefined hidden symbol: sha256_hmac_final
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
>>> referenced by C:\Users\Corsair\Desktop\hashcat-5.1.0\.\OpenCL\comgr-ff4eeb\input\linked.bc.o:(m02500_aux3)
Error: Creating the executable from LLVM IRs failed.

* Device #1: Kernel ./OpenCL/m02500-pure.cl build failed - proceeding without this device.

Started: Wed Jan 08 17:29:56 2020
Stopped: Wed Jan 08 17:30:12 2020

**Comment by philsmd** [comment]
did you try to run it with the most recent code?

https://hashcat.net/beta/ or the git code (if you are able to compile it yourself, very easy)

**Comment by Gucciy** [comment]
Downloading hashcat beta has seem to have fixed things, Thank you!
