### ISSUE TITLE
In Kali No device found/left

### ISSUE THREAD

**Issue by freewebwithme** [hashcat/hashcat#2273]
Hello I am using Kali linux with noveau graphic driver. And when I tried to do following
`sudo hashcat -m 500 md5hash.txt /usr/share/wordlists/rockyou.txt`
it says
No devices found/left.
I am using hashcat 5.1.0
Am I missing any package?

**Comment by jsteube** [comment]
GitHub issues are for bugs and feature requests only. Please ask on Hashcat Forum.
