### ISSUE TITLE
Crashing on start 

### ISSUE THREAD

**Issue by darthsnarkey** [hashcat/hashcat#2274]
I am running: 
hashcat -a 0 -m 2500 -D 2 -w 2 ./converted/myHccapx ./dicts/rockyou.txt 
and is simply says starting Hashcat followed by "Killed" if I run a second time it freezes and I cannot kill the process unless I reboot
Running Linux Mint 19.3, intel I5, 8gb ram AMD 460 with installed drivers.
No other error codes shown
This is compiled from source not a precompiled version
tested other hashes and get same result --force has no effect and pid must be manually deleted from sessions to clear.

**Comment by jsteube** [comment]
what's the filesize of ./converted/myHccapx

**Comment by darthsnarkey** [comment]
please disregard, after much searching and tinkering it is my system. Open CL is broken on my system and I cannot fix it
Sadly this was not easily apparent as it was a deep hidden issue in the Kernel, despite reinstalling everything it still hangs up and zombies just running clinfo 2 times. First time it simply kills second it zombies. I appologize for this

**Comment by jsteube** [comment]
OK feel free to reopen if needed
