### ISSUE TITLE
[Request Algorithm] Citrix Netscaler (SHA-512)

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2278]
We already have Citrix Netscaler (SHA-1) -m 8100

Another implementation is its SHA-512 variant.

Example hash:
`2f9282ade42ce148175dc3b4d8b5916dae5211eee49886c3f7cc768f6b9f2eb982a5ac2f2672a0223999bfd15349093278adf12f6276e8b61dacf5572b3f93d0b4fa886ce:hashcat`

**Comment by jsteube** [comment]
Added https://github.com/hashcat/hashcat/commit/53105abeb47a6c325dee6714b1503cd68bd0c9c8
