### ISSUE TITLE
[Request] CRYPTO1 - Mifare Classic

### ISSUE THREAD

**Issue by ErikPelli** [hashcat/hashcat#2283]
Could you implement a GPU CRYPTO1 hardnested attack for Mifare Classic NFC keys?
This tool does this but it works with CPU and it's slow: https://github.com/nfc-tools/mfoc

**Comment by jsteube** [comment]
I have no idea what this is. Is there any passwords involved? Maybe @iceman1001 can explain?

**Comment by matrix** [comment]
From my point of view it doesn't seem so slow to implement it on gpu

**Comment by jsteube** [comment]
No response from OP, feel free to reopen with updated information.
