### ISSUE TITLE
hashcat Windows not handling non-PWD

### ISSUE THREAD

**Issue by bannsec** [hashcat/hashcat#2288]
hashcat on Windows appears to only support executing it from the same PWD as the hashcat binary itself. Example:

```
hashcat.exe -I
hashcat (v5.1.0-1595-g53105abe) starting...

* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 10.2.95

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce RTX 2080 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 68
    Clock..........: 1665
    Memory.Total...: 11264 MB (limited to 2816 MB allocatable in one block)
    Memory.Free....: 9216 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 441.20
```

However:
```
C:\> C:\Users\User\Desktop\hashcat\hashcat.exe -I
hashcat (v5.1.0-1595-g53105abe) starting...

./backend_info.pid: Permission denied

./OpenCL/: No such file or directory
```

The first is likely that this user can't write backend_info.pid to C:\. That could be solved either by using the path of the running program or by using appropriate appdata paths.

The second is simply that hashcat is assuming OpenCL should be in the PWD, which is not the case when hashcat is in %PATH% or otherwise not run from the same directory.

I recall seeing other errors about hcctune as well. These issues do not appear to happen on linux.

**Comment by jsteube** [comment]
That's a known issue but I'm afraid there's no way to fix it. You need to run hashcat from its unpacking location.
