### ISSUE TITLE
Weird MIC result with mode 22000

### ISSUE THREAD

**Issue by mem50** [hashcat/hashcat#2295]
Hi,
Input : `WPA*02*242497axxxxxxx*macap*macsta*essid*anonce*eapol*mp`

Running `hashcat-beta-1627.exe  -m 22000 hash.txt  dic.txt`

Result: `ae972xxxxx:macap:macsta:essid:password`

MIC of the input (242497axxxxxxx) does not match with the MIC of the output (ae972xxx)

Any hints why?
Thanks!

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/424a6ee8e98e20fe18ea856b1cea06a5ba27c53f
Thanks for reporting!
