### ISSUE TITLE
Token Length Exception on Hashcat 5.1.0

### ISSUE THREAD

**Issue by aternoted** [hashcat/hashcat#2301]
E:\hashcat-5.1.0>hashcat64.exe -m 11600 -a3  has.txt
hashcat (v5.1.0) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1060 6GB, 1536/6144 MB allocatable, 10MCU

Hashfile 'has.txt' on line 1 ($7z$2$...94e90c98e1b2996959d1347$28292$06): Token length exception
No hashes loaded.

**Comment by jsteube** [comment]
GitHub issues are for bugs and feature requests only. Please ask on Forum.
