### ISSUE TITLE
zip2 hash length issue

### ISSUE THREAD

**Issue by bannsec** [hashcat/hashcat#2302]
hashcat appears to truncate long hashes, then complains about missing the ending of the hash... In this case, it's a WinZip encrypted ($zip2$) zip file over 300MBs in size. I can successfully extract that hash, but hashcat does not appear to have the ability to work on it.

It would be great if hashcat would support cracking large files.

**Comment by jsteube** [comment]
Imagine processing 300mb of data for each password candidate before we can check if the candidate was the correct one or not. In theory possible, but from an architectural perspective not compatible with hashcat. We should stick to a data length that is within the shared memory dimensions of a GPU. Therefore the constraints the way they are defined for now make sense. To do what you want to do, a different testing approach would be needed.
