### ISSUE TITLE
DCC2 (-m 2100) Bad parsing when user(salt) contains separator character

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2309]
Domain Cached Credentials 2 (DCC2), MS Cache 2 hashes follow the below format:

`$ Signature $ Rounds # User(salt) # hash`

 `$DCC2$10240#tom#e4e938d12fe5974dc42a90120bd9c90f`

It is possible/valid for the user to contain the separator character '#' which can lead to hashcat being unable to parse the hash, throwing a token length exception. I've just come across this in the wild during a pentest.

Code causing the issue starts here: https://github.com/hashcat/hashcat/blob/master/src/modules/module_02100.c#L74

**Comment by philsmd** [comment]
hmm, what do you suggest as alternative / fix ?
Does JTR has the same problem / hash format ?

**Comment by Caprico1** [comment]
I also have experienced this but I am trying to generate the hashes before hand. Might be a completely different issue.

But my output format matches the example DCC2 example in issue above.

```
['4c253e4b65c007a8cd683ea57bc43c76']
$DCC2$10240#Administrator#4c253e4b65c007a8cd683ea57bc43c76
hashcat (v5.1.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
nvmlDeviceGetFanSpeed(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: Quadro P1000, 1008/4032 MB allocatable, 4MCU

OpenCL Platform #2: The pocl project
====================================
* Device #2: pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, skipped.

Hash '#Administrator#4c253e4b65c007a8cd683ea57bc43c76': Separator unmatched
No hashes loaded.
```

Note all hashes here are generated and are not (hopefully) in use.

**Comment by hops** [comment]
@Caprico1 I'm pretty sure this is because you didn't escape the hash on your shell so `$DCC2` and `$10240` are treated as variables.

@philsmd John uses the same format but does parse such hashes correctly. In fact so did hashcat but I guess this was overlooked when the tokenizer got introduced.
https://github.com/hashcat/hashcat/issues/1278

**Comment by jsteube** [comment]
This has been fixed with commit https://github.com/hashcat/hashcat/commit/995742219107dc9703db030835ea811d4554c497
There's also a new binary beta available.

**Comment by seyyedalimou** [comment]
ihatepasswords

**Comment by seyyedalimou** [comment]
> I also have experienced this but I am trying to generate the hashes before hand. Might be a completely different issue.
> 
> But my output format matches the example DCC2 example in issue above.
> 
> ```
> ['4c253e4b65c007a8cd683ea57bc43c76']
> $DCC2$10240#Administrator#4c253e4b65c007a8cd683ea57bc43c76
> hashcat (v5.1.0) starting...
> 
> * Device #1: WARNING! Kernel exec timeout is not disabled.
>              This may cause "CL_OUT_OF_RESOURCES" or related errors.
>              To disable the timeout, see: https://hashcat.net/q/timeoutpatch
> * Device #2: Not a native Intel OpenCL runtime. Expect massive speed loss.
>              You can use --force to override, but do not report related errors.
> nvmlDeviceGetFanSpeed(): Not Supported
> 
> OpenCL Platform #1: NVIDIA Corporation
> ======================================
> * Device #1: Quadro P1000, 1008/4032 MB allocatable, 4MCU
> 
> OpenCL Platform #2: The pocl project
> ====================================
> * Device #2: pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, skipped.
> 
> Hash '#Administrator#4c253e4b65c007a8cd683ea57bc43c76': Separator unmatched
> No hashes loaded.
> ```
> 
> Note all hashes here are generated and are not (hopefully) in use.

$DCC2$10240#administrator#23d97555681813db79b2ade4b4a6ff25:ihatepasswords

**Comment by PenguinKeeper7** [comment]
> Hash '#Administrator#4c253e4b65c007a8cd683ea57bc43c76': Separator unmatched
> No hashes loaded.

This is a terminal issue with the `$`s. Wrap the hash in 'single quotes' and it won't do error or put the hash in a file. Also, update your Hashcat, 5.1.0 is very old
