### ISSUE TITLE
clCreateBuffer(): CL_MEM_OBJECT_ALLOCATION_FAILURE on windows 10

### ISSUE THREAD

**Issue by jedai47** [hashcat/hashcat#2312]
Hi so basically Im on windows 10 and Im using 4 GPUs AMD Radeon R9 200 / HD 7900 Series and one CPU Intel(R) Core(TM) i7-3930K CPU  @ 3.20GHz 6 Cores and i am having the following error when benchmarking:

PS C:\Users\Crack\Downloads\hashcat-5.1.0> .\hashcat64.exe -b
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Tahiti, 2393/3072 MB allocatable, 32MCU
* Device #2: Tahiti, 2393/3072 MB allocatable, 32MCU
* Device #3: Tahiti, 2393/3072 MB allocatable, 32MCU
* Device #4: Tahiti, 2393/3072 MB allocatable, 32MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#1.........:  7739.6 MH/s (67.69ms) @ Accel:128 Loops:512 Thr:256 Vec:1
Speed.#2.........:  7740.0 MH/s (67.69ms) @ Accel:128 Loops:512 Thr:256 Vec:1
Speed.#3.........:  7740.3 MH/s (67.69ms) @ Accel:128 Loops:512 Thr:256 Vec:1
Speed.#4.........:  7740.7 MH/s (67.69ms) @ Accel:128 Loops:512 Thr:256 Vec:1
Speed.#*.........: 30960.6 MH/s

Hashmode: 100 - SHA1

clCreateBuffer(): CL_MEM_OBJECT_ALLOCATION_FAILURE

Started: Thu Feb 20 13:14:06 2020
Stopped: Thu Feb 20 13:14:18 2020

I just updated the drivers so I dont know what is wrong.

**Comment by jsteube** [comment]
It's a miracle hashcat is still working with such old GPU. Please retry with latest beta hashcat version and update the issue first. Beta binaries are here: https://hashcat.net/beta/

**Comment by philsmd** [comment]
@jedai47 any updates here ? we need a reply, otherwise we probably need to close it as INVALID.
thx

**Comment by Remeslenik** [comment]
I have the same problem on win7 x64. hashcat-5.1.0 + 1749 + test.7z works great! Snx

**Comment by jsteube** [comment]
Please retry with hashcat 6.0.0 + 32 beta from https://hashcat.net/beta/ and reopen the issue if it still exists.
