### ISSUE TITLE
HashCat stuck on generating bitmap tables

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2318]
Hey, 
I'm recently trying to crack a hash and It's just stuck on Generating BitMap Tables
Graphics Card: 1060 6GB GTX

![image](https://user-images.githubusercontent.com/60533606/75632520-cc759200-5bca-11ea-84c2-90ed9519b188.png)
I already tried the latest version & a later one

I really need help.

`hashcat64.exe -m 0 -a 3 hash.txt rockyou.txt --increment --force`
Excute ^

**Comment by roycewilliams** [comment]
This is a support question, which should be asked in the hashcat forums.

**Comment by jsteube** [comment]
It's also super outdated hashcat version. Please use latest beta and if the problem still occurs, ask on hashcat forum.
