### ISSUE TITLE
Feature request: beep on completion or when password found

### ISSUE THREAD

**Issue by InfoSecOne** [hashcat/hashcat#2319]
Hi, would it be possible to add a 'system beep' option on two scenarios:

 - when the hashcat run out of possible combinations aka. 'exhausted' 
 - when a password is cracked 

The idea is that the hashcat is often ran in the background and it would be 'nice to have' some kind of notification when away from PC or when working on something else.

**Comment by jsteube** [comment]
I can see the Idea behind, but also a lot of problems that this could create. First of all, not all shells/terminals support this "bell" feature. This means many people will ask why the "bell" is not working on their terminal and then we are in the position to answer their terminal configuration problems. That's something to avoid. Another problem I can see if you have an easy unsalted hashlist where you instantly crack 10000 hashes at the same time. This will create 10000 annoying beep sounds and eventually create other problems like lagging terminals.

Instead, it's pretty easy to do this from external by using a process that monitors the outfile and detects the changes and does whatever you want it to do.
