### ISSUE TITLE
Documentation both in-app and the wiki, is outdated, incomplete and unmaintained 

### ISSUE THREAD

**Issue by Stefan-mcp** [hashcat/hashcat#2321]
Great project, but the documentation and in app help just sucks! Its leaving people to learn the fuctionality through a mixture of trial and error and internet chinese whispers. No point having more and more great features and capabilities added to the code if only a handful of people will have the patience to reverse engineering / guess how to use it, or what it does

**Comment by jsteube** [comment]
I fully agree with your critic that the documentation sucks. There's just not much I can do. Luckily most users find their way into how to use hashcat correctly and in depth. Very likely, as you mentioned, by trial and error. If you are patient a good source of information can be the IRC channel. If you want to contribute increasing the documentation quality I am happy to provide you with all the credentials.

**Comment by Stefan-mcp** [comment]
I'll revisit that thought when I've found my way around it myself. I'd be up for it as it's a shame to see the awesome dev involved in the project being a bit let down by the documentation. The project deserves to be more accessible. Hell - maybe I'll even make a gui :-0 lol
