### ISSUE TITLE
bitlocker Hash-types 掩码?l?l?l无法正确破解密码

### ISSUE THREAD

**Issue by ly20180228** [hashcat/hashcat#2323]
我的密码设置的88888aaa，破解时使用88888?l?l?，程序显示Exhausted

简单测试了下，连续三个?l?l?l  hashcat就会出现错误的结果

Session..........: hashcat
Status...........: Exhausted
Hash.Name........: BitLocker
Hash.Target......: $bitlocker$0$16$fc597079051577528201f9293dcff763$10...975e6d
Time.Started.....: Tue Mar 10 23:13:22 2020 (10 secs)
Time.Estimated...: Tue Mar 10 23:13:32 2020 (0 secs; Runtime limited: 14 mins, 50 secs)
Guess.Mask.......: 88888?l?l?l [8]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     1797 H/s (38.08ms) @ Accel:1 Loops:4096 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 17576/17576 (100.00%)
Rejected.........: 0/17576 (0.00%)
Restore.Point....: 17576/17576 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1044480-1048576
Candidates.#1....: 88888ane -> 88888qgx
Hardware.Mon.#1..: Temp: 45c Fan:  0% Util:100% Core:1890MHz Mem:6801MHz Bus:16
Started: Tue Mar 10 23:13:14 2020
Stopped: Tue Mar 10 23:13:33 2020
PS C:\Users\ly\Desktop\hashcat-5.1.0> .\hashcat -a 3 -m 22100 88888.txt --increment --increment-min 8 --increment-max 12 88888?l?l?l

**Comment by jsteube** [comment]
Not enough information provided. Please continue on https://hashcat.net/forum/thread-9030.html

**Comment by jsteube** [comment]
I've pushed a workaround for this nvidia specific problem with commit https://github.com/hashcat/hashcat/commit/24094793dabe3ede1d3cb0bdfc787ce80746afae.

I've also prepared a new binary beta on https://hashcat.net/beta/

If you have time, please test it.

**Comment by ly20180228** [comment]
非常感谢您的修复，但是发现对于纯数字已经正常，对于其他字符问题依然存在
hash我已经通过论坛私聊给您

**Comment by jsteube** [comment]
There is no private message on forum for me. Please verify you are addressing the correct account, my name is atom on the forum.

**Comment by ly20180228** [comment]
额，实在抱歉，的确发错人了，因为之前是另一位管理员一直跟我私信，已经发给您了
