### ISSUE TITLE
[Request] Support for encrypted vbox files (PBKDF2 with 2 salts and 2 iterations) using GPU?

### ISSUE THREAD

**Issue by xSn0wstorm** [hashcat/hashcat#2324]
Hi,

I was wondering if its possible to implement the ability to crack encrypted Virtual Box (.vbox) files in Hashcat. There is documentation available on how the encryption and key is stored: http://www.sinfocol.org/2015/07/virtualbox-disk-image-encryption-password-cracker/

There are already tools available that can crack it, but they're written in PHP and Python, which only use single core CPU, which you can imagine is really slow. The repo's for them are as follows:

https://github.com/sinfocol/vboxdie-cracker/
https://github.com/axcheron/pyvboxdie-cracker

I know JTR supports it with its plugin (vdi2john) which is multi CPU, but again obviously not as fast as GPU. Is it possible to implement support for this type of file/encryption into Hashcat?

I saw mentioned on another thread (I think by Jens) that a tutorial is being written about adding new plugins to Hashcat, is this something that could be solved with plugins, I'd be happy to look into it if thats the case.

Any help is much appreciated.

**Comment by jsteube** [comment]
That for the information provided. So far I never had the request to support Virtual Box volumes. However, the information provided is great. It looks very similar to LUKS. If I find some free time... :)

**Comment by xSn0wstorm** [comment]
Glad to hear it's similar to LUKS, so hopefully shouldn't be too difficult to implement in the future. I'll look forward to trying it out whenever you get around to it, thanks! :)

**Comment by trounce1** [comment]
@jsteube have you done anything on this yet? 
I’d be interested in giving it a shot.

**Comment by jsteube** [comment]
Nope, didn't try. I think all you need already exist in some other kernels and you can simply copy out the data from it. If you have any question feel free to drop by in IRC so we can discuss interactive.

**Comment by matrix** [comment]
Hi,
@xSn0wstorm @trounce1 check this #2884 :)

**Comment by xSn0wstorm** [comment]
> Hi,
> @xSn0wstorm @trounce1 check this #2884 :)

Amazing work! Just tested it and it’s working perfectly. Thank you :)

**Comment by matrix** [comment]
added with #2884
