### ISSUE TITLE
Multiple GPU Problem 

### ISSUE THREAD

**Issue by aliyazal** [hashcat/hashcat#2325]
Hello,
Os : Windows 10
Hascat Version: v5.1.0
GPUs : 12 X Manli P106L Mining Card
https://www.techpowerup.com/gpu-specs/ma...6-gb.b6880

One gpu no problem but multiple devices is problem 

one gpu 5883.6 MH/s for md5
all gpu each one : 1591 - 1913.5 MH/s for md5

One GPU Benchmark
` Speed.#1.........:  5883.6 MH/s (56.70ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1`

 ALL GPU:

> 

> ` Speed.#1.........:  1646.4 MH/s (56.72ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#2.........:  1647.0 MH/s (57.50ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#3.........:  1647.1 MH/s (57.36ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#4.........:  1591.2 MH/s (59.66ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#5.........:  1724.4 MH/s (57.47ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#6.........:  1666.7 MH/s (58.25ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#7.........:  1640.9 MH/s (57.27ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#8.........:  1667.5 MH/s (59.23ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#9.........:  1667.6 MH/s (57.57ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#10.........:  1752.7 MH/s (56.79ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#11.........:  1913.5 MH/s (59.07ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#12.........:  1905.4 MH/s (58.32ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Speed.#*.........: 20470.4 MH/s`

**Comment by jsteube** [comment]
Please retry with latest hashcat beta: https://hashcat.net/beta/

**Comment by aliyazal** [comment]
@jsteube have still same problem with beta version.

**Comment by jsteube** [comment]
Please retry with CUDA

**Comment by jsteube** [comment]
No response from OP, feel free to reopen if you have updated informations.
