### ISSUE TITLE
Ryzen 3 2200G

### ISSUE THREAD

**Issue by Evilsturn** [hashcat/hashcat#2326]
Hi I am new to hashcat and overall password cracking and I ran into some problem.
My drivers are upto date. So idk what to do
![hproblem](https://user-images.githubusercontent.com/62092586/76497260-a9679f80-6460-11ea-870f-775a7228248f.JPG)

**Comment by jsteube** [comment]
Please retry with latest beta version: https://hashcat.net/beta/

**Comment by Evilsturn** [comment]
> Please retry with latest beta version: https://hashcat.net/beta/

It still gives me the same error.

**Comment by jsteube** [comment]
It's a driver error. Please continue the thread on hashcat forum. GitHub issues are for bugs and feature requests only.
