### ISSUE TITLE
Getting "Exhausted" result even with 100% progress 

### ISSUE THREAD

**Issue by NimaaaNomaaa** [hashcat/hashcat#2328]
I can't stand this anymore
the final output is: 
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: WPA-EAPOL-PBKDF2
Hash.Target......: dom18 (AP:b0:b2:dc:89:05:2e STA:bc:e1:43:07:e4:ee)
Time.Started.....: Fri Mar 13 20:49:25 2020 (17 mins, 4 secs)
Time.Estimated...: Fri Mar 13 21:06:29 2020 (0 secs)
Guess.Base.......: File (/mnt/d/stuff/WordList/rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     9189 H/s (6.13ms) @ Accel:64 Loops:256 Thr:1 Vec:4
Recovered........: 0/1 (0.00%) Digests
Progress.........: 14344384/14344384 (100.00%)
Rejected.........: 4734913/14344384 (33.01%)
Restore.Point....: 14344384/14344384 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: $HEX[212121313233343536] -> $HEX[042a0337c2a156616d6f732103]

Im using Ubuntu 16.0 Windows Distributive for this
The code is: `./hashcat -m 2500 -a 0 /mnt/d/stuff/captured.hccapx /mnt/d/stuff/Wordlists/rockyou.txt`
I don't have any error's coming up when starting a crack
and i ABSOLUTELY have no idea what im doing wrong

**Comment by NimaaaNomaaa** [comment]
ffs i inserted the code wrong

**Comment by ZerBea** [comment]
Possible reasons:
1. The PSK is not in the wordlist. rockyou.txt is not the best choice.
2. the hccapx file is crappy. How did you convert it?

**Comment by NimaaaNomaaa** [comment]
I've made the hccapx file with Wifi-autopwner.
I captured the handshake and used the option "Bruteforce the handshake"

**Comment by ZerBea** [comment]
As far as I know, Wifi-autopwner runs aircrack suite. That isn't the best choice in combination with hashcat. Please attach the original cap file to check, if it is ok.

**Comment by NimaaaNomaaa** [comment]
smh my kali desktop went nuts and i can't do anything

**Comment by ZerBea** [comment]
No problem. If your desktop is ready again, please do the following steps:
Download hccapx example from here:
https://hashcat.net/misc/example_hashes/hashcat.hccapx
and test it running hashcat:
$ haschcat -m 2500 hashcat.hccapx -a3 "hashcat!"

We expect a result similar like this:
```

$ hashcat -m 2500 hashcat.hccapx -a3 "hashcat!"
hashcat (v5.1.0-1745-g434ad763) starting...

CUDA API (CUDA 10.2)
====================
* Device #1: GeForce 940M, 1884/2004 MB, 3MCU

OpenCL API (OpenCL 2.1 ) - Platform #1 [Intel(R) Corporation]
=============================================================
* Device #2: Intel(R) Gen9 HD Graphics NEO, 6226/6290 MB (3145 MB allocatable), 24MCU

OpenCL API (OpenCL 1.2 CUDA 10.2.141) - Platform #2 [NVIDIA Corporation]
========================================================================
* Device #3: GeForce 940M, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 233 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.  

aef50f22801c:987bdcf9f950:8381533406003807685881523:hashcat!
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Name........: WPA-EAPOL-PBKDF2
Hash.Target......: 8381533406003807685881523 (AP:ae:f5:0f:22:80:1c STA:98:7b:dc:f9:f9:50)
Time.Started.....: Sat Mar 14 16:38:22 2020 (0 secs)
Time.Estimated...: Sat Mar 14 16:38:22 2020 (0 secs)
Guess.Mask.......: hashcat! [8]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       22 H/s (0.55ms) @ Accel:8 Loops:64 Thr:1024 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:64 Loops:16 Thr:8 Vec:1
Speed.#*.........:       22 H/s
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-16
Candidates.#1....: hashcat! -> hashcat!
Candidates.#2....: [Generating]
Hardware.Mon.#1..: Temp: 39c Util: 20% Core:1071MHz Mem: 900MHz Bus:4
Hardware.Mon.#2..: N/A

Started: Sat Mar 14 16:37:51 2020
Stopped: Sat Mar 14 16:38:24 2020
```

In that case, everything is fine.

Successfully retrieving a PSK depend
- on the quality of the cap file,
- on the quality of the conversion tool,
- on the quality of the wordlist,
- and hashcat.

If you got similar results as above, hashcat is doing a good job and there are no issues to report here. You can close this issue report, because there is nothing to do.
If you can't retrieve the PSK from your hccapx file, either the PSK is not in the wordlist. In that case I suggest you to use a "better wordlist" than rockyou. This list is very old!
Or the cap file is crappy. A crappy cap file converted to hccapx will cause a crappy hccapx file and hashcat isn't able to recover the PSK. In that case I suggest you to make an issue report here:
https://github.com/Mi-Al/WiFi-autopwner
If you take a closer look at that script, you'll notice that the conversion to hccapx is done here:
`line  476: sudo aircrack-ng -j "hccapx/$ESSID" "handshakes/$theLastDir/$AP"`
and that is definitely not the recommended way for hashcat.

**Comment by NimaaaNomaaa** [comment]
Yep, confirmed that all the hccapx files are junky, and the test hash got cracked
Thank you for the help!

**Comment by NimaaaNomaaa** [comment]
the funniest thing is: i managed to crack one hash, looks like i got lucky with that not being junky!

**Comment by ZerBea** [comment]
I recommend to move to latest git head of hashcat (upcoming v6.0.0) to get full benefit of new hashmode 22000
`
  22000 | WPA-PBKDF2-PMKID+EAPOL                           | Network Protocols
`

**Comment by ShadowCyber1** [comment]
Same Problem its say EXHAUSTED but i have correct password in a wordlist when i put it. HOW I FIX IT?

**Comment by ZerBea** [comment]
Please add dump file (zip compressed) and correct password.


BTW:
I don't think it as a hashcat problem. This is a bug tracker, so it might be better to get support on hashcat, rather than here.
Also it would be helpful if you comment the entire commandline and the entire hashcat status output.
