### ISSUE TITLE
7100-OSX v10.8+ (PBKDF2-SHA512) Token length incorrect

### ISSUE THREAD

**Issue by kontrast23** [hashcat/hashcat#2331]
current hash-legth is set to 128 (also seen in example-hash-list)
real "current" hash is length 256, e.g. (plain: 1111):
$ml$49504$0dba6246bd38266b2e827ff7e7271380757c71d653893aa361d5902398302369$c5f198639915a101c99af326dffe13e8f14456be8fd2312a39a777b92178804e204ca4fee12a8667871440eff4288e811d86d746c6d96a60c919c3418dfebba42f329f5d73c0372d636d61d5dfda1add61af36c70e4acd771276107209e643ae92a0f43e95a452744e50fb4540d9bdf4e0b701725d7db488fbe18c1ab7737c6b
therefore no current 7100 are accepted atm by hashcat
can you please adjust?

**Comment by Banaanhangwagen** [comment]
(This is not a Hashcat issue)
Your hash needs to have the exact same format as found here: https://hashcat.net/wiki/doku.php?id=example_hashes

You can find more info here: https://hashcat.net/forum/thread-7792.html

**Comment by kontrast23** [comment]
Hi, 
thanks for your answer Banaanhangwagen; but it's not correct
with older hashcat version it's working, as the length limit was set correct; only in newer versions the length got limited which denies tasks on this valid hashes.
the example-hashes-list does not cover all potential options afaik

**Comment by jsteube** [comment]
It should be no problem to increase the digest length so it will work with the 128 bit and the 256 bit version. The real question is that really the maximum length we can expect from the "original" exporting tool? Which tools are you using to export the hash and how does it look like from the shell, can you paste?

**Comment by kontrast23** [comment]
it is extracted from a shadow plist (https://apple.stackexchange.com/questions/186893/os-x-10-9-where-are-password-hashes-stored)
256 seems to be the current version/length on mac os x

**Comment by jsteube** [comment]
Added support with commit https://github.com/hashcat/hashcat/commit/a6cf7caf4a522dba39b7b8d9a144b86f7a0a5415
