### ISSUE TITLE
 How do I install hashcat new version in hashtopolis latest version?

### ISSUE THREAD

**Issue by RobertLutece1** [hashcat/hashcat#2334]
How do I install hashcat new version in hashtopolis latest version?

I can’t understand which link to insert in crackers. Please help me.

I have installed 5.1.0 now. There are not many recent updates.

**Comment by jsteube** [comment]
There will be 6.0.0 version soon. If you want to use the beta use the copy the hashcat beta binary to a spot where your agents can reach it, i.e. the server where hashtopolis runs on. Please ask on hashtopolis support forum.
