### ISSUE TITLE
"make" compilation error - Latest version

### ISSUE THREAD

**Issue by ims1337** [hashcat/hashcat#2336]
I was installing Hashcat on kalilinux after updating Kali its self. Downloaded Hashcat and when i do make to compile it give me an error. I tried a lower version but same story.

Can you please help me with it, Really urgent to crack a hash.

`root@kali:~/hashcat# sudo make
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/affinity.c -o obj/affinity.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/autotune.c -o obj/autotune.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/backend.c -o obj/backend.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/benchmark.c -o obj/benchmark.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/bitmap.c -o obj/bitmap.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/bitops.c -o obj/bitops.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/combinator.c -o obj/combinator.NATIVE.o -fpic
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/common.c -o obj/common.NATIVE.o -fpic
In file included from src/backend.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
In file included from src/benchmark.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
In file included from src/bitmap.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
In file included from src/autotune.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
In file included from src/common.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
In file included from src/bitops.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
In file included from src/combinator.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
In file included from src/affinity.c:6:0:
include/common.h:40:10: fatal error: string.h: No such file or directory
 #include <string.h>
          ^~~~~~~~~~
compilation terminated.
src/Makefile:480: recipe for target 'obj/common.NATIVE.o' failed
make: *** [obj/common.NATIVE.o] Error 1
make: *** Waiting for unfinished jobs....
src/Makefile:480: recipe for target 'obj/bitops.NATIVE.o' failed
make: *** [obj/bitops.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/autotune.NATIVE.o' failed
make: *** [obj/autotune.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/backend.NATIVE.o' failed
make: *** [obj/backend.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/benchmark.NATIVE.o' failed
make: *** [obj/benchmark.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/bitmap.NATIVE.o' failed
make: *** [obj/bitmap.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/combinator.NATIVE.o' failed
make: *** [obj/combinator.NATIVE.o] Error 1
src/Makefile:480: recipe for target 'obj/affinity.NATIVE.o' failed
make: *** [obj/affinity.NATIVE.o] Error 1
`

**Comment by u666sa** [comment]
Type gcc --version see what version.
Type sudo updatedb then locate gcc and cd into that directory as root and type ls gcc* see what other versions you have available.

In later vesions of C++ there is no string.h. The solution should be to install older gcc, but don't quote me on this one.

**Comment by philsmd** [comment]
maybe you are missing some basic headers/libraries etc. because string.h is basically available anywhere a gcc / g++ compiler can be run.

under ubuntu normally it's enough to just install the package `build-essential`

I think this is a problem that is not specific to hashcat. You probably can't even compile a simple ANSI C program that involves the string.h include.

I think this is not a hashcat bug and therefore I would suggest to close it and maybe you can ask for help on your distros forums or even in the developer section of the hashcat forum (but again, I don't think a problem involving string.h not being found has anything to do with hashcat).
Thx
