### ISSUE TITLE
Out of memory with 21700 and 21800 hash types

### ISSUE THREAD

**Issue by ahvahsky2008** [hashcat/hashcat#2338]
Others hashtypes works perfect, but i have troubles with 2 hashtypes  - **21700** and **21800**
Hashcat version **v5.1.0-1755-gddb641b8**
`hashcat64.exe --machine-readable --quiet --runtime=30 --restore-disable --potfile-disable --session=hashtopolis -p "\t" ..\\..\\hashlists\\19 -a 3 ?l?l?l?l?l?l  --hash-type=21700  -o ..\\..\\hashlists\\19.out
`
its show error 
LLVM ERROR: out of memory 

my devices
![image](https://user-images.githubusercontent.com/8035828/77246323-294af200-6c37-11ea-9b9e-2015bd876560.png)

Windows 10.0.17763
RAM 8GB

**Comment by Chick3nman** [comment]
You have 8 GB of system ram on a system with 4x 11GB video cards. You need more system RAM, with a good minimum being at least 44GB, to support all 4 cards in all possible attack configurations. Out of memory issues are common with systems that have too little RAM for their GPUs. 

Now, it is technically possible that this is not your issue, but I would start troubleshooting there by placing more RAM in the system if possible.

**Comment by ahvahsky2008** [comment]
I added 16GB and all works

**Comment by Chick3nman** [comment]
Good, no issue here, Please close.
