### ISSUE TITLE
cudaHashcat fails to crack netscreen credentials with username longer than 10 characters.

### ISSUE THREAD

**Issue by tmzh** [hashcat/hashcat#234]
**Platform:**

```
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10586)
      System Manufacturer: ZOTAC
             System Model: ZBOX-EN760
                     BIOS: B248P002
                Processor: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 CPUs), ~2.3GHz
                   Memory: 8192MB RAM
                Card name: NVIDIA GeForce GTX 860M
             Manufacturer: NVIDIA
                Chip type: GeForce GTX 860M, 2048MB, 1084Mhz, 5MCU
```

**How to reproduce**

Generate hash using publicly available [netscreen.py](https://github.com/piyushcse29/john-the-ripper/blob/master/run/netscreen.py) (output verified independently on real equipment)

```
python netscreen.py netscreen netscreen   >  screenos.txt
python netscreen.py netscreeny netscreen  >> screenos.txt
python netscreen.py netscreenie netscreen >> screenos.txt


Contents of screenos.txt
nKVUM2rwMUzPcrkG5sWIHdCtqkAibn:netscreen
nIu5FsrFBNIBc79HVsABRFLt0cEyDn:netscreeny
nKNBG9rwFqhOc9VDqskJjeJtMwE96n:netscreenie

Contents of dict.txt
netscreen

Command
cudaHashcat64.exe -m 22 screenos.txt dict.txt

Result
nKVUM2rwMUzPcrkG5sWIHdCtqkAibn:netscreen:netscreen
nIu5FsrFBNIBc79HVsABRFLt0cEyDn:netscreeny:netscreen
```

**Comment by philsmd** [comment]
Thank you very much for reporting this issue and especially in this very clear and understandable format (even with "working" examples).
Pull request #259 should fix this problem, by increasing the max. salt length to 28 (55 - 22 - 1 - 4 as explained in #259).
This should be enough to fit even the longest usernames.

Thanks again

## 

BTW: just to be very clear about the limits: we have 2 limits here
- salt + 22 + pass must be less than 55
- salt itself must now be less than 29 (up to 28 - included - is supported)
