### ISSUE TITLE
Hashcat freezes in end

### ISSUE THREAD

**Issue by ahvahsky2008** [hashcat/hashcat#2341]
Hashcat version **v5.1.0-1755-gddb641b8**
Progress freezes on **98.55** percentage. 
`hashcat64.exe --machine-readable --quiet --runtime=30 --restore-disable --potfile-disable --session=hashtopolis -p "\t" ..\\..\\hashlists\\19 -a 3 ?l?l?l?l?l?l --hash-type=21700 -o ..\\..\\hashlists\\19.out`

This situation on 21700 and 21800 algos

**Comment by jsteube** [comment]
Can you please provide all information developers need to reproduce this on our development systems?

**Comment by ahvahsky2008** [comment]
@jsteube I noticed one pattern. Hashcat works with little length hash 21700. But when i try solve `?l?l?l?l?l?l` - its freeze on end.

**Comment by philsmd** [comment]
note: that we recently got a very similar problem report in the forum: https://hashcat.net/forum/thread-9081.html , it might or might not be related, but we definitely need to have some reproducible steps.

Maybe somebody can test if this only happens with a specific combination of password candidates and/or setups. Does this also happen with the CPU (e.g. with -D 1) ?

We would need more details to see when exactly this happens and being able to reproduce this every time with a minimal example
