### ISSUE TITLE
Problem executing hashcat (Aborting session due to kernel self-test failure)

### ISSUE THREAD

**Issue by DrShams** [hashcat/hashcat#2343]
root@kali:/home/sithis/SecLists/Passwords/WiFi-WPA# hashcat -m 16800 galleriaHC.16800 -a 0 --kernel-accel=1 -w 4 --force 'probable-v2-wpa-top4800.txt'
hashcat (v5.1.0-1755-gddb641b8) starting...

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.
OpenCL API (OpenCL 1.2 pocl 1.4, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
=============================================================================================================================
* Device #1: pthread-AMD Ryzen 5 3600 6-Core Processor, 10851/10915 MB (4096 MB allocatable), 4MCU

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 4 digests; 4 unique digests, 4 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Slow-Hash-SIMD-LOOP

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 64 MB

clEnqueueNDRangeKernel(): CL_OUT_OF_RESOURCES

Aborting session due to kernel self-test failure.

You can use --self-test-disable to override this, but do not report related errors.

**Comment by Chick3nman** [comment]
Please read the huge warnings I implemented that got thrown when you used `--force`. Then, after reading and understanding those huge warnings, close this issue.

**Comment by jsteube** [comment]
This is not a hashcat issue. I have disabled the use of POCL/MESA/NEO/Beignet and will reenable them as soon as they are fixed. Commit: https://github.com/hashcat/hashcat/commit/008072eb65cb104cfa0fe30f7e80798eca23987f

**Comment by DrShams** [comment]
As I understood I have to type only
 hashcat -m 16800 galleriaHC.16800 -a 0 --kernel-accel=1 -w 4 'probable-v2-wpa-top4800.txt'

without --force?
