### ISSUE TITLE
Support for POclReleaseMemObject issue

### ISSUE THREAD

**Issue by DrShams** [hashcat/hashcat#2344]
hello, please help me to solve that problem...

hashcat (v5.1.0-1755-gddb641b8) starting...
...
OpenCL API (OpenCL 1.2 pocl 1.4, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
...
* Device #1: pthread-AMD Ryzen 5 3600 6-Core Processor, 10851/10915 MB (4096 MB allocatable), 4MCU

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 4 digests; 4 unique digests, 4 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Slow-Hash-SIMD-LOOP

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 64 MB

Initialized device kernels and memory...hashcat: /build/pocl-zs5kii/pocl-1.4/lib/CL/clReleaseMemObject.c:41: POclReleaseMemObject: Assertion `r == 0' failed.
Aborted

**Comment by jsteube** [comment]
This is not a hashcat issue. I have disabled the use of POCL/MESA/NEO/Beignet and will reenable them as soon as they are fixed. Commit: https://github.com/hashcat/hashcat/commit/008072eb65cb104cfa0fe30f7e80798eca23987f

**Comment by pjaaskel** [comment]
Was there an associated pocl issue with this, and what made you come to the conclusion that it's not a hashcat issue?
