### ISSUE TITLE
XenForo algs

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#235]
Hello. In most cases Xenforo create hashes with XenForo_Authentication_Core and sha256/sha512:
sha256(sha256(password) . salt)
sha512(sha512(password) . salt)
Please, add this algs in oclHashcat.

**Comment by jsteube** [comment]
In theory, it should be easy to write that mode yourself. See -m 2610 if you need inspiration :)

**Comment by ghost** [comment]
I'm not C coder, i can`t do it myself :(

**Comment by Fist0urs** [comment]
Apparently, Xenforo default encryption scheme is using bcrypt. It also supports many different kind of encryption schemes, so these are particular cases. You must provide all schemes within this software

**Comment by AgelxNash** [comment]
XenForo kernel supports 2 encryption schemes:
**sha1(sha1($hash).$salt);**

> 8923d65394a85921b336e42ae89e93e28c5c381a:824acdc9c2276bc1b7b9a9ec22684e6ac4b55eda:**1**
> bc35e95b25b49ae6f8c7f903e16d339514585322:2661f4457c4d9ab6c4c5fffa539cfb7f12bdede0:**123**
> f14871a534e1b61211c39455c61acede6e588ea0:64269efd0831d0a031c8a98c8c090b6eb6124962:**qweqwe**

**sha256(sha256($hash).$salt);**

> f92f8c9de94d3d581c022320c6d812f14e48e2c239c88c255d5acd63edd1fc3a:6f70c9b20542c519285aa7bfbb10ce94113046c3bd1d27b16708c30ffe552194:**1**
> fcd42e07f1cb80704e859e2a371598dac3288546fad759551a21ca432955ff4d:b436a8594e03c5c8094fefac24f2e69ef6891a8a78e2608fd3ecd65d18154beb:**123**
> 697a718659641f5bd8235d56e2a77bf2fd68d081d3c78bb20653e1c239484f0a:c753530edd8c4fbab38bcb07daeeaa58e7f3011c1260859a91dd304c55e8da8d:**qweqwe**

[Source](https://gist.github.com/AgelxNash/4c1951c1dd1d409beca4b7d8ae67f11b)

**Comment by Fist0urs** [comment]
@AgelxNash I don't get what are supposed to be hash and salt in your examples, the two parts have either 20:20 bytes or 32:32 bytes

**Comment by AgelxNash** [comment]
@Fist0urs hash:salt:password

**Comment by Fist0urs** [comment]
wow the salt is as long as the hash? oO

**Comment by AgelxNash** [comment]
The original salt has a length of 10 characters. But it's not known, since in the database are stored encrypted by the selected method: sha1/sha256.

**Comment by Fist0urs** [comment]
So in case of SHA1, it would be : sha1(sha1(password).sha1(salt)) with sha1(salt) as "new" salt?

**Comment by AgelxNash** [comment]
Yes

**Comment by Fist0urs** [comment]
I can't reproduce the output of the first hash:

hashlib.new("sha1", hashlib.new("sha1", "1").digest()+"824acdc9c2276bc1b7b9a9ec22684e6ac4b55eda".decode("hex")).hexdigest()
'5218723a13afe0b988ec1c3dc2bb7699e2f7d2d2'

**Comment by AgelxNash** [comment]
Regex to match original salt `/^[a-f0-9]{10}$/`
If this is important...

``` Python
import hashlib

password = '1'
salt = '824acdc9c2276bc1b7b9a9ec22684e6ac4b55eda'

print hashlib.new("sha1", hashlib.new("sha1", password).hexdigest() + salt).hexdigest()
```

**Comment by Fist0urs** [comment]
Oh that's odd, it's based on hexdigest. Thanks, I'll try to take a look

**Comment by roycewilliams** [comment]
This September 2018 hashcat-based implementation is MIT-licensed:

https://gist.github.com/tbiehn/28531fdb324baaeaa2960aae1b9b36ab

**Comment by ghost** [comment]
https://github.com/hashcat/hashcat/compare/master...MilzoCSP:master

Needs a little more work, but it's a start.
The new kernels checkout but mode -a 3 needs implemented.

**Comment by jsteube** [comment]
Support for sha256(sha256(password) . salt) was added as -m 20710
Support for sha512(sha512(password) . salt) is still missing. It should be easy to add, just need to be done by someone :)

**Comment by matrix** [comment]
Support for sha512(sha512(password) . salt) was added as -m 32410
