### ISSUE TITLE
LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by DrShams** [hashcat/hashcat#2352]
Hello everyone, how to solve this ?

root@kali:~# hashcat -I
hashcat (v5.1.0-1755-gddb641b8) starting...

: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
root@kali:~# hashcat -I
hashcat (v5.1.0-1755-gddb641b8) starting...

**: CommandLine Error: Option 'limited-coverage-experimental' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options**

root@kali:~# uname -a
Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

**Comment by jsteube** [comment]
This is not a hashcat issue. I have disabled the use of POCL/MESA/NEO/Beignet and will reenable them as soon as they are fixed. Commit: https://github.com/hashcat/hashcat/commit/008072eb65cb104cfa0fe30f7e80798eca23987f
