### ISSUE TITLE
[Feature Request] Permutation Combiner Attack

### ISSUE THREAD

**Issue by forgotPassword** [hashcat/hashcat#2354]
This attack is useful when trying to crack url signatures. Eg many mobile applications sign their http requests, (client) secret keys can be easily extracted, then instead of spending time reversing the steps, it would be great to pass everything to hashcat and it would try to crack it.

Example:
http://example.com/?a=1&b=2&sig=8ef99d4bbe38324179bf4d853d7ad0fd

The application computes the hash: md5('example.com' + 'a' + '1' + 'b' + '2' + ',' + 'secret_key');

Ideally you would pass hashcat:

- list of items : `'http://', '/', 'example.com', 'a', 'b', '1', '2', 'secret_key', 'app_id', 'user_id'`
- list of joiners : `'', ',', '&', '='`
- number of items to try to join (6 in our case)

Hashcat will try all possible permutations of items, with all possible permutations of joiners, and apply the selected hashing function (md5).

Can you point me in the right direction, is this possible with hashcat, would you be interested in pulling such a feature?

**Comment by Chick3nman** [comment]
This is basically PRINCE but with configurable separators for each "field" or "string". Not sure how much application this has as a built in attack mode, it may be worth playing with Prince Processor and maybe adding any missing functionality to it instead.

**Comment by philsmd** [comment]
I also think that this is a too specific user problem... a user could have any slightly variant of this and therefore the "new feature" wouldn't work for them...
In such cases I would suggest to try testing with rules and/or use a very fast password generation script/program that pipes the input to hashcat in -a 0 mode. You could even pre-compute a small dict (but of course, this only makes sense if the total number of password candidates is quite small and you probably would still want to combine this approach with hashcat rules etc).

All in all, I think this is a case of very special input that can't really be generalized very easily to make it flexible enough that other users could benefit from it a lot. What if a user for instance knows that 2 out of 5 fields are fixed etc ?... it would be a waste to try guaranteed "wrong" password candidates .... therefore I think it's better to use a more specific tool or rules or pre-computed word-lists etc

Should we move this discussion to the hashcat forum ? Would you mind @forgotPassword to try to explain your strategy/problem on the hashcat forum @ https://hashcat.net/forum and discuss this problem there ? I think it would **NOT** make much sense to leave this issue open if we have no general idea what can/should be done in the hashcat code for this issue (no clever/flexible approach that would make sense also performance-wise etc known yet) ? Thx

**Comment by jsteube** [comment]
I agree with both @Chick3nman and @philsmd you could use princeprocessor and create a wordlist. In the end, there are too many unknowns. I think we have to go the hard way and reverse the steps, as you have written.
