### ISSUE TITLE
ERROR: clFinish() : -36 : CL_INVALID_COMMAND_QUEUE error in the latest pull of OCLHashcat

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#236]
Hi, it looks like  6c10ca5 introduced a Command Queue error It looks like it persists with md4 and md5 but not dcc2, it probably persists across more algorithms but those are the ones I have tested so far. A example is bellow:

```
sudo ./oclHashcat -b
oclHashcat v2.01 (g6c10ca5) starting in benchmark-mode...

Device #1: GeForce GTX 980 Ti, 1535/6143 MB allocatable, 1190Mhz, 22MCU
Device #2: GeForce GTX 980 Ti, 1535/6143 MB allocatable, 1190Mhz, 22MCU

Hashtype: MD4



ERROR: clFinish() : -36 : CL_INVALID_COMMAND_QUEUE




ERROR: clFinish() : -36 : CL_INVALID_COMMAND_QUEUE

```

**Comment by roycewilliams** [comment]
Try deleting the ./kernels directory and ~/.nv/.  I had this symptom until I did so.

**Comment by thesle3p** [comment]
That fixed it thanks.

**Comment by roycewilliams** [comment]
Great!  If you could close this ticket as resolved, that will make housekeeping easier.
