### ISSUE TITLE
Where dictionary cache is located?

### ISSUE THREAD

**Issue by megapro17** [hashcat/hashcat#2368]
Couldn't find any information in google or wiki
I want to delete it for old dictionaries that I no longer use

**Comment by philsmd** [comment]
`hashcat.dictstat2`

is a file within your hashcat folder (or located under ~/.hashcat/ if you installed hashcat with "make install")

Please don't forget to close this github issue and consider asking these types of question on the hashcat forum (which is better suited for this kind of requests/questions)... The forum also has a search function and many of similar question have already been discussed/explained in detail. The github issue tracker, on the other hand, is better suited for bug/problem reports and requesting new hashcat algorithms or features.

Thanks a lot. cheers

**Comment by shohabmsk** [comment]
where is it located on windows? I saw hashcat taking many storage when building 98gb dictionary cache, but i had a powerloss and im seeing some space is occupied, but cant find it anywhere.

**Comment by megapro17** [comment]
In a app directory
Or use ultrasearch to find it instantly
