### ISSUE TITLE
MacOS X 10.15.4 with Radeon Pro 560x gives openCL issues

### ISSUE THREAD

**Issue by commjoen** [hashcat/hashcat#2370]
Thank you for Hashcat! I love it!
I am running into the following problem, after doing `brew install hashcat` and then running it to do some JWT cracking, I end up with the following log:
```sh
hashcat -a0 -m 16500 bearer.hash google-10000-english/google-10000-english.txt
hashcat (v5.1.0) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, skipped.
* Device #2: Intel(R) UHD Graphics 630, 384/1536 MB allocatable, 24MCU
* Device #3: AMD Radeon Pro 560X Compute Engine, 1024/4096 MB allocatable, 16MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #3: Kernel /usr/local/Cellar/hashcat/5.1.0/share/hashcat/OpenCL/m16511_a0-pure.cl build failed - proceeding without this device.
```
How can I still make use of device 3? because i think it will have the most horsepower if it comes to computing the hash...

**Comment by philsmd** [comment]
did you try to use the latest code of hashcat ?
try to git clone, make it and run it from the cloned directory directly with "./hashcat ...", does the latest code fix the problem ?

Do also other hash types have this problem or only JWT ? It's probably a driver bug/problem if all other devices work correctly (even on your system). Not sure how much we could do here ?

maybe try updating or downgrading macOS versions / drivers and as said above test latest hashcat version (or even test with older version, just for testing purposes, from https://hashcat.net/hashcat) .

Thanks

**Comment by commjoen** [comment]
Building it from source gives me:
```
Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:7:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^

* Device #2: Kernel /Users/razor/Documents/workspace/hashcat/OpenCL/shared.cl build failed.

```

**Comment by commjoen** [comment]
Not sure what it can be, when i do brute forcing, it does work: e.g. i have both videochips that can do the hashing.

**Comment by philsmd** [comment]
I think this only proofs again, that there is something wrong with the drivers. As far as I understand, the same code works with other drivers/cards and even on other operating systems etc.

That said, we had some problems in the past with the OpenCL kernel compiler include flags (-I for include files etc)...

I think this might be unrelated to your original post, but it shows again, that something is really broken with the AMD drivers on macOS... we probably need some (at least little bit experienced) hashcat users that have the hardware and can do some testing and troubleshooting.

For that I've now opened a new hashcat forum thread: https://hashcat.net/forum/thread-9206.html
maybe you can contribute there and try to pinpoint this new problem.

I think the forum is a better platform to find a couple of hashcat users and maybe it's even better to discuss the problem and related problems for macOS there.

There could be a pattern on when this was introduced and on which version of the operating system users will get this error: https://github.com/hashcat/hashcat/search?q=%27inc_vendor.h%27+file+not+found&unscoped_q=%27inc_vendor.h%27+file+not+found&type=Issues

... but I didn't yet fully understand the problem, besides that it could be the AMD OpenCL kernel compiler flag (-I) that is broken, maybe only with some specific paths etc... dunno

Would you mind trying to mess around older version and older commits of hashcat and report your finding on the hashcat forum thread ? That would be great

I'm not sure if the "cvms_element_build_from_source" error is related... so I think we shouldn't really discuss 2 problems in this github issue.

Let's just try to make the latest hashcat code working again with the new macOS version or latest Apple hardware etc... by trying to find some fixes/workarounds etc.
Thx

**Comment by jsteube** [comment]
Please retry with hashcat 6.0.0 + 32 beta from https://hashcat.net/beta/ and reopen the issue if it still exists.

**Comment by johnelliott** [comment]
> I think this only proofs again, that there is something wrong with the drivers. As far as I understand, the same code works with other drivers/cards and even on other operating systems etc.
> 
> That said, we had some problems in the past with the OpenCL kernel compiler include flags (-I for include files etc)...
> 
> I think this might be unrelated to your original post, but it shows again, that something is really broken with the AMD drivers on macOS... we probably need some (at least little bit experienced) hashcat users that have the hardware and can do some testing and troubleshooting.
> 
> For that I've now opened a new hashcat forum thread: https://hashcat.net/forum/thread-9206.html maybe you can contribute there and try to pinpoint this new problem.
> 
> I think the forum is a better platform to find a couple of hashcat users and maybe it's even better to discuss the problem and related problems for macOS there.
> 
> There could be a pattern on when this was introduced and on which version of the operating system users will get this error: https://github.com/hashcat/hashcat/search?q=%27inc_vendor.h%27+file+not+found&unscoped_q=%27inc_vendor.h%27+file+not+found&type=Issues
> 
> ... but I didn't yet fully understand the problem, besides that it could be the AMD OpenCL kernel compiler flag (-I) that is broken, maybe only with some specific paths etc... dunno
> 
> Would you mind trying to mess around older version and older commits of hashcat and report your finding on the hashcat forum thread ? That would be great
> 
> I'm not sure if the "cvms_element_build_from_source" error is related... so I think we shouldn't really discuss 2 problems in this github issue.
> 
> Let's just try to make the latest hashcat code working again with the new macOS version or latest Apple hardware etc... by trying to find some fixes/workarounds etc. Thx

I have access to an intel Mac with AMD graphics (imac) to help with this. Today I was able to use the main branch here to compile and run on that machine.
