### ISSUE TITLE
Option to throttle speed

### ISSUE THREAD

**Issue by llamafilm** [hashcat/hashcat#2371]
On my machine, hashcat quits after a few minutes because the GPU exceeds 90º C, even running with `-w 1` and forcing GPU fans to 100%.  I think it would be nice to have a command-line option to throttle speed.  Perhaps this could be specified as `x%` GPU usage.

I tested on a HP Z840 with two Titan Xp.  This system does not have overheating issues with other applications.

**Comment by hops** [comment]
You can use nvidia-smi to limit the power usage of your GPUs. Check out this gist for reference
https://gist.github.com/roycewilliams/3e0a71d2f1fae83fba6b6b605ab3a5a4

The proper fix would be to make sure there's enough airflow in your system to dispense all the heat.
Personally I don't see the need to add a throttling feature to hashcat but that's not for me to decide.

**Comment by llamafilm** [comment]
Thanks, that's good enough for me.

**Comment by Joshfindit** [comment]
I would like to re-suggest this for two reasons:

1. VirtualSMC does not have the temperature monitoring for my Nvidia card
2. UI in MacOS is GPU-bound, and when the card is at 100% navigating through MacOS can stutter, but with a decent card even 2% free leaves more than enough for buttery smoothness.

**Comment by Joshfindit** [comment]
*Also: there is no `nvidia-smi` for MacOS*

**Comment by aenagy** [comment]
I too would like to see more/better control over CPU/GPU throttling. Having to start over because CPU temperature kinda is underwhelming. As a suggestion it would be good to specify that if the temperature reaches a safety threshold, e.g. Tmax - 10C or some such, then ease back on the rate. At least this would allow the crack jobs to finish.
