### ISSUE TITLE
Hashcat driver not compatiable and unavailable in Ubuntu for my card. What options do I have?

### ISSUE THREAD

**Issue by vikas-kundu** [hashcat/hashcat#2378]
My OS version is Ubuntu 18.04.4 LTS.
The graphics card I have is: AMD Radeon™ R5 M430 Graphics (2 GB DDR3 dedicated)
I checked on the official AMD site, there are no drivers in Ubuntu for this card. When I run hashcat, this happens:

```
hashcat --benchmark
hashcat (v4.0.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.
Segmentation fault (core dumped)
```
Now since, there is no driver for my card what options do I have?
1. Can I use drivers of other versions say AMD R5 M330 series?
2. Or should I use older versions of Hashcat ?
3. Or any other suggestions?

**Comment by philsmd** [comment]
why do you use such an old version of hashcat ? please test with release version or even beta from https://hashcat.net/beta/

It really seems to be a driver/setup problem, not a hashcat bug/problem. The driver seems to be crashing on your system.

Is your GPU supported by latest amdgpu drivers ? I don't think ROCm supports it, but you could try.

At the end, I would suggest that you are trying to ask/discuss/troubleshoot user configuration/setup problems like this on the hashcat forum.
The github issue tracker is mainly use for source code bugs/problem, new features or new algorithms for hashcat, not really suitable for user setup problems/questions. Please do NOT forget to close this issue. Thank you so much

**Comment by vikas-kundu** [comment]
Thank you so much for answering.
