### ISSUE TITLE
Strict check of salt components in WPA (-m 2500) mode

### ISSUE THREAD

**Issue by gpuhash** [hashcat/hashcat#238]
While experimenting with synthetic handcrafted multi-handshake HCCAP files we discovered that oclHashcat does not recognize unique salts in WPA (-m 2500) mode even if all WPA salt components are the same (but the MIC fields are different due to different known passwords used). Despite this situation is practically impossible in real handshakes due to ANonce and SNonce randomness, it will be quite useful to have strict stamping of WPA salt components.
Possible use of this feature is some kind of WPA proof-of-work system then untrusted worker gets several synthetic HCCAP handshakes with the same salt components but with different MIC fields.
He should find all possible password candidates not knowing who is the real one. If oclHashcat recognises these handshake as non-unique salts the performance of cracking drops significantly.
We tested our patch with few synthetic multi-handshake HCCAP files and found that now it reliable detects unique salts in WPA mode.

Pull request: https://github.com/hashcat/oclHashcat/pull/237

**Comment by philsmd** [comment]
hmm, the pull request was already merged ... but what I asked you (@gpuhash) here https://github.com/hashcat/oclHashcat/pull/237#issuecomment-188227146 is still valid. Can you please provide some more information + samples such that we have some docs ?
Thx

**Comment by gpuhash** [comment]
We created three test hccap files, all contain 3 digests with 3, 2 and 1 unique "salts".
Without our patch it always recognized as 3 unique salts and thus 3x time wasted.
All 3 passwords were successfully found during our tests (_Hint: all three passwords are 8-digit numbers_)

We can't imagine unique WPA salts in the real world (WPA salt isn't only ESSID, it is ESSID, both MACs, ANonce and SNonce as well) but this approach will be very handy for developing proof-of-work algorithms for distributed crackers.

[test_hccap.tar.gz](https://github.com/hashcat/oclHashcat/files/145295/test_hccap.tar.gz)

**Comment by jsteube** [comment]
Many thanks for the patch and the example data
