### ISSUE TITLE
$HEX[] syntax not recognized in self-tests

### ISSUE THREAD

**Issue by seger672** [hashcat/hashcat#2391]
In selftest.c, `$HEX[]` decoding is not performed. Hex passwords are only decoded if `OPTS_TYPE_PT_HEX` flag is set. This means passwords or salts in the `$HEX[]` format can not be used.

It is best to "train as you fight". Therefore, `selftest.c` should replicate or invoke `get_next_word` logic in `wordlist.c`, thereby invoking `convert_from_hex` and `iconv`. Currently, the code looks like this:

      if (module_opts_type & OPTS_TYPE_PT_HEX)
      {
        tmp.pw_len = hex_decode ((const u8 *) hashconfig->st_pass, (const int) tmp_len, (u8 *) tmp_ptr);
      }

**Comment by philsmd** [comment]
yeah, you could say it's a little bit lazy... but normally in such cases we try to avoid making the code more complex than needed and just use the hex representation of the plain text, for instance:
```
https://github.com/hashcat/hashcat/blob/ff37264c36a89bed32c4f5cff24dbf29bcb98642/src/modules/module_09810.c#L28
```
remember, that the $HEX[] feature is basically just a tool to make the user experience better, but for self-test with fixed strings, it makes absolutely no sense (in my opinion) to not just add the bytes AS-IS, without any need to run a superfluous/strange hex-converting process each and every run-time etc. That would be quite a waste of time/resources, even if it would be probably negligible fast (I admit)... but why should we make things more complicated by adding some additional decoding code that might also be buggy etc if we could just use the normal C/C++ syntax to add the bytes directly.


I think the question is actually not too bad, but I think we do not need this "feature" to parse/decode the simple hash passwords we have.
