### ISSUE TITLE
linux/version.h not found

### ISSUE THREAD

**Issue by fireridlle** [hashcat/hashcat#2394]
```
gcc -c -W -Wall -Wextra -O2 -pipe -std=gnu99 -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -DWITH_HWMON src/affinity.c -o obj/affinity.NATIVE.o -fpic
In file included from src/affinity.c:6:0:
include/common.h:88:27: fatal error: linux/version.h: No such file or directory
 #include <linux/version.h>
```

**Comment by philsmd** [comment]
This is probably not a hashcat bug/problem.

Please try to install some basic compiling tools that should be available on any developer system, e.g. like in ubuntu you would need:
```
sudo apt install build-essential linux-libc-dev git make
```
etc etc


This may warry from operating system to operating system and also be different on different linux distros etc... but the general idea should be clear: the basic compiling tools should be installed on any dev system.

Please also do not forget to close this issue and consider next time to write a little bit more about the details of your problems, what you have installed, what you are trying to do, what your system/hardware/OS specs looks like etc etc etc.

Thx
