### ISSUE TITLE
Use cases --increment for -m 2500 (WPA-EAPOL-PBKDF2)

### ISSUE THREAD

**Issue by ilya7zz** [hashcat/hashcat#2397]
There are not enough examples of using --increment in the manual
How to compose a syntax for enumerating from 8 to 12 characters digits?

##### hashcat64 -m 2500 -a 3 -i %hash% ?d?d?d?d?d?d?d?d?d?d?d?d

All my attempts do not change the execution:
Guess.mask .......:? D? D? D? D? D? D? D? D [8] - always 8
Please, help :)

**Comment by philsmd** [comment]
please ask questions like this on the hashcat forum.
The github issue tracker is only used for bugs/problems (or new features/algorithms).

To answer your question, hashcat will iterate/loop through all the masks one-by-one and therefore only report the current mask in the Guess.mask line.

What you are looking for is the "Guess.Queue" line in the status prompt, it will show how many masks are already completely finished, e.g. 1/5 means it is at mask one of five total. therefore this current mask plus 4 other masks are still in the queue (not started/done yet).

your command is therefore fine, but brute-forcing too long WPA passwords is probably not the most effective approach... we recommend rule-based (dictionary attack with rules) approaches for slow hash types (if the password is not 100% guaranteed to be random).

Please do not forget to close the issue
