### ISSUE TITLE
oclHashcat programming language for custom algo support

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#240]
With dropping cuda support oclHashcat generates runtime kernels that are run on OpenCL supported devices on the fly. Is it possible to implement some kind of language that would consist of already  implemented basic algorithms such as MD5 SHA1 and etc **pass *_and *_salt** keyword so that user can define custom algorithms that oclHashcat will run.
For example hashcat will generate custom kernel for this string just unrolling MD5(SHA256(pass).salt)

**Comment by jsteube** [comment]
I don't like the idea of a generic custom algo. JtR has such a "language" for CPU but it looks pretty complicated. There's alot of special cases that a user could need, or in other words, it can never be generic enough. Just an example: should the digest be in binary or encoded as ascii hex before hashing again, and if so, should it use lower or upper case. Do we need to truncate it at some point, etc. But the more complicated it becomes, the less useable it is.

I think if you really need to crack such a special algorithm that is used only a single implementation you should use JtR or your own cracker and if the system that uses that algorithm becomes popular enough we will add it to hashcat anyway.

**Comment by ghost** [comment]
Ok.
Is there any possibility to use already implemented kernel as preprocessing commands? to implement custom algo without copy paste existing code?
