### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by truesamurai** [hashcat/hashcat#2402]
I have a new build PC with AMD Sapphire Radeon 5500XT graphics card (not on virtualbox). The issue is that Hashcat does not detect the GPU. When I do lspci then the system can see the GPU, but its not detected by Hashcat (only the CPU is detected). I did not install any extra graphic drivers in Kali, for now its a fresh default Kali install. On the AMD website are Ubuntu drivers but when I try to install those I get a message that the OS is not correct. How should I proceed?

**Comment by philsmd** [comment]
Please first troubleshoot if some simple tools like `clinfo` are able to see your devices. If not, it's most likely not a hashcat problem/bug.

I think questions like this are more suitable for the hashcat forum (many of these are already answered -> search function). I don't see any hashcat bug/problem here. only a installation/configuration/setup/driver problem, that probably can be easily fixed if the driver supports your card (also see https://hashcat.net/faq/wrongdriver)

Please do not forget to close the issue
thx

**Comment by truesamurai** [comment]
When I do clinfo then I can see the device, only not in hashcat. I will look further into drivers.

**Comment by philsmd** [comment]
please post the clinfo output

and the output of

```
hashcat -I
```

thx
