### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ctkqiang** [hashcat/hashcat#2403]
I successfully run Hashcat and addedto _PATH_ENVIROMENT but when comes to usage like ```hashcat dir/file.txt``` it show me ```./hashcat.hctune: No such file or directory``` even though the file is there.

**Comment by philsmd** [comment]
I think you are just using it wrong.

on linux you can use "make install" (or some 3rd party and therefore not really recommended-by-us hashcat packages)... for the general usage you normally just move with "cd" into your hashcat path and execute hashcat directly like this:
on windows
```
hashcat.exe --help
````

on linux:
```
./hashcat --help
```

I think questions like this are better suited for the hashcat forum.... I don't think it's really a hashcat bug/problem and we probably shouldn't/can't do anything here (you either use the system-wide installed hashcat version or you navigate to the downloaded hashcat folder directly)

Please do not forget to close if this works for you.
thx

**Comment by ctkqiang** [comment]
This is what I got 

```
C:\Users\Johnmelodyme\Documents>hashcat.exe sd.txt
hashcat (v5.1.0) starting...

./hashcat.hctune: No such file or directory

Started: Sat May 16 05:55:45 2020
Stopped: Sat May 16 05:55:45 2020
```

I can use ```hashcat``` directly as I define in enviroment.

**Comment by philsmd** [comment]
I'm pretty sure this way of using hashcat is not supported. Where did you see that this environment variable can/should be used.
It's easier/better to just navigate into the correct folder... otherwise hashcat won't find the kernel files and other resources. It's not a supported feature.

**Comment by ctkqiang** [comment]
It works in other pc , but not my laptop.

**Comment by mpalmer** [comment]
Then I'd suggest checking what is different between your other PC and your laptop.

**Comment by ctkqiang** [comment]
> Then I'd suggest checking what is different between your other PC and your laptop.

Same model and same spec.
