### ISSUE TITLE
rules.txt has wrong comment for RULE_OP_MANGLE_SWITCH_AT 

### ISSUE THREAD

**Issue by Lense** [hashcat/hashcat#2413]
https://github.com/hashcat/hashcat/blob/f574cbc88a9fff8548e195cf6893411f7a9f0e3f/docs/rules.txt#L31

however `*` takes 2 positions to swap ([source](https://github.com/hashcat/hashcat/blob/e194fec2291e487d01c313934932ba782eed1367/src/rp.c#L400-L404))

the [wiki](https://hashcat.net/wiki/doku.php?id=rule_based_attack) matches the code's behavior:
>Swap @ p | *pM | Swaps character at position p with character at position M

**Comment by philsmd** [comment]
Thanks. I agree that this was incorrect.
I've suggested a change with PR #2418

**Comment by Lense** [comment]
Found another issue. I'll put it here because the PR isn't merged yet.

https://github.com/hashcat/hashcat/blob/f574cbc88a9fff8548e195cf6893411f7a9f0e3f/docs/rules.txt#L26-L27
 `z` and `Z` take count argument.
