### ISSUE TITLE
GPU invalid argument

### ISSUE THREAD

**Issue by 737simpilot** [hashcat/hashcat#2414]
I saw an issue here about this, but I have no idea how to fix it. This is what I get when I try running Hashcat. https://imgur.com/tX8LWn4

I'm using the GUI frontend.

**Comment by s77rt** [comment]
`--gpu-temp-disable` is now `--hwmon-disable`

https://hashcat.net/wiki/doku.php?id=hashcat

**Comment by 737simpilot** [comment]
What does that even mean? I am using the GUI frontend. I start Hashcat and I'm meant with that and nothing happens. I am using the latest from here.

**Comment by s77rt** [comment]
hashcat does not have an official gui
basically your gui software is using the command line argument `--gpu-temp-disable` to disable temp monitoring, however that argument is no longer exists and it's changed to `--hwmon-disable`  

Your options:

1. Use an older version that uses the `--gpu-temp-disable` arg
2. Use another gui try [hashcat.launcher](https://github.com/s77rt/hashcat.launcher)
3. Get rid of any gui and learn to use the cli

**Comment by 737simpilot** [comment]
Thanks. I tried your GUI and got an issue.

**Comment by philsmd** [comment]
it's not an official hashcat GUI. It's a third party tool, not developed by the hashcat developers.

You either need to contact the author of that 3rd party tool to ask for help or use hashcat without GUI (hashcat has no official GUI developed by the hashcat developers).

Please don't forget to **close** this issue, we can't do anything if you use an external tool that is not up-to-date with latest hashcat versions. We can't do anything here.
