### ISSUE TITLE
[DNSSEC/NSEC3] -a 7 on windows

### ISSUE THREAD

**Issue by exander77** [hashcat/hashcat#2415]
Does mode -a 7 work on Windows (v5.1.0)?

```
hashcat64.exe --status --status-timer 5 --potfile-disable --force -w 4 -m 8300 in.hashcat -a 7 -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy ?2?1?1?1?1 list -o in.res
```

Did not find anything, but there should be tens of thousands matches. On Linux, it worked fine. I am not able to crack a single hash in this mode on Windows.

Started with `-O` it ends without doing anything (that's also strange):
```
hashcat64.exe --status --status-timer 5 --potfile-disable --force -w 4 -O -m 8300 in.hashcat -a 7 -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy ?2?1?1?1?1 list -o in.res
```

Using mode `-3` with specifying one of the suffixes as part of the pattern works fine:
```
hashcat64.exe --status --status-timer 5 --potfile-disable --force -w 4 -m 8300 in.hashcat -a 3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy ?2?1?1?1?1aster -o in.res
```

Using mode `-a 1` worked fine as well.

**Comment by exander77** [comment]
Workaround:
```
#!/bin/bash
STRINGS=$(cat "$2")
for STRING in $STRINGS; do
  echo hashcat64.exe --status --status-timer 5 --potfile-disable --force -w 4 -m 8300 cz.hashcat -a 3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy "$1$STRING" -o cz.res
done
```
But is not efficient as it has big overhead, but it uses `-O` kernel.

It would be nice to be able to run multiple attacks on the same data loaded in the memory. Like the attack list:
```
-3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy "?2?1?1?1?1aster"
-3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy "?2?1?1?1?1orker"
-3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy "?2?1?1?1aster"
-3 -O -1 abcdeiklmnoprstuvy- -2 abcdeiklmnoprstuvy "?2?1?1?1orker"
...
```
This would be awesome. As it would simplify cracking by known attacks. People would be able to share these attack lists easily.

**Comment by philsmd** [comment]
The general rule is to never report a problem if you use `--force`.

What happens if you do not use that command line option ? ... maybe it's just a driver / configuration problem/bug and has nothing to do with linux/windows or the -m 8300 hash type (broken driver for instance).

I think for the second question (unrelated) you are just looking for the `mask file` support: https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files

an example could be:
```
hashcat -m 8300 -a 3 -w 3 -O hashes.txt mask_file.txt
```

where the file "mask_file.txt" contains the following lines:
```
abcdeiklmnoprstuvy-,abcdeiklmnoprstuvy,?2?1?1?1?1aster
abcdeiklmnoprstuvy-,abcdeiklmnoprstuvy,?2?1?1?1?1orker
abcdeiklmnoprstuvy-,abcdeiklmnoprstuvy,?2?1?1?1aster
abcdeiklmnoprstuvy-,abcdeiklmnoprstuvy,?2?1?1?1orker
```

**Comment by philsmd** [comment]
any update here?

btw: you could also rewrite your mask file like this:
```
abcdeiklmnoprstuvy,?1-,?1?2?2?2?2aster
abcdeiklmnoprstuvy,?1-,?1?2?2?2?2orker
abcdeiklmnoprstuvy,?1-,?1?2?2?2aster
abcdeiklmnoprstuvy,?1-,?1?2?2?2orker
```

it's more concise and (in my opinion) emphasizes better what the difference between the first custom charset (--custom-charset1) and the 2nd one (--custom-charset2) is

**Comment by jsteube** [comment]
any update here? @exander77
