### ISSUE TITLE
office2john update

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#242]
Is there an official repo somewhere holding office2hashcat other than https://github.com/stricture/hashstack-server-plugin-oclhashcat or is that "the one"?

Anyway you probably want to apply https://github.com/magnumripper/JohnTheRipper/commit/9e208da8d8280e68609a0476f294f6869f7ae1fc to it (and possibly other updates post fork).

**Comment by jsteube** [comment]
While there's a strong depency on it, that's not really a direct oclHashcat issue. @epixoip Please check this out
