### ISSUE TITLE
module_hash_binary_parse() return value is mishandled

### ISSUE THREAD

**Issue by solardiz** [hashcat/hashcat#2422]
I think `hashes.c` mishandles the return value from `module_hash_binary_parse()`. The modules set it to -1 on error or to hash count on success, but the caller wrongly expects valid `errno` on a 0 return, which merely indicates no hashes, not an errno-setting error. This results in spurious error messages based on whatever stale value `errno` has. The caller's use of `strparser (hashes_parsed)` on a -1 return is also wrong, which I think would result in "Ignored due to comment" error printed whereas the actual error tends to be (or always is?) a failed `fopen` call by the module.

I think this is the right fix:

```diff
index ab1d7c6..a8c4bed 100644
--- a/src/hashes.c
+++ b/src/hashes.c
@@ -1285,19 +1285,19 @@ int hashes_init_stage1 (hashcat_ctx_t *hashcat_ctx)
         const int hashes_parsed = module_ctx->module_hash_binary_parse (hashconfig, user_options, user_options_extra, hashes);
 
         if (hashes_parsed > 0)
         {
           hashes_cnt = hashes_parsed;
         }
-        else if (hashes_parsed == 0)
+        else if (hashes_parsed < 0)
         {
           event_log_warning (hashcat_ctx, "Hashfile '%s': %s", hashes->hashfile, strerror (errno));
         }
         else
         {
-          event_log_warning (hashcat_ctx, "Hashfile '%s': %s", hashes->hashfile, strparser (hashes_parsed));
+          event_log_warning (hashcat_ctx, "No hashes loaded.");
         }
       }
       else
       {
         hash_t *hash = &hashes_buf[hashes_cnt];
 
```

With this, the convention becomes that `module_hash_binary_parse` only returns -1 on system errors that set `errno`. If there's any other error, it should return 0. For the few modules I checked, this appears to be already the case, but I imagine that some with extra `return` statements might need adjustments.

Does this look right? Should I submit a PR?

**Comment by jsteube** [comment]
There was a recent change I merged to the section in hashes.c: https://github.com/hashcat/hashcat/commit/1dc3469f6e6307ed38a2975e9dec765203299844

I think we need to find a different solution. Do you have something special in mind? 

Btw: A good way to reproduce the error which lead to the above PR is to try to load a LUKS header which is not a true LUKS header. The error message "file exists" appeared which clearly is misleading. 

The problem was that if the binary file itself was load successfully it's still possible that the format inside the file is invalid. In this case errno was not set and the error message itself was invalid. The solution should either enable the plugin user to set the errno or hashcat tries to open the file before the plugin does to detect if there's any problem opening the file. I think the latter is the way to go. What you think?

**Comment by solardiz** [comment]
Oh, this gets more complicated. Maybe we can interpret values of -2 or lower as the corresponding `PARSER_*` constants, but -1 as implying a system error with `errno` set?

Edit: or maybe it'd be cleaner to introduce a `PARSER_HAVE_ERRNO` constant (with some currently unused value) and use that in place of -1. A very explicit name like this is less likely to be inadvertently used in places where `errno` is not set.

**Comment by jsteube** [comment]
Indeed that's not too bad. If I understand this correctly we can check in hashes.c if PARSER_HAVE_ERRNO was set and in this case use errno for the error message. Adding PARSER_HAVE_ERRNO also seems intuitive enough to me for the plugin developers to use it. I'll do the change, thanks for the suggestion.

**Comment by jsteube** [comment]
OK this issue should be fixed with commit https://github.com/hashcat/hashcat/commit/84d3981e7b6bc4efe3c1bcbaa6f4198f4c523204.

Please check and see if this fixes the issue and close it. 

@mpalmer I think this needs to be changed in your PR as well

**Comment by solardiz** [comment]
FWIW, I notice we still have two uses of `PARSER_HASH_FILE`:

```
./src/modules/module_05200.c:  if (hc_fopen (&fp, (const char *) line_buf, "rb") == false) return (PARSER_HASH_FILE);
./src/modules/module_09000.c:  if (hc_fopen (&fp, (const char *) line_buf, "rb") == false) return (PARSER_HASH_FILE);
```

I assume these stay because they're in `module_hash_decode` rather than in `module_hash_binary_*` and there's no intent to update the callers of `module_hash_decode` to be errno-aware?

**Comment by solardiz** [comment]
The commit fixes the issue for my test case. Closing. Thanks!
