### ISSUE TITLE
feature: standalone hash validity-checking command-line tool

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2435]
This is a request to add a hash validation command-line tool to hashcat.

The argument for adding it to hashcat (instead of hashcat-utils) is that hashcat has the code that is aware of all of the algorithms, so a lot of code could be (easily?) reused.

Input and parameters:
* list of hashes (either stdin, or from a file)
* the algorithm -m [mode] ID
* arguments for where to put the outputs

Output:
* the hashes that validate under that mode, to stdout or to a file
* hashes that do not validate, to stderr or to a file

It could be named 'hashval' or 'hashvalidate' or something like that, but this might be confusing when people use 'validate' to check whether the plaintext produces the same hash. So I am open to suggestions for what else to name it (maybe 'hashcheck' or 'hashclean' or something like that?)

**Comment by davidbolvansky** [comment]
https://github.com/hashcat/hashcat/pull/2434

(But yeah, you want something more than what patch implements.. but anybody can improve it futher)

**Comment by ZerBea** [comment]
Good idea. If possible, it also should check the validity of the potfile. That makes sense, if you have received a potfile from an unknown source.

**Comment by philsmd** [comment]
Note that @davidbolvansky mentioned here https://github.com/hashcat/hashcat/pull/2434#issuecomment-644968606 that it's working with --show as a nice **hack**.

Maybe it's not ideal in all of the cases, but --show can be actually quite helpful finding out which lines didn't load etc and it's also quite fast (and note that --left could actually also come handy sometimes) .

It's probably good enough for most of the cases and we shouldn't really implement too many fancy features that probably aren't used by a lot of users (also for maintenance reason etc).... Shouldn't the --show trick also work for you ?

Close or leave this open for further discussion ?

**Comment by roycewilliams** [comment]
Ah! This is very good and honestly something that I never thought of before! :)

This gets you most of the way there, though if you're strictly trying to validate an existing list, you'd want to use --potfile-path=/dev/null, to avoid showing plains from your potfile. The only other thing I can think of is that it might be better if non-valid-hash errors went to stderr. Today they go to stdout:

```
$ cat test.list
5d41402abc4b2a76b9719d911017c592
d41402abc4b2a76b9719d911017c59

$ hashcat --show -m 0 test.list
Hashfile 'test.list' on line 2 (d41402abc4b2a76b9719d911017c59): Token length exception
5d41402abc4b2a76b9719d911017c592:hello

$ hashcat --show -m 0 test.list >/dev/null
$

$ hashcat --show -m 0 test.list --potfile-path=/dev/null
Hashfile 'test.list' on line 2 (d41402abc4b2a76b9719d911017c59): Token length exception
```

If you see any value in the stderr change, I'll open a new issue (or a PR ;) ) for it. If it's super simple, if you could just add that while doing something else, go for it. 

Edit: with a gentle reminder about -o [outfile], that's good enough. :) Closing.

**Comment by roycewilliams** [comment]
FWIW, for future searchers: if the hash is longer than a certain length, it's abbreviated (with `...`) in the error output to the screen, so that's another reason why outfiles are the way to go.
