### ISSUE TITLE
Unknown hash-type '17200' selected.

### ISSUE THREAD

**Issue by trueshot86** [hashcat/hashcat#2436]
Can't we use pkzip mode???

I checked help, but I could not find pkzip options.

There is no 172xx series.

I expected below ↓
17200 | PKZIP (Compressed) *
17210 | PKZIP (Uncompressed) *
17220 | PKZIP (Compressed Multi-File) *
17225 | PKZIP (Mixed Multi-File) *
17230 | PKZIP (Compressed Multi-File Checksum-Only) *

but , there is no options in hashcat v5.

I wanna use pkzip mode.

**Comment by philsmd** [comment]
if you use an older version it won't be there for sure.
This is a new hash type only supported by beta versions (or if you compile the source code directly yourself): https://hashcat.net/beta/

Please don't forget to **close** this issue and remember that this issue tracker is mainly for source code bugs/problems and new feature requests (not really suited for user questions like yours). Thx
