### ISSUE TITLE
Feature/Bug: Remove silent hash corruption tolerance when marking hash cracked

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2437]
Currently, for performance reasons, we take some shortcuts in our kernels/modules. For many hash modes, when a hash is calculated, we only check a portion of the hash against the target(s) to save time. That portion is typically 128 bits or 4 "blocks". This results in a minuscule/negligible chance of producing a false positive crack due to the incredibly small likelihood of two valid hash outputs sharing the exact same 128bits of output, and we consider the speed/performance boost far more important/significant than such a small chance of error.

However, due to our checking of only 128 bits, any bits/bytes that fall outside those checked may be corrupted, as shown in the following example:

If we take the SHA1 of the candidate `password` like so:
```
$ echo -n password | sha1sum
5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8 *-
```
The kernel will compute the SHA1 hash and store it as the following:

```
    u32x a = SHA1M_A;
    u32x b = SHA1M_B;
    u32x c = SHA1M_C;
    u32x d = SHA1M_D;
    u32x e = SHA1M_E;
```

We don't want to check all of the bits/bytes for the performance reason stated above though, so we do this:
```
    COMPARE_S_SIMD (d, e, c, b);
```

As you can see, the A block of the hash is missing from this check. If a bit/byte in that block is corrupt in the target hash, its simply not considered. Here I have introduced some corruption to our target hash in that specific area:

```
5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8 -> 000a61e4c9b93f3f0682250b6cf8331b7ee68fd8 
```

As you might have guessed, since hashcat doesn't consider those bits/bytes, it cracks the hash just fine.
```
000a61e4c9b93f3f0682250b6cf8331b7ee68fd8:password

Session..........: hashcat
Status...........: Cracked
Hash.Name........: SHA1
Hash.Target......: 000a61e4c9b93f3f0682250b6cf8331b7ee68fd8
Time.Started.....: Sun Jun 07 23:54:33 2020 (1 sec)
Time.Estimated...: Sun Jun 07 23:54:34 2020 (0 secs)
```

While I think this sort of tolerance could be nice as a possible feature for when you are working with potentially corrupt data, this built in, and more specifically _silent_, corruption tolerance is not inherently good, as the result written to the potfile will _include_ that corruption. When the hashes are manually validated from the potfile or output file, it will be clear that the hash is not correct, but it may not be clear where the source of the original error was, leading the user to believe that hashcat may have calculated the hash incorrectly, which is not the case.

This silent corruption tolerance also appears when loading/parsing the hashes. If the following targets are provided to hashcat:
```
5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8
000a61e4c9b93f3f0682250b6cf8331b7ee68fd8
```
You will receive the following output:
```
Hashes: 2 digests; 1 unique digests, 1 unique salts
```
The hash that hashcat chooses to consider for its attack and eventually produce and write to the potfile/output file is simply the one that comes last in order of input. This is problematic because it means that even if the proper/valid target is present along with the corrupted inputs, it is not separately considered, leading to further obfuscation of the error should you receive a corrupted hash as a result of an attack.

I believe we should introduce a full hash check at some level to remove or at least reduce the chances of a corrupted hash being produced as a correct result, without the user being aware. The limited precision checks being done in the kernels are fine due to their performance reasons and low mathematical likelihood of producing colliding results, however, a check after a hash is marked as cracked could be performed to confirm that the hash does indeed match the entire target. In order to remediate the silent writing of corrupt hashes to potfiles/outfiles behavior at this point, since we have reasonably proven we cracked the hash(128 bit precision), should be to warn the user that the input hash was corrupt in some way and/or produce only the full valid hash to potfile/outfile. Even if the user is not explicitly warned about the possible input hash corruption, writing the full proper hash to the outfile/potfile seems like a far more reasonable thing to do, leaving hashcat as the source of "truth" in the process. When comparing/validating the hashes afterwards, a user could much more easily spot the mismatch and source of the error if hashcat produces a correct output, rather than carrying on the error/corruption silently. Now, it's possible that this behavior is unwanted by some users who would prefer to have exact 1:1 input to output hash match up, even if the error/corruption is present, so a user option flag such as `--skip-hash-correction` could be introduced to revert to the current behavior and keep the error/corruption present.

Any suggestions regarding the best way to implement this sort of check/behavior change or discussion regarding reasons why we should/shouldn't are appreciated.

**Comment by roycewilliams** [comment]
Originally noticed in this example in the wild (not my discovery, just putting it here for reference):
```
2123e22ae348aeb5660fc2140aec35850c4da997:admin
d033e22ae348aeb5660fc2140aec35850c4da997:admin
```
(both with trailing 0x0a)

**Comment by jsteube** [comment]
For a simple algorithm such as SHA1 a 'correction' might be easy to implement, but if we go that path we need to be consistent across all supported algorithms. This means we would need to re-implement all kernel for use on CPU. Actually we would need to add some additional logic because for some algorithms we were lucky to save to write some code because of that 128 bit check. 

If you think only on all the padding attack based kernels they could all have invalid 'data' section and we don't know about but that would also need to be checked.

This effort is huge and in contrast to what we gain from it IMO not worth the effort. In the end it is a user created error.

**Comment by Chick3nman** [comment]
Agreed, it would be significant work. When checking the potfile for matches though, these corrupt hashes would not match due to the bits we compare during an attack, even if they would crack again, right? So when storing the hash to potfile, it is almost certainly best to correct the hash so when the proper hash appears in the future, the match is made. Or maybe we make the potfile matching only consider those bits? I haven't taken time to look at the potfile code yet, this is all based on my assumptions.

**Comment by jsteube** [comment]
While this is actually a bug from technical perspective, it's triggered by a previous bug which was caused by the user.

It wont happen with real hashes and an external 3rd party script could fix it, if that is really necessary. And that tool actually exists, it's tools/test.pl.

Here's how to use it:

```
$ cat hash
2123e22ae348aeb5660fc2140aec35850c4da997
d033e22ae348aeb5660fc2140aec35850c4da997
$ cat crack 
2123e22ae348aeb5660fc2140aec35850c4da997:admin
d033e22ae348aeb5660fc2140aec35850c4da997:admin
$ tools/test.pl verify 100 hash crack result
$ cat result 
d033e22ae348aeb5660fc2140aec35850c4da997:admin
```

So instead of crack you'd use the potfile. You can use cut -d: to produce the hashfile out of the potfile and result is the fixed potfile. I think is best we can do here.
