### ISSUE TITLE
I think this hashcat forum question is related https://hashcat.net/forum/thread-9178.html ? Is this you on the forum ?

### ISSUE THREAD

**Issue by Goldleman** [hashcat/hashcat#2438]
I think this hashcat forum question is related https://hashcat.net/forum/thread-9178.html ? Is this you on the forum ?

I think the setup is quite strange here... why would you use linux on macOS ? what software do you use for virualization (vmware, parallels, bootcamp etc ?) ?

I don't think it's a good idea to use this virtualizations, because they come with a lot of problems... at least I would say, that only experience hashcat users could play with them, but not really report problems if the virtualization doesn't work out-of-the-box (it could be just a problem with your configuration / virtualization, not a hashcat issue).

For the remaining part, I already explained in the hashcat forum, that you would need to cleanly install the drivers (https://hashcat.net/faq/wrongdriver) and in some cases also install
```
ocl-icd-libopencl1 opencl-headers clinfo
```
as explained in the forum...

I think this is not really a hashcat source code problem and therefore I think that we should close this and get more information about why and how you do the virtualization etc in the above mentioned forum thread. @Goldleman, please do not forget to close this issue. thx

_Originally posted by @philsmd in https://github.com/hashcat/hashcat/issues/2380#issuecomment-625150697_

~# `clinfo`
```
Platform Name                Portable Computing Language                   
Number of devices            1
Device Name                  pthread-Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Device Vendor                GenuineIntel
Device Vendor ID             0x6c636f70
Device Version               OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-ivybridge
Drive Version                1.2
Device OpenCL C Version      OpenCL C 1.2 pocl
Device Type                  CPU

```

**Comment by jsteube** [comment]
Please do not report user errors on GitHub issues. Use the forum instead.
