### ISSUE TITLE
ADLODPerformanceLevel array subscript is above array bounds warnings

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#244]
This code within src/oclHashcat.c (and similar code within src/ext_ADL.c):

```
int engine_clock_profile_max = od_clock_mem_status[device_id].state.aLevels[1].iEngineClock;
```

produces the following compiler warning (with the correct compile warnings flags set - -Warray-bounds - and a recent gcc version):

```
warning: array subscript is above array bounds [-Warray-bounds]
```

The problem is that aLevels of the ADLODPerformanceLevels struct seems to have only one array item (slot):

<pre>
    typedef struct ADLODPerformanceLevels
    {
        ...
        ADLODPerformanceLevel aLevels <b>[1]</b>;
    } ADLODPerformanceLevels;
</pre>

Given this code, the array aLevels does allow only 1 performance level.

The problem is that even the ADL SDK has examples (for instance Sample/Overdrive/Overdrive_Sample.cpp) that use a subscription above [0], see this line within Overdrive_Sample.cpp of the AMD code:

<pre>
    printf ("Default effective range of GPU core clock: %d .. %d \n",  defaultStateInfo->aLevels[0].iEngineClock / 100, defaultStateInfo->aLevels<b>[1]</b>.iEngineClock / 100);
</pre>

(Btw: the definition of the ADLODPerformanceLevels struct is within the include/adl_structures.h file of the ADL SDK)

Some other tools also use these [0] **and** [1] indices within their code (probably because they also used the ADL SDK samples as reference), for instance [od6config](https://github.com/epixoip/od6config) (see: https://github.com/epixoip/od6config/blob/e323139f8c2c301169c2970df61f020eec3daa4d/ADL_SDK/include/adl_structures.h#L1053 , https://github.com/epixoip/od6config/blob/e323139f8c2c301169c2970df61f020eec3daa4d/src/adapter_info.c#L73 , https://github.com/epixoip/od6config/blob/e323139f8c2c301169c2970df61f020eec3daa4d/src/functions.c#L90 etc).

While discussing this a little bit with @epixoip (among others the author of od6config), we came to the conclusion that the definition of the ADLODPerformanceLevels struct (of AMD's ADL SDK) is probably the reason for this compiler warning and the number of array items should indeed be at least 2:

```
ADLODPerformanceLevel aLevels [2];
```

or it should even be of dynamic size (the correct size would probably be related to iNumberOfPerformanceLevels).

I suggest that we should test with a modified/patched ADLODPerformanceLevels (with at least 2 array items) and see if that works without any problems/side effects.
Thx

PS: this problem could lead to strange memory problems (memory corruption etc) because memory areas could possibly be read or written to that shouldn't be touched at all. This could lead to a severe stability issue (i.e. when oclHashcat's process memory is incorrectly read/written).

**Comment by jsteube** [comment]
> I suggest that we should test with a modified/patched ADLODPerformanceLevels (with at least 2 array items) and see if that works without any problems/side effects.

I think the same, we should do that
