### ISSUE TITLE
make DEBUG=1 doesn't allow debugging at all

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#245]
This is an issue for developers only.

The current Makefile with the check if the DEBUG variable is set, i.e. if the user runs:

```
make DEBUG=1
```

does not allow debugging at all.

There are actually 2 subproblems:
1. -O2 is used even if DEBUG=1 enables -g
2. -s (removing symbol table and relocation information from the binary) is used even if DEBUG=1 is set

Furthermore, currently the address sanitizer (-fsanitize=address) will be enabled whenever debugging is on. I'm not totally convinced that this makes sense in general. Maybe it should be enabled only whenever DEBUG=2 or something like that was specified on the command line. For instance, for "just" debugging a segmentation fault, it doesn't really make sense to enable compiler debug flags that do more than what e.g. -g does.

Thx

**Comment by jsteube** [comment]
I agree we should have 2 debugging levels.

The first one should "just" enable -g, without optimizations and stripping. 

The second one should be like the first, but additionally enable the sanitizer

Btw, what about that "-ggdb" flag? Does that do any help?
