### ISSUE TITLE
feature: capture current working directory in session log

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2453]
Because hashfiles are logged as specified on the command line with relative pathing, they can be ambiguous across sessions in cases where the user is moving among different directories.

Specifically, if the target hashfile has the same name in two different directories, and you change to each directory before running hashcat, the two hashfiles are indistinguishable.

To disambiguate, it would be useful to capture this in the session log.

One way to do this might be to add a `cwd` element:
```
TOP.xxxxxxxx.xxxxxxxx   hashes->hashfile        test.hashes
TOP.xxxxxxxx.xxxxxxxx   hashes->cwd        /home/user/hashwork
```

Another way might be to detect and append the full path to the existing hashfile entry:
```
TOP.xxxxxxxx.xxxxxxxx   hashes->hashfile        /home/user/hashwork/test.hashes
```
I'm open to suggestions on how best to express this. Just adding `cwd` is probably easiest, and would be enough for most purposes, IMO. It would also preserve compatibility with any implementations that currently use `hashes->hashfile`.

**Comment by philsmd** [comment]
This new feature was implemented with https://github.com/hashcat/hashcat/commit/02e2ef63fba1be0e5a9f336dafc9eb2622c1ebb6

please do not forget to close this issue @roycewilliams / @jsteube .

Thx

**Comment by roycewilliams** [comment]
Thanks, I totally missed this commit - perfect! And very good call adding the other folders as well. A solution that solves for the entire problem space, not just the piece that I noticed!

```
$ pwd
/home/royce/tmp

$ cat pa.hash
fnRL/G5lXVMug

$ which hashcat
/usr/local/bin/hashcat

$ hashcat --version
v6.1.1-51-g9121f66b1+

$ hashcat --quiet --potfile-path=test.pot --session=test -m 1500 -a 3 pa.hash ?l?l?l?l?l
fnRL/G5lXVMug:admin

$ grep folder_config ~/.hashcat/sessions/test.log
TOP.5f4678ab.00001efa   folder_config->cwd      /home/royce/tmp
TOP.5f4678ab.00001efa   folder_config->install_dir      /usr/local/bin
TOP.5f4678ab.00001efa   folder_config->profile_dir      /home/royce/.hashcat
TOP.5f4678ab.00001efa   folder_config->session_dir      /home/royce/.hashcat/sessions
TOP.5f4678ab.00001efa   folder_config->shared_dir       /usr/local/share/hashcat
```
