### ISSUE TITLE
hashcat fails when runtimes are installed without supported hardware

### ISSUE THREAD

**Issue by ZeroChaos-** [hashcat/hashcat#2455]
I know, the title seems obvious.  In this case I have a computer with 4 different opencl runtimes installed, intel cpu, intel gpu, nvidia, and amd rocm.  My system has supported hardware for all but the amd rocm.  When attempting to run hashcat with the amc rocm runtime installed hashcat fails finding devices and aborts.  Expected behavior is when the platform comes back empty (or errors) that should be caught and hashcat should continue with the platforms which came back with supported devices.  I'll attach some details but testing this isn't too bad so please ask me for whatever else you need and if you think you have a fix I can easily test any branch of git.  This should be considered a regression, as it does work as expected with hashcat 5.1.0 but not with 6.0.0

**Comment by ZeroChaos-** [comment]
[hashcat-6-amd.txt](https://github.com/hashcat/hashcat/files/4788324/hashcat-6-amd.txt)

**Comment by ZeroChaos-** [comment]
[clinfo-amd.txt](https://github.com/hashcat/hashcat/files/4788325/clinfo-amd.txt)

**Comment by ZeroChaos-** [comment]
[hashcat-5-amd.txt](https://github.com/hashcat/hashcat/files/4788326/hashcat-5-amd.txt)

**Comment by ZeroChaos-** [comment]
[hashcat-5-no-amd.txt](https://github.com/hashcat/hashcat/files/4788327/hashcat-5-no-amd.txt)

**Comment by ZeroChaos-** [comment]
[clinfo-no-amd.txt](https://github.com/hashcat/hashcat/files/4788328/clinfo-no-amd.txt)

**Comment by ZeroChaos-** [comment]
[hashcat-6-no-amd.txt](https://github.com/hashcat/hashcat/files/4788329/hashcat-6-no-amd.txt)

**Comment by jsteube** [comment]
It's kind of hard to reproduce this, could you please test this patch:

```
diff --git a/docs/changes.txt b/docs/changes.txt
index 1527da46..420c2102 100644
--- a/docs/changes.txt
+++ b/docs/changes.txt
@@ -1,3 +1,11 @@
+* changes v6.0.0 -> v6.0.x
+
+##
+## Improvements
+##
+
+- OpenCL Runtime: Reinterpret return code CL_DEVICE_NOT_FOUND from clGetDeviceIDs() as non-fatal
+
 * changes v5.1.0 -> v6.0.0
 
 ##
diff --git a/src/backend.c b/src/backend.c
index 80fdbb38..7f79879f 100644
--- a/src/backend.c
+++ b/src/backend.c
@@ -5185,7 +5185,31 @@ int backend_ctx_init (hashcat_ctx_t *hashcat_ctx)
         {
           event_log_error (hashcat_ctx, "clGetDeviceIDs(): %s", val2cstr_cl (CL_rc));
 
-          return -1;
+          // Special handling for CL_DEVICE_NOT_FOUND, see: https://github.com/hashcat/hashcat/issues/2455
+
+          #define IGNORE_DEVICE_NOT_FOUND 1
+
+          if (IGNORE_DEVICE_NOT_FOUND)
+          {
+            backend_ctx_t *backend_ctx = hashcat_ctx->backend_ctx;
+
+            OCL_PTR *ocl = (OCL_PTR *) backend_ctx->ocl;
+
+            const cl_int CL_err = ocl->clGetDeviceIDs (opencl_platform, CL_DEVICE_TYPE_ALL, DEVICES_MAX, opencl_platform_devices, &opencl_platform_devices_cnt);
+
+            if (CL_err == CL_DEVICE_NOT_FOUND)
+            {
+              // we ignore this error
+            }
+            else
+            {
+              return -1;
+            }
+          }
+          else
+          {
+            return -1;
+          }
         }
 
         opencl_platforms_devices[opencl_platforms_idx] = opencl_platform_devices;
```

Let me know if it works for you then I will commit to master.

**Comment by ZeroChaos-** [comment]
Yes, I'm glad to test, and I will do so presently.  That said, if I'm correct this bug should be super easy to test for you as well.  Do you have an amd rocm compatible device in your machine?  If not, install the rocm runtime and voila.

**Comment by ZeroChaos-** [comment]
@jsteube this appears to work exactly as expected for me.  The missing device is ignored and execution continues with the found devices.  Thanks!

**Comment by ZeroChaos-** [comment]
With this in master I think we can safely close this bug.

**Comment by philsmd** [comment]
Somebody with permissions needs to close this issue

CC: @ZeroChaos- , @jsteube 

Thx
