### ISSUE TITLE
cudaHashcat --limit=NUM problem

### ISSUE THREAD

**Issue by RezaSR** [hashcat/hashcat#246]
I used cudaHashcat64.bin 2.0.1

The following command is ok:
./cudaHashcat64.bin -m0 -a3 -s0 -i --increment-min=1 --increment-max=6 -1 ?l?u 2c539f7b23fc3fb3b8ec52d3bfa58834 ?1?1?1?1?1?1

Total number of words is: 52 ^ 6 = 19770609664
But when I set the -l (--limit) to 19770609664, it didn't work!
even setting the -l to half of that number didn't work either.
Estimated time is >10 Years!

The following command is NOT ok:
./cudaHashcat64.bin -m0 -a3 -s0 -l19770609664 -i --increment-min=1 --increment-max=6 -1 ?l?u 2c539f7b23fc3fb3b8ec52d3bfa58834 ?1?1?1?1?1?1

**Comment by Xanadrel** [comment]
https://hashcat.net/forum/thread-4942.html

Took a few seconds to search...

**Comment by jsteube** [comment]
There's two major problems in this report:

A) Appears OP did you understand what --keyspace does. This is essential here.
B) Parameter -s and -l is not supported in case -i is used.

**Comment by RezaSR** [comment]
Yes, I didn't know about keyspace.
Excuse me for the wrong report and thanks for your help.
