### ISSUE TITLE
Broken if CUDA Toolkit is not installed

### ISSUE THREAD

**Issue by xvitaly** [hashcat/hashcat#2463]
```
$ hashcat -I
hashcat (v6.0.0) starting...
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
```

5.1.0 works fine on the same system and hardware.

**Comment by philsmd** [comment]
this just looks like some setup/configuration problem. Did you try to cleanly remove all the OpenCL / CUDA drivers and just install the driver from https://nvidia.com directly (without the CUDA SDK) ? It works for me for sure.

Also see : https://hashcat.net/faq/wrongdriver
this is somehow similar, but I guess only talks about the AMD/ROCm drivers: https://github.com/hashcat/hashcat/issues/2455

**Comment by xvitaly** [comment]
> Did you try to cleanly remove all the OpenCL / CUDA drivers and just install the driver from https://nvidia.com directly (without the CUDA SDK) ? It works for me for sure.

I use Fedora and drivers from RPM Fusion. Version - 440.82. Card - RTX 2080 Ti, but tested also on GTX 1080 Ti.

This is definitely not a driver issue, because version 5.1.0 works fine on the same system and hardware.

**Comment by jsteube** [comment]
We had a similar report, the reason for it was an OpenCL runtime installed which had no devices it supports. I've pushed a workaround to GitHub master which you can compile from source or you can try a beta version from https://hashcat.net/beta/ if you prefer a binary. Please let us know if this fixed your problem.

**Comment by xvitaly** [comment]
> We had a similar report, the reason for it was an OpenCL runtime installed which had no devices it supports

Yes, removing of mesa-libOpenCL package fixes this problem for me.

**Comment by tim77** [comment]
Would be nice to try and test Beta version then.
