### ISSUE TITLE
feature: "[f] finish" - stop hashcat after the current attack

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2467]
It would be useful to be able to tell hashcat to "soft quit" or "graceful quit" - to stop at the end of the current attack. 

This is sort of like the opposite of 'bypass' - instead of skipping the current attack and going to the next attack (like 'bypass' does), we instead *do not* skip the current attack, but we *do not* go to the next attack.

Maybe this could be called something like (just brainstorming):

* [f] 'finish' after the current attack - I like this one best so far - my wife thought of it
* [e] 'end' after the current attack - also pretty good
* [t] 'terminate' after the current attack - OK but sounds too urgent, same as 'quit'
* [g] 'graceful' quit after the current attack - this is a somewhat common English idiom for this

We need a word that is intuitive to mean "finish what you're doing now, but then quit." Another name may be better - I am open to suggestions.

For an explicit example, imagine you are running -a 3 ?a?a?a?a?a?a?a?a?a -i, and you are currently on length 7. Pressing '[f]' would finish length 7, and then would not go on to length 8 or 9.

**Comment by jsteube** [comment]
I think this can be done, but as always there's the details.

1. After 'f' was pressed, should it be possible to undo it it? If yes, how?
2. After 'f' was pressed, should it be allowed to use 'b'?

**Comment by roycewilliams** [comment]
Ah, good questions. Hot takes:

1. yes, maybe undo with "un[f]inish" ?
2. yes, it seems reasonable for the user to change their mind and [b]ypass. (it could also be OK to require them to un[f]inish first to do so, but I think just directly supporting 'b' makes more sense)

**Comment by jsteube** [comment]
What kind of confirmation message would you send to the user after 'f' is pressed? For checkpoint we have:

Checkpoint enabled. Will quit at next restore-point update.
and
Checkpoint disabled. Restore-point updates will no longer be monitored.

**Comment by jsteube** [comment]
I think allowing 'b' after 'f' makes sense, yes, but not if the behavior is the same as what 'q' would do. If instead it will override the 'f' finish and continue with the next attack that would justify it. Otherwise you have twice the same action for two different keys.

**Comment by roycewilliams** [comment]
Agreed. For wording, how about something like

Finish enabled. Will quit after this attack.
and
Finish disabled. Will continue after this attack.

**Comment by jsteube** [comment]
About the [f]inish and un[f]inish that would be different to how [c]heckpoint works. That's why we send the notice to the user after the keypress. I will implement it that way just to stay conform.

One more thing. If the user activates [c]heckpoint, the status of the task in the status view chages from just "Running" to "Running (Checkpoint Quit requested)". I think something similar we should do for [f]inish. How about "Running (Quit after attack requested)"?

**Comment by jsteube** [comment]
One more thing about the 'b' after 'f'. So we agree that we will move on to the next attack, but for the next attack we could have the 'f' still activated or not? I see good things in both. I tend to unset it, but technically the user did not request to unset it....

**Comment by roycewilliams** [comment]
I like that - "Running (Quit after attack requested)" seems good

I think for most workflows, if the user changes their mind and decides to bypass, they are more likely to want to keep going (so, unset it, and let them hit "finish" again if they want to)

**Comment by jsteube** [comment]
OK, btw I checked the same is happening with checkpoint. if bypass is used after checkpoint was enabled if will disable the checkpoint.

**Comment by jsteube** [comment]
Implemented with https://github.com/hashcat/hashcat/commit/32b40d5c53e0c438576f33bfa03d8fe6b87d08e8

Thanks for the suggestion!
