### ISSUE TITLE
Mode 14000 (DES-ECB) doesn't find result on hashcat 6.0, works fine on 5.1

### ISSUE THREAD

**Issue by malakudi** [hashcat/hashcat#2475]
There is a regression on latest hashcat 6.0 release with mode 14000 being unable to find result, at least with nvidia gpus. Tried both cuda and opencl. hashcat 5.1 works fine.
Example run:
./hashcat64.bin 8855c0ee9e371811:a365948517d8e182 -m 14000 -a 3 -w 4 --hex-charset -1 charsets/DES_full.charset ?1?1?1?1?1?1d392
hashcat 5.1 finds the key a1ea5b385492d392 correctly
hashcat 6.0 doesn't find the key.
Same result if I use mask a1ea?1?1?1?1?1?1
Same result if I use ?1?1?1?1?1?1?1?1 (it will just take much longer)

It's a pitty because 6.0 works around 7-8% faster.

**Comment by jsteube** [comment]
Thanks for reporting it's fixed with commit https://github.com/hashcat/hashcat/commit/9ce625464e64b6b0c18299e4a5ecc495198c1af4

You can also use binary from https://hashcat.net/beta/ if you prefer that.

Please test and close the issue if fixed. Thanks

**Comment by malakudi** [comment]
It fixes the issue reported. Thank you
