### ISSUE TITLE
.restore file format changed without reason/notification/docs update (beta problem)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#248]
This is a problem of recent oclHashcat 2.10 (beta) versions.

The problem is, as mentioned here https://github.com/hashcat/oclHashcat/pull/158#issuecomment-187146881 , that the .restore file format did significantely change and therefore restoring (older) .restore files is impossible now (without extra steps like a specialized converter tool etc).
It is still not clear to me, why the format was changed... but as mentioned within a comment of issue #158 this change broke a lot of things (like documentation, analyze_hc_restore, restoring older .restore files etc) without any clear reason and notice.

I think @gm4tr1x needs to help us with this new "problem" since it is still not very clear to me if we need such changes in the .restore file format that justify these new arising problems.
Thx

**Comment by jsteube** [comment]
@gm4tr1x can you please answer @philsmd question? Basically, what's the reason for increasing the size of cwd in the restore struct datatype from 256 to 1024

**Comment by matrix** [comment]
@jsteube @philsmd try change back the value to 256 but I think I changed something else related to restore. Tell me if work.

**Comment by jsteube** [comment]
OK, change reverted. Thanks!

**Comment by matrix** [comment]
Thanks to you bros ;)
