### ISSUE TITLE
[delete]

### ISSUE THREAD

**Issue by romankosoj** [hashcat/hashcat#2481]
[delete]

**Comment by philsmd** [comment]
Hey,

What is the problem ?
What is the error message ?
What do you mean by "does not start" ?

We can't really do much here without any detailed description of the problem. You also should mention what hardware / setup you have and what output is shown on the screen.
Furthermore, the command that you use (with masked hashes if sensitive or not example hashes) would be at least the minimum that you need to provide if you try to report some error .

My gut feeling tells me that this is just a case of an user configuration setup problem in combination with an old or known to be broken driver / hardware. 

For instance for the -m 21800 we know of a problem with Intel GPUs and AMD GPUS, see:
https://github.com/hashcat/hashcat/blob/master/src/modules/module_21800.c#L88-L103

These are known problems and the only way it works is to use other/better hardware and drivers, unfortunately. With Intel CPUs and/or NVIDIA GPUs the hash type -m 21800 works perfectly fine.

This issue with inflate (DEFLATE decompression) kernel problems is similar to the one for PKZIP hash mode itself (-m 17200, -m 17220 and -n 17225). So my guess is that if you have problems with -m 21800 on AMD GPUs for instance, you also have problems with PKZIP cracking (the hash types above).
There is little we can do here, just a OpenCL compiler bug (depends on driver/runtime and hardware).

If this is the case and you get an error message about the unstable / broken driver like this:
```
Skipping hash-mode 21800 - known CUDA/OpenCL Runtime/Driver issue (not a hashcat issue)
```
it's for sure not a hashcat problem (but a compiler/driver problem) and we can't do anything here except recommending to use modern NVIDIA GPUs that do not have any of these OpenCL compiler bugs. In that case it would make sense to close this issue. Please don't forget to close. Thx

**Comment by romankosoj** [comment]
segmentation error

**Comment by romankosoj** [comment]
`Do not report hashcat issues encountered when using --force.
Kernel ./OpenCL/m21800-optimized.cl:
Optimized kernel requested but not needed - falling back to pure kernel

OpenCL API (OpenCL 2.1 AMD-APP (3004.8)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: Ellesmere, 4032/4096 MB (3264 MB allocatable), 36MCU

OpenCL API (OpenCL 1.2 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #2: Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz, skipped

Kernel ./OpenCL/m21800-optimized.cl:
Optimized kernel requested but not needed - falling back to pure kernel

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 13 digests; 13 unique digests, 13 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Brute-Force
* Slow-Hash-SIMD-LOOP
* Uses-64-Bit

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #1...0x00007FF9C59A70CA (0x0000000011226D78 0x0000000000000000 0x000000002AA7EDD0 0x0000000000000000), aclWriteToMem() + 0x161651A bytes(s)
0x00007FF9C59A33CD (0x000000000E6B22F0 0x0000000000A50000 0x0000000000000001 0x00000000009F4A10), aclWriteToMem() + 0x161281D bytes(s)
0x00007FF9C5969AE2 (0x000000002E4C4C08 0x00000000009F4D20 0x0000000000000000 0x000000002E4B63B0), aclWriteToMem() + 0x15D8F32 bytes(s)
0x00007FF9C5960B9E (0x000000000EBC9DE0 0x000000000001BBB0 0x000000002C1B8A70 0x000000002CCFB880), aclWriteToMem() + 0x15CFFEE bytes(s)
0x00007FF9C59613B8 (0x000000002AA7EDD0 0x000000000EA29370 0x0000000000000001 0x00000000009F94F8), aclWriteToMem() + 0x15D0808 bytes(s)
0x00007FF9C58D63FA (0x000000002AA7EDD0 0x000000002AA7EDD0 0x0000000000000000 0x00000000009FE4B0), aclWriteToMem() + 0x154584A bytes(s)
0x00007FF9C43D9EA2 (0xFFFFFFFF00000000 0x0000000000000000 0x0000000011AF44D0 0x0000000007EAE1E0), aclWriteToMem() + 0x492F2 bytes(s)
0x00007FF9C43AC7F2 (0x0000000007EAE1E0 0x0000000011AF44D0 0x00000000009FE9B0 0x0000000000000001), aclWriteToMem() + 0x1BC42 bytes(s)
0x00007FF9C43B0C6B (0x0000000007EAE1E0 0x000000000E77DAE0 0x000000000000000C 0x00000000009FEB1D), aclWriteToMem() + 0x200BB bytes(s)
0x00007FF9C43B235E (0x000000000000000E 0x0000000000000005 0x000000001124E780 0x0000000000000006), aclWriteToMem() + 0x217AE bytes(s)
0x00007FF9C438E6A9 (0x000000000E9D2798 0x00000000009FED90 0x00000000009FF320 0x0000000000000006), aclCompile() + 0xC9 bytes(s)
0x00007FF9C416556A (0x000000000E9D2670 0x000000000E9D2670 0x0000000000000000 0x0000000000000000), clGetPipeInfo() + 0x64AFA bytes(s)
0x00007FF9C4127C60 (0x0000000000000000 0x000000000EA296E0 0x0000000007EA91B0 0x000000000EA296E8), clGetPipeInfo() + 0x271F0 bytes(s)
0x00007FF9C411A072 (0x000000000E9CEEE0 0x0000000000000008 0x0000000001622940 0x0000000000000000), clGetPipeInfo() + 0x19602 bytes(s)
0x00007FF9C40F4055 (0x00000000009FFA10 0x0000000000DB6337 0x0000000001880040 0x00000000009FF658), clBuildProgram() + 0x155 bytes(s)
0x0000000000CE34CA (0x000000000E3C4920 0x0000000011670030 0x0000000000000004 0x0000000000A50000)
0x0000000000CE3D39 (0x00000000016762C0 0x0000000000000000 0x000000000000003D 0x000000000167AAC0)
0x0000000000CEE112 (0x0000000001671960 0x00007FFA0C362FBD 0x0000000001570080 0x0000000001671960)
0x0000000000CA483F (0x01D653DDDC94CC7D 0x0000000000000000 0x000000000167CC70 0x0000000000DA61F9)
0x0000000000CA4EDA (0x01D653DDDC2A364C 0x0000000000000000 0x0000000000000001 0x00000000009FDFF0)
0x0000000000DA2DDD (0x000000000000000D 0x000000000000000F 0x0000000000DCA030 0x0000000000000000)
0x0000000000CA13B4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x0000000000CA150B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFA0DF76FD4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFA0EABCEC1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

c:\Develops\hashcat-6.0.0>pause`

**Comment by romankosoj** [comment]
Yes problem AMD
2xXeon work normal

**Comment by romankosoj** [comment]
Что вы можете порекомендовать используя 20 gpu rx570-580
linux (какие драйвера)
win (какие драйвера)

What can you recommend using 20 gpu rx570-580
linux (which drivers)
win (which drivers)
