### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE on Mac OS 10.15.5

### ISSUE THREAD

**Issue by fjh1997** [hashcat/hashcat#2485]
works well for my CPU but failed for GPU：
```
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Error returned by cvms_element_build_from_source
* Device #2: Kernel /Users/fjh1997/hashcat/OpenCL/m00000_a0-pure.cl build failed.

```
my GPU is AMD Radeon RX Vega 56 Compute Engine, 8112/8176 MB (2044 MB allocatable), 56MCU
and hashcat version is v6.0.0-32-gb35a7fc7

**Comment by emwinkler** [comment]
If you don’t have a SIP disabled, then that is the issue.  The MacOS SIP blocks the OpenCL build when run from the hashcat build directory. The other work around is to install hashcat with “make install” and then run the installed version.

**Comment by philsmd** [comment]
any updates here ?

did you try to use the method / solution from above @fjh1997  ?

We need an update here to understand the problem and to see if this is a valid issue. thx

**Comment by fjh1997** [comment]
> any updates here ?
> 
> did you try to use the method / solution from above @fjh1997 ?
> 
> We need an update here to understand the problem and to see if this is a valid issue. thx

Sorry,I forget to reply.  My Sip  is already disabled though，but the error still exists. @emwinkler

**Comment by fjh1997** [comment]
I've tried the newest version(v6.1.1-47-gb8a09615),just build from souce, and everything work great!!! Thank you  for all  of the efforts!
