### ISSUE TITLE
clien/server version of hashcat

### ISSUE THREAD

**Issue by RB61** [hashcat/hashcat#2488]
Any plans for a client/server task sharing version for hashcat?

**Comment by RB61** [comment]
Is this what I think it is?
    --brain-server             |      | Enable brain server                                  |
     --brain-server-timer       | Num  | Update the brain server dump each X seconds (min:60) | --brain-server-timer=300
 -z, --brain-client             |      | Enable brain client, activates -S                    |
     --brain-client-features    | Num  | Define brain client features, see below              | --brain-client-features=3
     --brain-host               | Str  | Brain server host (IP or domain)                     | --brain-host=127.0.0.1
     --brain-port               | Port | Brain server port                                    | --brain-port=13743
     --brain-password           | Str  | Brain server authentication password                 | --brain-password=bZfhCvGUSjRq
     --brain-session            | Hex  | Overrides automatically calculated brain session     | --brain-session=0x2ae611db
     --brain-session-whitelist  | Hex  | Allow given sessions only, separated with commas     | --brain-session-whitelist=0x2ae611db

**Comment by oam7575** [comment]
Questions like this a best asked on the forums : https://hashcat.net/forum/

Yes : read here : https://hashcat.net/forum/thread-7903.html

You might also look at hashtopolis : https://github.com/s3inlc/hashtopolis
