### ISSUE TITLE
Windows hashcat 6.0.0 Cuda 11.0.197 named symbol not found

### ISSUE THREAD

**Issue by Qowy** [hashcat/hashcat#2492]
Hi,
I get the following error when trying to run anything on Windows 10 1909

GTX 1060
CUDA 11.0.192
hashcat 11.0.197

The -I detection works fine but for example running example0.cmd throws:

cuModuleGetFunction(): named symbol not found

**Comment by oam7575** [comment]
This type of question should probably be asked on the forums and should probably contain some more details.
With that said it sounds like a driver / CUDA mis-match issue.

Appears to be working fine for me.
Win 10 1909 
Other details below

E:\hashcat\hashcat-6.0.0>hashcat.exe -I
hashcat (v6.0.0) starting...

CUDA Info:
==========

CUDA.Version.: 11.0

Backend Device ID #1 (Alias: #2)
  Name...........: GeForce GTX 1660 Ti
  Processor(s)...: 24
  Clock..........: 1800
  Memory.Total...: 6144 MB
  Memory.Free....: 5033 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 11.0.208

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce GTX 1660 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 24
    Clock..........: 1800
    Memory.Total...: 6144 MB (limited to 1536 MB allocatable in one block)
    Memory.Free....: 4992 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 451.67


E:\hashcat\hashcat-6.0.0>hashcat.exe -m 500 example500.hash example.dict
hashcat (v6.0.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 11.0)
====================
* Device #1: GeForce GTX 1660 Ti, 5033/6144 MB, 24MCU

OpenCL API (OpenCL 1.2 CUDA 11.0.186) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: GeForce GTX 1660 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 485 MB

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

$1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1:hash234

Session..........: hashcat
Status...........: Cracked
Hash.Name........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: $1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1
Time.Started.....: Sat Jul 18 16:08:12 2020 (0 secs)
Time.Estimated...: Sat Jul 18 16:08:12 2020 (0 secs)
Guess.Base.......: File (example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   528.4 kH/s (7.04ms) @ Accel:8 Loops:31 Thr:1024 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 128416/128416 (100.00%)
Rejected.........: 0/128416 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:992-1000
Candidates.#1....: 0 -> zzzzzzzzzzz
Hardware.Mon.#1..: Temp: 53c Fan:  0% Util:  8% Core:1935MHz Mem:5750MHz Bus:16

Started: Sat Jul 18 16:07:43 2020
Stopped: Sat Jul 18 16:08:13 2020

E:\hashcat\hashcat-6.0.0>pause
Press any key to continue . . .

**Comment by Qowy** [comment]
There really isn't much more detail to it. But I will post the stdout.

I thought since it actually threw function names in my face Github might be the better place to ask. 
If there is no obvious solution I will take it to the forums then.

Driver is 451.67

PS C:\hashcat> .\example0.cmd

C:\hashcat>hashcat.exe -t 32 -a 7 example0.hash ?a?a?a?a example.dict
hashcat (v6.0.0) starting...

CUDA API (CUDA 11.0)
====================
* Device #1: GeForce GTX 1060 3GB, 2488/3072 MB, 9MCU

OpenCL API (OpenCL 1.2 CUDA 11.0.197) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: GeForce GTX 1060 3GB, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416

Hashes: 6494 digests; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

cuModuleGetFunction(): named symbol not found

Started: Fri Jul 17 13:52:38 2020
Stopped: Fri Jul 17 13:52:39 2020

**Comment by jsteube** [comment]
This is not a hashcat problem, I also tried with latest CUDA 11 SDK. Also I think it is a installation problem. See if you have outdated nvcuda.dll somewhere and remove it.

I tried to reproduce on my local system, it worked fine.
