### ISSUE TITLE
HEX-ify rules debug non-rules outputs that contain colons

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2493]
Example:

`TwinkleTwinkle!!:):::TwinkleTwinkle!!:)`

Here, the "original word" - TwinkleTwinkle!!:) - passes through via the ':' rule, resulting in the "processed word". But other variations are possible that contain one or more colons, making it difficult to extract rules from the debug output.

Desired output:

$HEX[696e205477696e6b6c655477696e6b6c6521213a29]:::$HEX[696e205477696e6b6c655477696e6b6c6521213a29]

**Comment by jsteube** [comment]
Was fixed with PR https://github.com/hashcat/hashcat/pull/2854
