### ISSUE TITLE
Not able to decrypt pdf1.7 hash 

### ISSUE THREAD

**Issue by guptasachin25** [hashcat/hashcat#2503]
Hash:`$pdf$4*4*128*-3868*1*16*8db690301b9ed76677cc0e498640a83a*64*bd73dabb2be0a3faf8037f68a1664e34003030003030003030003030003030003030003030003030003030003030003030003030003030003030003030003030*32*62b53eed11ae25cadd9c0be818ede219194b698ed855609c5dcde46d3d2ad6d5`

Hashcat version:v6.0.0
Password: `203012116`
Pdf Version: 1.7
Command: hashcat -m 10500 -a 3 hash ?d03012116

Error: Token length exception

**Comment by guptasachin25** [comment]
@jsteube would really appreciate if you can help solve this. I have a demo and recently found this hash is causing issues.

**Comment by Banaanhangwagen** [comment]
With what tool did you extract the hash?

You should be able to successfully crack it with `-m 10500`. 
If you look closely at the salt, there seems to be a lot of `3030030300...`; maybe it's a sort of padding?

When you look at the [example hashes](https://hashcat.net/wiki/doku.php?id=example_hashes), you'll see that Hashcat expects a salt of 32 bytes, and not 64 as in your example. Change that value and cut the salt, and you will successfully crack the PDF.

**Comment by guptasachin25** [comment]
Thanks @Banaanhangwagen its working after i changed hash to 
`$pdf$4*4*128*-3868*1*16*8db690301b9ed76677cc0e498640a83a*32*bd73dabb2be0a3faf8037f68a1664e3400303000303000303000303000303000*32*62b53eed11ae25cadd9c0be818ede219194b698ed855609c5dcde46d3d2ad6d5`

I am wondering where can I read about format of pdf hash more.
