### ISSUE TITLE
LLVM ERROR and CommandLine

### ISSUE THREAD

**Issue by Biswanath00** [hashcat/hashcat#2506]
root@kali:~/Documents/# hashcat -I
hashcat (v6.1.1-20-gdc9a2468) starting...

: CommandLine Error: Option 'polly' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by ghost** [comment]
are you using mesa? if so seems like you are trying alternate OpenCL....hmmm is there any drivers from your amd or nvdia gpu that isn't available? well in that case you can check out : https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_may_have_the_wrong_driver_installed_what_should_i_do

**Comment by jsteube** [comment]
Sorry but this is a driver installation issue and not a hashcat issue. Please ask on Kali Forums.
