### ISSUE TITLE
Bitcoin mode 11300 bug

### ISSUE THREAD

**Issue by mem50** [hashcat/hashcat#2511]
Hi,
I think there is a bug in cracking 'new' bitcoin hash format (shorter one).
Here are my tests:
1) I use the current bitcoin2john.py script to output a hash (from john repo).
2) Then I use an old version of bitcoin2john (28 Jun 2018) on the same wallet, it gives a bigger hash.
3) I launch john on both hashes, it cracks both of them: everything's OK.
4) I launch hashcat 6.1.1 on both hashes, but it cracks ONLY ONE of them: the longest one (old format, from 2.).

I can provide hashes via email if needed.

Logs:

```
Status...........: Exhausted
Hash.Name........: Bitcoin/Litecoin wallet.dat
Hash.Target......:  2hashes.txt
Time.Started.....: Wed Aug 12 10:07:49 2020 (2 secs)
Time.Estimated...: Wed Aug 12 10:07:51 2020 (0 secs)
Guess.Base.......: File (dic.txt)
Guess.Queue......: 1/1 (100.00%)
**Recovered........: 1/2 (50.00%) Digests**
```

```
$ ./john  2hashes.txt --wordlist=dic.txt
$ ./john  --show
?:password
?:password
**2 password hashes cracked, 0 left**
```

**Comment by philsmd** [comment]
yeah, it's difficult to reproduce like this. Please send them to atom (https://github.com/jsteube).
Thx

**Comment by mem50** [comment]
OK, done!

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/30949c15787c2ee4f9a195920cbe29c82886982a please test and close if fixed.

**Comment by mem50** [comment]
OK !
`Recovered........: 2/2 (100.00%) Digests`
Thanks.
