### ISSUE TITLE
Make bash-completion optional

### ISSUE THREAD

**Issue by doggodanubus** [hashcat/hashcat#2527]
I requested Fedora not force a download of bash-completion and they decline. Please make it optional in your spec file.

**Comment by philsmd** [comment]
do you mean the `Makefile` ?

Why do you not want the tab completion ? maybe you could mention the problems and we could try to improve it ?

As an alternative you can always just download `hashcat` from https://hashcat.net/hashcat/ into a new folder and just run it locally (without installing it) like this:
`./hashcat --help`

(the "./" at the start of the command is important for the local run)

**Comment by philsmd** [comment]
any updates / answers here ?

Please give a feedback otherwise we need to close this issue as invalid.

Thx

**Comment by doggodanubus** [comment]
In Fedora and perhaps others a program called bash-completion is required to use hashcat. I had assumed you set that as required as that is what I was told by a Fedora maintainer.  It is not needed and causes problems with accessibility. Yes we still love text even if the shaking makes us slower. Bash-completion is a horror to use in this case.
.
Since Fedora refused to work with me I contacted you. I am not sure who creates the rpm for fedora but it does not appear to be your issue as I'd thought.  I will close this and consider an ADA complaint against Redhat which might rattle someones cell over there.
