### ISSUE TITLE
wrong password (tail zeroed) returned (phpass -O)

### ISSUE THREAD

**Issue by BotPass** [hashcat/hashcat#2537]
##### problem

Under some circumstances hashcat print the wrong password. This seems to be true for "Candidates" in status as well as output and potfile. Instead of the real password hashcat prints $HEX version and the last bytes are zeroed instead of the correct bytes. For visualisation: instead of "password" it would print $HEX[70617373776f0000].
Depending on the last tests the problem seems to appear for passwords longer than 32 bytes. I thought seeing other length but could not reproduce that -- maybe I just could not count.

I do not know if this is only a problem with phpass. I tried MD5 but `-O` only allows 31 bytes while phpass allows 55 bytes (at last sometimes).

##### reproduce

Let's assume the escaped password is 
```
\xf0\x9f\xa6\x8e\xf0\x9f\xa7\x98\xf0\x9f\x8f\xbc\xe2\x80\x8d\xe2\x99\x82\xef\xb8\x8f\x52\x79\x7a\x65\x6e\x49\x73\x41\x44\x61\x6e\x63\x65\x72
```
thus the password is 16 "characters" short but need 35 bytes. Multibyte UTF-8 is not necessary, 35 times 'a' would work, too.

For testing a static salt is used therefore the hash starts with `$P$Jpwoflove`. With these information it should be possible to create the hash I used without me printing it here (that's prohibited, right?).

Now try to recover the password with hashcat:
```
hashcat.exe -a 0 -m 400 -D 2 bughash.txt bugpwd.txt --potfile-disable -o result.pot -O >> bug_realpwd.log
```
The log proclaims success (note: I used to have the password and the escaped one in the same file; the escaped one is obviously to long and was rejected here):
```
Session..........: hashcat
Status...........: Cracked
Hash.Name........: phpass
[...]
Recovered........: 1/1 (100.00%) Digests
Progress.........: 3/3 (100.00%)
Rejected.........: 1/3 (33.33%)
[...]
Candidates.#1....: $HEX[f09fa68ef09fa798f09f8fbce2808de29982efb88f52797a656e49734144616e000000] -> $HEX[]
```
And depending on the result the password should be `$HEX[f09fa68ef09fa798f09f8fbce2808de29982efb88f52797a656e49734144616e000000]`. Well of cause it's not. And this can be tested with hashcat itself.
The password from result could be used as new input:
```
hashcat.exe -a 0 -m 400 -D 2 bughash.txt bugpwd_result.txt --potfile-disable -o result2.pot -O >> bug_resultpwd.log
```
And hashcat is not able to find the password again with it's own output:
```
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: phpass
[...]
Recovered........: 0/1 (0.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
[...]
Candidates.#1....: $HEX[f09fa68ef09fa798f09f8fbce2808de29982efb88f52797a656e49734144616e000000] -> $HEX[f09fa68ef09fa798f09f8fbce2808de29982efb88f52797a656e49734144616e000000]
```

I tested `-D 1` as well with the same result.

##### version
This was tested with hashcat 6.0.0 as well as the newest beta build (6.1.1+51).

**Comment by jsteube** [comment]
This actually is a result of two individual bugs. I have fixed both with commits:

https://github.com/hashcat/hashcat/commit/a1b5af44330b1ba36eedd3030583f07c6623ee87
https://github.com/hashcat/hashcat/commit/fb448b6eb6963c8274262711658603c4fe0e1d96

There's also a new binary build on https://hashcat.net/beta/

Thanks for reporting!
