### ISSUE TITLE
Support for sha256($salt.sha256($pass))

### ISSUE THREAD

**Issue by redteamclinico** [hashcat/hashcat#2538]
Hi,

Would you guys be willing to add support for sha256($salt.sha256($pass))

Examples:

php > echo hash('sha256', '869dc2ed80187919'.hash('sha256',"hashcat"));
bae9edada8358fcebcd811f7d362f46277fb9d488379869fba65d79701d48b8b

Salt:  869dc2ed80187919
Hash:  bae9edada8358fcebcd811f7d362f46277fb9d488379869fba65d79701d48b8b
Pass: hashcat

thanks.

**Comment by jsteube** [comment]
Can you give example software/application where is this algorithm used in?

**Comment by redteamclinico** [comment]
Hi,

The algorithm is used in a login web page made for a custom development, not for commercial software.

**Comment by trounce1** [comment]
@redteamclinico i will implement for you should be easy enough. I’ll do it this weekend. If you still need it?

**Comment by trounce1** [comment]
@redteamclinico 

I have implemented this mode and it works well https://github.com/hashcat/hashcat/pull/2591

until i sort out the optimised kernels, you can find the repo here https://github.com/trounce1/hashcat/tree/20720

mode is 20720

**Comment by jsteube** [comment]
PR was marged to master repository
