### ISSUE TITLE
Password reassembly broken

### ISSUE THREAD

**Issue by spinkham** [hashcat/hashcat#2539]
Commit a1b5af44330b1ba36eedd3030583f07c6623ee87 broke password reassembly for me.

With the optimized kernel, the result stored in the pot file is missing the rules generated part of the match.

So for example, when running the optimized kernel like so:

./hashcat -m 0 -r rules/T0XlC-insert_00-99_1950-2050_toprules_0_F.rule -O forest2020.hash forest2020.txt

output looks like this:

./hashcat --show forest2020.hash 
605fa385f80a89a3a3d3a6a728fbc3b9:forest
f379cfd7a55b621577a8389d1817a102:forest

If I delete the .pot file and run again omitting the -O flag, I get the correct results:
605fa385f80a89a3a3d3a6a728fbc3b9:forest2020
f379cfd7a55b621577a8389d1817a102:forest

More importantly rolling back to the commit before a1b5af44330b1ba36eedd3030583f07c6623ee87 gives the correct results.

**Comment by jsteube** [comment]
Correct. This was just fixed with commit https://github.com/hashcat/hashcat/commit/1ba80a6c1edad7c5075091404f10fb212103e550

The beta binary builds also have been updated.

Thanks for reporting!
