### ISSUE TITLE
Kali - GPU not recognized only CPU - ROCm installation ERROR

### ISSUE THREAD

**Issue by Kaveltov** [hashcat/hashcat#2540]
Hey there!
I installed Kali two days ago and tried to use hashcat but it only shows the CPU. I tried to install the AMD drivers like they say on this site: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
But I already stopped at step 3 when I executed "sudo apt install rocm-dkms". I get this message:

The following packages have unmet dependencies:
 llvm-amdgpu : Depends: libstdc++-5-dev but it is not installable or
                        libstdc++-7-dev but it is not installable
               Depends: libgcc-5-dev but it is not installable or
                        libgcc-7-dev but it is not installable
               Recommends: gcc-multilib but it is not going to be installed
               Recommends: g++-multilib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I installed llvm-10 and reinstalled the packages but even fixing or dist-upgrade didn't work out.

And by the way; I didn't know what I had to do with the key before step 3?!

I really want to use my GPU because of its hashrate of course.

Thanks in advance

**Comment by jsteube** [comment]
Sorry but this is a driver installation issue and not a hashcat issue. Please ask on Kali Forums.
