### ISSUE TITLE
feature: include time and duration info when pausing and resuming

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2545]
Just as a "nice to have", it is sometimes useful to know when a session was paused, and how long it had been paused.

Maybe something like:

```
[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => p

Paused at Sun Aug 30 18:02:18 2020

[s]tatus [r]esume [b]ypass [c]heckpoint [q]uit => r

Resumed at Sun Aug 30 19:05:18 2020 (paused for 1 hour, 3 minutes)
```

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/ce41316ac378d1b6b593b201fa4100af4aa6238b
