### ISSUE TITLE
~/hashcat# make

### ISSUE THREAD

**Issue by StopSnitchin** [hashcat/hashcat#2552]
~/hashcat# make
gcc -c -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -DWITH_HWMON src/affinity.c -o obj/affinity.NATIVE.o -fpic
make: gcc: No such file or directory
make: *** [src/Makefile:534: obj/affinity.NATIVE.o] Error 127

help to install hashcat. how to solve the problem?

**Comment by roycewilliams** [comment]
Install the GCC compiler on your system. Google for "install GCC [name of your operating system]"

**Comment by StopSnitchin** [comment]
The following packages have unmet dependencies:
  libc6-dev: Breaks: libgcc-9-dev (<9.3.0-5 ~) but 9.2.1-19 must be installed

**Comment by StopSnitchin** [comment]
> Install the GCC compiler on your system. Google for "install GCC [name of your operating system]"

The following packages have unmet dependencies:
  libc6-dev: Breaks: libgcc-9-dev (<9.3.0-5 ~) but 9.2.1-19 must be installed

**Comment by StopSnitchin** [comment]
Thanks, I solved the problem with the command apt-get install gcc-multilib g++-multilib.
