### ISSUE TITLE
Problems with libhashcat.so in Python

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#2553]
Hello

I am working on small Python wrapper for Hashcat library. Finally I can get list of supported hashes, backend devices and perform benchmark test.

But there are some problems to use library properly in non-hashcat environment.

The biggest problem is with calling `hashcat_session_init`. In this function another one is called - `folder_config_init` - which works for Hashcat binary very well but not for other programs that uses Hashcat library.
For example when I am calling library from Python here you have the state of `hashcat_ctx->folder_config`:

    folder_config->install_dir = "/usr/bin"; // because exec_path in folder_config_init is "/usr/bin/python3"
    folder_config->profile_dir = "/usr/bin";
    ...
    folder_config->cpath_real = "/usr/bin/OpenCL";

I am thinking about some kind of `hashcat_library_session_init` which is going to be very similar with `hashcat_session_init` but developer can pass `install_dir`, `profile_dir` and so on as arguments (or whole initialised `folder_config`).

I can prepare PR but it would be nice if you tell me about proper way from your perspective of view.

**Comment by f0cker** [comment]
Have you tried PyHashcat? Might save you some time.
https://github.com/f0cker/pyhashcat

**Comment by philsmd** [comment]
Any updates here @ventaquil ?

I guess we can / should close this ? because pyhashcat proofs that it should work AS-IS , right ?

If we don't get any updates here, we might just close this issue after a few days... so please reply soon. Thx

**Comment by ventaquil** [comment]
Okay, pyhashcat looks fine, I am going to use it.

I think that we can close this issue now - and maybe reopen in future.

Thanks for response!

**Comment by process0** [comment]
> Any updates here @ventaquil ?
> 
> I guess we can / should close this ? because pyhashcat proofs that it should work AS-IS , right ?
> 
> If we don't get any updates here, we might just close this issue after a few days... so please reply soon. Thx

Sure pyhashcat's usage/implementation works. I don't think this should be taken as proof that the API is reasonable.  There are several comments on github about the unexpected behavior, and judging from pyhashcat's comments, id guess they were also confused by the behavior. 

```c
  char *py_path = "/usr/bin/";
  char *hc_path = "/usr/local/share/hashcat";
...
  /**
   *   !! IMPORTANT !!
   *   Getting the args to hashcat_session_init correct is critical.
   *   The first parameter is where Python is installed and
   *   the second is where you installed all the hashcat files.
   *
   * */
  self->rc_init = hashcat_session_init (self->hashcat_ctx, py_path, hc_path, 0, NULL, 0);
```
