### ISSUE TITLE
improve UX for file targets that do not write cracks to potfile

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2554]
Reference thread: https://hashcat.net/forum/thread-9490-post-50261.html#pid50261

A couple of suggestions:

* Consider restoring writing to potfile specifically for the formats that are filename-based

* If that's not attractive, consider generating a warning-level message to the user saying something like "WARNING: This format does not write cracks to the potfile - use -o" or something like that

**Comment by roycewilliams** [comment]
Just curious - what is the reason for not writing to the potfile? The previous behavior was simple and convenient.

**Comment by Chick3nman** [comment]
I believe it's to do with colliding entries in the potfile causing you to have to disable the potfile anyway if the entry is not a match. We throw other warnings like the warning for `--keep-guessing` about that dangers of duplicate entries in the potfile.
