### ISSUE TITLE
Misleading init message: "Successfully initialized NVIDIA CUDA library" even if CUDA is not installed

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2560]
I think we should change the wordings of https://github.com/hashcat/hashcat/blob/8207af471cee80012d370d551653d28516abf0c1/src/backend.c#L6277
^ This sentence is a little bit misleading, especially if the CUDA compiler/Toolkit/SDK is not even installed.

The problem is that the "normal" Nvidia GPU driver also ships with the runtime libs and therefore it's not completely wrong that the library was found and initialized... the problem is just that the user could be confused by this sentences because it might suggest that CUDA is installed, while it was not, see https://github.com/hashcat/hashcat/pull/2542#issuecomment-692832364 .

Any suggestions @roycewilliams , @jsteube etc ?

**Comment by jsteube** [comment]
Please some suggestions for rephrase?

**Comment by philsmd** [comment]
I really hoped that @roycewilliams and others would help us here.

I'm not 100% sure if the problem is clear to everyone...
The main problem is that the "normal" GPU driver already ships with the cuda runtime library, but can't really compile the kernel code etc... so CUDA needs to be installed separately.

Whenever the user only has the GPU driver installed (but didn't install CUDA Toolkit/SDK), the above error is currently shown.

My idea is to use something like `Runtime` or similar within the error message to make it clear that this is something different than the normal `CUDA compiler` or `CUDA SDK` or `CUDA Toolkit` etc. but of course it should be much more clearer than the current message.

I still think we can come up with an error message that isn't as misleading as the current one (because `Successfully initialized NVIDIA CUDA library` means to a lot of users that `CUDA` is working/installed etc, unfortunately).

**Comment by roycewilliams** [comment]
Apologies for not replying - it wasn't clear to me what the error should *mean*. I should have asked more questions. :) 

I agree that this needs to be clarified for sure.

If this message is *only* shown when CUDA is missing, is the fact that CUDA is missing then also *always* reported in a different message? 

If so, what is that message? (We can consider the phrasing of the two together). Perhaps something like "Successfully initialized stock NVIDIA CUDA library, checking for separate CUDA install ..." might work.

If a separate "CUDA is missing" message isn't shown, then is the message really needed at all *upon success*? In other words, if the value in this message is only diagnostic, then maybe only a failure message is needed.

**Comment by philsmd** [comment]
Yeah, maybe something like this:
```
Found and initialized the NVIDIA main driver CUDA runtime library, checking for CUDA Toolkit installation ...
```

As I mentioned above, it looks like this: https://github.com/hashcat/hashcat/pull/2542#issuecomment-692832364

and therefore it is:

```
Successfully initialized NVIDIA CUDA library.
```

followed by this:
```
Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
CUDA SDK Toolkit installation required for proper device support and utilization
Falling back to OpenCL Runtime
```

BTW: we also check for the RTC library:
```
Failed to initialize NVIDIA RTC library.
```

so these 2 checks are just in addition for users/devs to understand which libraries are missing and what could have gone wrong with the setup or driver installation

**Comment by jsteube** [comment]
I like @philsmd suggestion and it's easy to update. While not directly related it still is a problem that hashcat -I will show that CUDA library is installed and maybe lead to the same confusion as with the "Successfully initialized NVIDIA CUDA library." message. But I don't think we can do anything here. Please send in a PR.
