### ISSUE TITLE
Integer overflow detected with attack mode 6 and 7 (v6.1.1)

### ISSUE THREAD

**Issue by jeky--** [hashcat/hashcat#2567]
./hashcat -O -a 6 -m 1000 --username NTLM_all.txt ../Dizionari/Italian-Words.txt ?a?a?a?a?a
Integer overflow detected in keyspace of mask: ?a?a?a?a?a

This with hashcat 6.1.1. While using 5.1.1 or 4.2.1 it works, and the task takes less than 2 days.
May be there is a bug, in the fix?

_Originally posted by @jeky-- in https://github.com/hashcat/hashcat/issues/2117#issuecomment-702749794_

Using hashcat 6.1.1 I receive the "Integer overflow" error, with 6.0.0, instead, it started running but it stopped as "Exhausted" after 44.49%
I don't know if we need a larger variable, or something else.. let me know if you want I make any test.

(Node1)
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: NTLM
Hash.Target......: NTLM_all.txt
Time.Started.....: Fri Oct  2 16:34:24 2020 (5 hours, 27 mins)
Time.Estimated...: Sat Oct  3 04:41:49 2020 (6 hours, 40 mins)
Guess.Base.......: File (../Dizionari/Italian-Words.txt), Left Side
Guess.Mod........: Mask (?a?a?a?a?a) [5], Right Side
Guess.Queue.Base.: 1/1 (100.00%)
Guess.Queue.Mod..: 1/1 (100.00%)
Speed.#1.........: 10389.6 MH/s (1.26ms) @ Accel:16 Loops:256 Thr:1024 Vec:1
Speed.#2.........: 10522.9 MH/s (1.25ms) @ Accel:16 Loops:256 Thr:1024 Vec:1
Speed.#*.........: 20912.6 MH/s
Recovered........: 9302/25041 (37.15%) Digests
Remaining........: 15739 (62.85%) Digests
Recovered/Time...: CUR:0,0,N/A AVG:0,0,13 (Min,Hour,Day)
Progress.........: 402368396614809/904325519465625 (44.49%)
Rejected.........: 0/402368396614809 (0.00%)
Restore.Point....: 58436/116871 (50.00%)
Restore.Sub.#1...: Salt:0 Amplifier:-852125440--852125217 Iteration:0-256
Restore.Sub.#2...: Salt:0 Amplifier:-852125440--852125217 Iteration:0-256
Candidates.#1....: abateVuF0L -> minoranze]jKD_
Candidates.#2....: minorarleVuF0L -> zuzzurellone]jKD_
Hardware.Mon.#1..: Temp: 68c Fan:100% Util:  0% Core:1835MHz Mem:5005MHz Bus:8
Hardware.Mon.#2..: Temp: 47c Fan:100% Util:  0% Core:1873MHz Mem:5005MHz Bus:8

Started: Fri Oct  2 16:34:14 2020
Stopped: Fri Oct  2 22:01:49 2020

+++

(Node2)
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: NTLM
Hash.Target......: NTLM_all.txt
Time.Started.....: Fri Oct  2 16:12:18 2020 (5 hours, 41 mins)
Time.Estimated...: Sun Oct 11 00:11:34 2020 (8 days, 2 hours)
Guess.Base.......: File (../Dizionari/Italian-Words_firstUpper.txt), Left Side
Guess.Mod........: Mask (?2?2?2?2?2?2) [6], Right Side
Guess.Charset....: -1 ../commonSpecial.txt, -2 ?l?u?d?1, -3 Undefined, -4 Undefined
Speed.#1.........: 10722.0 MH/s (1.23ms) @ Accel:16 Loops:256 Thr:1024 Vec:1
Speed.#2.........: 10090.0 MH/s (1.21ms) @ Accel:16 Loops:256 Thr:1024 Vec:1
Speed.#*.........: 20811.9 MH/s
Recovered........: 9320/25041 (37.22%) Digests
Remaining........: 15721 (62.78%) Digests
Recovered/Time...: CUR:0,1,N/A AVG:0,3,88 (Min,Hour,Day)
Progress.........: 414469450619212/14971848783550796 (2.77%)
Rejected.........: 0/414469450619212 (0.00%)
Restore.Point....: 58438/116876 (50.00%)
Restore.Sub.#1...: Salt:0 Amplifier:-748734976--748734959 Iteration:0-256
Restore.Sub.#2...: Salt:0 Amplifier:-748734976--748734959 Iteration:0-256
Candidates.#1....: Minoranza0!t@UR -> Zuzzurellone3Q@fQW
Candidates.#2....: Abate0!t@UR -> Minora3Q@fQW
Hardware.Mon.#1..: Temp: 70c Fan:100% Util:  0% Core:1847MHz Mem:5005MHz Bus:8
Hardware.Mon.#2..: Temp: 43c Fan:100% Util:  0% Core:1898MHz Mem:5005MHz Bus:8

Started: Fri Oct  2 16:12:13 2020
Stopped: Fri Oct  2 21:53:44 2020

**Comment by jsteube** [comment]
It's correct how it is in latest version. The bug was in older version. This attack should have never been allowed. Details here: https://github.com/hashcat/hashcat/issues/2482
