### ISSUE TITLE
clCreateContext(): CL_OUT_OF_RESOURCES immediately after start

### ISSUE THREAD

**Issue by jujube34** [hashcat/hashcat#2592]
Microsoft Windows 10 with NVIDIA GTX 960M
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
NVIDIA driver version: 456.71
hashcat (v6.1.1-79-g0b0ce675)

```
D:\hashcat-6.1.1>.\hashcat.exe -I
hashcat (v6.1.1) starting...

clCreateContext(): CL_OUT_OF_RESOURCES

D:\hashcat-6.1.1>hashcat.exe -m 12500 -a 3 -w 3 -o outfile.txt $RAR3$*0*fb57f8d44ffd9823*5ecdf1ecee3aa3e96b4b9e832993f791 ?l?l?l?l?l
hashcat (v6.1.1) starting...

clCreateContext(): CL_OUT_OF_RESOURCES
```

However, hashcat of version lower than v6.0.0 could work (I have tried hashcat-5.1.0 and hashcat-4.1.0, and they worked fine), but they failed to recognize the CUDA API and switched to openCL platform, so I got compromised performance with minimal use of my NVIDIA GPU.

I have also used the code below to fix my register, but it didn't save my hashcat v6.1.1
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000000
```

What can I do to fix it?

**Comment by matrix** [comment]
Hi, it's a setup issue. Please close the issue and if need using the forum.
