### ISSUE TITLE
Useless .so files in 7z binaries archive for Windows (55 megabytes)

### ISSUE THREAD

**Issue by megapro17** [hashcat/hashcat#2597]
They are in modules folder
.so files can be executed only on linux, so they're waste of space on windows
![image](https://user-images.githubusercontent.com/16743370/97329827-8ae7d480-1888-11eb-8b38-0900de2539cf.png)
Also, it's strange to see example .sh files in main folder

**Comment by hops** [comment]
.dll files can only be executed on Windows, so they're wasting disk space on Linux.
It's also strange to have an exampleX.cmd It doesn't seem to work in bash.

Joking aside: There's no OS specific binary release. It's all in one package, hence both Windows and Linux binaries are present.
Feel free to delete the shared objects and any other Linux specific files.
I don't see a reason to make OS specific archives.

**Comment by megapro17** [comment]
> Joking aside: There's no OS specific binary release. It's all in one package, hence both Windows and Linux binaries are present.

Oh, really? I didn't know that hashcat.bin is binary for linux..

**Comment by megapro17** [comment]
```
del hashcat.bin
del example*
del .\modules\.lock
del .\modules\*.so

rmdir docs /s /q
rmdir extra /s /q

rmdir charsets /s /q
rmdir layouts /s /q
rmdir masks /s /q
rmdir rules /s /q
```
Here I made a simple script, adjust for your needs
