### ISSUE TITLE
Incorrect hash calculation with custom charset

### ISSUE THREAD

**Issue by dragonis41** [hashcat/hashcat#2598]
**How to reproduce :**
Create a hash (of your choice) that contain "€" (euro) symbol and try a bruteforce attack, whatever you try the hash will never be found.
Try to use custom charset (-1"€")  or .hcchr that contain this char and it still doesn't work, the output when I check the status is like "$HEX[54e02074]" Maybe it's the problem ? _--outfile-autohex-disable_ and _--wordlist-autohex-disable_ didn't change anything.

**Expected :**
The hash is correctly calculated and compared and the password is found.

**Actual result :**
The password is not found.

**Command tested :**
`$ hashcat -m13400 -a3 -w4 -1"€" keepass.hash T?1?st`
`$ hashcat -m0 -a3 -w4 -1 fr_ISO-8859-15.hcchr 790900d68b75a9dd65fb8406997287a8 ?u?1?s?l`
The password is **T€$t**

**Systems tested :**
- Parrot Security Mate 
- Debian 10
- Windows 10
- WSL

**Comment by hops** [comment]
That's because the Euro Sign is usually a multi byte character and hashcat masks are one byte per position.
The example hash `790900d68b75a9dd65fb8406997287a8` you gave was generated by having `T€$t` encoded in UTF-8 where the euro sign uses up 3 bytes (e2 82 ac).
```
$ echo -n 'T€$t' | xxd
00000000: 54e2 82ac 2474                           T...$t
$ echo -n 'T€$t' | md5sum 
790900d68b75a9dd65fb8406997287a8
```
You can crack this hash using a mask is by using the `--hex-charset` flag and set the custom charsets like this `-1 e2 -2 82 -3 ac`
The full hashcat command would be:
`$ hashcat -a3 --hex-charset -1 e2 -2 82 -3 ac 790900d68b75a9dd65fb8406997287a8 ?u?1?2?3?s?l`

Here's a rather old (but still relevant) blogpost going into more details: https://blog.bitcrack.net/2013/09/cracking-hashes-with-other-language.html

**Comment by dragonis41** [comment]
Oh yes I see, thanks for the explanation.
And if for example I know that there is a euro character in the password but I don't know where, is it possible to create a rule for that ? Testing all 3 **-1 e2 -2 82 -3 ac** + upper + lower in the first character, same on second etc or did I need to put manually multi-mask in a file ?

**Comment by philsmd** [comment]
Well it always depends on the attack type. For most attack types you could somehow use some known sequences of bytes...

the -a 3 attack is already explained above, btw it also works like this:
```
hashcat -m 0 -a 3 -w 3--hex-charset 790900d68b75a9dd65fb8406997287a8 ?ue282ac?s?l
```
i.e. if you use `--hex-charset` all the fixed/hard-coded/static substrings in the mask must be in the 0x00-0xff hexadecimal format (but the built-in charsets are automatically converted to hex, so ?1, ?2, ...?4 and ?l, ?u, ... ?b can be used also directly in the mask).

Yeah, the .hcmask file approach would work for -a 3 attacks.

For dictionary attacks with rules (-a 0 -r my.rule), you could use a rule file like this:
```
i0\xe2 i1\x82 i2\xac
i1\xe2 i2\x82 i3\xac
i2\xe2 i3\x82 i4\xac
i3\xe2 i4\x82 i5\xac
i4\xe2 i5\x82 i6\xac
i5\xe2 i6\x82 i7\xac
i6\xe2 i7\x82 i8\xac
i7\xe2 i8\x82 i9\xac
i8\xe2 i9\x82 iA\xac
i9\xe2 iA\x82 iB\xac
iA\xe2 iB\x82 iC\xac
```

i.e. insert the 3 bytes `e282ac` at different positions / offsets.

you could also combine this rule file with the multi rule feature of hashcat (-r rules/best64.rule -r my.rule). This works like a cross-product, all the rules of rules/best64.rule are combined with all rules of my.rule.... so you do not need to combine them externally yourself.

Please ask questions like this in the hashcat forum. The github issue tracker is of course only used for real bug/problem reports or algorithm/feature requests, not for the general user question (or support).

Please **close** this issue

Thx

**Comment by dragonis41** [comment]
Thanks for this complete and helpful response, if I've new question I will ask them on the forum ^^
I'm closing this issue
