### ISSUE TITLE
help me open this hash (telegram desktop passcode)

### ISSUE THREAD

**Issue by zloishax** [hashcat/hashcat#2599]
```
hashcat -l 3 -m 22600 -o rockyou.txt 1.txt
hashcat (v6.1.1) starting...

cuFuncSetAttribute is missing from CUDA shared library.

* Device #1: This device's local mem size is too small.

* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

No devices found/left.

Started: Wed Oct 28 23:39:57 2020
Stopped: Wed Oct 28 23:39:58 2020
```
`key_datas:$telegram$2*100000*c87d4f7a65112524d6c6ba36957d7a1a6dabe3b74d21b44399862f531c7144c4*01f117f6d3eed44bbef06f367a2d30eaf2ca2147ab3a3f41beb92765e79472e5ee009b631406aaec6d6e5f6a723cc7527c66fd1cc8b1cf8af4c0f60bf370a7cf8a26260d904ea7728f2db61fbe44cd82b4e3f1716739b0f689370b801aa3dcb7cdd52eaa696fcb617431f43bcb0dbef0db72a9f9786c2b451efd52775077067cc86a0adf471f6907d024b6b3def90ed5cd974eb5528323192b99ef1fffb9988ade5cc53f671daab54a5b495d397ad0c5d199ccd438ff4a5af80bc554d96ad436096d628a14a9346a64c9a22ba6cc11ede546c6002d48a676822f7fd7f84bf21a94204703f3db9d67961a6d2474856c4cce909b38e66b0cc1540983d8f8b8e249347395f7f798bdc2f96b6c79b8cd676ce55bc1f264b4f450373993e4af05c846`

`key_datas:$telegram$2*100000*0970f6c043d855aa895703b8a1cc086109cf081f72a77b6504f7f4bf3db06420*129294a5eac3196a4c9a88e556f7507b0957f6dd45d704db8abe607ec6d807270c02635289056256a6044a6408e7ef5d33f98c561f16f8aedd2b3ae33ddffddc63c8584dcb232c9f610953f461adb8d29da83f2b01e32db98101febffae4072703bfbfd492e1dd6abeb0926d3df2ed3b47dee4eb6c9f42ab657f89f19d7314c07e2ffc843e448c6d324e9f8d2c3e877a25b0b153736fddb35f5205737620ba2f96aa47f799366150b4de89a0c6e12caa4f03553d164ce9e2e975aadc83538e6ae3df93acb6026f97ac9f6f017a6bbc6607767e591b2c732e3c0ac844584c69dae89ca3272c996eb83b4e66976e3851cfc89be11dc602bb8c0cdf578d9a0a9dbc2296888fa5ee7e58d985a9bf9a1dbc75d2ddfd6ce222c5ee9f3bb40f6e25c2cd`

**Comment by philsmd** [comment]
this is not a "crack my hash service"

That's of course why we close these types of issues immediately.

There is no reason why you post hashes here and also this type of github issue titles/subject is of course discouraged/forbidden.


It's very obvious that you didn't install the driver correctly and this has nothing to do with the hash type.

(BTW: the hash type is not yet supported in any beta or release version, there is only a suggestion for adding this algorithm: [1](https://github.com/hashcat/hashcat/pull/2583), [2](https://hashcat.net/forum/thread-9532.html))
