### ISSUE TITLE
Wordlist not in sync message not giving understandable numbers when using rules

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#2600]
When running with attack mode 9, and for some reason (e.g. a blank line somewhere), the line count between the hashes and the plaintexts is off by one, the displayed error message is confusing, as it e.g. says:

```
Number of words in wordlist wl.txt is not in sync with number of salts (words: 11925732, salts: 152893)
```

Apparently, in the number which is given in `words`, the rules are already calculated into, which makes the message not really helpful to understand what is the issue. I think it would be better (if possible), to only print the number of wordlist entries, so it is possible to see how large the diff exactly is, e.g. in the case above it would be something like:

```
Number of words in wordlist wl.txt is not in sync with number of salts (words: 152894, salts: 152893)
```

**Comment by jsteube** [comment]
Thanks for reporting! Fixed with commit https://github.com/hashcat/hashcat/commit/2f99ea8595cc8fa946be4652bce69b29757355e7
