### ISSUE TITLE
Can't get the right command tfor a certain MD5 brute forcing decryption

### ISSUE THREAD

**Issue by Radu13** [hashcat/hashcat#2601]
Hello I can't get the right command to bruteforce a 16 byte MD5; the output needs to be a 16 byte file returned as 32 HEX values string.

**Comment by ventaquil** [comment]
Hey @Radu13 

I don't know what exactly do you mean by _"i can't get the right command"_.

If you want to use bruteforce (also known as mask attack) you should use attach mode number `3`.

MD5 digest is hash type number `0` for example.

Command below will search through all 7-length passwords using all lowercase letters on all positions.

    hashcat --attack-mode 3 --hash-type 0 '8743b52063cd84097a65d1633f5c74f5' '?l?l?l?l?l?l?l'

More options are available under `--help`.

**Comment by Radu13** [comment]
Hey @ventaquil I have a MD5 of a 16 byte file, the file itself can't be read as normal text, the md5 is based on the hex values of this file, so I need this program search for all 16 byte lenght hex numbers, using letters from A to F and numbers from 0 to 9.
This website calculates the md5 of this file hex input for example: https://emn178.github.io/online-tools/md5.html selecting Hex as input mode, I also attached an example output file it will need be searcherd (You need open it with an HEX viewer to see the exact values which are: FF FF 05 03 07 89 75 45 45 43 56 55 5D ED FF FF)
[Example.txt](https://github.com/hashcat/hashcat/files/5500774/Example.txt)

**Comment by ventaquil** [comment]
If you want you can use `?b` mask to brute-force hex values (from `0x00` to `0xFF`).

But if you want to brute-force 16-byte length input using this mask you probably fail because of overflow error.

**Comment by Radu13** [comment]
How do I set the 16-byte lenght?
Why overflow 16-byte is too much to bruteforce? (I know there will be like 256^16 values but still).

**Comment by ventaquil** [comment]
> How do I set the 16-byte lenght?

Just simply change `?l` symbol in mask from my example to `?b` and repeat 16 times - `?b?b?b?b?b?b?b?b?b?b?b?b?b?b?b?b`.

Please, read `--help` or check some basic examples.

> Why overflow 16-byte is too much to bruteforce? (I know there will be like 256^16 values but still).

Anyway, even if you iterate through 1 billion passwords per second you still need *some time* to iterate through all passwords in this key-space.

Check it out - [WolframAlpha: 256^16 / 10^9 seconds to years](https://www.wolframalpha.com/input/?i=256%5E16+%2F+10%5E9+seconds+to+years).

**Comment by matrix** [comment]
@Radu13 please close the issue and if need using the forum.
