### ISSUE TITLE
Hashtype Kerberos AS-REP with etype 17/18

### ISSUE THREAD

**Issue by rumiljonov** [hashcat/hashcat#2603]
Currently hashcat only supports etype 23 (NTLM) for AS-REP, but in case of Linux krb5kdc hash will be encrypted with AES-128 (etype 17) or AES-256 (etype 18).

Here is an example hash from my local krb5kdc test server
`$krb5asrep$18$roastable@rumiljonov.local:2a45894d63625b4cabc91a8fb8d7f2b7$118dec18ad6d7cdb3b46cd6234d6902b0ea4ba8278460a4b60aea8d4d2e8d24e9747bcf0277574604292bb0dcfcb81f975fe6587301503320e865c77f3d9617c5daf59a5a3c961ee0c38934fce6f88861c91a02850a2c787db89dea5b00b2a5d51d3f533cd9c13795d9542a46d6322e8cad8cad75c98e79c1589cc4b11dda84ce8a929178d384e7e0a8cddc93a8ef0b7c1ccb1b89c3c6712a4c6f7e9def82439c0440f5cfd1618239a3c9888b6e3a0b664a2fd46046e36859b83756b3c6ace4b456228b1496433fa6ab8c5ca8b0e8fed6028f6a222580ec4507e29803ef8fe322f0e`

password is `password`

**Comment by lapolis** [comment]
Hi everyone, is this algorithm being implemented any time soon? or there is a long list ahead?
