### ISSUE TITLE
cuInit(): unknown error while initializing hashcat

### ISSUE THREAD

**Issue by luk0y** [hashcat/hashcat#2605]
Linux version 5.9.0-kali1-amd64
Nvidia Driver Version: 455.32.00
CUDA Version: 11.1
hashcat (v6.1.1)

I am getting "cuInit(): unknown" while trying `hashcat -I ` I am attaching the screenshot below
![Screenshot_2020-11-04_17-44-01](https://user-images.githubusercontent.com/45989946/98149765-a770b600-1ef3-11eb-8c8f-bfc6cf5bd39e.png)
![2](https://user-images.githubusercontent.com/45989946/98150139-341b7400-1ef4-11eb-948b-03f03401c2f6.png)
![3](https://user-images.githubusercontent.com/45989946/98150219-531a0600-1ef4-11eb-84f6-71f65f87b406.png)

I did reinstall cuda many times but getting the same issue again and again. I went through many google searches but still can’t find any solution to get rid off it.

**Comment by DL9EVO** [comment]
Same problem here....

**Comment by ventaquil** [comment]
Are you (your user) in `video` group?

Have you tried with `sudo`?

There is similar problem with Radeon cards and I think that it's not Hashcat related problem.

```shellsession
~$ rocm-smi 
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK     MCLK    Fan     Perf  PwrCap  VRAM%  GPU%  
1    24.0c  7.0W    1138Mhz  800Mhz  13.73%  auto  220.0W    0%   0%    
2    24.0c  8.0W    1138Mhz  167Mhz  12.94%  auto  220.0W    0%   0%    
3    24.0c  15.0W   1138Mhz  167Mhz  13.73%  auto  220.0W    0%   0%    
4    26.0c  6.0W    1138Mhz  800Mhz  12.94%  auto  220.0W    0%   0%    
================================================================================
==============================End of ROCm SMI Log ==============================
~$ hashcat -I
hashcat (v6.1.1) starting...

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.0 AMD-APP (3186.0)

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version.: OpenCL 2.1 LINUX

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
    Version........: OpenCL 2.1 (Build 0)
    Processor(s)...: 40
    Clock..........: 2200
    Memory.Total...: 64070 MB (limited to 16017 MB allocatable in one block)
    Memory.Free....: 64006 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 18.1.0.0920

~$ sudo hashcat -I
hashcat (v6.1.1) starting...

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.0 AMD-APP (3186.0)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx900
    Version........: OpenCL 2.0 
    Processor(s)...: 64
    Clock..........: 1663
    Memory.Total...: 8176 MB (limited to 6949 MB allocatable in one block)
    Memory.Free....: 8064 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3186.0 (HSA1.1,LC)

  Backend Device ID #2
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx900
    Version........: OpenCL 2.0 
    Processor(s)...: 64
    Clock..........: 1663
    Memory.Total...: 8176 MB (limited to 6949 MB allocatable in one block)
    Memory.Free....: 8064 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3186.0 (HSA1.1,LC)

  Backend Device ID #3
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx900
    Version........: OpenCL 2.0 
    Processor(s)...: 64
    Clock..........: 1663
    Memory.Total...: 8176 MB (limited to 6949 MB allocatable in one block)
    Memory.Free....: 8064 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3186.0 (HSA1.1,LC)

  Backend Device ID #4
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx900
    Version........: OpenCL 2.0 
    Processor(s)...: 64
    Clock..........: 1663
    Memory.Total...: 8176 MB (limited to 6949 MB allocatable in one block)
    Memory.Free....: 8064 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3186.0 (HSA1.1,LC)

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version.: OpenCL 2.1 LINUX

  Backend Device ID #5
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
    Version........: OpenCL 2.1 (Build 0)
    Processor(s)...: 40
    Clock..........: 2200
    Memory.Total...: 64070 MB (limited to 16017 MB allocatable in one block)
    Memory.Free....: 64006 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 18.1.0.0920
```

**Comment by luk0y** [comment]
Already tried with sudo same error raising and my system has NViDia RTX 2060

My error is different and it’s related to hashcat and cuda compatibility (I think so)

I saw in some forums related to the similar error but they ain’t helpful

**Comment by gobbedy** [comment]
Same problem.

I have a hunch from reading forums (I could be way off the mark) that it's because my cuda is installed in ```/usr/lib/cuda``` instead of the more common ```/usr/local/cuda```. My suspicion is that ```hashcat``` incorrectly assumes that all cudas are installed in ```/usr/loca/cuda```.

Not sure how to verify my hunch though..

PS. I added my username to ```video``` and it didn't help. I also tried with ```sudo```, and it also didn't help.

**Comment by gobbedy** [comment]
Ok, after some more research I've realized that it's not a ```hashcat``` thing. NVIDIA simply does not support Linux kernel 5.9 as can be read here: https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-Linux-5.9-Delayed

I'm not an expert on this stuff, but the ```nvidia-smi``` and ```nvcc --version``` working appears to be a red herring. Perhaps the driver works for direct rendering, but CUDA is not supported? In any case, I confirmed that CUDA is not supported via python's ```tensorflow``` and ```pytorch```, both of which fail with some cuda error.

I notice that the original commenter (@luck0y) also uses kernel 5.9, so I suspect they're running into the same issue of nvidia not supporting the kernel.

So I think this can be closed as not being an issue with ```hashcat```.

My Kali linux has an option to boot up in 5.8 so I'll try to make nvidia play nice with kali 2020.3 with kernel 5.8, and I'll report back here if anyone else is interested (could take several days as I have other things to do)

**Comment by luk0y** [comment]
You are right .. https://developer.nvidia.com/cuda-downloads?target_os=Linux

I just checked in the top section saying incompatible issues with kernel version of 5.9+. I too have option to boot with 5.8. So let me make a try asap and will update on the issue

**Comment by luk0y** [comment]
Just now I tried installing cuda on the kernel version 5.8 and hurray.. it’s worked. Thank you so much @gobbedy and all . Thanks a lot for the help. Reading notes properly  before any installation is mandatory . Learnt something new. Once again thank you so much.

**Comment by gobbedy** [comment]
Hi @luk0y, I just tried to install the nvidia drivers on Kali 5.7 (I had to do a fresh re-install and now I have the option between 5.9 and 5.7, not 5.8) using the official Kali method: https://www.kali.org/docs/general-use/install-nvidia-drivers-on-kali-linux/

That did not work for me. Did you install using the runfile? Would grateful for some help.

**Comment by luk0y** [comment]
@gobbedy i have installed cuda from a local file .. you can get here 

https://developer.nvidia.com/cuda-downloads?target_os=Linux

My laptop is with 64 bit and I downloaded debian file and installed cuda locally
![C4C10EF1-C910-4A2F-989A-E87E3457BBD1](https://user-images.githubusercontent.com/45989946/98849887-ea91d280-2479-11eb-8d7f-873668cd44d7.jpeg)

**Comment by gobbedy** [comment]
@luk0y thanks for your help!

That didn't work for me (I got the same error when running nvidia-smi saying that it couldn't speak to nvidia drivers).

However, what did work for me was doing these two steps (in that order):

1. Create a file at /etc/modprobe.d/blacklist-nouveau.conf with the following contents:
```
blacklist nouveau
options nouveau modeset=0
```
2. run ```sudo update-initramfs -k all -u```

I'm not sure if the first step was actually necessary (I somehow suspect it actually wasn't), but since it's in the official nvidia guide I doubt it's harmful. The second one was definitely necessary for me!

**Comment by luk0y** [comment]
Cool. Nouveau is also graphic driver. Anyways Nvidia driver gets prioritised after installation. You can check the currently using driver as shown in Kali documentation. 

PS- I also once used to keep nouveau in blacklist and then only Nvidia worked properly

**Comment by gobbedy** [comment]
@luk0y are you able to use your backlight? Mine only works with nouveau. After trying about a million solutions on different forums, I'm about to give up. It seems that the proprietary nvidia drivers do not support backlight (or at least they don't on my laptop)

**Comment by luk0y** [comment]
You mean keyboard backlight?

**Comment by gobbedy** [comment]
@luk0y no, screen backlight. ie, changing the brightness of your screen (either through desktop environment's brightness slider or brightness keys on the keyboard). mine is stuck at 100%

**Comment by roycewilliams** [comment]
Hey, could we move this to the hashcat forums? GitHub issues are for bugs and features, not for general troubleshooting.

**Comment by gobbedy** [comment]
It's a closed issue and people googling this error are likely also to face the same problem, so I figure it can only help others, regardless of whether the original intent of the thread is to resolve a bug? Since the issue is closed it's not like I'm distracting from the main thrust of resolving it.

In any case I just found a solution to my issue. I'll post the solution here and you won't get pesky emails anymore. I solved my backlight issue by following this guy's answer:
https://askubuntu.com/questions/1247592/brightness-control-does-not-work-on-ubuntu-20-04-lts-with-nvidia-geforce-gtx-166

**Comment by luk0y** [comment]
@gobbedy i made something to control brightness in any Linux dist.. check this once https://github.com/luk0y/mlight . Yeah the discussion getting much so I am stopping here @roycewilliams . Anyways this is already closed but still not a place to discuss other than the things in scope.
