### ISSUE TITLE
hashcat error 

### ISSUE THREAD

**Issue by elizabethpareja** [hashcat/hashcat#2608]
hi, when using hashcat I get the error of "wrongdriver".
check my drivers and they are up to date also hashcat recommends using "AMD Radeon Adrenalin 2020 Edition" but when i try to open it,  it closes.
![error 2](https://user-images.githubusercontent.com/27970335/98581844-d777da80-22a0-11eb-89f2-2fba2f54a211.png)

**Comment by ventaquil** [comment]
How about different modes? Problem is only with this hash?

**Comment by elizabethpareja** [comment]
no problem with other hashes, but i need to use mode 1800 or similar

**Comment by ventaquil** [comment]
Which device raises error? You should check every device manually. Maybe it helps to detect the problem.

Have  you tried run attack on Linux? Maybe there are wrong drivers for Windows, idk.

**Comment by matrix** [comment]
Hi @elizabethpareja,

please, paste the output of "hashcat -I", like this: 

```
$ ./hashcat -I
hashcat (v6.1.1-120-g15bf8b730+) starting...

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (May  7 2020 00:10:14)

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 4
    Vendor.........: Intel
    Name...........: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Version........: OpenCL 1.2 
    Processor(s)...: 4
    Clock..........: 3000
    Memory.Total...: 8192 MB (limited to 2048 MB allocatable in one block)
    Memory.Free....: 8128 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.1

  Backend Device ID #2
    Type...........: GPU
    Vendor.ID......: 4
    Vendor.........: Intel
    Name...........: Iris
    Version........: OpenCL 1.2 
    Processor(s)...: 40
    Clock..........: 1200
    Memory.Total...: 1536 MB (limited to 384 MB allocatable in one block)
    Memory.Free....: 0 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2(Oct 30 2020 14:39:13)

```

**Comment by jsteube** [comment]
OP still around? Please retry with latest AMD driver and report the -I output
