### ISSUE TITLE
Feature Request - Add OpenEdge Progress Encode to Hash list

### ISSUE THREAD

**Issue by lucidpsimc** [hashcat/hashcat#2613]
Would it be possible to add this custom hash type? 

I've come across it a couple times and not had an easy tool to help dehash the content. The software was used in authentication setups for relational databases and stores data in a custom 16 character hash. It seems to be source coded here [https://github.com/pvginkel/ProgressEncode](https://github.com/pvginkel/ProgressEncode) .

Below are a few sample hashes to verify (Hash - Dehashed)
ahlnhTczpihljbIn - 1234
lISxlUdfjkinlnGb - 12345
qclcbcljNhJmplaW - 12345678
YajbpdncabllblMj - admin1

All the dehashed values I've seen seemed to be in 4-16 characters limits.

Thank you.

**Comment by jsteube** [comment]
Added to hashcat v6.2.2
