### ISSUE TITLE
ISSUE  launching hashcat -m 2500 -d 2 handshake.hccapx test.txt with intel iris plus graphics 640 1536 MB

### ISSUE THREAD

**Issue by hakimba1** [hashcat/hashcat#2618]
WHEN LAUNCHING I GOT THIS
![Screen Shot 2020-11-25 at 4 44 52 PM](https://user-images.githubusercontent.com/59903007/100284973-0a2aff80-2f3e-11eb-81ed-8cb97b0f12c6.png)

AFTER THAT I NEED TO PRESS s FOR  status each time to increase my percentage

![Screen Shot 2020-11-25 at 4 45 17 PM](https://user-images.githubusercontent.com/59903007/100285129-5413e580-2f3e-11eb-8a98-b4891f0da0ba.png)

i searched everywhere but it seems not working , can you confirm if im able to use hashcat with my graphic card or if you have any solution for that 

thanks a lot

**Comment by ventaquil** [comment]
How about `--help`? If you want to automatically update status check `--status-timer` option.

If you want to use your graphic card you can force backend devices using `--backend-devices` - in your case `--backend-devices 1,2`. Hashcat automatic devices allocation is quite nice so test hashrate for enabled and disabled first device. It can slow your faster device.

**Comment by hakimba1** [comment]
thanks a lot for replying.

**Comment by ventaquil** [comment]
@hakimba1 close issue if it's done.
