### ISSUE TITLE
Feature: Hash wordlist

### ISSUE THREAD

**Issue by zeeuk** [hashcat/hashcat#2619]
Hello,

Can't find a way to convert just a library (word list), to a hashes file. Would be a very useful feature.

Thanks
Zee

**Comment by roycewilliams** [comment]
This is what 'test.pl' in the hashcat distribution is for.

**Comment by matrix** [comment]
@zeeuk, please close the issue and if you want more details ask in forum.

**Comment by jsteube** [comment]
use tools/test.pl in passthrough mode
