### ISSUE TITLE
Feature Request - New-Algo - SolarWinds 2

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#2620]
In #1736 the old way that SolarWinds would use the lowercase username as the salt has changed so that the salt (random-ish 32 bits) is now stored in the database along with the password hash. 

Here is the code that can be used to generate the password store hash: https://gist.github.com/mubix/93a4a2fcb795dd55c38395b59a56d979

As the algorithm hasn't changed from the previous algorithm I'm assuming it would be a simple addition to accepting a base64 encoded salt as part of the hash input. I attempted to do this myself using other hash types as examples but could not figure out how to make it work (my C++ knowledge is rudimentary at best).

cc: @roycewilliams ;-)

Thank you for all the work ya'll do, it is much appreciated.

**Comment by mubix** [comment]
I'm sorry but I do not know the version when this changed to give a better idea of how to name this new algorithm.

**Comment by matrix** [comment]
Hey @mubix / @roycewilliams 

a little preview :)

```
$solarwindsv2$0$q83vASNFZ5q83vASNFZ5qw==$IcIQh9taIIeYQ3HJ4PUU+zOKGEYNxv8iIcquQv/Ll0YRtikrie+uOJ8Hu/tRK9XBT2RE6vGwhmgj7DSioQ7zqg==:HASHCAT
                                                 
Session..........: hashcat
Status...........: Cracked
Hash.Name........: SolarWinds Orion v2
Hash.Target......: $solarwindsv2$0$q83vASNFZ5q83vASNFZ5qw==$IcIQh9taII...7zqg==
Time.Started.....: Mon Nov 30 23:57:49 2020 (0 secs)
Time.Estimated...: Mon Nov 30 23:57:49 2020 (0 secs)
Guess.Base.......: File (21501.pass)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       35 H/s (0.35ms) @ Accel:32 Loops:15 Thr:1 Vec:2
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:990-999
Candidates.#1....: HASHCAT -> HASHCAT

Started: Mon Nov 30 23:57:41 2020
Stopped: Mon Nov 30 23:57:50 2020
```

**Comment by mubix** [comment]
You are amazing!! Awesome!!

**Comment by matrix** [comment]
I seem to understand that the salt length is fixed, so I removed the padding and the call to lowercase. Let me know if I misunderstood :) If you send me a valid hash/salt for password 'hashcat' I replace it in the code. Thanks!

**Comment by mubix** [comment]
I'm getting exactly the same salt length every time:
```
F26EDA2FEB68C5FB869A9E7FF299214A
DE91E4939E4D4D8A40795DC4263700C3
8CD867DE2D97B477D8F32E043A635D89
5E0B4EF1735673F2A221D82518E9F1BF
```
or in base64:
```
8m7aL+toxfuGmp5/8pkhSg==
3pHkk55NTYpAeV3EJjcAww==
jNhn3i2XtHfY8y4EOmNdiQ==
XgtO8XNWc/KiIdglGOnxvw==
```

**Comment by mubix** [comment]
Password: `hashcat`
Salt: `3pHkk55NTYpAeV3EJjcAww==`
Hash: `N4Ii2PxXX/bTZZwslQLIKrp0wvfZ5aN9hpyiR896ozJMJTPO1Q7BK1Eht8Vhl4kXq/42Vn2zp3qYeAkRuqsuEw==`

**Comment by mubix** [comment]
Referenced here: https://malicious.link/post/2020/solarflare-release-password-dumper-for-solarwinds-orion/ thanks @matrix - I recently tested it out and it worked perfectly. You rock!

**Comment by jsteube** [comment]
SolarWinds Orion v2 was added with v6.2.0
