### ISSUE TITLE
Update Hashcat to use ptx version 7.1

### ISSUE THREAD

**Issue by MaximeFrancoeur** [hashcat/hashcat#2626]
With the new CUDA release (11.1) it's impossible to use Hashcat.

Example:

```
~ hashcat -m 500 hash_file /..rockyou.txt
...
...
cuLinkAddData(): the provided PTX was compiled with an unsupported toolchain.
* Device #1: Kernel /usr/share/hashcat/OpenCL/m00500-pure.cl link failed. Error Log:
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.1; current version is '7.0'
* Device #1: Kernel /usr/share/hashcat/OpenCL/m00500-pure.cl build failed.
```

**Downgrading from version 11.1.0 to 11.0.3 fixes the issue.**

> Drivers version:
VIDIA-SMI 450.80.02
Driver Version: 450.80.02
CUDA Version: 11.0

**Comment by ventaquil** [comment]
Is this Hashcat binary from where? Have you tried to build binary from source?

As far as I know you should contact with package maintainer.

**Comment by MaximeFrancoeur** [comment]
yes already compile with source code from master branch

**Comment by haroldLuiz** [comment]
same problem here

```
cuLinkAddData(): the provided PTX was compiled with an unsupported toolchain.
* Device #1: Kernel /opt/hashcat-build/hashcat/OpenCL/shared.cl link failed. Error Log:
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.1; current version is '7.0'

* Device #1: Kernel /opt/hashcat-build/hashcat/OpenCL/shared.cl build failed.
```

And yes, i did compile the source instead of downloading the release.

nvidia-cuda-toolkit: 11.1.1-2
nvidia-driver: 450.80.02-1

**Comment by hops** [comment]
For CUDA 11.1 you need driver version >= 455.23
see: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions
In other words, there's nothing hashcat can do about this. PTX 7.1 is simply not compatible with the 450.x drivers.

**Comment by ventaquil** [comment]
So if it's not related with Hashcat I assume that this issue is ready to close?

**Comment by ZerBea** [comment]
The same applies to CUDA 11.2 (nvidia >= 460.27 mandatory)
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
reported here (for Arch Linux):
https://bugs.archlinux.org/task/69005

Definitely not a hashcat issue.
