### ISSUE TITLE
Ryzen 4700u: Hashcat run (including benchmark) on GPU never ends

### ISSUE THREAD

**Issue by mirao** [hashcat/hashcat#2627]
**Steps:**
```bash
$ ./hashcat.bin -b
hashcat (v6.1.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.
```
... and the benchmark doesn't finish even after a few minutes and does not log anything else.
Hashcat constantly utilizes one of my 8 cores constantly on 100%, see a screenshot from "htop":
![image](https://user-images.githubusercontent.com/12584138/100919873-ade65380-34da-11eb-8c0c-c2439e306765.png)

This is my configuration:
- HW: Lenovo Yoga Slim 7 14ARE05 (with AMD Ryzen 4700u)
- SW:
  - Ubuntu 20.10, kernel 5.8.0-31
  - hashcat 6.1.1
  - OpenCL from proprietary amdgpu-pro-20.40-1147286-ubuntu-20.04 (installed using `./amdgpu-install --opencl=legacy,pal --no-dkms --headless`)

hashscat -I
```
$ ./hashcat.bin -I
hashcat (v6.1.1) starting...

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.1 AMD-APP (3180.7)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: gfx902
    Version........: OpenCL 2.0 AMD-APP (3180.7)
    Processor(s)...: 7
    Clock..........: 1600
    Memory.Total...: 1740 MB (limited to 435 MB allocatable in one block)
    Memory.Free....: 1664 MB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3180.7 (PAL,HSAIL)

```

clinfo output:
```
  Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3180.7)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx902
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0 AMD-APP (3180.7)
  Driver Version                                  3180.7 (PAL,HSAIL)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         Unknown AMD GPU
  Device Topology (AMD)                           PCI-E, 03:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               7
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1600MHz
  Graphics IP (AMD)                               9.2
  Device Partition                                (core)
    Max number of sub-devices                     7
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              1825361100 (1.7GiB)
  Global free memory (AMD)                        1712851 (1.634GiB)
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           456340275 (435.2MiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    410706176 (391.7MiB)
  Preferred total size of global vars             1825361100 (1.7GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                64
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    16
  Max pipe packet size                            456340275 (435.2MiB)
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        456340275 (435.2MiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                262144 (256KiB)
    Max size                                      8388608 (8MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Number of P2P devices (AMD)                     0
  P2P devices (AMD)                               <printDeviceInfo:147: get number of CL_DEVICE_P2P_DEVICES_AMD : error -30>
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1606930531729121724ns (Wed Dec  2 18:35:31 2020)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  Yes
    Number of async queues (AMD)                  4
    Max real-time compute queues (AMD)            1
    Max real-time compute units (AMD)             0
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_copy_buffer_p2p 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx902
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx902
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx902
```

**What I tried:**
- To [install ROCM](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu). But build failed, it seems that only Ubuntu 20.04 with kernel 5.4 is [supported](https://github.com/RadeonOpenCompute/ROCm#list-of-supported-operating-systems) now
- To install Intel OpenCL (somewhere I read that it may helps even for AMD HW). I installed `intel-opencl-icd`, but clinfo doesn't show any info about it

**Comment by Avatat** [comment]
Had you looked here: https://github.com/RadeonOpenCompute/ROCm/issues/1101 ?
I don't think that installing Intel OpenCL would help anything.

**Comment by mirao** [comment]
I read https://github.com/RadeonOpenCompute/ROCm/issues/1101#issuecomment-709356296 and `amdgpu-pro` is what I installed (so had the same experience as that user), but hashcat is not working (neverending)
Just have tried [rocm-dev](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#using-debian-based-rocm-with-upstream-kernel-drivers) (installation of ROCM user level software without kernel driver). It succeeded, but after reboot if I run `clinfo` or `hashcast -I`, my system freezes completely (I must turn it off)

**Comment by mirao** [comment]
The issue is with GPU only.
I tried hashcat with CPU using POCL OpenCL implementation http://portablecl.org/ (built from master) and benchmark works well (no freezing):

```bash
$ OCL_ICD_VENDORS=/usr/local/etc/OpenCL/vendors/ ./hashcat.bin -I
hashcat (v6.1.1) starting...

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: The pocl project
  Name....: Portable Computing Language
  Version.: OpenCL 1.2 pocl 1.7-pre master-0-g89af801e, Debug+Asserts, LLVM 11.0.0, RELOC, SPIR, SLEEF, POCL_DEBUG

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 1
    Vendor.........: AuthenticAMD
    Name...........: pthread-AMD Ryzen 7 4700U with Radeon Graphics
    Version........: OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-znver1
    Processor(s)...: 8
    Clock..........: 2000
    Memory.Total...: 13372 MB (limited to 4096 MB allocatable in one block)
    Memory.Free....: 13308 MB
    OpenCL.Version.: OpenCL C 1.2 pocl
    Driver.Version.: 1.7-pre master-0-g89af801e

```
```bash
$ OCL_ICD_VENDORS=/usr/local/etc/OpenCL/vendors/ ./hashcat.bin -b
hashcat (v6.1.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 pocl 1.7-pre master-0-g89af801e, Debug+Asserts, LLVM 11.0.0, RELOC, SPIR, SLEEF, POCL_DEBUG) - Platform #1 [The pocl project]
====================================================================================================================================================
* Device #1: pthread-AMD Ryzen 7 4700U with Radeon Graphics, 13308/13372 MB (4096 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#1.........:   800.1 MH/s (10.24ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 100 - SHA1

Speed.#1.........:   541.0 MH/s (15.15ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 1400 - SHA2-256

Speed.#1.........:   214.5 MH/s (38.24ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 1700 - SHA2-512

Speed.#1.........: 66039.2 kH/s (63.25ms) @ Accel:1024 Loops:512 Thr:1 Vec:4

Hashmode: 22000 - WPA-PBKDF2-PMKID+EAPOL (Iterations: 4095)

Speed.#1.........:    17706 H/s (86.18ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 1000 - NTLM

Speed.#1.........:  1263.2 MH/s (6.51ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 3000 - LM

Speed.#1.........:   241.5 MH/s (33.78ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 5500 - NetNTLMv1 / NetNTLMv1+ESS

Speed.#1.........:   903.0 MH/s (9.17ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Hashmode: 5600 - NetNTLMv2

Speed.#1.........: 57576.5 kH/s (72.69ms) @ Accel:1024 Loops:512 Thr:1 Vec:8

Hashmode: 1500 - descrypt, DES (Unix), Traditional DES

Speed.#1.........:  9991.3 kH/s (50.16ms) @ Accel:64 Loops:1024 Thr:1 Vec:8

Hashmode: 500 - md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5) (Iterations: 1000)

Speed.#1.........:    55220 H/s (55.27ms) @ Accel:1024 Loops:500 Thr:1 Vec:8

Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix) (Iterations: 32)

Speed.#1.........:     2396 H/s (94.24ms) @ Accel:64 Loops:32 Thr:1 Vec:8

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.#1.........:     5095 H/s (79.92ms) @ Accel:512 Loops:512 Thr:1 Vec:4

Hashmode: 7500 - Kerberos 5, etype 23, AS-REQ Pre-Auth

Speed.#1.........:  5198.0 kH/s (50.02ms) @ Accel:4 Loops:128 Thr:64 Vec:8

Hashmode: 13100 - Kerberos 5, etype 23, TGS-REP

Speed.#1.........:  6271.2 kH/s (83.32ms) @ Accel:16 Loops:64 Thr:64 Vec:8

Hashmode: 15300 - DPAPI masterkey file v1 (Iterations: 23999)

* Device #1: Skipping hash-mode 15300 - known CUDA/OpenCL Runtime/Driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.

Hashmode: 15900 - DPAPI masterkey file v2 (Iterations: 12899)

Speed.#1.........:     2390 H/s (65.63ms) @ Accel:256 Loops:1024 Thr:1 Vec:4

Hashmode: 7100 - macOS v10.8+ (PBKDF2-SHA512) (Iterations: 1023)

* Device #1: Skipping hash-mode 7100 - known CUDA/OpenCL Runtime/Driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.

Hashmode: 11600 - 7-Zip (Iterations: 16384)

Speed.#1.........:     6102 H/s (83.26ms) @ Accel:256 Loops:4096 Thr:1 Vec:8

Hashmode: 12500 - RAR3-hp (Iterations: 262144)

Speed.#1.........:      984 H/s (64.85ms) @ Accel:128 Loops:16384 Thr:1 Vec:8

Hashmode: 13000 - RAR5 (Iterations: 32799)

Speed.#1.........:     2297 H/s (54.73ms) @ Accel:1024 Loops:512 Thr:1 Vec:8

Hashmode: 6211 - TrueCrypt RIPEMD160 + XTS 512 bit (Iterations: 1999)

Speed.#1.........:    12565 H/s (80.54ms) @ Accel:1024 Loops:256 Thr:1 Vec:8

Hashmode: 13400 - KeePass 1 (AES/Twofish) and KeePass 2 (AES) (Iterations: 24569)

Speed.#1.........:     1903 H/s (89.51ms) @ Accel:1024 Loops:512 Thr:1 Vec:8

Hashmode: 6800 - LastPass + LastPass sniffed (Iterations: 499)

Speed.#1.........:   120.6 kH/s (64.41ms) @ Accel:1024 Loops:499 Thr:1 Vec:8

Hashmode: 11300 - Bitcoin/Litecoin wallet.dat (Iterations: 200459)

* Device #1: Skipping hash-mode 11300 - known CUDA/OpenCL Runtime/Driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.

Started: Sun Dec  6 00:50:53 2020
Stopped: Sun Dec  6 00:59:32 2020
```

**Comment by mirao** [comment]
Steps how to build and install POCL (version 1.6-RC1):
```bash
git clone -b v1.6-RC1 https://github.com/pocl/pocl.git
cd pocl
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="/usr" ..
make
sudo make install
```
Now you can call `hashcat` without OCL_ICD_VENDORS, e.g.: `./hashcat.bin -b`

**Comment by matrix** [comment]
> **Steps:**
> 
> ```shell
> $ ./hashcat.bin -b
> hashcat (v6.1.1) starting in benchmark mode...
> 
> Benchmarking uses hand-optimized kernel code by default.
> You can use it in your cracking session by setting the -O option.
> Note: Using optimized kernel code limits the maximum supported password length.
> To disable the optimized kernel code in benchmark mode, use the -w option.
> ```
> 
> ... and the benchmark doesn't finish even after a few minutes and does not log anything else.
> Hashcat constantly utilizes one of my 8 cores constantly on 100%, see a screenshot from "htop":
> ![image](https://user-images.githubusercontent.com/12584138/100919873-ade65380-34da-11eb-8c0c-c2439e306765.png)
> 
> This is my configuration:
> 
> * HW: Lenovo Yoga Slim 7 14ARE05 (with AMD Ryzen 4700u)
> * SW:
>   
>   * Ubuntu 20.10, kernel 5.8.0-31
>   * hashcat 6.1.1
>   * OpenCL from proprietary amdgpu-pro-20.40-1147286-ubuntu-20.04 (installed using `./amdgpu-install --opencl=legacy,pal --no-dkms --headless`)
> 
> hashscat -I
> 
> ```
> $ ./hashcat.bin -I
> hashcat (v6.1.1) starting...
> 
> OpenCL Info:
> ============
> 
> OpenCL Platform ID #1
>   Vendor..: Advanced Micro Devices, Inc.
>   Name....: AMD Accelerated Parallel Processing
>   Version.: OpenCL 2.1 AMD-APP (3180.7)
> 
>   Backend Device ID #1
>     Type...........: GPU
>     Vendor.ID......: 1
>     Vendor.........: Advanced Micro Devices, Inc.
>     Name...........: gfx902
>     Version........: OpenCL 2.0 AMD-APP (3180.7)
>     Processor(s)...: 7
>     Clock..........: 1600
>     Memory.Total...: 1740 MB (limited to 435 MB allocatable in one block)
>     Memory.Free....: 1664 MB
>     OpenCL.Version.: OpenCL C 2.0 
>     Driver.Version.: 3180.7 (PAL,HSAIL)
> ```
> 
> clinfo output:
> 
> ```
>   Number of platforms                               1
>   Platform Name                                   AMD Accelerated Parallel Processing
>   Platform Vendor                                 Advanced Micro Devices, Inc.
>   Platform Version                                OpenCL 2.1 AMD-APP (3180.7)
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
>   Platform Host timer resolution                  1ns
>   Platform Extensions function suffix             AMD
> 
>   Platform Name                                   AMD Accelerated Parallel Processing
> Number of devices                                 1
>   Device Name                                     gfx902
>   Device Vendor                                   Advanced Micro Devices, Inc.
>   Device Vendor ID                                0x1002
>   Device Version                                  OpenCL 2.0 AMD-APP (3180.7)
>   Driver Version                                  3180.7 (PAL,HSAIL)
>   Device OpenCL C Version                         OpenCL C 2.0 
>   Device Type                                     GPU
>   Device Board Name (AMD)                         Unknown AMD GPU
>   Device Topology (AMD)                           PCI-E, 03:00.0
>   Device Profile                                  FULL_PROFILE
>   Device Available                                Yes
>   Compiler Available                              Yes
>   Linker Available                                Yes
>   Max compute units                               7
>   SIMD per compute unit (AMD)                     4
>   SIMD width (AMD)                                16
>   SIMD instruction width (AMD)                    1
>   Max clock frequency                             1600MHz
>   Graphics IP (AMD)                               9.2
>   Device Partition                                (core)
>     Max number of sub-devices                     7
>     Supported partition types                     None
>     Supported affinity domains                    (n/a)
>   Max work item dimensions                        3
>   Max work item sizes                             1024x1024x1024
>   Max work group size                             256
>   Preferred work group size (AMD)                 256
>   Max work group size (AMD)                       1024
>   Preferred work group size multiple              64
>   Wavefront width (AMD)                           64
>   Preferred / native vector sizes                 
>     char                                                 4 / 4       
>     short                                                2 / 2       
>     int                                                  1 / 1       
>     long                                                 1 / 1       
>     half                                                 1 / 1        (cl_khr_fp16)
>     float                                                1 / 1       
>     double                                               1 / 1        (cl_khr_fp64)
>   Half-precision Floating-point support           (cl_khr_fp16)
>     Denormals                                     No
>     Infinity and NANs                             No
>     Round to nearest                              No
>     Round to zero                                 No
>     Round to infinity                             No
>     IEEE754-2008 fused multiply-add               No
>     Support is emulated in software               No
>   Single-precision Floating-point support         (core)
>     Denormals                                     No
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  Yes
>   Double-precision Floating-point support         (cl_khr_fp64)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>   Address bits                                    64, Little-Endian
>   Global memory size                              1825361100 (1.7GiB)
>   Global free memory (AMD)                        1712851 (1.634GiB)
>   Global memory channels (AMD)                    4
>   Global memory banks per channel (AMD)           4
>   Global memory bank width (AMD)                  256 bytes
>   Error Correction support                        No
>   Max memory allocation                           456340275 (435.2MiB)
>   Unified memory for Host and Device              Yes
>   Shared Virtual Memory (SVM) capabilities        (core)
>     Coarse-grained buffer sharing                 Yes
>     Fine-grained buffer sharing                   Yes
>     Fine-grained system sharing                   No
>     Atomics                                       No
>   Minimum alignment for any data type             128 bytes
>   Alignment of base address                       2048 bits (256 bytes)
>   Preferred alignment for atomics                 
>     SVM                                           0 bytes
>     Global                                        0 bytes
>     Local                                         0 bytes
>   Max size for global variable                    410706176 (391.7MiB)
>   Preferred total size of global vars             1825361100 (1.7GiB)
>   Global Memory cache type                        Read/Write
>   Global Memory cache size                        16384 (16KiB)
>   Global Memory cache line size                   64 bytes
>   Image support                                   Yes
>     Max number of samplers per kernel             16
>     Max size for 1D images from buffer            134217728 pixels
>     Max 1D or 2D image array size                 2048 images
>     Base address alignment for 2D image buffers   256 bytes
>     Pitch alignment for 2D image buffers          256 pixels
>     Max 2D image size                             16384x16384 pixels
>     Max 3D image size                             2048x2048x2048 pixels
>     Max number of read image args                 128
>     Max number of write image args                64
>     Max number of read/write image args           64
>   Max number of pipe args                         16
>   Max active pipe reservations                    16
>   Max pipe packet size                            456340275 (435.2MiB)
>   Local memory type                               Local
>   Local memory size                               65536 (64KiB)
>   Local memory syze per CU (AMD)                  65536 (64KiB)
>   Local memory banks (AMD)                        32
>   Max number of constant args                     8
>   Max constant buffer size                        456340275 (435.2MiB)
>   Preferred constant buffer size (AMD)            16384 (16KiB)
>   Max size of kernel argument                     1024
>   Queue properties (on host)                      
>     Out-of-order execution                        No
>     Profiling                                     Yes
>   Queue properties (on device)                    
>     Out-of-order execution                        Yes
>     Profiling                                     Yes
>     Preferred size                                262144 (256KiB)
>     Max size                                      8388608 (8MiB)
>   Max queues on device                            1
>   Max events on device                            1024
>   Prefer user sync for interop                    Yes
>   Number of P2P devices (AMD)                     0
>   P2P devices (AMD)                               <printDeviceInfo:147: get number of CL_DEVICE_P2P_DEVICES_AMD : error -30>
>   Profiling timer resolution                      1ns
>   Profiling timer offset since Epoch (AMD)        1606930531729121724ns (Wed Dec  2 18:35:31 2020)
>   Execution capabilities                          
>     Run OpenCL kernels                            Yes
>     Run native kernels                            No
>     Thread trace supported (AMD)                  Yes
>     Number of async queues (AMD)                  4
>     Max real-time compute queues (AMD)            1
>     Max real-time compute units (AMD)             0
>   printf() buffer size                            4194304 (4MiB)
>   Built-in kernels                                (n/a)
>   Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_copy_buffer_p2p 
> 
> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
>   clCreateContext(NULL, ...) [default]            No platform
>   clCreateContext(NULL, ...) [other]              Success [AMD]
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx902
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx902
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
>     Platform Name                                 AMD Accelerated Parallel Processing
>     Device Name                                   gfx902
> ```
> 
> **What I tried:**
> 
> * To [install ROCM](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu). But build failed, it seems that only Ubuntu 20.04 with kernel 5.4 is [supported](https://github.com/RadeonOpenCompute/ROCm#list-of-supported-operating-systems) now
> * To install Intel OpenCL (somewhere I read that it may helps even for AMD HW). I installed `intel-opencl-icd`, but clinfo doesn't show any info about it

Hi,

there is one option you could try: 

`     --backend-vector-width     | Num  | Manually override backend vector-width to X          | --backend-vector=4
`

Start with 1 (--backend-vector=1) and check if something works or not with benchmark.

Let me known

**Comment by mirao** [comment]
@matrix No difference if call benchmark on GPU with `--backend-vector-width` (tried values 1,2,4,8 and 16) or without that option.
But thanks for tip. I can see the this option can improve performance on CPU (e.g. result for MD5 with value 16 is 1061.0 MH/s whereas result with 8 (default value used for my CPU) is only 795.4 MH/s)

Actually I solved my issue by using CPU instead of GPU (see [my comment](https://github.com/hashcat/hashcat/issues/2627#issuecomment-739433697)), so I can run `./hashcat -D1` successfully.
I guess even if hashcat worked with my GPU, the performance wouldn't be higher than for CPU with 8 cores as it's integrated GPU only ([Radeon RX Vega 7](https://www.notebookcheck.net/AMD-Radeon-RX-Vega-7-Graphics-Card-Benchmarks-and-Specs.450004.0.html)).

**Comment by jsteube** [comment]
Not a hashcat problem, is a driver problem. GitHub issues are for bugs and feature requests only.

**Comment by mirao** [comment]
The easiest way how to get working hashcat on latest Ubuntu 23.04 is `apt install hashcat`. It installs POCL automatically:
```bash
$ sudo apt install hashcat
...
The following additional packages will be installed:
  hashcat-data libpocl2 libpocl2-common pocl-opencl-icd
...
Unpacking hashcat (6.2.6+ds1-1) ...
Setting up hashcat-data (6.2.6+ds1-1) ...
Setting up libpocl2-common (3.1-3) ...
Setting up libpocl2:amd64 (3.1-3) ...
Setting up pocl-opencl-icd:amd64 (3.1-3) ...
Installing new version of config file /etc/OpenCL/vendors/pocl.icd ...
Setting up hashcat (6.2.6+ds1-1) ...
...
```
and everything works as expected

```
$ hashcat -I
hashcat (v6.2.6) starting in backend information mode

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: The pocl project
  Name....: Portable Computing Language
  Version.: OpenCL 3.0 PoCL 3.1+debian  Linux, None+Asserts, RELOC, SPIR, LLVM 15.0.7, SLEEF, DISTRO, POCL_DEBUG

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 1
    Vendor.........: AuthenticAMD
    Name...........: pthread-haswell-AMD Ryzen 7 4700U with Radeon Graphics
    Version........: OpenCL 3.0 PoCL HSTR: pthread-x86_64-pc-linux-gnu-haswell
    Processor(s)...: 8
    Clock..........: 2000
    Memory.Total...: 13293 MB (limited to 2048 MB allocatable in one block)
    Memory.Free....: 6614 MB
    Local.Memory...: 512 KB
    OpenCL.Version.: OpenCL C 1.2 PoCL
    Driver.Version.: 3.1+debian
```

I haven't tried `amdgpu` and `ROCM`. Something about installation is here: https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.3/page/How_to_Install_ROCm.html , but a non LTS Ubuntu 23.04 doesn't seem to be supported.
A latest package for `jammy` (Ubuntu 22.04 LTS) is here: https://repo.radeon.com/amdgpu-install/22.40.3/ubuntu/jammy/
