### ISSUE TITLE
An error was encountered when run with NVIDIA 3080

### ISSUE THREAD

**Issue by xieziping** [hashcat/hashcat#2628]
the phenomenon is：
nvrtcCompileProgram(): NVRTC_ERROR_INVALID_OPTION   
nvrtc: error: invalid value for --gpu-architecture (-arch)
* Device #1: Kernel /hashcat-6.1.1/OpenCL/shared.cl build failed.

CUDA version: 11.0
DRIVER: 455.23.04
hashcat version: 6.1.1

but the hashcat 6.1.1 works well in 2080TI

**Comment by n0rdlicht90** [comment]
Same Problem with 

Ubuntu Server 20.04.1
CUDA: 11.1
DRIVER: 455.45.01
HASHCAT: 6.1.1
GPU: RTX 3080

"invalid value for --gpu-architecture (-arch)"

when i run hashcat without cuda, it works.

**Comment by n0rdlicht90** [comment]
Using the correct CUDA Device with the Option "-d" solved my problem.

**Comment by matrix** [comment]
Hi, please retry by using git version.
Always send the output of "hashcat -I", so we can better understand the setup you have.

Thanks

**Comment by xieziping** [comment]
it's worked， thank you very much👍



---Original---

**Comment by matrix** [comment]
Thanks to you. Please remember to close this issue.

**Comment by VonKlotz** [comment]
i have only one gpu but i had use hashcat -d 2  to make it work
