### ISSUE TITLE
Last commits broke m 2500

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#263]
Hi.
Last commits broke m 2500

commits <= 55e339
Session.Name...: oclHashcat
Status.........: Cracked
Input.Mode.....: File (testliste)
Hash.Target....: File (test.hccap)
Hash.Type......: WPA/WPA2
Time.Started...: Wed Mar  9 12:01:04 2016 (44 secs)
Speed.Dev.#1...:   167.7 kH/s (19.72ms)
Recovered......: 382/382 (100.00%) Digests, 382/382 (100.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:510.07,30604.17,734500.19 (Min,Hour,Day)
Progress.......: 7228416/45782 (15788.77%)
Rejected.......: 0/7228416 (0.00%)
Restore.Point..: 13312/45782 (29.08%)
HWMon.GPU.#1...:  0% Util, 55c Temp, 44% Fan

commits > 55e339

Session.Name...: oclHashcat
Status.........: Exhausted
Input.Mode.....: File (testliste)
Hash.Target....: File (test.hccap)
Hash.Type......: WPA/WPA2
Time.Started...: Wed Mar  9 11:56:40 2016 (1 min, 42 secs)
Speed.Dev.#1...:   145.7 kH/s (4.92ms)
Recovered......: 41/382 (10.73%) Digests, 41/382 (10.73%) Salts
Recovered/Time.: CUR:19,N/A,N/A AVG:24.06,1443.83,34651.96 (Min,Hour,Day)
Progress.......: 17460838/17460838 (100.00%)
Rejected.......: 0/17460838 (0.00%)
HWMon.GPU.#1...:  0% Util, 68c Temp, 53% Fan

.... more than words can say ...

oclHashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-format=3 --outfile-autohex-disable --weak-hash-threshold=0 test.hccap testliste

NVIDIA Corporation GM204 [GeForce GTX 970]

ARCH -Linux

regards
ZerBea

**Comment by philsmd** [comment]
We for sure need some more information here:
1. does the example hash crack for you (https://hashcat.net/wiki/doku.php?id=example_hashes)
2. there is no such commit "55e339", but there is this one (very similar but not the same SHA1 beginning):  https://github.com/hashcat/oclHashcat/commit/555e339
3. if you mean the commit 555e339 I think it is very, very unlikely that it is the reason for this problem since it only touches kernels from -m 1100
4. we need a full example on how to reproduce this: .hccap file, input wordlist/mask/mask file, the correct password, the full command that you've used, info about your setup (escpecially GPUs, nvidia / AMD...) and other relevant information
5. please make sure that you have a clean build (no cached kernel files or obj etc), for instance under linux you might also need to remove ~/.nv/ etc

BTW: I can't reproduce, the example hash works here

**Comment by ZerBea** [comment]
Hi.
1. example works in all commits (but its a very, very, very simple example....)
2. 555e339... (-m 1100) is the last working commit for me)
3. 6636cc1... works not.
4. give me yout pm
5. every test begins with a clean build

Regards 
Mike

**Comment by philsmd** [comment]
so you are saying that "make DEBUG=2" is working, but just "make" isn't. That's weird.
Can you please test this again?

**Comment by ZerBea** [comment]
make DEBUG=2
incredible result:

Session.Name...: oclHashcat
Status.........: Exhausted
Input.Mode.....: File (testliste)
Hash.Target....: File (test.hccap)
Hash.Type......: WPA/WPA2
Time.Started...: Wed Mar  9 14:11:00 2016 (49 secs)
Speed.Dev.#1...:   133.2 kH/s (15.77ms)
Recovered......: 30/382 (7.85%) Digests, 30/382 (7.85%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:36.03,2161.55,51877.16 (Min,Hour,Day)
Progress.......: 6469170/6469170 (100.00%)
Rejected.......: 0/6469170 (0.00%)
HWMon.GPU.#1...:  0% Util, 52c Temp, 39% Fan

**Comment by ZerBea** [comment]
as i mentioned it beforre:
555e339... ist the last working version for me

oclHashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-format=3 --outfile-autohex-disable --weak-hash-threshold=0 test.hccap testliste

NVIDIA Corporation GM204 [GeForce GTX 970]

ARCH -Linux

**Comment by philsmd** [comment]
make DEBUG=2 should be "equivalent" to the Makefile that was used before 6636cc1 (with the additional debugging flags -g -ggdb).
Well, you should be able to see the difference of the full gcc command on the command line. Maybe you can play a little bit with it and see which flag is responsible for failing to crack all hashes.
What I mean is, when you run "make" you should see a/more "gcc ...." command(s). There should be a slight difference between what was set < 6636cc1 and the "make" of the master branch. Now, we need to find out, what (flag) is responsible for this problem.
Can you test this?

**Comment by ZerBea** [comment]
I played around with the Makefile and at least I found the fault....

It is essential to add some own compilerflags to build an arch package.
The new Makefile ignores my old flags and I have to create some new ones...

At least his solved my problem to build a working arch packet
build() {
	cd "$srcdir"
	make PREFIX=/usr/ INSTALL_FOLDER=/usr/bin/ CFLAGS="-I/usr/include/nvidia/gdk/ -Iinclude" oclHashcat64.bin
          }

By the way:
Is it possible to increase the password length for m 2500 from 27 to 63 (or 64 HEX)?

Best regards
Mike

**Comment by ZerBea** [comment]
Issue can be closed...

Thank you for your help

**Comment by ZerBea** [comment]
I did some more tests on the latest commit (https://github.com/hashcat/oclHashcat/commit/8d83493f33041ed5b5deb23bcc47c941339fa980)
compiled with make linux64  PREFIX=/usr/  CFLAGS="-I/usr/include/nvidia/gdk/ -Iinclude generates this kernel during runtime of oclHashcat: amp_a0.ddd53fbb.kernel 

compiled with make linux64  PREFIX=/usr  CFLAGS="-I/usr/include/nvidia/gdk/ -Iinclude generates this kernel during runtime of oclHashcat  amp_a0.7a8ffdfb.kernel

amp_a0.ddd53fbb.kernel works as expected
amp_a0.7a8ffdfb.kernel shows the issue in all amp-kernels

So I did a diff amp_a0.ddd53fbb.kernel amp_a0.7a8ffdfb.kernel
    42c42
    <   mul.wide.u32    %rd5, %r1, 80;
    ---
    >   mul.wide.u32    %rd5, %r1, 272;
    44c44
    <   ld.global.u32   %r10929, [%rd6+64];
    ---
    >   ld.global.u32   %r10929, [%rd6+256];
    20931c20931
    <   mul.lo.s64  %rd9, %rd12, 80;
    ---
    >   mul.lo.s64  %rd9, %rd12, 272;
    20941c20941
    <   st.global.u32   [%rd10+64], %r10929;
    ---
    >   st.global.u32   [%rd10+256], %r10929;

I didn't use make install. I build a package and installed this using pacman.

gcc:    5.3.0
make: 4.1

Package PKGBUILD:
...
build() {
    cd "$startdir"
    rsync -av --delete $_pkgname/ src
    patch -p1 $srcdir/src/Makefile < Makefile.patch
    cd "$srcdir"
    make linux64 CFLAGS="-I/usr/include/nvidia/gdk/ -Iinclude"
}

package() {
    cd "$srcdir"
    install -d "${pkgdir}/usr/share/oclHashcat/"
    install -d "${pkgdir}/usr/share/doc/oclHashcat/"
    cp -ar charsets OpenCL include masks rules hashcat.hcstat hashcat_tuning.hctab extra "${pkgdir}/usr/share/oclHashcat/"
    cp -ar docs/\* "${pkgdir}/usr/share/doc/oclHashcat/"
    install -Dm755 oclHashcat64.bin "$pkgdir/usr/bin/oclHashcat"
}
...

Makefile.patch:
-PREFIX                   ?= /usr/local
+PREFIX                   ?= /usr/

This works fine for me, but I don't understand why there is a difference in the compliled amp-kernels depending on a tailing slash in the Makefile....

Best regards
ZerBea

**Comment by philsmd** [comment]
First of all, this seems to be _a different problem_ if you say that what you are experiencing now has nothing to do with commit 6636cc1 .

Secondly, I don't think the way you are testing these problems is very clever, since you always mention this external pacman tool.
What about the native build (without involving any external package manager etc) but instead just running "make clean", rm -rf ~/.nv/, "make" and "./oclHashcat -m 2500..." ?

**Comment by ZerBea** [comment]
You're right. I patched the makefile before, and https://github.com/hashcat/oclHashcat/commit/6636cc144d35f2246b85c4b8bbe9b9f5bad5c799 reversed my patch.......

I did some other tests.

My flags (I need this to compile oclHashcat successfully on ARCH)
CFLAGS="-I/usr/include/nvidia/gdk/ -Iinclude"
- Native build works.
- make install didn'work because hashcat_tuning.hctab wasn't installed automaticly by the makefile
  /usr/local/share/oclHashcat/hashcat_tuning.hctab: No such file or directory
  must copy this file by hand and the the build works 
- make PREFIX=/usr install didn't work 
  2013 segmetation fault
- make PREFIX=/usr/ install works 
- Involving the arch package manager to install to /usr only works with the PREFIX=/user/
- Involving the arch package manager to install to /usr/local works

Well, it's not the ARCH package manager that causes the issue.
It seems, oclHashcat doesnt'l like to be installed in /usr

By the way...
Why do you not use the final suggestion (issue #20)
snip
We discussed the new "layout", this is the final suggestion:
    /usr/bin/_.bin
    /usr/share/doc/oclHashcat/ (stuff from docs/_ and example\* files)
    /usr/share/doc/oclHashcat/extra/*
    /usr/share/oclHashcat/hashcat.hcstat
    /usr/share/oclHashcat/charsets/*
    /usr/share/oclHashcat/kernels/*
    /usr/share/oclHashcat/masks/*
    /usr/share/oclHashcat/rules/*
snip

Instead of this,  Makefile uses:
PREFIX                   ?= /usr/local

best regards
ZerBea

**Comment by neheb** [comment]
umm are you sure you need those CFLAGS? I can compile oclHashcat without them. I remember they used to be required but not anymore.

edit: i just looked at the PKGBUILD. It makes assumptions that are not true anymore. amd-adl-sdk is not required anymore either.

**Comment by ZerBea** [comment]
Hi neheb. Thank your for the information. Indeed, the flags are used no more.
Which PKGBUILD do you mean?
I don't use AUR packages, I build my own packages (nvidia-gdk-352.79-1-x86_64.pkg / oclHashcat-git-r694.d7f8b35-1-x86_64.pkg). Both are working fine

My main questions are:
Why are there issues when compiling oclHashcat with /usr instead of /usr/local ?
(/usr/local is obsolete in ARCH in future times).
Why are there no issues when compiling oclHashcat with /usr/?

By the way, you should think about an increase of exec_path_len from 1024 to PATH_MAX (4096) in shared.c
char *get_exec_path ()
  int exec_path_len = 1024;

**Comment by ZerBea** [comment]
Is it possible, that the detection of the of the install dir (shared.c) could cause this issue:
  if ((last_slash = strrchr (install_dir, '/')) != NULL)
    *last_slash = 0;

**Comment by philsmd** [comment]
Well, this is just a simple way to remove the binary file (actually /binary_file[.bin]) from the exec_path (which conists of path/binary_file[.bin]) such that the result is just the "path".
You can always debug this if you are not convinced before this line: https://github.com/hashcat/oclHashcat/blob/master/src/oclHashcat.c#L5633, e.g. something like

```
printf ("%s vs %s\n", install_dir, resolved_install_folder);
```

**Comment by ZerBea** [comment]
Hi philsmd.
Tnx for your info. At least I think, I found the fault. The output of the compiler process on my machine was everytime "oclHashcat64.bin" (crosscompiled output).
After a clean copy of the make file, now the end of the process is a native build (oclHashcat) and everthing's fine......
Best regards
ZerBea
