### ISSUE TITLE
Building in ios14 terminal - error arc/affinity.c:6: include/common.h:40:10: fatal error: ‘String.h’ file not found

### ISSUE THREAD

**Issue by aymanioo** [hashcat/hashcat#2630]
![1FEDE8EA-CF63-4D5D-A20F-9272DE68DFB2](https://user-images.githubusercontent.com/75053469/101062305-7bcb0500-355f-11eb-98bd-685fbbb1c03c.jpeg)

**Comment by matrix** [comment]
Hi, build with iOS is not supported :)
Thanks
