### ISSUE TITLE
1820 type problem

### ISSUE THREAD

**Issue by Ilan-sec** [hashcat/hashcat#2633]
Hello,
I have this kind of hash:
$krb5asrep$18$test.com$bdf82921db1a1e3
which should belong to the 18200 type hash but it returns error.

Can anyone help with this?

Thanks,

Ilan-sec.

**Comment by matrix** [comment]
Hi, the signature of 18200 hash type is "$krb5asrep$23$", but you have "$krb5asrep$18$". Your hash type is currently not supported. Please, next time use the forum for this type of question.

Thanks

**Comment by matrix** [comment]
#2603

**Comment by jsteube** [comment]
Double post
