### ISSUE TITLE
Cannot crack SHA1 hashes whose bytes were Unicode (UTF-16) encoded

### ISSUE THREAD

**Issue by alhajee** [hashcat/hashcat#2635]
Hashcat does not support other encodings, I am working with are SHA1 (where the Bytes are encoded using Unicode (UTF-16))

Now, the Byte string I get when passwords are encoded using Unicode is different from when It's encoded in UTF8.

And I cannot find a way to tell Hashcat to Encode everything in Unicode too.

**Comment by alhajee** [comment]
Here's the code used to Hash the passwords
```
Public Function HashPassword(ByVal password As String) As String
        Dim hashBytes As Byte()
        Dim encoding As New UnicodeEncoding
        hashBytes = encoding.GetBytes(password)
        Dim sha1 As New SHA1CryptoServiceProvider
        Dim hashedPassword As Byte() = sha1.ComputeHash(hashBytes)

        'Convert bytes to Hex string
        Dim Result As New StringBuilder()
        For Each b As Byte In hashedPassword
            Result.Append(b.ToString("x2"))
        Next
        Return Result.ToString()
    End Function
```

**Comment by alhajee** [comment]
123456: 6ed5833cf35286ebf8662b7b5949f0d742bbec3f (**Unicode/UTF-16  Encoding**)

123456: 7c4a8d09ca3762af61e59520943dc26494f8941b (**UTF8 Encoding**)

**Comment by s3inlc** [comment]
You just need to convert it previously and fill with NULL values between the chars

```
6ed5833cf35286ebf8662b7b5949f0d742bbec3f:$HEX[310032003300340035003600]

Session..........: hashcat
Status...........: Cracked
Hash.Name........: SHA1
Hash.Target......: 6ed5833cf35286ebf8662b7b5949f0d742bbec3f
Time.Started.....: Tue Dec 08 22:36:42 2020 (0 secs)
Time.Estimated...: Tue Dec 08 22:36:42 2020 (0 secs)
Guess.Base.......: File (..\test.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     2008 H/s (0.02ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........:     2008 H/s
Recovered........: 1/1 (100.00%) Digests
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: $HEX[003100320033003400350036] -> $HEX[310032003300340035003600]
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 43c Fan: 27% Util: 16% Core:1506MHz Mem:3802MHz Bus:16
Hardware.Mon.#2..: Temp: 39c Fan: 29% Util: 23% Core:1151MHz Mem:3004MHz Bus:4

Started: Tue Dec 08 22:36:32 2020
Stopped: Tue Dec 08 22:36:43 2020
```

**Comment by alhajee** [comment]
I do not understand, please what command line value did you use?

**Comment by s3inlc** [comment]
I just let it run with a test dictionary containing the plaintext `$HEX[310032003300340035003600]`.
To automate the conversion it should be possible to use iconv and convert it to unicode first and then pipe directly into hashcat, no hex encoding needed in that case then.

**Comment by alhajee** [comment]
Oh, i get it. I am using a dictionary containing the plaintext in the form "123456" etc. 

I was hoping there was a way to do this in Hashcat without using an other program like iconv.

I noticed there is an option **--encoding-from** and **--encoding-to**

**Comment by alhajee** [comment]
Thank you. 

I was able to crack the hash when i added the $HEX[310032003300340035003600] into the dictionary.

Must i do that for all the wordlist in the dictionary>

**Comment by matrix** [comment]
@alhajee check this

```
$ cat test.hash 
6ed5833cf35286ebf8662b7b5949f0d742bbec3f
$ cat test.pass 
123456
$ ./hashcat -m 100 test.hash test.pass --encoding-to=utf-16le --quiet
6ed5833cf35286ebf8662b7b5949f0d742bbec3f:$HEX[310032003300340035003600]
```

Remember to close the issue if it has been resolved :)

**Comment by alhajee** [comment]
Thanks @matrix 

Works like a charm
