### ISSUE TITLE
Error to run in raspberry pi4

### ISSUE THREAD

**Issue by sagaardu** [hashcat/hashcat#2641]
Hi, 

I have installed hashcat:

sudo git clone https://github.com/hashcat/hashcat.git
cd hashcat
sudo make
sudo make install

But when i go to run show this:

hashcat (v6.1.1-120-g15bf8b730) starting...

ATTENTION! No OpenCL or CUDA installation found.

You are probably missing the CUDA or OpenCL runtime installation.

* AMD GPUs on Linux require this driver:
  "RadeonOpenCompute (ROCm)" Software Platform (3.1 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)

Started: Sat Dec 12 18:03:33 2020
Stopped: Sat Dec 12 18:03:33 2020

**Comment by ventaquil** [comment]
How about OpenCL drivers?

**Comment by Avatat** [comment]
I'm not sure if RPi 4 supports OpenCL :/

**Comment by ventaquil** [comment]
There is related issue #2606 - I think that POCL driver is an option.

**Comment by jsteube** [comment]
GitHub issues are for bugs and feature requests. Please use hashcat forums instead.
