### ISSUE TITLE
--encoding-to doesn't work in bruteforce mode

### ISSUE THREAD

**Issue by alhajee** [hashcat/hashcat#2642]
--encoding-to seems to only run in dictionary mode but fails to work in bruteforce mode

**Comment by alhajee** [comment]
I found a solution:

**Hashcat does support UTF-16le (Unicode) encoding**

You simply need to select the right hash type, prior to this I have been using the default **SHA1(100)** . 
Which by default encodes to UTF-8

The correct hash type for UTF-16le/Unicode encoded pass is **sha1(utf16le($pass).$salt)** (that's **-m 130** in command line)

If you do have a salt, use your preferred separator to separate them in your hash file.
Eg **"hash:salt"**

If you don't, still append the separator at the end of the hash
Eg **"hash:"**

**Comment by alhajee** [comment]
@matrix 👍

**Comment by matrix** [comment]
with -m 170 you can now quickly crack this type of hashes without set null salt
