### ISSUE TITLE
Error during plug-in

### ISSUE THREAD

**Issue by MG-302** [hashcat/hashcat#2643]
During plug-in development, the program reported an error "Missing symbol definitions. Old template?", how can I solve it?
In addition, how to debug the plug-in development?
Thanks！

**Comment by matrix** [comment]
I just pushed a lot of hash-modes, you can use them as a template / case study

**Comment by jsteube** [comment]
All you need to do is to add these lines to the module and recompile:

```
  module_ctx->module_hook_extra_param_size    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_init    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_term    = MODULE_DEFAULT;
```
