### ISSUE TITLE
-m2500 -a3 is missing cracks with partial mask

### ISSUE THREAD

**Issue by th3mechanic** [hashcat/hashcat#265]
Ubuntu 14.04  nvidia driver 361.28, git version g94912b3 

used hashcat example file to verify wasn't my own hccap issue,  

this mask will crack  ?l?lshcat! 
this one fails to find ?l?l?lhcat! 
seems to fail on any mask to right side hashca?l!  fails also

**Comment by jsteube** [comment]
I can't reproduce this. Tested with Ubuntu 15.04 nvidia driver 361.18, git version g94912b3

```
root@ht:~/oclHashcat# ./oclHashcat --weak-hash-threshold 0 --potfile-disable -m 2500 hashcat.hccap -a 3 '?l?lshcat!' --quiet
hashcat.net:0025cf2db489:b0487ad676e2:hashcat!
root@ht:~/oclHashcat# ./oclHashcat --weak-hash-threshold 0 --potfile-disable -m 2500 hashcat.hccap -a 3 '?l?l?lhcat!' --quiet 
hashcat.net:0025cf2db489:b0487ad676e2:hashcat!
```

You maybe forgot to rm -rf ~/.nv and kernels after pull?
