### ISSUE TITLE
RX580 Hashcat crashes on initialization

### ISSUE THREAD

**Issue by cyberneticsLab** [hashcat/hashcat#2660]
I am having some serious issues with getting hashcat to work with my RX580's. After a fresh install and driver installation, I grab hashcat and run it with the -I option to verify setup. It hangs, then I get a crash report. Here is what I have done so far:

Fresh install of 20.04.1.
Run updates for update, dist-upgrade, and install libnuma-dev and reboot.
Grab rocm gpg key and add it to the repo list, then install using rocm-dkms and reboot.
I then install hashcat and run -I for verification (v4.0.1 up to v6.1.1 with the same result)
I have installed it via apt install, via git, and through their website and unzipping via 7z e.
I have attempted to install the amdgpu-pro drivers from their website, and also have attempted many older and newer kernels without any luck. The farthest I had gotten was to get hashcat to list the GPU's, but then when running a benchmark, it would crash when starting a MD5 run.

I have verified I am running the latest version of my bios, and I have also tried just a single card with the same result (tried all four individually). I can verify that Ubuntu can see the cards when using lspci.

PC Specifications: Ubuntu 20.04.1(LTS) Linux Kernel 5.4.0-58 && 5.4.0-42 Gigabyte x399 AORUS PRO mobo AMD Ryzen Threadripper 2950X 32GB DDR4 RAM 4x MSI RX 580 GPU

Problem report: ProblemType - KernelOops Title - general protection fault: 0000 [#1] SMP NOPTI

Help would be greatly appreciated!

**Comment by ventaquil** [comment]
How about `clinfo` or `rocminfo`? Is it raises error too?

Which version of ROCm do you have?

**Comment by jsteube** [comment]
I'm not 100% certain but I think you need to use PCI 3.0 slots in order to use rocm. Please use the legacy drivers instead, at least they work for my RC480. However, this is not an issue for GitHub which is for bugs and feature requests only. Please use hashcat forums.
