### ISSUE TITLE
The most useful attack seems missing

### ISSUE THREAD

**Issue by cypherki** [hashcat/hashcat#2670]
There is no rule that tells hashcat to not to try to crack a hash with a candidate with repeated characters. imho, it would shorten a lot some attacks.

pd: sorry if this isn't the best place to tell this but i dont know how to pull a request

**Comment by matrix** [comment]
hi, for repeated characters you mean sequential characters ?

example
seq = 2
ABCCDEFG <= dropped
ABCDEFGH <= accepted
ABCDABCD <= accepted

Let me known :)

**Comment by dkmc360** [comment]
Following. Some attacks can be reduced if the option is available for the mask attack.

**Comment by cypherki** [comment]
> hi, for repeated characters you mean sequential characters ?
> 
> example
> seq = 2
> ABCCDEFG <= dropped
> ABCDEFGH <= accepted
> ABCDABCD <= accepted
> 
> Let me known :)

Almost. I meant:

ABCCDEFG <= accepted
ABCDEFGH <= accepted
ABCDABCD <= dropped

**Comment by jsteube** [comment]
It's not possible because the final keyspace is unknown. So this will work only in stdin mode. I recommend using maskprocessor using -r and then pipe this to hashcat.
