### ISSUE TITLE
Crack multi hccapx file at same time?

### ISSUE THREAD

**Issue by HeIp** [hashcat/hashcat#2675]
Hello I have a hccapx file that I combined with 3 other hcappx files.
My question is it's possible for hashcat to run against all the handshakes at the same time,
Instead of treating it like 3 different sessions.

I'm only asking as I would assume as this would speed up the process.
Example: 1 handshake takes 2 days. Hashcat is making the eta time 6 days.
Instead of scanning against each handshake per 1 bruteforce, taking a total of 2 days.

Wondering if there's a way to do this.
Thank you in advance.

**Comment by ZerBea** [comment]
Reuse of PBKDF2 is only possible on the same ESSIDs.
PMK = PBKDF2(PSK, ESSID, 4096, 256)
To get full advantage of reuse of PBKDF you should merge networks with the same ESSID into a file.

BTW:
hccapx is deprecated in favor of new hash mode 22000. 

You can read more here:
https://en.wikipedia.org/wiki/Pbkdf2
or play an example here:
http://jorisvr.nl/wpapsk.html

The hashcat recommended tools for WiFi capturing, conversion and pre-processing are hcxdumptool and hcxtools.

**Comment by ZerBea** [comment]
hcxtools will help you to get full benefit of reuse of PBKDF2:
hcxdumptool -> hcxpcapngtool -> hcxhashtool with option essid-group -> hashcat
In that case all networks (PMKID and EAPOL) with the same ESSID are stored in a single hashfile.
Running this hash file on hashcat, you'll get full hash rate.
