### ISSUE TITLE
Disable PID when using Hashcat as library

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#2678]
I am still working on porting Hashcat to Python. I looked at [`f0cker/pyhashcat`](https://github.com/f0cker/pyhashcat) but it looks like C-code-in-Python, not like Python project. I made up some changes [here](https://github.com/ventaquil/pyhashcat) but still working on many more and got next problem when using Python [`threading.Thread`](https://docs.python.org/3/library/threading.html#threading.Thread) class with Hashcat library.

In Python REPL for example I can spawn many Python threads to run multiple attacks in one script. Unfortunately Hashcat has some checks against that so I am thinking about library-only option that disables PID checks.

For example I have two devices and two different attacks

```python
from threading import Thread
dev0 = hashcat.devices[0]
dev1 = hashcat.devices[1]
att0 = create_dictionary_attack()
att1 = create_mask_attack()
thread0 = Thread(target=dev0.run, args=(att0,))
thread1 = Thread(target=dev1.run, args=(att1,))
thread0.start(), thread1.start()
print("wating for attacks")
thread0.join(), thread1.join()
```

After `check_running_process` function execution from file `pidfile.c` I got `hashcat_session_init failed: Already an instance '/usr/bin/python3.8' running on pid 81371`. When I comment it and set `const int rc = 0` everything works very well.

Unfortunately I cannot use [`multiprocessing.Process`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process) because I got `hashcat_session_init failed: clCreateCommandQueue(): CL_OUT_OF_HOST_MEMORY` for GPU devices (CPU seems to be okay).

I can prepare PR or keep changes in my private repo. So, what do you think?

**Comment by matrix** [comment]
Hi, are you sure you are not running multiple hashcat instances in parallel?

**Comment by ventaquil** [comment]
Hey @matrix, thanks for response.

I am sure that **I am running** many instances in parallel. Is this a problem? If yes - why? I got valid results.

**Comment by matrix** [comment]
In the past we have seen that running multiple instances in parallel generated false negatives. As if the buffers were being corrupted. Consequently this control has been integrated.
Let's say that if you use different devices, you shouldn't have too many problems, but it is a theory to be verified.

**Comment by ventaquil** [comment]
I am thinking how can I proof that it works 🤔 

Currently I launched a lot of concurrent benchmarks on 4x GPU and 1x CPU in one process where each device has own `hashcat_ctx`.

It seems that I don't lost so much on performance.

```
$ sudo hashcat --benchmark --hash-type 0 --workload-profile 4
hashcat (v6.1.1) starting in benchmark mode...

OpenCL API (OpenCL 2.0 AMD-APP (3186.0)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #2: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #3: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU
* Device #4: gfx900, 8064/8176 MB (6949 MB allocatable), 64MCU

OpenCL API (OpenCL 2.1 LINUX) - Platform #2 [Intel(R) Corporation]
==================================================================
* Device #5: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, skipped

Benchmark relevant options:
===========================
* --workload-profile=4

Hashmode: 0 - MD5

Speed.#1.........: 16208.8 MH/s (132.10ms) @ Accel:512 Loops:1024 Thr:64 Vec:1
Speed.#2.........: 16091.8 MH/s (133.02ms) @ Accel:512 Loops:1024 Thr:64 Vec:1
Speed.#3.........: 15921.0 MH/s (134.44ms) @ Accel:512 Loops:1024 Thr:64 Vec:1
Speed.#4.........: 15915.6 MH/s (134.68ms) @ Accel:512 Loops:1024 Thr:64 Vec:1
Speed.#*.........: 64137.2 MH/s

Started: Wed Jan 13 12:52:00 2021
Stopped: Wed Jan 13 12:52:19 2021
```

versus

```
BencharkResult(device=Device(id=0, global_id=1, type=2, name='gfx900', vendor='Advanced Micro Devices, Inc.'), hash=Hash(mode=0, name='MD5'), hashrate='13837.2 MH/s')
BencharkResult(device=Device(id=1, global_id=2, type=2, name='gfx900', vendor='Advanced Micro Devices, Inc.'), hash=Hash(mode=0, name='MD5'), hashrate='14339.0 MH/s')
BencharkResult(device=Device(id=2, global_id=3, type=2, name='gfx900', vendor='Advanced Micro Devices, Inc.'), hash=Hash(mode=0, name='MD5'), hashrate='14183.1 MH/s')
BencharkResult(device=Device(id=3, global_id=4, type=2, name='gfx900', vendor='Advanced Micro Devices, Inc.'), hash=Hash(mode=0, name='MD5'), hashrate='13552.2 MH/s')
```

It's first attempt - maybe I should disable self-test and tune something. I am going to work more on this topic.

Next step is to run some attacks and check for false-positives.

**Comment by jsteube** [comment]
I think running multiple hashcat instance in parallel is not a problem, even on the same device! But you need to make sure to set the --session parameter, that should also fix your pidfile issue. Please let me know if that fixed the problem.

**Comment by ventaquil** [comment]
Few quick tests return valid results so it seems that you are right @jsteube, thank you!

It looks like I had some bugs before because as far as I remember I have tried to deal with sessions.
