### ISSUE TITLE
-aes-256-ecb support

### ISSUE THREAD

**Issue by roccomuso** [hashcat/hashcat#2679]
Does Hashcat support aes 256 ecb cracking?

**Comment by ventaquil** [comment]
Are you asking about raw AES? How to generate key?

I am afraid that this options is not implemented.

**Comment by roccomuso** [comment]
Key is actually a padded password.

**Comment by bigfella237** [comment]
I'd also be interested in an AES256 ECB mode. Does it already exist in Hashcat?

I know the odds of finding a 256-bit key are astronomical but this mode would still be very handy.

**Comment by ventaquil** [comment]
Few more questions @roccomuso @bigfella237:
* How to pad key? Fill empty space with zeros? What if password is bigger than 256 bit key?
* How to verify that key is correct? For example TrueCrypt has known structure (like encrypted `TRUE`) but what structure has plaintext in your case?

**Comment by roccomuso** [comment]
- yes, password cannot be bigger than 256 bit key.
- In my case you have the encrypted block of a known plain text.

**Comment by bigfella237** [comment]
For me, I'm not interested in passwords nor padding.

I simply have a Plaintext / Ciphertext pair in hexadecimal and I need to find either the 128-bit or 256-bit AES key in hexadecimal. 

And of course I would need to select whether to search for a 128-bit or a 256-bit key (perhaps two different modes).

**Comment by bigfella237** [comment]
To add an example (for my purposes anyway):

Plaintext: 10 CE CC F2 30 74 0F 5F C7 6E FF 4F 01 E2 33 0E
Ciphertext: 6F EF FA 8A 14 D9 DB 09 EE 17 D2 C7 37 7E 6C 5A

And the verified 256-bit key used in this example is:
01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32

**Comment by ventaquil** [comment]
Okay, so you want to run known-plaintext attack. It seems to be useful but still don't know how you would like to generate keys from key-candidates.

Like I have dictionary with records:
```
cat
dog
sun
hello
admin
```

None of these can be valid AES key (no matter which - 128, 192 or 256). For example if I get `cat` record and use it as bytes `[0x63, 0x61, 0x74]` which padding should I add? Zeros?

You should also consider that breaking raw AES key can be costly.

**Comment by roccomuso** [comment]
yes, for instance padding with 0 would be ok in my case

**Comment by derekthedevil** [comment]
guys can anybody tell me the exact AES-256-CBC algorithm steps, which I think (correct me if I am wrong ) is used to encrypt passphrase in bitcoins/litecoin wallet.dat file example ( $bitcoin$64$ca08895529a74487.........................aeb0 )
I am developing a tool and and need it

**Comment by bigfella237** [comment]
@derekthedevil this support request is for AES ECB (Electronic Codebook) mode, not CBC (Cipher Blocker Chaining).

Perhaps your question would be better asked in the forums?

**Comment by derekthedevil** [comment]
Ok thanks 😁

**Comment by jsteube** [comment]
Is this still required? Otherwise please close this issue.

If you really want to have this (is actually super simple to add a plugin), but please explain the following: Inside the kernel we need to test for something to be true in case the correct key was used. So typically we decrypt some data and then we test some sort of structure or fixed byte stream. In other KPA hash-modes like DES we let the user specify the data portion. However in DES it's only 8 byte while in AES its 16 bytes. Is that what you're looking for?

**Comment by bigfella237** [comment]
Yes it's still required, please don't close this issue!

I don't have examples for the padded key search that @roccomuso was talking about, but I posted a verified data set a few posts above for a simple brute force attack...
> 
> 
> To add an example (for my purposes anyway):
> 
> Plaintext: 10 CE CC F2 30 74 0F 5F C7 6E FF 4F 01 E2 33 0E
> Ciphertext: 6F EF FA 8A 14 D9 DB 09 EE 17 D2 C7 37 7E 6C 5A
> 
> And the verified 256-bit key used in this example is:
> 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32

**Comment by jsteube** [comment]
@roccomuso KPA attacks in hashcat are always fixed to the key size exactly. So we can make this works, but you'd need to pad the passwords yourself. That ok for you?

**Comment by roccomuso** [comment]
yes

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/909d5e64a5d78ea6bab7c4dfa33d282dc51e1d32

As described in the commit message, I see this hash mode more like a template kernel because I believe there's only very few real-world applications using this, if any.

In order to utilize full GPU power we need to have some amplifiers involved. Therefore I lifted the exact input candidates length requirement so that you can use the rule engine, use hybrid attacks or even brute-force. The kernel will do the padding for you.

AES Bit length 128, 192 and 256 are supported.

Performance on my RTX2080Ti:

128: 3821.1 MH/s
192: 3291.4 MH/s
256: 2691.6 MH/s

**Comment by roccomuso** [comment]
@jsteube can you share some usage hints?
I'm not sure it covers my need.

If I have a dictionary or I wanna try bruteforce. I would need to pad the password with 0 in order to get to a 256 bit key:

`cat` would be like `cat0000000000000`

**Comment by jsteube** [comment]
You can use cat in a regular wordlist. The kernel will do the padding for you.

**Comment by bigfella237** [comment]
So the modes are m26401, m26402 & m26403?

Are they AES-128, AES-192 & AES-256 respectively?

**Comment by jsteube** [comment]
Yeah, try out --help

```
  26401 | AES-128-ECB NOKDF (PT = $salt, key = $pass)         | Raw Cipher, Known-Plaintext attack
  26402 | AES-192-ECB NOKDF (PT = $salt, key = $pass)         | Raw Cipher, Known-Plaintext attack
  26403 | AES-256-ECB NOKDF (PT = $salt, key = $pass)         | Raw Cipher, Known-Plaintext attack
```

**Comment by roccomuso** [comment]
what if I don't have a complete plain-text? like the 4 last bytes are unknown
