### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by mutepigz** [hashcat/hashcat#268]
I want to install it in linux,but how can i do it? thanx

**Comment by jsteube** [comment]
See here: https://github.com/hashcat/oclHashcat/blob/master/docs/BUILD.md

**Comment by epixoip** [comment]
Questions like this belong on the forums, not on Github.

**Comment by mutepigz** [comment]
thanks you!  But i have another problem when i run "sh example0.sh" :
`ERROR: clGetPlatformIDs() : -1001 : CL_UNKNOWN_ERROR`
what'this!

**Comment by epixoip** [comment]
Again, this is an issue for the Hashcat Forums, not Github. But this typically means your OpenCL environment is not set up correctly, or driver is not installed properly. See the Hashcat Wiki for help and if you still need assistance, ask on the forums.
