### ISSUE TITLE
des encrypted twice, where or which file  should i edit to take effect, please

### ISSUE THREAD

**Issue by is-xuwei** [hashcat/hashcat#2682]
i edited hashcat-6.1.1\OpenCL\m14000_a0-pure.cl and rebuid but it did not work.

**Comment by ventaquil** [comment]
What you want to achieve?

What changes have you implemented?

**Comment by is-xuwei** [comment]
hi,

thanks for reply.

i had changed:
\hashcat-6.1.1\OpenCL\m14000_a0-pure.cl and 
\hashcat-6.1.1\OpenCL\m14000_a1-pure.cl
 :
KERNEL_FQ void m14000_mxx (KERN_ATTR_RULES ()) and KERNEL_FQ void m14000_sxx (KERN_ATTR_RULES ())

{
...

    _des_crypt_keysetup (c, d, Kc, Kd, s_skb);

    u32 data[2];

    data[0] = salt_buf0[0];
    data[1] = salt_buf0[1];

    u32 iv[2];

    _des_crypt_encrypt (iv, data, Kc, Kd, s_SPtrans);

    /**********which i add***********/
 
    u32 data1[2];

    data1[0] = iv[0];
    data1[1] = iv[1];

    u32 iv1[2];

    _des_crypt_encrypt (iv1, data1, Kc, Kd, s_SPtrans);

    /*********************/
    u32 z = 0;

    COMPARE_M_SIMD (iv1[0], iv1[1], z, z);
...

}




it.is.xuwei@gmail.com
 
From: kgolawski
Date: 2021-01-13 20:13
To: hashcat/hashcat
CC: Indawn; Author
Subject: Re: [hashcat/hashcat] des encrypted twice, where or which file should i edit to take effect, please (#2682)
What you want to achieve?
What changes have you implemented?

**Comment by jsteube** [comment]
The patch should be ok, you probably just forgot to delete the cached kernel. Feel free to reopen if that did not fix the issue.
