### ISSUE TITLE
terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by dipanshparmar** [hashcat/hashcat#2684]
**Version 6.1.1**
**Fish**
![image](https://user-images.githubusercontent.com/49204837/104406020-4ebd3980-5584-11eb-926a-652e0509fe42.png)

**Bash**
![image](https://user-images.githubusercontent.com/49204837/104408321-cf326900-5589-11eb-8690-c5d019cb4746.png)

can anyone confirm this?

**Comment by ventaquil** [comment]
Which OS? Devices? Drivers? Can you give more details?

**Comment by dipanshparmar** [comment]
**OS**: Garuda Linux (based on arch)
**Hardware**: AMD Ryzen 5 3500U with Integrated graphics.

Before I was getting an error for openCL and after installing **openCL-amd** I am getting this error.

**Comment by dipanshparmar** [comment]
@ventaquil please let me know if you need any other info.

**Comment by ventaquil** [comment]
I am using `rocm-*` packages on Ubuntu (like `rocm-opencl` or `rocm-dkms`). As far as I see there are ROCm packages for Arch. Have you tried them?

Can you build Hashcat in debug mode and check when program crashes?

**Comment by dipanshparmar** [comment]
@ventaquil I was not sure how to start the debug mode, so this is how I did it.
![image](https://user-images.githubusercontent.com/49204837/104470667-f6b42080-55df-11eb-8355-36f3c97a0c36.png)

**Comment by ventaquil** [comment]
Build using `DEBUG=1` firstly

```shell-session
$ make distclean
rm -f hashcat
rm -f libhashcat.so.6.1.1
rm -rf modules/*.dSYM
rm -f modules/*.dll
rm -f modules/*.so
rm -f obj/*/*/*.o
rm -f obj/*/*.o
rm -f obj/*.o
rm -f obj/*.a
rm -rf *.dSYM
rm -f *.dylib
rm -f *.bin *.exe
rm -f *.pid
rm -f *.log
rm -f core
rm -rf *.induct
rm -rf *.outfiles
rm -rf kernels
rm -f *.restore
rm -f *.potfile
rm -f *.out
rm -f hashcat.dictstat2
rm -f brain.*
rm -rf test_[0-9]*
rm -rf tools/luks_tests
$ make -j$(nproc) DEBUG=1
...
```

Then use GDB for example to check what is going on
```
$ gdb hashcat
Reading symbols from hashcat...
(gdb) b src/main.c:1182
Breakpoint 1 at 0x55555555bdfb: file src/main.c, line 1182.
(gdb) run --benchmark --force
Starting program: /home/ventaquil/Git/hashcat/hashcat --benchmark --force
...
Thread 1 "hashcat" hit Breakpoint 1, main (argc=3, argv=0x7fffffffe698) at src/main.c:1182
1182	      rc_final = hashcat_session_execute (hashcat_ctx);
(gdb) list
1177	
1178	      backend_info_compact (hashcat_ctx);
1179	
1180	      user_options_info (hashcat_ctx);
1181	
1182	      rc_final = hashcat_session_execute (hashcat_ctx);
1183	    }
1184	  }
1185	
1186	  // finish the hashcat session, this shuts down backend devices, hwmon, etc
```

You don't need to set breakpoint at `src/main.c`, it's only an example.

Using `run` you can use your flags: `run -m 0 d6a5ab88370340f2bf2dd5fd3d11d049 /usr/share/wordlists/rockyou.txt`.
Debugger should show where program has problem. Use `list` command to see code around.

How about ROCm drivers?

**Comment by dipanshparmar** [comment]
@ventaquil I installed ROCm drivers and now this is what I am getting. I still can not make it work properly.

![image](https://user-images.githubusercontent.com/49204837/104506441-6a1f5780-560b-11eb-8007-e85c9f50a44f.png)

**Comment by matrix** [comment]
Hi, you need to remove Mesa. Check the hashcat forum for this kind of issue.
Thanks

**Comment by dipanshparmar** [comment]
@matrix I uninstalled OpenCL-mesa and now this warning is gone.
![image](https://user-images.githubusercontent.com/49204837/104543685-0b2e0280-564c-11eb-9d5c-b314576c5d45.png)

But this one is still there.
![image](https://user-images.githubusercontent.com/49204837/104543723-1ed96900-564c-11eb-9c4b-5c38b21ee790.png)

**Comment by roycewilliams** [comment]
@matrix - could you elaborate in the thread here? 

https://hashcat.net/forum/thread-9774.html

This one is new to me - I looked for relevant threads and couldn't find any.

**Comment by ZerBea** [comment]
from here:
https://github.com/RadeonOpenCompute/ROCm

```
Supported GPUs
Because the ROCm Platform has a focus on particular computational domains, we offer official support for a selection of AMD GPUs that are designed to offer good performance and price in these domains.

Note: The integrated GPUs of Ryzen are not officially supported targets for ROCm.
```

**Comment by matrix** [comment]
@dipanshparmar, please post the output of hashcat -I

**Comment by dipanshparmar** [comment]
@matrix I switched back to kali and it is working fine now.

**Comment by matrix** [comment]
ok, please close the issue. Thanks

**Comment by dipanshparmar** [comment]
Thanks everyone for your help

**Comment by md1440** [comment]
I am running in the same error code on Arch Linux even some hashcat -I looks good and recognizes the card correctly.

hashcat (v6.2.6-846-g4d412c8e0+) starting in backend information mode

hipInit(): 100

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version.: OpenCL 2.1 LINUX

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Version........: OpenCL 2.1 (Build 0)
    Processor(s)...: 12
    Clock..........: 2600
    Memory.Total...: 31954 MB (limited to 3994 MB allocatable in one block)
    Memory.Free....: 15945 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 18.1.0.0920

OpenCL Platform ID #2
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.1 AMD-APP (3380.4)

  Backend Device ID #2
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: AMD Radeon RX 560 Series
    Version........: OpenCL 2.0 AMD-APP (3380.4)
    Processor(s)...: 16
    Clock..........: 1199
    Memory.Total...: 4096 MB (limited to 3481 MB allocatable in one block)
    Memory.Free....: 3968 MB
    Local.Memory...: 64 KB
    OpenCL.Version.: OpenCL C 2.0 
    Driver.Version.: 3380.4 (PAL,HSAIL)
    PCI.Addr.BDF...: 01:00.0
