### ISSUE TITLE
[BUG] in POT-Parser for ALL entries -> hash:[salt:]pwpart1:pwpart2

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#2686]
Hashcat-Forum Link
https://hashcat.net/forum/thread-9768.html

i found a bug in the potfile-parser for entries like this

`hash:salt:pw-part1:pw-part2`

where the `:` is part of already found/known password

using a potfile eg.  with 100 entries, with an entry like this, results in hashcat only recognizing 99 entries, resulting in "recracking" the already known password, resulting in a second, third, fourth and so on... entry, duplicate entry

my potfile is hashtype specific, so with a little help of `sort, uniq -c and regex` i can tell you the following, the error (probably) occurs only in this specific style of entry, described obove, reasons:

`:` inside/outside a salt seems to work normally because i found this entry-style multiple times (but with uniq entries)
 
```
hash:salt-part1:salt-part2:password
hash:salt-part1::salt-part2:password
hash:salt-part1:salt-part2::password
hash::salt-part1:salt-part2:password
```
Hashtype is 2811, dont know wheter or not the saltsize is fixed for this hash or how your parser splits these specific entries, but the error should be located there?

**UPDATE** BUG affects all passwords with an : in it
added a simple test with plain md5, test-password was
`test1:test1`
same behavior, hashcat cannot recognize this plaintext-password in pot-file, resulting in recracking it again and again
potfile after 3 runs
`723210cefac9372c968e5bfd98cb022b:test1:test1`
`723210cefac9372c968e5bfd98cb022b:test1:test1`
`723210cefac9372c968e5bfd98cb022b:test1:test1`

md5 and i think all other hashes are fixed in size so everything after the first : should be parsed as password, which doesnt seem to happen, in the code for module0 i found
`token.len_min[0] = 32;
  token.len_max[0] = 32;`
so i think the length of md5 is already fixed, but i dont know where to look now (oufile, potfile?)

**Comment by matrix** [comment]
hi, can you kindly describe how to reproduce the issue? Thanks

**Comment by realSnoopy** [comment]
well i thought my report was quite okay but i will try 

im cracking on some old data for basic statistic research (pw-length, used chars used special chars, and so on)
using bf, dictionary attacks, different rules and so on, after a couple of sessions i have a quite good potfilefile for this dataset (~65% cracked) and in my afterwards auto generated statistic-file i noticed some "misbehavior" in some of the generated counts (for example pw -> uniq-pw)

hashcat 6.1.1
hashmode 2811 (hash:salt)

actual data (counts,no sensitive data)
after last session 
`Recovered........: 51487/79484 (64.78%)`

when restarting hashcat with same settings
`Recovered........: 51486/79484 (64.78%)`
**please notice the one missing password, i didnt noticed this for quite some time**

so i made some checks on my potfile and noticed duplicate entries on the end with this format
`hash:salt:crackedpw-part1:crackedpw-part2`
`hash:salt:crackedpw-part1:crackedpw-part2`
both entries are exactly the same! please notice the `third :` inside the cracked password

so i digged a litte more with
`sort potfile.pot | uniq -c | sort -nr | head`
`15 hash:salt:crackedpw-part1:crackedpw-part2`
`1 hash:salt:pw`
`1 hash:salt:pw`
`...`

so i cracked this hash:salt already `15` times without noticing, because hashcat cannot regognize this ONE special entry style in the potfile, other entries with more than `2 :` are recognized correct because i found multiple, but uniq entries with following formats in my potfile
**double :: are no typo!!!**
`hash:salt-part1:salt-part2:password`
`hash:salt-part1::salt-part2:password`
`hash:salt-part1:salt-part2::password`
`hash::salt-part1:salt-part2:password`

these entries are all uniq and recognized correct, so the problem seems to be the `third :` inside the cracked password.

**Comment by matrix** [comment]
Ok for the explanation, but if i can't replicate the problem i can't even figure out how to fix it. If you share the associated hash(es) and password(s) we can try to debug.

**Comment by realSnoopy** [comment]
Ah okay, is it allowed to share this one particular hash:salt and pw here in the comments? i think in hashcat-forum it was only allowed in private messages. i dont really care, but i dont want to get banned, **EDIT:** plain-pw is quite "standard and not sensitive" so see below

**EDIT 2:**
when preparing this single dataset for you i noticed another thing. the problem occurs with option `--outfile-autohex-disable`, without this option the cracked pw and entry are recognized correct

i prepared the following dataset

bad-hash.txt # the bad hash:salt combo
bad-pot.pot # single bad entry potfile generated `with `option `--outfile-autohex-disable`
bad-good.pot # potfile generated afterwards `without` option  `--outfile-autohex-disable`  where the "cracked" pw is in hex and afterwards recognized correct
bad-pw.txt  # the bad pw in plain text

How to replicate: (please mind, files are from a windows host)

`hashcat -a 0 -m 2811 --potfile-path bad-pot.pot --outfile-autohex-disable bad-hash.txt bad-pw.txt`
RESULT
second entry with "cracked" pw in bad-pot.pot -> restarting hashcat again not recognizing the entry, resulting in a third entry and so on

`hashcat -a 0 -m 2811 --potfile-path bad-pot.pot  bad-hash.txt bad-pw.txt`
RESULT
entry with "cracked" pw in hexstyle, restarting hashcat again -> recognizing the entry correct

Dataset as 7z (dont found the possibility for private messages so...)
[dataset](https://drive.google.com/file/d/1MKPf6s4NJd7oyz4ShjESOVj2z70JKnOL/view?usp=sharing)

**Comment by matrix** [comment]
> Ah okay, is it allowed to share this one particular hash:salt and pw here in the comments? i think in hashcat-forum it was only allowed in private messages. i dont really care, but i dont want to get banned, **EDIT:** plain-pw is quite "standard and not sensitive" so see below
> 
> **EDIT 2:**
> when preparing this single dataset for you i noticed another thing. the problem occurs with option `--outfile-autohex-disable`, without this option the cracked pw and entry are recognized correct
> 
> i prepared the following dataset
> 
> bad-hash.txt # the bad hash:salt combo
> bad-pot.pot # single bad entry potfile generated `with `option `--outfile-autohex-disable`
> bad-good.pot # potfile generated afterwards `without` option `--outfile-autohex-disable` where the "cracked" pw is in hex and afterwards recognized correct
> bad-pw.txt # the bad pw in plain text
> 
> How to replicate: (please mind, files are from a windows host)
> 
> `hashcat -a 0 -m 2811 --potfile-path bad-pot.pot --outfile-autohex-disable bad-hash.txt bad-pw.txt`
> RESULT
> second entry with "cracked" pw in bad-pot.pot -> restarting hashcat again not recognizing the entry, resulting in a third entry and so on
> 
> `hashcat -a 0 -m 2811 --potfile-path bad-pot.pot bad-hash.txt bad-pw.txt`
> RESULT
> entry with "cracked" pw in hexstyle, restarting hashcat again -> recognizing the entry correct
> 
> Dataset as 7z (dont found the possibility for private messages so...)
> [dataset](https://drive.google.com/file/d/1MKPf6s4NJd7oyz4ShjESOVj2z70JKnOL/view?usp=sharing)

If you post hashes to ask people help to crack it ... you will probably "banned".
But if you post hashes to help developers to address issue ... you probably do everyone a favor :)
As soon as possible I'll do some tests to verify the problem.
Thanks!

**Comment by matrix** [comment]
@realSnoopy with the git version I can't reproduce your issue. Please send the output of "hashcat -I".
Thanks

**Comment by realSnoopy** [comment]
**Edit 1**
a fast test with
v6.1.1-116-gfb219e0a6 from https://hashcat.net/beta/
same problem

**Edit 2**
Git-Version, compiled for Windows using WSL
same problem
hashcat -I
hashcat (v6.1.1-120-g15bf8b730) starting...

CUDA Info:
==========

CUDA.Version.: 11.1

Backend Device ID #1 (Alias: #2)
  Name...........: GeForce GTX 1050 Ti
  Processor(s)...: 6
  Clock..........: 1417
  Memory.Total...: 4096 MB
  Memory.Free....: 3376 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 1.2 CUDA 11.1.102

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: GeForce GTX 1050 Ti
    Version........: OpenCL 1.2 CUDA
    Processor(s)...: 6
    Clock..........: 1417
    Memory.Total...: 4096 MB (limited to 1024 MB allocatable in one block)
    Memory.Free....: 0 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 456.81

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) OpenCL
  Version.: OpenCL 2.0

  Backend Device ID #3
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz
    Version........: OpenCL 2.0 (Build 37)
    Processor(s)...: 48
    Clock..........: 2100
    Memory.Total...: 130722 MB (limited to 32680 MB allocatable in one block)
    Memory.Free....: 130658 MB
    OpenCL.Version.: OpenCL C 2.0
    Driver.Version.: 6.4.0.37

**Comment by realSnoopy** [comment]
**EDIT 3**
Git-Version compiled on/for Linux
same problem
hashcat (v6.1.1-120-g15bf8b730) starting...

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: The pocl project
  Name....: Portable Computing Language
  Version.: OpenCL 1.2 pocl 1.6, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 1
    Vendor.........: AuthenticAMD
    Name...........: pthread-AMD Athlon(tm) X4 950 Quad Core Processor
    Version........: OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-bdver4
    Processor(s)...: 4
    Clock..........: 3500
    Memory.Total...: 13975 MB (limited to 4096 MB allocatable in one block)
    Memory.Free....: 13911 MB
    OpenCL.Version.: OpenCL C 1.2 pocl
    Driver.Version.: 1.6

**Comment by realSnoopy** [comment]
okay learned, that --outfile-autohex-disable is a bad idea, so not a real bug
