### ISSUE TITLE
JTR Hex Rules not working on opencl?

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#2687]
Hashcat-Forum
https://hashcat.net/forum/thread-9777-post-51275.html

When trying answering to this https://hashcat.net/forum/thread-9773.html
i found this old/resolvded issue  https://github.com/hashcat/hashcat/issues/1580

hahscat wiki says, hashcat is 100% compatible with jtr rules but when trying to use a hex-rule like
`sa\xc3a4`
hashcat responds with

Cannot convert rule for use on OpenCL device in file ruletest.txt on line 1: sa\xc3a4

any ideas?

**Comment by jsteube** [comment]
Correct. Hashcat does not support utf8 in rules. The only workaround is to use the umlaut in a rule which is encoded as iso-8859-15 
 and put it into --stdout mode and then pipe it to a second instance of hashcat where you can do --encoding-from iso-8859-15. This is, however, not a rule engine problem.
