### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by nullfloppy** [hashcat/hashcat#2689]
Attempting to run hashcat bench in vmware pro 16, kali 2020.4 iso

`hashcat (v6.1.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 1.2 pocl 1.5, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
=============================================================================================================================
* Device #1: pthread-AMD Ryzen 9 5950X 16-Core Processor, 5824/5888 MB (2048 MB allocatable), 16MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

error: unknown target CPU 'generic'

* Device #1: Kernel /usr/share/hashcat/OpenCL/shared.cl build failed.

Started: Mon Jan 18 17:25:14 2021
Stopped: Mon Jan 18 17:25:14 2021
`

**Comment by matrix** [comment]
hi, it looks like a problem with POCL. Try looking on their github to see if and how to fix.
Thanks

**Comment by imp1sh** [comment]
did you find a fix for this?

**Comment by matanox** [comment]
Did you manage getting past this error?

**Comment by gfrancqu** [comment]
Having the same issue, any update ?

**Comment by hands-of-cat** [comment]
I could resolve this issue by using install.sh in opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz  according to the article below:
https://hashcat.net/forum/thread-9810.html

I downloaded tgz file below:
http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz

- Installer showed that my environment was lack of llvm 4.0.
- After installing, /etc/OpenCL/vendors/instel64.icd was created.

I hope this help you.

**Comment by tinyboxvk** [comment]
> 
> 
> I could resolve this issue by using install.sh in opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz according to the article below:
> https://hashcat.net/forum/thread-9810.html
> 
> I downloaded tgz file below:
> http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
> 
>     * Installer showed that my environment was lack of llvm 4.0.
> 
>     * After installing, /etc/OpenCL/vendors/instel64.icd was created.
> 
> 
> I hope this help you.

I can confirm this works. The latest version of OpenCL Runtime can be downloaded here:
https://www.intel.com/content/www/us/en/developer/tools/opencl-cpu-runtime/overview.html

**Comment by jsteube** [comment]
Thanks for update, indeed that's the way to go.

**Comment by GIJosh2687** [comment]
> > I could resolve this issue by using install.sh in opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz according to the article below:
> > https://hashcat.net/forum/thread-9810.html
> > I downloaded tgz file below:
> > http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
> > ```
> > * Installer showed that my environment was lack of llvm 4.0.
> > 
> > * After installing, /etc/OpenCL/vendors/instel64.icd was created.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this help you.
> 
> I can confirm this works. The latest version of OpenCL Runtime can be downloaded here: https://software.intel.com/content/www/us/en/develop/tools/opencl-cpu-runtime.html

This was the solution. I downloaded the file and ran the install_GUI.sh with sudo. Worked like a charm to fix my hashcat!

**Comment by 4akatun** [comment]
Thanks for the information, I had a problem on my laptop when using hashcat and thanks to the fact that I found this, I was able to solve it.

**Comment by Sorrow81** [comment]
Hello, I have the same problem. I solved it by installing the latest version of openCl.

To avoid wasting time to create an account on Intel to download OpenCL, I give you the link of the last version: 
```bash
cd /tmp/
wget https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
tar -xf l_opencl_p_18.1.0.015.tgz
cd l_opencl_p_18.1.0.015/
sudo ./install.sh
```
<details>
  <summary>Installation steps</summary>
  
Just follow these steps to install OpenCL 18.1.
  
![image](https://user-images.githubusercontent.com/43729314/191220627-fe74c6c6-e810-45c0-93b2-9c86e0e4cf02.png)
![image](https://user-images.githubusercontent.com/43729314/191220712-f73c3d0e-1071-4982-8f2b-3e6111fabfc1.png)
![image](https://user-images.githubusercontent.com/43729314/191220760-eb44e78a-7e85-4a4a-8a63-5bdd98fefdda.png)
![image](https://user-images.githubusercontent.com/43729314/191220812-7d0c87f8-9d8c-4817-acbd-4723032dd638.png)
![image](https://user-images.githubusercontent.com/43729314/191221078-5f63fc49-0d85-47d3-8f1a-6b7157adfa8a.png)
![image](https://user-images.githubusercontent.com/43729314/191221135-e90ceba6-c19c-44ed-86b6-ef78921cd511.png)

Enjoy
</details>

![image](https://user-images.githubusercontent.com/43729314/191222047-841459f2-dcef-48af-9869-2ee81e2b781c.png)

Thanks to all those who provided information that allowed me to solve the problem

**Comment by fcthevan123-vn** [comment]
> Hello, I have the same problem. I solved it by installing the latest version of openCl.
> 
> To avoid wasting time to create an account on Intel to download OpenCL, I give you the link of the last version:
> 
> ```shell
> cd /tmp/
> wget https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
> tar -xf l_opencl_p_18.1.0.015.tgz
> cd l_opencl_p_18.1.0.015/
> sudo ./install.sh
> ```
> 
> Installation steps
> ![image](https://user-images.githubusercontent.com/43729314/191222047-841459f2-dcef-48af-9869-2ee81e2b781c.png)
> 
> Thanks to all those who provided information that allowed me to solve the problem



> Hello, I have the same problem. I solved it by installing the latest version of openCl.
> 
> To avoid wasting time to create an account on Intel to download OpenCL, I give you the link of the last version:
> 
> ```shell
> cd /tmp/
> wget https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
> tar -xf l_opencl_p_18.1.0.015.tgz
> cd l_opencl_p_18.1.0.015/
> sudo ./install.sh
> ```
> 
> Installation steps
> ![image](https://user-images.githubusercontent.com/43729314/191222047-841459f2-dcef-48af-9869-2ee81e2b781c.png)
> 
> Thanks to all those who provided information that allowed me to solve the problem

I must login in github jutst say thank you to you <3

**Comment by 0xcyborg** [comment]
> # OCL_DEBUG) - Platform #1 [The pocl project]
> * Device [ERROR: cuMemsetD8() 1 #1](https://github.com/hashcat/hashcat/issues/1): pthread-AMD Ryzen 9 5950X 16-Core Processor, 5824/5888 MB (2048 MB allocatable), 16MCU
> 
> # Benchmark relevant options:
> * --optimized-kernel-enable
> 
> Hashmode: 0 - MD5
> 
> clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
> 
> error: unknown target CPU 'generic'
> 
> * Device [ERROR: cuMemsetD8() 1 #1](https://github.com/hashcat/hashcat/issues/1): Kernel /usr/share/hashcat/OpenCL/shared.cl build failed.
> 
> Started: Mon Jan 18 17:25:14 2021 Stopped: Mon Jan 18 17:25:14 2021 `

Thank you

**Comment by sk03d** [comment]
> I could resolve this issue by using install.sh in opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz according to the article below: https://hashcat.net/forum/thread-9810.html
> 
> I downloaded tgz file below: http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
> 
> * Installer showed that my environment was lack of llvm 4.0.
> * After installing, /etc/OpenCL/vendors/instel64.icd was created.
> 
> I hope this help you.

This solution works completely fine...go with it guys

if there is error in opening link try using this:

registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
