### ISSUE TITLE
[FR] Support of pbkdf2 hmac sha512

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#2690]
Hi,
Feature Request - Support of pbkdf2-hmac-sha512 (especially used in OSX 10.11)

```
$ python ml2john.py user.plist   # same result with mac2john.py
user:$pbkdf2-hmac-sha512$23708.18a9xxxxxxxxx
```
Existing OSX mode 7100 $ml$ does not fit.

It is also used by the newer version of Telegram Desktop algorithm (hashcat currently supports PBKDF2-HMAC-**SHA1** but newer version uses PBKDF2-HMAC-**SHA512**)

So I guess it is useful for several algorithms - so far I spotted OSX and Telegram, but more to come I guess.

Thanks!

**Comment by Banaanhangwagen** [comment]
Hashcat already supports `pbkdf2-hmac-sha512`. 

If you want to use mode 7100, make sure your hash is formatted in the correct way as found [here](https://hashcat.net/wiki/doku.php?id=example_hashes).
I suggest you use another tool for extracting the macOS-hash, for example [this one](https://gist.github.com/nueh/8252572).

Also, you make the suggestion to support newer Telegram Desktop. This work is already done, but only needs to be reviewed and merged by the developer. [Link ](https://github.com/hashcat/hashcat/pull/2583)to merge request. 

If you think your questions are answered, please close this issue.

**Comment by adrastee** [comment]
> I suggest you use another tool for extracting the macOS-hash, for example this one.

Awesome, it works great.
Thanks!
