### ISSUE TITLE
-m9800 has the following error under rtx3090, but not under 1080ti.

### ISSUE THREAD

**Issue by gs135269** [hashcat/hashcat#2694]
-m9800 has the following error under rtx3090, but not under 1080ti.

cuLinkAddData(): the provided PTX was compiled with an unsupported toolchain.

* Device #1: Kernel ./OpenCL/shared.cl link failed. Error Log:

ptxas application ptx input, line 9; fatal: Unsupported .version 7.2; current version is '7.1'

* Device #1: Kernel ./OpenCL/shared.cl build failed.

Hash: $oldoffice$3*972fa5775b4980a297ff7022aad14db4*fc8b23a5d28328347c4e7750d143f906*caf69704202c9dfa7e7d4209b656f31e7052be95

**Comment by matrix** [comment]
Hi, probably you update cuda but not the driver.

https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by gs135269** [comment]
@matrix Thank you very much for your help, the problem has been resolved. I will close this issue. In the future, we will pay attention to the association between cuda and the driver version.
