### ISSUE TITLE
[Request algo] Stuffit 5 Archive Password

### ISSUE THREAD

**Issue by gregesposito** [hashcat/hashcat#2698]
I'd love for Hashcat to support the Stuffit 5 Archive Password algorithm, used to password protect .SIT files, most commonly seen on Macintosh computers in the late 90s and early 2000s. Stuffit was the main archive utility used on Macs until Apple adopted .ZIP archives with Mac OS X. While there are at least 4 types of Stuffit password types (the original 80s version 1, the early 90s version 4, the mid 90s to early 2000s Stuffit 5, and the early 2000s Stuffit X), this request is just for Stuffit 5 which was by far the most common (based on timeline/marketshare/user requests). If successful, I'd love to engage with you on Stuffit 4 as well.

Based on code from TheUnarchiver (https://github.com/incbee/Unarchiver/blob/28a2330b16139f6d074cdf75ea34eee0ccd218c4/XADMaster/XADStuffIt5Parser.m) I was able to decode the format to be a custom dual MD5 function that returns a binary MD5 hash of the password, then takes the first 5 characters of the result and returns a hexadecimal MD5 hash. This resulting MD5 hash is then chopped off at the tenth character and used in the archive.

I am not a professional programmer, so forgive my incorrect use of terms.

Years ago, I had asked about adding this format to Hashcat https://hashcat.net/forum/thread-1558.html but this was before the plugin era. I then embarked on continuing to do it solo.

I have been able to distill (and optimize, thanks to StackOverflow https://stackoverflow.com/questions/41797566/optimizing-bitshift-into-array) the code into a simple program that accepts passwords from Hashcat's maskprocessor tool and runs it against the algorithm, and on an 8086k I benchmark about 4.4M tries a second, which when ran in parallel allows me to almost always get a hit within a few days. My code is available here : https://github.com/gregesposito/kasper5
![kasper5-8086k-4 3M](https://user-images.githubusercontent.com/8727407/105900935-b5ae0a00-5fea-11eb-98dc-66cb205947ea.PNG)
A quick overview of the meat and potatoes of the algorithm is here:
```
/* Start - MD5 Round 1 */

   unsigned char digest[16];
    char string2[5];	 

	MD5_CTX ctx;
	MD5_Init(&ctx);
	MD5_Update(&ctx, string, strlen(string));
	MD5_Final(digest, &ctx);

	/* End - MD5 Round 1 */
 
	/* Start - MD5 Round 2 */

// Set the string to the second MD5 hash of the first 5 characters (10 bit)
	memcpy(string2, digest, 5);

	MD5_Init(&ctx);
	MD5_Update(&ctx, string2, 5);
	MD5_Final(digest, &ctx);

    char mdString3[10]; 

	char *hexStr = "0123456789abcdef";

	mdString3[0] = hexStr[(digest[0] >> 4) & 0xf];
	mdString3[1] = hexStr[(digest[0]) & 0xf];
	mdString3[2] = hexStr[(digest[1] >> 4) & 0xf];
	mdString3[3] = hexStr[(digest[1]) & 0xf];
	mdString3[4] = hexStr[(digest[2] >> 4) & 0xf];
	mdString3[5] = hexStr[(digest[2]) & 0xf];
	mdString3[6] = hexStr[(digest[3] >> 4) & 0xf];
	mdString3[7] = hexStr[(digest[3]) & 0xf];
	mdString3[8] = hexStr[(digest[4] >> 4) & 0xf];
	mdString3[9] = hexStr[(digest[4]) & 0xf];
	
	/* End - MD5 Round 2 */

	/* Start - Hash Check */
for(int i = 1; i < argc; i++) {

	if (memcmp(mdString3, argv[i], 10) == 0){
			printf("Success at: %s", string);
			double end = std::clock();
			duration = (end - start) / (double)CLOCKS_PER_SEC;
			double linespersec = linecount/duration;
	std::cout << fixed << setprecision(0) << " for " << argv[i] << " in " << duration << " seconds at line " << linecount << " (" << linespersec << " l/s)\n";
    }
}
  }
    /* End - Hash Check*/
```

While this format is a dead format, I personally get many requests from users asking to run my tool to recover passwords. Maskprocessor and my tool together is too much for normal users indeed. Here on my site, you can see comments over the years about receiving assistance, and for these users I've been a great help : https://www.kiwidget.com/kasper-stuffit-5-password-recovery/ I believe adding this to a tool that has wide use will be a great help in allowing new people to handle the archives, versus having to reach out to me. Personally, I believe adding this would be something the users of the Macintosh Repository / Macintosh Garden (https://www.macintoshrepository.org/ and https://macintoshgarden.org/) would find valuable, as they run into old software archives and old user archives protected by this algorithm.

As a truncated MD5 derivative, the possibility of hash collisions occurring which are not the original password do happen. These collisions do indeed work on the archives (99% of the time- perhaps some special characters could fail it)

Attached are example hashes, both ones with collisions that work regardless of original password, and a list of examples I had found, verified, and resolved.

[stuffit5-hash-collision-examples.txt](https://github.com/hashcat/hashcat/files/5875885/stuffit5-hash-collision-examples.txt)
[stuffit5-example-passwords-and-hash.txt](https://github.com/hashcat/hashcat/files/5875889/stuffit5-example-passwords-and-hash.txt)

I can try to provide any further data as possible, but between the original source code base from TheUnarchiver, my code on Github, and my discussions on my blog about speeds, this represents almost the sum of my knowledge on the topic.

Thanks for your consideration.

**Comment by jsteube** [comment]
Hash-Mode was merged with PR https://github.com/hashcat/hashcat/pull/2702
