### ISSUE TITLE
Сombinator mode for small left dictionary

### ISSUE THREAD

**Issue by elplum** [hashcat/hashcat#2701]
Tested in mode 12700

hashcat -a 1 -m 12700 hash.txt LARGEdictionary.txt SMALLdictionary.txt
~1000 Mh/s

LARGEdictionary.txt <-> SMALLdictionary.txt

hashcat -a 1 -m 12700 hash.txt SMALLdictionary.txt LARGEdictionary.txt
~0,5 Mh/s (!)

**Comment by oam7575** [comment]
Sounds like a workload optimization issue.

Have you tried adding -w 3 and -O to your cmd line ?

Some quick testing on my side with a modest GTX1660ti went from ~18000 Kh to ~300Mh depending on word lists and tuning.

**Comment by jsteube** [comment]
In pure kernel mode hashcat needs to distribute the words from the left wordlist to the GPU shaders. Only in optimized mode  hashcat can select the larger one as the source for the distribute. Note that -m 12700 supports pure kernel mode only.

**Comment by jsteube** [comment]
As a workaround, you might want to use rules and convert the words from the smaller left wordlist into rules. These can be applied with high performance also in pure kernel mode.
