### ISSUE TITLE
What happened to the author of this project?

### ISSUE THREAD

**Issue by patric-r** [hashcat/hashcat#2705]
While being constantly active for several years almost on a daily basis (thank you!),
the author and main contributor of this project jsteube
stopped contributing anything since October 2020:

https://github.com/jsteube

Additionally, he did not login to the hashcat forum since that time.

Are there any news which I  have missed?
Let's cross our fingers that nothing severe has happened.

**Comment by roycewilliams** [comment]
I believe Jens has just been extremely busy with non-hashcat work. Chick3nman's heard from him in the past couple of weeks.

**Comment by jsteube** [comment]
Hey there, thanks for asking @patric-r and for answer @roycewilliams. Indeed I am busy with non-hashcat work, but I am fine. I will return to hashcat after other project is finished.
