### ISSUE TITLE
Hash_Hmac Question

### ISSUE THREAD

**Issue by fantasy04** [hashcat/hashcat#2707]
Dear Support,

Is it possible for hashcat to crack something like this:

hash_hmac(PASSWORD_HASH_ALGOS, $str . ":" . AUTH_MAGIC, $salt);
php -r '$hash=hash_hmac("sha256","your_passwd:hogehoge","saltishere");var_dump($hash);'
string(64) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

if we forget the Auth_Magic?

Supposed we have only SHA256 and Salt?

Thanks and appreciate your inputs and comments,

**Comment by jsteube** [comment]
Yes, but only if the auth_magic is a password or not too long to bf (max 8 char). However, this is not a question suitable to GitHub issues, please use hashcat forum instead.
