### ISSUE TITLE
hashcat does not start

### ISSUE THREAD

**Issue by raidz2** [hashcat/hashcat#2710]
whenever i enter in ` hashcat -m 0 -o -a 0 cracked-passwords.txt target-hashes.txt list.txt`
it outputs:

```
hashcat (v5.1.0) starting...

/usr/bin/hashcat.pid: Permission denied

/usr/bin/hashcat.induct: Permission denied

(null): Bad address
```
i am on ubuntu 20.04

**Comment by roycewilliams** [comment]
Hot take: likely to need to be handled by the package maintainer. Compiled from source, hashcat does not try to write to /usr/bin.

**Comment by oam7575** [comment]
Installing Hashcat 5.1.0 on Ubuntu 20.04 via apt appears to execute correctly.

Suggest closing issue

**Comment by jsteube** [comment]
Also super outdated version
