### ISSUE TITLE
Methods 23700 and 23800 missing from the hashcat binaries

### ISSUE THREAD

**Issue by iasenko** [hashcat/hashcat#2711]
I don't know why but both methods 23700 and 23800 are missing from the official binaries and sources. 
Where can I find those method dll files?

**Comment by Banaanhangwagen** [comment]
As you can read on https://hashcat.net/wiki/doku.php?id=example_hashes, those modes are not yet officially released.
Please use a beta (https://hashcat.net/beta/) or compile from Github.

If this is an answer to your question, please close the issue.
