### ISSUE TITLE
Arch linux Segmentation fault.

### ISSUE THREAD

**Issue by RumoEL** [hashcat/hashcat#2714]
in gdb with peda lib:
hashcat -b -D 2 --force
0x00007fffe2e8a2b6 in llvm::TargetInstrInfo::getNoop(llvm::MCInst&) const () from /usr/lib/libLLVM-11.so

hashcat -I in [log.txt](https://github.com/hashcat/hashcat/files/6024230/log.txt)

**Comment by ZerBea** [comment]
Looks like a pocl issue. You should report it here:
https://github.com/pocl/pocl/issues

Please notice that pocl is not recommended by hashcat team:
https://github.com/hashcat/hashcat/issues/1703

**Comment by RumoEL** [comment]
i removed pocl:
![Screenshot_20210310_101259](https://user-images.githubusercontent.com/76575360/110614004-caed8b00-8189-11eb-9785-0dd3828a3c06.png)


[log.txt](https://github.com/hashcat/hashcat/files/6114992/log.txt)

**Comment by ZerBea** [comment]
Here is the next issue, you ran into:
OpenCL API (OpenCL 1.1 Mesa 20.3.4) - Platform #1 [Mesa]

Neither MESA nor POCL are recommended to be used in combination with hashcat.

The recommended drivers for hashcat are:
NVIDIA cards:
https://archlinux.org/packages/extra/x86_64/nvidia/
https://archlinux.org/packages/community/x86_64/cuda/

AMD cards
https://aur.archlinux.org/packages/?O=0&K=rocm

INTEL CPU (integrated GPU) and AMD CPU
https://archlinux.org/packages/community/x86_64/intel-compute-runtime/

Also you should not use --force.
From your log file:
"You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force."


BTW:
I'm running Arch Linux (on all my systems), too.

**Comment by RumoEL** [comment]
[user@archlinux ~]$ pacman -Q |grep -i opencl 
intel-opencl-clang 11.0.0-2
lib32-opencl-mesa 20.3.4-3
opencl-clhpp 2.0.13-1
opencl-headers 2:2020.12.18-1
opencl-mesa 20.3.4-3

[user@archlinux ~]$ pacman -Q |grep -i intel-compute-runtime
intel-compute-runtime 20.48.18558-1

hashcat -b
Device #1: Unstable OpenCL driver detected!

**Comment by RumoEL** [comment]
how to remove mesa)? completely, I have 1 more program stopped working with mesa drivers
Linux archlinux 5.11.4-arch1-1 #1 SMP PREEMPT Sun, 07 Mar 2021 18:00:49 +0000 x86_64 GNU/Linux

Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Thames [Radeon HD 7500M/7600M Series]

**Comment by ZerBea** [comment]
There is no need to remove mesa completely:
$ pacman -Q | grep mesa
mesa 20.3.4-3

Just remove the mesa opencl part 

This warning is "normal":
Device #1: Unstable OpenCL driver detected!
Because the intel runtime is not very stable, but much better than pocl and mesa.

This card is very old and not supported by rocm:
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Thames [Radeon HD 7500M/7600M Series]

If the intel runtime doesn't support your CPU/iGPU, please consider to report the MESA issue on their git, too:
https://gitlab.freedesktop.org/mesa

**Comment by RumoEL** [comment]
sudo pacman -R $(pacman -Q | grep mesa|grep --color -E "^.*\ " -o|tr "\n" " ")

:: removing mesa breaks dependency 'mesa' required by gst-plugins-base-libs
:: removing mesa breaks dependency 'mesa' required by gtk3
:: removing lib32-mesa breaks dependency 'lib32-mesa' required by lib32-libglvnd
:: removing lib32-mesa breaks dependency 'lib32-opengl-driver' required by lib32-libglvnd
:: removing mesa breaks dependency 'mesa' required by libglvnd
:: removing mesa breaks dependency 'mesa' required by minecraft-launcher
:: removing mesa-demos breaks dependency 'mesa-demos' required by playonlinux
:: removing mesa breaks dependency 'mesa' required by qt5-base
:: removing mesa breaks dependency 'mesa' required by virglrenderer
:: removing lib32-mesa breaks dependency 'lib32-mesa' required by wine-nine
:: removing mesa breaks dependency 'mesa' required by xf86-video-amdgpu
:: removing mesa breaks dependency 'mesa' required by xf86-video-ati
:: removing mesa breaks dependency 'mesa' required by xf86-video-intel
:: removing mesa breaks dependency 'mesa' required by xf86-video-nouveau
:: removing mesa breaks dependency 'mesa' required by xf86-video-vmware
:: removing mesa breaks dependency 'mesa' required by xorg-server-devel

**Comment by ZerBea** [comment]
There is no need to remove mesa completely due to it's dependencies.
Just remove the opencl part: opencl-mesa

Than test if your CPI/iGPU is supported by the intel compute runtime.

**Comment by RumoEL** [comment]
i removed* lib32-opencl-mesa-20.3.4-3  opencl-mesa-20.3.4-3
get:

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL or CUDA runtime installation.

* AMD GPUs on Linux require this driver:
  "RadeonOpenCompute (ROCm)" Software Platform (3.1 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)

**Comment by ZerBea** [comment]
Now we know that non of your hardware parts are supported by the recommended drivers.
Neither your CPU nor your GPU satisfy the requirements of the new drivers and you really need POCL or MESA.
BTW:
Do you use hashcat from the Arch repo
https://archlinux.org/packages/community/x86_64/hashcat/

or from latest git head?
$ hashcat --version
v6.1.1-120-g15bf8b730

**Comment by ZerBea** [comment]
Are the opencl-headers installed?
$ pacman -Q | grep ocl
ocl-icd 2.2.14-1

$ pacman -Q | grep opencl
opencl-headers 2:2020.12.18-1

**Comment by RumoEL** [comment]
pacman -Q | grep ocl
lib32-ocl-icd 2.2.14-1
ocl-icd 2.2.14-1

pacman -Q | grep opencl
intel-opencl-clang 11.0.0-2
opencl-clhpp 2.0.13-1
opencl-headers 2:2020.12.18-1

**Comment by ZerBea** [comment]
That looks fine. Now we can try the last thing (than I'm running out of ideas):
Compile hashcat from latest git head with option DEBUG=1
I'm sure the issue will be seen in the mesa libraries here, too.
The list of mesa issues is long:
https://hashcat.net/forum/thread-8384.html?highlight=mesa

**Comment by RumoEL** [comment]
how compile with flag ?

like ?:
export DEBUG=1
make

**Comment by ZerBea** [comment]
First reinstall opencl-mesa, because you it looks like your hardware isn't working on latest drivers.
Than compile hashcat with debug options:
$ make DEBUG=1
During compiling you'll see something like this:
"g++ -c  -W -Wall -Wextra -DDEBUG -Og -ggdb ...."

When finished, run your commandline again.

I'm sure, we'll see that the issue is located in mesa libraries.

**Comment by RumoEL** [comment]
with opencl-mesa:
Device #1: Unstable OpenCL driver detected!

without :

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
ATTENTION! No OpenCL-compatible or CUDA-compatible platform found

**Comment by RumoEL** [comment]
maybe it's in the /etc/mkinitcpio.conf config?

cat /etc/mkinitcpio.conf|grep -v \#
MODULES=(i915 radeon)
BINARIES=()
FILES=()
HOOKS=(base consolefont keymap  udev systemd autodetect modconf block filesystems sd-encrypt keyboard fsck)

**Comment by ZerBea** [comment]
No.
Running this "MODULES=(i915 radeon)", the specified modules are loaded before any boot hooks are run.

This mean, that none of the latest drivers will work on your hardware:
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
ATTENTION! No OpenCL-compatible or CUDA-compatible platform found

and you need mesa:
Device #1: Unstable OpenCL driver detected!

Unfortunately mesa is unstable and running into the segmentation fault issue.
https://hashcat.net/forum/thread-5652-post-30375.html#pid30375

Running hashcat (compiled with DEBUG=1) will confirm this.
This is a typical MESA error:
0x00007fffe2e8a2b6 in llvm::TargetInstrInfo::getNoop(llvm::MCInst&) const () from /usr/lib/libLLVM-11.so

**Comment by RumoEL** [comment]
now https://github.com/hashcat/hashcat/issues/2714#issuecomment-795190487

**Comment by ZerBea** [comment]
As assumed, you're running into a MESA issue that has to be fixed be MESA developers.
I don't think that it can be done by a hashcat workaround.

**Comment by ZerBea** [comment]
I have one (the last idea). Please try john:
```
$ john --test --mask=?d?d?d?d --format=Raw-MD5-opencl
Note: Self-tests currently not performed when using --mask with --test
Device 1@test1: GeForce GTX 1080 Ti
Benchmarking: raw-MD5-opencl (length 4) [MD5 OpenCL/mask accel]... DONE
Raw:	16463M c/s real, 16384M c/s virtual, Dev#1 util: 100%
```
If you run into the same issue, we can be sure it is within MESA libs.

**Comment by ZerBea** [comment]
Running hashcat using a non bugged driver will work as expected (e.g. on my notebook - RYZEN CPU, NVIDIA GPU):
```
$ uname -r
5.11.2-arch1-1

$ hashcat -m 0 --benchmark
hashcat (v6.1.1-120-g15bf8b730) starting in benchmark mode...

CUDA API (CUDA 11.2)
====================
* Device #1: GeForce GTX 1650, 3855/3911 MB, 16MCU

OpenCL API (OpenCL 1.2 CUDA 11.2.153) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: GeForce GTX 1650, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 0 - MD5

Speed.#1.........: 10411.7 MH/s (50.62ms) @ Accel:64 Loops:512 Thr:1024 Vec:1

Started: Thu Mar 11 09:39:39 2021
Stopped: Thu Mar 11 09:39:49 2021
```

**Comment by RumoEL** [comment]
john:

Device 1@archlinux: AMD TURKS (DRM 2.50.0 / 5.11.4-arch1-1, LLVM 11.1.0)
Benchmarking: raw-MD5-opencl (length 4) [MD5 OpenCL/mask accel]... Options used: -I /usr/share/john/kernels -cl-mad-enable -D__MESA__ -D__GPU__ -DDEVICE_INFO=522 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=20 -DDEV_VER_MINOR=3 -D_OPENCL_COMPILER -D OFFSET_TABLE_SIZE=12 -D HASH_TABLE_SIZE=7 -D SHIFT64_OT_SZ=4 -D SHIFT64_HT_SZ=2 -D NUM_LOADED_HASHES=6 -D NUM_INT_KEYS=1000 -D SELECT_CMP_STEPS=4 -D BITMAP_SIZE_BITS_LESS_ONE=32767 -D USE_LOCAL_BITMAPS=1 -D IS_STATIC_GPU_MASK=1 -D CONST_CACHE_SIZE=751619276 -D LOC_0=0 -D LOC_1=1 -D LOC_2=2 -D LOC_3=-1 /usr/share/john/kernels/md5_kernel.cl
Build log: input.cl:271:18: warning: unknown attribute 'max_constant_size' ignored [-Wunknown-attributes]
<unknown>:0:0: in function md5 void (i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(4)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*, i32 addrspace(1)*): unsupported call to function md5_encrypt

Error building kernel /usr/share/john/kernels/md5_kernel.cl. DEVICE_INFO=522
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram

**Comment by ZerBea** [comment]
As expected, the issue is not located in hashcat.
The good news: LLVM 12.0 should be released, soon:
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-12.0-RC3-Released

**Comment by RumoEL** [comment]
close the thread

**Comment by ZerBea** [comment]
I recommend to report your issue either to Arch Linux bug tracker or directly to upstream bug tracker,
e.g. as we did it with NVIDIA issues:
https://bugs.archlinux.org/task/68312
