### ISSUE TITLE
sha512($salt.md5($password)) Support

### ISSUE THREAD

**Issue by jj2hh2hasdf** [hashcat/hashcat#2717]
Looking for someone to make sha512($salt.md5($password)) and add it to hashcat, will gladly donate if done !

**Comment by jsteube** [comment]
Where is this algorithm used in?

**Comment by jsteube** [comment]
No response from OP, therefore closing. Feel free to reopen with updated information.

**Comment by jj2hh2hasdf** [comment]
Sweclockers.com db
