### ISSUE TITLE
zip2john updated (bugs fixed); pkzip format changed

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#2719]
Just a heads-up (perhaps mainly to @philsmd and/or @s3inlc):

Some bugs has been squashed for good in [zip2john](https://github.com/openwall/john/issues/4571) and I had no option other than to change the hash input format.

Old hash format `$pkzip2$` featured two kinds of checksums, and neither zip2john or our formats knew which one to use - so at least in case of JtR, we checked both:
```c
              if (salt->chk_bytes == 2 && C != (e & 0xFF) && C != (e2 & 0xFF))
                      goto Failed_Bailout;
```
Obviously this gave fewer early rejections, since a random `C` could just happen to be same as `e` or as `e2`.

The solution (avoiding an all-new third version of input format such as `$pkzip3$`) was actually to revert to the original `$pkzip$(...)` format (without the `2`) which only lists one checksum (but unlike years ago we now always put the correct one there 🙄 ).

You really need to use the latest `zip2john` in order to get correct hashes in all cases, so I suggest you switch to supporting the new-old format. Actually you could drop support for `$pkzip2$` entirely, to ensure users don't end up attacking hashes created with older buggy tools and get false negatives.

**Comment by magnumripper** [comment]
Looking at some of your sources, you might not need to do anything! I only saw `$pkzip2$` in example hashes on the wiki but you seem to support `$pkzip$` too, and that should mean you're all set, except just inform your users they should use latest bleeding zip2john.

I will perform some testing to confirm.

**Comment by magnumripper** [comment]
Right, everything is fine and dandy. Just announce the importance of re-running zip2john, and close the issue 👍

**Comment by philsmd** [comment]
@jsteube I think we can close this issue without any further action/problems. Thanks @magnumripper for letting us know.

**Comment by jsteube** [comment]
OK, thanks @magnumripper
