### ISSUE TITLE
Hashcat OpenCl Build Failed

### ISSUE THREAD

**Issue by 33omac** [hashcat/hashcat#2720]
Downloaded hashcat with homebrew on Apple M1 mac.

Terminal output from hashcat: 
 

`
 hashcat -a 3 -m 0 202cb962ac59075b964b07152d234b70 "?d?d?d"
hashcat (v6.1.1) starting...

OpenCL API (OpenCL 1.2 (Dec 21 2020 17:26:51)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5397/5461 MB (1024 MB allocatable), 8MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clCreateProgramWithBinary(): CL_INVALID_VALUE

* Device #1: Kernel /opt/homebrew/Cellar/hashcat/6.1.1/share/hashcat/OpenCL/shared.cl build failed.

Started: Tue Mar  2 16:24:25 2021
Stopped: Tue Mar  2 16:24:25 2021
'
How can I fix this issue?

Cloning from git gave me `No devices found/left` error message.

**Comment by realSnoopy** [comment]
cannot build shared, i got this error back then when using wrong opencl drivers on intel cpu with self compiled git versions, what is your output of hahscat -I wiht your git-version of hashcat?

**Comment by 33omac** [comment]
Hashcat -I outputs no devices found/left.

**Comment by 33omac** [comment]
Figured out what the issue was and got it to work. I had some old version hashcat leftover files in /usr/local/bin and /usr/local/share that were conflicting with the current version of hashcat.
When I removed hashcat a few months ago with rm -rf hashcat, some files were not deleted and I forgot to check for leftovers.
