### ISSUE TITLE
CUDA 11.2 Toolkit issue in Windows with nVidia 30 series GPU

### ISSUE THREAD

**Issue by ddfault** [hashcat/hashcat#2722]
I have a 30 series nVidia card and even though I had CUDA Toolkit 11.2 installed.
OpenCL 1.2 CUDA 11.1.114

When I run hashcat.exe --backend-info
hashcat stills showed:
```
hashcat (v6.1.1) starting...

* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime
```
I installed CUDA Toolkit 10.2 (runtime only) and no change. I copied over the nvrtc64_112_0.dll and it saw the card! I eventually copied nvrtc64_112_0.dll and nvrtc-builtins64_112.dll to my hashcat-6.1.1 folder and rand my brute force. Unfortunately with CUDA 11.2 in this setup I get this error:
```
cuLinkAddData(): the provided PTX was compiled with an unsupported toolchain.

* Device #1: Kernel ./OpenCL/shared.cl link failed. Error Log:

ptxas application ptx input, line 9; fatal   : Unsupported .version 7.2; current version is '7.1'



* Device #1: Kernel ./OpenCL/shared.cl build failed.
```

When I swap out the dlls for CUDA Toolking 10.2 (nvrtc64_102_0.dll and nvrtc-builtins64_102.dll) I get this error:
```
nvrtcCompileProgram(): NVRTC_ERROR_INVALID_OPTION

nvrtc: error: invalid value for --gpu-architecture (-arch)

* Device #1: Kernel ./OpenCL/shared.cl build failed.

* Device #1: Kernel ./OpenCL/shared.cl build failed.
```

Googling about this today, it looks like Ubuntu has had success with CUDA 10.x, but is that about my only option? Happy to help if you need further debugging.

With the DLLs removed I am able to run using OpenCL 1.2, but as your documentation states it uses a CPU core per GPU.

**Comment by ddfault** [comment]
I have a second machine with CUDA 11.2 and it works out the box! I'll investigate and post my findings.

**Comment by ZerBea** [comment]
That is not a hashcat issue.
The CUDA toolkit doesn't match to your installed driver.
Please read more here:
https://github.com/hashcat/hashcat/issues/2626

**Comment by jsteube** [comment]
Why all this chaos. Just install latest CUDA SDK and everything will just work. There's no need to copy files back and forth. No matter if Linux or Windows.

**Comment by jsteube** [comment]
No response from OP, therefore closing. Feel free to reopen.
