### ISSUE TITLE
When I test on arm, I will report an error when I use 4 or more GPUs，Has anyone met it

### ISSUE THREAD

**Issue by luxianjun** [hashcat/hashcat#2725]
There are always problems on 13800, and the next time it becomes 3100,but there's no problem running 13800 or 3100  alone.

Speed.#5.........:        9 H/s (576.98ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#*.........:       43 H/s

Hashmode: 13800 - Windows Phone 8+ PIN/password

cuStreamSynchronize(): an illegal memory access was encountered
cuStreamSynchronize(): an illegal memory access was encountered
cuStreamSynchronize(): an illegal memory access was encountered
cuStreamSynchronize(): an illegal memory access was encountered
cuStreamSynchronize(): an illegal memory access was encountered
Speed.#1.........:   782.7 MH/s (428.65ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#2.........:   752.7 MH/s (445.72ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#3.........:   781.2 MH/s (429.44ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#4.........:        0 H/s (0.00ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#5.........:   758.2 MH/s (442.50ms) @ Accel:1 Loops:125 Thr:1024 Vec:1
Speed.#*.........:  3074.8 MH/s

Has anyone met it? Thank you very much

**Comment by jsteube** [comment]
Can you provide me with all files I need to reproduce locally?

**Comment by jsteube** [comment]
No response from OP, not added files to reproduce locally, plus oudated hashcat version. Feel free to reopen and update with files to reproduce locally.
