### ISSUE TITLE
Feature Request - Apple M1 Processor Support

### ISSUE THREAD

**Issue by 0xPCP** [hashcat/hashcat#2728]
Currently Apple M1 processor support appears to be lacking.

After compiling from latest release...

hashcat % ./hashcat -I --force            
hashcat (v6.1.1-120-g15bf8b730) starting...

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.
OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (Dec 21 2020 17:26:51)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 2
    Vendor.........: Apple
    Name...........: Apple M1
    Version........: OpenCL 1.2 
    Processor(s)...: 8
    Clock..........: 1000
    Memory.Total...: 10922 MB (limited to 1024 MB allocatable in one block)
    Memory.Free....: 10858 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2 1.0

./hashcat --benchmark --force
hashcat (v6.1.1-120-g15bf8b730) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.
No devices found/left.

Started: Fri Mar 12 12:53:40 2021
Stopped: Fri Mar 12 12:53:40 2021

**Comment by emwinkler** [comment]
I had the same issue on my Intel based Macbook Pro.  In order to make hashcat run on the internal Iris Plus GPU, I had to run the benchmark command like this:

hashcat --benchmark --force -D 2

My guess if you run ./hashcat --benchmark --force -D 1, then the GPU will be used.

**Comment by jsteube** [comment]
With -D1 you enable the CPU

```
- [ OpenCL Device Types ] -

  # | Device Type
 ===+=============
  1 | CPU
  2 | GPU
  3 | FPGA, DSP, Co-Processor
```

On macOS the default is set to CPU only but can be overwritten by using -D 2 to make use of the GPU.
