### ISSUE TITLE
Add Electrum Bitcoin wallet support

### ISSUE THREAD

**Issue by marcushat** [hashcat/hashcat#273]
Algorithm:
SHA256
[AES_256_CBC](https://github.com/heipei/engine-cuda/)
--[aes_cuda.cu](https://github.com/heipei/engine-cuda/blob/master/aes_cuda.cu), [aes_opencl.c](https://github.com/heipei/engine-cuda/blob/master/aes_opencl.c)

Why this should be implemented?
Electrum wallets are only hashed with 2 rounds of sha256 which makes it a great candidate for bruteforcing. I can current try 150k password a second on my i3 laptop, I hope we can do at least 100x that on a gpu. Recovering lost passwords to these wallets could be very valuable obviously since they store btc.

`aes256_cbc_decrypt(sha256(sha256("password")))`

**Comment by marcushat** [comment]
May offer my bitcoin wallet up for bounty if I'm not able to figure this out myself in the next month.

**Comment by kost123** [comment]
+1 for this

**Comment by neocogent** [comment]
Maybe a starting point could be Keepass 2 (m=13400)(which also uses AES and SHA256). I don't know enough about opencl coding. I think the AES mode may be CBC instead of ECB and I have no idea how that would change things for the existing the Keepass 2 code. Just thought since they both use same algos it may not need to be written from scratch.

Electrum cracking would need only the "xprv" string from the wallet file to run on for a result. eg. the following xprv has password test12345 and the decrypted result is the master private key.

    VrqpJdrmN6AFuJhMMSkj0fTXMhhHZdV65R+5EZLC1cEF17PSTkDPy4PXqYqkoVdzvjfM1mURv0i5suIFjEk4IzVgR5BL8NwpRcc6rZyT9dCVlVzAE5pcRa1HaRQ/KxV8pGCoo3D8rKMgXCl01q5WP5UZGZAaYmTzZBhifLytY08=  

(base64 decode first)

**Comment by marcushat** [comment]
Thanks I'll definitely look into it. My wallet is worth 4x what I bought it for so this is a great time to give it another go. I'll report back if I get something that works

**Comment by se7enten** [comment]
Looks like johntheripper has gotten support.  It's worth noting they created a electrum2john.py tool for extracting the hash.

https://github.com/magnumripper/JohnTheRipper/pull/2541/files

No opencl support though.

**Comment by marcushat** [comment]
I ran electrum2john.py and it got `default_wallet:$electrum$2*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

XXX=hex string


What do with this? I tried putting it in a file(hash.txt) and then ran `john --format=bitcoin hash.txt` and `john --format=bitcoin hash.txt` but it said "unknown ciphertext format name requested". Going to try it with the bleeding-jumbo version and see if that works

**Comment by magnumripper** [comment]
You obviously need to run a version of jumbo built from the very same tree where you got electrum2john.py. Any older john version will just support punch card crypto and bit-sliced 6-bit hashes from the days of steam trains and hot air balloons.

**Comment by marcushat** [comment]
Ha. Yeah, I figured it out. Running it now! Getting around 1M attempts per sec on a t2.micro EC2 instance. Thanks so much

**Comment by neocogent** [comment]
@marcushat 
You might try vultr.com as they have much faster instances and take bitcoin. I've used them several times and found that processing ran much faster than on EC2 spot instances. Easy interface too and pay per hour. Should be able to do many times better than a t2.micro I'd guess. 

I'm playing around with an Arty7 FPGA dev board I have. I created an Electrum cracker engine to try it out. Still simulating and debugging but it actually may work. I thought I would get 24 Mpwds/sec but it looks like the timing is too tight. It uses dual sha256 hashers from an FPGA bitcoin miner and dual AES  decrypter (both open source cores), and my own pwd sequencer logic. It hooks to a pc via usb and you send the xprv and pwd gen mask by usb, and wait for result back. We'll see... if it works then concievably it would be not hard to make a board with many fpga chips on it running in parallel. This chip costs ~ $40 each.

**Comment by marcushat** [comment]
Probably not going to be worth it for my wallet. I already spent the entire initial value of the wallet trying to crack it on AWS about a year ago. Once I rule out 9 char passwords I'm probably gonna have to go the wordlist route

**Comment by neocogent** [comment]
Ya, the FPGA is just toying around for curiosity and practice as I happen to have it here. I've got a working design in simulation but at 10M pwds/sec it still raises timing errors. I'm probably not doing something right so it's good to figure the timing out. In simulation it actually hashes correct values and decrypts the hash to match xprv result - so that's pretty cool for me.

**Comment by marcushat** [comment]
That did it! Haha. Got a paypal @se7enten?

**Comment by se7enten** [comment]
no paypal but i'll take those bitcoin you just cracked.  :P

if you feel inclined to make a small donation hook up magnumripper or hashcat or openwall or kholia since he actually coded the electrum support for jtr.

glad you got in though!  and I'd still like to see GPU support with hashcat.

**Comment by neocogent** [comment]
@marcushat 
Did it take all 18-19 days running to get it?

**Comment by marcushat** [comment]
12 days! On the ec2 micro instance it slowed down to about 100k/sec after a day or so, so it only took about 100bn passwords it crack it. Glad I didn't make my pasword 1 char longer!

**Comment by neocogent** [comment]
I guess the slow down was since micro instances aren't suited to ongoing cpu load and they limit you after a while. It's great to see that it actually worked out.

**Comment by 1sammy** [comment]
Any recommendations you can make now that some time has passed? I'm in the same scenario and I've ended up running JtR on my R7 1700, 2 days in and 2M passwords/sec, just wondering if y'all had any new insight as I've used some crazy passwords in the past and am not sure if this will work.

**Comment by kholia** [comment]
Use http://www.openwall.com/lists/john-users/ for support questions.

**Comment by kholia** [comment]
Edit: Oops, I posted on the wrong GitHub thread. It is very early morning for me.

**Comment by jsteube** [comment]
Support for Electrum Bitcoin wallet was added

**Comment by sbtc1** [comment]
@jsteube 
Hi Jens, great work on adding this. There seems to be an issue though with the new electrum support, it was running fine for a v1 example, but for this v2 hashcat does not find the password:

`$electrum$2*942782d00d632be27d54c1bac429a693*3b3c918cb07b4e08670ed4d2e8916b47`

I'm putting the password ("blabla55") in a wordlist, but hashcat does not detect it as being correct. (does get detected by JTR)

kr

**Comment by jsteube** [comment]
Only Salt-Type 1 is supported yet. I'll maybe add the other ones when I'm very bored ;)

**Comment by sbtc1** [comment]
Oh, I was confused because of the "Electrum Wallet (Salt-Type 1-3)" label in the tool. Good to know. I'll add a new feature request for tracking. Thanks.

**Comment by Metatronovich** [comment]
Is $electrum$2 really supported now?

I ran a test on a new wallet (from an older electrum version, 2.6.4.) - hashed out the hash using electrum2john.py, put around 6 words in a password list (one of them is 123abc, the real password)
and ran ./john --wordlist=wordlist.txt hashfile
It seems the program runs but no result.

`Using default input encoding: UTF-8
Loaded 1 password hash (electrum, Electrum Wallet [SHA256 AES / PBKDF2-SHA512 256/256 AVX2 8x])
Cost 1 (kdf [1:SHA256 2:PBKDF2-SHA512]) is 1 for all loaded hashes
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 2 candidates left, minimum 4 needed for performance.
0g 0:00:00:00 DONE (2019-03-07 19:16) 0g/s 9.090p/s 9.090c/s 9.090C/s 123abc..abc123
Session completed
`

Anyone have any idea why is that?
