### ISSUE TITLE
Cracking IKE Pre-shared-keys with diffie helman groups other than 2

### ISSUE THREAD

**Issue by hatlord** [hashcat/hashcat#2730]
Hello,

I noticed when capturing IKE handshakes with certain transform sets that they would not crack. In my case, I can set DH groups 2, 5, and 14. Only hashes for 2 will crack, 5 and 14 with the same password do not crack. The following handshake is a SHA handshake with DH group 14. The plaintext value is "password". Taken from my lab so no concerns about sharing it here:

~~~

ike-scan -A 192.168.1.251 -M -P --id=vpngroup --trans 7/128,2,65001,14                                                                                                                                                                  
Starting ike-scan 1.9.4 with 1 hosts (http://www.nta-monitor.com/tools/ike-scan/)
192.168.1.251	Aggressive Mode Handshake returned
	HDR=(CKY-R=f893a45c8ba9e6e9)
	SA=(Enc=AES KeyLength=128 Hash=SHA1 Group=14:modp2048 Auth=XAUTH_PSK LifeType=Seconds LifeDuration=28800)
	KeyExchange(256 bytes)
	Nonce(20 bytes)
	ID(Type=ID_IPV4_ADDR, Value=192.168.1.251)
	Hash(20 bytes)
	VID=12f5f28c457168a9702d9fe274cc0100 (Cisco Unity)
	VID=09002689dfd6b712 (XAUTH)
	VID=afcad71368a1f1c96b8696fc77570100 (Dead Peer Detection v1.0)
	VID=4048b7d56ebce88525e7de7f00d6c2d3c0000000 (IKE Fragmentation)
	VID=1f07f70eaa6514d3b0fa96542a500100 (Cisco VPN Concentrator)

IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
95734b37b53d8ece7b23e28cd34a2ea6701a28ddde70b68e063e5d31d2dcb54c9cccfeaf2b38929560608c3238e4359171708f44b6bd1d189584eca3b27bb0063b45c96af3ba082d1c4f5137e2a97509e8fdf562c80d38e254b0b8fe5b9ccfc40a35d06f63032b3a7b42129c3580eae767f078ed02cf087dc6fa1375bdbbfe9be53b0fc3f24f76541912a204eaa21803216d1eeda3fe1458e8710adf0b418a36d2de0b75145840ba70374e2c3f08972ed9189f283afb7e66c36ae28a96139a493411cdbc7f5fc4703f8b03527681f23f3b13e8c49a2059a985e1c3ddaf989403846af8826a8e74142dd38c1245f8cb6bc1557476eb642d91765dacb7dcbe43cf:250f8d0f786c9ffb93ba2a9ab512aa83c4a040e19cdcf9443a4ad7edad41a452b9e935dba9739cc9227c32bf9ae41f3352e6dc31fb8158fa28082c25e81274fe0d1f38b8ae835637ce1f983cb64b767d08138a72e537d64ad4dea12ec073d0463057ea0ff1bad005639557564126cf9ee89abef9c3dc675d673717d13a40d442:f893a45c8ba9e6e9:84cf87ccb71fd0c0:00000001000000010000003001010001000000280101000080010007800200028003fde98004000e800e0080800b0001000c000400007080:01110000c0a801fb:a7d43b320b4ee91d0389ee40fdb930240cf45b4c:c31ff081ebc1b485a85fd40afbc55a85f9847429:725e5541f8c469233944f3c00b5e4629d9b079b9
Ending ike-scan 1.9.4: 1 hosts scanned in 0.022 seconds (44.51 hosts/sec).  1 returned handshake; 0 returned notify

~~~

Im not sure if this is a limitation of hashcat, or if its purely because DH group 5 or 14 add something to the hash/computation that makes it impossible to crack, but it would be great to get your input please.

Thanks for the amazing tool!

**Comment by oam7575** [comment]
More details would likely be required to triage the issue.
Have you posted on the forums?
Can you share the PSK ? 
Have to attempted to use mode 5400 for IKE-PSK SHA hashes ? 
I understand that some DH group modes have various weaknesses; but am not familiar with them.
Group 14 is 2048-bit
Does Hashcat even run ? does it generator an error ? Does it take a while an not generate a result ?

**Comment by hatlord** [comment]
Hello!

I haven't posted on the forums but can if that is best?
The hash is in the original post, I have separated it out below. The PSK is 'password' and it is a SHA hash, DH Group 14:

~~~
95734b37b53d8ece7b23e28cd34a2ea6701a28ddde70b68e063e5d31d2dcb54c9cccfeaf2b38929560608c3238e4359171708f44b6bd1d189584eca3b27bb0063b45c96af3ba082d1c4f5137e2a97509e8fdf562c80d38e254b0b8fe5b9ccfc40a35d06f63032b3a7b42129c3580eae767f078ed02cf087dc6fa1375bdbbfe9be53b0fc3f24f76541912a204eaa21803216d1eeda3fe1458e8710adf0b418a36d2de0b75145840ba70374e2c3f08972ed9189f283afb7e66c36ae28a96139a493411cdbc7f5fc4703f8b03527681f23f3b13e8c49a2059a985e1c3ddaf989403846af8826a8e74142dd38c1245f8cb6bc1557476eb642d91765dacb7dcbe43cf:250f8d0f786c9ffb93ba2a9ab512aa83c4a040e19cdcf9443a4ad7edad41a452b9e935dba9739cc9227c32bf9ae41f3352e6dc31fb8158fa28082c25e81274fe0d1f38b8ae835637ce1f983cb64b767d08138a72e537d64ad4dea12ec073d0463057ea0ff1bad005639557564126cf9ee89abef9c3dc675d673717d13a40d442:f893a45c8ba9e6e9:84cf87ccb71fd0c0:00000001000000010000003001010001000000280101000080010007800200028003fde98004000e800e0080800b0001000c000400007080:01110000c0a801fb:a7d43b320b4ee91d0389ee40fdb930240cf45b4c:c31ff081ebc1b485a85fd40afbc55a85f9847429:725e5541f8c469233944f3c00b5e4629d9b079b9
~~~
The mode 5400/5300 is used appropriately depending on the hash type chosen in the transform, either MD5 or SHA.
Hashcat runs, no crashes, it just doesn't crack the hash. 

Thanks for the response!

**Comment by oam7575** [comment]
Hi @hatlord 

Both the MD5 and SHA1 examples from here : https://hashcat.net/wiki/doku.php?id=example_hashes appear to work correctly.

I dug out an old Juniper SSG5 for testing.

ike-scan appears to gather details correctly and hashcat cracked the hashes correctly.
All passwords for my testing are : 123456

Not sure what's happening at your end.

**Some details on ScreenOS Propsals**
Juniper P1 Proposal Configuration.
On ScreenOS devices you can select from several out of the box proposal configurations : Standard, Compatible and Basic.

You can also select Custom / User Defined Phase 1 Proposals.
For Custom Phase 1 Proposals you can mix and match from predefined Proposal options with security configurations you might expect from the time these older SSG and previous NetScreen devices were sold : EG : DES/MD5 ; 3DES/SHA1 etc.

Additionally ScreenOS allows for the creation of new P1 and P2 propsals allowing the administrator to mix and match encryption and hashing combinations.

**Testing**
For my testing I initially selected a "Standard" configuration to ensure everything would work and used ike-scan to get a PSK to crack.

Standard resulted in an AES SHA1 G2 128bit handshake

IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
5f87824a4ecfd297cc044b40a90dbbeb312c4decda1b9c62b3492becb24821e9995e63b84ae1b4c768123c44618b61663edd5e320f2377c834a1ae4b8989792e62d8c772230e744c5692a2a9edfb6812b0753fbac62801363ecdcf29c6e1624cae2f396a893df8e771acc5a11c7e773476b5baa7b3e437858ecc0a2f53ca7293:eee0e932e510b28c33e1690b460945d9ee3bcd772fe82066438f246dddf316a09870f6814ca75c51a926f937244e58f7855adf65de8f312a7569995ad442cf4f939de2acc8e8cf1188dc640c2ed7f6c2f37518a39e60a693836cf250fc49b46d97600efdccba04b90266be445253012e58018105c35527f309c63c543fefc54b:7c543d0d5aba14d7:2e2aac85438621be:00000001000000010000003001010001000000280101000080010007800200028003fde980040002800e0080800b0001000c000400007080:011101f40a210142:113057b38e2e60bf505e3229c7327d4fe584b20e:cb0800041e71e9e81f56bca36c9fe1a2a8c25f067dd2d25ea2d18f5bdb9b70bd:11e8c17b6fedd5f2968b8b5a5a9fb9324be10c03


I then manually specified a custom proposal "pre-g2-aes128-sha" to check correct behaviour

Again this resulted in an AES SHA1 G2 128bit handshake
IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
80c7e10e68cb3d95940a40f8ccd56ec0189c62ab87cfa6b1750fd26d63410adcc3f0dabab6f75df43d88558daa87dab6865dfb92e3bbd0cb0f196e2780156f90782a6b94e8cea20d8681452c2b036da60a0b81ad2d64081013e4d98e6d49054abcdb5e0b6375b37f6662ac63578443f6bbcf464ce7053cf438d2c1a08b60ad88:5080a60ed65332bfaf3ea76d86ec5f391e23de742038567e22f8bca13b13a5a5139e01dbb4e8788a884d32d22265823a6d4593e3559fa596434b9ff02f632ff4e880d9edd889e3593e489aa460b698013c2f3197ed5a78470077a9e16943f3570166d62103535c20b860c0bc321d4af104e21d6150e68627fcb3727708dd63bc:7c771a627e764c53:d9afd1a1f3cbdce2:00000001000000010000003001010001000000280101000080010007800200028003fde980040002800e0080800b0001000c000400007080:011101f40a210142:59571d4d850ed2f3a2fbcabc66593152520bb468:50d2e3a4d206a9093284d489cb48d18429d3d9347c3a3db3914543706bef8821:ffa840b968809ed4c60daa98bf1eba025f366148

I then began testing different P1 Proposal combinations
My testing showed ike-scan and hashcat were able to correctly handle the follow combinations

**SHA1 G14 AES 256Bit**

Starting ike-scan 1.9.4 with 1 hosts (http://www.nta-monitor.com/tools/ike-scan/)
172.16.10.66      Aggressive Mode Handshake returned
        HDR=(CKY-R=a7a471d9c9e6d4c4)
        SA=(Enc=AES Hash=SHA1 Group=14:modp2048 Auth=XAUTH_PSK KeyLength=256 LifeType=Seconds LifeDuration=28800)
        VID=e7a811cf8de6140e3adc82fd7855ff8ff1eadb8f000000130000061e
        VID=09002689dfd6b712 (XAUTH)
        VID=afcad71368a1f1c96b8696fc77570100 (Dead Peer Detection v1.0)
        VID=4865617274426561745f4e6f74696679386b0100 (HeartBeat_Notify)
        KeyExchange(256 bytes)
        Nonce(32 bytes)
        ID(Type=ID_IPV4_ADDR, Value=172.16.10.66)
        Hash(20 bytes)

IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
81b9f4005a71be92ce1ef2e0f502a8e37f781011d9c8c4cf8cff5771dc5418ab0d392cd619f6e1e9e1ef57759eaf860a0e6c6b02bcbb93d5f579efd20af7959a8f9908c98327806506fe2593885de92bea6fb5e11cb4da34a799aad7723dea4424ea5e2fecaaf992a2c228affbbae400e3c6c2882052b7f4ea627fdb35f759d1573ffbb34e19f5ad17fbbd6a41f3a3670799b6cc96fb4018a27b7d471390854dc1b924ad0ac5a92b417bc04c8cb465f24aebc133035756c19f521e2febd2338ff73e682f4933b1ed741618334d4f81b1835fa302c2cd9303729fe5f35b3ee0022b887845e74520bc6d1684d4f1d636c663383efb935056f683850f51b375c1ef:90346b5f4b1927b406eb1fe61f85d9b23c33875dc42b2f9100760943cf1ee1c3e07470b32c7561c8a20863cfca4446cdccb84629696e466512acc80542ae189e935607eb5f5928c9a13d90cf95e7352530423701c6d6cc7d24cb10a366be2a6388a20f597e59a61d94d75f4c40975b61b2dd791ec2696d339fb4446dd4eec29e:a7a471d9c9e6d4c4:77ad3980bc249540:00000001000000010000003001010001000000280101000080010007800200028003fde98004000e800e0100800b0001000c000400007080:011101f40a210142:f054efc57e2ed082727f80c2793715d30f5b8c4a:80e5a125726ea30122c41fa2b08199df13514e22bfcfdfca2150eb302c36be3f:260c1fd15852f05f58d66e6ba419d3dd4469bf41


**SHA1 G19 AES 256Bit**

Starting ike-scan 1.9.4 with 1 hosts (http://www.nta-monitor.com/tools/ike-scan/)
172.16.10.66      Aggressive Mode Handshake returned
        HDR=(CKY-R=b32cafde7bf379f2)
        SA=(Enc=AES Hash=SHA1 Group=19 Auth=XAUTH_PSK KeyLength=256 LifeType=Seconds LifeDuration=28800)
        VID=e7a811cf8de6140e3adc82fd7855ff8ff1eadb8f000000130000061e
        VID=09002689dfd6b712 (XAUTH)
        VID=afcad71368a1f1c96b8696fc77570100 (Dead Peer Detection v1.0)
        VID=4865617274426561745f4e6f74696679386b0100 (HeartBeat_Notify)
        KeyExchange(64 bytes)
        Nonce(32 bytes)
        ID(Type=ID_IPV4_ADDR, Value=172.16.10.66)
        Hash(20 bytes)

IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
db68f835ff192b303af5d717cac25951de92c5c2ad06bd88f646a5b25b926b26f4651794dfaea3c9b8076f51d008ce7a9139fa21accba8ccf17ed482c77e4555:6d1d110cf77aab4810d84a812e05a33ed05830fce80c2cc6e9e9e8f3c4c32371ce98526d031bf7342171d9100b6ed13672540fd347a389e1d3cb983d2c86b329dec1a35d35fe82b9f6a658a62421769950aed022928c8fd3df3a5d60a784e6423a4cb320ff7fa28683c2a798ce9901dc2ef1acafd0580dd33ffcf04f1443e39d:b32cafde7bf379f2:52ca7616196c1e67:00000001000000010000003001010001000000280101000080010007800200028003fde980040013800e0100800b0001000c000400007080:011101f40a210142:707c135767f219a08d65c3e769abb7a49bf40111:96bfe746f68668e8ae999714507bc128f29bfbacc3e3b90309546bf9333774ed:6a3745fc92e509d73cb1d1c9bb03ab42b531ae2c



**SHA1 G20 AES 256Bit**

172.16.10.66      Aggressive Mode Handshake returned
        HDR=(CKY-R=a7387a1a62d81125)
        SA=(Enc=AES Hash=SHA1 Group=20 Auth=XAUTH_PSK KeyLength=256 LifeType=Seconds LifeDuration=28800)
        VID=e7a811cf8de6140e3adc82fd7855ff8ff1eadb8f000000130000061e
        VID=09002689dfd6b712 (XAUTH)
        VID=afcad71368a1f1c96b8696fc77570100 (Dead Peer Detection v1.0)
        VID=4865617274426561745f4e6f74696679386b0100 (HeartBeat_Notify)
        KeyExchange(96 bytes)
        Nonce(32 bytes)
        ID(Type=ID_IPV4_ADDR, Value=172.16.10.66)
        Hash(20 bytes)

IKE PSK parameters (g_xr:g_xi:cky_r:cky_i:sai_b:idir_b:ni_b:nr_b:hash_r):
b9551e21604fa47214bdb73e073ee497ca2eab16f42d977ef65f7529baad813e940b77e1d998d347a60e50d3286dff9eb1c5f1293eeeb76b13fa71aaf624e01fb8f603482ebd749590ca4f86d2a84300a9f26d08167d03163290e047e34e2297:1bff7c880187c10df6696988b8ca5fae4e72b53e6c579ef6fb2cc6ece9e9f8ab2df2594a27c40d468d8533225f584c0cdca871931349ae99aadc6e38d9cc04c3676c0a4610ed4207942e55efbe178141a35baa59392a220916d240ab686caf73bd7a75ebbcbea5c65f2b1eb5864f827e03ce9e23374db37772a80fc5ebef781c:a7387a1a62d81125:0b77f79179ebbba5:00000001000000010000003001010001000000280101000080010007800200028003fde980040014800e0100800b0001000c000400007080:011101f40a210142:27e7b001f042cd9ae806e7366bc0f721db26a275:6da96e1f04754f6afbc0a1efa78926013b944393fad4c9e1184b350693898c02:439f7cf9affe1bd0e6fb7e4c0098568a82302f43


**Cracking**
Hashcat was able to crack all of these results quite quickly

**Issues**
The only issue I ran into was inadvertently selecting a 256bit SHA2 hash.
This resulted in a "Token Length Exception" error, as Hashcat IKE-PSK modes currently only support MD5 and SHA1 not SHA2

**Comment by hatlord** [comment]
Appreciate you going to these lengths to confirm! I’ll fire up the ASA tomorrow and re-check. I suppose it could be something the Cisco kit is doing.

**Comment by hatlord** [comment]
So this is definitely an odd one. I captured the hashes again, forcing Ike-scan to use specific transforms at each step. Both are SHA hashes. The group 2 hash cracks instantly, the group 14 hash does not. I began to think it might have been something wrong with my setup, so i installed hashcat on a windows host I have and the same issue occurs. This must be something to do with Cisco's implementation i suppose, im at a loss. Ive attached the group 2 and group 14 hashes just in case they are any use.
[group2_hash.txt](https://github.com/hashcat/hashcat/files/6177466/group2_hash.txt)
[group14_hash.txt](https://github.com/hashcat/hashcat/files/6177467/group14_hash.txt)

Commands used:

~~~
ike-scan -A 192.168.1.251 -M -P --id=vpngroup --trans=7/128,2,65001,2 #cracks
ike-scan -A 192.168.1.251 -M -P --id=vpngroup --trans=7/128,2,65001,14 #does not crack
~~~

**Comment by oam7575** [comment]
@hatlord 

I was able to crack your group2_hash.txt as expected.
The group14_hash.txt did not work as you indicated.

Some quick googling suggests there were IKE issues with older software versions on ASA devices that have been patched.
Perhaps cisco patched something when different DH groups were used ? 

I am not sure and rapidly getting beyond my knowledge.

Perhaps if you could provide details as to the ASA device, firmware version or other configuration others might be able to provide suggetions.

**Comment by hatlord** [comment]
Hello,

Yep im at a loss too to be honest. In terms of the version in use, this was on an Cisco ASAv (VMWARE) running ASA 9.14.2, so very recent in terms of software version. At this point from my side the issue can be closed, but if you wanted to keep it open for others to see thats your call. Ill probably test some other vendor's hardware as time allows and see if the issue is Cisco specific or something baked into the standard.

Appreciate the help, thanks again!

**Comment by jsteube** [comment]
Thanks for the update.
