### ISSUE TITLE
I found several problems with hashcat

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2732]
Hello,
Hi...
I found several problems with hashcat
When using a1, a6 attack modes, if there are only a few lines of strings in one of the dictionaries, the speed will be abnormal, especially on devices with more than 2 video cards
More strings need to be added to the dictionary for the speed to be normal.

Problem Description
Everything in the dictionary
cat dic.txt
abc
asd
qwe
qaz
abcd

 abnormal
hashcat.exe -m 0 -a 6 -1 0123456789  md5.txt -o outpass.txt --increment --increment-min 1 --increment-max 15  dic.txt ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxx7
Time.Started.....: Tue Mar 16 10:28:30 2021 (51 secs)
Time.Estimated...: Tue Mar 16 10:39:40 2021 (10 mins, 19 secs)
Guess.Base.......: File (dic.txt), Left Side
Guess.Mod........: Mask (?1?1?1?1?1?1?1?1) [8], Right Side
Guess.Charset....: -1 0123456789, -2 Undefined, -3 Undefined, -4 Undefined
Speed.#1.........:   901.6 kH/s (0.09ms) @ Accel:32 Loops:64 Thr:1024 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:32 Loops:64 Thr:1024 Vec:1
Speed.#*.........:   901.6 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 41061888/600000000 (6.84%)
Rejected.........: 0/41061888 (0.00%)
Restore.Point....: 0/6 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:6843584-6843648 Iteration:0-64
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-64
Candidates.#1....: Hi94562745 -> qaz86928055
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 46c Fan:  0% Util: 26% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 45c Fan:  0% Util:  0% Core: 300MHz Mem: 405MHz Bus:1

The same device, it seems to be normal when executing a7 mode, but a1 and a6 are abnormal

hashcat.exe -m 0 -a 7 -1 0123456789  md5.txt -o outpass.txt --increment --increment-min 1 --increment-max 15   ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1 dic.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7
Time.Started.....: Tue Mar 16 10:36:20 2021 (2 mins, 24 secs)
Time.Estimated...: Tue Mar 16 11:23:14 2021 (44 mins, 30 secs)
Guess.Base.......: File (dic.txt), Right Side
Guess.Mod........: Mask (?1?1?1?1?1?1?1?1?1?1?1?1) [12], Left Side
Guess.Charset....: -1 0123456789, -2 Undefined, -3 Undefined, -4 Undefined
Speed.#1.........:  1078.5 MH/s (1.44ms) @ Accel:64 Loops:6 Thr:1024 Vec:1
Speed.#2.........:  1053.8 MH/s (1.50ms) @ Accel:64 Loops:6 Thr:1024 Vec:1
Speed.#*.........:  2132.3 MH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 306076188672/6000000000000 (5.10%)
Rejected.........: 0/306076188672 (0.00%)
Restore.Point....: 51010338816/1000000000000 (5.10%)
Restore.Sub.#1...: Salt:0 Amplifier:0-6 Iteration:0-6
Restore.Sub.#2...: Salt:0 Amplifier:0-6 Iteration:0-6
Candidates.#1....: 785777989056Hi -> 319522669056qaz
Candidates.#2....: 251646669056Hi -> 885777989056qaz
Hardware.Mon.#1..: Temp: 59c Fan: 28% Util: 97% Core:1905MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 70c Fan: 61% Util: 96% Core:1830MHz Mem:6801MHz Bus:1

-a1  abnormal

hashcat.exe -m 0  -a 1 md5.txt  -o outpass.txt dic.txt 2.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Time.Started.....: Tue Mar 16 10:45:16 2021 (1 min, 4 secs)
Time.Estimated...: Tue Mar 16 10:55:03 2021 (8 mins, 43 secs)
Guess.Base.......: File (dic.txt), Left Side
Guess.Mod........: File (2.txt), Right Side
Speed.#1.........:  1020.3 kH/s (0.18ms) @ Accel:16 Loops:128 Thr:1024 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:32 Loops:64 Thr:1024 Vec:1
Speed.#*.........:  1020.3 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 65482752/600000000 (10.91%)
Rejected.........: 0/65482752 (0.00%)
Restore.Point....: 0/6 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:10913664-10913792 Iteration:0-128
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-64
Candidates.#1....: Hi10913664 -> qaz10913791
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 46c Fan:  0% Util: 29% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 44c Fan:  0% Util:  0% Core: 300MHz Mem: 405MHz Bus:1

But it works fine when they exchange dictionaries

hashcat.exe -m 0  -a 1 md5.txt  -o outpass.txt 2.txt dic.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxxx
Time.Started.....: Tue Mar 16 10:47:59 2021 (10 secs)
Time.Estimated...: Tue Mar 16 10:48:12 2021 (3 secs)
Guess.Base.......: File (2.txt), Left Side
Guess.Mod........: File (dic.txt), Right Side
Speed.#1.........: 27286.2 kH/s (2.08ms) @ Accel:64 Loops:6 Thr:1024 Vec:1
Speed.#2.........: 19938.0 kH/s (1.46ms) @ Accel:64 Loops:6 Thr:1024 Vec:1
Speed.#*.........: 47224.2 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 438829056/600000000 (73.14%)
Rejected.........: 0/438829056 (0.00%)
Restore.Point....: 70778880/100000000 (70.78%)
Restore.Sub.#1...: Salt:0 Amplifier:0-6 Iteration:0-6
Restore.Sub.#2...: Salt:0 Amplifier:0-6 Iteration:0-6
Candidates.#1....: 70778880Hi -> 73138175qaz
Candidates.#2....: 68419584Hi -> 70778879qaz
Hardware.Mon.#1..: Temp: 46c Fan:  0% Util: 14% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 49c Fan:  0% Util: 26% Core:1890MHz Mem:6801MHz Bus:1

I hope these problems will be fixed. In fact, I still have a lot of suggestions for improvement and optimization, which will be discussed later.

**Comment by Banaanhangwagen** [comment]
This is not an issue. Please read this article: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

For some attack-modes, there isn't enough work for the GPU; that's the reason it is slow. You can simply "fix" this by piping into hashcat, as explained in detail in the link above.

If this answers your question, please close this issue.

**Comment by ghost** [comment]
@Banaanhangwagen

Yeah,Thanks,

**Comment by ghost** [comment]
I tried for a few days,  still can’t solve this problem. Can  list the executed commands? Let me refer to it.
Thank you

**Comment by Banaanhangwagen** [comment]
Example for -a1:
`hashcat --stdout -a1 wordlist1.txt wordlist2.txt | hashcat -m 0 md5.txt -o outpass.txt`

**Comment by ghost** [comment]
Thank you, Banaanhangwagen
But I execute the following command to return some information
Using a1 seems normal

hashcat.exe --stdout -a 6 1.txt -1 0123456789 ?1?1?1?1?1?1?1?1?1?1 | hashcat.exe -m 0 md5.txt -o outpass.txt

Starting attack in stdin mode...

Integer overflow detected in keyspace of mask: ?1?1?1?1?1?1?1?1?1?1

Session..........: hashcat
Status...........: Exhausted
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxxx
Time.Started.....: Tue Mar 23 10:19:07 2021 (1 sec)
Time.Estimated...: Tue Mar 23 10:19:08 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:     8708 H/s (0.02ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........:     8708 H/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 8
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: * Device #1: CUDA SDK Toolkit installation NOT detected. ->
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 39c Fan:  0% Util:  5% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 41c Fan:  0% Util:  3% Core:1410MHz Mem:6801MHz Bus:1
Started: Tue Mar 23 10:19:04 2021
Stopped: Tue Mar 23 10:19:10 2021

D:\hashcat-6.1.1>pause



hashcat.exe --stdout -a 7  -1 0123456789 ?1?1?1?1?1?1?1?1?1?1 1.txt | hashcat.exe -m 0 md5.txt -o outpass.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Time.Started.....: Tue Mar 23 10:20:53 2021 (9 secs)
Time.Estimated...: Tue Mar 23 10:21:02 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........: 29835.2 kH/s (3.18ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........: 29835.2 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 2359296
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: * Device #1: CUDA SDK Toolkit installation NOT detected. -> 5287556999rc
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 39c Fan:  0% Util:  1% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 41c Fan:  0% Util:  0% Core:1410MHz Mem:6801MHz Bus:1

**Comment by Banaanhangwagen** [comment]
"Integer overflow" is a lot of times explained on the Hashcat-forum.
https://hashcat.net/forum/thread-8332.html
https://hashcat.net/forum/thread-6588.html
https://hashcat.net/forum/thread-8920.html

**Comment by ghost** [comment]
@Banaanhangwagen
Thanks...

**Comment by oam7575** [comment]
@LLH-l 
If you believe you under stand the problem and this is a "non-issue" please consider closing if possible

**Comment by ghost** [comment]
@oam7575

I still think it is a problem. Although I use the pipeline method, it still cannot reach the benchmark speed.

Video card equipment, 2 RTX2070



Test..

hashcat --stdout -a 6 PassDic.txt -1 0123456789 ?1?1?1?1?1?1?1?1?1?1?1??1?1 --increment --increment-min 1  --increment-max 13 | hashcat -m 2611 md5.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:17:19 2021 (1 min, 51 secs)
Time.Estimated...: Wed Mar 31 19:19:10 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:   226.8 kH/s (5.85ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:   230.0 kH/s (5.89ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........:   456.8 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 40108032
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: Hello24087655 -> Hello68459769
Candidates.#2....: Hello98563634 -> Hello07087655
Hardware.Mon.#1..: Temp: 47c Fan:  0% Util:  1% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 49c Fan:  0% Util:  5% Core:1410MHz Mem:6801MHz Bus:1



Test..

hashcat --stdout -a 7  -1 0123456789 ?1?1?1?1?1?1?1?1?1?1?1??1?1 PassDic.txt   --increment --increment-min 1  --increment-max 13 | hashcat -m 2611 md5.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:25:10 2021 (2 mins, 50 secs)
Time.Estimated...: Wed Mar 31 19:28:00 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........: 31354.9 kH/s (6.83ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........: 11396.7 kH/s (5.77ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........: 42751.6 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 4718592
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: * Device #1: CUDA SDK Toolkit installation NOT detected. -> 0324656Hello
Candidates.#2....: 2724656Hi -> 8033723Hello
Hardware.Mon.#1..: Temp: 52c Fan:  0% Util:  4% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 52c Fan: 42% Util:  9% Core:1410MHz Mem:6801MHz Bus:1




Test..

hashcat --stdout -a 1 2.txt PassDic.txt | hashcat -m 2611 md5.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:32:59 2021 (1 min, 40 secs)
Time.Estimated...: Wed Mar 31 19:34:39 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........:        0 H/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 0
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Copying]
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 48c Fan:  0% Util:  4% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 48c Fan:  0% Util:  9% Core:1410MHz Mem:6801MHz Bus:1

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:32:59 2021 (2 mins, 14 secs)
Time.Estimated...: Wed Mar 31 19:35:13 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........: 21220.6 kH/s (5.43ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........: 21220.6 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 2359296
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: * Device #1: CUDA SDK Toolkit installation NOT detected. -> 00623308Hello
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 49c Fan:  0% Util:  4% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 50c Fan:  0% Util:  9% Core:1410MHz Mem:6801MHz Bus:1




Test..

hashcat --stdout -a 1 PassDic.txt  2.txt | hashcat -m 2611 md5.txt

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:37:20 2021 (19 secs)
Time.Estimated...: Wed Mar 31 19:37:39 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........: 36031.9 kH/s (5.40ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:   445.7 kH/s (5.77ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........: 36477.6 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 7077888
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: Hello01179640 -> Hello02359287
Candidates.#2....: Hello02359288 -> Hello03538935
Hardware.Mon.#1..: Temp: 50c Fan:  0% Util:  2% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 53c Fan:  0% Util:  0% Core:1410MHz Mem:6801MHz Bus:1

Session..........: hashcat
Status...........: Running
Hash.Name........: vBulletin < v3.8.5
Hash.Target......: *******************:********
Time.Started.....: Wed Mar 31 19:37:20 2021 (1 min, 20 secs)
Time.Estimated...: Wed Mar 31 19:38:40 2021 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:   271.4 kH/s (5.47ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#2.........:   270.6 kH/s (5.79ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Speed.#*.........:   542.0 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 37748736
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: Hello17694712 -> Hello18874359
Candidates.#2....: Hello16515064 -> Hello17694711
Hardware.Mon.#1..: Temp: 51c Fan:  0% Util:  6% Core:1410MHz Mem:6801MHz Bus:16
Hardware.Mon.#2..: Temp: 55c Fan: 33% Util:  0% Core:1410MHz Mem:6801MHz Bus:1

**Comment by matrix** [comment]
@LLH-l look here

```
$ ./hashcat --hash-info -m 2611
hashcat (v6.1.1-191-g57213e6c6) starting...

Hash Info:
==========

Hash mode #2611
  Name................: vBulletin < v3.8.5
  Category............: Forums, CMS, E-Commerce
  Slow.Hash...........: No
  Password.Len.Min....: 0
  Password.Len.Max....: 256
  Salt.Type...........: Generic
  Salt.Len.Min........: 0
  Salt.Len.Max........: 256
  Kernel.Type(s)......: pure, optimized
  Example.Hash.Format.: plain
  Example.Hash........: 28f9975808ae2bdc5847b1cda26033ea:308
  Example.Pass........: hashcat
  Benchmark.Mask......: ?b?b?b?b?b?b?b
```

**Benchmark.Mask......: ?b?b?b?b?b?b?b**

If you want to reach the benchmark speed, you need to use -a 3.

**Comment by ghost** [comment]
@matrix
Hello,

If there is no better solution,  can only use a3 mode at present

**Comment by jsteube** [comment]
The original question was answered. If there's a new one, please create a new issue using the new issue template.
