### ISSUE TITLE
Error in Hashcat

### ISSUE THREAD

**Issue by MojoMoe** [hashcat/hashcat#2733]
I keep getting this error after about a minute of starting hashcat and I am not sure what is causing it:

Platform: Ubuntu 20.04 with AMD ATI Radeon HD 7970

$ hashcat --force --stdout ~/words.txt -r /usr/local/share/doc/hashcat/rules/dive.rule | hashcat --force -m 11300 hash.txt

Error below:
*******************************************************

clGetEventProfilingInfo(): CL_PROFILING_INFO_NOT_AVAILABLE

Session..........: hashcat
Status...........: Running
Hash.Name........: Bitcoin/Litecoin wallet.dat
Hash.Target......: $bitcoin$64$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...0$2$00
Time.Started.....: Sat Mar 20 13:53:57 2021, (1 min, 10 secs)
Time.Estimated...: Sat Mar 20 13:55:07 2021, (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:     3862 H/s (7.37ms) @ Accel:64 Loops:16 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 262144
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:2336-2352
Candidates.#1....: Incendie -> pouvoir1990

Session..........: hashcat
Status...........: Error
Hash.Name........: Bitcoin/Litecoin wallet.dat
Hash.Target......: $bitcoin$64$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...0$2$00
Time.Started.....: Sat Mar 20 13:53:57 2021, (1 min, 10 secs)
Time.Estimated...: Sat Mar 20 13:55:07 2021, (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:     3862 H/s (7.37ms) @ Accel:64 Loops:16 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 262144
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:2336-2352
Candidates.#1....: Incendie -> pouvoir1990
Started: Sat Mar 20 13:53:48 2021
Stopped: Sat Mar 20 13:55:08 2021

**Comment by LLH-l** [comment]
Hi..
Brother,  you use those tools and methods to get the BTC hash value

**Comment by ghost** [comment]
Hi..
Brother, what tools and methods do you use to get the BTC hash value

**Comment by MojoMoe** [comment]
> Hi..
> Brother, what tools and methods do you use to get the BTC hash value

You can use this python script or Google bitcoin2john.py 

https://github.com/openwall/john/blob/bleeding-jumbo/run/bitcoin2john.py

**Comment by ghost** [comment]
Thanks..

**Comment by jsteube** [comment]
What you see here is the driver reporting the feature CL_PROFILING_INFO_NOT_AVAILABLE is not supported. I think I can rewrite hashcat to disable this feature if it's not supported by the driver. Do you still need this fixed? I think it will occur only for very old drivers.

**Comment by MojoMoe** [comment]
> What you see here is the driver reporting the feature CL_PROFILING_INFO_NOT_AVAILABLE is not supported. I think I can rewrite hashcat to disable this feature if it's not supported by the driver. Do you still need this fixed? I think it will occur only for very old drivers.

Yes if you can fix it that would be much appreciated. It is happening on old amdgpu drivers but also on current Mesa drivers on Ubuntu 20.04. Cheers.

**Comment by jsteube** [comment]
OK, so I just checked the OpenCL specs for OpenCL and it is a hard requirement for the OpenCL runtime to support profiling. You can see here: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clCreateCommandQueue.html

There's no valid error return code for CL_PROFILING_INFO_NOT_AVAILABLE. So this is not a hashcat issue. It is a OpenCL runtime issue. In your case a MESA OpenCL runtime. This issue needs to be fixed inside MESA.
