### ISSUE TITLE
Could someone tell me what is wrong with my command?

### ISSUE THREAD

**Issue by mother2110** [hashcat/hashcat#2734]
E:\caps\hashcat-6.1.1\hashcat-6.1.1>**hashcat.exe -m 2500 -a3 -1 ?u?d ?1?1?1?1?1?1?1?1 hs1.hccapx**
hashcat (v6.1.1) starting...

* Device #1: CUDA SDK Toolkit installation NOT detected.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL API (OpenCL 1.2 CUDA 11.2.152) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: GeForce RTX 2080 Ti, 10112/11264 MB (2816 MB allocatable), 68MCU

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

**?1?1?1?1?1?1?1?1: Invalid argument**

Started: Mon Mar 22 12:22:32 2021
Stopped: Mon Mar 22 12:22:33 2021

E:\caps\hashcat-6.1.1\hashcat-6.1.1>

**Comment by Banaanhangwagen** [comment]
Try to put your hash, in your case the hccapx, next to the -m.
Like this: `hashcat.exe -m 2500 hs1.hccapx -a3 -1 ?u?d ?1?1?1?1?1?1?1?1`

If this answers your question, please close this issue.
(For other user-questions or how-to's, consider next time the Hashcat-forum.)

**Comment by mother2110** [comment]
That was it . Thanks
