### ISSUE TITLE
Cant Open It

### ISSUE THREAD

**Issue by TSVskillzYT** [hashcat/hashcat#2737]
I can't open Hashcat, When I open It It closes automatically.

**Comment by jsteube** [comment]
You mean like "When I click on hashcat.exe a black window flashes up and then disappears" ? Please see hashcat FAQ.

**Comment by TSVskillzYT** [comment]
how do i fix it?

**Comment by roycewilliams** [comment]
@TSVskillzYT - just as jsteube said, read the FAQ. Your issue is covered in the first entry.

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions

Please use the hashcat forums for future support questions.
