### ISSUE TITLE
BUG | oclHashcat | latest beta | -m 4900

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#274]
Running a straight a dic attack with or without rules throws a build error with 4900's kernel, hybrid and mask mode are ok.

Please emulate to confirm

> ./beta/oclHashcat-2.10$ ./oclHashcat64.bin -a 0 -m 4900 ~/Dropbox/hash.txt  /media/user/186CCB366CCB0E06/wordlists/rockyou-top50k.txt
> oclHashcat v2.01 (g19c548c) starting...
> 
> Device #1: Hawaii, 2721/3804 MB allocatable, 947Mhz, 40MCU
> Device #2: AMD FX(tm)-6300 Six-Core Processor, skipped
> 
> Hashes: 12 hashes; 12 unique digests, 12 unique salts
> Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
> Rules: 1
> Applicable Optimizers:
> - Zero-Byte
> - Precompute-Init
> - Precompute-Merkle-Demgard
> - Early-Skip
> - Not-Iterated
>   Watchdog: Temperature abort trigger set to 90c
>   Watchdog: Temperature retain trigger set to 80c
> 
> Device #1: Kernel /home/user/beta/oclHashcat-2.10/kernels/m04900_a0.5266cfd8.kernel not found in cache! Building may take a while...
> 
> === Build failed, retry with optimization disabled ===
> 
> ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE
> 
> === Build Options : -I/home/user/beta/oclHashcat-2.10/ -DVENDOR_ID=4098 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4 ===
> 
> === Build Log (start) ===
> "/tmp/OCL6869T1.cl", line 125: error: identifier "w0" is undefined
>       const u32x out_len = apply_rules_vect (pw_buf0, pw_buf1, pw_len, rules_buf, il_pos, w0, w1);
>                                                                                           ^
> 
> "/tmp/OCL6869T1.cl", line 125: error: identifier "w1" is undefined
>       const u32x out_len = apply_rules_vect (pw_buf0, pw_buf1, pw_len, rules_buf, il_pos, w0, w1);
>                                                                                               ^
> 
> "/tmp/OCL6869T1.cl", line 458: error: identifier "w0" is undefined
>       const u32x out_len = apply_rules_vect (pw_buf0, pw_buf1, pw_len, rules_buf, il_pos, w0, w1);
>                                                                                           ^
> 
> "/tmp/OCL6869T1.cl", line 458: error: identifier "w1" is undefined
>       const u32x out_len = apply_rules_vect (pw_buf0, pw_buf1, pw_len, rules_buf, il_pos, w0, w1);
>                                                                                               ^
> 
> 4 errors detected in the compilation of "/tmp/OCL6869T1.cl".
> Frontend phase failed compilation.
> 
> === Build Log (end) ===
> Device #1: Kernel /home/user/beta/oclHashcat-2.10/OpenCL/m04900_a0.cl build failure. Proceed without this device.
> 
> Checking for weak hashes...Unhandled signal in divisionErrorHandler()
> Aborted (core dumped)
> user@Ubuntu-Server:~/beta/oclHashcat-2.10$

**Comment by philsmd** [comment]
this is a temporary unavoidable and well-known problem because of the refactoring/changes to new code for all kernels, see all the "Cleanup -m xxx -a y kernel to latest standard"  commits here: https://github.com/hashcat/oclHashcat/commits/master
Soon the -m 4900 kernel will be changed too and working again.

Thanks anyway for noticing

**Comment by jsteube** [comment]
Fixed in latest beta
