### ISSUE TITLE
Google Cloud Hashcat error HC error: clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR HC error: ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

### ISSUE THREAD

**Issue by mijowe** [hashcat/hashcat#2741]
running on google cloud vm instance
keep getting
Start chunk...
HC error: clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR
HC error: ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

when i run python3 agent.zip on hashtopolis they set as cpu only please can someone help

less /proc/cpuinfo

processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 85
model name : Intel(R) Xeon(R) CPU
stepping : 7
microcode : 0x1
cpu MHz : 3100.192
cache size : 25344 KB
physical id : 0
siblings : 4
core id : 0
cpu cores : 2
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
bugs : spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa
bogomips : 6200.38
clflush size : 64
cache_alignment : 64
address sizes : 46 bits physical, 48 bits virtual
power management:

processor : 1
vendor_id : GenuineIntel
cpu family : 6
model : 85
model name : Intel(R) Xeon(R) CPU
stepping : 7
microcode : 0x1
cpu MHz : 3100.192
cache size : 25344 KB
physical id : 0

lspci

00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 03)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:03.0 Non-VGA unclassified device: Red Hat, Inc. Virtio SCSI
00:04.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:05.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG

**Comment by matrix** [comment]
Hi, you have to use the machines with the gpu. I tested them two years ago, everything works fine.

**Comment by mijowe** [comment]
theoretically if i can run hash cat on this server i should be able to run hashtopolis

**Comment by ventaquil** [comment]
What is the result of `clinfo` command?

**Comment by 0xVavaldi** [comment]
It seems as though you failed to install OpenCL. It might also be required to reboot the machine after this installation to get it functioning.

**Comment by Chick3nman** [comment]
This is not a hashcat issue as it appears you have simply selected a VM instance type with no attached GPU. This issue is better suited to the forums if anything, please discuss further there.
