### ISSUE TITLE
HashCat has stopped working

### ISSUE THREAD

**Issue by standyyyy** [hashcat/hashcat#2743]
I recently noticed that when I ran Hashcat6.1.1, a stopped popover popped up. This didn't happen six months ago. Anyone? What should I do?
![image](https://user-images.githubusercontent.com/39285732/113494713-81405800-951d-11eb-92be-ddfc5ff1d35e.png)
Try version 5.1. It works, but it's slow.

**Comment by jsteube** [comment]
Maybe a driver problem? Did you try to update to latest driver? Also please remove kernels folder in hashcat installation because it contains cached kernels. Is important that if you update hashcat to a new version that you unpack into a fresh folder not an existing one.

**Comment by standyyyy** [comment]
We have tried to update the driver, but the results are the same. It is not clear if this is a Windows update problem, versions under 6.1.1 will work, but it is slow




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hashcat/hashcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 凌晨0:13
***@***.***&gt;;
抄送:&nbsp;"草闲 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hashcat/hashcat] HashCat has stopped working (#2743)





 
Maybe a driver problem? Did you try to update to latest driver? Also please remove kernels folder in hashcat installation because it contains cached kernels. Is important that if you update hashcat to a new version that you unpack into a fresh folder not an existing one.

**Comment by jsteube** [comment]
I need more details to reproduce the problem locally. Please provide me with everything I need to reproduce locally.

**Comment by jsteube** [comment]
OP please update

**Comment by standyyyy** [comment]
Sorry, I've been busy lately and forgot to check your reply , please let me know what information or files you need from me, or system version, environment or whatever.

**Comment by jsteube** [comment]
I need every Information so that I can reproduce locally. Think of as you being a developer of application XY and someone sends you a bug report, what would you expect from him to report to you.

Before you going to collect everything make sure you have updated all your drivers to the latest version. There's also a new hashcat version.

**Comment by jakubpalacz** [comment]
I have the same problem. Any solution ?

**Comment by jakubpalacz** [comment]
I installed cuda, that fixed problem.

**Comment by jsteube** [comment]
I don't see how CUDA will do anything to help a problem with AMD drivers. CUDA is for NV only. Still waiting for @standyyyy to report back with new information.

**Comment by standyyyy** [comment]
I'm very sorry, but now I have time to continue to give feedback.
Before giving feedback, I pulled down the latest 6.2.1 to try, and it still has the same error
![微信图片_20210606145526](https://user-images.githubusercontent.com/39285732/120915694-c3ca1080-c6d7-11eb-868c-6b86646f1b15.png)
Let me talk about the computer configuration first:
System used：windows10
cpu：amd 2700x
GPU：vega56
Use hashcat -I result：
![微信图片_20210606145628](https://user-images.githubusercontent.com/39285732/120915731-0c81c980-c6d8-11eb-9c49-7ca40407790b.png)
The following is the log of hashcat
[hashcat.log](https://github.com/hashcat/hashcat/files/6603766/hashcat.log)

**Comment by jsteube** [comment]
OK, thanks for clarification. This is clearly an AMD driver problem. This is not a hashcat problem. There's nothing we can do. 

AMD drivers are very bad for OpenCL. They work with simple OpenCL code, but with complex OpenCL code it fails. The only way to get it working is to switch to ROCm drivers, which is much better. But ROCm exists for Linux only, so you need to switch to Linux to use hashcat if you want to use this GPU and in particular with hash-mode 11600. More simple kernels like hash-mode 0 or 1000 should work.
