### ISSUE TITLE
Usage Help

### ISSUE THREAD

**Issue by reteps** [hashcat/hashcat#2746]
I want to run hashcat in mask mode until it finds a hash that starts with `0e` and the rest of the digits are numbers. Basically I want to define a custom "success" function. How can I do this?

I have a salt, and I need a hash that starts with `0e`.

The hash needs to be in the format `0eDIGITS`, e.g. `0e1234` but not `0e1ea2`. RE: /^0+e[0-9]+$/
```
# e361bfc569ba48dc is salt
hashcat -m 0 -a 3 e361bfc569ba48dc?a?a?a?a?a
```

**Comment by Chick3nman** [comment]
You are trying to generate magic hashes. Hashcat does not have the ability to do this without modification to the kernel/module source. This is more of a topic for the forums than for github, there has already been significant work in the space of finding magic hashes elsewhere, including forks of hashcat.

**Comment by roycewilliams** [comment]
For the record, @reteps, I've long argued that such functionality should be explicitly included in the cracking suites - you're not crazy. :)

https://roycebits.blogspot.com/2015/10/hash-filtering-more-than-vanity.html
