### ISSUE TITLE
[Feature] Consider adding support for AVX-512 (SLIDE)

### ISSUE THREAD

**Issue by raidneural** [hashcat/hashcat#2747]
Hi, thanks for the awesome project!

I discovered this paper today: https://arxiv.org/abs/1903.03129:

> Using just a CPU, SLIDE drastically reduces the computations during both training and inference outperforming an optimized implementation of Tensorflow (TF) on the best available GPU

They have a repo: https://github.com/keroro824/HashingDeepLearning

Wondering if this is applicable to hashcat - would be awesome to see the above performance cracking hashes in CPUs :)

Thanks for your time!

**Comment by jsteube** [comment]
Hashcat supports 16 element vectors since many years. As soon OpenCL drivers add support for AVX-512, hashcat will automatically make use of them without the need for a change.
