### ISSUE TITLE
hashcat does not work with a known correct password

### ISSUE THREAD

**Issue by gomin1d** [hashcat/hashcat#2748]
good day

I have a microsoft office 2013 document and here is its hash:
```
$office$*2013*100000*256*16*6e3d225ef9cd9240d517461f987cdf1b*5e1240f0d56709c40bc0726738858750*131655035ceb748c567387bcd7081db094df4bbe6ea044e410fcef0d400331a5
```

And here is the correct password with which I can open the document:
```
Леша
```

I saved the hash to a `hash.txt` file.

I saved the password in the word `pass.txt`.

then I execute the following command to iterate over the dictionary:
```
hashcat.exe -w 1 -m 9600 -a 0 hash.txt pass.txt
```

but it fails to verify the correct password: 
```
Session..........: hashcat
Status...........: Exhausted
Hash.Name........: MS Office 2013
Hash.Target......: $office$*2013*100000*256*16*6e3d225ef9cd9240d517461...0331a5
Time.Started.....: Sat Apr 10 04:57:57 2021 (6 secs)
Time.Estimated...: Sat Apr 10 04:58:03 2021 (0 secs)
Guess.Base.......: File (pass.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        0 H/s (0.41ms) @ Accel:1 Loops:8 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: ╨Ы╨╡╤И╨░ -> ╨Ы╨╡╤И╨░
Hardware.Mon.#1..: Temp: 55c Fan: 30%

Started: Sat Apr 10 04:57:51 2021
Stopped: Sat Apr 10 04:58:05 2021
```

I tried different encodings of the dictionary, since the password consists of Russian characters. but I still could not find the correct encoding. or is that not the problem?

**Comment by jsteube** [comment]
This is a known problem when it comes to real unicode handling. The kernel automates the process in a very naive way. That's important to be fast but for slow hashes like MS Office 2013 it shouldn't matter. It's just that we do not have any real utf8 to etf16 conversion code yet.

As an alternative, you can modify the code in OpenCL/m09600-pure.cl  slightly:

find
```
sha512_update_global_utf16le_swap (&ctx, pws[gid].i, pws[gid].pw_len);
```
and replace with
```
sha512_update_global_swap (&ctx, pws[gid].i, pws[gid].pw_len);
```
Then remove kernels/ folder to make sure hashcat will not use the cached kernels.

Then you can run hashcat with the following parameters added:
```
 --encoding-from utf8 --encoding-to utf16le --self-test-disable 
```

Then it should work as expected but make sure the wordlist is stored in utf8.

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/d343e2c4a0699bb8a6fd8d47b06fe4f5a157c5e8

**Comment by gomin1d** [comment]
many thanks!!!
