### ISSUE TITLE
Bug: pwdump format parsing error

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2754]
Behavior when parsing NTDS files in pwdump format is inconsistent when extraneous data is present at the end of the lines.

The below pair of hashes clearly contains extra data at the end of the hash line:
```
corp.test.local\testuser0:10:299BD128C1101FD6C2265B23734E0DAC:6B52391994360119D932BBDE0846D255::: (pwdLastSet=2000-01-00 00:00) (status=Enabled)
corp.test.local\testuser1:11:299BD128C1101FD61D71060D896B7A46:3BA46F47616F0B667ED9AFBDD296AADF::: (pwdLastSet=2000-01-00 00:00) (status=Enabled)
```
Both hashes are correctly thrown out by hashcat
```
Hashfile 'example0.hash' on line 1 (corp.t...00-01-00 00:00) (status=Enabled)): Token length exception
Hashfile 'example0.hash' on line 2 (corp.t...00-01-00 00:00) (status=Enabled)): Token length exception
No hashes loaded.
```
However, if the first line does NOT contain this extra data, like this:
```
corp.test.local\testuser0:10:299BD128C1101FD6C2265B23734E0DAC:6B52391994360119D932BBDE0846D255:::
corp.test.local\testuser1:11:299BD128C1101FD61D71060D896B7A46:3BA46F47616F0B667ED9AFBDD296AADF::: (pwdLastSet=2000-01-00 00:00) (status=Enabled)
```
The pwdump format parser kicks in, detects it as pwdump, and begins to parse the entire file. The second line is ingested and parsed instead of being thrown out. The hashes do appear to be parsed correctly and both -m 3000 and -m 1000 appear to work when cracking the hashes due to the use of the separator as anchors. The inconsistent behavior regarding throwing out bad hash lines and then intake of lines containing unexpected data leads me to believe there is potential for memory/buffer issues here, at the very least unnecessary memory consumption.

**Comment by jsteube** [comment]
I just checked the code, there's no problem with the extra data at the end of the line. So there's no memory issue. The only thing that's missing is the extra data itself - it's lost.

**Comment by Chick3nman** [comment]
Alright, that's definitely best case. Should we change behavior to be consistent though? Even if it doesn't break anything, it's still inconsistent whether the lines are rejected or not based on how far into the process the very first line gets.

**Comment by jsteube** [comment]
I don't think we need to change anything. The user has to use --show --username anyway so they expect a different output than input anyway. If you have any clear ideas how it should look like let me know.

**Comment by Chick3nman** [comment]
I think that is fair, and given that there is no consequence from the extra data, this is probably not an issue we need to change right now but something to think about. I will consider some ways to improve it, but for now the issue can be closed. If i find a better way, i'll PR it and/or reopen the issue.
