### ISSUE TITLE
Dip in Keepass benchmark performance

### ISSUE THREAD

**Issue by donwayo** [hashcat/hashcat#2756]
Hi, 

I've been collecting hashcat benchmarks and comparing them. I noticed that in newer versions of hashcat (6.x.x) the performance for Keepass has dropped substantially. 

I made a post in the forum with the details: https://hashcat.net/forum/thread-10011.html

**Comment by jsteube** [comment]
I don't see how you can compare databases with different iteration counts? KeePass performance does not only depend on the compute device but also on the device which created the database in the first place. The faster the CPU of that system, the higher the iteration count. It's pretty clear to me that a database with 4 times the iterations is 4 times slower. It's the opposite. The speed is much faster now.

**Comment by donwayo** [comment]
I missed the iteration counts! I wrongly assumed that they would stay constant between hashcat versions. I see that older versions used 6000 iterations and the 6.x.x versions use 24569 in the benchmarks (4x). So nothing to see here.
