### ISSUE TITLE
System unusable when running Hashcat 6.1.1 with Nvidia GPUs on Ubuntu 20.04

### ISSUE THREAD

**Issue by MojoMoe** [hashcat/hashcat#2761]
System unusable when running Hashcat 6.1.1 with Nvidia RTX 3060  x2 (two of the same architecture GPUs, 1 Asus 1 Zotac).

I am using this command:
hashcat -a 1 -m 11300 hashes.txt ~/passwordlist1.txt ~/numbers.txt  --status --status-timer 30

I have tried to use -w 1 and 2 and 3 and 4 but they are all behaving the same. In Windows 10, the system is 100% usable while running the same command on Hashcat 6.1.1

$nvidia-smi
Sat Apr 17 13:37:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3060    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   43C    P3    26W / 170W |   1133MiB / 12051MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3060    Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   40C    P8    14W / 170W |      5MiB / 12053MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1162      G   /usr/lib/xorg/Xorg                713MiB |
|    0   N/A  N/A      1416      G   /usr/bin/gnome-shell              415MiB |
|    0   N/A  N/A      2072      G   /usr/lib/firefox/firefox            2MiB |
|    1   N/A  N/A      1162      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

$ neofetch
            .-/+oossssoo+/-.               
        `:+ssssssssssssssssss+:`           ----------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.8.0-49-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 27 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2515 (dpkg), 8 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.0.17 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 5120x2880, 3840x2160 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-6700 (8) @ 4.000GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 2503 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA 03:00.0 NVIDIA Corporation Device 2503 
      -+sssssssssssssssssyyyssss+-         Memory: 3547MiB / 15957MiB

**Comment by jsteube** [comment]
Please retry with beta https://hashcat.net/beta/ or GitHub master

**Comment by MojoMoe** [comment]
> Please retry with beta https://hashcat.net/beta/ or GitHub master

I have installed the master branch (current) Hashcat just now and tested with an RTX 3070 and the behaviour is still the same on Ubuntu 20.04 unfortunately

**Comment by MojoMoe** [comment]
> Please retry with beta https://hashcat.net/beta/ or GitHub master

Also noticing that the system is almost unusable (extremely heavy lagging) while using a secondary GPU AMD HD 7970 for display purposes only, while Hashcat (current master branch version) is running on the RTX 3070. If I quit Hashcat on the RTX 3070, the AMD HD 7970 displays without any lags. 

EDITED:
I have had the chance to test the same PC setup (dual-boot) in Windows 10 using the stable release 6.1.1 and I am 100% OK to use the PC and the display is fine, no lags on the AMD HD 7970 card while Hashcat is running on the RTX 3070. Seems to be a Linux issue only, as far as I can tell. Not sure if it is the OS, Linux drivers or Hashcat.

**Comment by jsteube** [comment]
Is really strange, I can't reproduce. However, I think most people use hashcat on linux on headless systems only. So there's just not many feedback from this kind of setup so we can't rule out that there's actually a problem. I find it also strange that the problem also occurs if you use the hd7970. Must have been a nightmare to get NV and AMD driver both working in parallel :)

One thing you could try is to optimize the xorg.conf settings.

```
nvidia-xconfig -s -a --force-generate --allow-empty-initial-configuration --cool-bits=12 --registry-dwords="PerfLevelSrc=0x2222" --no-sli --connected-monitor="DFP-0" -o /etc/X11/xorg.conf

sed -i '/Driver/a \ \ \ \ Option         "Interactive" "False"' /etc/X11/xorg.conf
```

Especially the second command seems relevant. Don't forget to restart X11 afterwards.

**Comment by jsteube** [comment]
OP please update

**Comment by jsteube** [comment]
No response from OP, therefore closing. Feel free to reopen if needed.
