### ISSUE TITLE
New Mode

### ISSUE THREAD

**Issue by nikolaigut** [hashcat/hashcat#2763]
Hi guys,

I need to crack self generated hashes with the format `md5($pass-md5($pass))` (yes it is a hyphen  between $pass and md5).

Is it possible to implement this mode? Or is there another chance to speed up the hashcat with rules or something to crack these hashes?

Many thanks

**Comment by jsteube** [comment]
For this mode you need to implement a new hash-mode with specific kernel. There's no way to work around using rules.

**Comment by nikolaigut** [comment]
How can I (or anyone) implement this?

**Comment by jsteube** [comment]
Please see here: https://github.com/hashcat/hashcat/blob/master/docs/hashcat-plugin-development-guide.md

**Comment by nikolaigut** [comment]
Many thanks, I will try it.
