### ISSUE TITLE
Bug: Race condition in potfile check during removal of empty hashes

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#2766]
Some algorithms have known "empty" hashes, such as `aad3b435b51404ee` for LM (-m 3000). We check for these and throw them out before the session starts, marking them as  `INFO: Removed 1 hash found in potfile.` however there is a race condition here that can lead to some issues. If no hashcat.potfile exists in place and hashcat has to create it for the very first time, this leads to the above INFO message not being displayed and the hash may not be removed from the pool of hashes correctly. This leads to it never cracking, giving instances that appear as if there is 1 hash remaining. However, upon using --show, due to the potfile now being in place from that run, all hashes will appear cracked. Likewise, --left will display 0 hashes left.

Suggested additional fix here is to commit the empty hash to the potfile. It appears that this hash is not added to the potfile directly, at least in the case of -m 3000. More testing needed.

**Comment by jsteube** [comment]
OK, I can reproduce this behavior using -a 3, but not using -a 0. However, could you explain why you think this is a race condition?

**Comment by jsteube** [comment]
OK, there was another problem related to --potfile-disabled. This is what caused the confusion.

**Comment by Chick3nman** [comment]
This issue appears to be a race between the initial potfile creation and the checks made by the kernel for empty hashes, If the potfile exists before the check, it completes successfully. If the potfile does not exist yet, the check will fail to complete while the file is being created. It should wait for this creation or not fail if the potfile isn't there since it doesnt actually rely on the potfile, it just makes use of the potfile function to mark the hash.

**Comment by jsteube** [comment]
Should be fixed with commit https://github.com/hashcat/hashcat/commit/56f47cabe21e819a3c93ec7f251a3508a7c2cba2

Please test

**Comment by Chick3nman** [comment]
Test passed, appears to be working as intended. There's a typo in the message but it will be fixed separately.
