### ISSUE TITLE
Strange data in input of .cl program

### ISSUE THREAD

**Issue by korenkonder** [hashcat/hashcat#2770]
Recently I've installed Windows 20H2. And after I was trying to run hashcat like this
`./hashcat -b -m 26800 >> log_26800.txt`
it prints data in log file in loop. And data is kinda weird. First pass or first two passes (which is or which are self test) are working normal, but after data starts to be kinda weird. Algorithm is [this](https://tanjent.livejournal.com/756623.html) but modified that way that all `lower case` ASCII characters becoming `UPPER CASE`. 
Source files as well as log are pinned to this message
[early_murmurhash_modified.zip](https://github.com/hashcat/hashcat/files/6368930/early_murmurhash_modified.zip)

Also I wanted to notice that exact same thing happens with other algorithm. In this case it's FNV 1a 64 bit that was modified that way that on output lower 32 bits are XOR'ed with higher 32 bits but output is still 64 bits
[fnv1a64_modified.zip](https://github.com/hashcat/hashcat/files/6368944/fnv1a64_modified.zip)

**Comment by jsteube** [comment]
There's no such hash-mode in hashcat.
