### ISSUE TITLE
Strange data in input of .cl program [Part 2]

### ISSUE THREAD

**Issue by korenkonder** [hashcat/hashcat#2771]
I don't know why @jsteube had closed my previous issue https://github.com/hashcat/hashcat/issues/2770#issuecomment-826041178. Some time ago I had posted this [request](https://github.com/hashcat/hashcat/issues/2738). And since noone had added that hashmode I decided to write module (for Early Murmurhash that is used in one game) on my own. Also I decided to add module for another algorithm (for modified FNV-1a 64 bit which is used in that one game too). Both modules worked fine on my previous system (Win 10 Build 17763.1911) but on current one (Win 10 Build 19042.928) both don't work. Only thing that I had done is rebasing local git to the latest commit on GitHub and building it. I also cleaned kernel folder before each run as developement guide suggests. I've tried to reinstall drivers but that doesn't help. Problem is still here. But for other algos that are in repo at this moment all goes fine in mode `-a 3`. Currently I'm developing only `-a 3` mode for both modules since that's the only thing that I was interested to do. I can't go back to previous install because I've reinstalled system from USB drive without saving previous information. Also I can't test this on another PC since it's the only PC I have

**Comment by Chick3nman** [comment]
Your issue is with code we did not write or allow into the repo, therefore we can not support it here. It was closed because this is not the place to have that discussion essentially. If you would like help writing your kernels, try the forums.

**Comment by korenkonder** [comment]
Oh... Sorry then. Didn't knew about forums. And thank you
