### ISSUE TITLE
Mask of 32 placeholders (Integer Overflow)

### ISSUE THREAD

**Issue by juniobranco** [hashcat/hashcat#2772]
Hi,
Recently, I was hit with a Ransomware (QLocker) which encrypted my files on my NAS... 
The encryption done used 7z ( which I obtained the hash already). I also know that the password given by them ( after suppose payment) would be of 32 characters long.

Hence, I wanted to use my GPU to perform brute-force/mask attack such that I can resolve this issue for myself and others.
However, whe defining the keyspace of 32 char length it throws an integer overflow.

I understand the number of combination is... astronomical but I was wondering if with a recent GPU it could possibly brute force with reasonable time..

`C:\Hashcat\hashcat-6.1.1>hashcat.exe -m 11600 -a 3 ..\hash.txt -1 ?d?u?l ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1
hashcat (v6.1.1) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce RTX 3090, 20452/24576 MB, 82MCU

OpenCL API (OpenCL 3.0 CUDA 11.3.55) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3090, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1292 MB

**Integer overflow detected in keyspace of mask: ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1**

Started: Sun Apr 25 00:01:56 2021
Stopped: Sun Apr 25 00:02:01 2021`

**Comment by Chick3nman** [comment]
You can not crack a 32 character password before the sun explodes and our solar system dies. The keyspace is so large that it overflows the u32 storing it. This is essentially a "won't fix" but really it's a "shouldn't have to" because while we can, it just simply doesn't make sense. Cracking something like that can not happen so there's no reason for us to try and support it.
