### ISSUE TITLE
Integer overflow detected in keyspace of mask: ?1?2?2?2?2?2?2?3?3?3?3?d?d

### ISSUE THREAD

**Issue by JLT032** [hashcat/hashcat#2776]
to further the senseless brute forcing i'm attempting i repeatedly pressed 's' and 'b', maybe also accidentaly 'n', either way this resulted in the below

Session..........: hashcat                       
Status...........: Bypass
Hash.Name........: LUKS
Hash.Target......: hascat.luks
Time.Started.....: Wed Apr 28 08:44:38 2021 (13 secs)
Time.Estimated...: Next Big Bang (282023861 years, 333 days)
Guess.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d [12]
Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined 
Guess.Queue......: 2/5 (40.00%)
Speed.#1.........:      429 H/s (69.05ms) @ Accel:32 Loops:512 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 0/3813661310945771520 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/61510666305576960 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:89088-89600
Candidates.#1....: sarierinere1 -> sn5jerinere1
Hardware.Mon.#1..: Temp: 78c Fan: 74% Core:1801MHz Mem: 800MHz Bus:0

Integer overflow detected in keyspace of mask: ?1?2?2?2?2?2?2?3?3?3?3?d?d

b

Next dictionary / mask in queue selected. Bypassing current one.

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => Integer overflow detected in keyspace of mask: ?1?2?2?2?2?2?2?3?3?3?3?d?d?d

Integer overflow detected in keyspace of mask: ?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d

**Comment by jsteube** [comment]
Is good, hashcat detected a too big mask to process.

**Comment by JLT032** [comment]
hashcat had been running for 2 days already, the mask specified is 8 char long and set by 

`-1 S -2 ?u -3 ?d ?1?2?3?a?a?a?a?a`

**Comment by jsteube** [comment]
This was the mask running:

```
Guess.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d [12]
Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
```

**Comment by jsteube** [comment]
It's the default mask btw. So you didn't specify a mask on the commandline

**Comment by JLT032** [comment]
this is what i used 

hashcat -m 14600 -i --increment-min=8 --increment-max=16 -a3 -w3 hascat.luks -1 S -2 ?u -3 ?d ?1?2?3?a?a?a?a?a

how can it  be hashcat runs fine for 2 days with this mask and only when i press [s] a few times, then [b] (accidentally also [n]) and it only then throws the message and exits ?

**Comment by jsteube** [comment]
Can't reproduce:

```
root@ht:~/hashcat# ./hashcat -m 400 example400.hash  -i --increment-min=8 --increment-max=16 -a3 -w3  -1 S -2 ?u -3 ?d ?1?2?3?a?a?a?a?a
hashcat (v6.1.1-278-g33d95348f) starting...

CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce GTX 980, 3963/4043 MB, 16MCU

OpenCL API (OpenCL 2.1 LINUX) - Platform #1 [Intel(R) Corporation]
==================================================================
* Device #2: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, skipped

OpenCL API (OpenCL 3.0 CUDA 11.3.55) - Platform #2 [NVIDIA Corporation]
=======================================================================
* Device #3: NVIDIA GeForce GTX 980, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 281 MB

[s]tatus [p]ause [b]ypass [c]heckpoint [q]uit => b

Next dictionary / mask in queue selected. Bypassing current one.

Session..........: hashcat                       
Status...........: Bypass
Hash.Name........: phpass
Hash.Target......: $H$9y5boZ2wsUlgl2tI6b5PrRoADzYfXD1
Time.Started.....: Wed Apr 28 10:00:33 2021 (1 sec)
Time.Estimated...: Tue May  4 16:13:00 2021 (6 days, 6 hours)
Guess.Mask.......: ?1?2?3?a?a?a?a?a [8]
Guess.Charset....: -1 S, -2 ?u, -3 ?d, -4 Undefined 
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  3720.5 kH/s (64.46ms) @ Accel:32 Loops:1024 Thr:1024 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 2621440/2011830437500 (0.00%)
Rejected.........: 0/2621440 (0.00%)
Restore.Point....: 2621440/2011830437500 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1024
Candidates.#1....: SP4m2000 -> SC8v9999
Hardware.Mon.#1..: Temp: 82c Fan: 45% Util: 99% Core:1265MHz Mem:3004MHz Bus:16

Started: Wed Apr 28 10:00:31 2021
Stopped: Wed Apr 28 10:00:35 2021
root@ht:~/hashcat# 
```

**Comment by JLT032** [comment]
Thanks anyway. 

Try alternating between [s] and [b] a few times then press [b] [n] [s]

**Comment by Adrianoross** [comment]
I am having same issues here
length 13. Tried the mask but getting integer overflow detected in keyspace of mask. Does it mean i cant find a 13 length password even knowing just few words from the whole length?
