### ISSUE TITLE
Performance issues potentially related to UTF kernel code

### ISSUE THREAD

**Issue by ecostin** [hashcat/hashcat#2778]
The following happens with NTLM hashes (m1000), pure kernel (not optimized kernel), attack mode dictionary + derivation rules. Hardware and driver info:

```
CUDA.Version.: 11.3

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1582
  Memory.Total...: 11178 MB
  Memory.Free....: 11035 MB

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.3.55

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1582
    Memory.Total...: 11178 MB (limited to 2794 MB allocatable in one block)
    Memory.Free....: 0 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 465.19.01
```
Running hashcat with:
```
wc -l dict.rules dict.txt input.pw 
    35406 dict.rules
 35136034 dict.txt
     7697 input.pw
hashcat -r dict.rules -m1000 -a0 input.pw dict.txt -w4
```
Before commit https://github.com/hashcat/hashcat/commit/d343e2c4a0699bb8a6fd8d47b06fe4f5a157c5e8 the hash rate used to be 1950181895, after it is 553872753
Furhter on, after commit https://github.com/hashcat/hashcat/commit/ee26805138dcb4627e94a9b7ca7125d47d8b7297 the hash rate becomes 217110457

When running with optimized kernel (-O) the hash rate is the same in all cases, around 10917775979.

Both CUDA and OpenCL modes are affected. The above numbers are for OpenCL. No other modes seem to be affected, optimized kernels (-O) appear also to be ok. I did not test other hash types.

Except for the hashcat commits there were no changes in the system.

Any idea what is causing this?

**Comment by Chick3nman** [comment]
Can you drop -w4 and then retry with the latest binary from hashcat.net/beta? I'm specifically curious to see if its maybe the autotuner giving you different values or something. There are a lot of rules and not a lot of words in that attack so the tuning could play a significant role in the speed.

**Comment by ecostin** [comment]
Tried without w4, a bit slower, but same difference between commits. I don't think trying the beta would show something else, but the 7z file from here https://hashcat.net/beta/hashcat-6.1.1%2B282.7z is broken anyway, archive cannot be opened.

I know the particular test case may not be optimized, but there should not be such a huge delta between the numbers.

**Comment by jsteube** [comment]
That's the price to pay for a true encoding to utf16. Indeed I did not had in mind that this will affect NTLM because I wrongly recalled the pure kernel to use naive encoding functions, but in the end it is how it is. We can try to improve the performance slightly, but there will be a performance drop compared to previous version, but for pure kernels only.

But in a second thought, that's not really a problem. In fact, the previous kernel did not deserve the mark pure. It is now alot closer to how it should be. And then on the other hand, that's what the optimized kernel is for. To give the user the opportunity to live with a naive conversion and get the full optimized speed of previous version. So the user can pick themself.

I do not plan to change this yet, but I am open to discussion. Please leave your comments.

**Comment by jsteube** [comment]
OK, here's some small test change but should have some impact. Try it. If you think its good I can try to roll out to other library functions. I didn't try to optimize this too much because I was expecting this to be used in slow hashes in _init kernel only.

```
diff --git a/OpenCL/inc_hash_md4.cl b/OpenCL/inc_hash_md4.cl
index 149e7002f..945db0d8e 100644
--- a/OpenCL/inc_hash_md4.cl
+++ b/OpenCL/inc_hash_md4.cl
@@ -363,10 +363,16 @@ DECLSPEC void md4_update_swap (md4_ctx_t *ctx, const u32 *w, const int len)
 
 DECLSPEC void md4_update_utf16le (md4_ctx_t *ctx, const u32 *w, const int len)
 {
-  u32 w_utf16_buf[256] = { 0 };
+  u32 w_utf16_buf[256];
 
   const int w_utf16_len = utf8_to_utf16le (w, len, 256, w_utf16_buf, sizeof (w_utf16_buf));
 
+  const int blkoff = (w_utf16_len / 64) * 16;
+
+  u32 *w_ptr = w_utf16_buf + blkoff;
+
+  truncate_block_16x4_le_S (w_ptr + 0, w_ptr + 4, w_ptr + 8, w_ptr + 12, w_utf16_len & 63);
+
   md4_update (ctx, w_utf16_buf, w_utf16_len);
 }
```

**Comment by ecostin** [comment]
After the patch we are up from 217110457 to 820282934. Still half of the original 1950181895, but much better.

Replacing the function md4_update_utf16le with the one before https://github.com/hashcat/hashcat/commit/d343e2c4a0699bb8a6fd8d47b06fe4f5a157c5e8 brings back the full speed and does not seem to break anything, but I only tested briefly.

Commenting on the true utf16 implementation in case of NTLM, I agree the two options - of having very fast but "naive" conversion for up to 27 chars (optimized) or slow, full utf16le for longer candidates (pure) - are perfectly ok, with one exception. We see in NTLM password audits done against massive numbers of accounts that applying derivation rules to password leaks yields excellent results, often recovering passwords longer than 27 chars. This means that it is very useful to have full speed, maybe paying the price of not having correct utf16le, for candidates longer than 27 after rules expansion. This is however my use case, others may see it differently, especially when dealing with non-Latin.

**Comment by jsteube** [comment]
Could you please retry with latest commit? https://github.com/hashcat/hashcat/commit/b7dffd92590d28784a38568a47d3be45fc9eb500

**Comment by ecostin** [comment]
Same system, same test case: 1610058635 hash rate. So only 17.5% slower than before https://github.com/hashcat/hashcat/commit/d343e2c4a0699bb8a6fd8d47b06fe4f5a157c5e8

Is it now full utf16le? If it is, the performance sacrifice is now perfectly acceptable.
---
I've just read the commend, question answered.

**Comment by jsteube** [comment]
I had another Idea. Added with commit: https://github.com/hashcat/hashcat/commit/f8ea1d5e78c974a672583daa35397cbd32dc32c8

Nothing more fun in coding than performance tuning. Please close if acceptable.

**Comment by ecostin** [comment]
Hash rate is now 1724765777. Only 11.5% slower. I guess we are good to go. Closing the issue. Many thanks!

**Comment by jsteube** [comment]
Not sure if you're already bored with this, but with commit https://github.com/hashcat/hashcat/commit/0439f0c4a1e069550640b3895ffb76163d9d053c I had improved this conversion from UTF8 to UTF16 again. We no longer need to allocate this huge buffer u32 xxx[256] and can instead stick to the block size of the underlaying crypto primitive. In your case it's just 32 xxx[16]. This should give a small boot in performance and it allows us to have input and output buffers sizes of dynamical length

**Comment by ecostin** [comment]
Certainly not bored, I've been using hashcat for years, I'm happy to help with dev or testing when I can.

Applied the commit, hash rate now is 1758954325. If I leave it running for a longer time, after https://github.com/hashcat/hashcat/commit/0439f0c4a1e069550640b3895ffb76163d9d053c it averages approx. 2%, maybe 3% faster then before. I also notice a 3% reduction in GPU memory usage (although this test is not memory intensive and the input is mostly 7-bit). Dynamic buffer size will likely also help with other bottlenecks.
