### ISSUE TITLE
v6.2.0

### ISSUE THREAD

**Issue by noraj** [hashcat/hashcat#2779]
[v6.1.1](https://github.com/hashcat/hashcat/releases/tag/v6.1.1) is from July 2020.
Since RSA/DSA/EC/OpenSSH Private Keys modules have been added afterward.
But this is just an example, there are more than 291 commits sicnce then: https://github.com/hashcat/hashcat/compare/v6.1.1...master
A new release would be welcome so Linux distro could benefits from all the changes, fixes, enhancements and additions.

[AL FS#70662](https://bugs.archlinux.org/task/70662)

**Comment by jsteube** [comment]
Thanks for the heads-up. I'm in the preparation but there's still many issues and PR I have to go for some serious issues.

**Comment by jsteube** [comment]
RC2 is up in hashcat.net/beta release soon

**Comment by noraj** [comment]
All good https://github.com/hashcat/hashcat/releases/tag/v6.2.0
