### ISSUE TITLE
slow down execution

### ISSUE THREAD

**Issue by oorlykk** [hashcat/hashcat#2781]
Hi. How can i limited hashcat use my gpu. 50% from available power. is it possible?

**Comment by ventaquil** [comment]
As far as I know you can use `--workload-profile`.

```
- [ Workload Profiles ] -

  # | Performance | Runtime | Power Consumption | Desktop Impact
 ===+=============+=========+===================+=================
  1 | Low         |   2 ms  | Low               | Minimal
  2 | Default     |  12 ms  | Economic          | Noticeable
  3 | High        |  96 ms  | High              | Unresponsive
  4 | Nightmare   | 480 ms  | Insane            | Headless
```

**Comment by jsteube** [comment]
You can use either -w or directly by using -u1 -n1 -T1 --force to set a work item minimum. But I think the best way in general is by using nvidia-smi -pl XXX and set the wattage.
