### ISSUE TITLE
Arch Hashcat error

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2787]
I installed Hashcat in Kali Linux and it works fine
But I use pacman -S hashcat in Arch and it shows an error，What am i doing ？
![Screenshot_20210508_204302](https://user-images.githubusercontent.com/83487691/117539608-08617e00-b03e-11eb-963e-786fa567df86.jpg)

**Comment by jsteube** [comment]
GitHub issues are for Bugs and FR only. Please ask on Forum.
