### ISSUE TITLE
OCL runtime fails to compile kernels for cache if path contains space due to not using quotes

### ISSUE THREAD

**Issue by RolfHashcat** [hashcat/hashcat#279]
If a freshly extracted oclhc is placed inside a path, which contains space(s) and the requested kernel isn't compiled & cached, it will fail to run due to not using quotes.
For example, if placed inside a path "C:\foo bar\" and all above conditions are met, the bug will occur.

If, however, the kernel was compiled and cached in a "good" path first, and then placed in a path with a space, it will still work.
This suggests that only the compilation and caching doesn't use quotes properly and the execution of pre-compiled/pre-cached kernels isn't affected.

**Comment by jsteube** [comment]
@RolfHashcat Could you please try with beta 149 from https://hashcat.net/beta/ and close the issue if fixed. Thanks!

**Comment by RolfHashcat** [comment]
Issue fixed, thanks.
