### ISSUE TITLE
NTLM Unoptimized kernel can not recover (specific) hashes

### ISSUE THREAD

**Issue by 0xVavaldi** [hashcat/hashcat#2790]
Located a bug in the unoptimized kernel of NTLM which can be found by the optimized kernel.
This was tested using v6.1.1-323-g286002a8d and v6.1.1-294-g59459d0e5 on ubuntu and windows respectively

Put the following plains in a text file:
Т89134010266
ас0639356749
hashcat

With the following hashes:
5c344d6d31bd69f0df66c30dc40237b2
aa8e4c77888e4af09db544e82776f6f2
b4b9b02e6f09a9bd760f388b67351e2b

expected result from -O is 3 founds
.\hashcat.exe -m 1000 test_hashes.txt test_plains.txt --potfile-disable -o NUL -O --quiet --machine-readable

Expected result without -O is 3 founds but gives 1 found.
.\hashcat.exe -m 1000 test_hashes.txt test_plains.txt --potfile-disable -o NUL --quiet --machine-readable

One locates both hashes while the other is unable to do so.
Same effect without --quiet or machine readable. Tried on both Ubuntu and Windows.

**Comment by Chick3nman** [comment]
Could you encode the plaintexts with hex please, I'm having a bit of trouble copying them to recreate this issue. They appear to contain misleading characters, rendered as "T" and "ac" in my browser, that are not easily copied/typed.

**Comment by Chick3nman** [comment]
Scratch that, no need, I have recreated the issue. The plaintexts contain Cyrillic characters at the start and do not crack properly when using the pure kernel. The do crack properly when using the optimized kernel. This is most likely related to the recent UTF-16LE changes that were made.

Here is the hex representation of the two test plaintexts above:
`D0A23839313334303130323636`
`D0B0D18130363339333536373439`

**Comment by 0xVavaldi** [comment]
Seems accurate, I used these as example because they didn't appear cyrillic, but the other examples I have been sent (1k+) almost all contained cyrillic characters and could not be verified by hashcat without the optimized kernel.

Is this intended as part of the optimization process or is it that the unoptimized kernel hasn't been updated yet to reflect the UTF-16LE changes made to the optimized kernel?

**Comment by Chick3nman** [comment]
This is not intended as far as i can tell and will likely need to be addressed and fixed.

**Comment by jsteube** [comment]
Welcome to the nightmare of encoding issues. 

The wordlist has to be stored as UTF8, but your example passwords are not:

5c344d6d31bd69f0df66c30dc40237b2

```
root@ht:~/hashcat# xxd word1
00000000: d0b0 d181 3036 3339 3335 3637 3439       ....0639356749
```

```
root@ht:~/hashcat# iconv -f utf8 -t utf16le < word1 | openssl dgst -md4 
(stdin)= d95dd7f0be117a736d6cff2eca443bca
```

aa8e4c77888e4af09db544e82776f6f2

```
root@ht:~/hashcat# xxd word2
00000000: d0a2 3839 3133 3430 3130 3236 36         ..89134010266
```

```
root@ht:~/hashcat# iconv -f utf8 -t utf16le < word2 | openssl dgst -md4  
(stdin)= c6a71d8a6c4c57a345ed436951faac69
```

So this sounds weird, but the fact you could crack them before in pure kernel mode was the result of an invalid conversion. It still is for the optimized mode and in theory it should not crack it, but having the naive conversion is the price we pay for having the optimized performance.

**Comment by jsteube** [comment]
OK, so the passwords are in iso-8859-15 (next common encoding after utf8). So in order to crack them with hashcat in pure kernel mode you can do:

```
root@ht:~/hashcat# ./hashcat -m 1000 hashes words --quiet --potfile-disable -O | wc -l
3
root@ht:~/hashcat# ./hashcat -m 1000 hashes words --quiet --potfile-disable | wc -l   
1
root@ht:~/hashcat# ./hashcat -m 1000 hashes words --quiet --potfile-disable --encoding-from iso-8859-15 | wc -l      
3
```

From my perspective hashcat works as good as it can. Please close the issue or if you have any ideas how to improve let me know.

**Comment by 0xVavaldi** [comment]
--encoding-from iso-8859-15 7417/17087
vs
-O 17087/17087

So there is still a difference in performance overall there that doesn't go quite right. The system is set up to be UTF8 and all files are UTF8. Is there a way to modify the plains so that they can be cracked on the pure kernel (file conversion wise) or is this just what it is, and the hashes itself were generated incorrectly?

**Comment by jsteube** [comment]
From performance I guess you don't mean real performance, in terms of H/s because that would totally confuse this issue. So let's stay to what we are discussing and that's the encoding issue of the input words. 

Everything depends on how the hashes have been generated, but that doesn't mean they were generated incorrectly. That could have been on a iso-8859-15 basis as with the 7417, but it could also have been any other 8 bit encoding, like iso-8859-5. However, the conversion code seems to work correctly, so it's not a hashcat issue.

**Comment by 0xVavaldi** [comment]
I meant in the sense of hashes cracked. The amount isn't the same.
A suggestion was made that these might have originated from troy hunts' NTLM hashes since he didn't properly perform NTLM hashing.

**Comment by jsteube** [comment]
Try to see it from a technical perspective. The passwords could have been in all random sort of encoding before troy hunt hashed them using NTLM. It's very unlikely he knew the encoding of every password because each leak comes from a different  site and each different site might have been using a different encoding. Still I don't get how's that connected to a hashcat issue.

**Comment by 0xVavaldi** [comment]
The hashcat issue is more the ability to get the hashes with -O and not without. You'd expect both to be able to or neither to be able to get the hashes. That's where the 'issue' resides in that.

**Comment by 0xVavaldi** [comment]
```
hashcat.exe -m1000 -a3 Hashes --encoding-from iso-8859-1
```
Reference for future cases. This worked for the pure kernel.
