### ISSUE TITLE
--stdout broken on Windows?

### ISSUE THREAD

**Issue by dom96** [hashcat/hashcat#2791]
On Windows:

```
.\hashcat -r .\rule --stdout .\word
Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit installation NOT detected or incorrectly installed.
             CUDA SDK Toolkit installation required for proper device support and utilization
             Falling back to OpenCL Runtime

```

On WSL:

```
$ hashcat -r rule --stdout word
Word
```

Is the OpenCL Runtime fallback not enough for Windows or is something else going on here?
 The version on Windows I am running is v6.2.0 whereas on Ubuntu it's v4.0.1.

**Comment by jsteube** [comment]
It shouldn't print that error, that's ugly indeed. You can try using --backend-ignore-cuda as a work around.

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/fe91f6276db5aff017573c38d0d586cd3b8a0525
