### ISSUE TITLE
TOTP cracking stops at status cracked instead of status exhausted

### ISSUE THREAD

**Issue by oschoudhury** [hashcat/hashcat#2792]
Hi,

I am trying to perform the TOTP cracking with hashcat mode 18100 with. This is a bit of a unique algorithm if I understood correctly in the sense that there can be multiple solutions and you need to enter multiple OTP codes from the same source and then see if any of the solutions are then duplicate. The author who wrote this module has a blog post at [here](https://www.unix-ninja.com/p/attacking_google_authenticator). Therefore in that example I see it continues until the keyspace is Exhausted.

If I try to run this myself, I observe the following:
```
sudo hashcat -m 18100 -o totp.hashfile -a3 totp1.hash '?l?l?l?l?l?l?l?l'
hashcat (v6.2.1) starting...

[...]
Session..........: hashcat
Status...........: Cracked
Hash.Name........: TOTP (HMAC-SHA1)
Hash.Target......: totp1.hash
Time.Started.....: Tue May 18 17:26:45 2021 (0 secs)
Time.Estimated...: Tue May 18 17:26:45 2021 (0 secs)
Guess.Mask.......: ?l?l?l?l?l?l?l?l [8]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   280.6 MH/s (6.46ms) @ Accel:8 Loops:32 Thr:1024 Vec:1
Recovered........: 2/2 (100.00%) Digests, 2/2 (100.00%) Salts
Progress.........: 1153957888/417654129152 (0.28%)
Rejected.........: 0/1153957888 (0.00%)
Restore.Point....: 0/11881376 (0.00%)
Restore.Sub.#1...: Salt:1 Amplifier:0-32 Iteration:0-32
Candidates.#1....: sarerane -> pongxhon
Hardware.Mon.#1..: Temp: 37c Fan: 23% Util: 11% Core:1328MHz Mem:3004MHz Bus:16
```

Afaik it has only looked at a small keyspace (0.28%), not the complete one. I also observe only one cracked hash per OTP code in my potfile. Has something been changed in how to execute this particular mode? There is barely information online of people describing how they used it.

**Comment by jsteube** [comment]
Yes, it has changed. And there's a big fat warning message about, but in your paste you had it removed. Why?

```
This hash-mode is known to emit multiple valid password candidates for the same hash.
Use --keep-guessing to prevent hashcat from shutdown after the hash has been cracked.
```

Therefore I'll close the issue.

**Comment by oschoudhury** [comment]
Ah, my bad. I didn't think of looking there for additional warnings as in my case it is already filled with CUDA related warnings. Hence why I cut it here too. Thanks for answering quickly!
