### ISSUE TITLE
Cant start hashcat because of unsupported ptx version

### ISSUE THREAD

**Issue by Nycz-lab** [hashcat/hashcat#2798]
Hashcat keeps on crashing on me when i run it.
I built hashcat from source and i am using the latest manjaro version.
![hashcat_error](https://user-images.githubusercontent.com/63111944/119266489-543e2680-bbeb-11eb-966c-dbe03ae979a4.png)
![nvidia--smi](https://user-images.githubusercontent.com/63111944/119266495-57391700-bbeb-11eb-9b9f-e4e4c035597e.png)

**Comment by jsteube** [comment]
User error. Please update to latest CUDA SDK.
