### ISSUE TITLE
I  am asking kindly to add a new bruteforcing mask feature developers of hashcat :)

### ISSUE THREAD

**Issue by aspiringpentester1** [hashcat/hashcat#2802]
hello hash cat developers i have to say that u did a very good job of creating hashcat and i am very appreciative that there is a tool like this today in my era but i have one slight request in masks. I know that i can use all character set by using ?a but what if i wanted to bruteforce using all character set inclusive of : 0-9, a-z, A-Z. You get what i mean, if i could code i would at it to the tool myself but i can't.
i would love to see a response from you all as soon as possible :)

**Comment by roycewilliams** [comment]
This is a question more for the [hashcat forums](https://hashcat.net/forum/). This is possible using the existing hashcat feature set.
