### ISSUE TITLE
Inline kdb 1 files are limited in size

### ISSUE THREAD

**Issue by bpdevries1** [hashcat/hashcat#2803]
**Describe the bug**
Although size of the inline Keepass database version 1 was enlarged previously in Issue [1415](https://github.com/hashcat/hashcat/issues/1415)  it still isn't large enough for sizable keepass databases. In this case a database of 1.5 MB was found. But this cannot be cracked it seems.  

**To Reproduce**
Try cracking a 1.5 MB Keepass 1 database.

**Expected behavior**
Please make keepass databases up to 2 MB crackable.

**Hashcat version (please complete the following information):**
hashcat (v6.1.1)

Post hashcat -I output
Hashfile 'pws.txt' on line 7 ($keepa...): Token length exception

**Comment by jsteube** [comment]
Please provide the .kdb file so that we can reproduce the problem locally. If you do not want to share the original kdb, create an artifical one yourself and see if the problem can be reproduced with that one. Then provide it here.

**Comment by jsteube** [comment]
@bpdevries1 Update please

**Comment by jsteube** [comment]
KeePass: Increase supported size for KeePass 1 databases from 300kB to 16MB with commit https://github.com/hashcat/hashcat/commit/56c2243dfb39cd090f05a5e9b5a81cce2d3761ae

Pro Tip: Use -o otherwise it will flood your screen :)

**Comment by bpdevries1** [comment]
Sorry for my slow response, thnx for the fix though this should be ample to crack large keepasses.
