### ISSUE TITLE
Feature Request: Add "auto detect only" functionality for hashes

### ISSUE THREAD

**Issue by sadreck** [hashcat/hashcat#2811]
Hi,

**Background**
This feature request is coming from this tweet: https://twitter.com/hashcat/status/1401612748115566603

**Current Functionality**
The way this has been implemented is that it's part of the cracking process, which means that it will kick off the session if it detects a single match, or otherwise it will prompt the user to select a type and then continue with the cracking.

**Feature Request**
It would be great if we could have an `--autodetect-only / --identify` feature where we could use it as a "hash-id" and simply identify a hash. It wouldn't even need to read it from a file, it could be as simple as:

```
hashcat --identify <hash>
```

Thanks,
Pavel

**Comment by Chick3nman** [comment]
We currently have a flag, added somewhat recently, call `--hash-info` that prints out a great little set of information about a hash type, specified with `-m`. I'm going to look at implementing this such that if you do not specify `-m` but do specify a hash or hash file, the parser runs and then prints out the same hash information for the detected hash type(s).

**Comment by Chick3nman** [comment]
An example of the `--hash-info` output looks like this:

```
Hash Info:
==========

Hash mode #2500
  Name................: WPA-EAPOL-PBKDF2
  Category............: Network Protocols
  Slow.Hash...........: Yes
  Password.Len.Min....: 8
  Password.Len.Max....: 63
  Salt.Type...........: Embedded
  Salt.Len.Min........: 0
  Salt.Len.Max........: 256
  Hashes.Count.Min....: 1
  Hashes.Count.Max....: 4294967295
  Kernel.Type(s)......: pure 
  Example.Hash.Format.: hex-encoded
  Example.Hash........: 4843505804000000000235380000000000000000000000000000000000000000000000000000000000000151aecc428f182acefbd1a9e62d369a079265784da83ba4cf88375c44c830e6e5aa5d6faf352aa496a9ee129fb8292f7435df5420b823a1cd402aed449cced04f552c5b5acfebf06ae96a09c96d9a01c443a17aa62258c4f651a68aa67b0001030077fe010900200000000000000001a4cf88375c44c830e6e5aa5d6faf352aa496a9ee129fb8292f7435df5420b8230000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018dd160050f20101000050f20201000050f20201000050f20200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  Example.Pass........: hashcat!
  Benchmark.Mask......: ?a?a?a?a?a?a?a?a
  ```

**Comment by t94j0** [comment]
Along with this, it would be really nice to have a "silent" option that could print out all possible hash mode types without headers so that hashcat could be easily integrated with other shell scripts.

E.g.
`hashcat --identity --silent 5f4dcc3b5aa765d61d8327deb882cf99`

stdout:
```
0
```

Maybe you could overload the `quiet` flag?

**Comment by jsteube** [comment]
I assume the output should go line by line not in a single line with a separator?

**Comment by t94j0** [comment]
I'm not the one implementing it, so whatever is easiest, but separating by newline would make the most sense to me. Since the silent option would mostly be used in shell scripts, it would just need to easily be parsable by something like awk.

**Comment by matrix** [comment]
pushed here #2821
:)

**Comment by t94j0** [comment]
@matrix Just tested it out. I really like the table with the hashcat identifier, name, and category as well as the `--quiet` option

**Comment by jsteube** [comment]
The changes have been made. 

Note I have changed --quiet to --machine-readable (you can write --mach) because we already have this option for other features like --keyspace and it suits much better that purpose.

Regular mode:

```
$ ./hashcat --id example0.hash 
```

```
The following 11 hash-modes match the structure of your input hash:

      # | Name                                                | Category
  ======+=====================================================+======================================
    900 | MD4                                                 | Raw Hash
      0 | MD5                                                 | Raw Hash
     70 | md5(utf16le($pass))                                 | Raw Hash
   2600 | md5(md5($pass))                                     | Raw Hash, Salted and/or Iterated
   3500 | md5(md5(md5($pass)))                                | Raw Hash, Salted and/or Iterated
   4400 | md5(sha1($pass))                                    | Raw Hash, Salted and/or Iterated
  20900 | md5(sha1($pass).md5($pass).sha1($pass))             | Raw Hash, Salted and/or Iterated
   4300 | md5(strtoupper(md5($pass)))                         | Raw Hash, Salted and/or Iterated
   1000 | NTLM                                                | Operating System
   9900 | Radmin2                                             | Operating System
   8600 | Lotus Notes/Domino 5                                | Enterprise Application Software (EAS)
```

Machine mode:

```
$ ./hashcat --id --mach example0.hash 
```

```
900
0
70
2600
3500
4400
20900
4300
1000
9900
8600
```

You can compile from source or use the beta binaries from hashcat.net/beta/
