### ISSUE TITLE
feature: add general platform information to "-I"

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#2827]
When helping users troubleshoot issues, it would be useful for -I to be a "one stop" way to include general platform information, about hashcat itself and the platform - perhaps things like:

* path to hashcat
* hashcat's work/config directory
* compile options used
* uname -a or similar architecture information
* etc.

This would expand the "-I" concept to be a more general "Information" option, rather than using up another letter. :)

**Comment by jsteube** [comment]
I like the idea, but the question is what we want to add. For example we cannot do it better than nvidia-smi or rocm-smi is doing it, or clinfo.

So should we reduce to hashcat specific information? I think we could also use -II like double "I", like some tools do it for -vvv, like very verbose. If the user is doing -II we can have more information. Or we just change the -I.

We can also modify the issue template and ask the user to provide the -II output instead. So maybe we should display information that are relevant to issue reports?

**Comment by matrix** [comment]
Hi, #3146 it's enough? or do we need something else?

**Comment by roycewilliams** [comment]
Wow - a great start!

It would also be nice to show the work/config directory. This would be useful when helping other users to troubleshoot, and they might even be able to help themselves (and not have to ask others). I assume that it would be harder to detect/show the compile/build options used?

**Comment by matrix** [comment]
We can add some of these, but not the compile/build options:

```
typedef struct folder_config
{
  char *cwd;
  char *install_dir;
  char *profile_dir;
  char *cache_dir;
  char *session_dir;
  char *shared_dir;
  char *cpath_real;

} folder_config_t;
```

**Comment by roycewilliams** [comment]
That would be fine, I think!

**Comment by Chick3nman** [comment]
Fix was merged, if more things need to be added, we can reopen or open a new issue.
