### ISSUE TITLE
Invalid rules if contains €

### ISSUE THREAD

**Issue by clem9669** [hashcat/hashcat#2829]
**Describe the bug**
Hashcat do not accept rules with € symbol.

**To Reproduce**
Skipping invalid or unsupported rule in file clem9669_small.rule on line 113: $€
Skipping invalid or unsupported rule in file clem9669_small.rule on line 225: ^€

**Expected behavior**
I expected 'password€' and '€password'. 

**Hashcat version (please complete the following information):**
 - OS: Kali Debian 5.10.28-1kali1

**Similar Issue**
https://github.com/hashcat/hashcat/issues/2598

**Comment by jsteube** [comment]
User error, utf8 is not supported with rules. Use iso-8859-15 instead. GitHub issues are for bugs and feature requests only. Please ask on hashcat forums instead.

**Comment by clem9669** [comment]
Hey @jsteube,

Thanks for you reply. I have seen the following solution you gave in https://github.com/hashcat/hashcat/issues/2598. 

Is it the recommanded way to crack with utf8 ?

**Comment by jsteube** [comment]
No, is a completely different thing. Ask on forum!

**Comment by clem9669** [comment]
If you have this problem, the solution I have been given is: `$€ => $\xe2 $\x82 $\xac`

1. Convert character to utf8 hex ([charset.org](https://www.charset.org/utf-8))
2. Build the hexa with `\x`
3. Write rules with the hexa value
