### ISSUE TITLE
new code style problems (whitespaces)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#2841]
This is something we could fix whenever we have some free time to make these minor changes.

I've found some minor code sections lately that have some weird whitespace (spaces at the end and tab characters etc).

We could probably easily find these files/sections like this:
```
grep -rl $'\t' OpenCL/
grep -l  $'\t' tools/test_modules/*.pm

grep -rl ' $' src/modules/
grep -rl ' $' OpenCL/
grep -l  ' $' tools/test_modules/*.pm
```

Don't hesitate to make these changes whenever you find the time to do so.... just a few lines need to be changed (a very good/easy fix for some contributers/volunteers).

thanks

**Comment by roycewilliams** [comment]
Can these be addressed with .editorconfig ?

**Comment by jsteube** [comment]
merged, many thanks!
