### ISSUE TITLE
make wsl broken

### ISSUE THREAD

**Issue by thatux** [hashcat/hashcat#2850]
**Describe the bug**
`make wsl` is not working.

**To Reproduce**
Following https://github.com/hashcat/hashcat/blob/master/BUILD_WSL.md on a fresh gjt clone results in:
```
src/backend.c:11670:30: error: request for member ‘QuadPart’ in something not a structure or union
11670 |     device_param->timer_speed.QuadPart = 0;
      |                              ^
make: *** [src/Makefile:741: obj/backend.WIN.o] Error 1
```

**Expected behavior**
should build Windows binaries hashcat.exe

**Hardware/Compute device (please complete the following information):**
Windows 10 laptop. Tried with both wsl1 (Ubuntu 18.04) and wsl2 (Ubuntu 20.04) both show same behaviour

**Comment by jsteube** [comment]
Can't reproduce:

```
atom@msi:~/hashcat$ uname -a
Linux msi 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
atom@msi:~/hashcat$ make -s win
atom@msi:~/hashcat$ ls -l hashcat.exe
-rwxr-xr-x 1 atom atom 1325568 Jun 23 23:02 hashcat.exe
```

**Comment by thatux** [comment]
d616a9e42 "Add note about tested WSL2 configuration" does work for me, but master doesn't: 
`make win > make_win.log 2>&1`
[make_win.log](https://github.com/hashcat/hashcat/files/6704878/make_win.log)


```
#uname -a
Linux A 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thatux** [comment]
OS Name	Microsoft Windows 10 Home
Version	10.0.19043 Build 19043

**Comment by jsteube** [comment]
This error looks more like if someone is trying to clone hashcat source to somewhere inside /mnt but that's not a hashcat issue? 

Note that this is not expected for WSL. Can you confirm you are not trying to compile under /mnt ?

**Comment by oam7575** [comment]
**Report**
Build process appears to work fine for me.

**Notes**
I have never used WSL previously and have used this bug report as a test for myself and the bug.

**Process**
I freshly installed WSL via Programs and Features and then installed and Ubuntu 20.04 environment via the Microsoft store.

Following the WSL build instructions here : https://github.com/hashcat/hashcat/blob/master/BUILD_WSL.md
resulted in a Windows EXE that was able to be run ( benchmark mode ) from standard windows CMD environment.

I then manually downloaded the hashcat-master.zip file, extracted it and compiled.
Again a working EXE file resulted.

**Screenshots**
The screen shots below show some of my environment and both versions of hashcat running benchmark mode correctly before being terminated.

**Fresh Ubuntu WSL installed**
![Fresh_Ubuntu_20 04_WSL_Install](https://user-images.githubusercontent.com/18411503/123202314-b7c3b880-d4f7-11eb-8b14-b06c5c5b8625.JPG)

**Hashcat Compiling**
![hashcat_compiled](https://user-images.githubusercontent.com/18411503/123202321-bb573f80-d4f7-11eb-982b-3d0937fc9249.JPG)

**Hashcat executing**
![hashcat_executing](https://user-images.githubusercontent.com/18411503/123202330-bd210300-d4f7-11eb-9dd4-fbb9ffd9a9da.JPG)

**Hashcat-Master executing**
![hashcat__master_executing](https://user-images.githubusercontent.com/18411503/123202339-bf835d00-d4f7-11eb-9549-95a2fa3faa2a.JPG)

**Comment by thatux** [comment]
> This error looks more like if someone is trying to clone hashcat source to somewhere inside /mnt but that's not a hashcat issue?
> 
> Note that this is not expected for WSL. Can you confirm you are not trying to compile under /mnt ?

Yeah I'm cloning it under /mnt/c such that I can also (easily) access the hashcat build from Windows Explorer.
I'm surprised that this wouldn't work actually, with a prior commit this still works (d616a9e), so I'm not sure why that wouldn't be possible to work anymore, apparently something in hashcat changed? Any pointers on that @jsteube?
I'll change the description in https://github.com/hashcat/hashcat/blob/master/BUILD_WSL.md as it now refers to a build in `cd "C:\Users\user\hashcat"` which would be `/mnt/c/Users/user/hashcat` from within WSL.

@oam7575 thanks for reproducing, I'm also able to build it in the homedir of WSL.
```
user@machine:~/hashcat$ pwd
/home/user/hashcat
user@machine:~/hashcat$ make -s win
user@machine:~/hashcat$ ls -l hashcat.exe
-rwxr-xr-x 1 user user 1325568 Jun 25 16:24 hashcat.exe
```

**Comment by jsteube** [comment]
I didn't investigate much further but I think the reason is that for /mnt/c (and similar) folders there is no more case sensitivity for file names because these are NTFS filesystems.

**Comment by jsteube** [comment]
Should be fixed with this commit https://github.com/hashcat/hashcat/commit/b30d55c5d98d8cfc08942052351e60cbd6c2ae7d

**Comment by thatux** [comment]
Cool, that works! Thanks :). Wouldn't have figured out that'd be the cause.
