### ISSUE TITLE
Nvidia+OpenCL error: implicit conversion from address space "global" to address space "private"

### ISSUE THREAD

**Issue by grische** [hashcat/hashcat#2851]
**Describe the bug**
hashcat fails to compile kernel `OpenCL/m13100_a3-optimized.cl` on a Nvidia 1080Ti (and others).
```
<kernel>:135:29: error: implicit conversion from address space "global" to address space "private" is not supported when passing to parameter of destination type 
  j = rc4_next_16 (S, i, j, edata2 + 0, out0); i += 16;
                            ^~~~~~~~~~
```
For more see here: https://gist.github.com/grische/397ed01a9146dcc3541543cdc1807d4b#file-stdout

**To Reproduce**
Simply run the Hashcat benchmark for "Hashmode: 13100 - Kerberos 5, etype 23, TGS-REP" with Nvidia's OpenCL (not with nvRTC).

**Expected behavior**
Either successfully compile the kernel and run the benchmark or at least skip the benchmark.

**Hardware/Compute device (please complete the following information):**
- Compute device name: `GeForce GTX 1080 Ti, 11008/11178 MB (2794 MB allocatable), 28MCU`
- OpenCL/CUDA driver name: `OpenCL API (OpenCL 1.2 CUDA 10.1.120) - Platform #1 [NVIDIA Corporation]`
- OpenCL/CUDA driver version: `430.50` (also `460.80` is affected)
- OpenCL/CUDA driver source: Ubuntu's pre-packaged Nvidia driver `nvidia-dkms-430` et al

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Ubuntu 18.04 (and 20.04 with 460.80)
 - Version: 6.2.2

**Diagnostic output compute devices:**

If still needed, I can deliver those

**Additional context**
The problem does not appear when running the benchmark with libnvrtc installed. Tested was libnvrtc11.2 on Ubuntu 21.04.

**Comment by jsteube** [comment]
I think I had this fixed yesterday with commit https://github.com/hashcat/hashcat/commit/b2193e1af4d1134694001538ec5c69b0e285e7f9

Can you please update to latest GitHub master and retry?

**Comment by grische** [comment]
@jsteube thanks for the fix.

I am unable to reproduce the problem with neither driver 430 nor 460 using hashcat on master (commit 84cf5e70e7331ebd7c4c3134ab8f058601a70e5a).
