### ISSUE TITLE
request for autohex on debug-mode=4 

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#2852]
When using --debug-mode=4, if the pre-rule plain has a colon in it or the post-rule plain has a colon it, the debug output becomes unparsable and generally not usable as there is no way to determine where the rule begins and ends.

It would be great if the debug output could be automatically converted into hex if a character exists that would otherwise cause parsing issues, exactly like hashcat already does for it's normal -o output.

**Comment by roycewilliams** [comment]
Good idea! :)
(Duplicate of #2493)

**Comment by 0xVavaldi** [comment]
Should be implemented honestly

**Comment by jsteube** [comment]
Was fixed with PR https://github.com/hashcat/hashcat/pull/2854
