### ISSUE TITLE
--hash-info does produce an error on certain modes

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#2859]
Used hashcat version is from the actual master.

When requesting mode information with --hash-info, it produces an error and quits for modes where only optimized kernels exist.

Example:
```
$ ./hashcat --hash-info -m 200
hashcat (v6.2.2-74-g56c2243df) starting in hash-info mode

.../hashcat/OpenCL/m00200_a0-pure.cl: No such file or directory
```

**Comment by jsteube** [comment]
OK, thanks for reporting. I can reproduce this behavior.

**Comment by jsteube** [comment]
Fix with commit https://github.com/hashcat/hashcat/commit/c322429

**Comment by s3inlc** [comment]
Thanks, I can confirm it works correctly again.
