### ISSUE TITLE
Make it easy for people to customize current hashcat kernels

### ISSUE THREAD

**Issue by jj2hh2hasdf** [hashcat/hashcat#2862]
**Describe the feature**
Make it easy for people to create their own kernel modes that reuse other kernels.

There are a lot of dbs now days that use an extra hash before hashing with another hash, and asking you guys to code a custom kernel for each new variation of the same hash type is pointless.

Example:

sha512($salt.md5($password))

This hashing variation doesn't exist in hashcat, and there are lots of dbs using different kinds of hashing variations that hashcat doesn't support since they are so niche, and it's understandable that you can't add them all but at least make it easier for people that don't know C to create their own custom kernels that reuse other kernels.

sha512($salt.$pass) exists in hashcat, all that's needed it to add md5($pass)

**Current behavior**
none

**Expected behavior**

Example: hashcat.exe -m sha512($salt.md5($pass)) hashlist.txt pwslist.txt

Hashcat would automatically create the kernel for that run by using existing kernels, or there could be a tutorial on how to add existing kernels to other existing kernels  for people that don't know C.

** I also understand that optimized kernels wouldn't be feasible so unoptimized kernels would be more than fine

**Comment by matrix** [comment]
> but at least make it easier for people that don't know C to create their own custom kernels that reuse other kernels.

Hi @jj2hh2hasdf, to add an algo in hashcat you need know C, perl and OpenCL programming language, as well as studying the logic already implemented on hashcat, and the guide to develop plugins. If you don't know C ... there is nothing that can make your life easy here.

**Comment by roycewilliams** [comment]
What they're asking for here is something like John's dynamic mode.

**Comment by matrix** [comment]
That's easier said than done. @jsteube what do you think about it?
Perhaps, with some ifdef on the kernel it is possible to manage the simplest cases in order not to go down too much in terms of performance.

**Comment by jj2hh2hasdf** [comment]
Yeah something like that @roycewilliams 

@matrix I'm asking to make it simpler for people to add a custom kernels from kernels that are already coded, by combining them maybe ? This would be useful right now and in the future since companies use more and more different combinations of already existing hash algos. This would also make it easier to add a lot more hashing algos like md5(md5(md5($pass))) or sha1($pass.$salt$.$pass.sha1($pass)) just example.

**Comment by jsteube** [comment]
There is an endless number of level of detail of possibilities. User will ask for more and more things like placing static values somewhere in between or capitalizing the result or encode as base64 before hashing with XXX hash. 

This kernel would ultimately grow into something that is not only difficult to maintain, but the more complex the code gets, the more unstable OpenCL drivers are likely not to compile. You can already see it with much more simple kernels. If performance really isn't that important, please use JtR.
