### ISSUE TITLE
Add keep guessing warning (OPTS_TYPE_SUGGEST_KG) to Java Object hashCode (mode 18700)

### ISSUE THREAD

**Issue by SK83RJOSH** [hashcat/hashcat#2864]
**Describe the feature**
Java Object hashCode is a pretty poor  hashing algorithm in terms of collisions and I think this hash mode needs this option in order to get useful results in some cases.

**Current behavior**
The current behavior is that there's no warning about the high number of collisions.

**Expected behavior**
That the end user gets a warning about hash collisions.

**Hashcat version (please complete the following information):**
 - OS: N/A
 - Distribution: N/A
 - Version: all

**Additional context**
I often find myself using this mode to crack field names / variable names in games as the algorithm is a modified K&R hash and is pretty pervasive. I've seen it in everything from Java -> .NET -> bespoke C++ game engines at this point and this is by far the most useful option to get useful results, and it took me a while to actually find.

**Comment by SK83RJOSH** [comment]
Actually I may have jumped the gun here when checking the code to see if this mode needed to be explicitly supported, I see now that it seems to work as expected but it'd be nice to get the warning added in any case. I've updated the issue accordingly. 👍

**Comment by jsteube** [comment]
True. Added with commit https://github.com/hashcat/hashcat/commit/a2f883396b1299bade079315ecd07f78c8fbe6bc
