### ISSUE TITLE
HW Temp Pause 

### ISSUE THREAD

**Issue by sopsmattw** [hashcat/hashcat#2869]
**Describe the feature**
on warmer days, I have a card or two that run warmer than the others. Occasionally, one card will hit the threshold and the whole  job will abort (by design). Is it feasible to add a feature similar to --hwmon-temp-abort that pauses the job until the temp drops to a nominal level? Can this be done per card? maybe pass upper and lower values to it?  (--hwmon-temp-pause 55:89)

 I can manually monitor the temps and pause/resume the job as needed. Just looking to automate that.

**Comment by Xanadrel** [comment]
Something a bit like that: https://github.com/hashcat/hashcat/commit/b864fa5ba74d9b1e9dafb1d6ee4bbfea6d954ce0

So instead of a new feature, you can probably play with the power limit of your gpus (which can be set per gpu even), so they don't get too hot.
