### ISSUE TITLE
-m13400 Optimization issue within Intel CPU OpenCL driver 

### ISSUE THREAD

**Issue by Fist0urs** [hashcat/hashcat#287]
Just to keep a record of it:

The actual implementation works either on GPU and CPU, but there is a problem with last Intel OpenCL CPU driver (15.1 as I am writing). This driver does some weird optimizations that produce wrong results while cracking.

**Comment by felipesalomao** [comment]
Hi, how i can run it using OpenCL driver ? I have macboor air I7 2014 and now i am running it slow speed (1.4 pass/sec).. Thank you

**Comment by jsteube** [comment]
@Fist0urs There's a new Intel OpenCL runtime version released. Should we retry if the problem still exist?

**Comment by Fist0urs** [comment]
We should try it yes, good idea. The problem is that I no longer have direct access to a HD4400 Graphics integrated GPU (which we experienced bugs). I'll try to get one to do some more tests

**Comment by jsteube** [comment]
Any update here?

**Comment by Fist0urs** [comment]
I'll ping back again my ex-coworker who has the problematic CPU

**Comment by jsteube** [comment]
I've pushed a workaround. Tested on my local Intel CPU: https://github.com/hashcat/hashcat/commit/3baec81d90c6046e42a6d10a40adda770d525826
