### ISSUE TITLE
Auto-tuning outside kernel can cause unpredictable behavior for tmp_t structs on CUDA

### ISSUE THREAD

**Issue by pellekuiters** [hashcat/hashcat#2876]
**Describe the bug**
When performing auto-tuning for an outside attack, the loop function is repeatedly called. When the plugin has a 'tmp_t' structure, with for example a length field, the behavior can be unpredictable. During auto-tuning, the init() function is not (always) called before the loop() function so the value of this length field is unpredictable. The length field may contain whatever was present in GPU memory. This can be nonsense or zero, depending on OS and/or driver. If this length field is used for division or other math functions, it can cause various CUDA errors with the following message: "An Illegal memory access was encountered".  
This error did not occur with OpenCL and also didn't occur using nearly the same device, also on Windows, but with a slightly older CUDA driver.

**To Reproduce**
For now, we do not have files that reproduce this error, but an upcoming plugin requires this change. The 22400 attack may also be susceptible to this issue.

**Expected behavior**
When performing auto-tuning, kernel functions should be called in the correct order, so that the various structures used by the kernel contain the correct data.

**Hardware/Compute device (please complete the following information):**
- Compute device name: RTX 2080 Super & GeForce GTX 1650
- Driver name: NVIDIA CUDA driver
- NVIDIA driver version: 461.09,  CUDA version: 11.2
- NVIDIA driver source: Windows (10) installer

**Hashcat version (please complete the following information):**
 - OS: Windows 10 using WSL (running Ubuntu)
 - Distribution: Ubuntu Linux 18.04.4 LTS
 - Version: 6.2.2

**Diagnostic output compute devices:**
(not applicable)

**Additional context**
Below the various errors you get with CUDA:
_cuStreamSynchronize(): an illegal memory access was encountered
cuFuncSetAttribute(): an illegal memory access was encountered
cuLaunchKernel(): an illegal memory access was encountered
cuMemFree(): an illegal memory access was encountered
cuEventDestroy(): an illegal memory access was encountered
cuStreamDestroy(): an illegal memory access was encountered
cuModuleUnload(): an illegal memory access was encountered_

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/pull/2886
