### ISSUE TITLE
[FR] allow --debug-mode with association attack (-a 9)

### ISSUE THREAD

**Issue by DaniloNC** [hashcat/hashcat#2880]
**Describe the feature**
The new association attack is great for discovering new (random) rules but it is lacking support to --debug-mode flag, requiring additional work to discover which rules were successful. 

**Current behavior**
```
➜ ./hashcat -m 0 -a 9 -r /opt/cracking/rules/password_cracking_rules/OneRuleToRuleThemAll.rule  foo.md5 wl.txt --debug-mode 1 --debug-file debug.txt
Parameter --debug-mode option is only allowed in attack mode 0 (straight).
```

**Expected behavior**
The `debug-mode` and `debug-file` flags would work with the association attack (-a 9)

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Manjaro
 - Version: 6.2.2 git commit v6.2.2-125-g11295e467

**Comment by jsteube** [comment]
That should have worked from the beginning, just missed to add the condition. Fixed with commit https://github.com/hashcat/hashcat/commit/acc592e96343f1e1e769a4ff14381288e2fe91cc
