### ISSUE TITLE
--veracrypt-pim-start and --veracrypt-pim-stop doesn't work in 6.2.3

### ISSUE THREAD

**Issue by metulski2013** [hashcat/hashcat#2887]
--veracrypt-pim-start and --veracrypt-pim-stop doesn't work in 6.2.3. It works only, when start and stop are the correct PIM like

"--veracrypt-pim-start=999 --veracrypt-pim-stop=999"

**Comment by jsteube** [comment]
Could you please add a header so that we can reproduce locally

**Comment by metulski2013** [comment]
failure

![failure](https://user-images.githubusercontent.com/17407529/126284144-c4b07497-0357-4ab9-9ac5-ee9861a18feb.PNG)

**Comment by metulski2013** [comment]
correct

![correct](https://user-images.githubusercontent.com/17407529/126284177-3e86b5f3-1e84-4197-a820-6cf4630edb15.PNG)

**Comment by jsteube** [comment]
So you are saying that this problem occurs only with 6.2.3, but not with older versions?

**Comment by metulski2013** [comment]
don't know

**Comment by metulski2013** [comment]
I gave you an case and now i'm afraid because of the PIM problem.

**Comment by metulski2013** [comment]
well, in the first beta, where PIM was supported, it works perfekt.

**Comment by jsteube** [comment]
I can reproduce the problem, thanks for reporting.

**Comment by jsteube** [comment]
What I found out so far: 

- Problem only occurs on CPU cracking
- Problem is related to vector size SIMD. If you disable it, it will work on CPU: --backend-vector-width 1

**Comment by metulski2013** [comment]
perfect, works!

**Comment by jsteube** [comment]
Fixed with commit: https://github.com/hashcat/hashcat/commit/777512e862a5321d76801d0a21585dc6ca6820ec

This was an excellent bug report, thanks again.

There's also a new beta on hashcat.net/beta in case you want to use this.
