### ISSUE TITLE
compilation fails with zlib-ng

### ISSUE THREAD

**Issue by Bogdan107** [hashcat/hashcat#2895]
**Describe the bug**
I try to switch zlib to zlib-ng in my system.
Hashcat compilation fails with many errors, like:
```
In file included from include/types.h:28,
                 from src/benchmark.c:7:
include/ext_lzma.h:12:10: fatal error: minizip/ioapi.h: No such file or directory
   12 | #include "minizip/ioapi.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [src/Makefile:560: obj/benchmark.NATIVE.o] Error 1
make: *** Waiting for unfinished jobs....
```
Main message is _include/ext_lzma.h:12:10: fatal error: minizip/ioapi.h: No such file or directory_.

**To Reproduce**
Gentoo.
Package sys-libs/zlib-ng compiled without "compat" flag.
Package sys-libs/zlib removed from system.
Package sys-libs/zlib-ng re-compiled with "compat" flag.
Package sys-libs/zlib marked as "provided" (/etc/portage/profile/package.provided).
Recompilation of hashcat fails as it require zlib with minizip mode, but zlib-ng does not support minizip mode.

**Expected behavior**
I want hashcat source code without minizip dependency of zlib package.

**Hashcat version:**
 - OS: Linux
 - Distribution: Gentoo
 - Version: 6.2.1-r1

**Comment by jsteube** [comment]
This is not a dependency from hashcat, but from LZMA SDK. We can't do anything.

**Comment by Bogdan107** [comment]
Problem resolved by compilation of hashcat with USE_SYSTEM_ZLIB=0 variable.
Bug for ebuild [reported](https://bugs.gentoo.org/803395).

**Comment by Bogdan107** [comment]
`ioapi` interface does not supoprted in minizip-ng. Details at [https://github.com/zlib-ng/minizip-ng/issues/447](https://github.com/zlib-ng/minizip-ng/issues/447)
