### ISSUE TITLE
support for punbb hashes

### ISSUE THREAD

**Issue by d2-d2** [hashcat/hashcat#29]
Hello, this is a follow up from forum thread: https://hashcat.net/forum/thread-4926-post-27675.html#pid27675

Would it be possible to add sha1($salt.sha1($pass)) into oclHashcat? There is already one (Redmine, -m 7600) but it uses 32 long salts.

Looking at the supported algos there is -m 3710 which is for MD5, so perhaps similar thing can be done with sha1 as well?

**Comment by philsmd** [comment]
Wait, is this a specific hash format ? I.e. is this a request for a generic sha1 ($salt . sha1 ($pass)) implementation or a request for a very specific hash algorithm used for a cms/forum etc?

If this is a request for a specific hash algorithm, what are the details about the limitations and input format etc ? max password length, max salt length, hash format used etc would be interesting for a specific cms/forum algorithm.

**Comment by d2-d2** [comment]
Thanks philsmd, so let me explain that a bit.

So this hash is used by PunBB forum, right? And as far as I can tell version 1.3.x version of that CMS is using following functions to produce hashes:

```
$salt = random_key(12);
$form_password_hash = forum_hash($form_password, $salt);
```

These two functions are as follow:

```
function random_key($len, $readable = false, $hash = false)
{
        $key = '';

        $return = ($hook = get_hook('fn_random_key_start')) ? eval($hook) : null;
        if ($return != null)
                return $return;

        if ($hash)
                $key = substr(sha1(uniqid(rand(), true)), 0, $len);
        else if ($readable)
        {
                $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

                for ($i = 0; $i < $len; ++$i)
                        $key .= substr($chars, (mt_rand() % strlen($chars)), 1);
        }
        else
                for ($i = 0; $i < $len; ++$i)
                        $key .= chr(mt_rand(33, 126));

        ($hook = get_hook('fn_random_key_end')) ? eval($hook) : null;

        return $key;
}
```

and

```
function forum_hash($str, $salt)
{
        $return = ($hook = get_hook('fn_forum_hash_start')) ? eval($hook) : null;
        if ($return != null)
                return $return;

        return sha1($salt.sha1($str));
}
```

So I think that's it for PunBB. Fixed salt length (12 characters) and sha1 function. But to be honest, if you could make two additional switches, one for PunBB and second one for any salt length that'd be great.

Do you think these options are possible?

**Comment by jsteube** [comment]
Just added with commit https://github.com/hashcat/hashcat/commit/e0c3f447da5b6f22321ae1e0660c41e1d01611d1
