### ISSUE TITLE
How to implement md5($salt1.$pass.$salt2)?

### ISSUE THREAD

**Issue by BeerFueledMayhem** [hashcat/hashcat#290]
Looking for advice on how to implement a format of md5($salt1.$pass.$salt2).

If it's just not plausible or there is a better way to deal with this I would appreciate that advice too.

Thanks

**Comment by jsteube** [comment]
There's currently no tutorial on how to add new hash-modes (I really should do that at some point). But several people managed to do it without. Just checkout the commit logs to find some of them.

**Comment by jsteube** [comment]
I just added sha1($salt1.$pass.$salt2) with commit https://github.com/hashcat/hashcat/commit/23917455efad1deba8c12516e192238f1609d8b7
Should be easy enought to replace the sha1 with md5

**Comment by ur7imd** [comment]
Can you make the same for md5, please?
