### ISSUE TITLE
Hashcat not working

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2911]
Unable to start. Output below:

```
$ hashcat -m 0 -a 0 hash wordlists/rockyou.txt 
hashcat (v6.2.2) starting...

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL or CUDA runtime installation.

* AMD GPUs on Linux require this driver:
  "RadeonOpenCompute (ROCm)" Software Platform (3.1 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)

Started: Wed Jul 28 14:30:19 2021
Stopped: Wed Jul 28 14:30:19 2021
```

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
```
Kernel: 5.11 (latest updated)

**Comment by roycewilliams** [comment]
It looks like the error contains your answer. Do you have one of the
required platforms installed?

**Comment by ghost** [comment]
Yes, I have NVIDIA. To use it on oryx7 from system76, you have to change the graphics card which I have done and always do. For some reason though, it doesn't work. And yes, the version is >440.64. I opened the issue here because I guessed that it could be a hashcat problem since I have NVIDIA running

**Comment by Chick3nman** [comment]
Could you post the output of `clinfo` as well as `nvidia-smi`? It looks like you are missing some critical headers or the runtime is missing from path or something. Need more info to be able to tell more.

**Comment by ghost** [comment]
Hi @Chick3nman 
Not sure what `clinfo` is but `nvidia-smi` returns "No devices were found"

**Comment by jsteube** [comment]
Not a hashcat issue. Hashcat issues are bugs and feature requests only. Please use hashcat forums instead.
