### ISSUE TITLE
SHA1DASH / sha1(--$salt--$pass--)

### ISSUE THREAD

**Issue by therealartifex** [hashcat/hashcat#2913]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**
For instance:
SHA1DASH is based on salted SHA1 with a prepended salt and two dashes ("--") surrounding and separating the salt and password.

**Describe alternatives you've considered**
The only alternative is to manually process your entire hashlist to add the dashes before and after the salt, then use hash mode 120 (sha1($salt:$pass)) in hashcat with the "-j '$-$-'" option, then manually process your potfile to remove the extra dashes at the end of every password.

**Provide an example hash/database/file and a known correct password**
```
0002b80997b9d9cc39f7895eebb762ce0a360bbd:224f9e85d91171f9b86c2d087f0fcc842e3f467f:Darwin97
00024a5845fcc9e5e069a0e8debf9a6ef0715e8b:3a0a8e8aec50cb0455b259ef6441e23e3e14675b:sammie13
00018fa5405406f024ef447a4d6d59afafbeae65:8ccb43ef51daf67244ca3ec13ff66df54aa79a64:Nathan08
3999d08db95797891ec77f07223ca81bf43e1be2:5dcc47b04c49d3c8e1b9e4ec367fddeed21b7b85:hashcat
```

**Explain how the cryptographic schema is implemented**
```sha1(--$salt--$pass--)```

**Describe the known limitations of the algorithm**
Limitations are equivalent to salted SHA1.

**Where do you typically find the algorithm**
Zynga, AnimalJam, 8tracks, Avvo, JobandTalent, IndabaMusic, and Thefaveapp, as seen on hashmob.net

**Additional context**
I'm reviving Issue https://github.com/hashcat/hashcat/issues/1987 because there are now several sites using it, and having a dedicated kernel would be a huge to those desiring to recover their lost passwords.

**Comment by Chick3nman** [comment]
I've commented on your PR already but I'll comment the same here for others to see it:

This hash algorithm, "SHA1DASH" as its known colloquially, is actually simply a slightly older variant of the default hashing scheme used by "Ruby on Rails Restful-Authentication", which you will see we have currently implemented as 19500. I would name and classify this mode following the actual origin of the algorithm and not what it's typically called if you'd like to add it to the official plugins. I would also suggest taking a look at the code we are currently using for 19500 as it is extremely similar, though it takes in a static "sitekey" as well, whereas this variant leaves that field blank. It also employs a slightly different number of rounds if my memory is correct. Getting most of the kernels, module, and tests from the existing code is generally a pretty safe bet when creating a plugin for something that's so similar to an already existing mode.

As for the reasoning for why we should add it, I'd like to point out that cracking passwords from leaks/breaches is not the main goal of hashcat or a good portion of its users as it generally falls into a grey area in terms of legality and/or ethics, barring academic research or similar This is a tool for recovery of one's own lost passwords or for use where permission/authorization are given.
