### ISSUE TITLE
Hashcat - WPA-EAPOL-PBKDF2 - Not show that it found the password during the running

### ISSUE THREAD

**Issue by D3vil0p3r** [hashcat/hashcat#2923]
Hello everyone,
I'm looking for an issue on hashcat where, if I try to crack a WPA key by passing as input a .hccapx file by using a wordlist with the real password, the hashcat process goes to Exhaust without finding the solution.
Doing some analysis, and watching some already Issues opened here (i.e. #2328 by @NimaaaNomaaa), I read that the conclusion was that the .hccapx files were junked because converters issue. I don't think could be that the problem but could be related to hashcat, related the way hashcat reads pcap file with a lot of wifi network information.

I'm using:

> Operating System: Parrot OS 4.11
> Kernel: Linux 5.10.0-6parrot1-cloud-amd64
> Architecture: x86-64
> hashcat version: v6.1.1
> hashcatutils: v1.9
> hcxpcapngtool: 6.2.0-46-g05c6121 (C) 2021 ZeroBeat
> Hash Target: WPA-EAPOL-PBKDF2

At the beginning, I have this .zip file containing a .pcap file that should have several wifi network session information.
[Hashcat_wireless1.zip](https://github.com/hashcat/hashcat/files/6913110/Hashcat_wireless1.zip)

I converted the .pcap file in hccapx file by using two separated tools:

- hashcatutils-> cap2hccapx.bin tool: `./cap2hccapx.bin corp_capture1-01.cap mic_to_crack.hccapx`
- hcxpcapngtool: `hcxpcaptool -o mic_to_crack.hccapx corp_capture1-01.cap`

In each of both cases, the output file is mic_to_crack.hccapx.

Now I make a wordlist of three strings containing also the password: 1212312121. I save this file as wl.txt that will be:

> hello@!
> 1212312121
> hashcat!

Let's run hashcat:

`hashcat -m 2500 mic_to_crack.hccapx -a 0 wl.txt`

The result will be:

> cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121   
> cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121   
>                                                  
> Session..........: hashcat
> Status...........: Exhausted
> Hash.Name........: WPA-EAPOL-PBKDF2
> Hash.Target......: mic_to_crack.hccapx
> Time.Started.....: Sun Aug  1 17:58:18 2021 (0 secs)
> Time.Estimated...: Sun Aug  1 17:58:18 2021 (0 secs)
> Guess.Base.......: File (wl.txt)
> Guess.Queue......: 1/1 (100.00%)
> Speed.#1.........:      338 H/s (0.50ms) @ Accel:128 Loops:512 Thr:1 Vec:8
> Recovered........: 2/7 (28.57%) Digests
> Progress.........: 3/3 (100.00%)
> Rejected.........: 1/3 (33.33%)
> Restore.Point....: 3/3 (100.00%)
> Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:6-13
> Candidates.#1....: 1212312121 -> hashcat!

So it states "Exhausted" but if we go on ".hashcat/hashcat.potfile", we can read the correct password:

> c8992e066686c8155d0f5f9674e1c818024172349f90512f32e82c7a2e37960e*434f52502d57494649:1212312121
> c8992e066686c8155d0f5f9674e1c818024172349f90512f32e82c7a2e37960e*434f52502d57494649:1212312121

So, hashcat stores the correct password in hashcat.potfile but during the run it does not say that it found.

Let's try to analyze brutally the mic_to_crack.hccapx.

Unlike the example file "[https://hashcat.net/misc/example_hashes/hashcat.hccapx](https://hashcat.net/misc/example_hashes/hashcat.hccapx)" that contains only a row with onlye one"HCPX ..... " string, the usual cases with more wifi network traffic like mic_to_crack.hccapx contains more strings with "HCPX ..... ".

If we edit brutally "mic_to_crack.hccapx" file by nano/vim/other text editors by deleting all the strings related to the previous "HCPX ..." pattern except the last one, and we save it like "mic_to_crack_edited.hccapx", we run it with hashcat as before:

`hashcat -m 2500 mic_to_crack_edited.hccapx -a 0 wl.txt` 

The output will be:

> cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121   
>                                                  
> Session..........: hashcat
> Status...........: Cracked
> Hash.Name........: WPA-EAPOL-PBKDF2
> Hash.Target......: CORP-WIFI (AP:cc:40:d0:a4:d0:96 STA:48:e2:44:a7:c4:fb)
> Time.Started.....: Sun Aug  1 18:09:43 2021 (0 secs)
> Time.Estimated...: Sun Aug  1 18:09:43 2021 (0 secs)
> Guess.Base.......: File (wl.txt)
> Guess.Queue......: 1/1 (100.00%)
> Speed.#1.........:      327 H/s (0.26ms) @ Accel:256 Loops:256 Thr:1 Vec:8
> Recovered........: 1/1 (100.00%) Digests
> Progress.........: 3/3 (100.00%)
> Rejected.........: 1/3 (33.33%)
> Restore.Point....: 0/3 (0.00%)
> Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
> Candidates.#1....: 1212312121 -> hashcat!

So it worked correctly.

Will be the main difference between the mic_to_crack case and the mic_to_crack_edited/hashcat.hccapx example?
It seems that in the first case we have more wifi sessions to crack (in this case 2) while in the second cases [mic_to_crack_edited/hashcat.hccapx example] we have only one wifi session to crack.

The issue will be that, if it gets exhausted, for long wordlist, even if find some password, it does not end immediately but will parse all the password lists.
How can we solve this issue?

If you need more information, I'm available.

Thank you in advance

**Comment by ZerBea** [comment]
No problem here, running hash mode 22000:

converting dump file to hash file:
```
$ hcxpcapngtool -o test.hc22000 corp_question1-01.cap
hcxpcapngtool 6.2.0-42-gcb7bf91 reading from corp_question1-01.cap...
failed to read pcap packet header for packet 95415

summary capture file
--------------------
file name................................: corp_question1-01.cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 17.07.2020 00:07:54
timestamp maximum (GMT)..................: 17.07.2020 00:12:43
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105)
endianess (capture system)...............: little endian
packets inside...........................: 95415
BEACON (total)...........................: 1
ACTION (total)...........................: 11
PROBERESPONSE............................: 432
DEAUTHENTICATION (total).................: 48668
AUTHENTICATION (total)...................: 327
AUTHENTICATION (OPEN SYSTEM).............: 327
ASSOCIATIONREQUEST (total)...............: 80
ASSOCIATIONREQUEST (PSK).................: 80
REASSOCIATIONREQUEST (total).............: 50
REASSOCIATIONREQUEST (PSK)...............: 50
WPA encrypted............................: 1145
EAPOL messages (total)...................: 22
EAPOL RSN messages.......................: 22
ESSID (total unique).....................: 1
EAPOLTIME gap (measured maximum usec)....: 110274420
EAPOL ANONCE error corrections (NC)......: not detected
REPLAYCOUNT gap (measured maximum).......: 2
EAPOL M1 messages (total)................: 8
EAPOL M2 messages (total)................: 5
EAPOL M3 messages (total)................: 6
EAPOL M4 messages (total)................: 3
EAPOL pairs (total)......................: 11
EAPOL pairs (best).......................: 2
EAPOL pairs written to combi hash file...: 2 (RC checked)
EAPOL M12E2 (challenge)..................: 1
EAPOL M32E2 (authorized).................: 1
packet read error........................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Warning: excessive number of deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER,
renew ANONCE and set PMKID to zero.
This could prevent to calculate a valid EAPOL MESSAGE PAIR
or to get a valid PMKID.

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.


session summary
---------------
processed cap files...................: 1
```

Runnig hashcat on that hash file:
```
$ hashcat -m 22000 test.hc22000 wordlist
hashcat (v6.2.3-87-gd4997d125) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce GTX 1080 Ti, 10638/11175 MB, 28MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.94) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce GTX 1080 Ti, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 4 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 2950 MB

Dictionary cache built:
* Filename..: wordlist
* Passwords.: 2
* Bytes.....: 20
* Keyspace..: 2
* Runtime...: 0 secs

Approaching final keyspace - workload adjusted.           

92a9fe85d5656281517162c33c0f62b6:cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121
b7703fd2171bec7933ffc900faa6eb5b:cc40d0a4d096:80822381a9c8:CORP-WIFI:rockyou1
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Name........: WPA-PBKDF2-PMKID+EAPOL
Hash.Target......: test.hc22000
Time.Started.....: Sun Aug  1 21:20:58 2021 (0 secs)
Time.Estimated...: Sun Aug  1 21:20:58 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (wordlist)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:       56 H/s (1.43ms) @ Accel:8 Loops:256 Thr:512 Vec:1
Recovered........: 2/2 (100.00%) Digests
Progress.........: 2/2 (100.00%)
Rejected.........: 0/2 (0.00%)
Restore.Point....: 0/2 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1-3
Candidate.Engine.: Device Generator
Candidates.#1....: 1212312121 -> rockyou1
Hardware.Mon.#1..: Temp: 56c Fan: 38% Util:  0% Core:1860MHz Mem:5005MHz Bus:16

Started: Sun Aug  1 21:20:56 2021
Stopped: Sun Aug  1 21:20:59 2021
```

Conclusion:
For me it looks like the tool used for capturing and attacking the network is buggy.
Too many deauthentications transmitted.
Deprecated hash mode 2500 is used instead of new hash mode 22000
cap2hccapx is outdated.

The issue is related to the dump tool, the attack tool and the conversion tool, while hashcat is working as expected:
both hashes are detected and converted correctly to hc22000 hash file:
EAPOL pairs (best).......................: 2

and both PSKs are recovered by hash cat
Recovered........: 2/2 (100.00%) Digests

client 48e244a7c4fb tried to connect to the network CORP-WIFI using the PSK 1212312121
client 80822381a9c8  tried to connect to the network CORP-WIFI using the PSK rockyou1

**Comment by jsteube** [comment]
Correct, hccapx is outdated, please stick to -m 22000.

**Comment by ZerBea** [comment]
I recommend to use hcxdumptool to capture the traffic and hcxpcapngtool to convert the traffic to hash file 22000.
Than run hashcat in mode 22000

BTW:
Both PSKs are recovered by wpa-sec, too (which run hcxtools in background):
https://wpa-sec.stanev.org/?search=cc%3A40%3Ad0%3Aa4%3Ad0%3A96

**Comment by ZerBea** [comment]
@D3vil0per , may I ask a question:
What tool do you use to capture the traffic and to attack the target?
48668 deauthentications to get a get a handshake is really excessive:
DEAUTHENTICATION (total).................: 48668
There are also many timestamp errors inside the dump file, which is a bug of the capturing tool.

**Comment by D3vil0p3r** [comment]
@ZeaBea the .pcap file comes from an exercise of Hack The Box environment (https://www.hackthebox.eu/) where they provided directly the .pcap file but I don't know which capturing tool they used.

**Comment by ZerBea** [comment]
Thanks for your answer.
A good dump tool / attack tool in combination with a good conversion tool let hashcat work as expected.
The new hash mode 22000 will make life easier. Atom did a great work, here.

BTW:
I edited my comment:
https://github.com/hashcat/hashcat/issues/2923#issuecomment-890572981
to explain what exactly happened.

**Comment by ZerBea** [comment]
To verify my comments you can run the following commands:
$ wget https://wpa-sec.stanev.org/dict/cracked.txt.gz
$ hcxpcapngtool -o test.hc22000 corp_question1-01.cap
$ hashcat -m 22000 test.hc22000 cracked.txt.gz

hashcat will do the rest:
92a9fe85d5656281517162c33c0f62b6:cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121
b7703fd2171bec7933ffc900faa6eb5b:cc40d0a4d096:80822381a9c8:CORP-WIFI:rockyou1
Recovered........: 2/2 (100.00%) Digests

Cheers
Mike

**Comment by D3vil0p3r** [comment]
@ZerBea It works following your suggestion.
About cap2hccapx.bin, I know it is part of hashcat-utils repository. In your opinion, should I open an issue there for cap2hccapx.bin or this tool is out of support?

Thank you

**Comment by ZerBea** [comment]
hcxtools provide several tools to work on WPA related traffic and hashes. To get information about the hash file, you can use hcxhashtool:

```
$ hcxhashtool -i test.hc22000 --info=stdout
SSID.......: CORP-WIFI
MAC_AP.....: cc40d0a4d096 (NETGEAR)
MAC_CLIENT.: 48e244a7c4fb (Hon Hai Precision Ind. Co.,Ltd.)
VERSION....: 802.1X-2001 (1)
KEY VERSION: WPA2
REPLAYCOUNT: 1
RC INFO....: NC not required
MP M2M3 E2.: authorized
MIC........: 92a9fe85d5656281517162c33c0f62b6
HASHLINE...: WPA*02*92a9fe85d5656281517162c33c0f62b6*cc40d0a4d096*48e244a7c4fb*434f52502d57494649*062267437c90d9185d010b9dabdbbae1b014e4ee435b93e5cdfea39b79eadd4a*0103007502010a000000000000000000015a494f36fadc4671749191c507b538920e7b1a42f01fc9faed572e61c5e035ed000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630140100000fac040100000fac040100000fac020000*02

SSID.......: CORP-WIFI
MAC_AP.....: cc40d0a4d096 (NETGEAR)
MAC_CLIENT.: 80822381a9c8 (Apple, Inc.)
VERSION....: 802.1X-2001 (1)
KEY VERSION: WPA2
REPLAYCOUNT: 3
RC INFO....: NC not required
MP M1M2 E2.: challenge
MIC........: b7703fd2171bec7933ffc900faa6eb5b
HASHLINE...: WPA*02*b7703fd2171bec7933ffc900faa6eb5b*cc40d0a4d096*80822381a9c8*434f52502d57494649*09f8fed1b3f740126b61ff3a9a2da482712ccbfd73d4e555fefe50568faf7075*0103007502010a0010000000000000000321c9245f339ac3d486b85a9f8f3bc0092befdecd2859411acab4941f31c94de4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630140100000fac040100000fac040100000fac020c00*00


OUI information file...: /home/zerobeat/.hcxtools/oui.txt
OUI entires............: 29871
total lines read.......: 2
valid hash lines.......: 2
EAPOL hash lines.......: 2
EAPOL written..........: 2
```

As you can see, we have an authorized CLIENT which belong to the NETWORK:
```
SSID.......: CORP-WIFI
MAC_AP.....: cc40d0a4d096 (NETGEAR)
MAC_CLIENT.: 48e244a7c4fb (Hon Hai Precision Ind. Co.,Ltd.)
VERSION....: 802.1X-2001 (1)
KEY VERSION: WPA2
REPLAYCOUNT: 1
RC INFO....: NC not required
MP M2M3 E2.: authorized
MIC........: 92a9fe85d5656281517162c33c0f62b6
```

and a not authorized CLIENT which doesn't belong to the NETWORK:
```
SSID.......: CORP-WIFI
MAC_AP.....: cc40d0a4d096 (NETGEAR)
MAC_CLIENT.: 80822381a9c8 (Apple, Inc.)
VERSION....: 802.1X-2001 (1)
KEY VERSION: WPA2
REPLAYCOUNT: 3
RC INFO....: NC not required
MP M1M2 E2.: challenge
MIC........: b7703fd2171bec7933ffc900faa6eb5b
```

Using hcxtools in combination with hashcat, you will get the PSK of both of them for the price (PBKDF2 calculation time) of one.
```
92a9fe85d5656281517162c33c0f62b6:cc40d0a4d096:48e244a7c4fb:CORP-WIFI:1212312121
b7703fd2171bec7933ffc900faa6eb5b:cc40d0a4d096:80822381a9c8:CORP-WIFI:rockyou1
```

BTW:
If you use hcxdumptool or hcxlabtool series (dump and attack), you will perform high density/speed attacks on that NETWORK and retrieve additional information hashcat can work on:
hcxdumptool/hcxlabtool -> hcxpcapngtool -> (hcxpsktool) -> hashcat

We use pcapng comment fields and message pair fields to communicate between the tools within the cracking work flow.

**Comment by jsteube** [comment]
> @ZerBea It works following your suggestion.
> About cap2hccapx.bin, I know it is part of hashcat-utils repository. In your opinion, should I open an issue there for cap2hccapx.bin or this tool is out of support?
> 
> Thank you

No need to, this tool is deprecated. Please follow @ZerBea suggestions

**Comment by ZerBea** [comment]
I recommend this procedure on every new dump file:
upload dumpfile to wpa-sec (either via web interface or via wlancap2wpasec and wait a day)
Than get the results:
$ wget https://wpa-sec.stanev.org/dict/cracked.txt.gz
$ hcxpcapngtool -o test.hc22000 corp_question1-01.cap
$ hashcat -m 22000 test.hc22000 cracked.txt.gz

Try to get PSK from WLAN traffic: attack network by hcxdumptool/hcxlabtool
$ hcxdumptool -i interface --enable_status=1 --active_beacon  -o dumpfile.pcapng
$ hcxpcapngtool -o test.hc22000 -E wordlist dumfile.pcapng
$ hashcat -m 22000 test.hc22000 wordlist

**Comment by ZerBea** [comment]
Some words about this warning:
```
Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.
```

Do not use filter options on the receiving branch. Everything that is filtered out is gone forever.
Do not use cleaning tools which remove useful/important frames from the dumpfile.
hcxpcapngtool is able to detect this behavior and print a warning.
 
Please read this comment:
https://github.com/evilsocket/pwnagotchi/issues/835#issuecomment-598597214
and make up your own mind.

**Comment by D3vil0p3r** [comment]
Hello,
I confirm what you reported. 

Thank you for your support.

**Comment by ZerBea** [comment]
Glad to hear this.
The new has mode has many advantages - that's why Atom decided to add it to hashcat.
