### ISSUE TITLE
Metamask (26600)  Token length exception

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2927]
Try to submit hash 1532 word lenght, hashcat error 
`Hashfile 'C:\hashcat\task.txt' on line 1 ($metam...***): Token length exception
No hashes loaded.`

**Comment by ghost** [comment]
If the metamask vault contain more than 5 wallets, it has long hash, hashcat can`t read it

Hashfile 'C:\work\hashcat\task.txt' on line 1 ($metam...==): Token length exception
No hashes loaded.

**Comment by jsteube** [comment]
@kipilk0 Did you try using @matrix new extraction tool?

**Comment by matrix** [comment]
@kipilk0 please include files that can be used to test

**Comment by ghost** [comment]
> 
> 
> @kipilk0 Did you try using @matrix new extraction tool?

Yes.

> 
> 
> @kipilk0 please include files that can be used to test

Sorry, i can`t send you hash due , because it have private data.
$metamask$ hash has 1300+ symbols length

**Comment by 123Serg** [comment]
@matrix I have same error, some of my hashes have big length, can you increase hash length limit to 2000-3000 sybmols please?

**Comment by ghost** [comment]
Metamask hash contain sensetive info , you have private e-mail where i can send hash ?

**Comment by ghost** [comment]
Hashes >1000 length with error
https://i.imgur.com/RgUldAK.png

**Comment by matrix** [comment]
Hi, could you please try this version? I doubled the length of the ciphertext

https://github.com/matrix/hashcat/tree/metamask_big

Let us know, thanks

**Comment by jsteube** [comment]
@matrix Why no PR? Are you unsure if it will still work?

**Comment by matrix** [comment]
> @matrix Why no PR? Are you unsure if it will still work?

I'm not sure if it's enough to double up. Maybe we need to triple the length, let's see what they say :)

**Comment by its5Q** [comment]
> > @matrix Why no PR? Are you unsure if it will still work?
> 
> I'm not sure if it's enough to double up. Maybe we need to triple the length, let's see what they say :)

I've tested bruteforcing a wallet with 10 accounts with your branch, and the hash was pretty long, and it worked, so I think the length is good enough.

**Comment by matrix** [comment]
> > > @matrix Why no PR? Are you unsure if it will still work?
> > 
> > 
> > I'm not sure if it's enough to double up. Maybe we need to triple the length, let's see what they say :)
> 
> I've tested bruteforcing a wallet with 10 accounts with your branch, and the hash was pretty long, and it worked, so I think the length is good enough.

Well. I'm waiting @123Serg and @kipilk0 feedback before PR. Thanks :)

**Comment by its5Q** [comment]
Just tried it with my Binance Chain wallet, and it turns out binance stores a lot of data in the vault, so I couldn't crack it even with doubled length, even though it worked on a metamask wallet with 50!! addresses.

**Comment by matrix** [comment]
> Just tried it with my Binance Chain wallet, and it turns out binance stores a lot of data in the vault, so I couldn't crack it even with doubled length, even though it worked on a metamask wallet with 50!! addresses.

what's the len of the ciphertext?

**Comment by its5Q** [comment]
> > Just tried it with my Binance Chain wallet, and it turns out binance stores a lot of data in the vault, so I couldn't crack it even with doubled length, even though it worked on a metamask wallet with 50!! addresses.
> 
> what's the len of the ciphertext?

The encrypted data length, or the whole hash? The whole hash is 3177 characters long.

**Comment by matrix** [comment]
only data

**Comment by its5Q** [comment]
> only data

The data is 3096 characters long.

**Comment by its5Q** [comment]
> only data

Also, sorry for the off-topic question, but why with your branch version that I compiled it builds the dictionary cache each time I run the attack with the same dictionary? That's not the case with the release version, and I don't think it should be doing that

**Comment by matrix** [comment]
Please retry again with https://github.com/matrix/hashcat/tree/metamask_big

**Comment by its5Q** [comment]
> Please retry again with https://github.com/matrix/hashcat/tree/metamask_big

Tried that, for me it works great now, didn't have any length problems.

**Comment by 123Serg** [comment]
Hey, one of my hashes length is 11500 symbols, @matrix can you please increase maximal hash length more please? 
Thanks

**Comment by 123Serg** [comment]
so can somebody help with increasing hash maximal length limit please?
