### ISSUE TITLE
Small wordlist slowness/not using all gpus

### ISSUE THREAD

**Issue by jj2hh2hasdf** [hashcat/hashcat#2929]
**Describe the issue**
The issue is that hashcat is isn't using all gpus/1 gpu full speed when using smaller wordlists... this is a huge problem when it comes to slow hashes like bcrypt etc..

**To Reproduce**
Run 100k bcrypt hashes + 1k wordlist

**Expected behavior**
I expect it to use all gpus available and maybe at least use the same amount of power as it uses normally.

Example:

If I would have had let's say 6 pc's with a gpu each and split the hashlist into 6 equal splits and run the same 1k wordlist on all of those runs I would get 6x the speed of running it on 1x pc with 6 gpus...

I got total of 1700h/s with all my gpus (it used 3 gpus only out of 6 and not full speed on any of those 3 gpus) combined BUT when I only used 1 of those gpus (ex: -d 1) I got 1700h/s on that one gpu, so that leads me to believe that there is a way to make hashcat better on handling small wordlists. 

I truly hope this gets some sort of fix/method since bcrypt and other slower hashes is just getting more and more used now days...

Things I tried:

piping the wordlist into hashcat, didn't do anything except only using 1 of the 6 gpus at 1700h/s instead of mixing when providing the wordlist directly to hashcat.

trying bigger wordlists indeed makes it use almost 100% of the speed that can be used but yea that is not optimal since it will take a lot of weeks to complete and doesn't really solve the small wordlist issue.

**Comment by Chick3nman** [comment]
This is not an issue and is simply related to the way we distribute work. Your attack design can be changed to fix this issue, as it stems from not understanding the underlying design architecture and not from an issue/problem.

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_is_it_possible_that_hashcat_does_not_utilize_all_gpus

You could pass the `-S` flag to indicate to hashcat that you have a small number of incoming candidates and help it distribute work better, but you may not see much better results on such a small wordlist and such a large list of salted, slow hashes.  A better option would be to rethink the way you have designed your attack. If you'd like to discuss this in more detail, please post on the forums or visit our IRC or Discord server as it is not a problem with hashcat but with the attack. If you find that you can not resolve this after redesigning your attack, we can reopen this issue as a possible feature request, but for now I'm going to close it as no issue.
