### ISSUE TITLE
Generate rules (upgrade)

### ISSUE THREAD

**Issue by SoSander** [hashcat/hashcat#2933]
I’ve got some idea that it would be nice if you could select a type of rule generation for example if I only need append and prepend rules that I could do --generate-rules-funcs-allowed=a,p and it would only generate rules that contain append & prepend rules the same for insert, replace and maybe even Unicode rules (if they are supported in the future)

**Comment by jsteube** [comment]
We should stick to the original function operators. So $ for append and ^ for prepend. But generally I like the idea.

**Comment by SoSander** [comment]
Sure it was just the example of a command

**Comment by jsteube** [comment]
Added with commit https://github.com/hashcat/hashcat/commit/05f107cbe59476dc5b5701e990c525abdd946fd6
