### ISSUE TITLE
[FR] allow for --debug-file to be used for matched and unmatched candidates

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#2938]
It would be really great to be able to see the 'before_rule:rule:after_rule' of a candidate regardless of it matching or not. Would it be possible to allow for the --debug-file to be used to output the results for matched and unmatched candidates? 

Maybe something along the lines of: 
--debug-mode=5 --debug-file=unmatched.rule --keep-guessing 

results in unmatched.rule would contain the exact same results as --debug-mode=4 but output all results (not just matched). Obviously this would be used in certain situations to do analysis on plains, before/after rules, and things like Levenshtein distance ,just to name a few scenarios.

**Comment by Chick3nman** [comment]
This is essentially what `--stdout` is for, as it produces all candidates generated, include after a rule is applied. Doing this in attack using the debug flag makes pretty much 0 sense as you will basically be dumping nearly the same results as `--stdout` to a file, except with pre-processed word and rule included. There's not really a reasonable way to parse such a large output of candidates with preprocessed:rule:post-processed as well, as any amount that you can look at by hand can be done separately using `--stdout`. Any tool or script that could parse the output for you would be doing nearly as much work as a tool that could generate the candidates for you, so it wouldn't make sense not to just do that. I don't really see an application for this, but I will leave this open for further discussion. I might just not understand the request fully. If you would like to discuss this a little easier, you can always come and chat about it in our [Discord](https://discord.com/invite/HFS523HGBT).
