### ISSUE TITLE
Minor error in Makefile

### ISSUE THREAD

**Issue by JirkaV** [hashcat/hashcat#294]
I just successfully built latest version on Windows using the MSys2 build environment. But I had to massage the Makefile a bit - while the BUILD documentation clearly says how to compile on Windows (so I assume it's supported), the default Makefile checks if platform is "Linux" or "Darvin". 

After removing the check (and changing the compiler in Makefile for CC_WIN_64 to just "gcc"), it comiled just fine. 

Maybe the Makefile check can be updated or removed?

**Comment by neheb** [comment]
the hashcat developers cross compile to windows from linux. hence the initial check.

pull requests always welcome.

**Comment by jsteube** [comment]
It's good to know you were able to compile it from Windows directly. We actually use the win\* targets only for cross compiling from linux. If you want to send in some PR, your change should affect the "native" target. That would be great!

**Comment by JirkaV** [comment]
I actually were not able to compile it using a native compiler, I used https://github.com/msys2. The reported OS in Makefile was "MSYS_NT-6.1".

I won't be submitting a pull request for this - I think this is an edge case and frankly, I'm not too experienced at neither WIndows nor cross compiling, so wouldn't trust the quality of my patch :/

Leaving this here in case someone needs to compile on Windows. The MSys2 path works, but Makefile needs to be hacked a bit.
