### ISSUE TITLE
[FR] add hash number to Hash.Name line

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#2945]
Could the hash number be added to Hash.Name line? I ask this because I use scripts to run hashcat and often end up having to look up the hash number at a later point of the run. 

Something like this: 
Hash.Name........: Blockchain, My Wallet, V2    (15200)
Hash.Name........: SHA1   (100)

or this:
Hash.Name...(15200): Blockchain, My Wallet, V2  
Hash.Name.....(100): SHA1

**Comment by 0xVavaldi** [comment]
Created a PR to resolve this ticket. The mode is kind of in the command and users have to specify it when they run their command. They can also check the hash.name on the site to verify which mode they ran so it's a little redundant.

I'll leave it to the devs to decide if they'd want this added or not.

**Comment by 0xVavaldi** [comment]
This can be closed @jsteube.
