### ISSUE TITLE
NTLM optimized kernel throws "clLinkProgram(): CL_LINK_PROGRAM_FAILURE"

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#2951]
Running hashcat using hash type 1000 (NTLM) _optmized_ kernel throws the following error:

```
$ ./hashcat.exe --hash-type 1000 -O --attack-mode 0 hashes/ntlm.hash ./top1m.txt
hashcat (v6.2.3) starting

OpenCL API (OpenCL 2.1 AMD-APP (3004.8)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: Radeon RX 580 Series, 8128/8192 MB (4048 MB allocatable), 36MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 27

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Optimized-Kernel
* Zero-Byte
* Precompute-Init
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #1. Please be patient...Error: Call of undefined function
clLinkProgram(): CL_LINK_PROGRAM_FAILURE

* Device #1: Kernel ./OpenCL/m01000_a0-optimized.cl build failed.

Started: Wed Aug 25 18:06:02 2021
Stopped: Wed Aug 25 18:06:05 2021
```

Removing the optimized kernel flag (-O) allows it to work, although at a much slower rate.

This issue seems to affect attack types 0 (straight), 1 (combination), 6 (wordlist + mask), and 7 (mask + wordlist).  Attack mode 3 (brute force) works correctly.  Attack mode 9 (association) wasn't tested.

I'm sure sure which version introduced this bug.  I was previously using 6.1.1 with no problems in any of these configurations.

Please let me know if there's any other info I can provide to help.  Thanks!

**Comment by hops** [comment]
This might be related to a bug introduced when support for HIP was added. If so it's already been fixed (after v6.2.3 was released)
Could you try using the beta from https://hashcat.net/beta/ and report back?

**Comment by llamasoft** [comment]
Nope, the issue persists.  Although I do get a new warning about hipFuncGetAttribute:

```
$ ./hashcat.exe --hash-type 1000 -O --attack-mode 0 hashes/ntlm.hash ./top1m.txt
hashcat (v6.2.3-261-gdaea190be) starting

hipFuncGetAttribute is missing from HIP shared library.

OpenCL API (OpenCL 2.1 AMD-APP (3004.8)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: Radeon RX 580 Series, 8064/8192 MB (4048 MB allocatable), 36MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 27

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Optimized-Kernel
* Zero-Byte
* Precompute-Init
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #1. Please be patient...Error: Call of undefined function
clLinkProgram(): CL_LINK_PROGRAM_FAILURE

* Device #1: Kernel ./OpenCL/m01000_a0-optimized.cl build failed.

Started: Thu Aug 26 17:19:54 2021
Stopped: Thu Aug 26 17:19:59 2021
```

Just as before, using `--benchmark --hash-type 1000 -O` works just fine.  I believe it uses the "a3" kernel which I haven't had issues with.

**Comment by Liverrrrr** [comment]
I don't know if there is already an issue for this, but something similar also happens to me any time I try to use hashcat with a 7100 hash. I tried pre-compiled binaries as well as compiling myself, which only gave me an additional error when i run the benchmark that says `Device #1: Not enough allocatable device memory for this attack.` (md5).

**Comment by llamasoft** [comment]
> I don't know if there is already an issue for this, but something similar also happens to me any time I try to use hashcat with a 7100 hash. I tried pre-compiled binaries as well as compiling myself, which only gave me an additional error when i run the benchmark that says `Device #1: Not enough allocatable device memory for this attack.` (md5).

That sounds unrelated.  You might want to open a separate issue for it.

**Comment by Liverrrrr** [comment]
Actually that device memory issue seems to be fixed when I went to hashacat.net and downloaded the official 6.2.3 release binaries and compiled it from there, but i still get this error on the 7100 without optimized kernel mode enabled...
```
clLinkProgram(): CL_LINK_PROGRAM_FAILURE

* Device #1: Kernel /c/users/ollie/downloads/hashcat-6.2.3/OpenCL/m07100-pure.cl build failed.
```
and with it, it says:
```
Kernel /c/users/ollie/downloads/hashcat-6.2.3/OpenCL/m07100-optimized.cl:
Optimized kernel requested, but not available or not required
Falling back to pure kernel
```
and then just displays the previous error. But I have only tried this with attack mode 3.

**Comment by jsteube** [comment]
It seems the legacy AMD driver on Linux fails to support clLinkProgram() which is a required function for OpenCL spec compatibility. Also HIP support is for future driver version which is not yet released by AMD.

**Comment by llamasoft** [comment]
Is `clLinkProgram` only used by the a0 and not the a3 kernel?  
Also it appears that `clLinkProgram` has been part of the OpenCL spec since v1.2.  I can't imagine why it wouldn't be present on my OpenCL 2.1 drivers.

If I had to hazard a guess, I don't think "Error: Call of undefined function" is referring to `clLinkProgram`.  I think the linking step discovered an unsatisfied external function call.  Unfortunately, it's not telling us _what_ function that is.  I tried running with `CL_LOG_ERRORS=stderr` but it provided no additional output.

**Comment by braindamagedjustnow** [comment]
Same thing happens to me (6900XT). I also tried to follow "I may have the wrong driver installed, what should I do?"
Reinstalled everything etc - still the same.
With hashcat 6.2.0 it's working as it should

**Comment by jsteube** [comment]
You can't do anything, neither can hashcat devs.

**Comment by braindamagedjustnow** [comment]
I guess I missed to write that I am on Windows 10. Also why I have no problems with 6.2.0 but it won't work on the latest version?

**Comment by llamasoft** [comment]
> You can't do anything, neither can hashcat devs.

Incorrect.  This appears to be fixed in the latest [hashcat beta](https://hashcat.net/beta/) (v6.2.4-25-g178003d69).  
Hash type 1000 (NTLM) optimized attack mode 0 now runs just fine for me.  It still throws a "hipFuncGetAttribute is missing from HIP shared library" warning but that doesn't seem to stop it.

It would be helpful if the device info (`-I`) flag showed HIP information.  It would make troubleshooting a lot easier.

**Comment by jsteube** [comment]
> It would be helpful if the device info (`-I`) flag showed HIP information. It would make troubleshooting a lot easier.

Is not possible, because the code that can be used to query versioning info is changed wildly by AMD, as well as versioning convention itself.
