### ISSUE TITLE
[FR] Allow option to clean hashfile and/or rulefile

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#2952]
Often when running large hashfiles or large rule files, invalid results will sneak in and cause dramatic slowdowns as well as issues with -a9. 

Example: Skipping invalid or unsupported rule in file ______
Example2: Hashfile 'hash.file' on line 90812935 (hash_here): Token encoding exception

It would be great if there was an option to remove bad hashes from the file or remove invalid rules, since it already knows that it's bad at the time of running. This would be nice so that the next time you're running it, you don't need to wait on the bad hashes or bad rules. It seems like it would be trivial enough to add a 'delete line' when it lists off the error messages saying the rule or hash is invalid?

Perhaps something along the lines of --clean_rulefile and --clean_hashfile

**Comment by jsteube** [comment]
I don't see how this affects performance, so this is not a valid FR. Also, 90m hashes is extreme, expect side effects.

**Comment by roycewilliams** [comment]
It takes a first pass, but you can use something like `-a 0 -m [mode] -O empty.txt --remove` to strip invalid hashes. (Thanks to @philsmd who first pointed this out to me.)

You can also use `--backend-ignore-opencl --left hashes.txt -m [mode] --potfile-path=/dev/null >cleaned.txt` to get the same effect, but it's less elegant.

**Comment by 0xVavaldi** [comment]
empty.txt --remove takes too much time since it goes over every blank password. With a list like bcrypt it's a lot of time.
--left is a lot faster - even if less elegant

**Comment by jsteube** [comment]
It's the opposite. The elegant solution is using --left. No clue why you think it's not elegant.
