### ISSUE TITLE
Teamspeak 3 channel hash feature request

### ISSUE THREAD

**Issue by mar232320** [hashcat/hashcat#2953]
I'd like to request adding Teamspeak 3 channel hash algorithm to hashcat

The algo is based on sha1 with the usage of base64
The exact algorithm is **base64(sha1(base64(sha1($pass))$virtualserver_keypair))**
The $virtualserver_keypair is 152 characters long so it's hard to bruteforce, but the user knows it and could supply it to the program. The hash colud also be converted from base64 to hex to improve the performance

I didn't found any application that supports that kind of hash. I've written myself an implementation in python but it works on CPU so it is much slower than hashcat

I found an example hash in my server database. Here they are:
hash **hDT8UKU9qEsSIj7qJSIiWWG6OZ8=**
password **2137**
virtualserver_keypair **MG4DAgeAAgEgAiBVIPQRIwRRH1XNno7fZ/oLt7OPPSenIVI8oGe7kPrg+QIhAMcTHy4mPua1/UHOSasSU2is655rZdoRgN5uvTldZXVtAiAmLuCr9Z6h8N7HMBEjrNj74ZBYAZNwF6rmzEglGiO09Q==**

There aren't any rules of the password

I found the hash in _channel_properties_ table of _ts3server.sqlitedb_ file in my teamspeak 3 server directory after I created channel with password

**Comment by jsteube** [comment]
152 bytes doesn't sound like something a developer would use for a hard coded length. Can we be sure this is a fixed length? What happens if you add another channel, maybe with a different parent channel, and a different password?

**Comment by mar232320** [comment]
The keypair is base64 encoded with the padding. I have made a few tests and the length is always 152 and base64 decoded keypair is **always** 112 characters long. The keypair doesn't change when I add new channels and subchannels and it doesn't depend of the password. Subchannel password hashes are generated using the same algorithm.

**Comment by mar232320** [comment]
Would it be added to public hashcat release or I would have to build it myself?

**Comment by jsteube** [comment]
I'll start working on this. I'll follow the hash format suggested in the JtR issue https://github.com/openwall/john/issues/4845

```
$teamspeak$3$vj8j6o/n/zeoK7mfe5jcliewMF0=$MG4DAgeAAgEgAiBVIPQRIwRRH1XNno7fZ/oLt7OPPSenIVI8oGe7kPrg+QIhAMcTHy4mPua1/UHOSasSU2is655rZdoRgN5uvTldZXVtAiAmLuCr9Z6h8N7HMBEjrNj74ZBYAZNwF6rmzEglGiO09Q==:abc
```

**Comment by jsteube** [comment]
Support has been added to hashcat with commits:

https://github.com/hashcat/hashcat/commit/c80ec44fdd9f984f399cf46970b6241f2efc6bfd
https://github.com/hashcat/hashcat/commit/0d304b68f1f20e9b1335da2093871f36771be048
https://github.com/hashcat/hashcat/commit/7e9bad7519618257aa0eefc0be25ab693cef5f58

```
root@ht:~/hashcat# ./hashcat -m 28300 hash.txt -a 3 ?l?l?l?l?l?l?l -w 3  
hashcat (v6.2.5-45-g0d304b68f) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10855/11019 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.56) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 2080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Early-Skip
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1474 MB

$teamspeak$3$E0aV0IQ29EDyxRfkFoQflUGJ6zo=$mRgDUkNpd0IwUEcTJQBmE0NHYwdDEhFzQ0VgMRcFJUIRYnaHBwNXRZJwk2ZUaURzdXkVYiUROERmI0hYYGFYCDiIJCeIU3N5EhRVcZFnSIRCJlkUFkY4YFMDcheYeTl4RYZEdpKGJYhxAIQJEYGYEA==:hashcat
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 28300 (Teamspeak 3 (channel hash))
Hash.Target......: $teamspeak$3$E0aV0IQ29EDyxRfkFoQflUGJ6zo=$mRgDUkNpd...GYEA==
Time.Started.....: Sun Dec 19 10:37:38 2021 (0 secs)
Time.Estimated...: Sun Dec 19 10:37:38 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?l?l?l?l?l?l?l [7]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  2708.5 MH/s (51.35ms) @ Accel:128 Loops:512 Thr:32 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 855638016/8031810176 (10.65%)
Rejected.........: 0/855638016 (0.00%)
Restore.Point....: 0/456976 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:2560-3072 Iteration:0-512
Candidate.Engine.: Device Generator
Candidates.#1....: hwoeran -> bctgezc
Hardware.Mon.#1..: Temp: 59c Fan:100% Util:100% Core:1830MHz Mem:6800MHz Bus:16

Started: Sun Dec 19 10:37:35 2021
Stopped: Sun Dec 19 10:37:39 2021
```
