### ISSUE TITLE
radeon sapphire nitro plus rx5700t is not detected on kali 

### ISSUE THREAD

**Issue by sylar-my** [hashcat/hashcat#2954]
I'm using AMD ryzen 7 3700x and radeon sapphire nitro plus rx5700xt on kali.

`Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux`

But My GPU is not detected but only working with CPU.I install amd gpu from amd.com for ubuntu and install with below command.

`./amdgpu-install --opencl=legacy --headless --no-dkms`

![hashcat](https://user-images.githubusercontent.com/85028023/131371658-52602095-4943-4d06-b2c9-9e0585e8b2c6.png)

my kernel gpu driver is may working I think. 

![kernel gpu](https://user-images.githubusercontent.com/85028023/131372507-d6546b2d-450d-417d-98d8-da5f5f6e905f.png)

Please I have been finding out solution like 2 months over. But I can't figure out. Thanks in advance!

**Comment by jsteube** [comment]
please ask on forum
