### ISSUE TITLE
Metamask - Reject candidates less than 8 characters

### ISSUE THREAD

**Issue by its5Q** [hashcat/hashcat#2955]
**Describe the feature**
Currently, when cracking metamask hashes, all candidates are used. When you are creating a metamask account, you can't actually set a password less than 8 characters long, so it would make sense to reject candidates less than 8 characters long.

**Hashcat version (please complete the following information):**
 - OS: Windows 10 
 - Version: 6.2.3

**Comment by jsteube** [comment]
I think is just adding the same function to the plugin like WPA 22000 is doing.
