### ISSUE TITLE
VirtualBox Kali Linux Illegal Hardware Instruction

### ISSUE THREAD

**Issue by visccyberacct** [hashcat/hashcat#2957]
I am fairly new to hashcat and I cannot seem to find a fix for this issue no matter how hard I look. I have been looking for about 2 weeks now. Everything I have found seems to show that hashcat cannot work in a VM environment. I apologize if this is the incorrect place to post this.

I have tried a number of different cli inputs and I get the same issue every time

Initializing backend runtime for device #1...zsh: illegal hardware instruction  hashcat -m 0 -a 0 -D 1 ***(hidden for privacy)*** /usr/share/wordlists/rockyou.txt --force

Initializing backend runtime for device #1...zsh: illegal hardware instruction  hashcat --force -m 0 ***(hidden for privacy)*** /usr/share/wordlists/rockyou.txt

**Comment by jsteube** [comment]
Do not use a VM for hashcat.
