### ISSUE TITLE
Support for Nvidia GeForce 9300M GS

### ISSUE THREAD

**Issue by felipesalomao** [hashcat/hashcat#297]
Hi, i only have macbook air I7 2014, but it have bad GPU (Intel  Graphics 5000) and Old PC with GeForce 9300M GS. But it is not supported  by olcHashcat, also tried old versions like 1.35 and 1.20, changed time and date of PC, but no luck.. It say that "Shader Model 1.0 - 1.3 Based GPU Detected".. What version you recomend use? 

Right now i only can run Hashcat on macbook (VMware Kali linux), its using CPU and is very slow (1600 WPA2 passwords/second).. I think that even old video card would be able to decode WPA2 Passsword fastest way that CPU running over VMWARE on MAC.. Buy new Graphic card, isnt option to me as this old PC is ALL in One.. 

Thank you guys !

**Comment by jsteube** [comment]
> It say that "Shader Model 1.0 - 1.3 Based GPU Detected".. What version you recomend use?

You can not change the Shader Model, because it's a version tag of your Hardware. NVidia dropped support for those old cards, therefore it's not an issue with oclHashcat.
