### ISSUE TITLE
7zip Token length exception for files >976kB

### ISSUE THREAD

**Issue by wherget** [hashcat/hashcat#2973]
**Describe the bug**
Hashcat seems to have trouble loading 7z hashes where the (smallest) file exceeds a certain size.
I've experimentally determined that size to be around the 977 kB mark, though if I understood 7z hashes correctly this may vary minimally with the compressibility of the data (the reproduction tries random data as to minimize that effect). You may need to increase the size slightly.
However, `7z2hashcat` only starts warning at the 16MB mark that the Hash couldn't be used, so I would expect files under this size to consistently work. A similar issue was reported and fixed earlier in #2154, however that should have long since landed in stable. Possibly a regression.

**To Reproduce**
Hashcat version (freshly built off `brew install hashcat --HEAD`):
```
$ hashcat --version
v6.2.4-46-g721e1ea54
```

Fresh clone of philsmd/7z2hashcat@2332f40bf

test.sh:
```
#!/bin/sh
rm test.7z test.hash word.txt
dd if=/dev/random of=sample.data bs=1k count=$1
7z a -pjustatest test.7z sample.data
perl 7z2hashcat.pl test.7z >test.hash
echo "justatest" >word.txt
hashcat -m 11600 test.hash word.txt
```
works:
```
sh test.sh 976
```
doesn't work:
``` 
$ sh test.sh 977
[...] 
Hashfile 'test.hash' on line 1 ($7z$2$...98aa3cd392913edf7c375$1000448$10): Token length exception
No hashes loaded.
```

**Expected behavior**
Hash loads in both cases (up to a file size of `PASSWORD_RECOVERY_TOOL_DATA_LIMIT` in `7z2hashcat.pl`, i.e. 16m as of writing).

**Hashcat version (please complete the following information):**
 - OS: macOS
 - Distribution: Mojave 10.14.6
 - Version: `v6.2.4-46-g721e1ea54`

**Comment by philsmd** [comment]
Please test with the fix below that allows longer field sizes for -m 11600 = 7-Zip:

https://github.com/hashcat/hashcat/commit/afa2330e6a4fa8837732d1cf6c07f9cd7c9c3d90

**Comment by wherget** [comment]
That looks to be working as expected. Thank you very much for the fast fix.
