### ISSUE TITLE
Benchmarks not running on Apple M1 as of v6.2.x

### ISSUE THREAD

**Issue by EricFromCanada** [hashcat/hashcat#2976]
Device: Apple Mac mini M1
OS: macOS 11.4-arm64
Version: 6.2.4

The last version that the Apple Silicon (M1) platform ran the benchmark on was 6.1.1:
```
% hashcat --benchmark -m 0 -D 1,2 -w 2 
hashcat (v6.1.1) starting in benchmark mode...

OpenCL API (OpenCL 1.2 (May  8 2021 03:14:28)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5397/5461 MB (1024 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1,2
* --workload-profile=2

Hashmode: 0 - MD5

Speed.#1.........:  1739.1 MH/s (7.35ms) @ Accel:256 Loops:1024 Thr:256 Vec:1

Started: Fri Sep 10 06:50:53 2021
Stopped: Fri Sep 10 06:51:06 2021
```

As of v6.2.0, it simply stops without output, even when built with DEBUG enabled:
```
% export CL_LOG_ERRORS=stdout
% hashcat --benchmark -m 0 -D 1,2 -w 2
hashcat (v6.2.4) starting in benchmark mode

[CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

Break on OpenCLErrorBreak to debug.
* Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (May  8 2021 03:14:28)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 2688/5461 MB (512 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1,2
* --workload-profile=2

-------------------
* Hash-Mode 0 (MD5)
-------------------

zsh: abort      hashcat --benchmark -m 0 -D 1,2 -w 2
```
Other hash types (e.g. 1500, 900, 50, 60) fail in the same manner.

For now, the Homebrew formula is [stuck](https://github.com/Homebrew/homebrew-core/pull/81093) at [v6.1.1](https://formulae.brew.sh/formula/hashcat).

```
% hashcat -I
hashcat (v6.2.4) starting in backend information mode

[CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

Break on OpenCLErrorBreak to debug.
OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (May  8 2021 03:14:28)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 2
    Vendor.........: Apple
    Name...........: Apple M1
    Version........: OpenCL 1.2 
    Processor(s)...: 8
    Clock..........: 1000
    Memory.Total...: 5461 MB (limited to 512 MB allocatable in one block)
    Memory.Free....: 2688 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2 1.0
```
```
% clinfo
Number of platforms                               1
  Platform Name                                   Apple
  Platform Vendor                                 Apple
  Platform Version                                OpenCL 1.2 (May  8 2021 03:14:28)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event

  Platform Name                                   Apple
Number of devices                                 1
  Device Name                                     Apple M1
  Device Vendor                                   Apple
  Device Vendor ID                                0x1027f00
  Device Version                                  OpenCL 1.2 
  Driver Version                                  1.2 1.0
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               8
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple (kernel)     32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (n/a)
[CL_INVALID_OPERATION] : OpenCL Error : Failed to retrieve device information! Invalid enumerated value!

Break on OpenCLErrorBreak to debug.
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (n/a)
  Address bits                                    64, Little-Endian
  Global memory size                              5726633984 (5.333GiB)
  Error Correction support                        No
  Max memory allocation                           1073741824 (1024MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             1 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4096 (4KiB)
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Apple
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [P0]
  clCreateContext(NULL, ...) [default]            Success [P0]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Apple
    Device Name                                   Apple M1
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Apple
    Device Name                                   Apple M1
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Apple
    Device Name                                   Apple M1
```

**Comment by EricFromCanada** [comment]
Bisecting shows the issue was introduced with https://github.com/hashcat/hashcat/commit/a0eae9050ce2431f612d7adc48c3b147c3878e92. Before this, benchmarks still run on the Apple M1. Can anyone suggest a workaround?

**Comment by matrix** [comment]
Hi @EricFromCanada 
unfortunately I don't have a mac with M1 to try on ... I am attaching a possible workaround based on the commit code you indicated.

Apply this patch to the master, and rebuild. 

[test_M1_01.patch.tar.gz](https://github.com/hashcat/hashcat/files/7470793/test_M1_01.patch.tar.gz)

Let me know if it works ;)
Thanks

**Comment by EricFromCanada** [comment]
It finished the benchmark, so that's some progress right there:
```
% brew test -v hashcat
==> Testing hashcat
==> /private/tmp/hashcat-test-20211103-25668-p8iv95/hashcat --benchmark -m 0 -D 1,2 -w 2 --force
hashcat (v6.2.4-122-gb768f9622+) starting in benchmark mode

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.

* Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Aug 30 2021 03:51:39)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5408/10922 MB (512 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --force
* --opencl-device-types=1,2
* --workload-profile=2

-------------------
* Hash-Mode 0 (MD5)
-------------------

* Device #1: ATTENTION! OpenCL kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Speed.#1.........:  1664.3 MH/s (7.70ms) @ Accel:256 Loops:1024 Thr:256 Vec:1

Started: Wed Nov  3 21:03:06 2021
Stopped: Wed Nov  3 21:03:27 2021
```
Note that the self-test failure message only appeared on the first run. I ran it with a few other hash modes (50, 60, 900, 1500) and they all came back clean. 

If the above patch can evolve into a pull request, I can use it to bring the formula [up to date](https://github.com/Homebrew/homebrew-core/pull/81093).

**Comment by matrix** [comment]
Great news. I try to work on it over the weekend.
Thanks

**Comment by matrix** [comment]
@EricFromCanada could you test this branch with your M1 ?

https://github.com/matrix/hashcat/tree/apple_silicon

**Comment by EricFromCanada** [comment]
Seems to fail in the same manner as the master branch.

**Comment by matrix** [comment]
updated now, please retry when you can. Thanks

**Comment by EricFromCanada** [comment]
That worked.

**Comment by matrix** [comment]
hi @EricFromCanada, could you test this patch on M1 ?

[hashcat_apple_silicon_workaround2.patch.zip](https://github.com/hashcat/hashcat/files/7548470/hashcat_apple_silicon_workaround2.patch.zip)

Thanks!

**Comment by EricFromCanada** [comment]
Still works 👍 
```
==> Testing hashcat
==> /private/tmp/hashcat-test-20211116-13845-rb1dxb/hashcat --benchmark -m 0 -D 1,2 -w 2
hashcat (v2.01-8015-gd2ccd96da+) starting in benchmark mode

* Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Aug 30 2021 03:51:39)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5408/10922 MB (512 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1,2
* --workload-profile=2

-------------------
* Hash-Mode 0 (MD5)
-------------------

Speed.#1.........:  1640.2 MH/s (1.93ms) @ Accel:512 Loops:1024 Thr:32 Vec:1

Started: Tue Nov 16 12:57:43 2021
Stopped: Tue Nov 16 12:57:59 2021
```

**Comment by matrix** [comment]
Hi @EricFromCanada, do you have the same problem reported in #3032 if you try to cracking hashes?

**Comment by EricFromCanada** [comment]
Have only run the benchmarks until now. Turns out it doesn't actually run on either ARM or Intel:
```
$ hashcat -m 0 -t 32 -a 7 example0.hash ?a?a?a?a example.dict -D1,2
hashcat (v6.2.5) starting

* Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Aug 30 2021 03:51:39)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5408/10922 MB (512 MB allocatable), 8MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Dictionary cache built:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 128416
* Runtime...: 0 secs

Hashes: 6494 digests; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Initializing backend runtime for device #1. Please be patient...UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Compilation failed: 

program_source:7:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^~~~~~~~~~~~~~

* Device #1: Kernel /opt/homebrew/Cellar/hashcat/6.2.5/share/hashcat/OpenCL/shared.cl build failed.

Started: Fri Dec  3 11:24:30 2021
Stopped: Fri Dec  3 11:24:31 2021
```

**Comment by matrix** [comment]
Never used brew to install hashcat, probably using _make_ after a _git clone_ will work (or rather, another error will be shown)

**Comment by EricFromCanada** [comment]
Oddly, that works; will have to debug that later. Am now seeing lots of `clEnqueueReadBuffer(): CL_INVALID_VALUE`.

**Comment by EricFromCanada** [comment]
Turns out that on first run it needs `OpenCL/` to be present in the current directory in order to compile kernels. Would be nice if it were possible to pass an option or set an env var pointing to that location instead.

**Comment by matrix** [comment]
hi @EricFromCanada, check my last comment here #3032

**Comment by BlastOffProductions** [comment]
So just checking, has this been fixed? I'm not fully understanding this issue. I am running hashcat on an M1 Mac installed with home-brew, and I'm getting this problem too, device 2 journal fail:` Device #2: Kernel /opt/homebrew/Cellar/hashcat/6.2.6_1/share/hashcat/OpenCL/shared.cl build failed.` `/Users/blank/.cache/hashcat/kernels/shared.833f28d0.kernel: No such file or directory`

Any help would be appreciated, thanks!

**Comment by EricFromCanada** [comment]
1. What's the command you're running?
2. What's the output of `brew doctor`?
3. What's the output of `brew config`?
4. hashcat v6.2.6 on M1 should automatically use the Metal API instead of OpenCL. This is its benchmark output on macOS Ventura: 
```
% hashcat --benchmark -m 0 -w 2
hashcat (v6.2.6) starting in benchmark mode

* Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

METAL API (Metal 306.7.5)
=========================
* Device #1: Apple M1, 5408/10922 MB, 8MCU

OpenCL API (OpenCL 1.2 (Oct 28 2023 11:19:36)) - Platform #1 [Apple]
====================================================================
* Device #2: Apple M1, skipped

Benchmark relevant options:
===========================
* --workload-profile=2

-------------------
* Hash-Mode 0 (MD5)
-------------------

Speed.#1.........:  1633.3 MH/s (9.08ms) @ Accel:512 Loops:128 Thr:32 Vec:1

Started: Wed Apr 17 09:47:58 2024
Stopped: Wed Apr 17 09:48:03 2024
```
As per the [manual](https://hashcat.net/wiki/doku.php?id=hashcat), specifying `-D 2` will have it only try GPU devices (not necessary since using the M-series CPU isn't supported), and `-d 1` or `-d 2` will have it specifically use device # 1 (Metal) or # 2 (OpenCL).

**Comment by BlastOffProductions** [comment]
> 1. What's the command you're running?
> 2. What's the output of `brew doctor`?
> 3. What's the output of `brew config`?
> 4. hashcat v6.2.6 on M1 should automatically use the Metal API instead of OpenCL. This is its benchmark output on macOS Ventura:
> 
> ```
> % hashcat --benchmark -m 0 -w 2
> hashcat (v6.2.6) starting in benchmark mode
> 
> * Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
>              You have been warned.
> 
> METAL API (Metal 306.7.5)
> =========================
> * Device #1: Apple M1, 5408/10922 MB, 8MCU
> 
> OpenCL API (OpenCL 1.2 (Oct 28 2023 11:19:36)) - Platform #1 [Apple]
> ====================================================================
> * Device #2: Apple M1, skipped
> 
> Benchmark relevant options:
> ===========================
> * --workload-profile=2
> 
> -------------------
> * Hash-Mode 0 (MD5)
> -------------------
> 
> Speed.#1.........:  1633.3 MH/s (9.08ms) @ Accel:512 Loops:128 Thr:32 Vec:1
> 
> Started: Wed Apr 17 09:47:58 2024
> Stopped: Wed Apr 17 09:48:03 2024
> ```
> 
> As per the [manual](https://hashcat.net/wiki/doku.php?id=hashcat), specifying `-D 2` will have it only try GPU devices (not necessary since using the M-series CPU isn't supported), and `-d 1` or `-d 2` will have it specifically use device # 1 (Metal) or # 2 (OpenCL).

Thanks for the quick replay. I’m new to this so it’s possible I’m just doing something wrong, but I went through tutorials and I can’t hash a hc22000 file, so I decided to run the test command for I think Homewbrew and the test for Hashcat and it came out with what I showed you. This is the command I ran: brew test -v hashcat

**Comment by BlastOffProductions** [comment]
> > 1. What's the command you're running?
> > 2. What's the output of `brew doctor`?
> > 3. What's the output of `brew config`?
> > 4. hashcat v6.2.6 on M1 should automatically use the Metal API instead of OpenCL. This is its benchmark output on macOS Ventura:
> > 
> > ```
> > % hashcat --benchmark -m 0 -w 2
> > hashcat (v6.2.6) starting in benchmark mode
> > 
> > * Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
> >              You have been warned.
> > 
> > METAL API (Metal 306.7.5)
> > =========================
> > * Device #1: Apple M1, 5408/10922 MB, 8MCU
> > 
> > OpenCL API (OpenCL 1.2 (Oct 28 2023 11:19:36)) - Platform #1 [Apple]
> > ====================================================================
> > * Device #2: Apple M1, skipped
> > 
> > Benchmark relevant options:
> > ===========================
> > * --workload-profile=2
> > 
> > -------------------
> > * Hash-Mode 0 (MD5)
> > -------------------
> > 
> > Speed.#1.........:  1633.3 MH/s (9.08ms) @ Accel:512 Loops:128 Thr:32 Vec:1
> > 
> > Started: Wed Apr 17 09:47:58 2024
> > Stopped: Wed Apr 17 09:48:03 2024
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As per the [manual](https://hashcat.net/wiki/doku.php?id=hashcat), specifying `-D 2` will have it only try GPU devices (not necessary since using the M-series CPU isn't supported), and `-d 1` or `-d 2` will have it specifically use device # 1 (Metal) or # 2 (OpenCL).
> 
> Thanks for the quick replay. I’m new to this so it’s possible I’m just doing something wrong, but I went through tutorials and I can’t hash a hc22000 file, so I decided to run the test command for I think Homewbrew and the test for Hashcat and it came out with what I showed you. This is the command I ran: brew test -v hashcat

Also, I assume I am doing something very wrong lol, because when I try to hash the .hc22000 file with this command: `hashcat -m 22000 /opt/homebrew/Cellar/hashcat/6.2.6_1/share/doc/hashcat/pcap.hc22000 /opt/homebrew/Cellar/hashcat/6.2.6_1/share/doc/hashcat/rockyou.txt.gz` I get this error: `/Users/zandy/.cache/hashcat/kernels/shared.833f28d0.kernel: No such file or directory

* Device #2: Kernel /opt/homebrew/Cellar/hashcat/6.2.6_1/share/hashcat/OpenCL/shared.cl build failed.` and I think this is connected to the issue. Thanks again for the quick reply I appreciate this!

**Comment by EricFromCanada** [comment]
It looks like benchmarks are running, so any further issue you're having isn't relevant to this issue. If adding `-D 2 -d 1` to your command has no effect, try asking for help in the [forums](https://hashcat.net/forum/index.php).

**Comment by BlastOffProductions** [comment]
> It looks like benchmarks are running, so any further issue you're having isn't relevant to this issue. If adding `-D 2 -d 1` to your command has no effect, try asking for help in the [forums](https://hashcat.net/forum/index.php).

Ok thanks, I’ll try adding that. I appreciate your help!
