### ISSUE TITLE
Hashcat6.2.4 bug

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2977]
Use 6.2.3 without this problem

Use6.2.4
hashcat.exe -m 13600 -a 3 zip.txt  -o outpass.txt  --increment --increment-min 1  --increment-max 7 ?a?a?a?a?a?a?a?a

OpenCL API (OpenCL 1.2 CUDA 11.0.228) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: GeForce RTX 2070, 6720/8192 MB (2048 MB allocatable), 36MCU
* Device #2: GeForce RTX 2070, 6720/8192 MB (2048 MB allocatable), 36MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

Started: Sat Sep 11 10:38:58 2021
Stopped: Sat Sep 11 10:39:07 2021

D:\hashcat-6.2.4>pause

**Comment by jsteube** [comment]
Please install CUDA SDK and post the result using the same command.

**Comment by ghost** [comment]
> Please install CUDA SDK and post the result using the same command.

Thanks  ......I will try when I have time
