### ISSUE TITLE
[Question] Recommended gpu videocards to use with oclHashcat

### ISSUE THREAD

**Issue by gituser** [hashcat/hashcat#298]
Hi.

I couldn't find a proper list of recommended video cards to use with hashcat.

The only recommendations I've found so far is to use Nvidia GTX 980 Ti, but from what I've seen lately in the code changes - CUDA support has been dropped? 

So what to get? AMD or Nvidia? What's better in terms of price/performance for oclHashcat?

Anyways, I think it would be nice for users to have in 1 place a list of recommended gpu video cards and list of gpus which are not recommended to use, which will be updated regularly.

Maybe use a wiki functionality on hashcat.net and put them there ? Or on github.com?

Thanks.

**Comment by jsteube** [comment]
Please use hashcat forum for this kind of questions: https://hashcat.net/forum/
