### ISSUE TITLE
Bug  Bug  Bug  Bug  Bug  Bug  

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2983]
Bug  Bug Bug Bug Bug Bug Bug Bug Bug Bug Bug 
 Is it never possible to solve it  ?  !!!!!

-a 6 mode
If the dic file is less than 10 words
Using this, in the case of multiple graphics cards, the maximum speed cannot be reached
I asked questions before
https://github.com/hashcat/hashcat/issues/2732
hashcat.exe -a 6 -m 2611  2611.hash  dic.txt  ?a?a?a?a?a?a

According to the method you  said
After using the pipe, it does not work at all, nothing happens, and the screen does not move
Don't believe you can try
 hashcat.exe --stdout -a 6 dic.txt  ?a?a?a?a?a?a  |  hashcat -m 2611  2611.hash 

Can any of you solve this problem

**Comment by jsteube** [comment]
GitHub issues are for bugs and feature requests only. For usage related questions, please ask on hashcat forum.
