### ISSUE TITLE
Hashcat     Integer overflow detected in keyspace of mask

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#2985]
windows 10   cpu: 16core      RAM: 8gb

V6.2.4 
Seems to encounter some errors

`D:\hashcat-6.2.4>hashcat --stdout -a 6 dic.txt  ?a?a?a?a?a   | hashcat  -m 22000  hc22000
hashcat (v6.2.4) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU
* Device #2: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.125) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #3: NVIDIA GeForce RTX 2070, skipped
* Device #4: NVIDIA GeForce RTX 2070, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #2. Please be patient...cuMemAlloc(): out of memory

cuMemAlloc(): out of memory

Started: Thu Sep 16 18:37:20 2021
Stopped: Thu Sep 16 18:37:22 2021

D:\hashcat-6.2.4>pause`

OK...
V6.2.3 
Integer overflow detected in keyspace of mask: ?a?a?a?a?a?a
If there are more than 4 ?a characters, an integer overflow will occur
How can i solve it ?

`D:\hashcat-6.2.3>hashcat --stdout -a 6 dic.txt  ?a?a?a?a?a?a   | hashcat  -m 22000  hc22000
hashcat (v6.2.3) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU
* Device #2: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.125) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #3: NVIDIA GeForce RTX 2070, skipped
* Device #4: NVIDIA GeForce RTX 2070, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1264 MB

Starting attack in stdin mode

Integer overflow detected in keyspace of mask: ?a?a?a?a?a?a

Session..........: hashcat
Status...........: Exhausted
Hash.Name........: WPA-PBKDF2-PMKID+EAPOL
Hash.Target......: hc22000
Time.Started.....: Thu Sep 16 18:42:36 2021 (1 sec)
Time.Estimated...: Thu Sep 16 18:42:37 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: Pipe
Speed.#1.........:        0 H/s (0.00ms) @ Accel:32 Loops:16 Thr:1024 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:16 Loops:32 Thr:1024 Vec:1
Speed.#*.........:        0 H/s
Recovered........: 0/2 (0.00%) Digests
Progress.........: 0
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-16
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-32
Candidate.Engine.: Device Generator
Candidates.#1....: [Copying]
Candidates.#2....: [Copying]
Hardware.Mon.#1..: Temp: 45c Fan:  0% Util: 13% Core:1937MHz Mem:6794MHz Bus:1
Hardware.Mon.#2..: Temp: 42c Fan:  0% Util: 19% Core:1896MHz Mem:6794MHz Bus:1
Started: Thu Sep 16 18:42:33 2021
Stopped: Thu Sep 16 18:42:38 2021

D:\hashcat-6.2.3>pause`

**Comment by philsmd** [comment]
This is related to this fix https://github.com/hashcat/hashcat/commit/91b663b14d4443d0cbdefbf30057a2fcf334115f and the following issue: #2482

The modifier (in this case the mask) can't have more than 2^32 combinations.

I'm not sure if we can/should do anything here or just can't improve anything here

cc: @jsteube

**Comment by ghost** [comment]
> This is related to this fix [91b663b](https://github.com/hashcat/hashcat/commit/91b663b14d4443d0cbdefbf30057a2fcf334115f) and the following issue: #2482
> 
> The modifier (in this case the mask) can't have more than 2^32 combinations.
> 
> I'm not sure if we can/should do anything here or just can't improve anything here
> 
> cc: @jsteube


Thanks.
v6.2.4
implement  
hashcat --stdout -a 6 dic  ?a?a?a?a?a | hashcat  -m 22000  hc22000
Prompt that there is not enough memory,
I don't know how much memory it needs at least

`D:\hashcat-6.2.4>hashcat --stdout -a 6 dic ?a?a?a?a?a   | hashcat  -m 22000  hc22000
hashcat (v6.2.4) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU
* Device #2: NVIDIA GeForce RTX 2070, 6744/8192 MB, 36MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.125) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #3: NVIDIA GeForce RTX 2070, skipped
* Device #4: NVIDIA GeForce RTX 2070, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 2 digests; 2 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #2. Please be patient...cuMemAlloc(): out of memory

cuMemAlloc(): out of memory

Started: Tue Sep 28 10:40:22 2021
Stopped: Tue Sep 28 10:40:25 2021

D:\hashcat-6.2.4>pause`
