### ISSUE TITLE
Hashcat hogging RAM when using slow candidates (-m 26600)

### ISSUE THREAD

**Issue by its5Q** [hashcat/hashcat#2990]
**Describe the bug**
When using slow candidates with -m 26600 on the example hash, if slow candidates is enabled hashcat consumes 12960 megabytes of RAM (I think it's equal to the VRAM amount, but sometimes it is more than 20 GB of RAM!). When not using slow candidates, the usage is about 2700 megabytes.

**To Reproduce**
`hashcat.exe -a 0 -m 26600 example26600.hash rockyou.txt` - 2700 megabytes of RAM
`hashcat.exe -a 0 -m 26600 -S example26600.hash rockyou.txt` - 12900 megabytes of RAM

**Expected behavior**
I expect the RAM usage to be about the same for both scenarios

**Hardware/Compute device (please complete the following information):**
- RTX 3060 12GB
- Nvidia Display Driver version 471.96
- CUDA 11.4

**Hashcat version (please complete the following information):**
 - OS: Windows 10 x64
 - Version: v6.2.4-71-gdb8de70ac

**Diagnostic output compute devices:**

CUDA Info:
==========

CUDA.Version.: 11.4

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce RTX 3060
  Processor(s)...: 28
  Clock..........: 1837
  Memory.Total...: 12288 MB
  Memory.Free....: 10983 MB
  PCI.Addr.BDFe..: 0000:07:00.0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.4.125

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce RTX 3060
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1837
    Memory.Total...: 12288 MB (limited to 3072 MB allocatable in one block)
    Memory.Free....: 8896 MB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 471.96
    PCI.Addr.BDF...: 07:00.0

**Comment by Chick3nman** [comment]
>Expected behavior
>I expect the RAM usage to be about the same for both scenarios

What gives you this expectation? -S moves candidate preparation, including rule processing, completely to the host(CPU) and will definitely consume more host resources doing so. Should it be using this much RAM regardless? That's hard to say and warrants a bit of investigation, but this is not really unexpected behavior.

**Comment by its5Q** [comment]
> > Expected behavior
> > I expect the RAM usage to be about the same for both scenarios
> 
> What gives you this expectation? -S moves candidate preparation, including rule processing, completely to the host(CPU) and will definitely consume more host resources doing so. Should it be using this much RAM regardless? That's hard to say and warrants a bit of investigation, but this is not really unexpected behavior.

That being said, I don't think it should consume 12 gigabytes of RAM when processing 100 passwords with 30 thousand rules. Besides, the RAM usage is 12 GB even if using wordlists without rules, for example, I tried running hashcat with a wordlist of just  125 candidates with -S enabled, and it used up all 12 GB, so it's not like it depends on the workload, it just wants to consume all my RAM.

```
Host memory required for this attack: 12973 MB

Dictionary cache hit:
* Filename..: dictionary.txt
* Passwords.: 125
* Bytes.....: 1795
* Keyspace..: 125
```

**Comment by its5Q** [comment]
Also I just found out that 6.2.3 doesn't have such problem, consuming just 2.4 GB of RAM

**Comment by jsteube** [comment]
260 * 28 * 1024 * 1024 * 1024 * 3 = 23.450.521.436.160 is required, but hashcat managed to reduce it to 12GB. If you want it to consume less, try -w 1 or -w 2 (which is basically what 6.2.3 does, just by default). So it works as expected.

**Comment by its5Q** [comment]
> 260 * 28 * 1024 * 1024 * 1024 * 3 = 23.450.521.436.160 is required, but hashcat managed to reduce it to 12GB. If you want it to consume less, try -w 1 or -w 2 (which is basically what 6.2.3 does, just by default). So it works as expected.

Changing -w did nothing to reduce RAM usage. Still 12 GB.
