### ISSUE TITLE
Why is 6 bytes mask overflow with simple hint dict?

### ISSUE THREAD

**Issue by bymanaire** [hashcat/hashcat#2992]
Case1
```
hashcat -m 1000 -a 6 <hash> -o result.txt dict\hint.txt -1 '?l?u?d!_-./@' ?1?1?1?1?1?1
```
```
Integer overflow detected in keyspace of mask: ?1?1?1?1?1?1
```

---
Case2
```
hashcat -m 1000 -a 3 <hash>  -o result.txt -1 '?l?u?d!_-./@' ?1?1?1?1?1?1?1?1?1?1
```
```
Time.Estimated...: Fri Oct 19 05:15:58 2057 (36 years, 26 days)
```

---

hint.txt only includes hint words with max length 4 bytes

Known password length is 10 bytes
In case there is a 4-byte hint, only 6-byte passwords need to be traversed. It should be very simple.
But the keyspace limit makes it impossible.

So how can I solve this problem?

**Comment by philsmd** [comment]
how many lines are there within those files ?

`hashcat` checks for the overall keyspace and number of combinations, if they can't be represented by a 64 bit number, we have a problem. It's also infeasible to combine too many base words with too large masks, so it's a valid error (if the base word list is really large).

Try with a smaller input (smaller dict etc) and report back

**Comment by bymanaire** [comment]
> how many lines are there within those files ?
> 
> `hashcat` checks for the overall keyspace and number of combinations, if they can't be represented by a 64 bit number, we have a problem. It's also infeasible to combine too many base words with too large masks, so it's a valid error (if the base word list is really large).
> 
> Try with a smaller input (smaller dict etc) and report back

only 3 lines in hint.txt
each line 4 bytes

**Comment by philsmd** [comment]
thanks for the answer..

this issue, #2985, has the same underlying problem with combinations > 2^32 for the masks itself.

I will close this issue for now because it seems we should discuss if we need/can to do anything within the other github issue (which is indeed related).

also see #2482 and https://github.com/hashcat/hashcat/commit/91b663b14d4443d0cbdefbf30057a2fcf334115f
