### ISSUE TITLE
Hashcat 6.1.1 seen under windows as a virus

### ISSUE THREAD

**Issue by kerszl** [hashcat/hashcat#2995]
**Describe the issue**
I downloaded Hashcat from https://hashcat.net/files/hashcat-6.1.1.7z
and Windows see it as a virus.

**Expected behavior**
run hashcat.exe, not delete

**Hardware/Compute device (please complete the following information):**
OpenCL Platform ID #1
  Vendor..: Advanced Micro Devices, Inc.
  Name....: AMD Accelerated Parallel Processing
  Version.: OpenCL 2.1 AMD-APP (3075.13)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: Advanced Micro Devices, Inc.
    Name...........: Radeon (TM) RX 470 Graphics
    Version........: OpenCL 2.0 AMD-APP (3075.13)
    Processor(s)...: 32
    Clock..........: 1250
    Memory.Total...: 4096 MB (limited to 3264 MB allocatable in one block)
    Memory.Free....: 4032 MB
    OpenCL.Version.: OpenCL C 2.0
    Driver.Version.: 3075.13
    PCI.Addr.BDF...: 01:00.0

**Hashcat version (please complete the following information):**
 - Program: hashcat-6.1.1
 - OS: Winodows 10 (21H1)

**Additional context**
```
PS C:\temp\hashcat-6.1.1> .\hashcat.exe
Program 'hashcat.exe' failed to run: Operacja nie zakończyła się pomyślnie, ponieważ plik zawiera wirusa lub potencjalnie niechcian
e oprogramowanieAt line:1 char:1
+ .\hashcat.exe
+ ~~~~~~~~~~~~~.
At line:1 char:1
+ .\hashcat.exe
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\temp\hashcat-6.1.1>
```

**Comment by oam7575** [comment]
What Antivirus software are you using?

A current 2021-09-25 scan from Virustotal reports as clean; though notably MS and some other scans timed out
https://www.virustotal.com/gui/file/444e1e671147056e96d265c77d8d44e8fef908bd008ce60fd4c3853a1c9ad3af?nocache=1

Hybridanalysis reports a low percentage malware hit
https://www.hybrid-analysis.com/sample/7a9050c813673e0d5d39c51b8eb26cd8bcd1683f0b1f3e1b79627248f339aada

However when checking that report
https://www.virustotal.com/gui/file/7a9050c813673e0d5d39c51b8eb26cd8bcd1683f0b1f3e1b79627248f339aada/detection/f-7a9050c813673e0d5d39c51b8eb26cd8bcd1683f0b1f3e1b79627248f339aada-1630580797

 it suggests that Crowdstrike and Microsoft are reporting it as a malicious file from date 2021-09-02

Rescanning the hashcat 6.1.1 .exe file on virustotal produces the same malicious file result
https://www.virustotal.com/gui/file/7a9050c813673e0d5d39c51b8eb26cd8bcd1683f0b1f3e1b79627248f339aada?nocache=1

Scanning hashcat 6.2.4 on both Virustotal and Hybridanalysis gives a clean scan result; but a malicious file result on the falcon sandbox.

https://www.hybrid-analysis.com/sample/2635a6b7de5ed6d0bd4407afba3eb88416adc627334f05353e9efaa056c5df7c
https://www.virustotal.com/gui/file/2635a6b7de5ed6d0bd4407afba3eb88416adc627334f05353e9efaa056c5df7c/detection

https://www.hybrid-analysis.com/sample/2635a6b7de5ed6d0bd4407afba3eb88416adc627334f05353e9efaa056c5df7c/6143acad1513c677590d0a0d

Appears as though MS, Crowdstrike and FalconSandbox possibly have false positives.

At this point I am not seeing anything too far out of the ordinary ( false positive ).
However I am not a malware expert; and specifically I am not _your_ malware expert.

**Comment by kerszl** [comment]
> 
> 
> What Antivirus software are you using?
> Microsoft defender
"Wersja klienta ochrony przed złośliwym oprogramowaniem: 4.18.2108.7"
Thanx 4 checking
