### ISSUE TITLE
RFE: opensource OpenCL support

### ISSUE THREAD

**Issue by igor-raits** [hashcat/hashcat#3]
Now we have support OpenCL for:
- CPU -> POCL
- Intel GPU -> Beignet
- AMD GPU -> mesa

Would be great to get opensource OpenCL support.

**Comment by jsteube** [comment]
Sorry, I don't understand what you mean, could you please rephrase?

**Comment by ignatenkobrain** [comment]
Currently oclHashcat supports only AMD OpenCL SDK and CUDA, but we have OpenCL which is not part of those. I want to get support of it.

**Comment by jsteube** [comment]
I see, that is indeed interessting especially for the CPU part, but definitly a long-term suggestion.

**Comment by ignatenkobrain** [comment]
I am not interested in CPU part, I'm mostly interested in beignet part, because it works on Intel GPUs which is mostly everywhere.

**Comment by epixoip** [comment]
Intel GPUs are not likely to be much if at all faster than CPU, which is one of the reasons we never bothered to support them.

**Comment by ignatenkobrain** [comment]
It is faster (at least with beignet). https://01.org/beignet

**Comment by epixoip** [comment]
That link doesn't really say anything of value.

Let's look at it this way: current top-of-the-line Intel GPUs have up to 384 cores which run at up to 1100 Mhz, and lack instructions that help reduce instruction count for many hash functions (nothing similar to bitselect, bitalign, LOP3.LUT, etc.) So basically these will be almost identical in speed very low-end pre-Maxwell Nvidia GPUs.

For example, the Iris Pro 6200 would be about as fast as a GT 640, which yields a staggering 450 MH/s on raw MD5. And by "staggering," I mean that's 23 times slower than a GTX 970. And that's for their top of the line GPU, if you have something like an HD4200 then it would be more like 50 times slower than a GTX 970. 

So this is why we've never cared about adding Intel GPU support. Even their fastest GPUs are about the same speed as high-end CPUs.

**Comment by magnumripper** [comment]
IMHO, regardless of Intel GPUs' current state there's really no reason for Hashcat not to "work" on just any OpenCL device. Instead you could just state that only AMD is actively "supported" and/or that the OpenCL code is optimized for AMD.

So I think we should look into wrapping AMD-specific stuff (just guessing there is some) in #ifdef blocks and provide some alternative "generic" alternative. Once it builds and runs on nvidia (as an alternative to CUDA) it should also run fine on Iris or crappy AMD APU's - as well as on some really cool FPGA board with OpenCL abstraction layer...

I haven't looked much at the code base yet so I'm mostly assuming things here.

**Comment by jsteube** [comment]
You're right. Now that we're not forced any longer to ship binary kernels we _could_ allow other platforms than AMD to run the OpenCL kernels. Sure, some of the optimizations wouldn't work. However I'm absolutely positive about this, especially as it would give us an easy start into support CPU as well. I'll look into this in some time, but would also would be happy on any help on it

**Comment by magnumripper** [comment]
In fact it might save you a lot of time and work if you (eventually) ditch all CUDA stuff and go all-in for OpenCL. Unless there are some clear cases where CUDA can be significantly faster?

**Comment by jsteube** [comment]
Yeah I'd like to do so, but the most important reason for using CUDA is that only with CUDA it's possible to cross-compile GPU code using nvcc's -arch option. So we'd have a strange situation in which we'd use OpenCL on Nvidia if the users chooses to use the JIT but for binary distribution we still need to use CUDA. That sounds very complicated. BTw, there was such an option back in earlier versions of NVidia OpenCL runtime, but it got dropped without any reason.

And yes there's also the reason with the performance:

a) While this is just speculation, it seems NV isn't really happy with OpenCL. It's obvious that they try to push CUDA instead of OpenCL, for business reasons.
b) I remember with driver change somewhere between 150.x and 200.x the speeds for the OpenCL began to drop by 15% without any reason or any change within the ptx. It's also speculation but I think they tried to artificially slow down OpenCL to make CUDA more interessting.

**Comment by jsteube** [comment]
It seems we have alot of good reasons to fully switch to OpenCL. I've tried that yesterday but it's more complicated than one would think in the first place. We need to get rid of all of our C++ code (which is mostly only overloaded functions) because NVidias OpenCL runtime does not support C++. But there's no way around, since so many other tasks depend on this change.

**Comment by magnumripper** [comment]
In JTR we use function-like macros for "overloading". Too bad the `typeof` keyword is not mandatory - that would have been perfect. Most drivers support it though (including AMD, nvidia and Apple) but Intel does not (well some of their drivers do).

**Comment by jsteube** [comment]
For those interessted in development: https://github.com/hashcat/oclHashcat/tree/GetRidOfCUDA

**Comment by shellster** [comment]
While I'm all for OpenCL, there is potentially at least one reason not to.  I currently bought an NVIDIA Jetson TK1 with the hope of eventually getting oclHashCat running on it.  There is currently (and likely never will be) any OpenCL support.  We are stuck with CUDA.  There are other issues with running on this platform (ARM and no NVML support), but only OpenCL will add yet another hurdle.  This may or may not be enough of a reason to not go full OpenCL.  I predict that we will see more of this specialty boards in the near future, and they offer some really nice power to energy ratios for cracking.

**Comment by magnumripper** [comment]
@shellster is that thing usable in real life? That is a sincere question, I'm not bashing. What's the performance?

There's no need to actually ditch the working CUDA code. Sure, the tree would be much easier to maintain without CUDA but you could keep the kernels for a while and just separate the builds: Stop calling them "nvidia" and "amd" and instead call them what they really are: "cuda" and "opencl". That is what we do in JtR although in that case, the CUDA stuff is mostly laughable.

**Comment by shellster** [comment]
@magnumripper That's a good question.  It's hard to know without being able to test it.  This guy is getting some pretty decent WPA cracking speeds with the board: https://devtalk.nvidia.com/default/topic/785084/jetson-for-pyrit-cpyrit-cuda-stats/

The killer feature is that the board only uses about 5W of power, so the potential power comes from clustering them.

**Comment by epixoip** [comment]
525 H/s @ 5W. Meanwhile a GTX 970 gets 180000 H/s @ 135W.  That's 105 H/W vs 1333 H/W. So that's both poor performance AND poor perf/Watt.

**Comment by shellster** [comment]
@epixoip: I believe you are misreading the post.  The first benchmark at the top is after adjusting the clock speed: 6203.2 PMKs/s

**Comment by epixoip** [comment]
Sorry, all I saw was "#1: 'CUDA-Device #1 'GK20A'': 525.1 PMKs/s (RTT 2.8)". But even 6203 H/s falls short in the perf/W category, and well short in perf/$ as well. You'd need 29 of these boards to match the speed of one GTX 970 for a cost of $5600 vs $320.

Historically we've had zero interest in underpowered / poor-performing hardware. I suppose that's because in our view, Hashcat is for serious professionals, and serious professionals have real hardware. I know JtR aims to be compatible with pretty much anything and everything, but I personally do not see our focus shifting away from serious use cases.

**Comment by ignatenkobrain** [comment]
I am very happy, that you are working on opencl support, but I have question. What is JtR?

**Comment by epixoip** [comment]
JtR is the acronym we frequently use to refer to John the Ripper.

**Comment by jsteube** [comment]
@shellster The whole Jetson TK1 discussion makes no sense since they dropped the support for the board with CUDA 7.0: https://devtalk.nvidia.com/default/topic/805540/no-cuda-7-0-support-for-jetson-tk1-board/

@magnumripper I'll drop CUDA completely not just because it's easier to maintain afterwards but also because it makes the host code easier to read. If I remove the code from the host, there's no sense in keeping the NV folder. If anyone really wants it simply checkout an older version. PS: The CUDA branch uses already an OpenCL/ folder

**Comment by jsteube** [comment]
So far the GetRidOfCUDA branch works, all unit-tests passed. Now we have to focus on the performance, and there's a lot to do! I justed started a sheet for comparison:

https://docs.google.com/spreadsheets/d/1B1S_t1Z0KsqByH3pNkYUM-RCFMu860nlfSsYEqOoqco/edit#gid=0

Don't get shocked by those early numbers, I'm confident we'll stabilize them after optimizing each single kernel

**Comment by jsteube** [comment]
FYI, first version working with pocl now

**Comment by ignatenkobrain** [comment]
Very cool, how I can compile it without having amd sdk, cuda and etc. ?

**Comment by jsteube** [comment]
You can not, however the depencies were reduced to only a few which you can automatically install using tools/deps.sh -- see building.md

**Comment by pjaaskel** [comment]
FYI, latest pocl versions support HSA, thus e.g. AMD Kaveri GPU and in the future hopefully more. Thus, not for commercial CPU-only devices anymore, but any HSA-supported devices should in principle work.

We'll try to take a look at   https://github.com/pocl/pocl/issues/290 as soon as possible.

**Comment by jsteube** [comment]
Just wanted to update the status on CPU here. It seems pocl works fine, but LLVM is buggy (even the latest LLVM 3.7).

The native AMD OpenCL CPU driver works really really good, all Unit-Tests pass. Speeds are almost the same as with pocl.

The native Intel OpenCL CPU driver also seem to work very good, but not all Unit-Tests pass (I'll have to look into that). But then the speeds are really good, much faster than with pocl.

**Comment by jsteube** [comment]
I think we're finished with this issue. All OpenCL platforms from all the differen vendors that I've tested, on all OS, seem to work fine.

**Comment by neheb** [comment]
mesa is still broken(clover).

**Comment by epixoip** [comment]
There's already another ticket open for Mesa (#71). And those failures appear to be Mesa's fault, not oclHashcat's. Remember that the state of Gallium is not at all mature and their OpenCL platform is not production-ready. Still a whole lot of red/orange on this chart, even for GCN https://dri.freedesktop.org/wiki/GalliumCompute/

**Comment by neheb** [comment]
point taken. just meant that not all platforms work.

**Comment by epixoip** [comment]
Sure, I think what atom meant was all the work necessary to make oclHashcat work with any OpenCL library has already been done, and thus the ticket can be closed.

**Comment by igor-raits** [comment]
Unfortunately it does not work with Beignet (Intel implementation)

```
[brain@x1carbon oclHashcat]$ ./example400.sh 
oclHashcat v2.01 (gc4e6ffc) starting...

Device #1: Intel(R) HD Graphics IvyBridge M GT2, 1024/2048 MB allocatable, 1000Mhz, 16MCU

Device #1: Kernel /home/brain/oclHashcat/kernels/m00400.25e54501.kernel (47756 bytes)
Device #1: Kernel /home/brain/oclHashcat/kernels/amp_a0.25e54501.kernel not found in cache! Building may take a while...
ASSERTION FAILED: insn2.header.opcode == GEN_OPCODE_NOP
  at file /builddir/build/BUILD/Beignet-1.1.1-Source/backend/src/backend/gen_encoder.cpp, function virtual void gbe::GenEncoder::patchJMPI(uint32_t, int32_t, int32_t), line 1043
./example400.sh: line 1: 21297 Broken pipe             cat example.dict
     21298 Trace/breakpoint trap   (core dumped) | ./oclHashcat -m 400 example400.hash
```

**Comment by epixoip** [comment]
Only with -m 400 or other algorithms as well?

**Comment by igor-raits** [comment]
Other algorithms as well.

**Comment by magnumripper** [comment]
I believe there are still plenty of bugs in Beignet. We've had issues in JtR about Beignet but as far as I can remember, all of them were their bugs, not ours. I expect these to be the same - it will eventually work better. BTW it got a LOT better just during last year.

Having said that, odd platforms like Beignet are good for finding "edge cases" or in our/your code that can be improved, or code that are actually "undefined behavior" but happen to work fine on many platforms.

**Comment by AnonymousRonin** [comment]
There's plenty of better options out there that don't require such ridiculous parameters.  In the OS's you would use hashcat most, you''ll never get it to run on your gpu.  Just remove it from your distro, it hogs a bunch of resources without even functioning anyways.
