### ISSUE TITLE
crash when using --benchmark together with some invalid params (a hash file)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#30]
Even if I agree that specifying a file with hashes or a dictionary doesn't make much sense in the benchmark mode, it somehow happened to me that I wrongfully accidentally had some unneeded parameters in the command line and the result was that it crashed.

We should prevent a crash with a command like this;
./hashcat-cli64.bin -b hash.txt dict.txt

(in my case, I was blind and didn't see that the -b was still there)

Currently, this ends up in a segfault since some variables are not correctly set (because of the mix of hash file vs hard coded mask in benchmarks).

Thanks

**Comment by jsteube** [comment]
Fixed! Thanks!
