### ISSUE TITLE
pocl segfaults with latest git

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#300]
it has for a while actually. the actual error is: error: <invalid loc>: unknown target CPU 'generic'

**Comment by jsteube** [comment]
pocl works fine for me, both the version from ubuntu's repo as well as the self compiled one

**Comment by neheb** [comment]
the package from fedora's repo and my self compiled one from arch show the same problem. interestingly enough, the device name now shows "pthread-" + name of device. well w/e. this isn't really a priority.

**Comment by jsteube** [comment]
Do I need a special version to reproduce, because if I can not reproduce this, I can not fix it. Since this is somehow related to CPU I think this is not related to the mesa thing discussed in the PR, right?

**Comment by neheb** [comment]
It is not. Maybe a pocl bug instead.

**Comment by jsteube** [comment]
I'm having problems to build latest pocl github master on ubuntu 16.04. Too bad it doesn't have it's owne ubuntu package anyway.

**Comment by neheb** [comment]
looks like the problem is some incompatibility with clover...

https://github.com/pocl/pocl/issues/217

**Comment by neheb** [comment]
closing since this is an upstream issue. just tried on an ubuntu install and it works fine.
