### ISSUE TITLE
Exclude combinations 

### ISSUE THREAD

**Issue by sliceaton** [hashcat/hashcat#3000]
I think it would be useful if we could exclude determinated combinations - example, in mask attack, I'm trying to crack some hash and I've already tried 10 digits passwords, but now I'm gonna try 10 hexadecimal characters passwords. The problem is, all the 10 digits passwords will be tested again. I know Brain can help in this kind of problem, but it requires a lot of memory. It would be nice if we could, for example, test all hexadecimal passwords except ones that uses exacly 10 digits. Is it possible?

**Comment by philsmd** [comment]
hey,

it's not really possible to tell hashcat to just make a [complement](https://en.wikipedia.org/wiki/Complement_(set_theory)) or "set difference" of a mask, but with [hashcat mask files](https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files) (.hcmask) (also see: [FAQ hashcat mask files](https://hashcat.net/faq#what_is_a_hashcat_mask_file)) you can just **skip** all masks that you already tried (this only works best and with a simple trick if the 2 masks are related and one is a subset of another mask).

if you already tried all numbers (masks with a certain length and digits only), you could just make sure that the new masks you run do not have digits in all positions, e.g. guarantee that there is at least one position with **no** numbers/digits.
```
abcdef,?h?h?h?h?h?h?h?h?h?1
abcdef,?h?h?h?h?h?h?h?h?1?h
abcdef,?h?h?h?h?h?h?h?1?h?h
abcdef,?h?h?h?h?h?h?1?h?h?h
abcdef,?h?h?h?h?h?1?h?h?h?h
abcdef,?h?h?h?h?1?h?h?h?h?h
abcdef,?h?h?h?1?h?h?h?h?h?h
abcdef,?h?h?1?h?h?h?h?h?h?h
abcdef,?h?1?h?h?h?h?h?h?h?h
abcdef,?1?h?h?h?h?h?h?h?h?h
```

this new hcmask file (see link above if you don't know what it is and how to use it) defines 10 new masks, each with a position guaranteed to not contain a digit (this is basically the complement/difference of your 2 masks, "all lowercase hex" - "only digits").

so the solution is to just think logically and use the features/tools that hashcat provides that help you to run such tasks.

Please also try to ask user questions like this in the [hashcat forum](https://hashcat.net/forum/) the next time (github issues are better suited for problems/bugs or other technical suggestions/recommendations)

**Comment by sliceaton** [comment]
Hi Phil, really thanks for the answer, nice and creative solution for that problem! 
I thought It would be nice to ask it here at github since It could be an idea for a new feature, but I'll be more careful in the future
Thanks!!
