### ISSUE TITLE
Metamask Token Length exception error

### ISSUE THREAD

**Issue by oxijoined** [hashcat/hashcat#3001]
metamask token length exception no hashes loaded error
I used the latest version of HASHCAT
[hashes.txt](https://github.com/hashcat/hashcat/files/7252741/hashes.txt)

**Comment by realSnoopy** [comment]
no error with latest beta / git
https://hashcat.net/beta/
seems to be fixed with this commit 2 months ago
https://github.com/hashcat/hashcat/commit/694f0cd7c8bf9d88b6e04401c1e8e4249cbc3c2b

use beta version or build from git
