### ISSUE TITLE
proposed: disambiguate empty strings as $HEX[]

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3002]
**Describe the feature**

Use $HEX[] (an empty $HEX sequence) to store and display empty founds.

**Current behavior**

Potfiles, `--show`, and other outputs currently represent empty strings as ... nothing:
```
d41d8cd98f00b204e9800998ecf8427e:
da39a3ee5e6b4b0d3255bfef95601890afd80709:
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:
31d6cfe0d16ae931b73c59d7e0c089c0:
458e0XXYe3hOY:
74be16979710d4c4e7c6647856088456:
$2a$05$MRK0MBC1KhizMB.1LhSzKu8R6qrARLMEtS6EXHdD.Oa7yavcEu09C:
```

This can be ambiguous in some contexts - when a found only contains space characters, when creating a merged list of founds and lefts, when visually inspecting hash:found pairs, etc.

```
$ hashcat -m 0 --potfile-path=./invisible.potfile --show invisible.hashes
# empty string
d41d8cd98f00b204e9800998ecf8427e:
# one space
7215ee9c7d9dc229d2921a40e899ec5f:
# two spaces
23b58def11b45727d3351702515f86af:
```

**Target behavior**

```
d41d8cd98f00b204e9800998ecf8427e:$HEX[]
da39a3ee5e6b4b0d3255bfef95601890afd80709:$HEX[]
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:$HEX[]
31d6cfe0d16ae931b73c59d7e0c089c0:$HEX[]
458e0XXYe3hOY:$HEX[]
74be16979710d4c4e7c6647856088456:$HEX[]
$2a$05$MRK0MBC1KhizMB.1LhSzKu8R6qrARLMEtS6EXHdD.Oa7yavcEu09C:$HEX[]
```

This makes the empty string explicit, recognizable, and unambiguous.

**Places this would have to be updated:**

* potfile writes
* `--show`
* test.pl
* code that encodes/decodes $HEX sequences
* ?

This could also be an argument to always HEX-escape sequences that _only_ contain spaces as well.

**Comment by jsteube** [comment]
I think that creates more problems that it solves. We should only use $HEX[] for technical reasons. The spaces are visual if the user is using the correct editor. This may be a inconvenient, but inconvenience is not a technical reason.

**Comment by roycewilliams** [comment]
Your call, of course. :) But IMO there are a variety of visual inspection and display use cases that have nothing to do with editing. I think most hashcat users probably don't spend most of their time viewing files in a way that displays spaces as anything other than an absence of characters on the screen. And those are exactly the users that are likely to be confused by an empty hash. Of course, once they Google it, they'll know the answer and be educated. I was just hoping to reduce the period of confusion. :D 

A devil's advocate question: what is the technical reason why tabs are escaped with $HEX[] ?
