### ISSUE TITLE
--quiet not working as expected

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#3004]
**Describe the bug**
`--quiet` does not suppress all warnings and not sure what kind of output it's supposed to suppress...
`--quiet` will suppress the warning coming from` --force`
but it will not suppress other warnings, example: `Unsupported AMD HIP runtime version '4.2' detected! Falling back to OpenCL...`

**To Reproduce**
`hashcat.bin -b` and `hashcat.bin -b --quiet` both yield the same warning (and errors if exist too)

**Expected behavior**
`--quiet` to suppress all warnings

**Question**
what exactly `--quiet`  is supposed to suppress?
(INFO + ADVICE + WARNING level messages?)

**Hashcat version:**
v6.2.4-83-g07e58631a

**Comment by Chick3nman** [comment]
I believe `--quiet` is simply designed to suppress things the user may know and wish not to see. Some warnings/errors are still shown as they are not the result of user interaction and are brought to the attention of the user for remediation or to indicate a problem. A warning/error related to the runtime, for example, is a problem the user typically needs to remedy, and is not the result of the users selection, such as the warnings from something like `--force` might be. I think it's up for debate on which messages in particular should or should not be shown with `--quiet` present, i'm not sure there is a defined level(INFO/Warning/Etc.) where it cuts off right now.

**Comment by jsteube** [comment]
The expected behavior should be that all message which are not warnings should go to stdout and are suppressed using --quiet. Warnings should go to stdout, but are not suppressed using --quiet. Errors should go to stderr and are not suppressed.

**Comment by jsteube** [comment]
Any update?

**Comment by s77rt** [comment]
sorry, just forgot to close the issue
all clear, thanks for your time
