### ISSUE TITLE
Incomplete kernel documentation for plugin development guide.

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#3005]
The hashcat plugin development guide doesn't fully explain the different required fast + optimized kernel functions.

The documentation mentions that they follow the naming pattern `mXXXXX_[m|s][04|08|16]` where `m` is for multiple hash targets and `s` is for single hash, but it says nothing about what the `04`, `08`, or `16` mean.  Later on in the "slow" kernel section it does mention this:

> As already mentioned, most slow hash modes do not use password length specific kernels like in a fast hash kernel. There is no "s04", "s08" kernels or anything like this.

From digging through the code and some of the kernels, I've pieced together that the [04|08|16] are the password length limits in u32 units (i.e. "04" is 4 * u32 = 16 bytes, "08" is 32 bytes, "16" is 64 bytes).

However, I discovered a few things that give me more questions than answers:

- The 08 and 16 kernels are only ever implemented for attack mode 3 (brute force and hybrid modes).
  - Why?  Is it because that's one of the few attack modes where the password length is known in advance?
- Even though no hash yet _implements_ them for other attack modes, are the 08 or 16 kernels still _executed_?
  - If so, what happens when the kernels are empty stubs?  Are the passwords silently rejected?

I'd be more than happy to submit a PR to update the documentation but I want to make sure I have my facts straight first.  Thanks for your help!

**Comment by jsteube** [comment]
Feel free to send in the PR. The -a0 and -a1 do not make use of this optimization, because zero based optimized really only have an impact for very fast algorithms. The overhead caused by -a0 rule engine is too large, even just the single switch case for the -a1 combination...

**Comment by llamasoft** [comment]
Thank you for the response!

So if I'm understanding you correctly: it's all about the balance of candidate generation time versus hash execution time.  

For "fast" hash algorithms, the overall kernel execution time largely consists of two factors: the candidate generation time and the hash execution time.  The candidate generation time is determined by the attack mode and the hash execution time is affected by the candidate length limit.

In mask-based attack modes, the candidate generation is so fast that that the overall execution time is determined almost entirely by the hash execution itself.  Given that the hash time is affected by the candidate length limit, adjusting the limit would directly impact the overall kernel performance.  For this reason, mask-based attacks implement all three of the [04|08|16] candidate length kernels.  (I imagine this is partly why only attack mode 3 is used for benchmarks.  It more accurately measures the hash execution itself and not the candidate generation.)

In rule-based and combination-based attack modes, the candidate generation overhead makes up a large portion of the overall kernel execution time.  The candidate length limit, and as a result the hash execution time, only affects the overall execution time when the limit is set aggressively low (e.g. "04" kernels limiting the candidate to 16 bytes).  The intermediate candidate length "08" and "16" kernels wouldn't perform significantly better than the "pure" kernel, so they're simply aren't used.

Please let me know if my understanding is correct and I'll start work on a PR!

**Comment by jsteube** [comment]
It's a very good description. As an addition for -a0 we can also mention that the rule engine itself is limited to a 32 byte buffer in optimized mode. That's also why there's two different rule engine cores, the other "pure" one is for the pure kernel and that one has to support up to length 256. But this requires more registers for temporary storage which also lowers the overall execution time, which is the reason why we are not reusing this one for optimized kernels.
