### ISSUE TITLE
Hashcat error: Not a native Intel OpenCL runtime for AMD Radeon GPU...

### ISSUE THREAD

**Issue by ARSuperTech** [hashcat/hashcat#3009]
Hashcat shows error:

Device #1: Not a native Intel OpenCL runtime. Expect massive speed loss. 

I can run it using --force but believe it is running very slow.

I have an Intel i7 CPU 8850H and AMD Radeon Pro WX 4150 for GPU. I've since went onto ROCm documentation to install repos and drivers, but issue still persists. I noticed that command rocminfo returns my GPU details but clinfo does not. The command rocm-smi also returns one or more commands failed showing 0 for GPU. The driver for GPU is AMDGPU. Hashcat version is 4.0.1. The OS is Ubuntu 18.04.1 with kernel 5.4.0-87. See specifics below.
--------------------------------------------------------------------------
ROCMINFO:

                      ROCk module is loaded
                      =====================    
                      HSA System Attributes    
                      =====================    
                      Runtime Version:         1.1
                      System Timestamp Freq.:  1000.000000MHz
                      Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
                      Machine Model:           LARGE                              
                      System Endianness:       LITTLE                             
                      
                      ==========               
                      HSA Agents               
                      ==========               
                      *******                  
                      Agent 1                  
                      *******                  
                        Name:                    Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                        Uuid:                    CPU-XX                             
                        Marketing Name:          Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                        Vendor Name:             CPU                                
                        Feature:                 None specified                     
                        Profile:                 FULL_PROFILE                       
                        Float Round Mode:        NEAR                               
                        Max Queue Number:        0(0x0)                             
                        Queue Min Size:          0(0x0)                             
                        Queue Max Size:          0(0x0)                             
                        Queue Type:              MULTI                              
                        Node:                    0                                  
                        Device Type:             CPU                                
                        Cache Info:              
                          L1:                      32768(0x8000) KB                   
                        Chip ID:                 0(0x0)                             
                        Cacheline Size:          64(0x40)                           
                        Max Clock Freq. (MHz):   4300                               
                        BDFID:                   0                                  
                        Internal Node ID:        0                                  
                        Compute Unit:            12                                 
                        SIMDs per CU:            0                                  
                        Shader Engines:          0                                  
                        Shader Arrs. per Eng.:   0                                  
                        WatchPts on Addr. Ranges:1                                  
                        Features:                None
                        Pool Info:               
                          Pool 1                   
                            Segment:                 GLOBAL; FLAGS: FINE GRAINED        
                            Size:                    16224356(0xf79064) KB              
                            Allocatable:             TRUE                               
                            Alloc Granule:           4KB                                
                            Alloc Alignment:         4KB                                
                            Accessible by all:       TRUE                               
                          Pool 2                   
                            Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
                            Size:                    16224356(0xf79064) KB              
                            Allocatable:             TRUE                               
                            Alloc Granule:           4KB                                
                            Alloc Alignment:         4KB                                
                            Accessible by all:       TRUE                               
                          Pool 3                   
                            Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
                            Size:                    16224356(0xf79064) KB              
                            Allocatable:             TRUE                               
                            Alloc Granule:           4KB                                
                            Alloc Alignment:         4KB                                
                            Accessible by all:       TRUE                               
                        ISA Info:                
                      *******                  
                      Agent 2                  
                      *******                  
                        Name:                    gfx803                             
                        Uuid:                    GPU-XX                             
                        Marketing Name:          Baffin [Radeon Pro WX 4130/4150]   
                        Vendor Name:             AMD                                
                        Feature:                 KERNEL_DISPATCH                    
                        Profile:                 BASE_PROFILE                       
                        Float Round Mode:        NEAR                               
                        Max Queue Number:        128(0x80)                          
                        Queue Min Size:          4096(0x1000)                       
                        Queue Max Size:          131072(0x20000)                    
                        Queue Type:              MULTI                              
                        Node:                    1                                  
                        Device Type:             GPU                                
                        Cache Info:              
                          L1:                      16(0x10) KB                        
                        Chip ID:                 26600(0x67e8)                      
                        Cacheline Size:          64(0x40)                           
                        Max Clock Freq. (MHz):   1053                               
                        BDFID:                   256                                
                        Internal Node ID:        1                                  
                        Compute Unit:            14                                 
                        SIMDs per CU:            4                                  
                        Shader Engines:          2                                  
                        Shader Arrs. per Eng.:   1                                  
                        WatchPts on Addr. Ranges:4                                  
                        Features:                KERNEL_DISPATCH 
                        Fast F16 Operation:      FALSE                              
                        Wavefront Size:          64(0x40)                           
                        Workgroup Max Size:      1024(0x400)                        
                        Workgroup Max Size per Dimension:
                          x                        1024(0x400)                        
                          y                        1024(0x400)                        
                          z                        1024(0x400)                        
                        Max Waves Per CU:        40(0x28)                           
                        Max Work-item Per CU:    2560(0xa00)                        
                        Grid Max Size:           4294967295(0xffffffff)             
                        Grid Max Size per Dimension:
                          x                        4294967295(0xffffffff)             
                          y                        4294967295(0xffffffff)             
                          z                        4294967295(0xffffffff)             
                        Max fbarriers/Workgrp:   32                                 
                        Pool Info:               
                          Pool 1                   
                            Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
                            Size:                    4194304(0x400000) KB               
                            Allocatable:             TRUE                               
                            Alloc Granule:           4KB                                
                            Alloc Alignment:         4KB                                
                            Accessible by all:       FALSE                              
                          Pool 2                   
                            Segment:                 GROUP                              
                            Size:                    64(0x40) KB                        
                            Allocatable:             FALSE                              
                            Alloc Granule:           0KB                                
                            Alloc Alignment:         0KB                                
                            Accessible by all:       FALSE                              
                        ISA Info:                
                          ISA 1                    
                            Name:                    amdgcn-amd-amdhsa--gfx803          
                            Machine Models:          HSA_MACHINE_MODEL_LARGE            
                            Profiles:                HSA_PROFILE_BASE                   
                            Default Rounding Mode:   NEAR                               
                            Default Rounding Mode:   NEAR                               
                            Fast f16:                TRUE                               
                            Workgroup Max Size:      1024(0x400)                        
                            Workgroup Max Size per Dimension:
                              x                        1024(0x400)                        
                              y                        1024(0x400)                        
                              z                        1024(0x400)                        
                            Grid Max Size:           4294967295(0xffffffff)             
                            Grid Max Size per Dimension:
                              x                        4294967295(0xffffffff)             
                              y                        4294967295(0xffffffff)             
                              z                        4294967295(0xffffffff)             
                            FBarrier Max Size:       32                                 
                      *** Done ***             
------------------------------------------------------------------------------------------
CLINFO:

                            Number of platforms                               1
                              Platform Name                                   Portable Computing Language
                              Platform Vendor                                 The pocl project
                              Platform Version                                OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
                              Platform Profile                                FULL_PROFILE
                              Platform Extensions                             cl_khr_icd
                              Platform Extensions function suffix             POCL
                            
                              Platform Name                                   Portable Computing Language
                            Number of devices                                 1
                              Device Name                                     pthread-Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                              Device Vendor                                   GenuineIntel
                              Device Vendor ID                                0x8086
                              Device Version                                  OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
                              Driver Version                                  1.1
                              Device OpenCL C Version                         OpenCL C 1.2 pocl
                              Device Type                                     CPU
                              Device Profile                                  FULL_PROFILE
                              Device Available                                Yes
                              Compiler Available                              Yes
                              Linker Available                                Yes
                              Max compute units                               12
                              Max clock frequency                             4300MHz
                              Device Partition                                (core)
                                Max number of sub-devices                     12
                                Supported partition types                     equally, by counts
                              Max work item dimensions                        3
                              Max work item sizes                             4096x4096x4096
                              Max work group size                             4096
                              Preferred work group size multiple              8
                              Preferred / native vector sizes                 
                                char                                                16 / 16      
                                short                                               16 / 16      
                                int                                                  8 / 8       
                                long                                                 4 / 4       
                                half                                                 0 / 0        (n/a)
                                float                                                8 / 8       
                                double                                               4 / 4        (cl_khr_fp64)
                              Half-precision Floating-point support           (n/a)
                              Single-precision Floating-point support         (core)
                                Denormals                                     Yes
                                Infinity and NANs                             Yes
                                Round to nearest                              Yes
                                Round to zero                                 Yes
                                Round to infinity                             Yes
                                IEEE754-2008 fused multiply-add               Yes
                                Support is emulated in software               No
                                Correctly-rounded divide and sqrt operations  Yes
                              Double-precision Floating-point support         (cl_khr_fp64)
                                Denormals                                     Yes
                                Infinity and NANs                             Yes
                                Round to nearest                              Yes
                                Round to zero                                 Yes
                                Round to infinity                             Yes
                                IEEE754-2008 fused multiply-add               Yes
                                Support is emulated in software               No
                              Address bits                                    64, Little-Endian
                              Global memory size                              14466256896 (13.47GiB)
                              Error Correction support                        No
                              Max memory allocation                           4294967296 (4GiB)
                              Unified memory for Host and Device              Yes
                              Minimum alignment for any data type             128 bytes
                              Alignment of base address                       1024 bits (128 bytes)
                              Global Memory cache type                        Read/Write
                              Global Memory cache size                        9437184 (9MiB)
                              Global Memory cache line size                   64 bytes
                              Image support                                   Yes
                                Max number of samplers per kernel             16
                                Max size for 1D images from buffer            268435456 pixels
                                Max 1D or 2D image array size                 2048 images
                                Max 2D image size                             16384x16384 pixels
                                Max 3D image size                             2048x2048x2048 pixels
                                Max number of read image args                 128
                                Max number of write image args                128
                              Local memory type                               Global
                              Local memory size                               8388608 (8MiB)
                              Max number of constant args                     8
                              Max constant buffer size                        8388608 (8MiB)
                              Max size of kernel argument                     1024
                              Queue properties                                
                                Out-of-order execution                        No
                                Profiling                                     Yes
                              Prefer user sync for interop                    Yes
                              Profiling timer resolution                      1ns
                              Execution capabilities                          
                                Run OpenCL kernels                            Yes
                                Run native kernels                            Yes
                                SPIR versions                                 1.2
                              printf() buffer size                            1048576 (1024KiB)
                              Built-in kernels                                
                              Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_spir cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64
                            
                            NULL platform behavior
                              clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
                              clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
                              clCreateContext(NULL, ...) [default]            Success [POCL]
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
                                Platform Name                                 Portable Computing Language
                                Device Name                                   pthread-Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
                                Platform Name                                 Portable Computing Language
                                Device Name                                   pthread-Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
                              clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
                                Platform Name                                 Portable Computing Language
                                Device Name                                   pthread-Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
                            
                            ICD loader properties
                              ICD loader Name                                 OpenCL ICD Loader
                              ICD loader Vendor                               OCL Icd free software
                              ICD loader Version                              2.2.11
                              ICD loader Profile                              OpenCL 2.1

-------------------------------------------------------------------------------------------------------
ROCM-SMI:

======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan  Perf  PwrCap  VRAM%  GPU%  
0    39.0c  7.013W  342Mhz  300Mhz  0%   auto  35.0W    10%   6%    
================================================================================
WARNING:  		 One or more commands failed
============================= End of ROCm SMI Log ==============================

-----------------------------------------------------------------------
HASHCAT -i

hashcat (v4.0.1) starting...

No devices found/left.

-----------------------------------------------------------------------
LSPCI 

00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 07)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device a368 (rev 10)
00:15.1 Serial bus controller [0c80]: Intel Corporation Device a369 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:1b.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port 21 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Device a338 (rev f0)
00:1c.5 PCI bridge: Intel Corporation Device a33d (rev f0)
00:1c.6 PCI bridge: Intel Corporation Device a33e (rev f0)
00:1f.0 ISA bridge: Intel Corporation Device a30e (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (7) I219-LM (rev 10)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon Pro WX 4130/4150]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device aae0
02:00.0 Non-Volatile memory controller: Micron Technology Inc Device 5410 (rev 01)
6e:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device 5260 (rev 01)
6f:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
---------------------------------------------------------------------------

Any help would be appreciated. Thanks in advance.

**Comment by jsteube** [comment]
GitHub issues are only for bugs and feature requests. Please ask on hashcat forums.
