### ISSUE TITLE
Problems with buffer lenght after commit AES Crypt Plugin: Replaced naive with true UTF8 to UTF16 conversion

### ISSUE THREAD

**Issue by realSnoopy** [hashcat/hashcat#3012]
posting bugreport for another forum member

https://hashcat.net/forum/thread-10404.html

affecting commit regarding philsmd
https://github.com/hashcat/hashcat/commit/0a60805

PROBLEM:
  u32 w[80] = { 0 };
...
...
...
  for (int i = 127; i >= 0; i--) // create some space for the first digest without extra buffer
  {
    w[8 + i] = w[i];
  }

The w size is 80, but for w[8 + i] = w[i] the i start from 127, this means i is out of the boundary.

disclaimer
not my finding, credits to hellohihi
https://hashcat.net/forum/user-15121.html

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/139ace28a90472af915dc862bb3b05fc9054a5a8

Thanks for reporing!
