### ISSUE TITLE
Attempting to build with termux "main issue"

### ISSUE THREAD

**Issue by flypsmashin1** [hashcat/hashcat#3015]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**

**To Reproduce**
Please provide us with all files required to reproduce the bug locally on our development systems. For instance: hash files, wordlists, rule files, ...

**Expected behavior**

**Hardware/Compute device (please complete the following information):**
- Compute device name: [e.g. RTX2080Ti]
- OpenCL/CUDA driver name: [e.g. NVIDIA DRIVER]
- OpenCL/CUDA driver version: [e.g. 465.21]
- OpenCL/CUDA driver source: [e.g. runtime installer/.exe installer]

**Hashcat version (please complete the following information):**
 - OS: [e.g. Linux]
 - Distribution: [e.g. Ubuntu 18.04]
 - Version: [e.g. 6.2.0]

**Diagnostic output compute devices:**

```
For NV: Post nvidia-smi output. This tool also exist on Windows
For AMD ROCm: Post rocm-smi and rocminfo output
```

```
Post clinfo output
```

```
Post hashcat -I output
```

```
On Linux: post lspci output
```

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).

> I am using termux proot-distro Ubuntu to give me root authority on a Samsung non-rooted phone I keep trying to make the install file using command ($ make install) an each time I get back this:
 Enjoy your fresh **hashcat** binaries ;)
root@localhost:~/hashcat# make install
install -m 755 -d                                                    /usr/local/share
gcc    -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -DWITH_HWMON src/main.c obj/combined.NATIVE.a -o hashcat                    -s -lstdc++ -lpthread -ldl -lrt -lm -DCOMPTIME=1635351968 -DVERSION_TAG=\"v6.2.4-107-gd9680a8f5\" -DINSTALL_FOLDER=\"/usr/local/bin\" -DSHARED_FOLDER=\"/usr/local/share/hashcat\" -DDOCUMENT_FOLDER=\"/usr/local/share/doc/hashcat\"
/usr/bin/ld: obj/combined.NATIVE.a(hashes.NATIVE.o): in function `save_hash':
hashes.c:(.text+0x664): undefined reference to `__errno'
/usr/bin/ld: hashes.c:(.text+0x698): undefined reference to `__errno'
/usr/bin/ld: hashes.c:(.text+0x710): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(hashes.NATIVE.o): in function `hashes_init_filename':
hashes.c:(.text+0x12a4): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(hashes.NATIVE.o): in function `hashes_init_stage1':
hashes.c:(.text+0x18f8): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(hashes.NATIVE.o):hashes.c:(.text+0x196c): more undefined references to `__errno' follow
/usr/bin/ld: obj/combined.NATIVE.a(shared.NATIVE.o): in function `select_read_timeout':
shared.c:(.text+0x11a0): undefined reference to `__FD_SET_chk'
/usr/bin/ld: obj/combined.NATIVE.a(shared.NATIVE.o): in function `select_write_timeout':
shared.c:(.text+0x1204): undefined reference to `__FD_SET_chk'
/usr/bin/ld: obj/combined.NATIVE.a(shared.NATIVE.o): in function `select_read_timeout_console':
shared.c:(.text+0x1280): undefined reference to `__FD_SET_chk'
/usr/bin/ld: obj/combined.NATIVE.a(straight.NATIVE.o): in function `straight_ctx_update_loop':
straight.c:(.text+0x3a8): undefined reference to `__errno'
/usr/bin/ld: straight.c:(.text+0x3f0): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(straight.NATIVE.o): in function `straight_ctx_init':
straight.c:(.text+0x868): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(terminal.NATIVE.o): in function `thread_keypress':
terminal.c:(.text+0x4f4): undefined reference to `__FD_SET_chk'
/usr/bin/ld: obj/combined.NATIVE.a(terminal.NATIVE.o): in function `tty_getchar':
terminal.c:(.text+0x8d8): undefined reference to `__FD_SET_chk'
/usr/bin/ld: obj/combined.NATIVE.a(tuningdb.NATIVE.o): in function `tuning_db_init':
tuningdb.c:(.text+0x184): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(user_options.NATIVE.o): in function `user_options_check_files':
user_options.c:(.text+0x21a8): undefined reference to `__errno'
/usr/bin/ld: user_options.c:(.text+0x2900): undefined reference to `__errno'
/usr/bin/ld: user_options.c:(.text+0x2924): undefined reference to `__errno'
/usr/bin/ld: user_options.c:(.text+0x2994): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(user_options.NATIVE.o):user_options.c:(.text+0x29c4): more undefined references to `__errno' follow
/usr/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `get_next_word':
wordlist.c:(.text+0x580): undefined reference to `libiconv'
/usr/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `count_words':
wordlist.c:(.text+0xcc8): undefined reference to `libiconv'
/usr/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `wl_data_init':
wordlist.c:(.text+0xfb4): undefined reference to `libiconv_open'
/usr/bin/ld: obj/combined.NATIVE.a(wordlist.NATIVE.o): in function `wl_data_destroy':
wordlist.c:(.text+0x1010): undefined reference to `libiconv_close'
/usr/bin/ld: obj/combined.NATIVE.a(brain.NATIVE.o): in function `brain_auth_challenge':
brain.c:(.text+0xba4): undefined reference to `__errno'
/usr/bin/ld: brain.c:(.text+0xbe8): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(brain.NATIVE.o): in function `brain_connect':
brain.c:(.text+0xd30): undefined reference to `__errno'
/usr/bin/ld: brain.c:(.text+0xd78): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(brain.NATIVE.o): in function `brain_client_connect':
brain.c:(.text+0x13c4): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(brain.NATIVE.o):brain.c:(.text+0x13f8): more undefined references to `__errno' follow
/usr/bin/ld: obj/combined.NATIVE.a(backend.NATIVE.o): in function `run_cracker':
backend.c:(.text+0xa6bc): undefined reference to `libiconv_open'
/usr/bin/ld: backend.c:(.text+0xafe0): undefined reference to `libiconv'
/usr/bin/ld: backend.c:(.text+0xb4b0): undefined reference to `libiconv'
/usr/bin/ld: backend.c:(.text+0xb7b8): undefined reference to `libiconv_close'
/usr/bin/ld: obj/combined.NATIVE.a(backend.NATIVE.o): in function `backend_session_begin':
backend.c:(.text+0x12f3c): undefined reference to `__errno'
/usr/bin/ld: backend.c:(.text+0x1c330): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(backend.NATIVE.o): in function `read_kernel_binary':
backend.c:(.text+0x21604): undefined reference to `__errno'
/usr/bin/ld: backend.c:(.text+0x21690): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(backend.NATIVE.o): in function `write_kernel_binary':
backend.c:(.text+0x21754): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(combinator.NATIVE.o):combinator.c:(.text+0x448): more undefined references to `__errno' follow
/usr/bin/ld: obj/combined.NATIVE.a(dispatch.NATIVE.o): in function `thread_calc_stdin':
dispatch.c:(.text+0x164): undefined reference to `libiconv_open'
/usr/bin/ld: dispatch.c:(.text+0x32c): undefined reference to `libiconv'
/usr/bin/ld: dispatch.c:(.text+0x5bc): undefined reference to `libiconv_close'
/usr/bin/ld: obj/combined.NATIVE.a(dispatch.NATIVE.o): in function `thread_calc':
dispatch.c:(.text+0x24ec): undefined reference to `__errno'
/usr/bin/ld: dispatch.c:(.text+0x2514): undefined reference to `__errno'
/usr/bin/ld: dispatch.c:(.text+0x2528): undefined reference to `__errno'
/usr/bin/ld: dispatch.c:(.text+0x25cc): undefined reference to `__errno'
/usr/bin/ld: dispatch.c:(.text+0x2cac): undefined reference to `__errno'
/usr/bin/ld: obj/combined.NATIVE.a(dispatch.NATIVE.o):dispatch.c:(.text+0x2e3c): more undefined references to `__errno' follow
collect2: error: ld returned 1 exit status
make: *** [src/Makefile:610: hashcat] Error 1
root@localhost:~/hashcat#
Any idea why or what have I done wrong?

**Comment by Chick3nman** [comment]
Please reopen with readable formatting or resubmit on a clean issue template. 

To briefly speak to the issue highlighted in the post, compiling and running hashcat on a Samsung Phone is not officially supported right now and should be considered an unsupported configuration and extremely experimental, While we can assist where possible, this is a topic for the forums or discord server, not really an issue with hashcat itself unless you wish to make some sort of feature request.
