### ISSUE TITLE
There are a few grammatical errors in the readme file

### ISSUE THREAD

**Issue by YSSVirus** [hashcat/hashcat#3020]
There are a few grammatical errors in the readme.md file and I have loved and used hashcat for years and wanted to contribute
I have forked this and added in the corrections for the readme
[GithubLink](https://github.com/YSSVirus/hashcat/blob/patch-3/docs/readme.txt)

Thank you for the years of an awesome tool!

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/pull/3018
