### ISSUE TITLE
Program tries to find module module_00001.dll, no such file.

### ISSUE THREAD

**Issue by mastermach50** [hashcat/hashcat#3024]
**Input:**
```
E:\Hashcat\hashcat-6.2.4>hashcat -m 1 -a 3 -O -w 3 -o output.txt input.txt wordlists\english-words\words_alpha.txt wordlists\english-words\words_alpha.txt
```
---
**Output:**
```
hashcat (v6.2.4) starting

Cannot load module ./modules/module_00001.dll

Started: Sun Nov 07 18:57:49 2021
Stopped: Sun Nov 07 18:57:49 2021
```
---
I could not find such a module in the repository or my copy of the program (latest release at time of posting).

> System:
AMD ryzen 3 3200G
No dedicated GPU
Windows 10 Pro (Version: 20H2)

**Comment by Chick3nman** [comment]
You have selected mode 1, which does not exist. This is not a problem in hashcat, this is a problem with your command.

**Comment by mastermach50** [comment]
Ahhh.... 
I actually wanted to set attack mode to 1.
My mistake.
