### ISSUE TITLE
Exodus secure-container (seco-v0-scrypt-aes)

### ISSUE THREAD

**Issue by its5Q** [hashcat/hashcat#3025]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**
Those secure containers are used in the Exodus cryptocurrency wallet to store seedphrases protected by a passphrase.

**Describe alternatives you've considered**
There are a few algorithms in hashcat that already support pretty similar hashing algorithms, and I haven't found any alternatives besides a JS script that is painfully slow.

**Provide an example hash/database/file and a known correct password**
An archive containing 4 secure containers that are created by the wallet, the password is "hashcat" without quotes.
https://siasky.net/HAAZ8JHrl10MiP4l8ZIsA1TIaAnfv2jYge5XjLMX0UX1qQ

**Explain how the cryptographic schema is implemented**
It seems that they use AES-256-GCM, as stated in their README

**Describe the known limitations of the algorithm**
The minimum password length is 4 characters, and Exodus checks for some popular passwords like 12345678

**Where do you typically find the algorithm**
It's used in the Exodus cryptocurrency wallet.

**Additional context**
There is a repository that contains technical information such as header formats and encryption algorithms, and the algorithm itself written in JS.
https://github.com/ExodusMovement/secure-container

**Comment by jsteube** [comment]
Hey there, support was added with commit https://github.com/hashcat/hashcat/commit/bf865d8bff2db0d7cc617c3fd5d8e73bd1b4a8b3

If you dont want to wait for the next release to test it you can also build from source or use the beta from hashcat.net/beta

The seed.seco from your wallet cracks fine. Thanks for the details.

**Comment by urbanurba** [comment]
>

**Comment by urbanurba** [comment]
> >

It hasn't been working for a year now, they changed something

**Comment by urbanurba** [comment]
Hi, can anyone explain how checking for the correct password works?

**Comment by urbanurba** [comment]
Hi, can anyone explain how checking for the correct password works?

**Comment by OlMi1** [comment]
one question: The python file returns `EXODUS:16384:8:1:/8A+6BZDTQlIkt+C1E1HysgsPyZKJ0SYsqCwx13lvBQ=:pXiPLKTLn5aHCAei:36FwWAFmQ64smtWWhrY8+GszilB8DBL4Qw5kFFVNxWw=:gb7/qvy3rX67fIPIlmfplg==` which leads to a token length exception, where should I split the hash?
