### ISSUE TITLE
Show "net new" cracks for each attack

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3028]
**Describe the feature**

Today, at the end of each attack, a summary of current status is displayed. This inclused a "Recovered" count and percentage, based on the _total_ number of recovered hashes for this target, regardless of whether they were part of the current attack, previous attacks in this run, found in the potfile, etc.

To help understand the effectiveness of that specific attack, it would be informative to display "net new" cracks for each attack.

**Current behavior**

`Recovered........: 26341/2000000 (1.32%) Digests`

**Desired behavior**

Just an example - could be done other ways:

`Recovered........: 26341/2000000 (1.32%) Digests, 17488 (0.87%) this attack`

This could only be shown in the final status, before the next attack in the series is run. Or it might be better to simply show it all the time. If hashcat is only performing a single attack in this run, the total would also be shown.

The phrasing above is deliberately compact, to fit as many characters within 80 columns as feasible if the total numbers are large.

**Hashcat version (please complete the following information):**

 - OS: all
 - Distribution: any
 - Version: future

**Other considerations**

To do this, the number of recovered hashes at the _beginning_ of the attack would need to be stored, and then compared at the end of the attack.

Actually, to make things simpler (and maybe even more useful), the "this attack" value could be shown all the time, instead of having to figure out when to show it. I will update the title accordingly.

**Comment by Chick3nman** [comment]
We show how many are found in the potfile at the start, this seems easy to add. Would this be per guess base/per dictionary? Or do you mean per session(max-potfile=net)?

**Comment by roycewilliams** [comment]
It would be cool to have both, but I suspect there isn't room for that unless we thought it was worth adding an entire new status line. So between the two, it would probably be (slightly) more useful for it to be per run/session.
