### ISSUE TITLE
/var/root/.local/share/hashcat/sessions/usage.pid: No such file or directory  /var/root/.local/share/hashcat: No such file or directory

### ISSUE THREAD

**Issue by juskek** [hashcat/hashcat#3035]
**Describe the bug**
No such file or directory in share folder after installing hashcat on MacOS:
/Users/XXX/.local/share/hashcat/sessions/usage.pid: No such file or directory

/Users/XXX/.local/share/hashcat: No such file or directory

**To Reproduce**
brew install hashcat
hashcat --help

**Fix**
mkdir /Users/XXX/.local/share
mkdir /Users/XXX/.local/share/hashcat
mkdir /Users/XXX/.local/share/hashcat/sessions
Replace XXX with your user name

**Comment by KJae2** [comment]
@juskek, the Fix doesn't work

karanjames@Macbook hashcat %  mkdir /Users/karanjames/.local/share
mkdir: /Users/karanjames/.local: No such file or directory
karanjames@Macbook hashcat %  mkdir /Users/karanjames/.local/share/hashcat
mkdir: /Users/karanjames/.local/share: No such file or directory
karanjames@Macbook hashcat %  mkdir /Users/karanjames/.local/share/hashcat/sessions
mkdir: /Users/karanjames/.local/share/hashcat: No such file or directory

**Comment by juskek** [comment]
Where is your hash at installed?

**Comment by KJae2** [comment]
Hi Justin, I got it resolved

 

 

Where is your hash at installed?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
