### ISSUE TITLE
v6.2.5 bug

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3040]
Allow me to report a bug
An error occurred on WIN7

`D:\hashcat-6.2.5>hashcat  -m 22000 -a0 WPA.hc22000  dic
hashcat (v6.2.5) starting

hipFuncGetAttribute is missing from HIP shared library.

hiprtcAddNameExpression is missing from HIPRTC shared library.

OpenCL API (OpenCL 2.1 AMD-APP (2906.8)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #1: AMD Radeon RX 580 2048SP, 3968/4096 MB (3264 MB allocatable), 32MCU

./hashcat.dictstat2: Invalid header, ignoring content

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Initializing backend runtime for device #1. Please be patient...
`

Next
The program pops up a small window that stops working and crashes
Exit after crash

**Comment by jsteube** [comment]
It crashes inside AMD library, not a hashcat bug.
