### ISSUE TITLE
NVDIA gpu SKIPPED

### ISSUE THREAD

**Issue by 0xm3t4lcup** [hashcat/hashcat#3043]
Hi I'm using windows 11 and i have installed CUDA 11.5 Hash cat is skipping GPU and cracking using AMD  How should i fix it. Im attaching the screenshot

Blow is error:

hashcat (v6.2.5) starting

hipFuncGetAttribute is missing from HIP shared library.

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
ADL2_Overdrive_Caps(): -8

ADL2_Overdrive_Caps(): -8

ADL2_Overdrive_Caps(): -8

nvmlDeviceGetFanSpeed(): Not Supported

ADL_Overdrive5_FanSpeed_Get(): -100

ADL_Overdrive5_Temperature_Get(): -100

CUDA API (CUDA 11.5)
====================
* Device #1: NVIDIA GeForce GTX 1650 Ti, 3323/4095 MB, 16MCU

OpenCL API (OpenCL 3.0 CUDA 11.5.56) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce GTX 1650 Ti, skipped

OpenCL API (OpenCL 2.1 AMD-APP (3004.4)) - Platform #2 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #3: AMD Radeon(TM) Graphics, 1536/3147 MB (1120 MB allocatable), 7MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 31 digests; 31 unique digests, 31 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
![1](https://user-images.githubusercontent.com/63362647/143623294-3f001d88-7d4e-4e48-919d-c50f9b611697.png)
![2](https://user-images.githubusercontent.com/63362647/143623299-69995d91-6198-4052-8f70-0e78e5b936a1.png)

**Comment by Chick3nman** [comment]
Not an issue, Device 1 and Device 2 are the same device just duplicated under different runtimes, CUDA and OpenCL. Since they are the same device, it can't run both runtimes simultaneously. It's using the CUDA runtime in the screenshot, which means the device wasn't actually skipped.

**Comment by WHET1** [comment]
That first error you got there in the red, I've got the same problem and if anyone has a solution I'd love to hear it ... Till then searching for a solution whilst trying myself on and off... The joys of being a beginner...
