### ISSUE TITLE
error on mac big sur

### ISSUE THREAD

**Issue by yovasx2** [hashcat/hashcat#3044]
**Describe the bug**
Error on mac after installing with brew:
```
➜  ~ hashcat --help 
hashcat (v6.2.5) starting in autodetect mode

/Users/yovasx2/.local/share/hashcat/sessions/hashcat.pid: No such file or directory

/Users/yovasx2/.local/share/hashcat/sessions/hashcat.induct: No such file or directory

(null): Bad address

Started: Sun Nov 28 22:02:46 2021
Stopped: Sun Nov 28 22:02:46 2021
➜  ~ sudo hashcat tmp
```

**To Reproduce**
install in mac using brew, run hashcat command

**Expected behavior**
Display help or interact with the command

**Hardware/Compute device (please complete the following information):**
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**Hashcat version (please complete the following information):**
mac big sure 11.3.1

**Diagnostic output compute devices:**

```
For NV: Post nvidia-smi output. This tool also exist on Windows
For AMD ROCm: Post rocm-smi and rocminfo output
```

```
Post clinfo output
```

```
Post hashcat -I output
```

```
On Linux: post lspci output
```

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).

**Comment by 0xPrial** [comment]
Getting same error. 

```
$ hashcat -m 1000 -a 0 hash.txt rockyou.txt                               1 ⨯
hashcat (v6.2.5) starting

/Users/0xPrial/.local/share/hashcat/sessions/hashcat.pid: No such file or directory

/Users/0xPrial/.local/share/hashcat/sessions/hashcat.induct: No such file or directory

(null): Bad address

Started: Fri Dec  3 01:05:38 2021
Stopped: Fri Dec  3 01:05:38 2021

```

Installed via brew :D

**Comment by Coadon** [comment]
Me too.
```
hashcat (v6.2.5-19-g3d53188cc) starting in help mode

/Users/user1/.local/share/hashcat/sessions/usage.pid: No such file or directory

/Users/user1/.local/share/hashcat: No such file or directory
```
Installed via self compilation.

**Comment by mfranzil** [comment]
Can reproduce.
```
❯ sudo hashcat --benchmark --force -D 1,2
hashcat (v6.2.5) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

You have enabled --force to bypass dangerous warnings and errors!
This can hide serious problems and should only be done when debugging.
Do not report hashcat issues encountered when using --force.

/<user>/.local/share/hashcat/sessions/benchmark.pid: No such file or directory

/<user>/.local/share/hashcat: No such file or directory

Started: Sun Dec  5 13:11:29 2021
Stopped: Sun Dec  5 13:11:29 2021
```
This happens when clean pulling with `brew install hashcat`. Building from source with relevant flags works.

Running on 2020 M1 MBP 13'' running Monterey 12.0.1.

**Comment by zestysoft** [comment]
To manually fix:
`mkdir -p /<user>/.local/share/hashcat/sessions`

**Comment by mfranzil** [comment]
Well, worked, but looks like the problem now is a different one:
```
> hashcat --benchmark --force -D 2
hashcat (v6.2.5-19-g3d53188cc) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default. [...truncated]

You have enabled --force to bypass dangerous warnings and errors! [...truncated]

* Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Oct  1 2021 19:40:58)) - Platform #1 [Apple]
====================================================================
* Device #1: Apple M1, 5408/10922 MB (1024 MB allocatable), 8MCU

Benchmark relevant options:
===========================
* --force
* --opencl-device-types=2
* --optimized-kernel-enable

-------------------
* Hash-Mode 0 (MD5)
-------------------

UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

* Device #1: Kernel $HOME/selfconf/pathable/hashcat/OpenCL/shared.cl build failed.

Started: Tue Dec  7 14:52:02 2021
Stopped: Tue Dec  7 14:52:04 2021
```

I'll move it to a different issue if is unrelated to this.

**Comment by 0xPrial** [comment]
`mkdir -p /<user>/.local/share/hashcat/sessions` fixed my issue :D

**Comment by matrix** [comment]
> Well, worked, but looks like the problem now is a different one:
> 
> ```
> > hashcat --benchmark --force -D 2
> hashcat (v6.2.5-19-g3d53188cc) starting in benchmark mode
> 
> Benchmarking uses hand-optimized kernel code by default. [...truncated]
> 
> You have enabled --force to bypass dangerous warnings and errors! [...truncated]
> 
> * Device #1: Apple's OpenCL drivers (GPU) are known to be unreliable.
>              You have been warned.
> 
> OpenCL API (OpenCL 1.2 (Oct  1 2021 19:40:58)) - Platform #1 [Apple]
> ====================================================================
> * Device #1: Apple M1, 5408/10922 MB (1024 MB allocatable), 8MCU
> 
> Benchmark relevant options:
> ===========================
> * --force
> * --opencl-device-types=2
> * --optimized-kernel-enable
> 
> -------------------
> * Hash-Mode 0 (MD5)
> -------------------
> 
> UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
> clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
> 
> * Device #1: Kernel $HOME/selfconf/pathable/hashcat/OpenCL/shared.cl build failed.
> 
> Started: Tue Dec  7 14:52:02 2021
> Stopped: Tue Dec  7 14:52:04 2021
> ```
> 
> I'll move it to a different issue if is unrelated to this.

hi, it is a known bug, we are tracking errors here #3032

**Comment by Chick3nman** [comment]
The root issue in the OP here is related to a broken build process in the homebrew installation. Please build from source to resolve the `No such file or directory` issue. It should be noted that we do not maintain the homebrew package and building from the github is always recommended instead. Closing because issue in OP is outside of hashcat and issue in continuation is a duplicate and is being tracked elsewhere.

**Comment by SuvanCheng** [comment]
> mkdir -p

thx a lot

**Comment by ShivaKatravath** [comment]
How to fix below issue: 

Shivas-MacBook-Pro:huntDay1 shivakatravath$ hashcat -m 16500
hashcat (v6.2.5) starting

OpenCL API (OpenCL 1.2 (Nov 13 2021 00:45:09)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, 4064/8192 MB (1024 MB allocatable), 4MCU
* Device #2: Intel(R) Iris(TM) Plus Graphics 640, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger set to 100c

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:7:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^

* Device #1: Kernel /usr/local/Cellar/hashcat/6.2.5/share/hashcat/OpenCL/shared.cl build failed.

Started: Fri Feb  4 17:25:52 2022
Stopped: Fri Feb  4 17:25:52 2022

**Comment by matrix** [comment]
> How to fix below issue:
> 
> Shivas-MacBook-Pro:huntDay1 shivakatravath$ hashcat -m 16500 hashcat (v6.2.5) starting
> 
> # OpenCL API (OpenCL 1.2 (Nov 13 2021 00:45:09)) - Platform #1 [Apple]
> * Device [ERROR: cuMemsetD8() 1 #1](https://github.com/hashcat/hashcat/issues/1): Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz, 4064/8192 MB (1024 MB allocatable), 4MCU
> * Device [for issue #1: cuMemsetD8() 1 error #2](https://github.com/hashcat/hashcat/pull/2): Intel(R) Iris(TM) Plus Graphics 640, skipped
> 
> Minimum password length supported by kernel: 0 Maximum password length supported by kernel: 256
> 
> Hashes: 1 digests; 1 unique digests, 1 unique salts Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates Rules: 1
> 
> Optimizers applied:
> 
> * Zero-Byte
> * Not-Iterated
> * Single-Hash
> * Single-Salt
> 
> Watchdog: Temperature abort trigger set to 100c
> 
> clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
> 
> :7:10: fatal error: 'inc_vendor.h' file not found #include "inc_vendor.h" ^
> 
> * Device [ERROR: cuMemsetD8() 1 #1](https://github.com/hashcat/hashcat/issues/1): Kernel /usr/local/Cellar/hashcat/6.2.5/share/hashcat/OpenCL/shared.cl build failed.
> 
> Started: Fri Feb 4 17:25:52 2022 Stopped: Fri Feb 4 17:25:52 2022

by stop using brew and start using github version

**Comment by szymon7890** [comment]
> `mkdir -p /<user>/.local/share/hashcat/sessions`

I use this command 
mkdir -p /szymon/.local/share/hashcat/sessions  

I was taken this command. I can't this fix problem ?
mkdir: /szymon: Read-only file system

**Comment by PurplePlatinumVirgate** [comment]
> 

Try `mkdir -p ~/.local/share/hashcat/sessions`

**Comment by ghost** [comment]
> > `mkdir -p /<user>/.local/share/hashcat/sessions`
> 
> I use this command mkdir -p /szymon/.local/share/hashcat/sessions
> 
> I was taken this command. I can't this fix problem ? mkdir: /szymon: Read-only file system

Can you try this :

`mkdir -p /Users/szymon/.local/share/hashcat/sessions`

**Comment by alexrengel** [comment]
Hi [staysafee](https://github.com/staysafee). Thank you. That worked.
