### ISSUE TITLE
Kernel build fails for module 17010 on CPU (Intel and POCL)

### ISSUE THREAD

**Issue by duffman2k5** [hashcat/hashcat#3048]
I'm using hashcat 6.2.5. When benchmarking module 17010 on CPU, hashcat quits with an error. I have tried the Intel-driver-implementation as well as POCL, both fail. I also tried this on different machines (laptop and a server). The benchmark works fine on GPU (NVIDIA).

The problem seems to be: "hc_byte_perm_S is undefined" and then the kernel build fails.

Here are the console-outputs of hashcat:

<details><summary>Intel-OpenCL-Log</summary>

    hashcat -b -m 17010
    hashcat (v6.2.5) starting in benchmark mode
    
    OpenCL API (OpenCL 1.2 LINUX) - Platform #1 [Intel(R) Corporation]
    ==================================================================
    * Device #1: Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz, 31939/63943 MB (7992 MB allocatable), 16MCU
    
    Benchmark relevant options:
    ===========================
    * --optimized-kernel-enable
    
    ----------------------------------------------------------------------------
    * Hash-Mode 17010 (GPG (AES-128/AES-256 (SHA-1($pass)))) [Iterations: 65536]
    ----------------------------------------------------------------------------
    
    clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
    
    Compilation started
    Compilation done
    Linking started
    Linking done
    Device build started
    Failed to build device program
    Error: unimplemented function(s) used:
    hc_byte_perm_S is undefined
    CompilerException Failed to parse IR
    
    * Device #1: Kernel /usr/local/share/hashcat/OpenCL/m17010-pure.cl build failed.
    
    Started: Wed Dec  1 15:02:16 2021
    Stopped: Wed Dec  1 15:02:32 2021

</details>

<details><summary>POCL-Log</summary>

    hashcat -b -m 17010
    hashcat (v6.2.5) starting in benchmark mode
    
    OpenCL API (OpenCL 2.0 pocl 1.8  Linux, RelWithDebInfo, RELOC, SPIR, LLVM 10.0.0, SLEEF, POCL_DEBUG) - Platform #1 [The pocl project]
    =====================================================================================================================================
    * Device #1: pthread-Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz, 30915/61895 MB (8192 MB allocatable), 16MCU
    
    ----------------------------------------------------------------------------
    * Hash-Mode 17010 (GPG (AES-128/AES-256 (SHA-1($pass)))) [Iterations: 65536]
    ----------------------------------------------------------------------------
    
    clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
    
    Error(s) while linking:
    Cannot find symbol hc_byte_perm_S in kernel library
    Device pthread-Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz failed to build the program, log: Error(s) while linking:
    Cannot find symbol hc_byte_perm_S in kernel library
    
    * Device #1: Kernel /usr/local/share/hashcat/OpenCL/m17010-pure.cl build failed.
    
    Started: Wed Dec  1 15:08:18 2021
    Stopped: Wed Dec  1 15:08:31 2021

</details>

If you need further logs / info, pls let me know. 
Thank you for your great work @ hashcat!

**Comment by jsteube** [comment]
Yep, I can reproduce:

```
Error: unimplemented function(s) used:
hc_byte_perm_S is undefined 
CompilerException Failed to parse IR
```

**Comment by jsteube** [comment]
Was fixed with commit https://github.com/hashcat/hashcat/commit/4dc98b334a70c4aa2ad2e9d8a251f6dbbdb13b1d

New beta binaries are also up, in case you need it: hashcat.net/beta

**Comment by duffman2k5** [comment]
Works like a charm with the beta binaries. Thank you!
