### ISSUE TITLE
Hash type 7401 iterations handling bug

### ISSUE THREAD

**Issue by bobcatbite** [hashcat/hashcat#3049]
Feeding Hashcat with hashes obtained from MySQL (type 7401) using the recommended hash retrieval method can result in a Hashcat token error when a non-default number of rounds have been configured on the server. 

The recommended method (reference 19) to retrieve a hash of this type is described in Hashcat [documentation](https://hashcat.net/wiki/doku.php?id=example_hashes) as: 

`SELECT user, CONCAT('$mysql',LEFT(authentication_string,6),'*',INSERT(HEX(SUBSTR(authentication_string,8)),41,0,'*')) AS hash FROM user WHERE plugin = 'caching_sha2_password' AND authentication_string NOT LIKE '%INVALIDSALTANDPASSWORD%';`

In MySQL the default number of rounds is 5000. The server being tested has been configured with 10000 rounds using the [caching_sha2_password_digest_rounds](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_caching_sha2_password_digest_rounds) server system variable. 

Using the recommended query, a hash with 10000 iterations gets retrieved that starts like this:
 $mysql$A$**00A**

Whereas a hash with 5000 rounds gets retrieved via the query that starts like this: 
$mysql$A$**005**

Hashcat errors with a "Token encoding exception" when it encounters a hash with 10000 iterations as the iterations are defined in hex and not digits as expected by Hashcat.

https://github.com/hashcat/hashcat/blob/040fb3b7eb115f2f97645f4121a5ad16fd398c04/src/modules/module_07401.c#L304-L308

This MySQL query works to retrieve a crackable hash using hashcat for a 10000 iteration hash and would work for hashes with the minimum number of rounds, 5000, to 999000 rounds):
 
`SELECT user, CONCAT('$mysql', substring(authentication_string,1,3), LPAD(conv(substring(authentication_string,4,3),16,10), 3, 0),'*',INSERT(HEX(SUBSTR(authentication_string,8)),41,0,'*')) AS hash FROM user WHERE plugin = 'caching_sha2_password' AND authentication_string NOT LIKE '%INVALIDSALTANDPASSWORD%';`

This results in 10000 iteration hashes being retrieved that start like this: 
`$mysql$A$010` 

Whilst the above query alone gives you the ability to crack hashes with more iterations without any Hashcat code changes, if you wanted to accommodate the maximum possible value for caching-sha2-password-digest-rounds of 4095000 (or any number of iterations from 1000000 up to the maximum possible number of iterations), then it would likely require a small hashcat code update, as that would require the iterations field in the hash to be increased to 4 in length. So hashes would then start like the following examples: 
`$mysql$A$0010`
`$mysql$A$4095`

The updated MySQL query would then be as follows (where the left padding is increased to 4): 
`SELECT user, CONCAT('$mysql', substring(authentication_string,1,3), LPAD(conv(substring(authentication_string,4,3),16,10), 4, 0),'*',INSERT(HEX(SUBSTR(authentication_string,8)),41,0,'*')) AS hash FROM user WHERE plugin = 'caching_sha2_password' AND authentication_string NOT LIKE '%INVALIDSALTANDPASSWORD%';`

**Comment by bobcatbite** [comment]
Actually, whilst the above query alone gives you the ability to crack hashes with more iterations without any Hashcat code changes, if you wanted to accommodate the maximum possible value for caching-sha2-password-digest-rounds of 4095000, then it would likely require a small hashcat code update, as that would require the iterations field in the hash to be 4 in length. Like so: 
`$mysql$A$0010`

**Comment by philsmd** [comment]
yeah, this seems to be the most clever solution that doesn't break backwards compatibility (add the padding for at least 4 digits).

I think this is a clever solution, we would only need to update the wiki and the `token.len_max[2] = 4` line. Could you make a pull request please @bobcatbite . we will then make sure that the wiki will be updated too

thx for the report...

**Comment by philsmd** [comment]
thanks, the above commit should fix the problem of a too short field.

I've added this to the example hash wiki:
```
SELECT user, CONCAT('$mysql', SUBSTR(authentication_string,1,3), LPAD(CONV(SUBSTR(authentication_string,4,3),16,10),4,0),'*',INSERT(HEX(SUBSTR(authentication_string,8)),41,0,'*')) AS hash FROM user WHERE plugin = 'caching_sha2_password' AND authentication_string NOT LIKE '%INVALIDSALTANDPASSWORD%';
```

please test this query (it's slightly different from yours, because I use SUBSTR() everywhere instead of a mix of substring() and substr(). I've also uppercased all MYSQL functions).
Thx
