### ISSUE TITLE
bcrypt + salt: Token length exception

### ISSUE THREAD

**Issue by s3rgeym** [hashcat/hashcat#3053]
```bash
➜ hashcat --version                                                                                              
v6.2.5

➜ hashcat -a 0 -m 3200 '$2y$10$...:<samesalt>' ~/work/misc/10-million-password-list-top-1000000.txt
...
Hash '$2y$10$...:<samesalt>': Token length exception
No hashes loaded.
...
```

**Comment by jsteube** [comment]
$2y$10$...:<samesalt> is not a valid hash

**Comment by s3rgeym** [comment]
```php
<?php
/**
 * Мы просто хотим захешировать свой пароль используя настройки по умолчанию.
 * Значит будет использован BCRYPT и результат будет 60 символов длиной.
 *
 * Помните, что алгоритм по умолчанию может измениться в будущем, так что
 * имеет смысл заранее позаботиться о том, чтобы система хранения хешей
 * смогла хранить более 60 символов (255 в самый раз)
 */
echo password_hash("rasmuslerdorf", PASSWORD_DEFAULT);
?>
```

$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a

**Comment by jsteube** [comment]
works fine:

```
root@ht:~/hashcat# cat > word.txt
rasmuslerdorf
root@ht:~/hashcat# ./hashcat -m 3200 '$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a' word.txt 
hashcat (v6.2.5-22-gc01a2b1a9) starting

CUDA API (CUDA 11.4)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10855/11019 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.4.56) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 2080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 72

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 298 MB

Dictionary cache built:
* Filename..: word.txt
* Passwords.: 1
* Bytes.....: 14
* Keyspace..: 1
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a:rasmuslerdorf
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 3200 (bcrypt $2*$, Blowfish (Unix))
Hash.Target......: $2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVA...Fykk1a
Time.Started.....: Wed Dec  8 08:43:17 2021 (1 sec)
Time.Estimated...: Wed Dec  8 08:43:18 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (word.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        2 H/s (9.08ms) @ Accel:1 Loops:16 Thr:16 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1008-1024
Candidate.Engine.: Device Generator
Candidates.#1....: rasmuslerdorf -> rasmuslerdorf
Hardware.Mon.#1..: Temp: 53c Fan: 44% Util: 71% Core:1935MHz Mem:6800MHz Bus:16

Started: Wed Dec  8 08:43:12 2021
Stopped: Wed Dec  8 08:43:20 2021
```

**Comment by s3rgeym** [comment]
> works fine:
> 
> ```
> root@ht:~/hashcat# cat > word.txt
> rasmuslerdorf
> root@ht:~/hashcat# ./hashcat -m 3200 '$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a' word.txt 
> hashcat (v6.2.5-22-gc01a2b1a9) starting
> 
> CUDA API (CUDA 11.4)
> ====================
> * Device #1: NVIDIA GeForce RTX 2080 Ti, 10855/11019 MB, 68MCU
> 
> OpenCL API (OpenCL 3.0 CUDA 11.4.56) - Platform #1 [NVIDIA Corporation]
> =======================================================================
> * Device #2: NVIDIA GeForce RTX 2080 Ti, skipped
> 
> Minimum password length supported by kernel: 0
> Maximum password length supported by kernel: 72
> 
> Hashes: 1 digests; 1 unique digests, 1 unique salts
> Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
> Rules: 1
> 
> Optimizers applied:
> * Zero-Byte
> * Single-Hash
> * Single-Salt
> 
> Watchdog: Temperature abort trigger set to 90c
> 
> Host memory required for this attack: 298 MB
> 
> Dictionary cache built:
> * Filename..: word.txt
> * Passwords.: 1
> * Bytes.....: 14
> * Keyspace..: 1
> * Runtime...: 0 secs
> 
> The wordlist or mask that you are using is too small.
> This means that hashcat cannot use the full parallel power of your device(s).
> Unless you supply more work, your cracking speed will drop.
> For tips on supplying more work, see: https://hashcat.net/faq/morework
> 
> Approaching final keyspace - workload adjusted.           
> 
> $2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a:rasmuslerdorf
>                                                           
> Session..........: hashcat
> Status...........: Cracked
> Hash.Mode........: 3200 (bcrypt $2*$, Blowfish (Unix))
> Hash.Target......: $2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVA...Fykk1a
> Time.Started.....: Wed Dec  8 08:43:17 2021 (1 sec)
> Time.Estimated...: Wed Dec  8 08:43:18 2021 (0 secs)
> Kernel.Feature...: Pure Kernel
> Guess.Base.......: File (word.txt)
> Guess.Queue......: 1/1 (100.00%)
> Speed.#1.........:        2 H/s (9.08ms) @ Accel:1 Loops:16 Thr:16 Vec:1
> Recovered........: 1/1 (100.00%) Digests
> Progress.........: 1/1 (100.00%)
> Rejected.........: 0/1 (0.00%)
> Restore.Point....: 0/1 (0.00%)
> Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1008-1024
> Candidate.Engine.: Device Generator
> Candidates.#1....: rasmuslerdorf -> rasmuslerdorf
> Hardware.Mon.#1..: Temp: 53c Fan: 44% Util: 71% Core:1935MHz Mem:6800MHz Bus:16
> 
> Started: Wed Dec  8 08:43:12 2021
> Stopped: Wed Dec  8 08:43:20 2021
> ```

Hash '$2y$10$h825.Gvp<MODX ADMIN HASH - SOME CHARS HIDDEN>:cb<100 CHARS MODX SALT>6ae2': Token length exception

**Comment by s3rgeym** [comment]
I just replace chars with dots

**Comment by jsteube** [comment]
I have no Idea what you are talking about.
