### ISSUE TITLE
--speed-only shows wrong results, when attacking multiple hashes with different iterations

### ISSUE THREAD

**Issue by duffman2k5** [hashcat/hashcat#3054]
Description of the bug:
--speed-only returns wrong results, when there are multiple hashes with different iteration numbers in the hash-file. I tested this with bcrypt and sha512-crypt.

To reproduce:
I use hashcat 6.2.5.

File bcrypt.ab:
> $2a$12$wsslG/baDAF5C.x59jSKXeOj4MPqvJrnXhY5o4o6VJIXc96.BXO.q
> $2a$05$/scyV.71.Gt/k5B8k46hCOAQL7DHaTFQpYhnr38paAnAli.aEPvwi

File bcrypt.a: (just the first hash of file bcrypt.ab)
> $2a$12$wsslG/baDAF5C.x59jSKXeOj4MPqvJrnXhY5o4o6VJIXc96.BXO.q

File bcrypt.b: (the second hash of bcrypt.ab)
> $2a$05$/scyV.71.Gt/k5B8k46hCOAQL7DHaTFQpYhnr38paAnAli.aEPvwi

Notice the different cost-factors of those two hashes (2^5 and 2^12).

Speed of bcrypt.a is very low as expected, due to the high cost-factor:
> ./hashcat.bin -m 3200 bcrypt.a -w 3 -a 3 "?a?a?a?a" --speed-only --quiet
> Speed.#1.........:      113 H/s (70.35ms)

Speed of bcrypt.b is very high and close to the bcrypt-benchmark as it uses the same, low cost-factor (5):
> ./hashcat.bin -m 3200 bcrypt.b -w 3 -a 3 "?a?a?a?a" --speed-only --quiet
> Speed.#1.........:    14204 H/s (69.08ms)

Here is the strange part: the speed for bcrypt.ab is almost the same as for bcrypt.b
> ./hashcat.bin -m 3200 bcrypt.ab -w 3 -a 3 "?a?a?a?a" --speed-only --quiet
> Speed.#1.........:    14266 H/s (69.03ms)

I suppose the speed for bcrypt.ab should be somewhere between bcrypt.a and bcrypt.b, because there are two hashes now and one of them has a very high cost-factor. It doesn't matter which hash is at the top of bcrypt.ab, speed-only results in a value that is the same for the faster hash-speed.

When I start the actual attack, hashcat shows the same speed (around 14.000 H/s) at the beginning, but then after a while it drops drastically to somewhere around 700 H/s, which is more likely a value I would expect in this scenario. I don't know, if this behavior (that hashcat shows the high value at the start and then drops) is the cause of the problem with speed-only, but as speed-only just runs for a few miliseconds I would guess so. 

Expected behavior:
I would expect that --speed-only returns a value around 700 H/s in this scenario, as it is the speed that the actual attack gets to after a while.

Current workaround: 
As --speed-only is not very reliable in the described scenario, I run the actual attack with --runtime=90 and parse the speed from status at that point.

**Comment by jsteube** [comment]
There are advantages and disadvantages in each configuration. There is a time limit for speed-only runs, I think about 4 seconds, which automatically terminates the session when reached. If the hashes are so slow that the work items have not returned during this time, they will not be processed to the next salt as this would add another 4 seconds. 

Now we could change this behavior, but that would cause other problems, e.g. a very long total time. Imagine you have not just 2 salts but 200 million. The run would take 400 million seconds. 

So how can we reasonably handle this and the answer is to have an absolute timeout and so does Hashcat.
