### ISSUE TITLE
adding coinomi wallet hash

### ISSUE THREAD

**Issue by cryptoprogramer** [hashcat/hashcat#3056]
is it possible to add coinomi wallet hash? to hashcat
if there is a tutorial on how to add hash please give link

**Comment by b0lek** [comment]
It is possible but it takes time.

For a guide see: [docs/hashcat-plugin-development-guide.md](https://github.com/hashcat/hashcat/blob/master/docs/hashcat-plugin-development-guide.md)

**Comment by cryptoprogramer** [comment]
I looked at this docs
but its complicated
can anyone help with this issue

**Comment by cryptoprogramer** [comment]
I am ready to pay anyone who can add coinomi and bip38 hash to hashcat
and I have one condition: fast speed
telegram id: @Btclover10

**Comment by matrix** [comment]
Hi, coinomi wallet hashes can be cracked using hash-mode 27700

```
$multibit$3*16384*8*1*4b75d8687278a57d*fde9a55ea9ed79f48843b45442055d990e1832c4418583bdecd985f3b716d112:@coinomi@@
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 27700 (MultiBit Classic .wallet (scrypt))
Hash.Target......: $multibit$3*16384*8*1*4b75d8687278a57d*fde9a55ea9ed...16d112
Time.Started.....: Fri Jun 16 18:15:15 2023 (1 sec)
Time.Estimated...: Fri Jun 16 18:15:16 2023 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: Pipe
Speed.#1.........:        1 H/s (37.21ms) @ Accel:8 Loops:1024 Thr:32 Vec:1
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 1
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:15360-16384
Candidate.Engine.: Device Generator
Candidates.#1....: @coinomi@@ -> @coinomi@@
Hardware.Mon.SMC.: Fan0: 37%
Hardware.Mon.#1..: Util:100%

```

**Comment by tioabadom** [comment]
> Hi, coinomi wallet hashes can be cracked using hash-mode 27700
> 
> ```
> $multibit$3*16384*8*1*4b75d8687278a57d*fde9a55ea9ed79f48843b45442055d990e1832c4418583bdecd985f3b716d112:@coinomi@@
> Session..........: hashcat
> Status...........: Cracked
> Hash.Mode........: 27700 (MultiBit Classic .wallet (scrypt))
> Hash.Target......: $multibit$3*16384*8*1*4b75d8687278a57d*fde9a55ea9ed...16d112
> Time.Started.....: Fri Jun 16 18:15:15 2023 (1 sec)
> Time.Estimated...: Fri Jun 16 18:15:16 2023 (0 secs)
> Kernel.Feature...: Pure Kernel
> Guess.Base.......: Pipe
> Speed.#1.........:        1 H/s (37.21ms) @ Accel:8 Loops:1024 Thr:32 Vec:1
> Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
> Progress.........: 1
> Rejected.........: 0
> Restore.Point....: 0
> Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:15360-16384
> Candidate.Engine.: Device Generator
> Candidates.#1....: @coinomi@@ -> @coinomi@@
> Hardware.Mon.SMC.: Fan0: 37%
> Hardware.Mon.#1..: Util:100%
> ```

Which script did you use to extract the hash?
