### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE on Apple M1 Pro

### ISSUE THREAD

**Issue by l3ra** [hashcat/hashcat#3057]
Using hashcat in benchmark mode on the Apple M1 Pro installed with brew. 

hashcat --benchmark -m 0 -D 1,2 -w 2 

returns:

UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

Compilation failed: 

program_source:7:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^~~~~~~~~~~~~~

* Device #1: Kernel /opt/homebrew/Cellar/hashcat/6.2.5/share/hashcat/OpenCL/shared.cl build failed.

To Reproduce:

M1 Pro laptop with homebrew hashcat, run:

hashcat --benchmark -m 0 -D 1,2 -w 2 

**Expected behaviour**

Produce benchmarks. 

**Hardware/Compute device (please complete the following information):**
- Compute device name: Apple M1 Pro
- OpenCL/CUDA driver name: OpenCL 1.2 (Oct  1 2021 19:40:58)
- OpenCL/CUDA driver version: OpenCL C 1.2 
- OpenCL/CUDA driver source:

**Hashcat version (please complete the following information):**
 - OS: MacOS 
 - Distribution: Monterey
 - Version: 12.0.1

**Diagnostic output compute devices:**
hashcat -I
hashcat (v6.2.5) starting in backend information mode

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (Oct  1 2021 19:40:58)

  Backend Device ID #1
    Type...........: GPU
    Vendor.ID......: 2
    Vendor.........: Apple
    Name...........: Apple M1 Pro
    Version........: OpenCL 1.2 
    Processor(s)...: 14
    Clock..........: 1000
    Memory.Total...: 10922 MB (limited to 1024 MB allocatable in one block)
    Memory.Free....: 5408 MB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2 1.0

**Comment by matrix** [comment]
check here #3032

**Comment by olenese** [comment]
I have the same issue on an Intel Mac.

I tried the -D variable to choose GPU or CPU but no difference

@MacBook-Pro-2 ~ % hashcat -m 0 56ab24c15b72a457069c5ea42fcfc640
hashcat (v6.2.5) starting

* Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

* Device #3: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Oct  1 2021 19:40:58)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, skipped
* Device #2: Intel(R) UHD Graphics 630, 704/1536 MB (192 MB allocatable), 24MCU
* Device #3: AMD Radeon Pro 5300M Compute Engine, 3968/4080 MB (1020 MB allocatable), 20MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:7:10: fatal error: 'inc_vendor.h' file not found
#include "inc_vendor.h"
         ^

* Device #2: Kernel /usr/local/Cellar/hashcat/6.2.5/share/hashcat/OpenCL/shared.cl build failed.

Started: Tue Dec 14 15:23:11 2021
Stopped: Tue Dec 14 15:23:13 2021

**Comment by matrix** [comment]
I don't think it is correct to mix the problems. Anyway hashcat works if you try it using the github version. Thanks

**Comment by cbowns** [comment]
It's a shell configuration problem, see my fix in https://github.com/hashcat/hashcat/issues/3080#issuecomment-1029682228

```
export CPLUS_INCLUDE_PATH=/usr/local/share/hashcat/OpenCL
hashcat -b -D2
```

**Comment by matrix** [comment]
@cbowns please tell me more about CPLUS_INCLUDE_PATH 
Thanks :)

edit: got it

https://clang.llvm.org/docs/CommandGuide/clang.html#envvar-C_INCLUDE_PATH,OBJC_INCLUDE_PATH,CPLUS_INCLUDE_PATH,OBJCPLUS_INCLUDE_PATH
