### ISSUE TITLE
--status-json does not include attack info

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#3061]
**Describe the feature**
`--status-json` should include attack info

**Current behavior**
`--status-json` does not include attack info

**Expected behavior**
`--status-json` to include attack info: such as guess.mod, guess,queue, etc...

**Hashcat version**
 - Version:  tested with 6.2.4, checked [master](https://github.com/hashcat/hashcat/blob/bf865d8bff2db0d7cc617c3fd5d8e73bd1b4a8b3/src/terminal.c#L1248-L1365) branch too, the feature does not exist yet

**Comment by Chick3nman** [comment]
What information do you specifically want added? `--status-json` presents a very slimmed down set of information on purpose, similar to `--machine-readable` so it will be lacking some information regardless, including any values that can be calculated or known externally.

**Comment by s77rt** [comment]
`guess.queue` cannot be calculated and not known externally
and any other fields that have a relation with it, such as `guess.base`

**Comment by Chick3nman** [comment]
`guess.queue` is just a count of remaining bases, with `guess.base` being the current file/mask. `guess.mod` will be right side masks/files for hybrids or combinators. This is further complicated by the inclusion of `guess.queue.base` and `guess.queue.mod` in some hybrid attacks. I believe these are all externally calculable or knowable with context though. For example, if you have 10 dictionaries in a folder of known size, you know which files are being processed and in which order[guess.base], how many there are[guess.queue], and where you are roughly in them at any time[guess.queue, guess.queue.base, guess.queue.mod] without too much difficulty, barring unexpected skips and/or significant speed ups or slow downs during the attack. You can also further simplify this by never issuing an attack with a larger list of bases/mods than you can know at any time and automating the iteration through your bases/mods. Given that this flag is specifically for automation systems and this is already how other systems handle this, I'm not sure I see the utility in adding more information to the outputs than what is necessary. Can still be done, just trying to keep the machine oriented outputs fairly slim.

**Comment by s77rt** [comment]
thanks for your explanation, but still `guess.queue` cannot be accurately calculated
`speed` also can be calculated in an non-accurate way but it's in the output
if you insist on keeping the json output that slim, maybe another flag can be introduced to get the full details
json is not only a machine readable format, it's also easy for humans

**Comment by Chick3nman** [comment]
While JSON is a more readable format, why not just use the normal output for reading? What is the use case? Like i said, it can definitely be added, I'm just not sure i understand the use case still. There may be a better way to accomplish what you are after.

**Comment by s77rt** [comment]
working on a gui for hashcat ([hashcat.launcher](https://github.com/s77rt/hashcat.launcher))
and it's necessary to provide info about the running tasks, i used to extract such info from the standard output but it requires regex while json does not

**Comment by b0lek** [comment]
Do you  want to get this type of status? :
`{ "session": "hashcat", "guess": { "guess_base": "?1?2", "guess_base_count": "15", "guess_base_offset": "2", "guess_base_percent": "13.33%", "guess_mask_length": "2", "guess_mod": "(null)", "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "10" } "status": 5, "target": "hashgoeshere", "progress": [2232, 2232], "restore_point": 36, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 187063, "temp": 63, "util": 55 } ], "time_start": 1639734718, "estimated_stop": 1639734718 }`

If that is enough, and there is OK to add it I already have code for that.
Other scenario is to add and extra option like `--status-json-ext` if backward compatibility is required.

**Comment by s77rt** [comment]
yes something like that except null variables should not be exported (`guess_mod` in your example)

**Comment by Chick3nman** [comment]
That's sort of another issue with this. I would expect the same variables to be sent in every single status output, regardless of if they are null or not. That would need to be handled on the receiving side. Varying what is output in the status is not ideal for a format meant for machine reading. Luckily, JSON is a key value store so varying outputs isnt the worst, but I think it would still be better to have a consistent set of variables in every output. @b0lek 's output would cover everything you want but it differs from the original output slightly. Tools relying on the current JSON output will need to be updated to fit with the new one. A second flag seems unnecessary as they can simply use the new format instead of the older one.

**Comment by b0lek** [comment]
Good. I go for same variables sent in every status output, with null values. Anyway checking if variable is present or if it is null adds `if` to receiver code. Checking for `null` is usually cheaper than checking if a variable is present. 
Thanks to your comments I just realized that null in JSON should be `null` not `(null)`.
Fixed and I will prepare PR.
