### ISSUE TITLE
JWT mode returns wrong hash in solved response for HS384/HS512 types

### ISSUE THREAD

**Issue by brandoncasaba** [hashcat/hashcat#3063]
**Describe the bug**
When cracking JWT hashes of hash HS384 and HS512 (not HS256), the JWT that is returned in cracked hashes does not match the input hash. 

**To Reproduce**
Example from https://jwt.io for HS384 with secret "hashcat":
eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.CijKKtet34Bk0HbTJDPl8x_0AFL8kcxD4FRczGGErYo6yi3jB52LRV783th9UNBV

Attempt to crack using 6.2.5:
```
>hashcat.exe -a3 -m 16500 eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.CijKKtet34Bk0HbTJDPl8x_0AFL8kcxD4FRczGGErYo6yi3jB52LRV783th9UNBV hashcat
hashcat (v6.2.5) starting

CUDA API (CUDA 11.5)
====================
* Device #1: NVIDIA GeForce GTX 1060 6GB, 5228/6143 MB, 10MCU

OpenCL API (OpenCL 3.0 CUDA 11.5.56) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce GTX 1060 6GB, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1473 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.163fgAooyiokM-XzZNB20_yRzEMf9ABSYYStiuBUXMw:hashcat

Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 16500 (JWT (JSON Web Token))
Hash.Target......: eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMj...uBUXMw
Time.Started.....: Thu Dec 16 17:45:10 2021 (0 secs)
Time.Estimated...: Thu Dec 16 17:45:10 2021 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: hashcat [7]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:      300 H/s (0.09ms) @ Accel:512 Loops:1 Thr:64 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: hashcat -> hashcat
Hardware.Mon.#1..: Temp: 50c Fan: 44% Util: 74% Core:1507MHz Mem:3802MHz Bus:16

Started: Thu Dec 16 17:45:04 2021
Stopped: Thu Dec 16 17:45:11 2021
```
Note that signature block changed in the printed found line. It is the size of the HS256 signature. I'm assuming it's generated from the found plaintext using HS256 signature algorithm. 

The same wrong signature block is observed in the potfile and output file outputs as well. 

This plays havoc on tools like Hashtopolis as well for obvious reasons of not matching an existing hash.

**Expected behavior**
The same input hash should be reported in the found hash line and output files as was passed in.

i.e.:
eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.**CijKKtet34Bk0HbTJDPl8x_0AFL8kcxD4FRczGGErYo6yi3jB52LRV783th9UNBV**:hashcat

**Hardware/Compute device (please complete the following information):**
- Compute device name: Multiple Nvidia devices on multiple machines
- OpenCL/CUDA driver name: Nvidia driver
- OpenCL/CUDA driver version: 496.13
- OpenCL/CUDA driver source: 

**Hashcat version (please complete the following information):**
 - OS: Windows or Linux
 - Distribution: Windows 10 and Ubuntu 18.04 tested
 - Version: 6.2.5

**Comment by brandoncasaba** [comment]
Byte analysis of the returned hash vs the original. 
```
Returned:
163fgAooyiokM-XzZNB20_yRzEMf9ABSYYStiuBUXMw
d7addf80 0a28ca2a 2433e5f3 64d076d3 fc91cc43 1ff40052 6184ad8a e0545ccc

Original:
CijKKtet34Bk0HbTJDPl8x_0AFL8kcxD4FRczGGErYo6yi3jB52LRV783th9UNBV
0a28ca2a d7addf80 64d076d3 2433e5f3 1ff40052 fc91cc43 e0545ccc 6184ad8a 3aca2de3 079d8b45 5efcded8 7d50d055
```

Notice some similar byte blocks between the two, I think I may have a guess where things went wrong. If I can fix it I'll make a pull request.

**Comment by brandoncasaba** [comment]
Problem found.
https://github.com/hashcat/hashcat/blob/master/src/modules/module_16500.c#L271

hashconfig->kern_type is always KERN_TYPE_JWT_HS256 or 16511 no matter the original hash algorithm. 

Quick fix is to do the same check on the esalt length as we do in the module_kern_type_dynamic function to determine type.

Created pull request #3064

**Comment by jsteube** [comment]
Merged the fix, many thanks!
