### ISSUE TITLE
No such file or directory OsX

### ISSUE THREAD

**Issue by KJae2** [hashcat/hashcat#3082]
Getting the same error while trying to run in Macbook Intel and M1, Catalina and Monterey

/Users/mac/.local/share/hashcat/sessions/usage.pid: No such file or directory

/Users/mac/.local/share/hashcat: No such file or directory

**Comment by matrix** [comment]
mkdir -p ${HOME}/.local/share/hashcat

**Comment by KJae2** [comment]
Thanks Gabriele, I created .local, share and hashcat directories individually and it worked.

 

mkdir -p ${HOME}/.local/share/hashcat

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wiliwix9** [comment]
having "wordlist.txt: No such file or directory" macos when running hashcat -m 2500 capture.hccapx wordlist.txt

any solutions?

**Comment by AnoKURSKnymouS** [comment]
> having "wordlist.txt: No such file or directory" macos when running hashcat -m 2500 capture.hccapx wordlist.txt
> 
> any solutions?

i have a SAME problem...
