### ISSUE TITLE
feature: --hex-separator

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3084]
**Describe the feature**
Allow specification of separator (-p/--separator) in hex.

**Additional context**
Some separators that are not visible, but are printable (such as tab) can potentially cause confusion during troubleshooting. This would allow them to be specified clearly.

**Comment by b0lek** [comment]
Do I understand it correctly?
You want to specify `--separator 0x09` for TAB separator?

**Comment by roycewilliams** [comment]
Yes, that is the goal. In keeping with the other `--hex` operators, I assumed that an additional `--hex-separator` flag would be needed. But now that I think about it, since separator is expected to be a single character, passing an `0x` value to --separator` could be automatically interpreted as wanting that. :D

**Comment by b0lek** [comment]
That is my plan. `0x` as a prefix would say that this is `hex` format. Otherwise exactly one character is expected.
I'll finish this tomorrow, as I need to do some more testing.

**Comment by Chick3nman** [comment]
This was merged in #3127, Closing. Reopen if merge did not satisfy original issue.
