### ISSUE TITLE
sha512 salt length

### ISSUE THREAD

**Issue by kost123** [hashcat/hashcat#310]
I have a sha512($password.$salt) It's (128:128) chars.

I edited the hashcat includes/source.h to allow salts of 128 chars and it doesn't crack a known password, so I'm wondering how can I crack 128char salts? I'm guessing somewhere deeper down the line it messes up but that goes beyond my depth :s

Tried it with insidepro's hashmanager and it worked.. but slow speeds..

I'm getting 100P/s on hashmanager and with my edited source.h I get like 1mil a second on hashcat Sad(( 

Is there anyway I can do this? please.

**Comment by jsteube** [comment]
You need to create a new hashmode and a new kernel for it. There's no way around. From my experience with new hashmode support you propably wont get much help unless the algorithm is used in a popular application or is important for some other reason. That's why you should always name the application where this algorithm is used in.

**Comment by kost123** [comment]
@jsteube would somebody accept payment for this? I don't have the skills to do so.

**Comment by jsteube** [comment]
Buying such a kernel would cost you several thousand dollars because there's only a few people who can do that. But why buy it if you can get it for free. You just need to provide all the information behind your request and the system using it. This way everyone can use it afterwards.

**Comment by kost123** [comment]
Well, it's just sha512 but with a longer salt. I made the system but.. I have seen a few posts on hashcat forums and alike with the same problem. I'm not sure why but there seems to be quite a few sha512 128:128 going around.

**Comment by jsteube** [comment]
OK so this isn't really about a new algorithm, it's generally more like you want to have a longer salt support. This is something people ask often, but not related to SHA512. It's not too hard to add but it's also not very high priority for me. Whoever wants to add this, feel free to do so.

**Comment by kost123** [comment]
It's fine, I hope it gets added at some point. I am using JTR at the moment, it's still on CPU but it works.

**Comment by kost123** [comment]
Any update on this guys?

It would be awesome if you could define your own salt length.

**Comment by epixoip** [comment]
Defining your own salt length isn't really possible because max salt length is hardcoded into the implementation of the algorithm, that's why jsteube said you'd have to write a new kernel to support this functionality. And generic algorithms with no length limitations are the antithesis of Hashcat.

**Comment by kost123** [comment]
Can you point me in the direction of the code I need to be looking at to change the salt length for sha512(pass.salt) then please? I've been looking and I really don't know. ( I know it's more complicated than changing a number)

**Comment by epixoip** [comment]
You can't just change the salt length. You have to write a completely new SHA512 implementation that can support that large of an input.

**Comment by kost123** [comment]
This can be closed then.

**Comment by kost123** [comment]
"it's generally more like you want to have a longer salt support. This is something people ask often, but not related to SHA512. It's not too hard to add"

Then

"You have to write a completely new SHA512 implementation that can support that large of an input. "

Which one is right?

**Comment by epixoip** [comment]
Both are correct, those two statements are not mutually exclusive.

**Comment by gituser** [comment]
You can split your salt to 2 if it's 128 chars.

I don't know for oclHashcat, but for CPU hashcat this is possible.

Of course you need to modify code.

**Comment by kost123** [comment]
Oh really... continue explaining a little please?

**Comment by jsteube** [comment]
Btw I've just added a new mode -m 13800 to crack Windows 8+ phone pins/password -- it's basically sha256 with a fixed 128 byte salt, so the same problem you have. You could hack it to do sha512 instead.

**Comment by kost123** [comment]
God damn yes.. brb :D

**Comment by kost123** [comment]
Actually.. won't I have the same problem trying to account for the hash length? or is it just a case of merging the two with the increased salt length?

**Comment by kost123** [comment]
Nope.. Don't think I can do it xD in 1710 the salt section is all seperate.. in 13800 you have the salt code mixed up seems like and involved with the carry switches and the memcat function?

Seems so much more complicated than 1710 >.>
Edit: well I have no idea.. if anybody could tell me the parts that need changing that would be great but for now I really don't know.

**Comment by kost123** [comment]
Found a better solution to my problems, credit to atom and phil :dancer: 
Close if u wish or keep it up, whatever.

**Comment by gituser** [comment]
What was a solution? :) Others might benefit from it.

**Comment by kost123** [comment]
Not related to hashcat..

Wouldn't mind hearing your 2 salt thing tho..

**Comment by gituser** [comment]
> Wouldn't mind hearing your 2 salt thing tho..

it's only for hashcat CPU.. oclhashcat got different architecture.

best is to study what @jsteube has added recently and compare to -m 1710

**Comment by kost123** [comment]
Yea I meant for hashcat CPU... I'd like to see and most likely will try to replicate on sha512. 

In fact I don't even know if it would be simpler to change the salt length in CPU version.

**Comment by gituser** [comment]
Here is a quick and dirty patch for hashcat-2.00 (release) it adjusts -m 1710 mode:
https://gist.github.com/gituser/c6e9bc382c978123ed5c558e8639e576

```
$ ./hashcat-cliAVX.bin -m 1710 test.sha512 test.wordlist 
Initializing hashcat v2.00 with 4 threads and 32mb segment-size...


Added hashes from file test.sha512: 1 (1 salts)
Activating quick-digest mode for single-hash with salt

2bbc652c39d5e0bf8680b9ac8d795f0c449f84db52c594cab4d853c4926d21963f2def0475fb0976d296747351d3cb9a44f53a7a3cffd152ba7d078f854c4a3a:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:test

All hashes have been recovered

Input.Mode: Dict (test.wordlist)
Index.....: 1/1 (segment), 1 (words), 5 (bytes)
Recovered.: 1/1 hashes, 1/1 salts
Speed/sec.: - plains, - words
Progress..: 1/1 (100.00%)
Running...: 00:00:00:01
Estimated.: --:--:--:--

```

**Comment by thepaandu** [comment]
@kost123 @gituser Hey, can you add me on skype at deepak.affrevenue? 
Need to talk about this dirty patch.
thanks!

**Comment by kost123** [comment]
Still need this (or pointing in direction for another mode I can adapt fairly easily)
