### ISSUE TITLE
clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3115]
Hello, I am getting an error when I execute the following command on M1：

```
hashcat  tony::DRIVER:f60939facd74237b:EE21D0CBE6E673EF1F80D43244AFE576:010100000000000012267FCB7D05D8013FB3B608D9A2B3BD00000000020000000000000000000000 2020-200_most_used_passwords.txt --force -D 2 -m 5600
```

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/92664048/148680537-35884d0a-d7a5-4e54-a4ba-c314e8825a16.png">

**Comment by amerkestijn** [comment]
I have no experience with the M1 Mac's but have you checked if the noted file "inc_vendor.h" is present in your OpenCL directory (/usr/local/share/hashcat/OpenCL/inc_vendor.h)?

**Comment by ghost** [comment]
> I have no experience with the M1 Mac's but have you checked if the noted file "inc_vendor.h" is present in your OpenCL directory (/usr/local/share/hashcat/OpenCL/inc_vendor.h)?

Yes.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/92664048/148683868-ade75d07-95cd-47a8-8261-919265a11973.png">

**Comment by matrix** [comment]
check here #3080

**Comment by matrix** [comment]
@0x0021h please give us feedback on the proposed solution. In case it is positive if you can also close the issue. Thanks!

**Comment by ghost** [comment]
> @0x0021h please give us feedback on the proposed solution. In case it is positive if you can also close the issue. Thanks!

<img width="795" alt="image" src="https://user-images.githubusercontent.com/92664048/149259232-0e74ebbd-26c5-4a5f-bfb7-8d4ab563e359.png">


It's working! Thank you!
