### ISSUE TITLE
The released compressed 7z does not contains binaries

### ISSUE THREAD

**Issue by vemonet** [hashcat/hashcat#3126]
**Describe the issue**
There is no documentation to install Hashcat, so I am trying to download the release from here: https://hashcat.net/files/hashcat-6.2.5.7z 

But after unzipping this file (on Ubuntu 20.04 Linux) it does not contain any binary, only a few (mostly) empty folders: charsets, docs, extra, layouts, masks, modules, OpenCL (this one has a few files in it but no binary), rules 

**To Reproduce**
Go to https://hashcat.net/hashcat/ and try to install hashcat on your Linux computer.

**Solution 1:** right click and unzip the 7z file. This solution manage to unzip a few empty folder and files, then get an error.

![Screenshot from 2022-01-13 17-49-27](https://user-images.githubusercontent.com/3778439/149373162-4576d13e-59ef-4109-a126-b7e7761ae7c4.png)

Could not find anything that I could use to execute hashcat.

**Solution 2**: download additional weird packages to make sure the problem don't come from unzipping (I should not need to do this just to get your binary on my machine, but let's try it)

```
sudo apt-get install p7zip
7zr e hashcat-6.2.5.7z
```

This unzip 2600+ files in the current folder, cf. the screenshot below

![Screenshot from 2022-01-13 17-52-52](https://user-images.githubusercontent.com/3778439/149373833-e33ca026-2521-47aa-9792-4ab41ba67864.png)

Of course there is no folder that seems to have binaries (e.g. a `bin` folder)

**Expected behavior**

It should be obvious and easy to download the binaries.

There are a few way to solve this:
* There should be a few basic instructions to get the binaries. And the `.7z` file should contain the binaries for various platforms
* The release zip file should contain only the binaries, no weird files that the end user has no care about
* Ideally you should avoid using compressed file altogether for your releases. Like a lot of other project do: just upload the various binaries for the various platforms directly on GitHub Release. So the user can just read the name of the binary, click on it to download the right one, and run it (no weird shenanigans in the middle for your users: no need to master a new compressiong formats, no thousands of useless files to go through; just read, click, and execute!)

**Comment by vemonet** [comment]
I found there is a `hashcat.bin` file in the middle of those 3000 files.

So I tried to run it, but of course the binary has not been compiled properly:

```bash
./hashcat.bin -h
hashcat (v6.2.5) starting in help mode

/home/vemonet/Downloads/hashcat/modules/module_00000.so: No such file or directory

If you are using the hashcat binary package, this may be an extraction issue.
For example, using "7z e" instead of using "7z x".
```

Funny note: I actually used `7z e`, and the file `module_00000.so` exists

So the problem is still there: is it possible to _just_ download and execute hashcat?

**Comment by ZerBea** [comment]
The release is decompressing as expected. Looks like your GUI is running the false tools to decompress it.
```
$ 7z t hashcat-6.2.5.7z

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 8652614 bytes (8450 KiB)

Testing archive: hashcat-6.2.5.7z
--
Path = hashcat-6.2.5.7z
Type = 7z
Physical Size = 8652614
Headers Size = 17414
Method = LZMA2:28 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok                                  

Folders: 44
Files: 2276
Size:       225959913
Compressed: 8652614

```

You should use command x
x : eXtract files with full paths
instead of e
e : Extract files from archive (without using directory names)
than everything would be fine:
```
$ 7z x hashcat-6.2.5.7z

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 8652614 bytes (8450 KiB)

Extracting archive: hashcat-6.2.5.7z
--
Path = hashcat-6.2.5.7z
Type = 7z
Physical Size = 8652614
Headers Size = 17414
Method = LZMA2:28 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok                                  

Folders: 44
Files: 2276
Size:       225959913
Compressed: 8652614

```
```
$ cd hashcat-6.2.5
[hashcat-6.2.5]$ ls
charsets  example0.cmd   example0.sh     example400.hash  example500.cmd   example500.sh  extra        hashcat.exe      hashcat.hctune  masks    OpenCL
docs      example0.hash  example400.cmd  example400.sh    example500.hash  example.dict   hashcat.bin  hashcat.hcstat2  layouts         modules  rules
```
