### ISSUE TITLE
feature: detect parameterless execution from UI and show warning

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3129]
**Describe the feature**
To inform naive "click to run" new users, detect when click-to-run and print a warning before exiting. 

**Current behavior**
Double-clicking on hashcat from a UI results in a brief terminal window that vanishes.

**Expected behavior**
Terminal window displays brief guidance, then prompts user to press enter or close the window to continue.

**Additional context**
This is one of the most frequent FAQ items, and addressing it could significantly reduce new-user confusion.

Windows is the OS of the primary use case. According to this [this reference](https://stackoverflow.com/a/14394730/263879), if the PROMPT environment variable is set in Windows,  then the command was run from the command line. So we might be able to check for the absence of PROMPT (and the absence of any other cmdline options), and branch accordingly.

**Comment by Chick3nman** [comment]
The current behavior on Windows if the binary is double clicked is to hold open until the user interacts and display the default parameterless help message. I think that fixes this issues, please review and close if so.

**Comment by roycewilliams** [comment]
Yep, that covers it - thanks!
