### ISSUE TITLE
error: the following arguments are required: --vault

### ISSUE THREAD

**Issue by WiFik18** [hashcat/hashcat#3137]
C:/python/python.exe c:/hashcat-metamask_big/tools/metamask2hashcat.py
usage: metamask2hashcat.py [-h] --vault VAULT
metamask2hashcat.py: error: the following arguments are required: --vault

_Originally posted by @WiFik18 in https://github.com/hashcat/hashcat/pull/2930#pullrequestreview-853777624_

**Comment by matrix** [comment]
@WiFik18 where's the bug? metamask2hashcat.py simply tell you about a missing argument
