### ISSUE TITLE
Integer overflow detected in keyspace of mask:

### ISSUE THREAD

**Issue by spartanhernan** [hashcat/hashcat#3149]
Integer overflow detected in keyspace of mask: ?l?u?l?u?l?u?l?l?d?d?u?u?d?u?u?d?s?l?u?l

C:\Users\Hernan\Downloads\hashcat-6.2.5>hashcat.exe -m 22000 -a3 -i --increment-min=20 --increment-max=20 NEWTEST.hc22000 ?l?u?l?u?l?u?l?l?d?d?u?u?d?u?u?d?s?l?u?l
hashcat (v6.2.5) starting

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 11.6)
====================
* Device #1: NVIDIA GeForce RTX 3090, 23336/24575 MB, 82MCU

OpenCL API (OpenCL 3.0 CUDA 11.6.58) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3090, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1462 MB

Integer overflow detected in keyspace of mask: ?l?u?l?u?l?u?l?l?d?d?u?u?d?u?u?d?s?l?u?l

Started: Tue Feb 01 23:14:24 2022
Stopped: Tue Feb 01 23:14:26 2022

PASSWORD AND MASK ARE THE FOLLOWING :

 w Z b L m N u t 3 4 T R 8 F X 0 % z B b
 ?l?u?l?u?l?u?l?l?d?d?u?u?d?u?u?d?s?l?u?l
 
 pcap turned into hash  cat file here:
 [https://drive.google.com/file/d/1xUpoJ243poCT4ywCUmOFOr87BjSA7Ppi/view?usp=sharing](url)
 https://drive.google.com/file/d/1xUpoJ243poCT4ywCUmOFOr87BjSA7Ppi/view?usp=sharing

**Comment by spartanhernan** [comment]
so attempting to test hash cat against more difficult passwords however looks like there is a memory issue for where the length of the password mask is too long?   what if the password is longer than 32 characters in length ?

**Comment by matrix** [comment]
> ?l?u?l?u?l?u?l?l?d?d?u?u?d?u?u?d?s?l?u?l

simplifying the mask, removing ?d and ?s, then reducing the len to 15, your attack will be over in 1565092352.5 millenniums, or 1565092352477.5 years, using one NVIDIA RTX 3090. I think this is enough as an explanation? :)

**Comment by spartanhernan** [comment]
Yes I believe it does :) thank you for helping realize more realistic
expectations. Mathematics hurt.

**Comment by matrix** [comment]
... if I have not miscalculated, I did them on the fly during my momentary awakening at night
