### ISSUE TITLE
Combinator attack by username

### ISSUE THREAD

**Issue by kost123** [hashcat/hashcat#3152]
Is it possible to add a combinator attack that works based off the username, the wordlist itself will be user:pass

User1:cat
User1:dog
User2:mouse
User2:chicken

Then it would try combinations of cat and dog for user1's, then combinations of mouse and chicken for user2 and so on against all hashes. This would greatly reduce keyspace in specific attacks, allowing you to not have to combinate entire dictionaries but target individual user combinations. Optional is another switch which could be enabled to combinate up to X amount of combinations(given the user has enough passwords to create them).

**Comment by Chick3nman** [comment]
This would be quite a challenge from a technical standpoint. Sort of like an -a 9 mixed with -a 1. I don't think that's likely to be added given how complicated it would be.

**Comment by 0xVavaldi** [comment]
I think -a9 itself covers this sufficiently, You can replicate this easily by splitting on the : and running the -a9 accordingly

**Comment by Chick3nman** [comment]
> I think -a9 itself covers this sufficiently, You can replicate this easily by splitting on the : and running the -a9 accordingly

@kost123 given that -a 9 does indeed perform this function, with only minimal user preparation, can we close this? Or do you still have a use case where this is important and -a 9 can not be used effectively?
