### ISSUE TITLE
The progress point established with the pipeline command does not take effect when the command is restored

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3164]
`hashcat --session 1 --stdout -a1 dic.txt  dic2.txt | hashcat  -m 20 md5.txt -o Pd.txt`
Use the pipeline command to establish a progress point, it will not take effect when the command is resumed
The progress point established with the pipeline command does not take effect when the command is restored
I tried adding --session parameter to the following command,
  But doesn't work when restore using `hashcat --session=hashcat --restore command`

`hashcat --session=hashcat --restore`

`Session..........: hashcat
Status...........: Running
Hash.Name........: md5($salt.$pass)
Hash.Target......: 0e97d5b70198d53e5ea26720eb7b52aa:431f3e71d0
Time.Started.....: Thu Feb 10 15:59:21 2022 (30 secs)
Time.Estimated...: Thu Feb 10 15:59:51 2022 (0 secs)
Guess.Base.......: Pipe
Speed.#1.........:        0 H/s (0.00ms) @ Accel:1024 Loops:1 Thr:64 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 0
Rejected.........: 0
Restore.Point....: 0
Restore.Sub.#1...: Salt:0 Amplifier:0-0 Iteration:0-1
Candidates.#1....: [Copying]
Hardware.Mon.#1..: Util:  0% Core: 300MHz Mem: 300MHz Bus:16
`

**Comment by Chick3nman** [comment]
I'm not sure restore and stdin/stdout can be used together effectively. What is the full command when you attempt to restore the attack?
