### ISSUE TITLE
-S "advertisement" in -a 9, when the two flags aren't compatible

### ISSUE THREAD

**Issue by PenguinKeeper7** [hashcat/hashcat#3169]
Hashcat "advertises" -S in -a 9 despite not being able to use it in that mode. Tested on the latest beta at the time of writing, `6.2.5-207-gac1997027`
Command: 
```
hashcat -a 9 -m 3200 hashes plains -D 2 -O
```
Erroneous text: 
```
* Append -S to the commandline.
  This has a drastic speed impact but can be better for specific attacks.
  Typical scenarios are a small wordlist but a large ruleset.
```
Error after trying to use -S in -a 9: 
```
Invalid attack mode (-a) value specified in slow-candidates mode.
```

**Comment by Chick3nman** [comment]
Fixed with https://github.com/hashcat/hashcat/pull/3178
