### ISSUE TITLE
Progress reset upon quitting when --restore is used

### ISSUE THREAD

**Issue by owenashurst** [hashcat/hashcat#317]
I've quit hashcat many times with the --restore option however it seems to reset my progress occasionally which is quite annoying when doing large cracking - meaning I have to start back at 0%. 

This is the latest version (v2.01) for Nvidia.

**Comment by epixoip** [comment]
Github issues should only be opened against the code that's actually in Github. cudaHashcat no longer exists, so please try latest oclHashcat beta or build from source, and if the problem persists, open an issue at that time. Thanks!

**Comment by jsteube** [comment]
Not a bug, just use "c" instead of "q" when stopping a session

**Comment by owenashurst** [comment]
"C" doesn't do anything - there's also no option for "c" that states
anything. There's only [S]Status, [P]ause, [R]esume, [B]ypass, [Q]uit.
