### ISSUE TITLE
confusion between PDF mode 10500 and 25400

### ISSUE THREAD

**Issue by piramiday** [hashcat/hashcat#3181]
hi all, 

I am confused by the following two hashcat modes:
```
  10500 | PDF 1.4 - 1.6 (Acrobat 5 - 8)                       | Document
  25400 | PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass | Document
```
I have a PDF 1.4 file:
```
user@host:~$ head -n1 test.pdf 
%PDF-1.4
```
from which I extracted the hash using `pdf2john.pl`, which comes out as:
```
$pdf$2*3*128*-1324*1*16*6adf3addaeb473206a2c780c706250f6*32*43f239ad53458a920d01393da38347e200000000000000000000000000000000*32*6a0549e56631c0b97b69723baca43b412f7ae6439a513d4906dfd11fa60a8afe
```
**the PDF file can be opened at will (no "user password", I believe) yet it is secured against modification ("owner password", I believe).**

the "hash examples" webpage does not help me detect which mode is more appropriate.
yet a bruteforce attack using mode 25400 **seems to find the solution**:
```
user@host:~$ ./hashcat.bin -a 3 -m 25400 -i "$HASH" "?a?a?a?a"
[...]
$pdf$2*3*128*-1324*1*16*6adf3addaeb473206a2c780c706250f6*32*43f239ad53458a920d01393da38347e200000000000000000000000000000000*32*6a0549e56631c0b97b69723baca43b412f7ae6439a513d4906dfd11fa60a8afe*:$HEX[592f6c2020202028757365722070617373776f72643d7e277a3a5c1a29192720706616356e6e29]
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 25400 (PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass)
Hash.Target......: $pdf$2*3*128*-1324*1*16*6adf3addaeb473206a2c780c706...a8afe*
[...]
```

on the other hand, attack mode 10500 exhausts all the possible passwords within the same attack space, in this case up to four `?a` characters.
I have tried the same steps multiple times and sometimes hashcat seems to crack the same hash with different solutions, even with different lengths.

anyway, this specific solution amounts to:
```
user@host:~$ echo 592f6c20202020287573657220706173737 | xxd -r -p
Y/l    (user password=~'z:\�)' pf5nn)
```
first of all, this seems to be providing a "user" password which is not actually needed, since anybody can open this PDF, but most importantly the "owner" password is definitely not `Y/l`.
furthermore, there seems to be a non-ASCII character in the reconstructed user password which, honestly, I wouldn't even know how to type into Acrobat Professional for modification.

other "cracked" passwords that this workflow produced, for the same hash, are:
```
user@host:~$ echo 6a5257362020202028757365722070617373776f72643d4f5c4473277e7a3d363b144f375a4a7929 | xxd -r -p
jRW6    (user password=O\Ds'~z=6;O7ZJy)
```
and again, the "owner" password is not `jRW6`.

so: how come hashcat thinks it is guessing the password?
how come by removing the pot file and retrying I am getting different results?
which mode is the appropriate mode for this type of solution?
I have tried using Acrobat Professional to create a brand new PDF file with no user password but with an owner password, e.g. 123456, and hashcat failed to crack it using attack mode 10500 yet successfully cracked it using attack mode 25400.

any suggestions are appreciated.

**Comment by Chick3nman** [comment]
PDFs can have several different types of passwords, some of which loop in an encryption step and disallow opening the PDF at all(10500) and some which simply disallow editing the PDF or making other changes(25400). These modes do different things and therefore, the behavior of them not cracking the same hashes is expected. The algorithm in play here is also rather weak and due to how it works, it is prone to generating collisions that work mathematically but do not always represent the original password. This is common amongst several of our other specialist kernels like 9820 for example. The solution is to enable --keep-guessing and generate several outputs until one of them works in the adobe application. The original passwords is not the only password that can/will work to open the document, you simply need any string that the documents accepts and that also works mathematically. This sounds very similar to the issue here: https://github.com/hashcat/hashcat/issues/2067

I will see if there are some changes we can make to help with the collision rate but I suspect not. I do have a PR open that disables specialist kernels from being suggested by Autodetect for this very reason as they often come with complex usage requirements and understanding.

**Comment by piramiday** [comment]
thanks for the explanation, I will read through the post you linked.

unfortunately, though, the addition of the `--keep-guessing` parameter just makes the output unbearable, as it produces a gazillion of collisions. these are just a few:
```
< HASH - snip >:$HEX[5e522b4a312020202028757365722070617373776f72643d48564c6b7d1c462e2652541426213c4629]
< HASH - snip >:$HEX[72394c74622020202028757365722070617373776f72643d56371929]
< HASH - snip >:$HEX[694e5367732020202028757365722070617373776f72643d344a784f6e3c791839215f2943666b3329]
< HASH - snip >:9)F!t    (user password=" mv{53npL~s$L^B)
< HASH - snip >:v.*^_    (user password=?)O!!z,i%{#01R=-)
< HASH - snip >:$HEX[79373c6a6d2020202028757365722070617373776f72643d414877163419466839666c237157435d29]
< HASH - snip >:uPM!t    (user password=MYP5EkX!/gj3na\i)
< HASH - snip >:$HEX[78794663722020202028757365722070617373776f72643d6947386b6c481a59211f23243651644c29]
< HASH - snip >:$HEX[40523424652020202028757365722070617373776f72643d3c3060727245752d3a182c1b216c573b29]
< HASH - snip >:$HEX[51473d21742020202028757365722070617373776f72643d537718273026336a5d3c1e687d74186229]
< HASH - snip >:$HEX[2452255a4c2020202028757365722070617373776f72643d5951352d2e1e7a415d667636632d583329]
< HASH - snip >:$HEX[2d5e612f2a2020202028757365722070617373776f72643d471762494a5b2b294a4a754e754e3c6d29]
< HASH - snip >:$HEX[2f20516d622020202028757365722070617373776f72643d3073797d1a76632557372a3a476c415229]
< HASH - snip >:$HEX[7b7a23756d2020202028757365722070617373776f72643d79564341383d3b6d793f16642264473229]
< HASH - snip >:$HEX[27714c67732020202028757365722070617373776f72643d551b2e6b643a6339687a52215829]
< HASH - snip >:$HEX[733f7b5a4c2020202028757365722070617373776f72643d43253c49261f14226f4e50204120196929]
< HASH - snip >:$HEX[32447b57332020202028757365722070617373776f72643d4d1f54235535386b4a40295e7829356b29]
< HASH - snip >:q}K'd    (user password=QQMYfl;/ K^)
< HASH - snip >:$HEX[752c7c73792020202028757365722070617373776f72643d581d4b3b375b6535732e662739623f7729]
< HASH - snip >:$HEX[44512e3e392020202028757365722070617373776f72643d3c7967601e262e343d603c58674a372e29]
< HASH - snip >:$HEX[5075774a312020202028757365722070617373776f72643d7c233d7d166d581c571b557a246f3f6329]
< HASH - snip >:$HEX[2474635e5f2020202028757365722070617373776f72643d731a5e43444a51453674586a4c625f4e29]
< HASH - snip >:$HEX[557b302c2c2020202028757365722070617373776f72643d6a566027707b2e56162a3e252740177929]
< HASH - snip >:-;b)j    (user password=2mVyH|#_IQ^GS7_8)
< HASH - snip >:$HEX[2f7e3a3c6f2020202028757365722070617373776f72643d726a2617293b646d324c477e756b1a4e29]
< HASH - snip >:$HEX[2b746e58332020202028757365722070617373776f72643d1438633a3446501865357d295f2629]
< HASH - snip >:$HEX[3b40475c302020202028757365722070617373776f72643d4a51617b493f616b5d1a157b22454f1c29]
< HASH - snip >:"'`\0    (user password=n ws}w$-m=H=S|+J)
< HASH - snip >:$HEX[605c7557332020202028757365722070617373776f72643d2e5d3850697b1f20713b143b705b705429]
< HASH - snip >:$HEX[3a4d7459452020202028757365722070617373776f72643d7216695d4e77656b3476477d6e5a484a29]
< HASH - snip >:$HEX[5c4f6c4b552020202028757365722070617373776f72643d7224264f531a39523753312229587c2929]
< HASH - snip >:)3R=a    (user password=1z-+NpVxaoDC!WnJ)
< HASH - snip >:$HEX[3e71443d612020202028757365722070617373776f72643d7e32521e697b58762b15456e5e741c4429]
< HASH - snip >:$HEX[6127796b752020202028757365722070617373776f72643d5b24726a1b43565e4a2777717553296c29]
< HASH - snip >:$HEX[6a2d2f33372020202028757365722070617373776f72643d6e42732f714a75682d654d745468521e29]
< HASH - snip >:$HEX[746e7761312020202028757365722070617373776f72643d2624265e5131365c41325e1b792e5a1529]
< HASH - snip >:$HEX[7a68475d692020202028757365722070617373776f72643d50445b1b784164691a7d2236637b616829]
< HASH - snip >:S|=du    (user password="fNtF?^0'TT)
< HASH - snip >:$HEX[434e2465652020202028757365722070617373776f72643d6d234c4443433e47641e2e524e16513129]
< HASH - snip >:N_gms    (user password=v+ebH9-T,m[@3def)
< HASH - snip >:$HEX[4f344952442020202028757365722070617373776f72643d561a6443542e2b5f4f4d387e39494b4d29]
< HASH - snip >:-"$ps    (user password=^)
< HASH - snip >:$HEX[3c417e60692020202028757365722070617373776f72643d1e4e5a1e5050612f4d1a3e29]
< HASH - snip >:'&K`i    (user password=e&AK6U&"fD29XFLx)
< HASH - snip >:$HEX[3e436574722020202028757365722070617373776f72643d453a264b4e1c193e2553447549464e1f29]
< HASH - snip >:$HEX[737a4052442020202028757365722070617373776f72643d3778353a582c4f1627266b1e585f267c29]
< HASH - snip >:$HEX[30716b39342020202028757365722070617373776f72643d1d3814576d782345567368602d18731a29]
< HASH - snip >:$HEX[70665070732020202028757365722070617373776f72643d392f55536a441c524b5467471e55792f29]
< HASH - snip >:$HEX[6b3a7b39342020202028757365722070617373776f72643d1c453d262e621f3c307960705c20514d29]
< HASH - snip >:4#;NK    (user password=^l9 HJLutAgm|fVN)
< HASH - snip >:$HEX[3539214e4b2020202028757365722070617373776f72643d433523377373704e1b73176a4c72227e29]
< HASH - snip >:$HEX[375a5c24302020202028757365722070617373776f72643d53416358612f4b56362d591b745d143a29]
< HASH - snip >:$HEX[7a257367792020202028757365722070617373776f72643d215879435419706179176a42573c694429]
< HASH - snip >:$HEX[50296774722020202028757365722070617373776f72643d4e4e5178482c62451a4f55785f4c751829]
< HASH - snip >:$HEX[4b4e2d2b642020202028757365722070617373776f72643d5c1529]
< HASH - snip >:$HEX[594b4e69722020202028757365722070617373776f72643d6a1c3f516a6d526647431a435129511f29]
< HASH - snip >:$HEX[40743f62682020202028757365722070617373776f72643d1a486c551745796219446e364c79745129]
< HASH - snip >:$HEX[24297934362020202028757365722070617373776f72643d27384e4425141b6d754e656f40781a5829]
< HASH - snip >:$HEX[22615f36342020202028757365722070617373776f72643d2e723a6f491c546236621f541e54304029]
< HASH - snip >:$HEX[6c7940296c2020202028757365722070617373776f72643d3b35312f24711f6a4f1f261b25232f7429]
< HASH - snip >:$HEX[37213948322020202028757365722070617373776f72643d3e3f1d2b5f2c20773d6c7e5e59491f4f29]
< HASH - snip >:SD|IR    (user password=,.-&NsB=[I%^b~l1)
< HASH - snip >:L;5KM    (user password=-L{ImnkR/xzT-$A`)
< HASH - snip >:Tk!S1    (user password=xYdeE!.!)
< HASH - snip >:$HEX[4728663b732020202028757365722070617373776f72643d1a7c783776495d40475a4160213b313f29]
< HASH - snip >:$HEX[495b435f722020202028757365722070617373776f72643d147c44672a29]
< HASH - snip >:VJ1_r    (user password=K]fVCVXp}@p\\HYw)
< HASH - snip >:ZlSdu    (user password=u]T9)
< HASH - snip >:$HEX[243e3057422020202028757365722070617373776f72643d4d275a6e19373f484277183d3877411729]
< HASH - snip >:$HEX[2e61712a732020202028757365722070617373776f72643d70632f36386a482e381833554b201e3829]
< HASH - snip >:$HEX[7d503252442020202028757365722070617373776f72643d626c46524b1d3a74481614607250166329]
< HASH - snip >:$HEX[31607d59302020202028757365722070617373776f72643d243d7b3418723138783a316e2554324129]
< HASH - snip >:$HEX[7058713f622020202028757365722070617373776f72643d317a5544271e34206a147d611419246629]
< HASH - snip >:$HEX[6a2972276f2020202028757365722070617373776f72643d3e44553d182621616f2e69534e71221629]
< HASH - snip >:$HEX[3842256d742020202028757365722070617373776f72643d3241603b17246d3d6b3765692436366429]
< HASH - snip >:$HEX[71797978342020202028757365722070617373776f72643d3a316824377e361a66624240452b351e29]
< HASH - snip >:$HEX[447e4e57692020202028757365722070617373776f72643d3c3155421a267368196a7a5b2f5d241629]
< HASH - snip >:E{;TN    (user password=bb^1#>DD@q^[#Vm[)
< HASH - snip >:$HEX[56324965762020202028757365722070617373776f72643d63416467635f422f473a4e3362586929]
< HASH - snip >:$HEX[2373596f652020202028757365722070617373776f72643d666c4b5278223e49314c6f723a412e2d29]
< HASH - snip >:@e=9b    (user password=x4Fw; s+/Jh0B,n-)
< HASH - snip >:Q{i*6    (user password=P1!bnk'@~J)O?y56)
< HASH - snip >:$HEX[262f61376c2020202028757365722070617373776f72643d574a3e357b5d2b404464661466267d4329]
< HASH - snip >:$HEX[5e596670622020202028757365722070617373776f72643d5d192577445477361a5e525e3933407229]
< HASH - snip >:{b9.f    (user password=zGL,2yBxEgg,p<pg)
< HASH - snip >:$HEX[27316241472020202028757365722070617373776f72643d1c4918706c3f1b6966377025356b581829]
< HASH - snip >:$HEX[20322b42322020202028757365722070617373776f72643d7677333b7d3f1a2f2c1e43597847671729]
< HASH - snip >:$HEX[6a567d43302020202028757365722070617373776f72643d272714256b39706d686d694e5b36216329]
< HASH - snip >:$HEX[64233b216d2020202028757365722070617373776f72643d6f471918702456677a2f403a5175485c29]
< HASH - snip >:$HEX[663549286b2020202028757365722070617373776f72643d364b777e747443794e4c2c29152f7c2e29]
< HASH - snip >:$HEX[39693b4d652020202028757365722070617373776f72643d7022692250561b58764e76453d25745f29]
< HASH - snip >:$HEX[7a603f76332020202028757365722070617373776f72643d5d741f725549722e65384b2c3b7d655129]
< HASH - snip >:$HEX[46264e6a732020202028757365722070617373776f72643d557d69457e607c652a362556595a511529]
< HASH - snip >:$HEX[49224f65762020202028757365722070617373776f72643d75623950354f3a1c6f4a33394e32205a29]
< HASH - snip >:$HEX[4f705379722020202028757365722070617373776f72643d175e71623a2d275f7675403a5b4e535129]
< HASH - snip >:$HEX[2e66644e302020202028757365722070617373776f72643d6e3c4d257e576d6b3b1f56416c274b6729]
< HASH - snip >:UAj]k    (user password=5-G)
< HASH - snip >:$HEX[3d4325486f2020202028757365722070617373776f72643d3a407e407b73241f592c44795e401d5829]
< HASH - snip >:%9kIB    (user password=y`&&uDRfl7}&<xA~)
< HASH - snip >:$HEX[3e5d364f552020202028757365722070617373776f72643d651d1e78203350725a603e6f1824525d29]
< HASH - snip >:$HEX[6c6b353f302020202028757365722070617373776f72643d47512e2e47276a2a206a391929]
< HASH - snip >:$HEX[6e7c225f6a2020202028757365722070617373776f72643d1d674e2c4a2677145637434d5b57313929]
< HASH - snip >:$HEX[415f3429642020202028757365722070617373776f72643d17596e5c4b38226f493f6a7961165a1d29]
< HASH - snip >:$HEX[57652247302020202028757365722070617373776f72643d19327a3a6b3619181b334a1d35632a3629]
< HASH - snip >:*&C?0    (user password=Mu'c% C*/E#RCH4E)
< HASH - snip >:$HEX[51252f60662020202028757365722070617373776f72643d62446163207c195f3c6a584a25462e1829]
< HASH - snip >:$HEX[2f494920302020202028757365722070617373776f72643d734962571a63604f726d50492072651629]
< HASH - snip >:$HEX[2b6e435c6f2020202028757365722070617373776f72643d311e63556134332a3d19246d3b57235429]
< HASH - snip >:$HEX[3d212e3e212020202028757365722070617373776f72643d5614454644697354672d7849242a2f1729]
< HASH - snip >:$HEX[7c2f4160662020202028757365722070617373776f72643d7c1a6955262f7c4f7e3748233155187729]
< HASH - snip >:$HEX[6d513961322020202028757365722070617373776f72643d5763236d1b244b6253432e4c4446146c29]
< HASH - snip >:$HEX[747e5e676e2020202028757365722070617373776f72643d20424e6b671b7667215c5e254f5b4a7d29]
< HASH - snip >:$HEX[6835676d6e2020202028757365722070617373776f72643d466931754e32237e30701d7d5569222729]
< HASH - snip >:$HEX[6762266d6e2020202028757365722070617373776f72643d427e4751196b7d3d2c7470307b21572629]
< HASH - snip >:$HEX[394d7473302020202028757365722070617373776f72643d1f527e203e1f571b7c5f30226216697729]
< HASH - snip >:$HEX[6f237270302020202028757365722070617373776f72643d41311e755f4d62143d24611a31796f29]
< HASH - snip >:$HEX[532d2273302020202028757365722070617373776f72643d74433a6e30632d732a521e394e5a731629]
< HASH - snip >:H"2|S    (user password=SDu5|@'[;=7,,M8')
< HASH - snip >:*sMCo    (user password=u1d9@^1o?R^1-/w.)
< HASH - snip >:$HEX[5637656a6e2020202028757365722070617373776f72643d2022655520717b4d241e276e1d6c7a5f29]
< HASH - snip >:$HEX[5e2a47495a2020202028757365722070617373776f72643d3f41222c784561242a6b322f1d29]
< HASH - snip >:$HEX[31784733622020202028757365722070617373776f72643d7c78767116413e5355355d756449425329]
< HASH - snip >:$HEX[70234162662020202028757365722070617373776f72643d276618525d534d3c603f22262b39353d29]
< HASH - snip >:$HEX[6c5a3b2f642020202028757365722070617373776f72643d2f2352353c222c4b5e3a57744218691429]
< HASH - snip >:$HEX[723b7163622020202028757365722070617373776f72643d573c344a2d625a2d433c194c57377a2129]
< HASH - snip >:$HEX[6953414a4c2020202028757365722070617373776f72643d4a333f3e24762a4d62747a301f157b2d29]
< HASH - snip >:$HEX[35287036642020202028757365722070617373776f72643d31491a6769236e367637162e364f631e29]
< HASH - snip >:89TFi    (user password=I5PvvxaehV~tK=mz)
< HASH - snip >:$HEX[4d436735622020202028757365722070617373776f72643d4a22476d43527b1d4b42295a276f154729]
< HASH - snip >:$HEX[49556f42692020202028757365722070617373776f72643d262b3872512170443c6e5d1955653a6129]
< HASH - snip >:$HEX[577b666b702020202028757365722070617373776f72643d5b67634e274e1d7c27634c4c2a45161529]
< HASH - snip >:$HEX[247c7b5b302020202028757365722070617373776f72643d1b7378432019222e3032574c6869341829]
< HASH - snip >:$HEX[3f257839742020202028757365722070617373776f72643d58594b6555347e1d2d512d6c3846514429]
< HASH - snip >:$HEX[253e2c6e6d2020202028757365722070617373776f72643d604d1b68713d1f56432929]
< HASH - snip >:$HEX[5d4e2d70302020202028757365722070617373776f72643d61416b7b4f32484966341e346c6d2b5c29]
< HASH - snip >:$HEX[7c567340342020202028757365722070617373776f72643d6b2d664753464455154318507122783129]
< HASH - snip >:$HEX[733b345f682020202028757365722070617373776f72643d233c6d655b1b3a2b54782d3629]
< HASH - snip >:18]Bi    (user password=`j/8_%XP4{>S3@o{)
< HASH - snip >:$HEX[622843766c2020202028757365722070617373776f72643d78264b6c4720681c1b2747147449325229]
< HASH - snip >:$HEX[6c725c415a2020202028757365722070617373776f72643d582a32651d1a6b4742563f234041436829]
< HASH - snip >:$HEX[64582f53302020202028757365722070617373776f72643d4d724a36586a3366346e1c746d6b515029]
< HASH - snip >:$HEX[6e57463b682020202028757365722070617373776f72643d6f351432317914326f3f23501d30512029]
< HASH - snip >:$HEX[4d697621642020202028757365722070617373776f72643d7e5170701e6937653e46671d7a7a217929]
< HASH - snip >:$HEX[7a444768632020202028757365722070617373776f72643d56721751785e1b304b72194d426c606c29]
< HASH - snip >:$HEX[7169622b6e2020202028757365722070617373776f72643d2d277c7b333e553a722b6a6748762f4429]
< HASH - snip >:$HEX[54234054322020202028757365722070617373776f72643d67307a7a2e144345341f79614859204f29]
< HASH - snip >:$HEX[562d653d332020202028757365722070617373776f72643d256e394f5a596c1c443029]
< HASH - snip >:$HEX[4f353d21642020202028757365722070617373776f72643d7b5d2d452a3536196d442a6c756a634329]
< HASH - snip >:$HEX[7e395168632020202028757365722070617373776f72643d76541729]
< HASH - snip >:$HEX[3a7c522d652020202028757365722070617373776f72643d654764176b391b342c7a1b4258576b3729]
```

I understand one cannot inform hashcat if not with more data with respect to this, but is there any way, e.g., to specify that hashcat is supposed to be looking for an "owner" password, while the "user" password is blank?
otherwise, this seems a tough problem.

**Comment by Chick3nman** [comment]
I may not fully understand the issue. Do none of those passwords work? If I understand the format correctly, the Owner/User passwords cracked with hashcat should work, and the fact that one is not needed is incidental since they are collisions. Perhaps Owner/User terminology is being confused here? See here: https://github.com/hashcat/hashcat/blob/540c0dde81b0524376f89af20b7c4f137147fc44/tools/pdf_tests/_README.txt

```
The user-password (to open the file is): user
The owner-password (to e.g. restrict printing is): owner

We have files with and without the "_userpw-in-hash" prefix,
this is to accommodate tests for 25400, which needs the user-password
to calculate the o-value. The user-password is used when no owner-password is set.
```

If there is no user-password set, I believe there are still collisions produced for the default key value, which is what you are seeing. 

See also: https://github.com/hashcat/hashcat/blob/540c0dde81b0524376f89af20b7c4f137147fc44/src/modules/module_25400.c#L338

```
  // we don't use the user-password in the attack now (as we don't need it),
  //  however we could use it in the comparison of the decrypted o-value,
  //  yet it may make this attack a bit more fragile, as now we just check for ASCII
```

We aren't currently doing anything with the User password if it is already known, because it doesn't appear that we need to, but perhaps it would cut down a little on the collision rate. Are you just trying to go after the more "real" password collisions based on knowing the user password? Because the passwords hashcat is giving you should work, even though they are not the "real" password and verifying that the password hashcat gives you is the "real" one, even by cutting down the rates with a known User password, would still be problematic given the collision rate.

**Comment by piramiday** [comment]
I am sure you understand the issue fully, whereas I am still a little confused by it.

in this specific case I manually tried a bunch of the "collided" owner passwords to modify the edit restrictions of the PDF, of course skipping the HEX results and focusing on those composed of ASCII characters, with no success as each time Adobe yielded the "password is incorrect" error message.
is there maybe a way to programmatically try each of the collisions for success?

I understand that mathematically they _behave_ like the true correct password, but I guess they are not and Adobe knows it.

**Comment by Chick3nman** [comment]
Update to the above, the test used to determine validity of the password is indeed a little weak and could be updated for mode 25400. This would potentially reduce false positives.

**Comment by ElDavoo** [comment]
> is there maybe a way to programmatically try each of the collisions for success?

i guess you can create a quick hack trying them with qpdf . Better if you know the user password, you can easily filter.

**Comment by daanyaal25** [comment]
Hi Guys,

I've read your posts and encountered the same issue with my encrypted PDF. The encryption version lies between 1.4 and 1.7 (based on Hashcat). I’ve tried various modes like PDF 11, PDF 7, and PDF 9, but none of them worked—they fail to load the hash. I can confirm that only two modes are applicable here: 10500 and 25400.

I tried both. With mode 10500, using my fast computer, I tested combinations up to 6 characters, which took about an hour. Unfortunately, the password isn't within the 1–6 character range. Cracking gets exponentially harder as the character count increases.

For mode 25400, Hashcat explicitly states that it works only if both user and owner passwords are set. On the other hand, mode 10500 is for PDFs with either a user or an owner password. I’ve attempted both modes, but the results were identical to what @piramiday mentioned in their post. I also converted the hexadecimal to plain text but only got gibberish.

One thing I noticed about mode 25400 is that when I test all combinations from 1 to 3 characters, it returns "Exhausted." However, testing from 4 characters onward, it provides a random hexadecimal number as a guess and claims success.

I used ExifTool to extract verbose information from the PDF and tried various tools like Hashcat (as mentioned by @piramiday) and John the Ripper. I even attempted brute-force attacks with other tools, but decrypting the PDF's original content still seems impossible.

Here’s the hash of the PDF file:
$pdf$4*4*128*-1852*0*16*993747baa0ff70dd966bbb55aa44a0df*32*c9171fd9d58f6f843211d4848d5cf37500000000000000000000000000000000*32*21025c3b498ea1cdd404b0ee86682e3148cd16b5c88dc241317b2aade7e03b49

Passwords tried:

Length 4: $HEX[523845452020202028757365722070617373776f72643d4924653c2b30667368642e1a4c6c3b29]
Length 5: $HEX[6f6428284c2020202028757365722070617373776f72643d7625533215616a4f2a4432603729634a29]
Length 6: $HEX[40387b7d3a2f2020202028757365722070617373776f72643d3c3d17441a627d711b745d1f2527532129]
Length 7: n~ueran (user password=mDx1P7\'g+*'-niO)
Length 8: $HEX[6c43636b6572696e2020202028757365722070617373776f72643d14734d68152720423929]


Despite gathering all this information and testing extensively, I haven’t been able to decrypt the original content of the PDF.!!

**Comment by NeuralSpectra** [comment]
Hi Guys,

I've read your posts and encountered the same issue with my encrypted PDF. The encryption version lies between 1.4 and 1.7 (based on Hashcat). I’ve tried various modes like PDF 11, PDF 7, and PDF 9, but none of them worked—they fail to load the hash. I can confirm that only two modes are applicable here: 10500 and 25400.

I tried both. With mode 10500, using my fast computer, I tested combinations up to 6 characters, which took about an hour. Unfortunately, the password isn't within the 1–6 character range. Cracking gets exponentially harder as the character count increases.

For mode 25400, Hashcat explicitly states that it works only if both user and owner passwords are set. On the other hand, mode 10500 is for PDFs with either a user or an owner password. I’ve attempted both modes, but the results were identical to what @piramiday mentioned in their post. I also converted the hexadecimal to plain text but only got gibberish.

One thing I noticed about mode 25400 is that when I test all combinations from 1 to 3 characters, it returns "Exhausted." However, testing from 4 characters onward, it provides a random hexadecimal number as a guess and claims success.

I used ExifTool to extract verbose information from the PDF and tried various tools like Hashcat (as mentioned by @piramiday) and John the Ripper. I even attempted brute-force attacks with other tools, but decrypting the PDF's original content still seems impossible.

Here’s the hash of the PDF file:
$pdf$4*4*128*-1852*0*16*993747baa0ff70dd966bbb55aa44a0df*32*c9171fd9d58f6f843211d4848d5cf37500000000000000000000000000000000*32*21025c3b498ea1cdd404b0ee86682e3148cd16b5c88dc241317b2aade7e03b49

Passwords tried:

Length 4: $HEX[523845452020202028757365722070617373776f72643d4924653c2b30667368642e1a4c6c3b29]
Length 5: $HEX[6f6428284c2020202028757365722070617373776f72643d7625533215616a4f2a4432603729634a29]
Length 6: $HEX[40387b7d3a2f2020202028757365722070617373776f72643d3c3d17441a627d711b745d1f2527532129]
Length 7: n~ueran (user password=mDx1P7'g+*'-niO)
Length 8: $HEX[6c43636b6572696e2020202028757365722070617373776f72643d14734d68152720423929]

|-------------------------------------------------------------------------------------------------------------------------------------------|

Here is a Possibles Solution for your issue:

Run the following Hashcat command:

hashcat -a 3 hash.txt --increment --increment-min=6 --increment-max=6 ?a?a?a?a?a?a

On Linux, you can omit the -m argument (which specifies the hash mode). Hashcat will attempt to auto-detect the mode and suggest the best option for your hash.

For example, in my case, the output was:

Hash-mode was not specified with -m. Attempting to auto-detect hash mode.

The following mode was auto-detected as the only one matching your input hash:

10500 | PDF 1.4 - 1.6 (Acrobat 5 - 8) | Document

This output indicates that Hashcat detected the most appropriate mode for your hash. You can use this information to confirm whether mode 10500 or 25400 is correct for your specific hash.


Despite gathering all this information and conducting extensive testing, I have not been able to decrypt the original content of the PDF.!!
