### ISSUE TITLE
explicit feedback when invalid hash modes are requested

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3185]
Today, if an invalid hash mode is requested, this error is produced:
```
$ hashcat -b -m 31337 --quiet
/usr/local/share/hashcat/modules/module_31337.so: cannot open shared object file: No such file or directory
```
For new users, it may be (briefly) unclear whether this is because of some other kind of hashcat error.

Instead, something like the following might be better:
```
Hash mode 31337 is not a valid hash mode.
```
It might also be useful if someone is following an old tutorial and requests a hash mode that _used_ to be in hashcat, but is now only in hashcat_legacy. If so, it might be useful to provide explicit separate feedback for [such modes](https://hashcat.net/wiki/doku.php?id=example_hashes#legacy_hash_types), maybe something like:
```
Hash mode 3300 is not supported by this version of hashcat, but is supported by
hashcat_legacy: https://github.com/hashcat/hashcat-legacy/
```

**Comment by Chick3nman** [comment]
While i see what you are saying, `Hash mode 31337 is not a valid hash mode.` doesn't quite make sense. The original error is actually the most correct error because hashcat supports drop-in plugins/kernels/modules. The only thing wrong at that step is that it doesn't see the file so perhaps you've put it in the wrong place. That said, I think we can add something to it to explain to users who aren't dropping a plugin into the folder what's going on. 

Maybe something along the lines of 

```
/usr/local/share/hashcat/modules/module_31337.so: cannot open shared object file: No such file or directory

INFO: The hash mode specified either does not exist in the official repository or the file(s) could not be found. 
Please check that the hash mode number is correct and that the files are in the correct place.

```

On the second point, given that hashcat now uses a modular plugin system, I do not believe we could properly do the legacy call out since a new valid module could occupy that number and be present.

**Comment by roycewilliams** [comment]
Fair to both points, though I'd argue that if someone is working with custom modules, they're not the demographic that would be confused by the current feedback. :D 

Proposed slight rewording and rewrap:
```
INFO: Either the specified hash mode does not exist in the official repository,
or the file(s) could not be found. Please check that the hash mode number is 
correct and that the files are in the correct place.
```

**Comment by Chick3nman** [comment]
Yeah, was going to check the wrapping we do with the ATTENTION! set of messages before pushing. Let me see how hard it is to catch that file error, we may be ditching on a generic status return during startup so I may need to setup a flow to catch it so it can present the message only for certain file not found errors and not unrelated ones.

**Comment by Chick3nman** [comment]
~~Update: It appears we already have code for handling this, but for some reason that code is not running. Seems like something else is racing it and the errors you are seeing cause the relevant message code not to be reached.~~

~~See here: https://github.com/hashcat/hashcat/blob/master/src/user_options.c#L2932~~

Edit: Ignore previous, misunderstood what that code block was for. We would need to add new code for this elsewhere.

**Comment by jsteube** [comment]
This sounds useful. Do we want to report this of type info, warning or error. The first one will not have a color, the warning is in yellow and the error is in red.

And in addition, should we keep presenting that error?

```
/usr/local/share/hashcat/modules/module_31337.so: cannot open shared object file: No such file or directory
```

**Comment by Chick3nman** [comment]
I think we do want to add a warning(yellow) to this but also keep the root error as well. Tycho made a pretty decent one above, though if you have other thoughts then feel free to reword it.

**Comment by roycewilliams** [comment]
Actually, I think showing the raw error only makes sense if it was missing for some reason *other* than it being an invalid hash mode. Otherwise, naive users may still think that this is a hashcat problem.

In my opinion, the desired behavior should be:

* Treat an invalid hash mode as a command line sanity checking problem and exit very early if an invalid hash mode is requested

* Continue to throw the missing file error only if a valid hash mode is requested, but for some unusual reason, the corresponding file is missing from disk

Put another way: If the user asks for an invalid mode, there is no reason to check whether or not the file is on disk. We already know that it is not - and performing that check anyway is potentially diagnostically confusing to the uninitiated user.

**Comment by roycewilliams** [comment]
In an aside, chick3nman reminds me that there is no list of "stock" modules within hashcat itself - very modular, though I'll make an argument elsewhere why that might be useful (#3252), it wouldn't address this issue. Instead, maybe expanded language like this:

```
Module for the specified hash type '99999' could not be loaded.
Invalid hash mode (check your syntax) or file access problem.
```

**Comment by jsteube** [comment]
OK check with current version if that's fine or if you want to modify something

**Comment by roycewilliams** [comment]
Looks great!
