### ISSUE TITLE
oclHashcat hangs at startup

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#319]
So on a clean install of Ubuntu 16.04 (with hashcat deps installed) OclHashcat compares the hashlist to the pot file, detects the GPUs and then hangs, it does not show the status menu or give any indication that hashes are being cracked. I can however do a bench mark and that runs as expected, so I don't think it's a driver issue. I tested it with modes 1000 1100 and 0 all hung at crack time.

**Comment by jsteube** [comment]
What hashcat deps are you talking about? There should be none left with latest version, see here: https://github.com/hashcat/oclHashcat/blob/master/docs/BUILD.md

Anyway about your issue, this sounds like some local installation error or broken hardware. Please try again with our precompiled betas to be sure it's not a compilation (and depency) error on your host. You can find them on hashcat.net/beta

**Comment by thesle3p** [comment]
I ran tools/deps.sh, and I think you may be right as the beta version does not work either, weird that the benchmark still works.

-----Original Message-----

**Comment by jsteube** [comment]
There's no such file anymore since a long time. I think you're also using an outdated github version

**Comment by thesle3p** [comment]
I just did a clean install of Ubuntu 16.04, the nvidia driver 361.42 and 

```
git clone https://github.com/hashcat/oclHashcat.git

sudo apt-get install nvidia-opencl-dev

cd oclHashcat/
make 
```

followed by 

```
./example0.sh
```

which results in the following to hang indefinitely regardless of whether or not it's ran as root 

```
./example0.sh 
oclHashcat v2.01 (g1e3d843) starting...

Device #1: GeForce GTX 980 Ti, 1535/6143 MB allocatable, 1190Mhz, 22MCU
Device #2: GeForce GTX 980 Ti, 1535/6143 MB allocatable, 1190Mhz, 22MCU
```

I am able to do a full benchmark no problem it's only when I try and actually crack hashes this happens.

**Comment by jsteube** [comment]
Does example400.sh work?

**Comment by thesle3p** [comment]
Same issue, as well as with 500

-----Original Message-----

**Comment by jsteube** [comment]
>  just did a clean install of Ubuntu 16.04, the nvidia driver 361.42 and

I'm using the same setup and it works pretty good. I'm however using the .bin from Nvidia site and not the driver that comes with Ubuntu. There's a small chance that this creates problems.

> sudo apt-get install nvidia-opencl-dev

I'm using the original one from Khronos but I don't think it will make any difference. But it's worth a try so purge nvidia-opencl-dev and add:

ocl-icd-dev
ocl-icd-opencl-dev
opencl-headers
ocl-icd-libopencl1

> Same issue as well as with 500

So you're propably having problems with _a0 kernels. Does -a 3 work?

Also try this:

rm -rf ~/.nv

and in oclHashcat directory:

rm -rf kernels

**Comment by thesle3p** [comment]
Switched to the Khronos package and nuked ~/.nv ~/.hashcat.kernels and ~/oclHashcat/Kernels and still persists with -a3 and -a0, I'm about to try switching to the Nvidia .bin driver. Weird benchmarks work just fine.

**Comment by thesle3p** [comment]
Which version of the binary driver are you using by the way?

**Comment by jsteube** [comment]
NVIDIA-Linux-x86_64-361.18.run

Maybe try -d 1 too

**Comment by thesle3p** [comment]
-d 1 is the same issue but it skips the second device, will try installing the .run driver and go from there.

**Comment by thesle3p** [comment]
Binary driver fixed it :) It's support like this that makes Hashcat My favorite tool to use the development version of.

-----Original Message-----

**Comment by jsteube** [comment]
Thanks :)
