### ISSUE TITLE
incorrect negative values in status prompt due to signed ints and %d usage

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#3199]
While I've investigated the problem reported in #3144 a little bit, I've found this problem of negative values in the status prompts in case a value (for actually different types of variables) was larger than `((0xffffffff + 1) / 2)` = 0x80000000 (2147483648). This is exactly the limit/threshold when a signed (positive OR negative) integer will "overflow".

You can reproduce this with e.g. -a 1 dicts that have more than 2147483648 words/lines (much more is easier to see, but also note that #3144 mentions another bug where the amount of lines should be less than or equal to 0xffffffff = 4294967295 otherwise `hashcat` currently triggers another bug):
`hashcat -a 1 hash.txt dict1.txt dict2.txt`

In different runs I've seen outputs like this:
```Restore.Sub.#1...: Salt:0 Amplifier:-256--1 Iteration:0-256```
```Restore.Sub.#1...: Salt:0 Amplifier:-1927007488--1927007296 Iteration:0-256```
```Restore.Sub.#1...: Salt:0 Amplifier:-743027456--743027296 Iteration:0-256 ```

Note the "Amplifier:-" and the '--" in the `Restore.Sub` line.

Unfortunately, there are multiple usage of "%d" instead of "%u" and `int` types instead of `u32` in the hashcat source files (e.g. `src/terminal.c and `src/status.c` and probably other files too, an instance of this is for example: https://github.com/hashcat/hashcat/blob/5df0adc1130a693bb39ff65005d423d2ce9a1131/src/terminal.c#L2337).

I suggest that we carefully review the code and try to use both "%u" and "u32" wherever applicable and possible.

note: using `u32` doesn't seem to be enough, in that case we would need both `u32` **AND** `%u`

instances of signed "int" are this:
```
device_info->innerloop_pos_dev
device_info->innerloop_left_dev
```
see https://github.com/hashcat/hashcat/blob/5df0adc1130a693bb39ff65005d423d2ce9a1131/include/types.h#L2585-L2586

but of course, as said, these might not be the only ones. There could also be problems with other status lines (not only `Restore.Sub`) and also other instances in the same lines in code e.g. the `Restore.Sub` `Iteration` value).

Please confirm, review and suggest a patch.

Thx

**Comment by davidbolvansky** [comment]
@philsmd we need similar fix for hash_info_single_json. Could you port fixes from hash_info_single to hash_info_single_json as well?

**Comment by davidbolvansky** [comment]
> @philsmd we need similar fix for hash_info_single_json. Could you port fixes from hash_info_single to hash_info_single_json as well?

ok, posted https://github.com/hashcat/hashcat/pull/3244
