### ISSUE TITLE
support for OPENCART hashes

### ISSUE THREAD

**Issue by 828** [hashcat/hashcat#32]
Hello.

Would it be possible to add sha1(salt.sha1(salt.sha1(pass))) into oclHashcat?
Hash algorithm for a very popular CMS (OPENCART)

sha1(salt.sha1(salt.sha1(pass)))

Hash:salt:pass
9c59d3071ee8a6486cf12d54d339f3b783ce2dde:0ccc3a77c:admin
d4d05b388a87e3055cc0ee109801cdca15e8d6d4:dbe8c88e5:taty
fabaff2487d3fc85b0fec32af618f5e8dc19b905:1dab633e0:admin

Download OpenCart
http://www.opencart.com/index.php?route=download/download

**Comment by jsteube** [comment]
Added to hashcat v3.10 thanks to @hops
