### ISSUE TITLE
convert  from Bettercap pcap file to hashcat format

### ISSUE THREAD

**Issue by slavadba** [hashcat/hashcat#3207]
HI, 
I have pcap file from Bettercap - but I cant convert  it to hashcat format.

# bettercap -version    
bettercap v2.32.0 (built for linux amd64 with go1.15.15)
                                                                                                                                                            
┌──(root💀kali)-[~]
└─# 
# hcxpcapngtool -o wpa_from_bettercap wpa.pcap
hcxpcapngtool 6.2.5-26-gb98b7ba reading from wpa.pcap...

summary capture file
--------------------
file name................................: wpa.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 05.03.2022 18:25:39
timestamp maximum (GMT)..................: 05.03.2022 18:25:39
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 4
frames with correct FCS..................: 4
packets received on 2.4 GHz..............: 4
EAPOL messages (total)...................: 4
EAPOL RSN messages.......................: 4
EAPOLTIME gap (measured maximum usec)....: 2955
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 2

Information: no hashes written to hash files

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.

session summary
---------------
processed cap files...................: 1

                                                                                                                                                            
┌──(root💀kali)-[~/DISTR/hcxdumptool]
└─#

Are there any ways to do this?

**Comment by matrix** [comment]
@slavadba I don't see any "hcxpcapngtool" tool inside hashcat
