### ISSUE TITLE
feature: include source wordlist in debugging format

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3209]
**Describe the feature**
It would sometimes be useful if the source wordlist was available in the rules debugging output.

The format specification might look like this:

`  5 | Source-Wordlist:Original-Word:Finding-Rule:Processed-Word`

Example output might be:

`/path/to/rockyou.txt:sourceword:$1:sourceword1`

If the input was stdin, something like this notation could be used:

`<stdin>:sourceword:$1:sourceword1`

This would make the debug output take up much more space, but it might sometimes be worth the trade-off.

**Comment by Shooter3k** [comment]
I LOVE this idea....but I recommend it's added to the debugging output at the end as to not break anything currently exists

- [ Rule Debugging Modes ] -

  # | Format
 ===+========
  1 | Finding-Rule
  2 | Original-Word
  3 | Original-Word:Finding-Rule
  4 | Original-Word:Finding-Rule:Processed-Word
  5 | Original-Word:Finding-Rule:Processed-Word:Wordlist

**Comment by matrix** [comment]
```
$ ./hashcat --help
[...]
- [ Rule Debugging Modes ] -

  # | Format
 ===+========
  1 | Finding-Rule
  2 | Original-Word
  3 | Original-Word:Finding-Rule
  4 | Original-Word:Finding-Rule:Processed-Word
  5 | Original-Word:Finding-Rule:Processed-Word:Wordlist
[...]
```
