### ISSUE TITLE
-k does not function with -a 7

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#3211]
Rules applied to -a 7 with -k do not appear to function currently. This seems like an oversight or other gap in the code. This issue was split from another issue.

**Comment by philsmd** [comment]
need to try to reproduce this myself. Is it the case that only `-k` does not work, but `-j` does ?

**Comment by jsteube** [comment]
Also this: https://github.com/hashcat/hashcat/commit/2e00ddb3961ad0972ede377d51fee7b5ca9e8010
