### ISSUE TITLE
sha1(sha1($salt.$pass.$salt))

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#322]
Can someone add this specific hash type?

sha1(sha1($salt.$pass.$salt))

Thanks a lot!

**Comment by trounce1** [comment]
@ghost I can implement this very quickly if you still want it?

**Comment by trounce1** [comment]
i have implemented this algo in https://github.com/hashcat/hashcat/pull/2594

**Comment by trounce1** [comment]
here is sample python code for this algo

```python3
from binascii import hexlify
from hashlib import sha1

password = b'hashcat'
salt = b'232725102020'

sth = salt + password + salt

r1 = hexlify(sha1(sth).digest())

r2 = sha1(r1).digest()

print(hexlify(r2))
```

it can be run here https://repl.it/repls/StunningUnripeElement

**Comment by jsteube** [comment]
Support merged into master, thanks @trounce1 for the contribution.
