### ISSUE TITLE
hashcat --benchmark is not working on macOS due to OpenCL files not being found

### ISSUE THREAD

**Issue by 0xDedSec42** [hashcat/hashcat#3221]
**Describe the bug**
After building from source (v6.2.5-326-g8bc4a9208) I get this error for every hash type when running benchmark mode:

```
clCompileProgram(): CL_BUILD_PROGRAM_FAILURE

<program source>:7:10: fatal error: '/Users/ulf/Downloads/hashcat/OpenCL/inc_vendor.h' file not found
#include M2S(INCLUDE_PATH/inc_vendor.h)
         ^
<built-in>:34:16: note: expanded from macro 'M2S'
#define M2S(x) XM2S(x)
               ^
<built-in>:37:17: note: expanded from macro 'XM2S'
#define XM2S(x) #x
                ^
<scratch space>:2:1: note: expanded from macro '#'
"/Users/ulf/Downloads/hashcat/OpenCL/inc_vendor.h"
^

* Device #2: Kernel /Users/ulf/Downloads/hashcat/OpenCL/shared.cl build failed.
```
But the file is there:
```
❯ file /Users/ulf/Downloads/hashcat/OpenCL/inc_vendor.h
/Users/ulf/Downloads/hashcat/OpenCL/inc_vendor.h: c program text, ASCII text
````

**To Reproduce**
Build hashcat from source (v6.2.5-326-g8bc4a9208) on macOS by doing git clone; make, then run ./hashcat --benchmark.

**Expected behavior**
The benchmark should run.

**Hardware/Compute device (please complete the following information):**
- Compute device name: AMD Radeon Pro 580
- OpenCL/CUDA driver name: METAL API
- OpenCL/CUDA driver version: Metal 258.18
- OpenCL/CUDA driver source: provided by Apple

**Hashcat version (please complete the following information):**
 - OS: macOS
 - Distribution: -
 - Version: 12.2.1

**Diagnostic output compute devices:**

Post hashcat -I output
```
hashcat (v6.2.5-326-g8bc4a9208) starting in backend information mode

Metal Info:
===========

Metal.Version.: 258.18

Backend Device ID #1
  Type...........: GPU
  Vendor.ID......: 2
  Vendor.........: Apple
  Name...........: AMD Radeon Pro 580
  Processor(s)...: 1
  Clock..........: N/A
  Memory.Total...: 8192 MB (limited to 3584 MB allocatable in one block)
  Memory.Free....: 8064 MB
  Local.Memory...: 32 KB
  Phys.Location..: built-in
  Feature.Set....: macOS GPU Family 2 v1
  Registry.ID....: 1584
  Max.TX.Rate....: N/A
  GPU.Properties.: headless 0, low-power 0, removable 0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (Dec 17 2021 16:38:42)

  Backend Device ID #2
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel
    Name...........: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Version........: OpenCL 1.2
    Processor(s)...: 8
    Clock..........: 4200
    Memory.Total...: 40960 MB (limited to 5120 MB allocatable in one block)
    Memory.Free....: 20448 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 1.1

  Backend Device ID #3
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: AMD
    Name...........: AMD Radeon Pro 580 Compute Engine
    Version........: OpenCL 1.2
    Processor(s)...: 36
    Clock..........: 1200
    Memory.Total...: 8192 MB (limited to 2048 MB allocatable in one block)
    Memory.Free....: 8064 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 1.2 (Jan 10 2022 21:29:11)
```

**Comment by matrix** [comment]
Hi, try move hashcat in "/Users/ulf/", rebuild "make clean && make -s" and run again.

**Comment by matrix** [comment]
https://github.com/hashcat/hashcat/issues/3080

**Comment by 0xDedSec42** [comment]
hashcat now runs, but it's still skipping the Metal device and using the CPU.

```
METAL API (Metal 258.18)
========================
* Device #1: AMD Radeon Pro 580, skipped

OpenCL API (OpenCL 1.2 (Dec 17 2021 16:38:42)) - Platform #1 [Apple]
====================================================================
* Device #2: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 20448/40960 MB (5120 MB allocatable), 8MCU
* Device #3: AMD Radeon Pro 580 Compute Engine, skipped
```

**Comment by matrix** [comment]
> hashcat now runs, but it's still skipping the Metal device and using the CPU.
> 
> ```
> METAL API (Metal 258.18)
> ========================
> * Device #1: AMD Radeon Pro 580, skipped
> 
> OpenCL API (OpenCL 1.2 (Dec 17 2021 16:38:42)) - Platform #1 [Apple]
> ====================================================================
> * Device #2: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 20448/40960 MB (5120 MB allocatable), 8MCU
> * Device #3: AMD Radeon Pro 580 Compute Engine, skipped
> ```

Hi, yes because Metal with AMD is untested. If you want to known more join on [hashcat discord](https://hashcat.net/discord), we can do some tests ;)

**Comment by emwinkler** [comment]
I can also assist in testing Metal with AMD.  Let me know how to help out.  Here is my hardware setup per the latest version of hashcat from githum:

hashcat (v6.2.5-355-g781ceb1df) starting in backend information mode

Metal Info:
===========

Metal.Version.: 261.13

Backend Device ID #1
  Type...........: GPU
  Vendor.ID......: 2
  Vendor.........: Apple
  Name...........: AMD Radeon RX Vega 64
  Processor(s)...: 1
  Clock..........: N/A
  Memory.Total...: 8176 MB (limited to 3584 MB allocatable in one block)
  Memory.Free....: 8064 MB
  Local.Memory...: 32 KB
  Phys.Location..: connected via an external interface (port 0)
  Feature.Set....: macOS GPU Family 2 v1
  Registry.ID....: 19956
  Max.TX.Rate....: 40000000 MB/sec
  GPU.Properties.: headless 0, low-power 0, removable 1

Backend Device ID #2
  Type...........: GPU
  Vendor.ID......: 2
  Vendor.........: Apple
  Name...........: Intel(R) Iris(TM) Plus Graphics
  Processor(s)...: 1
  Clock..........: N/A
  Memory.Total...: 1536 MB (limited to 1024 MB allocatable in one block)
  Memory.Free....: 704 MB
  Local.Memory...: 32 KB
  Phys.Location..: built-in
  Feature.Set....: macOS GPU Family 2 v1
  Registry.ID....: 1263
  Max.TX.Rate....: N/A
  GPU.Properties.: headless 0, low-power 1, removable 0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: Apple
  Name....: Apple
  Version.: OpenCL 1.2 (Feb 12 2022 01:56:27)

  Backend Device ID #3
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel
    Name...........: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Version........: OpenCL 1.2 
    Processor(s)...: 8
    Clock..........: 2300
    Memory.Total...: 32768 MB (limited to 4096 MB allocatable in one block)
    Memory.Free....: 16352 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.1

  Backend Device ID #4
    Type...........: GPU
    Vendor.ID......: 8
    Vendor.........: Intel Inc.
    Name...........: Intel(R) Iris(TM) Plus Graphics
    Version........: OpenCL 1.2 
    Processor(s)...: 64
    Clock..........: 1100
    Memory.Total...: 1536 MB (limited to 192 MB allocatable in one block)
    Memory.Free....: 704 MB
    Local.Memory...: 64 KB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2(Feb 21 2022 22:36:12)

  Backend Device ID #5
    Type...........: GPU
    Vendor.ID......: 1
    Vendor.........: AMD
    Name...........: AMD Radeon RX Vega 64 Compute Engine
    Version........: OpenCL 1.2 
    Processor(s)...: 64
    Clock..........: 1663
    Memory.Total...: 8176 MB (limited to 2044 MB allocatable in one block)
    Memory.Free....: 8064 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 1.2 
    Driver.Version.: 1.2 (Feb 21 2022 22:34:01)
