### ISSUE TITLE
metamask hash

### ISSUE THREAD

**Issue by kxnye** [hashcat/hashcat#3232]
How to get the metamask hash? Please provide an example so that I can get a hash of this format: $metamask$[BASE64encodedSALT]$[BASE64encodedIV]$[BASE64encodedData]

**Comment by kxnye** [comment]
like example:
**how can i get out of this :** {data:wM+CSmCIIlaofXHPxCRFqbcPvEDZESBYM1XdAE8VFanedCIXvDEEt15nhzdv1pqzkW0MCQDBA5T1W1/Ltg7lKBszkoJJ1PtVHOpTn/afhvLyIp2VBBV1Tuj4s8LGo2GM9KOHn1Hn5BC1YhjP56opGrJlsIT9qnuGYHT8EtA5IiHP4zB4fwgGqDhtX+QUJi4rdm+apXZ1DpRvDq5J+bCca2GHXzU5H57Esn3THPXev3RdlkmjhuXVjV8=,iv:ejhZW94EsJZ049Sb/at0Xg==,salt:jgW3gi0eyPtXXguqMzi6uGyuR6m+lgQXw8onqivK5w0=}


**i need this :** $metamask$amdXM2dpMGV5UHRYWGd1cU16aTZ1R3l1UjZtK2xnUVh3OG9ucWl2SzV3MD0=$ZWpoWlc5NEVzSlowNDlTYi9hdDBYZz09$d00rQ1NtQ0lJbGFvZlhIUHhDUkZxYmNQdkVEWkVTQllNMVhkQUU4VkZhbmVkQ0lYdkRFRXQxNW5oemR2MXBxemtXME1DUURCQTVUMVcxL0x0ZzdsS0JzemtvSkoxUHRWSE9wVG4vYWZodkx5SXAyVkJCVjFUdWo0czhMR28yR005S09IbjFIbjVCQzFZaGpQNTZvcEdySmxzSVQ5cW51R1lIVDhFdEE1SWlIUDR6QjRmd2dHcURodFgrUVVKaTRyZG0rYXBYWjFEcFJ2RHE1SitiQ2NhMkdIWHpVNUg1N0VzbjNUSFBYZXYzUmRsa21qaHVYVmpWOD0=

**Comment by philsmd** [comment]
does this help: https://github.com/hashcat/hashcat/issues/3052 and https://github.com/hashcat/hashcat/issues/2818 , https://github.com/hashcat/hashcat/pull/2930 and the tool itself: https://raw.githubusercontent.com/matrix/hashcat/master/tools/metamask2hashcat.py (need to run it with the python software)

I think questions like this are more suitable for the hashcat forum at https://hashcat.net/forum .
It should work with the correct hash format syntax.
