### ISSUE TITLE
Unable to crack the known Luks password

### ISSUE THREAD

**Issue by FloatingLizard** [hashcat/hashcat#3250]
I am currently trying to crack an unknown password and I have been doing this since last August and then I was curious to see if I was doing something wrong and it turns out that there is a problem and I would like to know what the issue is before I continue on.

Got a slice from the image 

sudo dd if=test_Luks_Partition.001 of=test_Luks_Partition.dd bs=512 count=4079

Here is my test where I know the password at the first I got this error when running hashcat  

hashcat -m 14600 -a 0 Luks_Partition_500gb.dd Dictionary.txt -o luks_password.txt

Hashfile 'Luks_Partition_500gb.dd': Disabled LUKS key detected

I padded it
truncate -s 2097664 Luks_Partition_500gb.dd
s -ltr Luks_Partition_500gb.dd

4. ran 
hashcat -m 14600 -a 0 paddedLuks_Partition_500gb.dd Dictionary.txt -o luks_password.txt
Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 14600 (LUKS)
Hash.Target......: paddedLuks_Partition_500gb.dd
Time.Started.....: Wed Mar 30 08:28:06 2022 (6 secs)
Time.Estimated...: Wed Mar 30 08:28:12 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (Dictionary.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.1.........: 0 H/s (0.42ms) @ Accel:128 Loops:256 Thr:1 Vec:8
Recovered........: 0/1 (0.00%) Digests
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.1...: Salt:0 Amplifier:0-1 Iteration:2216704-2216861
Candidate.Engine.: Device Generator
Candidates.1....: Known Password -> Known Password
Hardware.Mon.1..: Temp: 42c Util: 12%

Version:       	1
Cipher name:   	aes
Cipher mode:   	xts-plain64
Hash spec:     	sha256

I then decided to create an entirely new test and got the same results
The dictionary contains the password of 7 characters that is correct 

What is the issue?  btw I am new to this and I may not have been clear.

**Comment by jsteube** [comment]
I think you just have forgotten to format the drive. Please close the issue if it works afterwards. Some details: https://hashcat.net/forum/thread-6225.html

**Comment by FloatingLizard** [comment]
I need an educated feedback!  Obviously that's not the problem!!!  Ticket remains open until I get a contructive feedback!!!
And the drive was formated EXT4 before the test because I needed to encrypt the drive for the test.

**Comment by Banaanhangwagen** [comment]
Maybe you'll find your answer here: https://github.com/hashcat/hashcat/issues/2477

**Comment by FloatingLizard** [comment]
> Maybe you'll find your answer here: #2477

Thank you!  I will look.

**Comment by jsteube** [comment]
> I need an educated feedback! Obviously that's not the problem!!! Ticket remains open until I get a contructive feedback!!! And the drive was formated EXT4 before the test because I needed to encrypt the drive for the test.

It wasn't uneducated, in fact it's the opposite. If you formatted the drive, you didn't specify it in the description text and that's why I've mentioned it.

**Comment by jpalcantara** [comment]
> > I need an educated feedback! Obviously that's not the problem!!! Ticket remains open until I get a contructive feedback!!! And the drive was formated EXT4 before the test because I needed to encrypt the drive for the test.
> 
> It wasn't uneducated, in fact it's the opposite. If you formatted the drive, you didn't specify it in the description text and that's why I've mentioned it.

**Comment by jsteube** [comment]
I'm sorry, but so far hashcat is correctly working, there are no know issues on LUKS. 

If you can demonstrate with a case of yours that it is not working we can debug it. Please send all the data so we can reproduce it locally. You can generate a 10mb volume so it's not too big and attach it here and also tell us the password.

There's a hashcat discord where you can ask for help as well, but it's not guaranteed any developer is around.

**Comment by FloatingLizard** [comment]
Found the issue it was this 
sudo dd if=test_Luks_Partition.001 of=test_Luks_Partition.dd bs=512 count=4079
Changed it to 
dd if=/dev/sda1 of=header.luks bs=512 count=4097
Cracked!!   Hope it helps
Thank you anyway!

**Comment by jsteube** [comment]
OK, thanks for clarification.

I think I saw a very old blog post a while ago which had that error, too. I wrote to the author, but they never fixed it :(
