### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by GimmeAKitkat** [hashcat/hashcat#326]
I'm not by any means a master coder, but on line 12388 of src/oclHashcat.c, should it be 'force_jit_compilation = 8900' or 'force_jit_compilation = 9300'? Seems odd that the hash modes wouldn't match.

**Comment by jsteube** [comment]
I see what you mean, but it's actually correct like it is. The 8900 is the kernel used by both, 8900 and 9300. It's a bit confusing, tho
