### ISSUE TITLE
--debug-file default setting

### ISSUE THREAD

**Issue by 0xVavaldi** [hashcat/hashcat#3261]
--debug-file currently does not have a default set, but does require --debug-mode to be set.
The enhancement I'd like to see made is that --debug-file gets a default file to write to when --debug-mode is specified.
Similar to the potfile and session files they can be changed if the user wills it, but it still has a default to write to.

**Comment by jsteube** [comment]
OK, but we need to keep in mind that --debug-mode is allowed to be used without --debug-file which will cause it to write the data to stdout. That means we can't change the --debug-mode default value, but we can set it to some value if --debug-file is being set in user_options_preprocess(). Which default do you think is a good one?

**Comment by jsteube** [comment]
OK, like this? https://github.com/hashcat/hashcat/commit/ec7eae9886e1e89280af3834af2e101d91de9545

**Comment by 0xVavaldi** [comment]
Yes, this looks good. 
Please adjust the default value on the wiki accordingly as well when released

**Comment by 0xVavaldi** [comment]
@jsteube feel free to close this btw if you think this is adequately taken up with that pull request.
