### ISSUE TITLE
feature: ability to remove hashes/mark as solved from the hashlist while attack is running

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#3273]
Feature request: 

Ability to remove hashes/mark hashes as solved while attack is still running. This option would work similar/the same as if hashcat found the hash on it's own but would require manual intervention while the attack is running. 

scenario: 
You are in a hash cracking competition as a group and a bunch of people are working on cracking the same hashes at the same time. So, everyone would keep their source hash file in sync with each other and hashcat would know not to keep working on hashes that have already been solved by someone else. This option could also be used in scenarios where you'd like to remove hashes from the source list during an attack for various reasons (perhaps the modifier is too large or perhaps you no longer need a certain hash cracked for a certain reason).

Obviously, this would mostly be used in certain situations and for slow(er) hash types as the benefit wouldn't be there for faster hashes. 

Perhaps an additional argument could be passed with a file to check to see if a hash has been solved by someone/something else and while hashcat does it's looping, it could poll this file and remove it from the hashlist, so it stops checking the already solved hash.

**Comment by sensei-hacker** [comment]
This info I found in the docs may be helpful:
#
You may have already noticed that when you start hashcat, a 'hashcat.outfiles' directory is automatically created (more correctly the *.outfiles directory depends on the session name, see --session, so it is $session.outfiles/).
This directory can be used to tell hashcat that a specific hash was cracked on a different computer/node or with another cracker (such as hashcat-legacy). The expected file format is not just plain (which sometimes confuses people), but instead the full hash[:salt]:plain.
#

**Comment by Shooter3k** [comment]
Looks like this FAQ solves my request. Sorry about that

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_got_a_hash_cracked_on_a_different_computer_can_i_tell_hashcat_about_that_while_it_is_running
