### ISSUE TITLE
Incorrect Error message shown when using --runtime and --loopback

### ISSUE THREAD

**Issue by 0xVavaldi** [hashcat/hashcat#3274]
https://github.com/hashcat/hashcat/blob/ec7eae9886e1e89280af3834af2e101d91de9545/src/user_options.c#L722
Is returned when running --runtime and --loopback.

I believe this should be "--runtime and --loopback". It might be good to make the distinction between the two somewhere to return the correct error message.

**Comment by jsteube** [comment]
Nice catch! Fixed https://github.com/hashcat/hashcat/commit/38c44b4b35f27f94fb8baebb763e4840747d54f1

**Comment by jsteube** [comment]
Should we close this one?

**Comment by Chick3nman** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/38c44b4b35f27f94fb8baebb763e4840747d54f1
