### ISSUE TITLE
Improve historical akkack log

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3296]
For example, I need to save the following task hashes that have been attacked. Although they did not successfully recover the password, I still want to save all the data. What parameters can I use to do this?

`
1416dd1c08474c925d5b4449f48c3e47:c83a651d1d58:000b6b6ac13b:Tenda:
16c43abeb5ce0e23af27a670fc0f31f0:083e8ef0a805:14d1699f7073:CMCC-1105:
137c0a7e0dcddf65988d6f08f858ae34:0016783033ac:587f66ea01de:CMCC-GVDU:
1f6f8e8b95fcf1537de07424b61238a3:786255a37308:c8ddc2f59105:TP-LINK_6D2F:`

Also, there doesn't seem to be verbose logging when running -a0 or -a1 attack mode with hashcat
For example, I am attacking a wpa hash, and I hope that the attack process can be recorded in detail in the log

hashcat.log

`start hashcat -a0

start hashcat -a0 1f6f8e8b95fcf1537de07424b61238a3:786255a37308:c8ddc2f59105:TP-LINK_6D2F:

dic1.txt
dic2.txt
dic3.txt
dic4.txt
dic5.txt
stop`

**Comment by ghost** [comment]
Can the uncracked hash be synchronously written to the hashcat.potfile file for storage?

**Comment by ventaquil** [comment]
Just create file `uncracked_hashes.txt` and store your hashes there.

I do not exactly know why do you want to save uncracked hashes in potfile - entries saved in potfile are used to save time instead of cracking cracked hashes twice.

**Comment by ghost** [comment]
@ventaquil 

Of course it cannot be stored in the potfile, but another new parameter can be added
For example, add -L task.log
Detailed attack logs can be saved

For example: If it is WPA this task: 1f6f8e8b95fcf1537de07424b61238a3:786255a37308:c8ddc2f59105:TP-LINK_6D2F:

I can query  through the keyword history task: 786255a37308:c8ddc2f59105:TP-LINK_6D2F
I've used those pattern attacks, and I've used those dictionary attacks, so when I go back to the last progress I can very well understand its historical attack


For example, add -L  task.log
When using the new parameter, the detailed attack log is stored

The following is the detailed attack log storage
cat task.log

start hashcat -a0 1f6f8e8b95fcf1537de07424b61238a3:786255a37308:c8ddc2f59105:TP-LINK_6D2F:

18:54:39 June 01 2022     dic1.txt
18:54:39 June 01 2022     dic2.txt
18:54:39 June 01 2022     dic3.txt
18:54:39 June 01 2022     dic4.txt
18:54:39 June 01 2022     dic5.txt
stop
