### ISSUE TITLE
hashcat on macOS

### ISSUE THREAD

**Issue by F250SC** [hashcat/hashcat#3303]
Hey guys,

some how I don't get how to install hashcat on macOS.
Is there somehow an easy way for this?

**Comment by derwok** [comment]
Which way you tried?
Did you try it w/ brew?

`brew install hashcat`

**Comment by philsmd** [comment]
yeah, either use the `brew` version or just download the source and use `make` to build it yourself. You are right that there are no macOS binaries currently in the release versions, but this has several good reasons (the main is that several/most `hashcat` devs do not have a macOS system at their disposal and another valid reason is that we would need to target a couple of different macOS versions (`MACOSX_DEPLOYMENT_TARGET`) - so `brew` or `make` are just the better and easier way for the devs to point at).
