### ISSUE TITLE
PKCS#8 modes accept only 8-byte salts

### ISSUE THREAD

**Issue by geitda** [hashcat/hashcat#3323]
Modes 24410 and 24420 (PKCS#8 Private keys with PBKDF2-HMAC-SHA1 or PBKDF2-HMAC-SHA256) have a limitation: exactly 8 bytes of salt are required - no more, no less. This works fine for any PKCS#8 or PKCS#12 files generated from `openssl pkcs8` or `openssl pkcs12` as that tool is hardcoded to always use 8 bytes of random salt when generating those files: there's no options for changing the length of auto-generated salt or for specifing the exact salt value.
Java's `keytool` (as tested with version 18.0.1) can (and does by default) create PKCS#12 keystores. These stores use the same EncryptedPrivateKeyInfo as PKCS#8, so they should work with these modes. However, `keytool` uses 20-byte salts which cause a `Hashfile 'hashcat_pkcs8_from_jks.hash' on line 1 ($PEM$2...4d489ec7d92bf3ba81430ae14b88413e): Token length exception` error when run.
`keytool` is horrible to work with as it can't import certs and private keys separately: you still need to use something else to create a generic PKCS#12 file which `keytool` imports, re-encrypts, and adds some attributes to, resulting in a new PKCS#12 file (with 20-byte salts).
I've attached a source PKCS#12 file that was created with OpenSSL:
`>openssl pkcs12 -export -in hashcat.crt -inkey hashcat.key -name hashcat -out openssl.pkcs12`
This file uses 8-byte salts, so you could write a script or manually pull out the EncryptedPrivateKeyInfo (931 bytes starting at offset 53) and run it through pem2john.py (or manually pull out the correct values). However, lets continue with `keytool`:
`>keytool -importkeystore -srckeystore openssl.pkcs12 -destkeystore hashcat.jks -srcstoretype pkcs12 -alias hashcat`
It asks for both the new keystore password (twice) and the source keystore password, and then generates the JKS PKCS#12 file that includes attributes and uses 20-byte salts. Again, we can write a script or manually pull out the EncryptedPrivateKeyInfo (1344 bytes starting at offset 82) and go from there. I did it manually with a hex editor and then used pem2john.py:
`>python pem2john.py hashcat_pkcs8_from_jks.key`
and got the following:
`$PEM$2$4$854f4b91364c70859ac4d01f267eecb64f2b267d$10000$bfe88713bd8c9b4e8f6669c82c0794de$1232$7a0c79e9e9b456c5...`
This appears correct (2 = SHA256, 4 = AES-256-CBC, 40 hex chars salt, 10000 iterations, 32 hex chars IV, 1232 data length, and 2464 hex chars of data), but Hashcat won't take it since the salt field isn't exactly 16 hex chars. If you truncate the salt field to exactly 16 hex chars you can get Hashcat to start (though it will never find the correct password, obviously).
I'm happy to provide any additional examples or do some testing.
ZIP archive includes the original OpenSSL-generated PKCS#12 file, the `keytool` generated PKCS#12 file, the extracted PKCS#8 (EncryptedPrivateKeyInfo) file, and the corresponding hash file generated by pem2john.py. All passwords are `hashcat`
[PKCS12.zip](https://github.com/hashcat/hashcat/files/8910767/PKCS12.zip)

 - OS: Windows 10 Professional
 - Hashcat Version: 6.2.3

Hardware specifics should not be necessary as Hashcat _does_ work correctly with 8-byte salts, but for completeness:
```
>nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.65       Driver Version: 511.65       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2200       WDDM  | 00000000:01:00.0  On |                  N/A |
| 51%   44C    P0    22W /  75W |    461MiB /  5120MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+`
```

**Comment by ventaquil** [comment]
It should be relatively easy to change accepted salt length.

https://github.com/hashcat/hashcat/blob/c53c28ed3ad63c766ac525e522644a6318b66d5f/src/modules/module_24410.c#L175-L182

What is the maximum length of the used salt by keygen?

I can prepare PR with proper fix.

**Comment by geitda** [comment]
From what I can tell, `keytool` has no way to specify the salt length or an exact salt value, so this 20 byte default seems to be the "maximum". I read somewhere that FIPS also calls for 16 byte salts, so 20 should be fine, but if you're bothering to make a change, maybe go with 32.

**Comment by ventaquil** [comment]
@geitda check my PR, I tried to crack hash provided by you and it cracked successfully.

```
$ ./hashcat -m24420 -a3 --backend-ignore-cuda -w4 -O hashcat_pkcs8_from_jks.hash 'hash?l?l?l'
hashcat (v6.2.5-512-gbcbd9dc78) starting

OpenCL API (OpenCL 3.0 CUDA 11.4.189) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: NVIDIA GeForce RTX 3080, 9792/10018 MB (2504 MB allocatable), 68MCU
* Device #2: Quadro RTX 5000, 16000/16125 MB (4031 MB allocatable), 48MCU
* Device #3: Quadro RTX 4000, 7872/7982 MB (1995 MB allocatable), 36MCU

This hash-mode is known to emit multiple valid candidates for the same hash.
Use --keep-guessing to continue attack after finding the first crack.

Kernel /tmp/tmp.r3tMH5xEkM/OpenCL/m24420-optimized.cl:
Optimized kernel requested, but not available or not required
Falling back to pure kernel

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 4421 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

$PEM$2$4$854f4b91364c7085$10000$bfe88713bd8c9b4e8f6669c82c0794de$1232$7a0c79e9e9b456c51c6c0807f22eef9bc9976e818d37286b51382e133c0ce9580919fc32fc032581df7de1ad58984398e6af204f2a4688f064c469b620e7d4482b63fcb031af9f07f60f63eda6e0b626f1a9bcdc49421b13881c5edb04df3928690213bd7c32215e93a93be36b677f9c921552cd8bd1f68793243f9a921c3db026f20ee6ccaf379e128267835dd4f841ede3242c119fc1f17b41b323fce6771b54e22064da4902db707ee563a9334661216a8f6cf110727a431dec55d3bd57abeb271a7b529a4da8490092babad2f6fb554db518b381b732f1ed0b20cf984d8eb20ab1ac43cd05b95f24b92e55bc3775c456b91c7450f38a3c2ec5b965c1a69a45e2e5f1658d3af12e97d0fdccbfb8831d86a151a9b055d0700846cccb584de4a6f6dab33c271cc64d6fa7e7d6c0249d66c2531ef92354a407182fdbfc8cccf33ddd97d8fc74fa3d0242ed5d908a1e6855ef769c3dcb13be0db4b28d1e31fabe2f6816d564cbd08fcae51d437b7bc16227b9d253d46423471939046213bdc746fe6591362b1b45dee7dee34b688471540fb44b10f1e29122d2fc289407c9ff448b34f8c12f8ecf2f8cf9b6510236de10681977fbeedbe0acb2d50c58a1bbab595a8d04f95f03b4c0cdce28b17ba2fe03fde15ef1b363c6e8cf6344470effeef5ccd2f188c8ab9941f4b03d7c3f74cde4f858d3d41b6f5a954acab92df2e336244730efd5ac497f59b5a4d44dbde4bccbd788857163d048f66322bc3f2aca9b117f88713a4451a5d2dd5327e8516591900a8fd2e3c643c11196d30dd4b3908e45923fd77377a14ea1d943875e1a89dd28b584ac60aebb19464feb1af021e5baf70272e180424928358d6bb9b215656205c2f8397509ef06325cc44eac05a11d8042e6b40219cf69119ad60fd8983310ddf11da1efb2678f9d73f610c585308fafa3c8c3c78054d57fbe29fc8cafe38c5a96b750f1a446c7382cecab24420c441518ffe7fbb1f47eb2bb1631db08f0f78d58819d58c2339b31563e35271c5289e40066b6d45b4d9a8d2e843bd4232ad5dc3836457f9aab42b48b786baa562cfee7cd6d0d308d81c426903e19309d9393b68513a6f6f3f98ef67ccbbde0ebf201d1cb48e84abc9a124c4ab512132cf74856da689f8bc22d63dee6c74728c3aeebb24fc62f9bc384d0c851fd3359225ed1b40daee585b30b88ac5412dc9bae81053c5569f7e6d480cd2523577504533c3b0f2c49334f889a162583c5d73e3c35609b6d0281d7472b470c3ab129569dd959868e3a137b81573ab081167346a651609c03a1efc76efb9f8ffa9d11f543b537e9af871a5ebe3e1fff3a19075e6a9726b10cf9426fd621cdc5f3d404d19e6a9c317bb55512da684d659cb33cdb72962c29f034f4b90f27f3e6c4552842a4cf15d706492edb8668e33ba9832200949f3495d3012d17feff0572bc59b7f0615900ef0f4c3485724f5c1abcf65bda830c9c8bd05c0aea27f5d3f5513dfcbd22af4c0e0c8756fbb5f917e658203a781b342e5e17de092022c9fdd31e586e04142d2ea326c106b1c738faf789a583b9c83b30dfc1218fa3f8ac69e6ded77621f0c82b07def37c24c3507e1fc643ea2223c23821a17e511afbd49e98b9c8df0e7b8da7f3579d0421d980c965e7849ca5700f2ba29072a26fd7f9dc0b412c9191d44f3537ef91aabd8b7b47aa499c2d73cca9fe774d489ec7d92bf3ba81430ae14b88413e:hashcat
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 24420 (PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES))
Hash.Target......: $PEM$2$4$854f4b91364c7085$10000$bfe88713bd8c9b4e8f6...88413e
Time.Started.....: Fri Jun 17 16:15:28 2022 (0 secs)
Time.Estimated...: Fri Jun 17 16:15:28 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: hash?l?l?l [7]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   288.6 kH/s (5.97ms) @ Accel:64 Loops:1024 Thr:256 Vec:1
Speed.#2.........:     2900 H/s (5.73ms) @ Accel:64 Loops:1024 Thr:256 Vec:1
Speed.#3.........:        0 H/s (0.00ms) @ Accel:64 Loops:1024 Thr:256 Vec:1
Speed.#*.........:   291.5 kH/s
Recovered.Total..: 1/1 (100.00%) Digests
Progress.........: 17576/17576 (100.00%)
Rejected.........: 0/17576 (0.00%)
Restore.Point....: 0/17576 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:9216-9999
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:9216-9999
Restore.Sub.#3...: Salt:0 Amplifier:0-0 Iteration:0-1024
Candidate.Engine.: Device Generator
Candidates.#1....: hashana -> hashhfq
Candidates.#2....: hashcgq -> hashqxq
Candidates.#3....: [Generating]
Hardware.Mon.#1..: Temp: 47c Fan: 54% Util:  0% Core:1785MHz Mem:9251MHz Bus:16
Hardware.Mon.#2..: Temp: 47c Fan: 34% Util: 20% Core:1620MHz Mem:6500MHz Bus:16
Hardware.Mon.#3..: Temp: 60c Fan: 30% Util: 72% Core:1905MHz Mem:6500MHz Bus:16

Started: Fri Jun 17 16:15:13 2022
Stopped: Fri Jun 17 16:15:29 2022
```

**Comment by geitda** [comment]
Thanks for working on this. Looks like this is generally working.
However, the reported lines (both the full line with the result `:hashcat` at the end and the one that starts `Hash.Target......:` looks like they truncated to 16 hex characters (`854f4b91364c7085`). Is the resulting *.potfile correct/complete?

**Comment by ventaquil** [comment]
You are right, I forgot about `module_hash_encode` function. I will update this function and push changes when it will be ready.

**Comment by ventaquil** [comment]
You can check the newest changes, it looks like it is working fine right now.
