### ISSUE TITLE
Java Object Hashcode() example hash isnt an integer. Bruteforce doesnt work with a normal integer

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3325]
I'm trying to reverse a Java hashCode() integer to different kinds of String inputs. This is method 18700 in hashcat.
The example has for hashCode() is 29937c08, yet everywhere I look at hashCodes from java, its always an Integer, so what is the "c" doing there?

I've been trying to get the bruteforce to work on "886915140" as an integer value, as hashCode only produces integers, yet then it tells me that there is a token length exception. 

With the example hash on the webpage it does work like a charm, yet I do not know how there is a letter in the integer of the example hash... Can anyone help me understand this?

Edit: next to the token length exception there is also "No hashes loaded", but that is normal if it doesnt work

**Comment by ghost** [comment]
`hashcat -m 18700 -a 3 -D 1 -O hashes.txt -o output.txt ?a?a?a?a?a?a?a?a?a?a --keep-guessing --status`
Weirdly enough this works whenever i take one number off of the hash, so with the command above 88691514 works, but not 886915140

**Comment by ventaquil** [comment]
I am guessing that `29937c08` is just hex-encoded integer number - here you have [a Wikipedia article](https://en.wikipedia.org/wiki/Hexadecimal).

As you can see in the source code this module accepts only hex-encoded values.

https://github.com/hashcat/hashcat/blob/c53c28ed3ad63c766ac525e522644a6318b66d5f/src/modules/module_18700.c#L53-L56

**Comment by Xanadrel** [comment]
Closing, @ventaquil is right, there are different ways to write numbers, many hashes are written in hex for ease of use, it's also the case here.

**Comment by scout247** [comment]
Sorry for opening this again. I want to crack quite a long integer (32 numbers). The one i want to crack is the following in hex: 42969176025C3149
This hash gives me a Token Length Exception, although i'm certain of it being Hex and being a valid hashCode(). any clue on what the issue may be?
