### ISSUE TITLE
Support for thinkphp5 (md5(sha1($pass) . $salt)) 

### ISSUE THREAD

**Issue by entrailz** [hashcat/hashcat#3328]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**
For instance:
- it is just a different construct of the standard md5 and sha1 encryptions. 

**Describe alternatives you've considered**
Currently using John with a dynamic format, not ideal though. 

**Provide an example hash/database/file and a known correct password**
2fba5d6031ba47fb44517deb7a8f774e:salt

The password is password

**Explain how the cryptographic schema is implemented**
md5(sha1($pass) . $salt)

**Describe the known limitations of the algorithm**
Many applications limit the password and/or salt to a specific minimum and maximum length.

N/A

**Where do you typically find the algorithm**
Typically used in Thinkphp5.

**Additional context**
N/A

**Comment by philsmd** [comment]
This should now be supported, see #3334 (-m 4410 = `md5(sha1($pass).$salt)`).

Thanks @piwvvo , your contributions are VERY welcome.
