### ISSUE TITLE
Feature Request - pbkdf2 sha256 (huawei router)

### ISSUE THREAD

**Issue by danielocdh** [hashcat/hashcat#3329]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**
I'm not sure what is the exact hashing function, but I have been able to generate valid hashes with node and php:
- node: crypto.pbkdf2Sync (https://github.com/nodejs/node/blob/v16.4.0/lib/internal/crypto/pbkdf2.js)
- php: hash_pbkdf2 (https://github.com/php/php-src/blob/PHP-8.1.7/ext/hash/hash.c) and openssl_pbkdf2 (https://github.com/php/php-src/blob/PHP-8.1.7/ext/openssl/openssl.c)
- The hash has to be deciphered before being used for compare, more information: https://blog.fayaru.me/posts/huawei_router_config/
- Online tool to generate hashes(EncryptMode3) and cipher/decipher them: https://andreluis034.github.io/huawei-utility-page/

**Describe alternatives you've considered**
I tried hash modes 10900 and 10000 which didn't find the correct result.
I tried hash modes 20300 and 27400 which weren't compatible with the data format/length.
I have been reading but wasn't able to recreate the hashing with `openssl enc`.
I tried node using all CPU cores but the speed is slow (around 6kH/s), the php functions seem to be slower than the node one.

**Provide an example hash/database/file and a known correct password**
The configuration file of the router contains passwords like this:
```
<X_HW_WebUserInfoInstance InstanceID="1" UserName="XXX" Password="$2A.tD%XD@^AYLkU4j.uC1jG*#11K4EL#sujYsF[%+9e}2@Hzvs8UE=H2@RVOX=e,6M{VNHDmJb$C(LOD/:Z3]M0u}=3&amp;)VsQpA;CG$" UserLevel="1" Enable="1" ModifyPasswordFlag="1" Salt="e57194dd31da16b3e3b28cbe" PassMode="3" Alias="cpe-X"/>
```
The password hash is obtained by deciphering the Password field in the xml ( https://andreluis034.github.io/huawei-utility-page/ )
hash (password deciphered): a0ca2432cc3dc6312a601621693a8973f10bf1c9567f83d9828812ff1ac811db
iterations: 5000
salt hex (provided by router): a2a859db0c6a9f9ff7b51069
password: hashcat123
(more hashes below)

**Explain how the cryptographic schema is implemented**
node 16.4.0 example:
```node
const {pbkdf2Sync} = require('node:crypto');

const list = [
  //passwords from example.dict and salts provided by the router
  ['020584cu', 'c312fcbc0a94d1ccb54abaab'],
  ['cy42wafg', 'ad4a06733bd1ad9d03991927'],
  ['epoch2', '95d2acb0f4092073c98aacfa'],
  ['isla1755', '5a1f9f2b51ed3c9a3aa453ac'],
  ['ita:ita', 'e57194dd31da16b3e3b28cbe'],
  ['j365780k', '1790aadb0ec50c669817c897']
];

list.forEach(([pass, salt_hex]) => {
  console.log(
    pbkdf2Sync(pass, salt_hex, 5000, 32, 'sha256').toString('hex')
  );
});
```
PHP 8.1.7 example:
```php
$list = [
  //passwords from example.dict and salts provided by the router
  ['020584cu', 'c312fcbc0a94d1ccb54abaab'],
  ['cy42wafg', 'ad4a06733bd1ad9d03991927'],
  ['epoch2', '95d2acb0f4092073c98aacfa'],
  ['isla1755', '5a1f9f2b51ed3c9a3aa453ac'],
  ['ita:ita', 'e57194dd31da16b3e3b28cbe'],
  ['j365780k', '1790aadb0ec50c669817c897']
];
foreach ($list as list($pass, $salt_hex)) {
  echo hash_pbkdf2('sha256', $pass, $salt_hex, 5000, 64) . "\n";
}
echo "\n";
foreach ($list as list($pass, $salt_hex)) {
  echo bin2hex(openssl_pbkdf2($pass, $salt_hex, 32, 5000, 'sha256')) . "\n";
}
```
The resulting hashes for both php functions and node are:
```
34b445202cb928d76142de94508eed0857b8cd0dcc807e579e3cd671e97aa0d0
a5211e63228ea53e5019db94ef1e74031847507a46feac0f49fcef9ab6d28145
dcd90f426e73ded384fe5a8d710837c56a0cd28426726b7d044d20f909e62632
f11a8be37058bbc64ec53375db33cbc2ea752f314813da418928677416db169b
0b22cee2ae4ee9993e8e376204d164cee4e1b8e4d6e3bed49cc134dc5a00d311
8fbca31ec3e3df334c99c6e7f12d01460bfb31d66e8dbc1896ab1a38b35b0d44
```

**Describe the known limitations of the algorithm**
The router seems to provide 12 bytes salts only but the algorithm seems to work with shorter/longer salts

**Where do you typically find the algorithm**
Huawei routers configuration file with PassMode="3": HG8247Q, HS8247W, HG8145V5 and possibly others

**Additional context**
None for now

**Comment by piwvvo** [comment]
You actually can run this with 10900 mode in hashcat , you just have to format it correctly. I understand you assumed that salt was random bytes represented in hex, but actually the hex string is used as salt. In order to get the format that hashcat will accept and crack you have to convert the 32 bytes from the pbkdf2 and encode it with base64 and convert your salt to base64 as well (salt should be treated as a plaintext, not hex representation of bytes)

I slightly modified your PHP code, so it now outputs correct format for mode 10900

```php
$list = [
  //passwords from example.dict and salts provided by the router
  ['020584cu', 'c312fcbc0a94d1ccb54abaab'],
  ['cy42wafg', 'ad4a06733bd1ad9d03991927'],
  ['epoch2', '95d2acb0f4092073c98aacfa'],
  ['isla1755', '5a1f9f2b51ed3c9a3aa453ac'],
  ['ita:ita', 'e57194dd31da16b3e3b28cbe'],
  ['j365780k', '1790aadb0ec50c669817c897']
];
foreach ($list as list($pass, $salt_hex)) {
  echo 'sha256:5000:' . base64_encode($salt_hex) . ':' . base64_encode(hash_pbkdf2('sha256', $pass, $salt_hex, 5000, 32, true)) . PHP_EOL;
}
```
Perhaps module could be made to decipher the encrypted hash, although I'm not sure if it's really needed.

**Comment by danielocdh** [comment]
thanks for your time @piwvvo, that was exactly it
