### ISSUE TITLE
Multiple lengths

### ISSUE THREAD

**Issue by e2002e** [hashcat/hashcat#3333]
Hello, is it possible to consider treating lengths in a fashion that avoids standard increment mode ?
Meaning not being stuck on short lengths for ages, no one will ever try length 10 with sha512crypt while the password might be weak...
This would be a dramatic improvement.

**Comment by Chick3nman** [comment]
I apologize but this doesn't really make sense. You want to start at a longer length for increment mode? You understand that you won't be able to actually complete almost any attack at lengths like that, right? Further, this is already implemented in hashcat using the other increment settings flags, `--increment-min` and `--increment-max`.

```
 -i, --increment                |      | Enable mask increment mode                           |
     --increment-min            | Num  | Start mask incrementing at X                         | --increment-min=4
     --increment-max            | Num  | Stop mask incrementing at X                          | --increment-max=8
```

**Comment by e2002e** [comment]
Hi, thanks for the answer, i mean looping on length at each words.
?d?d
0
00
1
11
...
99
19
...

**Comment by Chick3nman** [comment]
Again, I don't really understand what you are talking about. If you want to do different lengths mixed together, you could specify them in a mask file. https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files

**Comment by e2002e** [comment]
Even better ! I wasn't aware of that feature.
Good bye.

**Comment by e2002e** [comment]
No actually i mean a way of trying all lengths between current length and max length in the same time.
Check my fork of john the ripper at https://github.com/e2002e/john
with options -stdout -mask you'll see what I mean.

**Comment by ventaquil** [comment]
@e2002e 

I am not exactly sure how can I understand your example

Mask: `?d?d`
Passwords:
```
0
00
1
11
..
99
19
..
```

Shouldn't be rather this?
Mask: `?d?d`
Passwords:
```
0
00
01
..
09
1
10
11
..
19
2
20
..
9
90
91
..
99
```

**Comment by e2002e** [comment]
No, the concept is about one extra loop around the generation of the word, and a subtotal to decrease the total count as:
length 1: total = 10 subtotal = 0
length 2: total = 100 subtotal = 10

the standard output would look like a pyramid, example:
max length 4
0
00
000
0000

when a length is done the state should NOT be reset, so that the words already treated don't reappear.
The way hashcat is managing the state via markov and also an extra loop on the length of the set makes it really hard for me to implement, i can get the desired effect but with duplicates so that instead of 1110 words I get 1230 of them.
Even though i'd fix this eventually (maybe) I don't get it how words are treated with an attack on hashes.
I'm looking for some equivalent to sp_exec()...

**Comment by Chick3nman** [comment]
This doesn't really make sense to me, you are trying to do more than 1 length a time? After length 10 there's almost no point in doing that, you won't complete that keyspace either way...

**Comment by e2002e** [comment]
It's more about spraying words, it does actually make sense only AFTER some length, since it's not possible to complete the keyspace, then let it at least start it. A lot of passwords would be found this way.
It slows down the attack by (max length - current length), so instead of hitting 1000 length 6 passwords then go to the next, we would get -  in the same timelapse - 100 length 6 but a lot of length 7, fewer 8 and so forth, given a max length at 10, with more and more focus on the current length and above while keyspaces are being completed.
It's a choice to just ignore long and complex password and crack a lot of words or fragment the work for a higher chance of finding "real" passwords.

**Comment by Chick3nman** [comment]
That still doesn't make sense to me, you want to start each keyspace randomly throughout the computing session? Based on what optimized order? This is attempting to recreate the variable length of a wordlist, but without the necessary external information that is needed to actually reduce the candidate space enough to be likely.

**Comment by e2002e** [comment]
Not randomly,
here is a video from the completed project on john the ripper, they won't merge it and I don't want to insist any further.
Actually this is better for working on paid hashes but to be honest hashcat can do a markov on mask which john cannot.

I worked out some kind of algorithm to beat the entropy but it is not human oriented (i called that rain given the effect on screen).
it is good maybe given an impossible password + luck, but I'm pretty sure it's some kind of scheduler more than a password's generating algorithm.

I uploaded a video of decent quality
https://youtu.be/0iXqarEllCU

given -i --increment-min=1 --increment-max=4:
you have a total of 1110 for -a ?d?d?d?d

The theory is in adding an extra loop on the lowest loop as follows:
```
for (i = min_len; i < max_len; i++) {
    if (i > min_len)
      subtotal = pow(10, i - 1)
    for (j = 0; j < pow(10, i) - subtotal; j++) {
      for (alt_len = 0; alt_len <= max_len - i; alt_len++)
      treat word and modify state
    }
}
```

**Comment by e2002e** [comment]
I am trying to complete the procedure with stdout, and will need to know about how mask is handled for cracking.
I've scrolled through the files and cannot understand. Is a function passed to the gpu device ? Are these different for each format ?

**Comment by e2002e** [comment]
Actually setting a maximum run time for each length is the solution, it permits trying a bit of every un-completable keyspaces without restarting the software manually.
