### ISSUE TITLE
Cannot build library

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#3337]
**Describe the bug**

I cannot build Hashcat library with the newest code.

**To Reproduce**

1. Download the newest code.
2. Run `make libhashcat.so.6.2.5 hashcat`.
3. See error.

```
/usr/bin/ld: obj/emu_inc_bignum_operations.NATIVE.o: in function `mul_mod':
emu_inc_bignum_operations.c:(.text+0x36c0): multiple definition of `mul_mod'; obj/emu_inc_ecc_secp256k1.NATIVE.o:emu_inc_ecc_secp256k1.c:(.text+0x16b0): first defined here
collect2: error: ld returned 1 exit status
make: *** [src/Makefile:644: libhashcat.so.6.2.5] Error 1
make: *** Waiting for unfinished jobs....
```

**Expected behavior**

Library should be built successfully.

**Hashcat version:**

 - OS: Linux
 - Distribution: Ubuntu 20.04
 - Version: v6.2.5+ (commit 372d3a127)

**Additional context**

Probably problem occurred after merging PR GH-3295 (my comment https://github.com/hashcat/hashcat/pull/3295#issuecomment-1161384563).

**Comment by philsmd** [comment]
Thanks for your report, I think the above pull request (#3341) should fix it. It seems to be a good fix/workaround/approach to rename this function and everything should work again. Thx
