### ISSUE TITLE
adding support for SM3

### ISSUE THREAD

**Issue by junshunhu** [hashcat/hashcat#3340]
SM3 is a cryptographic hash function used in the Chinese National Standard.Is it possible to support this algorithm?

**Comment by jsteube** [comment]
It looks a lot like SHA2 and I think is a GPU friendly algorithm. I can see there's some nice implementation in linux coreutils, too. So technically is not a problem is more like the number of requests. Where is it used in?

**Comment by mdawsonuk** [comment]
For one, it is used in the HMAC-SM3 format in Werkzeug, which I'm working through implementing hash formats in #3368

**Comment by loukabvn** [comment]
Hi, I would like to contribute for this issue, is it still available ?

**Comment by mdawsonuk** [comment]
> Hi, I would like to contribute for this issue, is it still available ?

Doesn't look like anyone's made a PR for it, so go ahead!

**Comment by Zgzorx** [comment]
Issue resolved by PR : https://github.com/hashcat/hashcat/pull/3620

**Comment by Chick3nman** [comment]
Looks like this was added in #3620, closing as complete.
