### ISSUE TITLE
Output of --hash-info is broken with new LUKS v1 hashes (-m 2951-29543)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#3359]
This is a new problem (accidentially, maybe unrelated) introduced by @ventaquil in https://github.com/hashcat/hashcat/commit/ddb2d6e61a67330bfff9966706262f4bcc8829c6.

The problem here is that `--hash-info` (and alias `--example-hashes`) are not behaving correctly with these example hashes and they cut the hashes at approximately 8167 bytes.

You can just run something like `hashcat --hash-info -m 29511` to see what the output is and look at the source code of the hash module `src/modules/module_29511.c` what the whole/full hash should be.

I think it is dangerous to truncate it there because we might get some problems with some tasks and external tools etc (maybe even updating something like the hashcat wiki page would be dangerous, if the output of `--hash-info` is not 100% correct and the dev/user trying to copy-paste that output does NOT know).

I think we should find a solution for these long hashes (my current educated guess is that the culprit is just that these hashes are now the longest hashcat).

These are the hashes affected:
```
29511 29512 29513 29521 29522 29523 29531 29532 29533 29541 29542 29543
```
(`LUKS v1`)

problem: truncated **AND**  NUL byte \x00 in the `--hash-info`/`--example-hashes` output

Please suggest a solution
CC: @ventaquil , @jsteube 

Thanks guys

**Comment by ventaquil** [comment]
Hey @philsmd, I investigated the issue and I hope that mine PR fixes it.

**Comment by philsmd** [comment]
@ventaquil thank you !
