### ISSUE TITLE
crossbuild failed mingw ubuntu/win64 (CONST conflict)

### ISSUE THREAD

**Issue by enwony** [hashcat/hashcat#3361]
**Describe the issue**
When I recently (3 jule 2022) checkout and build hashcat under ubuntu 22.03 (crossbuild for windows 64) I got same 2 errors in modules src/modules/module_28504.c and src/modules/module_28503.c:

I believe it's conflict between CONST identifier declared as const in mingw, fixed quickly by name change

```
x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 10-win32 20220113

```

failed command:
`x86_64-w64-mingw32-gcc    -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON   src/modules/module_28503.c obj/combined.WIN.a -o modules/module_28503.dll -s -lstdc++ -Wl,--dynamicbase -Wl,--nxcompat -lpsapi -lws2_32 -lpowrprof -static -static-libgcc -static-libstdc++   -shared -fPIC -D 
`
Error:
`
MODULE_INTERFACE_VERSION_CURRENT=630
src/modules/module_28503.c: In function ‘polymod_checksum’:
src/modules/module_28503.c:60:18: error: expected identifier or ‘(’ before ‘[’ token
   60 |   const u32 CONST[5] = { 0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3 };
      |                  ^
In file included from /usr/share/mingw-w64/include/windef.h:9,
                 from /usr/share/mingw-w64/include/windows.h:69,
                 from include/types.h:40,
                 from src/modules/module_28503.c:7:
src/modules/module_28503.c:76:12: error: expected expression before ‘const’
   76 |       c ^= CONST[j];
      |            ^~~~~
make: *** [src/Makefile:773: modules/module_28503.dll] Error 1
`
Build failed then

**To Reproduce**
ubuntu machine:
```
sudo apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 make git
git clone https://github.com/hashcat/hashcat
git clone https://github.com/win-iconv/win-iconv
cd win-iconv/
patch < ../hashcat/tools/win-iconv-64.diff
sudo make install
cd ../
make win

```
**Expected behavior**
Build successful

**Hardware/Compute device (please complete the following information):**
not applicable

**Hashcat version (please complete the following information):**
 - OS: [linux]
 - Distribution: [Ubuntu 22.04 LTS]
 - Version: [v6.2.5-534-ge0fae5c7a+]

**Diagnostic output compute devices:**
not applicable

**Comment by enwony** [comment]
quick fix

**Comment by philsmd** [comment]
fixed with https://github.com/hashcat/hashcat/pull/3362, thanks
