### ISSUE TITLE
./OpenCL/: No such file or directory

### ISSUE THREAD

**Issue by saikuru0** [hashcat/hashcat#3365]
**Describe the bug**
Trying to use hashcat in any way possible results in "./OpenCL/: No such file or directory"

**To Reproduce**
Just the base files and trying to use 'hashcat --help' are needed, tried re-downloading the binaries a couple of times, different versions too, different shells, all had the same error

**Expected behavior**
For 'hashcat --help' to show help

**Hardware/Compute device:**
- Compute device name: RTX2080
- OpenCL/CUDA driver name: NVIDIA DRIVER
- OpenCL/CUDA driver version: 456.71
- OpenCL/CUDA driver source: runtime installer

**Hashcat version:**
 - OS: Windows 10
 - Distribution: N/A
 - Version: 6.2.5

**Comment by GoTeamScotch** [comment]
Going to ask this to get the obvious out of the way...

Did you CD into your hashcat folder first?

![image](https://user-images.githubusercontent.com/11036843/177232151-6d33b5ac-679b-4a14-8e31-c02d76e5606d.png)

**Comment by philsmd** [comment]
it's also  important how you extract the 7-Zip file (on unix you need to use the `x` to extract the file correctly, not the "e", which does not preserve the file name hierarchy , i.e. file/folder names and subfolders).

Please reopen if you are sure that every file looks in the correct place/location as seen with the source code in https://github.com/hashcat/

**Comment by BURITOtheONE** [comment]
Hello, i have the same problem, but i want to make it so that i don't have to cd to the folder. i have added the folder to the path but it still displays the error, please help

**Comment by pmcstjean** [comment]
the real question is "Why hashcat not able to run from elsewhere, even though it's in the PATH"

**Comment by tkeriduN** [comment]
I'm having this issue too. Used x to extract. Files and folders are the same as in the git repo. 

I'm *not* within the directory of hashcat, but I *did* add the whole folder to my user path.  It runs as it should if I cd into the hashcat folder.

**Comment by avipars** [comment]
https://github.com/hashcat/hashcat/issues/1539#issuecomment-960358857 solved my issue

**Comment by tech4agr** [comment]
for mim with windows did not work either and these links y`all provided did not work as well.
i got RTX 3060 cuda is already install. it does work using linux kali in VM but i'd use with windows.
appreciate that

**Comment by avipars** [comment]
@tech4agr I run hashcat via WSL and it works well even with my NVIDIA GPU (I'd argue it's better than with a VM, especially since doing GPU passthrough - and specifically NVIDIA is a pain)...
