### ISSUE TITLE
OSX 10.11.4 - abort when using blowfish

### ISSUE THREAD

**Issue by lfaoro** [hashcat/hashcat#337]
I get this weird abort without any errors when I use blowfish (3200), any ideas?
even running with `--debug-mode=0` I get abort and 0 debugging output.

```
./hashcat.app -m 3200 -a 3 --status bcrypt.hash "?d?l?l?l?l?l?u?l?l?l"
hashcat (v3.00-beta-22-geea3424) starting...

Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
Device #2: Iris Pro, 384/1536 MB allocatable, 1200Mhz, 40MCU
Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 300Mhz, 10MCU

Device #2: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/m03200.cf8e615b.kernel not found in cache! Building may take a while...
Device #2: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/markov_le.cf8e615b.kernel not found in cache! Building may take a while...

Device #2: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/amp_a3.cf8e615b.kernel not found in cache! Building may take a while...

Device #3: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/m03200.a09b52dc.kernel not found in cache! Building may take a while...
Device #3: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/markov_le.a09b52dc.kernel not found in cache! Building may take a while...

Device #3: Kernel /Users/lfaoro/Projects/oclHashcat/./kernels/amp_a3.a09b52dc.kernel not found in cache! Building may take a while...

[1]    52316 abort      ./hashcat.app -m 3200 -a 3 --status bcrypt.hash "?d?l?l?l?l?l?u?l?l?l"
```

**Comment by lfaoro** [comment]
Actually I've looked into the system logs and found a crash log for hashcat, I don't know how to read it, hopefully it makes sense to someone for debugging/fixing the issue.
[hashcat.app_2016-05-16-011444_NB-IT-OSX-LFAORO.txt](https://github.com/hashcat/oclHashcat/files/265334/hashcat.app_2016-05-16-011444_NB-IT-OSX-LFAORO.txt)

**Comment by matrix** [comment]
@lfaoro, probably you need tune your AMD Radeon R9 M370X Compute Engine
by changing/adding config in hashcat.hctune file.

Let me know,
matrix

**Comment by jsteube** [comment]
notice debug-mode is about rule debugging, not process debugging

**Comment by lfaoro** [comment]
thank you guys

**Comment by lfaoro** [comment]
the problem seem to be `Device #2: Iris Pro, 384/1536 MB allocatable, 1200Mhz, 40MCU` device
if I exclude it from the ./hashcat -b - I complete the benchmark fine otherwise I get a crash at `Hashtype: SHA-3(Keccak)`

**Comment by lfaoro** [comment]
I think it broke or something happened to it as I was able to complete the benchmark before

**Comment by lfaoro** [comment]
if I run `./hashcat.app -b -d 3` I complete the benchmark no problem, no crash

```
Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
Device #2: Iris Pro, skipped
Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 300Mhz, 10MCU
```

**Comment by jsteube** [comment]
So that means there's no problem? Self-Healing? Can we close this?

**Comment by lfaoro** [comment]
yessir!
