### ISSUE TITLE
Add an “easy to parse” output to benchmark

### ISSUE THREAD

**Issue by Hydraze** [hashcat/hashcat#338]
Hello,
Would it be possible to add an “easy to parse” output mode to hashcat's benchmark?
I was thinking about the following format: 

```
<mode number>:<device number>:<raw number of candidates per second>
```

(NB: When I say “raw”, I mean not the “humanized” number, e.g. 1337 and not 1.3k)

**Comment by jsteube** [comment]
done https://github.com/hashcat/oclHashcat/commit/567fcfe176e17e7e9363742d15837d0092a6a8fe
