### ISSUE TITLE
make `--hash-info` readable again

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#3382]
After this commit https://github.com/hashcat/hashcat/pull/3321 and these changes https://github.com/hashcat/hashcat/issues/3359 (they fixed the reported problem, thanks @ventaquil ), I have a little problem with `--hash-info` (or old `--example-hashes`):

The problem is that this `--hash-info` was always nice to scroll and easy to read and search through, but after the changes with (mainly, but not limited to) the new `LUKS v1` format, it's difficult to scroll.

I'm talking about using `--hash-info` without `-m` switch, but it's also too much with the switch, I think.

My suggestion now is that we might consider changing this a little bit and have a limit on the hash lines we output... something we do with the normal "[s]tatus" prompt already.

My suggestion is to use something like this:

`hash_info_single ()`:
```C
char *tmp_line_buf;

hc_asprintf (&tmp_line_buf, "  Example.Hash........: %s", hashconfig->st_hash);

compress_terminal_line_length (tmp_line_buf, 24, 6); // 24 = strlen ("  Example.Hash........: ")

event_log_info (hashcat_ctx, "%s", tmp_line_buf);

hcfree (tmp_line_buf);
```

It uses `compress_terminal_line_length ()` in `src/terminal.c` .

The "only" problem I see with this that some user might need the full output, and for this problem I suggest that `--machine-readable` output remains unchanged.

Another problem I can see and I can kind of "forecast" is that some example hash output after this patch might seem to get too short or weird or that "too many hash types" get truncated (not only very, very long ones).

I think we could try it with the approach above or might discuss here even a better solution.

Any suggestion is welcome !
Thank you

**Comment by jsteube** [comment]
I agree, we need to change a few things here, I just don't know exactly how at the moment. There's another problem and that is that the .7z binary package (or release package) went from 7mb to 22mb.

What we could do is something similar to WPA. We make a MD5 of the whole hash so that it stays unique and whenever we print it somewhere, we just use that MD5. I also like @philsmd idea by keeping the --mach output unchanged.

**Comment by ventaquil** [comment]
Hey

Totally agree that machine-readable output should provide full string of example hash. In human-readable output we can for example accept up to 2-4 lines of output (so we need to compress each longer string like `LUKS v1` or new `TrueCrypt`/`VeraCrypt` strings).

It can impact on other formats (like `BitLocker` or some formats from category `Cryptocurrency Wallet`).

**Comment by philsmd** [comment]
Hey @ventaquil,

I've discussed this "problem" with @jsteube a little bit in private now. We could also think of an alternative of this truncation, i.e. we could just say that any example hash longer than for instance 2048 characters/bytes (or even smaller ?) shouldn't be printed directly when users use `--hash-info`, but we show a warning something like this instead:
```
[too long example hash for your terminal, use --machine-readable]
```

i.e. use this constant text (the "warning") instead of the actual example hash (only if the length is "too long")

so we also make sure that users aren't copy-pasting the "truncated" hash or are confused about this truncation.

What do you think about this alternative ? It should be easy to implement and we just leave `--machine-readable` AS-IS, so users could always use that format (JSON) for the full output.

(we also tought about a variant with `--force`, i.e. only show the full hash when using this switch, but I think this is just confusing and not very intuitive, users might just not know that `--force` output would be different)

Do you agree with the warning approach and would you think this was something that you could help us to implement (should be very easy) ?

Thanks !

**Comment by ventaquil** [comment]
Hey @philsmd 

Hmmm... Your idea with with this warning message looks great for me. I am thinking about small improvement which will show the beginning of the hash to help user to see how hash format looks like.

For example let's get some `LUKS` format (I trimmed hash to 256 characters and it looks fine and is readable even on small terminals).

```
Hash mode #29511
  Name................: LUKS v1 SHA-1 + AES
  Category............: Full-Disk Encryption (FDE)
  Slow.Hash...........: Yes
  Password.Len.Min....: 0
  Password.Len.Max....: 256
  Salt.Type...........: Embedded
  Salt.Len.Min........: 0
  Salt.Len.Max........: 256
  Kernel.Type(s)......: pure
  Example.Hash.Format.: plain
  Example.Hash........: [too long example hash for your terminal, use --machine-readable]
                        $luks$1$sha1$aes$cbc-essiv:sha256$128$151351$fe93ac0ab67cea12186b30980dd015a5652eec1ae0639aa34629c9e49118d235$4caf8f9e5a1fadff416b8ffe43d3a94b63c31b4740f2c391d282bab7cdb42177b1c601724811403b2692f9c32b17bc953ad6ea7a5e9c7799ec1eb8cf260f3c10be201b0eaf73d38...
  Example.Pass........: hashcat
  Benchmark.Mask......: ?b?b?b?b?b?b?b
  Autodetect.Enabled..: Yes
  Self.Test.Enabled...: Yes
  Potfile.Enabled.....: Yes
  Custom.Plugin.......: No
  Plaintext.Encoding..: ASCII, HEX
```

In my opinion idea with `--force` makes this option too powerful - another option could be added but should be different to do not confuse user (let's say it could be `--hash-info-full` or similar).

I think that I could prepare PR with this change - I hope to find some free time during next week.

**Comment by philsmd** [comment]
thanks, this looks much better now.

Your contributions @ventaquil are very much appreciated !
