### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by realprogrammersusevim** [hashcat/hashcat#3389]
The previous release was on November 21, 2021. The main reason that a new release is required is the large improvements that have been introduced thanks the to the hard work by @matrix with issue #3032 and issue #3044. The current release doesn't support the arm64 architecture in the M1 and M2 chips that are in all the Macs made by Apple in the last few years. Considering how popular these architectures are, (Apple claimed in it's Keynote that the MacBook Air is the single most popular laptop) and that the current head already supports it, a new release would bring large benefits at a trivial cost in time. Refer to the docs/changes.txt under "Features".

Now I will admit that it is possible to download the repository and compile it for yourself. However, that requires a lot of time to track down what's causing the problems and fix them. Creating a new release would also allow people using Homebrew to easily install hashcat. Currently, it still won't work even if you brew install with the --HEAD option.

To sum it all up, the repository has had large improvements that effect large amounts of users and that needs to be in the release.

**Hashcat version (please complete the following information):**
 - OS: macOS
 - Distribution: Monterey
 - Version: 12.4
 - Arch: arm64

**Comment by 0xVavaldi** [comment]
I want to second the release of a new beta at the very least

**Comment by philsmd** [comment]
beta versions are in general distributed over here: https://hashcat.net/beta/ and are most of the time quite up-to-date

Yeah, not sure about the date of the next release version. It's probably again just a matter of "it's ready when it's ready", but of course we will keep in mind your suggestion about the macOS improvement and the need for a new release version soonish.

**Comment by D4DB0DY** [comment]
> beta versions are in general distributed over here: https://hashcat.net/beta/ and are most of the time quite up-to-date
> 
> Yeah, not sure about the date of the next release version. It's probably again just a matter of "it's ready when it's ready", but of course we will keep in mind your suggestion about the macOS improvement and the need for a new release version soonish.

How do I compile the beta version? There are no instructions.

**Comment by realprogrammersusevim** [comment]
> > beta versions are in general distributed over here: https://hashcat.net/beta/ and are most of the time quite up-to-date
> > Yeah, not sure about the date of the next release version. It's probably again just a matter of "it's ready when it's ready", but of course we will keep in mind your suggestion about the macOS improvement and the need for a new release version soonish.
> 
> How do I compile the beta version? There are no instructions.

You're right, I tried good old `make` and that returned no Makefile. The beta doesn't actually include the source code files, only a hashcat.exe for Windows. A quick check in the Homebrew formula with `brew edit hashcat` shows that it actually just installs from the source code. It would definitely be nice to include a binary that people on GNU/Linux and macOS could use. Do we need to open a separate issue for that?

**Comment by philsmd** [comment]
The file `hashcat.bin` is a GNU/Linux binary (i.e. the executable for *NIX, like `hashcat.exe` on windows).

We have no pre-build macOS binaries because not many hashcat developers (main devs, I'm not speaking about users or contributers here, the "core devs") have such a system and furthermore we had problems with addressing different macOS versions, therefore the `brew` version or just `make` from `git`/`github` is the prefered way for these type of system.

**Comment by Chick3nman** [comment]
Minor release is now available.

**Comment by floam** [comment]
Minor release is *now* available, for anyone else confused.

**Comment by Chick3nman** [comment]
My bad, thanks for the catch @floam
