### ISSUE TITLE
#bug: simd destroy's -m 2500

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#339]
simd code destroy's -m 2500:

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: File (testlist)
Hash.Target....: File (test.hccap)
Hash.Type......: WPA/WPA2
Time.Started...: Tue May 17 09:53:34 2016 (3 mins, 10 secs)
Speed.Dev.#1...:    37100 H/s (15.29ms)
Recovered......: 0/382 (0.00%) Digests, 0/382 (0.00%) Salts
Recovered/Time.: CUR:0,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 7026508/7026508 (100.00%)
Rejected.......: 0/7026508 (0.00%)
HWMon.GPU.#1...:  0% Util, 58c Temp, N/A Fan

fresh install
rm -r $HOME/.hashcat/*
rm -r $HOME/.nv/*

GM108M [GeForce 940M]
driver 364.19
ARCH-LINUX

best regards
ZerBea

**Comment by jsteube** [comment]
What's the problem here?

**Comment by ZerBea** [comment]
I don't know. Did a update tomorrow from (v3.00-beta-11-gd0123e6+) to (v3.00-beta-25-gb5cb29a)
and none of my testlist word are found.

v3.00-beta-11-gd0123e6+:
Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: File (testlist)
Hash.Target....: File (test.hccap)
Hash.Type......: WPA/WPA2
Time.Started...: Tue May 17 10:21:44 2016 (3 mins, 8 secs)
Speed.Dev.#1...:    37612 H/s (15.31ms)
Recovered......: 382/382 (100.00%) Digests, 382/382 (100.00%) Salts
Recovered/Time.: CUR:120,N/A,N/A AVG:121.51,7290.55,174973.19 (Min,Hour,Day)
Progress.......: 7026508/7026508 (100.00%)
Rejected.......: 0/7026508 (0.00%)
HWMon.GPU.#1...:  0% Util, 57c Temp, N/A Fan

best regards
ZerBea

**Comment by jsteube** [comment]
try this one please:

http://hashcat.net/misc/example_hashes/hashcat.hccap

password is hashcat!

**Comment by ZerBea** [comment]
I'll check the git history to find the last working commit beetween beta 11 and beta 25 using hashcat.hccap

**Comment by ZerBea** [comment]
Last working commit (using hashcat.hccap and my my test.hccap) is:
https://github.com/hashcat/oclHashcat/commit/1d797a1c3e980922b2c048fed24969bcff8c3efc

Updating to this version causes the error in both (hashcat.hccap and my test.hccap):
https://github.com/hashcat/oclHashcat/commit/0ddb264a5ac0e9f09381062bb93f0b77fd099f3e

It seems, that packv() and unpackv() didn't work as expected.

best regards
ZerBea

**Comment by jsteube** [comment]
Fixed:

root@sf:~/hashcat# ./hashcat -m 2500 hashcat.hccap -a 3 'hashcat!'
hashcat (v3.00-beta-29-g18f05e9) starting...

Device #1: Hawaii, 2858/4025 MB allocatable, 1010Mhz, 44MCU
Device #2: AMD FX(tm)-8120 Eight-Core Processor, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
- Brute-Force
- Slow-Hash-SIMD
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 80c

ATTENTION!  
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       

hashcat.net:b0487ad676e2:0025cf2db489:hashcat!            

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: Mask (hashcat!) [8]
Hash.Target....: hashcat.net (b0:48:7a:d6:76:e2 <-> 00:25:cf:2d:b4:89)
Hash.Type......: WPA/WPA2
Time.Started...: Tue May 17 18:22:53 2016 (1 sec)
Speed.Dev.#1...:        0 H/s (0.64ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 1/1 (100.00%)
Rejected.......: 0/1 (0.00%)
HWMon.GPU.#1...:  0% Util, 37c Temp, 20% Fan

Started: Tue May 17 18:22:53 2016
Stopped: Tue May 17 18:22:56 2016
