### ISSUE TITLE
write "recovered new" value to session log

### ISSUE THREAD

**Issue by roycewilliams** [hashcat/hashcat#3392]
When specific attacks end, logging the new "Recovered.New" value for that session would be useful. It might be called `hashes->digests_done_new` or similar.

This would allow for analysis of attack performance per session.

**Comment by jsteube** [comment]
Main work here https://github.com/hashcat/hashcat/commit/a52b70d1c553ea4576bff101be5eb34f350323dc and here https://github.com/hashcat/hashcat/commit/bf0ffa66d73181a3286178b380f7fa6ffc14887c
