### ISSUE TITLE
the algorithm works from 8+ password characters

### ISSUE THREAD

**Issue by mobola1edu** [hashcat/hashcat#3393]
the algorithm works min 8+ password characters

![image](https://user-images.githubusercontent.com/80366344/180652388-b53f57b4-f63d-47b2-8bad-8c92f12a13ab.png)
![image](https://user-images.githubusercontent.com/80366344/180652424-29fc92a9-e9cf-40a9-954c-1bc72d633f2c.png)

How did I notice it?
Looked at: 
Candidates.#1....: **CLY** -> **CLY**
Candidates.#2....: **8Q** -> **82**
Candidates.#3....: 82,64~9266 -> **4h,64**

tested on 6.2.5 version and -S flag

**Comment by matrix** [comment]
yes, pw_min is 8

https://github.com/hashcat/hashcat/blob/master/src/modules/module_26600.c#L107-L112
