### ISSUE TITLE
Hash  unknown

### ISSUE THREAD

**Issue by DeLuca92** [hashcat/hashcat#3397]
Hello, I need help to discover this hash

bananadapassword:zg0hRAYjPZjP8BkiteoqTSE=::8bb53db42dcc97ae5a30f36c95ac5e3name

**Comment by ozypl** [comment]
Your hash may be one of the following:
- Cisco-ASA(MD5)
- DES
- 3DES
https://www.onlinehashcrack.com/hash-identification.php

**Comment by matrix** [comment]
> Hello, I need help to discover this hash
> 
> bananadapassword:zg0hRAYjPZjP8BkiteoqTSE=::8bb53db42dcc97ae5a30f36c95ac5e3name

Please use forum or discord for these kinds of questions
