### ISSUE TITLE
adding support for Blake2s-256 

### ISSUE THREAD

**Issue by kksm623** [hashcat/hashcat#3414]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**
The hashing function blake2s-256 is a public known hash algorithm on Wikipedia.
- The hashing function has been implemented in Python hashlib standard library.

**Describe alternatives you've considered**
Currently we use Python scripts for hashing, and it is extremely slow.

**Provide an example hash/database/file and a known correct password**
2c719b484789ad5f6fc1739012182169b25484af156adc91d4f64f72400e574a:hashcat

**Explain how the cryptographic schema is implemented**
def gethash(message:str):
    data = message
    return blake2s(data.encode("utf-8")).hexdigest()

**Describe the known limitations of the algorithm**
The maximum output length is 32 bytes, max key length is 16bytes. No limitations to input.

**Where do you typically find the algorithm**
Python hashlib, OPENSSL and CryptoPP.

**Additional context**
There is currently a github repo https://github.com/wfr/clblake, but we failed to port it to hashcat.

**Comment by Zgzorx** [comment]
Hi ! I would like to contribute, is the issue still available ?

**Comment by Zgzorx** [comment]
Issue resolved by PR: https://github.com/hashcat/hashcat/pull/3616
