### ISSUE TITLE
Hashcat is having trouble running on my system

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3418]
I try to run hashcat on my hostOS, (Manjaro)
My GPU is a RTX3080

And this is the output:

hashcat (v6.2.5) starting

CUDA API (CUDA 11.7)
====================
* Device #1: NVIDIA GeForce RTX 3080, 9038/10014 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 11.7.101) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: NVIDIA GeForce RTX 3080, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 31

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Optimized-Kernel
* Zero-Byte
* Precompute-Init
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1474 MB

Dictionary cache hit:
* Filename..: /home/xatt/wordlists/rockyou.txt
* Passwords.: 14344384
* Bytes.....: 139921497
* Keyspace..: 14344384

Approaching final keyspace - workload adjusted.           

Session..........: hashcat                                
Status...........: Exhausted
Hash.Mode........: 0 (MD5)
Hash.Target......: bf215ae939529608d188c106b656b71b
Time.Started.....: Thu Aug 11 13:47:37 2022 (4 secs)
Time.Estimated...: Thu Aug 11 13:47:41 2022 (0 secs)
Kernel.Feature...: Optimized Kernel
Guess.Base.......: File (/home/xatt/wordlists/rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:  5058.5 kH/s (0.04ms) @ Accel:2048 Loops:1 Thr:32 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 14344384/14344384 (100.00%)
Rejected.........: 3094/14344384 (0.02%)
Restore.Point....: 14344384/14344384 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: $HEX[287465786173296c6f6e67686f726e73] -> $HEX[042a0337c2a156616d6f732103]
Hardware.Mon.#1..: Temp: 61c Fan:  0% Util: 10% Core:1800MHz Mem:9501MHz Bus:16

Started: Thu Aug 11 13:47:37 2022
Stopped: Thu Aug 11 13:47:41 2022

**Comment by ghost** [comment]
The hash is MD5 and text is "iloveyou" just to test if it works.

**Comment by paulouderkirk** [comment]
The MD5 hash for "iloveyou" is: 
```
% echo -n iloveyou | md5
f25a2fc72690b780b2a14e140ef6a9e0
```

The hash you listed (bf215ae939529608d188c106b656b71b) is produced by MD5 hashing "krijgkanker"

```
% echo -n krijgkanker | md5
bf215ae939529608d188c106b656b71b  -
```

**Comment by ghost** [comment]
oh, a friend send me that as hash. I thought I replaced it with "Iloveyou"
Thank you for the response.
