### ISSUE TITLE
Module unstable warnings should be revisited for new AMD ROCr-based OpenCL

### ISSUE THREAD

**Issue by davidbolvansky** [hashcat/hashcat#3420]
As I reported in https://github.com/hashcat/hashcat/commit/95489b0473044db91c46d2aabc9d3d6c3426ca36#diff-26f199e5757858731172b87dd2d7f762dc604af11fc090bdbbcf3f623f6dd425

Current warnings might be OK for legacy, but not for ROCr-based OpenCL. I tried some experiments with "unstable" hash modes and they worked fine with --force. Current code comments suggest that warnings are based on experiments with legacy OpenCL...

What I see now for "hashcat -b -m 1500" (Vega 64, ROCm 5.0):
```
* Hash-Mode 1500 (descrypt, DES (Unix), Traditional DES)
--------------------------------------------------------

* Device #1: Skipping (hash-mode 1500)
             This is due to a known OpenCL runtime and/or device driver issue (not a hashcat issue)
             You can use --force to override, but do not report related errors.

```

With --force (no crashes, no bugs)
```
* Hash-Mode 1500 (descrypt, DES (Unix), Traditional DES)
--------------------------------------------------------

Speed.#1.........:   230.0 MH/s (63.46ms) @ Accel:4 Loops:1024 Thr:64 Vec:1
Speed.#2.........:   228.8 MH/s (63.77ms) @ Accel:4 Loops:1024 Thr:64 Vec:1
Speed.#3.........:   230.5 MH/s (63.30ms) @ Accel:4 Loops:1024 Thr:64 Vec:1
Speed.#*.........:   689.3 MH/s
```

So looks like the warnings are too strong/invalid for AMD ROCr OpenCL. These warnings needs to be regenerated again. Do you have any script for that?

rocminfo: https://pastebin.com/5xtjyLv5

**Comment by jsteube** [comment]
Can confirm, works on my Vega as well. Probably driver update patched it. Removed with commit https://github.com/hashcat/hashcat/commit/c3e18f7fed1e54ec3e7705b047197c9f62ed9add

We are using test.sh script to generate these kind of tests. If you see any other plugins that are fixed let me know or send a PR.

**Comment by davidbolvansky** [comment]
@jsteube thanks! AMD driver is much better now, it seems. I tried hashcat benchmark all with --force:
https://pastebin.com/zy3ufS0G
=> Looks like there is no broken hash mode. Results without --force: https://pastebin.com/K9qPN31N

So.. here is the list of hash modes where hashcat warns but they actually work:
```
3710
3711
4010
4110
6100
6231
6232
6233
7700
7701
7800
7801
7900
8900
13100
14400
15300
15310
16000
17200
17220
17225
18100
18200
19500
21800
22500
22700
23900
27700
29331
29332
29333
```

**Comment by davidbolvansky** [comment]
Sent PR
https://github.com/hashcat/hashcat/pull/3421
