### ISSUE TITLE
HIPRTC Removed from AMD GPU's

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [hashcat/hashcat#3428]
Note, that I did not include my system for security reasons. i.e., The C:\Users thing.

`` .\hashcat.exe -m 0 -a 0 hashes.txt rockyou.txt``
``hashcat (v6.2.5) starting``

``hiprtcAddNameExpression is missing from HIPRTC shared library``.

``OpenCL API (OpenCL 2.1 AMD-APP (3444.0)) - Platform #1 [Advanced Micro Devices, Inc.]``
``=====================================================================================``
``* Device #1: AMD Radeon RX 5700 XT, 8064/8176 MB (6732 MB allocatable), 20MCU``

``Minimum password length supported by kernel: 0``
``Maximum password length supported by kernel: 256``

``Hash 'hashes.txt': Token length exception``
``No hashes loaded.``

**Comment by De-Been-Tech-Solutions** [comment]
Yeah, I just tried to install it on a VM of Linux Mint and it refused to install complaining that libdrm and its dependencies are missing...

**Comment by jsteube** [comment]
HIP works fine on AMD stable WHQL drivers. Do not use beta drivers. Please do not forget to close this issue if fixed after drivers change.

**Comment by lnaphade** [comment]
where is the updated HIPRTC removed windows binary build, i am able to see only 2021 build in release portal???

**Comment by jsteube** [comment]
As always, you can find beta binary build on hashcat.net/beta

**Comment by SalAndras** [comment]
using Adrenalin Edition 22.5.1 (exactly) worked for me.

**Comment by ucflumm** [comment]
There are new WHQL drivers 22.11.2 ; not saying they work though.

**Comment by anon-0racle** [comment]
> There are new WHQL drivers 22.11.2 ; not saying they work though.

They don't, running that exact driver version and have the same error OP reported.

"hiprtcAddNameExpression is missing from HIPRTC shared library"

**Comment by jsteube** [comment]
I've talked to some AMD developers. They dropped HIPRTC from Windows without giving an exact reason. If you want to use HIP (what I recommend), then you need to use Linux or use the latest Windows driver that is known to work (Adrenalin 22.5.1). I'll update the documentation accordingly.

**Comment by roycewilliams** [comment]
@jsteube Is it possible for hashcat to detect this and give explicit advice? If so, I think this would be very useful to include _before_ the upcoming next release.
/cc @Chick3nman 
Update: added in 6ad36db9bac451ad5586c8f3e406a9bdfceb88cb

**Comment by tcsabina** [comment]
I just came across this thread googling on '_hiprtcCompileProgram is missing from HIPRTC shared library._'
Some say that you need in install the HIP SDK from AMD: https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html

Would that help with this issue? Or the problem is that the driver doesn't contain anymore what is needed for hashcat, so installing the SDK would do nothing?

**Comment by Shazgul** [comment]
> I just came across this thread googling on '_hiprtcCompileProgram is missing from HIPRTC shared library._' Some say that you need in install the HIP SDK from AMD: https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
> 
> Would that help with this issue? Or the problem is that the driver doesn't contain anymore what is needed for hashcat, so installing the SDK would do nothing?

I've installed the HIP SDK and still getting this Error, anyone can help?

**Comment by Paradigm00** [comment]
same with adrenalin edition 24.1.1 and HIP SDK 5.7.0

**Comment by bojtalepenye** [comment]
> using Adrenalin Edition 22.5.1 (exactly) worked for me.

However I have 24.1.1 installed, how can I downgrade?

**Comment by dontholdmyhand** [comment]
I get this error but my cracking still runs normally? i think? 6600xt

**Comment by pwaechtler** [comment]
From what I understand so far:

The older HIP drivers offered a method to "compile a program" for the specific device (graphics card).
I guess it was never used - and a brave developer decided to remove it.

The upper layers use clang/llvm/nvcc to compile a program that gets pushed "down" to the device.
The driver was never able to "compile" a program itself (llvm with gfx1??? target).

The first HC_LOAD_FUNC macro produces the error output and can be removed.

src/ext_hiprtc.c
int hiprtc_init (void *hashcat_ctx)
{
...
  if (hiprtc->lib == NULL) return -1;

  HC_LOAD_FUNC (hiprtc, hiprtcCompileProgram,     HIPRTC_HIPRTCCOMPILEPROGRAM,    HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcCreateProgram,      HIPRTC_HIPRTCCREATEPROGRAM,     HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcDestroyProgram,     HIPRTC_HIPRTCDESTROYPROGRAM,    HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcGetCode,            HIPRTC_HIPRTCGETCODE,           HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcGetCodeSize,        HIPRTC_HIPRTCGETCODESIZE,       HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcGetProgramLog,      HIPRTC_HIPRTCGETPROGRAMLOG,     HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcGetProgramLogSize,  HIPRTC_HIPRTCGETPROGRAMLOGSIZE, HIPRTC, 1);
  HC_LOAD_FUNC (hiprtc, hiprtcGetErrorString,     HIPRTC_HIPRTCGETERRORSTRING,    HIPRTC, 1);
