### ISSUE TITLE
Metamask Token length exception

### ISSUE THREAD

**Issue by qweDisgustin** [hashcat/hashcat#3429]
i have 26600 hash, but it had very big data, bcs user create 1000 adresses in him metamask
![image](https://user-images.githubusercontent.com/111783561/185981104-c8b697fc-9823-489c-b981-bc1acd5c1a76.png)
how i can cut or normalize the hash? or what is this...

**Comment by qweDisgustin** [comment]
https://github.com/hashcat/hashcat/issues/2818#issuecomment-877128049
checked this, so my data is to big for hashcat. It have >7000 symblos! Is there any variants, @matrix ?

**Comment by qweDisgustin** [comment]
https://github.com/hashcat/hashcat/issues/2818#issuecomment-877128049
checked this, so my data is to big for hashcat. It have >7000 symblos! Is there any variants, @matrix ?

**Comment by ventaquil** [comment]
Hey

From my quick analysis it should be possible with cutting your data to about 450 bytes.

Test script

```py
#!/usr/bin/env python3

from base64 import b64decode
from hashlib import pbkdf2_hmac

from Crypto.Cipher import AES 


vault = {'data': 'lgg/TjYLK52cncJQwpOv8US55yGvGaIzT/daqaxJvBHxsO3tj2Ga8b15+Wl3hW9hr5E1ByLW9hmwKRtt15o5NJnswcT/6Wr36+NyNJZDOozQsRN3G9gvAvvIMRoiX2WRXxYbNwwpC3lfZkMEHuEh5Kq7X9BHFYCxnyOasXtNdDSijA86V77MKJsblUd4kiBAohNrHWasIoGNLA3Y5VlaJyr4zl4l8h+g3I+ocx0ZVC6mIg79zraPSDNHGpDSFpG/dqEERRkJBbVqAsIbStAYAvu7eLKUNbgra9h9RAPIAv4Omde1eMFP8chslpGDE1wVV45ikzfLY/JW4yj5NcM1vUExhG1ZAU6zdTn/Srwn+DJZScgZ3XeiAmEIf5tMEpQCBCMngDNhaEWGsLByyeH7HWoB9sOUxOx2ivhojHZWYfoPsZ23So0nsw5ACS7xD852f8Nd6eWahITUUCNgzFNhwjX02Nh03jFzWsUnIScK6IAoD/V/iBWGqwkSIBG8uSHwOwell3fu4eY7JXSLYZ1SJbexQW2QwQLpVyiyU19K/wmvT1RpSK6yr4a/UFj8UX4T/V2SnWsHntGStA/IQUUfrLAwwCu8pswcGUUpqZ+KAXd+1ZE6NEEqMMwQJD/QUuiwPTfRR+FsIxqzms5Mn3CXlFCJX1C0VWdRoBsk3R2MS6G8vdEvgMk/iZISktCAfxuGpuB5XRAHePYw7otTC/5F', 'iv': 'rnaYg9MRgqdWkt2rKrATtA==', 'salt': 'GDpvDT4msNOqcZtOBz4kccLC3QY2wjfd5s7l1zzchqM='}

password = "Hasło123!"
salt = b64decode(vault["salt"])
key = pbkdf2_hmac("sha256", password.encode(), salt, 10_000)

iv = b64decode(vault["iv"])
payload = b64decode(vault["data"])
ciphertext = payload[:-16]
tag = payload[-16:]

cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
plaintext = cipher.decrypt(ciphertext)
try:
    cipher.verify(tag)
    print("The message is authentic:", plaintext.decode())
except ValueError:
    print("Key incorrect or message corrupted")

cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
plaintext = cipher.decrypt(ciphertext[:32])
print("Partially encrypted message (32 bytes):", plaintext.decode())

cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
plaintext = cipher.decrypt(ciphertext[:450])
print("Partially encrypted message (450 bytes):", plaintext.decode())
```

Output

```
The message is authentic: [{"type":"HD Key Tree","data":{"mnemonic":[99,97,114,103,111,32,103,97,114,108,105,99,32,117,114,103,101,32,116,111,112,32,100,101,112,117,116,121,32,97,119,107,119,97,114,100,32,106,97,114,32,99,111,117,114,115,101,32,102,117,110,32,102,97,114,109,32,116,117,98,101,32,108,101,97,114,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https://metamask.github.io/eth-ledger-bridge-keyring","implementFullBIP44":false}}]
Partially encrypted message (32 bytes): [{"type":"HD Key Tree","data":{"
Partially encrypted message (450 bytes): [{"type":"HD Key Tree","data":{"mnemonic":[99,97,114,103,111,32,103,97,114,108,105,99,32,117,114,103,101,32,116,111,112,32,100,101,112,117,116,121,32,97,119,107,119,97,114,100,32,106,97,114,32,99,111,117,114,115,101,32,102,117,110,32,102,97,114,109,32,116,117,98,101,32,108,101,97,114,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https:
```

Script requires PyCryptodome library and contains new, empty MetaMask vault.

I am assuming that new mode (probably 26610?) should be created - instead of checking tag we can do some entropy check or validation of partially valid JSON structure.

Some very quick (and very inaccurate) check is to verify that decrypted text starts with `[{"type":"HD Key Tree"` (or contains `"HD Key Tree"` in first few bytes).

**Comment by thatux** [comment]
This should work https://github.com/hashcat/hashcat/pull/3628 please provide some reference wallet if it doesn't

**Comment by jsteube** [comment]
I probably would have solved the issue differently. But the implementation as it is now is good and it looks like you spent some time implementing it. I'll merge the PR.

However, and you might still want to implement my notes as an add-on, I would have just thrown out the original 26000 method of checking the GCM tag. The main argument is that if the 26610 method is just as reliable as the original 26600, why should we keep the old one. Sure, GCM tags are perfect for hashcat, but from a min/max perspective, your approach is better.

Thanks for the contribution!

**Comment by thatux** [comment]
Thanks, and thanks for your notes, I agree, one could keep the hash signature the same, decode the base64 in module_26600.c and only attack the first block. I didn't want to inadvertently cause some wierd behavior in 26600 but I'll feel free to do so next time.

The only downside of doing that is the (huge) size of hashes (>7kb of b64). Not sure if $metamask is implemented elsewhere I'm hesitant on changing the hash structure without changing the hash-signature.

**Comment by BTGMiningUSA** [comment]
> Hey
> 
> From my quick analysis it should be possible with cutting your data to about 450 bytes.
> 
> Test script
> 
> ```python
> #!/usr/bin/env python3
> 
> from base64 import b64decode
> from hashlib import pbkdf2_hmac
> 
> from Crypto.Cipher import AES 
> 
> 
> vault = {'data': 'lgg/TjYLK52cncJQwpOv8US55yGvGaIzT/daqaxJvBHxsO3tj2Ga8b15+Wl3hW9hr5E1ByLW9hmwKRtt15o5NJnswcT/6Wr36+NyNJZDOozQsRN3G9gvAvvIMRoiX2WRXxYbNwwpC3lfZkMEHuEh5Kq7X9BHFYCxnyOasXtNdDSijA86V77MKJsblUd4kiBAohNrHWasIoGNLA3Y5VlaJyr4zl4l8h+g3I+ocx0ZVC6mIg79zraPSDNHGpDSFpG/dqEERRkJBbVqAsIbStAYAvu7eLKUNbgra9h9RAPIAv4Omde1eMFP8chslpGDE1wVV45ikzfLY/JW4yj5NcM1vUExhG1ZAU6zdTn/Srwn+DJZScgZ3XeiAmEIf5tMEpQCBCMngDNhaEWGsLByyeH7HWoB9sOUxOx2ivhojHZWYfoPsZ23So0nsw5ACS7xD852f8Nd6eWahITUUCNgzFNhwjX02Nh03jFzWsUnIScK6IAoD/V/iBWGqwkSIBG8uSHwOwell3fu4eY7JXSLYZ1SJbexQW2QwQLpVyiyU19K/wmvT1RpSK6yr4a/UFj8UX4T/V2SnWsHntGStA/IQUUfrLAwwCu8pswcGUUpqZ+KAXd+1ZE6NEEqMMwQJD/QUuiwPTfRR+FsIxqzms5Mn3CXlFCJX1C0VWdRoBsk3R2MS6G8vdEvgMk/iZISktCAfxuGpuB5XRAHePYw7otTC/5F', 'iv': 'rnaYg9MRgqdWkt2rKrATtA==', 'salt': 'GDpvDT4msNOqcZtOBz4kccLC3QY2wjfd5s7l1zzchqM='}
> 
> password = "Hasło123!"
> salt = b64decode(vault["salt"])
> key = pbkdf2_hmac("sha256", password.encode(), salt, 10_000)
> 
> iv = b64decode(vault["iv"])
> payload = b64decode(vault["data"])
> ciphertext = payload[:-16]
> tag = payload[-16:]
> 
> cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
> plaintext = cipher.decrypt(ciphertext)
> try:
>     cipher.verify(tag)
>     print("The message is authentic:", plaintext.decode())
> except ValueError:
>     print("Key incorrect or message corrupted")
> 
> cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
> plaintext = cipher.decrypt(ciphertext[:32])
> print("Partially encrypted message (32 bytes):", plaintext.decode())
> 
> cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
> plaintext = cipher.decrypt(ciphertext[:450])
> print("Partially encrypted message (450 bytes):", plaintext.decode())
> ```
> 
> Output
> 
> ```
> The message is authentic: [{"type":"HD Key Tree","data":{"mnemonic":[99,97,114,103,111,32,103,97,114,108,105,99,32,117,114,103,101,32,116,111,112,32,100,101,112,117,116,121,32,97,119,107,119,97,114,100,32,106,97,114,32,99,111,117,114,115,101,32,102,117,110,32,102,97,114,109,32,116,117,98,101,32,108,101,97,114,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https://metamask.github.io/eth-ledger-bridge-keyring","implementFullBIP44":false}}]
> Partially encrypted message (32 bytes): [{"type":"HD Key Tree","data":{"
> Partially encrypted message (450 bytes): [{"type":"HD Key Tree","data":{"mnemonic":[99,97,114,103,111,32,103,97,114,108,105,99,32,117,114,103,101,32,116,111,112,32,100,101,112,117,116,121,32,97,119,107,119,97,114,100,32,106,97,114,32,99,111,117,114,115,101,32,102,117,110,32,102,97,114,109,32,116,117,98,101,32,108,101,97,114,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https:
> ```
> 
> Script requires PyCryptodome library and contains new, empty MetaMask vault.
> 
> I am assuming that new mode (probably 26610?) should be created - instead of checking tag we can do some entropy check or validation of partially valid JSON structure.
> 
> Some very quick (and very inaccurate) check is to verify that decrypted text starts with `[{"type":"HD Key Tree"` (or contains `"HD Key Tree"` in first few bytes).

Has anyone been successful in trimming a metamask hash?

**Comment by thatux** [comment]
Yes 26610 was implemented specifically to solve this.
Use https://github.com/hashcat/hashcat/blob/master/tools/metamask2hashcat.py with --short-data.

This issue should be closed

**Comment by BTGMiningUSA** [comment]
One last question. Would it be possible to speed up 26600 and how can it be done?
