### ISSUE TITLE
md5(md5($pass).$salt) -> algorithm request

### ISSUE THREAD

**Issue by andreamoreto** [hashcat/hashcat#343]
I'm requesting support for this algorithm : 
md5(md5($pass).$salt)

This is the 2nd time I face it, I guess that it's popular, as it is listed on the "Hash-a-password" tool results, from hashkiller uk. Furthermore, md5($salt.md5($pass))  is already supported by hashcat ...

here is the code :
`$password = md5(md5($user['password']). $PASS_SALT );
if (isset($_POST['password']) && md5(md5($_POST['password']).$PASS_SALT) == $password){
...`

In this particular case, the salt is a md5 like value, created from the surname, iow, the length is 32.

ad1f95326d65ee793fa347ab7345b246:fc13de57255bed2c26fb5edaa3733640 takealunch
f84dec8b20b7ea511cb0085f0ec0afcc:3e6affc692019dc8d476111d25872fa1 oscar1017
5b4ea443ca4d325b60e9d95ce4c0943c:81599f2145e887463733f2810f6a8c72 N3V3R_m0r3

Thanks,

**Comment by epixoip** [comment]
md5(md5(p).s) is already supported by -m 2711. Oh, but it expects a 30-char salt doesn't it. We could probably just add a generic md5(md5(p).s) mode that isn't optimized for vBull.

**Comment by jsteube** [comment]
I'd think it's much more easy to create a hash-mode md5(md5($password).md5($salt) ); because this forces the length to exact 64.

**Comment by andreamoreto** [comment]
> I'd think it's much more easy to create a hash-mode md5(md5($password).md5($salt) )

... but this algorithm is already supported by 3910 , am i correct ? It will not work in this case.

**Comment by jsteube** [comment]
> ... but this algorithm is already supported by 3910 , am i correct ? It will not work in this case.

In Hashcat maybe, but not in oclHashcat. Why isn't it working? It's exactly what you've described

**Comment by magnumripper** [comment]
@jsteube the salt here is **already** an MD5. So basically (in oclHashcat's view) the requested format is 
md5(md5($pass).$salt) where $salt is 32 characters. For oclHashcat, the fact that the salt is an MD5 is more or less irrelevant except for the support of length.

**Comment by jsteube** [comment]
@magnumripper you sure about that? He said:

> the salt is a md5 like value, created from the surname

If we make it generic, and the length is known to be 32 or more, then the mode must be implemented with a second transformation. In such a case, the length of the salt _always_ must be at least of length 32 which is too strange for a generic mode. Therefore I think it's better to have a named hash-type and then we need to know which appliation uses this.

**Comment by magnumripper** [comment]
> @magnumripper you sure about that? He said:
> 
> > the salt is a md5 like value, created from the surname

He also said

> > the length is 32

His example hashes indicate the salt is stored as ready-to-use MD5:

```
ad1f95326d65ee793fa347ab7345b246:fc13de57255bed2c26fb5edaa3733640 takealunch
f84dec8b20b7ea511cb0085f0ec0afcc:3e6affc692019dc8d476111d25872fa1 oscar1017
5b4ea443ca4d325b60e9d95ce4c0943c:81599f2145e887463733f2810f6a8c72 N3V3R_m0r3
```

It's not 100% clear from the OP whether we know the surname so we can calculate the salt ourselves. @andreamoreto please clarify!

**Comment by andreamoreto** [comment]
As I stated before, this is the 2nd time I face this algorithm.  On the first time the salt was a random md5.

Now, due this curious salting method I can use the surname as salt and follow jsteube's suggestion. 

In my opinion this algorithm,  if accepted,  should be a generic one, as I found it on 2 distinct applications.

**Comment by BoBeR182** [comment]
I also ran into a database that uses `md5(md5($pass).$salt)` but the salt was 3 characters so I cannot use `-m 2711`

How can I implement this by hand.

**Comment by xinhuang** [comment]
I also came across a case where the format is `md5(md5($pass).$salt)`, in which the `$salt` is of 6 chars.

Is it possible to have a generic mode for such cases by specifying the salt pattern? Thanks!

**Comment by jsteube** [comment]
@xinhuang You should be able to load this hash already with latest version when using mode 2611

**Comment by jsteube** [comment]
Should work fine using -m 2611
