### ISSUE TITLE
m 150/160 HMAC SHA1 token length exception

### ISSUE THREAD

**Issue by AMAT0RY** [hashcat/hashcat#3433]
You can encrypt a lot of characters into a hash message, my message contains 500-1000, and hashcat only support 256. I also saw the messages of a person who has 7000 characters in the message. https://forum.exetools.com/showthread.php?p=118136
Example: 800 length
`b43819b4b6eeb204028e30130be6216cc1152ef1:11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111`
Secret key = 123

**Comment by AMAT0RY** [comment]
![image](https://user-images.githubusercontent.com/81570058/187347162-b3380655-5ba0-448d-9ae8-68e9ff7bc49e.png)

**Comment by AMAT0RY** [comment]
![image](https://user-images.githubusercontent.com/81570058/187347237-207b8b1a-8067-4617-b6ba-c85c38ed0f6f.png)

**Comment by jsteube** [comment]
Correct, for general purpose cracking the limit is 256. For oversized message you have to create a new plugin using an esalt. This causes performance drops, which is why we separate it.
