### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE on Intel - beta 15

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#344]
Some log: 

C:\Users\mangix\Downloads\hashcat-3.00>hashcat64 -b --opencl-device-types=1
hashcat (v3.00-beta-32-gde2074d) starting in benchmark-mode...

Device #1: GeForce GTX 750 Ti, skipped
Device #2: Intel(R) Pentium(R) CPU G3258 @ 3.20GHz, 2027/8110 MB allocatable, 3200Mhz, 2MCU

1 error generated.

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -cl-std=CL1.1 -I"C:\Users\mangix\Downloads\hashcat-3.00/" -DVENDOR_ID=8 -DCUDA_ARCH=0 -DVECT_SIZE=4 -DDEVICE_TYPE=2 -DKERN_TYPE=900 -D_unroll -cl-opt-disable ===

=== Build Log (start) ===
Compilation started
In file included from 1:19:
./OpenCL/types_ocl.c:604:10: error: requested shift is a vector of type 'const u32x' (aka 'const uint4') but the first operand is not a vector ('int')
./OpenCL/types_ocl.c:602:39: note: expanded from macro 'BFE'
./OpenCL/types_ocl.c:601:24: note: expanded from macro 'BIT_MASK'
./OpenCL/types_ocl.c:600:26: note: expanded from macro 'BIT'
Compilation failed

=== Build Log (end) ===
Device #2: Kernel C:\Users\mangix\Downloads\hashcat-3.00/OpenCL/m00900_a3.cl build failure. Proceed without this device.
Hashtype: MD4

1 error generated.

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -cl-std=CL1.1 -I"C:\Users\mangix\Downloads\hashcat-3.00/" -DVENDOR_ID=8 -DCUDA_ARCH=0 -DVECT_SIZE=4 -DDEVICE_TYPE=2 -DKERN_TYPE=0 -D_unroll -cl-opt-disable ===

=== Build Log (start) ===
Compilation started
In file included from 2:19:
./OpenCL/types_ocl.c:604:10: error: requested shift is a vector of type 'const u32x' (aka 'const uint4') but the first operand is not a vector ('int')
./OpenCL/types_ocl.c:602:39: note: expanded from macro 'BFE'
./OpenCL/types_ocl.c:601:24: note: expanded from macro 'BIT_MASK'
./OpenCL/types_ocl.c:600:26: note: expanded from macro 'BIT'
Compilation failed

=== Build Log (end) ===
Device #2: Kernel C:\Users\mangix\Downloads\hashcat-3.00/OpenCL/m00000_a3.cl build failure. Proceed without this device.
Hashtype: MD5

Started: Tue May 17 16:19:00 2016
Stopped: Tue May 17 16:19:03 2016

C:\Users\mangix\Downloads\hashcat-3.00>

**Comment by jsteube** [comment]
Should be fixed, thanks for report
