### ISSUE TITLE
Flask Session Cookie (Mode 29100) Token Length Too Small

### ISSUE THREAD

**Issue by IppSec** [hashcat/hashcat#3440]
The maximum payload size for this module is 27, which is the exact length used in the example:
```
{
  "username": "admin"
}
```
If the username is longer than admin or there are any more data in the payload than above hashcat says it is an invalid hash.  JWT is a very similar format and supports lengths up to 2047 for each token field.

**Comment by Chick3nman** [comment]
Closing as fixed, https://github.com/hashcat/hashcat/pull/3441 was merged into master.
