### ISSUE TITLE
Feature request: Document/warn that Association attacks don't support potfiles

### ISSUE THREAD

**Issue by tomspencer** [hashcat/hashcat#3447]
As the Association attack is the only mode to not support pot files, I would suggest at least documenting that divergence clearly and explicitly at least in the README and hashcat -h text.

It may even make sense to call it out during the runtime operation as this would be the most user-facing.

Thanks!

**Comment by Chick3nman** [comment]
Closing as fixed, https://github.com/hashcat/hashcat/pull/3446 was merged
