### ISSUE TITLE
Feature request: Support pot files for Association attacks

### ISSUE THREAD

**Issue by tomspencer** [hashcat/hashcat#3449]
As the title says, the request is to align the behavior of the Association attack to the other attack modes and support pot files.

**Comment by Chick3nman** [comment]
Currently I believe the reason we do not support potfiles is because we don't support removing/rejecting hashes, salts, or candidates in Association Attack mode. From a technical standpoint, this may be fairly complicated to add and will likely require some fundamental changes to how the attack mode works.

**Comment by tomspencer** [comment]
Hello @jsteube, as far as I can tell this has not been "completed" as in resolved, is this being closed as WONTFIX? If so, I get it, it may not be worth the refactor - I just want to make sure I understand.

There was also a separate issue for documenting/warning about potfiles not working in associate mode (https://github.com/hashcat/hashcat/issues/3447) which was previously closed completed by @Chick3nman since those warnings have been added, but this one was specifically about making potfiles work with -a 9.

**Comment by Chick3nman** [comment]
I spoke with @jsteube earlier and this was indeed closed as a "wont fix" for now. The technical limitations are too significant to add this as a feature. Apologies for the confusion, I was also surprised to see this closed as "completed".

**Comment by tomspencer** [comment]
Thanks @Chick3nman, i get it, and appreciate the clarification.
