### ISSUE TITLE
Signature (.asc) of release v6.2.6 missing

### ISSUE THREAD

**Issue by freswa** [hashcat/hashcat#3452]
The release is missing a gpg signature on the release page: https://hashcat.net/hashcat/
The .asc link only redirects and doesn't contain a signature.

**Comment by jsteube** [comment]
should be fixed. please retry and close if fixed. thanks for reporting!

**Comment by heftig** [comment]
Works now (with curl), but my browser doggedly refuses to request the now-present content because it cached the `301 Moved Permanently`. Given that there's no `Cache-Control` directive, this has no expiry date.

I think the server should respond with 404, or if you absolutely need a redirect, 302.
