### ISSUE TITLE
--status-json output is not properly escaped

### ISSUE THREAD

**Issue by s77rt** [hashcat/hashcat#3453]
**Describe the bug**
Some fields of `--status-json` output are not being escaped, this includes:
[session](https://github.com/hashcat/hashcat/blob/d04dec91d13f55d3800684666b22f8eb81f0bced/src/terminal.c#L1831)
[guess_base](https://github.com/hashcat/hashcat/blob/d04dec91d13f55d3800684666b22f8eb81f0bced/src/terminal.c#L1835)
[guess_mod](https://github.com/hashcat/hashcat/blob/d04dec91d13f55d3800684666b22f8eb81f0bced/src/terminal.c#L1849)

**To Reproduce**
Just run hashcat with `--status-json`
+ref: https://github.com/s77rt/hashcat.launcher/issues/101

**Expected behavior**
fields to be JSON escaped

**Hashcat version:**
 - Version: 6.2.6 and d04dec91d13f55d3800684666b22f8eb81f0bced
**UPDATE** Version 6.2.5 or even earlier are also effected (session field only since other fields did not exist)

**Comment by Chick3nman** [comment]
Do you have an example where they aren't being escaped properly? I don't believe "session" has changed between 6.2.5 and 6.2.6 so behavior should be the same as it always was.

**Comment by s77rt** [comment]
For the example check the linked ref.
For the "session" field see the update.

Here are few examples for the session field:
1. in an attempt to set the session name to: **test\\md5**
`./hashcat.bin -m 0 -t 32 -a 7 example0.hash ?a?a?a?a example.dict --status-json --session test\\md5`
Returns:
`{ "session": "test\md5" }` ==> **testmd5**

1. in an attempt to set the session name to: **test\\md5\\**
`./hashcat.bin -m 0 -t 32 -a 7 example0.hash ?a?a?a?a example.dict --status-json --session test\\md5\\`
Returns:
`{ "session": "test\md5\" }` ==> **INVALID JSON**

**Comment by Chick3nman** [comment]
Ahh, I see the problem, thanks for the example values. Should be an easy enough fix.

**Comment by davidbolvansky** [comment]
Posted https://github.com/hashcat/hashcat/pull/3456 to fix this issue.
