### ISSUE TITLE
Empty LUKS container is unbreakable

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#3455]
**Describe the bug**

Empty LUKS container is unbreakable.

**To Reproduce**

1. Create new LUKS disk image.
```
dd if=/dev/zero of=/tmp/empty-luks.img bs=1M count=4K status=progress
```
2. Mount disk image as loop device.
```
losetup -fP --show /tmp/empty-luks.img
```
3. Create new LUKS container.
```
cryptsetup luksFormat -v --type luks1 /dev/loop5  # <-- fill with your loop device
```
4. Extract container's hash.
```
python3 luks2hashcat.py /tmp/empty-luks.img > empty-luks.hash
```
5. Close loop device.
```
losetup -d /dev/loop5  # <-- fill with your loop device
```
6. Check `empty-luks.hash`.
```
$luks$1$sha256$aes$xts-plain64$512$3449262$f33c64316ff43e1f2d0c0...f60ca0ee$00000000...00000000
```

Zeroes at the end makes it unbreakable since header's payload is empty.

**Expected behavior**

`luks2hashcat.py` should return an error.

**Hashcat version:**
 - OS: Linux
 - Distribution: Ubuntu 20.04
 - Version: 6.2.6

**Additional context**

Introduced in this PR - GH-3321.

I will prepare PR in future weekend.

**Comment by jsteube** [comment]
I think everything is ok, just the scenario is invalid. 

Please see https://hashcat.net/forum/thread-6225.html

Missing:

```
cryptsetup luksOpen test tmp
mkfs.XXX /dev/mapper/tmp
cryptsetup luksClose tmp
```

**Comment by Banaanhangwagen** [comment]
See also [this issue](https://github.com/hashcat/hashcat/issues/2477) from two years ago which handles the same question...

**Comment by erlinafitri** [comment]
Help akun i hack.

**Comment by ventaquil** [comment]
@jsteube @Banaanhangwagen Not a Hashcat problem itself but `luks2hashcat.py` should return an error imho.

Before creating header struct there should be a quick check

https://github.com/hashcat/hashcat/blob/e30be9f17c03053dd3825973c53ee912187147a3/tools/luks2hashcat.py#L257-L271

```py
if sum(payload) == 0:
    raise ValueError("container not initialized")

# convert into header
header = HeaderVersion1(
    header.magic,
    header.version,
    header.cipher,
    header.mode,
    header.hash,
    payload,
    header.key_bytes * 8,
    header.digest,
    header.salt,
    header.iterations,
    header.uuid,
    keys,
)
```
