### ISSUE TITLE
Add new algorithm: BISQ .wallet (scrypt)

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#3462]
This post is a placeholder to discuss the adding of a new algorithm "Bisq .wallet (scrypt)".

Bisq (https://bisq.network/) is a decentralized bitcoin for fiat exchange.
After installing the application, the user can use a built-in bitcoin/bisq-wallet.

The user is encouraged to protect his wallet with a password of minimum 8 characters.
Once set, this password is asked at startup or when doing a transaction.

Bisq creates two encrypted .wallet files.
On Windows, you will find these files in the folder `AppData\Roaming\Bisq\btc_mainnet\wallet`.

The wallet files have the following header: `x0A x16 org.bitcoin.production`.
After reading [the code on their Github](https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/crypto/ScryptUtil.java), it appears that they use the same `ScryptUtil.java` as Multibit-wallet, but with slightly modified N, r, p parameters.

In order to crack this wallet password, I created a new mode for Hashcat (-m 29800). Since there is a big resemblance with `Multibit wallet (scrypt)`-mode 27700, this could be easily done. (right ;-) )

Please use `bisq2hashcat.py` (found in tools) on the .wallet files for extracting the hash.

---

Example :
```
$ python bisq2hashcat.py bisq_BTC.wallet
bisq_BTC.wallet:$bisq$3*32768*8*6*31d838af87f99cb8*5cfb7bf3228d9e865881156e17b1866589ffa6b757011e25d1319083595236d2
```
```
$ ./hashcat -m 29800 '$bisq$3*32768*8*6*31d838af87f99cb8*5cfb7bf3228d9e865881156e17b1866589ffa6b757011e25d1319083595236d2' -w3 -a3 hashcat1 -d4
hashcat (v6.2.6) starting

CUDA API (CUDA 11.7)
====================
* Device #1: NVIDIA GeForce GTX 1080 Ti, skipped
* Device #2: NVIDIA GeForce GTX 1080, skipped
* Device #3: NVIDIA GeForce GTX 1080, skipped
* Device #4: NVIDIA GeForce GTX 1070 Ti, 8014/8117 MB, 19MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 0 MB

Approaching final keyspace - workload adjusted.

$bisq$3*32768*8*6*31d838af87f99cb8*a2c2d0265f3e9e4ad2c2dd4c7d33e5a83462b20df3088c66135e7ae2afa440d4:hashcat1

Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 29800 (Bisq .wallet (scrypt))
Hash.Target......: $bisq$3*32768*8*6*31d838af87f99cb8*a2c2d0265f3e9e4a...a440d4
Time.Started.....: Fri Sep 16 19:40:32 2022 (6 secs)
Time.Estimated...: Fri Sep 16 19:40:38 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: hashcat1 [8]
Guess.Queue......: 1/1 (100.00%)
Speed.#4.........:        0 H/s (21.82ms) @ Accel:14 Loops:1024 Thr:32 Vec:1
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#4...: Salt:0 Amplifier:0-1 Iteration:31744-32768
Candidate.Engine.: Device Generator
Candidates.#4....: hashcat1 -> hashcat1
Hardware.Mon.#4..: Temp: 43c Fan:  0% Util: 99% Core:1885MHz Mem:3802MHz Bus:16

Started: Fri Sep 16 19:40:30 2022
Stopped: Fri Sep 16 19:40:40 2022
```

**Comment by ventaquil** [comment]
> The user is encouraged to protect his wallet with a password of minimum 8 characters.

According to this - `module_pw_min` shouldn't returns `8`?

https://github.com/hashcat/hashcat/blob/1bbf9a68a0d967450725e1d5b4752733aef1fc34/src/modules/module_29800.c#L480

MetaMask walllet module example.

https://github.com/hashcat/hashcat/blob/06bd5a44fbd2bdc153dbecfcf40657dd318012e6/src/modules/module_26600.c#L107-L112

**Comment by jsteube** [comment]
Yes, if the original tool has this policy, it should be set to 8 as described.
