### ISSUE TITLE
[Feature] Pure kernel support for up length of 256 characters

### ISSUE THREAD

**Issue by cyber-speed** [hashcat/hashcat#3474]
**Describe the feature**
Pure kernel support for up length of 256 characters, will definitely fix the limitation described.

**Current behavior**
Wile performing 2D attacks, if the needed strings to be combined are larger than 32 characters they get skipped.

**Expected behavior**
While using the CRC64 algo for 2D attacks to find strings, that go beyond 32 character length.

**Comment by jsteube** [comment]
Which hash mode are you referring to?

**Comment by cyber-speed** [comment]
Initially i wanted to use it on CRC64Jones the most, but CRC32 is needed as well, as many combinations i want to try requires characters length larger that current limit of 32 characters.

Oops forgot to add them modes:
11500 for CRC32B
28000 for CRC64Jones

**Comment by jsteube** [comment]
Pure kernel support for all CRC modes have been added.

**Comment by cyber-speed** [comment]
> Pure kernel support for all CRC modes have been added.

Thank you for supporting all CRC modes, it works as should now.
