### ISSUE TITLE
Random errors stopping cracking

### ISSUE THREAD

**Issue by pbies** [hashcat/hashcat#3476]
While cracking with command:

```
hashcat -m 11300 -a 0 -w 3 %file% %pass% -o %out% --session=%t%
```
(That's a bitcoin wallet hash crack)

I randomly get errors stopping the cracking process, hashcat exits:

```
cuEventSychronize(): an illegal memory access was encountered
cuMemcpyDtoHAsync(): an illegal memory access was encountered
cuMemFree(): an illegal memory access was encountered
cuEventDestroy(): an illegal memory access was encountered
cuStreamDestroy(): an illegal memory access was encountered
cuModuleUnload(): an illegal memory access was encountered
```

Expected behavior: hashcat should still go on with cracking process.

How to reproduce: it happens randomly and mostly when I start Google Chrome or Firefox and go through some pages. No specific actions can be made to init error.

Issue is with hashcat 6.2.5 and 6.2.6. Used is CUDA on NVIDIA card.

```
hashcat (v6.2.6) starting in backend information mode

CUDA Info:
==========

CUDA.Version.: 11.7

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce GTX 1080 Ti
  Processor(s)...: 28
  Clock..........: 1657
  Memory.Total...: 11263 MB
  Memory.Free....: 10223 MB
  Local.Memory...: 48 KB
  PCI.Addr.BDFe..: 0000:01:00.0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 11.7.102

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce GTX 1080 Ti
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 28
    Clock..........: 1657
    Memory.Total...: 11263 MB (limited to 2815 MB allocatable in one block)
    Memory.Free....: 10560 MB
    Local.Memory...: 48 KB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 517.48
    PCI.Addr.BDF...: 01:00.0

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) OpenCL
  Version.: OpenCL 3.0 WINDOWS

  Backend Device ID #3
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Version........: OpenCL 3.0 (Build 0)
    Processor(s)...: 16
    Clock..........: 3600
    Memory.Total...: 16312 MB (limited to 4078 MB allocatable in one block)
    Memory.Free....: 8124 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 3.0
    Driver.Version.: 2022.13.3.0.16_160000
```

nvidia-smi:
```
Wed Oct 12 06:28:04 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 34%   53C    P0    58W / 280W |    300MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2604    C+G   ...IR iCUE Software\iCUE.exe    N/A      |
|    0   N/A  N/A      4448    C+G   ...8wekyb3d8bbwe\GameBar.exe    N/A      |
|    0   N/A  N/A     11360    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     12964    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     14092    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     15128    C+G   ...2txyewy\TextInputHost.exe    N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by pbies** [comment]
Seems like these errors happen when cracking bitcoin wallets (hashes) and does happen when cracking TrueCrypt volume with non-legacy=new modes.
CPU cracking does not give these errors.

**Comment by ventaquil** [comment]
Strange - new TC modules share same kernels with old ones.

**Comment by pbies** [comment]
My tests:

6.0.0 GPU default device 84kH/s error
6.1.0 GPU default device 84kH/s error
6.1.1 GPU default device 63kH/s error
6.2.0 GPU default device 65kH/s error
6.2.1 GPU default device 84kH/s error
6.2.2 GPU default device 85kH/s error
6.2.3 GPU default device 85kH/s error
6.2.4 GPU default device 3kH/s too slow
6.2.4 GPU OpenCL 64kH/s error
6.2.6 GPU default device 65kH/s error
6.2.6 GPU OpenCL 77kH/s error

So I've noticed that all throw errors. With previous versions of hashcat I hadn't a problem, but CUDA and graphic card driver were older. So the problem must be hashcat, CUDA driver or graphic card driver.

CPU once had BSOD, but later allways ok.

I've checked RAM (memtest) and VRAM (OCCT) and everything is ok.

**Comment by jsteube** [comment]
Please provide all files and exact command line required to reproduce the problem locally.

**Comment by pbies** [comment]
> Please provide all files and exact command line required to reproduce the problem locally.

I've already done that in first post.

**Comment by jsteube** [comment]
Wait, you didn't. There's no hashfile and no wordlist. Since I believe this is not a hashcat problem because it doesn't occur for me, I suspect some unexpected data inside one of these remaining unknown factors. But without them I can't reproduce locally.

**Comment by pbies** [comment]
> Wait, you didn't. There's no hashfile and no wordlist. Since I believe this is not a hashcat problem because it doesn't occur for me, I suspect some unexpected data inside one of these remaining unknown factors. But without them I can't reproduce locally.

For obvious reasons I cannot share the hashes nor wordlist which is just too big. Used command is in the first post.
There is no unexpected data in both files. They are verified by hashcat and give no errors. Errors are related to something else.

**Comment by jsteube** [comment]
Well it works fine for me. 

You can use my input files to check on your system. I'll use exactly the same set of parameters you did. I've even downgraded to CUDA 11.7.

hash.txt:

```
$bitcoin$96$c265931309b4a59307921cf054b4ec6b6e4554369be79802e94e16477645777d948ae1d375191831efc78e5acd1f0443$16$8017214013543185$200460$96$480008005625057442352316337722323437108374245623701184230273883222762730232857701607167815448714$66$014754433300175043011633205413774877455616682000536368706315333388
```

word.txt:

```
hashcat
```

If it works on your system with my files, then the problem are your input files. If they do not work, then the problem is your driver or CUDA installation.

```
d:\tools\hashcat-6.2.6>hashcat -m 11300 -a 0 -w 3 hash.txt word.txt -o result.txt --session=lala --backend-ignore-opencl --backend-ignore-hip
hashcat (v6.2.6) starting

CUDA API (CUDA 11.7)
====================
* Device #1: NVIDIA GeForce RTX 3090, 23330/24575 MB, 82MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP
* Uses-64-Bit

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1462 MB

Dictionary cache built:
* Filename..: word.txt
* Passwords.: 1
* Bytes.....: 8
* Keyspace..: 1
* Runtime...: 0 secs

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.


Session..........: lala
Status...........: Cracked
Hash.Mode........: 11300 (Bitcoin/Litecoin wallet.dat)
Hash.Target......: $bitcoin$96$c265931309b4a59307921cf054b4ec6b6e45543...333388
Time.Started.....: Wed Oct 26 16:52:22 2022 (1 sec)
Time.Estimated...: Wed Oct 26 16:52:23 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (word.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:        1 H/s (3.63ms) @ Accel:8 Loops:1024 Thr:256 Vec:1
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 1/1 (100.00%)
Rejected.........: 0/1 (0.00%)
Restore.Point....: 0/1 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: hashcat -> hashcat
Hardware.Mon.#1..: Temp: 57c Fan:  0% Util: 93% Core:1840MHz Mem:9492MHz Bus:16

Started: Wed Oct 26 16:51:57 2022
Stopped: Wed Oct 26 16:52:24 2022
```

**Comment by pbies** [comment]
This won't work as errors happen several (>30) seconds from start of cracking. And it is dependent on Firefox or/and Chrome start in Windows beside hashcat. From the error messages we can see that there is some problem with memory - not with input files.

Second: it is ?b?b?b?b?b?b?b?b brute force cracking, and there is even no wordlist. Hashes tested by me where short (64) and long (96) - both give errors.

Problem both exists for dictionary and brute-force.

**Comment by jsteube** [comment]
Sorry but you said in your very first post that the command line is the following:

```
hashcat -m 11300 -a 0 -w 3 %file% %pass% -o %out% --session=%t%
```

So there's no mask with -a 0. 

Other than that it seems there's no way for us to come together and work on the problem. I'm sorry, but I can't help you.

**Comment by pbies** [comment]
I said nothing about mask. And I said that problem both exists for dictionary crack and brute-force - both on GPU.

Still the problem exists and is not resolved.

**Comment by pbies** [comment]
In the end it appeared that all errors are related to temperature. If the card goes up to 75 degrees C it throws errors. Looks like it is not a hashcat issue nor drivers issues.
