### ISSUE TITLE
Speed down with no reason

### ISSUE THREAD

**Issue by GraverErmitage** [hashcat/hashcat#3478]
Hello Team,

I see a big speed down after a short time from the start.
The command line:
 ./hashcat --brain-client --brain-client-features=2 --brain-host=IP --brain-port=port --brain-password=mypassword -a 3 -m 11300 -w 3 --self-test-disable my.hash ?u?l?l?l?l?l?d?d?d?d --hwmon-disable --spin-damp=50
No changes from the hardware or OS side were done between the speed down or during it.
I use 4 devices: RTX3080ti, RTX 3070, RTX 3080ti, 3060ti
NVIDIA driver 510.73.05
OS - Ubuntu 18.04 (HiveOS)
Hashcat version: 6.2.6
For NV: Post nvidia-smi output - attached.
Post clinfo output - attached.
Post hashcat -I output - attached.
On Linux: post lspci output - attached.
[clinfo.txt](https://github.com/hashcat/hashcat/files/9792732/clinfo.txt)
[hashcat.info.txt](https://github.com/hashcat/hashcat/files/9792733/hashcat.info.txt)
[lspci.txt](https://github.com/hashcat/hashcat/files/9792734/lspci.txt)
[nvidia-smi.txt](https://github.com/hashcat/hashcat/files/9792735/nvidia-smi.txt)
![Speed_down](https://user-images.githubusercontent.com/34091165/196000181-196324d9-bb87-4d8b-b11e-af78debb2403.png)
![Speed_down2](https://user-images.githubusercontent.com/34091165/196000294-d5c7c531-e84e-4b29-9257-b1845e7d168c.png)

**Comment by ventaquil** [comment]
Isn't it a result of using brain? What happens when you disable brain link?

Maybe GH-3412 is related.

**Comment by jsteube** [comment]
It's just too many entries (already over 88B). If you read the post on brain is that is designed for very slow hashes and everything > 100k for sure is not a very slow hash. Or if you really want to go with brain for faster hashes that only works for multiple hashes with multiple unique salts.

**Comment by GraverErmitage** [comment]
Sorry, seems it was my fault.
