### ISSUE TITLE
Algorithm request - SolarWinds Orion

### ISSUE THREAD

**Issue by MattCarothers** [hashcat/hashcat#3491]
**Is your request based on a publicly known cryptographic schema and where can we find information about?**

See https://www.atredis.com/blog/2018/10/24/fun-with-the-solarwinds-orion-platform

**Provide an example hash/database/file and a known correct password**

The username `admin` with an empty password produces the hash `/+PA4Zck3arkLA7iwWIugnAEoq4ocRsYjF7lzgQWvJc+pepPz2a5z/L1Pz3c366Y/CasJIa7enKFDPJCWNiKRg==`

**Explain how the cryptographic schema is implemented**

Orion password hashing is a variant of a salted SHA512 hash. The hash is computed by first generating a salt that consists of the lowercase username. If the salt is less than 8 bytes long, it is appended with bytes from the string "1244352345234" until it is 8 bytes. For example, the salt for username "ADMIN" would become "admin124", while the salt for "Bo" would become "bo124435". Once the salt has been calculated, a RFC2898 PBKFD2 is generated using the default iteration count of 1000 and the SHA1 hash algorithm. Finally, a SHA512 hash of the PBKDF2 output is taken and encoded using Base64. It doesn't appear that any existing tools support cracking passwords in this format, but Hashcat comes close with PBKDF2-HMAC-SHA1(sha1:1000) support, and is only missing the final call to SHA512(). 

**Where do you typically find the algorithm**

The SolarWinds Orion product.

**Comment by magnumripper** [comment]
> It doesn't appear that any existing tools support cracking passwords in this format

JtR supports it since 2018. Input format picked by the author is:
```
$solarwinds$0$admin$/+PA4Zck3arkLA7iwWIugnAEoq4ocRsYjF7lzgQWvJc+pepPz2a5z/L1Pz3c366Y/CasJIa7enKFDPJCWNiKRg==
```
The `$0$` is a version field for any future needs - currently required to be zero but not used otherwise.

As usual it would obviously be nice if hashcat use the same input format.

**Comment by magnumripper** [comment]
BTW it's not perfectly clear from that article what happens with a username that is longer than 8... will it be used in full (and not padded), or even truncated to 8? The JtR format currently truncates it, but I wouldn't bet that is correct - might as well be a guess or a misunderstanding. Ideally we should have a test vector created by the real deal.

EDIT: The [Ruby script mentioned in the article](https://github.com/atredispartners/solarwinds-orion-cryptography/blob/master/hash-password.rb) does not truncate it. But again, I wouldn't really trust anything other than a test vector generated by the actual SolarWinds Orion software.

**Comment by roycewilliams** [comment]
If needed, a reference of all the known cracks are here:

https://docs.google.com/spreadsheets/d/1u0_Df5OMsdzZcTkBDiaAtObbIOkMa5xbeXdKk_k0vWs

**Comment by jsteube** [comment]
The mode is already supported in hashcat (mode 21500).

**Comment by jsteube** [comment]
But I agree with @magnumripper it would be nice to have a real test vector for usernames > length 8
