### ISSUE TITLE
Time Machine

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3492]
I don't know why this hasn't been requested yet as it seems like an obvious thing to do but if anybody could invent a time machine, just think of the amount of time that could be saved, no more waiting for weeks for a run to finish. I have already planned out the specific implementation details required.

1. Invent a spaceship that can travel close to the speed of light
2. Fire rocket away from earth
3. Do a 180 and come back to earth

I realise this may be a bit too easy for the main Devs so if you want to tag new Devs to work on it that's fine.

**Comment by bigfella237** [comment]
It may be much easier (and pose much less a threat to the space/time continuum) to look into suspended animation instead?

Start your search, jump in your pod, set the timer for a month or so, and wake up when the search has finished...

This way you live longer as well!

**Comment by jsteube** [comment]
So, if the time it takes is too long, may I suggest the if-you-cant-find-the-answer-change-the-problem method.

All it needs is to change the rules of math used in hashes. We just enforce to add a final calculation to every hash function. That rule is something like multiplication with zero. 

No more password managers needed!
