### ISSUE TITLE
Low benchmark speeds with explicitly specified workload profile

### ISSUE THREAD

**Issue by davidbolvansky** [hashcat/hashcat#3496]
Version:
Fresh build of master branch.

Info:
`NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6`

Device:
```
CUDA API (CUDA 11.6)
====================
* Device #1: NVIDIA GeForce GTX 960M, 3625/4046 MB, 5MCU

```

Experiments:
```
./hashcat -b -m 0 -d 1

Speed.#1.........:  3515.2 MH/s (93.63ms) @ Accel:8192 Loops:256 Thr:32 Vec:8



./hashcat -b -m 0 -d 1 -w 1

Speed.#1.........:   949.6 MH/s (0.97ms) @ Accel:32 Loops:32 Thr:256 Vec:1

./hashcat -b -m 0 -d 1 -w 2

Speed.#1.........:  1255.3 MH/s (7.83ms) @ Accel:1024 Loops:64 Thr:32 Vec:1

./hashcat -b -m 0 -d 1 -w 4

Speed.#1.........:  1342.8 MH/s (247.72ms) @ Accel:128 Loops:1024 Thr:512 Vec:1
```

**Comment by davidbolvansky** [comment]
Ah, I see now.

With ./hashcat -b -m 0 -d 1, the optimized kernels are enabled. When -w is explicitly specified, they are not enabled.

So it depends if this is a bug or not, but definitely quite strange behaviour, I would say.

**Comment by jsteube** [comment]
It's perfect as I planned it. You even found out yourself and learned from it.
