### ISSUE TITLE
luks2hashcat.py hash only cracking the first keyslot

### ISSUE THREAD

**Issue by alex94562** [hashcat/hashcat#3497]
**Describe the bug**
With LUKS you're able to use multiple passwords for the same volume and mode 14600 recognises this and is able to crack them. 
When using the tools\luks2hashcat.py you will receive a hash that will only crack the first keyslot in a LUKS volume. 

**To Reproduce**
1. Create a LUKS1 volume and supply a password (123):
`dd if=/dev/zero of=LUKS1 bs=512 count=100000`
`cryptsetup -vy luksFormat --type luks1 LUKS1
`
2. Add an additional password (321):
`cryptsetup luksAddKey LUKS1
`
3. Create a filesystem on the volume so Hashcat is able to crack it:
`cryptsetup luksOpen LUKS1 Luks1Volume`
`mkfs.ext4 /dev/mapper/Luks1Volume`

4. Extract the hash:
`python3 tools\luks2hashcat.py LUKS1 > LUKS1_hash
`
5. Start the cracking:
`hashcat -m29521 LUKS1_hash -a3 ?d?d?d --keep-guessing
`

**Expected behavior**
Hashcat recognises and cracks the two passwords that unlock the volume. 
Instead it cracks one password, the password within the first keyslot for the LUKS volume. 
If this keyslot would be a key file the volume wouldn't crack. 

The image below shows how the output should look (the same LUKS volume is used but with mode 14600):
![14600](https://user-images.githubusercontent.com/45092174/199525774-f4244e02-c7e8-46e0-9e6c-92e435cae073.png)

**Hashcat version (please complete the following information):**
 - OS: Ubuntu 20.04 / Windows 10
 - Hashcat version: Latest (v6.2.6-97-gb8dd80694+)

**Comment by ventaquil** [comment]
My fault, should work now.

```
$ cryptsetup luksDump luks.img 
LUKS header information for luks.img

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha256
Payload offset: 4096
MK bits:        512
MK digest:      cc 39 80 08 4a c0 d7 a0 26 9c 27 6f a0 33 e4 e4 65 94 b2 b6 
MK salt:        4c a4 51 d2 14 36 00 02 7a dc 6b fc 37 ec 8c 07 
                05 5e c5 1d ab f0 57 5d 7c db 36 99 89 9b c8 2c 
MK iterations:  82852
UUID:           ea195063-038d-4894-a9cc-d46006f4a4cd

Key Slot 0: ENABLED
        Iterations:             1312360
        Salt:                   b6 0e 30 ea 85 44 08 e0 40 ba 62 b8 74 ce 61 35 
                                4d 0d db 4b af 42 cc f6 af 96 f8 ec 59 a9 63 fa 
        Key material offset:    8
        AF stripes:             4000
Key Slot 1: ENABLED
        Iterations:             1299350
        Salt:                   fc 03 71 94 ad 31 25 f1 f1 dd 28 0c ab 52 17 7f 
                                a2 c1 92 92 01 72 a1 19 73 27 3e 06 c9 ec cf a2 
        Key material offset:    512
        AF stripes:             4000
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED
$ tools/luks2hashcat.py luks.img | wc -l
2
```

Additional feature that could be added is `-k`/`--keyslot` parameter to extract only the chosen keys.

```
tools/luks2hashcat.py -k 1,8 luks.img
```
