### ISSUE TITLE
bcrypt fails with pocl

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#350]
some log:

Hashtype: bcrypt, Blowfish(OpenBSD)

remark: <unknown>:0:0: loop not vectorized: cannot prove it is safe to reorder memory operations
remark: <unknown>:0:0: loop not vectorized: cannot prove it is safe to reorder memory operations
Segmentation fault (core dumped)

ran with -b

**Comment by jsteube** [comment]
But its clearly a problem inside the OpenCL runtime, so not hashcats fault. Do you think it's correct to place it here?

**Comment by neheb** [comment]
Oh I didn't test with the others. My bad!
