### ISSUE TITLE
someone can contribute a c++ class for cuda/hip/apple backend?

### ISSUE THREAD

**Issue by black6816** [hashcat/hashcat#3503]
**Describe the feature**
the backend file is so big, and many functions are same for cuda/hip/metal,  so a factory class is need.

**Hashcat version (please complete the following information):**
 - OS: [e.g. Linux]
 - Distribution: [e.g. Ubuntu 18.04]
 - Version: [e.g. 6.2.0]

**Comment by ventaquil** [comment]
How could you add classes in C source code?

**Comment by black6816** [comment]
so,  change this project to C++ project， is a huge task, aha.
