### ISSUE TITLE
WPA mode 22000 miss rule based generated password if wordlist not saved to file

### ISSUE THREAD

**Issue by Jenr0** [hashcat/hashcat#3504]
**Describe the bug**
For some WPA (mode 22000) hashes, hashcat miss valid password when using rule option directly in command. When using same wordlist and rule to create dictionary password is found. This may lead to miss password using rule based attack.

**To Reproduce**
hash file
```
WPA*02*3a8172c33afc42516489a30d3bee69e5*c8eaf894b452*0207a872194b*504c415920496e7465726e6574203447204c54452d393442343444*9b9fe1b793d3f24482ca4d9cfbc9939e26b084c256e08089311a7a804b4d5221*0103007502010a0000000000000000000223b6299270c9a33c0982ff31cf82b377eac6a00a4bbc09e545b85739ae08fa87000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630140100000fac040100000fac040100000fac020000*02
```
wordlist file - (word to generate valid password on 3rd position)
```
wrongpass1
wrongpass2
patka
wrongpass3
wrongpass4
wrongpass5
wrongpass6
wrongpass7
wrongpass8
wrongpass9
wrongpass10
wrongpass11
wrongpass12
wrongpass13
wrongpass14
wrongpass15
wrongpass16
wrongpass17
wrongpass18
wrongpass19
wrongpass20
```
Rule: https://github.com/NotSoSecure/password_cracking_rules/blob/master/OneRuleToRuleThemAll.rule

command:
```
hashcat -m 22000 play.hcxp /tmp/pass -r OneRuleToRuleThemAll.rule
```
hashcat output -exhausted
```
Session..........: hashcat                                
Status...........: Exhausted
Hash.Mode........: 22000 (WPA-PBKDF2-PMKID+EAPOL)
Hash.Target......: play.hcxp
Time.Started.....: Mon Nov  7 07:30:25 2022 (13 mins, 23 secs)
Time.Estimated...: Mon Nov  7 07:43:48 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (/tmp/pass)
Guess.Mod........: Rules (OneRuleToRuleThemAll.rule)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     1359 H/s (0.41ms) @ Accel:128 Loops:128 Thr:1 Vec:4
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 1143890/1143890 (100.00%)
Rejected.........: 51995/1143890 (4.55%)
Restore.Point....: 22/22 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:51994-51995 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: wrongpasrr -> password
Hardware.Mon.#1..: Util: 60%

Started: Mon Nov  7 07:30:24 2022
Stopped: Mon Nov  7 07:43:50 2022
```
Using same rule and wordlist to create dictionary in file /tmp/valid:
```
hashcat --stdout /tmp/pass -r OneRuleToRuleThemAll.rule > /tmp/valid
```
Using generated static file to crack same hash:
```
hashcat -m 22000 play.hcxp /tmp/valid
```
hashcat output - cracked
```
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 22000 (WPA-PBKDF2-PMKID+EAPOL)
Hash.Target......: play.hcxp
Time.Started.....: Mon Nov  7 07:46:07 2022 (6 mins, 22 secs)
Time.Estimated...: Mon Nov  7 07:52:29 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (/tmp/valid)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     2657 H/s (6.05ms) @ Accel:256 Loops:64 Thr:1 Vec:4
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 1054066/1143892 (92.15%)
Rejected.........: 39282/1054066 (3.73%)
Restore.Point....: 1052943/1143892 (92.05%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: paxssord -> wrongpass32201
Hardware.Mon.#1..: Util: 97%

Started: Mon Nov  7 07:46:06 2022
Stopped: Mon Nov  7 07:52:31 2022
```

**Expected behavior**
Using rule directly in hashcat command should return same results as rule based generated static password file.

**Hardware/Compute device (please complete the following information):**
- Device 1: pthread-0x000, 2191/4447 MB (1024 MB allocatable), 4MCU - vmware
- RTX 3090 - same results

**Hashcat version (please complete the following information):**
- hashcat v6.2.6
- Linux kali 5.19.0-kali2-arm64  SMP Debian 5.19.11-1kali2 (2022-10-10) aarch64 GNU/Linux
- also tested on amd64 with rtx 3090 
- don't seem to be platform specific

** Hashcat -I output
```
hashcat (v6.2.6) starting in backend information mode

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: The pocl project
  Name....: Portable Computing Language
  Version.: OpenCL 3.0 PoCL 3.0+debian  Linux, None+Asserts, RELOC, LLVM 13.0.1, SLEEF, POCL_DEBUG

  Backend Device ID #1
    Type...........: CPU
    Vendor.ID......: 2147483648
    Vendor.........: 0x61
    Name...........: pthread-0x000
    Version........: OpenCL 1.2 PoCL HSTR: pthread-aarch64-unknown-linux-gnu-(null)
    Processor(s)...: 4
    Clock..........: 48
    Memory.Total...: 4447 MB (limited to 1024 MB allocatable in one block)
    Memory.Free....: 2191 MB
    Local.Memory...: 512 KB
    OpenCL.Version.: OpenCL C 1.2 PoCL
    Driver.Version.: 3.0+debian
```

**Comment by Chick3nman** [comment]
This is currently the intended behavior. WPA2/-m 22000 has a minimum password length of 8 and `patka` is clearly less than 8. It's understood that the rules will be applied to the password, making it long enough to be valid, but hashcat can't know that ahead of time. In effort to avoid issues as well as increase performance once the candidate is sent to the computing device(s), rejections based on minimum/maximum length happen on the host side. The rules you are using, when specified with -r, are being applied on the computing device, which is after the length based rejection happens. If you want to be able to modify the candidate before the reject happens, you will need to move the rule processing to the host side. Single rules applied with -j/-k are applied on the host and can operate on candidates prior to rejections. Specifying -S to enable slow candidates mode also move rule application to the host and I believe that it operates on candidates prior to rejection as well.
