### ISSUE TITLE
HIP GPU thread count with scrypt modules too high

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#3507]
When using AMD GPUs with scrypt modules (e.g. 8900), hashcat sets the thread count to 64 because it gets told by some GPUs that this is the desired thread count. But this introduces a bottleneck which makes the speed dropping by a factor of around 40 compared to when running with 32 threads.

Currently the only way to circumvent this is by using -T to override:
```
./hashcat -b -m 8900 -T 32 --force
```

The module interface does not allow setting a thread limit only for certain GPUs or backends, it would only be possible to limit it globally on the module by setting kernel_threads_max to 32 (which may influence other backends/models). Is there a way to e.g. set the threads_max to 32 for AMD GPUs (or certain models) for scrypt modules?

**Comment by black6816** [comment]
as i know, there are 64 threads per wavefront, and module 8900 is 'one thread does one work', i can't understand why 40x slow down with 64 threads.
