### ISSUE TITLE
Should Appveyor be disabled?

### ISSUE THREAD

**Issue by ventaquil** [hashcat/hashcat#3523]
Since Appveyor fails quite often maybe it should be disabled.

When GitHub runners will support GPU then new jobs with proper test could be added to existing setup - github/roadmap#505.

**Comment by Chick3nman** [comment]
I think the Appveyor config just needs an update. The build failures are due to a limitation of cygwin on 32bit windows. See here: https://ci.appveyor.com/project/jsteube/hashcat/build/job/a2bdir94jdt5xf7p

**Comment by ventaquil** [comment]
Since there are GitHub Actions is there a need to keep AppVeyor (and old Travis) config?

Here you have my [test run](https://github.com/ventaquil/hashcat/actions/runs/3640734628) of PoCL test.

Because of [usage limits](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) we need to think what should be tested during workflow (maybe quick benchmark is just enough).

**Comment by ventaquil** [comment]
Looks that it's solved now - [95a74b7](https://github.com/hashcat/hashcat/commit/95a74b778f4d2368854a1b09a867a6a2e40a5ab8).
