### ISSUE TITLE
macos AMD Radeon Pro 5500M GPUs not working

### ISSUE THREAD

**Issue by a3sroot** [hashcat/hashcat#3532]
**Describe the bug**
I have similar problem on intel mac its just skips both GPUs and uses CPU.

**Expected behavior**

**Hardware/Compute device (please complete the following information):**
- Compute device name: AMD Radeon Pro 5500M Compute Engine
- OpenCL/CUDA driver name: [e.g. NVIDIA DRIVER]
- OpenCL/CUDA driver version: [e.g. 465.21]
- OpenCL/CUDA driver source: [e.g. runtime installer/.exe installer]
![image](https://user-images.githubusercontent.com/81551286/206653904-cdb07afc-8597-40ec-a49d-d778016672e6.png)

**Hashcat version (please complete the following information):**
 - OS: macos
 - Distribution: 12.6
hashcat (v6.2.6) starting

https://hashcat.net/forum/thread-11081-post-56570.html#pid56570

![image](https://user-images.githubusercontent.com/81551286/206654507-ba46f104-34ac-4bc0-97ee-5c74b183206b.png)

**Comment by matrix** [comment]
Hi @a3sroot, please retry with github master. To select a device you have to use -d and not -D
