### ISSUE TITLE
Benchmark vs actual speed of LUKS on GPU is x200 lower

### ISSUE THREAD

**Issue by BrodaUa** [hashcat/hashcat#3535]
**Describe the bug**
LUKS is supposed to use GPU (https://hashcat.net/forum/thread-6225.html)
Running a LUKS benchamark (-m 14600) shows ~10800 H/s
![img1](https://user-images.githubusercontent.com/9928101/207400819-ba9c2f59-c1f8-4a08-a9a7-906dd4aa55a8.jpg)

Running an actual brute force attach (` hashcat -a 0 -m 14600 -D 1,2 -O -w 4 hdd.img wordlist.txt `) shows only 50-60 H/s.
![img2](https://user-images.githubusercontent.com/9928101/207400835-10052a67-8131-40de-beb8-08aef1a7d53c.jpg)

Why is there such significant drop in speed? or do I miss something ?

**To Reproduce**
Run benchmark vs actual LUKS attach

**Expected behavior**
Actual speed should be comparable to the benchmark

**Hardware/Compute device (please complete the following information):**
- Compute device name: RTX 2070
- OpenCL/CUDA driver name: NVIDIA DRIVER
- OpenCL/CUDA driver version: 470.103.01 / CUDA 11.4 

**Hashcat version (please complete the following information):**
 - OS:  ubuntu 20.10
 - Version: hashcat v5.1.0

**Comment by Chick3nman** [comment]
The benchmark iteration count is 163k, your hash has an iteration count >5M. LUKS hashes have variable difficulty and your target is very difficult. Closing as "working as expected".

**Comment by ventaquil** [comment]
Module `14600` implements variety of available LUKS modules - but only one variant is benchmaked.

You can benchmark modules `29511`-`29543` to see and compare benchmarks results of different LUKS modules (which differ at cipher and hash function).

**Comment by BrodaUa** [comment]
@Chick3nman Ok, thank you. Another question - it seems not using all the available CPU/GPU resources, then how can I speed up the iterations ?
@ventaquil can you guide please on how to test those modules? `-m` param is related only to hash-types as I see (trying `-m 29511` gives an error)

**Comment by ventaquil** [comment]
You can use a simple `for` loop - read more here https://www.redhat.com/sysadmin/bash-scripting-loops.

```bash
for i in 295{1,2,3,4}{1,2,3}
do
    hashcat -b -m $i
done
```
