### ISSUE TITLE
Keep-guessing doesn't appear to work for wordlist

### ISSUE THREAD

**Issue by fse-a** [hashcat/hashcat#3538]
**Describe the bug**
It appears that the --keep-guessing doe not work for wordlist attacks

**To Reproduce**
./hashcat -m 11500 --potfile-disable -w4 -a3  --keep-guessing AABBCCDD:00000000 -2 ?u?l?d ?2?2?2?2?2?2

The expected results are:
aabbccdd:00000000:VmwAra
aabbccdd:00000000:nEvUXC
aabbccdd:00000000:oYx8BN
aabbccdd:00000000:Wm6pix
aabbccdd:00000000:Pt1NCS
aabbccdd:00000000:3EovML
aabbccdd:00000000:h0Cwm5
aabbccdd:00000000:UQ3n0e
aabbccdd:00000000:XbhqNo
aabbccdd:00000000:6A3FW6
aabbccdd:00000000:oE7dCZ
aabbccdd:00000000:ISBRIm
aabbccdd:00000000:C43NpD
aabbccdd:00000000:14GUyY
aabbccdd:00000000:NJElcF

Then we create a wordlist with some of these answer surrounded by other passwords:
error1
VmwAra
error2
nEvUXC
error3
oYx8BN
error4
Wm6pix
error5
Pt1NCS
error6
3EovML
error7

Then we run hashcat with the wordlist:
./hashcat -m 11500 --potfile-disable -w4 -a0  --keep-guessing AABBCCDD:00000000 crc-wordlist.txt

Result:
aabbccdd:00000000:VmwAra

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 11500 (CRC32)
Hash.Target......: aabbccdd:00000000
Time.Started.....: Thu Dec 15 17:30:02 2022 (0 secs)
Time.Estimated...: Thu Dec 15 17:30:02 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (crc-wordlist.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:    96240 H/s (0.01ms) @ Accel:2048 Loops:1 Thr:32 Vec:1
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 13/13 (100.00%)
Rejected.........: 0/13 (0.00%)
Restore.Point....: 13/13 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: error1 -> error7
Hardware.Mon.#1..: Temp: 32c Fan: 33% Util: 60% Core:1797MHz Mem:4513MHz Bus:16

**Additional context**
After the first password  in the wordlist has been found hashcat stops with cracking. If I move a different password to be the first in the wordlist it will find this password first. 

Tested on the current master (15 december 2022) with a NVIDIA GeForce GTX 1080

[crc-wordlist.txt](https://github.com/hashcat/hashcat/files/10238900/crc-wordlist.txt)

**Comment by matrix** [comment]
same of https://github.com/hashcat/hashcat/issues/3212#issuecomment-1072087074
