### ISSUE TITLE
No pkzip hash larger than 32KB can be cracked with versions >= 6.2.5

### ISSUE THREAD

**Issue by s3inlc** [hashcat/hashcat#3546]
The changes from pull request #2970 makes it impossible to crack any larger pkzip hash.

@magnumripper back then when you provided this fix, did you test it with any hashes larger than ~32KB of data?

For some reason infstream.total_out in my case stops at 32'768 and does not increase further during the inflating process (even while uncompressing more data). And obviously, in that case the length check afterwards does not match.
Simply create an encrypted zip with a file larger than 32KB and smaller than 320KB to reproduce this. With version 6.2.4 (which was the last release before the change) it finds the password without any issue.

This makes hashcat never cracking any pkzip hash having uncompressed data larger than 32KB. 
Any idea why this counter is not increased further?

**Comment by magnumripper** [comment]
Ouch, that's not good. I usually test with a decent set of samples but I can't recall how I tested this one.

Why did you close this issue though?

**Comment by magnumripper** [comment]
I can reproduce. Very odd, just like you say the length doesn't increment beyond 32768. I have yet to spot why but it "has to" be some piece missing in `inc_zip_inflate.cl`... and I strongly believe my change in #2970 should stand.

**Comment by s3inlc** [comment]
> Why did you close this issue though?

I was notified yesterday, that there was already an issue open regarding that bug (issue #3434), that's why I closed it. It seems that the total_out value does not seem to provide what the name would make you think. Apparently, it gets reset on certain cases, so it may not be the right value to use for the total output check.

**Comment by magnumripper** [comment]
Oh, I see it now. I guess it differs from the normal library code because you are inflating into a smaller window. Easy fix then, just add a separate variable.
