### ISSUE TITLE
Hashcat cracked my $RAR3$*1* hash in a wrong way! False cracked

### ISSUE THREAD

**Issue by alanjfora** [hashcat/hashcat#3564]
Hello guys!
I know that hashcat has a lot of bad history with RAR3*1* hashs.
I'm using hascat v6.2.6.7 that supports to this hash type, however hashcat reports cracked almost instantly and a fake password that doesn't match the hash. Hashcat does this with 2 digits, 3, 4, 5... it always find a fake password that clearly won't open my .rar file

**Example of my last attempt**:

hashcat.exe -a3 -m23700 hash.txt -1 ?l?d?u ?1?1?1?1?1?1 -w3 -O
hashcat (v6.2.6) starting

CUDA API (CUDA 12.0)
====================
* Device #1: NVIDIA GeForce RTX 3080 Ti, 11086/12287 MB, 80MCU

OpenCL API (OpenCL 3.0 CUDA 12.0.94) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 20

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Optimized-Kernel
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1470 MB

$RAR3$*1*8d79d-----------[oculted]---------------a4bed89c380*30:s1RERA **(FAKE PASSWORD)**

Session..........: hashcat
Status...........: **Cracked**
Hash.Mode........: 23700 (RAR3-p (Uncompressed))
Hash.Target......: $RAR3$*1*8d79d-----------[oculted]---------------a4bed89c380*30
Time.Started.....: Thu Jan 05 12:40:31 2023 (1 sec)
Time.Estimated...: Thu Jan 05 12:40:32 2023 (0 secs)
Kernel.Feature...: Optimized Kernel
Guess.Mask.......: ?1?1?1?1?1?1 [6]
Guess.Charset....: -1 ?l?d?u, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   130.1 kH/s (78.26ms) @ Accel:8 Loops:16384 Thr:256 Vec:1
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 163840/56800235584 (0.00%)
Rejected.........: 0/163840 (0.00%)
Restore.Point....: 0/916132832 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:245760-262144
Candidate.Engine.: Device Generator
Candidates.#1....: sarier -> sgDder
Hardware.Mon.#1..: Temp: 55c Fan: 45% Util:100% Core:1680MHz Mem:9251MHz Bus:16

Started: Thu Jan 05 12:40:28 2023
Stopped: Thu Jan 05 12:40:33 2023

**ANOTHER Example of a attempt**:

hashcat.exe -a3 -m23700 hash.txt
hashcat (v6.2.6) starting

CUDA API (CUDA 12.0)
====================
* Device #1: NVIDIA GeForce RTX 3080 Ti, 11086/12287 MB, 80MCU

OpenCL API (OpenCL 3.0 CUDA 12.0.94) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3080 Ti, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 128

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1470 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 23700 (RAR3-p (Uncompressed))
Hash.Target......: $RAR3$*1*8d79d-----------[oculted]---------------a4bed89c380*30
Time.Started.....: Thu Jan 05 14:17:08 2023 (8 secs)
Time.Estimated...: Thu Jan 05 14:17:16 2023 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?1 [1]
Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Guess.Queue......: 1/15 (6.67%)
Speed.#1.........:        8 H/s (8.08ms) @ Accel:1 Loops:16384 Thr:512 Vec:1
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 62/62 (100.00%)
Rejected.........: 0/62 (0.00%)
Restore.Point....: 1/1 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:61-62 Iteration:245760-262144
Candidate.Engine.: Device Generator
Candidates.#1....: X -> X
Hardware.Mon.#1..: Temp: 46c Fan: 45% Util: 99% Core:2010MHz Mem:9251MHz Bus:16

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

$RAR3$*1*8d79d-----------[oculted]---------------a4bed89c380*30:su **(FAKE PASSWORD)**

Session..........: hashcat
Status...........: **Cracked**
Hash.Mode........: 23700 (RAR3-p (Uncompressed))
Hash.Target......: $RAR3$*1*8d79d-----------[oculted]---------------a4bed89c380*30
Time.Started.....: Thu Jan 05 14:17:17 2023 (0 secs)
Time.Estimated...: Thu Jan 05 14:17:17 2023 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?1?2 [2]
Guess.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Guess.Queue......: 2/15 (13.33%)
Speed.#1.........:      211 H/s (8.60ms) @ Accel:1 Loops:16384 Thr:512 Vec:1
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 36/2232 (1.61%)
Rejected.........: 0/36 (0.00%)
Restore.Point....: 0/36 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:245760-262144
Candidate.Engine.: Device Generator
Candidates.#1....: sa -> sq
Hardware.Mon.#1..: Temp: 49c Fan: 45% Util: 97% Core:2010MHz Mem:9251MHz Bus:16

Cracking performance lower than expected?

* Append -O to the commandline.
  This lowers the maximum supported password/salt length (usually down to 32).

* Append -w 3 to the commandline.
  This can cause your screen to lag.

* Append -S to the commandline.
  This has a drastic speed impact but can be better for specific attacks.
  Typical scenarios are a small wordlist but a large ruleset.

* Update your backend API runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => Started: Thu Jan 05 14:17:04 2023
Stopped: Thu Jan 05 14:17:20 2023

**Am I missing something?
What could be happening?
Any tips or solutions for this?

Thank you very much!**

**Comment by philsmd** [comment]
It's not impossible to hit some collisions with that speed and algo. DId you try to use `--keep-guessing` and see if one of the passwords work for you?

**Comment by alanjfora** [comment]
> It's not impossible to hit some collisions with that speed and algo. DId you try to use `--keep-guessing` and see if one of the passwords work for you?

No, I haven't tried that yet. But I imagine that it provides me many false passwords with a varied number of digits as I showed there.
Almost instantly, hashcat gives me any password regardless of the number of digits I ask for.

Thank you very much, philsmd for you help, man.
I'm using john the ripper at the moment and it's going well.

**Comment by roycewilliams** [comment]
@alanjfora - can this issue be closed?

**Comment by tsweet64** [comment]
I believe this issue should not have been closed. I have been experiencing the problem as well. It appears that John performs further checks to reject false positives (in any case, the false positives that hashcat "finds" do not get found by john), so perhaps it would be possible to implement these checks in hashcat as well.
