### ISSUE TITLE
Hashcat fails on AMD Radeon HD 7450

### ISSUE THREAD

**Issue by CryptoMinerAndriod** [hashcat/hashcat#3565]
My ubuntu PC (Dell Precision Workstation 390, Intel core 2 duo 6700, 1GB MSI AMD Radeon HD 7450, 666MHz DDR2 6GB RAM) is having issues with hashcat, I am trying to brute-force an old bitcoin wallet, that I got and its failing to use my GPU, any help?

**Comment by CryptoMinerAndriod** [comment]
CPU speed: 2666MHz

**Comment by Chick3nman** [comment]
Without more information about the error, there's nothing we can do. This may be a better topic for the forums/discord than here. Also, your hardware is outdated and unlikely to fall within the supported runtime versions. If that's the case, there's not much you can do.

**Comment by DEDSEC0708** [comment]
yes bro we need more information we can't do anything

**Comment by CryptoMinerAndriod** [comment]
Ok, I will probs buy an newer GPU' that doesn't break my Dell precision 390

**Comment by Chick3nman** [comment]
Closing as "no bug" for now, feel free to reopen if a specific issue comes up.
