### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hashcat/hashcat#3569]
I would like to point out that identifiers like “[`_BACKEND_H`](https://github.com/hashcat/hashcat/blob/43a27117a4d36720e468443f588a28c4d7896441/include/backend.h#L6 "Update candidate")” and “[`_HASHCAT_H`](https://github.com/hashcat/hashcat/blob/32b40d5c53e0c438576f33bfa03d8fe6b87d08e8/include/hashcat.h#L6 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jsteube** [comment]
Thanks for bringing this up. It is news to me, too. I think we can change it, it's not a problem.

**Comment by matrix** [comment]
fixed

**Comment by elfring** [comment]
:eyes: [Was another update candidate left over](https://github.com/hashcat/hashcat/blame/6716447dfce969ddde42a9abe0681500bee0df48/OpenCL/inc_cipher_cast.h#L3 "Update candidate: _OPENCL_CAST_H")?
