### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE on AMD - beta 51

### ISSUE THREAD

**Issue by L1nkus** [hashcat/hashcat#357]
Output log (Up to MD5):

$ ./hashcat64.bin -b
hashcat (v3.00-beta-122-g04dfe6e) starting in benchmark-mode...

Device #1: AMD ICELAND (DRM 3.1.0 / 4.5.4-1-ARCH, LLVM 3.9.0), 256/1024 MB allocatable, 6MCU
Device #2: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz, skipped

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -I "/home/adam/Downloads/hashcat-3.00/OpenCL/" -I '/home/adam/Downloads/hashcat-3.00/OpenCL/' -I /home/adam/Downloads/hashcat-3.00/OpenCL/ -I"/home/adam/Downloads/hashcat-3.00/OpenCL/" -I'/home/adam/Downloads/hashcat-3.00/OpenCL/' -I/home/adam/Downloads/hashcat-3.00/OpenCL/ -DVENDOR_ID=2147483648 -DCUDA_ARCH=0 -DVECT_SIZE=4 -DDEVICE_TYPE=4 -DKERN_TYPE=900 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===
<unknown>:0:0: in function l_markov void (%struct.pw_t addrspace(1)_, %struct.cs_t addrspace(1)_, %struct.cs_t addrspace(1)*, i64, i32, i32, i32, i32, i32, i32): unsupported call to function generate_pw

=== Build Log (end) ===
Device #1: Kernel /home/adam/Downloads/hashcat-3.00/OpenCL/markov_le.cl build failure. Proceed without this device.
Hashtype: MD4

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -I "/home/adam/Downloads/hashcat-3.00/OpenCL/" -I '/home/adam/Downloads/hashcat-3.00/OpenCL/' -I /home/adam/Downloads/hashcat-3.00/OpenCL/ -I"/home/adam/Downloads/hashcat-3.00/OpenCL/" -I'/home/adam/Downloads/hashcat-3.00/OpenCL/' -I/home/adam/Downloads/hashcat-3.00/OpenCL/ -DVENDOR_ID=2147483648 -DCUDA_ARCH=0 -DVECT_SIZE=4 -DDEVICE_TYPE=4 -DKERN_TYPE=0 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===
<unknown>:0:0: in function l_markov void (%struct.pw_t addrspace(1)_, %struct.cs_t addrspace(1)_, %struct.cs_t addrspace(1)*, i64, i32, i32, i32, i32, i32, i32): unsupported call to function generate_pw

=== Build Log (end) ===
Device #1: Kernel /home/adam/Downloads/hashcat-3.00/OpenCL/markov_le.cl build failure. Proceed without this device.
Hashtype: MD5

**Comment by jsteube** [comment]
Not hashcat's fault, it's crashing somewhere inside the OpenCL runtime. Make sure you have AMD driver 15.12 (not higher) installed.
