### ISSUE TITLE
Salt-length exception for salted SHA1

### ISSUE THREAD

**Issue by adrastee** [hashcat/hashcat#3574]
Is it possible to force the salt MAX length ? My salt length is 62 characters, which is upper than 51.
If not, is there any workaround?
Thanks

```
hashcat.exe -m 110  hash.txt dic.txt

hashcat (v6.2.6) starting
(....)
Minimim salt length supported by kernel: 0
Maximum salt length supported by kernel: 51

Hashfile  on line 1 (xxx): Salt-length exception.
```

**Comment by Chick3nman** [comment]
The maximum salt length for -m 110 is 256. 51 is the maximum length only for the optimized kernel. Simply do not specify `-O` and you should be able to use hashcat without issue.

**Comment by adrastee** [comment]
True! Thanks!
