### ISSUE TITLE
If I want to run hashcat with the function "execve()", how should I configure the *argv[]?

### ISSUE THREAD

**Issue by JKerbin** [hashcat/hashcat#3577]
for example, the command line "hashcat -a 3 -m 0 Blah, Blah, Blah..."

I have tried 'char *argv[] = {"hashcat", "-a3", "-m0", "Blah, Blah, Blah..."...};' and many other combinations, but they won't work.

I wonder how to configure that?

**Comment by b8vr** [comment]
I don't know the answer to the question, but you're missing a hash in that attack, so hashcat would not work even if what you do is correct.

**Comment by ventaquil** [comment]
@Ilovestella if you are trying to use Hashcat library with C code it could be very difficult.

You should take a look at `src/main.c` file and (probably) just copy code into your file.

https://github.com/hashcat/hashcat/blob/5adb38430fc70febd67f59e4630aa8e867158424/src/main.c#L1194-L1258

In my implementation I resigned from `argv` and I am setting all necessary variables on my own by using `hashcat.user_options`.

Check example below - it's part of the code which is setting proper variables to benchmark hashmode on selected devices.

```py
user_options = context.user_options
user_options.hc_argc = 0
user_options.hc_argv = NULL
user_options.hash_mode = module
user_options.hash_mode_chgd = True
user_options.benchmark = True
user_options.workload_profile = int(workload_profile)
user_options.workload_profile_chgd = True
opencl_device_types = "1,2".encode()  # force allow only GPU and CPU devices
user_options.opencl_device_types = opencl_device_types
backend_devices = ",".join(map(str, targets)).encode()
user_options.backend_devices = backend_devices
```

From my experience I **totally unrecommend** using Hashcat library - I put a lot of work to make it done but it's more difficult approach comparing to executing Hashcat binary.

**Comment by JKerbin** [comment]
OK, guys, I solve this problem by myself.

Actually, I am a fool. I forgot that the *argv[] needs to be ended with NULL !!!

Now I'll tell you what I'm trying to do. I want to calculate how long it takes to crack the code. I get the start timestamp in the parent process and let the child process run hashcat. When the child process return, I get the end timestamp.

I'm going to paste my code here.

```
#include <sys/wait.h>
#include <unistd.h>
#include <stdio.h>
#include <time.h>

int main() {
    int begin_time = 0;
    time_t timep;
    begin_time = time(&timep);

    pid_t pid;
    pid = fork();
    if (pid < 0) {
        printf("fork error.\n");
        return -1;
    } else if (pid == 0) {
        char *argv[] = {"hashcat", "-a3", "-m0", "ffd529f6b20aff2291bf876c68433e78", NULL};
        char *envp[] = {0, NULL};
        execve("/usr/local/hashcat-master/hashcat", argv, envp);
    } else {
        int status = 0;
        wait(&status); //wait the end of child process
        int end_time = 0;
        end_time = time(&timep);
        int running_time = end_time - begin_time;
        printf("running time = %ds\n", running_time);
    }
    return 0;
}
```
