### ISSUE TITLE
How to uninstall/remove

### ISSUE THREAD

**Issue by eva7280** [hashcat/hashcat#3578]
I get a laptop from other person and it has intalled hashcat, Is a Windows 11 SO. Now I want to uninstall/remove it but I don't know how it works and how to do it. Please explain me step by step cause I don't have any knowledge about this.
Help me! Thank you very much.

**Comment by Chick3nman** [comment]
Just delete the hashcat folder/binaries, it's typically not "installed" on Windows.

**Comment by eva7280** [comment]
ok, thank you!!
