### ISSUE TITLE
LLVM error in function m00900_m04

### ISSUE THREAD

**Issue by CthUlhUzzz** [hashcat/hashcat#358]
test@test:~/Downloads/hashcat-3.00$ ./hashcat64.bin -b
hashcat (v3.00-beta-124-g7ba1322) starting in benchmark-mode...

Device #1: AMD ARUBA (DRM 2.43.0, LLVM 3.8.0), 256/1024 MB allocatable, 6MCU
Device #2: AMD OLAND (DRM 2.43.0, LLVM 3.8.0), 256/1024 MB allocatable, 6MCU

LLVM ERROR: Cannot select: 0x3d84ba0: i32,ch = AtomicLoadAdd<Volatile LDST4[%773(addrspace=1)]> 0x47c55c0, 0x3d8c500, Constant:i32<1>
  0x3d8c500: i32 = add 0x3d983e0, 0x3d8cc20
    0x3d983e0: i32,ch = CopyFromReg 0x47c55c0, Register:i32 %vreg352
      0x3d85230: i32 = Register %vreg352
    0x3d8cc20: i32 = shl 0x3d88e40, Constant:i32<2>
      0x3d88e40: i32 = add 0x3d902e0, 0x3d88980
        0x3d902e0: i32,ch = CopyFromReg 0x47c55c0, Register:i32 %vreg91
          0x3d90b30: i32 = Register %vreg91
        0x3d88980: i32,ch = CopyFromReg 0x47c55c0, Register:i32 %vreg360
          0x3d88be0: i32 = Register %vreg360
      0x3d85360: i32 = Constant<2>
  0x3d89270: i32 = Constant<1>
In function: m00900_m04

OS: Ubuntu 16.04
###### 

Mesa: 11.2.0
ICD Loader: 2.2.8

**Comment by neheb** [comment]
You're using Mesa which doesn't support Northern Islands and below. A warning should be added and --force required. Actually, the second GPU should work. Try filtering it out with -d.

GCN 1.0 support for AMDGPU is coming but it not there yet(HD 7000 series).

**Comment by CthUlhUzzz** [comment]
Oh, thx. It works!) But i have next problem with sha3 kernel in benchmark mode:

Speed.Dev.#2.:  9050.8 kH/s (95.53ms)

ERROR: clBuildProgram() : -11 : CL_BUILD_PROGRAM_FAILURE

=== Build Options : -I "/home/test/Downloads/hashcat-3.00/OpenCL/" -I '/home/test/Downloads/hashcat-3.00/OpenCL/' -I /home/test/Downloads/hashcat-3.00/OpenCL/ -I"/home/test/Downloads/hashcat-3.00/OpenCL/" -I'/home/test/Downloads/hashcat-3.00/OpenCL/' -I/home/test/Downloads/hashcat-3.00/OpenCL/ -DVENDOR_ID=2147483648 -DCUDA_ARCH=0 -DVECT_SIZE=2 -DDEVICE_TYPE=4 -DKERN_TYPE=5000 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===
unsupported initializer for address space in m05000_m04
=== Build Log (end) ===
Device #2: Kernel /home/test/Downloads/hashcat-3.00/OpenCL/m05000_a3.cl build failure. Proceed without this device.

Hashtype: SHA-3(Keccak)

**Comment by neheb** [comment]
that error looks like it's for SHA3 not SHA512. SHA512 built successfully.

**Comment by CthUlhUzzz** [comment]
Of course. Message fixed.

**Comment by jsteube** [comment]
> A warning should be added and --force required.

OK, but how exactly can we recognize that case? Is there any OpenCL device-specific parameter?

**Comment by jsteube** [comment]
@CthulhUzzz since I can not reproduce this error, can you please try to find out which initializer is creating the problem?

**Comment by CthUlhUzzz** [comment]
Take me how i can do it)

**Comment by jsteube** [comment]
@CthulhUzzz Since the error is unknown, I can't give you any specific instructions. You need to find out yourself by change code in ther kernel.

**Comment by CthUlhUzzz** [comment]
@jsteube Unfortunately I do not have such skills. Can I help with verbose log or something like that?

**Comment by neheb** [comment]
@jsteube maybe apply a blacklist based on the codename that appears(eg ARUBA).

**Comment by PaveEvil** [comment]
Help pls!

> #hashcat -b
hashcat (v3.10) starting in benchmark-mode...

OpenCL Platform #1: Mesa
========================
- Device #1: AMD REDWOOD (DRM 2.46.0 / 4.8.0-parrot-amd64, LLVM 3.9.1), 716/1024 MB allocatable, 5MCU

LLVM ERROR: Cannot select: 0x56240bce25f0: i32,ch = AtomicLoadAdd<Volatile LDST4[%arrayidx524.i(addrspace=1)]> 0x56240bacc3e0, 0x56240bcdf030, Constant:i32<1>
  0x56240bcdf030: i32 = add 0x56240bce26d0, 0x56240bc87040
    0x56240bce26d0: i32,ch = CopyFromReg 0x56240bacc3e0, Register:i32 %vreg304
      0x56240bc86c50: i32 = Register %vreg304
    0x56240bc87040: i32 = shl 0x56240bcb0500, Constant:i32<2>
      0x56240bcb0500: i32 = add 0x56240bce3980, 0x56240bce39f0
        0x56240bce3980: i32,ch = CopyFromReg 0x56240bacc3e0, Register:i32 %vreg46
          0x56240bce24a0: i32 = Register %vreg46
        0x56240bce39f0: i32,ch = CopyFromReg 0x56240bacc3e0, Register:i32 %vreg312
          0x56240bce02c0: i32 = Register %vreg312
      0x56240bd43b20: i32 = Constant<2>
  0x56240bc8a520: i32 = Constant<1>
In function: m00900_m04

**Comment by neheb** [comment]
Reports like these make me think Mesa should be blacklisted

@jsteube ?
