### ISSUE TITLE
Can't use pocl with the latest build

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#359]
Log:

mangix@mangix-laptop:~/devstuff/oclHashcat$ ./hashcat --opencl-device-types=1 -b
hashcat (v3.00-beta-126-g34bcbb3) starting in benchmark-mode...

Device #1: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, skipped
Device #2: pthread-Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz, skipped

ERROR: No devices found/left

mangix@mangix-laptop:~/devstuff/oclHashcat$

**Comment by jsteube** [comment]
I've fixed this so that shows a warning:

```
Device #1: Hawaii, skipped
Device #2: WARNING: not native intel opencl runtime, expect massive speed loss
           You can use --force to override this but do not post error reports if you do so
Device #2: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, skipped
```

and with --force you should be able to use it. 

However, it's recommended to use intels opencl sdk, which is almost twice as fast. Please close the ticket if ok for you

**Comment by neheb** [comment]
perfect
