### ISSUE TITLE
Recovered NTLM password in hex is incorrect

### ISSUE THREAD

**Issue by mfrade** [hashcat/hashcat#3592]
**Describe the bug**
I made a test with the "aá" password with NTLM hash, and hashcat showed this as the result: `$HEX[61e1]`, but it should be `$HEX[6100e100]` because NTLM is an MD4 hash with a UTF-16LE encoding (2 bytes per character).

**To Reproduce**
```Shell
# Generate de NTLM hash:
$ echo -n "aá" | iconv -f UTF-8 -t UTF-16LE | openssl dgst -md4 -provider legacy
8fdba81f5a363a5b13c653cbe1325d60
```
In UTF-16LE  `aá` has a total of 4 bytes:
```Shell
$ echo -n "aá" | iconv -f UTF-8 -t UTF-16LE | xxd
00000000: 6100 e100
```
So, this command should work (brute force with 4 bytes):
```Shell
hashcat -m1000 -a3 8fdba81f5a363a5b13c653cbe1325d60 ?b?b?b?b
```
but it results in `Recovered: 0`

However, this one works (only 2 bytes):
```Shell
hashcat -m1000 -a3 8fdba81f5a363a5b13c653cbe1325d60 ?b?b
```
and it displays this as solution: `$HEX[61e1]` (which isn't correct)

**Expected behavior**
1. the mask `?b?b?b?b` should work
2. the correct recovered password should be `$HEX[6100e100]`

**Hardware/Compute device (please complete the following information):**
GPU: Nvidia GeForce RTX 3060 Laptop 
my OS: Ubuntu 22.04.1

**Hashcat version (please complete the following information):**
hashcat: v6.2.6

**Diagnostic output compute devices:**

```Console
$ nvidia-smi
Wed Jan 25 22:16:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   36C    P3    N/A /  N/A |      6MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3298      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

```

[clinfo.txt](https://github.com/hashcat/hashcat/files/10504216/clinfo.txt)

[hashcat-I.txt](https://github.com/hashcat/hashcat/files/10504217/hashcat-I.txt)

[lspci.txt](https://github.com/hashcat/hashcat/files/10504218/lspci.txt)

**Comment by Chick3nman** [comment]
Hashcat does the UTF-16LE conversion in the kernel, which is transparent to you as a user. The password you get back from the kernel will be the password you login with on Windows, which is $HEX[61e1] in this case, not $HEX[6100e100]. You are supplying the $password to the NTLM construction which looks like MD4(UTF-16LE($password)). If you want to supply the UTF-16LE of the password yourself you would want to use -m 900, MD4. 

This appear to be working as intended and not a bug.

**Comment by mfrade** [comment]
@Chick3nman 
The `-m 900` works the way I expected.
However,  here's another test with a multi-byte character that fails with the `-m 1000`:

1. create a new user on Windows 10
2. insert "😀" as password (`\U1f600`) -- the windows dialogue box displays 2 dots like if I have entered 2 characters because it has a total of 4 bytes:
```Console
echo -n "\U1f600" | iconv -f UTF-8 -t UTF-16LE | xxd
00000000: 3dd8 00de
```
3. extract the NTLM hash with pypykatz: `4b58a10cc20a4e7d808d218e1f80aabc`

The first attempt with **2 bytes** to crack fails (as I expected):
```Console
hashcat -a3 -m1000 4b58a10cc20a4e7d808d218e1f80aabc ?b?b
Recovered........: 0/1 (0.00%)
```
The second attempt with **4 bytes**  also fails:
```Console
hashcat -a3 -m1000 4b58a10cc20a4e7d808d218e1f80aabc ?b?b?b?b
Recovered........: 0/1 (0.00%)
```
I was expecting this command to work! 

However, this command with `-m 900` worked:
```Console
hashcat -a3 -m900 4b58a10cc20a4e7d808d218e1f80aabc ?b?b?b?b --show
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[3dd800de]
```

I wonder if the implementation of the `-m 1000` has some speed optimizations that prevent it from properly processing UTF-16LE multi-byte characters. 

---8<---------------
Edit:

Creating a UTF-8 wordlist with the multi-byte character works well:

```Console
echo -n "\U1f600" > wl.txt
hashcat -a0 -m1000 4b58a10cc20a4e7d808d218e1f80aabc wl.txt --potfile-disable
4b58a10cc20a4e7d808d218e1f80aabc:😀
```
Shouldn't the internal conversion from `UTF-8` to `UTF-16LE` be turned off when using bytes `?b` in the `-m 1000` mode?

**Comment by Chick3nman** [comment]
This appears to be a different and real issue with specifically the -a 3 pure kernel but it does look like a valid issue. For some context, you can see that we use different kernels with varying degrees of UTF-16LE from here: https://github.com/hashcat/hashcat/blob/master/docs/limits.txt#L26

I will reopen this issue until we can figure out why the -a 3 kernel fails to crack this NTLM with ?b?b?b?b as I believe it should.

**Comment by ghost** [comment]
I believe that hashcat should favor correctness over speed, and that the notoriously buggy NTLM implementation should be finally made right. It's long overdue. There are easily tens of posts on the forum about that.

https://hashcat.net/forum/thread-8456-post-45288.html#pid45288

**Comment by Chick3nman** [comment]
> I believe that hashcat should favor correctness over speed, and that the notoriously buggy NTLM implementation should be finally made right. It's long overdue. There are easily tens of posts on the forum about that.

Since 6.2.1 we actually do have a complete UTF-16LE conversion implementation for the pure kernels. Only the optimized use the old implementation for performance, but those kernels also impose many other limitations so it's generally acceptable there. That would make this simply a bug in the pure kernel that needs to be tracked down. Reference: https://github.com/hashcat/hashcat/blob/master/docs/limits.txt#L36

**Comment by mfrade** [comment]
That page says:
```
This applies to optimized kernels (-O) only
```
but I never used the `-O` option in my tests, is it turned on by default for NTLM?

**Comment by Chick3nman** [comment]
> That page says:
> 
> ```
> This applies to optimized kernels (-O) only
> ```
> 
> but I never used the `-O` option in my tests, is it turned on by default for NTLM?

I guess that description could be indented or something to make it more clear. Only the block of text immediately following that line applies to Optimized kernels. Line 36 then goes on to explain that we have a "true" implementation of the conversion process which takes place in the pure kernels. The default kernel selected is the pure kernel and thus should crack this password, which it actually does when using the -a 0 kernel. The failure appears to be specific to the -a 3 pure kernel from what I can tell but I'm still walking through it to try and find why it's not completing the conversion correctly.

**Comment by jsteube** [comment]
I can confirm that this is a bug and with commit https://github.com/hashcat/hashcat/commit/86f3e1f5b8e3e5d61bdfc4cdefce4c1829dd9f3f I've done some change in order to fix it. 

However, the problem is a lot more complicated than one might think and therefore the fix could raise questions.

The Problem is here in this section https://github.com/hashcat/hashcat/blob/v6.2.6/OpenCL/m01000_a3-pure.cl#L122-L128

```
    md4_ctx_vector_t ctx;

    md4_init_vector (&ctx);

    md4_update_vector_utf16le (&ctx, w, pw_len);

    md4_final_vector (&ctx);
```

You can see that the -a 3 kernel uses vector functions, whereas the -a 0 kernel does not https://github.com/hashcat/hashcat/blob/v6.2.6/OpenCL/m01000_a0-pure.cl#L102-L108

```
    md4_ctx_t ctx;

    md4_init (&ctx);

    md4_update_utf16le (&ctx, tmp.i, tmp.pw_len);

    md4_final (&ctx);
```

And the difference between the both algorithm can be seen here

https://github.com/hashcat/hashcat/blob/v6.2.6/OpenCL/inc_hash_md4.cl#L368-L391

and here

https://github.com/hashcat/hashcat/blob/v6.2.6/OpenCL/inc_hash_md4.cl#L1682-L1683

To make it short, the vector function does not support true conversion. Now the reason is simply because of performance (of old GPU and in general CPU with SIMD [all modern]). New GPU do not require SIMD to perform fully.

So we could argue that if we use maskprocessor (for instance) and pipe it to hashcat (which then results in -a 0 mode), it would crack correctly. However this is a fast hash so I can see the need to avoid any pipes between external generators and hashcat.

So I had change the code to do this:

```
    #if VECT_SIZE == 1

    md4_ctx_t ctx;

    md4_init (&ctx);

    md4_update_utf16le (&ctx, w, pw_len);

    md4_final (&ctx);

    #else

    md4_ctx_vector_t ctx;

    md4_init_vector (&ctx);

    md4_update_vector_utf16le (&ctx, w, pw_len);

    md4_final_vector (&ctx);

    #endif
```

This way we can maintain enable true conversion for devices that do not requires SIMD (like modern GPU), but for slow devices (like modern CPU), we keep the "fake" conversion. That could confuse users a lot, but I think is still the best solution we can do. At least we should mention it in docs/limits.txt

With this new patch you might also find strange results like this:

```
$ ./hashcat -m 1000 4b58a10cc20a4e7d808d218e1f80aabc -a 3 ?b?b?b?b
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[faffe11a]
```

Note, this is not a collision! The code we use to convert between utf8 and utf16le is kind of incomplete, but because for performance reasons.  So it skips some of the tests required to identify a valid utf8 input and therefore it's not what a true conversion function would do instead. Because of that, the input `$HEX[faffe11a]` ends up (in this case) a VALID output `$HEX[3dd800de]` . However, it should motive you to continue your search for the real plain, for instance by using --keep-guessing. If you do, you find this:

```
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[faffe11a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f87fe11a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa00a11a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f940a11a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa02205a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fbc2205a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa02211a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f882211a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa01611a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f941611a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa021f9a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f8821f9a]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[fa021eda]
4b58a10cc20a4e7d808d218e1f80aabc:$HEX[f8821eda]
```

Now even with --keep-guessing it will not show ALL matching password candidates. The reason for that is explained here https://github.com/hashcat/hashcat/blob/v6.2.6/docs/limits.txt#L38-L54

As a proof it works, you can do something like this: `./hashcat -m 1000 4b58a10cc20a4e7d808d218e1f80aabc -a 3 ?b?b?b80 --hex-charset`

```
4b58a10cc20a4e7d808d218e1f80aabc:😀
```

The new patch is not perfect, but I think it is the best trade off between functionality and performance. You can still switch to -a 0 (using maskprocessor) if needed.

**Comment by mfrade** [comment]
Thank you @jsteube, for the detailed answer.

I've downloaded and tested the patched version of hashcat, and it has, in fact, some weird behaviour (as pointed out).
I wonder if it would be possible to have an alternate NTLM mode (e.g. `-m1001`) that correctly implements the UTF-16LE conversion even with some performance cost. This new mode could be a fallback whenever a user identifies some weird behaviour due to optimizations.

This patch also fixes the problem I identified in my first post with the `aá` example. Now it displays the correct password:
```Shell
./hashcat -m1000 -a3 8fdba81f5a363a5b13c653cbe1325d60 ?b?b?b --potfile-disable
8fdba81f5a363a5b13c653cbe1325d60:aá
```
However, one must pay attention because hashcat expects its input to be UTF-8 by default and in this example, it must have 3 bytes: `a -> 1 byte` and `á -> 2 bytes`.

**Comment by jsteube** [comment]
@mfrade Retry with latest commit

**Comment by mfrade** [comment]
@jsteube, the new patch doesn't present any fake collisions with emojis:

```Console
./hashcat -m 1000 -a3 4b58a10cc20a4e7d808d218e1f80aabc ?b?b?b?b --potfile-disable --keep-guessing
4b58a10cc20a4e7d808d218e1f80aabc:😀

./hashcat -m 1000 -a3 c42bad6e423092d1d01ff8ef11e12b8c ?b?b?b?b --potfile-disable --keep-guessing
c42bad6e423092d1d01ff8ef11e12b8c:🔒
```

Edit:

However, I noticed something strange.  I created the `hashes.txt` file with 6 characters to do some testing:
```Console
chars=(a á Э ᠠ 😀 🔒)
for char in "${chars[@]}"; do
  ntlm=$(echo -n "$char" | iconv -f UTF-8 -t UTF-16LE | openssl dgst -md4 -provider legacy | cut -f2 -d" ")
  echo "$char = $ntlm"
  echo $ntlm >> hashes.txt
done

# Ascii
a = 186cb09181e2c2ecaac768c47c729904

# Latin-1
á = 4986f95c2216e11d1aaca503a714e225

# Cyrillic
Э = 6c81d97a082d51b2dd6e2c7254057860

# Mongolian
ᠠ = 62a3b633f0fadfcd90accb2495ef892c

# Emoticon
😀 = 4b58a10cc20a4e7d808d218e1f80aabc

# Miscellaneous Symbols and Pictographs
🔒 = c42bad6e423092d1d01ff8ef11e12b8c
```

To try to identify the problem, I cloned the hashcat repository 3 times and did a different `git checkout` on each folder:
```Console
# stable version
cd hashcat-v6.2.6
git checkout v6.2.6
make
mv hashcat hashcat-v6.2.6
cd ..

# previous patch
cd hashcat-86f3e1f
git checkout 86f3e1f
make
mv hashcat hashcat-86f3e1f
cd ..

# current patch
cd hashcat-6bd94c3
git checkout 6bd94c3
make
mv hashcat hashcat-6bd94c
```

I've run these tests:
```Console
./hashcat-v6.2.6 -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable >> ../results-v6.2.6.txt
./hashcat-v6.2.6 -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable --keep-guessing >> ../results-v6.2.6--keep-guessing.txt

./hashcat-86f3e1f -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable >> ../results-86f3e1f.txt
./hashcat-86f3e1f -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable --keep-guessing >> ../results-86f3e1f--keep-guessing.txt

./hashcat-6bd94c3 -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable >> ../results-6bd94c3.txt
./hashcat-6bd94c3 -m 1000 -a3 ../hashes.txt ?b?b?b?b -i --potfile-disable --keep-guessing >> ../results-6bd94c3--keep-guessing.txt
```

These are the results:
```Console
grep -n "Recovered\|Guess.Mask" results*.txt
results-v6.2.6--keep-guessing.txt:66:Guess.Mask.......: ?b [1]
results-v6.2.6--keep-guessing.txt:69:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-v6.2.6--keep-guessing.txt:92:Guess.Mask.......: ?b?b [2]
results-v6.2.6--keep-guessing.txt:95:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-v6.2.6--keep-guessing.txt:118:Guess.Mask.......: ?b?b?b [3]
results-v6.2.6--keep-guessing.txt:121:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-v6.2.6--keep-guessing.txt:139:Guess.Mask.......: ?b?b?b?b [4]
results-v6.2.6--keep-guessing.txt:142:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
# zero recovered!

results-v6.2.6.txt:62:Guess.Mask.......: ?b [1]
results-v6.2.6.txt:65:Recovered........: 2/6 (33.33%) Digests (total), 2/6 (33.33%) Digests (new)
results-v6.2.6.txt:89:Guess.Mask.......: ?b?b [2]
results-v6.2.6.txt:92:Recovered........: 2/6 (33.33%) Digests (total), 2/6 (33.33%) Digests (new)
results-v6.2.6.txt:116:Guess.Mask.......: ?b?b?b [3]
results-v6.2.6.txt:119:Recovered........: 2/6 (33.33%) Digests (total), 2/6 (33.33%) Digests (new)
results-v6.2.6.txt:138:Guess.Mask.......: ?b?b?b?b [4]
results-v6.2.6.txt:141:Recovered........: 2/6 (33.33%) Digests (total), 2/6 (33.33%) Digests (new)
# 2 recovered:
# 186cb09181e2c2ecaac768c47c729904:a
# 4986f95c2216e11d1aaca503a714e225:$HEX[e1]

results-86f3e1f--keep-guessing.txt:65:Guess.Mask.......: ?b [1]
results-86f3e1f--keep-guessing.txt:68:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-86f3e1f--keep-guessing.txt:93:Guess.Mask.......: ?b?b [2]
results-86f3e1f--keep-guessing.txt:96:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-86f3e1f--keep-guessing.txt:120:Guess.Mask.......: ?b?b?b [3]
results-86f3e1f--keep-guessing.txt:123:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-86f3e1f--keep-guessing.txt:151:Guess.Mask.......: ?b?b?b?b [4]
results-86f3e1f--keep-guessing.txt:154:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
# zero recovered!

results-86f3e1f.txt:61:Guess.Mask.......: ?b [1]
results-86f3e1f.txt:64:Recovered........: 1/6 (16.67%) Digests (total), 1/6 (16.67%) Digests (new)
results-86f3e1f.txt:90:Guess.Mask.......: ?b?b [2]
results-86f3e1f.txt:93:Recovered........: 3/6 (50.00%) Digests (total), 3/6 (50.00%) Digests (new)
results-86f3e1f.txt:118:Guess.Mask.......: ?b?b?b [3]
results-86f3e1f.txt:121:Recovered........: 4/6 (66.67%) Digests (total), 4/6 (66.67%) Digests (new)
results-86f3e1f.txt:140:Guess.Mask.......: ?b?b?b?b [4]
results-86f3e1f.txt:143:Recovered........: 6/6 (100.00%) Digests (total), 6/6 (100.00%) Digests (new)
# 6 recovered:
# 186cb09181e2c2ecaac768c47c729904:a
# 4986f95c2216e11d1aaca503a714e225:á
# 6c81d97a082d51b2dd6e2c7254057860:Э
# 62a3b633f0fadfcd90accb2495ef892c:ᠠ
# 4b58a10cc20a4e7d808d218e1f80aabc:$HEX[faffe11a] <-- fake collision
# c42bad6e423092d1d01ff8ef11e12b8c:🔒


results-6bd94c3--keep-guessing.txt:65:Guess.Mask.......: ?b [1]
results-6bd94c3--keep-guessing.txt:68:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-6bd94c3--keep-guessing.txt:93:Guess.Mask.......: ?b?b [2]
results-6bd94c3--keep-guessing.txt:96:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-6bd94c3--keep-guessing.txt:119:Guess.Mask.......: ?b?b?b [3]
results-6bd94c3--keep-guessing.txt:122:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
results-6bd94c3--keep-guessing.txt:142:Guess.Mask.......: ?b?b?b?b [4]
results-6bd94c3--keep-guessing.txt:145:Recovered........: 0/6 (0.00%) Digests (total), 0/6 (0.00%) Digests (new)
# zero recovered!

results-6bd94c3.txt:61:Guess.Mask.......: ?b [1]
results-6bd94c3.txt:64:Recovered........: 1/6 (16.67%) Digests (total), 1/6 (16.67%) Digests (new)
results-6bd94c3.txt:90:Guess.Mask.......: ?b?b [2]
results-6bd94c3.txt:93:Recovered........: 3/6 (50.00%) Digests (total), 3/6 (50.00%) Digests (new)
results-6bd94c3.txt:117:Guess.Mask.......: ?b?b?b [3]
results-6bd94c3.txt:120:Recovered........: 3/6 (50.00%) Digests (total), 3/6 (50.00%) Digests (new)
results-6bd94c3.txt:141:Guess.Mask.......: ?b?b?b?b [4]
results-6bd94c3.txt:144:Recovered........: 5/6 (83.33%) Digests (total), 5/6 (83.33%) Digests (new)
# 5 recovered:
# 186cb09181e2c2ecaac768c47c729904:a
# 4986f95c2216e11d1aaca503a714e225:á
# 6c81d97a082d51b2dd6e2c7254057860:Э
# 4b58a10cc20a4e7d808d218e1f80aabc:😀
# c42bad6e423092d1d01ff8ef11e12b8c:🔒
# not able to find this one --> 62a3b633f0fadfcd90accb2495ef892c:ᠠ
```

For some reason, in these tests, the `--keep-guessing` option always returns zero matches. Am I doing something wrong?
Also, the latest patch `6bd94c3` is not able to find the Mongolian char "ᠠ"

**Comment by jsteube** [comment]
Yes, keep-guessing will always return 0 cracks in that particular line, because if it would count cracks you'd get stuff like 43/5 cracked which is even more unexpected.

**Comment by jsteube** [comment]
OK the 62a3b633f0fadfcd90accb2495ef892c should also crack with https://github.com/hashcat/hashcat/commit/9ec6392c92fbe2076049c3d436cb052c9a49286f

Please check

**Comment by mfrade** [comment]
@jsteube, everything is working as expected now. Thank you for your effort and time. 

Here's the test I made with 34 different chars:

```Console
chars=(a ä ž ɏ ɐ ˫ μ ӿ ԟ Հ ॿ ৰ ੬ ૪ ୷ ௬ ౷ ೱ ൕ ෂ ๏ ໔ ࿖ ည ᇽ ፻ ᎇ Ꮻ ᙬ Э ᠠ € 😀 🔒)
for char in "${chars[@]}"; do
  ntlm=$(echo -n "$char" | iconv -f UTF-8 -t UTF-16LE | openssl dgst -md4 -provider legacy | cut -f2 -d" ")
  echo "$char = $ntlm"
  echo $ntlm >> hashes.txt
done

./hashcat-9ec6392 -m 1000 -a3 hashes.txt ?b?b?b?b -i --potfile-disable > results-9ec6392.txt

grep -n "Recovered\|Guess.Mask" results*.txt
61:Guess.Mask.......: ?b [1]
64:Recovered........: 1/34 (2.94%) Digests (total), 1/34 (2.94%) Digests (new)
98:Guess.Mask.......: ?b?b [2]
101:Recovered........: 11/34 (32.35%) Digests (total), 11/34 (32.35%) Digests (new)
146:Guess.Mask.......: ?b?b?b [3]
149:Recovered........: 32/34 (94.12%) Digests (total), 32/34 (94.12%) Digests (new)
168:Guess.Mask.......: ?b?b?b?b [4]
171:Recovered........: 34/34 (100.00%) Digests (total), 34/34 (100.00%) Digests (new)
```
All of them were "retrieved" without errors:
```
186cb09181e2c2ecaac768c47c729904:a
3104eab484d59efabcea2c44b07f41d3:ä
ae591521c6cd9971c53917aabc6bfb2b:ž
7f9f7ee8ea6fae5726852c6767adab32:ɏ
56dbdc35db6ef333383858a27d968ae1:ɐ
33f667b0f0c62a8d5a75aa5ea6e4162f:˫
0fbf19b9d1094a0ebbae12c254d459df:μ
cf9587f9b0f5668f97269c66d9f09877:ӿ
3f67643ddb56c03e058cdced1e0d93b2:ԟ
69e2aebe143f6a25d1a9bc23d7170622:Հ
e367485be68c957b0856fb1dc9dd8d9c:ॿ
6d02686f87ae60b7691b5363d95644fc:ৰ
51a35b21b9e952a27c09559192a1c376:੬
8642a381dfdbfbb1d884b2a284acc915:૪
de145f3243bd0ddcdd6adc0ef9a2b4c2:୷
6dc2d105b3205ed7ecc276a6416354f2:௬
2c74ac1ea99026eeb73f075c92761fa7:౷
70bce7d77f70eb72381b69e17b892ddf:ೱ
6943c10b0d69d04351e2c0ea57e43e15:ൕ
23cf172031371e4792b3c035602e7c40:ෂ
418411c7c9314b5562fe97d58d2110ce:๏
617cf76a5d9219b5a7f0157cbeb89a79:໔
5ca42bedc84ab7ccc00fdada2ca1a3d9:࿖
b0684fb35f5865bf1389f710545eefd0:ည
a70289fc3fd1f86784111e897e0819ce:ᇽ
0871e4ef9ccc043a008103a8cb7f6f96:፻
5724caa62b635ec42b60187aa04c4b4c:ᎇ
e9571a28a6964fa804b0ed89d4014ffa:Ꮻ
ba0105a8375029cab8306cdf58b1ce78:ᙬ
6c81d97a082d51b2dd6e2c7254057860:Э
62a3b633f0fadfcd90accb2495ef892c:ᠠ
030926b781938db4365d46adc7cfbcb8:€
4b58a10cc20a4e7d808d218e1f80aabc:😀
c42bad6e423092d1d01ff8ef11e12b8c:🔒
```

**Comment by Chick3nman** [comment]
Looks like this was fixed and passed the above test, please close if there's no issues left.
