### ISSUE TITLE
Metamask -m 26600 -- salt wrong length -- Token Length exception

### ISSUE THREAD

**Issue by s6410** [hashcat/hashcat#3595]
I have extracted SALT, IV and CT from the file "persist-root" on an iOS device. It looks like the information you get from the json file of the metamask browser plugin.

The problem is that the SALT length is 16 after base64-decode and the IV length is 24 after base64-decode.

These values differ from the values in the module for mode 26600 here, were salt length should be 44. [https://github.com/hashcat/hashcat/blob/master/src/modules/module_26600.c#L144](https://github.com/hashcat/hashcat/blob/master/src/modules/module_26600.c#L144)

Testing against example data from Meta Mask's website (https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-recover-your-Secret-Recovery-Phrase) regarding iOS makes Hashcat crash, throwing a "Token length exception".

Original data:
`{"cipher":"JaX8Z80QMzzqA4XMgPsUuleNLIuxvchXZ5q1SO9GO1kuNUmokUke06op9EF0ZU4WssILfUZ0yKI5kjzYY9H12t5aGb43BOAWJwlKuC8neXWeL5enoD/L05eDC9tzZEBupLwF7cGG6JdPHHQKdRDWWbQM+TUo6EvZv7LClPZQVJ17uowGvPMPB0UwXPea7DP/dE5DYleHmX1rhxAJr1YN4HUPAYpCCReU4W4/2QsaM+E=","iv":"dcabe6ed590ae3ee8e056c7844c583d7","salt":"h6IkHlWjloBgc9+KiGTYvQ==","lib":"original"}`

Hashcat formatted data:
`$metamask$h6IkHlWjloBgc9+KiGTYvQ==$dcabe6ed590ae3ee8e056c7844c583d7$JaX8Z80QMzzqA4XMgPsUuleNLIuxvchXZ5q1SO9GO1kuNUmokUke06op9EF0ZU4WssILfUZ0yKI5kjzYY9H12t5aGb43BOAWJwlKuC8neXWeL5enoD/L05eDC9tzZEBupLwF7cGG6JdPHHQKdRDWWbQM+TUo6EvZv7LClPZQVJ17uowGvPMPB0UwXPea7DP/dE5DYleHmX1rhxAJr1YN4HUPAYpCCReU4W4/2QsaM+E=`

**Hashcat version (please complete the following information):**
 - OS: Windows
 - Version: 6.2.6

**Diagnostic output compute devices:**
```
Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 256

Hashfile 'metamask_exampleHash.txt' on line 1 ($metam...hxAJr1YN4HUPAYpCCReU4W4/2QsaM+E=): Token length exception

* Token length exception: 1/1 hashes
  This error happens if the wrong hash type is specified, if the hashes are
  malformed, or if input is otherwise not as expected (for example, if the
  --username option is used but no username is present)

No hashes loaded.

Started: Thu Jan 26 09:26:18 2023
Stopped: Thu Jan 26 09:26:19 2023
```

**Comment by ventaquil** [comment]
Duplicate? Check my comment - https://github.com/hashcat/hashcat/issues/3429#issuecomment-1314682064.

**Comment by s6410** [comment]
> Duplicate? Check my comment - https://github.com/hashcat/hashcat/issues/3429#issuecomment-1314682064.

Hi!
Not entirely sure if it is the same problem. Is the salt in your example compliant with the hard coded length requirement, linked in my post?

My example is with only one wallet, that would be different from the other issue?

I may have missed something and you could of course be right!:)

**Comment by s6410** [comment]
I have tried with another MetaMask installation on another iPhone now, same result as my other try. Length of salt is only 16.

Version of MetaMask for iOS is 5.12.0

**Comment by sceriz** [comment]
26600 mode works for metamask's desktop browser extension. The mobile wallet's storage is a bit different and therefore a new mode would need to be made to accomondate for it in hashcat. 

There is a working implementation of mobile metamask decryption in [3rditeration's fork of btcrecover](https://github.com/3rdIteration/btcrecover/commit/bbabff44be7ab03df812eb44d34523ade6d9a50b).

**Comment by thatux** [comment]
So this should be labeled `new algorithm` as the metamask iOS implementation is different than metamask's browser implementation. this is not a bug. not sure how the iOS and browser differ and whether they can be supported by a single kernel.

**Comment by matrix** [comment]
Hi,
I have implemented the module that supports Metamask Mobile, I just need to figure out how to perform the verification to see if the password is the correct one or not. If any of you already know how to do that ... post here so we don't waste time :D
Thanks!

Edit: found it :)

**Comment by s6410** [comment]
I finally had time to test this. @matrix fantastic work! tried on metamask on iOS and it was a success!

I extracted the hash from "persist-root" with the updated extraction tool and the new mode  31900.

Closing the issue
