### ISSUE TITLE
permutation attack (-a 4) is buggy

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#36]
According to this wiki page: https://hashcat.net/wiki/doku.php?id=permutation_attack
the output of all permutation of the string "ABC" should be a set of 6 lines.

But if I run:
 ./hashcat-cli64.bin -a 4 --stdout dict.txt

where dict.txt just contains the string "ABC", I get an output of only 4 results.

This seems to be a bug. We need to troubleshoot this a little bit.
Thx

**Comment by jsteube** [comment]
Good find, good solution
