### ISSUE TITLE
Keccak fails with Beignet

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#360]
Log: 

mangix@mangix-laptop:~/devstuff/oclHashcat$ ./hashcat -b -m 5000
hashcat (v3.00-beta-126-g34bcbb3) starting in benchmark-mode...

Device #1: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 1024/2048 MB allocatable, 24MCU
Device #2: pthread-Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz, skipped

Hashtype: SHA-3(Keccak)

drm_intel_gem_bo_context_exec() failed: Input/output error

ERROR: clEnqueueNDRangeKernel() : -5 : CL_OUT_OF_RESOURCES

the computer freezes before displaying the error

**Comment by jsteube** [comment]
I can't reproduce, don't have that card.

**Comment by neheb** [comment]
fixed by switching to the padoka PPA. seems the ubuntu packaged version is no good.
