### ISSUE TITLE
When applying multiple rule files, hashcat does not output an error if the limit of 31 functions is exceeded in combinations.

### ISSUE THREAD

**Issue by tabularasa007** [hashcat/hashcat#3605]
**How to reproduce**
Create rule files to purge every special char of ?s.
``?s = «space»!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~``

Because of the limitation of max 31 functions per rule, we need to create at least _two_ rule files.
e.g. 
always_purge_special_chars.1.rule
``@  @! @" @# @$ @% @& @' @( @) @* @+ @, @- @. @/ @: @; @< @= @> @? @@ @[ @\ @] @^ @_ @` @{ @|``

always_purge_special_chars.2.rule
`@} @~`

Then create a dictionary with the line:
``«space»!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~``

Apply both created rules in one step:
`hashcat.bin --stdout -a0 dict.txt -r always_purge_special_chars.1.rule -r always_purge_special_chars.2.rule`

**Result:**
Hashcat will not output an error even though not all combined rules will be applied. This happens both with --stdout applied or not.
(Hashcat will also not output an error if you use only one rule file, but with several valid rules. Then a "rule" with more than 31 functions will also go unnoticed. However if the rule file consists of only the one "rule" with more than 31 functions, hashcat will output the message "No valid rules left.")

**Expected behavior:**
Print an error message.

**Comment by justpretending** [comment]
If you make it 32 rules, hashcat will complain.

```
Cannot convert rule for use on OpenCL device in file 2.rule on line 2: @  @! @" @# @$ @% @& @' @( @) @* @+ @, @- @. @/ @: @; @< @= @> @? @@ @[ @\ @] @^ @_ @` @{ @| $1
```

```
$ cat 1.rule
$1
@  @! @" @# @$ @% @& @' @( @) @* @+ @, @- @. @/ @: @; @< @= @> @? @@ @[ @\ @] @^ @_ @` @{ @| $1
```

**Comment by jsteube** [comment]
Should be fixed with commit https://github.com/hashcat/hashcat/commit/42f574646e5e4cda3d33ebe170fcd1c7466298bf

Please test and close the issue if fix is ok

**Comment by tabularasa007** [comment]
Works fine, thank you for taking care of this!
