### ISSUE TITLE
Hashcat mistakeningly applying rules to *the hashes* instead of following wordlist

### ISSUE THREAD

**Issue by ipaqmaster** [hashcat/hashcat#3606]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**
This command `hashcat -m 22000 hashes.22000 wordlist.txt -r rule.rule`

Applies the rules to the actual WPA* hashes seen in the hashes.22000 file, instead of the intended wordlist.txt file. Misleadingly causing hashcat to say Exhausted immediately even for months worth of hash work (Because the length of the hashes exceed the length limit of an actual intended passphrase) so hashcat just exits and calls it a day.

This behavior can be verified by tacking `--stdout` on the end and watching hashcat output an entire WPA hash with the number 00001 on the end (For example. Among other transformative rules)

**To Reproduce**
The command provided above reproduces this.

**Expected behavior**
Generating candidates using the wordlist provided in conjunction with the ruleset provided. 

**Hardware/Compute device (please complete the following information):**
- Compute device name: [e.g. RTX2080Ti]
By coincidence I happen to use a 2080Ti.

- OpenCL/CUDA driver name: [e.g. NVIDIA DRIVER]
nvidia/525.85.05
- OpenCL/CUDA driver version: [e.g. 465.21]
opencl-nvidia 525.85.05-1
- OpenCL/CUDA driver source: [e.g. runtime installer/.exe installer]
Archlinux official repository
**Hashcat version (please complete the following information):**
 - OS: [e.g. Linux]
Linux 6.1.8-arch1-1
 - Distribution: [e.g. Ubuntu 18.04]
Archlinux
 - Version: [e.g. 6.2.0]
v6.2.6

**Diagnostic output compute devices:**
NA

```
For NV: Post nvidia-smi output. This tool also exist on Windows
For AMD ROCm: Post rocm-smi and rocminfo output
[NA]
```

```
Post clinfo output
[NA]
```

```
Post hashcat -I output
[NA]
```

```
On Linux: post lspci output
[NA]
```

**Additional context**

It just seems hashcat's latching onto the hashfile assuming that it is the input text file for guessing with. I may be able to work around this using flags.

**Comment by ipaqmaster** [comment]
To clarify / TL;DR - Hashcat is applying the rules to each hash line treating them as the wordlist and is completely ignoring the actual provided wordlist.

This causes hashcat to output (Verifiable with `--stdout`) candidates such as: (Fake example hex used)


`WPA*01*0201400206ded4731a07e77d865aae52*4ae191c0a2ac*3498b5947a56*e9118b80000d6fbabf***269`
`WPA*01*0201400206ded4731a07e77d865aae52*4ae191c0a2ac*3498b5947a56*e9118b80000d6fbabf***270`
`WPA*01*0201400206ded4731a07e77d865aae52*4ae191c0a2ac*3498b5947a56*e9118b80000d6fbabf***271`
`WPA*01*0201400206ded4731a07e77d865aae52*4ae191c0a2ac*3498b5947a56*e9118b80000d6fbabf***272`

And so forth. Which are NOT valid WPA passphrases.

**Comment by ghost** [comment]
That is working as expected. You don't use a hashlist with `--stdout`, only wordlists.

**Comment by Chick3nman** [comment]
This is, as @justpretending stated, not a bug and seemingly working as intended. `--stdout` is for generating candidate only output on stdout and thus doesn't take a hash mode or hash list. It is considering your hash list as a wordlist and processing it as such. The only issue that may be present here as far as I can tell is that you were allowed to specify `-m` with `--stdout` and it didn't throw a warning

**Comment by ipaqmaster** [comment]
Ok sure for --stdout however but it still doesn't explain how my 2080Ti immediately blasts through (Rejects) 7.4billion guesses when it has a  hashrate for mode 22000 of 880KHs. Nowhere near enough to actually process that many.

**Comment by Chick3nman** [comment]
Sounds like a separate issue. Can you paste the status output that shows that?

**Comment by philsmd** [comment]
I think we can close this specific github issue, because it is a misunderstanding. Please open new issues for unrelated problems. Thank you very much

**Comment by ipaqmaster** [comment]
I made this issue for my specific "it's applying the rules to the hashes themselves" problem.. wasn't my misunderstanding...

Making a new ticket for the same problem.
