### ISSUE TITLE
Hashcat not working 

### ISSUE THREAD

**Issue by Aviril7** [hashcat/hashcat#3607]
Am using Kali nethunter installed through `Termux on Android phone` and I install hashcat with the command

`$ sudo apt install hashcat`

anytime am trying to run hashcat with the command

`┌──(kali㉿localhost)-[~]`
`└─$ hashcat -m 0 -a 3 -1 ?u -2 -?l?u?d -3 ?d hash ?1?2?2?2?3?3?3`

It keeps giving below quotes

`[hwloc/linux] failed to find sysfs cpu topology directory, aborting linux discovery.
Not enough memory to run on this device.`

Any solution or any idea on what it's saying

**Comment by Chick3nman** [comment]
Android devices without a compliant runtime or sufficient hardware resources are not really supported and extremely unlikely to be capable of running hashcat. This is not a hashcat issue and the error also seems to be unrelated to hashcat as well.
