### ISSUE TITLE
oclHashcat performance

### ISSUE THREAD

**Issue by gituser** [hashcat/hashcat#361]
Hi.

I have the same question as this guy: https://hashcat.net/forum/thread-5415.html

I'm using:
- oclHashcat (now named as hashcat v3.00-beta-135-g2e706ed) 
- with CPU and intel OpenCL: opencl_runtime_16.1_x64_ubuntu_5.2.0.10002
- algorythm is -m 20 md5($salt.$pass), all passwords have the same salt
- processor is Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz

Benchmark mode gave very nice results (406.7 MH/s):

```
$ oclhashcat -b -m 20
hashcat (v3.00-beta-135-g2e706ed) starting in benchmark-mode...

Device #1: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz, 16098/64392 MB allocatable, 8MCU

Hashtype: md5($salt.$pass)

Speed.Dev.#1.:   406.7 MH/s (95.68ms)
```

The actual bruteforce via mask gives about 290 MH/s:

```
$ oclhashcat -a 3 -c 512 -m 20 $PASSDB ?1?1?1?d?d?d?d?d?d?d?d --remove -o $PASSDB.pot --increment --increment-min 4 -1 ?l?u
Device #1: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz, 16098/64392 MB allocatable, 8MCU

Hashes: 589114 hashes; 589114 unique digests, 1 unique salts
Bitmaps: 17 bits, 131072 entries, 0x0001ffff mask, 524288 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Early-Skip
* Not-Iterated
* Prepended-Salt
* Single-Salt
* Brute-Force
* Raw-Hash
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?1?1?1?d?d?d?d?d) [8]
Hash.Target....: File (passwords.oclhashcat)
Hash.Type......: md5($salt.$pass)
Time.Started...: Fri Jun  3 21:33:44 2016 (9 secs)
Time.Estimated.: Fri Jun  3 21:36:27 2016 (2 mins, 15 secs)
Speed.Dev.#1...:   **291.6 MH/s** (13.77ms)
Recovered......: 37/589259 (0.01%) Digests, 0/3 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:223.30,13397.83,321547.81 (Min,Hour,Day)
Progress.......: 2670559232/42182400000 (6.33%)
Rejected.......: 0/2670559232 (0.00%)
Restore.Point..: 3968/100000 (3.97%)
```

But when I try to attack via dictionary with rules oclhashcat gives speed about (~50MH/s only):

```
$ oclhashcat -r ./all.rule -m 20 passwords.oclhashcat wordlist --remove -o passwords.oclhashcat.pot -w 3

Device #1: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz, 16098/64392 MB allocatable, 8MCU

Hashes: 589114 hashes; 589114 unique digests, 1 unique salts
Bitmaps: 17 bits, 131072 entries, 0x0001ffff mask, 524288 bytes, 5/13 rotates
Rules: 238369
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Early-Skip
* Not-Iterated
* Prepended-Salt
* Single-Salt
* Raw-Hash
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled


Cache-hit dictionary stats wordlist: 413332382 bytes, 42610827 words, 10157100221163 keyspace

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s

Session.Name...: hashcat
Status.........: Running
Rules.Type.....: File (./all.rule)
Input.Mode.....: File (wordlist)
Hash.Target....: File (passwords.oclhashcat)
Hash.Type......: md5($salt.$pass)
Time.Started...: Fri Jun  3 21:42:31 2016 (12 secs)
Time.Estimated.: Mon Jun  6 04:59:41 2016 (2 days, 7 hours)
Speed.Dev.#1...: **51033.8 kH/s** (96.14ms)
Recovered......: 0/589114 (0.00%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 565248000/10157100221163 (0.01%)
Rejected.......: 0/565248000 (0.00%)
Restore.Point..: 0/42610827 (0.00%)
```

Rules I'm using are from hashcat (CPU previous version).

I even tried piping hashcat --stdin mode to pipe wordlist to oclhashcat, but it gives even lower speeds:

```
$ hashcat -c 1024 --stdout wordlist -r all.rule |oclhashcat -m 20 passwords.oclhashcat --remove -o passwords.oclhashcat.pot

Device #1: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz, 16098/64392 MB allocatable, 8MCU

Hashes: 589114 hashes; 589114 unique digests, 1 unique salts
Bitmaps: 17 bits, 131072 entries, 0x0001ffff mask, 524288 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Early-Skip
* Not-Iterated
* Prepended-Salt
* Single-Salt
* Raw-Hash
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Starting attack in stdin mode...         

Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Pipe
Hash.Target....: File (passwords.oclhashcat)
Hash.Type......: md5($salt.$pass)
Time.Started...: Fri Jun  3 21:45:24 2016 (9 secs)
Speed.Dev.#1...:   **892.9 kH/s** (12.77ms)
Recovered......: 0/589114 (0.00%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 8084243
Rejected.......: 1683
```

Why there is such difference of speeds for oclHashcat in different modes?

I've also tested hashcat-2.0.0 (CPU) built with AVX2 and it gives quite constant 52Mh/s with the same rules for both wordlist and bruteforce attacks.

**Comment by jsteube** [comment]
Basically everything looks good for me. Also the benchmark speed matches exactly the real speed (you have to use one hash of course, not many). If you do not create enough amplifier you can't get out enough speed. Please read this and the following sections: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

**Comment by gituser** [comment]
@jsteube, why do you think it's normal?

291.6 MH/s vs 50 MH/s (incremental vs wordlist) ?

that means for wordlist with rules speed is 6 times slower.

i'm using 500k hashes (for incremental) with 400mb wordlist (for wordlist mode) and 200k rules, so I think there is enough 'work to do'.

**Comment by roycewilliams** [comment]
Please carefully read the link that @jsteube provided.  Depending on the type of hash, dictionary attacks will always be slower than bruteforce on GPU because dictionary attacks cannot take advantage of the parallel nature of the GPU. You can apply rules to your dictionary to achieve higher speeds, but if you are just looking to run through some dictionaries without applying rules, the speeds you are reporting are normal.

**Comment by gituser** [comment]
@roycewilliams I did read this link, but I can't figure out how it applies to my case? All parameters (hash, wordlists, rules) are stated in my first post, please read. Also I'm not using GPU at all, I'm using Intel OpenCL SDK with Intel XEON E3, also stated in first post.

I'm using 42M wordlist + >200000 rules, so what could be wrong?

I've also tried piping old cpu hashcat version but it gives even worse performance.

On CPU hashcat (old version v2.00) speed is same for both cases - incremental / wordlist, that's why I filled an issue here, might be there some performance bug for wordlist / rules attack?

**Comment by halexan** [comment]
Well, I posted that thread...I have the same question too.

Maybe as roycewilliams said

> dictionary attacks cannot take advantage of the parallel nature of the GPU

I think it is because dict attack cannot be calculated parallel in a CPU/GPU. Only after a password being calculated, the next password can be calculated. This leads to a performance drop.

And why rule based attack makes performance better? I think it's because different rules in a rule file can be calculated in parallel...maybe..

However, this condition likely does not happen on hashcat v2.00. I am confused!

Is there any way to improve performance of dict-mode? I mean calculate different passwords parallel in a CPU/GPU. @jsteube @roycewilliams

**Comment by gituser** [comment]
Is there any more clarification why speed jumps so much for wordlist attack vs incremental?

Thanks.
