### ISSUE TITLE
Teach hashcat to exit gracefully on SIGINT

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3618]
hashcat should exit gracefully on interrupt, exactly as if `q` was pressed. The second SIGINT will still kill it as before.

**Comment by mmtawous** [comment]
@jsteube 

I have looked into this for a while and can't think of a way to implement it without introducing a global variable into the equation. I know this project has been refactored in the past to remove all global variables for the sake of memory improvements so I am wondering if you could make an exception for this one case. 

The only global variable needed would be a pointer to the hashcat context; it could be stored in hashcat.c and accessed from the thread implementation which would contain the signal handlers. There seems to already be commented code there for signal handling.

**Comment by roycewilliams** [comment]
@justpretending - based on the discussion in #3618, should this issue also be closed?

**Comment by mmtawous** [comment]
I'd say it seems reasonable to close this issue. @jsteube was not fond of the idea of exiting gracefully on SIGINT regardless of the implementation complications.
