### ISSUE TITLE
oclHashcat ability to specify static salt from file for unsalted lists

### ISSUE THREAD

**Issue by gituser** [hashcat/hashcat#362]
Old CPU hashcat had an option (-e) where you could specify salt in a file:

```
hashcat --help|grep -- -e
  -e,  --salt-file=FILE              Salts-file for unsalted hashlists
```

which was very handy if you have a list of hashes with static salt.

Is it possible to implement this option as well in oclHashcat?

Thanks

**Comment by jsteube** [comment]
I didn't plan to add this feature, sorry. You can easily rebuild it yourself using hashcat-utils combinator.bin

**Comment by gituser** [comment]
no worries.

just thought it'd be useful for others, i'm just adding salt to hashfiles via sed.
