### ISSUE TITLE
Veeam VBK

### ISSUE THREAD

**Issue by kokolbin** [hashcat/hashcat#3623]
Hi there.
I want to recover password for Veeam *.vbk file, but there is no hashcat module for this purpose. I have reversed and recovered the hole algorithm of  password verification and found nearby module 27400(VMware VMX), but there are some differences.

So the algorithm of verification valid-or-not-valid password for *.vbk file is next (I will show example below):
1). From password and salt[64] using PBKDF2_HMAC_SHA1 with 10000 iterations we compute the output 48 byte array. First 32 byte is the key and next 16 byte is the IV for AES256_CBC
2). Using computed key and IV we try to decrypt 16 byte cipher text(which plain text was encrypted with padding flag) with AES256_CBC
3). Compare last 12 byte of decrypted cipher text with padding = 0c0c0c0c0c0c0c0c0c0c0c0c

I see it right there(I give the number for this module 27410):
27410 : Veeam VBK : $vbk${64 - salt length}${64 byte salt for PBKDF2_HMAC_SHA1}${iterations for PBKDF2 = 10000}${16 byte cipher text}${12 byte padding which was added while encrypting}

AES256_CBC (with BCRYPT_BLOCK_PADDING flag) is used for encrypt, and the plain text was a 4-bytes array.
Key and IV is computed by PBKDF2_HMAC_SHA1(password, salt, 10000, 48), where 48 is the length of output array. First 32 bytes is the key and next 16 bytes is the IV.
After decrypt 16 byte cipher text we will get 16 byte plain text, and only first 4 bytes is the plain text(which was encrypted) and next 12 byte array is padding(i have reversed and found it) : 0c0c0c0c0c0c0c0c0c0c0c0c

Here I can demonstrate an example(valid password is 'password1'):
$vbk$64$4e2df2b59029911ac171a2d07fdc8d5d68681ced7c2192d84ed4452d7fa7c8e44569e880bc27573663e185c80566ec49427363f17f4be0c294aade02799f07ed$10000$213e6e18c587f4cc196a24ce4509bbdb$0c0c0c0c0c0c0c0c0c0c0c0c

The whole decrypted cipher text(plain text) should be next: 4a9fb0a40c0c0c0c0c0c0c0c0c0c0c0c

All parameters for this example are:
Valid password: password1
Salt[64]: 4e2df2b59029911ac171a2d07fdc8d5d68681ced7c2192d84ed4452d7fa7c8e44569e880bc27573663e185c80566ec49427363f17f4be0c294aade02799f07ed
Computed Key[32]: 24108e118f94c67718cc28ab98c54c0e651a670d374984870cb34cdadd39f649
Computed IV[16]: db24df0fe5132d4e2bfeca5565d9910e
Cipher text[16]: 213e6e18c587f4cc196a24ce4509bbdb
Plain text[16]: 4a9fb0a40c0c0c0c0c0c0c0c0c0c0c0c

So can you add a new module please?
I can answer any questions about the algorithm :-)

**Comment by virusvfv** [comment]
Wow..  I'm realy need it! ))

**Comment by jsteube** [comment]
Hey there, I'll add it for you. But there's a few things to discuss:

1. Format, please change it to ```$vbk$*salt*iter*ct```

```
$vbk$*4e2df2b59029911ac171a2d07fdc8d5d68681ced7c2192d84ed4452d7fa7c8e44569e880bc27573663e185c80566ec49427363f17f4be0c294aade02799f07ed*10000*213e6e18c587f4cc196a24ce4509bbdb
```

2. With the example provided, I can't derive the same key. Is it sure that the password is actually 'password1'? I end up in

```
7fc970e8b1fc8e95f44566c075fbe04a82409a0808d07fcb
```

3. Can you provide an extraction tool (Ideally in python) to extract the required information from a Veeam *.vbk file into a hash line in (1)?

**Comment by kokolbin** [comment]
Thanks for reply, I will provide it and check for valid password. I need some time..

**Comment by kokolbin** [comment]
1. Ok, lets the format be like you have said
2. I think the problem is that i didn't write that the password we should give in "ASCII 0x00" format, it means that 'password1' should be input in PBKDF2 function like 700061007300730077006f00720064003100. Can you try to derive key and IV with it?
3. I didn't write extraction tool yet, I can say now that in every *.vbk file we can find hex-constant 600000001000000040000000 and after this hex-constant we can find 3 byte arrays with 0x60, 0x10 and 0x40 length. Where first 0x60 byte array - i don't know what is for, 0x10 byte array is the cipher text and 0x40 byte array is the salt for PBKDF2.

**Comment by jsteube** [comment]
OK, thanks for the update. Regarding (2), that means the password is encoded as unicode (utf16le). I've added conversion from UTF8 to UTF16le in the unit test and now I can derive the correct key. I'll finish the unit-test, module and kernel soon and commit it. Regarding (3), can you write such a tool?

**Comment by kokolbin** [comment]
(2) That's good!
(3) Yes, I'm working on it

**Comment by virusvfv** [comment]
Hello, guys.. 
Thank for your working about veeam! 
Here is my python scratch for parsing vbk:
```
import argparse
import binascii

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--file', required=False, help="VBK file")
    parser.add_argument('-s', '--seek', required=False, help="skip N bytes for large files")
    options = parser.parse_args()

    if options.file:
        with open(options.file, mode="rb") as f:
            if options.seek:
                f.seek(int(options.seek),0)
            while True:
                data = f.read(131072) #read data from file per 128 kBytes
                if not data:
                    break
                offs = data.find(b'\x60\x00\x00\x00\x10\x00\x00\x00\x40\x00\x00\x00')
                if offs != -1:
                    print("Found !")
                    part1 = data[offs+12:offs+12+96]
                    part2 = data[offs+12+96:offs+12+96+16]
                    part3 = data[offs+12+96+16:offs+12+96+16+64]
                    print(f'$vbk$64$%s$10000$%s$0c0c0c0c0c0c0c0c0c0c0c0c' % (binascii.hexlify(part3).decode('utf-8'), binascii.hexlify(part2).decode('utf-8')))
                    break
				

```
@kokolbin, please check it with your datas..

**Comment by jsteube** [comment]
@virusvfv Thanks for the tool! Some notes:

1. Could you please adopt it to the newly discussed format line?
2. After (1), please PR it
3. Could you please provide an example .vbk file, as small as possible, with the password "hashcat" so we can reproduce everything locally?

**Comment by virusvfv** [comment]
```
import argparse
import binascii

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--file', required=False, help="VBK file")
    parser.add_argument('-s', '--seek', required=False, help="skip N bytes for large files")
    options = parser.parse_args()

    if options.file:
        with open(options.file, mode="rb") as f:
            if options.seek:
                f.seek(int(options.seek),0)
            while True:
                data = f.read(131072) #read data from file per 128 kBytes
                if not data:
                    break
                offs = data.find(b'\x60\x00\x00\x00\x10\x00\x00\x00\x40\x00\x00\x00')
                if offs != -1:
                    print("Found !")
                    part1 = data[offs+12:offs+12+96]
                    part2 = data[offs+12+96:offs+12+96+16]
                    part3 = data[offs+12+96+16:offs+12+96+16+64]
                    print(f'$vbk$*%s*10000*%s' % (binascii.hexlify(part3).decode('utf-8'), binascii.hexlify(part2).decode('utf-8')))
                    break
				
```
[backup_password_hashcat.zip](https://github.com/hashcat/hashcat/files/10854769/backup_password_hashcat.zip)
`
$vbk$*93e8d35ccc866eadea0208cefbc0e7ff1b454f621e14c11ab880ceab4cad20026dc0b494cd97ec50ef7e17639154e5ccd3a4ef6169a08c70d1be0ac4926c247f*10000*ed0606567051812993c6dcac529d8e70
`
backup password:  hashcat

**Comment by jsteube** [comment]
Amazing. Many thanks for the all the contribution from @kokolbin and @virusvfv 

I've added new plugin with commit https://github.com/hashcat/hashcat/commit/a5d94c1f0dc0cbb21371e015741ddf5a2a6187cb

You should be able to crack these VBK files now. Good Luck!

**Comment by kokolbin** [comment]
> Amazing. Many thanks for the all the contribution from @kokolbin and @virusvfv 
> 
> I've added new plugin with commit https://github.com/hashcat/hashcat/commit/a5d94c1f0dc0cbb21371e015741ddf5a2a6187cb
> 
> You should be able to crack these VBK files now. Good Luck!

Thank you for your work, now I can try to recover password)

**Comment by TinoKautschkeCSNC** [comment]
Module was not shipped in the release binaries:

```
$ hashcat -m 31200 -a 0 -O veeam.hash /wordlists/uncompressed/rockyou.txt
...
hashcat (v6.2.6) starting

Either the specified hash mode does not exist in the official repository,
or the file(s) could not be found. Please check that the hash mode number is
correct and that the files are in the correct place.

/usr/local/share/hashcat/modules/module_31200.so: cannot open shared object file: No such file or directory
```

Even after compilling the module myself, the next error is:
`/usr/share/hashcat/OpenCL/m31200-pure.cl: No such file or directory`
