### ISSUE TITLE
--skip doesnt account for change in keyspace when using -S

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#3630]
**Describe the bug**
-S changes the "keyspace" of the attack, easily checked by the change in restore point, but --skip still operates on the keyspace as it  would have been  calculated without -S, causing a missmatch

**To Reproduce**
test1: take a wordlist (that's 200k lines), rule (that's 10m lines), and single hash. Run hashcat with with --skip 100000 and it will start the session at 50%. 

test2: take a wordlist (that's 200k lines), rule (that's 10m lines), and single hash. Run hashcat with with --skip 100000 -S and it will start the session at 0% because the keyspace is now much bigger. If you attempt to increase the --skip past 200k, it will not allow it because the --skip is not aware the -S made the keyspace bigger 

**Expected behavior**
--skip and -S work together either by allowing you to --skip 100000 (which is 50% of the wordlist) or by using the much bigger number that the keyspace now is once combined with the rules

**Comment by s3inlc** [comment]
I cannot reproduce this.
```
./hashcat --keyspace example.dict -r rules/d3ad0ne.rule
128417
```
```
./hashcat --keyspace example.dict -r rules/d3ad0ne.rule -S
4385954218
```
This command then works without any issues for me and picks up at the right point (`100000000/4385954218 (2.28%)`):
``` 
./hashcat -m 0 00000000000000000000000000000000 --skip 100000000 example.dict -r rules/d3ad0ne.rule -S
```

**Comment by Shooter3k** [comment]
Ah. I didn't notice before but it appears you need to use a salted hash

hashcat -m 10 01dfae6e5d4d90d9892622325959afbe:7050461 --skip 100000000 example.dict -r rules/d3ad0ne.rule
vs
hashcat -m 10 01dfae6e5d4d90d9892622325959afbe:7050461 --skip 100000000 example.dict -r rules/d3ad0ne.rule -S

what's particularly strange is that it's allowing the resume in this situation ... let me reproduce this and get back to you

**Comment by Shooter3k** [comment]
Turned out this was user error. I had an extra 0 on my --skip number. Sorry for the wasted time
