### ISSUE TITLE
FileVault 2 mode (16700) with erroneous behavior when executing as certain mask in a3 (attack does not work).

### ISSUE THREAD

**Issue by tabularasa007** [hashcat/hashcat#3631]
Hallo,

when attacking the following test hash (mode 16700, pw=hashcat), an erroneous behavior occurs when attacking with the specific mask ?l?l?d?d?d?s (and only then):
`$fvde$1$16$84286044060108438487434858307513$20000$f1620ab93192112f0a23eea89b5d4df065661f974b704191`

**The attack command which generates the erroneous behavior is:**
`hashcat -m 16700 hash.txt  -a3 ?l?l?d?d?d?s`

**The erroneous behavior:**
- The hashrate drops to almost zero.
- The field entry "Guess.Mask" contains yellow messages such as:
    - "Device #1: WARNING! Kernel exec timeout is not disabled. [67]"
    - "This may cause "CL_OUT_OF_RESOURCES" or related errors. [77]

**Software/Hardware:**
Hashcat 6.2.6 release. NVIDIA GeForce RTX 3080 Ti.

However, when substituting the last ?s with a custom char-set everything is fine. Also increasing the mask-length with another ?d before the ?s is fine.
e.g. The following mask works fine:
`hashcat -m 16700 hash.txt -a3 -1 ?s ?l?l?d?d?d?1`

**Comment by tabularasa007** [comment]
This behavior does not occur on a different gpu (NVIDIA GeForce RTX 3060).

**Comment by jsteube** [comment]
Doesn't happend to me:

```
root@ht:~/hashcat# ./hashcat -m 16700 hash.txt ?l?l?d?d?d?s -a 3
hashcat (v6.2.6-339-gce934be97) starting

CUDA API (CUDA 12.0)
====================
* Device #1: NVIDIA GeForce RTX 2080 Ti, 10840/11009 MB, 68MCU

OpenCL API (OpenCL 2.0 pocl 1.8  Linux, None+Asserts, RELOC, LLVM 11.1.0, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
=====================================================================================================================================
* Device #2: pthread-Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, skipped

OpenCL API (OpenCL 3.0 CUDA 12.0.147) - Platform #2 [NVIDIA Corporation]
========================================================================
* Device #3: NVIDIA GeForce RTX 2080 Ti, skipped

OpenCL API (OpenCL 1.2 Intel(R) FPGA SDK for OpenCL(TM), Version 20.3) - Platform #3 [Intel(R) Corporation]
===========================================================================================================
* Device #4: Intel(R) FPGA Emulation Device, skipped

OpenCL API (OpenCL 3.0 LINUX) - Platform #4 [Intel(R) Corporation]
==================================================================
* Device #5: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1474 MB

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => s

Session..........: hashcat
Status...........: Running
Hash.Mode........: 16700 (FileVault 2)
Hash.Target......: $fvde$1$16$264f8b278a50b38631dfcfef9a095d93$159624$...aeadd2
Time.Started.....: Thu Mar  2 10:01:59 2023 (1 min, 1 sec)
Time.Estimated...: Thu Mar  2 10:26:15 2023 (23 mins, 15 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?l?l?d?d?d?s [6]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:    15587 H/s (8.94ms) @ Accel:64 Loops:32 Thr:128 Vec:1
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 557056/22308000 (2.50%)
Rejected.........: 0/557056 (0.00%)
Restore.Point....: 0/858000 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:1-2 Iteration:91232-91264
Candidate.Engine.: Device Generator
Candidates.#1....: ma121/ -> mr892'
Hardware.Mon.#1..: Temp: 77c Fan:141% Util: 97% Core:1680MHz Mem:6800MHz Bus:16

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => 
```

However, from your given command line, it's obvious that you are missing the -a 3 parameter. So the only explanation is you have a file named '?l?l?d?d?d?s' or you use a uncommon shell like that interprets this mask and then matches a files of that mask. 

Anyway, I think it's not a hashcat problem. If you agree, please close the issue.

**Comment by tabularasa007** [comment]
I forgot to add the attack mode in the first post, but edited it quickly. Not quickly enough. :)

The bug seems to be limited to the workstation with a NVIDIA GeForce RTX 3080 Ti. However, at the moment I can't replicate it anymore... Will close this case then!
