### ISSUE TITLE
DEEP_COMP check whether # of unique salts == # of hashes 

### ISSUE THREAD

**Issue by thatux** [hashcat/hashcat#3641]
**Describe the bug**
When using a slow kernel and DEEP_COMP is not implemented only a single hash of hashes with the same salt is cracked.

**To Reproduce**
Use https://github.com/hashcat/hashcat/commit/37923e79e95b83b9e6a835b552d221e1cf7dcb08
```
git checkout b403f622ee937178f4ba26c7216e9b20348e9ba0
make
echo '$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$Utg0llVTQABXtcILHInd35IsFVewk1t1QOGN+I+qdk4=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$Utg0llVTQABXtcILHInd35IsFVewk1t1QOGN+I+qdk4=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$R4oYwU5aaEl2hYhDL7f3qcQPBF32lQsZdZ6B14ThZTQ=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$YMMX9n9nQlRIjdEaWZaCvug2bn34g2EmLIT38vXbOz8=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$YdYJy3kkYApCsrdTAaKLw4t5TViVmXJpJO+a4OG5LGQ=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$deUY13ovcXxjl5FeDfD42swwcwnv5GogfKu32+OpR2U=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$RZMN1S1CR3hqk5EWMOjD2+AQAU6AkgF+MJKCo+ard2M=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$fvYthzBsfgQmqII4SPDNptgSREnxgw46crWV7uO8e14=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$MY8i6GB5AGo7qa0jXbvl0/s9fwmSjncFZJeO5/nHN2Y=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$Q8gUnlxdT39I0axKXfvg0IghcViPiwE6Zrntrvr3PGI=
$metamask-short$jfGI3TXguhb8GPnKSXFrMzRk2NCEc131Gt5G3kZr5+s=$h+BoIf2CQ5BEjaIOShFE7g==$eNcE/X5oVh59hagvWKndov0WSHC6lxk4NZ+P8Nj+Pik=' > metamask.hashes
./hashcat.exe --quiet -a3 -m26610 'metamask.hashes' 'hashcat1'
```
**Expected behavior**
Either crack all hashes or stop with an error that not all hashes can be cracked. Latter is most likely easer to implement.

**Additional context**
https://github.com/hashcat/hashcat/pull/3637
https://discord.com/channels/566331281558732800/874753354511843368/1084932179861192754

This problem is described in the dev-guide but it'd be better to also check for it instead of just relying on devs to implement it correctly "Of course, if you only support single targets this is not a problem. The recommended way to deal with this is to verify if the salt_buf data you are using is unique. The goal is to force hashcat to call the _comp kernel as many times as it loads unique hashes from your hash list and iterates through all of them individually. If we choose to use this mode, it is essential for the salt_t buffer to be exactly as unique as the esalt buffer (the same number of entries). "

some pseudo code
```
if (slow_hash && !DEEP_COMP && number_unique_salts != number_of_hashes)
{ 
printf("this kernel cannot crack multiple hashes with the same salt, please choose one of the hashes"); 
exit();
} 
```

this check can probably be implemented in hashes.c

**Comment by roycewilliams** [comment]
@jsteube Can you briefly outline what factors influence when same-salt hashes are a problem? (I will use your answer to update the hashcat FAQ as well.)
