### ISSUE TITLE
[Feature Request] dynamic hash mode for hashcat

### ISSUE THREAD

**Issue by gituser** [hashcat/hashcat#365]
Hi.

Is there any possibility to add some code to autogenerate new kernel on-the-fly (maybe there will be some performance penalty), but would be really handy for users, for example in john 1.8.0:
`john --format='dynamic=md5(md5(md5($c1.$p.$p).$c2)),$c1=123,$c2=345'`

Would be nice to have some sort of ability to generate new kernel based on password pattern of most used functions, e.g. md5  / sha1 / sha256.

**Comment by gituser** [comment]
OK, so I managed to add this algorythm to CPU hashcat (v2.00), oclHashcat is bit complicated for me with all these kernels. I'll post a patch later if anyone is interested.

EDIT: I've updated first post to reflect the actual feature request for oclHashcat.

**Comment by jsteube** [comment]
Dynamic hash modes with hashcat is currently not planed. While such a thing is not impossible to do, I think kernels are easy enough to make a new custom mode if it's required.

**Comment by gituser** [comment]
Is there some sort of documentation on kernels to understand how to write your own dynamic hash (e.g. the one I mentioned in my first comment)?
