### ISSUE TITLE
clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#3664]
![1](https://user-images.githubusercontent.com/80609791/229039012-c2ab597e-95c6-484a-bb17-09036fe773f7.jpg)
![2023-03-31 141820](https://user-images.githubusercontent.com/80609791/229039048-92374de9-3839-4526-be42-0b7511d30e5d.png)

clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE
Please How to resolve this issues  Thanks

**Comment by Chick3nman** [comment]
Is this tested with the current master branch? Or with release?

**Comment by ghost** [comment]
@Chick3nman
I using  released version
https://hashcat.net/files/hashcat-6.2.6.7z

**Comment by mohemiv** [comment]
@LLH-l Have you tried hashcat 6.2.3?

Also, could you please provide the full hashcat output from start to finish?
