### ISSUE TITLE
Token length exception on Open Document hash

### ISSUE THREAD

**Issue by EggJJ** [hashcat/hashcat#3667]
This is the hash value I extracted using libreoffice2john.py:
`$odf$*0*0*1024*16*66d2f8bf7a7c728bea05e7e69ac436473f50c96c*8*d060e94fd1bd7de5*16*0f6d97f69e19d825e90139f97d4a5511*0*0a1ef460c8b39045001994786de7331b6263039b2e1f00ab485d8760f5555722c872fc8e79de6600a6c29e27fe46f0e35c47096e88634333d53fafa4e0ca9a226a1a814768e6f52c8064cae5fc42921333674f4bea72218823d92edf882c85a15fd0660ae11fdf0ef65902e4d90bfb9f5b24f24c5d9984990de5724a8f218945975bb99a20cb42c16bbaea0eba18ea36917b236cb13f90f0343ad8654fc976fd4f575238ac7d1c6dacb58af4ccd26050551febdbce0380538c36a29104be103206452950465e81a6893a0adfb9969621ec48cb2aea7e6fbbd714aca63fafcae7e3869f338a0bb6c46d779bd46240118f044eb65d99b673aba69f0c09d3d04631248d2d20d23bb50c34c5d544659ff449b92633a5fd563a7331dc48e23ad35086b1b8e3de8109c003d9dbb5cd1482c8c7f0ff01b03f8bd83bcfe2f74ff7b4186116a6ff684f0d083494794b1b66a0c26eedf9cc0f6d5c46fee11842a17c910cd02318279a938916d184363f3bfc0fa700fe22fbb11cd474b6de048130a53b0b45160016a5e215edb30b4a0a24f17f6b3ce03fbe892d20728f7b244d5fd3d72e9fd03139c1eb65c80851c5415d13e9d5f8006eb2783233541cd57c8ef8d4f1ae115d0f8ccf4159f691a5d204cc04915ec469d0b27a1aa59c4edf7d2b4fea08bec23f267aed37ad5e786f46e6465cf4592ce1239deefaeaa12905f15f73faf486dead7969a3535f6e77e29e17425b6d433957b5a718969f2588d5d61624597b7c4aa094285f782defa9e92de987edc9111601ca33390613671822a7318d59566f84e16bc77adda41f686aab4895428a33e33b19316511067e8c550bb22316359c2b2ec91879084a7904961e79b7f95f9382e6168cf6c8114ec4f4575e9fabd038ec3a491df8e2d6e5ee5f00efd692cb588bfaf445b707c8fa09325b064c09`
Then, when I use hashcat to crack it, I use the command: 
`hashcat -m 18600 - a 0 hash.txt - o out.txt dict.txt -- force`
report error： Token length exception. No hashes loaded.

**Comment by jsteube** [comment]
Fixed with commit https://github.com/hashcat/hashcat/commit/6862c1102eb1b34a646e1d60a29645d6ebf27406
Thanks for reporting!
