### ISSUE TITLE
More Built-in charsets!

### ISSUE THREAD

**Issue by rodrigozanatta** [hashcat/hashcat#3669]
Hashcat has the great ability to do [mask atack](https://hashcat.net/wiki/doku.php?id=mask_attack#built-in_charsets). But it only has 8 mask:
```
?l = abcdefghijklmnopqrstuvwxyz
?u = ABCDEFGHIJKLMNOPQRSTUVWXYZ
?d = 0123456789
?h = 0123456789abcdef
?H = 0123456789ABCDEF
?s = «space»!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
?a = ?l?u?d?s
?b = 0x00 - 0xff
```
Why not more? I know I can customize it with `--custom-charset[1-4]`, but I need some characters that my language (Brazilian Portuguese). And this is a problem to input! 

I discovery I can't direct input it in my ssh session (PuTTY, I hate you). Maybe, even the command line don't accept it. So I will need to manually get every UTF8 code and input it as hex. 

So, what code I sugest :
``` 
?p = áéíóúàãõâêôç       #Portuguese lowcase
?P = ÁÉÍÓÚÀÃÕÂÊÔÇ       #Portuguese UPPERCASE
```
I [search here](https://www.dicio.com.br/palavras-com-a-4/) to see exist words in my language with this character.
(**For Brazilian**: Eu não coloquei trema (üÜ) pois foi abolido da gramática. O site não tinha nenhuma palavra com trema. Há palavras com è, mas elas vem do francês e ninguém usaria isso como senha!).

Well, this will not hurt anyone:
``` 
?v = aeiou                      #Vowel lowcase
?V = AEIOU                      #Vowel UPPERCASE
?c = bcdfghjklmnpqrstvwxyz      #Consonant lowcase
?C = BCDFGHJKLMNPQRSTVWXYZ      #Consonant UPPERCASE
```
I can search for another languages, like spanish. I do not speak this language and have small knowledge about it. But I can search in the [dictionary here](https://dle.rae.es/) and [this manual](https://studyspanish.com/typing-spanish-accents)!

``` 
?e = áéíóúüñ           #"Espanhol" lowcase
?E = ÁÉÍÓÚÜÑ           #"Espanhol" UPPERCASE
?m = ¡¿                #Can be "more" special characters, Don't neet to be only this two
```

Maybe some crazy language, like chinese or arabic this is more difficult. But for some, just doing it will help a lot! 

If you like it, other people can help with their language and add to this list to show what character someone can use to create a password!

**Comment by ventaquil** [comment]
How about standard charsets placed here? [hashcat/charsets/standard/](https://github.com/hashcat/hashcat/tree/master/charsets/standard)

**Comment by Chick3nman** [comment]
More built-in charsets could be interesting, but I'm not sure if it'd be much better than just using a charset file and/or hex charset. Would it solve something that charset files don't?

**Comment by rodrigozanatta** [comment]
> How about standard charsets placed here? [hashcat/charsets/standard/](https://github.com/hashcat/hashcat/tree/master/charsets/standard)

To be fair... I didn't see it before. I really read a lot of documentation before doing this post. 
To be even more fair, this topic is on the SAME page I linked. I just don't understand... Look likes I am stupid :(

This was not a good sugestion...
