### ISSUE TITLE
Scrypt bug

### ISSUE THREAD

**Issue by Zyntax3rror** [hashcat/hashcat#367]
sorry if double posting in #150
again (but now only for dictionary attack)
r = 1 -> 8 = works
r >8 fails
log

---

hashcat (v3.00-beta-146-g106e781+) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 2621440

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 28 bytes, 4 words, 4 keyspace

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

SCRYPT:64:8:1:dGVhbWhhc2hjYXQ=:NsBlpyfWWxdEW1tNMPbWaiNOIrE5bet44Rms48iStQ0=:hashcat

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:8:1:dGVhbWhhc2hjYXQ=:NsBlpyfWWx...
Hash.Type......: scrypt
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (14.09ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 4/4 (100.00%)
Rejected.......: 0/4 (0.00%)

Started: Tue Jun 07 17:55:46 2016

Stopped: Tue Jun 07 17:55:56 2016

---

hashcat (v3.00-beta-146-g106e781+) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 2949120

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 28 bytes, 4 words, 4 keyspace

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyj...
Hash.Type......: scrypt
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (16.55ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 4/4 (100.00%)
Rejected.......: 0/4 (0.00%)

Started: Tue Jun 07 17:55:56 2016

Stopped: Tue Jun 07 17:56:06 2016

---

hashcat (v3.00-beta-146-g106e781+) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 3276800

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 28 bytes, 4 words, 4 keyspace

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:10:1:dGVhbWhhc2hjYXQ=:Dg4kia42f...
Hash.Type......: scrypt
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (16.87ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 4/4 (100.00%)
Rejected.......: 0/4 (0.00%)

Started: Tue Jun 07 17:56:06 2016

Stopped: Tue Jun 07 17:56:16 2016

**Comment by jsteube** [comment]
Try again with a single word in the wordlist

**Comment by Zyntax3rror** [comment]
a single word in wordlist worked. That does not make sense..

---

hashcat (v3.00-beta-151-g1c695b1) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 2949120

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 7 bytes, 1 words, 1 keyspace

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyjp61QoQhb9Y8oYXLtJ2WZoZN0wSL6ta7eA=:hashcat

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyj...
Hash.Type......: scrypt
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (11.84ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 1/1 (100.00%)
Rejected.......: 0/1 (0.00%)

Started: Sat Jun 11 12:38:44 2016

Stopped: Sat Jun 11 12:38:54 2016

**Comment by jsteube** [comment]
Can you please retry with latest version?

**Comment by Zyntax3rror** [comment]
ok..did not work for r>8 (4 words in example.dict), r<9 worked fine.

Hashcat64.exe -m 8900 SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=====:IBNEidINyjp61QoQhb9Y8oYXLtJ2WZoZN0wSL6ta7eA= example.dict

hashcat (v3.00-beta-232-g0e68b2a) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

# OpenCL Platform #1: NVIDIA Corporation
- Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 75c

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 23592960

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 28 bytes, 4 words, 4 keyspace

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

Session.Name...: hashcat
Status.........: Running
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyj...
Hash.Type......: scrypt
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (16.37ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 4/4 (100.00%)
Rejected.......: 0/4 (0.00%)
HWMon.Dev.#1...: Temp: 41c Fan: 25% Util: 52% Core:1019Mhz Mem:2700Mhz Lanes:16

Started: Mon Jun 27 00:07:28 2016

Stopped: Mon Jun 27 00:07:38 2016

**Comment by jsteube** [comment]
OK, pushed a new version with a dynamic tmp_t salt length. That one should fix it.

**Comment by Zyntax3rror** [comment]
YES!!! mission accomplished :) 
Thanks!!!

---

hashcat (v3.00-beta-242-g4ed8977) starting...

Removing duplicate hashes...

Comparing hashes with potfile entries...

Structuring salts for cracking task...

Generating bitmap tables with 16 bits...

# OpenCL Platform #1: NVIDIA Corporation
- Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 75c

Initializing device kernels and memory...

SCRYPT tmto optimizer value set to: 2, mem: 188743680

Checking for weak hashes...

Cache-hit dictionary stats example.dict: 1080247 bytes, 129989 words, 129989 keyspace

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => 

SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyjp61QoQhb9Y8oYXLtJ2WZoZN0wSL6ta7eA=:hashcat

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:64:9:1:dGVhbWhhc2hjYXQ=:IBNEidINyj...
Hash.Type......: scrypt
Time.Started...: Tue Jun 28 00:40:52 2016 (4 secs)
Speed.Dev.#1...:    29590 H/s (40.13ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 129989/129989 (100.00%)
Rejected.......: 0/129989 (0.00%)

Started: Tue Jun 28 00:40:52 2016

Stopped: Tue Jun 28 00:41:07 2016

**Comment by jsteube** [comment]
Thanks for reporting and testing :)
