### ISSUE TITLE
Issue with .editorconfig file stripping trailing whitespace from .rule files

### ISSUE THREAD

**Issue by superevr** [hashcat/hashcat#3675]
This line is causing the stripping of trailing whitespace from files edited in text editors that honor .editorconfig files, even when the behavior is not intended.

https://github.com/hashcat/hashcat/blame/6862c1102eb1b34a646e1d60a29645d6ebf27406/.editorconfig#L11

```
[*]
...
trim_trailing_whitespace = true
```

`.rule` files are meant to include trailing whitespace in certain circumstances. For example, a `$?s` rule will have `$ ` lines. There may be other files or directories to apply this to, such as charsets and pot files. I've only just learned that certain editors will perform these edits without warning when the document is saved.

One way to prevent the editorconfig override is to update it as below:

```
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

[*.{pot,rule}]
trim_trailing_whitespace = false

[Makefile]
indent_style = tab
```

Of course, another would be to be specific about which files the original rules apply to, (.c, .m, .py) instead of `*`.

**Comment by jsteube** [comment]
Very nice, done: https://github.com/hashcat/hashcat/commit/44f7fb70aff82107c9a866465c52703dc9f4a8f3
