### ISSUE TITLE
how do i uninstall hashcat i need a step to step

### ISSUE THREAD

**Issue by Kingzyz** [hashcat/hashcat#3695]
i need to get walked through by a step to step on how to uninstall hashcat i dont know anything about computers

**Comment by Chick3nman** [comment]
Hashcat isn't "installed" usually, it's just a binary in a folder and can be safely deleted, as long as no data from the folder is needed. On linux/MacOS you may have an "installation" where it resides in ~/.hashcat/. This question is better suited to the forums or discord though, so I'm close this github issue.
