### ISSUE TITLE
Hashcat cannot solve old blockchain wallets with Difficulty: 10

### ISSUE THREAD

**Issue by Drax4545** [hashcat/hashcat#3696]
Hashcat cannot solve old blockchain wallets with Difficulty: 10
When Hashcat was run there were no error but it cannot find the right password.
When I run the hashcat first I tried the sample hash. It find the right password right away. Then I tried my old blockchain wallet registered in 2012. I know the password of this wallet and I put in the wordlist file. Hashcat cannot find the password. Btcrecover hash no problem finding the right password but it is very slow.

**Comment by Chick3nman** [comment]
Do you have an example wallet with the properties described that you are able to share? I'm not sure how else we can really test this.

**Comment by Drax4545** [comment]
Sample wallet and password.
[wallet.zip](https://github.com/hashcat/hashcat/files/11300211/wallet.zip)

The wallet was created in October 26, 2012.

**Comment by Drax4545** [comment]
Based on ChatGPT

Blockchain V0 Wallet started in August 2011 - December 2013
Blockchain V1 Wallet started in December 2013 - 2015

**Comment by Drax4545** [comment]
I'm willing to sponsor. Please let me know.

**Comment by Chick3nman** [comment]
This is a problem with your blockchain2john.py extraction and NOT with hashcat. 

Your wallet is NOT the "standard" blockchain wallet.aes.json as its, clearly, not JSON inside, it's pure base64. When using `blockchain2john.py` there is an option for wallets that are 100% base64 encoded that you've not correctly used.

If you run `python blockchain2john.py walletx.aes.json` without the option, you will receive this output:
```
walletx.aes.json:$blockchain$344$514633594f384e59784f644a434d6b4a69395059666f6577717661476d39614651745173333659666c474852597a7636474e445348357244596b6f6a6f6e316d5a6c713374574f356535346756466b78587a2b624e2f79704b6e39592b704948685645446d67734763742b386a415853396f6f686a6467487243574536734c306e4a69693965756d41363745503767325353714e475145502f597836392b6d64616e49396a635044725a7337546d55516a784f4d31464d67574c582f7a7a422b6559344a646e736b4c64646c49784f5936754e353561427173434c54725461305163735934725a595961534e333659376e46524d666e4750334d6a774a6b396d3738384f44773062583576482f484d5365384e2b47554f2f4c55436839715331517334554e546466346b4c72626e4f63556d647950523454526d76414b5432594266463078337a5936326b37492b6e6a3567727a33513d3d
```
And you are correct, this will not crack in hashcat:
```
Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 12700 (Blockchain, My Wallet)
Hash.Target......: $blockchain$344$514633594f384e59784f644a434d6b4a693...513d3d
Time.Started.....: Fri May  5 19:40:44 2023, (0 secs)
Time.Estimated...: Fri May  5 19:40:44 2023, (0 secs)
```
However, if you run `python blockchain2john.py --base64 walletx.aes.json` you will receive the CORRECT output:
```
walletx.aes.json:$blockchain$256$405dd83bc358c4e74908c9098bd3d87e87b0aaf6869bd68542d42cdfa61f9461d1633bfa18d0d21f9ac3624a23a27d66665ab7b563b97b9e205459315f3f9b37fca92a7f58fa92078551039a0b0672dfbc8c05d2f68a218dd807ac2584eac2f49c98a2f5eba603aec43fb836492a8d19010ffd8c7af7e99d6a723d8dc3c3ad9b3b4e65108f138cd4532058b5ffcf307e798e09767b242dd765231398eae379e5a06ab022d3ad36b441cb18e2b65861a48ddfa63b9c544c7e718fdcc8f0264f66efcf0e0f0d1b5f9bc7fc73127bc37e1943bf2d40a1f6a4b542ce1435375fe242eb6e739c5267723d1e13466bc0293d9805f174c77cd8eb693b23e9e3e60af3dd
```
And this output will crack with hashcat just fine:
```
$blockchain$256$405dd83bc358c4e74908c9098bd3d87e87b0aaf6869bd68542d42cdfa61f9461d1633bfa18d0d21f9ac3624a23a27d66665ab7b563b97b9e205459315f3f9b37fca92a7f58fa92078551039a0b0672dfbc8c05d2f68a218dd807ac2584eac2f49c98a2f5eba603aec43fb836492a8d19010ffd8c7af7e99d6a723d8dc3c3ad9b3b4e65108f138cd4532058b5ffcf307e798e09767b242dd765231398eae379e5a06ab022d3ad36b441cb18e2b65861a48ddfa63b9c544c7e718fdcc8f0264f66efcf0e0f0d1b5f9bc7fc73127bc37e1943bf2d40a1f6a4b542ce1435375fe242eb6e739c5267723d1e13466bc0293d9805f174c77cd8eb693b23e9e3e60af3dd:garygurley

Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 12700 (Blockchain, My Wallet)
Hash.Target......: $blockchain$256$405dd83bc358c4e74908c9098bd3d87e87b...0af3dd
Time.Started.....: Fri May  5 19:45:00 2023, (0 secs)
Time.Estimated...: Fri May  5 19:45:00 2023, (0 secs)
```

This is an issue with your usage of the extract script and NOT a hashcat issue. The extract script could potentially be updated to avoid this problem or present more warnings but that's an issue for the John repo since that's where the script lives.

Closing as there is no hashcat issue present.

**Comment by Drax4545** [comment]
Hashcat still not working on blockchain from 2011 to february 2012.

**Comment by Chick3nman** [comment]
> Hashcat still not working on blockchain from 2011 to february 2012.

Do you have a test case that proves that? So far, your test case didn't show any issues with hashcat.
