### ISSUE TITLE
table lookup attack (-a 5) is not always reporting correct results

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#37]
Consider you have this 2 files:
$ cat my.table
a=a
a=A
b=b
b=B
$ cat dict.txt
abc
cde

and this command:
./hashcat-cli64.bin -a 5 --stdout --table-file my.table dict.txt

the output I currently get doesn't seem to be correct:
abc
Abc
aBc
ABc
cde
Abc  (???)
aBc  (???)
ABc  (???)

Note: (???) is not actually in the output, this is just to emphasize where the problem is

The second tripple Abc aBc ABc seem to be garbage and it seems to coming from non-cleared buffers or similar.
Please can anybody troubleshoot and fix.
Thx

**Comment by jsteube** [comment]
Good find, good solution
