### ISSUE TITLE
LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by iddq** [hashcat/hashcat#3701]
# ./hashcat -a 3 -m 0 example0.hash ?a?a
hashcat (v6.2.6-473-ga9d843870) starting

: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)

**Comment by matrix** [comment]
llvm bug, not hashcat
