### ISSUE TITLE
Hashcat Does not Work on Blockchain V1 wallets or 12700

### ISSUE THREAD

**Issue by Drax4545** [hashcat/hashcat#3717]
Hashcat Does not Work on Blockchain V1 wallets or 12700 code

I tried on 5 real blockchain v1 wallets it does not work. Btcrecover can find the password but hashcat cannot. The example hash is not a real blockchain v1 wallet. The real blockchain v1 wallets has more than 1 iteration. The example hash has 1 iteration only. The whole 12700 code does not work at all.

**Comment by Chick3nman** [comment]
Do you have an example of a wallet+password that doesn't work with hashcat but does work with BTCRecover?

**Comment by Chick3nman** [comment]
Ignore my comment above, I've diagnosed the problem in your other issue here: https://github.com/hashcat/hashcat/issues/3696#issuecomment-1536947789

I'm going to close this for now as a Duplicate and for the same reason I've closed the other issue. If my explanation does not solve your issue, please reopen 3696 and we can debug further there.
