### ISSUE TITLE
 oclHashcat-plus-0.15 is outdated

### ISSUE THREAD

**Issue by ahmedeissa1** [hashcat/hashcat#372]
hello
i have been using oclHashcat-plus-0.15 but it is outdated and shows me this: 

` ERROR: this copy of oclHashcat-plus is outdated. Get a more recent version.

E:\hashcat\oclHashcat-plus-0.15>

`

where can i get a recent version?

**Comment by philsmd** [comment]
oclHashcat-plus was replaced by (a new optimized version of) just "oclHashcat" a very long time ago (years!).

The newest release version of oclHashcat/cudaHashcat can always be downloaded from https://hashcat.net/oclhashcat/

Btw, now even "oclHashcat" (and "cudaHashcat") will no longer exist and be replaced by just "hashcat 3.0" (or newer versions, depending on when you read this ;) ). So, it would make sense to just download the newest beta version from https://hashcat.net/beta/

Please don't forget to close this issue
thx

**Comment by ahmedeissa1** [comment]
thx

i will close this issue
