### ISSUE TITLE
Potfile

### ISSUE THREAD

**Issue by AnnualMedia1328** [hashcat/hashcat#3744]
Hashcat keeps cracking and adding same hash to potfile

c3552a8023784ce220e02c24309c4ac8:password"':;!?,.

It's MD5.

**Comment by Chick3nman** [comment]
That password should not be added to the potfile in the first place, it should be wrapped in hex. What command are you running? And does it appear as hex in the potfile?

**Comment by AnnualMedia1328** [comment]
hashcat.exe -a 0 --session=2023-05-25 -m 0 -w 3 --status --status-timer=60 -p : -O --outfile-autohex-disable --hwmon-temp-abort=80 -o "C:\Users\andri\Desktop\andam.txt" --outfile-format=1,2 -r "E:\hashcat-6.2.6\hashcat-6.2.6\rules\best64.rule" "C:\Users\andri\Downloads\17194-1684953542-0248ac55-unfound.txt" "D:\HashcatGUI_v1.3.1\list.txt"

**Comment by AnnualMedia1328** [comment]
I have --outfile-autohex-disable, but it dosen't add other hashes that have special charset. In potfile it's also password"':;!?,.

**Comment by Chick3nman** [comment]
Did you crack this password recently? Or is this from an old potfile? The autohex-disable may be a part of the problem here. It should be hexed in the potfile.

**Comment by AnnualMedia1328** [comment]
Cracked it today, got multilist hashes from hashes.com, have done this type cracking over month (command is practically same, only changed wordlists and rules file).

**Comment by mohemiv** [comment]
I can confirm the issue. The flag `--outfile-autohex-disable` affects the potfile. Hashcat v6.2.6.

**Comment by mohemiv** [comment]
Please test the fix.
