### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by derhornspieler** [hashcat/hashcat#375]
make
gcc -D_POSIX -DOSX -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -c -o obj/ext_OpenCL.NATIVE.o src/ext_OpenCL.c
gcc -D_POSIX -DOSX -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -c -o obj/shared.NATIVE.o src/shared.c
gcc -D_POSIX -DOSX -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -c -o obj/rp_kernel_on_cpu.NATIVE.o src/rp_kernel_on_cpu.c
src/ext_OpenCL.c:400:5: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char
      *, ...)' [-Wimplicit-function-declaration]
    snprintf (options_update, len, "%s -cl-opt-disable", options);
    ^
src/ext_OpenCL.c:400:5: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
1 warning generated.
src/shared.c:4747:12: error: no member named 'st_atim' in 'struct stat'
  d2->stat.st_atim = d1->stat.st_atim;

``` ^
src/shared.c:4747:31: error: no member named 'st_atim' in 'struct stat'
  d2->stat.st_atim = d1->stat.st_atim;
                     ~~~~~~~~ ^
2 errors generated.
make: *** [obj/shared.NATIVE.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by derhornspieler** [comment]
For some reason I am getting compiler errors with the updated versions from github.

Cheers,

James

**Comment by jsteube** [comment]
Please try again with latest master and close the issue if fixed. Thanks for reporting!

**Comment by derhornspieler** [comment]
worked like a charm with the make command. Cheers!!
