### ISSUE TITLE
Token lenght exception and seperator unmatched

### ISSUE THREAD

**Issue by Gaming12846** [hashcat/hashcat#3752]
When I try to decrypt any hash i get the error message "Token length exception" or "Separator unmatched". For example the hash "$y$j9T$TANXgpk59y8r3jgPbDl/w/$UqiK6yahwqfyqhcegWLa1.z64TyePP5.VQpUnLqI3VD:19023:0:99999:7::" or "$y$j9T$t2uh16D5efOAkZiDSMEWy0$YefPabvH2iQFUE4ogow6yn5JQMde3PEYuuQszrNvTy.:19508:0:99999:7:::" which are SHA512 password hashes from different debian Linux users and should have hash mode 1800.

When is try this command "hashcat -m 1800 -a 0 hash.txt /usr/share/wordlists/rockyou.txt" i get the token length exception error and when I try any other SHA512 hash moded I get the seperator unmatched error. The hash is formatted correctly in the hash.txt and I also tried to write the hashes directly into the command. I also tried other hashes like MD5 or Open Document Format and got the same error.

I am using hashcat v.6.2.6 on debian linux.

**Comment by matrix** [comment]
yescrypt is not supported yet
