### ISSUE TITLE
oclHashCat rule based not append 2 digits to word in dictionary

### ISSUE THREAD

**Issue by emax73** [hashcat/hashcat#376]
oclHashCat rule based not append 2 digits to word in dictionary:

Example:
oclHashcat64.exe --status -m 2500 -a 0 ...

rules: $2
dictionary: password1
handshake: password12
working,

but
rules: $1 $2
dictionary: password
handshake: password12
not working on oclHashcat, only on CPU hashcat

**Comment by jsteube** [comment]
please try again with hashcat 3 beta: https://hashcat.net/beta

**Comment by emax73** [comment]
Same result:
at adding 2 digits: Status: Exhausted

**Comment by jsteube** [comment]
Can not reproduce with my 290x:

```
root@sf:~/hashcat# cat word
password
root@sf:~/hashcat# cat rule
$1 $2
root@sf:~/hashcat# ./hashcat -m 400 '$P$987518464/xFmp7w2mrJ9iZlX3eT1e0' -r rule word --potfile-disable --quiet
$P$987518464/xFmp7w2mrJ9iZlX3eT1e0:password12
```

Please try with my command

**Comment by emax73** [comment]
your variant are working,
can I sent by e-mail to you my not working variant?

**Comment by jsteube** [comment]
yes please

**Comment by emax73** [comment]
your e-mail please?

**Comment by jsteube** [comment]
atom@hashcat.net

**Comment by emax73** [comment]
sent to you not working variant

**Comment by jsteube** [comment]
Didn't get anything

**Comment by emax73** [comment]
sent just one,
password to arhive: password

**Comment by jsteube** [comment]
ok got it, thanks. looking into it

**Comment by jsteube** [comment]
OK, found the reason. It's not really a bug, it's a feature :) 

WPA has minimum password length of 8, but the word in dict.not.work.txt has length 7. That's why it's rejecting it. You can see it in status screen:

> Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
> Progress.......: 6/6 (100.00%)
> Rejected.......: 6/6 (100.00%) <--- here

**Comment by emax73** [comment]
How avoid this feature?
After adding rules to basis lenght of testing passwords becoming valid WPA

**Comment by emax73** [comment]
If I remember, CPU version of HashCat not have that feature

**Comment by jsteube** [comment]
you can not disable it, but you can workaround, which is the best way to do this attack anyway:

> ./hashcat --stdout -r 2digits.adding/test.rule 2digits.adding/dict.not.work.txt | ./hashcat -m 2500 2digits.adding/hash.hccap

this works on windows, too

**Comment by emax73** [comment]
Thanks you for suggested spikes, now I know reason, why I not able pen-test self Wi-Fi

**Comment by jsteube** [comment]
You're welcome
