### ISSUE TITLE
Algorithm 

### ISSUE THREAD

**Issue by Jasper5505** [hashcat/hashcat#3770]
I've been waiting for support for such an algorithm in hascat for a some time, but now I want to make a request
Hashcat already support sha1($salt.$pass), but I need md5(sha1($salt.$pass)) 
if it is possible, of course

**Comment by matrix** [comment]
done, thanks :)

**Comment by Jasper5505** [comment]
it's happened!!!
And i happied!!!
Very very thanks :))

**Comment by Jasper5505** [comment]
but not completely. The request was for **sha1($salt.$pass)**, but available is **sha1($pass.$salt)**

**Comment by matrix** [comment]
you are right :) as soon as I can I do another PR

**Comment by Jasper5505** [comment]
ok :)
