### ISSUE TITLE
Why the GPU utilization is 1% when crack Metamask Vault using RTX4090?

### ISSUE THREAD

**Issue by excellentreporter321** [hashcat/hashcat#3784]
I lost the password of my Metamask Wallet so I am going to decrypt my vault. 
So I purchased Online Server with RTX4090 and then run Hashcat using following command.

hashcat -a 0 -m 26600 hash.txt rockyou.txt

The speed is 790KH/s , but the GPU utilization is 1%. I want to use 100% of GPU utilization.

How can I solve this issue? Please help me.

**Comment by matrix** [comment]
please try on discord or hashcat forum
