### ISSUE TITLE
Add a new algorithm

### ISSUE THREAD

**Issue by SerLink04** [hashcat/hashcat#3785]
===================
NEW SHA512 COMBINATION
===================

**Is your request based on a publicly known cryptographic schema and where can we find information about?**
For instance:
- The hashing function SHA512 is a public known hash algorithm on Wikipedia. 
- You can decrypt that using this combination
EXAMPLE:
SALT: Vg9PUzEMP5
hash: e551e73d87a2e6a32f8658b48f32e5ae18c12d0976871d6ddd17379069fc0fd92eb690d61923841d2e4a2473500df2b1b70507bb5b36e72634a187ad6f390880
decrypted: gatito
===========
PYTHON SCRIPT
===========
import hashlib
from colorama import Fore, init

init()

passwords = ["gato", "gatito"]

salt = "Vg9PUzEMP5"
hash_str = "e551e73d87a2e6a32f8658b48f32e5ae18c12d0976871d6ddd17379069fc0fd92eb690d61923841d2e4a2473500df2b1b70507bb5b36e72634a187ad6f390880"

for password in passwords:
    if salt is not None:
        passwd3 = [hashlib.sha512(hashlib.sha512(password.encode()).digest() + salt.encode()).hexdigest().encode(), 
                            hashlib.sha512(hashlib.sha512(password.encode()).hexdigest().encode() + salt.encode()).hexdigest().encode(),              
                            hashlib.sha512(password.encode() + salt.encode()).hexdigest().encode()]
        passwd2 = hash_str.encode()
        print(f"{Fore.YELLOW}password ->{Fore.WHITE}", password)
        print(f"{Fore.YELLOW}password (encrypted combinations) ->{Fore.WHITE}", passwd3)
        print(f"{Fore.YELLOW}ORIGINAL HASH ->{Fore.WHITE}", passwd2)
        print("-------------------")
        result = [hashlib.sha512(hashlib.sha512(password.encode()).digest() + salt.encode()).hexdigest().encode(), hashlib.sha512(hashlib.sha512(password.encode()).hexdigest().encode() + salt.encode()).hexdigest().encode(), hashlib.sha512(password.encode() + salt.encode()).hexdigest().encode()]
        if hash_str.encode() in result:
            print(f"{Fore.GREEN}the password is {Fore.LIGHTGREEN_EX}{password}")

**Provide an example hash/database/file and a known correct password**
salt: Vg9PUzEMP5
hash: e551e73d87a2e6a32f8658b48f32e5ae18c12d0976871d6ddd17379069fc0fd92eb690d61923841d2e4a2473500df2b1b70507bb5b36e72634a187ad6f390880
password: gatito

**Explain how the cryptographic schema is implemented**
hashlib and python (view the example of above)

**Describe the known limitations of the algorithm**
Many applications limit the password and/or salt to a specific minimum and maximum length.
hash_str2 = "Vg9PUzEMP5$e551e73d87a2e6a32f8658b48f32e5ae18c12d0976871d6ddd17379069fc0fd92eb690d61923841d2e4a2473500df2b1b70507bb5b36e72634a187ad6f390880"

def get_hash():
    hash_str = hash_str2
    if '$' in hash_str:
        sp = hash_str.split('$')
        if '' in sp:
            sp.remove("")
        if len(sp) == 2:
            for a in sp:
                if '@' in a:
                    i = sp.index(a)
                    item = sp[i]
                    part1, part2 = item.split('@')
                    return part1 if len(part1) > len(part2) else part2
                    
            return sp[0] if len(sp[0]) > len(sp[1]) and (not sp[0].strip().lower().startswith('sha')) else '' if sp[0].strip().lower().startswith('sha') else sp[1]

        elif len(sp) == 3:
            for a in sp:
                if '@' in a:
                    i = sp.index(a)
                    item = sp[i]
                    part1, part2 = item.split('@')
                    return part1 if len(part1) > len(part2) else part2
            if sp[1].isdigit():
                # BCRYPT
                return hash_str
            return sp[0] if (len(sp[0]) > len(sp[1]) and len(sp[0]) > len(sp[2])) and (not sp[0].strip().lower().startswith("sha")) else sp[1] if (len(sp[1]) > len(sp[0]) and len(sp[1]) > len(sp[2])) and (not sp[1].strip().lower().startswith("sha")) else sp[2]
        return ''
    elif '@' in hash_str:
        part1, part2 = item.split('@')
        return part1 if len(part1) > len(part2) else part2
    else:
        return hash_str

def get_hash_type(hash_str):
    hash_str = hash_str
    if '$' not in hash_str and '@' not in hash_str and len(hash_str) == 32: return 'MD5'
    if '$' in hash_str:
        sp = hash_str.split('$')
        if "" in sp:
            sp.remove("")
        if len(sp) == 3 and sp[1].isdigit():
            return 'BCRYPT'
        if len(get_hash()) == 64 or len(hash_str) == 64: return 'SHA256'
        if len(get_hash()) == 128 or len(hash_str) == 128: return "SHA512"
        if len(get_hash()) == 40  or len(hash_str) == 40: return "SHA1"
    if len(hash_str) == 64: return 'SHA256'
    if len(hash_str) == 128: return "SHA512"
    return "SHA1" if len(hash_str) == 40 else 'Unknown'
print(get_hash_type(hash_str2)) #SHA 512

**Where do you typically find the algorithm**
In many minecraft servers like DynamicPvP, Ecuacraft, Hydracraft, Gamesmadeinpola, Latinplay and many more (this type of hash is very used)

**Comment by Chick3nman** [comment]
The result field appears to contain 3 distinct constructions, 

`result = [sha512(sha512(password) + salt), sha512(sha512(password).hexdigest() + salt), sha512(password + salt)]`

SHA512(SHA512($pass).$salt)
SHA512(HEX(SHA512($pass)).$salt)
SHA512($pass.$salt)

That would constitute 3 different algorithms. 

The first one and the last one are both present in hashcat, with the first one being added quite recently: https://github.com/hashcat/hashcat/pull/3763

The second one, with the intermediate hex digest, does not appear to be supported in hashcat. Is that the one you need?

**Comment by SerLink04** [comment]
Yup, I need the second one

**Comment by matrix** [comment]
Hi, I think the second is #3763 and only the first is missing

**Comment by SerLink04** [comment]
@matrix lol it works, thank so much!!!

**Comment by matrix** [comment]
done, thank to you ;)
