### ISSUE TITLE
Incorrect documentation of 3NX rule

### ISSUE THREAD

**Issue by mohemiv** [hashcat/hashcat#3788]
Here is a fragment from the source codes:
```
#define RULE_OP_MANGLE_TOGGLE_AT_SEP    '3' // switch the case of the first letter after occurrence N of char X
```

Here is a fragment from the documentation:
```
Title w/Nth separator | 3NX | Upper case the letter after the Nth instance of a char
```

We can see that in the source code the toggle term is used, but the documentation refers to switching to an upper case only.

**Comment by Chick3nman** [comment]
This appears to be a documentation issue, the original commit does appear to indicate that the intended behavior is to toggle the case of the following character, not necessarily capitalize it. The word "Title" in there is definitely a source of confusion. Thoughts on reword @roycewilliams? Might be something you can fix on the wiki/in the help?

See here for the original commit adding that rule: "[Add new rule function '3' to switch the case of the first letter after occurrence N of char X](https://github.com/hashcat/hashcat/commit/f4e52ca5330c9db3cd40f64460e3002300bf18ec)"

**Comment by 0xVavaldi** [comment]
```
Toggle after Nth separator | 3NX | Toggle case the letter after the Nth instance of a char
```

Seems like the easiest "solution"
reference documentation : https://hashcat.net/wiki/doku.php?id=rule_based_attack

**Comment by roycewilliams** [comment]
Good idea - wiki updated.

Toggle w/Nth separator | 3NX | Toggle case the letter after the Nth instance of a separator char
