### ISSUE TITLE
Support for CubeCart Hashes

### ISSUE THREAD

**Issue by putinputin** [hashcat/hashcat#3807]
Info:
https://github.com/adam12/CubeCart/blob/master/classes/password.class.php

Hashing by php:
`hash('whirlpool', $salt.$value.$salt);`

Salt limits are 8 symbols (a-f):
`substr(str_pad(dechex(mt_rand()), 8, '0', STR_PAD_LEFT ), -8);`

Example:
hashsalt:
`9ba2e4c4cd74dee122154d8b81366ebde802415f41e4aa72f7ebae1ed82a01db1f9d46f8da2546bc5a25c2bebb9a8b725ce1b24d8bb85ab4a0bef3180e0eff58:11992eda`
password:
`adidas22`
check:
`php -r "$salt='11992eda'; $pwd='adidas22'; echo hash('whirlpool',$salt.$pwd.$salt);"`

**Comment by Chick3nman** [comment]
Mode added in PR #3813, merged.
