### ISSUE TITLE
Ver: v6.2.6-663-g3173f9374 doesnt work on windows11

### ISSUE THREAD

**Issue by L3ss-dev** [hashcat/hashcat#3808]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**

**To Reproduce**
Please provide us with all files required to reproduce the bug locally on our development systems. For instance: hash files, wordlists, rule files, ...

**Expected behavior**
Builded it in linux with command: make win, and success, but when i copy the dir of hashcat to windows, and try to execute it with command: .\hashcat -II, nothing show out.

**Hardware/Compute device (please complete the following information):**
- Compute device name: RTX4090m
- OpenCL/CUDA driver name: NVIDIA DRIVER
- OpenCL/CUDA driver version: 536.40
- OpenCL/CUDA driver source: .exe installer

**Hashcat version (please complete the following information):**
 - OS: windows 11
 - Distribution: 22H2
 - Version: v6.2.6-663-g3173f9374 and v6.2.6

**Diagnostic output compute devices:**

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

and version: 12.2.0_536.25, I also try this version.
------------------------------------------------------------
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
```

```
Post clinfo output: 
    None
```

```
Post hashcat -I output
$ .\hashcat.exe -I --backend-ignore-hip
hashcat (v6.2.6-663-g3173f9374) starting in backend information mode

(base )

output is nothing.
```

```
On Linux: post lspci output
```

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).
With the same driver version in wsl2-ubunt, hashcat works, on windows there is not any error output, and i hava no idea how to fix it.

**Comment by Chick3nman** [comment]
This sounds like it's going to be the automatically installed Windows OpenCL runtime causing issues with the registration of the other runtimes. It's an issue I've seen repeatedly and the fix is to go into the install programs and remove that Windows specific runtime. If clinfo provides no output, hashcat is almost certainly not going to see anything either.

**Comment by L3ss-dev** [comment]
> This sounds like it's going to be the automatically installed Windows OpenCL runtime causing issues with the registration of the other runtimes. It's an issue I've seen repeatedly and the fix is to go into the install programs and remove that Windows specific runtime. If clinfo provides no output, hashcat is almost certainly not going to see anything either.

Yes, you are right, first time I downloaded cuda toolkit from scoop, but when I downloaded from nvidia, the problem fixed.
