### ISSUE TITLE
Permanent false negatives after "hashcat -j"

### ISSUE THREAD

**Issue by mohemiv** [hashcat/hashcat#3821]
Hello there,

I've discovered that after using hashcat with -j parameter it may permanently break hashcat.dictstat2 file and create false negatives.

Here is an example:
```
$ cat /tmp/test.txt
79126b343730445d61d0f98a606799ef

$ hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 0 ~/words/public/rockyou.txt -j '>G'
[no result]
$ hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 6 ~/words/public/rockyou.txt '202?d'
[no result]

$ rm ~/.hashcat/hashcat.dictstat2
$ hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 6 ~/words/public/rockyou.txt '202?d'
79126b343730445d61d0f98a606799ef:Maldives2023
```

Also related: https://github.com/hashcat/hashcat/pull/3800
Tested versions: v6.2.6 and v6.2.6-686-g7ee59e1a9.

**Comment by Chick3nman** [comment]
This behavior looks like a failure to initiate a dictionary cache rebuild when running the -a 6 attack. My guess is that this will be simply a missed case and the wordlist produced a cache hit when it should have missed and regenerated. This effect shouldn't be permanent, only up until the next time the dictionary cache is regenerated, but if it _does_ present as permanent, then perhaps it's a different issue.

**Comment by mohemiv** [comment]
According to my tests, the -j parameter creates a false cache in the hashcat.dictstat2 file. After that multiples attacks will be broken, including -a 0, -a 1, -a 6, and -a 7.

The dictionary cache is never regenerated after the wrong cache was written to hashcat.dictstat2.

**Comment by Chick3nman** [comment]
That's strange, that doesn't seem to be happening for me. Can you try from a clean test folder with a fresh download? Or potentially upload one of the broken dictstat files?

**Comment by mohemiv** [comment]
```
$ ./hashcat -V
v6.2.6-686-g7ee59e1a9
$ rm hashcat.dictstat2
$ md5sum ~/words/public/rockyou.txt
44e1cb6e0775a65e0ad61e5f46a242c4
$ ./hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 0 ~/words/public/rockyou.txt -j '>G' -D 1
[no result]
$ cat hashcat.dictstat2 | base64
aGNkaWN0MgIAAAAAAAAAAG+6AwAAAAAAEQgAAAAAAAAJASgBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAYwhXCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN0a
1FwAAAAAAAAAAAAAAAA8s7ZkAAAAAJSOvgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdXRm
LTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAHV0Zi04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAGtQYEfAJWiPWpIp6Rwj1x
$ ./hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 6 ~/words/public/rockyou.txt '202?d' -D 1
[no result]
$ echo 037931254d9d618abde71811a621688e >> /tmp/test.txt
$ ./hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 0 ~/words/public/rockyou.txt -D 1
[no result]
$ rm hashcat.dictstat2
$ ./hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 0 ~/words/public/rockyou.txt -D 1
037931254d9d618abde71811a621688e:Crack321
$ ./hashcat /tmp/test.txt --potfile-disable --session TEST -m 0 -O -a 6 ~/words/public/rockyou.txt '202?d' -D 1
79126b343730445d61d0f98a606799ef:Maldives2023
```
Please note that the path to hashcat.dictstat2 may differ in your configuration.

**Comment by Chick3nman** [comment]
I can recreate the issue and it does appear that the host rules generate a dictionary cache that is then not rebuilt like it should be. If you follow the initial attack (-j >G) with an attack that contains (-j : ), you will see it cache hit instead of cache rebuild, however it does actually function as expected, cracking the `Crack321` test hash. I'm not yet sure why it's causing this behavior though.

**Comment by jsteube** [comment]
Very good catch. I've put a harsh fix https://github.com/hashcat/hashcat/commit/734b4350280b572ec863cec05d576cb05b84a7f4, because false negatives are too important to avoid and hand-picking individual rules is too complex because it also depends on the input word.
