### ISSUE TITLE
DES crack error

### ISSUE THREAD

**Issue by IamHuskar** [hashcat/hashcat#3837]
**Describe the bug**
DES crack error

**To Reproduce**
message is 'aaaaaaaa' . key is 'bbbbbbbb'
```
#include<iostream>
#include<openssl/des.h>   
using namespace std;
int main(int argc, char* argv[])
{
	//unsigned char data[] = {0x56,0xa6,0xd5,0x6f,0x23,0xe6,0xd2,0x3f};  
	//'aaaaaaaa'
	unsigned char data[] =   {0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61}; 
	unsigned char out[1024] = { 0 };   
	unsigned char out2[1024] = { 0 };  
	//key 'bbbbbbbb'
	const_DES_cblock key ={0x62,0x62,0x62,0x62,0x62,0x62,0x62,0x62}; 
//	const_DES_cblock key ={1,1,1,1,1,1,1,1}; 
	DES_key_schedule key_sch;       
	cout << sizeof(const_DES_cblock) << endl;
	cout << sizeof(DES_cblock) << endl;
	cout << sizeof(DES_key_schedule) << endl;
	DES_set_key(&key, &key_sch);
	DES_ecb_encrypt((const_DES_cblock*)data, (DES_cblock*)out, &key_sch, 1);
	cout << out << endl;
        for(int i=0;i<8;i++)
        {
                printf("%02x",data[i]&0xff);
        }
cout<<":";
	for(int i=0;i<8;i++)
	{
		printf("%02x",out[i]&0xff);
	}
	cout<<endl;
	DES_ecb_encrypt((const_DES_cblock*)out, (DES_cblock*)out2, &key_sch, 0);
	cout << out2 << endl;
	return 0;
}
```
hash message is 6161616161616161:98c1d35a8a41fc25
hashcat -a 3 -m 14000 "6161616161616161:98c1d35a8a41fc25" ?l?l?l?l?l?l?l?l
can't get the right result

**Expected behavior**
show the correct result

**Hardware/Compute device (please complete the following information):**
- Compute device name: GTX1660SUPER
- OpenCL/CUDA driver name: [NVIDIA DRIVER]
- OpenCL/CUDA driver version: [510.108.03]

**Hashcat version (please complete the following information):**
 - OS: [Linux]
 - Distribution: [Ubuntu 22.04]
 - Version: [6.2.5]

hashcat -I output
hashcat -a 3 -m 14000 "6161616161616161:98c1d35a8a41fc25" ?l?l?l?l?l?l?l?l
hashcat (v6.2.5) starting

Successfully initialized NVIDIA CUDA library.

Failed to initialize NVIDIA RTC library.

* Device #1: CUDA SDK Toolkit not installed or incorrectly installed.
             CUDA SDK Toolkit required for proper device support and utilization.
             Falling back to OpenCL runtime.

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL API (OpenCL 3.0 CUDA 11.6.134) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #1: NVIDIA GeForce GTX 1660 SUPER, 5184/5922 MB (1480 MB allocatable), 22MCU

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 8

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1322 MB

Cracking performance lower than expected?                 

* Append -w 3 to the commandline.
  This can cause your screen to lag.

* Append -S to the commandline.
  This has a drastic speed impact but can be better for specific attacks.
  Typical scenarios are a small wordlist but a large ruleset.

* Update your backend API runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

Session..........: hashcat                                
Status...........: Exhausted
Hash.Mode........: 14000 (DES (PT = $salt, key = $pass))
Hash.Target......: 6161616161616161:98c1d35a8a41fc25
Time.Started.....: Wed Aug 16 11:39:47 2023 (12 secs)
Time.Estimated...: Wed Aug 16 11:39:59 2023 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?l?l?l?l?l?l?l?l [8]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........: 16918.9 MH/s (0.20ms) @ Accel:128 Loops:1024 Thr:32 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 208827064576/208827064576 (100.00%)
Rejected.........: 0/208827064576 (0.00%)
Restore.Point....: 11881376/11881376 (100.00%)
Restore.Sub.#1...: Salt:0 Amplifier:17408-17576 Iteration:0-1024
Candidate.Engine.: Device Generator
Candidates.#1....: fkxzbwvq -> xqxqxqgx
Hardware.Mon.#1..: Temp: 57c Fan: 40% Util:100% Core:1905MHz Mem:6801MHz Bus:16

Started: Wed Aug 16 11:39:46 2023
Stopped: Wed Aug 16 11:40:00 2023

**Comment by MaxRWS** [comment]
Try to use "98c1d35a8a41fc25:6161616161616161" instead of "6161616161616161:98c1d35a8a41fc25".

**Comment by IamHuskar** [comment]
> Try to use "98c1d35a8a41fc25:6161616161616161" instead of "6161616161616161:98c1d35a8a41fc25".

thank you very much . my mistake.
