### ISSUE TITLE
Major bug, caps line outputs to 256 lines on Windows in any hashcat 6.X version, not in 5.X when using --stdout with -a0 and any rule

### ISSUE THREAD

**Issue by Anynomouss** [hashcat/hashcat#3844]
I just found what I would consider a nast bug, something that destroyed quite some hours for me and since it might have affected many cases I worked on in the last year.

**BUG:** 
When using hashcat hashcat-6.1.1, or hashcat-6.2.3 on Windows, and likely but not yet tested any 6.X version, the maximum lines printed by --stdout option, **maximum line output will always be 256 lines with attack mode 0 and when using rules**. I tested this with many common rules such as dive.rule rockyou-30000.rule and my own rules. Whether I use the hashcat.exe version on Linus Subsystems for windows or in Windows CMD, the results is always the same, a maximum of 256 lines are outputted. This bug does not occur when I tested it with versions 5.0.0. 

Only yesterday I realized this problem which hugely affects me since I use rules --stdout to generate new word list with for example typos or pipe input into complex attacks all the time. Therefore I cannot verify if this issue just occurred after a recent Windows update or long time ago, I suspect the later. I will look into old files see if I can find out if this bug existed for long.
Please look into it, it can have a huge impact on any one working with Hashcat on Windows (Pro).

**To verify this bug, run on bash Windows:**
` echo 'test' | ./hashcat.exe -a0 --stdout -r rules/rockyou-30000.rule | wc`
**To verify this bug on Windows cmd run:**
`hashcat.exe -a0 --stdout file_with_single_line.txt -r rules/rockyou-30000.rule > test_output.txt`  => verify the output file has 256 lines.

**Comment by Chick3nman** [comment]
Currently unable to reproduce, can you retest with 6.2.6 release and/or the beta build from https://hashcat.net/beta/?

**Comment by Anynomouss** [comment]
Just tested it with hashcat-6.2.6+692, no problem, works as expected 👍 . I reconfirmed I have the bug with hashcat 6.1.1 and 6.2.3 on Windows 10 Pro, os build 19045.3324. Hashcat 6.2.6+692 appears to not have this issue and works as expected 🚀. This is great! It means I can get on with my work although I have to rerun and check a lot of cases from the past year with negative results that might be due to this issue.

**Comment by Chick3nman** [comment]
I'd love to see an update if you figure out the cause as it may be something we run into again in the future but since this is not impacting the current master I'm going to "close" this issue.
