### ISSUE TITLE
WPA2 handshake bruteforce error encountered

### ISSUE THREAD

**Issue by MiChaelinzo** [hashcat/hashcat#3853]
**Describe the bug**
I was trying to use `-m 22000` wpa2 for bruteforcing a handshake .cap, I converted it to .hccapx but it won't work I have `Separator unmatched errors` 
```
Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashfile 'josephwpa2.hccapx' on line 1 (HCPX ): Separator unmatched
Hashfile 'josephwpa2.hccapx' on line 2 (): Separator unmatched
Hashfile 'josephwpa2.hccapx' on line 3 (): Separator unmatched
No hashes loaded.

Started: Tue Aug 22 [17:40:33](https://www.youtube.com/watch?v=J8A8rKFZW-M&t=43200s) 2023
Stopped: Tue Aug 22 [17:40:45](https://www.youtube.com/watch?v=J8A8rKFZW-M&t=43200s) 2023!
```
 I also have 
```
 * Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
nvmlDeviceGetFanSpeed(): Not Supported errors!
 ``` 

**To Reproduce**
` hashcat -m 22000 -a 3 josephwpa2.hccapx ?a?a?a?a?a?a?a?a `

**Expected behavior**
Bruteforce the .hccapx handshake file I have!

**Hardware/Compute device (please complete the following information):**
HP Pavillion Laptop 14-ce3xxx

**Hashcat version (please complete the following information):**
 - OS: Windows 11 Enterprise 64-bit
 - Distribution: (10.0, Build 22631)
 - Version: 6.2.6

**Diagnostic output compute devices:**

```
Tue Aug 22 18:45:27 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.14                 Driver Version: 531.14       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX250          WDDM | 00000000:06:00.0 Off |                  N/A |
| N/A   46C    P0               N/A /  N/A|      0MiB /  4096MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+For AMD ROCm: Post rocm-smi and ``` rocminfo output
```

```
Post clinfo output
```

```
Post hashcat -I output
```
hashcat (v6.2.6) starting in backend information mode

CUDA Info:
==========

CUDA.Version.: 12.1

Backend Device ID #1 (Alias: #2)
  Name...........: NVIDIA GeForce MX250
  Processor(s)...: 3
  Clock..........: 1582
  Memory.Total...: 4095 MB
  Memory.Free....: 3392 MB
  Local.Memory...: 48 KB
  PCI.Addr.BDFe..: 0000:06:00.0

OpenCL Info:
============

OpenCL Platform ID #1
  Vendor..: NVIDIA Corporation
  Name....: NVIDIA CUDA
  Version.: OpenCL 3.0 CUDA 12.1.68

  Backend Device ID #2 (Alias: #1)
    Type...........: GPU
    Vendor.ID......: 32
    Vendor.........: NVIDIA Corporation
    Name...........: NVIDIA GeForce MX250
    Version........: OpenCL 3.0 CUDA
    Processor(s)...: 3
    Clock..........: 1582
    Memory.Total...: 4095 MB (limited to 1023 MB allocatable in one block)
    Memory.Free....: 3584 MB
    Local.Memory...: 48 KB
    OpenCL.Version.: OpenCL C 1.2
    Driver.Version.: 531.14
    PCI.Addr.BDF...: 06:00.0

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) OpenCL HD Graphics
  Version.: OpenCL 2.1

  Backend Device ID #3
    Type...........: GPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Iris(R) Plus Graphics
    Version........: OpenCL 2.1 NEO
    Processor(s)...: 64
    Clock..........: 1100
    Memory.Total...: 6457 MB (limited to 1614 MB allocatable in one block)
    Memory.Free....: 3168 MB
    Local.Memory...: 64 KB
    OpenCL.Version.: OpenCL C 2.0
    Driver.Version.: 26.20.100.7926
```
On Linux: post lspci output
```

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).

**Comment by Chick3nman** [comment]
HCCAPX is a deprecated format and should not work with 22000, this is working as expected. If you are following a youtube tutorial, it's likely that it's outdated or simply wrong. Please convert your hash to the correct 22000 format with the correct tool, hcxpcapngtool. Closed as there doesn't appear to be any bug here.

**Comment by MiChaelinzo** [comment]
I haven't used hashcat in ages, I never thought they updated it made a lot of formats deprecated! So what is the correct format? you didn't even provide it, is this command correct?  `./hcxpcapngtool -o output.22000 input.cap.`

**Comment by Chick3nman** [comment]
Apologies, please see here: https://hashcat.net/forum/thread-10253.html
