### ISSUE TITLE
Token Length Exception

### ISSUE THREAD

**Issue by BHack007** [hashcat/hashcat#3855]
Whenever I run this "hashcat -m 1800 -a 0 /home/spy/Desktop/hash.txt /home/spy/Desktop/rockyou.txt", this error is occur.
( hashcat (v6.2.6) starting

/sys/class/hwmon/hwmon4/temp1_input: No such file or directory

OpenCL API (OpenCL 3.0 PoCL 4.0+debian  Linux, None+Asserts, RELOC, SPIR, LLVM 15.0.7, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
==================================================================================================================================================
* Device #1: cpu-penryn-Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz, 2909/5882 MB (1024 MB allocatable), 4MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashfile '/home/spy/Desktop/hash.txt' on line 1 ($y$j9T...vA9m7zdBOuP2gdBBkJ5csBQDCnoPpSg1): Token length exception

* Token length exception: 1/1 hashes
  This error happens if the wrong hash type is specified, if the hashes are
  malformed, or if input is otherwise not as expected (for example, if the
  --username option is used but no username is present)

No hashes loaded.

Started: Fri Aug 25 23:56:54 2023
Stopped: Fri Aug 25 23:56:56 2023 )

This is my hash "$y$j9T$ifRPDSNWuB3F.ZxOkoHg4.$ea7k7sXXT60vA9m7zdBOuP2gdBBkJ5csBQDCnoPpSg1"
I want to recover user password by this hash.

**Comment by PenguinKeeper7** [comment]
This hash is yescrypt, which is not yet supported https://github.com/hashcat/hashcat/issues/2816 . Please use John The Ripper instead

**Comment by Chick3nman** [comment]
Closed as unsupported hash type.
