### ISSUE TITLE
OSX Kernel compilation - CL_INVALID_BUILD_OPTIONS

### ISSUE THREAD

**Issue by fmarquez** [hashcat/hashcat#386]
Since I cannot reopen #366, I'm creating this as a new issue:

I have the same problem, but my kernel is not even compiling... I have a Macbook Pro Retina 2015 with an AMD M370, clean 10.11.5 with latest Xcode, fully patched. 

I clone https://github.com/hashcat/oclHashcat.git and the headers. Make works fine and hashcat.app is generated, but I have problems with compiling the kernel for the GPUs:

hashcat (v3.00-beta-209-gc172da1) starting...

OpenCL Platform #1: Apple

Device #1: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz, skipped
Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
Device #3: AMD Radeon R9 M370X Compute Engine, 512/2048 MB allocatable, 10MCU
Hashes: 6494 hashes; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:

Zero-Byte
Precompute-Init
Precompute-Merkle-Demgard
Meet-In-The-Middle
Early-Skip
Not-Salted
Not-Iterated
Single-Salt
Raw-Hash
Device #2: Kernel m00000_a1.8b86d570.kernel not found in cache! Building may take a while...
=== Build failed, retry with optimization disabled ===

ERROR: clBuildProgram() : -43 : CL_INVALID_BUILD_OPTIONS

=== Build Options : -I "/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/" -I '/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/' -I /Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/ -I"/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/" -I'/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/' -I/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/ -DVENDOR_ID=4 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4 -DKERN_TYPE=0 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===

=== Build Log (end) ===

Device #2: Kernel /Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/m00000_a1.cl build failure. Proceeding without this device.
Device #3: Kernel m00000_a1.360b6dd0.kernel not found in cache! Building may take a while...
=== Build failed, retry with optimization disabled ===

ERROR: clBuildProgram() : -43 : CL_INVALID_BUILD_OPTIONS

=== Build Options : -I "/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/" -I '/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/' -I /Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/ -I"/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/" -I'/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/' -I/Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/ -DVENDOR_ID=2147483648 -DCUDA_ARCH=0 -DVECT_SIZE=1 -DDEVICE_TYPE=4 -DKERN_TYPE=0 -D_unroll -cl-std=CL1.1 ===

=== Build Log (start) ===

=== Build Log (end) ===

Device #3: Kernel /Users/fmarquez/Documents/FM/Projects/Px - Security/tools/oclHashcat/./OpenCL/m00000_a1.cl build failure. Proceeding without this device. Generated dictionary stats for example.dict: 1080240 bytes, 129988 words, 136302297088 keyspace
Session.Name...: hashcat
Status.........: Exhausted
Input.Left.....: Mask (?a?a?a?a) [4]
Input.Right....: File (example.dict)
Hash.Target....: File (example0.hash)
Hash.Type......: MD5
Time.Started...: 0 secs
Speed.Dev.#*...: 0 H/s
Recovered......: 0/6494 (0.00%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 0/136302297088 (0.00%)

How did you manage to compile the kernel? Where exactly do we need to place the OpenCL headers? I tried different combinations, but with the same result... :-(

**Comment by jsteube** [comment]
I think the problem here is the space character here: "Px - Secu". There's a -I without a quote following.  Since the entire string is already a workaround for OSX compilers, it would required to make a workaround inside a workaround. Any other solutions? Maybe using an environment variable?

**Comment by jsteube** [comment]
I've pushed a maybe-workaround. Please pull latest version from github and reinstall it and try again

**Comment by fmarquez** [comment]
Hi, your fix worked! I even pulled the modification over the same repository (with the space in the path) and it compiles the kernel for all the devices (The Iris and the Radeon).

Now I'll try different scenarios with it :-)

Thanks a lot!
