### ISSUE TITLE
Support for HIPRTC warning false positive

### ISSUE THREAD

**Issue by PenguinKeeper7** [hashcat/hashcat#3870]
**Describe the bug**
The non-blocking warning below triggers on multiple PCs, one of which has never seen AMD software. The error occurred significantly earlier (over 5 months earlier) for people compiling with WSL for whatever reason, however more and more people are now seeing it while being compiled with Cygwin etc although it still seems to be fairly sporadic, it's currently unknown to me what is causing this although it seems to not be tied to any CUDA or driver version.
```
Support for HIPRTC was dropped by AMD Adrenalin Edition 22.7.1 and later.
This is not a hashcat problem.

Please install the AMD HIP SDK
```

**To Reproduce**
Compile using WSL although it may work with Cygwin and run any Hashcat command, example `hashcat -I`

**Comment by Chick3nman** [comment]
I understand the issue here and I can reproduce now. I just don't have a fix yet that doesn't have limitations.

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/0d0a07012ce21afccd37c7a61a8afc4b70e4a69a 
Thanks for reporting!
