### ISSUE TITLE
invalid base58 check

### ISSUE THREAD

**Issue by benjiqq** [hashcat/hashcat#3878]
**Describe the bug**

I believe the base58 check here is invalid, reporting false solutions, should be sth like this

https://github.com/hashcat/hashcat/pull/1805/files

```
DECLSPEC int is_valid_base58_8 (const u8 v)
{
  if (v > (u8) 'z') return 0;
  if (v < (u8) '1') return 0;
  if ((v > (u8) '9') && (v < (u8) 'A')) return 0;
  if ((v > (u8) 'Z') && (v < (u8) 'a')) return 0;

  return 1;
}

```

should be IMO

```
DECLSPEC int is_valid_base58_8 (const uint8_t v) 
{
  const char *base58_chars = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

  for (int i = 0; i < 58; i++) 
  {
    if (v == base58_chars[i]) 
    {
      return 1;
    }
  }

  return 0;
}
```

**Comment by PenguinKeeper7** [comment]
For clarity: it checks for base58 characters with ASCII ranges between 49-57 (1-9), 65-90 (A-Z), 97-122 (a-z) but does not exclude capital `O`, capital `I` or lowercase `l` as base58 does. Fixed in PR https://github.com/hashcat/hashcat/pull/3879

**Comment by PenguinKeeper7** [comment]
Issue can be closed - Fixed in https://github.com/hashcat/hashcat/pull/3879
