### ISSUE TITLE
Is there some performance boost from multiple graphics cards on different PCI-E buses?

### ISSUE THREAD

**Issue by GermanAizek** [hashcat/hashcat#3905]
**Describe question**
At the moment, in hashcat increasing count GPUs to 2 will allow you to increase bruteforce speed, for example (h/s * 2.05) or (h/s * 2.1) and etc. or it will be like this ideal (h/s * 2).

I am also interested in whether PCI-E bus link widths from 4x to 16x and version from 3.0 to 5.0 affect hashspeed.

**Comment by PenguinKeeper7** [comment]
This is probably a question best for the forum, instead of here. Github is for bug logging and feature requests, not general support
https://hashcat.net/forum/

**Comment by Chick3nman** [comment]
Please take this to the forums.
