### ISSUE TITLE
Hashcat failing with token length exception for sha512 (-m 1800)

### ISSUE THREAD

**Issue by CustosClarus** [hashcat/hashcat#3912]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**
I'm using hashcat v6.2.6 and trying to decode /decrypt sha512 using the command below:-

hashcat -m 1800 hash.txt /usr/share/wordlists/rockyou.txt

I'm getting error of 
`"Hashfile 'hash.txt' on line 1 (root:$...pfZeMdw:0:0:root:/root:/bin/bash): Token length exception", `I tested the file for any hidden files or illegal bad characters there are none (as seen using vi )

Also, when I run this with example hash from command hashcat -m 1800 --example-hashes 
(  Example.Hash........: $6$72820166$U4DVzpcYxgw7MVVDGGvB2/H5lRistD5.Ah4upwENR5UtffLR4X4SxSzfREv8z6wVl0jRFX40/KnYVvK4829kD1) 
it works just fine.

**To Reproduce**
The hash.txt contains

`root:$6$Tb/euwmK$OXA.dwMeOAcopwBl68boTG5zi65wIHsc84OWAIye5VITLLtVlaXvRDJXET..it8r.jbrlpfZeMdw:0:0:root:/root:/bin/bash (test demo machine)
`
**Expected behavior**
![image](https://github.com/hashcat/hashcat/assets/7777434/2b4e4f56-f3fd-480e-b30e-799481aaa4ca)

**Hardware/Compute device (please complete the following information):**
00:02.0 VGA compatible controller: Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 05)

**Hashcat version (please complete the following information):**
 - OS: `6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`
 - Distribution: kali linux
 - Version: 6.5

**Diagnostic output compute devices:**
![image](https://github.com/hashcat/hashcat/assets/7777434/8da8b57c-60b6-4e74-86f4-9709f644389f)

**Additional context**
Add any other context about the problem here. For instance, it was working with hashcat version X.X.X (also please post output from older versions).

**Comment by Chick3nman** [comment]
The hash in your file, as hashcat has indicated, does not appear to be the correct length. Something is wrong with that hash and thus hashcat can not parse it correctly. Please verify your acquisition of the hash and if you have further issues, please take them to either the forums of the discord server, this is not really a good place to ask about issues with acquisition and we'd be better able to discuss and help with issues like this in one of those two places. If a bug is found or other issue with hashcat's loading in this case, we can reopen this or open a new issue for it once identified.
