### ISSUE TITLE
Parse pcap files

### ISSUE THREAD

**Issue by KillReal01** [hashcat/hashcat#3913]
I research algorithm in file `module_22000.c`, I have pcap files with information and need to crack password. In this code uses not original pcap file, but modified with symbols like * or :, what is it? Can you explain it? And maybe you know, where is this modification for pcap file to correctly handling with function `module_hash_decode`?
Because original pcap file doesnt has exactly 9 symbols * very strange...

**Comment by Chick3nman** [comment]
Please use the hcxtools for the pcap extraction. Hashcat does not handle pcap files directly. Please direct further questions at the forums.
