### ISSUE TITLE
Scrypt

### ISSUE THREAD

**Issue by Zyntax3rror** [hashcat/hashcat#393]
this one worked

---

SCRYPT:8192:16:1:Z200dHIxeGF0b20=:SCAtmj6yaENvIDnArrHgioQzVxhf6tL3sNprfVnUzNM=:hashcat

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: File (example.dict)
Hash.Target....: SCRYPT:8192:16:1:Z200dHIxeGF0b20=:SCAtmj6...
Hash.Type......: scrypt
Time.Started...: Tue Jun 28 19:26:12 2016 (1 hour, 26 mins)
Speed.Dev.#1...:        2 H/s (647766.66ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 10000/10000 (100.00%)
Rejected.......: 0/10000 (0.00%)

Started: Tue Jun 28 19:26:12 2016
Stopped: Tue Jun 28 21:05:03 2016

---

**but below one stopped with this error (changed to 4 words in example.dict to speed up)
not sure if its a bug or just out of memory (earlier 8192:16:1 should use the same amount of memory and that one passed without this error)**

Hashcat64.exe -m 8900 SCRYPT:512:256:1:Z200dHIxeGF0b20=====:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk= example.dict
hashcat (v3.00-beta-244-g6be99f5) starting...
# OpenCL Platform #1: NVIDIA Corporation
- Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 75c

WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
SCRYPT tmto optimizer value set to: 5, mem: 1342177280
- Device #1: Kernel amp_a0.1965267c.kernel not found in cache! Building may take a while...

Checking for weak hashes...

**ERROR: clEnqueueNDRangeKernel() : -6 : CL_OUT_OF_HOST_MEMORY**

**Comment by jsteube** [comment]
I did some changes to scrypt memory handling again, please retry

**Comment by Zyntax3rror** [comment]
I used to download from your latest version's from here
https://hashcat.net/beta/

Have you moved your release candidates to another folder?

**Comment by Zyntax3rror** [comment]
same error

---

Hashcat64.exe -m 8900 SCRYPT:512:256:1:Z200dHIxeGF0b20=====:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk= example.dict
hashcat (v3.00-25-g69e3e39) starting...

# OpenCL Platform #1: NVIDIA Corporation
- Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt
  Watchdog: Temperature abort trigger set to 90c
  Watchdog: Temperature retain trigger set to 75c

WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
WARNING: Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
SCRYPT tmto optimizer value set to: 5, mem: 1342177280
- Device #1: Kernel amp_a0.09b29f52.kernel not found in cache! Building may take a while...

Checking for weak hashes...

ERROR: clEnqueueNDRangeKernel() : -6 : CL_OUT_OF_HOST_MEMORY

**Comment by jsteube** [comment]
Lots of stuff changed since this last test. Can you please retry with latest version from github?

**Comment by Zyntax3rror** [comment]
hashcat-3.10+611\hashcat-3.10>Hashcat64.exe -m 8900 SCRYPT:512:256:1:Z200dHIxeGF0b20=====:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk= example.dict
hashcat (v3.10-611-gf234f72) starting...

nvmlDeviceSetPowerManagementLimit(): Insufficient Permissions

# OpenCL Platform #1: NVIDIA Corporation
- Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
- Zero-Byte
- Single-Hash
- Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
clEnqueueNDRangeKernel(): CL_OUT_OF_HOST_MEMORY

Started: Mon Oct 31 21:10:38 2016
Stopped: Mon Oct 31 21:12:03 2016

**Comment by 01BTC10** [comment]
Same problem. I was thinking about implementing "Multibit Classic" aes256(scrypt(password, salt))  and was looking how hashcat implemented scrypt. The default scrypt parameter in that case are higher than the default benchmark.

> SCRYPT:16384:8:1:MDIwMzMwNTQwNDQyNQ==:5FW+zWivLxgCWj7qLiQbeC8zaNQ+qdO0NUinvqyFcfo=


```
$./hashcat  -m 8900 -w3 -a 0 -r rules/rockyou-30000.rule scrypt.txt rockyou.txt
hashcat (v3.30) starting...

* Device #1: Not a native Intel OpenCL runtime, expect massive speed loss
             You can use --force to override this but do not post error reports if you do so
* Device #2: Old CUDA compute capability 3.5 detected, OpenCL performance is reduced.
             For ideal hashcat performance on NVIDIA GPU you need CUDA compute capability 5.0 or higher (Maxwell)
nvmlDeviceGetCurrPcieLinkWidth(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetUtilizationRates(): Not Supported

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, skipped

OpenCL Platform #2: NVIDIA Corporation
======================================
* Device #2: GeForce GTX 780 Ti, 755/3020 MB allocatable, 15MCU
* Device #3: GeForce GTX 950, 499/1996 MB allocatable, 6MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 30000

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled

Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 5, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
Checking for weak hashes...clEnqueueNDRangeKernel(): CL_MEM_OBJECT_ALLOCATION_FAILURE

Started: Fri Feb 17 22:41:54 2017
Stopped: Fri Feb 17 22:41:59 2017

```

**Comment by jsteube** [comment]
Please retry! The commit https://github.com/hashcat/hashcat/commit/da93d216dad39436ceeb01a4e7054abafb1c0d30 could have an impact here

**Comment by Zyntax3rror** [comment]
did say v3.30-382-g50b46d5 when i downloaded beta for 3.40

I got CL_OUT_OF_HOST_MEMORY

hashcat-3.40>Hashcat64.exe -m 8900 SCRYPT:512:256:1:Z200dHIxeGF0b20=====:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk= example.dict
hashcat (v3.30-382-g50b46d5) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 750 Ti, 512/2048 MB allocatable, 5MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
clEnqueueNDRangeKernel(): CL_OUT_OF_HOST_MEMORY

Started: Wed Mar 01 16:12:40 2017
Stopped: Wed Mar 01 16:14:17 2017

**Comment by Zyntax3rror** [comment]
Tested and worked on GTX1080 (2048 mb used compared to 512mb on GTX 750Ti)

Hashcat64.exe -m 8900 SCRYPT:512:256:1:Z200dHIxeGF0b20=====:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk= example.dict

hashcat (v3.30-382-g50b46d5) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080, 2048/8192 MB allocatable, 20MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Not enough single-block device memory allocatable to use --scrypt-tmto 2, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 3, increasing...
Not enough single-block device memory allocatable to use --scrypt-tmto 4, increasing...
Generated dictionary stats for example.dict: 29 bytes, 4 words, 4 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted

SCRYPT:512:256:1:Z200dHIxeGF0b20=:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk=:hashcat

Session..........: hashcat
Status...........: Cracked
Hash.Type........: scrypt
Hash.Target......: SCRYPT:512:256:1:Z200dHIxeGF0b20=:RLHfYNlTpELj0LAATTIMae5xEAOO2yMUTVFZivQhlzk=
Time.Started.....: Thu Mar 02 21:26:40 2017 (14 secs)
Time.Estimated...: Thu Mar 02 21:26:54 2017 (0 secs)
Input.Base.......: File (example.dict)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (13461.61ms)
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 4/4 (100.00%)
Rejected.........: 0/4 (0.00%)
Restore.Point....: 0/4 (0.00%)
Candidates.#1....: 989386 -> hashcat
HWMon.Dev.#1.....: Temp: 36c Fan: 92% Util:100% Core:  90MHz Mem:4513MHz Lanes:16

Started: Thu Mar 02 21:25:02 2017
Stopped: Thu Mar 02 21:26:55 2017

**Comment by jsteube** [comment]
I've investigated the problem with the CL_OUT_OF_HOST_MEMORY. It turns out this is a false error message created by the OpenCL runtime when calling clBuildProgram(). The error itself occurs inside the vendors OpenCL runtime while compiling the OpenCL kernel. You have to know that with scrypt the OpenCL kernel is rebuild with every start because it requires the scrypt configuration parts to be hardcoded to run efficient. So, depending on the configuration settings, the code changes each time. The higher you set them, the more memory it takes the JIT compiler to optimize the kernel and that's the error where it's running into. The only thing I don't understand is why it runs into that error with the 750Ti while it does not run into it with the 1080. That could be becuase of the different instruction set of the chips or different optimization settings for them in the compiler. But in both cases we can not know, because that's some hidden logic inside the vendors OpenCL runtime. That also means we can not do anything to not run into this error and that's why I think this is not a hashcat issue anymore.
