### ISSUE TITLE
Keberoast TGS etype18 shows a separator unmatched however TGS etype23 in the same format does work

### ISSUE THREAD

**Issue by AkechiShiro** [hashcat/hashcat#3949]
**Describe the bug**
Keberoast TGS etype18 shows a separator unmatched however TGS etype23 in the same format does work

**To Reproduce**
I will produce full reproducer in a later comment.

**Expected behavior**

**Hashcat version (please complete the following information):**
 - OS: Linux
 - Distribution: Ubuntu 22.04 LTS
 - Version: 6.2.6

**Additional context**
The error was previously mentioned here : https://github.com/hashcat/hashcat/issues/1384#issuecomment-1698011954

**Comment by AkechiShiro** [comment]
I will close this issue as it is probably an issue with the format I had with hashes.

**Comment by derekkddj** [comment]
well, i have the same problem.

**Comment by AkechiShiro** [comment]
@derekkddj  Let me know which tool you used so they can fix the format upstream, I'm not sure if there is really a bug in hashcat, you should try with the testing hashes, if you can reproduce the issue, then we should reopen it here else I don't think we should bother hashcat devs if we didn't check for sure that the issue isn't upstream
