### ISSUE TITLE
Number of words in wordlist 'words.txt' is not in sync with number of unique salts

### ISSUE THREAD

**Issue by scotch123** [hashcat/hashcat#3954]
Hello, i'm getting this error on -a 9 .. 

Host memory required for this attack: 2669 MB

Dictionary cache built:
* Filename..: words.txt
* Passwords.: 100000
* Bytes.....: 828498
* Keyspace..: 100000
* Runtime...: 0 secs

Number of words in wordlist 'words.txt' is not in sync with number of unique salts

Number of words in wordlist words.txt is not in sync with number of salts (words: 100000, salts: 1)

Also, i've got password hash for .vbk file veeam using your veeamvbk2hashcat.py toool .. And i've got this. $vbk$*fb00f2478d0ad92241fd17576be4dc048f3731763cf8c6f53e6ff6e33bc7884e60ee539be3aa3e8f97aa1b0bc52ad3c988a2ccdd70c4c72b5c1e528608bcb240*10000*c8f1488e5421f8ff3470ca9cedf43648  ... but the hashcat stops .. any advice or could you check the hash maybe there is a problem with its format?
Note : I've recompiled the hashcat cuz i've seen a fixed commit regarding -a 9  .. but still error.

Thank you

**Comment by PenguinKeeper7** [comment]
-a 9 isn't the attack mode you want, it's -a 0 for wordlists. If you need any extra help, please use the forum ([forum.hashcat.net](https://hashcat.net/forum/) instead.

**Comment by scotch123** [comment]
The problem is that i've used 0 but it kind of stops ...and I don't know why. here is my output. :

 ./hashcat -a 0 -m 31200 hash.txt words.txt
hashcat (v6.2.6) starting

CUDA API (CUDA 12.2)
====================
* Device #1: NVIDIA GeForce RTX 3090 Ti, 23980/24247 MB, 84MCU
* Device #2: NVIDIA GeForce RTX 2080 Ti, 10853/11011 MB, 68MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 2949 MB

Dictionary cache hit:
* Filename..: words.txt
* Passwords.: 100000
* Bytes.....: 828498
* Keyspace..: 100000

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Cracking performance lower than expected?

* Append -w 3 to the commandline.
  This can cause your screen to lag.

* Append -S to the commandline.
  This has a drastic speed impact but can be better for specific attacks.
  Typical scenarios are a small wordlist but a large ruleset.

* Update your backend API runtime / driver the right way:
  https://hashcat.net/faq/wrongdriver

* Create more work items to make use of your parallelization power:
  https://hashcat.net/faq/morework

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 31200 (Veeam VBK)
Hash.Target......: $vbk$*fb00f2478d0ad92241fd17576be4dc048f3731763cf8c...f43648
Time.Started.....: Fri Feb 23 19:50:28 2024 (10 secs)
Time.Estimated...: Fri Feb 23 19:50:38 2024 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (words.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     5891 H/s (0.45ms) @ Accel:64 Loops:128 Thr:32 Vec:1
Speed.#2.........:     5499 H/s (0.36ms) @ Accel:128 Loops:64 Thr:32 Vec:1
Speed.#*.........:    11390 H/s
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 100000/100000 (100.00%)
Rejected.........: 0/100000 (0.00%)
Restore.Point....: 98944/100000 (98.94%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:9984-9999
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:9984-9999
Candidate.Engine.: Device Generator
Candidates.#1....: RODRIGO -> 04091980
Candidates.#2....: 05060506 -> gayguy
Hardware.Mon.#1..: Temp: 48c Fan: 46% Util:  0% Core:1890MHz Mem:10251MHz Bus:16
Hardware.Mon.#2..: Temp: 36c Fan: 34% Util: 17% Core:1350MHz Mem:6800MHz Bus:16

Started: Fri Feb 23 19:49:58 2024
Stopped: Fri Feb 23 19:50:39 2024

**Comment by PenguinKeeper7** [comment]
"Exhausted" means that hashcat has tested every password that it was supposed to test. It does not mean that something went wrong, nor that something isn't working correctly. Try a different wordlist instead, as the one you chose doesn't contain the correct password. As I say, you should take this to the forum if you have any other problems because Hashcat is working completely as intended and isn't malfunctioning

**Comment by scotch123** [comment]
Thank you for your fast reply . Well i've tried 2 different .vbk hashes . One on which I have the plain text password for it and the other one i don't.  With -a 0 it doesn't find the password I already have but with a -9 works fine.  that's the reason i've been trying -a 9 ..

**Comment by Chick3nman** [comment]
Unless there's some kind of bug here, this appears to be an issue better dealt with on the forums or elsewhere. Closing for now, feel free to reopen if there's an issue with hashcat.
