### ISSUE TITLE
void _des_crypt_decrypt?

### ISSUE THREAD

**Issue by jeroen-80** [hashcat/hashcat#396]
I'm working on support for an extra algorithm. The algorithm consists of a few well knows hashing and encryption algorithms. I've successfully implemented most steps, recycling code of a bunch already available OpenCL kernels. However, I'm missing one step: DES decryption.

Perhaps the code is available and was removed by the developers of the DES-based algorithms (1500, 3000 etc.) since it's not used in the specific hash formats. If this is the case, can you please let me know? 

Thanks a lot!

**Comment by epixoip** [comment]
This type of question also belongs on the forums, not on Github.

Note that Github Issues is only for filing bug reports or requesting new features! If you need help or want to discuss a topic, please use the forums. Thanks!

**Comment by jsteube** [comment]
No reponse from OP, so closed
