### ISSUE TITLE
Please help me, how can i solve this error?

### ISSUE THREAD

**Issue by Benol07** [hashcat/hashcat#3964]
![image](https://github.com/hashcat/hashcat/assets/162541096/d481588a-2551-4eda-bd97-241389bda5e4)

**Comment by Chick3nman** [comment]
It appears that your file is not being found at the location specified and is instead being read as a literal string. This is not a bug and is instead just a usage problem. Please take issues like this to the forums or perhaps the discord, github doesn't feel like the right place for this.
