### ISSUE TITLE
28502 throwing "cuCtxCreate(): misaligned address" errors

### ISSUE THREAD

**Issue by Shooter3k** [hashcat/hashcat#3965]
when you run the following command (tested multiple hashcat versions) 
hashcat --session brain -m28502 1L9nr4GX4Zmd7gDL1UT75QPUqxSgNTvdHb -a3 5KcL859EUnBDtVG76134U6DZWnVmpE996emJnWmTLRW2hashcat

it throws the following errors (I'm not sure if this is "intended" or not): 
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
cuCtxCreate(): misaligned address
Host memory required for this attack: 1475 MB
cuMemcpyHtoDAsync(): misaligned address
cuStreamSynchronize(): misaligned address
Aborting session due to kernel self-test failure.

This was reproduced on multiple machines but my machine is OpenCL 3.0 CUDA 12.1.109

**Comment by PenguinKeeper7** [comment]
WFM. 
```
CUDA API (CUDA 12.3)
====================
* Device #1: NVIDIA GeForce RTX 3070, 7114/8191 MB, 46MCU

OpenCL API (OpenCL 3.0 CUDA 12.3.107) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: NVIDIA GeForce RTX 3070, skipped
```
```
>nvidia-smi
Thu Mar  7 20:24:36 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.65                 Driver Version: 546.65       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070      WDDM  | 00000000:08:00.0  On |                  N/A |
|  0%   52C    P8              17W / 134W |    531MiB /  8192MiB |     10%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by flaggx1** [comment]
I had the same problem with CUDA 12.1, it had been working with 11.7 I think?

Just upgraded to 12.4 and the module is working again.
