### ISSUE TITLE
Mask option: date

### ISSUE THREAD

**Issue by jeroen-80** [hashcat/hashcat#397]
What would be the best approach to limit the key space of a password that contains a date, e.g. <a lot of random characters>DDMM? Rights now I'm scripting a batch of hashcat command with masks like

0?d0?d
1?d0?d
2?d0?d
300?d
310?d
etc.

but that's not the easiest nor the fastest solution. Any ideas for a smarter / faster approach? Thanks!

**Comment by epixoip** [comment]
This type of question belongs on the forums, not on Github.

**Comment by jsteube** [comment]
No reponse from OP, so closed
