### ISSUE TITLE
jwt16500Separator unmatched

### ISSUE THREAD

**Issue by sexchen** [hashcat/hashcat#3972]
**Describe the bug**
运行时提示Separator unmatched

**To Reproduce**
 .\hashcat.exe hashcat -a 3 -m 16500 'eyJhbGciOiJIUzI1NiJ9.eyIzNDM2MzQyMCI6NTc2ODc1NDd9.f1nXZ3V_Hrr6ee-AFCTLaHRnrkiKmio2t3JqwL32guY' ?u?l?l?l?l?l?l?l -i --increment-min=6

**Hardware/Compute device (please complete the following information):**
GTX 1660 Ti
Windows 10 1909

**Hashcat version (please complete the following information):**
hashcat-6.2.6

![1711111827961](https://github.com/hashcat/hashcat/assets/17498101/f151eefe-cdd9-4345-ba18-49c1fd210c6a)

I tried using jwtExample, but it prompted "Separate unmatched"

**Comment by Chick3nman** [comment]
Remove the extra "hashcat" at the beginning of your command. This is not a hashcat issue, this is simply a command syntax problem.

**Comment by sexchen** [comment]
> 删除命令开头多余的“hashcat”。这不是 hashcat 问题，这只是命令语法问题。
是的，删除多余的hashcat后成功运行。感谢
.\hashcat.exe -a 3 -m 16500 eyJhbGciOiJIUzI1NiJ9.eyIzNDM2MzQyMCI6NTc2ODc1NDd9.f1nXZ3V_Hrr6ee-AFCTLaHRnrkiKmio2t3JqwL32guY ?u?l?l?l?l?l?l?l -i --increment-min=6
![image](https://github.com/hashcat/hashcat/assets/17498101/dfdc60c4-225e-423a-b26c-ae6c4ef77405)
