### ISSUE TITLE
Does hashcat support running on multiple nodes?

### ISSUE THREAD

**Issue by yl960122** [hashcat/hashcat#3975]
I want to test hashcat using multiple nodes, using MPI for inter-node communication, but I found that only one node can run.

**Comment by PenguinKeeper7** [comment]
You can use Hashcat across multiple nodes, just not natively through MPI
1) Using the --keyspace, --limit and --skip flags to manually define which parts of an attack should be covered by each agent [More info](https://hashcat.net/wiki/doku.php?id=distributing-work)
2) Using a dedicated distribution wrapper like Hashtopolis 
3) Using a Hashcat Brain [More Info](https://github.com/hashcat/hashcat/blob/master/docs/hashcat-brain.md)

This is probably best for the [Hashcat forum](https://hashcat.net/forum/), if you want to talk more about this, please use that

**Comment by yl960122** [comment]
Thank you for your response. I tried using hashcat brain to crack 8-character passwords, but it seems that the cracking time for each client did not decrease during the process.

**Comment by yl960122** [comment]
Client
![image](https://github.com/hashcat/hashcat/assets/65180595/1e01d08e-d062-41c9-b6b4-a373516df32b)

**Comment by yl960122** [comment]
Server
![image](https://github.com/hashcat/hashcat/assets/65180595/cf8084e9-3b09-4656-aee8-b2f0a3fe461d)

**Comment by yl960122** [comment]
My test command is as follows:
server：hashcat --brain-server --brain-host=c10r4n09 --brain-port=23000 --brain-password 12345
client1：hashcat -a 3 -m 0 0bb0bee22c9991248b04fd9b9947997e --increment --increment-min 8 --increment-max 8 ?a?a?a?a?a?a?a?a --brain-client --brain-host=c10r4n09 --brain-port=23000 --brain-password 12345

The cracking commands for client 2 and client 3 are the same as client 1.Actually, I hope that the task of brute-force cracking can be evenly distributed among the three clients.

**Comment by yl960122** [comment]
Thank you for your response. Perhaps I should go to the Hashcat forum to find more useful information.

**Comment by PenguinKeeper7** [comment]
That's not what Hashcat Brain is for, it's for making sure that there isn't any overlap between the work that Client A does from what Client B does when using **different** attacks. It should also only be used on quite slow algorithms. You want option 1 or 2.
Because this isn't a bug or new feature and you're just asking for support, it's probably best handled on the Hashcat forum instead of on Github

**Comment by Chick3nman** [comment]
Please take this to the forums or discord.
