### ISSUE TITLE
Batch cracking problem

### ISSUE THREAD

**Issue by oebta** [hashcat/hashcat#3983]
202cb962ac59075b964b07152d234b70
e10adc3949ba59abbe56e057f20f883e
202cb962ac59075b964b07152d234b70
e10adc3949ba59abbe56e057f20f883e
202cb962ac59075b964b07152d234b70
e10adc3949ba59abbe56e057f20f883e
202cb962ac59075b964b07152d234b70
202cb962ac59075b964b07152d234b70
202cb962ac59075b964b07152d234b70

How to crack md5 without changing it instead of just the following two？

e10adc3949ba59abbe56e057f20f883e
202cb962ac59075b964b07152d234b70

**Comment by PenguinKeeper7** [comment]
Hashcat automatically dedupes the hashlist and many parts of code would break if it was removed. You probably want an external tool like Linux's join to pair up the (deduped) output of Hashcat with the duplicate input of just your hashes. If you want any more support, feel free to join the Discord or the Forum instead as this isn't a Hashcat issue

**Comment by Chick3nman** [comment]
Not a hashcat issue. Please discuss elsewhere.
