### ISSUE TITLE
Hashcat on windows 

### ISSUE THREAD

**Issue by Aggelos11** [hashcat/hashcat#3992]
Hello ! When I run hashcat on windows I get the following error/warning . What it means , and how can it be fixed?
![Uploading IMG_8495.jpeg…]()

**Comment by Chick3nman** [comment]
Your image link is broken. Is suspect this is not going to be a hashcat issue and is going to be better discussed on the forums or perhaps in the discord, but without seeing the error message(s) you are referring to, it's difficult to say for sure.

**Comment by Aggelos11** [comment]
![IMG_8496](https://github.com/hashcat/hashcat/assets/62383412/6918d42c-26c7-4b00-9ed6-5d76d2e7421d)

This is the error

**Comment by Chick3nman** [comment]
If you are referring to the "ADL_" lines in red, then those are safe to ignore and are likely happening because this is a laptop and so obviously doesn't have the same kind of fans or fan speed APIs. If you mean the "All hashes found", that's not an error and seems to be pretty self explanatory.

**Comment by Aggelos11** [comment]
Yeah I am referring to those red lines and the fact that it says they device #1 is ignored .. Do you know what are these and why they exist ?

**Comment by Chick3nman** [comment]
As I had already mentioned, they are there because you are running on a laptop which doesn't support calls such as "FanSpeed_get". Hashcat appears to be working so it doesn't seem like there's any reason to worry about them.

**Comment by Aggelos11** [comment]
Ok and another question … Will hashcat work in a laptop which has intel HD 4400 graphics card? If yes will the performance be fast or relatively slow compared with other GPUs ?

**Comment by Chick3nman** [comment]
It should work but any laptop will be slow compared with other GPUs.

**Comment by Chick3nman** [comment]
Closing as not a hashcat issue. Please reopen if you believe this was closed in mistake.
