### ISSUE TITLE
Intel Arc GPU is supported?

### ISSUE THREAD

**Issue by GermanAizek** [hashcat/hashcat#3995]
1. Im download Intel OpenCL SDK: https://www.intel.com/content/www/us/en/developer/articles/tool/tools-for-opencl-applications.html
2. Im download latest release Hashcat and run `hashcat -b`
3. Freeze Windows 10 eveyone

Has anyone tested support Intel Arc and does Hashcat maintainers and developers need to fix something?

**Comment by matrix** [comment]
forum: https://hashcat.net/forum/thread-11948.html
