### ISSUE TITLE
![Screenshot 2024-05-04 124145](https://github.com/hashcat/hashcat/assets/44686366/f758ab6f-7436-48a6-b8b1-8a07e3918955)

### ISSUE THREAD

**Issue by XJani** [hashcat/hashcat#3998]
![Screenshot 2024-05-04 124145](https://github.com/hashcat/hashcat/assets/44686366/f758ab6f-7436-48a6-b8b1-8a07e3918955)
How to fix this ? I am running the latest hashcat 6.2.6 release file.
any help is appreciated !

_Originally posted by @faiyaz-libscr in https://github.com/hashcat/hashcat/issues/3981#issuecomment-2094360136_

**Comment by PenguinKeeper7** [comment]
https://github.com/hashcat/hashcat/issues/3981#issuecomment-2094435976

**Comment by Chick3nman** [comment]
Not a hashcat issue, your mask is simply too large to ever be feasible.
