### ISSUE TITLE
-s / -l behave somehow differently with the PRINCE attack mode (-a 8)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#40]
When using -s / -l with -a 8 it seems that the behaviour of hashcat is somehow different to -a 0, -a 1, ... -a 5.

for instance a command like this:
$ ./hashcat-cli64.bin -a 8 --stdout dict.txt -s 1 -l 1
where dict.txt contains:
$ cat dict.txt
ABC
DEF

doesn't generate any output at all. Furthermore, -l seems to be absolute (not relative to the offset given by -s). When using -s 1, -s 2, -s 3 the output lines that are skipped is also not what the user would expect (either it skips the full ABC plain - this is *not* really what it should do -, or it skips the 1st (set of) outputted line(s)).

The behaviour of -l should also depend on how -s is working, i.e. if -s x always skips x lines, then -l x should only show x lines (which it currently does *not*).
Thx

**Comment by jsteube** [comment]
Good find, good solution
