### ISSUE TITLE
Metamask - iterations update

### ISSUE THREAD

**Issue by Banaanhangwagen** [hashcat/hashcat#4022]
When extracting the Metamask-extension-vault, there is a new value, namely `"keyMetadata"`.
In this value, a new parameter is defined: `iterations : 600000`

The modules `26600` and `26610` have _10000_ iterations hardcoded.

Recompiling Hashcat after manually changing https://github.com/hashcat/hashcat/blob/master/src/modules/module_26600.c#L172 to 600000, did the trick. (ignoring a self-test-error)

To address this change, we can maybe make a new module ?
If not, the existing module needs to be made compatible with the old metamask iterations and with the new one. This means also that metamask2hashcat needs to be updated accordingly.

Example of a (empty) vault (tested on Chrome and on Firefox) made with latest `v11.16.11`.
Password is `hashcat1`
```{
	"data": "XMuQMLbMN+bAsa00DmcfQgbvvmSq6sJK5XXfM7IdKyfeOGEClvCHVYWyFd95IYq2hV3Lmns6StHXQ83K1U0q4l9JME07B7o8Ue1cFZMTormZJh2OV/DWe8Pl+64FQBuqvWU8DC4j2OHBeCbAu4TFA14nHNMOPkbGOoSFeIHY7XK1ic1np5bhV4FZMM7HWeVDb3Ps/GXOMOcZaeHTVyy4qGzSNyVV4bFiE5z4DVRSM39xzeuhvBHCorwbhAz1oOB+n7k0Y3KeY88NyjQVG2Gi0Ru3WtjJcNOqcGbLNA/dtEAG6UjHkI1gCBTwANboLC+rzwf2vKW6gMcguDltS6n9Gl8OhwQEGTnm9c6VwRwQu+jFpuepfbF7mTJ/SWsl5NWEpJfOktMgf4dHV95IUr3OvcWzcdFx6Z/gn0igbktFeRaAzPbzcqfW27QuYdt5pk50gDq9Jf5SASKTf/2t4JSTiGF0+h4GJHw8L+uNPYnch04S7hh/N5lbsY5ksok5EbqOOcO8",
	"iv": "pSD46gn5IYvHrvAqVaroLg==",
	"keyMetadata": {
		"algorithm": "PBKDF2",
		"params": {
			"iterations": 600000
		}
	},
	"salt": "bIUVkDtIJzlvKVyIws8wiVBtHXJcDu7y7WTAmSJK+ZM="
}
```

**Comment by PenguinKeeper7** [comment]
Already covered in this PR - https://github.com/hashcat/hashcat/pull/3952

**Comment by Banaanhangwagen** [comment]
Thanks for the link 👍 ; missed it apparently.
Closing this issue.
