### ISSUE TITLE
exec  ./hashcat.bin -D 1 -I, ATTENTION! No OpenCL, Metal, HIP or CUDA installation found error

### ISSUE THREAD

**Issue by xhc-code** [hashcat/hashcat#4032]
Hello, I will execute it again/ The following error occurred during `hashcat.bin-D 1-I `. I explicitly specified the use of CPU, but the operation still encountered an error. How should I operate it? The configuration of the server is only CPU and no GPU. I want to execute commands on the CPU.
![image](https://github.com/hashcat/hashcat/assets/28866025/43e3a7f1-386c-42f4-a6c3-505ce1abb31f)

**Comment by xhc-code** [comment]
Can hashcat only work on the CPU?

**Comment by ventaquil** [comment]
Yes, it does. However your CPU must support OpenCL and you must install required drivers.

**Comment by xhc-code** [comment]
> Yes, it does. However your CPU must support OpenCL and you must install required drivers.



> Yes, it does. However your CPU must support OpenCL and you must install required drivers.

Do CPUs still need to install drivers? I have only heard that graphics cards require driver installation. Although hashcat supports CPU mode operation, it must also work on a computer that supports graphics cards, is that correct?
Is there any other way for my requirement to function properly? I just hope that hashcat runs on the CPU, but without a GPU, hashcat cannot be used. So what is the meaning of the deviceType parameter?
![image](https://github.com/hashcat/hashcat/assets/28866025/80b8f7a7-6ced-4346-ae08-4172adc85f0c)
![image](https://github.com/hashcat/hashcat/assets/28866025/80b8f7a7-6ced-4346-ae08-4172adc85f0c)

**Comment by ventaquil** [comment]
As you can see it's "OpenCL device type". It requires OpenCL runtime for your processor.

It can handle CPU-only setup (machine without GPU) however it requires:

1. CPU which supports OpenCL.
2. Installed runtime for your CPU.

**Comment by xhc-code** [comment]
> As you can see it's "OpenCL device type". It requires OpenCL runtime for your processor.
> 
> It can handle CPU-only setup (machine without GPU) however it requires:
> 
> 1. CPU which supports OpenCL.
> 2. Installed runtime for your CPU.
When I execute dnf search OpenCL, I can only search for these packages, and there is no such thing as a CPU's OpenCL runtime that can be installed. I am using the Centos9Stream Linux system.
![image](https://github.com/hashcat/hashcat/assets/28866025/d92f1812-15ba-4ee3-a8da-7080df858112)

**Comment by xhc-code** [comment]
![image](https://github.com/hashcat/hashcat/assets/28866025/a377faf0-fdd6-41f9-9772-c98c30df8d29)
CPU info

**Comment by xhc-code** [comment]
use yum repolist
![image](https://github.com/hashcat/hashcat/assets/28866025/6026f23a-0bf1-40c8-ac69-8b89ebe752bb)

**Comment by xhc-code** [comment]
> As you can see it's "OpenCL device type". It requires OpenCL runtime for your processor.
> 
> It can handle CPU-only setup (machine without GPU) however it requires:
> 
> 1. CPU which supports OpenCL.
> 2. Installed runtime for your CPU.

Hello, could you please check if there is a CPU only running method? I was unable to find the openCL for the CPU from the yum repository

**Comment by ventaquil** [comment]
Fresh build from current master.

```
$ ./hashcat -I -D1
hashcat (v6.2.6-851-g6716447df) starting in backend information mode

OpenCL Info:
============

...

OpenCL Platform ID #2
  Vendor..: Intel(R) Corporation
  Name....: Intel(R) CPU Runtime for OpenCL(TM) Applications
  Version.: OpenCL 2.1 LINUX

  Backend Device ID #5
    Type...........: CPU
    Vendor.ID......: 8
    Vendor.........: Intel(R) Corporation
    Name...........: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
    Version........: OpenCL 2.1 (Build 0)
    Processor(s)...: 40
    Clock..........: 2200
    Memory.Total...: 64069 MB (limited to 8008 MB allocatable in one block)
    Memory.Free....: 32002 MB
    Local.Memory...: 32 KB
    OpenCL.Version.: OpenCL C 2.0
    Driver.Version.: 18.1.0.0920
```

Sample benchmark.

```
$ ./hashcat -D1 -b -m0
hashcat (v6.2.6-851-g6716447df) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

...

OpenCL API (OpenCL 2.1 LINUX) - Platform #2 [Intel(R) Corporation]
==================================================================
* Device #5: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, 32002/64069 MB (8008 MB allocatable), 40MCU

Benchmark relevant options:
===========================
* --backend-devices-virtual=1
* --opencl-device-types=1
* --optimized-kernel-enable

-------------------
* Hash-Mode 0 (MD5)
-------------------

Speed.#5.........:  2392.2 MH/s (17.34ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8

Started: Tue Jul  9 14:49:17 2024
Stopped: Tue Jul  9 14:49:29 2024
```

I am using Ubuntu Server.

[According to README](https://github.com/hashcat/hashcat?tab=readme-ov-file#usagehelp) you should ask on Discord, CPU support works in my case.

**Comment by xhc-code** [comment]
![image](https://github.com/hashcat/hashcat/assets/28866025/c72a0b59-967b-4201-b1a8-54523cc79dfa)
I executed this command without any valid information printing

**Comment by xhc-code** [comment]
Is it due to version reasons?

> Fresh build from current master.
> 
> ```
> $ ./hashcat -I -D1
> hashcat (v6.2.6-851-g6716447df) starting in backend information mode
> 
> OpenCL Info:
> ============
> 
> ...
> 
> OpenCL Platform ID #2
>   Vendor..: Intel(R) Corporation
>   Name....: Intel(R) CPU Runtime for OpenCL(TM) Applications
>   Version.: OpenCL 2.1 LINUX
> 
>   Backend Device ID #5
>     Type...........: CPU
>     Vendor.ID......: 8
>     Vendor.........: Intel(R) Corporation
>     Name...........: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
>     Version........: OpenCL 2.1 (Build 0)
>     Processor(s)...: 40
>     Clock..........: 2200
>     Memory.Total...: 64069 MB (limited to 8008 MB allocatable in one block)
>     Memory.Free....: 32002 MB
>     Local.Memory...: 32 KB
>     OpenCL.Version.: OpenCL C 2.0
>     Driver.Version.: 18.1.0.0920
> ```
> 
> Sample benchmark.
> 
> ```
> $ ./hashcat -D1 -b -m0
> hashcat (v6.2.6-851-g6716447df) starting in benchmark mode
> 
> Benchmarking uses hand-optimized kernel code by default.
> You can use it in your cracking session by setting the -O option.
> Note: Using optimized kernel code limits the maximum supported password length.
> To disable the optimized kernel code in benchmark mode, use the -w option.
> 
> ...
> 
> OpenCL API (OpenCL 2.1 LINUX) - Platform #2 [Intel(R) Corporation]
> ==================================================================
> * Device #5: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, 32002/64069 MB (8008 MB allocatable), 40MCU
> 
> Benchmark relevant options:
> ===========================
> * --backend-devices-virtual=1
> * --opencl-device-types=1
> * --optimized-kernel-enable
> 
> -------------------
> * Hash-Mode 0 (MD5)
> -------------------
> 
> Speed.#5.........:  2392.2 MH/s (17.34ms) @ Accel:1024 Loops:1024 Thr:1 Vec:8
> 
> Started: Tue Jul  9 14:49:17 2024
> Stopped: Tue Jul  9 14:49:29 2024
> ```
> 
> I am using Ubuntu Server.
> 
> [According to README](https://github.com/hashcat/hashcat?tab=readme-ov-file#usagehelp) you should ask on Discord, CPU support works in my case.

Is it due to version reasons?

**Comment by matrix** [comment]
please continue this discussion on discord or forum
