### ISSUE TITLE
what happend about my hashcat

### ISSUE THREAD

**Issue by moto-sgr** [hashcat/hashcat#4041]
C:\Users\moto\Desktop\hashcat-6.2.6>hashcat -m 11300 -a 3 wallet.hash.txt ?a?a?a?a?a?a -w 3 --increment --increment-min=6 --increment-max=20
hashcat (v6.2.6) starting

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 12.3)
====================
* Device #1: NVIDIA GeForce RTX 4060 Laptop GPU, 7114/8187 MB, 24MCU

OpenCL API (OpenCL 3.0 CUDA 12.3.107) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: NVIDIA GeForce RTX 4060 Laptop GPU, skipped

OpenCL API (OpenCL 3.0 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #3: Intel(R) UHD Graphics 770, 2752/5611 MB (1402 MB allocatable), 16MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD-LOOP
* Uses-64-Bit

Watchdog: Temperature abort trigger set to 90c

nvrtcCompileProgram(): NVRTC_ERROR_INVALID_OPTION

nvrtc: error: invalid value for --gpu-architecture (-arch)

* Device #1: Kernel ./OpenCL/shared.cl build failed.

* Device #1: Kernel ./OpenCL/shared.cl build failed.

Started: Wed Jul 10 16:57:34 2024
Stopped: Wed Jul 10 16:57:37 2024

**Comment by 0xVavaldi** [comment]
Could you provide the output of the `hashcat -II` command?

**Comment by matrix** [comment]
wrong cuda version installed, must be matched with current driver
