### ISSUE TITLE
Hashcat stucked

### ISSUE THREAD

**Issue by cmdcorp6534** [hashcat/hashcat#4049]
![屏幕截图 2024-07-21 073631](https://github.com/user-attachments/assets/b24a2755-d48a-423c-9575-2239407b0ad7)
As the screenshot shows, I want to use hashcat on Windows, but hashcat has stucked on self-test for a long time. I installed kali linux Virtual machine, it worked properly. How can I use hashcat on Windows?

**Comment by PenguinKeeper7** [comment]
You redacted the hash in your command but not in the title of the command prompt window, by the way. As for your question, it may be your integrated graphics being a little annoying, so using "-d 1" to select only your dedicated card may fix your issue. If even that doesn't work try installing the CUDA Toolkit as it suggests, the amount of VRAM in your GPUs may just simply not be enough so if installing the toolkit doesn't work, you'd have to try "-D 1 -d 3" which would select your CPU. Not ideal to use CPU but if that's the only way to make it work, there's no choice

**Comment by cmdcorp6534** [comment]
@PenguinKeeper7 Thank you very much. This problem was solved by using "-d 1", but I installed CUDA as well, it runned much faster.
