### ISSUE TITLE
Make a dependency on any OpenCL optional

### ISSUE THREAD

**Issue by barracuda156** [hashcat/hashcat#4059]
Is it possible to make OpenCL optional? It is not universally supported, while otherwise C99 is.
No need to change the default behavior, just make it possible to disable it if desired.

**Comment by Chick3nman** [comment]
I'm not sure I understand how it could be optional. We use OpenCL as our computing runtime, a "backend" as we call it, as it's the most universally supported interface. Without OpenCL, our kernels would not function. We do have other backend runtimes, CUDA, HIP, Metal, etc., but all of our kernels are essentially derived from the written OpenCL and compiled into formats understood by the other backends. C99 is not a compute runtime, at least to my knowledge, and doesn't really make sense as a "replacement" for OpenCL here. Perhaps there is some misunderstanding of the two?

**Comment by barracuda156** [comment]
@Chick3nman Sorry, indeed. I did not read through the code and assumed that OpenCL is used to speed-up computations but is not the only back-end in effect. I will close the issue as not planned.
