### ISSUE TITLE
Doesn't see CPU, GPU

### ISSUE THREAD

**Issue by SatoshiMota** [hashcat/hashcat#4066]
All the drivers are installed (the newest ones), I’m already thinking maybe it’s not the newest versions that are needed?

Video card rtx 3050 laptop

"C:\Users\satos\Downloads\hashcat-7.0.0-by-mavrodi>hashcat -I
hashcat (v6.2.6-851-g6716447df) starting in backend information mode

C:\Users\satos\Downloads\hashcat-7.0.0-by-mavrodi>"

**Comment by SatoshiMota** [comment]
"KeyringController":{"vault":"{\"data\":\"i4EPrEBuLqo3pmP80zNpXKQlYJ2VwBZOULMhNWBdczOj8dZFJBZKB26SfGJXqm9b36lfzftYZ56+jDv6YQUy2krdslyxL55M8Fr2WdK+zq17ekuZvE/8SMMOfqD6XAReS7bsVM3giOmTZDwH9BVJMFXR7E/VEsWkTMUyz3XMHWaDLPRhCDeFFB5OoQ2wACMLphrys35lLwRljYYwPy2j9rfT2pzFAQy7aif9avdlIMvNhTz1+q2pUDNLGPcUK0D/ZaBNMUiC6TLmr2eD66wqib9M3UtTxBvjzmCHSNUpx3EWzctYx7ctSu2v1l14WDKVU9UrA2jrn6HfYPEQUSa1cghN7+HSsBKZCAX/hf2iW5k6t8GMyzIHYjDF2kqK4AJAKvcMmvVhu8G7jAzrE2A8/G7uiK3oyNp9Rk8gjbaBo9kvhJxPm+IZnXXzoPR6Tc/fvr8WOQ8gqKaRmvaUSgbXfZ4D1pA1tkJ7TKUEA/JOkUhlDpRMuVb3Uz+FgPcGy+QHCcYli16Vl3l/v1EY1ihrcqI9Y2qXfsleIu83uoB/JqWG\",\"iv\":\"1SGH/41Ej34IxRts7Nssug==\",\"keyMetadata\":{\"algorithm\":\"PBKDF2\",\"params\":{\"iterations\":600000}},\"salt\":\"nzwtn+GGezB85lemeD462X01tyxeTxaVHtxsVXgzKos=\"}"}

And if you’re not too lazy, post the correct format for the new MetaMask (600,000 iterations) by type

$metamask$nzwtn+GGezB85lemeD462X01tyxeTxaVHtxsVXgzKos=$1SGH/41Ej34IxRts7Nssug==$i4EPrEBuLqo3pmP80zNpXKQlYJ2VwBZOULMhNWBdczOj8dZFJBZKB26SfGJXqm9b36lfzftYZ56+jDv6YQUy2krdslyxL55M8Fr2WdK+zq17ekuZvE/8SMMOfqD6XAReS7bsVM3giOmTZDwH9BVJMFXR7E/VEsWkTMUyz3XMHWaDLPRhCDeFFB5OoQ2wACMLphrys35lLwRljYYwPy2j9rfT2pzFAQy7aif9avdlIMvNhTz1+q2pUDNLGPcUK0D/ZaBNMUiC6TLmr2eD66wqib9M3UtTxBvjzmCHSNUpx3EWzctYx7ctSu2v1l14WDKVU9UrA2jrn6HfYPEQUSa1cghN7+HSsBKZCAX/hf2iW5k6t8GMyzIHYjDF2kqK4AJAKvcMmvVhu8G7jAzrE2A8/G7uiK3oyNp9Rk8gjbaBo9kvhJxPm+IZnXXzoPR6Tc/fvr8WOQ8gqKaRmvaUSgbXfZ4D1pA1tkJ7TKUEA/JOkUhlDpRMuVb3Uz+FgPcGy+QHCcYli16Vl3l/v1EY1ihrcqI9Y2qXfsleIu83uoB/JqWG

**Comment by PenguinKeeper7** [comment]
It's a very common issue with OpenCL. Make sure you have the CUDA Toolkit installed then use `--backend-ignore-opencl` and it should work okay. Also, it's a really, really bad idea to post your metamask data like that. Your private keys can be reversed from that information you posted

**Comment by SatoshiMota** [comment]
> It's a very common issue with OpenCL. Make sure you have the CUDA Toolkit installed then use `--backend-ignore-opencl` and it should work okay. Also, it's a really, really bad idea to post your metamask data like that. Your private keys can be reversed from that information you posted

I wrote myself a code in JS that creates such data, there is an empty seed phrase inside. I figured it out with `--backend-ignore-opencl` thanks
