### ISSUE TITLE
error：Cannot load module ./modules/module_02630.dll

### ISSUE THREAD

**Issue by a2vllcO** [hashcat/hashcat#4072]
C:\Users\Administrator01\Downloads\hashcat-test\hashcat-6.2.6>hashcat.exe -a 3 -m 2630 vpn2.txt test.txt
hashcat (v6.2.6) starting

Either the specified hash mode does not exist in the official repository,
or the file(s) could not be found. Please check that the hash mode number is
correct and that the files are in the correct place.

Cannot load module ./modules/module_02630.dll

Started: Wed Sep 04 18:49:24 2024
Stopped: Wed Sep 04 18:49:24 2024

https://hashcat.net/wiki/doku.php?id=example_hashes There is indeed an encryption algorithm - m 2630 in the system, but module_02630.dll does not exist

**Comment by PenguinKeeper7** [comment]
On the examples page, it has an asterisk next to the name, which means "* In beta or not yet released". In order to use this module, you can't use the release 6.2.6 and you either have to compile the latest code yourself or use the public beta at hashcat.net/beta

**Comment by Chick3nman** [comment]
Not a bug, module was not available before last release and has only been added to the repo since then.
