### ISSUE TITLE
$RAR3$*0 - hashfile is empty or corrupt. But its not?

### ISSUE THREAD

**Issue by henninghh990** [hashcat/hashcat#4075]
....

**Comment by PenguinKeeper7** [comment]
> hashcat.exe -m 12500 -a 0 cracked.txt hash.txt mypass.txt

To set an output file you need to use `-o`, so `-o cracked.txt` or:
`hashcat.exe -m 12500 -a 0 -o cracked.txt hash.txt mypass.txt`
It's trying to use your cracked.txt file as a hash file because it's first

**Comment by henninghh990** [comment]
> > hashcat.exe -m 12500 -a 0 cracked.txt hash.txt mypass.txt
> 
> To set an output file you need to use `-o`, so `-o cracked.txt` or: `hashcat.exe -m 12500 -a 0 -o cracked.txt hash.txt mypass.txt` It's trying to use your cracked.txt file as a hash file because it's first

Wow, how did I not see that..
Well, that brings me to the next error!
`Hashfile 'hash.txt' on line 1 (nameoff...0f34bfaf11d9b1:0::::nameoffile.rar): Signature unmatched`

Edit: Seems removing filename worked.

**Comment by PenguinKeeper7** [comment]
Yeah, this isn't a bug, that's just John's format, which is different to Hashcat's. If you need any additional support, feel free to use the Hashcat Discord or Forum

**Comment by magnumripper** [comment]
Drop the passwd-style fields:
```
nameoffile.rar:$RAR3$*0*a985092fc40819b3*ccc5eaac1223e99eb20f34bfaf11d9b1:0::::nameoffile.rar
```
→
```
$RAR3$*0*a985092fc40819b3*ccc5eaac1223e99eb20f34bfaf11d9b1
```
