### ISSUE TITLE
hashcat looking in binary folder for resources

### ISSUE THREAD

**Issue by jdek** [hashcat/hashcat#408]
Compiling and installing master from source (using `make install`) and then trying to run ends up with:

```
$ hashcat -m 100 -a 3 -1 abcdef ~/hashes.txt "?1?1?1?1?1?1?1?1?1?1"
hashcat (v3.00-16-g86cf95e) starting...



/usr/local/bin/hashcat.hctune: No such file or directory
```

**Comment by anthraxx** [comment]
I can confirm this issue, but the provided patch does not help for me (running Linux).

```
> strace -e open,rmdir,mkdir hashcat --benchmark 
[...]
mkdir("/usr/bin/kernels", 0700)         = -1 EACCES (Permission denied)
open("/usr/bin/hashcat.restore", O_RDONLY) = -1 ENOENT (No such file or directory)
hashcat (v3.00) starting in benchmark-mode...

rmdir("/usr/bin/hashcat.induct")        = -1 ENOENT (No such file or directory)
mkdir("/usr/bin/hashcat.induct", 0700)  = -1 EACCES (Permission denied)


ERROR: /usr/bin/hashcat.induct: Permission denied

+++ exited with 255 +++
```

it should use some world writable location like /tmp or cwd. Currently this issue keeps me from being able to move hashcat into the main distro packages.

everything installed via `make install`

**Comment by jdek** [comment]
@anthraxx I spoke with a friend who uses linux, they are having the same issue. I think it's because `hashcat` isnt in the `$(prefix)/bin` folder which it was compiled with, and defaults to the binary dir, [this](https://github.com/hashcat/hashcat/blob/master/src/hashcat.c#L6198) if statement is to blame afaict.
Try manually setting the PREFIX maybe?

**Comment by anthraxx** [comment]
@joshdekock well I provided PREFIX but didn't thought it may be required for building and the install step that contained the PREFIX was separated. works, thx :smile_cat:

**Comment by jdek** [comment]
This probably needs to be added to the README, or there needs to be a design change so that it doesn't fail like this. It was something I'd like to ask the hashcat guys: wouldn't it be better to check the relative resource directories (I.e. `../share`) from the bin directory, and then if they don't exist check the current directory before describing an error if neither directories are writable so that a user can either fix permissions or change the prefix? It wouldn't create much overhead, and would reduce a lot of confusion IMO.

**Comment by anthraxx** [comment]
well, I agree with the documentation, however the /usr/share directory will never be writable to a user for a distro package. Luckily hashcat uses ~/.hashcat/ is such cases.

**Comment by jdek** [comment]
I was more thinking about /usr/local. Although in your case it didn't use ~/.hashcat even though it should have fallen back onto it. This was my main point really, implement a fallback (or fix the non-working one). Mind you, I haven't had too much time to look at the code though

**Comment by anthraxx** [comment]
I see, valid point. ignore my comment :stuck_out_tongue_closed_eyes:
