### ISSUE TITLE
ZIP PK2 PASSword Cannot be got with  HASHCAT. 

### ISSUE THREAD

**Issue by z1n** [hashcat/hashcat#4084]
**GitHub is for bugs and features - not for support**
For support, please use the hashcat forums https://hashcat.net/forum/

**Check the FAQ**
Some items that might appear to be issues are not issues. Please review the hashcat FAQ https://hashcat.net/wiki/doku.php?id=frequently_asked_questions before submitting a bug report.

**Describe the bug**
One zip hash was generated by zip2john and can be cracked with john but cannot be cracked with hashcat.
The hash is 
[new.hash.linux.txt](https://github.com/user-attachments/files/17150085/new.hash.linux.txt)

John found the correct password: 6598
`john D:\Files\Research\2024网络安全大师\traffic2附件\new.hash.linux.txt
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 7 candidates buffered for the current salt, minimum 8 needed for performance.
Warning: Only 5 candidates buffered for the current salt, minimum 8 needed for performance.
Warning: Only 7 candidates buffered for the current salt, minimum 8 needed for performance.
Almost done: Processing the remaining buffered candidate passwords, if any.
Warning: Only 3 candidates buffered for the current salt, minimum 8 needed for performance.
Proceeding with wordlist:password.lst, rules:Wordlist
Proceeding with incremental:ASCII
6598             (output_1.zip/screct.pdf)
1g 0:00:00:15 DONE 3/3 (2024-09-26 22:19) 0.06336g/s 2676Kp/s 2676Kc/s 2676KC/s 054619944..nicd38
Use the "--show" option to display all of the cracked passwords reliably
Session completed
`

but hashcat failed to find the password with mask ?d?d?d?d

`
hashcat -a 3 -m 17200 new.hash.linux.txt ?d?d?d?d
hashcat (v6.2.6) starting

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #3: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #4: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #5: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #6: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 12.2)
====================
* Device #1: NVIDIA GeForce RTX 3090, 23320/24575 MB, 82MCU
* Device #2: NVIDIA GeForce RTX 3090, 23320/24575 MB, 82MCU
* Device #3: NVIDIA GeForce RTX 3090, 23320/24575 MB, 82MCU

OpenCL API (OpenCL 3.0 CUDA 12.2.79) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #4: NVIDIA GeForce RTX 3090, skipped
* Device #5: NVIDIA GeForce RTX 3090, skipped
* Device #6: NVIDIA GeForce RTX 3090, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 2160 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 17200 (PKZIP (Compressed))
Hash.Target......: $pkzip2$1*1*2*0*c1b8*db4d*2d4bc916*0*28*8*c1b8*2d4b...kzip2$
Time.Started.....: Thu Sep 26 22:21:45 2024 (2 secs)
Time.Estimated...: Thu Sep 26 22:21:47 2024 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?d?d?d?d [4]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     7850 H/s (1273.28ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#3.........:        0 H/s (0.00ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#*.........:     7850 H/s
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 10000/10000 (100.00%)
Rejected.........: 0/10000 (0.00%)
Restore.Point....: 0/1000 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-10 Iteration:0-10
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-10
Restore.Sub.#3...: Salt:0 Amplifier:0-0 Iteration:0-10
Candidate.Engine.: Device Generator
Candidates.#1....: 1234 -> 6764
Candidates.#2....: [Generating]
Candidates.#3....: [Generating]
Hardware.Mon.#1..: Temp: 57c Fan: 30% Util:100% Core:1950MHz Mem:9501MHz Bus:16
Hardware.Mon.#2..: Temp: 32c Fan: 30% Util:  0% Core:1695MHz Mem:9501MHz Bus:16
Hardware.Mon.#3..: Temp: 33c Fan: 30% Util:  0% Core:1695MHz Mem:9501MHz Bus:16

Started: Thu Sep 26 22:21:42 2024
Stopped: Thu Sep 26 22:21:47 2024
`

**Comment by matrix** [comment]
Hi,

on my side it works if you remove "output_1.zip/screct.pdf:" from new.hash.linux.txt

```
[...]6e4c2347acf70e41095df22e3637854cc67755edf670ccc6f10cb891cdecc240430736a*$/pkzip2$:6598

Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 17200 (PKZIP (Compressed))
Hash.Target......: $pkzip2$1*1*2*0*c1b8*db4d*2d4bc916*0*28*8*c1b8*2d4b...kzip2$
Time.Started.....: Sat Oct 26 13:36:34 2024, (0 secs)
Time.Estimated...: Sat Oct 26 13:36:34 2024, (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?d?d?d?d [4]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   553.3 kH/s (17.92ms) @ Accel:512 Loops:10 Thr:1 Vec:4
Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
Progress.........: 10000/10000 (100.00%)
Rejected.........: 0/10000 (0.00%)
Restore.Point....: 0/1000 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-10 Iteration:0-10
Candidate.Engine.: Device Generator
Candidates.#1....: 1234 -> 6764
Hardware.Mon.SMC.: Fan0: 20%
Hardware.Mon.#1..: Temp: 52c
```

**Comment by ThomasCr** [comment]
please, can you also explain, for what it the last number **after** `....0430736a*$/pkzip2$:` and where have you got that number from?

**Comment by matrix** [comment]
> please, can you also explain, for what it the last number **after** `....0430736a*$/pkzip2$:` and where have you got that number from?

Is the password that hashcat found ...

**Comment by z1n** [comment]
> Hi,
> 
> on my side it works if you remove "output_1.zip/screct.pdf:" from new.hash.linux.txt
> 
> ```
> [...]6e4c2347acf70e41095df22e3637854cc67755edf670ccc6f10cb891cdecc240430736a*$/pkzip2$:6598
> 
> Session..........: hashcat
> Status...........: Cracked
> Hash.Mode........: 17200 (PKZIP (Compressed))
> Hash.Target......: $pkzip2$1*1*2*0*c1b8*db4d*2d4bc916*0*28*8*c1b8*2d4b...kzip2$
> Time.Started.....: Sat Oct 26 13:36:34 2024, (0 secs)
> Time.Estimated...: Sat Oct 26 13:36:34 2024, (0 secs)
> Kernel.Feature...: Pure Kernel
> Guess.Mask.......: ?d?d?d?d [4]
> Guess.Queue......: 1/1 (100.00%)
> Speed.#1.........:   553.3 kH/s (17.92ms) @ Accel:512 Loops:10 Thr:1 Vec:4
> Recovered........: 1/1 (100.00%) Digests (total), 1/1 (100.00%) Digests (new)
> Progress.........: 10000/10000 (100.00%)
> Rejected.........: 0/10000 (0.00%)
> Restore.Point....: 0/1000 (0.00%)
> Restore.Sub.#1...: Salt:0 Amplifier:0-10 Iteration:0-10
> Candidate.Engine.: Device Generator
> Candidates.#1....: 1234 -> 6764
> Hardware.Mon.SMC.: Fan0: 20%
> Hardware.Mon.#1..: Temp: 52c
> ```

No. **Could you get the password with GPU devices?**

It's really strange.

log:
[hashcat.log](https://github.com/user-attachments/files/17608931/hashcat.log)

D:\Download\hashcat-6.2.6>hashcat -a 3 -m 17200 new.hash.linux.txt ?d?d?d?d
hashcat (v6.2.6) starting

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #3: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #4: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #5: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #6: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 12.6)
====================
* Device #1: NVIDIA GeForce RTX 3090, 23306/24575 MB, 82MCU
* Device #2: NVIDIA GeForce RTX 3090, 23306/24575 MB, 82MCU
* Device #3: NVIDIA GeForce RTX 3090, 23306/24575 MB, 82MCU

OpenCL API (OpenCL 3.0 CUDA 12.6.65) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #4: NVIDIA GeForce RTX 3090, skipped
* Device #5: NVIDIA GeForce RTX 3090, skipped
* Device #6: NVIDIA GeForce RTX 3090, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 2160 MB

The wordlist or mask that you are using is too small.
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Mode........: 17200 (PKZIP (Compressed))
Hash.Target......: $pkzip2$1*1*2*0*c1b8*db4d*2d4bc916*0*28*8*c1b8*2d4b...kzip2$
Time.Started.....: Sun Nov 03 09:35:53 2024 (2 secs)
Time.Estimated...: Sun Nov 03 09:35:55 2024 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Mask.......: ?d?d?d?d [4]
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:     7751 H/s (1289.72ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#2.........:        0 H/s (0.00ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#3.........:        0 H/s (0.00ms) @ Accel:1024 Loops:10 Thr:32 Vec:1
Speed.#*.........:     7751 H/s
Recovered........: 0/1 (0.00%) Digests (total), 0/1 (0.00%) Digests (new)
Progress.........: 10000/10000 (100.00%)
Rejected.........: 0/10000 (0.00%)
Restore.Point....: 0/1000 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-10 Iteration:0-10
Restore.Sub.#2...: Salt:0 Amplifier:0-0 Iteration:0-10
Restore.Sub.#3...: Salt:0 Amplifier:0-0 Iteration:0-10
Candidate.Engine.: Device Generator
Candidates.#1....: 1234 -> 6764
Candidates.#2....: [Generating]
Candidates.#3....: [Generating]
Hardware.Mon.#1..: Temp: 60c Fan: 30% Util:100% Core:1950MHz Mem:9501MHz Bus:16
Hardware.Mon.#2..: Temp: 32c Fan: 30% Util:  0% Core:1695MHz Mem:9501MHz Bus:16
Hardware.Mon.#3..: Temp: 61c Fan: 31% Util:  0% Core:1695MHz Mem:9501MHz Bus:16

Started: Sun Nov 03 09:35:48 2024
Stopped: Sun Nov 03 09:35:55 2024

**Comment by z1n** [comment]
> please, can you also explain, for what it the last number **after** `....0430736a*$/pkzip2$:` and where have you got that number from?

the complete hash is in the file https://github.com/user-attachments/files/17150085/new.hash.linux.txt

**Comment by matrix** [comment]
> > please, can you also explain, for what it the last number **after** `....0430736a*$/pkzip2$:` and where have you got that number from?
> 
> the complete hash is in the file https://github.com/user-attachments/files/17150085/new.hash.linux.txt

@z1n hashcat works If you follow the directions I already wrote. Since there is no bug but just a problem with how you use hashcat, if you need please use the forum or discord.

**Comment by s3inlc** [comment]
Just as a note.. the real problem here is, that @z1n is using a way too old hashcat (2 years) where there was a bug existing (most likely fixed in #3549), resulting in not cracking such a hash. 
With the newest builds from master or beta builds it works, but not with the v6.2.6 release.

**Comment by z1n** [comment]
@s3inlc  @matrix   Thank you for taking the time to identify this issue. 
Also, where could I download the latest Windows release version, or must I compile it from the source?

**Comment by matrix** [comment]
to be on the safe side, I recommend you compile the source manually because the last release is too old.
If you can't, try here https://hashcat.net/beta/

**Comment by z1n** [comment]
> to be on the safe side, I recommend you compile the source manually because the last release is too old. If you can't, try here https://hashcat.net/beta/

Okay.  Thank you for your quick and thorough reply, and  I will try to compile the source manually.
