### ISSUE TITLE
hashcat kernel time out 

### ISSUE THREAD

**Issue by V1bho** [hashcat/hashcat#4095]
WARNING! Kernel exec timeout is not disabled.
This may cause "CL_OUT_OF_RESOURCES" or related errors.
To disable the timeout, see: https://hashcat.net/q/timeoutpatch

This problem i faced right now give solution for windows 11 i try the all method thos show in this web site https://hashcat.net/q/timeoutpatch i create a file name called "wddm_timeout_patch.reg" in binary type on registry but this not working for me if some one know about so give the solution for that pls help me for that.

**Comment by V1bho** [comment]
WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch

 This problem i faced right now give solution for windows 11 i try the all method thos show in this web site https://hashcat.net/q/timeoutpatch i create a file name called "wddm_timeout_patch.reg" in binary type on registry if some one haw solution so tell me pls.

**Comment by Chick3nman** [comment]
This is an older warning and the issue that it's related to seems to not be a problem on more modern systems or versions of Windows. You can safely ignore the warning for now and it will likely be deprecated/removed in future versions of hashcat.
