### ISSUE TITLE
hashcat v3.00 segfaulting on Kali

### ISSUE THREAD

**Issue by Kilonga** [hashcat/hashcat#410]
No issues at compile time.  I am running Kali on a late 2013 MacBook Pro.

Here is the output of uname -a:

> uname -a
> Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.2-2kali2 (2016-06-28) x86_64 GNU/Linux

I tried to run hashcat with `--gpu-temp-disable` as suggested in the forums but got the same result.
I am attaching a core dump.

Please let me know if you need any other tests or information.

Thanks!

Core dump: [core](https://drive.google.com/open?id=0B49iQjwTxmoHVXBsR3VYZnlidmc)

**Comment by ghost** [comment]
Do you have the intel/gt450m setup?  I am running at late 2013 MBP with kali rolling and do not see this issue.  Assuming you have the same hardware, the only difference is that I'm on 4.0.0 where you are on 4.6.0.

**Comment by Kilonga** [comment]
I have the Intel/GT750m setup.  If I compile the same version of hashcat (v3.00) on OSX and run it there it works with no issues, but it will not work on Kali.

**Comment by ghost** [comment]
Which nvidia driver are you using on Kali?

**Comment by Kilonga** [comment]
I installed the package `nvidia-kernel-dkms`

**Comment by ghost** [comment]
Ok, try removing that and installing the latest driver from NVIDIA.

**Comment by Kilonga** [comment]
Installed latest drivers but still having the same issue.
`nvidia-smi` output
NVIDIA-SMI 367.27                 Driver Version: 367.27

**Comment by ghost** [comment]
List the output of `nvidia-smi -q -a` please

**Comment by Kilonga** [comment]
Here is the output:

> ==============NVSMI LOG==============

Timestamp                           : Mon Jul  4 11:28:01 2016
Driver Version                      : 367.27

Attached GPUs                       : 1
GPU 0000:01:00.0
    Product Name                    : GeForce GT 750M
    Product Brand                   : GeForce
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : Disabled
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-faa35d8c-e3f1-0aef-1885-38a70dc1ed9b
    Minor Number                    : 0
    VBIOS Version                   : 80.07.C7.04.01
    MultiGPU Board                  : N/A
    Board ID                        : N/A
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : N/A
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x0FE910DE
        Bus Id                      : 0000:01:00.0
        Sub System Id               : 0x0130106B
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 1969 MiB
        Used                        : 336 MiB
        Free                        : 1633 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
        Encoder                     : N/A
        Decoder                     : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit  
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit  
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
        Aggregate
            Single Bit  
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit  
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 49 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : N/A

**Comment by ghost** [comment]
I meant to tell you that I have tried numerous ways to reproduce this error and have not been able to.

**Comment by jsteube** [comment]
Can you guys retry please with latest version from github. So much changed....

**Comment by jsteube** [comment]
Any updates here?

**Comment by jsteube** [comment]
OP not responding for months and too old version. Closing.
