### ISSUE TITLE
Convert plaintext to hash value

### ISSUE THREAD

**Issue by x0da6h** [hashcat/hashcat#4100]
Since the principle of hashcat is to convert each password in the codebook into over 200 different hash values, why not create a feature that can convert a single plaintext or multiple plaintexts into a specified hash type and output it directly? This is very helpful for some hash password replacement issues!

**Comment by x0da6h** [comment]
We need the ability to convert text into hash!

**Comment by AnnualMedia1328** [comment]
There already tools that can do that like mdxfind.

**Comment by matrix** [comment]
hi, I suggest you continue this conversation on discord or the forum.
