### ISSUE TITLE
Incorrect documentation of "C" rule

### ISSUE THREAD

**Issue by mohemiv** [hashcat/hashcat#4119]
Here is the fragment of the documentation:
```
C 	Lowercase first found character, upercase the rest
```
But in fact, what the "C" rule does is lowercase the first character of the word (not the first found character) and uppercase the rest.

**Comment by Chick3nman** [comment]
Perhaps this is a language barrier issue, but what is the perceived difference between "first found character" and "first character"?

**Comment by PenguinKeeper7** [comment]
> Perhaps this is a language barrier issue, but what is the perceived difference between "first found character" and "first character"?

Potentially being the word "found", implying that it looks for the first a-z character, when it doesn't. It just attempts to lowercase whatever the first character in the string is
```
> echo password | ./hashcat --stdout -j C
pASSWORD

> echo 1password | ./hashcat --stdout -j C
1PASSWORD 
```
I kinda agree that it's a bit confusing and the "found" word should be removed, as it implies that the second result would be 1pASSWORD instead of 1PASSWORD

**Comment by Chick3nman** [comment]
Yeah, I can see "Found" being a bit confusing, hence the question about how it's being perceived. Otherwise, it seems to do exactly what it says, just the description is a bit overly verbose in that way.

**Comment by mohemiv** [comment]
Yeah, @PenguinKeeper7 has explained exactly what I meant. So, the easy solution is to just remove the word "found" and close the issue.

Also, it will be great to change the documentation for the "c" rules as well. For example:
"Capitalize the first letter and lower the rest" => " Capitalize the first character and lower the rest"

In this context, "first letter" may be read as "first found character", but "first character" will be read as "first byte".

Or, we can modify the code to make it work as the text says.

**Comment by Chick3nman** [comment]
To be clear, this would just be a wiki change right? I don't believe we have any other documentation that indicates the function of the rule operators.

As for changing the code, many of the rule operations are actually designed with the intent of being cross compatible with already existing tools like JohnTheRipper which also implement these functions so it would not be good to change the behavior to be different from those tools.

**Comment by mohemiv** [comment]
Yep. I am absolutely fine with this.

**Comment by roycewilliams** [comment]
Wiki updated.

https://hashcat.net/wiki/doku.php?id=rule_based_attack#implemented_compatible_functions

 	| Capitalize | c | Capitalize the first ~letter~ character and lower the rest | c | p@ssW0rd | P@ssw0rd |  | 
 	| Invert Capitalize | C | Lowercase the first ~found~ character, uppercase the rest | C | p@ssW0rd | p@SSW0RD |  |

**Comment by Chick3nman** [comment]
This looks resolved to me, I'm going to close it for now but feel free to reopen if the fix was not enough.
