### ISSUE TITLE
hashcat -m 1000 当密码本非常大时会出问题

### ISSUE THREAD

**Issue by Eyjafjalla6** [hashcat/hashcat#4122]
密码本password.txt大小为9MB

原始密码Admin@1234，对应NTLM为cb136a448767792bae25563a498a86e6
如下图，直接 "exhausted"
![I(CXR1FB5NAW4TF8FU7$HF2](https://github.com/user-attachments/assets/56ffd554-690f-4192-93f6-ff87cf53af90)

![UY2URRPUQ$(67 K}0VMS@NR](https://github.com/user-attachments/assets/30e6b2e7-78bb-46fa-b8ef-7e649641c462)

图中的12116是密码本最后一个密码

**Comment by ghost** [comment]
Most likely `Admin@1234` just isn't in password.txt.

**Comment by Eyjafjalla6** [comment]
![image](https://github.com/user-attachments/assets/7447c9c0-eec3-497b-921b-a2408cfa6e85)

**Comment by b8vr** [comment]
Is the password.txt utf-8 encoded? It should be.

**Comment by PenguinKeeper7** [comment]
Admin@1234 and admin@1234 resolve to different hashes. In this case, your hash above is for Admin@1234 so admin@1234 would do nothing to help crack it unless you used rules, like `-r rules/dive.rule`

**Comment by Eyjafjalla6** [comment]
PenguinKeeper7 大佬说得对，应该是大小写问题导致hash值对不上
![image](https://github.com/user-attachments/assets/37955cad-77c6-4512-83e1-42616091158c)
