### ISSUE TITLE
Weird issue on Fedora 24

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#414]
I'll just copy/paste

`[mangix@mangix hashcat]$ ./hashcat -b
hashcat (v3.00-21-g30919d4) starting in benchmark-mode...

ERROR: clGetDeviceIDs() : -1 : CL_DEVICE_NOT_FOUND

[mangix@mangix hashcat]$ ./hashcat --opencl-platforms=2 -b
hashcat (v3.00-21-g30919d4) starting in benchmark-mode...

ERROR: clGetDeviceIDs() : -1 : CL_DEVICE_NOT_FOUND

[mangix@mangix hashcat]$ ./hashcat --opencl-platforms=1 -b
hashcat (v3.00-21-g30919d4) starting in benchmark-mode...
# OpenCL Platform #1: Intel
- Device #1: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 1024/2048 MB allocatable, 24MCU

ERROR: clGetDeviceIDs() : -1 : CL_DEVICE_NOT_FOUND

[mangix@mangix hashcat]$ 
`

2 runtimes are installed on here: Beignet and Mesa. If I specify nothing, it seems that hashcat looks at the Mesa runtime and quits after failing to find a device without looking at other runtimes. If I specify Beignet manually, it still gives up even though it sees the device.

Version is latest git.

**Comment by jsteube** [comment]
Can you post output of clinfo please

**Comment by neheb** [comment]
http://pastebin.com/UuuRicR1

**Comment by jsteube** [comment]
Should be fixed, please test and close the issue

**Comment by neheb** [comment]
almost ;). here's some weirdness: http://pastebin.com/TsQA0PFt

basically: original with pocl, beignet, and mesa works. remove pocl and it no longer works. another issue seems to be that the devices seem to show up multiple times. cosmetic issue i guess.

at least it's the GPU that gets used.

**Comment by jsteube** [comment]
Try again please

**Comment by jsteube** [comment]
I pushed some fix

**Comment by neheb** [comment]
fixed
