### ISSUE TITLE
MBP not enough allocatable device-memory

### ISSUE THREAD

**Issue by BeanBagKing** [hashcat/hashcat#416]
Forum Reference: https://hashcat.net/forum/thread-5575.html

There are two issues related to hashcat running on a Macbook Pro with a Core i5-5287U.

1) When reaching scrypt, the device runs out of memory and, rather than skipping gracefully, it gives the following error and dies.
`Device #2: Device does not provide enough allocatable device-memory to handle this attack`
Atom gave the following comments regarding this issue:

> This kind of error is actually that you do not have enough (device) memory to handle scrypt. But you're right, it should skip over the error and continue. Please post a GitHub issue for that.

2) When using the Iris Graphics 6100 device on the same CPU, the following error is encountered.
`ERROR: clEnqueueNDRangeKernel() : -54 : CL_INVALID_WORK_GROUP_SIZE`
Again, the expected behavior is gracefully skipping this benchmark test and moving on. Atom's comments via forum:

> This is a known error. For some reason on OSX, on CPU, it's not allowed to use a 2nd (or 3rd) dimension for the kernel execution in GPGPU. It's a runtime limitation which is basically not there, it's a pure software limitation. I can't workaround this, because for bitsliced DES kernel (like LM) it's required. However the problem is the same. It should skip over and continue with the benchmark.

**Comment by jsteube** [comment]
Lots of stuff changed since this last test. Can you please retry with latest version from github?

**Comment by jsteube** [comment]
Any update here?

**Comment by jsteube** [comment]
OP not responding for months and too old version. Closing.

**Comment by danpalmer** [comment]
I just experienced this on macOS Sierra, MacBook Pro i7, Hashcat 3.10.

**Comment by DustyPaw** [comment]
Same here, eg:

```
... Hashmode: 3200 - bcrypt $2*$, Blowfish (Unix) (Iterations: 32)

* Device #1: Skipping unstable hash-mode 3200 for this device.
             You can use --force to override, but do not report related errors.

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.Dev.#1.....:      624 H/s (79.90ms) @ Accel:512 Loops:128 Thr:1 Vec:2

Hashmode: 7500 - Kerberos 5 AS-REQ Pre-Auth etype 23

clEnqueueNDRangeKernel(): CL_INVALID_WORK_GROUP_SIZE ...
```

or ...

```
$ ./hashcat -m 2500 -D1,2 -b
hashcat (v4.1.0-7-gf6cfcbb) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz, 4096/16384 MB allocatable, 4MCU

Benchmark relevant options:
===========================
* --opencl-device-types=1,2
* --optimized-kernel-enable

Hashmode: 2500 - WPA/WPA2 (Iterations: 4096)

Speed.Dev.#1.....:     2806 H/s (90.93ms) @ Accel:1024 Loops:256 Thr:1 Vec:4

Started: Fri Apr 13 20:24:51 2018
Stopped: Fri Apr 13 20:24:57 2018
```

**Comment by DustyPaw** [comment]
Ah OK, OpenCL isn't supported on Macs with Intel HD Graphics 3000.
