### ISSUE TITLE
BUILD.md (Linux) contains inaccurate information

### ISSUE THREAD

**Issue by VOC-LINK** [hashcat/hashcat#422]
I mean lines from: "# Building hashcat for Linux and OSX" to: "Run "make" ".

Anyone tried to follow this? If so - of course it won't compile anything, spitting errors instead. What I did to have hashcat compiled, was moving the contents of "deps/OpenCL-Headers" into "/usr/include/CL". But IMHO compilation should be feasible without a need to switch to root user (and without doing any special research "what do I do" - just by following BUILD.md step-by-step).

**Comment by VOC-LINK** [comment]
One more thing: just compiled hashcat. When trying to use it, it istantly spits an error instead of doing its job:

"hashcat (v3.00-30-g450b779) starting...

ATTENTION! Can't find OpenCL ICD loader library

You're probably missing the "ocl-icd-libopencl1" package (Debian/Ubuntu)
  sudo apt-get install ocl-icd-libopencl1"

Of course I'm missing, since I've got no idea, what "OpenCL ICD loader library" actually is, neither why do I want it (I didn't need it before). Not a single word about this in BUILD.md, of course - it is assumed, that since I'm Linux user, therefore I'm familiar with every single one out of thousands various libraries available for Linux.

**Comment by ZbigniewB** [comment]
So I downloaded OCL library from Intel's site, copied the file libOpenCL.so.2.0 (along with two symlinks ibOpenCL.so, and ibOpenCL.so.1) into /usr/local/lib64/opencl - then "ldconfig" - hashcat startet finally its work, but terminated it with:

 Generating bitmap tables with 16 bits...

 ERROR: clGetPlatformIDs() : -1001 : CL_UNKNOWN_ERROR

Now what?

**Comment by VOC-LINK** [comment]
- numactl dependency not mentioned at all
- it could be worthy to explain, how to install "OpenCL ICD loader library" by hand, the most "generic" way, which will work everywhere (I use Slackware, not Debian/Ubuntu)

With a little help of "strace" finally I managed to make it work - it could be done much faster with proper, tidy docs.

**Comment by magnumripper** [comment]
Perhaps you could open a PR with suggested improvements? It'd put you in the hall of fame!

**Comment by jsteube** [comment]
@ZbigniewB Your points are incorrect, sorry. If you follow the BUILD.md 1:1 it will work. Install the missing ICD loader library is not part of hashcat. It's basic OpenCL stuff.
