### ISSUE TITLE
Salt-value exception with PDF hash

### ISSUE THREAD

**Issue by negrusti** [hashcat/hashcat#423]
Extracted hash from an encrypted PDF using pdf2hashcat.
Start of the hash:
$pdf$5_5_256_-1084_0_16_...
when loading that hash with arguments -a 3 -m 10600, hashcat exits immediately with:
Salt-value exception
Parsed Hashes: 1/1 (100.00%)

ERROR: No hashes loaded

**Comment by philsmd** [comment]
Without a complete example hashes it's difficult to say what the problem could be.

It's always recommended to look at the example hashes page and compare with the hashes of the same hash type: https://hashcat.net/wiki/example_hashes
Do you see any major difference?

Are you sure that there are no leading/trailing spaces ?

**Comment by negrusti** [comment]
Thanks for replying, I can send you the complete hash via email, can you send me yours to negrusti@gmail.com?

**Comment by philsmd** [comment]
Thanks for the offer to share your hash file such that we can investigate and maybe exclude/confirm any bugs/problems in hashcat.

Please use the contact info (mail) within the docs/changes.txt file for this: https://raw.githubusercontent.com/hashcat/hashcat/master/docs/contact.txt
