### ISSUE TITLE
Potfile being ignored / improperly read for WPA under some conditions

### ISSUE THREAD

**Issue by vom513** [hashcat/hashcat#424]
Running v3.00-30-g450b779

Steps to reproduce:
- Start with no hashcat.pot file present
- Crack WPA handshake 1 
- Confirm expected result is in potfile
- Try to re-crack 1
- Skipped - as already cracked in potfile
- Crack WPA handshake 2
- Confirm expected result is in potfile
- Try to re-crack 2
- 2 is not skipped, rather - cracking runs again
- Result from 2 is now in potfile twice

I will attach a file (sanitized) showing me running these steps.  I've named 1 ALICE and 2 BOB.

**Comment by vom513** [comment]
[hashcat-potfile-example.txt](https://github.com/hashcat/hashcat/files/353096/hashcat-potfile-example.txt)

**Comment by philsmd** [comment]
Thank you very much for the instruction. Indeed, I didn't previously test (after you mentioned it on a forum post) to crack 2 different .hccap file and test to crack a third time one of the hashes.

Seems to be fixed now.

Thanks again
(and as always, please test to confirm, thx)

See https://github.com/hashcat/hashcat/pull/426
(as of now, we still need to wait for a merge into master, will happen very soon!)

**Comment by vom513** [comment]
Yes, seems to (really) work as expected now - tested with v3.00-47-gbaea682.  I put my original oclHashcat.pot in place (~ 200k lines, multiple algos/hashes) and it did fine parsing that as well.

Thanks so much for looking at this so quickly.

**Comment by philsmd** [comment]
Great. Thanks for testing.

Don't forget to close this issue! thx
