### ISSUE TITLE
Can't build with MinGW anymore

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#425]
make win64 errors with

make: **\* No rule to make target '/usr/x86_64-w64-mingw32/lib/CRT_glob.o', needed by 'hashcat64.exe'.  Stop.

it does the same on both cygwin and fedora 24.

edit: the fix was to change CRT_GLOB_64 to /usr/x86_64-w64-mingw32/sys-root/mingw/lib/CRT_glob.o

**Comment by jsteube** [comment]
Yeah I was going to say you maybe just need to adjust the path. Problem is I don't know if it's possible to not use a path and let MinGW find the object itself.

**Comment by philsmd** [comment]
I think the correct path could be programmatically found (w/ the Makefile) like this:

linux - 32 bit cross-compilation:
`$ i686-w64-mingw32-ld --verbose | grep -m 1 SEARCH_DIR | sed 's/.*"\([^"]*\)".*/\1/'                                                                         
/usr/i686-w64-mingw32/lib`

linux - 64 bit cross-compilation:
`$ x86_64-w64-mingw32-ld --verbose | grep -m 1 SEARCH_DIR | sed 's/.*"\([^"]*\)".*/\1/'
/usr/x86_64-w64-mingw32/lib`

It should work the same way under mingw too, we need just someone to test this. @neheb, can you try this ? The "ld --verbose ..." command should output the correct lib path even under mingw @ windows

btw: the grep ... | sed ... could also be replaced by:
`grep -Po -m 1 'SEARCH_DIR\("\K.*?(?=")'`
but I'm not sure if mingw (and all other supported operating systems used to build from source) supports this

**Comment by neheb** [comment]
both commands return /usr/lib on fedora 24. not sure on cygwin. replacing the grep | sed commands with the last one results in:

=/usr/i686-w64-mingw32/lib
=/usr/local/lib
=/lib
=/usr/lib

and

=/usr/x86_64-w64-mingw32/lib
=/usr/local/lib
=/lib
=/usr/lib

respectively.

**Comment by philsmd** [comment]
Are you sure that you are trying with the correct "mingw32-ld" command (i686-w64-mingw32-ld or x86_64-w64-mingw32-ld) ?
Using a different ld version (e.g. not the mingw32 provided one), also gives me different results. But this is ofc to be expected. We are trying to get the correct path from mingw32-ld after all.

**Comment by neheb** [comment]
i am

**Comment by philsmd** [comment]
maybe something more flexible would be this:
`x86_64-w64-mingw32-ld --verbose | grep 'SEARCH_DIR(.*mingw' | head -n 1 | sed 
's/SEARCH_DIR("=\?//' | sed 's/".*//'`

can you try ?

**Comment by neheb** [comment]
/usr/x86_64-w64-mingw32/lib

**Comment by philsmd** [comment]
Thanks, that should be the correct path we are looking for.
This also should be identical to the more compact version:
`x86_64-w64-mingw32-ld --verbose | grep -m 1 'SEARCH_DIR(.*mingw' | sed 's/SEARCH_DIR("=\?\([^"]*\)".*/\1/'`

The most important thing now is: is this also working under cygwin (windows operating system) ?
Maybe someone is able to test this

**Comment by neheb** [comment]
same result with cygwin. path and behavior is the same as fedora 24.

**Comment by philsmd** [comment]
wait... shouldn't the output (the path) be:

`/usr/x86_64-w64-mingw32/sys-root/mingw/lib`

under cygwin?

So not even the mingw32-ld --verbose output contains the correct path ?

**Comment by neheb** [comment]
it does not, no.

**Comment by philsmd** [comment]
okay. Thanks for testing.

Next, I would suggest that (because the above ld mechanism didn't work) we need to apply a change similar to this one:

```
diff --git a/src/Makefile b/src/Makefile
index 4e4da2d..3ded550 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -63,6 +63,7 @@ FIND                     := find
 INSTALL                  := install
 RM                       := rm
 SED                      := sed
+EGREP                    := egrep
 ifeq ($(UNAME),Darwin)
 SED                      := gsed
 endif
@@ -178,8 +179,30 @@ LINUX_32_OBJS            := obj/ext_OpenCL.LINUX.32.o obj/shared.LINUX.32.o obj/
 LINUX_64_OBJS            := obj/ext_OpenCL.LINUX.64.o obj/shared.LINUX.64.o obj/rp_kernel_on_cpu.LINUX.64.o obj/ext_ADL.LINUX.64.o obj/ext_nvml.LINUX.64.o obj/ext_nvapi.LINUX.64.o obj/ext_xnvctrl.LINUX.64.o

 ## may need to adjust according to your mingw distribution
-CRT_GLOB_32              := /usr/i686-w64-mingw32/lib/CRT_glob.o
-CRT_GLOB_64              := /usr/x86_64-w64-mingw32/lib/CRT_glob.o
+CRT_GLOB_LIB_PATH_32     := /usr/i686-w64-mingw32/lib/
+CRT_GLOB_LIB_PATH_64     := /usr/x86_64-w64-mingw32/lib/
+
+CRT_GLOB_LIB_SYSROOT_32  := $(shell $(CC_WIN_32) --verbose 2>&1 | $(EGREP) -o '(with-sysroot="[^"]"|with-sysroot=[^ ]*)' | $(SED) 's/^with-sysroot="\?\([^"]*\)"\?$$/\1/')
+CRT_GLOB_LIB_SYSROOT_64  := $(shell $(CC_WIN_64) --verbose 2>&1 | $(EGREP) -o '(with-sysroot="[^"]"|with-sysroot=[^ ]*)' | $(SED) 's/^with-sysroot="\?\([^"]*\)"\?$$/\1/')
+
+ifneq (,$(CRT_GLOB_LIB_SYSROOT_32))
+CRT_GLOB_LIB_PATH_32     := $(CRT_GLOB_LIB_SYSROOT_32)
+endif
+
+ifneq (,$(CRT_GLOB_LIB_SYSROOT_64))
+CRT_GLOB_LIB_PATH_64     := $(CRT_GLOB_LIB_SYSROOT_64)
+endif
+
+CRT_GLOB_32 := $(shell $(FIND) "$(CRT_GLOB_LIB_PATH_32)" -name CRT_glob.o)
+CRT_GLOB_64 := $(shell $(FIND) "$(CRT_GLOB_LIB_PATH_64)" -name CRT_glob.o)
+
+ifeq (,$(CRT_GLOB_32))
+$(error "! The MinGW CRT GLOB library for 32-bit compilation was not found on your system. Please make sure that CRT_glob.o exists")
+endif
+
+ifeq (,$(CRT_GLOB_64))
+$(error "! The MinGW CRT GLOB library for 64-bit compilation was not found on your system. Please make sure that CRT_glob.o exists")
+endif

 WIN_32_OBJS              := obj/ext_OpenCL.WIN.32.o   obj/shared.WIN.32.o   obj/rp_kernel_on_cpu.WIN.32.o   obj/ext_ADL.WIN.32.o   obj/ext_nvml.WIN.32.o   obj/ext_nvapi.WIN.32.o   obj/ext_xnvctrl.WIN.32.o   $(CRT_GLOB_32)
 WIN_64_OBJS              := obj/ext_OpenCL.WIN.64.o   obj/shared.WIN.64.o   obj/rp_kernel_on_cpu.WIN.64.o   obj/ext_ADL.WIN.64.o   obj/ext_nvml.WIN.64.o   obj/ext_nvapi.WIN.64.o   obj/ext_xnvctrl.WIN.64.o   $(CRT_GLOB_64)
```

(the diff is attached to this post, you should be able to just run "git apply crt_glob_Makefile_diff.txt")

This makes sure, that if gcc was configured with a sys-root folder, that we respect this path and search for CRT_glob.o within this folder.

Could I kindly ask you (again, I know!) that you test this with both (all?) your systems (fedora and cygwin would of course be most important, but we should make sure that it continues to work with "different" systems that do not use sys-root via --with-sysroot).
Thanks
[crt_glob_Makefile_diff.txt](https://github.com/hashcat/hashcat/files/361796/crt_glob_Makefile_diff.txt)

**Comment by philsmd** [comment]
I did some further changes (shouldn't be significant to this testing but maybe important to stop "error messages" where not necessarily needed etc).
Please try with version 2 of the changes (attached):
[crt_glob_Makefile_diff_v2.txt](https://github.com/hashcat/hashcat/files/362134/crt_glob_Makefile_diff_v2.txt)

Update:
BTW: an alternative to the list of "IS_WIN_BUILD := 1" sections would be something like this:

```
MG := $(MAKECMDGOALS)

IS_WIN_BUILD := $(filter binaries,$(MG))$(filter win32,$(MG))$(filter win64,$(MG))$(filter hashcat32.exe,$(MG))$(filter hashcat64.exe,$(MG))

ifneq (,$(IS_WIN_BUILD))
...
endif
```

but this is just a matter of how we decide to write that specific make target list filter

**Comment by neheb** [comment]
worked.

**Comment by jsteube** [comment]
@philsmd Any news with the patch? All you need is to push it into an external file and include it from Makefile
