### ISSUE TITLE
OSX GeForce GT 750M - Not able to recover hashes

### ISSUE THREAD

**Issue by c3r63ru5** [hashcat/hashcat#428]
Hi,

I have two issues, I think one is already logged (crashes trap 6), the other is that one one of my graphics cards (GT 750M) hashcat won't recover known hashes (e.g. 1234), please see below.

./hashcat --opencl-device-types=2 --opencl-devices=3 --hash-type=1000 --attack-mode=3 test-hash.txt  ?a?a?a?a
hashcat (v3.00-30-g450b779) starting...
# OpenCL Platform #1: Apple               
- Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
- Device #2: Iris Pro, skipped
- Device #3: GeForce GT 750M, 512/2048 MB allocatable, 2MCU

Hashes: 31 hashes; 28 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Precompute-Init
- Precompute-Merkle-Demgard
- Meet-In-The-Middle
- Early-Skip
- Not-Salted
- Not-Iterated
- Single-Salt
- Brute-Force
- Raw-Hash
  INFO: approaching final keyspace, workload adjusted  

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?a?a?a?a) [4]
Hash.Target....: File (test-hash.txt)
Hash.Type......: NTLM
Time.Started...: 0 secs
Speed.Dev.#3...:  2284.7 MH/s (0.13ms)
Recovered......: 0/28 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 81450625/81450625 (100.00%)
Rejected.......: 0/81450625 (0.00%)

Started: Fri Jul  8 12:38:02 2016
Stopped: Fri Jul  8 12:38:04 2016 

./hashcat --opencl-device-types=2 --opencl-devices=2 --hash-type=1000 --attack-mode=3 test-hash.txt  ?a?a?a?a
hashcat (v3.00-30-g450b779) starting...
# OpenCL Platform #1: Apple               
- Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
- Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
- Device #3: GeForce GT 750M, skipped

Hashes: 31 hashes; 28 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
- Zero-Byte
- Precompute-Init
- Precompute-Merkle-Demgard
- Meet-In-The-Middle
- Early-Skip
- Not-Salted
- Not-Iterated
- Single-Salt
- Brute-Force
- Raw-Hash
  7ce21f17c0aee7fb9ceba532d0546ad6:1234  
  INFO: approaching final keyspace, workload adjusted  

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (?a?a?a?a) [4]
Hash.Target....: File (test-hash.txt)
Hash.Type......: NTLM
Time.Started...: 0 secs
Speed.Dev.#2...:   395.3 MH/s (11.33ms)
Recovered......: 1/28 (3.57%) Digests, 0/1 (0.00%) Salts
Progress.......: 81450625/81450625 (100.00%)
Rejected.......: 0/81450625 (0.00%)

Started: Fri Jul  8 12:38:13 2016
Stopped: Fri Jul  8 12:38:15 2016

**Comment by jsteube** [comment]
I remember someone reported the same problem with a GeForce device on Apple. There's no known workaround or fix. Also note that this is not a hashcat problem, it's a driver or runtime problem.

**Comment by migroves** [comment]
Installing Nvidia's alternative drivers of OS X fixed it for an iMac with a geforce 750M (- Device #2: GeForce GT 750M, 256/1024 MB allocatable, 2MCU)

The current version for El Capitan (10.11.6) can be found here:
http://www.nvidia.com/download/driverResults.aspx/105646/en-us

**Comment by philsmd** [comment]
@migroves do you think we should/could close this issue, because it is not in our hands to fix it? (only a new/better driver or fortunately the alternative driver helps here)

If so, please close the issue. Thanks
