### ISSUE TITLE
Hashcat OSX cannot execute binary file

### ISSUE THREAD

**Issue by komer83** [hashcat/hashcat#430]
OS 10.11.5, Xcode 7.3.1, Hashcat 3.0.0 

-bash: ./hashcat64.bin: cannot execute binary file

**Comment by jsteube** [comment]
https://www.phillips321.co.uk/2016/07/09/hashcat-on-os-x-getting-it-going/

Please close issue if it helps

**Comment by komer83** [comment]
ERROR: clEnqueueNDRangeKernel(): CL_INVALID_WORK_GROUP_SIZE

hashcat -D 1,2 -m xx -a 0 /Users/xxx/hashes.txt /xxx/rockyou.txt -outfile=unhashed.txt

**Comment by jsteube** [comment]
Double post: https://github.com/hashcat/hashcat/issues/416
