### ISSUE TITLE
support for sha1(md5($pass).$salt) hashes

### ISSUE THREAD

**Issue by Carlos7777** [hashcat/hashcat#431]
is it possible to add support for this algorithm:

sha1(md5($pass).$salt)

4780273b56d495904a225131211ea20c9dccc567:bEpY4bEr:13lucky
00f7f21a49313d75b36f451e11606e148106637d:rVzYynKa:047925
003e0b6c2d4f9b6e1d1adc650192679402c725a5:RJdPbqfz:901603
0054c29fff4efa9c4085fa71dfd29aec59cb8f24:u9Z.PVVW:890926
005bad6fe73622226e86780a40bd1926ffedbcfb:rMwA4KNU:250273
0092930759fba02263e1ad81ec2dda46c1bc99ca:nEjvYaGb:311205
47655fd371071d9a5c1c3c2030c6caa90fe96e14:n.=V4rY=:nirvana123

**Comment by Ins1ghtLabs** [comment]
+1

**Comment by forhuan** [comment]
+1

**Comment by jsteube** [comment]
Support added with PR https://github.com/hashcat/hashcat/pull/2129
