### ISSUE TITLE
fopen(): No such file or directory - Space in path fcks everything up

### ISSUE THREAD

**Issue by hshct** [hashcat/hashcat#432]
Hi,

Just wanted to report that having a space in the path leads to the following error, in case someone else experienced this, too:

```
Y:hash cat-3.00 -$ ./hashcat.app -b
hashcat () starting in benchmark-mode...

OpenCL Platform #1: Apple
=========================
- Device #1: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz, skipped
- Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU



ERROR: /Users/X/Downloads/hash\ cat-3.00/OpenCL/inc_cipher_aes256.cl: fopen(): No such file or directory
```

System: OSX 10.11.5
Version: hashcat 3.00

In case this is already known, sorry for wasting your time.

Have a nice day

**Comment by jsteube** [comment]
Should be fixed, thanks for report. Please reopen if it's not fixed.
