### ISSUE TITLE
Someone knows how to solve this problem?

### ISSUE THREAD

**Issue by ghroll** [hashcat/hashcat#436]
**$ hashcat -m 0 HASH.txt wordlist.txt**
hashcat (v3.00) starting...

Generating bitmap tables with 16 bits...

ERROR: clGetDeviceIDs() : -1 : CL_DEVICE_NOT_FOUND

$ **hashcat -b -m 0 -d1**
hashcat (v3.00) starting in benchmark-mode...

ERROR: clGetDeviceIDs() : -1 : CL_DEVICE_NOT_FOUND

Is not working.

**Comment by neheb** [comment]
that bug should be fixed in the latest beta: https://hashcat.net/beta/

**Comment by ghroll** [comment]
wine hashcat32.exe -b -m 0 
hashcat (v3.00-61-g2b7e36b) starting in benchmark-mode...

OpenCL Platform #1: Mesa, skipped! No OpenCL compatible devices found

ERROR: No devices found/left

**Comment by neheb** [comment]
sounds like you need an opencl runtime then. supported ones by hashcat are:

If nvidia, the drivers should include it.
if intel, beignet is probably your best bet.

**Comment by ghroll** [comment]
Here is intel
I do not use gpu
It only works with gpu this new version of hashcat?
If so I'm lost ....

I dont use video card :(

**Comment by neheb** [comment]
You can try installing the Intel OpenCL runtime but that's a mess to do on Linux. Another alternative is pocl.

**Comment by ghroll** [comment]
I saw it really is one terrible installation ...
I'm going back to an earlier version of hashcat.
I received a new update on linux kali and I am with this problem.
I will try to find an easier way to solve it :/
Thank you for answering!

**Comment by dmknght** [comment]
Hi everyone! I am using core i3 3110M, parrot os 4.9. My hashcat is having clGetDeviceIDs(): CL_DEVICE_NOT_FOUND error. But i made it work by adding --force option.
I used `hashcat -m 0 hash temp/rockyou.txt --force`, hash is the file stored my testing md5 hash.

**Comment by gripedthumbtacks** [comment]
If you run nvidia driver:

$ sudo apt remove mesa-opencl-icd
$ sudo apt install nvidia-opencl-icd
