### ISSUE TITLE
Unexplainable mask issues

### ISSUE THREAD

**Issue by noaht8um** [hashcat/hashcat#439]
I am trying to use attack method 7 (Hybrid Mask + Wordlist) and get strange results.
If I use an eight character mask (?l?l?l?d?d?d?d?d) it tells me about 2 hr. to crack, but if I add a "?d" to that, the time goes _down_ to 15 minutes. I don't understand why it would take longer to crack something with less characters. I am running the latest compiled version.

Session.Name...: hashcat
Status.........: Running
Input.Left.....: Mask **(?l?l?l?d?d?d?d?d) [8]**
Input.Right....: File (/Users/username/Desktop/folder/file1.txt)
Hash.Target....: File (/Users/username/Desktop/folder/hashes.txt)
Hash.Type......: NTLM
Time.Started...: Wed Jul 20 18:44:41 2016 (2 secs)
Time.Estimated.: Wed Jul 20 20:37:33 2016 (1 hour, 52 mins)
Speed.Dev.#2...:   496.6 MH/s (0.15ms)
Recovered......: 1207/3543 (34.07%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 1467152394/3362288800000 (0.04%)
Rejected.......: 0/1467152394 (0.00%)
Restore.Point..: 0/1913 (0.00%)

Session.Name...: hashcat
Status.........: Aborted
Input.Left.....: Mask **(?l?l?l?d?d?d?d?d?d) [9]**
Input.Right....: File (/Users/username/Desktop/folder/file1.txt)
Hash.Target....: File (/Users/username/Desktop/folder/hashes.txt)
Hash.Type......: NTLM
Time.Started...: Wed Jul 20 18:45:02 2016 (4 secs)
Time.Estimated.: Wed Jul 20 19:00:04 2016 (14 mins, 57 secs)
Speed.Dev.#2...:   840.6 MH/s (0.50ms)
Recovered......: 1207/3543 (34.07%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:N/A,N/A,N/A AVG:0.00,0.00,0.00 (Min,Hour,Day)
Progress.......: 3652412467/757798251008 (0.48%)
Rejected.......: 0/3652412467 (0.00%)
Restore.Point..: 0/1913 (0.00%)

**Comment by jsteube** [comment]
That's an integer overflow. A known issue since the total Keyspace (you can see it in the progress column in status view) is limited to 64 bit. however, it's nothing i'm going to fix soon because you can't search through such a range anyway, which is the reason why it is how it is.

**Comment by magnumripper** [comment]
Why would you not be able to exhaust `?l?l?l?d?d?d?d?d?d`? That's a tiny keyspace for NTLM.
