### ISSUE TITLE
-m 3800 to support salts of up to 40 characters

### ISSUE THREAD

**Issue by v-user** [hashcat/hashcat#442]
Hi,

Is it possible to raise the salt length limit to 40 characters on this algorithm?

Lately I've been working on the hashes.org left lists and it seems that a lot of md5 hashes are lacking the salt which is either a MD5 or a SHA1 hash randomly generated. Probably someone posted the hashes without/ignoring the salts.

As far I could search around this hashing technique is used on TBDev but maybe there are other sources.

Here are a few examples cracked by HashManager:
2795594cf113b4f3fac5f465f760de5b:f3a4a9779b7282b14327864dd2bca93ff7b61367:2221167
d9962a186627d78bfb975772f8fe7409:b76bd40b9fdb9edcdf7eba41e15eff4d18e9cbc0:1850712
ba3fad0bbefe7ccbcc5fd60d9adc2ff7:828fdfe4a23de9a0a739347c50d4311e4a48efd5:trailang
5a9961e5d70421bdaddb7c76c7bd82e4:f5d9fcb77abd31d0ea13f0fb878f36c2146c24dd:amcccp1

Regards

**Comment by jsteube** [comment]
This issue makes no sense. If you don't know the salt, you can't crack it, whatever hashcat supports salt length 40 or not. Please re-explain

**Comment by jsteube** [comment]
Continue here: https://github.com/hashcat/hashcat/issues/565
