### ISSUE TITLE
Mac OSX not supported anymore?

### ISSUE THREAD

**Issue by idontlie** [hashcat/hashcat#444]
Your site mentions OSX compatibility, yet there is no .app file. Am I trying to run this wrong? Did I download the wrong file? All the current tutorials on the internet require the hashcat app file.

**Comment by philsmd** [comment]
This seems to be a duplicate of these (closed) issues: #403, #430 

Please don't forget to close this issue
Thank you very much

**Comment by idontlie** [comment]
Ok, thanks. But since this seems to be a common issue, it would be nice if  someone made a wiki article tutorial thing about it.
