### ISSUE TITLE
Add costume mode/hash ?

### ISSUE THREAD

**Issue by vdun** [hashcat/hashcat#447]
How to add a costume hash/mode ?

**Comment by philsmd** [comment]
Do you mean a custom hashing algorithm?

Well, there is no documentation yet to guide you to all of the steps you need to do, but it should be quite easy to add a new custom algorithm if you have a glance at the most recently commits of "new algorithms".

For instance, atom even mentioned here https://github.com/hashcat/hashcat/issues/68#issuecomment-170273665 that this is kind of a "guide", expressed by a new hash-mode commit (these few lines of code should tell you more than thousands of lines of documentation, if you are into coding).

**Comment by vdun** [comment]
Thanks, this is what I meant.
Sometimes one does not know in details the implementation of the hash algorithm (e.g. closed source program). So would it be possible to add a new feature by making it more generic by letting hashcat call a target program (with the clear text) and comparing the output if it is correct or not ?

**Comment by jsteube** [comment]
This is not about a new hash mode, it's mode like a new program. That's not how cracking is done. If the programm is closed source you have to reverse engineer the algorithm. You can't have a tool to do that automatically because there's an unlimited number of possibilities.

**Comment by vdun** [comment]
This could be done by making a new mode/API for target programs.
Example:
- input for target is: buf as byte[](clear text), len as INT (length of buf)
- If the target program returns 1=Good, -1=Bad, ...
  And it is up to the reverser to make a wrapper around to make it comply with the API.

**Comment by bledari** [comment]
I'm dealing with a MD5 + DES encryption, seems this issue would be the solution. Any suggestions on how I can use hashcat on my scenario?
