### ISSUE TITLE
Network cluster ?

### ISSUE THREAD

**Issue by vdun** [hashcat/hashcat#448]
Say I have multiple machines on the network all having hashcat and I have ssh access. How could I distribute the tasks on them ?

**Comment by gituser** [comment]
there are multiple solutions to your problem

you can use https://bitbucket.org/seinlc/hashtopussy

**Comment by epixoip** [comment]
This is not a bug report or a feature request, so this type of question belongs on the forums not on Github. Please close this issue.

**Comment by vdun** [comment]
Thanks
