### ISSUE TITLE
Add custom charset info field

### ISSUE THREAD

**Issue by aress31** [hashcat/hashcat#449]
Hi,
I would like to know if it would be possible to add new information fields when using custom char-set.
Let's say that I am using `-1 ?l?u` and `-2 ?s?d` sometimes I process really long hash-files (thousands of entries and it can take up to a week). I like to display the status of the session multiple times and therefore in the terminal history to go back to the command line to remember my mask I have to scroll up a lot. Consequently, if it could be an extra information field I would welcome it. In addition, it would avoid irrelevant question such as #427 for people using `-a 3` mode without specifying any mask.
Please let me know what you think of this idea.
Kind regards,
Alex

**Comment by ghost** [comment]
If I understand this correctly you are looking for something like:

>  Session.Name...: hashcat
> Status.........: Aborted
> Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
> Custom.Char..: -1 ?l?u -2 ?s?d
> Hash.Target....: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> Hash.Type......: MD5

**Comment by aress31** [comment]
Exactly!

**Comment by ghost** [comment]
This is already output in the log file:

> TOP81ca1880   custom_charset_1    ?l?u
> TOP81ca1880 custom_charset_2    ?s?d

I suppose I could see a use case but to me it seems like clutter in output.

**Comment by aress31** [comment]
I personally think that it might be a "good" extra information to print out. It is up to you at the end. :)

**Comment by ghost** [comment]
I added it with that PR.  Feel free to build and try for yourself until it's merged.

**Comment by aress31** [comment]
Thanks :)

**Comment by jsteube** [comment]
beta is up here: http://hashcat.net/beta/
