### ISSUE TITLE
Better use of the hashpot?

### ISSUE THREAD

**Issue by aress31** [hashcat/hashcat#450]
Hi,
Could it be possible to automatically use the hashpot as a wordlist. One of the first thing hashcat does is parsing the hashpot to find already cracked hashes. However when using rules, the rules are not applied to passwords containing in the hashpot. I suggest that instead of simply parsing the hashpot we should use the haspot as an "built-in wordlist" which will be processed first for wordlist attacks.
Real life scenario, we dump the Active Directory hashes there are few thousand hashes using our wordlist we are able to crack 20% of the hashes, most of time employees use the company names in their password or use at least similar schema (enforced password policy) therefore when using a set of rules on the already cracked hashes we might be able to obtain some more. At the current state of hashcat (I am just guessing I am not sure about how it works under the hood) when using rules attacks the rules are applied only on the inputted wordlist and not the hashcat and one of the good point of the hashcat is that the more hashes you have cracked, the bigger the hashpot is, the better it is.
Let me know what you think of this idea.
Kind regards,
Alex

**Comment by ghost** [comment]
It is better that this is done manually or you potentially have a bunch of duplicates being processed.
