### ISSUE TITLE
Temperature retain trigger not working

### ISSUE THREAD

**Issue by KevinMeinon** [hashcat/hashcat#454]
Hey guys. So when I use hashcat for MD5 or MD4 etc, the retainer works as supposed to and my GPU does not go above 75°. When I want to crack WPA2 howerver, using a 15GB wordlist, my GPU will go above 75° up to 90° and hashcat will stop. I tried using the minimum workload setting, which did nothing. I also tried setting the retain trigger to 65°, which did nothing either. Any tipps? 

Specs: 

Windows 10 Pro x64
CPU: Intel Core i5 4670k @ 4.5GHz
RAM: G.Skill TridentX 16GB, DDR3-2400
GPU: MSI Radeon R9 390
Motherboard: ASrock Fatal1ty z87 Killer
PSU: EVGA 650 GQ

**Comment by dropdeadfu** [comment]
Try to watch your clock speeds, maybe they can give a clue why that happens.

**Comment by jsteube** [comment]
There's no relation between the hashmode and the retain algorithm. It's more likely that your fans are unable to cool down the device fast enough, like the trigger starts at 75c and starts the fans but when the watchdog checks the temp its already 90c. 

IWO, This sounds like a cooling issue on user side. Please reopen the ticket if you're sure it's a bug
