### ISSUE TITLE
Support for SHA 224

### ISSUE THREAD

**Issue by TheAifam5** [hashcat/hashcat#455]
There is a lot of algorithms inside this beauty, except one what i need :P
SHA 224 :(

**Comment by jsteube** [comment]
I could add this, but please answer the following questions first: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this

**Comment by matrix** [comment]
@TheAifam5 you need also with salt?

**Comment by jsteube** [comment]
Thanks @matrix for adding
