### ISSUE TITLE
Display Warning or Error when using --skip together with a .hcmask file

### ISSUE THREAD

**Issue by franky436** [hashcat/hashcat#457]
When using --skip together with a (multi-line) .hcmask file, hashcat printed this error:

"ERROR: Restore value greater keyspace"

which is quite irritating/misleading. Possibly happens only if skip is higher than the keyspace of the first mask in the .hcmask file, haven't checked sources for that yet.

Suggestion: check if --skip was used together with a .hcmask file and print a warning/error that this combination is not supported.

**Comment by jsteube** [comment]
Yes, that check sounds useful
