### ISSUE TITLE
[feature request] ability to encrypt/decrypt files via GPU

### ISSUE THREAD

**Issue by alexivanou** [hashcat/hashcat#458]
Hi, All!
Yesterday I found the problem: there are no actual programs to encrypt/decript files in linux using GPU instead of CPU. There are some articles describing GPU cryptographic theory. There is CUDA AES extension which work 20-30% faster than CPU in AES encoding. There is no program on Radeon GPU for AES.
Hashcat use AES algorithms in cracking encoded data. So, maybe it is not so difficult to add function to crypt files with AES?

**Comment by philsmd** [comment]
I think this is totally not within the scope of what hashcat is intended to do.
After all, hashcat is an "advanced password recovery" tool (as you can read on hashcat's website/github README etc etc).

What you instead think hashcat should do (in the future) by encrypting/decrypting whole files etc has nothing to do with passwords, nor with hashes. Also, encryption is of course not the same as hashing. As you may know, hashcat focuses on recovering passwords by starting with a password hash (yeah, sometimes the hashing algorithm also has some encryption steps, also sometimes involving AES, but that are most of the times special cases of "key derivation" starting from passwords etc).

I don't think that we should support something like this within hashcat.
A different tool that maybe does not exist already (I didn't check it in detail) may be available in the future (I don't know, at least I can't exclude it at all). At least it isn't totally impossible. But it probably won't be called "hashcat" or a "password recovery tool".

You also need to consider that it's not the same procedure of hashing a few bytes compared to encrypting dozens or hundreds (or even thousands?) of megabytes. There might be other challenges that needs to be addressed, like transfer time bottlenecks etc  (if you transfer more bytes in both directions, to and away from your GPU, there could be some (speed) problems involved etc).

I don't think something like this should be implemented in hashcat.

**Comment by jsteube** [comment]
I agree with @philsmd
