### ISSUE TITLE
Feature Request: Loopback feed from POT file

### ISSUE THREAD

**Issue by mubix** [hashcat/hashcat#466]
During testing it doesn't look like the "previously cracked" load of the POT file doesn't get factored in for the loopback feature. Would be nice if this was the case because lots of potential could easily be gained from previously found hashes having rules applied to them.

**Comment by roycewilliams** [comment]
Culturally, I suspect that it's left up to user to determine when to feed the entire backlog of discovered plains into an attack. 

That being said, some kind of "pre-loopback" option might be convenient, IMO.

**Comment by jsteube** [comment]
Note sure if I get this right. So the idea is it to use the potfile as previous wordlist input before running the actual wordlist? What if the user doesn't do wordlist attack, but hybrid-attack?

**Comment by mubix** [comment]
The point would be to make sure any "known" plaintext would not have to be cracked, even if it's from a different hash type

**Comment by jsteube** [comment]
So check the potfile words only in case --loopback is used?

**Comment by jsteube** [comment]
@mubix Also, this would work only for rule-based attacks, not BF

**Comment by jsteube** [comment]
@mubix OK, pushed this: https://github.com/hashcat/hashcat/commit/1f756bf752f1fae16f50be57eb75d22c97639e6a

Please try

**Comment by jsteube** [comment]
This feature went into hashcat v3.30, therefore closing the issue. If it's not working, please open up a new one.
