### ISSUE TITLE
missing source tarball signature for release v3.10

### ISSUE THREAD

**Issue by anthraxx** [hashcat/hashcat#470]
Hi,

During updating hashcat to v3.10 to publish it for the distro I have noticed that it was failing duo to missing source tarball signatures on the homepage:
https://hashcat.net/files/v3.10.tar.gz.asc

They are linked here:
https://hashcat.net/hashcat/

The binary tarball has a signature, just the source tarball does not provide any. This currently prevents me from rolling out the update.

cheers,
Levente

**Comment by philsmd** [comment]
I think we need to fix the URL, it should be this one https://hashcat.net/files/hashcat-3.10.tar.gz.asc

**Comment by jsteube** [comment]
This should be fixed, but note that to fix this, I had to move the source tarball to hashcat.net because GitHub didn't let me choose the download filename manually.

**Comment by anthraxx** [comment]
Consistency is nice but primarily my goal was to be able to get the signature file... where the other files are coming from did not really matter... thats the good part of a trusted signature, the source could be anywhere (like a dropbox :smile: )
thanks a lot for clarification and fixing, works. Packaging it for my distro now :smile_cat:
