### ISSUE TITLE
Abort session after NUM seconds of runtime - changes required?

### ISSUE THREAD

**Issue by d2-d2** [hashcat/hashcat#472]
Hi,

Currently, with **runtime** parameter hashcat is working for X seconds. But if you press pause in the meantime, the counter do not stop. When you unpause hashcat and time is up then hashcat will terminate session.

I'm wondering if that should be changed. Talked with atom about it and here are two propositions:
1. runtime=X describes for how long hashcat will work, regardles if you hit pause or not (timer stops when hashcat is paused, if you unpause it it will continue to run for X remaining seconds)
2. runtime=X sets a general timer, when time is up, hashcat will be terminated not matter if it's paused or not

What do you people think? Which option would be better? Or maybe this initial behaviour shouldn't be changed at all?

**Comment by roycewilliams** [comment]
1. I think that most users would expect pausing to trump (take priority over) the timer. That's what I would expect, anyway. :)

**Comment by dropdeadfu** [comment]
1 - pause should also pause the timer

**Comment by magnumripper** [comment]
I agree, 1. is what I would expect

**Comment by jsteube** [comment]
All right, will do :)

**Comment by jsteube** [comment]
Done
