### ISSUE TITLE
Potential 32-bit MinGW issue

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#473]
running "make win32" with the added -Wundef compiler warning results in the following output: 

src/ext_nvapi.c: In function 'nvapi_init':
src/ext_nvapi.c:17:7: warning: "**x86_64**" is not defined [-Wundef]
   #if **x86_64**
       ^~~~~~~~~~
src/ext_nvapi.c:19:9: warning: "**x86**" is not defined [-Wundef]
   #elif **x86**
         ^~~~~~~

That is quite bizarre as the function deals with which DLL to load under Windows.

Running on Fedora 24 with MinGW 6.1

**Comment by neheb** [comment]
Just tested on Windows. Loading the library fails.

**Comment by jsteube** [comment]
Thanks for the fixes. Please do not forget to add your fixes to the docs/changes.txt
