### ISSUE TITLE
Generic KDF mode 10900 Signature unmatched

### ISSUE THREAD

**Issue by XeniaGabriela** [hashcat/hashcat#477]
Dear hashcat-team,

I do not have much experience with hashcat, but I wanted to test the cracking of a PBKDF2_SHA256 (0394a2ede332c9a13eb82e9b24631604c31df978b4e2f0fbd2c549944f9d79a5 in the file pbkdf2.txt). 
 I ran the command 'hashcat -a 0 -m 10900 pbkdf2.txt C:\hashcat\wordlists
As result I got the Warning: Signature unmatched.

My hexstring has the length 64 (32 bytes), as far as I know that is right. 
Can you outline my mistake?
Is there a way to specify salt and rounds in this mode?

Regards,

Xenia

**Comment by jsteube** [comment]
GitHub is for bugreports and feature requests or anything development related. Please use the hashcat forum for user questions.
