### ISSUE TITLE
WARNING: Hash 'hash.txt': Line-length exception

### ISSUE THREAD

**Issue by zer0sec** [hashcat/hashcat#478]
I've looked at every post and tried everything but still i get this stupid error
WARNING: Hash 'hash.txt': Line-length exception
in the hash.txt is 
5617fa68af265a7c7cc7ae00d5ae5982:luw
8ce4a2ac80288eb393b56b813abcbe8e:5Po
584ee6d41f7955349f911a369def4e21:>Hp

they are vbulletin which is -m 2711 

so i run like hashcat64.exe -a 0 -m 2711 hash.txt wordlists/super.txt

i tried lots of other command lines but still i get WARNING: Hash 'hash.txt': Line-length exception
in the hash.txt is 
im using windows 10

**Comment by jsteube** [comment]
GitHub is for bugreports and feature requests or anything development related. Please use the hashcat forum for user questions.
