### ISSUE TITLE
No empty LM hash with -a 3 -m 3000 possible

### ISSUE THREAD

**Issue by mame82** [hashcat/hashcat#483]
Using hascat64.bin Version 3.10 in attack mode 3 with --increment option enabled empty hashes don't geht recognized for LM (hashmode 3000).
This has to be solved manually by switching to straight attack and hitting enter to produce an empty hash, as --weak-hash-threshold doesn't work in attack mode 3 and an empty mask couldn't be used.

Without this manual fix passwords with length < 8 will never get cracked

**Comment by jsteube** [comment]
Double post, please see https://github.com/hashcat/hashcat/issues/434
