### ISSUE TITLE
Hash mode 110 doesn't appear to process salt values in some cases when bruteforcing

### ISSUE THREAD

**Issue by ZakDanger** [hashcat/hashcat#487]
I may be misunderstanding the code it appears that the salt values are not being processed in some cases for hash mode 110 in bruteforce attack mode.

If you look at opencl function m00110s() from file m00110_a3.cl it doesn't appear to process the salt values passed in.
When you compare it to the function m00110m() in the same file you can see that m00110m() does process the salt values passed in.

If this is an error then it may also exist in other files, I just happened to be looking at this file in particular.

**Comment by jsteube** [comment]
All fine here, the salt is embedded into the mask as part of an optimization process.
