### ISSUE TITLE
Minimal workload for restore point update

### ISSUE THREAD

**Issue by koallen** [hashcat/hashcat#491]
Hi, I'm trying to use the --restore feature in hashcat. I'm doing a dictionary attach and I only have ~470000 words in my dictionary. I tried to use `./hashcat64.bin --restore`, but it seems that it restarts from 0 every time.

Then I read from somewhere that it only restores from the restore point. And obviously my restore point is kept at 0 during the run. Therefore, I'm wondering that is the minimal workload that triggers an update to the restore point?

Is hashcat restarting from 0 everytime I restore because of this?

**Comment by jsteube** [comment]
Of course not, that wouldn't make sense at all then. It depends on serveral factors, but the most important it the number of amplifier (for example rules). Note that a good attack uses large wordlists and a small number of rules, not the opposite. You can also use --stdout feature to pregenerate a large base and pipe it back into hashcat. Anyway, GitHub issues are for feature request and bug reports. For general hashcat use please use the hashcat forum.
