### ISSUE TITLE
Does anyone know how to solve this new problem?

### ISSUE THREAD

**Issue by ghroll** [hashcat/hashcat#494]
**hashcat -m 0 hash.txt wordlist.txt**
hashcat (v3.10) starting...

OpenCL Platform #1: Mesa, skipped! No OpenCL compatible devices found

ERROR: No devices found/left

**Since hashcat has been updated to version 3.0 I can not use it!**

My system is 32-bit

**Comment by neheb** [comment]
Issue is that you need an OpenCL runtime.

**Comment by ghroll** [comment]
@neheb 
I have installed this shit
How can I solve this problem ?
The hashcat developer did not leave another alternative for users ... at least an earlier version.
He only knows close the issues .

Thank you for answering ;)

**Comment by neheb** [comment]
My answer was accurate and concise. A simple Google search should suffice.

**Comment by roycewilliams** [comment]
Same issue as  two months ago. See https://github.com/hashcat/hashcat/issues/436 .
