### ISSUE TITLE
memory leak hashcat (v3.10-110-g376e12e) -m 2500

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#498]
Memory leak in last commit. Valgrind says:
==20925== Warning: set address range perms: large range [0x395d8028, 0x499d8058) (noaccess)
==20925== Invalid read of size 4
==20925==    at 0x52BCB64: fclose@@GLIBC_2.2.5 (in /usr/lib/libc-2.24.so)
==20925==    by 0x408942: ??? (in /usr/bin/hashcat)
==20925==    by 0x5276290: (below main) (in /usr/lib/libc-2.24.so)
==20925==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==20925== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==20925==  Access not within mapped region at address 0x0
==20925==    at 0x52BCB64: fclose@@GLIBC_2.2.5 (in /usr/lib/libc-2.24.so)
==20925==    by 0x408942: ??? (in /usr/bin/hashcat)
==20925==    by 0x5276290: (below main) (in /usr/lib/libc-2.24.so)
==20925==  The main thread stack size used in this run was 8388608.
==20925== 
==20925== HEAP SUMMARY:
==20925==     in use at exit: 604,644,657 bytes in 1,332 blocks
==20925==   total heap usage: 133,290 allocs, 131,958 frees, 1,499,323,219 bytes allocated
==20925== 
==20925== LEAK SUMMARY:
==20925==    definitely lost: 360 bytes in 2 blocks
==20925==    indirectly lost: 0 bytes in 0 blocks
==20925==      possibly lost: 144,860 bytes in 612 blocks
==20925==    still reachable: 604,499,437 bytes in 718 blocks
==20925==                       of which reachable via heuristic:
==20925==                         stdstring          : 196 bytes in 6 blocks
==20925==         suppressed: 0 bytes in 0 blocks
==20925== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Last Version - hashcat (v3.10-109-gac77ee5) - works fine.
Best regards
ZerBea

**Comment by jsteube** [comment]
I've pushed something, please check if it's fixed now and close the issue if fixed

**Comment by ZerBea** [comment]
works like a charm - good job.....
issue closed
regards
ZerBea
