### ISSUE TITLE
hashcat benchmark on windows 10 results in fopen() error

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#499]
I've just downloaded the hashcat binary and tried to run the benchmark which results in an error:

ERROR: inc_cipher_256aes.cl: fopen(): No such file or directory

The file it speaks of is in the same directory as the binary and I get the same error using both 64 and 32-bit versions. It also results in the same error if I run the example0 with a known hash file.

**Comment by dropdeadfu** [comment]
Which version did you download? The beta? On which OS are you?

**Comment by dropdeadfu** [comment]
Nevermind the OS question i've just seen the subject.

**Comment by ghost** [comment]
I downloaded v3.10

**Comment by dropdeadfu** [comment]
Ok, then there seems to be something wrong with your settings. My guess
would be that there is something strange with the UAC or something similar.
Did you make sure the user you are starting it with also has read and write
permissions on the directory? Did you try running the cmd-box as admin?

**Comment by ghost** [comment]
I've just tried it and I get the same error.

**Comment by dropdeadfu** [comment]
Is that all you get when you start the benchmark or do you at least get the
other results leading up to it?

**Comment by ghost** [comment]
I also get the following output:

hashcat (v3.10) starting in benchmark-mode...

# OpenCL Platform #1: Intel(R) Corporation
- Device #1:       Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz, skipped
- Device #2: Intel(R) HD Graphics, 343/1374 MB allocatable, 4MCU

**Comment by dropdeadfu** [comment]
Make a copy of the complete console you are trying this in, put it on
pastebin and send the link to the paste.

**Comment by ghost** [comment]
http://pastebin.com/HTit03Vd

**Comment by neheb** [comment]
I remember a similar issue involving spaces in paths.

**Comment by dropdeadfu** [comment]
I need to see the complete console, including everything you did before
starting hashcat

**Comment by ghost** [comment]
@neheb I've already moved the folder and all of it's contents to the root of my C drive and I still get the same error.

@dropdeadfu I typed in hashcat64 -b. I have a PATH environment variable set to: C:\Program Files\hashcat

**Comment by neheb** [comment]
I just realized. You posted on GitHub but made no indication that you were using the beta. Try https://hashcat.net/beta

**Comment by jsteube** [comment]
Lots of stuff changed since this last test. Can you please retry with latest version from github?

**Comment by jsteube** [comment]
@fsociety79 any update?

**Comment by jsteube** [comment]
OP not responding for months and too old version. Closing.
