### ISSUE TITLE
hashcat m -2500 fails on passwords length > 32 chars

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#500]
hashcat (v3.10-115-g7e6f3ef) fails on passwords  length > 32 chars
Driver: NVIDIA 370.28 
did several tests with manually generated hccap's:
8 .. 32 everything's fine
greater 32 Exhausted
Rejected 0/5   well, all passwords accepted, but ignored during calculation of pmk

testwordlist (ascii - not utf8) contains:
1234567890123456789012345678901234
123456789012345678901234567890123
12345678901234567890123456789012
1234567890123456789012345678901
123456789012345678901234567890

tested some older versions, too:
hashcat-git-r1343.176fcb5
hashcat-git-r1346.b8e47c2
hashcat-git-r1347.3ed4bfd
hashcat-git-r1400.ac77ee5
same regressions appeared!

Best regards
ZerBea

**Comment by jsteube** [comment]
Works fine for me

```
root@ht:~/hashcat# ./hashcat -m 2500 x.hccap -a 3 123456789012345678901234567890123
hashcat (v3.10-118-gbc75ba7) starting...

OpenCL Platform #1: NVIDIA Corporation  
======================================
- Device #1: GeForce GTX 750 Ti, 499/1998 MB allocatable, 5MCU

OpenCL Platform #2: The pocl project
====================================
- Device #2: pthread-AMD FX(tm)-8120 Eight-Core Processor, skipped

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

ATTENTION!                                                
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       

6454331:1c18d4ca52a7:62b9bdade67b:123456789012345678901234567890123

Session.Name...: hashcat
Status.........: Cracked
Input.Mode.....: Mask (123456789012345678901234567890123) [33]
Hash.Target....: 6454331 (1c:18:d4:ca:52:a7 <-> 62:b9:bd:ad:e6:7b)
Hash.Type......: WPA/WPA2
Time.Started...: 0 secs
Speed.Dev.#1...:        0 H/s (0.43ms)
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 1/1 (100.00%)
Rejected.......: 0/1 (0.00%)

Started: Wed Sep 14 17:06:42 2016
Stopped: Wed Sep 14 17:06:45 2016 
```

Also works with -D 2 (CPU).

I guess your hccap was somehow generated wrongly.

**Comment by jsteube** [comment]
I also pushed a small patch in case you were using a wordlist:
- Allow words of length > 32 in wordlists for -a 0 for slow hashes if no rules are in use or a ":" rule is in the rulefile

Please close the issue if that's ok

**Comment by ZerBea** [comment]
Hi Jens.
All generated hccap are ok. Running a mask attack the password was found on each generated hccap,
but running a dictionary attack using a wordlist hashcat fails if the word is greater than 32 chars:

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-format=3 --outfile-autohex-disable test.hccap testlist

I think it's o problem of parsing the wordlist.

**Comment by ZerBea** [comment]
I'll try.....

**Comment by ZerBea** [comment]
Well, patch worked like a charm on dictionary attack if words > 32 chars.
Best regards
ZerBea
