### ISSUE TITLE
can`t run, my GPU Skip

### ISSUE THREAD

**Issue by clfdhq** [hashcat/hashcat#501]
- Device #1:        Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz, skipped
- Device #2: Intel(R) HD Graphics 4000, 324/1297 MB allocatable, 16MCU
  
  Device #3: GeForce GT 620M, 512/2048 MB allocatable, 2MCU
  Device #3: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code 702
            See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch
  
  Device #2: Kernel m02500.3d391022.kernel not found in cache! Building may take a while...
  Device #2: Kernel markov_le.3d391022.kernel not found in cache! Building may take a while...
  
  Device #2: Kernel amp_a3.3d391022.kernel not found in cache! Building may take a while...
  
  Device #3: Kernel m02500.18d8b4cc.kernel not found in cache! Building may take a while...
  Device #3: Kernel markov_le.18d8b4cc.kernel not found in cache! Building may take a while...
  
  Device #3: Kernel amp_a3.18d8b4cc.kernel not found in cache! Building may take a while...

Thanks

**Comment by dropdeadfu** [comment]
clinfo output please

**Comment by clfdhq** [comment]
close it topic, it working, thanks

**Comment by hartattack0** [comment]
clfdhq how did you fix this issue?

**Comment by clfdhq** [comment]
i don`t know, i try more time, it run, but it can`t decryption
