### ISSUE TITLE
hashcat return code always 255

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#512]
After Update from hashcat-git-r1485.a628cd3 to hashcat-git-r1530.62b97a6 I noticed that hashcat's return code is always 255 (Exhausted, Cracked, Aborted)
Scripts won't work anymore.
Best regards
ZerBea

**Comment by jsteube** [comment]
Please close if fixed

**Comment by ZerBea** [comment]
Fixed:
0 = Cracked
1 = Exhausted
2 = Aborted
