### ISSUE TITLE
Cant decrypt longsalt

### ISSUE THREAD

**Issue by botkosgap** [hashcat/hashcat#513]
i have hash : salt ( LongSalt)
and hashcat cant decrypt due to longSalt
u can fix?
egb/hm work
md5($salt.md5($pass))
For example
hash:14c7790bfa2733ab9550601d21712319
Salt:6ab03a8fb0ee2f0442789941f82b74543d680f6b
Password:1220da

**Comment by jsteube** [comment]
When is it really long enough? 50 or 500 or 500000? @magnumripper what's the maximum in JtR?

**Comment by magnumripper** [comment]
JtR core supports arbitrarily long salts but most optimized formats has a fairly tight limit just like Hashcat, to keep things in one or two Merkel Damgard blocks.

This particular format is supported in JtR as dynamic_2009 (only CPU) with salt lengths up to 200 (same format with max. 23 bytes salt is dynamic_9 and it's obviously faster).

**Comment by jsteube** [comment]
Continue here: https://github.com/hashcat/hashcat/issues/565
