### ISSUE TITLE
Support for TAB delimited hashfiles.

### ISSUE THREAD

**Issue by BoBeR182** [hashcat/hashcat#515]
Is there support for TAB delimited hashfiles?

I tried `hashcat -p \t hash.file` but it failed.

**Comment by magnumripper** [comment]
Using a decent shell you should just escape an actual tab character. Normally that would be something like 'ctrl-v + tab' surrounded by quotes.

**Comment by jsteube** [comment]
Yes, tabs are supported. You just need to deal with your shell to not re-interpret it somehow, but that's not part of hashcat.
