### ISSUE TITLE
"Device does not provide enough allocatable device-memory to handle this attack"

### ISSUE THREAD

**Issue by nadiamoe** [hashcat/hashcat#516]
I'm getting this error when trying to load 55M hashes into memory and around 15M words from a list.
My OCL device is a 750Ti with 2G VRAM.

As it works with smaller files, I can, of course, split the file and script hashcat to iterate through them, but would't be better if HC could handle this scenarios by itself? I don't thinl it's _that_ uncommon.

Here's the complete output and version:

```
hashcat (v3.10) starting...

OpenCL Platform #1: NVIDIA Corporation      
======================================
- Device #1: GeForce GTX 750 Ti, 500/2000 MB allocatable, 5MCU

WARNING: Failed loading the XNVCTRL library: libXNVCtrl.so: cannot open shared object file: No such file or directory
         Please install libxnvctrl-dev package.

Hashes: 55316745 hashes; 35061359 unique digests, 1 unique salts
Bitmaps: 24 bits, 16777216 entries, 0x00ffffff mask, 67108864 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Initializing device kernels and memory...

- Device #1: Device does not provide enough allocatable device-memory to handle this attack
```
### OS info:

`Linux Hostname 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux`

```
local/libxnvctrl 370.28-1
    NVIDIA NV-CONTROL X extension
local/nvidia 370.28-1
    NVIDIA drivers for linux
local/nvidia-utils 370.28-1
    NVIDIA drivers utilities
local/opencl-nvidia 370.28-1
    OpenCL implemention for NVIDIA
```

**Comment by roycewilliams** [comment]
There isn't enough GPU memory to hold your attack. hashcat cannot handle this scenario - only you can (either by getting a card with more memory, getting more cards ... or as you said, by dividing up the job). 

Unless I'm misunderstanding your question. :) How could hashcat better handle this?

**Comment by nadiamoe** [comment]
Hi,

You are correct, my VRAM is clearly not enough to hold the whole list of hashes. I was thinking about some kind of internal splitting. Load the whole list on RAM, and move chunks to the vram maybe? It would be slow, yes, but is still better than launching several hashcats in succession.

Sorry if it's a dumb suggestion, I don't actually know how the hashcat internals work :(

**Comment by roycewilliams** [comment]
It's not a dumb suggestion at all -- but it is probably outside the hashcat project's current scope. If it's something that can easily be scripted externally, @atom is usually less inclined to take it on as an internal feature. But you're not crazy. :)

**Comment by nadiamoe** [comment]
Cool, I'll go on with the script approach then :smile: 

Just another related question: How can I determine how many hashes will fit in memory? Is it as simple as `vram / size_of_hash`, or is some other metadata stored with them?

**Comment by roycewilliams** [comment]
I think it's sometimes hash-dependent, but should always be pretty close to that ratio. Starting with that ratio, and then doing a bisect (binary walk) should narrow it down pretty quickly.

**Comment by magnumripper** [comment]
> Is it as simple as `vram / size_of_hash`?

My guess would be a quarter of that. For some (silly) reason, nearly all OpenCL implementations limit size of any single alloc to a quarter of total memory. You can see that figure when listing devices:

```
  Device ID #2
    Type           : Gpu
    Vendor ID      : 2147483648
    Vendor         : NVIDIA
    Name           : GeForce GT 650M
    Processor(s)   : 2
    Clock          : 900
    Memory         : 256/1024 MB allocatable
    OpenCL Version : OpenCL C 1.2 
```

The "256/1024 MB allocatable" is what I'm talking about. You can allocate all 1024 but only at most 256 MB at a time.

**Comment by jsteube** [comment]
As @roycewilliams said, I'm not much less inclined to take it on as an internal feature if it's something that can easily be scripted externally. Therefore closing this issue.

**Comment by roycewilliams** [comment]
For future searchers, note that I did a survey of real-world memory allocation across multiple platforms.

https://gist.github.com/roycewilliams/5ac28350023613c614034c7fb6ba715d

Summary of findings:

* At this writing, NVIDIA never exceeds 25%
* AMD, Intel, and pocl sometimes exceed 25%
* pocl sometimes makes 100% available (or claims to in hashcat output, anyway)

And if I learn any useful technical information, I'll post it to this NVIDIA forums thread:

https://devtalk.nvidia.com/default/topic/992502/cuda-programming-and-performance/why-is-cl_device_max_mem_alloc_size-never-larger-than-25-of-cl_device_global_mem_size-only-on-nvidia-/
