### ISSUE TITLE
DES-ECB not working

### ISSUE THREAD

**Issue by Forts117** [hashcat/hashcat#519]
As seen in this thread: https://github.com/hashcat/hashcat/pull/452#issuecomment-249888233

we have discovered that -m 14000 is not working with known CT:PT.  Hopefully this can be investigated!

**Comment by mattames** [comment]
Hi guys, from talking to a few users, yes this is broken. Forts117 and bigfella237 - perhaps it would be useful if you ran Hashcat against some standard DES test vectors and some known keys to demonstrate that this is the case please?

**Comment by jsteube** [comment]
DES mode is not broken, please provide some example key:value pairs so that we can reproduce here. Here's one, showing it's working fine. 

```
root@ht:~/hashcat# echo -n hashcat1 | tools/test.pl passthrough 14000
cd674507b21e5ebe:1435662222276461
root@ht:~/hashcat# ./hashcat -m 14000 cd674507b21e5ebe:1435662222276461 -a 3 hashcat1 --quiet 
cd674507b21e5ebe:1435662222276461:hashcat1
root@ht:~/hashcat# echo $?
0
root@ht:~/hashcat# 
```

Feel free to reopen the issue in case you can provide such info.

**Comment by bigfella237** [comment]
Could you tell us please, what is the correct key variable expected from this search?

cd674507b21e5ebe:1435662222276461

**Comment by Forts117** [comment]
As I mentioned above, a few datasets were tested in the other page I linked to.  A few other users (jark22, fransla and bigfella237) were unable to get known keys from CT:PT pairs.  Fransla noted that -14100 works but he was unable to have success with -14000.  Here are 4 datasets, none of which seem to work for me:

47DC9810ADE39295:A04AB36B33E34FF2  (key: 0101010101010101)

1B5B3EDF6511A554:DA93B01EF7F98852  (key: 0101010101012626)

1DBD2AB7D1CB9E7E:B36DE1B9DAC7DC0D  (key: 01020407080B0D0E)

1BB15088EFD7E0FA:9510DC4C681ED5AD  (key: ABBACDDCEFFE1023)

Can someone else please try one of these sets using -14000 and see if it works for them?

Also I don't understand the example you posted above... where is the recovered key shown? I'm quite new to this whole process so please excuse my ignorance if I'm doing something in the process incorrectly....

**Comment by bigfella237** [comment]
Note that those key variables @Forts117 listed above all have odd-parity bytes, however there are some even-parity bytes in the default "DES_full.charset" file so the key you find may not be that exact variable, but the seven Most Significant Bits of each byte should still be the same.

Remember that if you disregard parity that means there are 256 copies of every DES key (2^64 divided by 2^56), so we must only deal with odd-parity bytes.

**Comment by jsteube** [comment]
@bigfella237 As you can see from my first post, the key for cd674507b21e5ebe:1435662222276461 is "hashcat1", or 6861736863617431. You can use --outfile-format to show it in hex, too:

```
root@et:~/hashcat# ./hashcat -m 14000 cd674507b21e5ebe:1435662222276461 -a 3 --quiet --hex-charset 6861736863617431 --outfile-format 5 --potfile-disable
cd674507b21e5ebe:1435662222276461:6861736863617431
```

@Forts117 Your example work pretty well. I tested them on with pocl OpenCL runtime, Intel OpenCL runtime, NVidia OpenCL runtime (amd-gpu-pro is known to be broken). Anyway, they all work fine:

```
root@et:~/hashcat# ./hashcat -m 14000 47DC9810ADE39295:A04AB36B33E34FF2 -a 3 --quiet --hex-charset --outfile-format 5 --potfile-disable 0101010101010101
47dc9810ade39295:a04ab36b33e34ff2:0101010101010101
```

Here's it again, with a little bit of search space:

```
root@et:~/hashcat# ./hashcat -m 14000 47DC9810ADE39295:A04AB36B33E34FF2 -a 3 --quiet --hex-charset --outfile-format 5 --potfile-disable ?1?101010101?1?1 -1 charsets/DES_full.charset
47dc9810ade39295:a04ab36b33e34ff2:0101010101010101
```

If you try to reproduce, here's the version I'm using:

```
root@et:~/hashcat# uname -a
Linux et 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@et:~/hashcat# ./hashcat -V
v3.10-339-gfb3e6ba+
root@et:~/hashcat# nvidia-smi 
Sat Oct  1 08:52:02 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 370.28                 Driver Version: 370.28                    |
|-------------------------------+----------------------+----------------------+
```

**Comment by Forts117** [comment]
Oh!  Ok, maybe we've found the problem then.  You mentioned "amd-gpu-pro is known to be broken" and I am indeed using an AMD GPU (RX-480).  Could this be the root of all my issues then perhaps??

Update: I just tried my sample numbers again using your command line of:

`hashcat64 -m 14000 47DC9810ADE39295:A04AB36B33E34FF2 -a 3 --quiet --hex-charset --outfile-format 5 --potfile-disable ?1?101010101?1?1 -1 charsets/DES_full.charset`

and it's working! Not sure what I was doing didderently but this is very encouraging.  Thank you very much for your help with this @jsteube it's greatly appreciated!

**Comment by jamesthecat7** [comment]
jsteube's example works for me, but if i try a 32 character CT:PT I get "no hashes loaded" error. Can someone explain this?
Example where PT=testingtesting11 and key = hashcat1:
`hashcat64 -m 14100 8d38b97dfad9ff21ffa6dcd7c2f78caf:74657374696e6774657374696e673131 -a 3 --potfile-disable`

**Comment by jsteube** [comment]
In 3DES, the blocksize doesn't change compared to DES. Not sure what you
mean with 32 character, maybe 3DES in combination with a block chaining
mode?

**Comment by jhanson-dev** [comment]
Thank's jsteube. I'm now trying a 64 bit block but now get the error 'invalid mask' when trying 3DES.
`hashcat64 -m 14100 cd674507b21e5ebe:1435662222276461 -a 3 --potfile-disable`

**Comment by jsteube** [comment]
You didn't specify a mask. Anyway that's not a hashcat issue, please ask on hashcat forum for correct hashcat usage.

**Comment by jhanson-dev** [comment]
Sorry, new to hashcat, i wasn't sure if the mask would be set for me like with the 14000. I'll read up the documentation creating an efficient mask for my task, although i'd imagine a 3DES key will take a millennia to break anyway if they've used the full 192 bits.

**Comment by mattames** [comment]
After reviewing this thread, I believe all the troubles were due to the order of the PT and CT. Hashcat requires the 64 bit input and output blocks in the format Ciphertext:Plaintext, where as Fort's failed examples above are in the order of PT:CT.

In any case this mode has been confirmed working by many people at this stage so I'm sure this one can be closed off.
