### ISSUE TITLE
internal compiler error while compiling a windows64 exe on Raspberry pi Kali full distro

### ISSUE THREAD

**Issue by cyclo-techtwister** [hashcat/hashcat#521]
Just so you are aware, I will try on a full desktop next most likely a pi thing...
FYI, compiles linux version just fine....

internal compiler error while compiling a windows64 exe on raspberry pi Kali distro
Too many to list....
i686-w64-mingw32-gcc: internal compiler error: Killed (program cc1)
src/Makefile:277: recipe for target 'obj/ext_nvapi.WIN.32.o' failed
make: **\* [obj/ext_nvapi.WIN.32.o] Error 4
^Csrc/Makefile:277: recipe for target 'obj/affinity.WIN.32.o' failed
make: **\* [obj/affinity.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/autotune.WIN.32.o' failed
make: **\* [obj/autotune.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/bitops.WIN.32.o' failed
make: **\* [obj/bitops.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/combinator.WIN.32.o' failed
make: **\* [obj/combinator.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/convert.WIN.32.o' failed
make: **\* [obj/convert.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/cpu_aes.WIN.32.o' failed
make: **\* [obj/cpu_aes.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/cpu_sha1.WIN.32.o' failed
make: **\* [obj/cpu_sha1.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/cpu_sha256.WIN.32.o' failed
make: **\* [obj/cpu_sha256.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/debugfile.WIN.32.o' failed
make: **\* [obj/debugfile.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/dictstat.WIN.32.o' failed
make: **\* [obj/dictstat.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/dispatch.WIN.32.o' failed
make: **\* [obj/dispatch.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/ext_ADL.WIN.32.o' failed
make: **\* [obj/ext_ADL.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/ext_nvml.WIN.32.o' failed
make: **\* [obj/ext_nvml.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/ext_xnvctrl.WIN.32.o' failed
make: **\* [obj/ext_xnvctrl.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/folder.WIN.32.o' failed
make: **\* [obj/folder.WIN.32.o] Interrupt
src/Makefile:289: recipe for target 'obj/hashcat.WIN.32.o' failed
make: **\* [obj/hashcat.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/hlfmt.WIN.32.o' failed
make: **\* [obj/hlfmt.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/hwmon.WIN.32.o' failed
make: **\* [obj/hwmon.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/logfile.WIN.32.o' failed
make: **\* [obj/logfile.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/loopback.WIN.32.o' failed
make: **\* [obj/loopback.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/monitor.WIN.32.o' failed
make: **\* [obj/monitor.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/mpsp.WIN.32.o' failed
make: **\* [obj/mpsp.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/opencl.WIN.32.o' failed
make: **\* [obj/opencl.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/outfile_check.WIN.32.o' failed
make: **\* [obj/outfile_check.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/outfile.WIN.32.o' failed
make: **\* [obj/outfile.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/potfile.WIN.32.o' failed
make: **\* [obj/potfile.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/rp.WIN.32.o' failed
make: **\* [obj/rp.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/rp_cpu.WIN.32.o' failed
make: **\* [obj/rp_cpu.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/shared.WIN.32.o' failed
make: **\* [obj/shared.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/status.WIN.32.o' failed
make: **\* [obj/status.WIN.32.o] Interrupt
src/Makefile:277: recipe for target 'obj/stdout.WIN.32.o' failed

**Comment by jsteube** [comment]
Propably not enough host memory for mingw, so the process gets killed by the OS. Anyway, not a hashcat issue, so closed.
