### ISSUE TITLE
[BUG] Hashcat 3.1 making PC turn off with SHA512 Bruteforce

### ISSUE THREAD

**Issue by Virtix21** [hashcat/hashcat#522]
Specs:
2X AMD RX 480 GPU's - not OC'd
AMD drivers 16.9.2
Core i7 4790k
1kW EVGA PSU
Windows 7 x64

On the 7 char length SHA512 (-m 1700) the whole PC shuts off.
The screen goes black, and around 5 seconds later the PC shuts off. Doesn't seem to be a heat problem or anything in that manner.
I can't find reason in event log.

**Comment by jsteube** [comment]
Propably power consumption issue. The RX480 is not pci compliant. It's known to suck more power from the board than allowed. Anyway, not a hashcat issue, so closed.
