### ISSUE TITLE
v3.10 ERROR: clGetPlatformIDs(): CL_UNKNOWN_ERROR 

### ISSUE THREAD

**Issue by Thedemon007** [hashcat/hashcat#523]
I try and run either a benchmark or a crack and show error:

> ERROR: clGetPlatformIDs(): CL_UNKNOWN_ERROR

I run in GNU/Linux the pc no have a graphic card with support OPENCLl i want use CPU Via nano how to force use only cpu? 

It be great that supported the "VIA PadLock engine"...

Sorry for my bad english :D ...

**Comment by jsteube** [comment]
Your CPU needs an OpenCL runtime

**Comment by Thedemon007** [comment]
Now only old versions support cpu, without OpenCL runtime?

**Comment by roycewilliams** [comment]
That is correct. Support for all platforms and devices has been centralized around OpenCL.
