### ISSUE TITLE
Using the CPU in Hashcat v3

### ISSUE THREAD

**Issue by butterworth1492** [hashcat/hashcat#525]
Firstly, I'll admit to not being a Hashcat expert.  Having said that, here's my issue after upgrading to v3:

```
# hashcat -b
hashcat (v3.10) starting in benchmark-mode...

OpenCL Platform #1: Mesa
========================
- Device #1: NVC4, 1048576/1048576 MB allocatable, 7MCU

ERROR: clBuildProgram(): CL_BUILD_PROGRAM_FAILURE
invalid source
Segmentation fault
```

I also can't seem to explicitly enumerate the CPU as a usable device.  

```
hashcat -b --opencl-device-types=1
hashcat (v3.10) starting in benchmark-mode...

OpenCL Platform #1: Mesa
========================
- Device #1: NVC4, skipped

ERROR: No devices found/left
```

These were not issues I had with v2.  Can someone point me in the right direction?

**Comment by jsteube** [comment]
Note that v2 doesn't use OpenCL for CPU, but v3 does. Now it seems the OpenCL runtime for the NVC4 has some internal problems, hence the CL_BUILD_PROGRAM_FAILURE. Sorry, but not a hashcat issue
