### ISSUE TITLE
Use CMake for build

### ISSUE THREAD

**Issue by KOLANICH** [hashcat/hashcat#527]
#520

> we should discuss this in more detail

**Comment by jsteube** [comment]
OK, what's wrong with simple Make?

**Comment by KOLANICH** [comment]
1 It is not crossplatform. I mean if you need make you will have to install a gnu toolchain either mingw or cygwin. Because make is not feature-rich, makefiles are often augmented with bash, which means most likely you will have to install cygwin and gnu utils. Cygwin is large and its installation is pain because it installs packages one by one.
cmake is only ~40 Mib (unpacked) and doesn't need cli gnu tools to build the project if used in a right way. The right way is not to rely on bash or python (if python is strict requirement of your app, you can use scons) :)
2 it is not good if you support many toolchains with different command lines. I mean that you'll have to write code creating buildng and linking command line by hand for every compiler and platform supported. cmake does this automatically (in fact not cmake itself, but the code in cmake language shipped with cmake, uts stdlib): you just declare the project files paths and cmake generates the files you need to build the project with the selected toolchain. Unfortunatily you will have to set some parameters like `/nxcompat` by hand because cmake dev's haven't developed this functionality yet.

**Comment by jsteube** [comment]
1) About crossplatform: Currently hashcat compiles natively on linux, freebsd, windows (using msys2) and osx. What's missing?
2) About many toolchains: I personally prefer to have dedicated code for buildng and linking command line by hand for every compiler and platform than to have "project files". Such files always create a feeling of "I have no clue what's going inside there" and this gives me a bad feeling. Does CMAKE create such files?

**Comment by KOLANICH** [comment]
1 gnu toolchain and other gnu tools are missing. there are exist some native windows tools not requiring cygwin, but they are really ancient. To have bash you need cygwin and it is glitchy if you have non-ascii characters in path.

**Comment by KOLANICH** [comment]
2 cmake is shipped with scripts creating projects files for different ides and toolchains.

**Comment by mabrowning** [comment]
Honestly, cmake is best for when you need to make build-time decisions. hashcat has minimal dependencies. I was skeptical for 10 seconds at first too, but haven't had any problems just `make`ing.

The one A++ feature of cmake is trivial/necessary out-of-tree builds. I haven't attempted that with hashcat, but it is slightly annoying to me that the build artifacts are polluting my source control'd directory.

**Comment by jsteube** [comment]
I see no reason to keep this issue open. There's no real benefit using cmake. I was under the impression cmake is required to build hashcat from VS, but it seems that's not the case. @KOLANICH  If I'm wrong, please reopen

**Comment by KOLANICH** [comment]
>I was under the impression cmake is required to build hashcat from VS, but it seems that's not the case.

It was not required, in fact, it was just an easiest way to make it build crossplatform crosstoolchain without messing with cygwin and bash. Since I don't use VS anymore (I have migrated to linux, but haven't managed to make VS to work on it (yet) ) VS support is not critical *for me* *for now*. cmake support is still will be helpful, because it is the project format used by qtcreator.
