### ISSUE TITLE
1080's Issues ? or just install / dep issues ?

### ISSUE THREAD

**Issue by n0x00** [hashcat/hashcat#528]
Hey All, has anyone seen any of this before? I have just done the disco-dance that is getting Kali and nVidia to play nice, but now I see a few things I had not seen on previous builds of kali

pulled the latest version from git

any pointers welcomed  

hashcat (master) starting in benchmark-mode...

OpenCL Platform #1: Mesa, skipped! No OpenCL compatible devices found

ERROR: No devices found/left

ERROR: opencl_ctx_devices_init() failed

Started: Tue Oct  4 20:15:27 2016
Stopped: Tue Oct  4 20:15:27 2016

**Comment by jsteube** [comment]
Looks like your OpenCL install is broken. Please continue on hashcat forum, github issues is for bugs and feature requests.

**Comment by n0x00** [comment]
already looked on the forum, hence me coming here.

FWIW i also have the same issue on another system recently with a new installing Kali, so I'll take it over to those guys and see if they can help me get hashcat working - doesn't work out of the box nor beta nor fresh git.
