### ISSUE TITLE
7-zip can't change Recovered....... prompt

### ISSUE THREAD

**Issue by zdavid008** [hashcat/hashcat#529]
When hashcat 7-zip, it can get the password, but not display correct Recovered..... prompt:

./hashcat -a 0 -m 11600  7z-11600.txt  test1.txt

$7z$0$14$0$$0$00000000000000000000000000000000$4123686674$32$29$d1b268dbc07e2325dce8397e5844180120845572fa40684def1f694275a5587b:1234
$7z$0$14$0$$7$37313435363138000000000000000000$39279930$16$9$4ea5cb0d53be00e0c0862a746fa1400d:123456
$7z$0$14$0$$0$00000000000000000000000000000000$3480438440$32$27$251aeb751fed9d439356ca2b6c62510e0b0c55e962c6c7fb866e64f6e3e98e25:pussy
$7z$0$14$0$$5$38353634350000000000000000000000$2566951658$16$7$bb2630d6db894532c2a3e7121e9aa717:12345
$7z$0$14$0$$0$00000000000000000000000000000000$2212294583$16$1$5a9c92be9897bb78ad9b522eb635db5a:football
$7z$0$14$0$$11$30343731313336333232330000000000$2558164349$16$7$f51a100633aead41515e0608a90c915e:experienced
$7z$0$14$0$$9$32343638343035363200000000000000$2464894690$32$23$9b266645003f1bb2fbe898d2fbf8f47e908bb3bdac1b3c17db252339a921175c:12345678
$7z$0$14$0$$8$30303338373634360000000000000000$147077226$32$24$fb7719d494b5271618dbaac803b1f0822a6c15e4f123b918174a35395d73c5c2:password
$7z$0$14$0$$11$31313137343636323431370000000000$3334941949$16$11$d939d3d23aeae9cee008de4e5f20f5c2:superman
$7z$0$14$0$$2$34370000000000000000000000000000$736984999$16$6$18551d8b5f9180bfbe9238a20bbddfda:dragon
$7z$0$14$0$$8$36383235313234360000000000000000$766310136$16$5$9796695a60dbb17f036785e1e01743ed:baseball
$7z$0$14$0$$5$35303731360000000000000000000000$2391308914$16$12$dbfba82414b73b63dc035fa7f7dd39f8:qwerty
Session.Name...: hashcat  
Status.........: Exhausted
Input.Mode.....: File (/home/jim/gyja/hash/test.pl.hash/test1.txt)
Hash.Target....: File (/home/jim/gyja/hash/test.pl.hash/hash/7z-11600.txt)
Hash.Type......: 7-Zip
Time.Started...: Wed Oct  5 16:38:49 2016 (4 secs)

Speed.Dev.#1...:       26 H/s (2.33ms)
Recovered......: 0/16 (0.00%) Digests, 0/16 (0.00%) Salts
======Above  Error======
Progress.......: 208/208 (100.00%)
Rejected.......: 0/208 (0.00%)
HWMon.Dev.#1...: Temp: 34c Fan: 40%

[test1.txt](https://github.com/hashcat/hashcat/files/510475/test1.txt)
[7z-11600.txt](https://github.com/hashcat/hashcat/files/510476/7z-11600.txt)

**Comment by jsteube** [comment]
That's because with 7-zip there's a high chance of false positives. We can't be sure the password is really correct. That's why we have to mark it as NEVER_CRACK, which then leads to the fact that it can not increase the recovered status. Anyway, sharp eye you have, but it will not change here.
