### ISSUE TITLE
Problems with allocating memory

### ISSUE THREAD

**Issue by KOLANICH** [hashcat/hashcat#531]
The version I've managed to build with VS in fact was unusable for using with large dictionaries : ocl runtime returned error when allocating memory for buffers. Old ocl-hashcat worked fine for the same dic.

It was even unusable for small dictionaries, but because of another reason - failure to allocate heap memory. I had to decrease count of devices in platform and count of platforms to make the progress achieve the stage of allocating memory for buffers.

**Comment by jsteube** [comment]
There was a problem for large dictionaries related to u32 as word counter. I've changed this to u64. I think this was the real problem.

**Comment by KOLANICH** [comment]
7 октября 2016 г. 15:20:06 GMT+03:00, Jens Steube notifications@github.com пишет:

> There was a problem for large dictionaries related to u32 as word
> counter. I've changed this to u64. I think this was the real problem.

Thank you. Then feel free to close this issue, when I am able to check I will comment this.
