### ISSUE TITLE
Kernel not found in cashe

### ISSUE THREAD

**Issue by robrah** [hashcat/hashcat#532]
How I can fix it? I have ASUS with nvidia geforce 720m and i3, system kali linux 2016.2
I use 
hashcat -m 1600 -a 0 hashes.txt /usr/share/john/password.lst

I get
hashcat (v3.10) starting...
# OpenCL Platform #1: Mesa                
- Device #1: NVD7, 1048576/1048576 MB allocatable, 2MCU

Hashes: 4 hashes; 4 unique digests, 4 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
Applicable Optimizers:
- Zero-Byte
  Watchdog: Temperature abort trigger disabled
  Watchdog: Temperature retain trigger disabled
- Device #1: Kernel m01600.ef5021ff.kernel not found in cache! Building may take a while...

ERROR: clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

invalid source
Ошибка сегментирования

**Comment by jsteube** [comment]
Why use MESA driver if you have a NVidia device. Please install correct OpenCL runtime.
