### ISSUE TITLE
Speed decreases with mask attacks when prefixing with string content

### ISSUE THREAD

**Issue by polarathene** [hashcat/hashcat#534]
While trying to optimize/debug my performance problems with algorithm implementation for mask attack I noticed that it wasn't my logic, this is the results for two very similar commands with an empty `m99000s` method. Each additional prefixed string character seems to have impact reducing performance further. 

**BUG:** Providing a known prefix to improve mask attack performance actually has the opposite effect.

Did some testing with more results than the initial 2 I provided, you can see that it seems to be a problem if the first 3 characters are not mask values for biggest hit. With one `p` after the first 3 chars, performance doesn't seem affected, a 2nd p anywhere after 1st 3 chars again drops it down to 2-3k GH/s, adding a third p brings performance down to 130 GH/s...

It could be specific to the way I've implemented 99000 without documentation that I did something wrong or should have set(or not set) some values in the hashconfig to cause an empty function to degrade like this. In which case it'd be good to know for documentation what causes this.

**hashcat -a 3 -m 99000 'a0850878201803bd' p?l?l?l?l?l?l?l?l --potfile-disable**:

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (p?l?l?l?l?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: panagnwwn -> pqojhowmp
Speed.Dev.#1...:   420.3 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 34555822080/208827064576 (16.55%)
Rejected.......: 0/34555822080 (0.00%)
Restore.Point..: 51118080/308915776 (16.55%)
HWMon.Dev.#1...: Temp: 48c Fan:  0% Util: 29% Core:1594Mhz Mem:3802Mhz Lanes:16

```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?lp?l?l?l?l?l?l?l --potfile-disable**

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?lp?l?l?l?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: spaccpjti -> upzlslfqw
Speed.Dev.#1...:   437.5 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 21265121280/208827064576 (10.18%)
Rejected.......: 0/21265121280 (0.00%)
Restore.Point..: 31457280/308915776 (10.18%)
HWMon.Dev.#1...: Temp: 45c Fan:  0% Util:  2% Core:1594Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?lp?l?l?l?l?l?l --potfile-disable**

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?l?lp?l?l?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: sapagnwwn -> uqpjhowmp
Speed.Dev.#1...:   408.5 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 34555822080/208827064576 (16.55%)
Rejected.......: 0/34555822080 (0.00%)
Restore.Point..: 51118080/308915776 (16.55%)
HWMon.Dev.#1...: Temp: 48c Fan:  0% Util:  0% Core:1594Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?lp?l?l?l?l?l --potfile-disable** (first run reported 25.9k GH/s at 23%)

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?l?l?lp?l?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: iovpxjfhy -> arrpgmrtd
Speed.Dev.#1...:  8968.3 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 97297367040/208827064576 (46.59%)
Rejected.......: 0/97297367040 (0.00%)
Restore.Point..: 3932160/11881376 (33.10%)
HWMon.Dev.#1...: Temp: 48c Fan:  0% Util:  3% Core:1594Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?l?lp?l?l?l?l --potfile-disable**

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?l?l?l?lp?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: visxpnjps -> cmmzpdcib
Speed.Dev.#1...:  7130.4 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 77164707840/208827064576 (36.95%)
Rejected.......: 0/77164707840 (0.00%)
Restore.Point..: 3932160/11881376 (33.10%)
HWMon.Dev.#1...: Temp: 43c Fan:  0% Util:  2% Core:1594Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?l?l?l?l?l?lp --potfile-disable**

```
Session.Name...: hashcat
Status.........: Running
Input.Mode.....: Mask (?l?l?l?l?l?l?l?lp) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: rmixjgmyp -> zhozcsibp
Speed.Dev.#1...:  7228.5 GH/s (0.03ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 73138176000/208827064576 (35.02%)
Rejected.......: 0/73138176000 (0.00%)
Restore.Point..: 3932160/11881376 (33.10%)
HWMon.Dev.#1...: Temp: 56c Fan:  1% Util:  1% Core:1594Mhz Mem:3802Mhz Lanes:16
```

**hashcat]$ hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?l?l?l?l?l?l?l --potfile-disable** (complete mask, no fixed characters)

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (?l?l?l?l?l?l?l?l?l) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: fxuaocehq -> uqoqlqlqv
Speed.Dev.#1...:  8170.8 GH/s (0.02ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 5429503678976/5429503678976 (100.00%)
Rejected.......: 0/5429503678976 (0.00%)
HWMon.Dev.#1...: Temp: 52c Fan:  0% Util: 71% Core:1949Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?l?l?l?l?lpp --potfile-disable** (speed halves when replacing any mask value with a 2nd fixed char, if replacing one of 1st 3 masks drops to similar slow speed/performance as above, about 690 GH/s)

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (?l?l?l?l?l?l?lpp) [9]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: fxuananpp -> uqoqlqlpp
Speed.Dev.#1...:  3541.4 GH/s (0.00ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 8031810176/8031810176 (100.00%)
Rejected.......: 0/8031810176 (0.00%)
HWMon.Dev.#1...: Temp: 52c Fan:  0% Util:  0% Core:1949Mhz Mem:3802Mhz Lanes:16
```

**Comment by polarathene** [comment]
Here is some output with my logic being running through instead of an empty function. It proves that the static chars are affecting performance when combined with masks:

**hashcat -a 3 -m 99000 'a0850878201803bd' ppp?a?a?a?a?a?d?d --potfile-disable**

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (ppp?a?a?a?a?a?d?d) [10]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 20:57:45 2016 (47 secs)
Candidates.#1..: pppeex6{73 -> ppp::~}z57
Speed.Dev.#1...: 16348.4 MH/s (8.01ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 773780937500/773780937500 (100.00%)
Rejected.......: 0/773780937500 (0.00%)
HWMon.Dev.#1...: Temp: 72c Fan: 27% Util: 96% Core:1873Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?l?l?l?a?a?a?ap00 --potfile-disable**
Little bit longer at 130% speed roughly, **covered twice the keyspace** almost:  773780937500 vs 1431576185000.

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (?l?l?l?a?a?a?ap00) [10]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 20:59:24 2016 (1 min, 6 secs)
Candidates.#1..: xlqJPj}p00 -> uqo:~\~p00
Speed.Dev.#1...: 21524.4 MH/s (5.26ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 1431576185000/1431576185000 (100.00%)
Rejected.......: 0/1431576185000 (0.00%)
HWMon.Dev.#1...: Temp: 73c Fan: 29% Util: 94% Core:1847Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' pp?l?a?a?a?a?a?d0 --potfile-disable**
Over twice the keyspace almost 3x 773780937500 vs 2011830437500?

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (pp?l?a?a?a?a?a?d0) [10]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 21:10:54 2016 (1 min, 34 secs)
Candidates.#1..: ppn\Fn"~60 -> ppz::~}z50
Speed.Dev.#1...: 21102.6 MH/s (5.07ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 2011830437500/2011830437500 (100.00%)
Rejected.......: 0/2011830437500 (0.00%)
HWMon.Dev.#1...: Temp: 73c Fan: 31% Util: 93% Core:1860Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' pass?l?l?l?l?l?l?l --potfile-disable**

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (pass?l?l?l?l?l?l?l) [11]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 21:51:09 2016 (16 secs)
Candidates.#1..: passxcxkwvq -> passqlqlqvq
Speed.Dev.#1...:   482.5 MH/s (2.27ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 8031810176/8031810176 (100.00%)
Rejected.......: 0/8031810176 (0.00%)
HWMon.Dev.#1...: Temp: 59c Fan:  0% Util: 96% Core:1923Mhz Mem:3802Mhz Lanes:16
```

**26x the keyspace of previous** 8031810176 vs 208827064576, yet a vert similar time.
**hashcat -a 3 -m 99000 'a0850878201803bd' pas?l?l?l?l?l?l?l?l --potfile-disable**

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (pas?l?l?l?l?l?l?l?l) [11]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 21:52:25 2016 (21 secs)
Candidates.#1..: pastxcxkwvq -> pasxqlqlqvq
Speed.Dev.#1...:  9566.2 MH/s (4.70ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 208827064576/208827064576 (100.00%)
Rejected.......: 0/208827064576 (0.00%)
HWMon.Dev.#1...: Temp: 68c Fan: 15% Util: 98% Core:1898Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' pa?l?l?l?l?l?l?l?l?l --potfile-disable**
26x the keyspace again, but done at **twice the rate as the previous**.

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (pa?l?l?l?l?l?l?l?l?l) [11]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: Mon Oct 10 21:54:59 2016 (4 mins, 21 secs)
Candidates.#1..: panuhkceqvq -> paqoqlqlqvq
Speed.Dev.#1...: 20504.5 MH/s (7.19ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 5429503678976/5429503678976 (100.00%)
Rejected.......: 0/5429503678976 (0.00%)
HWMon.Dev.#1...: Temp: 73c Fan: 33% Util: 95% Core:1835Mhz Mem:3802Mhz Lanes:16
```

No speedup with replacing `a` with `?l` this time.

**hashcat -a 3 -m 99000 'a0850878201803bd' z?a?a?a?a --potfile-disable**

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (z?a?a?a?a) [5]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: z4"j" -> z:~|~
Speed.Dev.#1...:   454.8 MH/s (2.27ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 81450625/81450625 (100.00%)
Rejected.......: 0/81450625 (0.00%)
HWMon.Dev.#1...: Temp: 57c Fan:  2% Util: 51% Core:1759Mhz Mem:3802Mhz Lanes:16
```

**hashcat -a 3 -m 99000 'a0850878201803bd' ?a?a?a?a?a --potfile-disable**

```
Session.Name...: hashcat                                  
Status.........: Exhausted
Input.Mode.....: Mask (?a?a?a?a?a) [5]
Hash.Target....: a0850878201803bd
Hash.Type......: PD2 - Payday 2
Time.Started...: 0 secs
Candidates.#1..: 1$OR} -> ::~|~
Speed.Dev.#1...: 16108.2 MH/s (8.12ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 7737809375/7737809375 (100.00%)
Rejected.......: 0/7737809375 (0.00%)
HWMon.Dev.#1...: Temp: 63c Fan:  2% Util: 97% Core:1860Mhz Mem:3802Mhz Lanes:16
```

**Comment by jsteube** [comment]
There's no discussion needed about this behavior. It's a well known limitation and there's also a standard workaround. Therefore I'm closing this issue.

Here's an explanation: Without a fixed w[0] the innerloop has nothing to iterate through, the il_cnt variable will be 1 and the kernel will finish too fast to run efficient. After that, hashcat will run the candidates generator to produce the next set of parallelized candidates. This kernel takes some serious time as it has to read and write to global memory.  This is not a problem usually because compared to the hashing kernel it's almost no time. The typical kernel with -w 3 will run at 100ms while the candidate generator kernel will run a 0.1ms, so the GPU utilization for actual cracking is very high. But if you set il_cnt to 1, the kernel will take 0.1ms as well and the GPU utilization for actual cracking drops massive. Note the numbers are not very accurate but help explaining this.

The best workaround is to have a prefix added to the hash as a salt. This way you can also make use of a precomputed intermediate hash for this static data before you enter the inner loop. You can see -m 20 on how to do that.

**Comment by polarathene** [comment]
Thanks for the explanation, I'm still having trouble understanding what you're saying though. Why does the same length have such a big difference if using a pure mask vs mask with some static string data?

> Without a fixed w[0] the innerloop has nothing to iterate through

This is the first 4 chars right? When you say fixed what do you mean? Isn't the example with `pass` as the prefix static/fixed? Yet it seems considerably slower than replacing the letters with `?l`. `?l?l?l?l?l?l?lpass`finishes straight away at 32 GH/s but `pass?l?l?l?l?l?l?l` which you'd think would have much less to compute takes 13 secs at <600 MH/s.. Am I better in some cases to always start my mask attack with first 4 chars as mask values? 

I'm not quite sure how parralelization is occuring, from the sounds of it, it seems starting the key with `L` the GPU can only operate on a single sequence at a time vs `?l` where it can do parraelize 26? and presumably each of those 26 again if the next char is mask `?l`?

> There's no discussion needed about this behavior. It's a well known limitation and there's also a standard workaround

**Where is this documented?** There was no mention of this problem or work around on the Mask Attack wiki page from memory.

> The best workaround is to have a prefix added to the hash as a salt.

I don't know if this will be too viable, I have about 4k+ hashes and 8k+ file paths, that'd mean appending the salt 8k times per hash right? Are the other attacks where I can preprend the file path vulnerable to this performance problem too? 

I'm thinking my best option right now is to preprocess the paths and copy/paste their data into a prefix array before the inner loop and then loop through that array for each key generated by the mask.
