### ISSUE TITLE
windows 64 bit restore

### ISSUE THREAD

**Issue by SquirrelAssassin** [hashcat/hashcat#539]
code is using wrong slash when restoring
WARN: Rename file 'C:\Users\new\binaries/1.restore.new' to 'C:\Users\new\binaries/1.restore': No such file or directory

**Comment by jsteube** [comment]
Please try with latest beta: hashcat.net/beta and report back

**Comment by SquirrelAssassin** [comment]
fix for the current version is to use double quotes around your restore name --session="1"

**Comment by jsteube** [comment]
I tested on Windows 7 64 bit and restore works fine. Can you do a screenshot of what's wrong?

**Comment by jsteube** [comment]
OP did not respond and the issue can not be reproduced, so closed. Feel free to reopen and to provide more information I need to reproduce.
