### ISSUE TITLE
new hashcat 3 does not work anymore on my nvidia

### ISSUE THREAD

**Issue by r3k2** [hashcat/hashcat#540]
this used to work with cudahashcat... but is not working but does not error out neither.. is just blank.. does not do anything at all.. what is wrong? some flags below is me skipping one GPU testing here and there see whats the problem but no output.

```
 sudo hashcat -m 2500 -a3 --opencl-platforms=1 handshake_ExamPle_F8-18-00-00-00-00_2016-10-10T20-40-40.cap.hccap ?d?d?d?d?d?d?d?d  --status --force -d 1 -D 1,2,3
hashcat (v3.10) starting...

OpenCL Platform #1: NVIDIA Corporation  
======================================
- Device #1: GeForce GTX 590, 382/1530 MB allocatable, 16MCU
- Device #2: GeForce GTX 590, skipped

s


[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s


[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s


[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s


[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => s
```

**Comment by jsteube** [comment]
This looks like an OpenCL runtime installation problem. Please install latest driver and also try with a different OpenCL tool. If it still does not work, please use hashcat forum for report. GitHub is for bug reports and feature requests.
