### ISSUE TITLE
New ALgo

### ISSUE THREAD

**Issue by botkosgap** [hashcat/hashcat#541]
return bin2hex(hash("sha512", $password . $salt, true) ^ hash("whirlpool", $salt . $password, true)); 
service:leet.cc
example log:hash
P_GaMeMInG_TH:2ae035abcccdb5dab691eb8cfa48448871b6623988c676a460da42c5a74ed5b3aea46abd77ad58ec61254a2666f8e7a69923c43e31d468c7f1c8f1505cfbff98 
Synsyn45:e9839f5b96772b2082ca494e92efac7debea3f38badbb8452f66c62610d1b44d26478cac4069665a575ad720cf6aeb6f9cb06881700e4249d15b36acd0c8c7bd 
koogur_TH:9cadd76b22da5702b0c7a1664f1949297d272ac80e6e00176fab3704b0f75b0c5bf142fc32aa433102e1744e0222660ee935f778dc8cb5ca7ed5ea5e5f9e8a49 
masterofpizza:b485cb2321ea92982cefcf691ea5b5d2fa317c191dadc405db1e3cdcf2f5862b570655509bdda0c5b22ab058fd299a52f67a287e8e11436913a02ffb4da5084c 
MinecraftMegan:269d900ebe5e02f6e74473d9a99ab949b435b4de0bcf93db4f0b7fc56b359b8fa6c8c3fad3966983e0bb489a4c2463f5ff2f84c569407839f62f68c60e345d7c 
TheUnicornGirl:cee2fab51a772226468c2285fbe1bb32d86685bc9f2e45340c124384447d778189fcdd295b7142098edc9ea8ab845469db6721d6815c620acf7f5903415e4110 
lordhunter13:348895af54b08708177b27dbaec655afd35cb57d8a6a03273f95dddbc37cdfd6e52bd92f320ad038fca500ece2e14acbb173a856cf8f6a24fd10312c52cba4b4 
HahahaxD:44fc9e03e13d11a9ce0617b51b781ad6582f32e7806313502d7198419ca2028289d8a63078525f0497520b06492856bd1478f2aba1aceaebd210b3fe962a3cba 
Nobita_621:103c5d9f8a6125cde91fbc2cbf2d56122d7c24c0413d207aa30c8672d5df792a03c6af59e6ed53f92d9e147f1602634410557cba8655de84dc473ab404c2197e 
izzy_wizzy:d2198f10246dd2e6e37144c63e7a67486ba40c90b67d851fe7dd0065e88f2fbeb2446d16368e0bf24dea00b2fe3ef858eae0755d911618ca1ea922178415df29 
hiposinger999:eee067638ec0ad98301aabdca17fbc1358455eb0bb6afa447294f407a1ac8dfd59c0d234e42994887212bc0f9f55d166ee49a431abe2df86426b27343fd23453 
psychosiid557:0b81a4d96649d6142f0f5b2cfdd0c4cdb4803122e3e92edad23182f13452f56eab53a971f75e4ae6ab2c1f625134259d3e1d1d96fea8506e97c40a7bbdff94bd 
linktijger:4ab1c246a7659aef217dc4589d60b14b316f50c6c5bb511c39150c563b0c396a97c31e45b1973e4a71e365a840737fe6e8ba1a334edc34bd74f6ebe2fbb8b4a7 
Mu5hroom24:20c8113a1e29c175b806b58f519ff829499583e8cb705af314e6610099ee9b65b73c67b10c7976ead40e871d1ec608206063cc5c5cc10f2e4925f2dff511cfae 
aliqfadli:b0eb5a9dcb33e0f277bad4fcca1d5232566d71c63a31dc71c7767de31eedd4210b21f8b1610a6617f0d27a388a2c8607432429e851d533a3a746b32c53464a24 
marcosjunior:70c37d4ad15247cd5e8be8b651f1db9f5a23baf3b2f025afb92c520df8a14bddc7ec4318ac595870ba190d62f9c4d5d5ea11b43dc7647cf6a1aa156a8d3a5c9c 
monnzeTuSyounen:8b40f1951539cc0f3d02a45b82c6b54e84a6c1b5148a3f84313b8aec60bcf546e4e758f3bbc9c05dfd4501e32f3c14f94b3ea1bb0e50165a491c041e11e5dbc3

**Comment by botkosgap** [comment]
need gpu:C

**Comment by botkosgap** [comment]
need for hashcat:D can?) 
i can give $

**Comment by jsteube** [comment]
Useless site-specific algo. Makes no sense to add
