### ISSUE TITLE
when hash in hashcat.pot , -o output.txt  no effect

### ISSUE THREAD

**Issue by x-falcon** [hashcat/hashcat#542]

**Comment by jsteube** [comment]
Are you using a beta version?

**Comment by x-falcon** [comment]
@jsteube download from first pages ,the version is 3.10 ,may not beta version 
for detail,  one hash has been cracked and store in hashcat.pot,
when crack the same hash again, the -o will not output  any file.
It's a small problem

**Comment by jsteube** [comment]
Please retry with latest beta version from https://hashcat.net/beta/ and close the issue if fixed

**Comment by x-falcon** [comment]
@jsteube It work now. Thank you
