### ISSUE TITLE
Using --show with SHA256crypt(-m 7400) only outputs partial hashes

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#543]
After running a list through several attacks, I used the following command to export the cracked hashes from my potfile.

hashcat64.exe -m 7400 example0.hash --show -o cracked_hashes

This command works for other hashes types, however when exporting SHA256crypt hashes, only the hash ID and the round number are exported, the salt and hash are removed, making the exported list pretty much useless. The full hashes are present in the potfile and it does correctly export only the ones in the input list that have been cracked, yet they come out looking like this:

$5$rounds=7500:pass1234

Instead of like this:

$5$rounds=7500$yJn+KOYWjLRgVq7+$BZ1Eey/qecgvx4dEMeveBBr77ZZKBtmyzSCxNVpINpA:pass1234

**Comment by jsteube** [comment]
Please retry with latest beta version from https://hashcat.net/beta/ and close the issue if fixed

**Comment by Chick3nman** [comment]
Fixed in Beta hashcat-3.10+515. Thank you!
