### ISSUE TITLE
On Mac getting "(null): No such file or directory"

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#545]
Here's the text from terminal from compilation to the error occurring. I am not developer so please let me know if I'm missing something. 

macOS Sierra with latest Nvidia drivers
MacBook Pro
GeForce GT 650M

```
Users-MBP:~ useracct$ git clone https://github.com/hashcat/hashcat.git
Cloning into 'hashcat'...
remote: Counting objects: 16443, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 16443 (delta 12), reused 0 (delta 0), pack-reused 16410
Receiving objects: 100% (16443/16443), 15.65 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (13602/13602), done.
Checking connectivity... done.
Users-MBP:~ useracct$ mkdir -p hashcat/deps
Users-MBP:~ useracct$ git clone https://github.com/KhronosGroup/OpenCL-Headers.git hashcat/deps/OpenCL
Cloning into 'hashcat/deps/OpenCL'...
remote: Counting objects: 288, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 288 (delta 16), reused 0 (delta 0), pack-reused 263
Receiving objects: 100% (288/288), 218.99 KiB | 114.00 KiB/s, done.
Resolving deltas: 100% (186/186), done.
Checking connectivity... done.
Users-MBP:~ useracct$ cd hashcat/
Users-MBP:hashcat useracct$ make
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/affinity.NATIVE.o src/affinity.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/autotune.NATIVE.o src/autotune.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/benchmark.NATIVE.o src/benchmark.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/bitmap.NATIVE.o src/bitmap.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/bitops.NATIVE.o src/bitops.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/combinator.NATIVE.o src/combinator.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/common.NATIVE.o src/common.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/convert.NATIVE.o src/convert.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpt.NATIVE.o src/cpt.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_aes.NATIVE.o src/cpu_aes.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_crc32.NATIVE.o src/cpu_crc32.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_des.NATIVE.o src/cpu_des.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_md5.NATIVE.o src/cpu_md5.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_sha1.NATIVE.o src/cpu_sha1.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/cpu_sha256.NATIVE.o src/cpu_sha256.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/debugfile.NATIVE.o src/debugfile.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/dictstat.NATIVE.o src/dictstat.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/dispatch.NATIVE.o src/dispatch.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/dynloader.NATIVE.o src/dynloader.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/event.NATIVE.o src/event.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/ext_ADL.NATIVE.o src/ext_ADL.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/ext_nvapi.NATIVE.o src/ext_nvapi.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/ext_nvml.NATIVE.o src/ext_nvml.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/ext_OpenCL.NATIVE.o src/ext_OpenCL.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/ext_xnvctrl.NATIVE.o src/ext_xnvctrl.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/filehandling.NATIVE.o src/filehandling.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/folder.NATIVE.o src/folder.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/hashcat.NATIVE.o src/hashcat.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/hashes.NATIVE.o src/hashes.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/hlfmt.NATIVE.o src/hlfmt.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/hwmon.NATIVE.o src/hwmon.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/induct.NATIVE.o src/induct.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/interface.NATIVE.o src/interface.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/locking.NATIVE.o src/locking.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/logfile.NATIVE.o src/logfile.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/loopback.NATIVE.o src/loopback.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/memory.NATIVE.o src/memory.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/monitor.NATIVE.o src/monitor.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/mpsp.NATIVE.o src/mpsp.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/opencl.NATIVE.o src/opencl.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/outfile_check.NATIVE.o src/outfile_check.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/outfile.NATIVE.o src/outfile.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/potfile.NATIVE.o src/potfile.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/restore.NATIVE.o src/restore.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/rp.NATIVE.o src/rp.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/rp_cpu.NATIVE.o src/rp_cpu.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/rp_kernel_on_cpu.NATIVE.o src/rp_kernel_on_cpu.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/shared.NATIVE.o src/shared.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/status.NATIVE.o src/status.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/stdout.NATIVE.o src/stdout.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/straight.NATIVE.o src/straight.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/terminal.NATIVE.o src/terminal.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/thread.NATIVE.o src/thread.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/timer.NATIVE.o src/timer.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/tuningdb.NATIVE.o src/tuningdb.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/usage.NATIVE.o src/usage.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/user_options.NATIVE.o src/user_options.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/weak_hash.NATIVE.o src/weak_hash.c
gcc -c  -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o obj/wordlist.NATIVE.o src/wordlist.c
gcc     -pipe -W -Wall -std=c99 -O2 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -o hashcat obj/affinity.NATIVE.o obj/autotune.NATIVE.o obj/benchmark.NATIVE.o obj/bitmap.NATIVE.o obj/bitops.NATIVE.o obj/combinator.NATIVE.o obj/common.NATIVE.o obj/convert.NATIVE.o obj/cpt.NATIVE.o obj/cpu_aes.NATIVE.o obj/cpu_crc32.NATIVE.o obj/cpu_des.NATIVE.o obj/cpu_md5.NATIVE.o obj/cpu_sha1.NATIVE.o obj/cpu_sha256.NATIVE.o obj/debugfile.NATIVE.o obj/dictstat.NATIVE.o obj/dispatch.NATIVE.o obj/dynloader.NATIVE.o obj/event.NATIVE.o obj/ext_ADL.NATIVE.o obj/ext_nvapi.NATIVE.o obj/ext_nvml.NATIVE.o obj/ext_OpenCL.NATIVE.o obj/ext_xnvctrl.NATIVE.o obj/filehandling.NATIVE.o obj/folder.NATIVE.o obj/hashcat.NATIVE.o obj/hashes.NATIVE.o obj/hlfmt.NATIVE.o obj/hwmon.NATIVE.o obj/induct.NATIVE.o obj/interface.NATIVE.o obj/locking.NATIVE.o obj/logfile.NATIVE.o obj/loopback.NATIVE.o obj/memory.NATIVE.o obj/monitor.NATIVE.o obj/mpsp.NATIVE.o obj/opencl.NATIVE.o obj/outfile_check.NATIVE.o obj/outfile.NATIVE.o obj/potfile.NATIVE.o obj/restore.NATIVE.o obj/rp.NATIVE.o obj/rp_cpu.NATIVE.o obj/rp_kernel_on_cpu.NATIVE.o obj/shared.NATIVE.o obj/status.NATIVE.o obj/stdout.NATIVE.o obj/straight.NATIVE.o obj/terminal.NATIVE.o obj/thread.NATIVE.o obj/timer.NATIVE.o obj/tuningdb.NATIVE.o obj/usage.NATIVE.o obj/user_options.NATIVE.o obj/weak_hash.NATIVE.o obj/wordlist.NATIVE.o src/main.c -DCOMPTIME=1477089452 -DVERSION_TAG=\"v3.10-536-gf558a64\" -DINSTALL_FOLDER=\"/usr/local/bin\" -DSHARED_FOLDER=\"/usr/local/share/hashcat\" -DDOCUMENT_FOLDER=\"/usr/local/share/doc/hashcat\" -lpthread -s
ld: warning: option -s is obsolete and being ignored
Users-MBP:hashcat useracct$ ./hashcat -b
hashcat (v3.10-536-gf558a64) starting in benchmark mode...

(null): No such file or directory

```

**Comment by ghost** [comment]
A clean install of El Capitan did not solve the issue

**Comment by roycewilliams** [comment]
Can reproduce. Not sure how to produce useful debugging. Here's a try:

bash-3.2# dtruss -f ./hashcat -b 2>&1 | tee macos.out
[...]
bash-3.2# cat macos.out
dtrace: system integrity protection is on, some features will not be available
    PID/THRD  SYSCALL(args)          = return
hashcat (v3.10-541-g1c055a6) starting in benchmark mode...

(null): No such file or directory

dtrace: error on enabled probe ID 2149 (ID 454: syscall::pread:return): invalid kernel access in action #13 at DIF offset 44
dtrace: error on enabled probe ID 2149 (ID 454: syscall::pread:return): invalid kernel access in action #13 at DIF offset 44
dtrace: error on enabled probe ID 2158 (ID 552: syscall::sysctl:return): invalid kernel access in action #11 at DIF offset 40
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
dtrace: error on enabled probe ID 2133 (ID 942: syscall::write_nocancel:return): invalid kernel access in action #13 at DIF offset 92
 1724/0x2ce7:  thread_selfid(0x0, 0x0, 0x0)      = 11495 0
 1724/0x2ce7:  open(".\0", 0x0, 0x1)         = 3 0
 1724/0x2ce7:  fstat64(0x3, 0x7FFF5981D810, 0x1)         = 0 0
 1724/0x2ce7:  fcntl(0x3, 0x32, 0x7FFF5981DAB0)      = 0 0
 1724/0x2ce7:  close(0x3)        = 0 0
 1724/0x2ce7:  stat64("/usr/local/src/hashcat\0", 0x7FFF5981D780, 0x7FFF5981DAB0)        = 0 0
 1724/0x2ce7:  issetugid(0x7FFF5981DAB0, 0x7FFF5981D780, 0x7FFF5981DAB0)         = 0 0
 1724/0x2ce7:  csops(0x0, 0x0, 0x7FFF5981DAB0)       = 0 0
 1724/0x2ce7:  shared_region_check_np(0x7FFF5981B0E8, 0x0, 0x7FFF5981DAB0)       = 0 0
 1724/0x2ce7:  getpid(0x7FFF5981B0E8, 0x0, 0x7FFF5981DAB0)       = 1724 0
 1724/0x2ce7:  proc_info(0x2, 0x6BC, 0x8)        = 1272 0
 1724/0x2ce7:  stat64("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x7FFF5981CF78, 0x8)         = 0 0
 1724/0x2ce7:  open("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x0, 0x0)      = 3 0
 1724/0x2ce7:  fcntl(0x3, 0x61, 0x7FFF59814758)      = 0 0
 1724/0x2ce7:  mmap(0x0, 0x620, 0x5, 0x1, 0x3, 0x7000)       = 0x1064D0000 0
 1724/0x2ce7:  munmap(0x1064D0000, 0x620)        = 0 0
 1724/0x2ce7:  mmap(0x1064D0000, 0x2000, 0x5, 0x12, 0x3, 0x7000)         = 0x1064D0000 0
 1724/0x2ce7:  mmap(0x1064D2000, 0x1000, 0x3, 0x12, 0x3, 0x9000)         = 0x1064D2000 0
 1724/0x2ce7:  mmap(0x1064D3000, 0x2E20, 0x1, 0x12, 0x3, 0xA000)         = 0x1064D3000 0
 1724/0x2ce7:  close(0x3)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x7FFF5981D4D8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/libSystem.B.dylib\0", 0x7FFF5981CDA8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libcache.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libcommonCrypto.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libcompiler_rt.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libcopyfile.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libcorecrypto.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libdispatch.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libdyld.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libkeymgr.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/liblaunch.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libmacho.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libquarantine.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libremovefile.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_asl.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_blocks.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_c.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_configuration.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_coreservices.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_coretls.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_dnssd.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_info.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_kernel.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_m.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_malloc.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_network.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_networkextension.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_notify.dylib\0", 0x7FFF5981C9B8, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_platform.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_pthread.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_sandbox.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_secinit.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_symptoms.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libsystem_trace.dylib\0", 0x7FFF5981C9B8, 0x1)        = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libunwind.dylib\0", 0x7FFF5981C9B8, 0x1)      = 0 0
 1724/0x2ce7:  stat64("/usr/lib/system/libxpc.dylib\0", 0x7FFF5981C9B8, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/libobjc.A.dylib\0", 0x7FFF5981BC78, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/libauto.dylib\0", 0x7FFF5981BB58, 0x1)       = 0 0
 1724/0x2ce7:  stat64("/usr/lib/libc++abi.dylib\0", 0x7FFF5981BB58, 0x1)         = 0 0
 1724/0x2ce7:  stat64("/usr/lib/libc++.1.dylib\0", 0x7FFF5981BB58, 0x1)      = 0 0
 1724/0x2ce7:  open("/dev/dtracehelper\0", 0x2, 0x7FFF5981D980)      = 3 0
 1724/0x2ce7:  ioctl(0x3, 0x80086804, 0x7FFF5981D908)        = 0 0
 1724/0x2ce7:  close(0x3)        = 0 0
 1724/0x2ce7:  thread_selfid(0x3, 0x80086804, 0x7FFF5981D908)        = 11495 0
 1724/0x2ce7:  bsdthread_register(0x7FFFBCD7E224, 0x7FFFBCD7E214, 0x2000)        = 1073741919 0
 1724/0x2ce7:  ulock_wake(0x1, 0x7FFF5981D02C, 0x0)      = -1 Err#2
 1724/0x2ce7:  issetugid(0x1, 0x7FFF5981D02C, 0x0)       = 0 0
 1724/0x2ce7:  mprotect(0x1064D8000, 0x88, 0x1)      = 0 0
 1724/0x2ce7:  mprotect(0x1064DA000, 0x1000, 0x0)        = 0 0
 1724/0x2ce7:  mprotect(0x1064F0000, 0x1000, 0x0)        = 0 0
 1724/0x2ce7:  mprotect(0x1064F1000, 0x1000, 0x0)        = 0 0
 1724/0x2ce7:  mprotect(0x106507000, 0x1000, 0x0)        = 0 0
 1724/0x2ce7:  mprotect(0x106508000, 0x1000, 0x1)        = 0 0
 1724/0x2ce7:  mprotect(0x1064D8000, 0x88, 0x3)      = 0 0
 1724/0x2ce7:  mprotect(0x1064D8000, 0x88, 0x1)      = 0 0
 1724/0x2ce7:  getpid(0x1064D8000, 0x88, 0x1)        = 1724 0
 1724/0x2ce7:  stat64("/AppleInternal/XBS/.isChrooted\0", 0x7FFF5981CEE8, 0x1)       = -1 Err#2
 1724/0x2ce7:  stat64("/AppleInternal\0", 0x7FFF5981CF80, 0x1)       = -1 Err#2
 1724/0x2ce7:  csops(0x6BC, 0x7, 0x7FFF5981CA10)         = -1 Err#22
 1724/0x2ce7:  csops(0x6BC, 0x7, 0x7FFF5981C2F0)         = -1 Err#22
 1724/0x2ce7:  getrlimit(0x1008, 0x7FFF5981E428, 0x7FFF5981C2F0)         = 0 0
 1724/0x2ce7:  fstat64(0x1, 0x7FFF5981E448, 0x7FFF5981C2F0)      = 0 0
 1724/0x2ce7:  open_nocancel(".\0", 0x0, 0x1)        = 3 0
 1724/0x2ce7:  fstat64(0x3, 0x7FFF5981E3A0, 0x1)         = 0 0
 1724/0x2ce7:  fcntl_nocancel(0x3, 0x32, 0x7FFF5981DF10)         = 0 0
 1724/0x2ce7:  close_nocancel(0x3)       = 0 0
 1724/0x2ce7:  stat64("/usr/local/src/hashcat\0", 0x7FFF5981E310, 0x7FFF5981DF10)        = 0 0
 1724/0x2ce7:  stat64("/\0", 0x7FFF5981C830, 0x7FFF5981DF10)         = 0 0
 1724/0x2ce7:  getattrlist("/usr\0", 0x7FFFBCC25B24, 0x7FFF5981E140)         = 0 0
 1724/0x2ce7:  getattrlist("/usr/local\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = 0 0
 1724/0x2ce7:  getattrlist("/usr/local/bin\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = -1 Err#2
 1724/0x2ce7:  getattrlist("/usr\0", 0x7FFFBCC25B24, 0x7FFF5981E140)         = 0 0
 1724/0x2ce7:  getattrlist("/usr/local\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = 0 0
 1724/0x2ce7:  getattrlist("/usr/local/src\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = 0 0
 1724/0x2ce7:  getattrlist("/usr/local/src/hashcat\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = 0 0
 1724/0x2ce7:  getattrlist("/usr/local/src/hashcat/hashcat\0", 0x7FFFBCC25B24, 0x7FFF5981E140)       = 0 0

**Comment by ghost** [comment]
A clean install of 10.11.5 also did not help.

**Comment by ghost** [comment]
Solved the issue by creating the folder /usr/local/bin
