### ISSUE TITLE
des algorithm ronge key 

### ISSUE THREAD

**Issue by mohsenamd** [hashcat/hashcat#548]
I test crypte des algoritm try for crack but I get ronge result 

hash:96d0028878d58c89:3132333435363738

key: 12345678

but cracked:12345669

**Comment by jsteube** [comment]
With DES there can be many valid keys, because the keyspace is 56 bit not 64 bit. Each of them can be used to correctly decrypt the CT. See here:

```
root@ht:~# perl -e 'print pack ("H*", "3132333435363738")' | openssl enc -des-ecb -K 3132333435363738 | xxd
00000000: 96d0 0288 78d5 8c89 feb9 59b7 d464 2fcb  ....x.....Y..d/.
root@ht:~# perl -e 'print pack ("H*", "3132333435363738")' | openssl enc -des-ecb -K 3132333435363639 | xxd                
00000000: 96d0 0288 78d5 8c89 feb9 59b7 d464 2fcb  ....x.....Y..d/.
```
