### ISSUE TITLE
VCL support revisited

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#55]
@jsteube, did you ever try out VCL using nvidia w/ OpenCL? I figure it would be easy now that you dropped CUDA. Do you have anything left of whatever VCL-specific code you had in there back then? Or perhaps there was no specific code, just an alternate linkage?

**Comment by jsteube** [comment]
I haven't used VCL for a long long while. Is it still maintained? But you're right, could be worth a look. There was specialized VCL code in old oclHashcat but it was mostly for handling binary kernel data instead of the source kernel data. It should (in theory) work out of the box once all OpenCL platforms are supported. I'm currently working on this

**Comment by magnumripper** [comment]
I'll do some experiments and report back.

**Comment by epixoip** [comment]
VCL hasn't been touched in almost 3 years. It's a dead project.

**Comment by th3mechanic** [comment]
I remember SnuCL was brought up in the forums before,  wasn't a fit then maybe it is now  http://snucl.snu.ac.kr/

**Comment by martiGIT** [comment]
VCL still works with oclHashcat 1.31. Never versions get /usr/lib/vcl/libOpenCL.so: no version information available
oclHashcat v2.10 will have support to utilize all OpenCL compatible platforms not just GPU, so possibly VCL too.

**Comment by magnumripper** [comment]
I'm simply hoping the reason it's not been touched in years is that it works like a champ [for nvidia]. I'm assuming they just gave up on AMD's crappy drivers that introduce new bugs with every release. We'll see. The `libOpenCL.so: no version information available` is a benign warning that can be ignored.

I had a look at SnuCL some time ago but it's much less transparent. IIRC you need to compile with MPI and I guess you'd need lots of special code in oclHashcat. For VCL, all magic is in the OpenCL driver layer, not the application.

**Comment by martiGIT** [comment]
yep, but this information is followed by:
oclHashcat64.bin: relocation error: oclHashcat64.bin: symbol clCreateCommandQueueWithProperties, version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference

**Comment by magnumripper** [comment]
That's worse. But using nvidia and latest oHC source, I guess it shouldn't be a problem.

**Comment by magnumripper** [comment]
I did some testing with VCL 1.22 with poor results. And then... wow, just as I was going to ask the developers whether they abandoned the project, they released VCL 1.23 - after 2.5 years of silence. Changelog:
- Works with OpenCL 1.2 or higher.
- Added the following functions of OpenCL version 1.2:
  - clEnqueueFillBuffer()
  - clEnqueueFillImage()
  - clEnqueueMigrateMemObjects()
  - clCreateImage() (no new image types yet beyond OpenCL 1.1)
  - clCreateCommandQueueWithProperties() (no new options yet beyond OpenCL 1.1)
  - clEnqueueMarkerWithWaitList()
  - clEnqueueBarrierWithWaitList()
- Deleted bypass code for some ATI bugs that were fixed.
- Updated the instructions for connecting with Slurm.
- Bug fixes.

Who knows what "Bug fixes" might include, but anyway I will test this ASAP.

**Comment by epixoip** [comment]
VCL is just a grad school project so I assume interest in it will peak and fade as students come and go.

**Comment by magnumripper** [comment]
BTW @jsteube I think you mentioned clKernelArgIsMemoryObject in earlier VCL discussions. I can't remember the details and the trac discussion is gone now. Curiously enough Google hasn't heard of clKernelArgIsMemoryObject... what was that?

**Comment by jsteube** [comment]
Yeah, I remember, that was some special "helper" function. The developer told me to use it for binary kernel. VCL is unable, if it's a binary kernel, to determine if some kernel argument was either a cl_mem or some other datatype.

BTW, for the VCL tests, you can try to force the use of source kernel by setting force_jit_compilation variable to 1500 or so. This is just a hack but should do it for a test. If it turns out to help we could add a commandline option to do it.

**Comment by magnumripper** [comment]
Several problems, mostly not dramatic:
- VCL has a hard time sourcing header files from kernels. It's easy to understand why it's a problem and a variant of it is seen with JtR too. If you pass a path with `-I` in OpenCL build options, that path should be absolute and has to be valid from every node's viewpoint (eg. a shared directory for oclHashcat). Ultimately it's a problem with VCL and only for JIT compilation.
- When run with NV devices (352.39), clCreateContext() fails "CL_DEVICE_NOT_AVAILABLE" after the node's VCL daemon (opencld) segfaults. This seems to be a pure VCL problem.
- When run with AMD devices, Hashcat thinks vendor is "generic" so tries to define its own amd_bytealign() function. This clashes with the real one so the build aborts with error. The problem is you are using the _platform_ vendor - using the _device_ vendor would problably solve a bunch of problems.

I tried a quick hack in oclHashcat so it assumed AMD vendor for VCL, and this introduced another problem: clGetDeviceInfo() -30 (CL_INVALID_VALUE). This is from using proprietrary AMD extension CL_DEVICE_WAVEFRONT_WIDTH_AMD that VCL doesn't support. Hacking that away (allowing failure and falling back to a hardcoded default), VCL basically "works" with AMD although I didn't really test it properly yet. Anyway you will probably need to keep track of platform vendor as well as device vendor and use the "right" one for each operation. For things like "amd_bytealign" you need to look at device vendor [per device], but for using proprietrary parameters you may need to keep using platform vendor (or simply handle errors and fall back to sane defaults).

I may end up with a PR sooner or later. I emailed VCL developers about the `-I` and nvidia issues.

**Comment by jsteube** [comment]
With latest version on GitHub we've switched to device-vendor, as your suggested. I guess it should work now, of couse, you need to make sure the include files exist on all the nodes, as you wrote. Do you think we can close this issue?

**Comment by jsteube** [comment]
Or, due to the changes related to platform and device vendor, can you simply try it again now? Maybe it will work out of the box now.

**Comment by magnumripper** [comment]
I'll try to test this within a week.

**Comment by jsteube** [comment]
Hey @magnumripper any updates on this?

**Comment by magnumripper** [comment]
Nah, but please keep this open. VCL is evolving very _very_ slowly but I do have some (even slower) communication with the authors. Rest assured I'm on this. VCL, when it works, is awesome.

**Comment by magnumripper** [comment]
VCL seems to be *completely* stalled now, at v1.25 which came Oct. 14, 2017. I think we can close this, we could obviously re-open it at some point in the future.
