### ISSUE TITLE
Error when trying to brute force

### ISSUE THREAD

**Issue by ghost** [hashcat/hashcat#551]
i use this command :  hashcat64 -a 3 -m 0 test.txt ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789! &quot;#$%&amp;'()*+,-./:;&lt;=&gt;?@[]^_`{|}~

picture of the error :

http://i.epvpimg.com/G6BWf.pngl

pic of hash :

http://i.epvpimg.com/ksO2d.png

**Comment by ghost** [comment]
ok so now i found that i was using it wrong
the new command is 

hashcat64 -a 3 -m 0 test.txt ?l?u?d?s?a

the error is

Generating bitmap tables with 16 bits.... ERROR: clGetPlatformIDs(): CL_UNKNOWN_ERROR

**Comment by jsteube** [comment]
Invalid use of hashcat, please ask on forum for correct syntax
