### ISSUE TITLE
Support for sha1_salt_pass

### ISSUE THREAD

**Issue by bahrammp** [hashcat/hashcat#554]
Examples hash:salt:
f64eae67783e54cd39d00c3eac301a30856fcf65:kR38NQ_vQRSc_rQ4FnuB 
9c5063c8726b259dc4ece6074d12d094c1d1feea:yD7FvdKF65umfp2Xmjrm

hash:pass 

f64eae67783e54cd39d00c3eac301a30856fcf65:baydog 
9c5063c8726b259dc4ece6074d12d094c1d1feea:tntt1982

Code:

```
function calculate_hash($password, $salt)  { 
$begin="--".$salt."--"; 
$end="--".$password."----"; 
$hash=""; 
for ($round=0; $round<10; $round++)  $hash=sha1($begin.$hash.$end); 
return $hash; 
}
```

https://www.sendspace.com/file/a6893o around 4M hashes.

**Comment by gastonke** [comment]
I've seen quite a bit of these, especially with different rounds up to 100, generally mostly are 10. support

**Comment by kvkenyon** [comment]
seen this in rail apps, would love to see this added.

**Comment by jsteube** [comment]
Implemented: https://github.com/hashcat/hashcat/commit/2bda020c83ea07e6b8d3f807a1deb3a784c86876
