### ISSUE TITLE
hashcat-git-r1904.d6b7b39 - cosmetics

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#564]
Some cosmetics....
Makefile:VERSION_EXPORT          := $Format:%D$
rsults in stdout:
hashcat (ormat:%D$) starting...
Best regards
ZerBea

**Comment by jsteube** [comment]
Hm, doesn't happend here. How do you compile?

**Comment by ZerBea** [comment]
Problem is solved.
It seems to be an arch specific problem (using makepkg and PKGBUILD on a cloned working folder).
I did an rsync -av --exclude="._"  hashcat src
to clone the sourcecode to a "working folder called src ", but excluded "._" and got the version info via
echo "r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)" from the git cloned hashcat folder.

To get the correct version info hashcat requires compiling direct form a git clone because it reads the tag from git info

VERSION_TAG             := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)"|cut -d, -f2|$(SED) -r 's|.\* (\w+/)?([^ ]+)|\2|')

Well, compiling from a source folder without git info, results in an empty string......
hashcat -V
ormat:%D$
