### ISSUE TITLE
Don't use $HEX[deadbabe] for UTF-8

### ISSUE THREAD

**Issue by magnumripper** [hashcat/hashcat#568]
Virtually every user of Hashcat is running a UTF-8 capable terminal, right? Personally I'd much appreciate not getting $HEX[deadcafe] output for perfectly fine UTF-8 strings. This goes for pot files as well as screen output. I can make a PR but I thought we'd discuss details first:

I propose we add a UTF-8 test but keep the "printable ASCII" test, and add some option for which of them to use. I'd personally vote for using the UTF-8 test by default. BTW in some cases where we *know* hashes can't be made from UTF-8 (eg. LM), we'd auto-disable it and fall back to the "printable ASCII" test.

See also #567.

**Comment by jsteube** [comment]
I think I can agree _if_ we find a way to tell if a string is a valid UTF-8 string. For example $HEX[00003030] surely is not. In such a case we should stick to $HEX[...]. Is there any easy way to check this?

**Comment by magnumripper** [comment]
Sure, that's the base of the idea. I already have that code in use elsewhere and it's proven to work like a champ. For extremely short (eg. two bytes) passwords consisting of random binary data there's a slight chance of mis-interpreting - but actually there's not much harm there either. Once you realise this is the case you can always re-encode it. No data is lost! For lengths of 3-4 bytes already, the risk of mis-interpreting is really slim. For real-life passwords, it practically never happens.

Having said that, I think it's a good idea to "blacklist" LM from this default behaviour since we know it's never ever made of UTF-8 but from an "OEM codepage" like CP850. Same goes for 40-bit RC4 brute-force as in eg. oldoffice.

**Comment by jsteube** [comment]
merged, thanks!
