### ISSUE TITLE
Static analysis results

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#578]
I ran clang-analyzer on the project and posted the results here: https://dl.dropboxusercontent.com/u/102011983/hashcat.tar.xz

I can't really fix all of the issues so posting this here.

**Comment by jsteube** [comment]
Good stuff! I think I fixed them all. Please verify and close the issue.

**Comment by neheb** [comment]
Will do so when I get home. I think I'll run 3.9 just in case.

Also on this note, Coverity should be considered. Free for open source projects: https://scan.coverity.com

**Comment by neheb** [comment]
no bugs with 3.9. closing.
