### ISSUE TITLE
Oracle Database 10g hash

### ISSUE THREAD

**Issue by quentinhardy** [hashcat/hashcat#58]
Hello,

[Comment modified the 2016/02/26]
I have noticed there is not a module in hashcat (or oclhashcat) for _cracking_ __Oracle Database__ __hashes <=10g__. 

Is this feature will be appended in hashcat?

Thank you in advance for the response,

**Comment by quentinhardy** [comment]
Notice if we are on Oracle Database>=11g, we should _crack_ the Oracle Database <=10g hash (_password_ column)  first . After, with the clear text password <=10g which is not case sensitive, we should _crack_ the Oracle Database>=11g (case sensitive, _spare4_ column). The second step is very easy..

**Comment by quentinhardy** [comment]
Is a feature for cracking Oracle Database hashes (__<=10g__ type) will be added in hachcat? (as *woraauthbf* http://www.soonerorlater.hu/index.khtml?article_id=513 for example)

**Comment by quentinhardy** [comment]
I have developed quickly a small C program for computing a 10g hash (Oracle Database).

```c
/* Quentin HARDY
 * Example for computing a 10g hash. 
 * This example computes the 10g hash of SYS user ('oracle' password).
 */
#include <openssl/des.h>

char* stoupper( char* s ){
  char* p = s;
  while (*p = toupper( *p )) p++;
  return s;
}

void hashORACLE10g(unsigned char* pPlain, int nPlainLen, unsigned char* username, int nUsernameLen, unsigned char pHash[8]){
		//Information about 10g algorithm: http://marcel.vandewaters.nl/oracle/security/password-hashes
        char ToEncrypt[256];
        char temp[256];
        DES_cblock iv,iv2;
        DES_key_schedule ks1,ks2;
        unsigned char deskey_fixed[]={ 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef};
        int i,j;
        stoupper ((char*) pPlain); // Can be deleted if we are sure that the clear text password is in UPPERCASE
        memset (ToEncrypt,0,sizeof(ToEncrypt));

        for (i=1,j=0; j<nUsernameLen; i++,j++){
                ToEncrypt[i] = username[j];
                i++;
        }
        for (j=0; j<nPlainLen; i++,j++){
                ToEncrypt[i] = pPlain[j];
                i++;
        }
        i=i-1;
        memset (iv,0,8);
        memset (iv2,0,8);
        DES_set_key((DES_cblock*) deskey_fixed, &ks1);
        DES_ncbc_encrypt((unsigned char*) ToEncrypt, (unsigned char*) temp, i, &ks1, &iv, DES_ENCRYPT);
        DES_set_key((DES_cblock*) &iv, &ks2);
        DES_ncbc_encrypt((unsigned char*) ToEncrypt, (unsigned char*) temp, i, &ks2, &iv2, DES_ENCRYPT);
        memcpy (pHash,iv2,8);
}

int main(int argc, char *argv[]){
	//unsigned char hashPwd[17] = "8a8f025737a9097a"; //"oracle" password, ex: https://tobtu.com/oracle.php
	int i = 0;
	unsigned char username[31] = "SYS"; //MUST BE in UPPERCASE !!! not case sensitive for 10g hash
	int usernameLen = 3;
	char cleartextPwd[50] = "ORACLE"; //MUST BE in UPPERCASE !!! not case sensitive for 10g hash
	int cleartextPwdLen = 6;
	unsigned char computedHash[9] = {'\0'};
	hashORACLE10g(cleartextPwd, cleartextPwdLen, username, usernameLen, computedHash);
	printf("[+] 'oracle' hashed with 10g hash (Oracle Database): %02x%02x%02x%02x%02x%02x%02x%02x\n", computedHash[0], computedHash[1], computedHash[2], computedHash[3], computedHash[4], computedHash[5], computedHash[6], computedHash[7]);
	return EXIT_SUCCESS;
}
```
For compiling:
```bash
gcc -o cracker-10g main.o -lcrypto
```
This program is not optimized -:(.
I wish this small source code will help us to implement 10g hash in hashcat -:)

I think we can't use openssl library in hashcat, but this souce code is an example...

Thank you in advance for your help.

**Comment by epixoip** [comment]
I'm sorry, I don't understand what all this is about... You do know that Oracle 10g is already supported (and has been for quite some time) by mode 3100, right?

`epixoip@token:~/oclHashcat-2.01$ ./oclHashcat64.bin -d 1 --quiet -m 3100 -a 3 '8a8f025737a9097a:SYS' oracle
8A8F025737A9097A:SYS:ORACLE
`

**Comment by quentinhardy** [comment]
Thank you for you response.

I agree with you for 10g hashes in __oclhachcat__.
However, I think this feature is not implemented under __hashcat__ (CPU mode). Am I right ?

I have not a computer with a Nvidia GPU, consequently I think I can't use oclhashcat...

Thank you in advance for you response,

**Comment by epixoip** [comment]
Ah, yes, I suppose this is the hashcat repo, not the oclHashcat repo, isn't it :smirk:

But actually you can use oclHashcat with your CPU now, if you grab the latest beta from hashcat.net/beta and install an OpenCL runtime for your CPU.

**Comment by quentinhardy** [comment]
Very __great news__ for oclhashcat & CPU.

I have tried with this driver "OpenCL™ Runtime 14.2 for Intel® CPU and Intel® Xeon Phi™ Coprocessors for Linux* (64-bit)" (https://software.intel.com/en-us/articles/opencl-drivers#philinux) and oclhashcat can be used with my CPU now.

Thank you for your help (and this __excellent project__ :+1:).
