### ISSUE TITLE
RAR3-hp fails with example

### ISSUE THREAD

**Issue by japhar81** [hashcat/hashcat#580]
From https://hashcat.net/wiki/doku.php?id=example_hashes:
`12500	RAR3-hp	$RAR3$*0*45109af8ab5f297a*adbf6c5385d7a40373e8f77d7b89d317`

When I build on Ubuntu 16.04 from master;
```
./hashcat64.bin -m 12500 $RAR3$*0*45109af8ab5f297a*adbf6c5385d7a40373e8f77d7b89d317
hashcat (v3.10) starting...

WARNING: Hash '0*45109af8ab5f297a*adbf6c5385d7a40373e8f77d7b89d317': Line-length exception


ERROR: No hashes loaded
```

**Comment by jsteube** [comment]
You need to quote, because of the $ char. The shell will try to interpret it as a variable otherwise:

```
./hashcat64.bin -m 12500 '$RAR3$*0*45109af8ab5f297a*adbf6c5385d7a40373e8f77d7b89d317'
```
