### ISSUE TITLE
Hashcat 3.10 " BUG feof() " When cracking pwdump output

### ISSUE THREAD

**Issue by johnnyxmas** [hashcat/hashcat#597]
When attempting to crack NTLM (1000) hashes from pwdump-style output, hashcat 3.10 returns BUG feof() and ends. Testing the same hashes in 2.01 & same arguments works with no issues. 

Command: hashcat64.bin -p --show --gpu-temp-disable -a3 -o outfile.txt -m 1000  --username --status hashes.hash

Sample hash which causes the problem (password is Secure123):
username:12345:aad3b435b51404eeaad3b435b51404ee:d6e18fd584c1569b1ba1a8c812ae8c68:::

**Comment by jsteube** [comment]
Can you please retry with 3.20 rc2 ? You can download it from
https://hashcat.net/beta/

**Comment by johnnyxmas** [comment]
I do not experience the problem in 3.20 rc2. It appears to be cracking as expected. Thanks!
