### ISSUE TITLE
Clang analyzer take 2

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#603]
https://dl.dropboxusercontent.com/u/102011983/hashcat.tar.xz

Interestingly enough, VERIFY_PTR also fools clang into thinking it's a file descriptor.

**Comment by jsteube** [comment]
How can I reproduce this?

**Comment by neheb** [comment]
My full command line is,

scan-build -enable-checker alpha.core.BoolAssignment -enable-checker alpha.core.CallAndMessageUnInitRefArg -enable-checker alpha.core.CastSize -enable-checker alpha.core.CastToStruct -enable-checker alpha.core.DynamicTypeChecker -enable-checker alpha.core.FixedAddr -enable-checker alpha.core.IdenticalExpr -enable-checker alpha.core.PointerArithm -enable-checker alpha.core.SizeofPtr -enable-checker alpha.core.TestAfterDivZero -enable-checker alpha.core.TestAfterDivZero -enable-checker alpha.deadcode.UnreachableCode -enable-checker alpha.security.ArrayBound -enable-checker alpha.security.ArrayBoundV2 -enable-checker alpha.security.MallocOverflow -enable-checker alpha.security.ReturnPtrRange -enable-checker alpha.security.taint.TaintPropagation -enable-checker alpha.unix.cstring.BufferOverlap -enable-checker alpha.unix.cstring.NotNullTerminated -enable-checker alpha.unix.cstring.OutOfBounds -enable-checker alpha.unix.Stream -enable-checker alpha.unix.SimpleStream make

As of now, 55 warnings show up. The last two checkers are responsible for the VERIFY_PTR issue. Interestingly enough, if those get disabled, other warnings such as unreachable code ones also disappear.

**Comment by jsteube** [comment]
Yeah I kind of run into the same problems here. For example, I wanted to
examine the divide by zero problem reported (which in the html looks
more like a bug in scan-build itself) but when I'm selecting only
"alpha.core.TestAfterDivZero" the problem disappears. We have to be very
careful with some of this stuff.

**Comment by jsteube** [comment]
I've reduced what scan-build calls "bugs" to a short number. The remaining ones are files handles that need to stay open during the session, so this is not an error.

Please close the issue if that's fine for you.

Thanks for the input anyway, this is good stuff.

**Comment by neheb** [comment]
I actually left out a checker in that command line: alpha.core.PointerSub

The reason was that it complains on strtok_r. Given that nothing can really be done about it, there's no point in trying to "fix" it. However that checker also complains about 3 usages of strcmp. My fix was to switch to strncmp for those.

Other than that, looks good. cppcheck complains less now as well.

**Comment by jsteube** [comment]
Yeah, I also think we can't do anything about the strtok_r() problem. 

I've merged the 3 changes on strncmp() from your PR
