### ISSUE TITLE
macOS X 10.11.6 | WPA/WPA2 --opencl-vector-width issues

### ISSUE THREAD

**Issue by diegodieguex** [hashcat/hashcat#605]
hashcat (v3.10-776-g3b32ad0) starting...

hashcat -a 3 -m 2500 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Cracked

(WPA/WPA2 key: 01411862585)

 Device ID # 2
    Type           : GPU
    Vendor ID      : 2147483648
    Vendor         : AMD
    Name           : AMD Radeon R9 M395 Compute Engine
    Version        : OpenCL 1.2 
    Processor(s)   : 28
    Clock          : 834
    Memory         : 512/2048 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 1.2 (Sep 25 2016 23:31:16)

hashcat -a 3 -m 2500 --opencl-vector=2 example.hccap 014**11**?d?d?d?d?d?d
Status...........: Cracked

hashcat -a 3 -m 2500 --opencl-vector=2 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=4 example.hccap 01411d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=4 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=8 example.hccap 01411d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=8 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=16 example.hccap 01411d?d?d?d?d?d
Status...........: Exhausted

hashcat -a 3 -m 2500 --opencl-vector=16 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Exhausted

**Comment by jsteube** [comment]
Checking, but did you notice 01411d?d?d?d?d?d is an invalid mask?

**Comment by diegodieguex** [comment]
no, sorry maybe It's a typing error. The truth is that the opencl-vector does not work

**Comment by jsteube** [comment]
I've pushed some fix, can you please retry?

**Comment by diegodieguex** [comment]
hashcat -a3 -m2500 -b
Speed.Dev.# 2.....:   111.6 kH/s (75.64ms)

hashcat -a 3 -m 2500 --opencl-vector=2 -b
Speed.Dev.# 2.....:   111.0 kH/s (91.26ms)

hashcat -a 3 -m 2500 --opencl-vector=4 -b
Speed.Dev.# 2.....:    55900 H/s (61.75ms)

hashcat -a 3 -m 2500 --opencl-vector=8 -b
Speed.Dev.# 2.....:    55610 H/s (72.89ms)

hashcat -a 3 -m 2500 --opencl-vector=16 -b
Speed.Dev.# 2.....:    27886 H/s (54.39ms)

**Comment by jsteube** [comment]
OK, looks good, please close the issue if everything is fixed

**Comment by diegodieguex** [comment]
using opencl-vector has decrease the performance. no looks good for me

**Comment by jsteube** [comment]
The goal was to fix the bug, which was that the password was not found.
Now that bug is fixed, so we should close the issue.

The fact that the performance decreases when increasing the vector width
is something else and is caused by the fact that the more wider the
vector is, the more local variables (registers) are required to hold
them. Unless your hardware is designed to run best on a specific vector
width, this always results in a performance loss.

**Comment by diegodieguex** [comment]
ok thanks

hashcat -a 3 -m 2500 --opencl-vector=4 example.hccap 014?d?d?d?d?d?d?d?d
Status...........: Cracked
Speed.Dev.# 2.....:    72466 H/s (11.81ms)

slow... what is the improvement of opencl-vector?
At this point, I think than is better not use it

**Comment by jsteube** [comment]
It depends on GPU. Some GPU needs higher vector width to run at higher
speed, other's do not. Modern GPU do not need it and should stick to 1.

**Comment by diegodieguex** [comment]
AMD Radeon R9 M395 Compute Engine
Memory : 512/2048 MB allocatable

hashcat -a3 -m2500 -b
Speed.Dev.# 2.....: 111.6 kH/s (75.64ms)

do you think than is a good speed? or what should I do?

**Comment by jsteube** [comment]
Yes, it's pretty good for a mobile GPU.

**Comment by diegodieguex** [comment]
but I have an iMac (Retina 5K, 27-inch, Late 2015)

**Comment by jsteube** [comment]
If you want higher speed, you need better GPU. Not certain if you can
simply put in a different GPU into a Mac, maybe need to switch to PC.

Anyway, bug is fixed, please close the issue.

**Comment by diegodieguex** [comment]
I need to switch to PC? 
no many thanks ;-)
