### ISSUE TITLE
Mode 99999 doesn't work

### ISSUE THREAD

**Issue by recon-ng** [hashcat/hashcat#606]
Whenever I invoke hashcat64.exe with "-m 99999" flag I get the following error: ERROR: Invalid hash-type specified.

**Comment by jsteube** [comment]
Are you sure you're using the latest version from GitHub?

The mode 99999 works fine for me.

Please paste full commandline, version number, etc. whatever I need to
reproduce locally

**Comment by recon-ng** [comment]
I was using the pre-compiled version 3.10 available through the hashcat website (binaries) with the following arguments: "-m 99999 -a 3 path_to_file ?a?a?a?a?a?a?a?a". I suppose the issue will go away once I pull the latest and build from source. I'll let you know how that goes when I succeed.

**Comment by jsteube** [comment]
Binaries are here: https://hashcat.net/beta/

**Comment by recon-ng** [comment]
Yay! Works! Thnx!
