### ISSUE TITLE
hashcat (v3.10-800-g7ca6a45) crash:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#608]
After update from hashcat (v3.10-756-g1c82cc9) to hashcat (v3.10-800-g7ca6a45)
hashcat crashes with this error:

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  156 (NV-CONTROL)
  Minor opcode of failed request:  3 ()
  Value in failed request:  0x17
  Serial number of failed request:  15
  Current serial number in output stream:  16

uname -r     : 4.8.8-2
nvidia driver: 375.20-1

Best regards
ZerBea

**Comment by jsteube** [comment]
Please post ./hashcat -I output and clinfo output

**Comment by ZerBea** [comment]
./hashcat -I
hashcat (v3.10-800-g7ca6a45) starting...
OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 8.0.0

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GTX 970
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 13
    Clock          : 1228
    Memory         : 1016/4065 MB allocatable
    OpenCL Version : OpenCL C 1.2 
    Driver Version : 375.20

**Comment by ZerBea** [comment]
./clinfo:
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 8.0.0
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce GTX 970
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  375.20
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Topology (NV)                            PCI-E, 01:00.0
  Max compute units                               13
  Max clock frequency                             1228MHz
  Compute Capability (NV)                         5.2
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              4263182336 (3.97GiB)
  Error Correction support                        No
  Max memory allocation                           1065795584 (1016MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        212992
  Global Memory cache line                        128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 256
    Max number of write image args                16
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     9
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 No
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.9
  ICD loader Profile                              OpenCL 2.1

**Comment by ZerBea** [comment]
During startup of hashcat I got this 2 warnings:

nvmlDeviceSetPowerManagementLimit(): Insufficient Permissions
XNVCTRLQueryTargetAttribute(NV_CTRL_GPU_COOLER_MANUAL_CONTROL) failed

Then hashcat runs awhile
...
Time.Started.......: Tue Nov 22 09:41:38 2016 (48 secs)
Time.Estimated...: Tue Nov 22 09:42:37 2016 (11 secs)
...
and crashed
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  156 (NV-CONTROL)
  Minor opcode of failed request:  3 ()
  Value in failed request:  0x17
  Serial number of failed request:  15
  Current serial number in output stream:  16

Best regards
ZerBea

**Comment by jsteube** [comment]
I did some changes to xnvctrl handling with a recent version, however I've tested it on my local X11 installation. I'm using 375.20 as well, it's the latest stable version. 

The nvmlDeviceSetPowerManagementLimit requires root permission, but it doesn't hurt if you don't use it. It's mostly important for modern high end GPU to disable over-aggressive powersave features.

The XNVCTRLQueryTargetAttribute() however is kind of suspicious. Do you run hashcat via ssh? Did you add the required access control to X11 so that an external program can query X11?

**Comment by ZerBea** [comment]
Installation is arch minimal xfce desktop.
Hashcat is not running via ssh.
Hashcat is able to connect and query X11.
Hashcat v3.10-800-g7ca6a45 runs awhile and crashed.
Test conditions v3.10-756-g1c82cc9 <->  v3.10-800-g7ca6a45 are the same, each on a clean system.
I'll go back in git history to see which commit causes the issue.

**Comment by ZerBea** [comment]
Everything is fine up to version v3.10-796-g9e1574a
Version v3.10-797-g06c1d4a and above crashed.

**Comment by jsteube** [comment]
I've pushed some change. Since I can not reproduce your error (and I tried really hard) it's almost impossible to fix it. Please check if the error still occurs and, more important, if the program crashed. IF it crashes, how does it crash? Can you send me a corefile?

**Comment by ZerBea** [comment]
No more crash, but

First run:
./hashcat -m 2500 --benchmark

hashcat (v3.10-801-gfe3398f) starting...
XNVCTRLQueryTargetAttribute(NV_CTRL_GPU_COOLER_MANUAL_CONTROL) failed
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 156 (NV-CONTROL)
Minor opcode of failed request: 3 ()
Value in failed request: 0x17
Serial number of failed request: 15
Current serial number in output stream: 16

Second run:
./hashcat -m 2500 --benchmark --gpu-temp-disable
hashcat (v3.10-801-gfe3398f) starting in benchmark mode...
nvmlDeviceSetPowerManagementLimit(): Insufficient Permissions
OpenCL Platform #1: NVIDIA Corporation

    Device #1: GeForce GTX 970, 1016/4065 MB allocatable, 13MCU
    Hashtype: WPA/WPA2
    Speed.Dev.#1.....: 172.9 kH/s (76.77ms)
    Started: Tue Nov 22 17:09:14 2016
    Stopped: Tue Nov 22 17:09:21 2016

using --gpu-temp-disable and everything works......
Maybe a variable exceeded....

**Comment by jsteube** [comment]
Can you please post xorg.conf

**Comment by ZerBea** [comment]
arch is using xorg.conf.d:

20-nvidia.conf :
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
	Option         "NoLogo" "1"
	Option         "Interactive" "False"
EndSection

**Comment by jsteube** [comment]
I see the problem, I'll write a patch

**Comment by jsteube** [comment]
OK, try again

**Comment by ZerBea** [comment]
Fixed....
Well done.
Best regards

**Comment by cristiaan3003** [comment]
I don't see the solution. Could you post solution here, please?

**Comment by neheb** [comment]
solution is to enable CoolBits in xorg.conf
