### ISSUE TITLE
PBKDF2(Atlassian) supported 

### ISSUE THREAD

**Issue by dibiloid** [hashcat/hashcat#611]
Hi.
Add please this algorithm. PBKDF2(Atlassian)
I am ready to donation ;)

http://pythonhosted.org/passlib/lib/passlib.hash.atlassian_pbkdf2_sha1.html

**Comment by jsteube** [comment]
I think you can simply convert this into -m 12000

**Comment by dibiloid** [comment]
please show how it can be done )

**Comment by philsmd** [comment]
This is an example hash:
{PKCS5S2}OHyYon6Cl9y842mEUkgeCsH0HkipUYNNLjqotyOE0wF1oywazi6sm9kDASYw0xzF:hashcat

it can be generated like this (perl):
```
#!/usr/bin/env perl

use strict;
use warnings;

use MIME::Base64;
use Crypt::PBKDF2;

my $w = "hashcat";
my $s = pack ("H*", "387c98a27e8297dcbce3698452481e0a");

my $a = Crypt::PBKDF2->new
(
  hasher     => Crypt::PBKDF2->hasher_from_algorithm ('HMACSHA1'),
  iterations => 10000,
  output_len => 32,
);

my $h = $a->PBKDF2 ($s, $w);

my $b = encode_base64 ($s. $h);
$b =~ s/[\r\n]//g;

print "{PKCS5S2}" . $b . "\n";
```

python (passlib method):
```
#!/usr/bin/env python

from passlib.hash import atlassian_pbkdf2_sha1
from binascii import unhexlify

w = "hashcat"
s = unhexlify ("387c98a27e8297dcbce3698452481e0a")

a = atlassian_pbkdf2_sha1.using (salt=s)

#print a.verify (w, "{PKCS5S2}OHyYon6Cl9y842mEUkgeCsH0HkipUYNNLjqotyOE0wF1oywazi6sm9kDASYw0xzF")

print a.hash (w);
```

To convert it (manually) to the hashcat format (-m 12000 = PBKDF2-HMAC-SHA1):
- we know we have always 10000 iteration
- we know that the salt has a fixed length of 16
- we need to base64 decode the whole string (lets say into hexadeximal):
```
$ echo OHyYon6Cl9y842mEUkgeCsH0HkipUYNNLjqotyOE0wF1oywazi6sm9kDASYw0xzF | base64 -d | xxd -p
387c98a27e8297dcbce3698452481e0ac1f41e48a951834d2e3aa8b72384d30175a32c1ace2eac9bd903012630d31cc5
```
- use the first 32 hex chars (or 16 bytes) and base64 encode them:
```
$ echo 387c98a27e8297dcbce3698452481e0a | xxd -p -r | base64
OHyYon6Cl9y842mEUkgeCg==

```
- use the remaining bytes as input to base64 (they will form the actual "hash"):
```
$ echo c1f41e48a951834d2e3aa8b72384d30175a32c1ace2eac9bd903012630d31cc5 | xxd -p -r | base64
wfQeSKlRg00uOqi3I4TTAXWjLBrOLqyb2QMBJjDTHMU=
```
- and combine it all together:
sha1:10000:OHyYon6Cl9y842mEUkgeCg==:wfQeSKlRg00uOqi3I4TTAXWjLBrOLqyb2QMBJjDTHMU=

- we can try to crack it with hashcat:
```
$ ./hashcat -m 12000 -a 3 'sha1:10000:OHyYon6Cl9y842mEUkgeCg==:wfQeSKlRg00uOqi3I4TTAXWjLBrOLqyb2QMBJjDTHMU=' ?lashcat
sha1:10000:OHyYon6Cl9y842mEUkgeCg==:wfQeSKlRg00uOqi3I4TTAXWjLBrOLqyb2QMBJjDTHMU=:hashcat
```

Actually, it should be pretty easy to both convert the hashes manually (or with a simple script) or implement a simple parser into hashcat.

Is anyone still interested in this support ? Should hashcat add a parser for this type of hashes?

**Comment by philsmd** [comment]
@dibiloid could you please test with the current beta version (https://hashcat.net/beta/ , beta 3.40-rc12 or any later version)?
