### ISSUE TITLE
-m 11600 running error with example hash

### ISSUE THREAD

**Issue by pascalqq** [hashcat/hashcat#612]
**I'm using  GeForce GTX 960 with 375.70 driver. When I test -m 11600, I got this:**

OpenCL Platform #1: NVIDIA Corporation
======================================
- Device #1: GeForce GTX 960, 1024/4096 MB allocatable, 8MCU
- Device #1: WARNING! Kernel exec timeout is not disabled, it might cause you errors of code 702
             See the wiki on how to disable it: https://hashcat.net/wiki/doku.php?id=timeout_patch

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

- Device #1: Kernel m11600.f82c639f.kernel not found in cache! Building may take a while...
- Device #1: Kernel markov_le.f82c639f.kernel not found in cache! Building may take a while...

- Device #1: Kernel amp_a3.f82c639f.kernel not found in cache! Building may take a while...

ATTENTION!
  The wordlist or mask you are using is too small.
  Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
  The cracking speed will drop.
  Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted

[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit =>

**ERROR: clEnqueueReadBuffer(): CL_INVALID_VALUE**

Session.Name...: hashcat
Status.........: Exhausted
Input.Mode.....: Mask (123?d?d?d) [6]
Hash.Target....: $7z$0$19$0$$8$33265f3da45446d800000000000...
Hash.Type......: 7-Zip
Time.Started...: Wed Nov 23 14:09:11 2016 (1 sec)
Speed.Dev.#1...:      588 H/s (0.31ms)
Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.......: 1000/1000 (100.00%)
Rejected.......: 0/1000 (0.00%)

Started: Wed Nov 23 14:09:11 2016
Stopped: Wed Nov 23 14:09:19 2016

**and post the clinfo:**

Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 CUDA 8.0.0
  Platform Name:				 NVIDIA CUDA
  Platform Vendor:				 NVIDIA Corporation
  Platform Extensions:				 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts

  Platform Name:				 NVIDIA CUDA
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Device ID:					 4318
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 64
  Max work group size:				 1024
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Max clock frequency:				 1278Mhz
  Address bits:					 14757395255531667488
  Max memory allocation:			 1073741824
  Image support:				 Yes
  Max number of images read arguments:		 256
  Max number of images write arguments:		 16
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 4096
  Max image 3D height:				 4096
  Max image 3D depth:				 4096
  Max samplers within kernel:			 32
  Max size of kernel argument:			 4352
  Alignment (bits) of base address:		 4096
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 128
  Cache size:					 131072
  Global memory size:				 4294967296
  Constant buffer size:				 65536
  Max number of constant args:			 9
  Local memory type:				 Scratchpad
  Local memory size:				 49152
  Error correction support:			 0
  Profiling timer resolution:			 1000
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 01133358
  Name:						 GeForce GTX 960
  Vendor:					 NVIDIA Corporation
  Driver version:				 375.70
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 CUDA
  Extensions:					 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts

Cheers mate!

**Comment by jsteube** [comment]
Please retry with latest beta: https://hashcat.net/beta/ or compile from source using GitHub master.

I've fixed something with this commit: https://github.com/hashcat/hashcat/commit/90f0aec707532ba6a9d96c54a46fa6a0f5d4d065

Please close the issue if fixed. Thanks for reporting!

**Comment by pascalqq** [comment]
Tks for the fix. It works fine now.

But still a question, why cracked with the statuts exhausted? Like this:

$7z$0$19$0$$8$......:123456
Session..........: all
Status...........: **Exhausted**
Hash.Type........: 7-Zip
Hash.Target......: $7z$0$19$0$$8$33265f3da.......
........

**Comment by jsteube** [comment]
Because with 7-Zip there's a chance hashcat emits a false positive. Therefore we must let hashcat continue to crack more passwords so you can try all the possible outputs.

**Comment by pascalqq** [comment]
All right, TKS.
