### ISSUE TITLE
hashcat64  -a 0 -m 3300 running error

### ISSUE THREAD

**Issue by su-coder** [hashcat/hashcat#614]
D:\tools\hashcat-3.10>hashcat64 -a 0 -m 3300 sun.txt example.dict
hashcat (v3.10) starting...

Usage: hashcat [options]... hash|hashfile|hccapfile [dictionary|mask|directory]...

Try --help for more help.

D:\tools\hashcat-3.10>

-m 3300  has been lost in hashcat 3.10 ?

**Comment by jsteube** [comment]
Yes, mode 3300 was not transported to hashcat v2.xx. No one yet noticed, you're the first. Use hashcat-legacy please or open a new issue requesting the addition.
