### ISSUE TITLE
hashcat (v3.10-820-g899413f) status display ‎confusing

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#616]
After update from hashcat (v3.10-809-g7fe575e) to hashcat (v3.10-820-g899413f) 
the status display is very confusing

hashcat (v3.10-820-g899413f) starting ...

Hash.Target......: test.hccap
Time.Started.....: Sat Nov 26 15:44:08 2016 (1 sec)
Time.Estimated...: Sat Nov 26 18:10:54 2016 (2 hours, 26 mins)
...
Hash.Target......: test.hccap
Time.Started.....: Sat Nov 26 15:44:08 2016 (9 secs)
Time.Estimated...: Sat Nov 26 22:19:22 2016 (6 hours, 35 mins)
...
Hash.Target......: test.hccap
Time.Started.....: Sat Nov 26 15:44:08 2016 (31 secs)
Time.Estimated...: Sat Nov 26 18:12:07 2016 (2 hours, 27 mins)
...
Hash.Target......: test.hccap
Time.Started.....: Sat Nov 26 15:44:08 2016 (1 min, 0 secs)
Time.Estimated...: Sat Nov 26 15:45:08 2016 (0 secs)
Input.Base.......: File (/tmp/tstsrt.tmp)
...
Started: Sat Nov 26 15:44:08 2016
Stopped: Sat Nov 26 15:45:08 2016

Best regards
ZerBea

**Comment by jsteube** [comment]
Maybe rejects?

**Comment by jsteube** [comment]
I found some problem, please retry

**Comment by ZerBea** [comment]
Fixed.....
Testfile doesn't contain "words to be rejected".
