### ISSUE TITLE
performance degradation in 2.00 for md5

### ISSUE THREAD

**Issue by gituser** [hashcat/hashcat#64]
Hi.

First of all thanks a lot for making hashcat open-source.

I noticed there is a slight performance issue for some reason on v2.00 (latest master) for md5:
hashcat-0.47.AVX.bin: **29.66M** words for md5 mask bruteforce attack
hashcat-2.00 (compiled with -msse2 -msse3 -mavx): **27.10M** words for md5 mask bruteforce attack.

I didn't test all modes throughouly but it might be possible that in wordlist attack or any other mode there is same degradation.

EDIT: also possible this degradation introduced in some of the versions in between of 0.47 -> 2.00, e.g. in 0.48 or in 0.49 or 0.50.

**Comment by jsteube** [comment]
hashcat will be deprecate soon, please switch over to oclHashcat which has support for CPU now. You just need to install an OpenCL runtime for your CPU but you get a huge performance increase, over multiple times.

**Comment by gituser** [comment]
@jsteube i've compiled oclHashcat from latest git, but I'm getting this:

./oclHashcat --opencl-device-types 1 -b
oclHashcat v2.01 (g298e9a3) starting in benchmark-mode...
ERROR: clGetPlatformIDs() : -1001 : CL_UNKNOWN_ERROR

I don't have any GPU (except built-in intel I think).

How to solve this?

Thanks
