### ISSUE TITLE
unknown hash_mode

### ISSUE THREAD

**Issue by LichFaker** [hashcat/hashcat#65]
I want to get the doc file's password, and I use `office2john.py` to get the hash code, it is `oldoffice$1`.But when I try to crack, it always hint unknown hash_mode error. 
![image](https://cloud.githubusercontent.com/assets/5850082/14843209/e234149c-0c80-11e6-9314-19d660854dc7.png)

**Comment by jsteube** [comment]
You need oclHashcat, not hashcat
