### ISSUE TITLE
support for recovering RAR (archive) passwords

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#68]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | minga |
| Title: | ocl support for RAR |
| Ticket number: | 159 |
| Date reported: | 2013-06-14T18:22:56+02:00 |
| **Description**: | In the business world, OCL support for encrypted RAR files would be amazing. |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | Rolf | I support this feature request, but WinRAR v5 is emerging, with a different encryption/hashing scheme. <br><br> Also, some archives may use file name encryption, which again alters the scheme. <br><br> All of this should be taken into consideration. |
| 2. | Kucikuc24 | Would be useful. +1 |
| 3. | Rolf | This will help : ​[Archive format description](http://www.rarlab.com/technote.htm) and ​[unrar sources](http://www.rarlab.com/rar/unrarsrc-5.0.10.tar.gz). |
| 4. | Rolf | Okay, WinRAR 5 was released. |
| 5. | Rolf | I've talked to IvanG about WinRARv5 encryption, he said it's pretty straightforward: it uses PBKDF2/SHA256 for hash computation. <br><br> He added it was made extra simple, so, once oclhc gets all the data extracted from the archive (the hash and precise iteration count), it can attack the hash itself without the need to decrypt any actual data. <br><br> But this is only the latest version. <br><br> Previous versions used variable (based on pw length) iteration count and other shenanigans. <br><br> [​This may help](http://www.crark.net/Cuda-OpenSrc.rar) |

**Comment by jsteube** [comment]
Update: Support for RAR3 (with header encryption) was added. RAR3 (without header encryption) and RAR5 is still missing

**Comment by magnumripper** [comment]
RAR5 is simpler than RAR3, it's standard PBKDF2-SHA256 and no UTF-16.

**Comment by jsteube** [comment]
Cool, it was indeed easy to add. Pushed with https://github.com/hashcat/oclHashcat/commit/f0a84a2410fe5832ee120c3cbe62a84dca42b511

(Also a good example of how to add new hashes, should do a writeup on it)

Now it's just RAR3 without header encryption missing.

**Comment by Fist0urs** [comment]
@jsteube this issue can be closed then?

**Comment by jsteube** [comment]
Almost, there's still a variant which is not supported: RAR3 + not-encrypted headers.

**Comment by japhar81** [comment]
I'd like to take a stab at the RAR3 + unencrypted headers, but I can not for the life of me find any info on what the algorithm is.. has anyone gotten anywhere in figuring out what actually needs to be done?

**Comment by magnumripper** [comment]
Have a look at JtR for complete code, including early-rejection code that is required for speed. You also need a lot of unrar-code, we nicked it from clamAV. You probably need to do all but the 256K SHA-1 on CPU side.

**Comment by jsteube** [comment]
Since rar3-hp and rar5 was added, there's only rar3-p missing. Therefore this issue is continue on a dedicated issue for this mode: https://github.com/hashcat/hashcat/issues/1334
