### ISSUE TITLE
support for java KeyStore hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#76]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | crackall |
| Title: | java keys store |
| Ticket number: | 451 |
| Date reported: | 2014-05-25T16:54:10+02:00 |
| **Description**: | please add [support to] brute java keys[:]<br> [oracle.com - keytool - Key and Certificate Management Tool](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html) |

**Comment by jsteube** [comment]
please add more descriptions[:] like algorithm, example hashes, etc

**Comment by julienbedard** [comment]
John jumbo added the code to his repo.

https://fossies.org/dox/john-1.8.0-jumbo-1/keystore2john_8py_source.html
https://fossies.org/dox/john-1.8.0-jumbo-1/keystore2john_8c.html

Algorith is SHA1

Example hash are in attachment from john the ripper.

[hash_reference.zip](https://github.com/hashcat/hashcat/files/394232/hash_reference.zip)

**Comment by jsteube** [comment]
support added with commit https://github.com/hashcat/hashcat/commit/7e5b8d3f25821c7c8707190f074739c9370554b4
