### ISSUE TITLE
support for NETLM hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#78]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | Picch |
| Title: | Requesting LAN Manager (LM Hash) & NETLM Hash Addition |
| Ticket number: | 471 |
| Date reported: | 2014-06-20T23:36:15+02:00 |
| **Description**: | Hey Folks,<br>I'm wondering about the feasibility of adding support for LM and NETLM hashes? I know their counterparts NT and NTLMv1/2 are already implemented but we've been running into cases while performing pentests where it would be more practical to attack the LM side of things given the weaknesses in the algorithm (and rainbow tables are going to be more trouble than their worth.)<br><br>I have a sample LM hash that I've created and stole an NETLM hash example from ticket 98 [old trac ticketing system]:<br>Password: HASHCAT2014<br>LabAccount:1012:299bd128c1101fd615c5627ce31416b2:d311c413a01dffad3ffd6f57bfe271d7:::<br><br>In the hash above the data is as follows: \<userAcct\>:\<uid\>:\<LM Hash\>:\<NT Hash\>:::<br>Password: PASSWORD1<br>test::LAB:76365E2D142B5612CD10E1B93D342334E8FD283ECD7B9170:8614B8A84404B1C0333C8875A22BC10690BBF6A7EDCF549D:1122334455667788<br>In the hash above the data is as follows: \<userAcct\>::\<Domain\>:\<NETLM Hash\>:\<NETNTLMv1 hash\>:\<Challenge\><br><br>I'm more than happy to provide any help that I can.<br><br>Thanks!<br>Garret Picchioni |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | philsmd | Note: You can crack the first (299bd128c1101fd615c5627ce31416b2) w/ -m 3000, output is: 299bd128c1101fd6:HASHCAT2014<br><br>Note2: You can crack the second one (d311c413a01dffad3ffd6f57bfe271d7) w/ -m 1000, output is: d311c413a01dffad3ffd6f57bfe271d7:hashcat2014 |
| 2. | Picch | Doh, didn't realize -m 3000 was there, apologies for that. NETLM would still be a nice addition though. |
| 3. | atom | let's see if there [are] more request[s]. anyone else interes[~~s~~]ted in netlm please add a +1 here |
| 4. | Izzet | +1 |

**Comment by bandrel** [comment]
+1

**Comment by epixoip** [comment]
Cracking NetLM is already supported via -m 3000 and -m 1000, this would be just adding support for this particular format string (like when we added pwdump format.)

**Comment by philsmd** [comment]
I think we can close this ticket since both of these types of hashes can already be natively loaded:

for -m 1000
```
$ cat 1000_3000.hash 
LabAccount:1012:299bd128c1101fd615c5627ce31416b2:d311c413a01dffad3ffd6f57bfe271d7:::
$ ./hashcat -m 1000 -a 3 1000_3000.hash hashcat2014
d311c413a01dffad3ffd6f57bfe271d7:hashcat2014
```
for -m 3000
```
$ cat 1000_3000.hash 
LabAccount:1012:299bd128c1101fd615c5627ce31416b2:d311c413a01dffad3ffd6f57bfe271d7:::
$ cat dict.xt
HASHCAT2014
$ ./hashcat -m 3000 1000_3000.hash dict.txt
299bd128c1101fd6:HASHCAT
15c5627ce31416b2:2014
```
for -m 5500
```
$ ./hashcat -m 5500 -a 3 'test::LAB:76365E2D142B5612CD10E1B93D342334E8FD283ECD7B9170:8614B8A84404B1C0333C8875A22BC10690BBF6A7EDCF549D:1122334455667788' Password1
test::LAB:76365e2d142b5612cd10e1b93d342334e8fd283ecd7b9170:8614b8a84404b1c0333c8875a22bc10690bbf6a7edcf549d:1122334455667788:Password1
```

There is nothing that needs to be converted or changed, the formats are already detected by hashcat and can be cracked AS-IS.
Is there anything missing here? Can we close this issue?

**Comment by philsmd** [comment]
I had a further look @ NETLM and tried to understand how this related to the hashes/features requested within this issue (that was imported by me from the old trac).
I came to the conclusion that the examples and description within the trac issue do not really correspond to the title of this issue, i.e. the description and examples are all about LM and NetNTLM which hashcat already support.
NETLM instead is something that hashcat currently does not support. There are two versions:
1. NETLM: LM Challenge/Response (see jtr code: https://github.com/magnumripper/JohnTheRipper/blob/8bcaddef35f703c47367fad612e473061459b156/src/NETLM_fmt_plug.c)
2. NETLMv2: LMv2 Challenge/Response (see jtr code: https://github.com/magnumripper/JohnTheRipper/blob/8bcaddef35f703c47367fad612e473061459b156/src/NETLMv2_fmt_plug.c)

So my conclusion is that NETLM and NETLMv2 are different algorithms which hashcat currently does not support, but since the example and description within this issue is all about LM and NETNTLMv2, I would say we close this issue for now.

If somebody wants to requests NETLM and NETLMv2 in the future within a new github issue, she should also provide some examples of NETLM/NETLMv2 and example code (like the one from jtr).
Thanks
