### ISSUE TITLE
longer salt length support for sha1($pass.$salt)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#79]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.
---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | hithron |
| Title: | Increase the salt length. |
| Ticket number: | 491 |
| Date reported: | 2014-08-11T16:14:21+02:00 |
| **Description**: | Hello.<br>I would like to see the salt length increase. At least on SHA1($pass.$salt).<br><br>As i have a substantial amount of hashes that needs cracking. It's more and more common that i see developers face-rolling the keyboard to set a salt. A new limit on length to 35-40 on the most common algorithms? <br><br> Hope you will take this under consideration. |
---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | The current limit is 32 chars. Can you be a bit more specific which application uses longer salts?<br><br>In that case, maybe we can make a specific mode for it. Because changing length in generic types will decrease performance on all algorithm that use gener[ic] types... |
| 2. | hithron | Often its custom build web applications that i have seen this pattern in, but frameworks like Cakephp also starting to use a long string as salt.<br><br>A mode would be great, to solve my problem but this seems to be a problem that comes up once in a while.<br>But if a mode for SHA1($pass.$salt) would shut me up for a while.<br><br>​[hashcat forum link 1](https://hashcat.net/forum/thread-3477.html), [hashcat forum link 2](https://hashcat.net/forum/thread-575.html) |

**Comment by jsteube** [comment]
https://github.com/hashcat/hashcat/issues/565
