### ISSUE TITLE
support for Inno Setup hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#85]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | lucmc |
| Title: | hash type request: Inno Setup |
| Ticket number: | 574 |
| Date reported: | 2015-02-10T09:22:33+01:00 |
| **Description**: | Inno Setup is an installation utility that has the ability to encrypt files with RC4 and request password during installation. The password hash/salt can be easily extracted with a tool like: InnoUnpack.<br><br>There are two versions of the algo:<br>InnoSetup < 5.3.9:<br>hash = md5('PasswordCheckHash', salt, 'PASSWORD')<br><br>InnoSetup >= 5.3.9:<br>hash = sha1('PasswordCheckHash', salt, 'PASSWORD')<br><br>Both the PASSWORD and PasswordCheckHash are strings, however the salt is parsed in hex (from string).<br><br>Example data:<br>algo - md5<br>hash - 32cba66270ec6a9ecff50a28e1e01ab4<br>salt - e5d7af4f0e6ed7bf (hex)<br>pass - aaa |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | philsmd | The algorithm here is just:<br>-m 20 = md5 ($salt.$pass) or<br>-m 120 = sha1 ($salt.$pass)<br><br>since one can easily simplify that<br>$salt = 'PasswordCheckHash', salt<br><br>Therefore (and I tested it), you can simply crack these hashes like this:<br>$ < hash cat<br>32cba66270ec6a9ecff50a28e1e01ab4:50617373776f7264436865636b48617368e5d7af4f0e6ed7bf<br>$ ./oclHashcat64.bin -m 20 --hex-salt hash -a 3 aaa<br>32cba66270ec6a9ecff50a28e1e01ab4:50617373776f7264436865636b48617368e5d7af4f0e6ed7bf:aaa<br><br>The only thing some users don't know is that one needs to use --hex-salt if (some part of) the salt should be converted from hex to binary.<br><br>So basically, I converted the whole salt like this:<br>$ echo -n PasswordCheckHash$(echo -en "\xe5\xd7\xaf\x4f\x0e\x6e\xd7\xbf") | xxd -p<br>50617373776f7264436865636b48617368e5d7af4f0e6ed7bf<br>the format for -m 20 and -m 120 is simply hash:salt, so you use the hexadecimal salt here + use the --hex-salt switch.<br><br>The example was for -m 20, but the same holds for -m 120.<br>Note: even if it is already "supported" to crack those hashes (in the way described above), we may still consider to add a new format, if there are enough request/up votes.<br><br>The "only" thing that might change with a new format is that it might get a little bit more convenient to manage the hash list (i.e. it won't be needed anymore to hex-convert the salt).<br><br>My questions:<br>\- does this solution work for you?<br>\- do you think devs still need to add/implement a new hash type for this? Any more convincible arguments to implement this new hash type nevertheless?<br><br>Thx |
| 2. | lucmc | Thanks for the fast response.<br><br>Yes, both sha1/md5 are indeed working with the latest version<br><br>I realize this is more of a user-friendly change, rather than actually new algo. As such its not something really necessary.<br><br>However, here's my argument why it should be added:<br>\- Unless you start looking through the source you would never know that you have to prepend 'PasswordCheckHash', because the installer actually uses 'PasswordCheckHash' only for verification. The actual decryption just uses md5(salt, pass).<br>\- Easy-of-use: you can just input: hash:salt as strings without formatting or parsing |

**Comment by jsteube** [comment]
Please use the generic hash mode as philsmd described, this will work fine.
