### ISSUE TITLE
LM hash reported as uncracked although cracking successful

### ISSUE THREAD

**Issue by hgbstu** [hashcat/hashcat#889]
When hashcat successfully cracks an LM hash it reports the hash as left.
As for my understanding successfully cracked hashes should not be printed when calling hashcat with the "--left" option.

### How to reproduce:
content of lm.hash:
> 01FC5A6BE7BC6929AAD3B435B51404EE

run hashcat

> hashcat64.bin -m 3000 -a 3 lm.hash

after successfull cracking, this is the content of the potfile
> 01fc5a6be7bc6929:TEST

running following command
>hashcat64.bin lm.hash --potfile-path=hashcat.potfile --left

prints this output
> 01fc5a6be7bc6929aad3b435b51404ee

Tested with hashcat v3.10, v3.20rc4 on Ubuntu 14.04.5

**Comment by jsteube** [comment]
Is fixed, new betas up. Thanks for report!
