### ISSUE TITLE
support for MS-CHAPv2

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#89]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | rezca |
| Title:                                  | Add support for MS-CHAPv2 in oclHashcat |
| Ticket number:                  | 613 |
| Date reported:                  | 2015-04-16T17:14:10+02:00 |
| **Description**:                 |  I know this has been suggested before in the forums, but I'd like to request support for recovering the MD4 hash from an MS-CHAPv2 challenge/response in oclHashcat.<br><br>The problem is reduced to a single DES bruteforce by the good people at [Cloud Cracker](https://www.cloudcracker.com/blog/2012/07/29/cracking-ms-chap-v2/)<br>They're using dedicated hardware to accomplish this in less than a day, as the previous link details.<br><br>Further it has been [shown](http://home.deib.polimi.it/barenghi/files/ITNG2010.pdf) that it is cost effective to use CUDA vs dedicated hardware for DES key brute-forcing already in 2010.<br><br>This [can] already be accomplished using [openssl - github - heipei engine-cuda](​https://github.com/heipei/engine-cuda), however we know oclHashcat already has a DES implementation, and hashcat has nice features like pw-skip and pw-limit for space splitting. It's also unclear whether the openssl implementation would utilize all cores since it has very different goals.<br><br>It would be great to allow researchers to do this using own resources (including EC2), at the very least to evaluate the cost-benefit of using a service like Cloud Cracker.<br><br>Thanks! |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | Once we have bitslice for DES it could be done with a single hd290x in ~ 100, or faster if you run multiple 290x in parallel which is supported with oclHashcat. |

**Comment by jsteube** [comment]
Update: We do have bitslice now

**Comment by thesle3p** [comment]
Any updates on this?

**Comment by p1pkin** [comment]
that information / data required ?
if you mean input data format - I can provide [chapcrack](https://github.com/moxie0/chapcrack) "token" description.

**Comment by magnumripper** [comment]
This is the same algorithm as the already implemented C/R NTLMv1 and has same opportunity to BF the 3rd DES and then run crazy fast. Only the input parsing differs.

**Comment by epixoip** [comment]
To clarify, this ticket is only for recovering the MD4 hash from an MS-CHAP hash; if you're looking to just crack MS-CHAP directly, this algorithm is already supported via -m 5500. https://hashcat.net/forum/thread-5052.html

**Comment by p1pkin** [comment]
@magnumripper  can you please point to NTLMv1 input format ?
cloudcracker have it base64 encoded 26bytes, 8bytes plain data and 2x DES encrypted data using 2x different keys, followed by least significant 2 bytes of MD4 hash recovered by chapcrack tool itself.

actually I'm looking for the way to BF random unknown DES keys, having decrypted and encrypted data. can you plz give advice in what form input values must be feed to oclhashcat ?

**Comment by magnumripper** [comment]
@p1pkin not sure what you mean but see https://hashcat.net/forum/thread-2563.html (referenced in the thread epixoip mentioned). But if you're looking for finding a full 56-bit DES key I'm afraid 5500 wont help you at all.

**Comment by p1pkin** [comment]
@magnumripper thanks, you right, 5500 is not helpful at all for my task.
as I see in 245301c9b444616aa083ef8fda83decbc690f4c1 on recent hardware DES BF speed is ~400M/s which is about 5 years for full run, right ? if so - it's not really acceptable for practical use.

practical use in my case is recovering lost DES keys for various 10-15 year old software (for arcade machines, I'm member of [MAME project](https://github.com/mamedev))
we used cloudcracker's MS-CHAPv2 FPGA BF service for this task, but it's server is down during few last month, so we are looking for alternatives now.

PS: sorry for out of topic

**Comment by magnumripper** [comment]
Your 400MH/s figure is for descrypt, which is 25xDES. For cracking your DES key I think oclHashcat would do over 20 GH/s per GPU if someone wrote a format for it. With some help (volunteers) that key may well be cracked in a few days.

**Comment by p1pkin** [comment]
thanks for explanation. 20GH/s sounds pretty cool.

> if someone wrote a format for it

what means format in this context, .cl module or just some input parser ?

**Comment by p1pkin** [comment]
>  I think oclHashcat would do over 20 GH/s per GPU 

did some quick hack/editing, in m05500_a3.cl commented out such things: MD4 password increments, 2nd DES key schedule and decrypt, skip of non-ASCII passwords ... and (unsurprisingly) because of last change - BF becomes significantly slower.

after quick tests I got ~2.1GH/s on my HD6870, and about 2x faster on fellow's AMD 290
any ideas why it is not even close to 20GH/s ?

PS: used current git code selfcompiled using Msys64 on win32 x64

**Comment by magnumripper** [comment]
I think you should base it on m3000 (LM) for a starter.

**Comment by thesle3p** [comment]
Any updates?

**Comment by jsteube** [comment]
Implemented as -m 14000 - have fun :)

**Comment by p1pkin** [comment]
thank you very much!
may I ask about approximate speed on recent GPUs ?
-b -m 14000 on old hd6870 gives only about 337.0 MH/s
