### ISSUE TITLE
find mode 3300 hash cracking again

### ISSUE THREAD

**Issue by su-coder** [hashcat/hashcat#894]
mode 3300 was not transported to hashcat v2.xx.
please find it and add it in again.

**Comment by philsmd** [comment]
Note: this is about -m 3300 = MD5(Sun) (example hash: $md5$rounds=904$iPPKEBnEkp3JV8uX$0L6m7rOFTVFn.SGqo2M9W1:hashcat).

This hash type was never implemented on GPU and was only available on hashcat-legacy (CPU only).
As far as I remember, this is kind of a strange/GPU-unfriendly algorithm.

We need to decide if it makes sense to implement it in hashcat.

**Comment by jsteube** [comment]
So far no requests for this in 3 years. If there's more demand we can reopen and implement.
