### ISSUE TITLE
hashcat (v3.20-8-ga9a45ca) several bugs

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#901]
After upgade from hashcat (v3.20-3-gf098211)
there are some bugs which causes hashcat to crash

1. Status display shows incorrect date:

Time.Started.....: Sat Dec   (1 min, 1 sec)
Time.Estimated...: Sat Dec   (0 secs)

2. Memory leak (race condition ?):
--22215-- REDIR: 0x530d540 (libc.so.6:__GI___strcasecmp_l) redirected to 0x4c2e860 (__GI___strcasecmp_l)
--22215-- REDIR: 0x53ae340 (libc.so.6:__strcspn_sse42) redirected to 0x4c324d0 (strcspn)
22220 Speicherzugriffsfehler  (Speicherabzug geschrieben) hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o neu test.hccap wordlist

hashcat exit code: 139

==22215== 
==22215== HEAP SUMMARY:
==22215==     in use at exit: 40,479 bytes in 608 blocks
==22215==   total heap usage: 3,552 allocs, 2,944 frees, 205,309 bytes allocated
==22215== 
==22215== Searching for pointers to 608 not-freed blocks
==22215== Checked 214,688 bytes
==22215== 
==22215== LEAK SUMMARY:
==22215==    definitely lost: 11 bytes in 1 blocks
==22215==    indirectly lost: 0 bytes in 0 blocks
==22215==      possibly lost: 0 bytes in 0 blocks
==22215==    still reachable: 40,468 bytes in 607 blocks
==22215==         suppressed: 0 bytes in 0 blocks

Best regards
ZerBeat

**Comment by matrix** [comment]
The bug is here, wrong usage of ctime_r()

https://github.com/hashcat/hashcat/pull/898/commits/96591f3118e46fe449201a3125b4c2c777aed4cf#diff-b1e5020435e46f32362c9ddb87f83690

Thanks

**Comment by jsteube** [comment]
@ZerBea Can you confirm both issues fixed?
@matrix Thanks for patch

**Comment by ZerBea** [comment]
Both issues fixed.
Best regards
ZerBea
