### ISSUE TITLE
support for iterated sha1($pass.$salt ))

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#91]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | fflluker |
| Title: | Future REQ : SHA1( $password.$salt )) n-th iteration support in oclHashcat |
| Ticket number: | 622 |
| Date reported: | 2015-05-14T10:09:49+02:00 |
| **Description**: | I am requesting that SHA1( $password.$salt )) n-th iteration hash type be considered for addition to oclHashcat.<br><br>this hash type is used [by] Web Services Security<br><br>See details [here](https://docs.oasis-open.org/wss/v1.1/wss-v1.1-spec-pr-UsernameTokenProfile-01.htm#_Toc104276214) |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | OK, please provide some example hashes with known password and a method how to extract those hashes from the native database where they are stored in (or textfile) |

**Comment by sebdotv** [comment]
I have a similar request here, except that I need to iterate on `SHA1( $salt.$password ))`, where `$salt` is binary. I could probably emulate my needs if requested algorithm was implemented, by using an empty $salt and including my binary $salt into $password keyspace.

An example implementation of original request is class UsernameTokenUtil from Apache WSS4J.
(https://svn.apache.org/repos/asf/webservices/wss4j/trunk/ws-security-common/src/main/java/org/apache/wss4j/common/util/UsernameTokenUtil.java).

Example hash of original request:
password: `hashcat`(ascii)
salt: `2016`(ascii)
iterations: 1000
hash: `ZjhhYPVDGgqaTSasfwFPZoejm6w=` (base64)

**Comment by philsmd** [comment]
We try to focus on some very specific algorithms for instance used by CMS/forums/software etc...
They still could have some kind of iteration count... but the algorithm should be much more well-defined and clear and also widely used... just n-iterations of salted sha is a very unspecific request and there could be so many other problems and restrictions (e.g. using binary or hex data, upper or lowercase hex, min/max pass, min/max salt etc)... there are too many ways of implementing salted sha1, we would need something specific...

maybe the WSS4J is something more specific, but it should probably be a new github issue.
I will close this issue for now, because it's too broad and unspecific
