### ISSUE TITLE
Feature request: GH/s

### ISSUE THREAD

**Issue by dtest505** [hashcat/hashcat#911]
Can a GH/S be displayed in the status?
The MH/s gets to be a large number for when glancing
(yup, its minor)

**Comment by coolbry95** [comment]
It has GH/s but you need to be at GH/s to have it displayed. It will not display 0.124 GH/s but instead display 124753.3 MH/s.

**Comment by RealEnder** [comment]
This happens because of
https://github.com/hashcat/hashcat/blob/2039e2c06eb7459f89b7de25bc127362c538e8c8/src/status.c#L115
I believe it's by design.

**Comment by jsteube** [comment]
Right, if you do > 100000 MH/s it will switch to GH/s. I find it easier to read that way

**Comment by dtest505** [comment]
My bad.  Math-fu was off.  Thought 1000 M = 1 G.
(Isn't 1000MB 1GB?  Thought that would carry over)

**Comment by magnumripper** [comment]
@dtest505 yes it is. At 100000 MH it will start saying 100 GH. I suppose the reason it doesn't do so earlier is you lose too much detail because there's just one decimal: 1423.4 MH would show as 1.4 GH.

**Comment by dtest505** [comment]
Ah!  That makes sense.
Thanks guys.  Sorry to cutter things here.
