### ISSUE TITLE
--keyspace doesn't work as expected 

### ISSUE THREAD

**Issue by milzo247** [hashcat/hashcat#914]
With 3.20

./hashcat -a 3 -m 0 example0.hash ?a?a?a?a?a?a?a?a --keyspace
Usage: ./hashcat [options]... hash|hashfile|hccapfile [dictionary|mask|directory]...

Try --help for more help.

==========================================================
With 3.10

./hashcat64.bin -a 3 -m 0 example0.hash ?a?a?a?a?a?a?a?a --keyspace
7737809375

**Comment by jsteube** [comment]
That's actually a problem in v3.10 which was undetected, but is now detected in v3.20. The problem is the command you're using. You need to remove the hashlist. If you used --keyspace in combination with a hashlist before, you always used it wrong.
