### ISSUE TITLE
Change to increment mode format. Make it same as maskprocessors.

### ISSUE THREAD

**Issue by blandyuk** [hashcat/hashcat#915]
With hashcat, using increment mode is quite long-winded as shown below:
-i --increment-min=4 --increment-max=8

When using maskprocessor, its very simple as below:
-i 4:8
searches lengths 4-8 (inclusive)

Would be great if hashcat adopted the same format as its a huge difference.

**Comment by jsteube** [comment]
No problem, I just don't see how we can handle both the old and the new commandline parsing configuration at once. So this will break old overlays and also many tutorials and forum help threads. I'll redirect complains to you :)

**Comment by jsteube** [comment]
I've changed my mind about this while implementing. It's really more disadvantages than advantages. Alternatively we could up a shortcut for both --increment-min and --increment-max, what you think?

**Comment by blandyuk** [comment]
If that's the best option for you then yes, shortcuts would be OK :) It's a shame about the maskprocessor format as it is very easy and compact. Cheers atom.

**Comment by magnumripper** [comment]
The problem with --increment-min/max options is you can't abbreviate them except for the very last letter. How about --lengh-range=4,8, which can be abbreviated to just --len=4,8?

**Comment by jsteube** [comment]
--increment-range 4:8 with 'R' as shortcut? @blandyuk ?

**Comment by magnumripper** [comment]
Same problem. You'll need to type `--increment-r` before it gets unambigouous

**Comment by jsteube** [comment]
Yes, but assigning 'R' to it would work. What I mean, if sticking to
--increment-min and --increment-max, what would be the shortcut? It
wouldn't be intuitive because both min and max start with 'm'.

**Comment by blandyuk** [comment]
Why can't you read the command-line parameter for -i and check if there is a value present? If not, default to what hashcat does anyway but, if say -i 4:8 was present, then apply the increment min/max values. I sure I could do this with my apps I have but not sure how hashcat is setup so it may not be possible :( if not, I'll just close this issue.

**Comment by jsteube** [comment]
I can't because I have no control over getops (the library handling the
commandline parameter) for such a specific case. I have to configure
each option as it has a parameter or not, not both.

**Comment by roycewilliams** [comment]
Huh. I had no idea that only GNU getopts let you do this, and that "optional options" is not POSIX.

http://stackoverflow.com/a/19604773/263879

**Comment by magnumripper** [comment]
Interesting. OSX sed(1) sucks so I have GNU sed installed too. It has at least one option with optional parameter, `-i [suffix]`, and that works just fine. Perhaps I should have a look at how they did that.

**Comment by magnumripper** [comment]
OK it turns out OSX getopt doesn't support optional arguments but getopt_long (which isn't POSIX anyway) does (just like GNU's). So as long as we use getopt_long, optional parameters should not be a problem.

**Comment by jsteube** [comment]
I still prefer the way it is right now. Adding code for handling any backward compatiblity was never how hashcat worked. We can assume users follow the changes because the typical hashcat user is a more experienced user. Bundled with bash completion (which hashcat supports) it's typed really fast with --inc<tab>
