### ISSUE TITLE
Using --loopback along with --potfile-disable can cause an infinite loop

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#917]
Giving hashcat a command that will start a rule-based attack, and including --loopback and --potfile-disable will cause hashcat to infinitely loop back after finding 100% of the hashes.

Command used for testing:
hashcat64.exe -m 0 --loopback -a 0 example0.hash .\dicts\* -r .\rules\best64.rule --potfile-disable

MD5 hash and plaintext used:
919509ee78ca3da484bd24e5d76def50:WelCome

**Comment by roycewilliams** [comment]
Can replicate using v3.20-28-gec561027.

$ cat example0.hash
919509ee78ca3da484bd24e5d76def50

$ cat dicts1
WelCome

$ ./hashcat -m 0 --loopback -a 0 example0.hash ./dicts* -r /var/local/rules/best64.rule --potfile-disable
hashcat (v3.20-28-gec561027) starting...

XOpenDisplay() failed

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #2: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #3: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #4: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #5: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #6: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #7: AMD FX(tm)-8350 Eight-Core Processor, skipped

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 77

Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled

Generated dictionary stats for ./dicts1: 8 bytes, 1 words, 77 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted

919509ee78ca3da484bd24e5d76def50:WelCome

Session..........: hashcat
Status...........: Cracked
Hash.Type........: MD5
Hash.Target......: 919509ee78ca3da484bd24e5d76def50
Time.Started.....: Fri Dec  9 20:59:32 2016 (0 secs)
Time.Estimated...: Fri Dec  9 20:59:32 2016 (0 secs)
Input.Base.......: File (./dicts1)
Input.Mod........: Rules (/var/local/rules/best64.rule)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#4.....:        0 H/s (0.04ms)
Speed.Dev.#5.....:        0 H/s (0.00ms)
Speed.Dev.#6.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 9/77 (11.69%)
Rejected.........: 0/9 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Copying]
Candidates.#2....: [Copying]
Candidates.#3....: [Copying]
Candidates.#4....: WelCome -> WelCome4
Candidates.#5....: [Copying]
Candidates.#6....: [Copying]
HWMon.Dev.#1.....: Temp: 62c Fan:  2% Util:  0% Core:1290Mhz Mem:3004Mhz Lanes:8
HWMon.Dev.#2.....: Temp: 60c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#3.....: Temp: 54c Fan:  0% Util:  0% Core:1290Mhz Mem:3004Mhz Lanes:16
HWMon.Dev.#4.....: Temp: 51c Fan:  0% Util:  0% Core:1366Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#5.....: Temp: 62c Fan:  0% Util: 77% Core:1379Mhz Mem:3004Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 61c Fan:  0% Util: 99% Core:1366Mhz Mem:3004Mhz Lanes:1

Generated dictionary stats for /usr/local/src/sec/crack/hashcat/github/hashcat/hashcat.induct/hashcat.loopback.1481349572_936: 8 bytes, 1 words, 77 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted


Session..........: hashcat
Status...........: Exhausted
Hash.Type........: MD5
Hash.Target......: 919509ee78ca3da484bd24e5d76def50
Time.Started.....: Fri Dec  9 20:59:33 2016 (0 secs)
Time.Estimated...: Fri Dec  9 20:59:33 2016 (0 secs)
Input.Base.......: File (/usr/local/src/sec/crack/hashcat/github/hashcat/hashcat.induct/hashcat.loopback.1481349572_936)
Input.Mod........: Rules (/var/local/rules/best64.rule)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#4.....:        0 H/s (0.00ms)
Speed.Dev.#5.....:        0 H/s (0.00ms)
Speed.Dev.#6.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 77/77 (100.00%)
Rejected.........: 0/77 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Copying]
Candidates.#2....: el -> elCoel
Candidates.#3....: [Copying]
Candidates.#4....: [Copying]
Candidates.#5....: [Copying]
Candidates.#6....: [Copying]
HWMon.Dev.#1.....: Temp: 63c Fan:  3% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:8
HWMon.Dev.#2.....: Temp: 61c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#3.....: Temp: 55c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:16
HWMon.Dev.#4.....: Temp: 51c Fan:  0% Util:  0% Core:1366Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#5.....: Temp: 62c Fan:  0% Util:100% Core:1379Mhz Mem:3004Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 61c Fan:  0% Util: 63% Core:1366Mhz Mem:3004Mhz Lanes:1

Cache-hit dictionary stats /usr/local/src/sec/crack/hashcat/github/hashcat/hashcat.induct/hashcat.loopback.1481349572_936: 8 bytes, 1 words, 77 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted


Session..........: hashcat
Status...........: Exhausted
Hash.Type........: MD5
Hash.Target......: 919509ee78ca3da484bd24e5d76def50
Time.Started.....: Fri Dec  9 20:59:35 2016 (0 secs)
Time.Estimated...: Fri Dec  9 20:59:35 2016 (0 secs)
Input.Base.......: File (/usr/local/src/sec/crack/hashcat/github/hashcat/hashcat.induct/hashcat.loopback.1481349572_936)
Input.Mod........: Rules (/var/local/rules/best64.rule)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.00ms)
Speed.Dev.#4.....:        0 H/s (0.00ms)
Speed.Dev.#5.....:        0 H/s (0.00ms)
Speed.Dev.#6.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 77/77 (100.00%)
Rejected.........: 0/77 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Copying]
Candidates.#2....: el -> elCoel
Candidates.#3....: [Copying]
Candidates.#4....: [Copying]
Candidates.#5....: [Copying]
Candidates.#6....: [Copying]
HWMon.Dev.#1.....: Temp: 63c Fan:  5% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:8
HWMon.Dev.#2.....: Temp: 61c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#3.....: Temp: 55c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:16
HWMon.Dev.#4.....: Temp: 51c Fan:  0% Util:  0% Core:1366Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#5.....: Temp: 63c Fan:  0% Util:100% Core:1379Mhz Mem:3004Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 63c Fan:  0% Util: 99% Core:1366Mhz Mem:3004Mhz Lanes:1

Cache-hit dictionary stats /usr/local/src/sec/crack/hashcat/github/hashcat/hashcat.induct/hashcat.loopback.1481349572_936: 8 bytes, 1 words, 77 keyspace

^C

**Comment by roycewilliams** [comment]
Yep, fixed for me. Exactly the same setup as before.

$ ./hashcat -m 0 --loopback -a 0 example0.hash ./dicts* -r /var/local/rules/best64.rule --potfile-disable
hashcat (v3.20-29-gf424650c) starting...

XOpenDisplay() failed

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #2: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #3: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #4: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #5: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU
* Device #6: GeForce GTX 970, 1017/4068 MB allocatable, 13MCU

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #7: AMD FX(tm)-8350 Eight-Core Processor, skipped

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 77

Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled

Generated dictionary stats for ./dicts1: 8 bytes, 1 words, 77 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted

919509ee78ca3da484bd24e5d76def50:WelCome

Session..........: hashcat
Status...........: Cracked
Hash.Type........: MD5
Hash.Target......: 919509ee78ca3da484bd24e5d76def50
Time.Started.....: Sat Dec 10 05:45:24 2016 (0 secs)
Time.Estimated...: Sat Dec 10 05:45:24 2016 (0 secs)
Input.Base.......: File (./dicts1)
Input.Mod........: Rules (/var/local/rules/best64.rule)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#3.....:        0 H/s (0.25ms)
Speed.Dev.#4.....:        0 H/s (0.00ms)
Speed.Dev.#5.....:        0 H/s (0.00ms)
Speed.Dev.#6.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 77/77 (100.00%)
Rejected.........: 0/77 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Copying]
Candidates.#2....: [Copying]
Candidates.#3....: WelCome -> elCoel
Candidates.#4....: [Copying]
Candidates.#5....: [Copying]
Candidates.#6....: [Copying]
HWMon.Dev.#1.....: Temp: 61c Fan:  2% Util:  0% Core:1290Mhz Mem:3004Mhz Lanes:8
HWMon.Dev.#2.....: Temp: 62c Fan:  2% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#3.....: Temp: 56c Fan:  0% Util:  0% Core:1354Mhz Mem:3004Mhz Lanes:16
HWMon.Dev.#4.....: Temp: 49c Fan:  0% Util:  0% Core:1366Mhz Mem:3004Mhz Lanes:4
HWMon.Dev.#5.....: Temp: 68c Fan:  0% Util:100% Core:1379Mhz Mem:3004Mhz Lanes:1
HWMon.Dev.#6.....: Temp: 66c Fan:  2% Util:100% Core:1366Mhz Mem:3004Mhz Lanes:1

Started: Sat Dec 10 05:45:07 2016
Stopped: Sat Dec 10 05:45:26 2016
