### ISSUE TITLE
No Status update & after Ctrl-c restart done in 1 second

### ISSUE THREAD

**Issue by decker78** [hashcat/hashcat#921]
I use hashcat on a regular basis using something like hashcat -m 2500 6345_1481997586.hccap ../Documents/realhuman_phill.txt 

At this moment, with hashcat 3.10 in Kali, there are no status updates. It doesn't respond to the " s" . Running hashcat -m 2500 6345_1481997586.hccap ../Documents/realhuman_phill.txt --status auto updates the status. 
Other issue is that whenever I ctrl-c a task and restart, it is ready in 1 second. Bypasses all. If I remove rm -rf ~/.hashcat/kernels than the job runs again.

**Comment by jsteube** [comment]
hashcat v3.10 is outdated, please update to v3.20 and reopen if the issue still exists
