### ISSUE TITLE
Feature request: make debug modes aware of --separator flag

### ISSUE THREAD

**Issue by recon-ng** [hashcat/hashcat#923]
If I have strings with ":" in them, parsing debug files is hard since the rule can't be easily distinguished from the source and result strings (especially if the rule itself operates on the ":" character.

**Comment by jsteube** [comment]
But that doesn't really solve the problem. The same problem will occur
again if the character selected for separator will be part of the debug
line.

We've recently solved a similar problem for the output file by switching
to $HEX[...] encoding if the separator character is part of the data.
For example, if the password is "lala:" (without quotes) then the output
with the latest hashcat version is:

```

757f75dc2ce17be3bb9ccc1f3f565b51:$HEX[6c616c613a]

```

and not

```

757f75dc2ce17be3bb9ccc1f3f565b51:lala:

```

The same systematic could be done for debug mode line.

**Comment by recon-ng** [comment]
I see! Thnx. Closing this.
