### ISSUE TITLE
No line-length exception for invalid input

### ISSUE THREAD

**Issue by hgbstu** [hashcat/hashcat#924]
When the input file for hashcat contains a special crafted string, hashcat starts cracking a weird hash that isn't present in the input file.

# How to reproduce
Create a file containing the following line. Notice the `TAB` between the first and the second part of the line.
`1234567890123	123456789012345678`
[invalidhash.txt](https://github.com/hashcat/hashcat/files/660766/invalidhash.txt)

Run hashcat
`hashcat64.bin -a 3 -m 0 invalidhash.txt`

hashcat detects the given string in the file as the following md5 hash and starts cracking
`12345678901239123456789012345678`

See the output for detailed informations
[invalidhash_stdout.txt](https://github.com/hashcat/hashcat/files/660893/invalidhash_stdout.txt)

Tested with hashcat v3.10 and v3.20 on Ubuntu 14.04.5

**Comment by jsteube** [comment]
I've pushed a patch for this with commit https://github.com/hashcat/hashcat/commit/fa5b5d298d89cf825ee7169f86e4de089418c5a0

Can you please test if it's working for you and close the issue?

I've also upload a new pre-compiled beta version to https://hashcat.net/beta/

**Comment by jsteube** [comment]
Any update?

**Comment by jsteube** [comment]
This feature went into hashcat v3.30, therefore closing the issue. If it's not working, please open up a new one.
