### ISSUE TITLE
hashcat -m 2500 feature request: 1) Improvement of potfile, 2) increase speed

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#926]
1) Improvement of potfile
The results in the potfile are not unique. (Doesn't take care if password is changend).
essid:ap-mac:client-mac:password

Please add the mic to make the result more unique. This allows a better analyze, especially when using multiple hccap's. 
essid:ap-mac:client-mac:mic:password

2) Increase of speed
hashcat does a presort of the essid's by length, but doesn't take care on different ap's using the same essid.
Please do a second presort to filter out ap's with the same essid and do only PBKDF2 once 
for this ones.

Best regards
ZerBea

**Comment by jsteube** [comment]
For 2) it already does that

**Comment by ZerBea** [comment]
For 2) seems to work not like expected.....

#hashcat
Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccap
Time.Started.....: Wed Dec 21 08:46:34 2016 (4 mins, 45 secs)
Time.Estimated...: Wed Dec 21 08:51:19 2016 (0 secs)
Input.Base.......: File (testlist)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   158.1 kH/s (16.56ms)
Recovered........: 0/537 (0.00%) Digests, 0/536 (0.00%) Salts
Progress.........: 45209456/45209456 (100.00%)
Rejected.........: 81472/45209456 (0.18%)
Restore.Point....: 84346/84346 (100.00%)
Candidates.#1....: (*#&)&)()) -> zzkcorcipe420
HWMon.Dev.#1.....: Temp: 75c Fan: 56% Util:100% Core:1277Mhz Mem:3004Mhz Lanes:16

Started: Wed Dec 21 08:46:30 2016
Stopped: Wed Dec 21 08:51:21 2016

#john
Device 0: GeForce GTX 970
Local worksize (LWS) 64, global worksize (GWS) 1048576
Loaded 537 password hashes with 537 different salts (wpapsk-opencl, WPA/WPA2 PSK [PBKDF2-SHA1 OpenCL])
Note: minimum length forced to 8
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 DONE (2016-12-21 08:51) 0g/s 54672p/s 30452Kc/s 30452KC/s GPU:64°C util:96% fan:48% 
Session completed

testfile: 537 different ap's using the same essid
hashcat:     158.1 kH/s
john......: 30452 Kc/s

Remarks:
Please don't wonder about the difference digest / salts.
In one set I switched ap and client to see how the progs will act...


Best regards
ZerBea

**Comment by jsteube** [comment]
I've just pushed commit https://github.com/hashcat/hashcat/commit/72af615e8b9be2039341867fbe0f8775f8edee65

It's a better solution for the duplicate essid detection and should make use of it to increase performance. There's also a new binary beta on https://hashcat.net/beta/

Please try it out

**Comment by jsteube** [comment]
Note if you compile from source to do a make clean

**Comment by ZerBea** [comment]
Looking good (and faster than john...)

Session..........: hashcat                                
Status...........: Exhausted
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccap
Time.Started.....: Thu Dec 22 07:58:30 2016 (1 sec)
Time.Estimated...: Thu Dec 22 07:58:31 2016 (0 secs)
Input.Base.......: File (testliste)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   145.3 MH/s (16.32ms)
Recovered........: 0/537 (0.00%) Digests, 0/536 (0.00%) Salts
Progress.........: 45209992/45209992 (100.00%)
Rejected.........: 81472/45209992 (0.18%)
Restore.Point....: 84347/84347 (100.00%)
Candidates.#1....: (*#&)&)()) -> zzkcorcipe420
HWMon.Dev.#1.....: Temp: 46c Fan: 33% Util: 83% Core:1303Mhz Mem:3004Mhz Lanes:16

Started: Thu Dec 22 07:58:27 2016
Stopped: Thu Dec 22 07:58:32 2016

It was purely coincidental that I did this test.
During the past weekend I did a refactroring of my programm
and decided to run some tests using hashcat and john.
During this test I found that bug. I didn't noticed that bug previously.

By this way, please stay using C (#511).....
Both, c and asm are fine. I'm to old to use c++ or c#......lol

Again, well done.....


p.s. I don't like binaries........lol

**Comment by magnumripper** [comment]
> Note if you compile from source to do a make clean

With a perfect Makefile, this is never needed so some dependency must be missing. I've been meaning to audit that for a while (using some tools of mine) but then again it's not super important.

**Comment by ZerBea** [comment]
No problem for me. I use PKGBUILD......
