### ISSUE TITLE
Add new algorithm: {SSHA256} for some LDAP 

### ISSUE THREAD

**Issue by su-coder** [hashcat/hashcat#928]
add new algorithm $hash = "{SSHA256}".base64_encode(hash('sha256', $password . $salt) . $salt) .

for example with SSHA256 you know that the hash itself is 32 bytes (256 bits/8 bits per byte). Everything after that 32 bytes is the salt. For example if you have a password(not real):

{SSHA256}SoR/78T5q0UPFng8UCXWQxOUKhzrJZlwfNtllAupAeUT+kQv

After base64 decoding it you'll see that its length is 36 bytes, so the first 32 bytes are the hash and the following 4 bytes are the salt : 

**length**: echo SoR/78T5q0UPFng8UCXWQxOUKhzrJZlwfNtllAupAeUT+kQv|base64 -d|wc -c -> 36

**hash**: echo SoR/78T5q0UPFng8UCXWQxOUKhzrJZlwfNtllAupAeUT+kQv|base64 -d|dd bs=1 count=32|hexdump -C -> 4a 84 7f ef c4 f9 ab 45 0f 16 78 3c 50 25 d6 43 13 94 2a 1c eb 25 99 70 7c db 65 94 0b a9 01 e5

**salt**: echo SoR/78T5q0UPFng8UCXWQxOUKhzrJZlwfNtllAupAeUT+kQv|base64 -d|dd bs=1 skip=32|hexdump -C -> 13 fa 44 2f

**Comment by byte4sec** [comment]
mode 6400  doesn't work ?

**Comment by jsteube** [comment]
No, mode 6400 is something else. He's looking for something like 1711, but for SHA256. 

Basically this requires only to write the parser, the kernel is already there. If anyone want to write it, see 1711 as an example.
