### ISSUE TITLE
support for longer salt lengths for sha1 ($salt.$pass)

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#93]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.
---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | katolic |
| Title: | SHA1 large salt don't working ( |
| Ticket number: | 627 |
| Date reported: | 2015-06-07T14:38:54+02:00 |
| **Description**: | sha1($salt.$pass) whith large salt don't working (<br><br>root@kali:/usr/share/cudaHashcat-1.36# ./cudaHashcat64.bin -m 120 -a 3 mail2.txt ?a?a?a?a?a --gpu-devices=1<br>cudaHashcat v1.36 starting...<br><br>WARNING: Hashfile 'mail2.txt' in line 1<br>(<SHA1 hash redacted by philsmd>): Line-length exception<br>Parsed Hashes: 1/1 (100.00%)<br><br>ERROR: No hashes loaded |
---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | Please read [this](https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_the_maximum_supported_salt_length) and reply with answers in this ticket!<br> |

**Comment by jsteube** [comment]
https://github.com/hashcat/hashcat/issues/565
