### ISSUE TITLE
does hashcat can crack fortigate (fortios ) hash ?

### ISSUE THREAD

**Issue by bigbigmonkey123** [hashcat/hashcat#930]
does hashcat can crack fortigate (fortios ) hash ?
hash like this :
VdKhOIpDmSZSU5i3FzNHKp7wr6cRlMDDSFw58Mxpa8tOkeuolD4Dwjq4raBqvdATIEmxS/bkDp4QxBoD/m+rv71ecLn/PRf3kBW7CWu2nF5djgBlFb7jlorwCiPEY3+ENzkmg+vq6CsHR1phAzaE56Cc6ekFW6yTK2x4kDfhDhtIJXBqhqy4HeusLIpYNDjxSG3TVA==

**Comment by ZilentJack** [comment]
I just double tried to check on latest version (3.20) and it doesn't seem like Hash-Mode 7000 is included anymore, not sure why?

-m 7000 should be "Fortigate (FortiOS)" (https://hashcat.net/wiki/doku.php?id=example_hashes), but I'm getting "Unknown hash-type '7000' selected".

**Comment by jsteube** [comment]
It was never included in hashcat, it was only in hashcat-legacy.

Am 27.12.2016 21:28 schrieb "ZilentJack" <notifications@github.com>:
