### ISSUE TITLE
Small mask in mask file causes other masks to run slower

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#931]
When using a mask file as an input source, after a small mask (one with a small keyspace) is encountered, future masks run considerably slower.

I've put together a demo script and captured logs to help illustrate the issue: https://gist.github.com/llamasoft/31fe66c07726c617eedbdab11d48f36a

The script does the following:

1. Generate 10k dummy hashes
2. As a single mask input, try `?d?d?d?d?d?d` (length 6)
Result: **530 MH/s** ([log](https://gist.github.com/llamasoft/31fe66c07726c617eedbdab11d48f36a#file-mask_6d-log))
3. As a single mask input, try `?d?d?d?d` (length 4)
Result: **5 MH/s** ([log](https://gist.github.com/llamasoft/31fe66c07726c617eedbdab11d48f36a#file-mask_4d-log)), pretty bad but understandable due to very small keyspace
4. As a single mask input, try `?d?d?d?d?d?d?d` (length 7)
Result: **525 MH/s** ([log](https://gist.github.com/llamasoft/31fe66c07726c617eedbdab11d48f36a#file-mask_7d-log)), pretty much the same as length 6

Here's where the issue shows up:

5. Put the three masks into a file, length 6, length 4, and length 7.
6. Use the mask file as an input ([log](https://gist.github.com/llamasoft/31fe66c07726c617eedbdab11d48f36a#file-mask_file-log))
Length 6 result: 550 MH/s, about the same as before
Length 4 result: 5 MH/s, about the same as before
Length 7 result: 55 MH/s, about _90% slower_ than before

**Comment by jsteube** [comment]
Excellent report, many thanks! Before I'm going to investigate, did you
run those on the latest github version? There was some patch I did a
while ago:
https://github.com/hashcat/hashcat/commit/72599fd10956179ee36df25d63fda27422cbe112
it's possible that this was the bug and that it's already fixed. Please
try that first and report back. There's also a precompiled beta version
if you do not want to build from sources: https://hashcat.net/beta/

**Comment by llamasoft** [comment]
Looks like that beta build fixes it!  Thanks for the quick response.

**Comment by jsteube** [comment]
Thanks for your report!
