### ISSUE TITLE
Custom charsets in mask definition broken in beta build

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#932]
It appears that commit 767ad440b2ed64bd02018184e965c87b9d4eaa1c broke [custom charset definitions in masks](https://hashcat.net/wiki/doku.php?id=mask_attack#hashcat_mask_files).

For example, using the following mask file named `custom.hcmask`:

```
aeiou,?d?d?d?d?d?1
aeiou,AEIOU,?d?d?d?d?1?2
abcdef,?d?d?d?d?d?1
```

The release version v3.20 parses the masks correctly ([log](https://gist.github.com/llamasoft/dd9737e9a03a957a93861215cd70057b#file-custom_3-20-log)).
The current beta v3.20-60-g45aae6a rejects all the masks with `Custom-charset 1 is undefined` ([log](https://gist.github.com/llamasoft/dd9737e9a03a957a93861215cd70057b#file-custom_3-20-60-log)).

Somewhat related, the current v3.20 build replaces the `Input.Queue` status line with `Input.Charset` even when the masks are being read from file.  It only does this when the masks include custom charset definitions, making it impossible to determine how far you've progressed into a mask file without manual inspection.  
The beta build may still have this issue but it's being hidden by the fact it's failing to detect the custom charsets.

**Comment by jsteube** [comment]
Should be fixed, also new beta up. Thanks again for reporting!
