### ISSUE TITLE
[Feature Request] "Input Queue" status line when using custom charset masks from file

### ISSUE THREAD

**Issue by llamasoft** [hashcat/hashcat#934]
As the title says, the "Input Queue" status line is replaced with "Input Charset" when the mask has a custom charset definition even if it's being read from file.

Example: create a file with the following lines and use the file as an input for a mask attack.:
```
aeiou,?d?d?d?d?d?1
aeiou,AEIOU,?d?d?d?d?1?2
abcdef,?d?d?d?d?d?1
```

Without the "input queue" status, it's difficult to tell your progress into the mask file.  You can manually find your position by searching your mask file for the charsets and mask, but it can get tedious.  The above example is pretty short, but hopefully it illustrates the issue.

In lieu of a pull request, I suggest changing [these lines](https://github.com/hashcat/hashcat/blob/eda7344f34f2ebd1886c594bf9a99989fa449ae3/src/terminal.c#L901-L910) to:

```
    case INPUT_MODE_MASK:
    case INPUT_MODE_MASK_CS:

      event_log_info (hashcat_ctx,
        "Input.Queue......: %d/%d (%.02f%%)",
        hashcat_status->input_base_offset,
        hashcat_status->input_base_count,
        hashcat_status->input_base_percent);

      break;
```

(Added the case label for `INPUT_MODE_MASK_CS`)

**P.S.** Sorry for opening so many issues today.  Keep up the good work!

**Comment by jsteube** [comment]
No worries, please keep opening good issues like that :)
