### ISSUE TITLE
ERROR: clCreateKernel(): CL_INVALID_KERNEL_NAME

### ISSUE THREAD

**Issue by R47P70R** [hashcat/hashcat#935]
Hello I am trying to crack WPA 2 Password using brute forcing .hccap file. Here is the output I get
hashcat (v3.10) starting...

OpenCL Platform #1: Mesa                
========================
- Device #1: NV118, 1048576/1048576 MB allocatable, 3MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force
* Slow-Hash-SIMD
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Initializing device kernels and memory...

ERROR: clCreateKernel(): CL_INVALID_KERNEL_NAME

**Comment by neheb** [comment]
Nvidia GPUs under Mesa are not supported and probably never will be. Install the proprietary drivers.
