### ISSUE TITLE
Issues compiling from git : warning: "_WIN32" is not defined [-Wundef]

### ISSUE THREAD

**Issue by peterpt** [hashcat/hashcat#942]
I got an error when i  try to compile from git .

deps/OpenCL-Headers/CL/cl_platform.h:100:11: warning: "_WIN32" is not defined [-Wundef]
 and after the "make install" and try "hashcat -b"
i get this :

"OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: AMD Athlon(tm) II X4 631 Quad-Core Processor, 2047/3946 MB allocatable, 4MCU

Hashtype: MD4

clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

"/usr/local/share/hashcat/OpenCL/inc_vendor.cl", line 57: error: can't enable
          all OpenCL extensions or unrecognized OpenCL extension
  #pragma OPENCL EXTENSION cl_amd_media_ops2 : enable
                                               ^

"/usr/local/share/hashcat/OpenCL/inc_types.cl", line 260: error: function
          "amd_bfe" declared implicitly
    return amd_bfe (a, b, c);
           ^

"/usr/local/share/hashcat/OpenCL/inc_types.cl", line 265: error: function
          "amd_bfe" declared implicitly
    return amd_bfe (a, b, c);
           ^

3 errors detected in the compilation of "/usr/local/share/hashcat/OpenCL/OCLbqlRd7.cl".

Internal error: clc compiler invocation failed.

* Device #1: Kernel /usr/local/share/hashcat/OpenCL/m00900_a3.cl build failure. Proceeding without this device"

Any idea how to get thru this issue ?
Thanks

**Comment by jsteube** [comment]
The first error is a bug in OpenCL headers, which is already fixed. Try: git submodule update --remote --recursive

The other error is not related. It simply looks like your (very old) CPU is not supported by AMDs OpenCL runtime. Reporting errors at AMD is time waste, so I'd suggest upgrade your CPU.

**Comment by peterpt** [comment]
Installed hashcat-legacy instead , working perfectly .
https://s24.postimg.org/3w6fnjwt1/hashcat_legacy.png

I fixed the script deps.sh in hashcat-legacy where was getting a 404 for libssl package .
I compiled hashcat-legacy with the new changed script and it is working perfectly as you may see in the image before .
check the pull requests .

**Comment by neheb** [comment]
Actually the first error might not be fixed if this is Ubuntu 14.04. I have a pull request waiting: https://github.com/KhronosGroup/OpenCL-Headers/pull/14/commits/d3efacb69d64c086d1a0508fa4656700e6bd4187

**Comment by peterpt** [comment]
After upgrading my graphic card to nvidia , all compilation issues disappeared , it was a straight forward compilation without any errors .
https://s30.postimg.org/gmkgafext/hashcatnvidia.png

The first post could be related to an old ati card i had here installed that ati did not denveloped new drivers to it for the new kernels after 3.4 .
