### ISSUE TITLE
Some hash are getting cracked over and over

### ISSUE THREAD

**Issue by segumarc** [hashcat/hashcat#945]
Hello,
I am using the 3.20 release of hashcat64 under linux and tested the last beta (3.20 build 88) and I am cracking some hash over and over and they are written multiple time to the potfile. 

Here's some of the hash : 

> 63ee9967dc9b571e746ecb52c9518455:.::H|CBO::.
> c3ee19ff73bcb2ebdf72188fd991aebe:.::Killthezoo::

Here's a screenshot of the potfile
![screenshot from 2016-12-31 13 45 01](https://cloud.githubusercontent.com/assets/2931748/21578859/726c145a-cf5f-11e6-8807-958a7247764e.png)

Regards,

**Comment by jsteube** [comment]
Can you please post the full commandline you're using

**Comment by segumarc** [comment]
Here we go : 
`./hashcat64.bin ../Hash/all.txt ../Dic/CT_Crackedv2.txt -D 1,2 -w 3 --force -r rules/combinator.rule`

Also the show command doesn't show it : 
`./hashcat64.bin --show ../Hash/all.txt`

And I grep the hashcat.potfile to find the result of the screenshot:
`cat hashcat.potfile |grep "\.::"`

Is it possible that the issue is related to the 4 colons like the[ issue 889](https://github.com/hashcat/hashcat/issues/899) ?

**Comment by jsteube** [comment]
Yes, that's what I think, too. But I'm unable to reproduce. For example
this:

```

root@ht:~# echo -n .::Killthezoo:: | md5sum
37fe8a5cff2cabefba9488e92617ddc8  -

```

But in your paste, there's no such hash. I also need the hashlist and
the wordlist.

Ideally reduce both lists to an absolute minimum so that you can
transfer it easily.

Also post hashcat version using hashcat -V and the output of hashcat -I.

**Comment by segumarc** [comment]
Oops my bad, I did a bad copy paste, it's 

> .::Killthezoo::. 


Here's the hashlist : 

> 30020acffe70e97f5672dbd144b74446
> 782d37d42ca81398be30be0540648b25
> 63ee9967dc9b571e746ecb52c9518455
> c3ee19ff73bcb2ebdf72188fd991aebe

Here's the Dict : 

> .::H|CBO::.
> .::Killthezoo::.
> merhoussame:::::
> :d:d:d:d:d1

I added the two following hash that cause the same error : 

> 30020acffe70e97f5672dbd144b74446:merhoussame:::::
> 782d37d42ca81398be30be0540648b25::d:d:d:d:d1


Here's the output off the -V and -I
> 
> ./hashcat64.bin -V
> v3.20
> 
> ./hashcat64.bin -I
> hashcat (v3.20) starting...
> 
> OpenCL Info:
> 
> Platform ID #1
>   Vendor  : Intel(R) Corporation
>   Name    : Intel(R) OpenCL
>   Version : OpenCL 1.2 LINUX
> 
>   Device ID #1
>     Type           : CPU
>     Vendor ID      : 8
>     Vendor         : Intel(R) Corporation
>     Name           :        Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
>     Version        : OpenCL 1.2 (Build 25)
>     Processor(s)   : 8
>     Clock          : 3400
>     Memory         : 2047/16015 MB allocatable
>     OpenCL Version : OpenCL C 1.2 
>     Driver Version : 1.2.0.25
> 
> Platform ID #2
>   Vendor  : Advanced Micro Devices, Inc.
>   Name    : AMD Accelerated Parallel Processing
>   Version : OpenCL 2.0 AMD-APP (1800.11)
> 
>   Device ID #2
>     Type           : GPU
>     Vendor ID      : 1
>     Vendor         : Advanced Micro Devices, Inc.
>     Name           : Cayman
>     Version        : OpenCL 1.2 AMD-APP (1800.11)
>     Processor(s)   : 24
>     Clock          : 880
>     Memory         : 512/1761 MB allocatable
>     OpenCL Version : OpenCL C 1.2 
>     Driver Version : 1800.11 (VM)
> 
>   Device ID #3
>     Type           : CPU
>     Vendor ID      : 128
>     Vendor         : GenuineIntel
>     Name           : Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
>     Version        : OpenCL 1.2 AMD-APP (1800.11)
>     Processor(s)   : 8
>     Clock          : 3056
>     Memory         : 2047/16015 MB allocatable
>     OpenCL Version : OpenCL C 1.2 
>     Driver Version : 1800.11 (sse2,avx)

**Comment by jsteube** [comment]
Hey, I still can reproduce it. See here:

```
root@sf:~/hashcat# rm hashcat.potfile 
root@sf:~/hashcat# ./hashcat hash --show
root@sf:~/hashcat# cat wl
.::H|CBO::.
.::Killthezoo::.
merhoussame:::::
:d:d:d:d:d1
root@sf:~/hashcat# ./hashcat hash wl
hashcat (v3.20-88-gd36cc4c) starting...

OpenCL Platform #1: Advanced Micro Devices, Inc.
================================================
* Device #1: Ellesmere, 2047/4038 MB allocatable, 14MCU
* Device #2: Hawaii, 2047/4043 MB allocatable, 14MCU
* Device #3: AMD FX(tm)-6100 Six-Core Processor, skipped

OpenCL Platform #2: The pocl project
====================================
* Device #4: pthread-AMD FX(tm)-6100 Six-Core Processor, skipped

Hashes: 4 digests; 4 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 75c

Cache-hit dictionary stats wl: 58 bytes, 4 words, 4 keyspace

The wordlist or mask you are using is too small.
Therefore, hashcat is unable to utilize the full parallelization power of your device(s).
The cracking speed will drop.
Workaround: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#how_to_create_more_work_for_full_speed

INFO: approaching final keyspace, workload adjusted       

63ee9967dc9b571e746ecb52c9518455:$HEX[2e3a3a487c43424f3a3a2e]
c3ee19ff73bcb2ebdf72188fd991aebe:$HEX[2e3a3a4b696c6c7468657a6f6f3a3a2e]
30020acffe70e97f5672dbd144b74446:$HEX[6d6572686f757373616d653a3a3a3a3a]
782d37d42ca81398be30be0540648b25:$HEX[3a643a643a643a643a6431]
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Type........: MD5
Hash.Target......: hash
Time.Started.....: Sun Jan  1 18:43:39 2017 (0 secs)
Time.Estimated...: Sun Jan  1 18:43:39 2017 (0 secs)
Input.Base.......: File (wl)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.03ms)
Speed.Dev.#2.....:        0 H/s (0.00ms)
Speed.Dev.#*.....:        0 H/s
Recovered........: 4/4 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 4/4 (100.00%)
Rejected.........: 0/4 (0.00%)
Restore.Point....: 0/4 (0.00%)
Candidates.#1....: .::H|CBO::. -> :d:d:d:d:d1
Candidates.#2....: [Copying]
HWMon.Dev.#1.....: Temp: 80c Fan: 20% Core:1266Mhz Mem:1750Mhz Lanes:16
HWMon.Dev.#2.....: Temp: 64c Fan: 26% Core:1010Mhz Mem:1250Mhz Lanes:16

Started: Sun Jan  1 18:43:38 2017
Stopped: Sun Jan  1 18:43:40 2017
root@sf:~/hashcat# ./hashcat hash --show
63ee9967dc9b571e746ecb52c9518455:$HEX[2e3a3a487c43424f3a3a2e]
30020acffe70e97f5672dbd144b74446:$HEX[6d6572686f757373616d653a3a3a3a3a]
782d37d42ca81398be30be0540648b25:$HEX[3a643a643a643a643a6431]
c3ee19ff73bcb2ebdf72188fd991aebe:$HEX[2e3a3a4b696c6c7468657a6f6f3a3a2e]
root@sf:~/hashcat# 
```

Maybe remove old potfile (or raname) and then try again (with latest beta version)

**Comment by segumarc** [comment]
Finally, I removed the old potfile and it was the problem. It working under the 3.20 build 88.
