### ISSUE TITLE
Device getting skipped

### ISSUE THREAD

**Issue by Wolfmandeny** [hashcat/hashcat#947]
CPU device is skipped when using the -d (-d 1,2,3) parameter.
Where device #1 is the CPU.

I know this is the default behavior when not specifying devices/device types/platforms, but in this case Hashcat overrides the user specified choices.
Using -D works correct.

> hashcat-3.20>hashcat64 -I
> hashcat (v3.20-39-gcafd4b5) starting...
> 
> OpenCL Info:
> 
> Platform ID #1
>   Vendor  : Intel(R) Corporation
>   Name    : Intel(R) OpenCL
>   Version : OpenCL 1.2
> 
>   Device ID #1
>     Type           : CPU
>     Vendor ID      : 8
>     Vendor         : Intel(R) Corporation
>     Name           :        Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
>     Version        : OpenCL 1.2 (Build 76427)
>     Processor(s)   : 4
>     Clock          : 1900
>     Memory         : 2047/10125 MB allocatable
>     OpenCL Version : OpenCL C 1.2
>     Driver Version : 3.0.1.10891
> 
>   Device ID #2
>     Type           : GPU
>     Vendor ID      : 8
>     Vendor         : Intel(R) Corporation
>     Name           : Intel(R) HD Graphics 4000
>     Version        : OpenCL 1.2
>     Processor(s)   : 16
>     Clock          : 1150
>     Memory         : 350/1400 MB allocatable
>     OpenCL Version : OpenCL C 1.2
>     Driver Version : 10.18.10.4276
> 
> Platform ID #2
>   Vendor  : NVIDIA Corporation
>   Name    : NVIDIA CUDA
>   Version : OpenCL 1.2 CUDA 8.0.0
> 
>   Device ID #3
>     Type           : GPU
>     Vendor ID      : 32
>     Vendor         : NVIDIA Corporation
>     Name           : GeForce GT 620M
>     Version        : OpenCL 1.1 CUDA
>     Processor(s)   : 2
>     Clock          : 1250
>     Memory         : 256/1024 MB allocatable
>     OpenCL Version : OpenCL C 1.1
>     Driver Version : 368.39

**Comment by jsteube** [comment]
Yep, that's the wanted behavior. Using CPU can lower GPU speed. If there's no GPU detected, CPU is automatically activated.

**Comment by Wolfmandeny** [comment]
Is this wanted even when the user explicitly spesifies the devices to use ?
I can understand it's done when defaults are used, but don't think hashcat should overriding the users choices.

**Comment by jsteube** [comment]
Kind of, but you need to respect the platform hierarchy, means you have
to able enable it with -D 1 first. After that, -d should be relevant. So
platform > device

**Comment by Wolfmandeny** [comment]
I assume in that case it would have to be -D 1,2, since otherwise it would be CPU only ?
So in this case -D 1,2 -d 1,2,3
?

**Comment by jsteube** [comment]
If you have 3 devices 1, 2 and 3 then you don't need to set them. If you
want all devices used all you need to do is -D 1,2

**Comment by Wolfmandeny** [comment]
What I wanted was just to select individual devices regardless of the platform.
I found it illogical that I had to specify the platforms as well.
It's the same thing with the platform (--opencl-platforms=) option. If I select the Intel platform the CPU will be skipped here as well, and only the GPU will be used.

This all seems just to force the user to use one more parameter then needed. Unless there is something I can't see here?

In my view the default restriction set on CPU should not be set when users start to configure the devices manually.

**Comment by magnumripper** [comment]
FWIW I agree with OP. If user says `-d (...)` it would be logical to over-ride the default for `-D`.

**Comment by jsteube** [comment]
I don't think so. If there's multiple levels of hierarchy there must be
some sort of hard logic two distinguish them otherwise it becomes
uncontrollable. What I mean is there can not be some configuration
parameter of hierarchy 1 that, if set, influences hierarchy 2.

Anyway, this goes back to NVidia creating 100% CPU load. It's the root
problem. Otherwise there would be no need to disable CPU support at all.
If you want to track this, here's the forum post:
https://devtalk.nvidia.com/default/topic/978985/opencl-busy-wait-still-not-fixed


After that, I've also opened a bug at their bug trackers, but the bug
tracker is not publicly available.

As soon this bug is resolved I will automatically re-enable CPU use.

**Comment by Brendanbc1** [comment]
Isn't the bug fixed now? I haven't noticed any CPU load with nvidia GPUs, and when I manually enable both CPU+GPU it improves my total hash rate (at least for SHA1)

**Comment by jsteube** [comment]
It's still in there. You can disable our workaround by using --nvidia-spin-damp 0 to reproduce locally
