### ISSUE TITLE
Blank MD5 Unix

### ISSUE THREAD

**Issue by qxygene** [hashcat/hashcat#948]
Console shows blank password but it is saying cracked, issued in here as well https://hashcat.net/forum/thread-2365.html

Using binary cudaHashcat-2.01\cudaHashcat64.exe

example hash : $1$Yvdv8JqH$g4mSb3Acg9MZW4pijEBCx.

**Comment by epixoip** [comment]
Why are you filing a bug report for cudaHashcat 2.01? cudaHashcat doesn't even exist anymore.

**Comment by jsteube** [comment]
Please retry with github version (or binary version from https://hashcat.net/beta/ ) and reopen if needed.
