### ISSUE TITLE
support for longer salts for bitcoin hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#95]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.
---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | Cerberus |
| Title: | Bitcoin (id: 11300) |
| Ticket number: | 632 |
| Date reported: | 2015-06-23T22:03:24+02:00 |
| **Description**: | I have a question on the implementation of the algorithm Bitcoin(id 11300). I ran [~~in~~] oclhashcat 1.36 with the inability to load the hash from the bitcoin wallet with these parameters:<br><br>N = 27450<br>SaltLen = 130<br><br>Dear atom[, you] really need to fix this problem. |
---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | We need to know what the maximum possible value for SaltLen is. Can you please find out |
| 2. | Cerberus | maybe view [here](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/bitcoin_fmt_plug.c)<br><br>static struct custom_salt {<br>unsigned char cry_master[SZ];<br>int cry_master_length;<br>unsigned char cry_salt[SZ];<br>int cry_salt_length;<br>int cry_rounds;<br>unsigned char ckey[SZ];<br>int ckey_length;<br>unsigned char public_key[SZ];<br>int public_key_length;<br>} *cur_salt;<br><br>--> #define SZ 128<br><br>it is possible that the way it is. I do not know how to generate a [bitcoin "hash"] with a long salt, I have only [a sample "hash"] from which I have no password |
| 3. | atom | I think I can make it work for salt length up to 256. But it will take some time, I'm busy with a different algorithm atm |

**Comment by jsteube** [comment]
Continue here: https://github.com/hashcat/hashcat/issues/565
