### ISSUE TITLE
New return codes for checkpoint and end of --runtime

### ISSUE THREAD

**Issue by chuckfw** [hashcat/hashcat#950]
I use a script to automate multiple runs of hashcat with different parameters. I've run into limitations with this process due to hashcat return the same exit status code in different situations. Specifically:

- Hashcat returns 1 on exhaustion for a run (all passwords tried, but not all hashes cracked). This value is also returned if the user has manually used the "checkpoint" feature to request for hashcat to exit at the next checkpoint. I suggest that a different value should be returned if the user has requested an exit after the next checkpoint.

- Hashcat return 2 if it is manually quit by the user. This value is also returned if time is exhausted using the --runtime option. I suggest that a different value should be returned if hashcat reaches the end of the time specified with --runtime.

**Comment by jsteube** [comment]
I think I could change this to return 3 for case 1 and 4 for case 2?

**Comment by chuckfw** [comment]
Those return values look fine to me. Thank you.

**Comment by jsteube** [comment]
Implemented with https://github.com/hashcat/hashcat/commit/c7999c66bc289023917b2178cb981f2c47585f45
