### ISSUE TITLE
--Runtime in combination with --loopback leads to endless loop

### ISSUE THREAD

**Issue by dropdeadfu** [hashcat/hashcat#953]
If the current job gets terminated by the defined runtime the cleanup of the loopback dir will not be handled as it should be and will therefor lead to an endless loop. (The loop should only last as long as there are plains found but will continue on even if nothing is found.)

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/0fe6db6839f9646124a5c6ae6f52111a573fe1ac
Thanks!
