### ISSUE TITLE
--Runtime doesn't calculate correctly during the first run

### ISSUE THREAD

**Issue by dropdeadfu** [hashcat/hashcat#954]
For example --runtime 10 will run for 15 sec on a 980ti and for 32sec on a 4x1080 sys but only in the first run of a queue, in each following job of the queue the runtime will be calculated correctly

**Comment by jsteube** [comment]
Fixed with https://github.com/hashcat/hashcat/commit/038b915e2da7951f2599b5894169e54c93142c19
Thanks!
