### ISSUE TITLE
Reuse PBKDF2 intermediate keys if duplicate essid is detected not working on large hccap's

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#955]
Reuse PBKDF2 intermediate keys if duplicate essid is detected is not working on large hccap's

Session..........: hashcat
Status...........: Running
Hash.Type........: WPA/WPA2
Hash.Target......: test.hccap
Time.Started.....: Sat Jan  7 10:57:24 2017 (1 hour, 40 mins)
Time.Estimated...: Sat Jan  7 14:39:11 2017 (2 hours, 1 min)
Input.Base.......: File (testlist)
Input.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:   156.3 kH/s (4.91ms)
Recovered........: 252/85743 (0.29%) Digests, 245/83842 (0.29%) Salts
Recovered/Time...: CUR:2,166,N/A AVG:2,151,3624 (Min,Hour,Day)
Progress.........: 945155872/2086240486 (45.30%)
Rejected.........: 0/945155872 (0.00%)
Restore.Point....: 0/24883 (0.00%)
Candidates.#1....: ~!@#$%^&* -> Tr1angle
HWMon.Dev.#1.....: Temp: 75c Fan: 59% Util: 99% Core:1277Mhz Mem:3004Mhz Lanes:16

Speed must be much faster, because there are many, many duplicate essid's in the hccap.
It's also seen in the output:
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password1
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password2
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password3
ESSID2:xxxxxxxxxxxx:yyyyyyyyyyyy:anotherpassword
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password4
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password5
ESSID3:xxxxxxxxxxxx:yyyyyyyyyyyy:anotherpassword
ESSID4:xxxxxxxxxxxx:yyyyyyyyyyyy:anotherpassword
ESSID1:xxxxxxxxxxxx:yyyyyyyyyyyy:password5

Best regards
ZerBea

**Comment by jsteube** [comment]
I need the .hccap you're using to reproduce locally

**Comment by ZerBea** [comment]
File is realy big.
So please download cap's from here
http://wpa.darkircop.org/cap/archive/
wpa-1.cap and wpa.cap are very good for testing purposes.

I don't use wpaclean or cap2hccap (both are faulty, so I wrote my own prog).
You must check the cap files . All Handshakes with replaycount 17 are fake handshakes.

On that lage hccap files, john is still up to 20 times faster (depends on how much diplicate essid's are inside the file).

**Comment by jsteube** [comment]
Those files are in no way helping. If you want to have this fixed you need to send me the .hccap which you use so that I can reproduce the problem locally and fix it.

**Comment by ZerBea** [comment]
Sorry, can't upload:

"Something went really wrong, and we can’t process that file. "

Neither .zip, nor .gz, nor .7z accepted........

**Comment by jsteube** [comment]
send it to my email: atom at hashcat.net

**Comment by ZerBea** [comment]
Ok.
done......

**Comment by jsteube** [comment]
OK, I got the file. Now I need one example of a duplicate which is not detected as duplicate. Please name me one.

**Comment by ZerBea** [comment]
Send you a pm.......

**Comment by ZerBea** [comment]
Candidates.#1....: ~!@#$%^&* -> ZZZZZZZZZZ

**Comment by ZerBea** [comment]
So all founds on the same essid must be in a row.......
but they didn't.

**Comment by jsteube** [comment]
Yeah I think I found the root problem. Need to think about a good solution. Prepare for testing :)

**Comment by ZerBea** [comment]
It works on small hccap's < 100
but my test files a really big ....
Ok, I stay tuned......

**Comment by ZerBea** [comment]
Right now, I do a presort on the essid and run hashcat on this presorted hccap's.
Speed is above 179 M!

**Comment by ZerBea** [comment]
Maybe the idea of sorting by length of essid is not a good idea.
It could be a better way to sort by alphabetical order....

**Comment by jsteube** [comment]
OK, I've patched hashcat. There's also a new beta at https://hashcat.net/beta/

In an ideal world, the output of your file should look like this:

```
Hashes: 69295 digests; 66980 unique digests, 57302 unique salts
```

That is because your file has 11993 handshakes with the same ESSID. Now the problem is that there's a chance that some of those handshakes have the same ESSID, but they are actually from a different AP. There's no way for hashcat to know about this. Therefore we must check all the handshakes, even if they have the same ESSID. But we can still make use of the duplicate ESSID shortcut. I've patched hashcat, so don't get confused if you see this loading screen instead:

```
Hashes: 69295 digests; 69295 unique digests, 69295 unique salts
```

It will still make use of the duplicate PBKDF2 shortcut. You can find out if you meassure the time it takes to process a full wordlist. Simply ignore what the "Time.Estimated" in the status screen tells you.

**Comment by ZerBea** [comment]
Well done. Now everything works like expected.
Again faster then john.........
The test file is one of my smallest.......
