### ISSUE TITLE
format for 3des on wiki?

### ISSUE THREAD

**Issue by thesle3p** [hashcat/hashcat#958]
It looks like the hashcat-compliant format for 3des and des is missing from the wiki? Also would it be possible to write up how to format 3des ciphertext to work with hashcat?

**Comment by byte4sec** [comment]
yes,hash-mode 14000/14100/14400/1300 not yet updated to wiki:
https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by jsteube** [comment]
Update 14000, 14100 and 14400.
Mode 1300 is not part of hashcat (only hashcat-legacy)

**Comment by d3d3-g** [comment]
Version 3.30 , Hashcat Added hash-mode 1300 = SHA-224
see here: https://hashcat.net/forum/thread-6187.html

**Comment by byte4sec** [comment]
@jsteube 
Version 3.30 , Hashcat Added hash-mode 1300 = SHA-224
see here: https://hashcat.net/forum/thread-6187.html
