### ISSUE TITLE
Support for Kerberos Pre-Auth etype 17/18 (SHA-1)

### ISSUE THREAD

**Issue by brandoncasaba** [hashcat/hashcat#959]
With more and more enterprises using Win7+ kerb tickets are being required to use the aes256-cts-hmac-sha1-96 tickets, less and less passive analysis returns the old RC4 based tickets that Hashcat supports. 

Would like to see Hashcat support the more modern Windows network hashes present on more and more enterprise networks. 

Samples with implementation here:
http://www.openwall.com/lists/john-users/2012/11/18/5
ETA, or more currently here, thanks Magnum, you guys rock!:
https://github.com/magnumripper/JohnTheRipper/blob/8bcaddef35f703c47367fad612e473061459b156/src/opencl_krb5pa-sha1_fmt_plug.c

	{"$krb5ng$user1$EXAMPLE.COM$2a0e68168d1eac344da458599c3a2b33ff326a061449fcbc242b212504e484d45903c6a16e2d593912f56c93$883bf697b325193d62a8be9c", "openwall"},
	{"$krb5ng$user1$EXAMPLE.COM$a3918bd0381107feedec8db0022bdf3ac56e534ed54d13c62a7013a47713cfc31ef4e7e572f912fa4164f76b$335e588bf29c2d17b11c5caa", "openwall"},
	{"$krb5ng$l33t$EXAMPLE.COM$98f732b309a1d7ef2355a974842a32894d911e97150f5d57f248e1c2632fbd3735c5f156532ccae0341e6a2d$779ca83a06021fe57dafa464", "openwall"},
        {"$krb5ng$aduser$AD.EXAMPLE.COM$64dfeee04be2b2e0423814e0df4d0f960885aca4efffe6cb5694c4d34690406071c4968abd2c153ee42d258c$5e09a41269bbcd7799f478d3", "password@..."},
        {"$krb5ng$aduser$AD.EXAMPLE.COM$f94f755a8b4493d925094a4eb1cec630ac40411a14c9733a853516fe426637d9daefdedc0567e2bb5a83d4f8$9a0ad1a4b178662b6106c0ff", "password@...45678"},

**Comment by magnumripper** [comment]
That sample code is ancient and we no longer use that tag. This now corresponds to krb5pa-sha1 in current JtR. It's straightforward to implement and finally uses UTF-8 like anyone else IIRC.
```c
{"$krb5pa$18$user1$EXAMPLE.COM$$2a0e68168d1eac344da458599c3a2b33ff326a061449fcbc242b212504e484d45903c6a16e2d593912f56c93883bf697b325193d62a8be9c", "openwall"},
{"$krb5pa$18$user1$EXAMPLE.COM$$a3918bd0381107feedec8db0022bdf3ac56e534ed54d13c62a7013a47713cfc31ef4e7e572f912fa4164f76b335e588bf29c2d17b11c5caa", "openwall"},
{"$krb5pa$18$l33t$EXAMPLE.COM$$98f732b309a1d7ef2355a974842a32894d911e97150f5d57f248e1c2632fbd3735c5f156532ccae0341e6a2d779ca83a06021fe57dafa464", "openwall"},
{"$krb5pa$18$aduser$AD.EXAMPLE.COM$$64dfeee04be2b2e0423814e0df4d0f960885aca4efffe6cb5694c4d34690406071c4968abd2c153ee42d258c5e09a41269bbcd7799f478d3", "password@123"},
{"$krb5pa$18$aduser$AD.EXAMPLE.COM$$f94f755a8b4493d925094a4eb1cec630ac40411a14c9733a853516fe426637d9daefdedc0567e2bb5a83d4f89a0ad1a4b178662b6106c0ff", "password@12345678"},
{"$krb5pa$18$aduser$AD.EXAMPLE.COM$AD.EXAMPLE.COMaduser$f94f755a8b4493d925094a4eb1cec630ac40411a14c9733a853516fe426637d9daefdedc0567e2bb5a83d4f89a0ad1a4b178662b6106c0ff", "password@12345678"},	
/* etype 17 hash obtained using MiTM etype downgrade attack */
{"$krb5pa$17$user1$EXAMPLE.COM$$c5461873dc13665771b98ba80be53939e906d90ae1ba79cf2e21f0395e50ee56379fbef4d0298cfccfd6cf8f907329120048fd05e8ae5df4", "openwall"},
```

**Comment by thesle3p** [comment]
would be great to see this.

**Comment by ihamburglar** [comment]
Anyone looking to work on this, I would recommend taking a look at the [MS-KILE](https://msdn.microsoft.com/en-us/library/cc233855.aspx) documentation, which even has some key generation examples as well as a ton of other info regarding MS' implementation of Kerberos.

**Comment by Fist0urs** [comment]
I could do that when I find time... (also the KRB 5 TGS one)

**Comment by elitest** [comment]
I'm not a C expert, but I have a decent understanding of the crypto behind this.  Feel free to DM me on Twitter if you would like to collaborate.

**Comment by brandoncasaba** [comment]
$100 Bounty added.
https://www.bountysource.com/issues/40782580-support-for-kerberos-pre-auth-etype-17-18-sha-1

**Comment by SneakyOttersec** [comment]
$20 Bounty Added

**Comment by Fist0urs** [comment]
I'll implement this one soon :+1:
