### ISSUE TITLE
Abort trap 6: MacBook Pro macos -m 3200 

### ISSUE THREAD

**Issue by Ysagi** [hashcat/hashcat#960]
Hello.

I get a Abort trap: 6 trying to crack bcrypt hashes. See output below.

mattias$ ./hashcat -d 1,2 -m 3200 hash.lst /Users/mattias/Password\ lists/Passwords/hydra.lst
hashcat (v3.30) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 540, 384/1536 MB allocatable, 48MCU

Hashes: 5 digests; 5 unique digests, 5 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte

Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Generated dictionary stats for /Users/mattias/Password lists/Passwords/hydra.lst: 41202 bytes, 5200 words, 5200 keyspace

Abort trap: 6

Best regards Mattias

**Comment by Ysagi** [comment]
Sweet no it is working with the new hashcat.hctune file.

Thanks.

**Comment by matrix** [comment]
@Ysagi if ok please close the issue. Thanks :)

**Comment by amlweems** [comment]
I'm having the same issue using the hashcat.hctune file from the latest commit (89f8739dde). I have a slightly different machine type than Ysagi, however. @matrix I've tried tuning it myself, but I'm not quite sure what I'm doing. Any ideas?

```
$ hashcat -m 3200 hashes.txt ~/wordlists/words.txt -o cracked.txt
hashcat (v3.30-397-g89f8739ddecc) starting...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, skipped
* Device #2: Iris Pro, 384/1536 MB allocatable, 40MCU
* Device #3: GeForce GT 750M, 512/2048 MB allocatable, 2MCU

Hashes: 140 digests; 140 unique digests, 140 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte

Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Cache-hit dictionary stats /Users/amlweems/wordlists/words.txt: 139921525 bytes, 14343299 words, 14343299 keyspace

Abort trap: 6
```
