### ISSUE TITLE
--show --username doesn't show all users with non-unique passwords

### ISSUE THREAD

**Issue by kosborn** [hashcat/hashcat#963]
We just noticed this change/issue, and I don't see it documented anywhere, so I'm reporting this as an issue. Somewhere between commit 1f72aa95e60a13b6a48f285102ca388cb4c146d8 and a460ab01b684eeb1d26c503df60d8654a57bf699, functionality with --show --username changed.

Previous and expected functionality:

DOMAIN\James:[hash]:Password1
DOMAIN\Michelle:[hash]:Password1
DOMAIN\Nick:[hash]:Password1
[etc]

Output after the commit (and apparent code refactor):

DOMAIN\James:[hash]:Password1
<END>

Works:
--show --username works (shows unique users with dupe passwords)
Commit: 1f72aa95e60a13b6a48f285102ca388cb4c146d8
v3.10-508-g1f72aa9+

First Broken:
--show --username (only shows the first user in the source hash file)
Commit: a460ab01b684eeb1d26c503df60d8654a57bf699
v3.10-514-ga460ab0+

Latest version (v3.30) is also broken.

**Comment by kaluche** [comment]
I can confirm, same problem here, with latest 3.30.

**Comment by jsteube** [comment]
This feature was never a wanted feature in older version. It was "just luck" that it worked like that. Therefore not ported to new version. 

But I can see how it can be useful. Have to think about how to re-add it with new architecture.
