### ISSUE TITLE
support for Skip32 known-plaintext attack

### ISSUE THREAD

**Issue by iceman1001** [hashcat/hashcat#967]
To implement a kernel for a generic Skip32 plainttext attack.

- take input,  known plaintext,
- compare result bytes with specified user known-plaintext
---if match, log result, break
- repeat

Background
Skip32 works with 10byte key, outputs 4bytes and is a simpler version of skipjack algo.
input: 1122334455667788
output: xxyyzzww

Ref:
Skip32:   Naive impl: https://github.com/nlenepveu/Skip32

**Comment by matrix** [comment]
Hey Iceman, nice to see you here ;)

**Comment by iceman1001** [comment]
You guys are so hardcore gurus, I don't deserve to be here :)
Maybe you can optimize the iclass hash1, hash2, solution in the pm3 too...

**Comment by jsteube** [comment]
Support has been added. Note that the high performance will create tons of collisions, thus it's printing them all and not stopping after one has been found. We can change that if you want.
