### ISSUE TITLE
Possible wrong behaviour for O rule with -j/-k options

### ISSUE THREAD

**Issue by mhasbini** [hashcat/hashcat#969]
1- When running `O` rule with `-j`/`-k` options with omit range equal to the provided plain it skip the plain.
2- When using the same rule from a file it works as expected.

### first scenario
`given` file `w.txt` that contains the string `abc`.
`and` I run this command: `hashcat --stdout -j 'O03' w.txt` (or `hashcat --stdout -k 'O03' w.txt`).
`then`
**expected output**
`` ( empty )
**actual**
`abc`

### second scenario
`given` file `w.txt` that contains the string `abc`.
`and` file `rule.rule` that contains the string `O03`.
`and` I run this command: `hashcat --stdout -r rule.rule w.txt`.
`then`
**expected output**
`` ( empty )
**actual**
as expected.

### Hashcat version: 

```
$ hashcat --version
v3.30-5-gdd57ef52
```

Is this an expected behaviour ?

**Comment by milzo247** [comment]
Rule O delete a range so the result of `empty` is correct with you rule. Read the docs at 
https://hashcat.net/wiki/doku.php?id=rule_based_attack

O02 will delete chars ab and leave you with c

Start at 0 for character position 0-9
character position 10=A ,11=B and so on

**Comment by jsteube** [comment]
No, it's a bug, not wanted behaviour. I can reproduce.

**Comment by jsteube** [comment]
Fixed, thanks for reporting
