### ISSUE TITLE
support for longer salt lengths for md5 ($salt.md5($pass))

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#97]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.
---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | hashnew |
| Title: | about salt too long |
| Ticket number: | 635 |
| Date reported: | 2015-06-26T02:40:26+02:00 |
| **Description**: | md5($salt.md5($pass)) [doesn't result in any] crack[s for me], atom said 'salt too long'. [Could you please] increase salt length?<br><br>Thank you!<br>[Forum post](https://hashcat.net/forum/thread-4475.html) |
---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | If this is a single-user problem we're not going to add it.<br><br>Please tell us which software is using such a long salt. |

**Comment by jsteube** [comment]
Continue here: https://github.com/hashcat/hashcat/issues/565
