### ISSUE TITLE
Veracrypt AES-Twofish-Serpent broken

### ISSUE THREAD

**Issue by 0xpr03** [hashcat/hashcat#973]
Hello, currently the AES-Twofish-Serpent implementation is broken. I can try to crack at freshly created file with -a 0 and hashcat can't crack it, -a 0 --veracrypt-pim 485 -m 13723.
I've double checked about the pim, it's the default one.
Or did I miss something?

**Comment by jsteube** [comment]
Yes, the --veracrypt-pim option is currently not supported, it has nothing to do with the selected cipher

**Comment by 0xpr03** [comment]
I've used it with and without the pim option, as I was using the default PIM.
I was giving veracrypt the PW for direct try on my test container and it didn't work.
I suppose the combination of aes + twofish + serpent isn't suuported by hashcat.

**Comment by 0xpr03** [comment]
@jsteube I've retried it. This time with only one entry: Hashcat can crack it.
But if I try it with a pw-file of 300 entries (including the right one) I'm getting the following error:
```
[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => clEnqueueReadBuffer(): CL_INVALID_VALUE

clEnqueueReadBuffer(): CL_DEVICE_NOT_FOUND
Session..........: hashcat
Status...........: Exhausted
```

with

`hashcat64.exe -a 0 -w 3 -m 13723 "X:\XXX" "X:\pws.TXT"`

And so hashcat isn't able to crack it anymore. (regardless of using -w 3 or not.)
System: Win7, 64bit
GTX 970, latest drivers from NVIDIA

```
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 970, 1024/4096 MB allocatable, 13MCU

OpenCL Platform #2: Advanced Micro Devices, Inc.
================================================
* Device #2: AMD FX-8370 Eight-Core Processor               , skipped

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1
```

As I've said, trying it with one PW-Entry works, but the moment I'm trying it again with some bulk entries, hashcat spits out this error.

**Comment by 0xpr03** [comment]
Update:
I've set the size of my file down to ~200 entries and now hascat doesn't emit any errors anymore. As if my file was too huge with 300 entries.
