### ISSUE TITLE
clEnqueueNDRangeKernel(): CL_UNKNOWN_ERROR on Kali Linux

### ISSUE THREAD

**Issue by ijanson** [hashcat/hashcat#975]
I'm trying to crack an OSX hash but when I do I get this error. I am running this on a 2012 MacBook Pro
`hashcat (v3.30) starting...

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

OpenCL Platform #1: Mesa, skipped or no OpenCL compatible devices found

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #1:        Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz, 2047/15958 MB allocatable, 4MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD
* Uses-64-Bit

Watchdog: Hardware Monitoring Interface not found on your system
Watchdog: Temperature abort trigger disabled
Watchdog: Temperature retain trigger disabled

Checking for weak hashes...clEnqueueNDRangeKernel(): CL_UNKNOWN_ERROR

Started: Wed Jan 18 23:39:20 2017
Stopped: Wed Jan 18 23:39:20 2017
`

**Comment by jsteube** [comment]
Can you please retry on Ubuntu? Kali is known to run a broken OpenCL runtime installation.

**Comment by jsteube** [comment]
Should be fixed with https://github.com/hashcat/hashcat/commit/9005b6662663ebbfab7025d03aa661374d34bf31

If it's not working for you, please reopen the issue. Thanks for reporting!
