### ISSUE TITLE
ITunes Backup Password via GPUs in Hashcat

### ISSUE THREAD

**Issue by dertuxel** [hashcat/hashcat#977]
I would be glad if you in the Hashcat synonymous decode of ITunes backup picks up. The calculation only with the CPU is very slow and my GPUs are bored
There are already very good solutions in the forum
https://hashcat.net/forum/thread-6047.html
Thank you and I look forward to the implementation

**Comment by IncognitoEntity** [comment]
As per forum thread mentioned in the comment above I would love GPU implementation for manifest.plist IOS backup cracking.  Other current methods are very slow and not brilliant.  I feel GPU utilisation in hashcat would be the best solution to this.  I know personally that big police forces within the UK have wanted this implementation.  I'm surprised this hasn't been requested more given its prevolence.  I must get through at least around 25 - 30 of these per month.  Thank you hashcat for taking this onboard.  I look too look forward to any GPU implementation.

**Comment by philsmd** [comment]
-m 14700 was added for versions < 10.0 and maybe -m 14800 will be added soon. In the meantime you can try to use -m 14700 (with beta versions or git versions) and maybe also this tool helps: https://github.com/philsmd/itunes_backup2hashcat
Thanks

**Comment by philsmd** [comment]
Update: we now also implemented -m 14800 = iTunes Backup >= 10 , see https://github.com/hashcat/hashcat/commit/07c89833c922bd4980f9bee489fc0d73725380de

**Comment by dertuxel** [comment]
Hello, I am just back from the holidays and will test the same time.
Thank you for your work

Uwe


________________________________
Von: philsmd <notifications@github.com>
Gesendet: Donnerstag, 26. Januar 2017 20:20
An: hashcat/hashcat
Cc: dertuxel; Author
Betreff: Re: [hashcat/hashcat] ITunes Backup Password via GPUs in Hashcat (#977)


Update: we now also implemented -m 14800 = iTunes Backup >= 10 , see 07c8983<https://github.com/hashcat/hashcat/commit/07c89833c922bd4980f9bee489fc0d73725380de>

-

**Comment by riverwu0709boss** [comment]
$itunes_backup$*9*0259e63540c10104264a7e8e7a676fd4ed9f9895d5b0b294fdbae9c95e497c4235b846671f87f48d*10000*e9051012d7621b23a8c5ebe4b2837016f96ee7b2**

please help me how to solution this question , i forget password
