### ISSUE TITLE
File existence checks should happen before possibly intensive operations

### ISSUE THREAD

**Issue by Chick3nman** [hashcat/hashcat#979]
Hashcat only checks for the existence of things such as wordlists and rules after doing operations such as the potfile comparison and hash loading. These operations can take quite a long time with large lists of hashes and especially large potfiles and waiting 15+ minutes for hashcat to get done loading and comparing, only to find that you've made an error in the file path for your wordlist can be frustrating. The file existence checks should be done at startup, before any intensive operations, avoiding possible issues such as the example above later on in the attack.

**Comment by jsteube** [comment]
OK, added with commit: https://github.com/hashcat/hashcat/commit/84fcd8289fa70cb0a5bbd36126cb7b645d493e7f

Please verify and close the issue

**Comment by roycewilliams** [comment]
Fantastic. This will **really** help with the learning curve for new users. Very happy to see this.

**Comment by Chick3nman** [comment]
Working as expected, thanks.
