### ISSUE TITLE
support for Stanford Javascript Crypto Library (SJCL) hashes

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#98]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details: |  |
| --- | --- |
| Original reporter (OP): | duterium71 |
| Title: | Add support for Stanford Javascript Crypto Library (SJCL) |
| Ticket number: | 636 |
| Date reported: | 2015-07-02T01:18:20+02:00 |
| **Description**: | SJCL uses salted PBKDF2 with AES using CCM or OCB2 with a unique IV per message. Key size (ks) and Authentication strength (ts) are variable.<br><br>Example:<br>{"iv":"iRGVsqktW/UKWi1cNfMZrQ==",<br>"v":1,<br>"iter":1000,<br>"ks":128,<br>"ts":64,<br>"mode":"ccm",<br>"adata":"",<br>"cipher":"aes",<br>"salt":"BX5Xuh4BuU8=",<br>"ct":"mg709j8o9tpNus1iyoy5+zMWMJbWcg=="<br>}<br><br>Input message is 'secret message' and password is 'test'.<br><br>[Source [code] for SJCL](https://github.com/bitwiseshiftleft/sjcl)​ |

---

| Comments: |  |  |
| --- | --- | --- |
| 1. | atom | Where is it used in? |

**Comment by ghost** [comment]
I added a $75 bounty for this and the AES decrypt routine should be executed on whatever is fastest between AES-NI (CPU) or GPU.

There's also a demo page for the library here: https://bitwiseshiftleft.github.io/sjcl/demo/.

**Comment by philsmd** [comment]
Very old github issue, without much user interest. Even the user above isn't really available on github anymore.

I'm not even sure if this hashing algorithm is still widely used and the details are still the same.

This is a issue that was first reported on the old `trac` issue tracking system we used for hashcat. It's a very old algorithm request without much user interest, unfortunately.

I would suggest that if you are still interested in this or similar new hashing algorithms not yet supported by hashcat, you should open a new github issue with all the details about the algorithm and hash:password examples (see guide here: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#i_want_to_request_some_new_algorithms_or_features_how_can_i_accomplish_this).

Thank you
