### ISSUE TITLE
hashcat is truncating output in attack mode 1

### ISSUE THREAD

**Issue by d2-d2** [hashcat/hashcat#980]
Hi Atom, when I use attack mode 1 with hashcat 3.30 it is truncating output passwords to 32 characters. Some examples of what's going on:

```
67deccd2d8eb401916cf5db63757756d:lucaslugomarques2003@hotmail.co
3aeadba900d4cec1931e918ba6b978d6:christianchicharito14@hotmail.c
fc2ccf6bc6cf4307b74ac1a9698a962c:juanandreslemosarteaga2004@hotm
b7f313adcb7113f87d3d27e33227d399:sebashernandezmorales@hotmail.c
```

So obviously correct passwords are:
```
lucaslugomarques2003@hotmail.com
christianchicharito14@hotmail.com
juanandreslemosarteaga2004@hotmail.com
sebashernandezmorales@hotmail.com
```
Hashes are not changed though. More examples of this issue if needed: https://pastebin.com/4zE2W35u

**Comment by philsmd** [comment]
Could you please re-try with these changes: https://github.com/hashcat/hashcat/pull/982 ?
Thanks
