### ISSUE TITLE
Outfile format wrong

### ISSUE THREAD

**Issue by ins0** [hashcat/hashcat#985]
Just updated hashcat and it seems that the ``--outfile-format=2`` is wrong.
The output thats gets written in the resultfile is a hex encoded string representation and not ``plain``.

So ``--outfile-format=2`` gives me ``$HEX[..........]`` in the resultfile.

Edit:

Just found out that if i add the option ``--outfile-autohex-disable`` to my argument list, the output is now plaintext. Removing the argument and the output is hex again with format ``2``.

**Comment by jsteube** [comment]
See release notes from v3.30:
```
Files: Use $HEX[...] in case the password includes the separater character, increases potfile reading performance
```
And release notes from v3.20:
```
Password candidates: Do not use $HEX[] if the password candidate is a valid UTF-8 string and print out as-is
```

There's no relation between --outfile-format and $HEX[...]. I know this is kind of confusing.
