### ISSUE TITLE
can't run hashcat 3.30 in GPU Mode on NVidia GTX 880M on Win 10Pro

### ISSUE THREAD

**Issue by MultiStorm** [hashcat/hashcat#995]
Hello,
when i try to run hashcat in GPU Mode i become this error:

clWaitForEvents(): CL_OUT_OF_RESOURCES

i have update my nvidia driver to the last version ... 378.xx but i cant start hashcat,
I try to install nvidia cuba installer (2.1 GB) now i have the Driver version 369.30 but the problem is the same

System:
AlienWare 17"
32 GB RAM
GTX 880M
Intel Core I7 CPU
SSD HDD

Windows 10 x64 Pro
can you help me?

here the complete terminal Text:
______________________________________________________________________________________________________________
`
hashcat64.exe -D 2 -d 1 -a 3 -m 3200 hash_php.hash
hashcat (v3.30) starting...

* Device #1: Old CUDA compute capability 3.0 detected, OpenCL performance is reduced.
             For ideal hashcat performance on NVIDIA GPU you need CUDA compute capability 5.0 or higher (Maxwell)
nvmlDeviceGetCurrPcieLinkWidth(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetFanSpeed(): Not Supported

nvmlDeviceGetClockInfo(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetTemperatureThreshold(): Not Supported

nvmlDeviceGetUtilizationRates(): Not Supported

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 880M, 2047/8192 MB allocatable, 8MCU

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz, skipped

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger disabled

clWaitForEvents(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1 [1]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 1/15 (6.67%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/62 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/1 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 55c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2 [2]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 2/15 (13.33%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/2232 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/36 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 55c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2 [3]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 3/15 (20.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/80352 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/1296 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 55c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2 [4]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 4/15 (26.67%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/2892672 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/46656 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2 [5]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 5/15 (33.33%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/104136192 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/1679616 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2 [6]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 6/15 (40.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/3748902912 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/60466176 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2 [7]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 7/15 (46.67%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/134960504832 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/2176782336 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3 [8]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 8/15 (53.33%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/5533380698112 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/89248075776 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3 [9]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 9/15 (60.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/226868608622592 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/3659171106816 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3 [10]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 10/15 (66.67%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/9301612953526272 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/150026015379456 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3 [11]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 11/15 (73.33%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/381366131094577152 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/6151066630557696 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d [12]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 12/15 (80.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/3813661310945771520 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/61510666305576960 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 55c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d?d [13]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 13/15 (86.67%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/1243124962038611968 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/20050402613525999 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d?d?d [14]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 14/15 (93.33%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/12431249620386119680 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/200504026135259994 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

clEnqueueWriteBuffer(): CL_OUT_OF_RESOURCES

clFlush(): CL_OUT_OF_RESOURCES

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: bcrypt, Blowfish(OpenBSD)
Hash.Target......: $2y$10$aTbeTZZ17OEC/RntxKEXyeJg4HrZR.JVos6/eyYrhOncTpzCVtsmq
Time.Started.....: Wed Jan 25 19:46:28 2017 (0 secs)
Time.Estimated...: Wed Jan 25 19:46:28 2017 (0 secs)
Input.Mask.......: ?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d [15]
Input.Charset....: -1 ?l?d?u, -2 ?l?d, -3 ?l?d*!$@_, -4 Undefined
Input.Queue......: 15/15 (100.00%)
Speed.Dev.#1.....:        0 H/s (0.00ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 0/13632031761603887104 (0.00%)
Rejected.........: 0/0 (0.00%)
Restore.Point....: 0/219871480025869146 (0.00%)
Candidates.#1....: [Generating]
HWMon.Dev.#1.....: Temp: 54c

Started: Wed Jan 25 19:46:23 2017
Stopped: Wed Jan 25 19:46:29 2017
`

**Comment by jsteube** [comment]
Can you please paste the output of the clinfo program? Maybe limited shared memory is the problem.

**Comment by jsteube** [comment]
Please retry with latest beta version from https://hashcat.net/beta/

There has been lots of changes

**Comment by jsteube** [comment]
OP not responding but we believe this case be fixed with TDR patch which hashcat is warning the user now on startup, therefore closing

**Comment by Anton9999999** [comment]
Народ может кто нибудь напишит команду, полным перебором для ХЕШ $1$mERr$hzbDZHr8wLbe1IQDjIwx6/

Для Winows
