### ISSUE TITLE
hashcat (v3.30-62-g7c7e4605) - outfile for recovered hash not longer working

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#999]
After upgrade from hashcat (v3.30-43-g55f4d636) to (v3.30-62-g7c7e4605) 
outfile for recovered hash not longer working:

hashcat -m 2500 -w 3 --remove --logfile-disable --potfile-disable --outfile-autohex-disable --outfile-format=3 -o found.list testlist.hccap wordlist

results in
found.list: No such file or directory
and hashcat terminates.

After manually creating the outfile (touch found.list) hashcat works like expected. It seems, that hashcat doesn't create this file, but checks if it exist's if outfile option is used.

Best regards
ZerBea

**Comment by ZerBea** [comment]
same behavior on hashcat (v3.30-65-g518983d3):
found.list: No such file or directory

**Comment by jsteube** [comment]
Thanks @ZerBea for reporting
